### ISSUE TITLE
Cannot manage Django 1.7 application with pyinstaller ( AppRegistryNotReady )

### ISSUE THREAD

**Issue by garthylou** [pyinstaller/pyinstaller#1067]
I have an application running with django 1.7.

If I try to execute pyinstaller with it, it fails on a django exception : 
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

Do you know what is the problem ? Is it specific for django 1.7, is there the same issue with other version ?
Someone succeeds to build a django app with Django 1.7 ?

Thank you

With the full stacktrace (on Windows XP) : 
```
INFO: Django root directory C:\project\Libreosteo\Libreosteo
Traceback (most recent call last):
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\hooks\utils\django-import-finder.py", line 47, in <module>
    base_module = __import__(base_module_name, {}, {}, ["urls"])
  File "C:\project\Libreosteo\Libreosteo\urls.py", line 7, in <module>
    admin.autodiscover()
  File "C:\Python\Libreosteo\lib\site-packages\django\contrib\admin\__init__.py", line 23, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\Python\Libreosteo\lib\site-packages\django\utils\module_loading.py", line 67, in autodiscover_modules
    for app_config in apps.get_app_configs():
  File "C:\Python\Libreosteo\lib\site-packages\django\apps\registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "C:\Python\Libreosteo\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
Traceback (most recent call last):
  File "C:\Python\Libreosteo\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==2.1', 'console_scripts', 'pyinstaller')()
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\build.py", line 1924, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\build.py", line 1873, in build
    execfile(spec)
  File "C:\project\manager.spec", line 6, in <module>
    runtime_hooks=None)
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\build.py", line 446,in __init__
    self.__postinit__()
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\build.py", line 309,in __postinit__
    self.assemble()
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\build.py", line 599,in assemble
    importTracker.analyze_script(script)
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\depend\imptracker.py", line 273, in analyze_script
    return self.analyze_r('__main__')
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\depend\imptracker.py", line 166, in analyze_r
    newnms = self.analyze_one(name, nm, imptyp, level)
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\depend\imptracker.py", line 227, in analyze_one
    mod = self.doimport(nm, ctx, fqname)
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\depend\imptracker.py", line 325, in doimport
    hook = imp.load_module('PyInstaller.hooks.' + hookmodnm, *m)
  File "C:\Python\Libreosteo\lib\site-packages\PyInstaller\hooks\hook-django.py", line 35, in <module>
    package_name + '.wsgi',
TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by maccinza** [comment]
@garthylou 
Hello! Could you please give me some tips on how to solve the 'Apps aren't loaded yet.' error? What was the problem in your case (maybe I can learn from it and solve mine)?

Thanks a lot!

**Comment by matysek** [comment]
I just pushed several commits that should fix django support. The basic mysite project is working.
