### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#1093]
Per issue 1089 (open a new issue for any further test failures), I see the following failure:

```
C:\Users\bjones\Documents\pyinstaller-git\tests>python runtests.py --verbose bas
ic\test_onefile_ctypes.py
Running test:  basic/test_onefile_ctypes
35 INFO: Testing for ability to set icons, version resources...
149 INFO: ... resource update available
152 INFO: UPX is not available.
171 INFO: Processing hook hook-os
273 INFO: Processing hook hook-time
275 INFO: Processing hook hook-cPickle
334 INFO: Processing hook hook-_sre
439 INFO: Processing hook hook-cStringIO
519 INFO: Processing hook hook-encodings
531 INFO: Processing hook hook-codecs
858 INFO: Processing hook hook-httplib
863 INFO: Processing hook hook-email
956 INFO: Processing hook hook-email.message
1161 WARNING: library python%s%s required via ctypes not found
test_onefile_ctypes (__main__.GenericTestCase) ...
########## BUILDING TEST basic/test_onefile_ctypes ##########

'cl' is not recognized as an internal or external command,
operable program or batch file.
1871 INFO: Extending PYTHONPATH with C:\Users\bjones\Documents\pyinstaller-git\t
ests\basic
1871 INFO: checking Analysis
1871 INFO: building Analysis because out00-Analysis.toc non existent
1871 INFO: running Analysis out00-Analysis.toc
1874 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable

1966 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21
022.8_none ...
1967 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc
8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91.manifest
1969 INFO: Searching for file msvcr90.dll
1970 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.21022.8_none_bcb86ed6ac711f91\msvcr90.dll
1970 INFO: Searching for file msvcp90.dll
1971 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.21022.8_none_bcb86ed6ac711f91\msvcp90.dll
1971 INFO: Searching for file msvcm90.dll
1972 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.21022.8_none_bcb86ed6ac711f91\msvcm90.dll
2049 INFO: Analyzing C:\Users\bjones\Documents\pyinstaller-git\PyInstaller\loade
r\_pyi_bootstrap.py
2060 INFO: Processing hook hook-os
2073 INFO: Processing hook hook-site
2088 INFO: Processing hook hook-encodings
2186 INFO: Processing hook hook-time
2189 INFO: Processing hook hook-cPickle
2251 INFO: Processing hook hook-_sre
2360 INFO: Processing hook hook-cStringIO
2452 INFO: Processing hook hook-codecs
2787 INFO: Processing hook hook-httplib
2789 INFO: Processing hook hook-email
2888 INFO: Processing hook hook-email.message
3101 WARNING: library python%s%s required via ctypes not found
3255 INFO: Processing hook hook-pydoc
3308 INFO: Analyzing C:\Users\bjones\Documents\pyinstaller-git\PyInstaller\loade
r\pyi_importers.py
3417 INFO: Analyzing C:\Users\bjones\Documents\pyinstaller-git\PyInstaller\loade
r\pyi_archive.py
3529 INFO: Analyzing C:\Users\bjones\Documents\pyinstaller-git\PyInstaller\loade
r\pyi_carchive.py
3640 INFO: Analyzing C:\Users\bjones\Documents\pyinstaller-git\PyInstaller\loade
r\pyi_os_path.py
3648 INFO: Analyzing test_onefile_ctypes.py
3745 INFO: Hidden import 'codecs' has been found otherwise
3746 INFO: Hidden import 'encodings' has been found otherwise
3746 INFO: Looking for run-time hooks
4147 INFO: Using Python library C:\Windows\system32\python27.dll
4200 INFO: Warnings written to C:\Users\bjones\Documents\pyinstaller-git\tests\b
asic\build\test_onefile_ctypes\warntest_onefile_ctypes.txt
4206 INFO: checking PYZ
4207 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
4207 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
5000 INFO: checking PKG
5001 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
5001 INFO: building PKG (CArchive) out00-PKG.pkg
5972 INFO: checking EXE
5973 INFO: rebuilding out00-EXE.toc because test_onefile_ctypes.exe missing
5973 INFO: building EXE from out00-EXE.toc
5976 INFO: Appending archive to EXE C:\Users\bjones\Documents\pyinstaller-git\te
sts\basic\dist\test_onefile_ctypes.exe

########## EXECUTING TEST basic/test_onefile_ctypes ##########

RUNNING: dist\test_onefile_ctypes.exe

########## STDOUT basic/test_onefile_ctypes ##########


########## STDERR basic/test_onefile_ctypes ##########

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\bjones\Documents\pyinstaller-git\tests\basic\build\test_onefile
_ctypes\out00-PYZ.pyz\ctypeslib", line 32, in dummy
  File "C:\Users\bjones\Documents\pyinstaller-git\tests\basic\build\test_onefile
_ctypes\out00-PYZ.pyz\ctypes", line 365, in __init__
WindowsError: [Error 126] The specified module could not be found

FAIL

======================================================================
FAIL: test_onefile_ctypes (__main__.GenericTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 537, in _generic_test_function
    msg='Running exe of %s failed.' % self.test_name)
AssertionError: False is not True : Running exe of basic/test_onefile_ctypes fai
led.

----------------------------------------------------------------------
Ran 1 test in 5.159s

FAILED (failures=1)
```

My configuration:

```
C:\Users\bjones\Documents\pyinstaller-git\tests>systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. A03, 4/11/2011

C:\Users\bjones\Documents\pyinstaller-git\tests>python --version
Python 2.7.5

C:\Users\bjones\Documents\pyinstaller-git\tests>git log -1
commit 970c1b9bfbae5e66220d880457bc50a2af466aa7
Merge: e1e76d2 03902c1
Author: Martin Zibricky <matysek@users.noreply.github.com>
Date:   Thu Nov 20 18:39:03 2014 +0100

    Merge pull request #1091 from matysek/develop

    Fixed a couple of failing tests from issue #1089.
```

**Comment by matysek** [comment]
@htgoebel is working on tests in #1341 . Closing as duplicate.
