### ISSUE TITLE
LookupError: unknown encoding: idna in child process when using multiprocessing with PyInstaller.

### ISSUE THREAD

**Issue by marcinbarczynski** [pyinstaller/pyinstaller#1113]
PyInstaller: version 2.1
Platform: Linux

Let's consider the following code:

``` python
import requests
from requests.exceptions import ConnectionError
import multiprocessing as mp
#import encodings.idna

def connect():
    try:
        response = requests.request('GET', 'http://localhost:1234')
    except ConnectionError as e:
        pass

if __name__ == "__main__":
    mp.freeze_support()
    ps = [mp.Process(target=connect) for _ in range(1000)]

    for p in ps:
        p.start()

    for p in ps:
        p.join()
```

When I run PyInstalled version of it (--onedir or --onefile), some processes succeed, but some fail with the following error:

```
Process Process-117:
Traceback (most recent call last):
  File "/home/barczynski/Downloads/a/build/req2/out00-PYZ.pyz/multiprocessing.process", line 258, in _bootstrap
  File "/home/barczynski/Downloads/a/build/req2/out00-PYZ.pyz/multiprocessing.process", line 114, in run
  File "<string>", line 8, in connect
  File "/home/barczynski/Downloads/a/build/req2/out00-PYZ.pyz/requests.api", line 44, in request
  File "/home/barczynski/Downloads/a/build/req2/out00-PYZ.pyz/requests.sessions", line 422, in request
  File "/home/barczynski/Downloads/a/build/req2/out00-PYZ.pyz/requests.sessions", line 360, in prepare_request
  File "/home/barczynski/Downloads/a/build/req2/out00-PYZ.pyz/requests.models", line 294, in prepare
  File "/home/barczynski/Downloads/a/build/req2/out00-PYZ.pyz/requests.models", line 352, in prepare_url
LookupError: unknown encoding: idna
```

Uncommenting `import encodings.idna` helps, but it doesn't remove the root cause of it.

**Comment by htgoebel** [comment]
@marcinbarczynski Can you please check if this error still occurs in the current development version. If so, please check if #1161 solved this issue. Thanks for your support.

**Comment by htgoebel** [comment]
In contrast to https://github.com/pyinstaller/pyinstaller/issues/1113#issuecomment-67745639 I was now able to reproduce the problem and #1161 solves the issue.

**Comment by htgoebel** [comment]
Merged #1161, so I can close this issue new.

**Comment by AndCycle** [comment]
hit similar one with concurrent.futures.ThreadPoolExecutor on current dev ver.

**Comment by John-Nagle** [comment]
I've had this error on Windows 7 with a single-process but multi-thread Python program. It's intermittent; sometimes I don't get the error.  Python 3.4, Pyinstaller 3.2. 

The error traceback is

    File "socket.py", line 533, in getaddrinfo
    LookupError: unknown encoding: idna 

I've tried putting

    hiddenimports=["encodings.idna"],

in the .spec file, but it didn't help. 

The line in socket.py is

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

so the problem is actually in C code. Looking at "socketmodule.c", where "getaddrinfo" is implemented in (https://github.com/python/cpython/blob/master/Modules/socketmodule.c) there is

    idna = PyUnicode_AsEncodedString(hobj, "idna", NULL);

This is documented at (https://docs.python.org/3/c-api/unicode.html), which says "The codec to be used is looked up using the Python codec registry."

This isn't an ordinary import error. It's a codec lookup error, from "codecs.lookup(encodingname)":
Documentation says "Encodings are first looked up in the registry’s cache. If not found, the list of registered search functions is scanned. If no CodecInfo object is found, a LookupError is raised. Otherwise, the CodecInfo object is stored in the cache and returned to the caller."

More to follow; the problem is still further down.

**Comment by John-Nagle** [comment]
I've been able to get this to work by adding

    import encodings.idna

in the main Python program. Adding it as a hidden import won't work. Apparently including the encoding somehow registers it, although I don't see from the source code to "idna.py" how that happens.

**Comment by fiendish** [comment]
I'm also having this error on latest pyinstaller dev with Fedora 25, python 3.5.2. Maybe the bug should be reopened?

**Comment by htgoebel** [comment]
We just recently discovered some issues in the import mechanism when using threading #2371 , maybe this is related. Can out try #2377

**Comment by fiendish** [comment]
Reporting back. I just tried with editing PyInstaller/loader/pyimod03_importers.py  as suggested in #2377
Still getting the error.  Here's my traceback showing it still happening in getaddrinfo same as @John-Nagle 

```
Traceback (most recent call last):
  File "exfiltrate.py", line 195, in fetch_thumbnail
  File "exfiltrate.py", line 235, in fetch_to_file
  File "urllib/request.py", line 163, in urlopen
  File "urllib/request.py", line 466, in open
  File "urllib/request.py", line 484, in _open
  File "urllib/request.py", line 444, in _call_chain
  File "urllib/request.py", line 1282, in http_open
  File "urllib/request.py", line 1254, in do_open
  File "http/client.py", line 1106, in request
  File "http/client.py", line 1151, in _send_request
  File "http/client.py", line 1102, in endheaders
  File "http/client.py", line 934, in _send_output
  File "http/client.py", line 877, in send
  File "http/client.py", line 849, in connect
  File "socket.py", line 693, in create_connection
  File "socket.py", line 732, in getaddrinfo
LookupError: unknown encoding: idna
```
fetch_thumbnail is running inside a concurrent.futures.ThreadPoolExecutor worker.
fetch_to_file basically just does 
`with urllib.request.urlopen(url, None, 10) as r, open(to_file, 'wb') as of:
    of.write(r.read())
` with retries on timeout.

The suggestion to import encodings.idna in the main app also works for me.

**Comment by xoviat** [comment]
@fiendish Add the following to [line 607][1] and post the output:

```
print(module.__spec__.name)
```

[1]: https://github.com/pyinstaller/pyinstaller/pull/2377/files#diff-2f954df38432470965be62cb3747992aR607

**Comment by fiendish** [comment]
```
os
stat
posixpath
genericpath
ctypes
ctypes._endian
urllib
urllib.parse
urllib.request
base64
bisect
email
hashlib
http
enum
http.client
email.parser
email.feedparser
email.errors
email.message
uu
quopri
warnings
email.utils
random
socket
selectors
datetime
email._parseaddr
calendar
email.charset
email.base64mime
email.quoprimime
string
email.encoders
email._policybase
email.header
email._encoded_words
email.iterators
ssl
ipaddress
textwrap
tempfile
shutil
fnmatch
tarfile
copy
bz2
_compression
threading
tokenize
token
lzma
contextlib
urllib.error
urllib.response
subprocess
signal
concurrent
concurrent.futures
concurrent.futures._base
logging
concurrent.futures.process
queue
multiprocessing
multiprocessing.context
multiprocessing.process
multiprocessing.connection
multiprocessing.reduction
pickle
_compat_pickle
multiprocessing.util
concurrent.futures.thread

Processing request.
Completed files will be put in the exfiltrated_documents/ETAT_CIVIL_MER folder.
Run again with the same parameters to resume exfiltration.
Fetching thumbnails
stringprep
unknown encoding: idna
Traceback (most recent call last):
  File "exfiltrate.py", line 195, in fetch_thumbnail
  File "exfiltrate.py", line 235, in fetch_to_file
  File "urllib/request.py", line 163, in urlopen
  File "urllib/request.py", line 466, in open
  File "urllib/request.py", line 484, in _open
  File "urllib/request.py", line 444, in _call_chain
  File "urllib/request.py", line 1282, in http_open
  File "urllib/request.py", line 1254, in do_open
  File "http/client.py", line 1106, in request
  File "http/client.py", line 1151, in _send_request
  File "http/client.py", line 1102, in endheaders
  File "http/client.py", line 934, in _send_output
  File "http/client.py", line 877, in send
  File "http/client.py", line 849, in connect
  File "socket.py", line 693, in create_connection
  File "socket.py", line 732, in getaddrinfo
LookupError: unknown encoding: idna
```

**Comment by xoviat** [comment]
Well, the error is coming from [here][1]. Try this: add the following to to the [search function][2]:

```
print(encoding)
```

Also, print the ImportError that occurs [here][3].

```
except Exception as e:
    print(e)
```


[1]: https://github.com/python/cpython/blob/636be379d8f1f447b87d99989c07cead4faabe15/Python/codecs.c#L171
[2]: https://github.com/python/cpython/blob/636be379d8f1f447b87d99989c07cead4faabe15/Lib/encodings/__init__.py#L73
[3]: https://github.com/python/cpython/blob/636be379d8f1f447b87d99989c07cead4faabe15/Lib/encodings/__init__.py#L104

**Comment by xoviat** [comment]
Unfortunately, I was unable to reproduce the given example on Python 3.6:

```
PS C:\Users\User\Downloads> cat pyinstallertest.py
import requests
from requests.exceptions import ConnectionError
import multiprocessing as mp
#import encodings.idna

def connect():
    try:
        response = requests.request('GET', 'http://localhost:1234')
    except ConnectionError as e:
        pass

if __name__ == "__main__":
    mp.freeze_support()
    ps = [mp.Process(target=connect) for _ in range(1000)]

    for p in ps:
        p.start()

    for p in ps:
        p.join()
PS C:\Users\User\Downloads> pyinstaller pyinstallertest.py
1345 INFO: PyInstaller: 3.3.dev0+g278f57f
1346 INFO: Python: 3.6.0
1346 INFO: Platform: Windows-10-10.0.14393-SP0
1349 INFO: wrote C:\Users\User\Downloads\pyinstallertest.spec
1352 INFO: UPX is not available.
1356 INFO: Extending PYTHONPATH with paths
['C:\\Users\\User\\Downloads', 'C:\\Users\\User\\Downloads']
1357 INFO: checking Analysis
1381 INFO: Building because C:\Users\User\Downloads\pyinstallertest.py changed
1381 INFO: Initializing module dependency graph...
1388 INFO: Initializing module graph hooks...
1410 INFO: Analyzing base_library.zip ...
10687 INFO: running Analysis out00-Analysis.toc
10713 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\program files\python36\python.exe
12000 INFO: Caching module hooks...
12005 INFO: Analyzing C:\Users\User\Downloads\pyinstallertest.py
18049 INFO: Loading module hooks...
18050 INFO: Loading module hook "hook-encodings.py"...
18161 INFO: Loading module hook "hook-pydoc.py"...
18178 INFO: Loading module hook "hook-requests.py"...
18183 INFO: Loading module hook "hook-xml.py"...
18474 INFO: Looking for ctypes DLLs
18489 INFO: Analyzing run-time hooks ...
18501 INFO: Looking for dynamic libraries
21760 INFO: Looking for eggs
21761 INFO: Using Python library c:\program files\python36\python36.dll
21761 INFO: Found binding redirects:
[]
21772 INFO: Warnings written to C:\Users\User\Downloads\build\pyinstallertest\warnpyinstallertest.txt
21859 INFO: checking PYZ
21876 INFO: Building because toc changed
21877 INFO: Building PYZ (ZlibArchive) C:\Users\User\Downloads\build\pyinstallertest\out00-PYZ.pyz
23048 INFO: Building PYZ (ZlibArchive) C:\Users\User\Downloads\build\pyinstallertest\out00-PYZ.pyz completed success
fully.
23068 INFO: checking PKG
23069 INFO: Building because C:\Users\User\Downloads\build\pyinstallertest\out00-PYZ.pyz changed
23069 INFO: Building PKG (CArchive) out00-PKG.pkg
23110 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
23112 INFO: Bootloader C:\Users\User\AppData\Roaming\Python\Python36\site-packages\PyInstaller\bootloader\Windows-64
bit\run.exe
23112 INFO: checking EXE
23115 INFO: Rebuilding out00-EXE.toc because pkg is more recent
23115 INFO: Building EXE from out00-EXE.toc
23115 INFO: Appending archive to EXE C:\Users\User\Downloads\build\pyinstallertest\pyinstallertest.exe
23228 INFO: Building EXE from out00-EXE.toc completed successfully.
23235 INFO: checking COLLECT
23236 INFO: Building COLLECT out00-COLLECT.toc
25005 INFO: Building COLLECT out00-COLLECT.toc completed successfully.
PS C:\Users\User\Downloads> .\dist\pyinstallertest\pyinstallertest.exe
PS C:\Users\User\Downloads>
```

**Comment by fiendish** [comment]
I'll see if I can write up a minimal test when I get home in a few hours,
but at least for now I can point you at my not-so-minimal but hopefully
helpful problem child.

Get this file:
https://github.com/fiendish/anom_exfiltrator/blob/master/exfiltrate.py

Then

`pyinstall --onefile exfiltrate.py`

And then

```
./exfiltrate '
http://anom.archivesnationales.culture.gouv.fr/p2w/?dossier=/collection/INVENTAIRES/DPPC/NMD/&first=ETAT_CIVIL_MER_018&last=ETAT_CIVIL_MER_022&title=Delsol,+Auguste+12+d%C3%A9cembre+1828
'
```

**Comment by fiendish** [comment]
Markdown formatting doesn't work if you respond by email? Doh.

**Comment by fiendish** [comment]
I'll see if I can write up a minimal test when I get home in a few hours,
but at least for now I can point you at my not-so-minimal but hopefully
helpful problem child.

Get this file:
https://github.com/fiendish/anom_exfiltrator/blob/master/exfiltrate.py

Then

`pyinstall --onefile exfiltrate.py`

And then

```
./exfiltrate 'http://anom.archivesnationales.culture.gouv.fr/p2w/?dossier=/collection/INVENTAIRES/DPPC/NMD/&first=ETAT_CIVIL_MER_018&last=ETAT_CIVIL_MER_022&title=Delsol,+Auguste+12+d%C3%A9cembre+1828'
```

**Comment by xoviat** [comment]
I never was able to replicate the encoding error, but I did receive various FileNotFound errors.

**Comment by fiendish** [comment]
FileNotFound? From my code? Shouldn't be.

**Comment by xoviat** [comment]
Well I don't have the same environment as you:

```
PS C:\Users\User\Downloads> .\exfiltrate.py 'http://anom.archivesnationales.culture.gouv.fr/p2w/?dossier=/collection
/INVENTAIRES/DPPC/NMD/&first=ETAT_CIVIL_MER_018&last=ETAT_CIVIL_MER_022&title=Delsol,+Auguste+12+d%C3%A9cembre+1828'

Processing request.
Completed files will be put in the exfiltrated_documents\ETAT_CIVIL_MER folder.
Run again with the same parameters to resume exfiltration.
Fetching thumbnails
.....
Done fetching thumbnails
Fetching pages

Fetching pieces of ETAT_CIVIL_MER page 18.
............
Assembling ETAT_CIVIL_MER page 18.
Traceback (most recent call last):
  File "C:\Users\User\Downloads\exfiltrate.py", line 363, in <module>
    e.exfiltrate(start, end)
  File "C:\Users\User\Downloads\exfiltrate.py", line 337, in exfiltrate
    self.fetch_desired_pages(start, end)
  File "C:\Users\User\Downloads\exfiltrate.py", line 315, in fetch_desired_pages
    total += len(self.fetch_page(page))
  File "C:\Users\User\Downloads\exfiltrate.py", line 288, in fetch_page
    + successful_downloads + [pageFile])
  File "C:\Users\User\Downloads\exfiltrate.py", line 56, in subproc_noconsole
    startupinfo=startupinfo)
  File "C:\Program Files\Python36\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
PS C:\Users\User\Downloads>
```

**Comment by xoviat** [comment]
Well, it's clear that PyInstaller should be loading the encodings module at startup:
```
PS C:\Users\User\Downloads> python -v
import _frozen_importlib # frozen
import _imp # builtin
import sys # builtin
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
# C:\Program Files\Python36\lib\encodings\__pycache__\__init__.cpython-36.pyc matches C:\Program Files\Python36\lib\encodings\__init__.py
# code object from 'C:\\Program Files\\Python36\\lib\\encodings\\__pycache__\\__init__.cpython-36.pyc'
# C:\Program Files\Python36\lib\__pycache__\codecs.cpython-36.pyc matches C:\Program Files\Python36\lib\codecs.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\codecs.cpython-36.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D92A630>
# C:\Program Files\Python36\lib\encodings\__pycache__\aliases.cpython-36.pyc matches C:\Program Files\Python36\lib\encodings\aliases.py
# code object from 'C:\\Program Files\\Python36\\lib\\encodings\\__pycache__\\aliases.cpython-36.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D9691D0>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D91FC18>
# C:\Program Files\Python36\lib\encodings\__pycache__\utf_8.cpython-36.pyc matches C:\Program Files\Python36\lib\encodings\utf_8.py
# code object from 'C:\\Program Files\\Python36\\lib\\encodings\\__pycache__\\utf_8.cpython-36.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D974240>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files\Python36\lib\encodings\__pycache__\latin_1.cpython-36.pyc matches C:\Program Files\Python36\lib\encodings\latin_1.py
# code object from 'C:\\Program Files\\Python36\\lib\\encodings\\__pycache__\\latin_1.cpython-36.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D9746A0>
# C:\Program Files\Python36\lib\__pycache__\io.cpython-36.pyc matches C:\Program Files\Python36\lib\io.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\io.cpython-36.pyc'
# C:\Program Files\Python36\lib\__pycache__\abc.cpython-36.pyc matches C:\Program Files\Python36\lib\abc.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\abc.cpython-36.pyc'
# C:\Program Files\Python36\lib\__pycache__\_weakrefset.cpython-36.pyc matches C:\Program Files\Python36\lib\_weakrefset.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\_weakrefset.cpython-36.pyc'
import '_weakrefset' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D97D5C0>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D974C50>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D974898>
# C:\Program Files\Python36\lib\__pycache__\site.cpython-36.pyc matches C:\Program Files\Python36\lib\site.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\site.cpython-36.pyc'
# C:\Program Files\Python36\lib\__pycache__\os.cpython-36.pyc matches C:\Program Files\Python36\lib\os.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\os.cpython-36.pyc'
import 'errno' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files\Python36\lib\__pycache__\stat.cpython-36.pyc matches C:\Program Files\Python36\lib\stat.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\stat.cpython-36.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F814208>
# C:\Program Files\Python36\lib\__pycache__\ntpath.cpython-36.pyc matches C:\Program Files\Python36\lib\ntpath.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\ntpath.cpython-36.pyc'
# C:\Program Files\Python36\lib\__pycache__\genericpath.cpython-36.pyc matches C:\Program Files\Python36\lib\genericpath.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\genericpath.cpython-36.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F821128>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F814898>
# C:\Program Files\Python36\lib\__pycache__\_collections_abc.cpython-36.pyc matches C:\Program Files\Python36\lib\_collections_abc.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\_collections_abc.cpython-36.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F8216D8>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F802198>
# C:\Program Files\Python36\lib\__pycache__\_sitebuiltins.cpython-36.pyc matches C:\Program Files\Python36\lib\_sitebuiltins.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\_sitebuiltins.cpython-36.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F802550>
# C:\Program Files\Python36\lib\__pycache__\sysconfig.cpython-36.pyc matches C:\Program Files\Python36\lib\sysconfig.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\sysconfig.cpython-36.pyc'
import 'sysconfig' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F802A58>
# C:\Program Files\Python36\lib\__pycache__\_bootlocale.cpython-36.pyc matches C:\Program Files\Python36\lib\_bootlocale.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\_bootlocale.cpython-36.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F957D30>
# C:\Program Files\Python36\lib\encodings\__pycache__\cp1252.cpython-36.pyc matches C:\Program Files\Python36\lib\encodings\cp1252.py
# code object from 'C:\\Program Files\\Python36\\lib\\encodings\\__pycache__\\cp1252.cpython-36.pyc'
import 'encodings.cp1252' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F95D278>
# C:\Program Files\Python36\lib\__pycache__\types.cpython-36.pyc matches C:\Program Files\Python36\lib\types.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\types.cpython-36.pyc'
# C:\Program Files\Python36\lib\__pycache__\functools.cpython-36.pyc matches C:\Program Files\Python36\lib\functools.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\functools.cpython-36.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files\Python36\lib\collections\__pycache__\__init__.cpython-36.pyc matches C:\Program Files\Python36\lib\collections\__init__.py
# code object from 'C:\\Program Files\\Python36\\lib\\collections\\__pycache__\\__init__.cpython-36.pyc'
# C:\Program Files\Python36\lib\__pycache__\operator.cpython-36.pyc matches C:\Program Files\Python36\lib\operator.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\operator.cpython-36.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285FA916A0>
# C:\Program Files\Python36\lib\__pycache__\keyword.cpython-36.pyc matches C:\Program Files\Python36\lib\keyword.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\keyword.cpython-36.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285FA9B908>
# C:\Program Files\Python36\lib\__pycache__\heapq.cpython-36.pyc matches C:\Program Files\Python36\lib\heapq.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\heapq.cpython-36.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285FAA1160>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files\Python36\lib\__pycache__\reprlib.cpython-36.pyc matches C:\Program Files\Python36\lib\reprlib.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\reprlib.cpython-36.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285FA95E10>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285FA71DD8>
# C:\Program Files\Python36\lib\__pycache__\weakref.cpython-36.pyc matches C:\Program Files\Python36\lib\weakref.py
# code object from 'C:\\Program Files\\Python36\\lib\\__pycache__\\weakref.cpython-36.pyc'
import 'weakref' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285FA7A208>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F963588>
# C:\Program Files\Python36\lib\collections\__pycache__\abc.cpython-36.pyc matches C:\Program Files\Python36\lib\collections\abc.py
# code object from 'C:\\Program Files\\Python36\\lib\\collections\\__pycache__\\abc.cpython-36.pyc'
import 'collections.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F96A320>
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285F95D828>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x000001285D982E10>
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
>>>
```

**Comment by fiendish** [comment]
> Well I don't have the same environment as you. I don't have gm installed.

Ah. Oops, yeah. I forgot that it execs gm. For me the error happens in fetching thumbnails, which your environment gets past, and for this URL that happens before you get to any gm calls.

**Comment by fiendish** [comment]
I just tested Python 3.6.0 and problem still occurs. If you can't replicate, then perhaps it's only on Linux and not Windows?

**Comment by xoviat** [comment]
What's odd is that my script doesn't seem to be importing encodings either.

**Comment by xoviat** [comment]
[Found it.][1] 

[1]: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/pyiboot01_bootstrap.py#L111

**Comment by xoviat** [comment]
I've been able to isolate this issue, and it's not good news. The encodings are being loaded with the builtin importer, which means this is a CPython problem.

**Comment by xoviat** [comment]
You can see the imports here:

```
Builtin: pyimod00_crypto_key
Builtin: os
os
Builtin: errno
Builtin: stat
stat
Builtin: _stat
Builtin: ntpath
ntpath
Builtin: genericpath
genericpath
Builtin: _collections_abc
Builtin: ctypes
ctypes
Builtin: _ctypes
Builtin: ctypes._endian
ctypes._endian
Builtin: urllib
urllib
Builtin: urllib.parse
urllib.parse
Builtin: re
Builtin: enum
enum
Builtin: types
Builtin: functools
Builtin: _functools
Builtin: collections
Builtin: operator
Builtin: _operator
Builtin: keyword
Builtin: heapq
Builtin: _heapq
Builtin: itertools
Builtin: reprlib
Builtin: _collections
Builtin: weakref
Builtin: collections.abc
Builtin: sre_compile
Builtin: _sre
Builtin: sre_parse
Builtin: sre_constants
Builtin: _locale
Builtin: copyreg
Builtin: urllib.request
urllib.request
Builtin: base64
base64
Builtin: binascii
Builtin: bisect
bisect
Builtin: _bisect
Builtin: email
email
Builtin: hashlib
hashlib
Builtin: _hashlib
Builtin: _blake2
Builtin: _sha3
Builtin: http
http
Builtin: http.client
http.client
Builtin: email.parser
email.parser
Builtin: email.feedparser
email.feedparser
Builtin: email.errors
email.errors
Builtin: email._policybase
email._policybase
Builtin: email.header
email.header
Builtin: email.quoprimime
email.quoprimime
Builtin: string
string
Builtin: _string
Builtin: email.base64mime
email.base64mime
Builtin: email.charset
email.charset
Builtin: email.encoders
email.encoders
Builtin: quopri
quopri
Builtin: email.utils
email.utils
Builtin: time
Builtin: random
random
Builtin: warnings
warnings
Builtin: math
Builtin: _random
Builtin: socket
socket
Builtin: _socket
Builtin: selectors
selectors
Builtin: select
Builtin: datetime
datetime
Builtin: _datetime
Builtin: email._parseaddr
email._parseaddr
Builtin: calendar
calendar
Builtin: locale
Builtin: email.message
email.message
Builtin: uu
uu
Builtin: email._encoded_words
email._encoded_words
Builtin: email.iterators
email.iterators
Builtin: ssl
ssl
Builtin: ipaddress
ipaddress
Builtin: textwrap
textwrap
Builtin: _ssl
Builtin: posixpath
posixpath
Builtin: tempfile
tempfile
Builtin: shutil
shutil
Builtin: fnmatch
fnmatch
Builtin: tarfile
tarfile
Builtin: copy
copy
Builtin: org
Find module: org
Builtin: grp
Find module: grp
Builtin: bz2
bz2
Builtin: _compression
_compression
Builtin: threading
threading
Builtin: traceback
Builtin: linecache
Builtin: tokenize
tokenize
Builtin: token
token
Builtin: _bz2
Builtin: lzma
lzma
Builtin: _lzma
Builtin: pwd
Find module: pwd
Builtin: grp
Find module: grp
Builtin: contextlib
contextlib
Builtin: urllib.error
urllib.error
Builtin: urllib.response
urllib.response
Builtin: nturl2path
nturl2path
Builtin: subprocess
subprocess
Builtin: signal
signal
Builtin: msvcrt
Builtin: _winapi
Builtin: concurrent
concurrent
Builtin: concurrent.futures
concurrent.futures
Builtin: concurrent.futures._base
concurrent.futures._base
Builtin: logging
logging
Builtin: atexit
Builtin: concurrent.futures.process
concurrent.futures.process
Builtin: queue
queue
Builtin: multiprocessing
multiprocessing
Builtin: multiprocessing.context
multiprocessing.context
Builtin: multiprocessing.process
multiprocessing.process
Builtin: multiprocessing.reduction
multiprocessing.reduction
Builtin: pickle
pickle
Builtin: _compat_pickle
_compat_pickle
Builtin: org
Find module: org
Builtin: _pickle
Builtin: multiprocessing.connection
multiprocessing.connection
Builtin: _multiprocessing
Builtin: multiprocessing.util
multiprocessing.util
Builtin: concurrent.futures.thread
concurrent.futures.thread

Processing request.
Completed files will be put in the exfiltrated_documents\ETAT_CIVIL_MER folder.
Run again with the same parameters to resume exfiltration.
Builtin: _bootlocale
Builtin: encodings.cp1252
Fetching thumbnails
.....
Done fetching thumbnails
Fetching pages

Fetching pieces of ETAT_CIVIL_MER page 18.
...Builtin: encodings.idna
Builtin: stringprep
stringprep
Builtin: unicodedata
.........
```

**Comment by htgoebel** [comment]
@fiendish 
1. Please try again with the current development head, as we now included some changes xoviat mentioned earlier.
2. If this still does not work, please create a **minimal** example for reproducing the error. Which means: remove everything from your code which is not relevant for this bug, esp. don't use external programs.
3. Please report back if the problem still exists.
4. If the problem still exists, please (again) describe you current test environment. If you are using some Python distribution, also describe this and give the version number or date.

@xoviat: 
> I've been able to isolate this issue, and it's not good news. The encodings are being loaded with the builtin importer, which means this is a CPython problem. What you could try is this: replace line 665 with the following:

Can you please elaborate this? Your suggestion basically means changing the order imports are searched, see  #1455 for a decent list of importers for Python 2 and Python 3. `encodings` is not built-in, but contained in `base_library.zip`. So it should not be the "built-in importer" (as you wrote), but the "built-in *frozen* importer" – which may look like the same.

`encodings.idna` is included in base_library.zip, too, to it should be imported be the built-in frozen importer.

> What I'm curious about is what other modules should we be importing that Python imports on startup?

As you already found out, its the modules used my loader/pyimod* and loader/pyboot*. For Python 3 this includes quite some stuff included in `base_library.zip`.

**Comment by FadedCoder** [comment]
Ping. Facing same issue on Windows 10, Python 3.7.2 and using aiohttp. Will post a minimal example soon, but it's along the lines of:
```
for _ in range(threads):  # I used threads 30-ish and this problem appeared.
    tasks.append(process(queue))  # process is quite resource intensive, handful of aiohttp calls, some encryption and decryption.
```
This bug does not appear when thread count is around 1-3. Although I haven't run the program for a long stretch, so can't be sure.
Log is same as others.
`import encodings.idna` did fix it.

**Comment by efiop** [comment]
For the record, here is how awscli guys resolved it https://github.com/aws/aws-cli/blob/1.16.277/awscli/clidriver.py#L55

**Comment by amaork** [comment]
This problem can be fixed in a strange way: 
Just add `socket.gethostbyname_ex(socket.gethostname())`  before launch `concurrent.futures.ThreadPoolExecutor()`.
Your can refer here: https://github.com/amaork/raspi-io/blob/master/raspi_io/utility.py#L111
