### ISSUE TITLE
Problem with pandas

### ISSUE THREAD

**Issue by lucapinello** [pyinstaller/pyinstaller#1130]
Hi, I am trying to package some software with Pyinstaller that uses pandas: http://pandas.pydata.org/

In particular it seems that there is some strange problem with using  the read_csv function, 
a function to read a text file and convert to a dataframe.

I am attaching a minimal code just with a call to read_csv so you can  reproduce the error here:
https://groups.google.com/forum/#!searchin/PyInstaller/luca/pyinstaller/1XxQzdnFCJk/f1VRgVVk-y4J

I am using pandas 0.13.1 (i tried also 0.14) and pyinstaller 2.1.

Using the --onedir mode it works fine. Instead with the --onefile there is something that is not get imported properly.

On Linux and Cygwin it works fine, the problem is only on OSX.

The TextReader class is inside pandas.parser

I tried to add pandas.parser to the hidden_imports on the specs file but it doesn't help.

Any idea how to fix this problem?

This is the tracklog:
```
lucas-mbp:test_pyinstaller luca$ ./dist/test_pandas 
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/Users/luca/Desktop/test_pyinstaller/build/test_pandas/out00-PYZ.pyz/pandas.io.parsers", line 420, in parser_f
  File "/Users/luca/Desktop/test_pyinstaller/build/test_pandas/out00-PYZ.pyz/pandas.io.parsers", line 218, in _read
  File "/Users/luca/Desktop/test_pyinstaller/build/test_pandas/out00-PYZ.pyz/pandas.io.parsers", line 502, in __init__
  File "/Users/luca/Desktop/test_pyinstaller/build/test_pandas/out00-PYZ.pyz/pandas.io.parsers", line 610, in _make_engine
  File "/Users/luca/Desktop/test_pyinstaller/build/test_pandas/out00-PYZ.pyz/pandas.io.parsers", line 972, in __init__
AttributeError: 'module' object has no attribute 'TextReader'
```
Thanks a lot.

Luca

**Comment by matysek** [comment]
@lucapinello could you try with latest dev version?

**Comment by matysek** [comment]
Not responded for a long time.
