### ISSUE TITLE
"No such file" when copying file from bincache - OSX

### ISSUE THREAD

**Issue by cortesi** [pyinstaller/pyinstaller#1132]
Hi folks, 

I've just released a new version of mitmproxy, and hit two bugs in pyinstaller (I'll make a separate issue for the second bug). The first is shown by the following traceback when attempting to build either mitmproxy or mitmdump with pyinstaller: 

```
Traceback (most recent call last):
  File "/Users/cortesi/tmp/pyinstaller/pyinstaller.py", line 18, in <module>
    run()
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/build.py", line 1966, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/build.py", line 1915, in build
    execfile(spec)
  File "./release/mitmdump.spec", line 32, in <module>
    console=True )
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/build.py", line 1150, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/build.py", line 988, in __init__
    self.__postinit__()
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/build.py", line 320, in __postinit__
    self.assemble()
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/build.py", line 1030, in assemble
    dist_nm=inm)
  File "/Users/cortesi/tmp/pyinstaller/PyInstaller/build.py", line 857, in checkCache
    shutil.copy2(fnm, cachedfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/cortesi/Library/Application Support/pyinstaller/bincache00_py27/cryptography/_Cryptography_cffi_2a871178xb3816a41.so
```

I tracked this down to commit b813174a3067baf15af02c63ae82946dc446187b by @htgoebel - when I revert this, the build succeeds. 

To reproduce this, simply check out the current [mitmproxy master](http://github.com/mitmproxy/mitmproxy), and attempt to package mitmdump. I tested this on OSX Yosemite. 

Thanks,

Aldo

**Comment by matysek** [comment]
Fix merged in #1135.
