### ISSUE TITLE
Error importing xcb.proto in Ubuntu 14.04

### ISSUE THREAD

**Issue by jlcastillo** [pyinstaller/pyinstaller#1152]
OS: Ubuntu 14.04 64-bit
Python: 2.7.6

test.py
```
import xcb.proto       # installed from python-xpyb 1.3.1-1 Ubuntu package
print "hello world"
```
Run
```
> python test.py
hello world
```
Compile & Run:
```
> pyinstaller test.py
> ./dist/test/test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/media/sf_dev/build/test/out00-PYZ.pyz/xcb.xproto", line 11, in <module>
AttributeError: 'module' object has no attribute 'Struct'

```

xproto.py   (/usr/lib/python2.7/dist-packages/xcb/)
```
#
# This file generated automatically from xproto.xml by py_client.py.
# Edit at your peril.
#

import xcb
import cStringIO
from struct import pack, unpack_from
from array import array

class CHAR2B(xcb.Struct):                                     #  line 11
    def __init__(self, parent, offset, size):
        xcb.Struct.__init__(self, parent, offset, size)
        (self.byte1, self.byte2,) = unpack_from('BB', parent, offset)
```

List dist folder:
```
> ls ./dist/test
audioop.so     _codecs_hk.so       _codecs_kr.so  _hashlib.so         libpython2.7.so.1.0  libtinfo.so.5  libXdmcp.so.6       readline.so  test
bz2.so         _codecs_iso2022.so  _codecs_tw.so  libbz2.so.1.0       libreadline.so.6     libXau.so.6    libz.so.1           _ssl.so      xcb.xcb.so
_codecs_cn.so  _codecs_jp.so       datetime.so    libcrypto.so.1.0.0  libssl.so.1.0.0      libxcb.so.1    _multibytecodec.so  termios.so
```

Note that xcb.xcb.so is an exact copy of /usr/lib/python2.7/dist-packages/xcb/xcb.so, installed by Ubuntu package python-xpyb 1.3.1-1. Let's inspect it:

```
> nm -D ./dist/test/xcb.xcb.so | grep Struct
                 U _Py_NoneStruct
                 U _Py_ZeroStruct
0000000000007110 T xpybStruct_modinit
000000000020bd60 D xpybStruct_type
```

strace (without installer)

```
> strace python test.py  2>&1 | grep open.*xcb\\. | grep -v such
open("/usr/lib/python2.7/dist-packages/xcb/xcb.so", O_RDONLY) = 4
open("/usr/lib/python2.7/dist-packages/xcb/xcb.so", O_RDONLY|O_CLOEXEC) = 5
open("/usr/lib/x86_64-linux-gnu/libxcb.so.1", O_RDONLY|O_CLOEXEC) = 5
```

strace (with installer)
```
> strace ./dist/test/test 2>&1 | grep open
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/media/sf_dev/dist/test/test", O_RDONLY) = 3
```
Any idea of what may be happening? Some old posts suggest fixing symbolic links to xcb, but doesn't seem to be my problem, as xcb.so is actually collected.

**Comment by htgoebel** [comment]
This looks more like the import-mechanism does not load the xcb.xcb.so when it should.
Please the PyInstaller development version. If this does not help, use strace to see where PyInstaller searches for the .so.

**Comment by jlcastillo** [comment]
I edited the original comment, adding the strace while you were writing yours..

**Comment by jlcastillo** [comment]
Thanks, it works fine with the latest development versión. I tried both one-dir and one-file options.
