### ISSUE TITLE
PyInstaller test_pycrypto failed

### ISSUE THREAD

**Issue by lumy** [pyinstaller/pyinstaller#1154]
Hi,

I just clone the depot, and run the test,
```
(env_2.7)bash-3.2$ python runtests.py test_pycrypto
Running test:  /test_pycrypto
114 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:
VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /Users/lumy-meludia/.pyenv/versions/env_2.7/bin/python
4128 INFO: UPX is not available.
4156 INFO: Processing hook hook-os
4268 INFO: Processing hook hook-time
4271 INFO: Processing hook hook-cPickle
4343 INFO: Processing hook hook-_sre
4465 INFO: Processing hook hook-cStringIO
4561 INFO: Processing hook hook-encodings
4575 INFO: Processing hook hook-codecs
test_pycrypto (__main__.GenericTestCase) ... FAIL
======================================================================
FAIL: test_pycrypto (__main__.GenericTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 542, in _generic_test_function
    msg='Test %s not found.' % self.test_name)
AssertionError: False is not true : Test /test_pycrypto not found.
----------------------------------------------------------------------
Ran 1 test in 0.001s
FAILED (failures=1)
```

And if i run the full test i get

```
(env_2.7)bash-3.2$ python runtests.py
Running normal tests (-i for interactive tests)...
91 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:
    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /Users/lumy-meludia/.pyenv/versions/env_2.7/bin/python
4099 INFO: UPX is not available.
4123 INFO: Processing hook hook-os
4230 INFO: Processing hook hook-time
4233 INFO: Processing hook hook-cPickle
4310 INFO: Processing hook hook-_sre
4422 INFO: Processing hook hook-cStringIO
4518 INFO: Processing hook hook-encodings
4532 INFO: Processing hook hook-codecs
test_12 (__main__.BasicTestCase) ... ok
test_13 (__main__.BasicTestCase) ... ok
test_absolute_ld_library_path (__main__.BasicTestCase) ... skipped 'Required another Python version or OS.'
test_absolute_python_path (__main__.BasicTestCase) ... ok
test_celementtree (__main__.BasicTestCase) ... ok
test_codecs (__main__.BasicTestCase) ... ok
test_email (__main__.BasicTestCase) ... ok
test_email_oldstyle (__main__.BasicTestCase) ... ok
test_encoders (__main__.BasicTestCase) ... ok
test_f_option (__main__.BasicTestCase) ... ok
test_filename (__main__.BasicTestCase) ... ok
test_getfilesystemencoding (__main__.BasicTestCase) ... ok
test_helloworld (__main__.BasicTestCase) ... ok
test_module__file__attribute (__main__.BasicTestCase) ... ok
test_module_attributes (__main__.BasicTestCase) ... ok
test_module_reload (__main__.BasicTestCase) ... ok
test_multiprocess (__main__.BasicTestCase) ... ok
test_onefile_chdir_meipass (__main__.BasicTestCase) ... ok
test_onefile_ctypes (__main__.BasicTestCase) ... ok
test_onefile_get_meipass2_value (__main__.BasicTestCase) ... ok
test_onefile_helloworld (__main__.BasicTestCase) ... ok
test_onefile_module__file__attribute (__main__.BasicTestCase) ... ok
test_onefile_multiprocess (__main__.BasicTestCase) ... ok
test_onefile_nestedlaunch0 (__main__.BasicTestCase) ... ok
test_onefile_nestedlaunch1 (__main__.BasicTestCase) ... ok
test_onefile_python_makefile (__main__.BasicTestCase) ... ok
test_onefile_win32com (__main__.BasicTestCase) ... skipped 'Module win32com is missing.'
test_option_verbose (__main__.BasicTestCase) ... ok
test_option_wignore (__main__.BasicTestCase) ... ok
test_pkg_structures (__main__.BasicTestCase) ... ok
test_python_home (__main__.BasicTestCase) ... ok
test_pyz_as_external_file (__main__.BasicTestCase) ... ok
test_site (__main__.BasicTestCase) ... ok
test_threading (__main__.BasicTestCase) ... ok
test_threading2 (__main__.BasicTestCase) ... ok
test_time (__main__.BasicTestCase) ... ok
test_win32com (__main__.BasicTestCase) ... skipped 'Module win32com is missing.'
test_crypto (__main__.CryptoTestCase) ... NOTE: Bytecode encryption is enabled for this test.ok
test_nocrypto (__main__.CryptoTestCase) ... ok
test_onefile_crypto (__main__.CryptoTestCase) ... NOTE: Bytecode encryption is enabled for this test.ok
test_onefile_nocrypto (__main__.CryptoTestCase) ... ok
test_app_with_plugins (__main__.ImportTestCase) ... ok
test_c_extension (__main__.ImportTestCase) ... skipped 'Module simplejson is missing.'
test_ctypes_cdll_c (__main__.ImportTestCase) ... ok
test_eggs1 (__main__.ImportTestCase) ... skipped 'Unzipped eggs not yet implemented.'
test_eggs2 (__main__.ImportTestCase) ... ok
test_hiddenimport (__main__.ImportTestCase) ... ok
test_hook_without_hook_for_package (__main__.ImportTestCase) ... ok
test_import_module_with_unicode (__main__.ImportTestCase) ... ok
test_onefile_c_extension (__main__.ImportTestCase) ... skipped 'Module simplejson is missing.'
test_onefile_ctypes_cdll_c (__main__.ImportTestCase) ... ok
test_onefile_error_during_import (__main__.ImportTestCase) ... ok
test_onefile_pkg_resources (__main__.ImportTestCase) ... ok
test_onefile_pkgutil-get_data (__main__.ImportTestCase) ... ok
test_onefile_pkgutil-get_data__main__ (__main__.ImportTestCase) ... FAIL
test_onefile_relative_import (__main__.ImportTestCase) ... ok
test_onefile_relative_import2 (__main__.ImportTestCase) ... ok
test_onefile_relative_import3 (__main__.ImportTestCase) ... ok
test_onefile_zipimport (__main__.ImportTestCase) ... ok
test_onefile_zipimport2 (__main__.ImportTestCase) ... ok
test_pep302_import_protokol (__main__.ImportTestCase) ... ok
test_Image (__main__.LibrariesTestCase) ... skipped 'Module Image is missing.'
test_Image2 (__main__.LibrariesTestCase) ... skipped 'Module Image is missing.'
test_PIL (__main__.LibrariesTestCase) ... skipped 'Module PIL is missing.'
test_PIL2 (__main__.LibrariesTestCase) ... skipped 'Module PIL is missing.'
test_PyQt4-QtWebKit (__main__.LibrariesTestCase) ... ok
test_PyQt4-uic (__main__.LibrariesTestCase) ... ok
test_enchant (__main__.LibrariesTestCase) ... skipped 'Required another Python version or OS.'
test_gst (__main__.LibrariesTestCase) ... skipped 'Module gst is missing.'
test_idlelib (__main__.LibrariesTestCase) ... ok
test_keyring (__main__.LibrariesTestCase) ... FAIL
test_markdown (__main__.LibrariesTestCase) ... skipped 'Module markdown is missing.'
test_numpy (__main__.LibrariesTestCase) ... ok
test_onefile_matplotlib (__main__.LibrariesTestCase) ... skipped 'Module matplotlib is missing.'
test_onefile_numpy (__main__.LibrariesTestCase) ... ok
test_onefile_tkinter (__main__.LibrariesTestCase) ... ok
test_pycparser (__main__.LibrariesTestCase) ... ok
test_pycrypto (__main__.LibrariesTestCase) ... FAIL
test_pyexcelerate (__main__.LibrariesTestCase) ... skipped 'Module pyexcelerate is missing.'
test_pygments (__main__.LibrariesTestCase) ... skipped 'Module pygments is missing.'
test_pylint (__main__.LibrariesTestCase) ... skipped 'Module pylint is missing.'
test_pyodbc (__main__.LibrariesTestCase) ... skipped 'Module pyodbc is missing.'
test_python_makefile (__main__.LibrariesTestCase) ... ok
test_pyttsx (__main__.LibrariesTestCase) ... skipped 'Module pyttsx is missing.'
test_pytz (__main__.LibrariesTestCase) ... skipped 'Module pytz is missing.'
test_scapy1 (__main__.LibrariesTestCase) ... skipped 'Module scapy is missing.'
test_scapy2 (__main__.LibrariesTestCase) ... skipped 'Module scapy is missing.'
test_scapy3 (__main__.LibrariesTestCase) ... skipped 'Module scapy is missing.'
test_scipy (__main__.LibrariesTestCase) ... skipped 'Module scipy is missing.'
test_sphinx (__main__.LibrariesTestCase) ... skipped 'Module sphinx is missing.'
test_sqlalchemy (__main__.LibrariesTestCase) ... skipped 'Module sqlalchemy is missing.'
test_sqlite3 (__main__.LibrariesTestCase) ... ok
test_sysconfig (__main__.LibrariesTestCase) ... ok
test_twisted_qt4reactor (__main__.LibrariesTestCase) ... ok
test_twisted_reactor (__main__.LibrariesTestCase) ... ok
test_usb (__main__.LibrariesTestCase) ... ok
test_wx (__main__.LibrariesTestCase) ... skipped 'Module wx is missing.'
test_wx_pubsub (__main__.LibrariesTestCase) ... skipped 'Module wx is missing.'
test_wx_pubsub_arg1 (__main__.LibrariesTestCase) ... skipped 'Module wx is missing.'
test_wx_pubsub_kwargs (__main__.LibrariesTestCase) ... skipped 'Module wx is missing.'
test_xml (__main__.LibrariesTestCase) ... ok
test_zmq (__main__.LibrariesTestCase) ... skipped 'Module zmq is missing.'
test_zope_interface (__main__.LibrariesTestCase) ... ok
test_multipackage1 (__main__.MultipackageTestCase) ... ok
test_multipackage2 (__main__.MultipackageTestCase) ... ok
test_multipackage3 (__main__.MultipackageTestCase) ... ok
test_multipackage4 (__main__.MultipackageTestCase) ... ok
test_multipackage5 (__main__.MultipackageTestCase) ... ok

======================================================================
FAIL: test_onefile_pkgutil-get_data__main__ (__main__.ImportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 546, in _generic_test_function
    msg='Running exe of %s failed.' % self.test_name)
AssertionError: False is not true : Running exe of import/test_onefile_pkgutil-get_data__main__ failed.

======================================================================
FAIL: test_keyring (__main__.LibrariesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 546, in _generic_test_function
    msg='Running exe of %s failed.' % self.test_name)
AssertionError: False is not true : Running exe of libraries/test_keyring failed.

======================================================================
FAIL: test_pycrypto (__main__.LibrariesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 546, in _generic_test_function
    msg='Running exe of %s failed.' % self.test_name)
AssertionError: False is not true : Running exe of libraries/test_pycrypto failed.

----------------------------------------------------------------------
Ran 108 tests in 376.877s

FAILED (failures=3, skipped=31)
```

I was trying to make an MacOsX app containing pycrypto.
What i missed on my dependencies ?

**Comment by htgoebel** [comment]
1) The test is called libraries/test_pycrypto, so for running only this one use: `python runtests.py libraries/test_pycrypto`
2) Run the in verbose mode: `python runtests.py -v libraries/test_pycrypto`
3) Depending on the insights from step 2, you may want to follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong

**Comment by lumy** [comment]
I manage to resolve this problem.
But now i make my application and when i start it i get this error
```
Traceback (most recent call last):
  File "<string>", line 28, in <module>
  File "/Users/lumy-meludia/Meludia/clients/campaign_manager_gui/build/main/out00-PYZ.pyz/campaign_manager_gui.client_campaign.CampaignClient", line 149, in run
  File "/Users/lumy-meludia/Meludia/clients/campaign_manager_gui/build/main/out00-PYZ.pyz/campaign_manager_gui.client_campaign.CampaignClient", line 135, in run
  File "/Users/lumy-meludia/Meludia/clients/campaign_manager_gui/build/main/out00-PYZ.pyz/twisted.internet.posixbase", line 507, in connectSSL
  File "/Users/lumy-meludia/Meludia/clients/campaign_manager_gui/build/main/out00-PYZ.pyz/twisted.protocols.tls", line 769, in __init__
  File "/Users/lumy-meludia/Meludia/clients/campaign_manager_gui/build/main/out00-PYZ.pyz/twisted.protocols.tls", line 648, in __init__
  File "/Users/lumy-meludia/Meludia/clients/campaign_manager_gui/build/main/out00-PYZ.pyz/pymelu_client.client.ClientNetwork", line 43, in getContext
  File "/Users/lumy-meludia/Meludia/clients/campaign_manager_gui/build/main/out00-PYZ.pyz/OpenSSL.SSL", line 391, in use_certificate_file
  File "/Users/lumy-meludia/Meludia/clients/campaign_manager_gui/build/main/out00-PYZ.pyz/OpenSSL._util", line 22, in exception_from_error_queue
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]
```

I now that with py2app i can not import Openssl directly in my project from system libraries.
and I think it's the same kind of probleme. isn't it ?

Thanks for the fast help anyway ! :)

**Comment by matysek** [comment]
@lumy I don't know about py2app but this looks like missing some data files that are not bundled with your app.

**Comment by lumy** [comment]
Yes that was the second problem.
I'm going to close the issue,

For knowledge, i resolve my trouble by installing in my virtualenv and in my system with pip the missing package.
