### ISSUE TITLE
Pyinstaller3: SyntaxError when building even small scripts

### ISSUE THREAD

**Issue by Vieler** [pyinstaller/pyinstaller#1155]
**Platform**: Windows, 64bit
**Python ver.**: 3.4.2, 32bit
**Pyinstaller version**: downloaded zipped `python3` branch, latest commit was `c4abe904e0791841ec3c76306199c16b1c687b98` and did `python setup.py install`.

I tried building my application but failed with this traceback:
```
Traceback (most recent call last):
  File "<root>\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.0.dev0', 'console_scripts', 'pyinstaller')()
  File "<root>\Python34\lib\site-packages\pkg_resources\__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "<root>\Python34\lib\site-packages\pkg_resources\__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "<root>\Python34\lib\site-packages\pkg_resources\__init__.py", line 2310, in load
    return self.resolve()
  File "<root>\Python34\lib\site-packages\pkg_resources\__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<root>\Python34\lib\site-packages\pyinstaller-3.0.dev0-py3.4.egg\PyInstaller\main.py", line 21, in <module>
    import PyInstaller.build
  File "<root>\Python34\lib\site-packages\pyinstaller-3.0.dev0-py3.4.egg\PyInstaller\build.py", line 24, in <module>
    from PyInstaller.depend.utils import is_path_to_egg
  File "<root>\Python34\lib\site-packages\pyinstaller-3.0.dev0-py3.4.egg\PyInstaller\depend\utils.py", line 28, in <module>
    from PyInstaller.utils.hooks.hookutils import collect_submodules
  File "<root>\Python34\lib\site-packages\pyinstaller-3.0.dev0-py3.4.egg\PyInstaller\utils\hooks\hookutils.py", line 329
    except IOError,:
                  ^
SyntaxError: invalid syntax
```
I could reproduce this *exact* error with the following file:
```
import os

print(os.getcwd())
```
and building with
```
pyinstaller test.py
```
I didnit try the develop branch because I assumed it is for `python2` only.

**Comment by matysek** [comment]
This is similar to this pull request #1157 which was merged just today. It should be fixed. Thanks for reporting anyway.
