### ISSUE TITLE
[Pyinstaller3] crcmod: import error on Linux

### ISSUE THREAD

**Issue by thorstenkampe** [pyinstaller/pyinstaller#1160]
I'm getting the following exception after successfully building an executable on Linux. The same Pyinstaller3 generated build works on Windows and with Pyinstaller2 on Linux:
```
Traceback (most recent call last):
  File "/mnt/hgfs/drive-f/Documents/dev/python/script/site-packages-linux/crcmod/__init__.py", line 2, in <module>
    from crcmod.crcmod import *
ImportError: No module named 'crcmod.crcmod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/mnt/hgfs/drive-f/Documents/dev/python/script/pyinstaller/pyinstaller3/PyInstaller/loader/pyi_importers.py", line 302, in load_module
    exec(bytecode, module.__dict__)
  File "/mnt/hgfs/drive-f/Documents/dev/python/script/_init.py", line 15, in <module>
    import time, crcmod                  ## VERSION
  File "/mnt/hgfs/drive-f/Documents/dev/python/script/pyinstaller/pyinstaller3/PyInstaller/loader/pyi_importers.py", line 302, in load_module
    exec(bytecode, module.__dict__)
  File "/mnt/hgfs/drive-f/Documents/dev/python/script/site-packages-linux/crcmod/__init__.py", line 7, in <module>
    import predefined
ImportError: No module named 'predefined'
```

**Comment by matysek** [comment]
@thorstenkampe Do you have any code example to reproduce this error?

Please look at
* https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong
* https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by thorstenkampe** [comment]
The problem was with the third-party module crcmod imported from directory other than site-packages. crcmod is a Python2 and Python3 module from https://pypi.python.org/pypi/crcmod/1.7 .
```
> set PYTHONPATH=

> python3 -c "import crcmod"

> set PYTHONPATH=mytest

> python3 -c "import crcmod"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\Documents\dev\python\script\mytest\crcmod\__init__.py", line 2, in <module>
    from crcmod.crcmod import *
  File "F:\Documents\dev\python\script\mytest\crcmod\crcmod.py", line 88
    def __init__(self, poly, initCrc=~0L, rev=True, xorOut=0, initialize=True):
                                       ^
SyntaxError: invalid syntax

> python2 -c "import crcmod"

>
```
So basically importing crcmod works from `site-packages` or from `mytest` - but not in Python3. Extremely weird, but not a Pyinstaller issue.
