### ISSUE TITLE
PyInstaller 2.1 fails when run in parallel ( using fixed temporary file c:/Temp\\me_test_exe.tmp )

### ISSUE THREAD

**Issue by manuel-koch** [pyinstaller/pyinstaller#1189]
Using PyInstaller to create multiple executables from Python sources in a parallel build process. This results in multiple PyInstaller instances interfering which each other.
In particular PyInstaller uses a simple temp file to test if resource update is possible.

See following stacktrace:
'''
....
391 INFO: Testing for ability to set icons, version resources...
562 INFO: ... resource update available
Traceback (most recent call last):
  File "d:/Python/2.7.2//pyinstaller-2.0/pyinstaller.py", line 91, in <module>
    main()
  File "d:/Python/2.7.2//pyinstaller-2.0/pyinstaller.py", line 86, in main
    run_build(opts, spec_file)
  File "d:/Python/2.7.2//pyinstaller-2.0/pyinstaller.py", line 50, in run_build
    PyInstaller.build.main(spec_file, **opts.__dict__)
  File "d:\Python\2.7.2\pyinstaller-2.0\PyInstaller\build.py", line 1611, in main
    config = configure.get_config(kw.get('upx_dir'))
  File "d:\Python\2.7.2\pyinstaller-2.0\PyInstaller\configure.py", line 171, in get_config
    test_RsrcUpdate(config)
  File "d:\Python\2.7.2\pyinstaller-2.0\PyInstaller\configure.py", line 98, in test_RsrcUpdate
    os.remove(rw_test_exe)
WindowsError: [Error 2] The system cannot find the file specified: 'c:/Temp\\me_test_exe.tmp'
'''

Multiple PyInstaller instances will use the same file c:/Temp\\me_test_exe.tmp and eventually break execution of other instance(s) !?

Please use unique temporary files to allow parallel execution of PyInstaller.

**Comment by codewarrior0** [comment]
It looks like this is fixed in version 2.1. 98e62eb4ca032b64fc83cc80d6c1aab532255c69, issue #706

You seem to be using version 2.0.

**Comment by htgoebel** [comment]
As codewarrior wrote: You are using PyInstaller 2.0 Pleae use at least 2.1 or - if this still fails -- the current develeopment version. See https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs for more information.
