### ISSUE TITLE
SciPy <= 0.14.0 Importation Fails at Runtime

### ISSUE THREAD

**Issue by leycec** [pyinstaller/pyinstaller#1198]
SciPy versions older than 0.14.0 raise runtime exceptions on importation resembling:

    Traceback (most recent call last):
      File "/home/leycec/py/betse/betse/cli/cli.py", line 82, in run
        self._run()
      File "/home/leycec/py/betse/betse/cli/clicli.py", line 114, in _run
        subcommand_method()
      File "/home/leycec/py/betse/betse/cli/clicli.py", line 263, in _run_sim
        from betse.science.simrunner import SimRunner
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/home/leycec/py/betse/betse/science/simrunner.py", line 11, in <module>
        from betse.science import visualize as viz
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/home/leycec/py/betse/betse/science/visualize.py", line 14, in <module>
        from betse.science import toolbox as tb
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/home/leycec/py/betse/betse/science/toolbox.py", line 13, in <module>
        import scipy.spatial as sps
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/usr/lib64/python3.3/site-packages/scipy/spatial/__init__.py", line 87, in <module>
        from .kdtree import *
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/usr/lib64/python3.3/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
        import scipy.sparse
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/usr/lib64/python3.3/site-packages/scipy/sparse/__init__.py", line 182, in <module>
        from .csr import *
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/usr/lib64/python3.3/site-packages/scipy/sparse/csr.py", line 15, in <module>
        from .sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/usr/lib64/python3.3/site-packages/scipy/sparse/sparsetools/__init__.py", line 5, in <module>
        from .csr import *
      File "/usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py", line 302, in load_module
        exec(bytecode, module.__dict__)
      File "/usr/lib64/python3.3/site-packages/scipy/sparse/sparsetools/csr.py", line 26, in <module>
        _csr = swig_import_helper()
      File "/usr/lib64/python3.3/site-packages/scipy/sparse/sparsetools/csr.py", line 18, in swig_import_helper
        import _csr
    ImportError: No module named '_csr'    

As reported [here](https://bitbucket.org/anthony_tuininga/cx_freeze/issue/43/import-errors-when-using-cx_freeze-with) and [here](https://github.com/swig/swig/issues/145), this is a well-known, unresolved issue with SWIG. To quote [takluyver](https://github.com/takluyver) from the latter issues thread:

> SWIG autogenerates a `swig_import_helper()` Python function, which from what I can see, attempts to do relative imports in a way that remains valid syntax in Python 2.4. Unfortunately, the use of `__file__` doesn't work in frozen applications, and it falls back to `import %s (line)`, which doesn't work as a relative import in Python 3.

Since SciPy 0.14.0 appears to have dropped SWIG, this probably only applies to older SciPy versions – and every other library still using SWIG.

**Comment by matysek** [comment]
This should be fixed since related fixes were merged.
