### ISSUE TITLE
python3: "hooks/hook-IPython.py" Broken under IPython >= 2.3.1 (...and possibly older)

### ISSUE THREAD

**Issue by leycec** [pyinstaller/pyinstaller#1212]
The IPython hook is broken under newer versions of IPython – at least as recently as IPython 2.3.1 and possibly older. To demonstrate this, consider the single-line Python script consisting of only:

    import IPython

Attempting to freeze this script results in the following chain of exceptions:

    73 INFO: wrote /home/leycec/tmp/testem/ipython.spec
    80 INFO: UPX is available.
    82 INFO: Extending PYTHONPATH with /home/leycec/tmp/testem
    82 INFO: checking Analysis
    82 INFO: building Analysis because out00-Analysis.toc non existent
    82 INFO: Creating base_library.zip for Python 3
    2530 INFO: running Analysis out00-Analysis.toc
    2569 INFO: Analyzing ipython.py
    17167 INFO: Analyzing /usr/lib64/python3.3/site-packages/PyInstaller/loader/_pyi_bootstrap.py
    17189 INFO: Analyzing /usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_importers.py
    17197 INFO: Analyzing /usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_archive.py
    17203 INFO: Analyzing /usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_carchive.py
    17211 INFO: Analyzing /usr/lib64/python3.3/site-packages/PyInstaller/loader/pyi_os_path.py
    17214 INFO: Hidden import 'codecs' has been found otherwise
    17214 INFO: Hidden import 'encodings' has been found otherwise
    17214 INFO: Looking for import hooks ...
    17259 INFO: Processing hook   hook-encodings.py
    17682 INFO: Processing hook   hook-pydoc.py
    17690 INFO: Processing hook   hook-distutils.py
    17700 INFO: Processing hook   hook-xml.py
    17702 INFO: Processing hook   hook-site.py
    17708 INFO: Processing hook   hook-sysconfig.py
    17710 INFO: Processing hook   hook-IPython.py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib64/python3.3/site-packages/IPython/__init__.py", line 48, in <module>
        from .core.application import Application
      File "/usr/lib64/python3.3/site-packages/IPython/core/application.py", line 40, in <module>
        from IPython.core import release, crashhandler
      File "/usr/lib64/python3.3/site-packages/IPython/core/crashhandler.py", line 30, in <module>
        from IPython.utils.sysinfo import sys_info
      File "/usr/lib64/python3.3/site-packages/IPython/utils/sysinfo.py", line 101, in <module>
        @py3compat.doctest_refactor_print
      File "/usr/lib64/python3.3/site-packages/IPython/utils/py3compat.py", line 45, in wrapper
        doc = str_change_func(doc)
      File "/usr/lib64/python3.3/site-packages/IPython/utils/py3compat.py", line 126, in doctest_refactor_print
        return _print_statement_re.sub(_print_statement_sub, doc)
    TypeError: expected string or buffer
    Traceback (most recent call last):
      File "/usr/lib/python-exec/python3.3/pyinstaller", line 9, in <module>
        load_entry_point('PyInstaller===3.0dev-be553f0-mod', 'console_scripts', 'pyinstaller')()
      File "/usr/lib64/python3.3/site-packages/PyInstaller/main.py", line 88, in run
        run_build(opts, spec_file, pyi_config)
      File "/usr/lib64/python3.3/site-packages/PyInstaller/main.py", line 46, in run_build
        PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
      File "/usr/lib64/python3.3/site-packages/PyInstaller/build.py", line 1842, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
      File "/usr/lib64/python3.3/site-packages/PyInstaller/build.py", line 1789, in build
        exec(compile(open(spec).read(), spec, 'exec'))
      File "/home/leycec/tmp/testem/ipython.spec", line 6, in <module>
        runtime_hooks=None)
      File "/usr/lib64/python3.3/site-packages/PyInstaller/build.py", line 355, in __init__
        self.__postinit__()
      File "/usr/lib64/python3.3/site-packages/PyInstaller/build.py", line 215, in __postinit__
        self.assemble()
      File "/usr/lib64/python3.3/site-packages/PyInstaller/build.py", line 564, in assemble
        hook_name_space = mod_loader.load_module()
      File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
      File "<frozen importlib._bootstrap>", line 1022, in load_module
      File "<frozen importlib._bootstrap>", line 1003, in load_module
      File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
      File "<frozen importlib._bootstrap>", line 868, in _load_module
      File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
      File "/usr/lib64/python3.3/site-packages/PyInstaller/hooks/hook-IPython.py", line 16, in <module>
        datas = collect_data_files('IPython')
      File "/usr/lib64/python3.3/site-packages/PyInstaller/utils/hooks/hookutils.py", line 622, in collect_data_files
        pkg_base, pkg_dir = get_package_paths(package)
      File "/usr/lib64/python3.3/site-packages/PyInstaller/utils/hooks/hookutils.py", line 544, in get_package_paths
        assert is_package
    AssertionError

This is probably the most inscrutable exception chain I've ever received from PyInstaller. Fortunately, I'm fairly awesome. (Don't worry: you are too.) **So, I fixed it.** 

I'll submit a pull request shortly. Let's put this bug to the piebald sword of vengeance.

**Comment by leycec** [comment]
**Closed.** This issue appears to have committed ritual seppuku for me. (I am spitefully grateful.)

*Translation*: I can't reproduce this anymore under the current `python3` HEAD. Yay! :ok_woman:
