### ISSUE TITLE
Cannot install for Python 3.4.1

### ISSUE THREAD

**Issue by carlopires** [pyinstaller/pyinstaller#1219]
$ spip3 install pyinstaller
    Downloading/unpacking pyinstaller
      Downloading PyInstaller-2.1.tar.gz (4.8MB): 4.8MB downloaded
      Running setup.py (path:/tmp/pip_build_root/pyinstaller/setup.py) egg_info for package pyinstaller
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/tmp/pip_build_root/pyinstaller/setup.py", line 18, in <module>
            from PyInstaller import get_version
          File "/tmp/pip_build_root/pyinstaller/PyInstaller/__init__.py", line 32, in <module>
            from PyInstaller import compat
          File "/tmp/pip_build_root/pyinstaller/PyInstaller/compat.py", line 129
            if sys.maxint > 2L ** 32:
                             ^
        SyntaxError: invalid syntax
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
    
      File "<string>", line 17, in <module>
    
      File "/tmp/pip_build_root/pyinstaller/setup.py", line 18, in <module>
    
        from PyInstaller import get_version
    
      File "/tmp/pip_build_root/pyinstaller/PyInstaller/__init__.py", line 32, in <module>
    
        from PyInstaller import compat
    
      File "/tmp/pip_build_root/pyinstaller/PyInstaller/compat.py", line 129
    
        if sys.maxint > 2L ** 32:
    
                         ^
    
    SyntaxError: invalid syntax
    
    ----------------------------------------
    Cleaning up...

**Comment by htgoebel** [comment]
Hi Carlos,

PyInstaller does not yet support Python 3.

If you need Python 3, you may check out the experimental python3-branch
at github.

-- 
Schönen Gruß
Hartmut Goebel
Dipl.-Informatiker (univ), CISSP, CSSLP
Information Security Management, Security Governance, Secure Software
Development

Goebel Consult, Landshut
http://www.goebel-consult.de

Blog:
http://www.goebel-consult.de/blog/digitale-burgerrechte-in-der-ara-snowden
Kolumne: http://www.cissp-gefluester.de/2010-08-scheingefechte-um-rim
