### ISSUE TITLE
Support for unicode paths when building

### ISSUE THREAD

**Issue by m1lhaus** [pyinstaller/pyinstaller#1222]
Please, add full support for non-ascii paths. i.e. when pyinstaller is lauched from path with non-ascii character in it. It really drives me nuts :-/ Thanks

Example traceback from path 'D:\Programovaní\woofer-git\build':

```
20 INFO: Testing for ability to set icons, version resources...
26 INFO: ... resource update available
26 INFO: UPX is not available.
40 INFO: Processing hook hook-os
109 INFO: Processing hook hook-time
118 INFO: Processing hook hook-cPickle
161 INFO: Processing hook hook-_sre
238 INFO: Processing hook hook-cStringIO
300 INFO: Processing hook hook-encodings
310 INFO: Processing hook hook-codecs
572 INFO: Processing hook hook-httplib
574 INFO: Processing hook hook-email
643 INFO: Processing hook hook-email.message
789 WARNING: library python%s%s required via ctypes not found
875 INFO: Removing temporary files and cleaning cache in C:\Users\Milhaus\AppData\Roaming\pyinstaller
875 INFO: Extending PYTHONPATH with D:\Programovan�\woofer-git
875 INFO: checking Analysis
875 INFO: Building Analysis because out00-Analysis.toc non existent
875 INFO: running Analysis out00-Analysis.toc
875 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
962 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
962 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91.manifest
963 INFO: Searching for file msvcr90.dll
963 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcr90.dll
963 INFO: Searching for file msvcp90.dll
963 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcp90.dll
963 INFO: Searching for file msvcm90.dll
963 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcm90.dll
1023 INFO: Analyzing C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\loader\_pyi_bootstrap.py
1029 INFO: Processing hook hook-os
1039 INFO: Processing hook hook-site
1049 INFO: Processing hook hook-encodings
1112 INFO: Processing hook hook-time
1120 INFO: Processing hook hook-cPickle
1164 INFO: Processing hook hook-_sre
1243 INFO: Processing hook hook-cStringIO
1312 INFO: Processing hook hook-codecs
1572 INFO: Processing hook hook-httplib
1572 INFO: Processing hook hook-email
1644 INFO: Processing hook hook-email.message
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==2.1.1.dev0', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\build.py", line 1994, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\build.py", line 1940, in build
    execfile(spec)
  File "D:\Programovan�\woofer-git\build\windows.spec", line 4, in <module>
    pathex=['build'])
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\build.py", line 481, in __init__
    self.__postinit__()
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\build.py", line 320, in __postinit__
    self.assemble()
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\build.py", line 568, in assemble
    importTracker.analyze_script(script)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\imptracker.py", line 226, in analyze_script
    return self.analyze_r('__main__')
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\imptracker.py", line 119, in analyze_r
    newnms = self.analyze_one(name, nm, imptyp, level)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\imptracker.py", line 180, in analyze_one
    mod = self.doimport(nm, ctx, fqname)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\imptracker.py", line 252, in doimport
    mod = parent.doimport(nm)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\modules.py", line 127, in doimport
    mod = self.subimporter.getmod(nm)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\impdirector.py", line 140, in getmod
    mod = owner.getmod(nm)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\owner.py", line 127, in getmod
    mod = self._modclass()(nm, pth, co)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\modules.py", line 79, in __init__
    self.scancode()
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\modules.py", line 96, in scancode
    self.pyinstaller_binaries = _resolveCtypesImports(self.pyinstaller_binaries)
  File "C:\Python27\lib\site-packages\pyinstaller-2.1.1.dev0-py2.7.egg\PyInstaller\depend\utils.py", line 328, in _resolveCtypesImports
    cpath = find_library(os.path.splitext(cbin)[0])
  File "C:\Python27\lib\ctypes\util.py", line 54, in find_library
    fname = os.path.join(directory, name)
  File "C:\Python27\lib\ntpath.py", line 84, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)
```

**Comment by htgoebel** [comment]
Depending on the version you used (which you did not state), this may be fixed meanwhile. Can you please test the current development version.

**Comment by m1lhaus** [comment]
Same issue even with latest dev version. Same error.

**Comment by codewarrior0** [comment]
If it helps, the convention for python2 and python3 is to always handle filename/pathname data as `unicode`. All of python's filesystem functions accept `unicode` and will implicitly encode using the correct encoding.

Furthermore, `sys.getfilesystemencoding` *cannot* be trusted. On Windows, it encodes as a legacy codepage which can't encode most code points. On top of that, when you pass `bytes` to the filesystem functions on Windows, it invokes the legacy ANSI APIs which only expect a legacy codepage encoding - if you want to invoke the modern UTF-16 APIs, you need to always pass `unicode` to the filesystem functions.

**Comment by codewarrior0** [comment]
The first thing to do is add a unit test where the source file and build dir have a non-ASCII path.

**Comment by AndCycle** [comment]
there is also test need to be done for non-ASCII data filename under win32,

one is when add data from specs by glob syntax for folder it will fail,
I can take care of this by walk file by myself,

the other is
I hit this line in bootloader while I  bundle data file with Chinese filename under win32 then try to execute it,

bootloader/src/pyi_archive.c 
```
FATALERROR("%s could not be extracted!\n", ptoc->name);
```

**Comment by matysek** [comment]
@codewarrior0 is this issue still relevant or is it better captured in referenced issues #1422 and #1604?

**Comment by codewarrior0** [comment]
I think it's still relevant. Those issues are just aspects of the overall fix, which is to change all filenames to `unicode` type for Python 2.

**Comment by Legorooj** [comment]
Now supported (With a few bugs, but works 90% of the time)
