### ISSUE TITLE
'mbcs' codec error while executing pyinstaller generated exe

### ISSUE THREAD

**Issue by Ramkg** [pyinstaller/pyinstaller#1245]
Hi,
This is with respect to importing a pymsgbox module in py scripts. I'm using Python 3.4.3 for Windows 7- 32 bit version and a corresponding pyinstaller to generate the exe file for the same. This is working pretty fine when i try to generate exe for normal .py files. The exe executes to successful completion.
However, i face issues when i try to execute the exe for py files that import pymsgbox modules. Consider the below snippet:
```
import pymsgbox
pymsgbox.alert('Hello','Alert Box')
```
The above snippet executes nicely as a stand alone .py file from IDLE. However, when i create an exe (from pyinstaller) for this file and execute it, i get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\ramkumarg\Downloads\pyinstaller-python3(1)\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", li
ne 302, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python34\lib\site-packages\pymsgbox-1.0.0-py3.4.egg\pymsgbox\__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\ramkumarg\Downloads\pyinstaller-python3(1)\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", li
ne 302, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\ramkumarg\Downloads\Caution\Pynistaller\pyinstaller-python3\tkinter\__init__.py", line 38, in <module>
    from _tkinter import *
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\ramkumarg\Downloads\pyinstaller-python3(1)\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", li
ne 472, in load_module
    module = loader.load_module(fullname)
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character
```
As per, @leycec 's suggestion in issue #1164, i have implemented the patch suggested by @codewarrior0 . It still returns the same error.
Could someone please let me know what is it that i am doing wrongly here?
P.S: The path in which i have the script for execution does not contain any strange characters to cause the unicode issue. Even if that is the probable cause, this should occur for all exes that i generate, but not.

**Comment by leycec** [comment]
I neglected to mention that you'll also need to recompile PyInstaller's Windows 32 bootloaders. Sorry about that.

Unfortunately, recompiling *anything* under Windows is always a dicey proposition. Fortunately, the PyInstaller wiki has [detailed instructions](https://github.com/pyinstaller/pyinstaller/wiki/Build-Bootloader-Win64) for doing so. Unfortunately, the instructions are specific to 64-bit Windows.

If you *do* manage to successfully recompile Windows 32 bootloaders, it'd be great if you could submit a pull request containing all modified files in the `PyInstaller/bootloader/Windows-32bit/` directory. (No worries if you don't have time, of course.)

**Comment by matysek** [comment]
I tested the code example and recompiling windows bootloaders with Py_SetProgramName patch fixes that.
