### ISSUE TITLE
PyInstaller Unusable under Windows Anaconda

### ISSUE THREAD

**Issue by leycec** [pyinstaller/pyinstaller#1247]
[Anaconda](http://continuum.io/downloads) is arguably the most popular Python distribution for Windows. Naturally, Anaconda installs PyWin32 DLLs to non-standard directories resulting in the following exception on PyInstaller startup:

    PyInstaller cannot check for assembly dependencies.
    Please install PyWin32.
    http://sourceforge.net/projects/pywin32/

**The exception message is flat-out wrong.** PyWin32 *is* installed; it simply can't find a dependent DLL. To show this, locally edit the PyWin32 test in PyInstaller's `PyInstaller/__init__.py` file as follows:

    # Fail hard if Python on Windows does not have pywin32 installed.
    if is_win:
        import pywintypes  # One module from pywin32.

This results in the following exception on PyInstaller startup:

    Traceback (most recent call last):
      File "C:\Miniconda3\Scripts\pyinstaller-script.py", line 9, in <module>
        load_entry_point('PyInstaller==3.0.dev0', 'console_scripts', 'pyinstaller')()
      File "C:\Miniconda3\lib\site-packages\setuptools-15.1-py3.4.egg\pkg_resources\__init__.py", line 546, in load_entry_point
      File "C:\Miniconda3\lib\site-packages\setuptools-15.1-py3.4.egg\pkg_resources\__init__.py", line 2666, in load_entry_point
      File "C:\Miniconda3\lib\site-packages\setuptools-15.1-py3.4.egg\pkg_resources\__init__.py", line 2339, in load
      File "C:\Miniconda3\lib\site-packages\setuptools-15.1-py3.4.egg\pkg_resources\__init__.py", line 2345, in resolve
      File "C:\Miniconda3\lib\site-packages\pyinstaller-3.0.dev0-py3.4.egg\PyInstaller\__init__.py", line 36, in <module>
        import pywintypes  # One module from pywin32.
      File "C:\Miniconda3\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
        __import_pywin32_system_module__("pywintypes", globals())
      File "C:\Miniconda3\lib\site-packages\win32\lib\pywintypes.py", line 98, in __import_pywin32_system_module__
        raise ImportError("No system module '%s' (%s)" % (modname, filename))
    ImportError: No system module 'pywintypes' (pywintypes34.dll)

Now *that's* better. This is a [well-known](https://stackoverflow.com/questions/19280894/py2exe-no-system-module-pywintypes) and [currently unresolved issue](https://github.com/ContinuumIO/anaconda-issues/issues/3) in Anaconda's `pywin32` recipe. There's even a [year-old thread](http://comments.gmane.org/gmane.comp.python.pyinstaller/6693) on the PyInstaller mailing list about this.

The usual recommendation is for the end user to manually copy DLLs from one directory to another. While this *does* make the problem go away in the short-term, it also invites long-term issues that are probably worse – including [DLL hell](https://en.wikipedia.org/wiki/DLL_Hell)-style desynchronization between old and new DLLs on automatic updates to PyWin32. Moreover, the end user shouldn't have to do *anything* manually. PyInstaller should just work out of the box, even if Anaconda's `pywin32` recipe is horribly broken.

Can we do this? **Yes,** and my latest pull request demonstrates how.

**Comment by htgoebel** [comment]
@leycec 
> Can we do this? Yes, and my latest pull request demonstrates how.

Which pull-request you are referring to?

**Comment by leycec** [comment]
I knew you'd catch me with my Github pants down. It's up now.

**Comment by htgoebel** [comment]
#1249 fixing this issue is merged.
