### ISSUE TITLE
Import PIL._imaging fails

### ISSUE THREAD

**Issue by philipgoh** [pyinstaller/pyinstaller#1248]
I'm having trouble packaging up an executable on my development VM.

Some details:

  * Ubuntu 14.04.2 32 bit
  * Python 2.7.6
  * PyInstaller 2.1

The following is a simple Python program that illustrates the problem. The script runs fine if I run it via the Python interpreter, but it fails when packaged up with PyInstaller. 

```
from PIL import Image
import gtk.gdk


def screen_grab_gtk(file_name, quality=70):
    w = gtk.gdk.get_default_root_window()
    sz = w.get_size()
    pb = gtk.gdk.Pixbuf(gtk.gdk.COLORSPACE_RGB, False, 8, sz[0], sz[1])
    pb = pb.get_from_drawable(w, w.get_colormap(), 0, 0, 0, 0, sz[0], sz[1])
    if pb is None:
        return None
    else:
        width, height = pb.get_width(), pb.get_height()
        i = Image.frombytes("RGB", (width, height), pb.get_pixels())
        i.save(file_name, "JPEG", quality=quality)


if __name__ == "__main__":
    screen_grab_gtk("test.jpg")

```

I package it up in PyInstaller using the command `pyinstaller test_gtk.py --onedir --noupx`. In the build directory, I get a file with lots of warnings about "no module named:...". The contents are attached below.

```
W: no module named glib.markup_escape_text (top-level import by gobject)
W: no module named glib.OptionGroup (top-level import by gobject)
W: no module named nt (conditional import by pyi_os_path)
W: no module named nt (conditional import by __main__)
W: no module named glib.idle_add (top-level import by gobject)
W: no module named glib.OPTION_FLAG_NOALIAS (top-level import by gobject)
W: no module named gtkglext (top-level import by gtk)
W: no module named glib.Source (top-level import by gobject)
W: no module named msvcrt (conditional import by getpass)
W: no module named glib.filename_display_name (top-level import by gobject)
W: no module named glib.MainContext (top-level import by gobject)
W: no module named glib.IO_STATUS_NORMAL (top-level import by gobject)
W: no module named glib.IO_STATUS_ERROR (top-level import by gobject)
W: no module named glib.SPAWN_LEAVE_DESCRIPTORS_OPEN (top-level import by gobject)
W: no module named gdk (top-level import by gtk)
W: no module named glib.SPAWN_DO_NOT_REAP_CHILD (top-level import by gobject)
W: no module named glib.get_current_time (top-level import by gobject)
W: no module named glib.Idle (top-level import by gobject)
W: no module named gtk.gtkgl (top-level import by gtk)
W: no module named ICCProfile (delayed, conditional import by PIL.PngImagePlugin)
W: no module named rourl2path (conditional import by urllib)
W: no module named glib.OPTION_ERROR_UNKNOWN_OPTION (top-level import by gobject)
W: no module named _winreg (delayed import by urllib)
W: no module named _subprocess (conditional import by subprocess)
W: no module named _dummy_threading (top-level import by dummy_threading)
W: no module named glib.SPAWN_STDOUT_TO_DEV_NULL (top-level import by gobject)
W: no module named glib.uri_list_extract_uris (top-level import by gobject)
W: no module named glib.IO_OUT (top-level import by gobject)
W: no module named glib.set_application_name (top-level import by gobject)
W: no module named glib.OPTION_FLAG_OPTIONAL_ARG (top-level import by gobject)
W: no module named gtk.glade (top-level import by gtk)
W: no module named glib.timeout_add_seconds (top-level import by gobject)
W: no module named glib.PollFD (top-level import by gobject)
W: no module named org (top-level import by copy)
W: no module named gtk.gdk (top-level import by __main__)
W: no module named glib.SPAWN_STDERR_TO_DEV_NULL (top-level import by gobject)
W: no module named msvcrt (delayed import by getpass)
W: no module named glib.spawn_async (top-level import by gobject)
W: no module named glib.IO_FLAG_SET_MASK (top-level import by gobject)
W: no module named gtkgl (top-level import by gtk)
W: no module named glib.IO_FLAG_APPEND (top-level import by gobject)
W: no module named glib.Timeout (top-level import by gobject)
W: no module named glib.source_remove (top-level import by gobject)
W: no module named glib.OPTION_REMAINING (top-level import by gobject)
W: no module named gdkglext (top-level import by gtk)
W: no module named glib.IO_FLAG_GET_MASK (top-level import by gobject)
W: no module named glib.Pid (top-level import by gobject)
W: no module named glib.IO_IN (top-level import by gobject)
W: no module named glib.IO_STATUS_AGAIN (top-level import by gobject)
W: no module named glib.OPTION_ERROR (top-level import by gobject)
W: no module named glib.IO_FLAG_IS_WRITEABLE (top-level import by gobject)
W: no module named nt (top-level import by ntpath)
W: no module named glib.glib_version (top-level import by gobject)
W: no module named glib.SPAWN_FILE_AND_ARGV_ZERO (top-level import by gobject)
W: no module named cl (delayed, conditional import by aifc)
W: no module named glib.IOChannel (top-level import by gobject)
W: no module named glib.filename_display_basename (top-level import by gobject)
W: no module named PIL.VERSION (top-level import by PIL.Image)
W: no module named PIL.PILLOW_VERSION (top-level import by PIL.Image)
W: no module named glib.OPTION_FLAG_REVERSE (top-level import by gobject)
W: no module named glib.OPTION_FLAG_NO_ARG (top-level import by gobject)
W: no module named glib.OPTION_FLAG_FILENAME (top-level import by gobject)
W: no module named glib.get_application_name (top-level import by gobject)
W: no module named EasyDialogs (conditional import by getpass)
W: no module named glib.io_add_watch (top-level import by gobject)
W: no module named glib.IO_STATUS_EOF (top-level import by gobject)
W: no module named glib.IO_FLAG_IS_READABLE (top-level import by gobject)
W: no module named glib.IO_PRI (top-level import by gobject)
W: no module named glib.OPTION_ERROR_FAILED (top-level import by gobject)
W: no module named glib.IO_ERR (top-level import by gobject)
W: no module named glib.OptionContext (top-level import by gobject)
W: no module named glib.IO_FLAG_NONBLOCK (top-level import by gobject)
W: no module named gtk.gdk (top-level import by gtk)
W: no module named glib.filename_from_utf8 (top-level import by gobject)
W: no module named glib.set_prgname (top-level import by gobject)
W: no module named glib.IO_FLAG_MASK (top-level import by gobject)
W: no module named glib.SPAWN_SEARCH_PATH (top-level import by gobject)
W: no module named glib.PRIORITY_DEFAULT_IDLE (top-level import by gobject)
W: no module named glib.GError (top-level import by gobject)
W: no module named glib.SPAWN_CHILD_INHERITS_STDIN (top-level import by gobject)
W: no module named glib.timeout_add (top-level import by gobject)
W: no module named glib.IO_FLAG_IS_SEEKABLE (top-level import by gobject)
W: no module named builtins (top-level import by PIL.Image)
W: no module named org (top-level import by pickle)
W: no module named glib.PRIORITY_LOW (top-level import by gobject)
W: no module named glib.get_prgname (top-level import by gobject)
W: no module named glib.main_depth (top-level import by gobject)
W: no module named glib.OPTION_ERROR_BAD_VALUE (top-level import by gobject)
W: no module named _scproxy (conditional import by urllib)
W: no module named glib.PRIORITY_DEFAULT (top-level import by gobject)
W: no module named glib.main_context_default (top-level import by gobject)
W: no module named _imaging_gif (top-level import by PIL.GifImagePlugin)
W: no module named msvcrt (conditional import by subprocess)
W: no module named gobject.GObjectMeta (top-level import by gio)
W: no module named glib.IO_NVAL (top-level import by gobject)
W: no module named glib.OPTION_FLAG_HIDDEN (top-level import by gobject)
W: no module named glib.PRIORITY_HIGH_IDLE (top-level import by gobject)
W: no module named cl (delayed import by aifc)
W: no module named glib.child_watch_add (top-level import by gobject)
W: no module named glib.IO_HUP (top-level import by gobject)
W: no module named _emx_link (conditional import by os)
W: no module named _winreg (top-level import by mimetypes)
W: no module named glib.OPTION_FLAG_IN_MAIN (top-level import by gobject)
W: no module named glib.MainLoop (top-level import by gobject)
W: no module named SOCKS (top-level import by ftplib)
W: no module named gdkgl (top-level import by gtk)
W: no module named PIL._plugins (top-level import by PIL.Image)
W: no module named glib.PRIORITY_HIGH (top-level import by gobject)
W: delayed conditional __import__ hack detected at line 0 - pyi_archive (/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_archive.pyc)
W: __all__ is built strangely at line 0 - dummy_threading (/usr/lib/python2.7/dummy_threading.pyc)
W: delayed  exec statement detected at line 0 - bdb (/usr/lib/python2.7/bdb.pyc)
W: delayed  eval hack detected at line 0 - bdb (/usr/lib/python2.7/bdb.pyc)
W: delayed  eval hack detected at line 0 - bdb (/usr/lib/python2.7/bdb.pyc)
W: delayed  __import__ hack detected at line 0 - optparse (/usr/lib/python2.7/optparse.pyc)
W: delayed  __import__ hack detected at line 0 - PIL.Image (/usr/lib/python2.7/dist-packages/PIL/Image.pyc)
W: delayed conditional __import__ hack detected at line 0 - doctest (/usr/lib/python2.7/doctest.pyc)
W: delayed  exec statement detected at line 0 - doctest (/usr/lib/python2.7/doctest.pyc)
W: delayed conditional __import__ hack detected at line 0 - doctest (/usr/lib/python2.7/doctest.pyc)
W: __all__ is built strangely at line 0 - tokenize (/usr/lib/python2.7/tokenize.pyc)
W: __all__ is built strangely at line 0 - tokenize (/usr/lib/python2.7/tokenize.pyc)
W: delayed  __import__ hack detected at line 0 - pickle (/usr/lib/python2.7/pickle.pyc)
W: delayed  __import__ hack detected at line 0 - pickle (/usr/lib/python2.7/pickle.pyc)
W: delayed  __import__ hack detected at line 0 - encodings (/usr/lib/python2.7/encodings/__init__.pyc)
W: delayed  __import__ hack detected at line 0 - pydoc (/usr/lib/python2.7/pydoc.pyc)
W: delayed  __import__ hack detected at line 0 - pydoc (/usr/lib/python2.7/pydoc.pyc)
W: __all__ is built strangely at line 0 - dis (/usr/lib/python2.7/dis.pyc)
W: __all__ is built strangely at line 0 - hashlib (/usr/lib/python2.7/hashlib.pyc)
W: delayed conditional eval hack detected at line 0 - warnings (/usr/lib/python2.7/warnings.pyc)
W: delayed conditional __import__ hack detected at line 0 - warnings (/usr/lib/python2.7/warnings.pyc)
W: delayed conditional exec statement detected at line 0 - pyi_importers (/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.pyc)
W: delayed conditional __import__ hack detected at line 0 - gtk.deprecation (/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/deprecation.pyc)
W: delayed  __import__ hack detected at line 0 - email (/usr/lib/python2.7/email/__init__.pyc)
W: delayed  exec statement detected at line 0 - pdb (/usr/lib/python2.7/pdb.pyc)
W: delayed conditional eval hack detected at line 0 - pdb (/usr/lib/python2.7/pdb.pyc)
W: delayed  eval hack detected at line 0 - pdb (/usr/lib/python2.7/pdb.pyc)
W: delayed conditional eval hack detected at line 0 - pdb (/usr/lib/python2.7/pdb.pyc)
W: delayed  eval hack detected at line 0 - pdb (/usr/lib/python2.7/pdb.pyc)
W: delayed  __import__ hack detected at line 0 - pkgutil (/usr/lib/python2.7/pkgutil.pyc)
W: delayed conditional __import__ hack detected at line 0 - pkgutil (/usr/lib/python2.7/pkgutil.pyc)
W: __all__ is built strangely at line 0 - collections (/usr/lib/python2.7/collections.pyc)
W: delayed  exec statement detected at line 0 - collections (/usr/lib/python2.7/collections.pyc)
W: delayed conditional __import__ hack detected at line 0 - unittest.main (/usr/lib/python2.7/unittest/main.pyc)
W: delayed  __import__ hack detected at line 0 - gtk._lazyutils (/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_lazyutils.pyc)
W: delayed conditional __import__ hack detected at line 0 - gtk._lazyutils (/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_lazyutils.pyc)
W: delayed conditional __import__ hack detected at line 0 - unittest.loader (/usr/lib/python2.7/unittest/loader.pyc)
W: delayed conditional __import__ hack detected at line 0 - unittest.loader (/usr/lib/python2.7/unittest/loader.pyc)
W: delayed  __import__ hack detected at line 0 - unittest.loader (/usr/lib/python2.7/unittest/loader.pyc)
W: __all__ is built strangely at line 0 - __future__ (/usr/lib/python2.7/__future__.pyc)
W: delayed  eval hack detected at line 0 - gettext (/usr/lib/python2.7/gettext.pyc)
```

The output of the pyinstaller command:
```
5 INFO: wrote /mnt/hgfs/silverstar/Tools/Development Machine/test_gtk.spec
21 INFO: UPX is available.
34 INFO: Processing hook hook-os
94 INFO: Processing hook hook-time
95 INFO: Processing hook hook-cPickle
141 INFO: Processing hook hook-_sre
212 INFO: Processing hook hook-cStringIO
265 INFO: Processing hook hook-encodings
272 INFO: Processing hook hook-codecs
535 INFO: Extending PYTHONPATH with /mnt/hgfs/silverstar/Tools/Development Machine
535 INFO: checking Analysis
535 INFO: building Analysis because out00-Analysis.toc non existent
536 INFO: running Analysis out00-Analysis.toc
556 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/_pyi_bootstrap.py
565 INFO: Processing hook hook-os
576 INFO: Processing hook hook-site
587 INFO: Processing hook hook-encodings
681 INFO: Processing hook hook-time
683 INFO: Processing hook hook-cPickle
749 INFO: Processing hook hook-_sre
859 INFO: Processing hook hook-cStringIO
943 INFO: Processing hook hook-codecs
1312 INFO: Processing hook hook-pydoc
1443 INFO: Processing hook hook-email
1493 INFO: Processing hook hook-httplib
1517 INFO: Processing hook hook-email.message
1573 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py
1631 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_archive.py
1683 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_carchive.py
1735 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_os_path.py
1742 INFO: Analyzing test_gtk.py
1745 INFO: Processing hook hook-PIL
1758 INFO: Processing hook hook-PIL.Image
1910 INFO: Processing hook hook-gtk
2085 INFO: Hidden import 'codecs' has been found otherwise
2085 INFO: Hidden import 'encodings' has been found otherwise
2085 INFO: Looking for run-time hooks
2086 INFO: Analyzing rthook /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/rthooks/pyi_rth_PIL_Image.py
objdump: section '.dynamic' mentioned in a -j option, but not found in any input file
2771 INFO: Using Python library /usr/lib/i386-linux-gnu/libpython2.7.so.1.0
2771 INFO: Adding Python library to binary dependencies
3308 INFO: Warnings written to /mnt/hgfs/silverstar/Tools/Development Machine/build/test_gtk/warntest_gtk.txt
3313 INFO: checking PYZ
3314 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
3314 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
3914 INFO: checking PKG
3914 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
3914 INFO: building PKG (CArchive) out00-PKG.pkg
objdump: section '.dynamic' mentioned in a -j option, but not found in any input file
3974 INFO: checking EXE
3975 INFO: rebuilding out00-EXE.toc because test_gtk missing
3975 INFO: building EXE from out00-EXE.toc
3976 INFO: Appending archive to EXE /mnt/hgfs/silverstar/Tools/Development Machine/build/test_gtk/test_gtk
4005 INFO: checking COLLECT
4005 INFO: building COLLECT out00-COLLECT.toc
```

PyInstaller has successfully created a `dist` folder that seems to contain the necessary packages. Note `PIL._imaging`:
![screen shot 2015-04-27 at 16 14 16](https://cloud.githubusercontent.com/assets/70234/7350693/a4fb32de-ecf8-11e4-8a65-55c2e4a62fc0.png)

However, I get the following error when running the generated executable.
```
Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/mnt/hgfs/silverstar/Tools/Development Machine/build/test_gtk/out00-PYZ.pyz/PIL.PngImagePlugin", line 40, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/mnt/hgfs/silverstar/Tools/Development Machine/build/test_gtk/out00-PYZ.pyz/PIL.Image", line 53, in <module>
ImportError: cannot import name _imaging
```
 
Any help in understanding and resolving this issue is much appreciated.

**Comment by htgoebel** [comment]
Please try the latest development version.

**Comment by philipgoh** [comment]
The latest development version works!

I guess this bug is fixed in the next version of PyInstaller.
