### ISSUE TITLE
Issue with the Drobpox module and Python 2.7

### ISSUE THREAD

**Issue by AugustoEst** [pyinstaller/pyinstaller#1262]
I'm having an issue running a **.exe** of python script that uses the **Dropbox module**. This happens in both *onedir* and *onefile*, and with or without the *UPX packaging*.

The error I obtain when I run the **.exe** is:

    Traceback (most recent call last):
      File "<string>", line 45, in <module>
      File "<string>", line 36, in main
      File "D:\Dropbox\Python\New features\build\send_to_touchcloud\out00-PYZ.pyz\dropbox_link", line 16, in get_file_path
      File "D:\Dropbox\Python\New features\build\send_to_touchcloud\out00-PYZ.pyz\dropbox.client", line 1142, in share
      File "D:\Dropbox\Python\New features\build\send_to_touchcloud\out00-PYZ.pyz\dropbox.rest", line 311, in GET
      File "D:\Dropbox\Python\New features\build\send_to_touchcloud\out00-PYZ.pyz\dropbox.rest", line 246, in GET
      File "D:\Dropbox\Python\New features\build\send_to_touchcloud\out00-PYZ.pyz\dropbox.rest", line 224, in request
        dropbox.rest.RESTSocketError: Error connecting to 
        "https://api.dropbox.com/1/shares/dropbox/20150222025718.png?oauth_nonce=...": 
        SSL certificate error: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate
        routines:X509_load_cert_crl_file:system lib

*I've hidden some sensitive information in the error message*

[Edit htgoebel: Break long lines to make trace back more readable]

**Comment by htgoebel** [comment]
Obviously some SSL certificate is missing. Please [Make sure everything is packaged correctly)[https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly].

**Comment by AugustoEst** [comment]
Yes, obviously. Now regarding some help creating an exe that includes SSL certificates...
