### ISSUE TITLE
Installation via pip on Manjaro Linux failing

### ISSUE THREAD

**Issue by zauberparacelsus** [pyinstaller/pyinstaller#1278]
When I try to install pyinstaller on Arch Linux, I get a build failure:

```
[zauber@manjaro ~]$ pip install pyinstaller
Collecting pyinstaller
  Downloading PyInstaller-2.1.tar.gz (4.8MB)
    100% |████████████████████████████████| 4.8MB 110kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-tb8wwgte/pyinstaller/setup.py", line 18, in <module>
        from PyInstaller import get_version
      File "/tmp/pip-build-tb8wwgte/pyinstaller/PyInstaller/__init__.py", line 32, in <module>
        from PyInstaller import compat
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tb8wwgte/pyinstaller

```

**Comment by htgoebel** [comment]
Which version of pip you are using? Is this from Arch Linux or directly from PyPi resp. get-pip.py?  Are you running in a virtual environment?

**Comment by zauberparacelsus** [comment]
This is the pip that Arch Linux has packaged.  And considering how bleeding-edge Arch Linux is, you can safely assume that its version is whichever is the latest.

**Comment by htgoebel** [comment]
And which version is it? (Do you really expect me to recherche this while you are sitting in front of a resp. system?)

**Comment by robertbasic** [comment]
I get the same error on Fedora.

```
(env)robert@odin ~/pugdebug[master*]$ python --version
Python 3.4.1
(env)robert@odin ~/pugdebug[master*]$ pip --version
pip 7.0.1 from /home/robert/pugdebug/env/lib/python3.4/site-packages (python 3.4)
(env)robert@odin ~/pugdebug[master*]$ which pip
~/pugdebug/env/bin/pip
(env)robert@odin ~/pugdebug[master*]$ pip install pyinstaller
Collecting pyinstaller
  Using cached PyInstaller-2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-yk7dkgcq/pyinstaller/setup.py", line 18, in <module>
        from PyInstaller import get_version
      File "/tmp/pip-build-yk7dkgcq/pyinstaller/PyInstaller/__init__.py", line 32, in <module>
        from PyInstaller import compat
      File "/tmp/pip-build-yk7dkgcq/pyinstaller/PyInstaller/compat.py", line 129
        if sys.maxint > 2L ** 32:
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yk7dkgcq/pyinstaller
```

Let me know if I need to provide any more information.

**Comment by robertbasic** [comment]
FWIW pyinstaller installed OK under a 2.7 python venv.

**Comment by robertbasic** [comment]
Got it working with the `python3` branch

```
(env)robert@odin ~/pugdebug[master*]$ pyinstaller --version
3.0dev
```

**Comment by htgoebel** [comment]
@zauberparacelsus Are you sure, your traceback is complete? (I've seen just now, that the actual error is missing.)

**Comment by zauberparacelsus** [comment]
@htgoebel That was the entirity of the command line output.

On another note, I just retried, and I found that although installation fails under the Python3 version of pip, it installs just fine with the Python2 version of pip.

And the version of pip I'm using is 6.1.1.  Today I'm getting a prompt to update to 7.0.1 that I wasn't getting previously.  I just upgraded pip and then tried installing pyinstaller again, and I am now getting the same error output as Robert:

```
[zauber@manjaro ~]$ sudo pip install pyinstaller
Collecting pyinstaller
  Using cached PyInstaller-2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-rduz6m7f/pyinstaller/setup.py", line 18, in <module>
        from PyInstaller import get_version
      File "/tmp/pip-build-rduz6m7f/pyinstaller/PyInstaller/__init__.py", line 32, in <module>
        from PyInstaller import compat
      File "/tmp/pip-build-rduz6m7f/pyinstaller/PyInstaller/compat.py", line 129
        if sys.maxint > 2L ** 32:
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rduz6m7f/pyinstaller
```

**Comment by robertbasic** [comment]
@zauberparacelsus install it from the python3 branch, it works nicely for me under both Fedora and Linux. Trying to bring up a hackintosh now to test it under osx as well :)

**Comment by zauberparacelsus** [comment]
@robertbasic Um... it's the Python3 version that will not install for me.

**Comment by robertbasic** [comment]
Yea, but actually check out the python3 branch of the pyinstaller https://github.com/pyinstaller/pyinstaller/tree/python3

**Comment by htgoebel** [comment]
So your Linux`s default python is Python 3.x and you are installing PyInstaller from PyPI, which is documented to work with Python 2.x only. See the wiki and the PyPI-entry.
