### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by seanthegeek** [pyinstaller/pyinstaller#1293]
Mac OS 10.10, Macports, pip 7.0.1 

Collecting pyinstaller
  Downloading PyInstaller-2.1.tar.gz (4.8MB)
    100% |████████████████████████████████| 4.8MB 112kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-dx_ka20_/pyinstaller/setup.py", line 18, in <module>
        from PyInstaller import get_version
      File "/private/tmp/pip-build-dx_ka20_/pyinstaller/PyInstaller/__init__.py", line 32, in <module>
        from PyInstaller import compat
      File "/private/tmp/pip-build-dx_ka20_/pyinstaller/PyInstaller/compat.py", line 129
        if sys.maxint > 2L ** 32:
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-dx_ka20_/pyinstaller

**Comment by htgoebel** [comment]
Python 2.1 only supports Python p to 2.7.
