### ISSUE TITLE
ImportError: No module named _core_

### ISSUE THREAD

**Issue by siliconplains44** [pyinstaller/pyinstaller#1303]
This error occurs when I am running the main.exe application after a pyinstaller build.

I am using pyinstaller 2.1 stable.  

I am using python 2.7.6 on Ubuntu Linux 14.04 lts.

I think the wxcore error is wxpython.  I am not quite sure.  It appears the exe is not finding wxpython.

This problem is not happening on windows or mac os x

Example program

Just create a program that depends on wxpython 3.0.2.0.  import wx, create a main frame and it won't work.

I did not try to implement a hook.  I am not familiar with the concept.  

./main.exe
```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/allan/projects/toolg/toolwxpy/build/main/out00-PYZ.pyz/application.appwindowed", line 6, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/allan/projects/toolg/toolwxpy/build/main/out00-PYZ.pyz/wx", line 45, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/allan/projects/toolg/toolwxpy/build/main/out00-PYZ.pyz/wx._core", line 4, in <module>
ImportError: No module named _core_
```

**Comment by htgoebel** [comment]
> I am using pyinstaller 2.1 stable.

Please try latest development version.

> Example program

Please provide a minimal working one. Esp. one "that depends on wxpython 3.0.2.0" (how should this be achieved?)

**Comment by siliconplains44** [comment]
The development version I pulled from git worked!  Thanks for the heads up.
