### ISSUE TITLE
Python3: Cygwin Python library not found

### ISSUE THREAD

**Issue by rickfoosusa** [pyinstaller/pyinstaller#1307]
Installed with easy_install-3.4
 pyinstaller  -D -i icon.ico -w --uac-admin Installer.py
```
14046 INFO: Analyzing run-time hooks ...
14064 INFO: Looking for dynamic libraries
16142 INFO: Looking for eggs - TODO
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller===3.0dev-e944769', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3.4/site-packages/PyInstaller-3.0dev_e944769-py3.4.egg/PyInstaller/main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "/usr/lib/python3.4/site-packages/PyInstaller-3.0dev_e944769-py3.4.egg/PyInstaller/main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/usr/lib/python3.4/site-packages/PyInstaller-3.0dev_e944769-py3.4.egg/PyInstaller/build.py", line 2127, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3.4/site-packages/PyInstaller-3.0dev_e944769-py3.4.egg/PyInstaller/build.py", line 2071, in build
    exec(compile(open(spec).read(), spec, 'exec'))
  File "/home/jenkins-slave/jenkins/jenkins/workspace/Firmware_ftdi_SWD-DP/ftdi_SWD-DP/Installer/AMagdiInstaller.spec", line 12, in <module>
    cipher=block_cipher)
  File "/usr/lib/python3.4/site-packages/PyInstaller-3.0dev_e944769-py3.4.egg/PyInstaller/build.py", line 406, in __init__
    self.__postinit__()
  File "/usr/lib/python3.4/site-packages/PyInstaller-3.0dev_e944769-py3.4.egg/PyInstaller/build.py", line 242, in __postinit__
    self.assemble()
  File "/usr/lib/python3.4/site-packages/PyInstaller-3.0dev_e944769-py3.4.egg/PyInstaller/build.py", line 788, in assemble
    self._check_python_library(self.binaries)
  File "/usr/lib/python3.4/site-packages/PyInstaller-3.0dev_e944769-py3.4.egg/PyInstaller/build.py", line 854, in _check_python_library
    raise IOError(msg)
OSError: Python library not found! This usually happens on Debian/Ubuntu
where you need to install Python library:

  apt-get install libpythonX.Y
```

**Comment by htgoebel** [comment]
For cygwin, PyInstaller expects to find `libpython34.dll` and is searching in the PE file of sys.executable. Please help us fixing by debugging/tracing `PyInstaller.depend.bindepend._getImports_pe`. Thanks

**Comment by ThomasWaldmann** [comment]
+1 Just had the same issue on cygwin.

**Comment by juanitogan** [comment]
Same problem.  In my cygwin install the file is called `libpython3.4m.dll` and not `libpython34.dll`.

**Comment by pstrzelczak** [comment]
I have the same issue:

```
$ pyinstaller sample.py 
46 INFO: PyInstaller: 3.1.1
46 INFO: Python: 2.7.10
62 INFO: Platform: CYGWIN_NT-6.0-2.3.1-0.291-5-3-x86_64-64bit
62 INFO: wrote /home/Administrator/pyinstaller-trial/sample.spec
78 INFO: UPX is not available.
78 INFO: Extending PYTHONPATH with paths
['/home/Administrator/pyinstaller-trial',
 '/home/Administrator/pyinstaller-trial']
78 INFO: checking Analysis
78 INFO: Building Analysis because out00-Analysis.toc is non existent
78 INFO: Initializing module dependency graph...
93 INFO: Initializing module graph hooks...
125 INFO: running Analysis out00-Analysis.toc
296 INFO: Analyzing /home/Administrator/pyinstaller-trial/sample.py
1297 INFO: Looking for import hooks ...
1297 INFO: Processing hook   hook-encodings.py
1859 INFO: Looking for ctypes DLLs
1859 INFO: Analyzing run-time hooks ...
1859 INFO: Looking for dynamic libraries
2359 INFO: Looking for eggs
2359 INFO: Python library not in binary depedencies. Doing additional searching...
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/python2.7/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/usr/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 183, in __postinit__
    self.assemble()
  File "/usr/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 510, in assemble
    self._check_python_library(self.binaries)
  File "/usr/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 593, in _check_python_library
    raise IOError(msg)
IOError: Python library not found: libpython27.dll
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

Indeed recently installed cygwin does not have libpython27.dll. It does have 

```
$ ls -al /usr/lib/libpython2.7.dll.a   
lrwxrwxrwx 1 Administrator None 35 Dec  1 12:07 /usr/lib/libpython2.7.dll.a -> python2.7/config/libpython2.7.dll.a
```
though. Isn't this enough for pyinstaller? If not, can cygwin be easily equipped with missing dll?

**Comment by htgoebel** [comment]
@pstrzelczak `.dll.a` does not look like a valid name for a shared library. Which Python did you install *exactly*?

**Comment by pstrzelczak** [comment]
@htgoebel what I just did was:
- install clean Windows 64 bit (I repeated the procedure on all of: Windows Server 2008 Standard, Windows Server 2008 R2 Standard and Windows Server 2012 DataCenter)
- install latest Cygwin 64 bit with python package ticked to be installed. This installed lates cygwin (2.4.1 I think) with python 2.7.10 no board.
- in Cygwin console I ran python -m ensure pip. This installed pip 6.1.1
- in Cygwin console I ran pip install pyinstaller. This installed pyinstaller 3.1.1
- in Cygwin console I ran pyinstaller -F sample.py

The last command fails not finding libpython27.dll whereas all installations have /usr/lib/libpython2.7.dll.a

**Comment by htgoebel** [comment]
Can you please provide an URL where *this very version* of python 2.7.10 can be downloaded?

**Comment by pstrzelczak** [comment]
Yes, I can. One of mirror links: http://ftp.inf.tu-dresden.de/software/windows/cygwin32/x86_64/release/python/python-2.7.10-1.tar.xz

Interesting think is that looked inside that package and found that libpython2.7.dll is present threre but is deployed in /usr/bin . Maybe that is the reason it is not found by pyinstaller.
