### ISSUE TITLE
Error in hook-django.py: KeyError when accessing CONF['scripts']

### ISSUE THREAD

**Issue by bosha** [pyinstaller/pyinstaller#1334]
Hello. 

I have an application running with django 1.7.
If I try to execute pyinstaller with it, it fails:

````
╰─➤  pyinstaller local/manage.py 
27 INFO: wrote /home/bosha/Dropbox/sync/python-dev/defects/manage.spec
29 INFO: UPX is not available.
30 INFO: Extending PYTHONPATH with /home/bosha/Dropbox/sync/python-dev/defects/local
30 INFO: checking Analysis
30 INFO: Building Analysis because out00-Analysis.toc non existent
30 INFO: Creating base_library.zip for Python 3
3712 INFO: running Analysis out00-Analysis.toc
3751 INFO: Looking for graph hooks ...
3752 INFO: Analyzing local/manage.py
10548 INFO: Analyzing /home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/loader/_pyi_bootstrap.py
10619 INFO: Analyzing /home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/loader/pyi_importers.py
10631 INFO: Analyzing /home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/loader/pyi_archive.py
10649 INFO: Analyzing /home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/loader/pyi_carchive.py
10663 INFO: Analyzing /home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/loader/pyi_os_path.py
10667 INFO: Hidden import 'codecs' has been found otherwise
10667 INFO: Hidden import 'encodings' has been found otherwise
10667 INFO: Looking for import hooks ...
10673 INFO: Processing hook   hook-encodings.py
11097 INFO: Processing hook   hook-pydoc.py
11099 INFO: Processing hook   hook-distutils.py
11108 INFO: Processing hook   hook-xml.py
11109 INFO: Processing hook   hook-site.py
11209 INFO: Processing hook   hook-sysconfig.py
11210 INFO: Processing hook   hook-django.core.management.py
11535 INFO: Processing hook   hook-django.db.backends.py
11899 INFO: Processing hook   hook-django.core.mail.py
11978 INFO: Processing hook   hook-django.db.backends.mysql.base.py
11981 INFO: Processing hook   hook-django.db.backends.oracle.base.py
11986 INFO: Processing hook   hook-sqlite3.py
12044 INFO: Processing hook   hook-xml.sax.py
12045 INFO: Processing hook   hook-xml.dom.domreg.py
12045 INFO: Processing hook   hook-xml.dom.py
12050 INFO: Processing hook   hook-django.core.cache.py
12089 INFO: Processing hook   hook-django.py
Traceback (most recent call last):
  File "/home/bosha/Dropbox/sync/python-dev/defects/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0dev', 'console_scripts', 'pyinstaller')()
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/main.py", line 96, in run
    run_build(opts, spec_file, pyi_config)
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/main.py", line 49, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/build.py", line 2170, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/build.py", line 2116, in build
    exec(text, spec_namespace)
  File "<string>", line 12, in <module>
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/build.py", line 403, in __init__
    self.__postinit__()
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/build.py", line 240, in __postinit__
    self.assemble()
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/build.py", line 675, in assemble
    hook_name_space = mod_loader.load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/hooks/hook-django.py", line 23, in <module>
    root_dir = django_find_root_dir()
  File "/home/bosha/Dropbox/sync/python-dev/defects/lib/python3.4/site-packages/PyInstaller/utils/hooks/hookutils.py", line 514, in django_find_root_dir
    manage_py = CONF['scripts'][0]
KeyError: 'scripts'
````

CONF dict is empty.
Running on Linux, inside virtualenv, with python3.4 and python3 branch of pyinstaller.

**Comment by matysek** [comment]
I'm able to reproduce this error.

**Comment by matysek** [comment]
The keyerror with CONF should be fixed. Now I get error with raise AppRegistryNotReady("Apps aren't loaded yet.") and that's described in #1067.
