### ISSUE TITLE
'time' module not working with locales

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1378]
It looks like pull request #1369 broke some python modules when using with non 'C' locales. On my system I use locale 'cs_CZ.UTF-8' and the test_time_module is failing.
```
(pyinst3) [martin@martin-laptop python3]$ export LC_ALL=C
(pyinst3) [martin@martin-laptop python3]$ py.test
========================================== test session starts ==========================================
platform linux -- Python 3.4.2 -- py-1.4.30 -- pytest-2.7.2 -- /home/martin/Projects/python/pyinst3/bin/python
rootdir: /home/martin/Projects/pyinstaller/python3, inifile: setup.cfg
plugins: xdist
collected 71 items 

tests/functional/test_basic.py::test_time_module[onedir] PASSED

======================================= 1 passed in 8.41 seconds ========================================
(pyinst3) [martin@martin-laptop python3]$ export LC_ALL=cs_CZ.UTF-8
(pyinst3) [martin@martin-laptop python3]$ py.test
========================================== test session starts ==========================================
platform linux -- Python 3.4.2 -- py-1.4.30 -- pytest-2.7.2 -- /home/martin/Projects/python/pyinst3/bin/python
rootdir: /home/martin/Projects/pyinstaller/python3, inifile: setup.cfg
plugins: xdist
collected 71 items 

tests/functional/test_basic.py::test_time_module[onedir] FAILED

=============================================== FAILURES ================================================
_______________________________________ test_time_module[onedir] ________________________________________

----------------------------------------- Captured stdout call ------------------------------------------
RUNNING: './pyi_time_module'
----------------------------------------- Captured stderr call ------------------------------------------
PyInstaller Bootloader 3.x
LOADER: LC_CTYPE is C
LOADER: Setting LC_CTYPE to "" (using current locale)
LOADER: LC_CTYPE is now cs_CZ.UTF-8
LOADER: executable is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: homepath is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module
LOADER: LD_LIBRARY_PATH=/tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module
PyInstaller Bootloader 3.x
LOADER: LC_CTYPE is C
LOADER: Setting LC_CTYPE to "" (using current locale)
LOADER: LC_CTYPE is now cs_CZ.UTF-8
LOADER: executable is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: homepath is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module
LOADER: _MEIPASS2 is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module
LOADER: archivename is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: Already in the child - running user's code.
LOADER: Python library: /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/libpython3.4m.so.1.0
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (PYTHONPATH, PYTHONHOME)
LOADER: Pre-init PYTHONPATH is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/base_library.zip:/tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module
LOADER: PYTHONHOME is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module
LOADER: Setting runtime options
LOADER: S
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init PYTHONPATH is /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/base_library.zip:/tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module
LOADER: Setting sys.argv
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: out00-PYZ.pyz
LOADER: import sys; sys.path.append(r"/tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module?35568")
LOADER: Running scripts
LOADER: RC: -1 from pyi_time_module
LOADER: OK.
LOADER: Cleaning up Python interpreter.
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/usr/lib64/python3.4/_strptime.py", line 494, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib64/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data 'Mon Aug  3 14:26:33 2015' does not match format '%a %b %d %H:%M:%S %Y'
LOADER: Back to parent
LOADER: Doing cleanup
LOADER: Freeing archive status for /tmp/pytest-23/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
======================================== short test summary info ========================================
FAIL tests/functional/test_basic.py::test_time_module[onedir]
======================================= 1 failed in 8.92 seconds ========================================
(pyinst3) [martin@martin-laptop python3]$ 

```

After deeper analysis of the `time` module I found out that with locale cs_CZ.UTF-8:
* `time.ctime()` returns current date in English but
* `time.strptime()` uses locale cs_CZ.UTF-8 to parse the time string.

**Comment by htgoebel** [comment]
@codewarrior0 I had a deeper look into the code of #1369, and I have the impression, that the locale is set twice and maybe not reset correctly.

**Comment by codewarrior0** [comment]
@matysek There is a line missing from your LOADER debug output. Before `LOADER: Running Scripts`, it should say [`LOADER: Restoring LC_CTYPE to C`](https://github.com/pyinstaller/pyinstaller/pull/1369/files#diff-71f02638d1f1878187c29045c696d4f9R327)

Could you force-rebuild your bootloader and try again?

**Comment by matysek** [comment]
I recompiled bootloader and tried again, locale cs_CZ.UTF-8:
```
PyInstaller Bootloader 3.x
LOADER: LC_CTYPE is C
LOADER: Setting LC_CTYPE to "" (using current locale)
LOADER: LC_CTYPE is now cs_CZ.UTF-8
LOADER: executable is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: homepath is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module
LOADER: LD_LIBRARY_PATH=/tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module
PyInstaller Bootloader 3.x
LOADER: LC_CTYPE is C
LOADER: Setting LC_CTYPE to "" (using current locale)
LOADER: LC_CTYPE is now cs_CZ.UTF-8
LOADER: executable is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: homepath is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module
LOADER: _MEIPASS2 is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module
LOADER: archivename is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: Already in the child - running user's code.
LOADER: Python library: /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/libpython3.4m.so.1.0
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (PYTHONPATH, PYTHONHOME)
LOADER: Pre-init PYTHONPATH is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/base_library.zip:/tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module
LOADER: PYTHONHOME is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module
LOADER: Setting runtime options
LOADER: S
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init PYTHONPATH is /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/base_library.zip:/tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module
LOADER: Setting sys.argv
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: out00-PYZ.pyz
LOADER: import sys; sys.path.append(r"/tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module?35576")
LOADER: Restoring LC_CTYPE to C
LOADER: Running scripts
LOADER: RC: -1 from pyi_time_module
LOADER: OK.
LOADER: Cleaning up Python interpreter.
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/usr/lib64/python3.4/_strptime.py", line 494, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib64/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data 'Tue Aug  4 11:43:17 2015' does not match format '%a %b %d %H:%M:%S %Y'
LOADER: Back to parent
LOADER: Doing cleanup
LOADER: Freeing archive status for /tmp/pytest-24/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
======================================== short test summary info ========================================
FAIL tests/functional/test_basic.py::test_time_module[onedir]
======================================= 1 failed in 7.91 seconds ========================================
(pyinst3) [martin@martin-laptop python3]$ 
```

**Comment by matysek** [comment]
On OS X it is the same, when I do `export LC_ALL=cs_CZ`:
```
PyInstaller Bootloader 3.x
LOADER: LC_CTYPE is C
LOADER: Setting LC_CTYPE to "" (using current locale)
LOADER: LC_CTYPE is now cs_CZ
LOADER: executable is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: homepath is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module
LOADER: _MEIPASS2 is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module
LOADER: archivename is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
LOADER: Already in the child - running user's code.
LOADER: Python library: /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module/Python
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (PYTHONPATH, PYTHONHOME)
LOADER: Pre-init PYTHONPATH is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module/base_library.zip:/private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module
LOADER: PYTHONHOME is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module
LOADER: Setting runtime options
LOADER: S
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init PYTHONPATH is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module/base_library.zip:/private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module
LOADER: Setting sys.argv
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: out00-PYZ.pyz
LOADER: import sys; sys.path.append(r"/private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module?38744")
LOADER: Restoring LC_CTYPE to C
LOADER: Running scripts
LOADER: RC: -1 from pyi_time_module
LOADER: OK.
LOADER: Cleaning up Python interpreter.
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/_strptime.py", line 494, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data 'Tue Aug  4 11:43:42 2015' does not match format '%a %b %d %H:%M:%S %Y'
LOADER: Back to parent
LOADER: Doing cleanup
LOADER: Freeing archive status for /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-9/test_time_module_onedir_0/dist/pyi_time_module/pyi_time_module
======================================= 1 failed in 10.32 seconds =======================================
(pyinst3) bash-3.2$ 
```

**Comment by matysek** [comment]
Could this be anyhow related to this code?
```C
// pyi_launch.c
    #ifndef WIN32
    /*
     * On Linux sys.getfilesystemencoding() returns None but should not.
     * If it's None(NULL), get the filesystem encoding by using direct
     * C calls and override it with correct value.
     */
    if (!*PI_Py_FileSystemDefaultEncoding) {
        char *saved_locale, *loc_codeset;
        saved_locale = strdup(setlocale(LC_CTYPE, NULL));
        VS("LOADER: LC_CTYPE was %s but resulted in NULL FileSystemDefaultEncoding\n", saved_locale);
        setlocale(LC_CTYPE, "");
        loc_codeset = nl_langinfo(CODESET);
        setlocale(LC_CTYPE, saved_locale);
        free(saved_locale);
        VS("LOADER: Setting FileSystemDefaultEncoding to %s (was NULL)\n", loc_codeset);
        *PI_Py_FileSystemDefaultEncoding = loc_codeset;
    }
    #endif /* WIN32 */
```

**Comment by htgoebel** [comment]
> export LC_ALL=cs_CZ:
> LOADER: LC_CTYPE is C

I really wonder why the loader says LC_TYPE is C if you explicitly have set LC_ALL=cs_CZ.

**Comment by codewarrior0** [comment]
Thanks. I went and double checked this bit:

```
time.ctime() returns current date in English but
time.strptime() uses locale cs_CZ.UTF-8 to parse the time string.
```

And it appears to be true. ctime is documented to ignore the current locale, and strptime/strftime are documented to use the current locale for formatting and parsing (for things like month/day names, etc). So, the pyi_time_module test is technically broken, except that it doesn't call setlocale so it should *rightly expect* that strptime can parse the return value of ctime.

So what we need to find out is why strptime is using the current locale. I took care to set the LC_CTYPE locale category back to what it was on app startup (and the log output verifies this) but I didn't think to look for any other calls to setlocale to see if the locale setting for categories other than LC_CTYPE is being changed. (The LC_TIME category is what controls the behavior of strftime/strptime).

I noticed a call to change LC_ALL [here in pyi_arch_cache_argv](https://github.com/pyinstaller/pyinstaller/blob/python3/bootloader/src/pyi_archive.c#L490) and I'm wondering if it's getting the locale value that was previously set for LC_CTYPE and applying it to all locale categories.

**Comment by codewarrior0** [comment]
> I really wonder why the loader says LC_TYPE is C if you explicitly have set LC_ALL=cs_CZ.

This is part of the C standard. The locale categories are all set to "C" at the start of the program. You can set any of the locale environment variables, and they won't affect the locale until you call setlocale.

**Comment by htgoebel** [comment]
I assume this is caused saving the result of`setlocale(LC_CTYPE, NULL)`, which is always `C` (see https://github.com/pyinstaller/pyinstaller/pull/1369#discussion_r36171935).

OTOH, AFAIK `time` should honor the current locale only if `locale` is used.

**Comment by codewarrior0** [comment]
> OTOH, AFAIK time should honor the current locale only if locale is used.

Yes, this test *should* be passing. 

I think the setlocale calls in pyi_arch_cache_argv aren't needed any more, since the locale is already set at the beginning of main.

**Comment by codewarrior0** [comment]
@matysek Can you try #1383? If it makes the test pass for you, please merge it.

**Comment by matysek** [comment]
@codewarrior0 yes, with these changes the test passes. Thanks.
