### ISSUE TITLE
Cannot create executable for OSX after installing Pillow

### ISSUE THREAD

**Issue by aodock** [pyinstaller/pyinstaller#1400]
I run the command `pyinstaller -i 'icon.icns' --windowed 'main.py'`. I get no warning messages while creating an executable. But the executable file dose not open. So i right clicked > show package contents and found my main.py file inside `Contents/MacOS/main.py`. when i double clicked that i get the following output.
```
Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller-2.1.1dev_-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/username/Desktop/main/out00-PYZ.pyz/PIL.PngImagePlugin", line 40, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller-2.1.1dev_-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/username/Desktop/main/out00-PYZ.pyz/PIL.Image", line 53, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller-2.1.1dev_-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/username/Desktop/main/out00-PYZ.pyz/FixTk", line 74, in <module>
OSError: [Errno 20] Not a directory: '/Users/username/Desktop/mainA.app/Contents/MacOS/tcl'
logout

[Process completed]
```

**Comment by aodock** [comment]
now im getting a bit different error

```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller-2.1.1dev_-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 271, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/username/Desktop/main/out00-PYZ.pyz/Tkinter", line 39, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller-2.1.1dev_-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 416, in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
ImportError: dlopen(/Users/username/Desktop/dist/main.app/Contents/MacOS/_tkinter.so, 2): Library not loaded: @loader_path/Tcl
  Referenced from: /Users/username/Desktop/dist/main.app/Contents/MacOS/_tkinter.so
  Reason: no suitable image found.  Did find:
	/Users/username/Desktop/dist/main.app/Contents/MacOS/Tcl: not a file
	/Users/username/Desktop/dist/main.app/Contents/MacOS/Tcl: not a file
logout

[Process completed]
```

**Comment by htgoebel** [comment]
We need more infos, please follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by aodock** [comment]
Hi,.. Im using the default version of python `2.7.4` that came with `Mac 10.10.4`. Previously, i was able to use pyinstaller to create `.app` file which was able to open on all similar mac. Then i had to install `Pillow`. I got the error which i mentioned [here](https://github.com/pyinstaller/pyinstaller/issues/1395),.. 

so, to give a fresh start,..I uninstalled the older version, removed the config and cache files as mentioned on the [How to Report Bug](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) link.  And installed pyinstaller by running this on terminal `sudo pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`. Without sudo i cannot install any thing using pip. so usually use "sudo pip install *some package*".

***Situation 1:***  When i use `Pillow` in my code(like `from PIL import ImageTk, Image`). code executes fine without any error. But the problem occurs when running pyinstaller. After installing the latest develop version, when i run `pyinstaller --windowed 'main.py'`, i get a runtime warning while building an executable for mac
```
6745 INFO: Analyzing main.py
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/hooks/hook-PIL.Image.py:14: RuntimeWarning: Parent module 'PyInstaller.hooks.hook-PIL' not found while handling absolute import
  from PyInstaller.hooks.shared_PIL_Image import *
6993 INFO: Processing hook hook-PIL.Image
```
and a bunch of errors at the end of making an executable,..
```
12382 INFO: checking PYZ
12387 INFO: Building because toc changed
12387 INFO: Building PYZ (ZlibArchive) out00-PYZ.toc
15456 INFO: checking PKG
15482 INFO: Building because /Users/username/Desktop/main/out00-PYZ.pyz changed
15482 INFO: Building PKG (CArchive) out00-PKG.pkg
15506 INFO: checking EXE
15507 INFO: ignoring icon, version, manifest and resources = platform not capable
15507 INFO: Rebuilding out00-EXE.toc because pkg is more recent
15507 INFO: Building EXE from out00-EXE.toc
15519 INFO: Appending archive to EXE /Users/username/Desktop/main/main
15528 INFO: Fixing EXE for code signing /Users/username/Desktop/main/main
15734 INFO: checking COLLECT
15735 INFO: Removing dir /Users/username/Desktop/dist/main
15771 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==2.1.1dev-', 'console_scripts', 'pyinstaller')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/main.py", line 90, in run
    run_build(opts, spec_file, pyi_config)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/main.py", line 48, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/build.py", line 2059, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/build.py", line 2005, in build
    execfile(spec)
  File "/Users/username/Desktop/main.spec", line 29, in <module>
    name='cp_mainA2_u2')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/build.py", line 1460, in __init__
    self.__postinit__()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/build.py", line 321, in __postinit__
    self.assemble()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/build.py", line 1495, in assemble
    shutil.copy(fnm, tofnm)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 20] Not a directory: '/Users/username/Desktop/dist/main/tcl/auto.tcl'
```

***Situation 2:*** Removing the import PIL line from my code.
i get no warnings while building and executable as like above. But when i try to open the .app file, nothing happens,.. so to trace back what was happening behind, i right clicked at the app file and opened `show package content`. Inside which i double clicked the file `Contents/MacOS/main.py`. Which opened a terminal and gave output as follows.
```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller-2.1.1dev_-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 271, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/username/Desktop/main/out00-PYZ.pyz/Tkinter", line 39, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller-2.1.1dev_-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 416, in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
ImportError: dlopen(/Users/username/Desktop/dist/main.app/Contents/MacOS/_tkinter.so, 2): Library not loaded: @loader_path/Tcl
  Referenced from: /Users/username/Desktop/dist/main.app/Contents/MacOS/_tkinter.so
  Reason: no suitable image found.  Did find:
	/Users/username/Desktop/dist/main.app/Contents/MacOS/Tcl: not a file
	/Users/username/Desktop/dist/main.app/Contents/MacOS/Tcl: not a file
logout

[Process completed]
```

I don't know whether this is a bug or not,.. But in both the cases, it seems pyinstaller definetly cannot pick some files. Can you please help

**Comment by aodock** [comment]
Hi, It seems i was using python from mac's default version, I tried installing  python through brew. Now it works fine.
