### ISSUE TITLE
python 3.5 support

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1407]
Current python3 branch does not support Python 3.5 and our test suite fails with Python 3.5:
https://travis-ci.org/pyinstaller/pyinstaller/jobs/75171273

There is issue with Python 3.5 environment in travis: missing shared Python library. Related issue:
https://github.com/travis-ci/travis-ci/issues/4834

**Comment by codewarrior0** [comment]
Some information about the Windows release of Python 3.5:

http://stevedower.id.au/blog/building-for-python-3-5/

It seems that 3.5 will link the C Runtime Library using a shared assembly again, after 3.3 and 3.4 simply linked it as a DLL in `c:\windows`.

**Comment by matysek** [comment]
@codewarrior0  I was playing with python 3.5 on OS X and I got error `Cannot dlsym for _Py_char2wchar`. Do you have any idea how that could be fixed?
```
RUNNING:  '/private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_import_onedir
_0/dist/pyi_import_relative/pyi_import_relative' , args:  ['./pyi_import_relative']
PyInstaller Bootloader 3.x
LOADER: executable is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_im
port_onedir_0/dist/pyi_import_relative/pyi_import_relative
LOADER: homepath is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_impo
rt_onedir_0/dist/pyi_import_relative
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_i
mport_onedir_0/dist/pyi_import_relative/pyi_import_relative
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative
_import_onedir_0/dist/pyi_import_relative
PyInstaller Bootloader 3.x
LOADER: executable is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_im
port_onedir_0/dist/pyi_import_relative/pyi_import_relative
LOADER: homepath is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_impo
rt_onedir_0/dist/pyi_import_relative
LOADER: _MEIPASS2 is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_imp
ort_onedir_0/dist/pyi_import_relative
LOADER: archivename is /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_i
mport_onedir_0/dist/pyi_import_relative/pyi_import_relative
LOADER: Already in the child - running user's code.
LOADER: Python library: /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_import_onedir_0/dist/pyi_import_relative/Python
Cannot dlsym for _Py_char2wchar
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /private/var/folders/yr/g1rrgkws6lv5267bg2bwc8ww0000gn/T/pytest-15/test_relative_import_onedir_0/dist/pyi_import_relative/pyi_import_relative
FAILED
```

**Comment by codewarrior0** [comment]
I believe the function is renamed to `Py_DecodeLocale` in 3.5. Good thing, too - you'll need it if you're embedding Python.

**Comment by codewarrior0** [comment]
A quick search and replace for `_Py_char2wchar` -> `Py_DecodeLocale` should get you going.

As for the permanent fix, I think it's best to use the new `Py_DecodeLocale` name in our code, and when loading Python 3 dlls below 3.5, load the `_Py_char2wchar` symbol into that name. It's the same function, just renamed with a "public" name in 3.5.

**Comment by matysek** [comment]
@codewarrior0 Thanks for the tip. I got Python 3.5 working on OS X. Not sure about other platforms.

**Comment by codewarrior0** [comment]
I just gave Python 3.5 a try on Windows. `pywin32-219` is not compatible with Python 3.5, but only takes minor tweaks to get it working. After that, I get what looks like a bug in `py.test`:

```
C:\python35\Lib\ast.py:245: in visit
    return visitor(node)
.env35\lib\site-packages\_pytest\assertion\rewrite.py:796: in visit_Compare
    left_res, left_expl = self.visit(comp.left)
C:\python35\Lib\ast.py:245: in visit
    return visitor(node)
.env35\lib\site-packages\_pytest\assertion\rewrite.py:700: in visit_Name
    locs = ast.Call(self.builtin("locals"), [], [], None, None)
E   TypeError: Call constructor takes either 0 or 3 positional arguments
```

**Comment by codewarrior0** [comment]
It looks like the `py.test` bug with 3.5 is already fixed on their master: pytest-dev/pytest#744. Going to install pytest from git and try again.

**Comment by codewarrior0** [comment]
And now I run into another bug installing pytest:

```error in pytest setup command: Invalid environment marker: sys_platform=="win32"```

To fix this one, I have to install the Python 3.5.0rc2 which was released just yesterday. Hooray for progress!

After installing Python 3.5.0rc2 and the master branch of pytest, and rebuilding the bootloader after your recent changes, I can now run the `helloworld` test.

**Comment by matysek** [comment]
@codewarrior0 good progress.

**Comment by codewarrior0** [comment]
The test ran and passed on my dev machine, but when I copied the exe to a VM that never had Python 3.5 installed, it was missing some DLLs. I just made the necessary changes to make sure those DLLs (parts of the UCRT) are now pulled in. One of those changes was to handle [forwarded exports](http://blogs.msdn.com/b/oldnewthing/archive/2006/07/19/671238.aspx) where DLL references can be in the exports of a DLL, and not just its imports. This should improve general support for DLLs that do that kind of thing.

**Comment by matysek** [comment]
Linux support for Python 3.5 is still incomplete. Travis can't find the `libpython3.5.so`. libpython is probably linked statically on Ubuntu in Travis. Travis complains about this:
```
self = <PyInstaller.building.build_main.Analysis object at 0x7f31c260da90>
binaries = [('resource', '/3.5-dev/lib/python3.5/lib-dynload/resource.cpython-35m-x86_64-linux-gnu.so', 'EXTENSION'), ('_datetime...'/lib/x86_64-linux-gnu/libbz2.so.1.0', 'BINARY'), ('liblzma.so.5', '/usr/lib/x86_64-linux-gnu/liblzma.so.5', 'BINARY')]
    def _check_python_library(self, binaries):
        """
            Verify presence of the Python dynamic library in the binary dependencies.
            Python library is an essential piece that has to be always included.
            """
        # First check that libpython is in resolved binary dependencies.
        for (nm, filename, typ) in binaries:
            if typ == 'BINARY' and nm in PYDYLIB_NAMES:
                # Just print its filename and return.
                logger.info('Using Python library %s', filename)
                # Checking was successful - end of function.
                return
    
        # Python lib not in dependencies - try to find it.
        logger.info('Python library not in binary depedencies. Doing additional searching...')
        python_lib = bindepend.get_python_library_path()
        if python_lib:
            logger.debug('Adding Python library to binary dependencies')
            binaries.append((os.path.basename(python_lib), python_lib, 'BINARY'))
            logger.info('Using Python library %s', python_lib)
        else:
            msg = """Python library not found! This usually happens on Debian/Ubuntu
    where you need to install Python library:
    
      apt-get install python3-dev
      apt-get install python-dev
    
    """
>           raise IOError(msg)
E           OSError: Python library not found! This usually happens on Debian/Ubuntu
E           where you need to install Python library:
E           
E             apt-get install python3-dev
E             apt-get install python-dev
```

**Comment by matysek** [comment]
* This is related travis bug report: https://github.com/travis-ci/travis-ci/issues/4834 about missing libpython3.4m.so.
* It looks like Travis guys fixed that: https://travis-ci.org/pyinstaller/pyinstaller/jobs/81581825

**Comment by matysek** [comment]
Closing since the travis tests passed with Python 3.5. We've got Python 3.5 support in pyinstaller.

**Comment by htgoebel** [comment]
> We've got Python 3.5 support in pyinstaller.

Yeah!

**Comment by borfast** [comment]
Is pyinstaller supposed to work with Python 3.5 under pyenv? I'm getting the following error with even a simple `print("hello world")` script:

```
[borfast:/home/borfast/playground] [playground] $ pyinstaller test.py 
45 INFO: PyInstaller: 3.3.dev0+116033
45 INFO: Python: 3.5.1
46 INFO: Platform: Linux-3.19.0-32-generic-x86_64-with-debian-jessie-sid
47 INFO: wrote /home/borfast/playground/test.spec
50 INFO: UPX is not available.
51 INFO: Extending PYTHONPATH with paths
['/home/borfast/playground', '/home/borfast/playground']
51 INFO: checking Analysis
51 INFO: Building Analysis because out00-Analysis.toc is non existent
51 INFO: Initializing module dependency graph...
52 INFO: Initializing module graph hooks...
53 INFO: Analyzing base_library.zip ...
2493 INFO: running Analysis out00-Analysis.toc
2518 INFO: Caching module hooks...
2523 INFO: Analyzing /home/borfast/playground/test.py
2530 INFO: Loading module hooks...
2531 INFO: Loading module hook "hook-encodings.py"...
2542 INFO: Loading module hook "hook-xml.py"...
2752 INFO: Loading module hook "hook-pydoc.py"...
2768 INFO: Looking for ctypes DLLs
2776 INFO: Analyzing run-time hooks ...
2788 INFO: Looking for dynamic libraries
3576 INFO: Looking for eggs
3576 INFO: Using Python library /home/borfast/.pyenv/versions/3.5.1/lib/libpython3.5m.so.1.0
3589 INFO: Warnings written to /home/borfast/playground/build/test/warntest.txt
3597 INFO: checking PYZ
3598 INFO: Building PYZ because out00-PYZ.toc is non existent
3598 INFO: Building PYZ (ZlibArchive) /home/borfast/playground/build/test/out00-PYZ.pyz
3946 INFO: checking PKG
3946 INFO: Building PKG because out00-PKG.toc is non existent
3946 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/home/borfast/.pyenv/versions/playground/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.3.dev0+116033', 'console_scripts', 'pyinstaller')()
  File "/home/borfast/.pyenv/versions/3.5.1/envs/playground/lib/python3.5/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/borfast/.pyenv/versions/3.5.1/envs/playground/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/borfast/.pyenv/versions/3.5.1/envs/playground/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/borfast/.pyenv/versions/3.5.1/envs/playground/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 26, in <module>
  File "/home/borfast/.pyenv/versions/3.5.1/envs/playground/lib/python3.5/site-packages/PyInstaller/building/api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/home/borfast/.pyenv/versions/3.5.1/envs/playground/lib/python3.5/site-packages/PyInstaller/building/api.py", line 189, in __init__
    self.__postinit__()
  File "/home/borfast/.pyenv/versions/3.5.1/envs/playground/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/home/borfast/.pyenv/versions/3.5.1/envs/playground/lib/python3.5/site-packages/PyInstaller/building/api.py", line 266, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "/home/borfast/.pyenv/versions/3.5.1/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by htgoebel** [comment]
@borfast Please open a new ticket for your issue. This one is closed for 9 month now.
