### ISSUE TITLE
something strange with python-rpm

### ISSUE THREAD

**Issue by bsavelev** [pyinstaller/pyinstaller#1476]
I try to pack simple app that use python-rpm (4.11.3-1.1, from Debian 8) with PyInstaller==2.1
```python
print 'Hello'
import rpm
print rpm.VERIFY_SIGNATURE
```

Pack --onedir
```shell
pyinstaller -D --noupx ./test.py
```
and run
```shell
./dist/test/test 
Hello
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/boris/PycharmProjects/2/build/test/out00-PYZ.pyz/rpm", line 9, in <module>
ImportError: No module named _rpm
```

strace -ff -etrace=open ./dist/test/test
```
[pid 19733] open("/home/boris/PycharmProjects/2/dist/test/test", O_RDONLY|O_LARGEFILE) = 5
Hello
Traceback (most recent call last):
  File "<string>", line 2, in <module>
[pid 19733] open("<string>", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
[pid 19733] open("/home/boris/PycharmProjects/2/dist/test/<string>", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
[pid 19733] open("/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", O_RDONLY|O_LARGEFILE) = 6
    exec(bytecode, module.__dict__)
  File "/home/boris/PycharmProjects/2/build/test/out00-PYZ.pyz/rpm", line 9, in <module>
[pid 19733] open("/home/boris/PycharmProjects/2/build/test/out00-PYZ.pyz/rpm", O_RDONLY|O_LARGEFILE) = -1 ENOTDIR (Not a directory)
[pid 19733] open("/home/boris/PycharmProjects/2/dist/test/rpm", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
ImportError: No module named _rpm
[pid 19733] +++ exited with 255 +++
```

Ooook. It's a first bug. Why it looks into dist/test/rpm dir and not found in dist/test?
Create dir and copy so
```shell
mkdir dist/test/rpm
cp dist/test/rpm._rpm.so dist/test/rpm/_rpm.so
```
and run
```
Hello
error: Failed to initialize NSS library
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/boris/PycharmProjects/2/build/test/out00-PYZ.pyz/rpm", line 10, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/boris/PycharmProjects/2/build/test/out00-PYZ.pyz/rpm.transaction", line 5, in <module>
ImportError: cannot import name ts
```

```error: Failed to initialize NSS library``` is it an another bug?

rpm.transaction have:
```python
from rpm._rpm import ts as Transaction
```
There are no module ```ts``` anywhere. Is it another bug?

My env is pretty stable Debian 8 -)
I use python2.7 from repo. All packages like python-rpm are also from repo. PyInstaller from ```pip install```

**Comment by matysek** [comment]
@bsavelev Could you try the `python3` branch? There is now the main development focus and we'd like to release a new version in a month or so.

**Comment by bsavelev** [comment]
just try with
```
./pyinstaller.py -v
3.0.dev0+a51d7f0-mod
```
First error gone away.
The two last are present:
```
./dist/test/test 
Hello
error: Failed to initialize NSS library
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/boris/PycharmProjects/1/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib/python2.7/dist-packages/rpm/__init__.py", line 10, in <module>
    from rpm.transaction import *
  File "/home/boris/PycharmProjects/1/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib/python2.7/dist-packages/rpm/transaction.py", line 5, in <module>
    from rpm._rpm import ts as TransactionSetCore
ImportError: cannot import name ts
test returned -1
```

**Comment by matysek** [comment]
* What tells you command `ldd dist/test/rpm._rpm.so`?
* Are `libnss*` in dist/test directory?
* `libnss*` are excluded by default on Linux (file PyInstaller/depend/dylib.py). Could you try to comment out lines like `r'/libnss_*` and try again?
* This issue looks like a question whether `libnss` should be on Linux bundled or not by default.

**Comment by bsavelev** [comment]
```shell
ldd dist/test/rpm._rpm.i386-linux-gnu.so 
        linux-gate.so.1 (0xb7760000)
        librpm.so.3 => /usr/lib/i386-linux-gnu/librpm.so.3 (0xb7683000)
        librpmio.so.3 => /usr/lib/i386-linux-gnu/librpmio.so.3 (0xb7654000)
        libdl.so.2 => /lib/i386-linux-gnu/i686/cmov/libdl.so.2 (0xb764e000)
        libpthread.so.0 => /lib/i386-linux-gnu/i686/cmov/libpthread.so.0 (0xb7632000)
        libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xb7488000)
        libpopt.so.0 => /lib/i386-linux-gnu/libpopt.so.0 (0xb747a000)
        libselinux.so.1 => /lib/i386-linux-gnu/libselinux.so.1 (0xb7452000)
        libcap.so.2 => /lib/i386-linux-gnu/libcap.so.2 (0xb744b000)
        liblua5.2.so.0 => /usr/lib/i386-linux-gnu/liblua5.2.so.0 (0xb7413000)
        libdb-5.3.so => /usr/lib/i386-linux-gnu/libdb-5.3.so (0xb7221000)
        libnss3.so => /usr/lib/i386-linux-gnu/libnss3.so (0xb70a8000)
        libbz2.so.1.0 => /lib/i386-linux-gnu/libbz2.so.1.0 (0xb7095000)
        libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb7077000)
        libelf.so.1 => /usr/lib/i386-linux-gnu/libelf.so.1 (0xb705e000)
        liblzma.so.5 => /lib/i386-linux-gnu/liblzma.so.5 (0xb7035000)
        /lib/ld-linux.so.2 (0xb7761000)
        libpcre.so.3 => /lib/i386-linux-gnu/libpcre.so.3 (0xb6fc4000)
        libattr.so.1 => /lib/i386-linux-gnu/libattr.so.1 (0xb6fbe000)
        libm.so.6 => /lib/i386-linux-gnu/i686/cmov/libm.so.6 (0xb6f77000)
        libnssutil3.so => /usr/lib/i386-linux-gnu/libnssutil3.so (0xb6f4e000)
        libplc4.so => /usr/lib/i386-linux-gnu/libplc4.so (0xb6f48000)
        libplds4.so => /usr/lib/i386-linux-gnu/libplds4.so (0xb6f43000)
        libnspr4.so => /usr/lib/i386-linux-gnu/libnspr4.so (0xb6eff000)
        librt.so.1 => /lib/i386-linux-gnu/i686/cmov/librt.so.1 (0xb6ef5000)
```

```shell
ls dist/test/ |sort
bz2.i386-linux-gnu.so
_codecs_cn.i386-linux-gnu.so
_codecs_hk.i386-linux-gnu.so
_codecs_iso2022.i386-linux-gnu.so
_codecs_jp.i386-linux-gnu.so
_codecs_kr.i386-linux-gnu.so
_codecs_tw.i386-linux-gnu.so
_hashlib.i386-linux-gnu.so
libattr.so.1
libbz2.so.1.0
libcap.so.2
libcrypto.so.1.0.0
libdb-5.3.so
libelf.so.1
liblua5.2.so.0
liblzma.so.5
libmagic.so.1
libnspr4.so
libnss3.so
libnssutil3.so
libpcre.so.3
libplc4.so
libplds4.so
libpopt.so.0
libpython2.7.so.1.0
libreadline.so.6
librpmbuild.so.3
librpmio.so.3
librpmsign.so.1
librpm.so.3
libselinux.so.1
libssl.so.1.0.0
libtinfo.so.5
libz.so.1
_multibytecodec.i386-linux-gnu.so
readline.i386-linux-gnu.so
resource.i386-linux-gnu.so
rpm._rpmb.i386-linux-gnu.so
rpm._rpm.i386-linux-gnu.so
rpm._rpms.i386-linux-gnu.so
test
```

excluding ```libnss_*``` doesn't help

BUT!
As you can see in first code block (ldd) rpm._rpm use libnss3.so which have own nss plugins...
I do this:
```shell
$ dpkg -S /usr/lib/i386-linux-gnu/libnss3.so
libnss3:i386: /usr/lib/i386-linux-gnu/libnss3.so

$ dpkg -L libnss3:i386 |grep so
/usr/lib/i386-linux-gnu/libnss3.so
/usr/lib/i386-linux-gnu/libnssutil3.so
/usr/lib/i386-linux-gnu/libsmime3.so
/usr/lib/i386-linux-gnu/libssl3.so
/usr/lib/i386-linux-gnu/nss/libsoftokn3.chk
/usr/lib/i386-linux-gnu/nss/libfreebl3.so
/usr/lib/i386-linux-gnu/nss/libsoftokn3.so
/usr/lib/i386-linux-gnu/nss/libnssdbm3.so
/usr/lib/i386-linux-gnu/nss/libnssckbi.so

cp /usr/lib/i386-linux-gnu/nss/* ./dist/test/
```

And test program works well.

So I need special hook for libnss3 to copy it own plugins?

**Comment by matysek** [comment]
> So I need special hook for libnss3 to copy it own plugins?

Probably. But here are some questions:
* How does libnss determine path where to load its plugins? LD_LIBRARY_PATH?
* Could be `libnss3` considered as something that has stable api and is available in every linux distribution?
* Do you think that pyinstaller should bundle `libnss3` by default or ignore it?
* Does your app work when you remove all 'libnss3*' files and its plugins from `dist/test` directory?

@htgoebel What do you think about libnss3? Should pyinstaller exclude it or it is necessary to create a hook for package python-rpm?

**Comment by bsavelev** [comment]
>How does libnss determine path where to load its plugins? LD_LIBRARY_PATH?

I belive that it defined at compile time

>Could be libnss3 considered as something that has stable api and is available in every linux distribution?

Libnss has backcompat feature (http://upstream.rosalinux.ru/versions/nss.html) but it not in every distro in core (in every repo, maybe. chromium, for example use this lib)

>Do you think that pyinstaller should bundle libnss3 by default or ignore it?

I think it should be bundled

>Does your app work when you remove all 'libnss3*' files and its plugins from dist/test directory?

Yes, it work, but in runtime use system libnss.
```shell
strace -ff -etrace=open ./test 2>&1 | grep nss
[pid 21671] open("/home/boris/PycharmProjects/1/test/dist/test/libnss3.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21671] open("/usr/lib/i386-linux-gnu/libnss3.so", O_RDONLY|O_CLOEXEC) = 4
[pid 21671] open("/home/boris/PycharmProjects/1/test/dist/test/libnssutil3.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21671] open("/usr/lib/i386-linux-gnu/libnssutil3.so", O_RDONLY|O_CLOEXEC) = 4
[pid 21671] open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 4
[pid 21671] open("/home/boris/PycharmProjects/1/test/dist/test/libnss_compat.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21671] open("/lib/i386-linux-gnu/i686/cmov/libnss_compat.so.2", O_RDONLY|O_CLOEXEC) = 4
[pid 21671] open("/home/boris/PycharmProjects/1/test/dist/test/libnss_nis.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21671] open("/lib/i386-linux-gnu/i686/cmov/libnss_nis.so.2", O_RDONLY|O_CLOEXEC) = 4
[pid 21671] open("/home/boris/PycharmProjects/1/test/dist/test/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21671] open("/lib/i386-linux-gnu/i686/cmov/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 4
[pid 21671] open("/usr/lib/i386-linux-gnu/nss/libsoftokn3.so", O_RDONLY|O_CLOEXEC) = 4
[pid 21671] open("/usr/lib/i386-linux-gnu/nss/libfreebl3.so", O_RDONLY|O_CLOEXEC) = 4
```

**Comment by matysek** [comment]
> Does your app work when you remove all 'libnss3*' files and its plugins from dist/test directory?
> Yes, it work, but in runtime use system libnss.

Thanks. Could you find out what files exactly should be bundled? libnss3, libnssutil, plugins, etc?

**Comment by htgoebel** [comment]
> Do you think that pyinstaller should bundle libnss3 by default or ignore it?

Since it is similar to openssl, I would handle it like openssl.

**Comment by matysek** [comment]
I think postponing this for 3.1 is fine.

**Comment by htgoebel** [comment]
Removing this from the project's schedule until somebody wants to pick it up an provide a pull-request.
