### ISSUE TITLE
Error 'pip install pyinstaller' for Python 3.4.3 Win

### ISSUE THREAD

**Issue by ctulhu** [pyinstaller/pyinstaller#1479]
I see error:
```
Collecting pyinstaller
  Downloading PyInstaller-2.1.tar.gz (4.8MB)
    100% |################################| 4.8MB 112kB/s
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Dmitry\AppData\Local\Temp\pip-build-oqo56b2d\pyinstaller\setup.py", line 18, in <module>
        from PyInstaller import get_version
      File "C:\Users\Dmitry\AppData\Local\Temp\pip-build-oqo56b2d\pyinstaller\PyInstaller\__init__.py", line 32, in <module>
        from PyInstaller import compat
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "C:\Users\Dmitry\AppData\Local\Temp\pip-build-oqo56b2d\pyinstaller\setup.py", line 18, in <module>

        from PyInstaller import get_version

      File "C:\Users\Dmitry\AppData\Local\Temp\pip-build-oqo56b2d\pyinstaller\PyInstaller\__init__.py", line 32, in <module>

        from PyInstaller import compat

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\Dmitry\AppData\Local\Temp\pip-build-oqo56b2d\pyinstaller
```

For bug reproduce:
```
1. cd <your-project-dir>
2. c:\python34\python.exe -m venv env
3. env\scripts\activate.bat
4. pip install pyinstaller
```

OS: Windows 8.1 Enterprise 64-bit
Python version 3.4.3

**Comment by htgoebel** [comment]
PyInstaller 2.1 does not support Python 3. Even the categories in PyPi tell so, just pip ignores them.
Use
`pip install https://github.com/pyinstaller/pyinstaller/archive/python3.zip`

**Comment by htgoebel** [comment]
I just updated the wiki to hold this information
