### ISSUE TITLE
pkg_resources.DistributionNotFound: distribute

### ISSUE THREAD

**Issue by gclsoft** [pyinstaller/pyinstaller#1515]
pyinstaller Main.py:
```
D:\Users\asus\Documents\GitHub\newUndo2048\tool\videoPei\stockNOw>pyinstaller Ma
in.py
Traceback (most recent call last):
  File "D:\Py27\Scripts\pyinstaller-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build\bdist.win32\egg\pkg_resources.py", line 2793, in <module>
  File "build\bdist.win32\egg\pkg_resources.py", line 673, in require
  File "build\bdist.win32\egg\pkg_resources.py", line 576, in resolve
pkg_resources.DistributionNotFound: distribute
```

**Comment by matysek** [comment]
Please provide more information:
* https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong
* https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by htgoebel** [comment]
Got no further info since four months now. Closing.

**Comment by riggsd** [comment]
I'm not the original reporter, but this issue just came up while searching for a resolution, and I see it was closed just 5 days ago. It appears that I'm seeing it also, on a completely different platform.

PyInstaller 3.1, Python 2.7.11 (homebrew), virtualenv, on OS X 10.9.5

```
(myvenv)[user@host ~/project]$ pyinstaller myscript.py
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3130, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3116, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3143, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'distribute' distribution was not found and is required by PyInstaller
```

```
(myvenv)[user@host ~/project]$ which pyinstaller
/Users/user/.virtualenvs/myvenv/bin/pyinstaller
```

```
(myvenv)[user@host ~/project]$ pip freeze
astroid==1.4.4
BeautifulSoup==3.2.1
docutils==0.11
Jinja2==2.8
lazy-object-proxy==1.2.1
logilab-common==1.1.0
MarkupSafe==0.23
pep8==1.5.6
Pygments==2.1
PyInstaller==3.1
pylint==1.2.0
python-dateutil==2.2
pytz==2014.2
six==1.10.0
Sphinx==1.2.2
wheel==0.24.0
wrapt==1.10.6
```

I'm not sure why `setuptools` doesn't show up in that `pip freeze` output, as the latest version is installed.

```
(myvenv)[user@host ~/project]$ pip install -U setuptools
Requirement already up-to-date: setuptools in /Users/user/.virtualenvs/myvenv/lib/python2.7/site-packages
```

**Comment by riggsd** [comment]
Note that my application does not require `distribute`.

Note also that I just tried installing `distribute==0.7.3` (which apparently just depends on `setuptools>=0.7`) into my virtualenv, and I still get the exact same exception.

**Comment by riggsd** [comment]
Oof! It turns out my system had a crusty old 2.1 version of PyInstaller (outside the venv) which was causing the problem. A quick `pip -U pyinstaller` swapped it out for version 3.1 and all appears to be well. 

Apologies!
