### ISSUE TITLE
IOError on --onefile

### ISSUE THREAD

**Issue by kilbyjmichael** [pyinstaller/pyinstaller#1597]
36 INFO: PyInstaller: 3.0
37 INFO: Python: 2.7.6
37 INFO: Platform: Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 97, in run
    spec_file = run_makespec(opts, args)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 41, in run_makespec
    spec_file = PyInstaller.building.makespec.main(args, **opts.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/makespec.py", line 334, in main
    specfile = open(specfnm, 'w')
IOError: [Errno 13] Permission denied: '/home/kilby/pupy/client/reverse_ssl.spec'

**Comment by matysek** [comment]
Please follow this guide: https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by htgoebel** [comment]
Closing since no more details have been given since a month now.
