### ISSUE TITLE
OS X, Tk/TCL and matplotlib

### ISSUE THREAD

**Issue by LevN0** [pyinstaller/pyinstaller#1606]
Hello, 

Python version: 2.7.10
PyInstaller version: 3.0
Matplotlib version: 1.4.3

A proposed workaround to the OSX bug reported in the link below, where Tk/TCL is not packaged on MacOS, is to install python via homebrew. Here's the issue description:

https://github.com/pyinstaller/pyinstaller/issues/1350

Following this method, I installed python 2.7 via homebrew, and added only matplotlib and its dependencies via pip. My app is able to start correctly, but when calling matplotlib imports I receive the following error:

Traceback (most recent call last):
.... 
  File "/Users/build/Documents/app_pyinstaller/app/image_viewer.py", line 38, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
  File "/private/var/folders/td/x56vzsb91wg9hlnyr367tj240000gn/T/pip-build-4vRcH9/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 11, in <module>
    import matplotlib.backends.tkagg as tkagg
  File "/private/var/folders/td/x56vzsb91wg9hlnyr367tj240000gn/T/pip-build-4vRcH9/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 2, in <module>
    from matplotlib.backends import _tkagg
  File "/private/var/folders/td/x56vzsb91wg9hlnyr367tj240000gn/T/pip-build-4vRcH9/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 517, in load_module
ImportError: dlopen(/var/folders/td/x56vzsb91wg9hlnyr367tj240000gn/T/_MEIgd1wCT/matplotlib.backends._tkagg.so, 2): Library not loaded: @loader_path/Tcl
  Referenced from: /var/folders/td/x56vzsb91wg9hlnyr367tj240000gn/T/_MEIgd1wCT/matplotlib.backends._tkagg.so
  Reason: no suitable image found.  Did find:
    /var/folders/td/x56vzsb91wg9hlnyr367tj240000gn/T/_MEIgd1wCT/Tcl: not a file
    /private/var/folders/td/x56vzsb91wg9hlnyr367tj240000gn/T/_MEIgd1wCT/Tcl: not a file

I also receive the same error if I use macports and add matplotlib via pip. If I use macports and add matplotlib via 'port install py27-matplotlib', then everything works fine. Using the anaconda distribution of python also works. 

Edit: Clarifying that Tk/Tcl does appear to be imported (because the entire app depends on it and it runs fine until it hits matplotlib), it's the matplotlib TkAgg aspect that has an issue with PyInstaller somewhere.

**Comment by matysek** [comment]
Thanks for reporting this issue. We get similar error while running `test_tkinter` in travis: https://travis-ci.org/pyinstaller/pyinstaller-osx-tests

**Comment by Legorooj** [comment]
Is this issue fixed?
