### ISSUE TITLE
Error when looking for ctypes DLLs

### ISSUE THREAD

**Issue by ryansturmer** [pyinstaller/pyinstaller#1608]
Version 3.0 of pyinstaller gives me this error on Windows 7 using python 2.7.5

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 207, in __init__
    self.__postinit__()
  File "C:\Python27\lib\site-packages\PyInstaller\building\datastruct.py", line 156, in __postinit__
    self.assemble()
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 468, in assemble
    ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
  File "C:\Python27\lib\site-packages\PyInstaller\depend\utils.py", line 164, in scan_code_for_ctypes
    nested_binaries, nested_warnings = scan_code_for_ctypes(c)
  File "C:\Python27\lib\site-packages\PyInstaller\depend\utils.py", line 181, in scan_code_for_ctypes
    elif binary != os.path.basename(binary):
  File "C:\Python27\lib\ntpath.py", line 198, in basename
    return split(p)[1]
  File "C:\Python27\lib\ntpath.py", line 181, in split
    return d + head, tail
TypeError: cannot concatenate 'str' and 'tuple' objects
```

This is a relatively simple application that uses wxpython, and a single ctypes-loaded dll (loaded by 
`windll.LoadLibrary` using a bare filename)

**Comment by htgoebel** [comment]
Please provide more information, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by ryansturmer** [comment]
Closing this as it seems the same as #1609
