### ISSUE TITLE
ctypes.utils not found 

### ISSUE THREAD

**Issue by patillacode** [pyinstaller/pyinstaller#1623]
Hi there,

I found that when trying to run pyinstaller I get the following error, both in windows 7 and Mac OS X 10.9.5 - both machines run Python 2.7

```
5770 INFO: Looking for ctypes DLLs
Traceback (most recent call last):
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 207, in __init__
    self.__postinit__()
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 468, in assemble
    ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/depend/utils.py", line 158, in scan_code_for_ctypes
    ctypesb, ctypesw = scan_code_instruction_for_ctypes(co, instrs, i)
  File "/Users/gonzalo.fernandez/.virtualenvs/imagination-doorman/lib/python2.7/site-packages/PyInstaller/depend/utils.py", line 280, in scan_code_instruction_for_ctypes
    soname = ctypes.util.find_library(libname)
AttributeError: 'module' object has no attribute 'util'
```

The weird part is that when running a python console and import ctype I can find utils without problems.

this only happens with one of my scripts. Imports in this problematic script are below, in case it may help:
```python
import json

from twisted.internet import reactor

from autobahn.twisted.websocket import WebSocketServerFactory
from autobahn.twisted.websocket import WebSocketServerProtocol
from autobahn.twisted.websocket import listenWS
```

Can't get my head around this one, any ideas?

Thanks.

**Comment by matysek** [comment]
@patillacode Could you  try the latest dev  version? Is the failure still the same?

**Comment by patillacode** [comment]
@matysek yes, same exact problem:

60 INFO: PyInstaller: 3.1.dev0
60 INFO: Python: 2.7.5
65 INFO: Platform: Darwin-13.4.0-x86_64-i386-64bit
70 INFO: wrote /Users/gonzalo.fernandez/Downloads/pyinstaller-develop/broadcast/broadcast.spec
77 INFO: UPX is not available.
78 INFO: Extending PYTHONPATH with /Users/gonzalo.fernandez/projects/imagination-doorman/python
78 INFO: checking Analysis
78 INFO: Building Analysis because out00-Analysis.toc is non existent
78 INFO: Initializing module dependency graph...
81 INFO: Initializing module graph hooks...
132 INFO: running Analysis out00-Analysis.toc
143 INFO: Analyzing /Users/gonzalo.fernandez/projects/imagination-doorman/python/broadcast.py
3396 INFO: Processing pre-find module path hook   distutils
4405 INFO: Looking for import hooks ...
4407 INFO: Processing hook   hook-distutils.py
4414 INFO: Processing hook   hook-xml.py
4415 INFO: Processing hook   hook-httplib.py
4415 INFO: Processing hook   hook-encodings.py
4942 INFO: Processing hook   hook-xml.dom.domreg.py
4948 INFO: Processing hook   hook-xml.sax.py
4948 INFO: Processing hook   hook-xml.dom.py
4965 INFO: Looking for ctypes DLLs
Traceback (most recent call last):
  File "pyinstaller.py", line 15, in <module>
    run()
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/building/build_main.py", line 738, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/building/build_main.py", line 208, in __init__
    self.__postinit__()
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/building/build_main.py", line 469, in assemble
    ctypes_binaries = scan_code_for_ctypes(co)
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/depend/utils.py", line 152, in scan_code_for_ctypes
    __recursivly_scan_code_objects_for_ctypes(co, binaries)
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/depend/utils.py", line 184, in __recursivly_scan_code_objects_for_ctypes
    bin = __scan_code_instruction_for_ctypes(co, instructions)
  File "/Users/gonzalo.fernandez/Downloads/pyinstaller-develop/PyInstaller/depend/utils.py", line 280, in __scan_code_instruction_for_ctypes
    return ctypes.util.find_library(libname)
AttributeError: 'module' object has no attribute 'util'

**Comment by matysek** [comment]
@patillacode Which line of the example is causing this?

**Comment by patillacode** [comment]
Hi @matysek 
I am not sure but I think it is not even related to my script:

```ptyhon 
return ctypes.util.find_library(libname)
```
is the line where it gets stuck, but _ctypes_ is there and has _utils_ as proven via a python terminal.

**Comment by htgoebel** [comment]
Something seams to be mixed up with out installation. Please add a `print ctypes` just before the failing line and verify it's the correct `ctypes` module.

**Comment by codewarrior0** [comment]
`depend/utils.py` should have `import ctypes.util`.

If some other module does `import ctypes.util` before that, the `util` name is added to the `ctypes` module and can be used without `import ctypes.util`. Otherwise, trying to use `ctypes.util` without explicitly importing it with `import ctypes.util` raises an AttributeError. This must be why the test suite doesn't catch this error - some other module is importing it first.

**Comment by codewarrior0** [comment]
In my case, that other module was `pyreadline`, which is imported automatically when starting up an interactive interpreter. It imports `ctypes.util`, which makes it available to other modules that only import `ctypes`. If I run the interpreter in one-command mode instead of interactive: `python -c 'import ctypes; print ctypes.util'`, then I get the attribute error.

**Comment by codewarrior0** [comment]
Should be fixed in f788dec36b8d55f4518881be9f4188ad865306ec.

**Comment by patillacode** [comment]
@codewarrior0
I was testing, and you are right, I will pull now.

thanks.

**Comment by patillacode** [comment]
@codewarrior0 
Seems like there is a misprint
file: ```pyinstaller-develop/PyInstaller/depend/utils.```
line: ```171```

``` python
loggger.warn("ignoring %s - ctypes imports only supported using bare filenames" % binary)
```

**Comment by codewarrior0** [comment]
Embarassing! Fixed in 85496703d421da2dfb6b1ca33e13888cfd08b56b. I searched for `loggger` just to be sure.

**Comment by patillacode** [comment]
All good! :+1: 
Thanks!

**Comment by cb109** [comment]
I was going to report this bug when I found this issue. Thanks for fixing so quickly. Can confirm the current **3.1.dev0** works for me on Windows 7, Python 2.7.10 x64. Looking forward to the next release :sunglasses:
