### ISSUE TITLE
_find_prefix() fails on Homebrew: IndexError

### ISSUE THREAD

**Issue by nchammas** [pyinstaller/pyinstaller#1641]
I went through the [PyInstaller Recipes](https://github.com/pyinstaller/pyinstaller/wiki/Recipes) and it doesn't look like I've run into any of the common issues.

I'm trying to freeze a simple Python application on OS X. I'm just running `pyinstaller flintrock.py`.

This is the traceback I get:

```
$ pyinstaller flintrock.py
43 INFO: PyInstaller: 3.0
43 INFO: Python: 3.5.0
55 INFO: Platform: Darwin-15.0.0-x86_64-i386-64bit
56 INFO: wrote /path/flintrock/flintrock.spec
56 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /path/flintrock/venv/bin/python3

1063 INFO: UPX is not available.
1066 INFO: Extending PYTHONPATH with /path/flintrock
1067 INFO: checking Analysis
1067 INFO: Building Analysis because out00-Analysis.toc is non existent
1067 INFO: Initializing module dependency graph...
1069 INFO: Initializing module graph hooks...
1070 INFO: Analyzing base_library.zip ...
4763 INFO: running Analysis out00-Analysis.toc
4772 INFO: Analyzing /path/flintrock/flintrock.py
9333 INFO: Processing pre-find module path hook   distutils
11222 INFO: Looking for import hooks ...
11224 INFO: Processing hook   hook-pydoc.py
11224 INFO: Processing hook   hook-distutils.py
Traceback (most recent call last):
  File "/path/flintrock/venv/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 207, in __init__
    self.__postinit__()
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 428, in assemble
    imphook_object = ImportHook(imported_name, hook_file)
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/building/imphook.py", line 175, in __init__
    self._module = importlib_load_source(hook_modname, self._filename)
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/compat.py", line 492, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/hooks/hook-distutils.py", line 33, in <module>
    datas = [(_CONFIG_H, relpath_to_config_or_make(_CONFIG_H))]
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/utils/hooks/__init__.py", line 995, in relpath_to_config_or_make
    prefix = _find_prefix(filename)
  File "/path/flintrock/venv/lib/python3.5/site-packages/PyInstaller/utils/hooks/__init__.py", line 985, in _find_prefix
    return possible_prefixes[0]
IndexError: list index out of range
```

Anything I should look into to help debug this issue?

I'm using the latest versions of Python, PyInstaller, and OS X. I manage my Python installation using Homebrew, in case that matters.

**Comment by htgoebel** [comment]
Looms as if the makefile is found *outside* your Pythin installation.

Can you please add these lines to `PyInstaller/utils/hooks/__init__.py` line 980 and post teh output:
```
print(repr(prefixes))
print(repr(filename))
```

**Comment by nchammas** [comment]
In [`hooks/__init__.py`](https://github.com/pyinstaller/pyinstaller/blob/cebd6267e7cfc493bb1c3a9e5be5bc4cecb7ecd9/PyInstaller/utils/hooks/__init__.py#L1003-L1008):
* `repr(prefixes)`:

  ```
['/path/flintrock/venv', '/usr/local/bin/../Cellar/python3/3.5.0/bin/../Frameworks/Python.framework/Versions/3.5']
```
* `repr(filename)`:

  ```
'/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/include/python3.5m/pyconfig.h'
```
* `repr(common), repr(prefix)`:

  ```
'/' '/path/flintrock/venv'
'/usr/local/' '/usr/local/bin/../Cellar/python3/3.5.0/bin/../Frameworks/Python.framework/Versions/3.5'
```

So it looks like the problem is that `compat.base_prefix` is not normalized, so `os.path.commonprefix()` doesn't detect the common prefix across `prefix` and `filename`.

I fixed the problem by defining `prefixes` as follows:

```
prefixes = [os.path.abspath(sys.prefix), os.path.abspath(compat.base_prefix)]
```

I don't know if for consistency we should also apply `abspath()` to `filename`. Also, there is a new method, [`os.path.commonpath()`](https://docs.python.org/3/library/os.path.html#os.path.commonpath), which we should probably use instead of `os.path.commonprefix()` if possible.

Should I open a PR with these fixes?

**Comment by nchammas** [comment]
To clarify, my fix lets me build successfully, which I couldn't do before. But the resulting package doesn't run:

```
  File "/path/flintrock/venv/lib/python3.5/site-packages/boto/vendored/six.py", line 738, in <module>
    __spec__.submodule_search_locations = []  # PEP 451 @UndefinedVariable
AttributeError: 'NoneType' object has no attribute 'submodule_search_locations'
```

I'll save this for a separate issue.

**Comment by htgoebel** [comment]
Thanks for debugging. I'll just pushed a fix.
And thanks for offering a PR, too. I've seen this too late.

Re. `os.path.commonpath()`: This is new in Python 3.5, so we can not use it yet.

**Comment by nchammas** [comment]
Thanks for investigating with me and applying the fix so fast.

**Comment by jose-t** [comment]
I'm encountering the same issue when I'm running `pyinstaller --windowed main.spec`.
I'm using virtualenv with pyenv on macOS High Sierra.

Traceback :

```
58 INFO: PyInstaller: 3.3.1
58 INFO: Python: 3.5.1
64 INFO: Platform: Darwin-17.6.0-x86_64-i386-64bit
67 INFO: UPX is not available.
69 INFO: Extending PYTHONPATH with paths
['/Users/lol/Desktop/freezed_app',
 '/Users/lol/Desktop/freezed_app']
69 INFO: checking Analysis
69 INFO: Building Analysis because out00-Analysis.toc is non existent
69 INFO: Initializing module dependency graph...
70 INFO: Initializing module graph hooks...
72 INFO: Analyzing base_library.zip ...
3718 INFO: Analyzing hidden import 'PyQt5'
3722 INFO: Analyzing hidden import 'oauthlib'
3726 INFO: Analyzing hidden import 'requests'
3817 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
5390 INFO: Analyzing hidden import 'requests_oauthlib'
5668 INFO: running Analysis out00-Analysis.toc
5676 INFO: Caching module hooks...
5680 INFO: Analyzing freezed_app/main.py
6776 INFO: Processing pre-find module path hook   distutils
8062 INFO: Processing pre-find module path hook   site
8062 INFO: site: retargeting to fake-dir '/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/fake-modules'
8090 INFO: Processing pre-safe import module hook   win32com
10618 INFO: Loading module hooks...
10618 INFO: Loading module hook "hook-setuptools.py"...
10619 WARNING: Hidden import "setuptools.msvc" not found!
10619 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
11025 INFO: Loading module hook "hook-requests.py"...
11026 INFO: Loading module hook "hook-sysconfig.py"...
# DEBUG common == prefix
/Users/lol/.pyenv/versions/3.5.1/ == /Users/lol/.pyenv/versions/3.5.1/envs/freezer
/Users/lol/.pyenv/versions/3.5.1/ == /Users/lol/.pyenv/versions/3.5.1/Python.framework/Versions/3.5
# END DEBUG
Traceback (most recent call last):
  File "/Users/lol/.pyenv/versions/freezer/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
    self.__postinit__()
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 472, in assemble
    module_hook.post_graph()
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/building/imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/building/imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/compat.py", line 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/hooks/hook-sysconfig.py", line 30, in <module>
    datas = [(_CONFIG_H, relpath_to_config_or_make(_CONFIG_H))]
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/utils/hooks/__init__.py", line 802, in relpath_to_config_or_make
    prefix = _find_prefix(filename)
  File "/Users/lol/.pyenv/versions/3.5.1/envs/freezer/lib/python3.5/site-packages/PyInstaller/utils/hooks/__init__.py", line 791, in _find_prefix
    return possible_prefixes[0]
IndexError: list index out of range
```

It is appeared just after I have installed numpy package.
