### ISSUE TITLE
ImportError: No module named symbol

### ISSUE THREAD

**Issue by mtwu-aviatrix** [pyinstaller/pyinstaller#1652]
Pull a latest dev Pyinstaller and bump into the following error. Is it a bug in the latest source?
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.1.dev0+618b7f0-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 364, in load_module
    exec(bytecode, module.__dict__)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 32, in <module>
ImportError: No module named symbol
pyi_rth_pkgres returned -1
```

**Comment by htgoebel** [comment]
Need more info: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by htgoebel** [comment]
Got no further info since two months now. Closing.
