### ISSUE TITLE
PyCrypto - ImportError with Crypto.Cipher._AES when using --key option

### ISSUE THREAD

**Issue by benmao** [pyinstaller/pyinstaller#1663]
## test4.py

```
#!/usr/bin/env python
# coding:utf-8

import Crypto.Cipher.AES

if __name__ == '__main__':
    print "run success"
```

## build command

>pyinstaller.py  test4.py --debug --key=123

## output

```
PyInstaller Bootloader 3.x
LOADER: executable is e:\poppy\gg\dist\test4\test4.exe
LOADER: homepath is e:\poppy\gg\dist\test4
LOADER: _MEIPASS2 is NULL
LOADER: archivename is e:\poppy\gg\dist\test4\test4.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(e:\poppy\gg\dist\test4)
LOADER: Already in the child - running user's code.
LOADER: Python library: e:\poppy\gg\dist\test4\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is e:\poppy\gg\dist\test4
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is e:\poppy\gg\dist\test4
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted pyimod00_crypto_key
LOADER: callfunction returned...
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running test4.py
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "d:\pyinstaller2\PyInstaller\loader\pyimod03_importers.py", line 364, in load_module
    exec(bytecode, module.__dict__)
  File "D:\Python27\lib\site-packages\Crypto\Cipher\AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: cannot import name _AES
test4 returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.
```

**Comment by matysek** [comment]
@benmao Please provide more info:
* pyinstaller version
* pycrypto version
* are you sure that _AES C extension was compiled when insstalling pycrypto?

**Comment by benmao** [comment]
@matysek 

* pyinstaller 3.1.dev0
* pycrypto 2.6.1
* I can see Crypto.Cipher._AES.pyd in dist folder.

>pyinstaller.py test4.py --debug
works good.

**Comment by jun0s** [comment]
Hi, same problem with pyinstaller 3.0 and python 2.7.10 x32 Windows, pycrypto 2.6.1 working fine on "native way" .py scripts.

**Comment by tammela** [comment]
I got the same problem.
PyInstaller 3.0
pycrypto 2.6
Python 2.7
openSUSE 13.2 X86_64

### output from executable

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/home/pedro/workspace/ping/src/tools.py", line 4, in <module>
    from Crypto import Random
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib64/python2.7/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib64/python2.7/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib64/python2.7/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 36, in <module>
    from Crypto.Cipher import AES
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib64/python2.7/site-packages/Crypto/Cipher/AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: cannot import name _AES
main returned -1

**Comment by jun0s** [comment]
No updates about this issue? @matysek 
thanks.

**Comment by aclewis182** [comment]
Same issue seen on OS X
[localhost] local: pyinstaller scrat.py --clean --onefile --key *********
28 INFO: PyInstaller: 3.1.dev0+4da2503
28 INFO: Python: 2.7.6
35 INFO: Platform: Darwin-14.5.0-x86_64-i386-64bit

**Comment by aclewis182** [comment]
Same issue on Linux / ARM:
PyInstaller: 3.1.dev0+6d65e7c
[debian@10.1.0.9:22] out: 774 INFO: Python: 2.7.3
[debian@10.1.0.9:22] out: 778 INFO: Platform: Linux-3.8.13-bone47-armv7l-with-debian-7.4

**Comment by matysek** [comment]
* I was able to reproduce it on Linux with the code from the description.
* PyInstaller's `crypto feature` uses module `Crypto.Cipher._AES` and somehow it interferes with PyCrypto when using that module in your code.

**Comment by matysek** [comment]
This is the correct output imports without --key option:
```
import os # PyInstaller PYZ
import stat # PyInstaller PYZ
import posixpath # PyInstaller PYZ
import genericpath # PyInstaller PYZ
import _collections_abc # PyInstaller PYZ
# ctypes not found in PYZ
LOADER: Running hello_test.py
import Crypto # PyInstaller PYZ
import Crypto.Cipher # PyInstaller PYZ
import Crypto.Cipher.AES # PyInstaller PYZ
import Crypto.Cipher.blockalgo # PyInstaller PYZ
import Crypto.Util # PyInstaller PYZ
import Crypto.Util.py3compat # PyInstaller PYZ
# Crypto.Cipher._AES not found in PYZ
# _bootlocale not found in PYZ
import _bootlocale # loaded from Zip /home/martin/Projects/pyinstaller/develop/hello_test/dist/hello_test/base_library.zip/_bootlocale.pyc
# extension module loaded from '/home/martin/Projects/pyinstaller/develop/hello_test/dist/hello_test/Crypto.Cipher._AES.cpython-34m.so'
```
This is the wrong output imports with `--key` option:
```
import os # PyInstaller PYZ
import stat # PyInstaller PYZ
import posixpath # PyInstaller PYZ
import genericpath # PyInstaller PYZ
import _collections_abc # PyInstaller PYZ
# ctypes not found in PYZ
LOADER: Running hello_test.py
import Crypto # PyInstaller PYZ
import Crypto.Cipher # PyInstaller PYZ
import Crypto.Cipher.AES # PyInstaller PYZ
import Crypto.Cipher.blockalgo # PyInstaller PYZ
import Crypto.Util # PyInstaller PYZ
import Crypto.Util.py3compat # PyInstaller PYZ
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/martin/Projects/pyinstaller/develop/PyInstaller/loader/pyimod03_importers.py", line 364, in load_module
    exec(bytecode, module.__dict__)
  File "/home/martin/Projects/python/pyinst3/lib/python3.4/site-packages/Crypto/Cipher/AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: cannot import name '_AES'
```

**Comment by matysek** [comment]
I just commited a fix. Could any of you @benmao @jun0s @tammela @aclewis182 to confirm it's workig?

**Comment by tammela** [comment]
It's working.
Thanks!

**Comment by jun0s** [comment]
Works for me too (Windows, pyinstaller 3.1.dev0).. thanks u @matysek

**Comment by aclewis182** [comment]
Works on OS X.  I'll be able to test the ARM on Monday.  @matysek thanks for the quick turn around on this!

**Comment by benmao** [comment]
@matysek works. thx

**Comment by pertsev** [comment]
import  Crypto.Cipher._AES as AES
import Crypto.Hash._SHA256 as SHA256

if __name__ == '__main__':
    c = AES.new('1234567890123456')
    cipher = c.encrypt('blabblabblabblab')
    print(cipher.encode('hex'))
    h = SHA256.new('blabblabblabblab')
    print(h.hexdigest())

**Comment by matysek** [comment]
This is another issue. Please open a new issue with more details.
