### ISSUE TITLE
Cannot import pyusb by pyInstaller3

### ISSUE THREAD

**Issue by xiekuncn** [pyinstaller/pyinstaller#1682]
Dear PyInstaller Team:
I use the pyintaller 3 to package python program with pyusb by the command:
```bash
pyinstaller usb-hook-test.py
```

But I got the following error: 
```python
956 INFO: Processing hook   hook-usb.py
Traceback (most recent call last):
  File "/home/aoi/Development/pyinstaller/pyinstaller.py", line 18, in <module>
    run()
  File "/home/aoi/Development/pyinstaller/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/home/aoi/Development/pyinstaller/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 207, in __init__
    self.__postinit__()
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 428, in assemble
    imphook_object = ImportHook(imported_name, hook_file)
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/imphook.py", line 175, in __init__
    self._module = importlib_load_source(hook_modname, self._filename)
  File "/home/aoi/Development/pyinstaller/PyInstaller/hooks/hook-usb.py", line 55, in <module>
    binaries.pop(2)
IndexError: pop index out of range
````

Minimal code:

```python
#!/bin/python2.7
# filename: usb-hook-test.py
import usb

print 'pyusb.version:{}'.format(usb.__version__)
dev = usb.core.find()
print dev
```
My System info is:
> Python 2.7.6
> pyusb version: 1.0.0rc1
> Linux/ Ubuntu 14.04
> PyInstaller 3.0

I've debuged with the source code of the PyInstaller3, and try to guess the structure of the variable **binaries** at **hook-usb.py** , but got nothing. Maybe you can help me to understand the binaries mean, and I can pull a request for fixed this issue.

Thank you.

**Comment by tallforasmurf** [comment]
The hook is trying to establish a global `binaries` that will tell the main code to include some libs. Normal feature of the hook API. Odd failure because `binaries.pop(2)` is immediately preceded by `assert len(binaries[0]) == 3`

    https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-usb.py#L54

... oh, wait. I think I see a problem there... @htgoebel this is code from #292138 and it appears the assert and the pop refer to different things?

**Comment by xiekuncn** [comment]
Thank you for replying. I test at 4ea614d1ff7d4d601488c1d2ee253df3f6dcb82c and it's failure too.
and i got an error here:
```python
Traceback (most recent call last):
  File "/home/aoi/Development/pyinstaller/pyinstaller.py", line 15, in <module>
    run()
  File "/home/aoi/Development/pyinstaller/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/aoi/Development/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 683, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 432, in assemble
    imphook_object = ImportHook(imported_name, hook_file)
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/imphook.py", line 182, in __init__
    self._module = importlib_load_source(hook_modname, self._filename)
  File "/home/aoi/Development/pyinstaller/PyInstaller/hooks/hook-usb.py", line 55, in <module>
    binaries[0].pop(2)
AttributeError: 'tuple' object has no attribute 'pop'
````

I notice you fixed this issue at branch python 3, but my interpreter is  python 2.7. Is it all same at this issue?

I try to change the hook-usb.py last line as:

```python
    binaries[0] = binaries[0][:2]
````

then I got the error like this:
```python
740 INFO: Processing hook   hook-usb.py
Traceback (most recent call last):
  File "/home/aoi/Development/pyinstaller/pyinstaller.py", line 15, in <module>
    run()
  File "/home/aoi/Development/pyinstaller/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/aoi/Development/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 683, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/build_main.py", line 434, in assemble
    imphook_object.update_dependencies(self.graph)
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/imphook.py", line 311, in update_dependencies
    self._process_binaries(mod_graph)
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/imphook.py", line 293, in _process_binaries
    self.binaries.update(set(format_binaries_and_datas(self._module.binaries)))
  File "/home/aoi/Development/pyinstaller/PyInstaller/building/utils.py", line 421, in format_binaries_and_datas
    src_root_path_or_glob))
PyInstaller.compat.FileNotFoundError: Path or glob "libusb-1.0.so.0" not found or matches no files.
````

**Comment by htgoebel** [comment]
5dbd130 should fix this issue. But then a new one arose - fix for which is currently running in CI my personal repo. Will commit here later this day.

**Comment by xiekuncn** [comment]
I got the new issue as:
```python
$ ./usb-hook-test/dist/usb-hook-test/usb-hook-test 
pyusb.version:1.0.0b2
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/usb/core.py", line 1199, in find
ValueError: No backend available
usb-hook-test returned -1
````

**Comment by xiekuncn** [comment]
@htgoebel any update?

**Comment by htgoebel** [comment]
I assume the pyusb-guys can help here much quicker since they know all the internals of their load-engine. It would me take at least an hour to understand this,

**Comment by xiekuncn** [comment]
@htgoebel thanks a lot. I had found help from pyusb. And is there any documents about the hook's binaries? I am sure pyusb worked at some version of the pyinstaller2. Maybe I can  debug this issue following the instruction of the documents.

**Comment by chengchengpei** [comment]
My hook-usb.py is:
libusb_candidates = (
    # libusb10
    'usb-1.0', 'usb', 'libusb-1.0',
    # libusb01
    'usb-0.1', 'libusb0',
    # openusb
    'openusb',
)

for candidate in libusb_candidates:
    libname = ctypes.util.find_library(candidate)
    if libname is not None:
        break

if libname is not None:
    # Use basename here because Python returns full library path
    # on Mac OSX when using ctypes.util.find_library.
    bins = [os.path.basename(libname)]
    binaries = _resolveCtypesImports(bins)
elif is_cygwin:
    bins = ['cygusb-1.0-0.dll', 'cygusb0.dll']
    binaries = _resolveCtypesImports(bins)[:1]  # use only the first one if any
else:
    binaries = []
if binaries:
    # `_resolveCtypesImports` returns a 3-tuple, but `binaries` are only
    # 2-tuples, so remove the last element:
    assert len(binaries[0]) == 3
    binaries = [reversed(binaries[0][:2])]


My error is:
19 INFO: PyInstaller: 3.0
19 INFO: Python: 2.7.3
19 INFO: Platform: Linux-3.5.0-54-generic-x86_64-with-Ubuntu-12.04-precise
19 INFO: wrote /home/cpei/learning/usbdemo/demo.spec
21 INFO: UPX is not available.
21 INFO: Extending PYTHONPATH with /home/cpei/learning/usbdemo
21 INFO: checking Analysis
24 INFO: Building because inputs changed
24 INFO: Initializing module dependency graph...
25 INFO: Initializing module graph hooks...
49 INFO: running Analysis out00-Analysis.toc
71 INFO: Analyzing /home/cpei/learning/usbdemo/demo1.py
1014 INFO: Looking for import hooks ...
1015 INFO: Processing hook   hook-encodings.py
1265 INFO: Processing hook   hook-_tkinter.py
1303 INFO: checking Tree
1305 INFO: checking Tree
1307 INFO: Processing hook   hook-usb.py
1335 INFO: Looking for ctypes DLLs
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 207, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 468, in assemble
    ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/utils.py", line 158, in scan_code_for_ctypes
    ctypesb, ctypesw = scan_code_instruction_for_ctypes(co, instrs, i)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/utils.py", line 280, in scan_code_instruction_for_ctypes
    soname = ctypes.util.find_library(libname)
  File "/usr/lib/python2.7/ctypes/util.py", line 224, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib/python2.7/ctypes/util.py", line 212, in _findSoname_ldconfig
    expr = r'\s+(lib%s\.[^\s]+)\s+\(%s' % (re.escape(name), abi_type)
  File "/usr/lib/python2.7/re.py", line 206, in escape
    s = list(pattern)
TypeError: 'code' object is not iterable

No idea how to fix it....

**Comment by htgoebel** [comment]
Use the *latest* development-version. This problem was fixed in 55b542f1353.

**Comment by htgoebel** [comment]
For futher problem related to pyusb, please open a new ticket. Thanks.
