### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'macholib' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by mgrady3** [pyinstaller/pyinstaller#1713]
Error running the application after the build process completes.

I am using OS X.11 El Capitan with python version 2.7.10 via Anaconda.

I have installed the latest dev version of pyinstaller via github and pip. I have tried using --noupx.
I don't think the error is related to a module that I import, however, the main libraries I depend on for this app are matplotlib, numpy, scipy, PyQt4 and opencv

The error occurs after the build step when trying to launch the Application:

Error printout from Terminal:

```
imac:~ *****$ /Users/****/test-build/dist/main/main ; exit;

Traceback (most recent call last):
  File "<string>", line 170, in <module>
  File "/Users/*****/anaconda/lib/python2.7/site-packages/PyInstaller-3.1.dev0-
py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 382, in load_module
  exec(bytecode, module.__dict__)
  File "/Users/*****/anaconda/lib/python2.7/ctypes/macholib/__init__.py", line 10, in <module>
    __version__ = pkg_resources.require('macholib')[0].version
  File "/Users/*****/anaconda/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 952, in require
  File "/Users/*****/anaconda/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 839, in resolve
pkg_resources.DistributionNotFound: The 'macholib' distribution was not found and is required by the application
pyiboot01_bootstrap returned -1
```

The error specifically mentions macholib which is present in my python distribution; the following returns no errors from Terminal: 'python -c "from ctypes import macholib"

I see that the library exists in ~/anaconda/lib/python2.7/ctypes/macholib/

I have also tried to add "import ctypes.macholib" into my code to force pyinstaller to find the library but that had no differing results.

**Comment by bjones1** [comment]
Create a `hook-ctypes.macholib.py` file containing:

``` Python
from PyInstaller.utils.hooks import copy_metadata

datas = copy_metadata('macholib')
```

Make sure PyInstaller finds this hook file -- for example, use the `--additional-hooks-dir` command-line argument (see https://htmlpreview.github.io/?https://github.com/pyinstaller/pyinstaller/blob/develop/doc/Manual.html#general-options). Also, you **MUST** use the latest source available from github.

**Comment by mgrady3** [comment]
Thanks for the quick reply

That gave me now an error about altgraph being required by macholib

trying a similar work around with a hook for altgraph (its already installed)

will report back if it works

**Comment by GitMensch** [comment]
I have a similar problem using Python 3.4.3 and PyInstaller 3.1.1 on Win64:
The thing that seems to be special (and problematic) is that the modules that should be bundled were directly installed via pip from git:

~~~~
pip3 install ipython==3.2.1 pyzmq --upgrade
pip3 install git+https://github.com/HackEdit/hackedit.git --upgrade
pip3 install git+https://github.com/HackEdit/hackedit-cobol.git --upgrade
pip3 install git+https://github.com/HackEdit/hackedit-python.git --upgrade
~~~~

The simple `pyinstaller.exe hackedit-console-script.py` results in

~~~~
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "site-packages\pkg_resources\__init__.py", line 549, in load_entry_point
  File "site-packages\pkg_resources\__init__.py", line 542, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 422, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 943, in require
  File "site-packages\pkg_resources\__init__.py", line 830, in resolve
pkg_resources.DistributionNotFound: The 'hackedit==1.0a2.dev60' distribution was not found and is required by the application
hackedit-console-script returned -1
~~~~

I found no way to include it correctly. Using `--hidden-module` resulted in a warning "module not found", both w-/wo the part "==1.0a2.dev60".

Any ideas?

**Comment by htgoebel** [comment]
@mgrady3 Is this issue solve for you in the measwhile?
@GitMensch: Please try downgrading setuptools to < 19.0.

**Comment by GitMensch** [comment]
@htgoebel : i've used pip to uninstall setuptools and installed 18.0.0 - the result is the same. More suggestions?

**Comment by muzik113** [comment]
Hi,

I have an equivalent issue here with:
- python 3.5.1
- setup tools 19.2
- pyinstaller 3.1.1

I had an issue with my binairy compilation then I tried to make a dummy one and add the different dependancies into the import list
Currently here is my code dummy.py

`# from flask import Flask
# import flask
# import GTSFramework.Lib.Network as Net
import socket
import _socket
import pyexpat
# import select
import packaging
import packaging.version
import packaging.specifiers
import packaging.requirements
# import time
import PyInstaller
import six
# from PyInstaller.utils.hooks import collect_submodules

print("hello world")
`

and my spec file:
`# -*- mode: python -*-

block_cipher = None

from PyInstaller.utils.hooks import collect_submodules
from PyInstaller.utils.hooks import copy_metadata

a = Analysis(['dummy.py'],
             pathex=['C:\\Users\\user\\PycharmProjects\\Framework'],
             binaries=None,
             datas=copy_metadata('PyInstaller'),
             hiddenimports=collect_submodules('pkg_resources._vendor')+['PyInstaller'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='dummy',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='dummy')
`

My current error is 

> PS C:\Users\craynaud010409\PycharmProjects\Framework\dist\dummy> .\dummy.exe
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "D:\craynaud010409\pythonanaconda\lib\site-packages\pyinstaller-3.1.1-py3.5.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module exec(bytecode, module.__dict__)
  File "PyInstaller\__init__.py", line 61, in <module>
  File "pkg_resources\__init__.py", line 535, in get_distribution
  File "pkg_resources\__init__.py", line 415, in get_provider
  File "pkg_resources\__init__.py", line 943, in require
  File "pkg_resources\__init__.py", line 829, in resolve
**pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by **the application
dummy returned -1

On my original source code I need:
from flask import Flask
import flask
import Framework.Lib.Network as Net 
import socket
import time

In network i use:
import os
import socket

Any ideas?

**Comment by limitforever** [comment]
Why is this problem occured?
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\CV2\fast-style-transfer-master\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\program files\python36\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 472, in assemble
    module_hook.post_graph()
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\program files\python36\lib\site-packages\PyInstaller\compat.py", line 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "G:\CV2\fast-style-transfer-master\hook-ctypes.macholib.py", line 3, in <module>
    datas = copy_metadata('apscheduler')
  File "c:\program files\python36\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 852, in copy_metadata
    dist = pkg_resources.get_distribution(package_name)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 562, in get_distribution
    dist = get_provider(dist)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 436, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'apscheduler' distribution was not found and is required by the application

**Comment by htgoebel** [comment]
>  File "G:\CV2\fast-style-transfer-master\hook-ctypes.macholib.py", line 3, in 

Obviously you application is using ctypes.macholib, which triggers the hook, which tries to find apscheduler (which (I assume) is required by macholib). Please install all requirements of you application.

**Comment by kivdev** [comment]
Windows 10 x64
Python 3.8.1 x32
PyInstaller==4.0.dev0+55c8855d9d
CMD: pyinstaller --onefile test_for_build.py
test_for_build.py:
```
import PyInstaller.__main__

PyInstaller.__main__.run([
    '--name=test',
    '--onefile',
    '--windowed',
    '--icon=icon.ico',
    os.path.join('my_package', 'main.py'),
])

```
main.py:
```
print('Hello World')
input()
```
test_for_build.exe:
```
Traceback (most recent call last):
  File "test_for_build.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\PyInstaller\__init__.py", line 55, in <module>
  File "site-packages\pkg_resources\__init__.py", line 481, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 357, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 900, in require
  File "site-packages\pkg_resources\__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application
[5292] Failed to execute script test_for_build
```
