### ISSUE TITLE
Hidden import PyUsb 1.0 error

### ISSUE THREAD

**Issue by wahono77** [pyinstaller/pyinstaller#1720]
I use PyUSB 1.0 (import usb.core) and hidden import using 'usb.core',
But when building I got error : 
```
16394 INFO: Looking for ctypes DLLs
16457 WARNING: library msvcr90.dll required via ctypes not found
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 47, in run_
build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)

  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line
737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line
680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line
207, in __init__
    self.__postinit__()
  File "C:\Python27\lib\site-packages\PyInstaller\building\datastruct.py", line
156, in __postinit__
    self.assemble()
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line
468, in assemble
    ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
  File "C:\Python27\lib\site-packages\PyInstaller\depend\utils.py", line 158, in
 scan_code_for_ctypes
    ctypesb, ctypesw = scan_code_instruction_for_ctypes(co, instrs, i)
  File "C:\Python27\lib\site-packages\PyInstaller\depend\utils.py", line 280, in
 scan_code_instruction_for_ctypes
    soname = ctypes.util.find_library(libname)
  File "C:\Python27\lib\ctypes\util.py", line 54, in find_library
    fname = os.path.join(directory, name)
  File "C:\Python27\lib\ntpath.py", line 67, in join
    p_drive, p_path = splitdrive(p)
  File "C:\Python27\lib\ntpath.py", line 117, in splitdrive
    if len(p) > 1:
TypeError: object of type 'code' has no len()
```
What's wrong in my step?

thanks

**Comment by wahono77** [comment]
I have installer Microsoft Visual C++ 2008 Redistributable Package (x86) to install missing file msvcr90.dll, but still error.

**Comment by htgoebel** [comment]
Please 
a) try the current development head. There have been changes in this area lately.
b) provide a minimal example for reproducing this. See https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by wahono77** [comment]
Yes, after reinstall current development, it's OK now. Thanks htgoebel.
