### ISSUE TITLE
ImportError: No module named management.commands.runserver

### ISSUE THREAD

**Issue by andrew-malkov** [pyinstaller/pyinstaller#1721]
I succefully built django application exe but on starting django server I've got an error

LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth_django.py
LOADER: Running manage.py
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named management.commands.runserver
manage returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.

**Comment by htgoebel** [comment]
Fix merged.
