### ISSUE TITLE
Bundling Tkinter application fails with "[Errno 20] Not a directory" on Mac OS X

### ISSUE THREAD

**Issue by viotti** [pyinstaller/pyinstaller#1737]
I'm trying to bundle a Tkinter application on OS X, and it is failing with the following error.

```
pyinstaller a.py
37 INFO: PyInstaller: 3.0
37 INFO: Python: 3.4.3
44 INFO: Platform: Darwin-15.2.0-x86_64-i386-64bit
45 INFO: wrote /Users/viotti/testtkinter/a.spec
46 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /Users/viotti/testtkinter/a/bin/python3.4

1051 INFO: UPX is not available.
1053 INFO: Extending PYTHONPATH with /Users/viotti/testtkinter
1054 INFO: checking Analysis
1054 INFO: Building Analysis because out00-Analysis.toc is non existent
1054 INFO: Initializing module dependency graph...
1055 INFO: Initializing module graph hooks...
1057 INFO: Analyzing base_library.zip ...
2767 INFO: Processing pre-find module path hook   distutils
4261 INFO: running Analysis out00-Analysis.toc
4273 INFO: Analyzing /Users/viotti/testtkinter/a.py
4475 INFO: Looking for import hooks ...
4477 INFO: Processing hook   hook-xml.py
4757 INFO: Processing hook   hook-distutils.py
4758 INFO: Processing hook   hook-pydoc.py
4758 INFO: Processing hook   hook-encodings.py
4770 INFO: Processing hook   hook-_tkinter.py
4773 INFO: checking Tree
4773 INFO: Building Tree because out00-Tree.toc is non existent
4773 INFO: Building Tree out00-Tree.toc
4954 INFO: checking Tree
4954 INFO: Building Tree because out01-Tree.toc is non existent
4954 INFO: Building Tree out01-Tree.toc
4978 INFO: Processing hook   hook-xml.sax.py
5002 INFO: Looking for ctypes DLLs
5007 INFO: Analyzing run-time hooks ...
5011 INFO: Including run-time hook 'pyi_rth__tkinter.py'
5022 INFO: Looking for dynamic libraries
5143 INFO: Looking for eggs
5143 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.4/Python
5151 INFO: Warnings written to /Users/viotti/testtkinter/build/a/warna.txt
5164 INFO: checking PYZ
5164 INFO: Building PYZ because out00-PYZ.toc is non existent
5164 INFO: Building PYZ (ZlibArchive) /Users/viotti/testtkinter/build/a/out00-PYZ.pyz
5345 INFO: checking PKG
5345 INFO: Building PKG because out00-PKG.toc is non existent
5345 INFO: Building PKG (CArchive) out00-PKG.pkg
5353 INFO: Bootloader /Users/viotti/testtkinter/a/lib/python3.4/site-packages/PyInstaller/bootloader/Darwin-64bit/run
5353 INFO: checking EXE
5353 INFO: Building EXE because out00-EXE.toc is non existent
5353 INFO: Building EXE from out00-EXE.toc
5360 INFO: Appending archive to EXE /Users/viotti/testtkinter/build/a/a
5361 INFO: Fixing EXE for code signing /Users/viotti/testtkinter/build/a/a
5379 INFO: checking COLLECT
5379 INFO: Building COLLECT because out00-COLLECT.toc is non existent
5379 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
  File "/Users/viotti/testtkinter/a/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "/Users/viotti/testtkinter/a/lib/python3.4/site-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/Users/viotti/testtkinter/a/lib/python3.4/site-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/Users/viotti/testtkinter/a/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/viotti/testtkinter/a/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "/Users/viotti/testtkinter/a/lib/python3.4/site-packages/PyInstaller/building/api.py", line 653, in __init__
    self.__postinit__()
  File "/Users/viotti/testtkinter/a/lib/python3.4/site-packages/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/Users/viotti/testtkinter/a/lib/python3.4/site-packages/PyInstaller/building/api.py", line 681, in assemble
    os.makedirs(todir)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/viotti/testtkinter/dist/a/tcl/tzdata'
```

This is my environment:
- Mac OS X 10.11.2 BuildVersion 15C50.
- Python 3.4.3 from [PSF](http://www.python.org/).
- ActiveTcl 8.5.18.0 (as suggested on http://www.python.org/download/mac/tcltk/).
- Pyinstaller 3.0.

After installing Python 3.4.3 and ActiveTcl these are the steps to reproduce the problem.

```
pyvenv a
. a/bin/activate
pip install pyinstaller
echo 'import tkinter' > a/a.py
cd a
pyinstaller a.py
```

I've traced the problem to `pyinstaller` copying the `Tcl` binary from `/Library/Frameworks/Tcl.framework/Versions/8.5` to the `dist` directory, and then trying to copy the `Resources/Scripts` folder as `tcl` in that same directory. Mac OS X filesystems are usually case insensitive, so a `Tcl` (capital T) file and a `tcl` (lowercase) folder cannot coexist as siblings, hence the error. The same reasoning applies to `Tk`.

**Comment by jhargis** [comment]
Confirmed with pyinstaller current HEAD @ 9c4a08f

**Comment by htgoebel** [comment]
The relevant code-part is:
```
            if not os.path.exists(todir):
                os.makedirs(todir)
```
So I'd assume this is a bug in Python:-(

**Comment by jhargis** [comment]
@htgoebel I suspect you are right.  When I build against the pre installed version of Python for osx 10.7.5, which is ..
```
Python 2.7.1 (r271:86832, Jun 16 2011, 16:59:05)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
```
It works.    

With latest Python 2.7.11, I see same failures occurring for Tk and Tcl in the CI tests 

https://travis-ci.org/pyinstaller/pyinstaller-osx-tests/jobs/100706541#L2245

**Comment by htgoebel** [comment]
I checked the Python source revisions and can not spot any change related to this between 2.7.1 and 3.4.4. So I revise my assumption that this is a bug in Python.

**Comment by viotti** [comment]
In any case having a binary file and a folder under the same path, with names differing only by capitalization seems dangerous to me. This is what I did to fix the problem: https://github.com/pyinstaller/pyinstaller/issues/1737.

**Comment by jimbo1qaz** [comment]
I encountered the same bug... I'm building a program... but it only works on Windows.

Assume `cd /dist/program`.

On Windows:
- pyinstaller writes to `program.exe`
- I store resources in `program\gui\...` both when running from `python -m program` and via PyInstaller.
    - `Analysis(...datas=[('file.xml', 'program/gui')...]...)`

On Linux:
- pyinstaller writes to `program`
- I store resources in `program/gui/...`

And you can't create a subdirectory of a binary program.

Maybe PyInstaller should raise a better error message when this happens.

**Comment by rokm** [comment]
Closing this as the reported version of python (3.4) is not supported anymore.

Recent commits should take care of lingering issues with `tkinter` and Tcl/Tk on macOS for supported python versions. If you encounter any `tkinter`-related issues with those, please open a new issue with updated details.
