### ISSUE TITLE
No module named django. core.cache.backends.locmem

### ISSUE THREAD

**Issue by uayyappa** [pyinstaller/pyinstaller#1738]
When i am executing the django project with 

mysite.exe runserver localhost:8080

I am getting the following error.
```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
399, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 242,
 in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 280,
 in execute
    translation.activate('en-us')
  File "C:\Python27\lib\site-packages\django\utils\translation\__init__.py", lin
e 130, in activate
    return _trans.activate(language)
  File "C:\Python27\lib\site-packages\django\utils\translation\trans_real.py", l
ine 188, in activate
    _active.value = translation(language)
  File "C:\Python27\lib\site-packages\django\utils\translation\trans_real.py", l
ine 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "C:\Python27\lib\site-packages\django\utils\translation\trans_real.py", l
ine 159, in _fetch
    app = import_module(appname)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in im
port_module
    __import__(name)
  File "c:\python27\lib\site-packages\PyInstaller-3.1.dev0-py2.7.egg\PyInstaller
\loader\pyimod03_importers.py", line 382, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python27\lib\site-packages\django\contrib\auth\__init__.py", line 6,
in <module>
    from django.middleware.csrf import rotate_token
  File "c:\python27\lib\site-packages\PyInstaller-3.1.dev0-py2.7.egg\PyInstaller
\loader\pyimod03_importers.py", line 382, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python27\lib\site-packages\django\middleware\csrf.py", line 14, in <m
odule>
    from django.utils.cache import patch_vary_headers
  File "c:\python27\lib\site-packages\PyInstaller-3.1.dev0-py2.7.egg\PyInstaller
\loader\pyimod03_importers.py", line 382, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python27\lib\site-packages\django\utils\cache.py", line 26, in <modul
e>
    from django.core.cache import get_cache
  File "c:\python27\lib\site-packages\PyInstaller-3.1.dev0-py2.7.egg\PyInstaller
\loader\pyimod03_importers.py", line 382, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python27\lib\site-packages\django\core\cache\__init__.py", line 138,
in <module>
    cache = get_cache(DEFAULT_CACHE_ALIAS)
  File "C:\Python27\lib\site-packages\django\core\cache\__init__.py", line 130,
in get_cache
    "Could not find backend '%s': %s" % (backend, e))
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend
 'django.core.cache.backends.locmem.LocMemCache': Error importing module django.
core.cache.backends.locmem: "No module named locmem"
manage returned -1
```

**Comment by htgoebel** [comment]
Obviously some django backend is missing. Please refer to https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Executable-From-Django and esp. the very last paragraph.

**Comment by htgoebel** [comment]
Got no further info since one month now. Closing.

**Comment by mohanraj-r** [comment]
I was facing the same issue.
Adding `from django.core.cache.backends import locmem` to `manage.py` seems to have fixed the issue. Had to rinse and repeat for a bunch of other import errors as well. 

Thanks for the pointer @htgoebel
