### ISSUE TITLE
Crash when building

### ISSUE THREAD

**Issue by Insoleet** [pyinstaller/pyinstaller#1739]
Hello,

I'd like to discover pyinstaller to compare it to cx_Freeze. But I'm having a strange crash when trying to build my app with it : 

```
(sakia-env) ➜  sakia git:(feature/explorer_tab) ✗ pyinstaller src/sakia/main.py
46 INFO: PyInstaller: 3.0
46 INFO: Python: 3.5.0
46 INFO: Platform: Linux-4.2.5-1-ARCH-x86_64-with-arch
47 INFO: wrote /home/inso/code/ucoin/sakia/main.spec
48 INFO: UPX is not available.
49 INFO: Extending PYTHONPATH with /home/inso/code/ucoin/sakia/src
49 INFO: checking Analysis
49 INFO: Building Analysis because out00-Analysis.toc is non existent
50 INFO: Initializing module dependency graph...
50 INFO: Initializing module graph hooks...
51 INFO: Analyzing base_library.zip ...
3200 INFO: running Analysis out00-Analysis.toc
3227 INFO: Analyzing /home/inso/code/ucoin/sakia/src/sakia/main.py
7664 INFO: Processing pre-find module path hook   distutils
10247 INFO: Processing pre-find module path hook   site
10247 INFO: site: retargeting to fake-dir '/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/fake-modules'
13475 INFO: Looking for import hooks ...
13478 INFO: Processing hook   hook-PyQt5.QtGui.py
13808 INFO: Processing hook   hook-PyQt5.QtSvg.py
13810 INFO: Processing hook   hook-PyQt5.QtCore.py
13870 INFO: Processing hook   hook-setuptools.py
13871 INFO: Processing hook   hook-requests.py
13873 INFO: Processing hook   hook-PyQt5.QtWidgets.py
13874 INFO: Processing hook   hook-distutils.py
13875 INFO: Processing hook   hook-sysconfig.py
13876 INFO: Processing hook   hook-PyQt5.py
13929 INFO: Processing hook   hook-PyQt5.QtNetwork.py
13983 INFO: Processing hook   hook-pydoc.py
13983 INFO: Processing hook   hook-encodings.py
13996 INFO: Processing hook   hook-jsonschema.py
13997 INFO: Processing hook   hook-xml.py
14054 INFO: Processing hook   hook-xml.etree.cElementTree.py
14054 INFO: Processing hook   hook-xml.sax.py
14055 INFO: Processing hook   hook-PyQt5.Qt.py
14124 INFO: Looking for ctypes DLLs
14200 WARNING: library libsodium-{0} required via ctypes not found
14237 WARNING: library tweetnacl required via ctypes not found
14271 WARNING: library libsodium.dylib required via ctypes not found
14304 WARNING: library tweetnacl.dylib required via ctypes not found
14365 WARNING: library /usr/local/lib/libsodium.so required via ctypes not found
14399 WARNING: library libsodium.so.{0} required via ctypes not found
14434 WARNING: library tweetnacl.so required via ctypes not found
Traceback (most recent call last):
  File "/home/inso/.pyenv/versions/sakia-env/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 207, in __init__
    self.__postinit__()
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 468, in assemble
    ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/depend/utils.py", line 181, in scan_code_for_ctypes
    elif binary != os.path.basename(binary):
  File "/home/inso/.pyenv/versions/3.5.0/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'tuple' object has no attribute 'rfind'
```

Any idea what is going on ?
Thanks in advance,

**Comment by htgoebel** [comment]
This is a know bug which is already fixed. Please use the current development version, see https://github.com/pyinstaller/pyinstaller/wiki#downloads
