### ISSUE TITLE
jsonschema hook is broken - missing __spec__ module attr for Python 3.4+

### ISSUE THREAD

**Issue by Insoleet** [pyinstaller/pyinstaller#1740]
Hello,

I'm not mastering pyinstaller enough to be able to do a PR, so I'm just creating the ticket, sorry.

https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-jsonschema.py

```python

from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('jsonschema')
```

The files are not included in the binary but in next to it, in a folder "jsonschema". Thus, it fails to start because it is trying to use `pkgutil.get_data` to load the files : 

```
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 382, in load_module
    exec(bytecode, module.__dict__)
  File "jsonschema/__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 382, in load_module
    exec(bytecode, module.__dict__)
  File "jsonschema/validators.py", line 163, in <module>
  File "jsonschema/_utils.py", line 57, in load_schema
  File "pkgutil.py", line 611, in get_data
  File "importlib/util.py", line 102, in find_spec
ValueError: jsonschema.__spec__ is None
main returned -1
```

**Comment by matysek** [comment]
I also confirm that simple `import jsonschema` causes this error.

**Comment by matysek** [comment]
It should be fixed in `develop`. PyInstaller will now set module attribute `__spec__` properly.
