### ISSUE TITLE
Tkinter Issue

### ISSUE THREAD

**Issue by rankinstudio** [pyinstaller/pyinstaller#1742]
Using Py3.4 and pyinstaller 3

Ran:
pyinstaller.exe --onefile --windowed -import=Tkinter C:\N.py

Output:
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\David>cd desktop/pyins

C:\Users\David\Desktop\pyins>pyinstaller.bat

C:\Users\David\Desktop\pyins>pyinstaller.exe --onefile --windowed -import=Tkinte
r C:\Users\David\PycharmProjects\Comets\N.py
62 INFO: PyInstaller: 3.0
62 INFO: Python: 3.4.3
62 INFO: Platform: Windows-8-6.2.9200
62 INFO: wrote C:\Users\David\Desktop\pyins\N.spec
62 INFO: UPX is not available.
62 INFO: Extending PYTHONPATH with C:\Users\David\PycharmProjects\Comets
62 INFO: checking Analysis
78 INFO: Building Analysis because out00-Analysis.toc is non existent
78 INFO: Initializing module dependency graph...
80 INFO: Initializing module graph hooks...
82 INFO: Analyzing base_library.zip ...
2613 INFO: Processing pre-find module path hook   distutils
4602 INFO: running Analysis out00-Analysis.toc
5629 INFO: Analyzing C:\Users\David\PycharmProjects\Comets\N.py
9792 INFO: Processing pre-find module path hook   site
9792 INFO: site: retargeting to fake-dir 'C:\\Python34\\lib\\site-packages\\PyIn
staller\\fake-modules'
14173 INFO: Processing pre-safe import module hook   six.moves
19469 INFO: Looking for import hooks ...
19473 INFO: Processing hook   hook-win32com.client.py
19473 INFO: Processing hook   hook-xml.py
19473 INFO: Processing hook   hook-matplotlib.backends.py
20146 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
20668 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
21013 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
21527 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
22045 INFO:   Matplotlib backend "Qt4Agg": ignored
    No module named 'PySide'
22558 INFO:   Matplotlib backend "Qt5Agg": ignored
    No module named 'PySide'
23081 INFO:   Matplotlib backend "TkAgg": added
23463 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxversion, which was not fou
nd.
23995 INFO:   Matplotlib backend "WXAgg": ignored
    Matplotlib backend_wx and backend_wxagg require wxversion, which was not fou
nd.
24331 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
24869 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
25206 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\matplotlib\backends\backend_webagg.py", li
ne 28, in <module>
    import tornado
ImportError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Python34\lib\site-packages\matplotlib\backends\backend_webagg.py", li
ne 30, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
25558 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'tornado'
26082 INFO:   Matplotlib backend "agg": added
26426 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
26771 INFO:   Matplotlib backend "emf": ignored
    No module named 'matplotlib.backends.backend_emf'
27125 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
27641 INFO:   Matplotlib backend "pdf": added
28495 INFO:   Matplotlib backend "pgf": added
29013 INFO:   Matplotlib backend "ps": added
29517 INFO:   Matplotlib backend "svg": added
30036 INFO:   Matplotlib backend "template": added
30278 INFO: Processing hook   hook-xml.sax.py
30279 INFO: Processing hook   hook-_tkinter.py
30489 INFO: checking Tree
30522 INFO: checking Tree
30554 INFO: Processing hook   hook-pythoncom.py
30877 INFO: Processing hook   hook-pydoc.py
30878 INFO: Processing hook   hook-pytz.py
31015 INFO: Processing hook   hook-PIL.py
31015 INFO: Excluded import 'PySide' not found
31015 INFO: Excluding import 'tkinter'
31015 WARNING:   Removing import 'tkinter.commondialog'
31015 WARNING:   Removing import 'tkinter.messagebox'
31015 WARNING:   Removing import 'tkinter.messagebox'
31015 WARNING:   Removing import 'tkinter.filedialog'
31015 WARNING:   Removing import 'tkinter.constants'
31015 WARNING:   Removing import 'tkinter.dialog'
31015 WARNING:   Removing import 'tkinter._fix'
31015 WARNING:   Removing import 'tkinter.filedialog'
31015 WARNING:   Removing import 'tkinter'
31015 INFO: Excluded import 'FixTk' not found
31015 INFO: Excluding import 'PyQt5'
31015 INFO: Excluding import 'PyQt4'
31015 INFO: Processing hook   hook-pywintypes.py
31337 INFO: Processing hook   hook-scipy.sparse.csgraph.py
31337 INFO: Processing hook   hook-setuptools.py
31337 INFO: Processing hook   hook-encodings.py
31375 INFO: Processing hook   hook-PIL.Image.py
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 783, in _updateReference
    ed = self.edgeData(fromnode, tonode)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\altgraph\ObjectGraph.py",
line 89, in edgeData
    return self.graph.edge_data(edge)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\altgraph\Graph.py", line 2
96, in edge_data
    return self.edges[edge][2]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\PyInstaller\lib\altgraph\Graph.py", line 1
10, in add_edge
    self.nodes[tail_id][0].append(edge)
KeyError: 'tkinter._fix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 47, in run_
build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)

  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line
737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line
680, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line
207, in __init__
    self.__postinit__()
  File "C:\Python34\lib\site-packages\PyInstaller\building\datastruct.py", line
156, in __postinit__
    self.assemble()
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line
430, in assemble
    imphook_object.update_dependencies(self.graph)
  File "C:\Python34\lib\site-packages\PyInstaller\building\imphook.py", line 341
, in update_dependencies
    self._process_hiddenimports(mod_graph)
  File "C:\Python34\lib\site-packages\PyInstaller\building\imphook.py", line 209
, in _process_hiddenimports
    self._process_one_hiddenimport(item, mod_graph)
  File "C:\Python34\lib\site-packages\PyInstaller\building\imphook.py", line 217
, in _process_one_hiddenimport
    mod_graph.import_hook(item, caller=caller)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 892, in import_hook
    m = self._load_tail(q, tail)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 997, in _load_tail
    result = self._safe_import_module(head, mname, result)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 204,
 in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1178, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1257, in _load_module
    self._scan_code(co, m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1435, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1553, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1387, in _safe_import_hook
    sm = self.import_hook(name, caller, fromlist=[sub], level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 895, in import_hook
    for s in self._ensure_fromlist(m, fromlist):
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1021, in _ensure_fromlist
    submod = self._safe_import_module(sub, fullname, m)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 204,
 in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1178, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1257, in _load_module
    self._scan_code(co, m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1435, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1553, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1280, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 891, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 975, in _find_head_package
    q = self._safe_import_module(head, qname, parent)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 204,
 in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1178, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1210, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1597, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1257, in _load_module
    self._scan_code(co, m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1435, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1553, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 1370, in _safe_import_hook
    self._updateReference(caller, sm, edge_data=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 785, in _updateReference
    return self.createReference(fromnode, tonode, edge_data)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py
", line 797, in createReference
    return super(ModuleGraph, self).createReference(fromnode, tonode, edge_data=
edge_data)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\altgraph\ObjectGraph.py",
line 194, in createReference
    self.graph.add_edge(fromident, toident, edge_data=edge_data)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\altgraph\Graph.py", line 1
13, in add_edge
    raise GraphError('Invalid nodes %s -> %s' % (head_id, tail_id))
PyInstaller.lib.altgraph.GraphError: Invalid nodes tkinter -> tkinter._fix

C:\Users\David\Desktop\pyins>

**Comment by matysek** [comment]
@rankinstudio This issue looks similar to #1660. Could you confirm this?

**Comment by rankinstudio** [comment]
I'm not using Tix? Here is my import list:

import scipy
import scipy.misc
import math
import matplotlib.pyplot as plt
import numpy as np
from scipy.ndimage import label
import scipy.ndimage.measurements
from scipy.sparse.csgraph import _validation
from scipy import ndimage
from tkinter import *
from tkinter.filedialog import askopenfilenames

Should I try the dev version? 

Thanks!

**Comment by rankinstudio** [comment]
--hidden-import=tkinter seems to have fixed that error. Now when it finishes, the .exe file returns a fatal error -1. How can I determine what is causing this?

Ran:
pyinstaller.exe --onefile --windowed --hidden-import=tkinter --hidden-import=scipy --hidden-import=matplotlib --hidden-import=fixtk C:\Users\David\PycharmProjects\Comets\N.py

C:\Users\David\Desktop\pyins>pyinstaller.bat

C:\Users\David\Desktop\pyins>pyinstaller.exe --onefile --windowed --hidden-impor
t=tkinter --hidden-import=scipy --hidden-import=matplotlib --hidden-import=fixtk
 C:\Users\David\PycharmProjects\Comets\N.py
78 INFO: PyInstaller: 3.0
78 INFO: Python: 3.4.3
78 INFO: Platform: Windows-8-6.2.9200
78 INFO: wrote C:\Users\David\Desktop\pyins\N.spec
78 INFO: UPX is not available.
78 INFO: Extending PYTHONPATH with C:\Users\David\PycharmProjects\Comets
93 INFO: checking Analysis
259 INFO: checking PYZ
327 INFO: checking PKG
409 INFO: Building because C:\Users\David\Desktop\pyins\build\N\N.exe.manifest c
hanged
409 INFO: Building PKG (CArchive) out00-PKG.pkg
22326 INFO: Bootloader C:\Python34\lib\site-packages\PyInstaller\bootloader\Wind
ows-32bit\runw.exe
22326 INFO: checking EXE
22329 INFO: Building because out00-EXE.toc is bad
22329 INFO: Building EXE from out00-EXE.toc
22336 INFO: Appending archive to EXE C:\Users\David\Desktop\pyins\dist\N.exe

C:\Users\David\Desktop\pyins>

**Comment by rankinstudio** [comment]
Got it fixed by running the script without --onefile. I could see the error was coming from a scipy module now. This scrip worked after importing scipy.integrate.

Thanks for an awesome compiler! Had way more luck with this one than cx freeze or py2exe.

pyinstaller.exe --onefile --windowed --hidden-import=tkinter --hidden-import=scipy --hidden-import=matplotlib --hidden-import=fixtk --hidden-import=scipy.integrate C:\Users\David\PycharmProjects\Comets\N.py

**Comment by matysek** [comment]
@rankinstudio could you please try the `develop` version for your app without the `hidden-import` option?

**Comment by rankinstudio** [comment]
Its working now.

**Comment by matysek** [comment]
Thanks for confirming that it is fixed in the `develop` version. Closing.
