### ISSUE TITLE
How to use pyinstaller to build “pyjnius” project

### ISSUE THREAD

**Issue by Mingo-Wild** [pyinstaller/pyinstaller#1745]
I fork a project https://github.com/Mingo-Wild/tikadetect. I want to build it into a executable file,but I get this errors:
```
ImportError: 'No module named platform' in 'jnius.create_jnienv' ignor
ed
Traceback (most recent call last):
File "", line 18, in 
File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
line 363, in load_module
exec(bytecode, module.dict)
File "C:\Python27\lib\site-packages\jnius__init__.py", line 13, in 
from .reflect import *
File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
line 363, in load_module
exec(bytecode, module.dict)
File "C:\Python27\lib\site-packages\jnius\reflect.py", line 6, in 
class Class(JavaClass):
File "jnius\jnius_export_class.pxi", line 31, in jnius.MetaJavaClass.new (
jnius\jnius.c:9243)
File "jnius\jnius_export_class.pxi", line 51, in jnius.MetaJavaClass.resolve_c
lass (jnius\jnius.c:9608)
jnius.JavaException: Unable to get the JNI Environment
tikadetect returned -1
```
what can i do? thank you

**Comment by htgoebel** [comment]
Please have a look at [If Things Go Wrong](https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). If this does not help, I suggest asking the mingo-wild community for requirements or such.
