### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 1313: invalid continuation byte

### ISSUE THREAD

**Issue by a691662** [pyinstaller/pyinstaller#1775]
when i compile any python34 scripts with matplotlib, this error will show up

**Comment by htgoebel** [comment]
This sounds more like an encoding-problem in on of your files.
Please provide more information: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by a691662** [comment]
Thanks for reply.

here is more info:

pyinstaller C:\pyqttest\test2.py -a -y --clean --debug
56 INFO: PyInstaller: 3.2.dev0+5427395
56 INFO: Python: 3.4.3
56 INFO: Platform: Windows-8-6.2.9200
57 INFO: wrote C:\pyqttest\release\test2.spec
59 INFO: UPX is not available.
59 INFO: Removing temporary files and cleaning cache in C:\Users\Tom\AppData\Roaming\pyinstaller
60 INFO: Extending PYTHONPATH with paths
['C:\\pyqttest', 'C:\\pyqttest\\release']
61 INFO: checking Analysis
61 INFO: Building Analysis because out00-Analysis.toc is non existent
61 INFO: Initializing module dependency graph...
62 INFO: Initializing module graph hooks...
64 INFO: Analyzing base_library.zip ...
1489 INFO: Processing pre-find module path hook   distutils
2524 INFO: running Analysis out00-Analysis.toc
2569 INFO: Analyzing C:\pyqttest\test2.py
4709 INFO: Processing pre-find module path hook   site
4710 INFO: site: retargeting to fake-dir 'C:\\Python34\\lib\\site-packages\\PyInstaller\\fake-modules'
4728 INFO: Processing pre-safe import module hook   win32com
6129 INFO: Processing pre-safe import module hook   six.moves
Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2.dev0+5427395', 'console_scripts', 'pyinstaller')()
  File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "C:\Python34\lib\site-packages\PyInstaller\building\datastruct.py", line 183, in __postinit__
    self.assemble()
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 388, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 144, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 886, in run_script
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1469, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1582, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1310, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 900, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 984, in _find_head_package
    q = self._safe_import_module(head, qname, parent)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1205, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1237, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1628, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1289, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1469, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1582, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1310, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 901, in import_hook
    m = self._load_tail(q, tail)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1006, in _load_tail
    result = self._safe_import_module(head, mname, result)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1205, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1289, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1469, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1582, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1310, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 900, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 984, in _find_head_package
    q = self._safe_import_module(head, qname, parent)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1205, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1289, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1469, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1582, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1310, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 901, in import_hook
    m = self._load_tail(q, tail)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1006, in _load_tail
    result = self._safe_import_module(head, mname, result)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1205, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1289, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1469, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1582, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1310, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 901, in import_hook
    m = self._load_tail(q, tail)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1006, in _load_tail
    result = self._safe_import_module(head, mname, result)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1205, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1289, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1469, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1582, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1310, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 901, in import_hook
    m = self._load_tail(q, tail)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1006, in _load_tail
    result = self._safe_import_module(head, mname, result)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1205, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1289, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1469, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1582, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1418, in _safe_import_hook
    sm = self.import_hook(name, caller, fromlist=[sub], level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 904, in import_hook
    for s in self._ensure_fromlist(m, fromlist):
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1031, in _ensure_fromlist
    submod = self._safe_import_module(sub, fullname, m)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1199, in _safe_import_module
    module_basename, search_dirs, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1678, in _find_module
    return self._find_module_path(fullname, name, path)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 253, in _find_module_path
    fullname, module_name, search_dirs)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1834, in _find_module_path
    file_handle = StringIO(loader.get_source(module_name))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 1313: invalid continuation byte

Process finished with exit code 1

**Comment by a691662** [comment]
This minimal script can raise the error:

```
import matplotlib.pyplot

print('test')
```

**Comment by codewarrior0** [comment]
It is probably `loader.get_source()` throwing the Unicode error.

We need to find out which module is causing the error. Could you run these commands?

```
set MODULEGRAPH_DEBUG=4
pyinstaller C:\pyqttest\test2.py -a -y --clean --debug > pyinstaller.out
```

This will collect the output to a file `pyinstaller.out`, which I will ask you to post to [Gist](https://gist.github.com/) because it will be rather long.

**Comment by a691662** [comment]
Thanks for the help.

Here is the gist of output.txt: https://gist.github.com/a691662/5cdc8aff9fa744e829e0

**Comment by codewarrior0** [comment]
That is bizarre.

The `dateutil` module explicitly declares a Latin-1 encoding, but the loader ignores it and tries to decode it as UTF-8. I wonder if this is a bug in Python? I'll have to investigate this some more.

**Comment by a691662** [comment]
actually it works fine in my the other pc with same python, windows and pyinstall version.

have no idea what happened in this PC. 

Thanks for the help, looking forward you can figure it out.

**Comment by codewarrior0** [comment]
Maybe it started after installing a different version of `dateutil`?  Here is a list of all the versions they released:

https://pypi.python.org/simple/python-dateutil/

**Comment by a691662** [comment]
Oh, it works!

I use ```pip uninstall python_dateutil``` to uninstall the ```dateutil``` and then install it back using  ```pip install python_dateutil```. Then, it works! Even though infomation shows these two ```dateutil``` has same version as 2.42.

Anyway, it works now. Thanks a lot!

**Comment by codewarrior0** [comment]
Glad to hear you got it fixed, and that it wasn't PyInstaller's fault after all. :)
