### ISSUE TITLE
pyi_rth_pkgres returned -1 after exe file is run

### ISSUE THREAD

**Issue by gordeychuk** [pyinstaller/pyinstaller#1786]
Hi everyone,

Python 3.5.1 (have the same issue with python 3.4)
PyInstaller 3.1

I created exe file for my program and tried to run it.

Firstly I got this:

C:\Python35-32\Scripts\TD-Jira\dist1\TDJ_Comp>TDJ_Comp.exe
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 74, in <module>
  File "site-packages\pkg_resources\extern\__init__.py", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
pyi_rth_pkgres returned -1

After that I googled and found that this could be related with permissions and I run my program from Command Prompt as Administrator and I got this (with debug key):

C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp>TDJ_Comp.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp\TDJ_Comp.exe
LOADER: homepath is C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp\TDJ_Comp.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp\base_library.zip;C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp
LOADER: sys.prefix is C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp\base_library.zip;C:\Python35-32\Scripts\TD-Jira\dist3\TDJ_Comp
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_pkgres.py
pkg_resources.extern.packaging
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 74, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "site-packages\pkg_resources\extern\__init__.py", line 57, in load_module
TypeError: Can't convert 'NoneType' object to str implicitly
pyi_rth_pkgres returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.

========

I tried to install packaging module using pip but it doesn't help.

Any ideas how to fix it?

**Comment by gordeychuk** [comment]
Solved by downgrading setuptools from 19.4 to 19.2
