### ISSUE TITLE
AttributeError: module 'requests' has no attribute 'get'

### ISSUE THREAD

**Issue by dimaqq** [pyinstaller/pyinstaller#1788]
* Python 3.5.1
* virtualenv
* PyInstaller==3.1
* requests==2.9.1

foo.py:
```py
import requests
requests.get
```

pyinstaller foo.py
./dist/foo/foo

```bash
(v35)[dima@bmg test567458]$ ./dist/foo/foo 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'requests' has no attribute 'get'
foo returned -1
```

**Comment by htgoebel** [comment]
Duplicate, see #1773

**Comment by dimaqq** [comment]
Build log

```bash
(v35)[dima@bmg test567458]$ pyinstaller foo.py 
26 INFO: PyInstaller: 3.1
26 INFO: Python: 3.5.1
27 INFO: Platform: Linux-4.3.3-2-ARCH-x86_64-with-arch
27 INFO: wrote /dima/test567458/foo.spec
28 INFO: UPX is not available.
29 INFO: Extending PYTHONPATH with paths
['/dima/test567458', '/dima/test567458']
29 INFO: checking Analysis
29 INFO: Building Analysis because out00-Analysis.toc is non existent
29 INFO: Initializing module dependency graph...
30 INFO: Initializing module graph hooks...
31 INFO: Analyzing base_library.zip ...
894 INFO: running Analysis out00-Analysis.toc
909 INFO: Analyzing /dima/test567458/foo.py
2000 INFO: Looking for import hooks ...
2002 INFO: Processing hook   hook-xml.py
2028 INFO: Processing hook   hook-encodings.py
2034 INFO: Processing hook   hook-requests.py
2045 INFO: Looking for ctypes DLLs
2078 INFO: Analyzing run-time hooks ...
2088 INFO: Looking for dynamic libraries
2316 INFO: Looking for eggs
2316 INFO: Using Python library /usr/lib/libpython3.5m.so.1.0
2323 INFO: Warnings written to /dima/test567458/build/foo/warnfoo.txt
2327 INFO: checking PYZ
2327 INFO: Building PYZ because out00-PYZ.toc is non existent
2327 INFO: Building PYZ (ZlibArchive) /dima/test567458/build/foo/out00-PYZ.pyz
2487 INFO: checking PKG
2488 INFO: Building PKG because out00-PKG.toc is non existent
2488 INFO: Building PKG (CArchive) out00-PKG.pkg
2497 INFO: Bootloader /dima/v35/lib/python3.5/site-packages/PyInstaller/bootloader/Linux-64bit/run
2497 INFO: checking EXE
2497 INFO: Building EXE because out00-EXE.toc is non existent
2497 INFO: Building EXE from out00-EXE.toc
2498 INFO: Appending archive to EXE /dima/test567458/build/foo/foo
2499 INFO: checking COLLECT
2499 INFO: Building COLLECT because out00-COLLECT.toc is non existent
2499 INFO: Building COLLECT out00-COLLECT.toc
```

cat warnfoo.txt | grep req
```txt
missing module named binascii.hexlify - imported by binascii, requests.packages.urllib3.util.ssl_
missing module named binascii.unhexlify - imported by binascii, requests.packages.urllib3.util.ssl_
missing module named select.select - imported by select, requests.packages.urllib3.util.connection
missing module named select.poll - imported by select, requests.packages.urllib3.util.connection
missing module named select.POLLIN - imported by select, requests.packages.urllib3.util.connection
missing module named threading.RLock - imported by threading, _threading_local, bz2, requests.packages.urllib3._collections, /dima/test567458/foo.py
missing module named sys.version_info - imported by sys, requests.packages.chardet
missing module named chardet - imported by requests.packages
missing module named urllib3 - imported by requests.packages
missing module named ssl.OP_NO_COMPRESSION - imported by ssl, requests.packages.urllib3.util.ssl_
missing module named ssl.OP_NO_SSLv2 - imported by ssl, requests.packages.urllib3.util.ssl_
missing module named ssl.OP_NO_SSLv3 - imported by ssl, requests.packages.urllib3.util.ssl_
missing module named ssl.PROTOCOL_SSLv23 - imported by ssl, requests.packages.urllib3.util.ssl_
missing module named socket._fileobject - imported by socket, requests.packages.urllib3.contrib.pyopenssl
missing module named socket.timeout - imported by socket, requests.packages.urllib3.connectionpool, requests.packages.urllib3.connection, requests.packages.urllib3.response, requests.packages.urllib3.contrib.pyopenssl
missing module named socket.error - imported by socket, requests.packages.urllib3.connectionpool, requests.packages.urllib3.connection, requests.packages.urllib3.response, requests.packages.urllib3.contrib.pyopenssl
missing module named hashlib.md5 - imported by hashlib, requests.packages.urllib3.util.ssl_, uuid
missing module named hashlib.sha256 - imported by hashlib, requests.packages.urllib3.util.ssl_
missing module named hashlib.sha1 - imported by hashlib, requests.packages.urllib3.util.ssl_, uuid
missing module named 'requests.packages.urllib3.packages.six.moves'.http_client - imported by 'requests.packages.urllib3.packages.six.moves', requests.packages.urllib3.util.response, requests.packages.urllib3.response
missing module named 'requests.packages.urllib3.packages.six.moves' - imported by requests.packages.urllib3.util.response, requests.packages.urllib3.response
missing module named StringIO - imported by requests.packages.urllib3.packages.six, requests.compat
missing module named StringIO.StringIO - imported by StringIO, requests.compat
missing module named backports.CertificateError - imported by backports, requests.packages.urllib3.packages.ssl_match_hostname
missing module named backports.match_hostname - imported by backports, requests.packages.urllib3.packages.ssl_match_hostname
missing module named backports - imported by requests.packages.urllib3.packages.ssl_match_hostname
missing module named httplib.HTTPException - imported by httplib, requests.packages.urllib3.connection
missing module named httplib.HTTPConnection - imported by httplib, requests.packages.urllib3.connection
missing module named httplib - imported by requests.packages.urllib3.connection
missing module named urllib.quote - imported by urllib, requests.compat
missing module named urllib.unquote_plus - imported by urllib, requests.compat
missing module named urllib.unquote - imported by urllib, requests.compat
missing module named urllib.getproxies - imported by urllib, requests.compat
missing module named urllib.proxy_bypass - imported by urllib, requests.compat
missing module named urllib.quote_plus - imported by urllib, requests.compat
missing module named urllib.urlencode - imported by urllib, requests.packages.urllib3.request, requests.compat
missing module named _abcoll.ItemsView - imported by _abcoll, requests.packages.urllib3.packages.ordered_dict
missing module named _abcoll.ValuesView - imported by _abcoll, requests.packages.urllib3.packages.ordered_dict
missing module named _abcoll.KeysView - imported by _abcoll, requests.packages.urllib3.packages.ordered_dict
missing module named _abcoll - imported by requests.packages.urllib3.packages.ordered_dict
missing module named dummy_thread.get_ident - imported by dummy_thread, requests.packages.urllib3.packages.ordered_dict
missing module named dummy_thread - imported by requests.packages.urllib3.packages.ordered_dict
missing module named thread.get_ident - imported by thread, requests.packages.urllib3.packages.ordered_dict
missing module named thread - imported by requests.packages.urllib3.packages.ordered_dict
missing module named urlparse.urljoin - imported by urlparse, requests.packages.urllib3.poolmanager, requests.compat
missing module named urlparse - imported by requests.packages.urllib3.poolmanager, requests.compat
missing module named urlparse.urlunparse - imported by urlparse, requests.compat
missing module named urlparse.urlsplit - imported by urlparse, requests.compat
missing module named urlparse.urlparse - imported by urlparse, requests.compat
missing module named urlparse.urldefrag - imported by urlparse, requests.compat
missing module named winreg - imported by mimetypes, platform, urllib.request
missing module named Queue.Full - imported by Queue, requests.packages.urllib3.connectionpool
missing module named Queue.Empty - imported by Queue, requests.packages.urllib3.connectionpool
missing module named Queue.LifoQueue - imported by Queue, requests.packages.urllib3.connectionpool
missing module named Queue - imported by requests.packages.urllib3.connectionpool
missing module named _scproxy._get_proxy_settings - imported by _scproxy, urllib.request
missing module named _scproxy._get_proxies - imported by _scproxy, urllib.request
missing module named _scproxy - imported by urllib.request
missing module named Cookie.Morsel - imported by Cookie, requests.compat
missing module named Cookie - imported by requests.compat
missing module named cookielib - imported by requests.compat
missing module named urllib2.parse_http_list - imported by urllib2, requests.compat
missing module named urllib2 - imported by requests.compat
missing module named simplejson - imported by requests.compat
missing module named certifi.where - imported by certifi, requests.certs
missing module named certifi - imported by requests.certs
missing module named 'pyasn1.type'.univ - imported by 'pyasn1.type', requests.packages.urllib3.contrib.pyopenssl
missing module named 'pyasn1.type'.constraint - imported by 'pyasn1.type', requests.packages.urllib3.contrib.pyopenssl
missing module named 'pyasn1.type' - imported by requests.packages.urllib3.contrib.pyopenssl
missing module named pyasn1.decoder - imported by pyasn1, requests.packages.urllib3.contrib.pyopenssl
missing module named pyasn1 - imported by requests.packages.urllib3.contrib.pyopenssl
missing module named OpenSSL - imported by requests.packages.urllib3.contrib.pyopenssl
missing module named 'ndg.httpsclient'.SubjectAltName - imported by 'ndg.httpsclient', requests.packages.urllib3.contrib.pyopenssl
missing module named 'ndg.httpsclient' - imported by requests.packages.urllib3.contrib.pyopenssl
missing module named ndg.SUBJ_ALT_NAME_SUPPORT - imported by ndg, requests.packages.urllib3.contrib.pyopenssl
missing module named ndg - imported by requests.packages.urllib3.contrib.pyopenssl
```

**Comment by htgoebel** [comment]
Sorry, I've been to qucik in closing this one.

**Comment by dimaqq** [comment]
I've traced it down to:

```py
Traceback (most recent call last):
  File "<string>", line 89, in <module>
ImportError: No module named 'requests.adapters'
```

which also happens if there's an explicit `import requests.adapters`, but here I'm stuck -- there's nothing else in the traceback!

**Comment by dimaqq** [comment]
I'd like to help, if I can.
How do I go about debugging what modules are included?
I've checked `pyi-archive_viewer` and requests' modules are not included at all, apparently.

**Comment by htgoebel** [comment]
That's a very good idea :-) You'll find tips at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged

**Comment by sfpprxy** [comment]
I got the same problem here.
Python 3.5.0
PyInstaller==3.1
requests==2.9.1

Any new progress?

**Comment by htgoebel** [comment]
> Same thing happened when use py2exe, cx_freeze and so on.

So it does not seam to be a PyInstaller problem. Maybe one of you should talk to the `requests` developers.

**Comment by ironchef** [comment]
As a counterpoint, I have requests=2.9.1 with Python 3.4 and py2exe compiling fine.

**Comment by sfpprxy** [comment]
Can you post your compiling configuration(like setup.py) please?

**Comment by ironchef** [comment]
Sure...this is what I use on py2exe:

    from distutils.core import setup
    from glob import glob
    import py2exe


    #This includes the msvcp100.dll and MSVCR100.dll
    data_files = [("Microsoft.VC100.CRT", glob(r'z:\vm_shared\snapshot\*.dll')),
                  ("", ["csv.xsl", "logging_config.ini"])]

    setup(console=[
    ... #Redacted as it's priv company code..just a bunch of internal python script
    ... #  that are used by the main py / exe
                  ],
          #new
          data_files=data_files,
          options={"py2exe":{"includes":["blowfish","envoy","get_generic"]}})
      
    #get_generic is an internal thing which shouldn't matter...

Hope that helps

**Comment by dimaqq** [comment]
Anyone?

**Comment by OpaOnWindowsNow** [comment]
Same problem:
requests==2.8.1
python==3.4
PyInstaller==3.1

Adding a collect_submodules('requests') in hook-requests does not solve the problem even if it add a lot of modules:
----------------
Collecting submodules for requests
- Found submodules: {'requests.exceptions', 'requests.packages.chardet.escsm', 'requests.packages.chardet.jisfreq', 'requests.packages.urllib3.util.retry', ... }
----------------

Inspecting the file (--one-file):
----------------
user@____:/tmp/_MEIpCJ0pw$ find . | grep requests
./requests
./requests/cacert.pem
----------------

If I add a print(dir(requests)); print(requests.__doc__), I obtain:
---------------
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
None
---------------

**Comment by htgoebel** [comment]
Please try PyInstaller version 3.1.1, released a week ago.

**Comment by dimaqq** [comment]
3.1.1 works!
Thanks ;-)

**Comment by sfpprxy** [comment]
3.1.1 works!
Thanks :)
