### ISSUE TITLE
pytest import causes error

### ISSUE THREAD

**Issue by phelix** [pyinstaller/pyinstaller#1789]
I had accidentally imported pytest. This gave me a nasty error.

pyinstaller v3.1, pytest v2.8.5  

```
import pytest
print "hello"
```
result:  
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 48, in <module>
  File "site-packages\pkg_resources\extern\__init__.py", line 60, in load_module
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
pyi_rth_pkgres returned -1
```  

The original project gave me this error:
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\_temp\git\nameGUI\build\nameguiwin\out00-PYZ.pyz\pkg_resources", line 74, in <module>
  File "C:\_temp\git\nameGUI\build\nameguiwin\out00-PYZ.pyz\pkg_resources.extern", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning,
 consult the packager of your distribution.
```  

I could fix it by removing the import or excluding pytest ('--exclude-module=pytest').

**Comment by htgoebel** [comment]
This seams to be an issue with setuptools 19.3, see https://github.com/pyinstaller/pyinstaller/issues/1772#issuecomment-172467268. Please try downgrading setuptools to 19.2. If this does not solve you issue, please reopen the ticket.

**Comment by phelixbtc** [comment]
Yeah, that seems to work for my case, too. At least I got a different error that way ('ImportError: No module named mark'), unfortunalty I am happy with my workaround and don't have time to dive into it.  
Thanks for your help!
