### ISSUE TITLE
win32com DispatchWithEvents fails to launch

### ISSUE THREAD

**Issue by Zyell** [pyinstaller/pyinstaller#1803]
I have a script that leverages DispatchWithEvents from win32com.client.  It compiles without issue under pyinstaller 3.x, but fails to launch as a single file executable or folder.  The script runs without issue normally.  I ran into 3 errors all seemingly originating from a failure to establish the appropriate entries in sys.modules for the win32com.gen_py directory.  I was able to add an entry in sys.modules for each of the 3 errors to allow my compiled script to run.  However, I do not yet understand how pyinstaller might incorporate the fixes to resolve the issue with DispatchWithEvents.  Something that might be of note is that Dispatch functions without issue, only DispatchWithEvents fails.  I have tried pyinstaller 3.0 all the way up to the latest dev version and I am running python 2.7.10.  For what it's worth, it used to work in pyinstaller 2.x.
Adding the following lines to my script allows the resulting exe to run:

``` python
sys.modules['win32com.gen_py.os'] = None
sys.modules['win32com.gen_py.pywintypes'] = None
sys.modules['win32com.gen_py.pythoncom'] = None
```

It also works to point the above entries to the actual modules os, pywintypes, & pythoncom.  When the script runs normally, it creates entries that point to None.

The first error being resolved with the os entry was the following:
Traceback (most recent call last):
  File "<string>", line 783, in <module>
  File "<string>", line 776, in main
  File "site-packages\win32com\client__init__.py", line 252, in DispatchWithEvents
  File "site-packages\win32com\client\gencache.py", line 520, in EnsureModule
  File "site-packages\win32com\client\gencache.py", line 287, in MakeModuleForTypelib
  File "site-packages\win32com\client\makepy.py", line 286, in GenerateFromTypeLibSpec
  File "site-packages\win32com\client\gencache.py", line 550, in AddModuleToCache
  File "site-packages\win32com\client\gencache.py", line 629, in _GetModule
  File "c:\users\user\appdata\local\temp\tmp4mxuxe\gen_py\00062FFF-0000-0000
-C000-000000000046x0x9x5.py", line 10, in <module>
    import win32com.client.CLSIDToClass, pythoncom, pywintypes
  File "C:\Python27\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 158, in load_module
  File "C:\Python27\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\pythoncom.py", line 2, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 158, in load_module
  File "C:\Python27\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\win32\lib\pywintypes.py", line 2, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 158, in load_module
  File "C:\Python27\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "os.py", line 120, in <module>
ImportError: No module named path

While googling this issue I did find this same above error referenced in a closed issue #1601 posted on Nov 3, 2015.
The ImportError above seems to be the same as one found in test_pyttsx and remained unresolved according to the posts on the referenced issue.

The second error being resolved by the pywintypes entry was the following:
Traceback (most recent call last):
  File "<string>", line 790, in <module>
  File "<string>", line 782, in main
  File "site-packages\win32com\client__init__.py", line 252, in DispatchWithEvents
  File "site-packages\win32com\client\gencache.py", line 524, in EnsureModule
  File "site-packages\win32com\client\gencache.py", line 291, in MakeModuleForTypelib
  File "site-packages\win32com\client\makepy.py", line 286, in GenerateFromTypeLibSpec
  File "site-packages\win32com\client\gencache.py", line 554, in AddModuleToCache
  File "site-packages\win32com\client\gencache.py", line 633, in _GetModule
  File "c:\users\user\appdata\local\temp\tmp336ryi\gen_py\00062FFF-0000-0000
-C000-000000000046x0x9x4.py", line 12, in <module>
    from pywintypes import IID
ImportError: cannot import name IID

I at first thought that maybe a hook would be helpful here, but nothing I tried worked until I placed an entry in sys.modules.

The final error being resolved by the pythoncom entry was the following:
Traceback (most recent call last):
  File "<string>", line 790, in <module>
  File "<string>", line 782, in main
  File "site-packages\win32com\client__init__.py", line 252, in DispatchWithEvents
  File "site-packages\win32com\client\gencache.py", line 524, in EnsureModule
  File "site-packages\win32com\client\gencache.py", line 291, in MakeModuleForTypelib
  File "site-packages\win32com\client\makepy.py", line 286, in GenerateFromTypeLibSpec
  File "site-packages\win32com\client\gencache.py", line 554, in AddModuleToCache
  File "site-packages\win32com\client\gencache.py", line 633, in _GetModule
  File "c:\users\user\appdata\local\temp\tmpftqvqv\gen_py\00062FFF-0000-0000
-C000-000000000046x0x9x4.py", line 17, in <module>
    defaultNamedOptArg=pythoncom.Empty
AttributeError: 'module' object has no attribute 'Empty'

While I have managed a workaround for my script, I would like to help get a more permanent fix into pyinstaller.  Thanks for the great library you have created and any help better understanding a permanent fix for this is much appreciated.

**Comment by alancummings** [comment]
Thanks for posting this workaround. I have the exact same issue when the built app tries to import win32com.gen_py.os

This workaround is the only thing that worked for me after several hours of trial & error & google.

**Comment by Kojoley** [comment]
It looks like this hack is not needed in 3.3 anymore.

**Comment by JokerQyou** [comment]
This hack is actually still needed for Windows machines with non-ASCII characters in username. To be more specific, for  Windows machines with non-ASCII characters in the actual value of `%USERPROFILE%` environment variable (that's the `~` for a Windows user). I experienced this issue reacently with PyInstaller 3.3.1. But sorry I have no sample code to reproduce it.

**Comment by Kojoley** [comment]
The tilde `~` is an ASCII char actually https://tools.ietf.org/html/rfc20.

**Comment by JokerQyou** [comment]
No, I did not mean `~` is not an ASCII char. I mean the value of `%USERPROFILE%` variable on Windows, which is a directory path, is much like `~` or `$HOME` on Unix.

If a Windows user has (or used to has) a username that contains non-ASCII characters, this issue will occur. Let's say the username is `测试`, which means the `%USERPROFILE%` value is `C:\Users\测试`, and a Python application bundled with PyInstaller installs into `%APPDATA%` (which is `%USERPROFILE%\AppData\Roaming`, and expands to `C:\Users\测试\AppData\Roaming`), in that application we use `DispatchWithEvents`, then this issue might be reproducible. After applying this hack provided by @Zyell it will be gone.
