### ISSUE TITLE
windows anaconda setuptools error 64 bit

### ISSUE THREAD

**Issue by CPrescher** [pyinstaller/pyinstaller#1817]
I am trying to "compile" one of my larger applications, however, i am getting the following error, when trying to run the program after compiling:

```
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dioptas\controller\__init__.py", line 19, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dioptas\controller\CalibrationController.py", line 25, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dioptas\widgets\CalibrationWidget.py", line 24, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dioptas\widgets\plot_widgets\__init__.py", line 5, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dioptas\widgets\plot_widgets\SpectrumWidget.py", line 24, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dioptas\model\__init__.py", line 24, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dioptas\model\PhaseModel.py", line 24, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dioptas\model\util\cif.py", line 6, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\pymatgen\__init__.py", line 15, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\pymatgen\core\__init__.py", line 13, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\pymatgen\core\structure.py", line 44, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\pymatgen\core\lattice.py", line 21, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\mock\__init__.py", line 2, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\mock\mock.py", line 71, in <module>
  File "site-packages\pbr\version.py", line 452, in semantic_version
  File "site-packages\pbr\version.py", line 438, in _get_version_from_pkg_resources
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\pbr\packaging.py", line 32, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\setuptools-19.2-py2.7.egg\setuptools\command\develop.py", line 9, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\setuptools-19.2-py2.7.egg\setuptools\command\easy_install.py", line 48, in <module>
  File "c:\users\clemens\appdata\local\temp\pip-build-mq9v6k\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\setuptools-19.2-py2.7.egg\setuptools\package_index.py", line 203, in <module>
  File "site-packages\setuptools-19.2-py2.7.egg\pkg_resources\__init__.py", line 962, in require
  File "site-packages\setuptools-19.2-py2.7.egg\pkg_resources\__init__.py", line 849, in resolve
pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by the application
Dioptas returned -1
```

i already tried to decrease the version of setuptools, but it seems to not be affected by this

**Comment by htgoebel** [comment]
Please provide more information, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by htgoebel** [comment]
No info since 1 3/4 years. Closing.
