### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by akbhat** [pyinstaller/pyinstaller#1839]
Running into below error when using --onefile mode inside virtualenv environment on CentOS 6.6. Complete debug log attached.
```
Traceback (most recent call last):
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.2.dev0+69ca81d', 'console_scripts', 'pyinstaller')()
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/building/build_main.py", line 756, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/building/build_main.py", line 702, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/building/api.py", line 489, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/building/api.py", line 280, in __init__
    self.__postinit__()
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/building/datastruct.py", line 183, in __postinit__
    self.assemble()
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/building/api.py", line 357, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "/home/abhat/Desktop/jcollect2/jcollect2.7/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```
[error.txt](https://github.com/pyinstaller/pyinstaller/files/144058/error.txt)

**Comment by akbhat** [comment]
Did anybody get a chance to look at this?

**Comment by htgoebel** [comment]
Obviously `bindepend.get_python_library_path()` does not find you Python Lib, which is a bit curious.

Please try tracking this down (see https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/depend/bindepend.py#L813) and let us know were it went wrong.

**Comment by akbhat** [comment]
> /lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/depend/bindepend.py(733)findLibrary()
-> lp = compat.getenv('LD_LIBRARY_PATH', '')
(Pdb) l
728  	    if is_aix:
729  	        lp = compat.getenv('LIBPATH', '')
730  	    elif is_darwin:
731  	        lp = compat.getenv('DYLD_LIBRARY_PATH', '')
732  	    else:
733  ->	        lp = compat.getenv('LD_LIBRARY_PATH', '')
734  	    for path in lp.split(os.pathsep):
735  	        libs = glob(os.path.join(path, name + '*'))
736  	        if libs:
737  	            lib = libs[0]
738  	            break
(Pdb) n
> /lib/python2.7/site-packages/PyInstaller-3.2.dev0+69ca81d-py2.7.egg/PyInstaller/depend/bindepend.py(734)findLibrary()
-> for path in lp.split(os.pathsep):
(Pdb) p lp
''

LD_LIBRARY_PATH does not seem to be set in my virtualenv environment. I have not built in virtualenv before so not sure if that should be set automatically. Should I manually update the variable? What directories do I need to add? (export VIRTUALENV_LD_LIBRARY_PATH=??)  

This is virtualenv on CentOS 6.6 and since PyInstaller3 dropped support for Python2.6, I installed a local copy of the Python2.7 in the virtualenv environment (using --python). Do I need to pass additional virtualenv parameters at create time?

**Comment by matysek** [comment]
@akbhat It is still not clear how exactly you get python2.7 on centos 6.6.  Did you use `pyenv` (not to be confused with `pyvenv`)?

PyInstaller needs the dynamically linked python library `libpythonXY.so`. In some cases this library is not built by default when compiling python of source.

**Comment by akbhat** [comment]
http://stackoverflow.com/questions/5506110/is-it-possible-to-install-another-version-of-python-to-virtualenv

**Comment by htgoebel** [comment]
@akbhat This describes about four or five methods, as far as I can see on a first glance. If you want us to help you solve your problem, please point us to the exact way. We are volunteers and do not have the time.

**Comment by akbhat** [comment]
@htgoebel I used the process listed in the top voted answer.

**Comment by htgoebel** [comment]
So you basically compiled Python from source. You need to `configure` with `--enable-shared`. Otherwise there is no `libpython2.7.so`. You may run into another problem, which I'm currently investigating (ticket will show up here soon). So you indeed may need to set to something like `LD_LIBRARY_PATH=~/.localpython/lib64`.

**Comment by Tristan79** [comment]
Same error on OSX, it has to do with upx, install it with brew, and it gives this error, remove it and it works perfectly....  (osx,el capitan,brew)

 ```
File "../pyinstaller-develop/pyinstaller.py", line 15, in <module>
    run()
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 37, in <module>
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/building/osx.py", line 85, in __init__
    self.__postinit__()
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/building/osx.py", line 171, in assemble
    fnm = checkCache(fnm, strip=self.strip, upx=self.upx, dist_nm=inm)
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/building/utils.py", line 222, in checkCache
    fnm = checkCache(fnm, strip=True, upx=False)
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/building/utils.py", line 195, in checkCache
    dylib.mac_set_relative_dylib_deps(cachedfile, dist_nm)
  File "/Users/Tristan/pyinstaller-develop/PyInstaller/depend/dylib.py", line 289, in mac_set_relative_dylib_deps
    if os.path.dirname(distname):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1

```
