### ISSUE TITLE
matplotlib problem

### ISSUE THREAD

**Issue by geobo** [pyinstaller/pyinstaller#1852]
Hello I'm trying to build an exe using pyinstaller but I get an error which I think is to do with matplotlib

I'm using python 3.5.1
MatplotLib 1.5.1
PyInstaller: 3.2.dev0+d47b3a7
Windows 7

this is my test code:

```
import numpy as np
import matplotlib.pyplot as plt
##import time
##import math as mth

print("hello world 12345")
```

and below is the output from when I run pyinstaller:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\gbown>cd C:\Users\gbown\Documents\Python Scripts\sensor_comparison-wip

C:\Users\gbown\Documents\Python Scripts\sensor_comparison-wip>pyinstaller build_
test.py
39 INFO: PyInstaller: 3.2.dev0+d47b3a7
39 INFO: Python: 3.5.1
39 INFO: Platform: Windows-7-6.1.7601-SP1
39 INFO: wrote C:\Users\gbown\Documents\Python Scripts\sensor_comparison-wip\bui
ld_test.spec
39 INFO: UPX is not available.
49 INFO: Extending PYTHONPATH with paths
['C:\\Users\\gbown\\Documents\\Python Scripts\\sensor_comparison-wip',
 'C:\\Users\\gbown\\Documents\\Python Scripts\\sensor_comparison-wip']
49 INFO: checking Analysis
49 INFO: Building because C:\Users\gbown\Documents\Python Scripts\sensor_compari
son-wip\build_test.py changed
49 INFO: Initializing module dependency graph...
49 INFO: Initializing module graph hooks...
49 INFO: Analyzing base_library.zip ...
2321 INFO: running Analysis out00-Analysis.toc
2581 INFO: Analyzing C:\Users\gbown\Documents\Python Scripts\sensor_comparison-w
ip\build_test.py
3149 INFO: Processing pre-find module path hook   distutils
4823 INFO: Processing pre-find module path hook   site
4823 INFO: site: retargeting to fake-dir 'c:\\anaconda3\\lib\\site-packages\\PyI
nstaller\\fake-modules'
4863 INFO: Processing pre-safe import module hook   win32com
6183 INFO: Processing pre-safe import module hook   six.moves
14467 INFO: Looking for import hooks ...
14470 INFO: Processing hook   hook-requests.py
14473 INFO: Processing hook   hook-PyQt4.QtGui.py
14716 INFO: Processing hook   hook-matplotlib.backends.py
15126 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
15407 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
15622 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
15912 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
16252 INFO:   Matplotlib backend "Qt4Agg": added
16592 INFO:   Matplotlib backend "Qt5Agg": added
16918 INFO:   Matplotlib backend "TkAgg": added
17271 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
17585 INFO:   Matplotlib backend "WXAgg": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
17789 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
18100 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
18341 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "c:\anaconda3\lib\site-packages\matplotlib\backends\backend_webagg.py", l
ine 32, in <module>
    import tornado.web
  File "c:\anaconda3\lib\site-packages\tornado\web.py", line 82, in <module>
    from tornado.concurrent import Future
  File "c:\anaconda3\lib\site-packages\tornado\concurrent.py", line 37, in <modu
le>
    from concurrent import futures
  File "c:\anaconda3\lib\site-packages\concurrent\futures\__init__.py", line 8,
in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "c:\anaconda3\lib\site-packages\concurrent\futures\_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
18562 INFO:   Matplotlib backend "nbAgg": ignored
    Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "c:\anaconda3\lib\site-packages\matplotlib\backends\backend_nbagg.py", li
ne 14, in <module>
    import tornado.ioloop
  File "c:\anaconda3\lib\site-packages\tornado\ioloop.py", line 46, in <module>
    from tornado.concurrent import TracebackFuture, is_future
  File "c:\anaconda3\lib\site-packages\tornado\concurrent.py", line 37, in <modu
le>
    from concurrent import futures
  File "c:\anaconda3\lib\site-packages\concurrent\futures\__init__.py", line 8,
in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "c:\anaconda3\lib\site-packages\concurrent\futures\_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
18858 INFO:   Matplotlib backend "agg": added
19053 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
19253 INFO:   Matplotlib backend "emf": ignored
    No module named 'matplotlib.backends.backend_emf'
19428 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
19739 INFO:   Matplotlib backend "pdf": added
20076 INFO:   Matplotlib backend "pgf": added
20358 INFO:   Matplotlib backend "ps": added
20672 INFO:   Matplotlib backend "svg": added
20953 INFO:   Matplotlib backend "template": added
21135 INFO: Processing hook   hook-xml.etree.cElementTree.py
21136 INFO: Processing hook   hook-PIL.Image.py
21254 INFO: Processing hook   hook-setuptools.py
21255 INFO: Processing hook   hook-encodings.py
21268 INFO: Processing hook   hook-pycparser.py
21405 INFO: Processing hook   hook-zmq.py
21549 INFO: Excluding import 'zmq.libzmq'
21549 WARNING:   From zmq removing import zmq.libzmq
21559 INFO: Processing hook   hook-xml.py
21559 INFO: Processing hook   hook-jinja2.py
21569 INFO: Processing hook   hook-pkg_resources.py
21569 INFO: Processing hook   hook-pythoncom.py
21789 INFO: Processing hook   hook-pywintypes.py
22022 INFO: Processing hook   hook-PyQt4.QtCore.py
22072 INFO: Processing hook   hook-lib2to3.py
22072 INFO: Processing hook   hook-jsonschema.py
22072 INFO: Processing hook   hook-win32com.py
22122 INFO: Processing hook   hook-pygments.py
22941 INFO: Processing hook   hook-_tkinter.py
23031 INFO: checking Tree
23051 INFO: checking Tree
23061 INFO: Processing hook   hook-pytz.py
23101 INFO: Processing hook   hook-PIL.py
23111 INFO: Excluding import 'PyQt5'
23111 WARNING:   From PIL.ImageQt removing import PyQt5
23111 WARNING:   From PIL.ImageQt removing import PyQt5.qRgba
23111 WARNING:   From PIL.ImageQt removing import PyQt5.QImage
23111 WARNING:   From PIL.ImageQt removing import PyQt5.QPixmap
23111 INFO: Excluding import 'PyQt4'
23111 WARNING:   From PIL.ImageQt removing import PyQt4.QtCore.QIODevice
23111 WARNING:   From PIL.ImageQt removing import PyQt4.QtGui
23111 WARNING:   From PIL.ImageQt removing import PyQt4.QtGui.QImage
23121 WARNING:   From PIL.ImageQt removing import PyQt4.QtGui.QPixmap
23121 WARNING:   From PIL.ImageQt removing import PyQt4.QtCore
23121 WARNING:   From PIL.ImageQt removing import PyQt4.QtGui.qRgba
23121 WARNING:   From PIL.ImageQt removing import PyQt4.QtCore.QBuffer
23121 INFO: Excluding import 'tkinter'
23121 WARNING:   From PIL.ImageTk removing import tkinter
23121 INFO: Excluding import 'PySide'
23121 WARNING:   From PIL.ImageQt removing import PySide.qRgba
23121 WARNING:   From PIL.ImageQt removing import PySide.QImage
23121 WARNING:   From PIL.ImageQt removing import PySide.QPixmap
23121 WARNING:   From PIL.ImageQt removing import PySide
23131 INFO: Import to be excluded not found: 'FixTk'
23131 INFO: Processing hook   hook-matplotlib.py
23321 INFO: Processing hook   hook-PyQt4.QtSvg.py
23321 INFO: Processing hook   hook-cryptography.py
23321 INFO: Processing hook   hook-sysconfig.py
23331 INFO: Processing hook   hook-PIL.SpiderImagePlugin.py
23331 INFO: Excluding import 'tkinter'
23331 INFO: Import to be excluded not found: 'FixTk'
23331 INFO: Processing hook   hook-pydoc.py
23331 INFO: Processing hook   hook-distutils.py
23331 INFO: Processing hook   hook-PyQt4.py
23331 INFO: Processing hook   hook-sqlite3.py
23341 INFO: Processing hook   hook-xml.dom.domreg.py
23341 INFO: Processing hook   hook-IPython.py
41321 INFO: Processing hook   hook-scipy.linalg.py
41321 INFO: Processing hook   hook-scipy.io.matlab.py
41321 INFO: Processing hook   hook-scipy.special._ufuncs.py
41321 INFO: Processing hook   hook-tables.py
41321 INFO: Processing hook   hook-sphinx.py
43294 INFO: Processing hook   hook-boto.py
43304 INFO: Processing hook   hook-babel.py
43354 INFO: Processing hook   hook-lxml.etree.py
43354 INFO: Processing hook   hook-idlelib.py
43364 INFO: Processing hook   hook-docutils.py
43674 INFO: Processing hook   hook-patsy.py
43684 INFO: Processing hook   hook-scipy.sparse.csgraph.py
43684 INFO: Processing hook   hook-sqlalchemy.py
43814 WARNING: Hidden import 'MySQLdb' not found (probably old hook)
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2.dev0+d47b3a7', 'console_scripts', 'pyinstaller')()
  File "c:\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 756, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 702, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 183, in __postinit__
    self.assemble()
  File "c:\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 462, in assemble
    self.zipped_data.extend(deps_proc.make_zipped_data_toc())
  File "c:\anaconda3\lib\site-packages\PyInstaller\building\toc_conversion.py", line 151, in make_zipped_data_toc
    tree = self.__collect_data_files_from_zip(dist.location)
  File "c:\anaconda3\lib\site-packages\PyInstaller\building\toc_conversion.py", line 135, in __collect_data_files_from_zip
    os.makedirs(workpath)
  File "c:\anaconda3\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 
'C:\\Users\\gbown\\Documents\\Python Scripts\\sensor_comparison-wip\\build\\
build_test\\setuptools-19.6.2-py3.5.egg'
```

**Comment by htgoebel** [comment]
Looks like one of your modules is not compatible with Python3:
```
  File "c:\anaconda3\lib\site-packages\concurrent\futures\__init__.py", line 8,
in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "c:\anaconda3\lib\site-packages\concurrent\futures\_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

**Comment by geobo** [comment]
i'm rolling back to 2.7,
hopefully will work then.

**Comment by geobo** [comment]
i've rolled back to python 2.7 and the exe builds but when I run it I get:

fatal python error: cannot get zipimporter instance

**Comment by htgoebel** [comment]
Is this still an issue? If so, have you tried the current development version and is it solved there?

**Comment by htgoebel** [comment]
No reaction, closing. If this is still an issue for you, feel free to provide up to date information.
