### ISSUE TITLE
Crypto.Cipher._ARC4: DLL load failed

### ISSUE THREAD

**Issue by dolphin845** [pyinstaller/pyinstaller#1857]
I have problems when I want to bundles the smbrelayx.py of the impacket example.

The environment I'm using is as follows:

Windows 7 64 Bits
Python 2.7.11 (WinPython)

when i try to run the exe and the log that appears is :

```
Traceback (most recent call last):
  File "<string>", line 46, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+0ad4651-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win-amd64\egg\impacket\examples\serviceinstall.py", line 20, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+0ad4651-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win-amd64\egg\impacket\dcerpc\v5\transport.py", line 21, in
<module>
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+0ad4651-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win-amd64\egg\impacket\dcerpc\v5\rpcrt.py", line 23, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+0ad4651-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win-amd64\egg\Crypto\Cipher\ARC4.py", line 66, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+0ad4651-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win-amd64\egg\Crypto\Cipher\_ARC4.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\Crypto\Cipher\_ARC4.py", line 6, in __bootstrap__
ImportError: DLL load failed: 
smbrelayx returned -1
```

**Comment by htgoebel** [comment]
Obviously  not all required dlls are packaged. Please follow https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly and try to find you, what exactly is missing. We'd then appreciate a pull-request for a hooks :-)

Related: #1834

**Comment by htgoebel** [comment]
I assume this issue is solved.
