### ISSUE TITLE
problem with matplotlib

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#186]
**Original date**: 2010/11/06

Hello everybody,

I am using PyInstaller to generate a set of stand-alone unix-like python utilities to be distributed within a research group. These utilities are simple but rely on many libraries sometime not so easy to install (scipy, matplotlib, etc.). I am working with a Mac OSX 10.6.2 and python 2.6.1.
In most cases PyInstall does a nice job. There are however problems when matplotlib is involved (as usual, I'd say...). 
I report below the error I read:

```
./SRPCosmology 
WARNING: astImages: failed to import matplotlib - some functions will not work.
Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 521, in doimport
    exec co in mod.__dict__
  File "/Users/covino/Desktop/SRP/build/pyi.darwin/SRPCosmology/outPYZ1.pyz/astLib", line 16, in <module>
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 521, in doimport
    exec co in mod.__dict__
  File "/Users/covino/Desktop/SRP/build/pyi.darwin/SRPCosmology/outPYZ1.pyz/astLib.astPlots", line 42, in <module>
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 521, in doimport
    exec co in mod.__dict__
  File "/Users/covino/Desktop/SRP/build/pyi.darwin/SRPCosmology/outPYZ1.pyz/pylab", line 1, in <module>
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 521, in doimport
    exec co in mod.__dict__
  File "/Users/covino/Desktop/SRP/build/pyi.darwin/SRPCosmology/outPYZ1.pyz/matplotlib.pylab", line 247, in <module>
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 521, in doimport
    exec co in mod.__dict__
  File "/Users/covino/Desktop/SRP/build/pyi.darwin/SRPCosmology/outPYZ1.pyz/matplotlib.pyplot", line 78, in <module>
  File "/Users/covino/Desktop/SRP/build/pyi.darwin/SRPCosmology/outPYZ1.pyz/matplotlib.backends", line 25, in pylab_setup
  File "/Users/covino/Pacchetti/pyinstaller-1.4/iu.py", line 455, in importHook
    raise ImportError, "No module named %s" % fqname
ImportError: No module named matplotlib.backends.backend_macosx
```

Do you know what I could try to solve the problem or whether at least could there be a workaround?

Thanks a lot,
  Stefano

**Comment by Chaoste** [comment]
I am still facing this issue. Is there any way to include it explicit?
