### ISSUE TITLE
'NullWriter' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by 10se1ucgo** [pyinstaller/pyinstaller#1883]
I'm currently writing a project which uses youtube-dl to download audio. However, when bundled with `-w`, users report that an error [like this is raised](http://i.imgur.com/FpuJFOJ.png). (Note: This is an excepthook/exception wrapper I wrote which displays the error in a GUI, not related to the problem)

So, if debug=False and console=False, embedding youtube-dl will throw the following AttributeError:

```
03:06:34 CRITICAL: Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "site-packages\youtube_dl\YoutubeDL.py", line 1718, in download
  File "site-packages\youtube_dl\YoutubeDL.py", line 679, in extract_info
  File "site-packages\youtube_dl\YoutubeDL.py", line 724, in process_ie_result
  File "site-packages\youtube_dl\YoutubeDL.py", line 1364, in process_video_result
  File "site-packages\youtube_dl\YoutubeDL.py", line 1677, in process_info
  File "site-packages\youtube_dl\YoutubeDL.py", line 526, in report_warning
AttributeError: 'NullWriter' object has no attribute 'isatty'
```

It seems that youtube-dl's warning output uses isatty() for whatever reason.

In order for me to get this traceback, I had to create a sys.excepthook to log to a file (because all output to console was disabled, of course)

Version info:
- Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
- pyinstaller 3.1.1
- youtube-dl 2016.03.06

test.spec:
```py
# -*- mode: python -*-

block_cipher = None


a = Analysis(['test.py'],
             pathex=["C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64"],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='test2',
          debug=False,
          strip=False,
          upx=False,
          console=False )
```

test.py
```py
#!python3
import sys
import logging
import traceback
import youtube_dl

logging.basicConfig(filename='test.log', level=logging.DEBUG,
                    format='\n%(asctime)s %(levelname)s: %(message)s', datefmt='%H:%M:%S', filemode='w')

sys.excepthook = lambda x, y, z: logging.critical(''.join(traceback.format_exception(x, y, z)))

yt_opts = {'format': 'bestaudio/best', 'outtmpl': '%(title)s.%(ext)s'}

with youtube_dl.YoutubeDL(yt_opts) as yt_dl:
    yt_dl.download([sys.argv[1]])
```

Example usage:
`test.py "https://www.youtube.com/watch?v=7IVJVTUNl0I"`

Hope this is enough information. If not, I apologize and will try to add whatever you need.

**Comment by tallforasmurf** [comment]
[`NullWriter`](https://docs.python.org/3.5/library/formatter.html?highlight=nullwriter#formatter.NullWriter) is a property of the `formatter` class, "deprecated due to lack of use". So why is it being used, or by whom? Hmmm. Could it be the same as the [logging.Formatter](https://docs.python.org/3.5/library/logging.html#logging.Formatter) class? (If so, somebody made a mistake in deprecating it!)

If I were you I'd try to get youtube_dl out of the picture here, for example instead of, or before, calling it do `raise Exception('kablooie')` and see if the call into your excepthook is all that is needed.

**Comment by 10se1ucgo** [comment]
Nope, works fine

test.py
```py
#!python3
import sys
import logging
import traceback
# import youtube_dl

logging.basicConfig(filename='test.log', level=logging.DEBUG,
                    format='\n%(asctime)s %(levelname)s: %(message)s', datefmt='%H:%M:%S', filemode='w')

sys.excepthook = lambda x, y, z: logging.critical(''.join(traceback.format_exception(x, y, z)))

raise Exception('kablooie')

# yt_opts = {'format': 'bestaudio/best', 'outtmpl': '%(title)s.%(ext)s'}

# with youtube_dl.YoutubeDL(yt_opts) as yt_dl:
#     yt_dl.download([sys.argv[1]])
```

log
```
14:36:56 CRITICAL: Traceback (most recent call last):
  File "<string>", line 12, in <module>
Exception: kablooie
```

**Comment by htgoebel** [comment]
@10se1ucgo Please debug which `NullWriter` in accessed here. For this:
1. Use the current development head and rebuild the bootloader - this is required to get the correct filename into the PyInstaller module
2. Add `import pdb ; pdb.set_trace()` into your program
3. Freeze your program and run it. When PDB steps in, just say `c` (continue) and when the exception occurs, investigate the `NullWriter`  object.

@tallforasmurf There is also a NullWriter in PyInstaller/loader/pyiboot01_bootstrap.py, and this one does not have an attribute `istty`.

**Comment by 10se1ucgo** [comment]
Will do in ~30 minutes.

**Comment by 10se1ucgo** [comment]
Okay, I built version 3.2.dev0+ge6ba86f.mod and I may have done something wrong.
Running any script causes this error

```
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\10se1ucgo\test\dist\test2.exe
LOADER: homepath is C:\Users\10se1ucgo\test\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\10se1ucgo\test\dist\test2.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\10se1ucgo\test\dist\test.exe
LOADER: homepath is CC:\Users\10se1ucgo\test\dist
LOADER: _MEIPASS2 is C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882
LOADER: archivename is C:\Users\10se1ucgo\test\dist\test.exe
LOADER: SetDllDirectory(C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882\test.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882\base_library.zip;C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882
LOADER: sys.prefix is C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename test2.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882\base_library.zip;C:\Users\10se1ucgo\AppData\Local\Temp\_MEI82882
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running test2.py
> c:\users\10se1ucgo\test\dist\test.py(3)<module>()
(Pdb) c
Failed to execute script test2
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for C:\Users\10se1ucgo\test\dist\test.exe
```

**Comment by matysek** [comment]
`NullWriter` is defined in file `PyInstaller/loader/pyiboot01_bootstrap.py`. Probably a function `def istty()` returning False should be added?

**Comment by htgoebel** [comment]
Argl, I'd expect pdb to drop you into the console. But you do not have one with `--windowed`.

I'm afraind you need to figure out how you can axess this NullWriter object yourself. Maybe https://code.activestate.com/recipes/65287-automatically-start-the-debugger-on-an-exception/ contains some hints (esp. the `pdb.pm()` part).

**Comment by htgoebel** [comment]
@matysek Yes. But I would like to know it it is this NullWriter causing the error. If so, we should check if there are other methods to be added.

**Comment by 10se1ucgo** [comment]
Wouldn't it be easier for me to just add `isatty` to the pyinstaller `NullWriter` and test if it works? `pdb` isn't working for me.

**Comment by matysek** [comment]
@10se1ucgo go ahead and try this patch:
```
diff --git a/PyInstaller/loader/pyiboot01_bootstrap.py b/PyInstaller/loader/pyiboot01_bootstrap.py
index 81b4362..c84381d 100644
--- a/PyInstaller/loader/pyiboot01_bootstrap.py
+++ b/PyInstaller/loader/pyiboot01_bootstrap.py
@@ -81,6 +81,11 @@ class NullWriter:
 
     def flush(*args):
         pass
+
+    def isatty(self):
+        return False
+
+
 # In Python 3 sys.stdout/err is None in GUI mode on Windows.
 # In Python 2 we need to check .fileno().
 if sys.stdout is None or sys.stdout.fileno() < 0:

```

**Comment by 10se1ucgo** [comment]
Works fine after adding `isatty()` to pyinstaller's `NullWriter`.

**Comment by matysek** [comment]
I commited the patch. @10se1ucgo thanks for testing.

@htgoebel if you think there is something else that should be added go ahead.

**Comment by 10se1ucgo** [comment]
Awesome, thanks.
