### ISSUE TITLE
openpyxl: AttributeError: 'module' object has no attribute '__version__'

### ISSUE THREAD

**Issue by beargan** [pyinstaller/pyinstaller#1890]
1 xl_test.py:

```
# -*- coding: utf-8 -*-
import pandas as pd

df = pd.DataFrame(data=[[1, 2, 3]], columns=("a", "b", "c"))
df.to_excel("xlstest.xlsx")'
```

2 >pyinstaller -F  xl_test.py

3 > xl_test.exe

```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "site-packages\pandas\core\frame.py", line 1403, in to_excel
  File "site-packages\pandas\io\excel.py", line 570, in __new__
  File "site-packages\pandas\io\excel.py", line 58, in get_writer
AttributeError: 'module' object has no attribute '__version__'
xl_test returned -1
```

4
|>  python xl_test.py
Generate xlstest.xlsx
That the code is not  problem.

how to solve?

**Comment by htgoebel** [comment]
First of all you need to know which module is failing. Please check pandas\io\excel.py", line 58. If this does not help, you need to debug your program.

**Comment by beargan** [comment]
@htgoebel 
|> python xl_test.py
Generate xlstest.xlsx
That the code is not problem.

**Comment by isomorphicor** [comment]
hi,beargan.I met the same problem,and i still don't know how to deal with it.

**Comment by pandafeeder** [comment]
Hi @isomorphicor @beargan , I met this too. But there's a work around. You can get the openpyxl's version you're using first, let's say its '2.3.5'.  Then you can just edit pandas.io.excel.py, in this file's def get_writer defination block, under import openpyxl, add this line: openpyxl__version__ = '2.3.5' , this will solve the problem.

**Comment by codewarrior0** [comment]
It looks to me like `openpyxl/.constants.json` needs to be included as a data file.

**Comment by pandafeeder** [comment]
Hi @codewarrior0 , yes, I think you are absolutely right, thanks.

**Comment by beargan** [comment]
Hi @codewarrior0 @pandafeeder ：
How to include file openpyxl/.constants.json ,as a data file in the openpyxl hook?

**Comment by stephenrauch** [comment]
@beargan, I have submitted a [pull request](https://github.com/pyinstaller/pyinstaller/issues/2066) with an openpyxl hook.  You can get it there

**Comment by beargan** [comment]
@stephenrauch thanks.
your method is feasible.

**Comment by hujichn** [comment]
Hi, @pandafeeder thanks! Your idea works out the problem.
The line to be added should be: openpyxl.__version__ = '2.3.5'
Don't miss that dot : )

**Comment by revolter** [comment]
What do you have to do to make this work?

**Comment by hujichn** [comment]
1. Find excel.py at your installation directory of python.
For example, C:\Python34\Lib\site-packages\pandas\io\excel.py
![1st](https://cloud.githubusercontent.com/assets/16831662/19378256/2eaa1aec-921e-11e6-9b5a-6d9aee03d8f4.png)

2. Add the following line:
openpyxl.__version__ = '2.3.5'
![2nd](https://cloud.githubusercontent.com/assets/16831662/19378257/2f6abbbc-921e-11e6-99c9-2c165ddb6447.png)

**Comment by revolter** [comment]
Isn't this supposed to be fixed by PyInstaller with #2066?

**Comment by revolter** [comment]
Firstly, I'm using a virtualenv, and secondly, there's no `pandas` folder :(

**Comment by stephenrauch** [comment]
Are using dev tip?

**Comment by revolter** [comment]
I replaced `from openpyxl import load_workbook` with `import openpyxl` in my script and it worked.

**Comment by MEL27** [comment]
@stephenrauch  I'm not using pandas, but this error occurs even after using the hook. (I placed the file under the hooks dir and deleted all *.pyc .)

`C:\Users\John\Documents\buildddddddddd\dist>C:\Users\John\Documents\buildddddddddd\dist\fetcher.exe
Traceback (most recent call last):
  File "fetcher.py", line 3, in <module>
  File "c:\users\john\documents\buildddddddddd\myapp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\openpyxl\__init__.py", line 32, in <module>
  File "c:\users\john\documents\buildddddddddd\myapp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\openpyxl\workbook\__init__.py", line 5, in <module>
  File "c:\users\john\documents\buildddddddddd\myapp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\openpyxl\workbook\workbook.py", line 16, in <module>
  File "c:\users\john\documents\buildddddddddd\myapp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\openpyxl\writer\write_only.py", line 23, in <module>
  File "c:\users\john\documents\buildddddddddd\myapp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\openpyxl\writer\excel.py", line 36, in <module>
  File "c:\users\john\documents\buildddddddddd\myapp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\openpyxl\packaging\extended.py", line 4, in <module>
ImportError: cannot import name '__version__'
Failed to execute script fetcher`

This can be triggered by a one-line python script
'import openpyxl'

Any ideas?

Python 3.5.2 on Windows 10 64bit
PyInstaller 3.2
openpyxl 2.4.1

**Comment by htgoebel** [comment]
New news in this for more then half a year. closing. If you feel this is still an issue with the current release, please open a brand new issue.
