### ISSUE TITLE
ImportError: bad magic number in 'packaging': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by snorfalorpagus** [pyinstaller/pyinstaller#1916]
Today I started getting an error when building an application using PyInstaller. The app was previously OK, so I'm not sure what has changed. The error is: (see end for full traceback)

```
ImportError: bad magic number in 'packaging': b'\x03\xf3\r\n'
```

I believe this issue might be related to #1781 as I've also seen that error while trying to work out what was wrong, although I'm unable to reproduce it now.

I'm using Python 3.4.4, 64-bit installed using Anaconda on Windows 7.

I was running on setuptools 20.3. Downgrading to setuptools 19.2 doesn't seem to have helped.

I've also tried the upgrading to the lastest version of PyInstaller (3.2-dev). No joy.

The full log is below.

```
84 INFO: PyInstaller: 3.1.1
84 INFO: Python: 3.4.4
84 INFO: Platform: Windows-7-6.1.7601-SP1
88 INFO: wrote D:\SuDSStudio\sudsstudio.spec
91 INFO: UPX is not available.
93 INFO: Extending PYTHONPATH with paths
['D:\\SuDSStudio', 'D:\\SuDSStudio']
93 INFO: checking Analysis
94 INFO: Building Analysis because out00-Analysis.toc is non existent
94 INFO: Initializing module dependency graph...
98 INFO: Initializing module graph hooks...
100 INFO: Analyzing base_library.zip ...
2997 INFO: Processing pre-find module path hook   distutils
4399 INFO: running Analysis out00-Analysis.toc
4472 INFO: Analyzing D:\SuDSStudio\app.py
8285 INFO: Processing pre-find module path hook   site
8286 INFO: site: retargeting to fake-dir 'c:\\miniconda3-x64\\envs\\python34\\lib\\site-packages\\PyInstaller\\fake-modules'
10177 INFO: Processing pre-safe import module hook   win32com
17241 INFO: Processing pre-safe import module hook   six.moves
42888 INFO: Looking for import hooks ...
42896 INFO: Processing hook   hook-scipy.sparse.csgraph.py
42899 INFO: Processing hook   hook-PyQt4.QtSvg.py
42900 INFO: Processing hook   hook-win32com.py
43006 INFO: Processing hook   hook-distutils.py
43008 INFO: Processing hook   hook-pythoncom.py
43920 INFO: Processing hook   hook-PySide.QtCore.py
44313 INFO: Processing hook   hook-requests.py
44336 INFO: Processing hook   hook-_tkinter.py
45106 INFO: checking Tree
45107 INFO: Building Tree because out00-Tree.toc is non existent
45107 INFO: Building Tree out00-Tree.toc
45310 INFO: checking Tree
45310 INFO: Building Tree because out01-Tree.toc is non existent
45310 INFO: Building Tree out01-Tree.toc
45342 INFO: Processing hook   hook-pygments.py
46788 INFO: Processing hook   hook-pytz.py
46935 INFO: Processing hook   hook-encodings.py
46965 INFO: Processing hook   hook-PySide.QtGui.py
48507 INFO: Processing hook   hook-scipy.special._ufuncs.py
48510 INFO: Processing hook   hook-xml.dom.domreg.py
48511 INFO: Processing hook   hook-PyQt4.QtCore.py
48775 INFO: Processing hook   hook-IPython.py
55212 INFO: Processing hook   hook-PyQt4.QtGui.py
56564 INFO: Processing hook   hook-jsonschema.py
56574 INFO: Processing hook   hook-lib2to3.py
56577 INFO: Processing hook   hook-pywintypes.py
57171 INFO: Processing hook   hook-sqlite3.py
57179 INFO: Processing hook   hook-PyQt4.py
57180 INFO: Processing hook   hook-setuptools.py
57180 INFO: Processing hook   hook-sqlalchemy.py
57700 WARNING: Hidden import 'MySQLdb' not found (probably old hook)
57701 WARNING: Hidden import 'psycopg2' not found (probably old hook)
58809 INFO: Processing hook   hook-pkg_resources.py
58812 INFO: Processing hook   hook-sysconfig.py
58813 INFO: Processing hook   hook-xml.py
58814 INFO: Processing hook   hook-docutils.py
59532 INFO: Processing hook   hook-idlelib.py
59567 INFO: Processing hook   hook-rasterio.py
59572 INFO: Processing hook   hook-osgeo.py
59590 INFO: Processing hook   hook-xml.etree.cElementTree.py
59591 INFO: Processing hook   hook-PySide.py
59592 INFO: Processing hook   hook-jinja2.py
59612 INFO: Processing hook   hook-sudsstudio.py
59617 INFO: Processing hook   hook-zmq.py
59928 INFO: Excluding import 'zmq.libzmq'
59936 WARNING:   From zmq removing import zmq.libzmq
59938 INFO: Processing hook   hook-tables.py
59940 INFO: Processing hook   hook-scipy.linalg.py
59941 INFO: Processing hook   hook-pydoc.py
59941 INFO: Processing hook   hook-babel.py
60124 INFO: Processing hook   hook-sphinx.py
63171 INFO: checking Tree
63172 INFO: Building Tree because out02-Tree.toc is non existent
63172 INFO: Building Tree out02-Tree.toc
63290 INFO: Looking for ctypes DLLs
63391 WARNING: library dllpaths required via ctypes not found
63430 INFO: Analyzing run-time hooks ...
63486 INFO: Including run-time hook 'pyi_rth_pkgres.py'
63487 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
63489 INFO: Including run-time hook 'pyi_rth_osgeo.py'
63491 INFO: Including run-time hook 'pyi_rth__tkinter.py'
63492 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
63494 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
63598 INFO: Looking for dynamic libraries
63619 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\resources\arrows.qml
63620 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\resources\arrows.qml
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63637 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\resources\splash_image.png
63637 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\resources\splash_image.png
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63638 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\resources\opt.qml
63639 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\resources\opt.qml
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63639 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\resources\routes.qml
63640 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\resources\routes.qml
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63640 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\githash.txt
63641 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\githash.txt
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1817, in __parse__
    raise PEFormatError('Unable to read the DOS Header, possibly a truncated file.')
PyInstaller.lib.pefile_py3.PEFormatError: 'Unable to read the DOS Header, possibly a truncated file.'
63743 INFO: Cannot get manifest resource from non-PE file c:\miniconda3-x64\envs\python34\lib\lib2to3\PatternGrammar.txt
63743 WARNING: Can not get binary dependencies for file: c:\miniconda3-x64\envs\python34\lib\lib2to3\PatternGrammar.txt
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63793 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\resources\sinks.qml
63794 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\resources\sinks.qml
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63794 INFO: Cannot get manifest resource from non-PE file c:\miniconda3-x64\envs\python34\lib\lib2to3\Grammar.txt
63795 WARNING: Can not get binary dependencies for file: c:\miniconda3-x64\envs\python34\lib\lib2to3\Grammar.txt
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63814 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\resources\aggregated_information.qml
63815 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\resources\aggregated_information.qml
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63816 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\resources\sources.qml
63816 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\resources\sources.qml
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
63929 INFO: Cannot get manifest resource from non-PE file D:\SuDSStudio\sudsstudio\resources\icon.png
63930 WARNING: Can not get binary dependencies for file: D:\SuDSStudio\sudsstudio\resources\icon.png
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 699, in getImports
    return _getImports_pe(pth)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\depend\bindepend.py", line 106, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\lib\pefile_py3.py", line 1826, in __parse__
    raise PEFormatError('DOS Header magic not found.')
PyInstaller.lib.pefile_py3.PEFormatError: 'DOS Header magic not found.'
64056 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
64057 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
64058 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4940_none_acd19a1fe1da248a.manifest
64059 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
64165 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
64165 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251.manifest
64166 INFO: Searching for file msvcr90.dll
64167 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcr90.dll
64167 INFO: Searching for file msvcp90.dll
64167 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcp90.dll
64167 INFO: Searching for file msvcm90.dll
64167 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcm90.dll
64257 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
64259 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
64259 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4940_none_acd19a1fe1da248a.manifest
64260 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
64261 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
64359 WARNING: lib not found: MSVCR90.dll dependency of c:\miniconda3-x64\envs\python34\Library\bin\spatialindex_c-64.dll
64444 WARNING: lib not found: MSVCP90.dll dependency of c:\miniconda3-x64\envs\python34\Library\bin\spatialindex_c-64.dll
65482 WARNING: lib not found: libzmq.pyd dependency of c:\miniconda3-x64\envs\python34\lib\site-packages\zmq\backend\cython\socket.pyd
65575 WARNING: lib not found: libzmq.pyd dependency of c:\miniconda3-x64\envs\python34\lib\site-packages\zmq\backend\cython\error.pyd
65702 WARNING: lib not found: libzmq.pyd dependency of c:\miniconda3-x64\envs\python34\lib\site-packages\zmq\backend\cython\_poll.pyd
65805 WARNING: lib not found: libzmq.pyd dependency of c:\miniconda3-x64\envs\python34\lib\site-packages\zmq\backend\cython\_device.pyd
65901 WARNING: lib not found: libzmq.pyd dependency of c:\miniconda3-x64\envs\python34\lib\site-packages\zmq\backend\cython\context.pyd
65996 WARNING: lib not found: libzmq.pyd dependency of c:\miniconda3-x64\envs\python34\lib\site-packages\zmq\backend\cython\_version.pyd
66089 WARNING: lib not found: libzmq.pyd dependency of c:\miniconda3-x64\envs\python34\lib\site-packages\zmq\backend\cython\message.pyd
66195 WARNING: lib not found: libzmq.pyd dependency of c:\miniconda3-x64\envs\python34\lib\site-packages\zmq\backend\cython\utils.pyd
68104 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt4.QtCore
68104 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt4.QtSvg
68104 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt4.QtGui
68105 WARNING: Attempted to add Python module twice with different upper/lowercases: scipy.optimize.moduleTNC
68105 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtSvg
68105 WARNING: Attempted to add Python module twice with different upper/lowercases: Cython.Compiler.Scanning
68105 WARNING: Attempted to add Python module twice with different upper/lowercases: Cython.Compiler.Parsing
68105 WARNING: Attempted to add Python module twice with different upper/lowercases: Cython.Compiler.Code
68106 WARNING: Attempted to add Python module twice with different upper/lowercases: Cython.Compiler.Visitor
68106 WARNING: Attempted to add Python module twice with different upper/lowercases: Cython.Compiler.FlowControl
68106 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtNetwork
68106 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtWebKit
68106 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtGui
68106 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtCore
68107 INFO: Looking for eggs
68107 INFO: Using Python library c:\miniconda3-x64\envs\python34\python34.dll
68107 INFO: Found binding redirects: 
[BindingRedirect(name='Microsoft.VC90.CRT', language=None, arch='amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken='1fc8b3b9a1e18e3b')]
68387 INFO: Warnings written to D:\SuDSStudio\build\sudsstudio\warnsudsstudio.txt
69443 INFO: checking PYZ
69443 INFO: Building PYZ because out00-PYZ.toc is non existent
69444 INFO: Building PYZ (ZlibArchive) D:\SuDSStudio\build\sudsstudio\out00-PYZ.pyz
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3-x64\envs\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3-x64\envs\python34\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\building\api.py", line 106, in __init__
    self.__postinit__()
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\building\datastruct.py", line 183, in __postinit__
    self.assemble()
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\building\api.py", line 177, in assemble
    self.code_dict[entry[0]] = self.__get_code(entry[0], entry[1])
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\building\api.py", line 160, in __get_code
    co = load_code(modname, filename)
  File "c:\miniconda3-x64\envs\python34\lib\site-packages\PyInstaller\building\api.py", line 148, in load_code
    return loader.get_code(modname)
  File "<frozen importlib._bootstrap>", line 1677, in get_code
  File "<frozen importlib._bootstrap>", line 624, in _validate_bytecode_header
ImportError: bad magic number in 'packaging': b'\x03\xf3\r\n'
```

**Comment by jakirkham** [comment]
Also saw this recently and was using `conda`. Any thoughts on this issue?

**Comment by htgoebel** [comment]
This error is raised by the python interpreter. I assume you changed the interpreter version (e.g. 3.3 to 3.4) and there is some .pyc file with the corresponding .py file missing. So the interpreter can not recompile the source but tries to load the .pyc which has the wrong version.

To quickly find the offending file I suggest adding a `print(modname, file=sys.stderr)` statement (mind the sys.stderr, otherwise the traceback will hinder this to be written in order) just before PyInstaller\building\api.py, line 148,
