### ISSUE TITLE
Build failed with Networkx

### ISSUE THREAD

**Issue by RaVhen** [pyinstaller/pyinstaller#1926]
Hello,
I've been trying to build a package, with Networkx and in the import. I keep having :the error :  No such file or directory. Did I forget something in the Makefile ? 

`pyinstaller -wF myprogram.py
18 INFO: PyInstaller: 3.1.1
18 INFO: Python: 2.7.10
18 INFO: Platform: Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
[...]
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.1.1', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/datastruct.py", line 183, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 432, in assemble
    imphook_object = ImportHook(imported_name, hook_file)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/imphook.py", line 182, in __init__
    self._module = importlib_load_source(hook_modname, self._filename)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/hooks/hook-gi.repository.GdkPixbuf.py", line 36, in <module>
    cachedata = subprocess.check_output('gdk-pixbuf-query-loaders')
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:17: recipe for target 'build' failed
make: *** [build] Error 1`

Thank you

**Comment by Legorooj** [comment]
Closing due to inactivity
