### ISSUE TITLE
Error running Pyinstaller through wine.

### ISSUE THREAD

**Issue by eevees-lattes** [pyinstaller/pyinstaller#1936]
Whenever I try to run a program containing PyGTK in it, it always crashes with a subprocess.py error, as follows:

Traceback (most recent call last):
```
  File "C:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.1.1', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "C:\Python27\lib\site-packages\PyInstaller\building\datastruct.py", line 183, in __postinit__
    self.assemble()
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 432, in assemble
    imphook_object = ImportHook(imported_name, hook_file)
  File "C:\Python27\lib\site-packages\PyInstaller\building\imphook.py", line 182, in __init__
    self._module = importlib_load_source(hook_modname, self._filename)
  File "C:\Python27\lib\site-packages\PyInstaller\hooks\hook-gi.repository.GdkPixbuf.py", line 36, in <module>
    cachedata = subprocess.check_output('gdk-pixbuf-query-loaders')
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] File not found
```

I am running it on Ubuntu Trusty and with Wine 1.6. I already have PyGTK and PyInstaller installed as it would be on a Windows system. I cannot for the life of me understand what is going on, and google has been no help. I have installed gdk using an all-in-one installer.

**Comment by tallforasmurf** [comment]
Just to be clear -- you do realize that PyInstaller is not a cross-compiler, and to get an app that runs on Windows, you have to run PyInstaller *on Windows* to make it? Forgive me if you knew that already...

**Comment by eevees-lattes** [comment]
I feel really dumb for not realizing that even though it's literally plastered everywhere...
