### ISSUE TITLE
ImportError: No module named Queue Failed to execute script pyi_rth_twisted

### ISSUE THREAD

**Issue by abhigenie92** [pyinstaller/pyinstaller#1939]
Versions:

- pyinstaller==3.2.dev0+g2f86ac6

- c:\Users\sony\Dropbox\notepad_app\2_Paint\dist\noteapp>python -m pip install twisted --upgrade
Requirement already up-to-date: twisted in c:\anaconda\lib\site-packages
Requirement already up-to-date: zope.interface>=3.6.0 in c:\anaconda\lib\site-packages (from twisted)
Requirement already up-to-date: setuptools in c:\anaconda\lib\site-packages (from zope.interface>=3.6.0->twisted)

- Python: 2.7.11 |Anaconda 2.5.0 (64-bit)| 

noteapp_modified.spec
```
# -*- mode: python -*-
from kivy.deps import sdl2, glew

from PyInstaller.utils.hooks import collect_submodules

a = Analysis(['__main__.py'],
             pathex=['C:\\Users\\sony\\Dropbox\\notepad_app\\2_Paint\\build\\windows'],
             binaries=None,
             datas=None,
             hiddenimports=collect_submodules('cryptography.hazmat.bindings.openssl') + ['_cffi_backend'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='../../noteapp',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               Tree('images'),
               Tree('kivy'),
               a.zipfiles,
               a.datas,
               strip=False,
               *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
               upx=True,
               name='../../noteapp')

```
Executing the spec file:
```
c:\Users\sony\Dropbox\notepad_app\2_Paint>python -m PyInstaller noteapp_modified.spec
171 INFO: PyInstaller: 3.2.dev0+g2f86ac6
171 INFO: Python: 2.7.11
173 INFO: Platform: Windows-10-10.0.10240
178 INFO: UPX is not available.
[INFO              ] [Logger      ] Record log in c:/Users/sony\.kivy\logs\kivy_16-04-15_22.txt
209 INFO: [Logger      ] Record log in c:/Users/sony\.kivy\logs\kivy_16-04-15_22.txt
[INFO              ] [Kivy        ] v1.9.1
207 INFO: [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]
210 INFO: [Python      ] v2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]
222 INFO: Extending PYTHONPATH with paths
['c:\\Users\\sony\\Dropbox\\notepad_app',
 'C:\\Users\\sony\\Dropbox\\notepad_app\\2_Paint\\build\\windows']
223 INFO: checking Analysis
223 INFO: Building Analysis because out00-Analysis.toc is non existent
223 INFO: Initializing module dependency graph...
230 INFO: Initializing module graph hooks...
239 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.pkcs7'
4966 INFO: Processing pre-find module path hook   distutils
14032 INFO: Processing pre-safe import module hook   _xmlplus
14799 INFO: Processing pre-find module path hook   site
14801 INFO: site: retargeting to fake-dir 'c:\\Anaconda\\lib\\site-packages\\pyinstaller-3.2.dev0+g2f86ac6-py2.7.egg\\PyInstaller\\fake-modules'
14857 INFO: Processing pre-safe import module hook   win32com
31401 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.binding'
31413 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.err'
31414 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.bio'
31417 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.hmac'
31418 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.evp'
31421 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.rsa'
31423 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.ssl'
31426 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.engine'
31427 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.x509v3'
31428 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.dh'
31430 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.objects'
31433 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.ecdsa'
31434 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.osrandom_engine'
31437 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.dsa'
31439 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.opensslv'
31440 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.x509'
31441 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.conf'
31444 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.cms'
31446 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.pkcs12'
31447 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.x509name'
31449 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.pem'
31450 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.ecdh'
31453 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.asn1'
31454 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.x509_vfy'
31457 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.rand'
31459 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.nid'
31460 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.bignum'
31461 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.ec'
31464 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.cmac'
31467 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.crypto'
31469 INFO: Analyzing hidden import 'cryptography.hazmat.bindings.openssl.aes'
31470 INFO: running Analysis out00-Analysis.toc
31476 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\Anaconda\python.exe
31634 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_18f8a87fd1919cd9.manifest
31635 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
31637 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
31638 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
31640 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9158_none_acd1eec7e1d9fa24.manifest
31793 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9158_none ...
31795 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9158_none_08e47e47a83d53d6.manifest
31796 INFO: Searching for file msvcr90.dll
31798 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9158_none_08e47e47a83d53d6\msvcr90.dll
31798 INFO: Searching for file msvcp90.dll
31799 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9158_none_08e47e47a83d53d6\msvcp90.dll
31799 INFO: Searching for file msvcm90.dll
31799 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9158_none_08e47e47a83d53d6\msvcm90.dll
31954 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_18f8a87fd1919cd9.manifest
31956 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
31957 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
31960 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
31961 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9158_none_acd1eec7e1d9fa24.manifest
31963 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9158)
38387 INFO: Caching module hooks...
38394 INFO: Analyzing __main__.py
50838 INFO: Loading module hooks...
50838 INFO: Loading module hook "hook-distutils.py"...
50839 INFO: Loading module hook "hook-sysconfig.py"...
50841 INFO: Loading module hook "hook-xml.py"...
50842 INFO: Loading module hook "hook-PIL.py"...
50848 INFO: Excluding import 'FixTk'
50854 INFO: Excluding import 'Tkinter'
50859 INFO: Excluding import 'PyQt5'
50867 WARNING:   Removing import PIL.ImageQt from module PyQt5
50868 WARNING:   Removing import PIL.ImageQt from module PyQt5.qRgba
50868 WARNING:   Removing import PIL.ImageQt from module PyQt5.QPixmap
50868 WARNING:   Removing import PIL.ImageQt from module PyQt5.QImage
50868 INFO: Excluding import 'PySide'
50875 WARNING:   Removing import PIL.ImageQt from module PySide.QPixmap
50875 WARNING:   Removing import PIL.ImageQt from module PySide.qRgba
50875 WARNING:   Removing import PIL.ImageQt from module PySide
50877 WARNING:   Removing import PIL.ImageQt from module PySide.QImage
50877 INFO: Excluding import 'PyQt4'
50884 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtGui.QImage
50884 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtCore
50884 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtGui.QPixmap
50885 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtCore.QIODevice
50885 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtCore.QBuffer
50887 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtGui.qRgba
50887 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtGui
50888 INFO: Loading module hook "hook-cryptography.py"...
50907 INFO: Loading module hook "hook-pycparser.py"...
51167 INFO: Loading module hook "hook-httplib.py"...
51168 INFO: Loading module hook "hook-pydoc.py"...
51174 INFO: Excluding import 'Tkinter'
51178 WARNING:   Removing import pydoc from module Tkinter
51180 INFO: Loading module hook "hook-PyQt4.py"...
51184 INFO: Loading module hook "hook-kivy.py"...
[INFO              ] [Factory     ] 179 symbols loaded
51189 INFO: [Factory     ] 179 symbols loaded
57595 INFO: Excluding import 'Tkinter'
57615 INFO: Excluding import 'twisted'
57630 WARNING:   Removing import kivy.support from module twisted.internet.error
57631 WARNING:   Removing import kivy.support from module twisted.internet._threadedselect
57631 WARNING:   Removing import kivy.support from module twisted
57631 WARNING:   Removing import kivy.support from module twisted.internet
57632 WARNING:   Removing import kivy.support from module twisted.internet.reactor
57638 INFO: Excluding import '_tkinter'
57657 INFO: Loading module hook "hook-_tkinter.py"...
58713 INFO: checking Tree
58713 INFO: Building Tree because out00-Tree.toc is non existent
58713 INFO: Building Tree out00-Tree.toc
58996 INFO: checking Tree
58996 INFO: Building Tree because out01-Tree.toc is non existent
58996 INFO: Building Tree out01-Tree.toc
59032 INFO: Loading module hook "hook-docutils.py"...
61413 INFO: Loading module hook "hook-PIL.Image.py"...
61951 INFO: Loading module hook "hook-xml.dom.domreg.py"...
61953 INFO: Loading module hook "hook-PyQt4.QtGui.py"...
62401 INFO: Loading module hook "hook-pkg_resources.py"...
63076 INFO: Loading module hook "hook-requests.py"...
63092 INFO: Loading module hook "hook-cv2.py"...
63092 INFO: Loading module hook "hook-certifi.py"...
63097 INFO: Loading module hook "hook-pywintypes.py"...
63839 INFO: Loading module hook "hook-setuptools.py"...
63842 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
63848 INFO: Excluding import 'FixTk'
63854 INFO: Excluding import 'Tkinter'
63859 INFO: Loading module hook "hook-encodings.py"...
64405 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
64407 INFO: Loading module hook "hook-pygame.py"...
64407 WARNING: Hidden import "pygame._view" not found!
64408 INFO: Loading module hook "hook-PyQt4.QtCore.py"...
64496 INFO: Loading module hook "hook-win32com.py"...
64730 INFO: Loading module hook "hook-pythoncom.py"...
65450 INFO: Loading module hook "hook-pygments.py"...
67894 INFO: checking Tree
67894 INFO: Building Tree because out02-Tree.toc is non existent
67894 INFO: Building Tree out02-Tree.toc
67926 INFO: checking Tree
67927 INFO: Building Tree because out03-Tree.toc is non existent
67927 INFO: Building Tree out03-Tree.toc
67951 INFO: Looking for ctypes DLLs
68061 INFO: Analyzing run-time hooks ...
68078 WARNING: Attempted to add Python module twice with different upper/lowercases: Queue
68082 WARNING: Attempted to add Python module twice with different upper/lowercases: Tkinter
68092 INFO: Including run-time hook 'pyi_rth_kivy.py'
68095 INFO: Including run-time hook 'pyi_rth_gstreamer.py'
68098 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
68101 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
68104 INFO: Including run-time hook 'pyi_rth__tkinter.py'
68107 INFO: Including run-time hook 'pyi_rth_pkgres.py'
68111 INFO: Including run-time hook 'pyi_rth_twisted.py'
68150 WARNING: Attempted to add Python module twice with different upper/lowercases: Queue
68153 WARNING: Attempted to add Python module twice with different upper/lowercases: Tkinter
68178 INFO: Looking for dynamic libraries
305191 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.1_none_3624aa14c1dce505.manifest
305197 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_a551ff35e6a96bed.manifest
305200 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.5570_none_a555b7a9e6a5e955.manifest
305201 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_a554a30de6a6e582.manifest
305355 INFO: Searching for assembly amd64_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
305355 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146.manifest
305358 INFO: Searching for file mfc90.dll
305358 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfc90.dll
305358 INFO: Searching for file mfc90u.dll
305359 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfc90u.dll
305359 INFO: Searching for file mfcm90.dll
305361 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfcm90.dll
305361 INFO: Searching for file mfcm90u.dll
305361 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfcm90u.dll
305510 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.1_none_3624aa14c1dce505.manifest
305513 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_a551ff35e6a96bed.manifest
305515 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.5570_none_a555b7a9e6a5e955.manifest
305516 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_a554a30de6a6e582.manifest
305518 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
808289 WARNING: Attempted to add Python module twice with different upper/lowercases: PIL._imagingft
808289 WARNING: Attempted to add Python module twice with different upper/lowercases: PIL._webp
808289 WARNING: Attempted to add Python module twice with different upper/lowercases: PIL._imagingtk
808291 WARNING: Attempted to add Python module twice with different upper/lowercases: PIL._imaging
808291 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt4.QtGui
808292 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt4.QtCore
808292 INFO: Looking for eggs
808292 INFO: Using Python library c:\Anaconda\python27.dll
808292 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9158), publicKeyToken=u'1fc8b3b9a1e18e3b')]
808362 INFO: Warnings written to c:\Users\sony\Dropbox\notepad_app\2_Paint\build\noteapp_modified\warnnoteapp_modified.txt
809250 INFO: checking PYZ
809250 INFO: Building PYZ because out00-PYZ.toc is non existent
809250 INFO: Building PYZ (ZlibArchive) c:\Users\sony\Dropbox\notepad_app\2_Paint\build\noteapp_modified\out00-PYZ.pyz
816322 INFO: checking PKG
816322 INFO: Building PKG because out00-PKG.toc is non existent
816322 INFO: Building PKG (CArchive) out00-PKG.pkg
816509 INFO: Bootloader c:\Anaconda\lib\site-packages\pyinstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\bootloader\Windows-64bit\run.exe
816509 INFO: checking EXE
816510 INFO: Building EXE because out00-EXE.toc is non existent
816510 INFO: Building EXE from out00-EXE.toc
816512 INFO: Appending archive to EXE c:\Users\sony\Dropbox\notepad_app\2_Paint\build\noteapp_modified\noteapp.exe
816595 INFO: checking Tree
816597 INFO: Building Tree because out04-Tree.toc is non existent
816597 INFO: Building Tree out04-Tree.toc
816601 INFO: checking Tree
816602 INFO: Building Tree because out05-Tree.toc is non existent
816602 INFO: Building Tree out05-Tree.toc
816608 INFO: checking Tree
816609 INFO: Building Tree because out06-Tree.toc is non existent
816609 INFO: Building Tree out06-Tree.toc
816624 INFO: checking Tree
816625 INFO: Building Tree because out07-Tree.toc is non existent
816625 INFO: Building Tree out07-Tree.toc
816638 INFO: checking COLLECT
816638 INFO: Building COLLECT because out00-COLLECT.toc is non existent
816638 INFO: Building COLLECT out00-COLLECT.toc
816690 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9158)

c:\Users\sony\Dropbox\notepad_app\2_Paint>cd dist

c:\Users\sony\Dropbox\notepad_app\2_Paint\dist>ls
noteapp

c:\Users\sony\Dropbox\notepad_app\2_Paint\dist>cd noteapp

```
```
c:\Users\sony\Dropbox\notepad_app\2_Paint\dist\noteapp>cmd /K noteapp.exe
Traceback (most recent call last):
  File "c:\Anaconda\lib\site-packages\pyinstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\rthooks\pyi_rth_twisted.py", line 23, in <module>
    from twisted.internet import default
  File "c:\anaconda\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Anaconda\lib\site-packages\twisted\internet\default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "c:\Anaconda\lib\site-packages\twisted\internet\default.py", line 52, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "c:\anaconda\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Anaconda\lib\site-packages\twisted\internet\selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "c:\anaconda\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Anaconda\lib\site-packages\twisted\internet\posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "c:\anaconda\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Anaconda\lib\site-packages\twisted\internet\udp.py", line 53, in <module>
    from twisted.internet import base, defer, address
  File "c:\anaconda\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Anaconda\lib\site-packages\twisted\internet\base.py", line 23, in <module>
    from twisted.internet import fdesc, main, error, abstract, defer, threads
  File "c:\anaconda\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Anaconda\lib\site-packages\twisted\internet\threads.py", line 14, in <module>
    import Queue
ImportError: No module named Queue
Failed to execute script pyi_rth_twisted

```

On suggestion I tried it with default python instead of Anaconda. The same error I get:
```
Abhishek@ABHISHEK ~/Dropbox/notepad_app/2_Paint/dist/noteapp (master)
$ cmd /K noteapp.exe
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\pyinstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\rthooks\pyi_rth_twisted.py", line 23, in <module>
    from twisted.internet import default
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Python27\lib\site-packages\twisted-16.1.1-py2.7-win-amd64.egg\twisted\internet\default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "c:\Python27\lib\site-packages\twisted-16.1.1-py2.7-win-amd64.egg\twisted\internet\default.py", line 52, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Python27\lib\site-packages\twisted-16.1.1-py2.7-win-amd64.egg\twisted\internet\selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Python27\lib\site-packages\twisted-16.1.1-py2.7-win-amd64.egg\twisted\internet\posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Python27\lib\site-packages\twisted-16.1.1-py2.7-win-amd64.egg\twisted\internet\udp.py", line 53, in <module>
    from twisted.internet import base, defer, address
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Python27\lib\site-packages\twisted-16.1.1-py2.7-win-amd64.egg\twisted\internet\base.py", line 23, in <module>
    from twisted.internet import fdesc, main, error, abstract, defer, threads
  File "c:\python27\lib\site-packages\PyInstaller-3.2.dev0+g2f86ac6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Python27\lib\site-packages\twisted-16.1.1-py2.7-win-amd64.egg\twisted\internet\threads.py", line 14, in <module>
    import Queue
ImportError: No module named Queue
Failed to execute script pyi_rth_twisted
```

**Comment by stephenrauch** [comment]
I ran into what looks like the same problem. In my case it is a 2.7 only problem, and was due to the presence of the 'queue' (lowercase) module from future.

Basic problem appears to be that pyinstaller cannot have two modules of the same name that differ only by lower/upper case.  The from the future 'queue' simply imports all of the 'Queue' module.  So by my reading, since 'queue' and 'Queue' can not coexist in a frozen app, and 'queue' requires 'Queue' there is no way to use 'queue' in a frozen 2.7 app.

Here is a pre_find_module_path hook I wrote to fix my problem, but I don't know that it is a general solution, but it does solve my problem 

```python
#-----------------------------------------------------------------------------
# Copyright (c) 2005-2016, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------

"""
warning for 'import queue' in 2.7 from the future

Problem appears to be that pyinstaller cannot have two modules of the same
name that differ only by lower/upper case.  The from the future 'queue' simply
imports all of the 'Queue' module.  So by my reading, since 'queue' and 'Queue'
can not coexist in a frozen app, and since 'queue' requires 'Queue', there is
no way to use 'queue' in a frozen 2.7 app.
"""

from PyInstaller.compat import is_py2
from PyInstaller.utils.hooks import logger

def pre_find_module_path(api):
    if not is_py2:
        return

    # maybe the 'import queue' was not really needed, so just make sure it
    # is not found, otherwise it will crowd out the potential future
    # import of 'Queue'
    api.search_dirs = []
    logger.warning("import queue (lowercase), not supported")
```

**Comment by abhigenie92** [comment]
@stephenrauch Thanks for the comment! Can you please answer the below questions:
1. Can you elaborate on how to use this hook, should just add it to the spec file.
2. Won't this just create a warning while running pyinstaller, how will remove import of queue?

**Comment by stephenrauch** [comment]
1) See http://pythonhosted.org/PyInstaller/#understanding-pyinstaller-hooks.  In short the file needs to be placed in ```{hook-dir}/pre_find_module_path/hook-queue.py```  where ```{hook-dir}``` is specified as ```pyinstaller --additional-hooks-dir={hook-dir}```

2) The warning is not really just a warning, when it issues the warning it does not include the import it is warning about.  What this hook does is stops pyinstaller from finding 'queue'. Thus when it later tries to import 'Queue', the import will succeed.  The reason I didn't just submit this as a pull request, is that this hook will not help if your code tries to execute both an ```import queue``` and an ```import Queue```, which will work in an unfrozen app.  This hook will only help if pyinstaller is importing 'queue' but it isn't really used by your program.

**Comment by abhigenie92** [comment]
@stephenrauch  Thanks so much for the reply! You mentioned hookdir while running `pyinstaller --additional-hooks-dir={hook-dir}`. Should this be done at both times, while building first time to generate spec file and second time while specifying the spec file.

**Comment by stephenrauch** [comment]
It will be necessary anytime you are generating an '.exe'

**Comment by htgoebel** [comment]
@stephenrauch Can you please provide a minimal example? Preferable not using twisted, but a small custom module. Thanks.

**Comment by htgoebel** [comment]
@stephenrauch Please continue commenting on #1935 as I'm closing this issue for being a duplicate.

**Comment by htgoebel** [comment]
For the records: This is about the package `future` https://pypi.python.org/pypi/future, mapping Py3-name to py2-names (and objects).
