### ISSUE TITLE
ImportError: No module named flask.ext.compress

### ISSUE THREAD

**Issue by mohanraj-r** [pyinstaller/pyinstaller#1950]
A straightforward import of `flask.ext.compress` fails

``` python 
# Install flask compress and the latest pyinstaller
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip 
pip install flask-compress

# Create a test file with just a import statement and freeze it
echo "from flask.ext.compress import Compress" > compress.py
pyinstaller compress.py

# Run the frozen binary
./dist/compress/compress
Failed to execute script compress
Traceback (most recent call last):
  File "compress.py", line 1, in <module>
    from flask.ext.compress import Compress
ImportError: No module named flask.ext.compress

# But importing it directly in Python works
$python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask.ext.compress import Compress
>>> dir(Compress)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'after_request', 'compress', 'init_app']
```

I tried `--onedir`, `--noupx`, `--hidden-import='flask.ext.compress'`

The archive file doesn't seem to contain the `compress` module

``` bash
$pyi-archive_viewer -rb build/compress/out00-PYZ.pyz  | grep -i compress
```

There are warnings in the warn file though
``` bash
$grep -i compress build/compress/warncompress.txt
missing module named 'flask.ext.compress'.Compress - imported by 'flask.ext.compress', /tmp/compress.py
missing module named 'flask.ext.compress' - imported by /tmp/compress.py
```

Can you please help me fix or debug this error.
Let me know if you need any more info.

**Comment by mohanraj-r** [comment]
Looking at the source of flask compress module, I don't see anything fancy. So it puzzles me as to why this doesn't work
https://github.com/libwilliam/flask-compress/blob/master/flask_compress.py

**Comment by mohanraj-r** [comment]
Attaching output from the freeze process and the output when running the frozen application with `--debug` and `--log-level=DEBUG` flags

Environment info:

``` bash
$uname -a
Linux 3.13.0-85-generic Ubuntu SMP

$python --version
Python 2.7.6

$pyinstaller --version
3.2.dev0+2f86ac6

$pip freeze
Flask==0.10.1
Flask-Compress==1.3.0
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
PyInstaller==3.2.dev0+2f86ac6
Werkzeug==0.11.8
```

Freezing compress.py:
```
14 INFO: PyInstaller: 3.2.dev0+2f86ac6
14 INFO: Python: 2.7.6
14 INFO: Platform: Linux-3.13.0-85-generic-x86_64-with-Ubuntu-14.04-trusty
14 INFO: wrote /tmp/compress.spec
15 DEBUG: Testing for UPX ...
18 INFO: UPX is not available.
18 INFO: Removing temporary files and cleaning cache in /home/mohan/.cache/pyinstaller
18 DEBUG: script: /tmp/compress.py
18 INFO: Extending PYTHONPATH with paths
['/tmp', '/tmp']
18 INFO: checking Analysis
18 INFO: Building Analysis because out00-Analysis.toc is non existent
19 INFO: Initializing module dependency graph...
19 INFO: Initializing module graph hooks...
20 DEBUG: Hidden import: codecs
41 DEBUG: Hidden import 'codecs' already found
41 INFO: running Analysis out00-Analysis.toc
41 DEBUG: Analyzing /home/mohan/.virtualenvs/pyinstaller/bin/python
48 DEBUG: Skipping libdl.so.2 dependency of python
48 DEBUG: Skipping libc.so.6 dependency of python
49 DEBUG: Skipping libutil.so.1 dependency of python
49 DEBUG: Skipping libpthread.so.0 dependency of python
49 DEBUG: Skipping libm.so.6 dependency of python
49 DEBUG: Adding libz.so.1 dependency of python from /lib/x86_64-linux-gnu/libz.so.1
49 DEBUG: Analyzing /lib/x86_64-linux-gnu/libz.so.1
59 DEBUG: Skipping libc.so.6 dependency of libz.so.1
59 INFO: Caching module hooks...
64 INFO: Analyzing /tmp/compress.py
1028 INFO: Processing pre-find module path hook   distutils
1031 INFO: distutils: retargeting to non-venv dir '/usr/lib/python2.7/distutils'
1222 INFO: Processing pre-safe import module hook   _xmlplus
1962 INFO: Loading module hooks...
1962 INFO: Loading module hook "hook-distutils.py"...
1963 INFO: Loading module hook "hook-sysconfig.py"...
1963 INFO: Loading module hook "hook-xml.py"...
1996 INFO: Loading module hook "hook-jinja2.py"...
2006 INFO: Loading module hook "hook-httplib.py"...
2006 INFO: Loading module hook "hook-pydoc.py"...
2007 INFO: Excluding import 'Tkinter'
2007 WARNING:   Removing import pydoc from module Tkinter
2007 INFO: Loading module hook "hook-encodings.py"...
2007 DEBUG: Collecting submodules for encodings
2009 DEBUG: - Found submodules: set(['encodings.cp932', 'encodings.johab', 'encodings.iso2022_jp_ext', 'encodings.cp424', 'encodings.big5', 'encodings.cp1140', 'encodings.cp862', 'encodings.cp775', 'encodings.euc_jis_2004', 'encodings.utf_32_le', 'encodings.utf_7', 'encodings.euc_kr', 'encodings.mac_arabic', 'encodings.utf_8', 'encodings.cp037', 'encodings.base64_codec', 'encodings.big5hkscs', 'encodings.shift_jis', 'encodings.iso8859_9', 'encodings.iso8859_8', 'encodings.mac_romanian', 'encodings.iso8859_3', 'encodings.iso8859_2', 'encodings.iso8859_1', 'encodings.iso8859_7', 'encodings.iso8859_6', 'encodings.iso8859_5', 'encodings.iso8859_4', 'encodings.cp857', 'encodings.cp856', 'encodings.cp855', 'encodings.cp852', 'encodings.cp850', 'encodings.cp858', 'encodings', 'encodings.mac_iceland', 'encodings.gbk', 'encodings.shift_jis_2004', 'encodings.mac_greek', 'encodings.palmos', 'encodings.iso2022_jp', 'encodings.utf_8_sig', 'encodings.koi8_r', 'encodings.koi8_u', 'encodings.aliases', 'encodings.iso2022_jp_1', 'encodings.cp1026', 'encodings.undefined', 'encodings.mac_farsi', 'encodings.iso2022_jp_3', 'encodings.iso2022_jp_2', 'encodings.utf_16_le', 'encodings.gb2312', 'encodings.uu_codec', 'encodings.ptcp154', 'encodings.euc_jisx0213', 'encodings.iso2022_jp_2004', 'encodings.zlib_codec', 'encodings.tis_620', 'encodings.cp720', 'encodings.cp875', 'encodings.cp874', 'encodings.rot_13', 'encodings.bz2_codec', 'encodings.unicode_escape', 'encodings.punycode', 'encodings.mac_croatian', 'encodings.mac_centeuro', 'encodings.mac_roman', 'encodings.cp437', 'encodings.utf_16', 'encodings.cp737', 'encodings.utf_16_be', 'encodings.latin_1', 'encodings.utf_32', 'encodings.charmap', 'encodings.hp_roman8', 'encodings.cp1006', 'encodings.iso8859_16', 'encodings.iso8859_15', 'encodings.iso8859_14', 'encodings.iso8859_13', 'encodings.iso8859_11', 'encodings.iso8859_10', 'encodings.cp500', 'encodings.unicode_internal', 'encodings.iso2022_kr', 'encodings.mac_turkish', 'encodings.mac_cyrillic', 'encodings.hz', 'encodings.euc_jp', 'encodings.cp1258', 'encodings.cp1257', 'encodings.cp1256', 'encodings.cp1255', 'encodings.cp1254', 'encodings.cp1253', 'encodings.cp1252', 'encodings.cp1251', 'encodings.cp1250', 'encodings.string_escape', 'encodings.utf_32_be', 'encodings.quopri_codec', 'encodings.idna', 'encodings.hex_codec', 'encodings.mac_latin2', 'encodings.cp869', 'encodings.cp866', 'encodings.cp864', 'encodings.cp865', 'encodings.cp949', 'encodings.cp863', 'encodings.cp860', 'encodings.cp861', 'encodings.ascii', 'encodings.shift_jisx0213', 'encodings.gb18030', 'encodings.raw_unicode_escape', 'encodings.mbcs', 'encodings.cp950'])
2196 INFO: Loading module hook "hook-_tkinter.py"...
2212 DEBUG: Adding libexpat.so.1 dependency of _tkinter.so from /lib/x86_64-linux-gnu/libexpat.so.1
2212 DEBUG: Adding libXss.so.1 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libXss.so.1
2213 DEBUG: Adding libXau.so.6 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libXau.so.6
2213 DEBUG: Adding libXrender.so.1 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libXrender.so.1
2213 DEBUG: Skipping libdl.so.2 dependency of _tkinter.so
2213 DEBUG: Adding libXft.so.2 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libXft.so.2
2213 DEBUG: Adding libfreetype.so.6 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libfreetype.so.6
2213 DEBUG: Adding libpng12.so.0 dependency of _tkinter.so from /lib/x86_64-linux-gnu/libpng12.so.0
2213 DEBUG: Skipping libxcb.so.1 dependency of _tkinter.so
2213 DEBUG: Adding libtk8.6.so dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libtk8.6.so
2213 DEBUG: Skipping libc.so.6 dependency of _tkinter.so
2214 DEBUG: Adding libXext.so.6 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libXext.so.6
2214 DEBUG: Adding libfontconfig.so.1 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
2214 DEBUG: Adding libX11.so.6 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libX11.so.6
2214 DEBUG: Skipping libpthread.so.0 dependency of _tkinter.so
2214 DEBUG: Adding libtcl8.6.so dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
2214 DEBUG: Adding libXdmcp.so.6 dependency of _tkinter.so from /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
2214 DEBUG: Skipping libm.so.6 dependency of _tkinter.so
2252 INFO: checking Tree
2252 INFO: Building Tree because out00-Tree.toc is non existent
2252 INFO: Building Tree out00-Tree.toc
2290 INFO: checking Tree
2290 INFO: Building Tree because out01-Tree.toc is non existent
2290 INFO: Building Tree out01-Tree.toc
2301 INFO: Loading module hook "hook-pkg_resources.py"...
2301 DEBUG: Collecting submodules for pkg_resources._vendor
2301 DEBUG: - Found submodules: set(['pkg_resources._vendor.packaging._structures', 'pkg_resources._vendor.packaging.specifiers', 'pkg_resources._vendor.packaging', 'pkg_resources._vendor.packaging._compat', 'pkg_resources._vendor.packaging.__about__', 'pkg_resources._vendor', 'pkg_resources._vendor.packaging.version'])
2307 DEBUG: Looking for egg data files...
2307 INFO: Looking for ctypes DLLs
2307 DEBUG: Scanning jinja2.debug for shared libraries or dlls
2308 DEBUG: Scanning FixTk for shared libraries or dlls
2357 DEBUG: Scanning uuid for shared libraries or dlls
2387 INFO: Analyzing run-time hooks ...
2401 INFO: Looking for dynamic libraries
2401 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_multibytecodec.x86_64-linux-gnu.so
2413 DEBUG: Skipping libc.so.6 dependency of _multibytecodec.x86_64-linux-gnu.so
2413 DEBUG: Skipping libpthread.so.0 dependency of _multibytecodec.x86_64-linux-gnu.so
2413 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_tw.x86_64-linux-gnu.so
2424 DEBUG: Skipping libc.so.6 dependency of _codecs_tw.x86_64-linux-gnu.so
2424 DEBUG: Skipping libpthread.so.0 dependency of _codecs_tw.x86_64-linux-gnu.so
2424 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_cn.x86_64-linux-gnu.so
2439 DEBUG: Skipping libc.so.6 dependency of _codecs_cn.x86_64-linux-gnu.so
2439 DEBUG: Skipping libpthread.so.0 dependency of _codecs_cn.x86_64-linux-gnu.so
2439 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_jp.x86_64-linux-gnu.so
2453 DEBUG: Skipping libc.so.6 dependency of _codecs_jp.x86_64-linux-gnu.so
2453 DEBUG: Skipping libpthread.so.0 dependency of _codecs_jp.x86_64-linux-gnu.so
2453 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_kr.x86_64-linux-gnu.so
2466 DEBUG: Skipping libc.so.6 dependency of _codecs_kr.x86_64-linux-gnu.so
2466 DEBUG: Skipping libpthread.so.0 dependency of _codecs_kr.x86_64-linux-gnu.so
2467 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/datetime.x86_64-linux-gnu.so
2481 DEBUG: Skipping libc.so.6 dependency of datetime.x86_64-linux-gnu.so
2481 DEBUG: Skipping libpthread.so.0 dependency of datetime.x86_64-linux-gnu.so
2481 DEBUG: Skipping libm.so.6 dependency of datetime.x86_64-linux-gnu.so
2481 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
2497 DEBUG: Skipping libc.so.6 dependency of _hashlib.x86_64-linux-gnu.so
2497 DEBUG: Skipping libpthread.so.0 dependency of _hashlib.x86_64-linux-gnu.so
2497 DEBUG: Adding libcrypto.so.1.0.0 dependency of _hashlib.x86_64-linux-gnu.so from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
2497 DEBUG: Skipping libdl.so.2 dependency of _hashlib.x86_64-linux-gnu.so
2497 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so
2510 DEBUG: Skipping libc.so.6 dependency of readline.x86_64-linux-gnu.so
2510 DEBUG: Skipping libpthread.so.0 dependency of readline.x86_64-linux-gnu.so
2510 DEBUG: Adding libreadline.so.6 dependency of readline.x86_64-linux-gnu.so from /lib/x86_64-linux-gnu/libreadline.so.6
2510 DEBUG: Adding libtinfo.so.5 dependency of readline.x86_64-linux-gnu.so from /lib/x86_64-linux-gnu/libtinfo.so.5
2511 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/resource.x86_64-linux-gnu.so
2522 DEBUG: Skipping libc.so.6 dependency of resource.x86_64-linux-gnu.so
2522 DEBUG: Skipping libpthread.so.0 dependency of resource.x86_64-linux-gnu.so
2522 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_iso2022.x86_64-linux-gnu.so
2534 DEBUG: Skipping libc.so.6 dependency of _codecs_iso2022.x86_64-linux-gnu.so
2534 DEBUG: Skipping libpthread.so.0 dependency of _codecs_iso2022.x86_64-linux-gnu.so
2535 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/bz2.x86_64-linux-gnu.so
2547 DEBUG: Skipping libc.so.6 dependency of bz2.x86_64-linux-gnu.so
2547 DEBUG: Skipping libpthread.so.0 dependency of bz2.x86_64-linux-gnu.so
2547 DEBUG: Adding libbz2.so.1.0 dependency of bz2.x86_64-linux-gnu.so from /lib/x86_64-linux-gnu/libbz2.so.1.0
2548 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_hk.x86_64-linux-gnu.so
2561 DEBUG: Skipping libc.so.6 dependency of _codecs_hk.x86_64-linux-gnu.so
2561 DEBUG: Skipping libpthread.so.0 dependency of _codecs_hk.x86_64-linux-gnu.so
2561 DEBUG: Analyzing /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
2577 DEBUG: Skipping libc.so.6 dependency of libcrypto.so.1.0.0
2577 DEBUG: Skipping libdl.so.2 dependency of libcrypto.so.1.0.0
2577 DEBUG: Analyzing /lib/x86_64-linux-gnu/libreadline.so.6
2590 DEBUG: Skipping libc.so.6 dependency of libreadline.so.6
2590 DEBUG: Analyzing /lib/x86_64-linux-gnu/libtinfo.so.5
2603 DEBUG: Skipping libc.so.6 dependency of libtinfo.so.5
2604 DEBUG: Analyzing /lib/x86_64-linux-gnu/libbz2.so.1.0
2615 DEBUG: Skipping libc.so.6 dependency of libbz2.so.1.0
2616 INFO: Looking for eggs
2616 INFO: Python library not in binary depedencies. Doing additional searching...
2646 DEBUG: Adding Python library to binary dependencies
2646 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
2651 INFO: Warnings written to /tmp/build/compress/warncompress.txt
2660 INFO: Graph drawing written to /tmp/build/compress/graph-compress.dot
2679 INFO: Graph cross-reference written to /tmp/build/compress/xref-compress.html
2704 INFO: checking PYZ
2704 INFO: Building PYZ because out00-PYZ.toc is non existent
2704 INFO: Building PYZ (ZlibArchive) /tmp/build/compress/out00-PYZ.pyz
2843 INFO: checking PKG
2844 INFO: Building PKG because out00-PKG.toc is non existent
2844 INFO: Building PKG (CArchive) out00-PKG.pkg
2879 DEBUG: Compiling /home/mohan/.virtualenvs/pyinstaller/local/lib/python2.7/site-packages/PyInstaller/loader/pyiboot01_bootstrap.py
2879 DEBUG: Compiling /home/mohan/.virtualenvs/pyinstaller/local/lib/python2.7/site-packages/PyInstaller/loader/pyiboot01_bootstrap.py
2882 DEBUG: Compiling /tmp/compress.py
2882 DEBUG: Compiling /tmp/compress.py
2885 INFO: Bootloader /home/mohan/.virtualenvs/pyinstaller/local/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
2885 INFO: checking EXE
2885 INFO: Building EXE because out00-EXE.toc is non existent
2885 INFO: Building EXE from out00-EXE.toc
2886 INFO: Appending archive to ELF section in EXE /tmp/build/compress/compress
2892 DEBUG: objcopy returned 0
2892 DEBUG: 
2893 DEBUG: 
2896 INFO: checking COLLECT
2896 INFO: Building COLLECT because out00-COLLECT.toc is non existent
2896 INFO: Building COLLECT out00-COLLECT.toc
```

Running the frozen binary:
``` 
PyInstaller Bootloader 3.x
LOADER: executable is /tmp/dist/compress/compress
LOADER: homepath is /tmp/dist/compress
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /tmp/dist/compress/compress
LOADER: pyi_arch_check_cookie failed
LOADER: Search for cookieLOADER: package found skipping digital signature in /tmp/dist/compress/compress
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /tmp/dist/compress
LOADER: LD_LIBRARY_PATH=/tmp/dist/compress
PyInstaller Bootloader 3.x
LOADER: executable is /tmp/dist/compress/compress
LOADER: homepath is /tmp/dist/compress
LOADER: _MEIPASS2 is /tmp/dist/compress
LOADER: archivename is /tmp/dist/compress/compress
LOADER: pyi_arch_check_cookie failed
LOADER: Search for cookieLOADER: package found skipping digital signature in /tmp/dist/compress/compress
LOADER: Already in the child - running user's code.
LOADER: Python library: /tmp/dist/compress/libpython2.7.so.1.0
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is /tmp/dist/compress
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /tmp/dist/compress
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: LC_CTYPE was C but resulted in NULL FileSystemDefaultEncoding
LOADER: Setting FileSystemDefaultEncoding to UTF-8 (was NULL)
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running compress.py
Failed to execute script compress
Traceback (most recent call last):
  File "compress.py", line 1, in <module>
    from flask.ext.compress import Compress
ImportError: No module named flask.ext.compress
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /tmp/dist/compress/compress
```

**Comment by htgoebel** [comment]
Thanks for your detailed report. As your `grep -i compress build/compress/warncompress.txt` show, PyInstaller correctly detects the module but does not find it. Please have a look at #1071 for more on this. If you have any idea how to solve this, we'd appreciate a pull-request.
