### ISSUE TITLE
Error when packaging scipy as minpack2 cannot be found

### ISSUE THREAD

**Issue by kokes** [pyinstaller/pyinstaller#1958]
I have a clean install of Anaconda 4.0.0 (32-bit, Python 3.5), `pip`-installed PyInstaller, and trying to pack a script which uses `numpy`. It packs `scipy` as well, but it crashes as it cannot find `scipy.optimize.minpack2` in its bincache (`minpack` is fine).

    In [5]: PyInstaller.__version__
    Out[5]: '3.1.1'

    In [6]: scipy.__version__
    Out[6]: '0.17.0'
    
I'm running `pyinstaller --onefile --distpath="." file.py`. I tried disabling upx (doesn't seem relevant to the problem, but I tried a bunch of things), switching to `--onedir` doesn't help either.

The error I get is as follows. I have tried downgrading setuptools to 19.2, which helped with problems in the past, but to no avail here. **`--exclude-module=scipy` works, but it's obviously not the ideal solution.**

    80543 INFO: Building PKG because out00-PKG.toc is non existent
    80543 INFO: Building PKG (CArchive) out00-PKG.pkg
    81536 WARNING: One binary added with two internal names.
    81537 WARNING: ('libsodium.cp35-win32.pyd',
     'c:\\users\\ok\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\zmq\\libsodium.cp35-win32.pyd',
     'BINARY')
    81538 WARNING: was placed previously at
    81538 WARNING: ('zmq\\libsodium.cp35-win32.pyd',
     'c:\\users\\ok\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\zmq\\libsodium.cp35-win32.pyd',
     'BINARY')
    **Cannot find ('scipy.optimize.minpack2.cp35-win32.pyd',** 'C:\Users\ok\AppData\Roaming\pyinstaller\bincache01_py35_32bit\scipy.optimize.minpack2.cp35-win32.pyd', 1, 'b')
    Traceback (most recent call last):
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\ok\AppData\Local\Continuum\Anaconda3\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 90, in run
        run_build(pyi_config, spec_file, **vars(args))
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
        PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
        exec(text, spec_namespace)
      File "<string>", line 28, in <module>
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\building\api.py", line 489, in __init__
        strip_binaries=self.strip, upx_binaries=self.upx,
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\building\api.py", line 280, in __init__
        self.__postinit__()
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 183, in __postinit__
        self.assemble()
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\building\api.py", line 365, in assemble
        pylib_name=pylib_name)
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\archive\writers.py", line 328, in __init__
        super(CArchiveWriter, self).__init__(archive_path, logical_toc)
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\archive\writers.py", line 58, in __init__
        self._add_from_table_of_contents(logical_toc)
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\archive\writers.py", line 83, in _add_from_table_of_contents
        self.add(toc_entry)  # The guts of the archive.
      File "c:\users\ok\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\archive\writers.py", line 375, in add
        fh = open(pathnm, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ok\\AppData\\Roaming\\pyinstaller\\bincache01_py35_32bit\\scipy.optimize.minpack2.cp35-win32.pyd'

Thanks for any help on this.

**Comment by kokes** [comment]
Updating scipy in conda (still 0.17.0, but conda offered an update) resolved the issue. So it was presumably some import issue within scipy itself, which was patched after Anaconda 4.0.0 was released. Closing.

**Comment by htgoebel** [comment]
This is curious: A file from the bincache is added to the archive, but the file is not in the bincache. But the bincache ought to be filled up just before.

Can you please try running pyinstaller with option `--clean`? Otherwise please check the file-permission s(just in case) and try debugging `checkCache` in PyInstaller/building/utils.py.

**Comment by htgoebel** [comment]
Waiting for info for more the 1 1/2 years. closing,
