### ISSUE TITLE
Appveyor complaints

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#1970]
Looking at fixing some Appveyor problems, I see the following in the [logs](https://ci.appveyor.com/project/matysek/pyinstaller/build/971/job/notq76k1qjhgbn68#L1822):

```
bindepend.py               702 WARNING  Can not get binary dependencies for file: C:\windows\system32\api-ms-win-crt-runtime-l1-1-0.dll
Traceback (most recent call last):
  File "C:\projects\pyinstaller\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "C:\projects\pyinstaller\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
bindepend.py               211 DEBUG    Analyzing C:\windows\system32\api-ms-win-crt-math-l1-1-0.dll
bindepend.py               702 WARNING  Can not get binary 
```

I suspect a quick fix, but haven't investigated this yet.

**Comment by bjones1** [comment]
Fixed by #1981.
