### ISSUE TITLE
Can't open the exe program. pyinstaller 3.2 for windows 7.

### ISSUE THREAD

**Issue by xueshirong** [pyinstaller/pyinstaller#1980]
1. The error occur when running the frozen program.
2. The error is 

```
E:\360Clude\UTA_LAB\CellProfiler_6c2d8960\dist\CellProfiler>CellProfiler.exe
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "c:\users\cse8243\appdata\local\temp\pip-build-jluptr\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 75, in <module>
  File "build\bdist.win-amd64\egg\pkg_resources\extern\__init__.py", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with
this package so if you get this warning, consult the packager of your distribution.
Failed to execute script pyi_rth_pkgres
```
1. version of Python: 2.7
2. version of PyInstaller: 3.2
3. version of Platform: Windows 7

**Comment by JMSwag** [comment]
[Start here](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs)

**Comment by htgoebel** [comment]
Please follow https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong

**Comment by htgoebel** [comment]
No info since 1 1/2 years. Closing.
