### ISSUE TITLE
Not finding @rpath modules for QWebEngine

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1984]
Mac OS 10.10.5
Python 3.5.1
PyQt, Qt 5.6
PyInstaller cloned from current develop, in particular bindepend:634 reads `rpath = re.sub('^@(executable_path|loader_path|rpath)/', executable_path + '/', rpath)`.

I will continue to investigate this, but wanted to document it now so anyone with an idea can jump in (please). Following is a minimal test case:

```
# minimal QWebEngine example.
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl
app = QApplication( [] )
view = QWebEngineView()
view.load( QUrl( "http://www.pyinstaller.org" ) )
view.show()
app.exec_()
```

Script works as expected from the command line, opening a minimal window displaying that web page.

```
 python pyinstaller/pyinstaller.py --clean -y minwebview.py 
87 INFO: PyInstaller: 3.3.dev0+gb688e31
87 INFO: Python: 3.5.1
91 INFO: Platform: Darwin-14.5.0-x86_64-i386-64bit
100 INFO: wrote /Developer/PYINSTALLERWORK/minwebview.spec
101 INFO: UPX is not available.
102 INFO: Removing temporary files and cleaning cache in /Users/dcortesi/Library/Application Support/pyinstaller
116 INFO: Extending PYTHONPATH with paths
['/Developer/PYINSTALLERWORK', '/Developer/PYINSTALLERWORK']
116 INFO: checking Analysis
116 INFO: Building Analysis because out00-Analysis.toc is non existent
116 INFO: Initializing module dependency graph...
117 INFO: Initializing module graph hooks...
118 INFO: Analyzing base_library.zip ...
1676 INFO: running Analysis out00-Analysis.toc
1683 INFO: Caching module hooks...
1685 INFO: Analyzing /Developer/PYINSTALLERWORK/minwebview.py
1692 INFO: Loading module hooks...
1692 INFO: Loading module hook "hook-encodings.py"...
1699 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
1700 INFO: Loading module hook "hook-xml.py"...
1832 INFO: Loading module hook "hook-PyQt5.QtWebEngineWidgets.py"...
2098 INFO: Loading module hook "hook-pydoc.py"...
2099 INFO: Loading module hook "hook-PyQt5.py"...
2142 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
2196 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
2502 INFO: Loading module hook "hook-PyQt5.QtNetwork.py"...
2554 INFO: Loading module hook "hook-PyQt5.Qt.py"...
2555 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
2618 INFO: Looking for ctypes DLLs
2623 INFO: Analyzing run-time hooks ...
2627 INFO: Including run-time hook 'pyi_rth_qt5.py'
2628 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
2629 INFO: Including run-time hook 'pyi_rth_qt5webengine.py'
2634 INFO: Looking for dynamic libraries
2639 ERROR: Can not find path ./QtQuick.framework/Versions/5/QtQuick (needed by /Developer/Qt5.6/5.6/clang_64/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess)
2639 ERROR: Can not find path ./QtNetwork.framework/Versions/5/QtNetwork (needed by /Developer/Qt5.6/5.6/clang_64/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess)
2639 ERROR: Can not find path ./QtWebChannel.framework/Versions/5/QtWebChannel (needed by /Developer/Qt5.6/5.6/clang_64/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess)
2640 ERROR: Can not find path ./QtWebEngineCore.framework/Versions/5/QtWebEngineCore (needed by /Developer/Qt5.6/5.6/clang_64/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess)
2640 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Developer/Qt5.6/5.6/clang_64/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess)
2640 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Developer/Qt5.6/5.6/clang_64/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess)
2640 ERROR: Can not find path ./QtQml.framework/Versions/5/QtQml (needed by /Developer/Qt5.6/5.6/clang_64/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess)
2825 INFO: Looking for eggs
2825 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.5/Python
2838 INFO: Warnings written to /Developer/PYINSTALLERWORK/build/minwebview/warnminwebview.txt
2846 INFO: checking PYZ
2846 INFO: Building PYZ because out00-PYZ.toc is non existent
2846 INFO: Building PYZ (ZlibArchive) /Developer/PYINSTALLERWORK/build/minwebview/out00-PYZ.pyz
3117 INFO: checking PKG
3117 INFO: Building PKG because out00-PKG.toc is non existent
3117 INFO: Building PKG (CArchive) out00-PKG.pkg
3123 INFO: Bootloader /Developer/PYINSTALLERWORK/pyinstaller/PyInstaller/bootloader/Darwin-64bit/run
3123 INFO: checking EXE
3124 INFO: Building EXE because out00-EXE.toc is non existent
3124 INFO: Building EXE from out00-EXE.toc
3124 INFO: Appending archive to EXE /Developer/PYINSTALLERWORK/build/minwebview/minwebview
3125 INFO: Fixing EXE for code signing /Developer/PYINSTALLERWORK/build/minwebview/minwebview
3128 INFO: checking COLLECT
3129 INFO: Building COLLECT because out00-COLLECT.toc is non existent
3129 INFO: Building COLLECT out00-COLLECT.toc
```

```
$ dist/minwebview/minwebview 
Failed to execute script minwebview
Traceback (most recent call last):
  File "minwebview.py", line 3, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
  File "/Developer/PYINSTALLERWORK/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
ImportError: No module named 'PyQt5.QtWebEngineCore'
```

**Comment by tallforasmurf** [comment]
Note that QWebEngine, esp. on Mac OS, is extraordinarily complex, it starts an entirely separate app called QWebEngineProcess.

**Comment by tallforasmurf** [comment]
Hmmm it appears I was not in fact getting the current bindepend but the 3.2 version. Problem is different. Closing.

**Comment by edrex** [comment]
I'm seeing this same behavior with the latest `develop` branch, using the minimal app above. Any ideas?
