### ISSUE TITLE
UnicodeDecode error while importing xlwt

### ISSUE THREAD

**Issue by AninaRJ** [pyinstaller/pyinstaller#1996]
I have built an internal tool using on Python 3.4 which reformats xls data. I am using Xlwt and Xlrd for writing and reading excel files and it runs perfectly when I run on shell. Problem is when I try to build using PyInstaller. I seem to be getting a UnicodeDecode error when I import xlwt module. 

Following is the error log:

```
Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2', 'console_scripts', 'pyinstaller')()
  File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 90, in run    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "C:\Python34\lib\site-packages\PyInstaller\building\datastruct.py", line 178, in __postinit__
    self.assemble()
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 413, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 144, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 892, in run_script
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1475, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1588, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1316, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 906, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 990, in _find_head_package
    q = self._safe_import_module(head, qname, parent)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1211, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1243, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1634, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1295, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1475, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1588, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1316, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 906, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 990, in _find_head_package
    q = self._safe_import_module(head, qname, parent)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1211, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1295, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1475, in _scan_code
    self._process_imports(m)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1588, in _process_imports
    imported_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1424, in _safe_import_hook
    sm = self.import_hook(name, caller, fromlist=[sub], level=level, attr=attr)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 910, in import_hook
    for s in self._ensure_fromlist(m, fromlist):
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1037, in _ensure_fromlist
    submod = self._safe_import_module(sub, fullname, m)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1205, in _safe_import_module
    module_basename, search_dirs, parent_package)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_module
    return self._find_module_path(fullname, name, path)
  File "C:\Python34\lib\site-packages\PyInstaller\depend\analysis.py", line 253, in _find_module_path
    fullname, module_name, search_dirs)
  File "C:\Python34\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1840, in _find_module_path
    file_handle = StringIO(loader.get_source(module_name))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 52807: invalid start byte
```

**Comment by codewarrior0** [comment]
Ugh. The error handling in modulegraph is pretty bad - it doesn't say which module failed to parse or how it was imported. Do you think you could run pyinstaller with a debug option to get that info? Something like:

```
MODULEGRAPH_DEBUG=3 pyinstaller <your args> 2>pyinstaller.err
tail -n40 pyinstaller.err
```

**Comment by AninaRJ** [comment]
Ah it says MODULEGRAPH_DEBUG is not recognized as an internal or external command. What is the dependency I need to add?

**Comment by codewarrior0** [comment]
Oh right, you're using cmd.exe, but I gave you the sh syntax instead. I think for cmd, you would write:

```
set MODULEGRAPH_DEBUG=3
pyinstaller <your args> 2>pyinstaller.err
```

**Comment by AninaRJ** [comment]
Looks like the error log is giving me the same thing. I have it attached here. 
[pyinstaller.txt](https://github.com/pyinstaller/pyinstaller/files/277340/pyinstaller.txt)

**Comment by AninaRJ** [comment]
Hi, any update on this?

**Comment by codewarrior0** [comment]
Your error log doesn't have the debug info I need. Try running it again like this:

```
set MODULEGRAPH_DEBUG=3
pyinstaller <your args> >pyinstaller.out 2>pyinstaller.err
```

One of the two output files should have the modulegraph info.

**Comment by cycleuser** [comment]
[pyinstaller.txt](https://github.com/pyinstaller/pyinstaller/files/848094/pyinstaller.txt)


@codewarrior0 

I just use this:

```Bash
set MODULEGRAPH_DEBUG=3
pyinstaller <your args> >pyinstaller.out 2>pyinstaller.err
```

and get this err file and a blank out file.

Same Error.

**Comment by htgoebel** [comment]
@cycleuser 

> Same Error.

No! The original error was caused by some import and in modulegraph, by while your is cause by hook-zmq.py. Also the error message is different. 

Original: 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 52807: invalid start byte

Your's is: 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 110: invalid continuation byte

Quite a difference, isn't it?

**Comment by cycleuser** [comment]
@htgoebel  

yep, you are right.

so, any tips on solving that?

**Comment by NathalieSchmiedt** [comment]
Have you already solved the issue?
I have exactly the same problem with my python script using xlwt and xlrd.
File "C:\Python351\lib\site-packages\pyinstaller-3.1-py3.5.egg\PyInstaller\lib\modulegrap\modulegraph.py", line 1842, in _find_module_path,
file_handle = StringIO(loader.get_source(module_name))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 52807: invalid start byte

**Comment by htgoebel** [comment]
@AninaRJ @NathalieSchmiedt PyInstaller 3.3 includes changes which may have solved this issue. Please check if this issue persists. If possible please try with the versions of xlwt and xlrd you used back then.

If the problem persists, please use `pyinstaller --log-level=TRACE …`. This will give you *a lot* of messages, out of which only the last few above the traceback regarding `_find_module_path` are relevant. Please post them here.

If the problem is solved, finding the root course would still be interesting. Please search the log-output for "_find_module_path -> unicode error" message. Please post the surrounding "_find_module_path" messages.

**Comment by htgoebel** [comment]
Please also provide the exact version of the package the failing module belongs to.

**Comment by Legorooj** [comment]
Author not responding
