### ISSUE TITLE
Problem with hidden import for pytest

### ISSUE THREAD

**Issue by davidedelvento** [pyinstaller/pyinstaller#2009]
I encountered a problem when trying to create a binary with pyinstaller when importing pytest. My program is fairly complicated, but I've been able to reproduce the issue with a hello_world example, which hopefully will make it much easier for you to reproduce and fix (if it's indeed a issue and not "operator error").

Note that the software in /opt and /contrib has been manually installed (from source when relevant e.g. for python), and is not the OS default which would be super old.

As far as I can tell, I followed all the instructions from the guides, so here is what I do on my shell:

```
$ uname -a
Linux yslogin2 2.6.32-358.el6.x86_64 #1 SMP Tue Jan 29 11:47:41 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.4 (Santiago)
Release:        6.4
Codename:       Santiago

$ ls
bug_with_pytest.py

$ cat bug_with_pytest.py 
import pytest

print dir(pytest)
print pytest.__version__

$ python bug_with_pytest.py 
['Class', 'Collector', 'File', 'Function', 'Generator', 'Instance', 'Item', 'Module', 'Session', 'UsageError', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__version__', '_fillfuncargs', '_preloadplugins'
, 'cmdline', 'collect', 'deprecated_call', 'exit', 'fail', 'fixture', 'freeze_includes', 'importorskip', 'main', 'mark', 'raises', 'set_trace', 'skip', 'xfail', 'yield_fixture']
2.7.0

$ python --version
Python 2.7.7

$ pyinstaller --version
3.2

$ pyinstaller \
> --hidden-import=py._code.code    \
> --hidden-import=py._builtin      \
> --hidden-import=_pytest.mark     \
> --hidden-import=_pytest.main     \
> bug_with_pytest.py \
>
42 INFO: PyInstaller: 3.2
42 INFO: Python: 2.7.7
43 INFO: Platform: Linux-2.6.32-358.el6.x86_64-x86_64-with-redhat-6.4-Santiago
44 INFO: wrote ~/bugreport/bug_with_pytest.spec
49 INFO: UPX is not available.
51 INFO: Extending PYTHONPATH with paths
['~/bugreport',
 '~/bugreport']
51 INFO: checking Analysis
52 INFO: Building Analysis because out00-Analysis.toc is non existent
52 INFO: Initializing module dependency graph...
65 INFO: Initializing module graph hooks...
104 INFO: Analyzing hidden import 'py._code.code'
2972 INFO: Analyzing hidden import 'py._builtin'
3034 INFO: Analyzing hidden import '_pytest.mark'
3552 INFO: Processing pre-find module path hook   distutils
3952 INFO: Processing pre-safe import module hook   _xmlplus
5066 INFO: Analyzing hidden import '_pytest.main'
5425 INFO: running Analysis out00-Analysis.toc
5550 INFO: Caching module hooks...
5554 INFO: Analyzing ~/bugreport/bug_with_pytest.py
5561 INFO: Loading module hooks...
5562 INFO: Loading module hook "hook-distutils.py"...
5575 INFO: Loading module hook "hook-sysconfig.py"...
5591 INFO: Loading module hook "hook-xml.py"...
5751 INFO: Loading module hook "hook-httplib.py"...
5766 INFO: Loading module hook "hook-pkg_resources.py"...
5767 INFO: Loading module hook "hook-encodings.py"...
7144 INFO: Looking for ctypes DLLs
7144 INFO: Analyzing run-time hooks ...
7149 INFO: Including run-time hook 'pyi_rth_pkgres.py'
7162 INFO: Looking for dynamic libraries
7691 INFO: Looking for eggs
7692 INFO: Using Python library /opt/python/2.7.7/gnu-westmere/4.8.2//lib/libpython2.7.so.1.0
7704 INFO: Warnings written to ~/bugreport/build/bug_with_pytest/warnbug_with_pytest.txt
7870 INFO: checking PYZ
7870 INFO: Building PYZ because out00-PYZ.toc is non existent
7870 INFO: Building PYZ (ZlibArchive) ~/bugreport/build/bug_with_pytest/out00-PYZ.pyz
8312 INFO: checking PKG
8313 INFO: Building PKG because out00-PKG.toc is non existent
8313 INFO: Building PKG (CArchive) out00-PKG.pkg
8391 INFO: Bootloader /contrib/pyinstaller/lib/python2.7/site-packages/PyInstaller-3.2-py2.7.egg/PyInstaller/bootloader/Linux-64bit/run
8392 INFO: checking EXE
8392 INFO: Building EXE because out00-EXE.toc is non existent
8392 INFO: Building EXE from out00-EXE.toc
8393 INFO: Appending archive to ELF section in EXE ~/bugreport/build/bug_with_pytest/bug_with_pytest
8503 INFO: checking COLLECT
8503 INFO: Building COLLECT because out00-COLLECT.toc is non existent
8503 INFO: Building COLLECT out00-COLLECT.toc

$ ls
bug_with_pytest.py  bug_with_pytest.spec  build  dist

$ cd dist/bug_with_pytest/

$ ls
array.so         bz2.so              _codecs_jp.so    cPickle.so    _functools.so  include       libbz2.so.1          libreadline.so.6  _locale.so          parser.so    resource.so  strop.so    unicodedata.so
binascii.so      _codecs_cn.so       _codecs_kr.so    cStringIO.so  grp.so         _io.so        libcrypto.so.1.0.0   libssl.so.1.0.0   math.so             pyexpat.so   select.so    _struct.so  zlib.so
_bisect.so       _codecs_hk.so       _codecs_tw.so    datetime.so   _hashlib.so    itertools.so  libexpat.so.1        libtinfo.so.5     _multibytecodec.so  _random.so   _socket.so   termios.so
bug_with_pytest  _codecs_iso2022.so  _collections.so  fcntl.so      _heapq.so      lib           libpython2.7.so.1.0  libz.so.1         operator.so         readline.so  _ssl.so      time.so

$ ./bug_with_pytest 
Traceback (most recent call last):
  File "bug_with_pytest.py", line 1, in <module>
  File "/contrib/pyinstaller/lib/python2.7/site-packages/PyInstaller-3.2-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "/opt/pytest/2.7.0/lib/python2.7/site-packages/pytest.py", line 17, in <module>
    _preloadplugins() # to populate pytest.* namespace so help(pytest) works
  File "/opt/pytest/2.7.0/lib/python2.7/site-packages/_pytest/config.py", line 58, in _preloadplugins
    _preinit.append(get_plugin_manager())
  File "/opt/pytest/2.7.0/lib/python2.7/site-packages/_pytest/config.py", line 67, in get_plugin_manager
    pluginmanager.import_plugin(spec)
  File "/opt/pytest/2.7.0/lib/python2.7/site-packages/_pytest/core.py", line 318, in import_plugin
    mod = importplugin(modname)
  File "/opt/pytest/2.7.0/lib/python2.7/site-packages/_pytest/core.py", line 370, in importplugin
    __import__(importspec)
ImportError: No module named main
Failed to execute script bug_with_pytest

$ 
```

Note that I've manually anonymized some of the reporting directories with ~. 

For convenience of study, here are the relevant lines of codes where it is crashing: https://github.com/pytest-dev/pytest/blob/2.7.0/_pytest/core.py#L363 (which make it clear that the failing code is trying to import `_pytest.main` and not some other `main`). 

So it seems to me that  `--hidden-import=_pytest.main` is not working and not correctly importing `_pytest.main`.

Last and least, it should probably go without saying that the other `--hidden-import=`'s have been added to solve similar `ImportError`'s (FWIW in the same L363 linked above) and they worked.

**Comment by Legorooj** [comment]
Closing due to inactivity
