### ISSUE TITLE
Issue with multiprocessing.Manager() and --onefile on Windows

### ISSUE THREAD

**Issue by devgc** [pyinstaller/pyinstaller#2028]
When I compile the following sample test code as --onedir the compiled application completes successfuly, however, when it runs with --onefile, the compiled application errors out with 'IOError: [Errno 6] The handle is invalid'

```
import multiprocessing
from multiprocessing.managers import BaseManager

class ProgressBar(object):
    def __init__(self):
        self.value = 0
    
class ProgressManager(BaseManager):
    pass

ProgressManager.register('ProgressBar', ProgressBar)

if __name__ == "__main__":
    multiprocessing.freeze_support()
    progressManager = ProgressManager()
    progressManager.start()
    print 'end'
```

I get the following error:

```
LOADER: Running test.py
Process ProgressManager-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 114, in run
  File "multiprocessing\managers.py", line 553, in _run_server
IOError: [Errno 6] The handle is invalid
LOADER: Back to parent (RC: 1)
LOADER: Doing cleanup
LOADER: Freeing archive status for D:\test\dist\test.exe
Traceback (most recent call last):
  File "test.py", line 16, in <module>
  File "multiprocessing\managers.py", line 528, in start
EOFError
Failed to execute script test
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for D:\test\dist\test.exe
```

This appears to be similar to an error that was marked as too old here: https://github.com/pyinstaller/pyinstaller/issues/1051

Here are my versions:
Python 2.7.11 x64 (also tried with Python 2.7.10 x64)
pyinstaller - 3.3.dev0+3de588a

If it helps, here is the spec file:
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['test.py'],
             pathex=['D:\\test'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='test',
          debug=1,
          strip=False,
          upx=False,
          console=True )
```

**Comment by devgc** [comment]
Any insight into this?

**Comment by matysek** [comment]
@devgc have you tried to look at this recipe? https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing

**Comment by devgc** [comment]
That does solve the issue. Thanks for the guidance.
