### ISSUE TITLE
ImportError: No module named 'past'

### ISSUE THREAD

**Issue by AndCycle** [pyinstaller/pyinstaller#2031]
Python 3.4.4
with pyinstaller develop head ver

pefile.py require https://pypi.python.org/pypi/future

```

Traceback (most recent call last):
  File "c:\Python34\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python34\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\AndCycle\Documents\work\corelight\proj\usermetagen\build\virtualenv_runtime\env\lib\site-packages\pyinstaller-3.3.dev0+gec3d094-py3.4.egg\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "D:\AndCycle\Documents\work\corelight\proj\usermetagen\build\virtualenv_runtime\env\lib\site-packages\pyinstaller-3.3.dev0+gec3d094-py3.4.egg\PyInstaller\building\build_main.py", line 34, in <module>
    from .api import PYZ, EXE, COLLECT, MERGE
  File "D:\AndCycle\Documents\work\corelight\proj\usermetagen\build\virtualenv_runtime\env\lib\site-packages\pyinstaller-3.3.dev0+gec3d094-py3.4.egg\PyInstaller\building\api.py", line 38, in <module>
    from PyInstaller.utils.win32 import winmanifest, icon, versioninfo, winresource
  File "D:\AndCycle\Documents\work\corelight\proj\usermetagen\build\virtualenv_runtime\env\lib\site-packages\pyinstaller-3.3.dev0+gec3d094-py3.4.egg\PyInstaller\utils\win32\versioninfo.py", line 18, in <module>
    from ...lib import pefile
  File "D:\AndCycle\Documents\work\corelight\proj\usermetagen\build\virtualenv_runtime\env\lib\site-packages\pyinstaller-3.3.dev0+gec3d094-py3.4.egg\PyInstaller\lib\pefile.py", line 26, in <module>
    from past.builtins import cmp, long
ImportError: No module named 'past'

```

**Comment by stephenrauch** [comment]
The new pefile requires 'future' to support PY3.  'future' was previously added as a requirement for the test suite to support tests against future. So the recent change to backout the pypi version of pefile passed the appveyor tests, and similarly passed on my machine because future was already present.

**Comment by matysek** [comment]
Patch was merged.
