### ISSUE TITLE
Import error when running an executable from a python script which imports lxml.etree

### ISSUE THREAD

**Issue by moagstar** [pyinstaller/pyinstaller#2059]
I am having difficulty getting a workable exe using lxml and pyinstaller, I get the following error message when running the built exe:

```
Traceback (most recent call last):
  File "pyinstaller_lxml.py", line 1, in <module>
    from lxml.etree import iterparse, QName
  File "c:\users\bradbu~1\appdata\local\temp\pip-build-lbikwr\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 546, in load_module
```

These are the various versions I am using:

```
Python 2.7.10
PyInstaller 3.2
lxml 3.4.4
Windows 10 (Version 1511 OS Build 10586.420)
```

Here is a minimal python example (just importing lxml.etree is enough):

```python
from lxml.etree import iterparse, QName
```

I build with the following command:
```
pyinstaller --clean --debug pyinstaller_lxml.py
```

This is the output:

```
100 INFO: PyInstaller: 3.2
100 INFO: Python: 2.7.10
100 INFO: Platform: Windows-8-6.2.9200
101 INFO: wrote D:\Personal\Sandbox\pyinstaller_lxml\pyinstaller_lxml.spec
105 INFO: UPX is not available.
105 INFO: Removing temporary files and cleaning cache in C:\Users\bradburnd\AppData\Roaming\pyinstaller
111 INFO: Extending PYTHONPATH with paths
['D:\\Personal\\Sandbox\\pyinstaller_lxml',
 'D:\\Personal\\Sandbox\\pyinstaller_lxml']
111 INFO: checking Analysis
111 INFO: Building Analysis because out00-Analysis.toc is non existent
111 INFO: Initializing module dependency graph...
118 INFO: Initializing module graph hooks...
197 INFO: running Analysis out00-Analysis.toc
203 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
266 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
269 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
272 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4974_none_f48176b4f6540019.manifest
273 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
273 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_f4813cfaf6543c37.manifest
338 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9177_none ...
338 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_5093cc7abcb795e9.manifest
340 INFO: Searching for file msvcr90.dll
341 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_5093cc7abcb795e9\msvcr90.dll
341 INFO: Searching for file msvcp90.dll
341 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_5093cc7abcb795e9\msvcp90.dll
342 INFO: Searching for file msvcm90.dll
342 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_5093cc7abcb795e9\msvcm90.dll
403 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
404 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
406 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4974_none_f48176b4f6540019.manifest
407 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
407 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_f4813cfaf6543c37.manifest
409 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9177)
557 INFO: Caching module hooks...
559 INFO: Analyzing D:\Personal\Sandbox\pyinstaller_lxml\pyinstaller_lxml.py
3090 INFO: Loading module hooks...
3090 INFO: Loading module hook "hook-lxml.etree.py"...
3121 INFO: Loading module hook "hook-httplib.py"...
3121 INFO: Loading module hook "hook-clr.py"...
3125 INFO: Loading module hook "hook-encodings.py"...
3562 INFO: Looking for ctypes DLLs
3571 INFO: Analyzing run-time hooks ...
3577 INFO: Looking for dynamic libraries
3986 INFO: Looking for eggs
3986 INFO: Using Python library C:\WINDOWS\system32\python27.dll
3986 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9177), publicKeyToken=u'1fc8b3b9a1e18e3b')]
3995 INFO: Warnings written to D:\Personal\Sandbox\pyinstaller_lxml\build\pyinstaller_lxml\warnpyinstaller_lxml.txt
4036 INFO: checking PYZ
4038 INFO: Building PYZ because out00-PYZ.toc is non existent
4038 INFO: Building PYZ (ZlibArchive) D:\Personal\Sandbox\pyinstaller_lxml\build\pyinstaller_lxml\out00-PYZ.pyz
4387 INFO: checking PKG
4387 INFO: Building PKG because out00-PKG.toc is non existent
4388 INFO: Building PKG (CArchive) out00-PKG.pkg
4410 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run_d.exe
4410 INFO: checking EXE
4410 INFO: Building EXE because out00-EXE.toc is non existent
4411 INFO: Building EXE from out00-EXE.toc
4411 INFO: Appending archive to EXE D:\Personal\Sandbox\pyinstaller_lxml\build\pyinstaller_lxml\pyinstaller_lxml.exe
4444 INFO: checking COLLECT
4444 INFO: Building COLLECT because out00-COLLECT.toc is non existent
WARNING: The output directory "D:\Personal\Sandbox\pyinstaller_lxml\dist\pyinstaller_lxml" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
7170 INFO: Removing dir D:\Personal\Sandbox\pyinstaller_lxml\dist\pyinstaller_lxml
7177 INFO: Building COLLECT out00-COLLECT.toc
7209 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9177)
7347 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9177)
7348 INFO: Updating manifest in C:\Users\bradburnd\AppData\Roaming\pyinstaller\bincache00_py27_32bit\python27.dll
7348 INFO: Updating resource type 24 name 2 language 1033
7623 INFO: Updating manifest in C:\Users\bradburnd\AppData\Roaming\pyinstaller\bincache00_py27_32bit\lxml.etree.pyd
7624 INFO: Updating resource type 24 name 2 language 1033
```

And run with the following command
```
"./dist/pyinstaller_lxml/pyinstaller_lxml.exe"
```

This is the output of running:

```
PyInstaller Bootloader 3.x
LOADER: executable is D:\Personal\Sandbox\pyinstaller_lxml\dist\pyinstaller_lxml\pyinstaller_lxml.exe
LOADER: homepath is D:\Personal\Sandbox\pyinstaller_lxml\dist\pyinstaller_lxml
LOADER: _MEIPASS2 is NULL
LOADER: archivename is D:\Personal\Sandbox\pyinstaller_lxml\dist\pyinstaller_lxml\pyinstaller_lxml.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(D:\Personal\Sandbox\pyinstaller_lxml\dist\pyinstaller_lxml)
LOADER: Already in the child - running user's code.
LOADER: Python library: D:\Personal\Sandbox\pyinstaller_lxml\dist\pyinstaller_lxml\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is D:\Personal\Sandbox\PYINST~1\dist\PYINST~1
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is D:\Personal\Sandbox\pyinstaller_lxml\dist\pyinstaller_lxml
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyinstaller_lxml.py
Traceback (most recent call last):
  File "pyinstaller_lxml.py", line 1, in <module>
    from lxml.etree import iterparse, QName
  File "c:\users\bradbu~1\appdata\local\temp\pip-build-lbikwr\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 546, in load_module
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Failed to execute script pyinstaller_lxml
LOADER: OK.
LOADER: Cleaning up Python interpreter.
```

I tried using the DependencyWalker to figure out if there is something missing however I couldn't really make much sense of the output.

This is the output of the generated .spec file:

```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['pyinstaller_lxml.py'],
             pathex=['D:\\Personal\\Sandbox\\pyinstaller_lxml'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='pyinstaller_lxml',
          debug=True,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='pyinstaller_lxml')
```

**Comment by stephenrauch** [comment]
As an FYI worked for me with:

407 INFO: PyInstaller: 3.3.dev0+g8689a5d.mod
407 INFO: Python: 2.7.11
407 INFO: Platform: Windows-7-6.1.7601-SP1

**Comment by moagstar** [comment]
I just tried this downloaded a development version and can confirm that this fixes the problem. @stephenrauch thanks for the tip.
