### ISSUE TITLE
cffi.verify spits error in xcffib

### ISSUE THREAD

**Issue by timeyyy** [pyinstaller/pyinstaller#2067]
Pyinstaller version 3.2
python 3.4.3 x86
Ubuntu-Linux
module: [xcffib](https://github.com/tych0/xcffib)

Error happens when running the simple script (after bundling, in both single file and directory mode)
example python script `t.py` below fails

```python
import xcffib
print('hi')
```

here is a snippet from ffi.py which results in our error

```python
C = ffi.verify("""
    #include <stdlib.h>
    #include <xcb/xcb.h>
    #include <xcb/xcbext.h>
    #include <xcb/render.h>

    xcb_connection_t *wrap(long ptr) {
        return (xcb_connection_t *) ptr;
    }
""", libraries=['xcb'], modulename='_xcffib')
``` 
I noticed that in the cwd that i run the script  from, `xcffib/__pycache__/_xcffib.c` will be created. 

cffi.verify works as follows:
> when you call the ffi.verify function CFFI will attempt to load an already compiled module for this    FFI instance, and failing to find it will implicitly compile a new one and then load it. 

I had a peak in `hook-cryptography.py` (also using cffi) and tried applying similar tactics but nothing changed.

```bash
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    import xcffib
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "xcffib/__init__.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "xcffib/ffi.py", line 256, in <module>
  File "cffi/api.py", line 373, in verify
  File "cffi/verifier.py", line 96, in load_library
  File "cffi/verifier.py", line 192, in _compile_module
  File "cffi/ffiplatform.py", line 38, in compile
  File "cffi/ffiplatform.py", line 62, in _build
  File "distutils/dist.py", line 973, in run_command
  File "distutils/cmd.py", line 107, in ensure_finalized
  File "distutils/command/build_ext.py", line 137, in finalize_options
  File "distutils/cmd.py", line 286, in set_undefined_options
  File "distutils/dist.py", line 846, in get_command_obj
  File "distutils/dist.py", line 832, in get_command_class
distutils.errors.DistutilsModuleError: invalid command 'build'
Failed to execute script t
```
I will try understanding more what cffi.verify is doing and why it's not working. Just posting here if anyone has any insight

**Comment by tallforasmurf** [comment]
The code snippet, `C = ffi.verify("""...` boggles my mind. The only purpose I can see is that this ffi module at runtime is going to invoke a C compiler to test that it can compile that code and ... are they actually going to try to link it as `_xcffib.dll` and then import it? (amazed emoji here)

Well, even the first part means that this code requires a working C compiler on the execution path at run-time. There is no way PyInstaller can provide that.

**Comment by codewarrior0** [comment]
Are you using an old version of `xcffib`? I don't see any calls to `ffi.verify` in the latest sources.

**Comment by timeyyy** [comment]
Upgrading... and solved :/
