### ISSUE TITLE
How to get PyInstaller to use standard library files from the correct python version?

### ISSUE THREAD

**Issue by Atheros1** [pyinstaller/pyinstaller#2081]
PyInstaller appears to be pulling in standard library files from a different python version. How can I prevent this?

Versions:
- Ubuntu 14.04 (64-bit)
- PyInstaller: 3.2
- Platform: Linux-4.2.0-38-generic-x86_64-with-debian-jessie-sid

Ubuntu comes with Python 2.7.6 by default which is not sufficient. I installed Python 2.7.12 using the source code and it runs nicely when I type _python2.7_. 

This test script runs just fine in both python 2.7.6 and python 2.7.12:

```
import hmac
import hashlib
msg = "hi there"
print "output:", hmac.new(b'1234567890', msg=msg, digestmod=hashlib.sha256).digest().encode('hex')
```

I can compile it just fine using _python2.7 pyinstaller.py test.py_

But when I run ./test , it complains:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
  File "/home/vubuntu/Downloads/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "hmac.py", line 8, in <module>
ImportError: cannot import name _compare_digest
```

[This post](https://stackoverflow.com/questions/26535043/python-flask-error-importerror-cannot-import-name-compare-digest) suggests that it is using the wrong standard library files with the Python binary. 
I've tried doing this both inside and outside of a virtualenv. Is there a way to get it to not use the wrong standard library files?

Other threads recommended that I turn on a verbose option. Here is the output although I don't know if it is interesting to you:

```
...    
# encodings.__builtin__ not found in PYZ
# encodings.__builtin__ not found in PYZ
# ctypes not found in PYZ
import hmac # PyInstaller PYZ
import operator # builtin
Traceback (most recent call last):
  File "test.py", line 3, in <module>
  File "/home/vubuntu/Downloads/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "hmac.py", line 8, in <module>
ImportError: cannot import name _compare_digest
Failed to execute script test
# clear __builtin__._
# clear sys.path
...
```

**Comment by tallforasmurf** [comment]
I think it is too soon to suppose the problem is differing Python versions. Pyinstaller uses the version of Python that is executing the PyInstaller command as its source for all modules. Or more specifically, it uses the sys.path managed by that Python, to find installed modules. Then it puts *all* imported modules into the output folder.

When it finishes you should have a folder `./dist/test` and an executable `./dist/test/test` -- I assume that is what you mean when you "run ./test"? When that executable runs, the PyInstaller bootloader code gets its Python interpreter and all imported modules from the archive that is part of the executable, or from inside the `dist/test` folder.

It appears that the imported module `hmac` is not finding something. If you have not already done so, have a look at ["Make Sure Everything is Packaged"](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) and the rest of that page.

I'm a little puzzled in that the only module hmac I see on pypi is documented as "Not needed with Python 2.5 or later." Maybe you could drop it in favor of the hashlib module?

**Comment by Atheros1** [comment]
Thank you for your reply. The hmac module was just one module I needed; this was just the minimum failing program I was able to come up with. After much fiddling, I was able to solve this by configuring the Python compiler to build a shared object file and set an environmental variable to point to it. Hopefully this helps someone else.

When compiling and installing Python, instead of 

    sudo ./configure --enable-unicode=ucs4

..I did:

    sudo ./configure --enable-unicode=ucs4 -enable-shared

(followed by the normal _sudo make altinstall_)

I then searched for "libpython2.7" and found libpython2.7.so in /usr/local/lib where it wasn't before so I did this:

    export LD_LIBRARY_PATH=/usr/local/lib

And then pyinstaller was able to make use of it:

    3698 INFO: Using Python library /usr/local/lib/libpython2.7.so.1.0

**Comment by tallforasmurf** [comment]
I'm glad you resolved this. Some puzzling things. The doc does note that PyInstaller [requires a Python DLL](http://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html?highlight=static#build-time-python-errors) however that same section says there is an error message at build time.  No message, so PyInstaller did find something that it bundled as a Python DLL. Maybe you were right in the first place and it looked in the usual places and found a DLL for a different Python? (do a `find /usr -name 'libpyth* -print` to see if there are some others)

**Comment by Atheros1** [comment]
vubuntu@vubuntu:~$ find /usr -name 'libpyth*' -print
    /usr/share/doc/libpython3.4-minimal
    /usr/share/doc/libpython2.7-minimal
    /usr/share/doc/libpython3.4
    /usr/share/doc/libpython2.7-stdlib
    /usr/share/doc/libpython2.7
    /usr/share/doc/libpython2.7-dev
    /usr/share/doc/libpython3-stdlib
    /usr/share/doc/libpython-stdlib
    /usr/share/doc/libpython-dev
    /usr/share/doc/libpython3.4-stdlib
    /usr/share/lintian/overrides/libpython3.4-minimal
    /usr/share/lintian/overrides/libpython2.7-minimal
    /usr/share/lintian/overrides/libpython3.4
    /usr/share/lintian/overrides/libpython2.7-stdlib
    /usr/share/lintian/overrides/libpython2.7
    /usr/share/lintian/overrides/libpython2.7-dev
    /usr/share/lintian/overrides/libpython3.4-stdlib
    /usr/local/lib/libpython2.7.so.1.0
    /usr/local/lib/libpython2.7.a
    /usr/local/lib/python2.7/config/libpython2.7.a
    /usr/local/lib/libpython2.7.so
    /usr/src/Python-2.7.12/Tools/gdb/libpython.py
    /usr/src/Python-2.7.12/libpython2.7.so.1.0
    /usr/src/Python-2.7.12/libpython2.7.a
    /usr/src/Python-2.7.12/libpython2.7.so
    /usr/lib/libpeas-1.0/loaders/libpython3loader.so
    /usr/lib/libpeas-1.0/loaders/libpythonloader.so
    /usr/lib/python3.4/config-3.4m-x86_64-linux-gnu/libpython3.4.so
    /usr/lib/python3.4/config-3.4m-x86_64-linux-gnu/libpython3.4m.so
    /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.a
    /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
    /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7-pic.a
    /usr/lib/x86_64-linux-gnu/libpython3.4m.so.1
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1
    /usr/lib/x86_64-linux-gnu/libpython2.7.a
    /usr/lib/x86_64-linux-gnu/libpython2.7.so
    /usr/lib/x86_64-linux-gnu/libpython3.4m.so.1.0
    /usr/lib/libreoffice/program/libpythonloaderlo.so

I think it did bundle the wrong Python SO file. I went and removed the libpython files in /usr/local/lib/ and reran pyinstaller to see what it would do and this is the one it used:

    2916 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0

**Comment by tallforasmurf** [comment]
@htgoebel you are a linux guru, why are there so many `libpython2.7*` files in so many places in this system, and how would PyInstaller know which to use?

**Comment by Legorooj** [comment]
Closing due to inactivity. @tallforasmurf `hmac` is part of the python standard library.
