### ISSUE TITLE
boto3 1.3.1 unsupported: ImportError: No module named HTMLParser

### ISSUE THREAD

**Issue by jessesuen** [pyinstaller/pyinstaller#2094]
Pyinstaller is unable to bundle a package which imports boto3. It fails with import error: `ImportError: No module named HTMLParser`

Sample script

```
#!/usr/bin/env python
import boto3
print("hello world")
```

Environment details

```
$ python --version
Python 2.7.11

$ pyinstaller --version
3.2

$ pip freeze
boto3==1.3.1
botocore==1.4.36
docutils==0.12
futures==3.0.5
jmespath==0.9.0
PyInstaller==3.2
python-dateutil==2.5.3
six==1.10.0
```

Here is the output of the script (with debug mode enabled):

```
$ ./dist/importboto/importboto
PyInstaller Bootloader 3.x
LOADER: executable is /Users/jesse/dist/importboto/importboto
LOADER: homepath is /Users/jesse/dist/importboto
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /Users/jesse/dist/importboto/importboto
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /Users/jesse/dist/importboto
PyInstaller Bootloader 3.x
LOADER: executable is /Users/jesse/dist/importboto/importboto
LOADER: homepath is /Users/jesse/dist/importboto
LOADER: _MEIPASS2 is /Users/jesse/dist/importboto
LOADER: archivename is /Users/jesse/dist/importboto/importboto
LOADER: Already in the child - running user's code.
LOADER: Python library: /Users/jesse/dist/importboto/.Python
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is /Users/jesse/dist/importboto
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /Users/jesse/dist/importboto
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running importboto.py
Failed to execute script importboto
Traceback (most recent call last):
  File "importboto.py", line 2, in <module>
    import boto3
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/boto3/__init__.py", line 16, in <module>
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/boto3/session.py", line 17, in <module>
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/botocore/session.py", line 27, in <module>
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/botocore/client.py", line 18, in <module>
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/botocore/waiter.py", line 18, in <module>
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/botocore/docs/__init__.py", line 15, in <module>
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/botocore/docs/service.py", line 18, in <module>
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/botocore/docs/bcdoc/restdoc.py", line 16, in <module>
  File "/private/var/folders/3p/dgr1_d756pn7kfdq1shytv5w0000gn/T/pip-build-8v70Zc/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/botocore/docs/bcdoc/docstringparser.py", line 16, in <module>
  File "site-packages/botocore/vendored/six.py", line 89, in __get__
  File "site-packages/botocore/vendored/six.py", line 108, in _resolve
  File "site-packages/botocore/vendored/six.py", line 79, in _import_module
ImportError: No module named HTMLParser
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /Users/jesse/dist/importboto/importboto
```

**Comment by jessesuen** [comment]
Line 16 of botocore/docs/bcdoc/docstringparser.py is the class definition of DocStringParser:

```
from botocore.compat import six


class DocStringParser(six.moves.html_parser.HTMLParser):
    """
    A simple HTML parser.  Focused on converting the subset of HTML
    that appears in the documentation strings of the JSON models into
    simple ReST format.
    """
```
