### ISSUE TITLE
problems with python xy after installing pyInstaller

### ISSUE THREAD

**Issue by iakovace** [pyinstaller/pyinstaller#2097]
I use Spyder from python XY to develop scientific/numeric applications.

I installed pyInstaller and right after that spyder stop runing. Bellow you can find the error.

Any help?

Traceback (most recent call last):
  File "C:\Python27\Scripts\xyhome.pyw", line 20, in <module>
    from xy import xyhome
  File "C:\Python27\lib\site-packages\xy\xyhome.pyw", line 60, in <module>  
    from xy.config import (CONF, STARTUP_PATH, LOG_PATH, PLUGINS, XY_VERSION,
  File "C:\Python27\lib\site-packages\xy\config.py", line 40, in <module>
    CONF = UserConfig('xy', defaults=DEFAULTS, version=**version**, subfolder='.xy')
  File "C:\Python27\lib\site-packages\xy\userconfig.py", line 110, in **init**
    if version != self.get_version(version):
  File "C:\Python27\lib\site-packages\xy\userconfig.py", line 130, in get_version
    return self.get(self.DEFAULT_SECTION_NAME, 'version', version)
  File "C:\Python27\lib\site-packages\xy\userconfig.py", line 266, in get
    self.set(section, option, default)
  File "C:\Python27\lib\site-packages\xy\userconfig.py", line 332, in set
    self.__save()
  File "C:\Python27\lib\site-packages\xy\userconfig.py", line 167, in __save
    self.write(conf_file)
  File "C:\Python27\lib\ConfigParser.py", line 407, in write
    fp.write("[%s]\n" % section)
TypeError: must be unicode, not str

**Comment by Legorooj** [comment]
Closing due to inactivity.
