### ISSUE TITLE
ImportError when running an executable from a python script involving Theano

### ISSUE THREAD

**Issue by Rafantasy** [pyinstaller/pyinstaller#2114]
I want to use python library "Theano" to do neural networking analysis, but encounter the problem when packing the libraries with Pyinstaller.

Here is the script, which include only one line:

`import theano`

The following is the output of pyinstaller:
```
28 INFO: PyInstaller: 3.2
29 INFO: Python: 2.7.10
29 INFO: Platform: Linux-2.6.32-358.el6.x86_64-x86_64-with-redhat-6.4-Santiago
30 INFO: wrote /home/primea/STC/data/test_nnet/test/theano_test.spec
34 INFO: UPX is not available.
35 INFO: Extending PYTHONPATH with paths
['/home/primea/STC/data/test_nnet/test',
 '/home/primea/STC/data/test_nnet/test']
35 INFO: checking Analysis
35 INFO: Building Analysis because out00-Analysis.toc is non existent
36 INFO: Initializing module dependency graph...
37 INFO: Initializing module graph hooks...
77 INFO: running Analysis out00-Analysis.toc
90 INFO: Caching module hooks...
95 INFO: Analyzing /home/primea/STC/data/test_nnet/test/theano_test.py
1776 INFO: Processing pre-find module path hook   distutils
4295 INFO: Processing pre-safe import module hook   _xmlplus
4657 INFO: Processing pre-find module path hook   site
4657 INFO: site: retargeting to fake-dir '/opt/python27/lib/python2.7/site-packages/PyInstaller/fake-modules'
4686 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named win32com
4705 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named win32com
6362 INFO: Processing pre-safe import module hook   six.moves
14197 INFO: Loading module hooks...
14198 INFO: Loading module hook "hook-distutils.py"...
14199 INFO: Loading module hook "hook-sysconfig.py"...
14199 INFO: Loading module hook "hook-xml.py"...
14257 INFO: Loading module hook "hook-httplib.py"...
14257 INFO: Loading module hook "hook-pydoc.py"...
14261 INFO: Excluding import 'Tkinter'
14264 WARNING:   Removing import pydoc from module Tkinter
14264 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
14265 INFO: Loading module hook "hook-pkg_resources.py"...
14268 INFO: Loading module hook "hook-scipy.linalg.py"...
14269 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
14272 INFO: Loading module hook "hook-setuptools.py"...
14273 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
14274 INFO: Loading module hook "hook-encodings.py"...
14690 INFO: Looking for ctypes DLLs
14753 INFO: Analyzing run-time hooks ...
14777 INFO: Including run-time hook 'pyi_rth_pkgres.py'
14814 INFO: Looking for dynamic libraries
15869 INFO: Looking for eggs
15869 INFO: Using Python library /usr/local/lib/libpython2.7.so.1.0
15922 INFO: Warnings written to /home/primea/STC/data/test_nnet/test/build/theano_test/warntheano_test.txt
16194 INFO: checking PYZ
16194 INFO: Building PYZ because out00-PYZ.toc is non existent
16194 INFO: Building PYZ (ZlibArchive) /home/primea/STC/data/test_nnet/test/build/theano_test/out00-PYZ.pyz
17964 INFO: checking PKG
17964 INFO: Building PKG because out00-PKG.toc is non existent
17964 INFO: Building PKG (CArchive) out00-PKG.pkg
62261 INFO: Bootloader /opt/python27/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
62261 INFO: checking EXE
62261 INFO: Building EXE because out00-EXE.toc is non existent
62261 INFO: Building EXE from out00-EXE.toc
62261 INFO: Appending archive to ELF section in EXE /home/primea/STC/data/test_nnet/test/dist/theano_test
```
This is the prompt when running the executable file:
```
Traceback (most recent call last):
  File "theano_test.py", line 1, in <module>
  File "/opt/python27/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/theano/__init__.py", line 210, in <module>
ImportError: No module named shared_randomstreams
Failed to execute script theano_test
```
Software version:
```
Python: 2.7.10
OS: RHEL 6.4
Pyinstaller: 3.2
```

The related Python Modules(requirements for Theano) version:
```
Keras (1.0.6)
numpy (1.11.1)
pandas (0.18.1)
scikit-learn (0.17.1)
scipy (0.17.1)
Theano (0.8.2)
```

**Comment by htgoebel** [comment]
Just look at "site-packages/theano/__init__.py", line 210, which reads:
```
__import__('theano.tensor.shared_randomstreams')
```

This is an import PyInstaller can not detect. You need to add it as an hidden import (see manual).

We would appreciate if you'd submit a hook for this. See https://pyinstaller.readthedocs.org/en/latest/hooks.html for more information about who to implement hooks.

**Comment by Rafantasy** [comment]
@htgoebel Thanks for your reply.
I have tried the method 
`pyinstaller --onefile --hiddern-import=theano.tensor.shared_randomstreams theano_test.py`
It can run normally on my machine now; but when copied the executable file to another machine which does not install "Theano", it can not work.
What should be done to make it work normally on a new machine without installing "Theano"?

**Comment by htgoebel** [comment]
Well, I don't know theano and don't have it installed. But this sounds like like not all required files are packaged.

Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by fahimkhan** [comment]
I also had same issue with hidden import. I tried hook script as well but it doesn't workout.

Finally I look have to import the hidden package which inside my py file even though I was not using it directly but it was being used indirectly.

I think if you import theano.tensor.shared_randomstreams in one of your python file then it should work.

**Comment by MaratZakirov** [comment]
Hello guys I came from duplicate bug and I know something useful for you.
Use THEANO_FLAGS=cxx=        my_keras_or_theano_script.exe to switch off compiling
My example, compile it with pyinstaller --onefile:
```
import os
os.environ['KERAS_BACKEND']='theano'

import keras
import theano.tensor.shared_randomstreams

print "Hello keras"

from keras.models import Sequential
from keras.layers import Dense, Activation, LSTM, Input
from keras.models import Model
import numpy

x_data = numpy.array([[1, 3], [4, 5], [6, 7], [8, 9]]).astype('float32')
l_data = numpy.array([0.3, 0.5, -0.7, 0.8]).astype('float32')

model = Sequential([Dense(1, input_dim=2), Activation('linear')])
model.compile(optimizer='sgd', loss='mse')

model.fit(x = x_data, y=l_data)
```
Then start on any machine with 
THEANO_FLAGS=cxx=        my_keras_or_theano_script.exe

**Comment by avielbl** [comment]
Hi,
I tried your solution with setting the cxx flag to my executable but it fails as it tries to use it as the compiler.
Is there a way to make an executable packed by pyinstaller to use a precompiled directory somehow and solve this issue together with allowing theano to run with its fancy optimizations?
Aviel

**Comment by MaratZakirov** [comment]
@avielbl Worked for me on ubuntu 15.04. Ensure that THEANO_FLAGS=cxx=<WHITESPACE>script.exe

**Comment by cbdbdd** [comment]
my operating system is win10. and i followed@MaratZakirov method: pyinstaller --onefile your_script.py
then i open cmd,  i put:  set THEANO_FLAGS="cxx= " & your_script.exe
error occurs as follows:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\myaccount\\dist\\your_script\\theano\\gpuarray\\blockgemv.c'
Failed to execute script your_script

then i tried cmd command:     set THEANO_FLAGS="cxx= " &  set THEANO_FLAGS="device=cpu" & your_script.exe
error again:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\myaccount\\dist\\your_script\\theano\\gpuarray\\blockgemv.c'
Failed to execute script your_script

then i tried:   in folder  'C:\\Users\\myaccount\\dist\\your_script\\'  create folder:  ''theano\\gpuarray\\", then put 'blockgemv.c'  and 'blockger.c' in this folder. these two files can be found in your 'C:\Users\myaccount\Anaconda2\Lib\site-packages\theano\gpuarray' folder.
then set THEANO_FLAGS="cxx= " & your_script.exe gets worked.

however, this exe can only be used in cpu mode. i  cannot use gpu device.

if i try:set THEANO_FLAGS="device=gpu" & C:\Users\myaccount\dist\your_script\your_script.exe

error:
Exception: Compilation failed (return status=1): C:\Users\myaccount\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-2.7.12-64\cutils_ext\mod.cpp:2:28: fatal error: Python.h: No such f. compilation terminated.
Failed to execute script your_script

**Comment by cbdbdd** [comment]
seems like pyinstaller cannot find 'blockgemv.c' and 'blockger.c' and you need to put them in correct place before you can get your script.exe work. Therefore, you also cannot use pyinstaller --onefile command.

wait for better solutions.

**Comment by huodng** [comment]
@MaratZakirov 
I had error like [#2512](https://github.com/pyinstaller/pyinstaller/issues/2512)
When I set THEANO_FLAGS=cxx=my_keras_or_theano_script.exe . It hadn't error occurs but nothing happened. At the same time, so many processes are running.
Is this a multithreaded problem？Many thanks！

**Comment by htgoebel** [comment]
Quite a few people are having this issue. What about submitting a pull-request with an appropriate hook?

**Comment by siyaxiaa** [comment]
@cbdbdd  
Hi, did you figure out how to run the executable file in GPU mode?  I got the same challenge: it only works in cpu mode but not gpu. Also, the warning appears:

WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.

**Comment by juharris** [comment]
I was able to get around some of those issues posted here regarding missing files. In `cmd`:
```
pyinstaller --noconfirm --onefile ^
  --hidden-import=theano.tensor.shared_randomstreams ^
  --add-data C:\dev\Anaconda3\envs\env_name\Lib\site-packages\theano;theano ^
  --add-data C:\dev\Anaconda3\envs\env_name\include;Include ^
  --add-data C:\dev\Anaconda3\envs\env_name\Lib\site-packages\numpy\core\include;Include ^
  script.py
```

However, I get this error (note that I redacted some insignificant parts):
```
ERROR (theano.gof.cmodule): [WinError 123] The filename, directory name, or volume label syntax is incorrect: "['C:\\\\Users\\\\[REDACTED]\\\\Library\\\\bin']"
[ERROR] 2017-07-12 16:33:41,366 - cmodule.py::module_from_key
[WinError 123] The filename, directory name, or volume label syntax is incorrect: "['C:\\\\Users\\\\[REDACTED]\\\\Library\\\\bin']"

[REDACTED]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\theano\gof\cc.py", line 1099, in lib_dirs
TypeError: c_lib_dirs() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  [REDACTED]
  File "site-packages\theano\compile\function.py", line 326, in function
  File "site-packages\theano\compile\pfunc.py", line 486, in pfunc
  File "site-packages\theano\compile\function_module.py", line 1810, in orig_function
  File "site-packages\theano\compile\function_module.py", line 1674, in create
  File "site-packages\theano\gof\link.py", line 699, in make_thunk
  File "site-packages\theano\gof\vm.py", line 1055, in make_all
  File "site-packages\theano\gof\op.py", line 954, in make_thunk
  File "site-packages\theano\gof\op.py", line 858, in make_c_thunk
  File "site-packages\theano\gof\cc.py", line 1206, in make_thunk
  File "site-packages\theano\gof\cc.py", line 1147, in __compile__
  File "site-packages\theano\gof\cc.py", line 1602, in cthunk_factory
  File "site-packages\theano\gof\cmodule.py", line 1156, in module_from_key
  File "site-packages\theano\gof\cc.py", line 1503, in compile_cmodule
  File "site-packages\theano\gof\cc.py", line 1101, in lib_dirs
  File "site-packages\theano\tensor\blas_c.py", line 20, in c_lib_dirs
  File "site-packages\theano\tensor\blas.py", line 386, in ldflags
  File "site-packages\theano\gof\utils.py", line 257, in rval
  File "site-packages\theano\tensor\blas.py", line 423, in _ldflags
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: "['C:\\\\Users\\\[REDACTED]\\\\Library\\\\bin']"
Failed to execute script script
```

It happens with `--onefile` and without `--onefile`.

Has anyone gotten past syntax error?

**Comment by MikeVlad6** [comment]
Dunno if it's going to help anyone but i'm just going to put it here:
Just had a problem where Pyinstaller was importing all kinds of modules when i imported openpyxl or pandas and the .exe file had 200 mb. 
The solution i found was to make a virtual environment with `--no-site-packages` option and just install there only the modules i actively used. Pyinstaller worked very well, .exe ended up having 8mb.

**Comment by juharris** [comment]
@MikeVlad6 Interesting. It's not documented. How did you find that and what version of pyinstaller are you using?

**Comment by MikeVlad6** [comment]
@juharris Pyinstaller version is `3.3.dev0+964547c` . I saw that pyinstaller was importing libraries that apparently had nothing to do with my script - such as PyQt5 which i certainly didn't use. 
From what i read 

> https://github.com/pyinstaller/pyinstaller/issues/2652

 it seems that @htgoebel was explaining that Pyinstaller tries to include whatever module it thinks you might need. Probably one of my included modules, openpyxl imported pandas somewhere, pandas imported some other module and so i finally got PtQt5 in my build. 
So the solution looks like to use pyinstaller in an environment where you have only what you need installed.
I tried using --exlcude-module but had no luck so virtualenv did the thing.
