### ISSUE TITLE
test_multiprocessing[onefile] failure on under Windows

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#2116]
The title captures this issue. Debug steps so far: per https://docs.python.org/2/library/multiprocessing.html#logging, adding logging produces:

On Python 2.7 onedir, this yields:

```
PyInstaller Bootloader 3.x
LOADER: executable is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess\pyi_multiprocess.exe
LOADER: homepath is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess
LOADER: _MEIPASS2 is NULL
LOADER: archivename is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess\pyi_multiprocess.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess)
LOADER: Already in the child - running user's code.
LOADER: Python library: c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is c:\Users\bjones\AppData\Local\Temp\PYTEST~1\pytest-8\TEST_M~1\dist\PYI_MU~1
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_multiprocess.py
main begins
[DEBUG/MainProcess] created semlock with handle 708
[DEBUG/MainProcess] created semlock with handle 712
[DEBUG/MainProcess] Queue._after_fork()
PyInstaller Bootloader 3.x
LOADER: executable is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess\pyi_multiprocess.exe
LOADER: homepath is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess
LOADER: _MEIPASS2 is NULL
LOADER: archivename is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess\pyi_multiprocess.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess)
LOADER: Already in the child - running user's code.
LOADER: Python library: c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is c:\Users\bjones\AppData\Local\Temp\PYTEST~1\pytest-8\TEST_M~1\dist\PYI_MU~1
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onedir_0\dist\pyi_multiprocess
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_multiprocess.py
[DEBUG/SendeventProcess-1] recreated blocker with handle 40
[DEBUG/SendeventProcess-1] recreated blocker with handle 40
[DEBUG/SendeventProcess-1] recreated blocker with handle 36
[DEBUG/SendeventProcess-1] recreated blocker with handle 36
[DEBUG/SendeventProcess-1] Queue._after_fork()
[DEBUG/SendeventProcess-1] Queue._after_fork()
[INFO/SendeventProcess-1] child process calling self.run()
[INFO/SendeventProcess-1] child process calling self.run()
SendeventProcess begins
[DEBUG/SendeventProcess-1] Queue._start_thread()
[DEBUG/SendeventProcess-1] Queue._start_thread()
[DEBUG/SendeventProcess-1] doing self._thread.start()
[DEBUG/SendeventProcess-1] doing self._thread.start()
[DEBUG/SendeventProcess-1] starting thread to feed data to pipe
[DEBUG/SendeventProcess-1] ... done self._thread.start()
[DEBUG/SendeventProcess-1] starting thread to feed data to pipe
[DEBUG/SendeventProcess-1] ... done self._thread.start()
SgendeventProcess endset ends

[INFO/SendeventProcess-1] process shutting down
[INFO/SendeventProcess-1] process shutting down
[DEBUG/SendeventProcess-1] running all "atexit" finalizers with priority >= 0
[DEBUG/SendeventProcess-1] running all "atexit" finalizers with priority >= 0
[DEBUG/SendeventProcess-1] telling queue thread to quit
[DEBUG/SendeventProcess-1] telling queue thread to quit
[DEBUG/SendeventProcess-1] running the remaining "atexit" finalizers
[DEBUG/SendeventProcess-1] running the remaining "atexit" finalizers
[DEBUG/SendeventProcess-1] feeder thread got sentinel -- exiting
[DEBUG/SendeventProcess-1] feeder thread got sentinel -- exiting
[DEBUG/SendeventProcess-1] joining queue thread
[DEBUG/SendeventProcess-1] joining queue thread
[DEBUG/SendeventProcess-1] ... queue thread joined
[DEBUG/SendeventProcess-1] ... queue thread joined
[INFO/SendeventProcess-1] process exiting with exitcode 0
[INFO/SendeventProcess-1] process exiting with exitcode 0
main ends
Traceback (most recent call last):
  File "scripts\pyi_multiprocess.py", line 49, in <module>
AssertionError
Failed to execute script pyi_multiprocess
LOADER: OK.
LOADER: Cleaning up Python interpreter.
[INFO/MainProcess] process shutting down
[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
[DEBUG/MainProcess] running the remaining "atexit" finalizers
```

On Python 2.7 onefile, this yields:

```
PyInstaller Bootloader 3.x
LOADER: executable is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
LOADER: homepath is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\bjones\AppData\Local\Temp\_MEI77842
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
LOADER: homepath is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist
LOADER: _MEIPASS2 is C:\Users\bjones\AppData\Local\Temp\_MEI77842
LOADER: archivename is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
LOADER: SetDllDirectory(C:\Users\bjones\AppData\Local\Temp\_MEI77842)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\bjones\AppData\Local\Temp\_MEI77842\pyi_multiprocess.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\bjones\AppData\Local\Temp\_MEI77842\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\bjones\AppData\Local\Temp\_MEI77~1
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename pyi_multiprocess.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\bjones\AppData\Local\Temp\_MEI77842
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out01-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_multiprocess.py
main begins
[DEBUG/MainProcess] created semlock with handle 700
[DEBUG/MainProcess] created semlock with handle 176
[DEBUG/MainProcess] Queue._after_fork()
PyInstaller Bootloader 3.x
LOADER: executable is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
LOADER: homepath is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\bjones\AppData\Local\Temp\_MEI19042
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
LOADER: homepath is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist
LOADER: _MEIPASS2 is C:\Users\bjones\AppData\Local\Temp\_MEI19042
LOADER: archivename is c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
LOADER: SetDllDirectory(C:\Users\bjones\AppData\Local\Temp\_MEI19042)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\bjones\AppData\Local\Temp\_MEI19042\pyi_multiprocess.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\bjones\AppData\Local\Temp\_MEI19042\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\bjones\AppData\Local\Temp\_MEI19~1
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename pyi_multiprocess.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\bjones\AppData\Local\Temp\_MEI19042
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out01-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_multiprocess.py
[DEBUG/SendeventProcess-1] recreated blocker with handle 28
[DEBUG/SendeventProcess-1] recreated blocker with handle 28
[DEBUG/SendeventProcess-1] recreated blocker with handle 40
[DEBUG/SendeventProcess-1] recreated blocker with handle 40
[DEBUG/SendeventProcess-1] Queue._after_fork()
[DEBUG/SendeventProcess-1] Queue._after_fork()
[INFO/SendeventProcess-1] child process calling self.run()
[INFO/SendeventProcess-1] child process calling self.run()
SendeventProcess begins
Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "scripts\pyi_multiprocess.py", line 34, in run
  File "multiprocessing\queues.py", line 101, in put
KeyboardInterrupt
[INFO/SendeventProcess-1] process exiting with exitcode 1
[INFO/SendeventProcess-1] process exiting with exitcode 1
LOADER: Back to parent (RC: 1)
LOADER: Doing cleanup
LOADER: Freeing archive status for c:\Users\bjones\AppData\Local\Temp\pytest-of-bjones\pytest-8\test_multiprocess_onefile_0\dist\pyi_multiprocess.exe
```

Note that I pressed ctrl-break, then also killed one of the `pyi_multiprocess` processes to get the full result above.

The second process (onefile) seems to do two of everything...???

**Comment by bjones1** [comment]
@codewarrior0, do you have any guesses on this one? I'm clueless...
