### ISSUE TITLE
"RuntimeError: context has already been set" when creating a bundle with sklearn and multiprocessing

### ISSUE THREAD

**Issue by jfmorazzani** [pyinstaller/pyinstaller#2118]
I wrote a program that should use the multiprocessing feature with sklearn but it does not work once bundled with pyinstaller. The program works fine when executed unbundled.
Environment:
- Windows 10 64bits 
- Python 3.5.2
- pyinstaller v3.2 - Also tried with the latest build (26/07/2016) through: pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
- scikit-learn 0.17.1

code:

```
import multiprocessing
import time
import sklearn

def func (param1, param2):
    print ("hello " + str (param1))
    time.sleep (param2)
    print ("Hello again " + str (param1))
    return "test "  + str (param1)

def main ():
    lParams = [("test1", 3),
               ("test2", 2),
               ("test3", 1)]
    args = []
    for param1, param2 in lParams:
        tup = (param1, param2)
        args.append (tup)   
    with multiprocessing.Pool (multiprocessing.cpu_count ()) as p:
        results = [p.apply_async (func, a) for a in args]
        for r in results:
            print ("Returned " + r.get ())

if __name__ == '__main__':
    # On Windows calling this function is necessary.
    multiprocessing.freeze_support ()
    main ()
```

make:
`pyinstaller -n Test.exe Test.py`

Error:

```
Traceback (most recent call last):
  File "Core\Test.py", line 26, in <module>
  File "multiprocessing\context.py", line 148, in freeze_support
Traceback (most recent call last):
  File "Core\Test.py", line 26, in <module>
  File "multiprocessing\spawn.py", line 74, in freeze_support
  File "multiprocessing\context.py", line 148, in freeze_support
  File "multiprocessing\spawn.py", line 106, in spawn_main
Traceback (most recent call last):
  File "Core\Test.py", line 26, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 74, in freeze_support
  File "multiprocessing\context.py", line 148, in freeze_support
  File "multiprocessing\spawn.py", line 221, in prepare
Traceback (most recent call last):
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 106, in spawn_main
  File "multiprocessing\spawn.py", line 74, in freeze_support
  File "multiprocessing\context.py", line 231, in set_start_method
  File "Core\Test.py", line 26, in <module>
  File "Core\Test.py", line 26, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 106, in spawn_main
Traceback (most recent call last):
RuntimeError: context has already been set
...
```

Note that I have to interrupt the execution using "CTRL+C" otherwise it keeps going into an infinite loop.

I tried to add quite a few hidden-import for sklearn like: 
`--hidden-import=sklearn.neighbors.typedefs --hidden-import=sklearn`

But it did not help.
Note that I only import sklearn in this example as it is sufficient to make it "crash". But my coding do use sklearn.

FYI, the output when executed without pyinstaller, or when I remove the "import sklearn" line:

```
C:\Core>python Test.py
hello test1
hello test2
hello test3
Hello again test3
Hello again test2
Hello again test1
Returned test test1
Returned test test2
Returned test test3
```

**Comment by mkassner** [comment]
I m quite sure this is relevant:
http://scikit-learn.org/stable/faq.html#why-do-i-sometime-get-a-crash-freeze-with-n-jobs-1-under-osx-or-linux

if you move `import sklearn` into main you be able to work around the problem.
