### ISSUE TITLE
"Failed to execute script pyi_rth_pkgres" -- External dependency issue?

### ISSUE THREAD

**Issue by nchammas** [pyinstaller/pyinstaller#2123]
My Travis CI builds which test my PyInstaller packaging have recently started failing with the following:

```
Failed to execute script pyi_rth_pkgres
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/pkg_resources/__init__.py", line 2958, in <module>
  File "site-packages/pkg_resources/__init__.py", line 2944, in _call_aside
  File "site-packages/pkg_resources/__init__.py", line 2986, in _initialize_master_working_set
UnboundLocalError: local variable 'dist' referenced before assignment
```

You can see the full build log [here](https://travis-ci.org/nchammas/flintrock/jobs/148724723#L756-L768).

The same code built fine a few weeks ago. I'm guessing one of PyInstaller's external dependencies recently changed and broke this. Is that plausible?

I don't see this issue when I run the same test locally. It seems to be something related to the environment on Travis CI, but I'm not sure how to continue debugging this. Forcing the test to run on Python 3.5.2 (as opposed to 3.5.0) didn't resolve the issue. I'm running PyInstaller 3.2.

Any pointers on where to look?

**Comment by stephenrauch** [comment]
This is the same thing that was seen on windows in https://github.com/pyinstaller/pyinstaller/issues/2120#issuecomment-236072760.  I could not duplicate that one, so I would agree that it seems likely to be environment related.

**Comment by htgoebel** [comment]
This is a bug in pkg_resources: Within a private function/method there a local variable is used before assignment. Please ty updating setuptools (which pkg_resources belongs to) and in cse report the but at setuptools.

**Comment by nchammas** [comment]
Ah OK, thanks for the pointer. I will experiment with different versions of `setuptools` and report back on which ones fix the issue for others who may run into this.

**Comment by nchammas** [comment]
Hmm, now my Travis builds are working again, even before I tried playing with the version of `setuptools`. I'm not sure why.

Anyway!  `¯\_(ツ)_/¯`
