### ISSUE TITLE
"Unicode-objects must be encoded before hashing" prevents bundling matplotlib

### ISSUE THREAD

**Issue by allthedata** [pyinstaller/pyinstaller#2124]
I'm running Python 3.5 on Windows, on the latest develop branch of pyinstaller. When bundling the simplest test program using matplotlib, I got the following error:
```python
Traceback (most recent call last):
  File "C:\Users\al\Anaconda3\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.3.dev0+501ad40', 'console_scripts', 'pyinstaller')()
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\building\api.py", line 642, in __init__
    self.__postinit__()
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\building\api.py", line 674, in assemble
    dist_nm=inm)
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\building\utils.py", line 189, in checkCache
    digest = cacheDigest(fnm, redirects)
  File "C:\Users\al\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+501ad40-py3.5.egg\PyInstaller\building\utils.py", line 336, in cacheDigest
    hasher.update(str(redirects))
TypeError: Unicode-objects must be encoded before hashing
```
This looks like a simple fix, I just changed one line in PyInstaller/building/utils.py in the cacheDigest function:
`hasher.update(str(redirects))`
to
`hasher.update(str(redirects).encode())`
and it works fine now.

**Comment by htgoebel** [comment]
Thanks for this bug-report.

**Comment by codewarrior0** [comment]
Whoops. Turns out I only tested this with Python 2.7. With 3.5, `hashlib` refuses to hash Unicode-objects because the internal byte-representation varies from platform to platform (and can even be changed with build flags when building CPython) - so it requires you to encode it as bytes with a given encoding to ensure consistent hashing.
