### ISSUE TITLE
ImportError: No module named Tkinter

### ISSUE THREAD

**Issue by Spiruel** [pyinstaller/pyinstaller#2127]
When attempting to create an .exe using `pyinstaller get_profile.py` using latest install of pyinstaller on pip.
Stacktrace:

`Traceback (most recent call last):
  File "get_profile.py", line 4, in <module>
    from utils.results import WorkspaceManager
  File "c:\anaconda2\lib\site-packages\PyInstaller-3.2-py2.7.egg\PyInstaller\loa
der\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "utils\results.py", line 10, in <module>
    import tkinter as tk
  File "c:\anaconda2\lib\site-packages\PyInstaller-3.2-py2.7.egg\PyInstaller\loa
der\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "tkinter\__init__.py", line 5, in <module>
ImportError: No module named Tkinter
Failed to execute script get_profile`

Running Python 2.7.11 :: Anaconda 4.1.0 (64-bit)

**Comment by UgoT** [comment]
Here is the answer:
  https://github.com/pyinstaller/pyinstaller/issues/2139

**Comment by Legorooj** [comment]
Closing due to inactivity
