### ISSUE TITLE
No module named struct error when trying to run executable

### ISSUE THREAD

**Issue by ubehera** [pyinstaller/pyinstaller#2131]
[root@myrig CommandManager]# ./dist/SSHConn/SSHConn
mod is NULL - structTraceback (most recent call last):
  File "/opt/python/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: /home/ubehera/CommandManager/dist/SSHConn/_struct.so: undefined symbol: PyUnicodeUCS2_AsEncodedString
mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "/tmp/pip-build-xDjNbD/pyinstaller/PyInstaller/loader/pyimod02_archive.py", line 28, in <module>
ImportError: No module named struct
mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "/tmp/pip-build-xDjNbD/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 24, in <module>
ImportError: No module named pyimod02_archive
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 15, in <module>
    import pyimod03_importers
ImportError: No module named pyimod03_importers
Failed to execute script pyiboot01_bootstrap

**Comment by ubehera** [comment]
PyInstaller needs python to be compiled with `--enable-shared and LDFLAGS=-Wl,-rpath=<path to python lib>`.

In my case:

`./configure --enable-shared --prefix=/opt/python LDFLAGS=-Wl,-rpath=/opt/python/lib`

Additional reference: https://bugs.python.org/issue27685
