### ISSUE TITLE
PyInstaller generated .exe file on windows not reading arguments, with threading.

### ISSUE THREAD

**Issue by ubehera** [pyinstaller/pyinstaller#2136]
Running the py file:

```
C:\Users\ubehera\PycharmProjects\CommandManager>python SSHConn.py --ipfile text.txt
Connected to 10.235.140.208
Connected to 10.235.140.212
Connected to 10.235.140.214
Unexpected error at IP 10.235.140.110. See output file for more details.
Disconnecting from 10.235.140.208
Disconnecting from 10.235.140.214
Disconnecting from 10.235.140.212
Program execution completed.
```

Building with PyInstaller:

```
C:\Users\ubehera\PycharmProjects\CommandManager>C:\Python35\Scripts\pyinstaller.exe --onefile SSHConn.py
134 INFO: PyInstaller: 3.2
134 INFO: Python: 3.5.2
135 INFO: Platform: Windows-7-6.1.7601-SP1
136 INFO: wrote C:\Users\ubehera\PycharmProjects\CommandManager\SSHConn.spec
139 INFO: UPX is not available.
147 INFO: Extending PYTHONPATH with paths
['C:\\Users\\ubehera\\PycharmProjects\\CommandManager',
 'C:\\Users\\ubehera\\PycharmProjects\\CommandManager']
147 INFO: checking Analysis
147 INFO: Building Analysis because out00-Analysis.toc is non existent
147 INFO: Initializing module dependency graph...
150 INFO: Initializing module graph hooks...
153 INFO: Analyzing base_library.zip ...
2370 INFO: running Analysis out00-Analysis.toc
2429 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-runtime-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
2458 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-stdio-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
2504 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-locale-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
2535 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-math-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
2909 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-heap-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
2928 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-convert-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
2965 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-string-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
2975 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-conio-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
3006 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-time-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
3018 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
3028 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-environment-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
3041 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-process-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
3047 INFO: Caching module hooks...
3071 INFO: Analyzing C:\Users\ubehera\PycharmProjects\CommandManager\SSHConn.py
3588 INFO: Processing pre-find module path hook   distutils
3761 INFO: Processing pre-find module path hook   site
3763 INFO: site: retargeting to fake-dir 'c:\\python35\\lib\\site-packages\\PyInstaller\\fake-modules'
6322 INFO: Processing pre-safe import module hook   six.moves
6475 INFO: Loading module hooks...
6476 INFO: Loading module hook "hook-xml.dom.domreg.py"...
6477 INFO: Loading module hook "hook-pkg_resources.py"...
6628 INFO: Loading module hook "hook-cryptography.py"...
6635 INFO: Loading module hook "hook-pywintypes.py"...
6839 INFO: Loading module hook "hook-sysconfig.py"...
6841 INFO: Loading module hook "hook-pydoc.py"...
6843 INFO: Loading module hook "hook-encodings.py"...
6854 INFO: Loading module hook "hook-_tkinter.py"...
7082 INFO: checking Tree
7082 INFO: Building Tree because out00-Tree.toc is non existent
7083 INFO: Building Tree out00-Tree.toc
7137 INFO: checking Tree
7138 INFO: Building Tree because out01-Tree.toc is non existent
7138 INFO: Building Tree out01-Tree.toc
7153 INFO: Loading module hook "hook-distutils.py"...
7155 INFO: Loading module hook "hook-xml.py"...
7157 INFO: Loading module hook "hook-lib2to3.py"...
7201 INFO: Looking for ctypes DLLs
7224 INFO: Analyzing run-time hooks ...
7232 INFO: Including run-time hook 'pyi_rth_pkgres.py'
7235 INFO: Including run-time hook 'pyi_rth__tkinter.py'
7252 INFO: Looking for dynamic libraries
9350 WARNING: Can not get binary dependencies for file: C:\Windows\system32\api-ms-win-crt-utility-l1-1-0.dll
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
9350 INFO: Looking for eggs
9351 INFO: Using Python library c:\python35\python35.dll
9356 INFO: Found binding redirects:
[]
9375 INFO: Warnings written to C:\Users\ubehera\PycharmProjects\CommandManager\build\SSHConn\warnSSHConn.txt
9412 INFO: checking PYZ
9413 INFO: Building PYZ because out00-PYZ.toc is non existent
9413 INFO: Building PYZ (ZlibArchive) C:\Users\ubehera\PycharmProjects\CommandManager\build\SSHConn\out00-PYZ.pyz
10448 INFO: checking PKG
10448 INFO: Building PKG because out00-PKG.toc is non existent
10449 INFO: Building PKG (CArchive) out00-PKG.pkg
13847 INFO: Bootloader c:\python35\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
13848 INFO: checking EXE
13849 INFO: Building EXE because out00-EXE.toc is non existent
13852 INFO: Building EXE from out00-EXE.toc
13854 INFO: Appending archive to EXE C:\Users\ubehera\PycharmProjects\CommandManager\dist\SSHConn.exe

C:\Users\ubehera\PycharmProjects\CommandManager>

```

Executing with --help:

```
C:\Users\ubehera\PycharmProjects\CommandManager>dist\SSHConn.exe --help
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]

Controller Telnet Command Automation

optional arguments:
  -h, --help         show this help message and exit
  --ipfile IPFILE
  --cmd CMD
  --threads THREADS

C:\Users\ubehera\PycharmProjects\CommandManager>
```

Executing with argument:

```
C:\Users\ubehera\PycharmProjects\CommandManager>dist\SSHConn.exe --ipfile text.txt
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile
usage: SSHConn.exe [-h] --ipfile IPFILE [--cmd CMD] [--threads THREADS]
SSHConn.exe: error: the following arguments are required: --ipfile

```

Goes into loop until I kill the command window.

Same script compiles and runs fine on Linux.
Am I doing something wrong on windows?

**Comment by cherryleafroad** [comment]
I'm having the same issue, Commands are not being passed in the generated exe, but the script works fine. I'll update with any new info I find out..

**Comment by Legorooj** [comment]
You've proved in your comment that it's reading the `--help` option properly, therefore you might have an error in your script.
