### ISSUE TITLE
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

### ISSUE THREAD

**Issue by JPFrancoia** [pyinstaller/pyinstaller#2161]
Hi,

I'm trying to package a (complex) GUI software.

Among the dependencies, I have PyQt4, numpy and sklearn. No matplotlib, or at least I don't import it explicitly.

When I run ```pyinstaller gui.py```, the command runs fine. However when I try to execute the bundled program, I get the following error:

```
╭─djipey-laptop ~/informatique/python/ChemBrows/dist/gui ‹update*› ‹cb› 11:24:11
╰─$ ./gui 
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt4plugins.py", line 41, in <module>
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt4plugins.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
Failed to execute script pyi_rth_qt4plugins
```

I am on Manjaro Linux, and I packaged the program from a virtualenv. Here is my requirements.txt (obtained directly from ```pip freeze```):

```
appdirs==1.4.0
arrow==0.8.0
beautifulsoup4==4.5.1
decorator==4.0.10
esky==0.9.9
feedparser==5.2.1
numpy==1.11.1
Pillow==3.3.1
python-dateutil==2.5.3
requests==2.11.1
requests-futures==0.9.7
scikit-learn==0.17.1
scipy==0.18.0
setuptools==19.2
six==1.10.0
sklearn==0.0
twitter==1.17.1
validators==0.10.3
```

Could you help me to solve this problem please ?

**Comment by JPFrancoia** [comment]
Sorry, I had installed pyinstaller globally, not in my virtualenv. Uninstalling it globally and installing it solely in the virtualenv solved the issue (only PyQt4 is in the virtualenv).

Damn, I love virtualenv !
