### ISSUE TITLE
Bootload fails to compile when there are white spaces in the path

### ISSUE THREAD

**Issue by gjvnq** [pyinstaller/pyinstaller#2169]
I have just spent a considerable amout of time trying to get a specific version of PyInstall to work. In the end, the solution was rather trivial: move the folder to another place.

What I would like to ask is not to spend time trying to actually solve the bug, but rather to include a litte remainder on the README.md file and on the script. Some thing like a little print() in case things go wrong.

**Comment by gjvnq** [comment]
I know realized I misspelt the title. It shou be bootloader, not bootload.

**Comment by ryukinix** [comment]
I have the same problem here: here a example: 

```
41 INFO: PyInstaller: 3.2.1
41 INFO: Python: 3.6.3
43 INFO: Platform: Linux-4.9.65-1-lts-x86_64-with-glibc2.3.4
43 INFO: wrote /home/lerax/Desktop/I'm Cancer/TR3/rentalcar/rentalcar.spec
45 INFO: UPX is not available.
46 INFO: Extending PYTHONPATH with paths
["/home/lerax/Desktop/I'm Cancer/TR3/rentalcar",
 "/home/lerax/Desktop/I'm Cancer/TR3/rentalcar"]
47 INFO: checking Analysis
49 INFO: Building because inputs changed
49 INFO: Initializing module dependency graph...
56 INFO: Initializing module graph hooks...
57 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3.6/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/usr/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/usr/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "/usr/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/usr/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "/usr/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "/usr/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

**Comment by htgoebel** [comment]
@gjvnq Is this the error you have experienced, or is this a different one?

@ryukinix This error looks to be unrelated to white-spaces in path. It lloks more like corrupted byte-code or something else weird. Have you verified, this error does *not* occur if there is no white-space in the path? Also please run pyinstaller with `--log-level=DEBUG` to find out which module causes the crash. please only post the relevant last part of the log – the whole log is huge.

**Comment by ryukinix** [comment]
Yes, I verified. Doesn't occurs If I move the same project to a path without whitespaces.

**Comment by htgoebel** [comment]
@ryukinix And the answers to the remaining questions?

**Comment by ryukinix** [comment]
Sorry, you are right, because I move that path and update the  pyinstaller on the same test because I just was trying to fix that as soon as possible.

I misunderstood one thing: this happened with PyInstaller 3.2. I installed 3.3 and this is fixed, whatever the path has whitespaces or not. Just for information: I'm using Python3.6.1. The things are running smootlhy now. I think [none log](http://sprunge.us/CVYi
) from me can help you.

Probably the main issue of the OP is another thing, sorry again for creating confusion here.

**Comment by htgoebel** [comment]
@gjvnq I'm closing this ticket now. If it still is a problem with the current version (3.3 resp. 3.3.1), please pen a new ticket an provide more information.
