### ISSUE TITLE
Failed to run application due to "The specified module could not be found" error

### ISSUE THREAD

**Issue by WKrauze** [pyinstaller/pyinstaller#2180]
Python 3.5
Win10
PyInstaller ver. 3.2
I try to create a GUI app using the onedir option. The application builds correctly, but when I try to run the exe file I get the following error:

```
(C:\Users\Wojtek\Anaconda3) C:\Users\Wojtek\SkyDrive\Repos\RealTimePhasePy\src\dist\GUI-grid>cmd /k GUI-grid.exe
Traceback (most recent call last):
  File "site-packages\llvmlite\binding\ffi.py", line 40, in <module>
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 131, in __init__
  File "ctypes\__init__.py", line 347, in __init__
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GUI-grid.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\wojtek\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\accelerate\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\wojtek\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\numba\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\wojtek\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\numba\config.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\wojtek\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\llvmlite\binding\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\wojtek\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\llvmlite\binding\dylib.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\wojtek\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\llvmlite\binding\ffi.py", line 45, in <module>
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 131, in __init__
  File "ctypes\__init__.py", line 347, in __init__
OSError: [WinError 126] The specified module could not be found
Failed to execute script GUI-grid
```

In GUI-grid.py in line 4 I have: 
`from accelerate import cuda as a_cuda`
and I believe that this package is causing problems - specifically the llvmlite package.
To fix this problem I already tried:
- this [solution](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Win-Load-External-DLL), by adding the code snippet to my GUI-grid.py, and giving the path to llvmlite.dll file,
- to run PyInstaller with the --hidden-import=accelerate.cuda option,
- to edit the `.spec` file, by changing the fragment:
  `binaries=None`
  to
  `binaries=['llvmlite.dll']`

but nothing helped. Still, when I run the application I get the same errors as above.
Also, earlier I had different errors, but got rid of them by downgrading setuptools to ver. 19.2 (as was suggested), so now I have setuptools 19.2.
Could you please suggest what else could I change?

**Comment by davidh-ssec** [comment]
I had this same problem or at least similar when I was using numba which requires llvmlite. It looks like the proper llvmlite hook was added and is tagged in version 3.2.1 of PyInstaller. Make sure you have the newest version. The commit that added it is here: https://github.com/pyinstaller/pyinstaller/commit/f386ec72e72245d93aa86c65b2f67744f76e7adf

Before I found that the new version should work I added the following to my spec file when run under Windows and it seemed to fix it although the builtin hook in 3.2.1 should be used instead:

    lib_dir = sys.executable.replace("python.exe", os.path.join("Lib", "site-packages"))
    binaries += [(os.path.join(lib_dir, 'llvmlite', 'binding', 'llvmlite.dll'), '')]
