### ISSUE TITLE
SyntaxError: unexpected EOF while parsing: empty index.dat

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#2193]
Any suggestions how to debug this? I'm using the latest dev version from git. thanks

$ pyinstaller main.py -F
124 INFO: PyInstaller: 3.3.dev0+gb78bfe5
124 INFO: Python: 3.5.2
124 INFO: Platform: Windows-10-10.0.10586-SP0
125 INFO: wrote C:\Users\Nicolas\dropbox\pythonprojects\poker\main.spec
126 INFO: UPX is not available.
128 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Nicolas\\dropbox\\pythonprojects\\poker',
 'C:\\Users\\Nicolas\\dropbox\\pythonprojects\\poker']
128 INFO: checking Analysis
811 INFO: checking PYZ
1011 INFO: checking PKG
1013 INFO: Building because toc changed
1013 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "C:\Users\Nicolas\Anaconda35-64\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.3.dev0+gb78bfe5', 'console_scripts', 'pyinstaller')()
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\building\api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\building\api.py", line 189, in __init__
    self.__postinit__()
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\building\api.py", line 252, in assemble
    dist_nm=inm)
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\building\utils.py", line 173, in checkCache
    cache_index = load_py_data_struct(cacheindexfn)
  File "C:\Users\Nicolas\Anaconda35-64\lib\site-packages\pyinstaller-3.3.dev0+gb78bfe5-py3.5.egg\PyInstaller\utils\misc.py", line 230, in load_py_data_struct
    return eval(f.read())
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

when checking what f.read is, it seems to refer to a file called index.dat:
<_io.TextIOWrapper name='C:\\Users\\Nicolas\\AppData\\Roaming\\pyinstaller\\bincache00_py35_64bit\\index.dat' mode='rU' encoding='utf-8'>

and I can confirm that this file is empty.

**Comment by htgoebel** [comment]
Try running PyInstaller with `--clean`.

**Comment by dickreuter** [comment]
the --clean helped, but only after I deactivated kaspersky internet security. Looks like they decided to block pyinstaller in some cases.
