### ISSUE TITLE
Class RunStopper is implemented

### ISSUE THREAD

**Issue by insomnia9527** [pyinstaller/pyinstaller#2197]
Hi,

  1) First pyinstaller was installed successfully and I can use it for simple case.

  2) The problem is that when I want to include one module in my script, there is a error when run the unix executable result :

*_lis-MacBook-Pro:pyinstaller li$ pyinstaller --onedir hello.py 
19 INFO: PyInstaller: 3.2
19 INFO: Python: 2.7.11
24 INFO: Platform: Darwin-15.4.0-x86_64-i386-64bit
25 INFO: wrote /Users/li/work/test_folder/pyinstaller/hello.spec
29 INFO: UPX is available.
30 INFO: Extending PYTHONPATH with paths
['/Users/li/work/test_folder/pyinstaller',
 '/Users/li/work/test_folder/pyinstaller']
30 INFO: checking Analysis
31 INFO: Building Analysis because out00-Analysis.toc is non existent
31 INFO: Initializing module dependency graph...
32 INFO: Initializing module graph hooks...
65 INFO: running Analysis out00-Analysis.toc
70 INFO: Caching module hooks...
72 INFO: Analyzing /Users/li/work/test_folder/pyinstaller/hello.py
1996 INFO: Processing pre-find module path hook   distutils
2507 INFO: Processing pre-safe import module hook   _xmlplus
4680 INFO: Processing pre-find module path hook   site
4680 INFO: site: retargeting to fake-dir '/usr/local/lib/python2.7/site-packages/PyInstaller/fake-modules'
4702 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named win32com
4727 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named win32com
6849 INFO: Processing pre-safe import module hook   six.moves
10462 INFO: Loading module hooks...
10462 INFO: Loading module hook "hook-distutils.py"...
10463 INFO: Loading module hook "hook-sysconfig.py"...
10464 INFO: Loading module hook "hook-xml.py"...
10465 INFO: Loading module hook "hook-httplib.py"...
10465 INFO: Loading module hook "hook-pydoc.py"...
10468 INFO: Excluding import 'Tkinter'
10470 WARNING:   Removing import pydoc from module Tkinter
10470 INFO: Loading module hook "hook-encodings.py"...
10756 INFO: Loading module hook "hook-_tkinter.py"...
10759 INFO: checking Tree
10759 INFO: Building Tree because out00-Tree.toc is non existent
10759 INFO: Building Tree out00-Tree.toc
10817 INFO: checking Tree
10818 INFO: Building Tree because out01-Tree.toc is non existent
10818 INFO: Building Tree out01-Tree.toc
10838 INFO: Loading module hook "hook-matplotlib.backends.py"...
11141 INFO:   Matplotlib backend "GTK": ignored
    Gtk_ backend requires pygtk to be installed.
11394 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk\* backend requires pygtk to be installed.
11555 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named gtk
11840 INFO:   Matplotlib backend "MacOSX": added
12092 INFO:   Matplotlib backend "Qt4Agg": ignored
    Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.
12337 INFO:   Matplotlib backend "Qt5Agg": ignored
    Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.
12597 INFO:   Matplotlib backend "TkAgg": added
12922 INFO:   Matplotlib backend "WX": added
13251 INFO:   Matplotlib backend "WXAgg": added
13407 INFO:   Matplotlib backend "CocoaAgg": ignored
    The CococaAgg backend required PyObjC to be installed!
13563 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
13796 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
13948 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_webagg.py", line 30, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
14106 INFO:   Matplotlib backend "nbAgg": ignored
    No module named tornado.ioloop
14362 INFO:   Matplotlib backend "agg": added
14522 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
14684 INFO:   Matplotlib backend "emf": ignored
    No module named backend_emf
14835 INFO:   Matplotlib backend "gdk": ignored
    No module named gobject
15088 INFO:   Matplotlib backend "pdf": added
15359 INFO:   Matplotlib backend "pgf": added
15605 INFO:   Matplotlib backend "ps": added
15865 INFO:   Matplotlib backend "svg": added
16108 INFO:   Matplotlib backend "template": added
16350 INFO: Loading module hook "hook-matplotlib.py"...
16508 INFO: Loading module hook "hook-xml.dom.domreg.py"...
16509 INFO: Loading module hook "hook-pkg_resources.py"...
16568 INFO: Loading module hook "hook-IPython.py"...
16578 INFO: Excluding import 'Tkinter'
16582 WARNING:   Removing import IPython.lib.clipboard from module Tkinter
16583 WARNING:   Removing import IPython.lib.inputhook from module Tkinter
16586 INFO: Excluding import 'PySide'
16590 WARNING:   Removing import IPython.external.qt_loaders from module PySide.QtCore
16591 WARNING:   Removing import IPython.external.qt_loaders from module PySide.QtGui
16591 WARNING:   Removing import IPython.external.qt_loaders from module PySide.QtSvg
16591 WARNING:   Removing import IPython.external.qt_loaders from module PySide
16595 INFO: Excluding import 'gtk'
16599 WARNING:   Removing import IPython.lib.inputhook from module gtk
16599 WARNING:   Removing import IPython.lib.inputhookgtk from module gtk
16604 INFO: Excluding import 'PyQt5'
16609 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5.QtWidgets
16609 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5.QtCore
16609 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5.QtGui
16609 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5
16609 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5.QtSvg
16613 INFO: Excluding import 'PyQt4'
16617 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtSvg
16617 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtGui
16617 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtCore
16617 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4
16620 INFO: Excluding import 'matplotlib'
16628 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.pyplot
16628 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.figure.Figure
16628 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.figure
16628 WARNING:   Removing import IPython.core.pylabtools from module matplotlib._pylab_helpers
16628 WARNING:   Removing import IPython.core.pylabtools from module matplotlib
16628 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.pylab
16628 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.rcParams
16628 INFO: Loading module hook "hook-pytz.py"...
16652 INFO: Loading module hook "hook-setuptools.py"...
16654 INFO: Loading module hook "hook-sqlite3.py"...
16689 INFO: Looking for ctypes DLLs
16705 WARNING: library user32 required via ctypes not found
16720 INFO: Analyzing run-time hooks ...
16730 INFO: Including run-time hook 'pyi_rth_traitlets.py'
16730 INFO: Including run-time hook 'pyi_rth_pkgres.py'
16751 INFO: Looking for dynamic libraries
16922 INFO: Looking for eggs
16922 INFO: Using Python library /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Python
16944 INFO: Warnings written to /Users/li/work/test_folder/pyinstaller/build/hello/warnhello.txt
17162 INFO: checking PYZ
17162 INFO: Building PYZ because out00-PYZ.toc is non existent
17162 INFO: Building PYZ (ZlibArchive) /Users/li/work/test_folder/pyinstaller/build/hello/out00-PYZ.pyz
18249 INFO: checking PKG
18249 INFO: Building PKG because out00-PKG.toc is non existent
18249 INFO: Building PKG (CArchive) out00-PKG.pkg
18266 INFO: Bootloader /usr/local/lib/python2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
18266 INFO: checking EXE
18266 INFO: Building EXE because out00-EXE.toc is non existent
18267 INFO: Building EXE from out00-EXE.toc
18267 INFO: Appending archive to EXE /Users/li/work/test_folder/pyinstaller/build/hello/hello
18272 INFO: Fixing EXE for code signing /Users/li/work/test_folder/pyinstaller/build/hello/hello
18280 INFO: checking COLLECT
18280 INFO: Building COLLECT because out00-COLLECT.toc is non existent
18280 INFO: Building COLLECT out00-COLLECT.toc
lis-MacBook-Pro:pyinstaller li$ cd dist/hello/
lis-MacBook-Pro:hello li$ ./hello 
objc[61093]: Class RunStopper is implemented in both /Users/li/work/test_folder/pyinstaller/dist/hello/libCore.so and /Users/li/tools/root/lib/libCore.so. One of the two will be used. Which one is undefined.

 **\* Break **\* segmentation violation
 Generating stack trace...
An admin user name and password is required to enter Developer Mode.
Admin user name (li): ^Z
[3]+  Stopped                 ./hello
lis-MacBook-Pro:hello li$ 
**

  And the script is very simple:
**
import ROOT
print 'hello'
**

  And my information is that: Python 2.7.11, pyinstaller 3.2 and mac 10.11.4.
  For the module ROOT, the homepage is: https://root.cern.ch/  which is written by C++ but can be loaded in python.

  My confusion just like the error report said, there are two libs, what can I do to fix it?

**Comment by dhyams** [comment]
It looks like you might have /Users/li/tools/root/lib in your DYLD_LIBRARY_PATH when you run ./hello.  Otherwise I don't see how it would know to look there for your libCore.so shared lib.  Try unsetting this environment variable  before running, just as a test.

Later versions of macOS (El Capitan and Sierra) probably ignore this variable anyway, though...I know that I have not been able to set it (it's a security hole technically) on my El Capitan machine.

**Comment by Legorooj** [comment]
Closing due to inactivity
