### ISSUE TITLE
Attempted ascii decode of md5 digest fails

### ISSUE THREAD

**Issue by stephenrauch** [pyinstaller/pyinstaller#2229]
Was not able to pair this down to a reasonable test case, but here is the stack trace:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2.3\helpers\pydev\pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2.3\helpers\pydev\pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/stephen/Documents/src/test_scripts/hash_bytes-test.py", line 272, in <module>
    m.make_exe()
  File "C:/Users/stephen/Documents/src/test_scripts/hash_bytes-test.py", line 252, in make_exe
    self._call_pyinstaller()
  File "C:/Users/stephen/Documents/src/test_scripts/hash_bytes-test.py", line 227, in _call_pyinstaller
    clean_build=True,
  File "C:\Users\stephen\Documents\github\pyinstaller\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\stephen\Documents\github\pyinstaller\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\stephen\Documents\github\pyinstaller\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 31, in <module>
  File "C:\Users\stephen\Documents\github\pyinstaller\PyInstaller\building\api.py", line 642, in __init__
    self.__postinit__()
  File "C:\Users\stephen\Documents\github\pyinstaller\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "C:\Users\stephen\Documents\github\pyinstaller\PyInstaller\building\api.py", line 674, in assemble
    dist_nm=inm)
  File "C:\Users\stephen\Documents\github\pyinstaller\PyInstaller\building\utils.py", line 323, in checkCache
    save_py_data_struct(cacheindexfn, cache_index)
  File "C:\Users\stephen\Documents\github\pyinstaller\PyInstaller\utils\misc.py", line 211, in save_py_data_struct
    pprint.pprint(data, f)
  File "C:\Python27\lib\pprint.py", line 59, in pprint
    printer.pprint(object)
  File "C:\Python27\lib\pprint.py", line 117, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "C:\Python27\lib\pprint.py", line 164, in _format
    allowance + 1, context, level)
  File "C:\Python27\lib\pprint.py", line 222, in _format
    write(rep)
  File "C:\Python27\lib\codecs.py", line 706, in write
    return self.writer.write(data)
  File "C:\Python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 15: ordinal not in range(128)
```

The failing data is:

type str = `"\\xb2E0\\x19\\x98�Wo-�\\'~S��l"`

The data comes from a call to: `utils.cacheDigest`

**Comment by htgoebel** [comment]
Fixed by #2230
