### ISSUE TITLE
Running pyinstaller against a nonexistent script leads to a stack trace, not an error message.

### ISSUE THREAD

**Issue by dhyams** [pyinstaller/pyinstaller#2234]
If one runs pyinstaller on a script that doesn't exist (let's say I misspelled the script's name), pyinstaller terminates with a stack trace.   It would be much better if pyinstaller just said "xxx: file not found" instead.

**Comment by Legorooj** [comment]
@bwoodsend can you check if this has been done already, and if not, submit a PR? This should be an easy change.

@dhyams apologies this issue never got dealt with.

**Comment by bwoodsend** [comment]
There's a check for this which first appeared in 2015 which is odd considering this was raised in 2016.

```python
           if not os.path.exists(script):
               raise ValueError("script '%s' not found" % script)
```
It's moved around a bit since then but it certainly works currently.
```shell
λ PyInstaller i_dont_exist.py
133 INFO: PyInstaller: 3.6
134 INFO: Python: 3.7.8
135 INFO: Platform: Windows-8-6.2.9200-SP0
139 INFO: wrote E:\notebooks\pyi-issues\4908\i_dont_exist.spec
169 INFO: UPX is not available.
Traceback (most recent call last):
  File "e:\install\.pyenv\pyenv-win\versions\3.7.8-amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\install\.pyenv\pyenv-win\versions\3.7.8-amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\install\.pyenv\pyenv-win\versions\3.7.8-amd64\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "e:\install\.pyenv\pyenv-win\versions\3.7.8-amd64\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "e:\install\.pyenv\pyenv-win\versions\3.7.8-amd64\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "e:\install\.pyenv\pyenv-win\versions\3.7.8-amd64\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "e:\install\.pyenv\pyenv-win\versions\3.7.8-amd64\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "E:\notebooks\pyi-issues\4908\i_dont_exist.spec", line 17, in <module>
    noarchive=False)
  File "e:\install\.pyenv\pyenv-win\versions\3.7.8-amd64\lib\site-packages\PyInstaller\building\build_main.py", line 191, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'E:\notebooks\pyi-issues\4908\i_dont_exist.py' not found
```

A non-existent spec file just raises a `FileNotFoundError: [Errno 2] No such file or directory: 'i_dont_exist_either.spec'`.

**Comment by dhyams** [comment]
I think though this is precisely the point (see your post above)...a tool should not display a stack trace in this situation (unhandled exception); it should just come back with a message that says "File not found: xxxx.py".  I wouldn't close this issue, because it still exists.

**Comment by bwoodsend** [comment]
Ahh I see what you mean. But I'd argue that `ValueError: script 'E:\notebooks\pyi-issues\4908\i_dont_exist.py' not found` is as self explanatory error message and a non-zero error code is still returned. We could catch it, reword the message, then call `sys.exit(1)` but really what does that achieve (besides heavily diluting our code-base with clutter-some error messages)? Bear in mind that there are loads of other files which PyInstaller could fail to found and numerous other ways it can screw up. We can't gift-wrap them all.

**Comment by Legorooj** [comment]
@bwoodsend I'll just replace the `ValueError`s and `FileNotFoundError`s with `SystemExit(message)`. No stack trace and it'll take 2 mins.
