### ISSUE TITLE
requests problem

### ISSUE THREAD

**Issue by evilxyz** [pyinstaller/pyinstaller#2240]
``` bash
uname -an
Linux evilxyz 4.8.2-1-ARCH #1 SMP PREEMPT Mon Oct 17 08:11:46 CEST 2016 x86_64 GNU/Linux

pyinstaller --version
3.1.1

python -V
Python 3.5.2
```

when i use this command 

``` bash
pyinstaller -F --debug -p "/usr/lib/python3.5/site-packages/pip-7.1.0-py3.5.egg:/usr/lib/python3.5/site-packages/seantis_questionnaire-2.0.1-py3.5.egg:/usr/lib/python3.5/site-packages/PyYAML-3.11-py3.5-linux-x86_64.egg:/usr/lib/python3.5/site-packages/django_compat-1.0.12-py3.5.egg:/usr/lib/python3.5/site-packages/django_transmeta-0.7.3-py3.5.egg:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-linux:/usr/lib/python3.5/lib-dynload:/usr/lib/python3.5/site-packages" awesome.py
```

``` python
LOADER: Running awesome.py
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/usr/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "payloads.py", line 11, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/requests/__init__.py", line 60, in <module>
  File "/usr/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 158, in load_module
    return self._importer.load_module(fullname, self._fullname)
  File "/usr/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/urllib3/exceptions.py", line 2, in <module>
  File "/usr/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 158, in load_module
    return self._importer.load_module(fullname, self._fullname)
  File "/usr/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/urllib3/packages/__init__.py", line 3, in <module>
ImportError: cannot import name 'ssl_match_hostname'
awesome returned -1
LOADER: OK.
```

awesome.py import

``` python
import os
import re
import sys
import time
import queue
import signal
import socket
import _thread
import payloads
```

payloads.py import

``` python
import os
import sys
import json
import time
import socket
import random
import getpass
import requests
import threading
import subprocess
import urllib.request
```

when i import requests, this happened.
I have no idea to fix it ...

**Comment by htgoebel** [comment]
Please try the curent developer version.

BTW: Your command line liks like you want to use a virtual env :-)

**Comment by evilxyz** [comment]
I try to use develop version, and 
```bash
./pyinstaller/pyinstaller.py -F --debug -p "/usr/lib/python3.5/site-packages/pip-7.1.0-py3.5.egg:/usr/lib/python3.5/site-packages/seantis_questionnaire-2.0.1-py3.5.egg:/usr/lib/python3.5/site-packages/PyYAML-3.11-py3.5-linux-x86_64.egg:/usr/lib/python3.5/site-packages/django_compat-1.0.12-py3.5.egg:/usr/lib/python3.5/site-packages/django_transmeta-0.7.3-py3.5.egg:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-linux:/usr/lib/python3.5/lib-dynload:/usr/lib/python3.5/site-packages:/home/xyz/Develop/python/botnet/irc_trojans:/usr/lib/python3.5/site-packages/requests/" awesome.py
```
```bash
./dist/awesome 
PyInstaller Bootloader 3.x
LOADER: executable is /home/xyz/Develop/python/botnet/irc_trojans/dist/awesome
LOADER: homepath is /home/xyz/Develop/python/botnet/irc_trojans/dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /home/xyz/Develop/python/botnet/irc_trojans/dist/awesome
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /tmp/_MEIpRl2x9
[1]    18821 segmentation fault (core dumped)  ./dist/awesome
```

default version is python3...

**Comment by htgoebel** [comment]
Is this still an issue? If yeas, please try the current development head, set up a virtual environment, and install the required packages in this virtual environment. Do *not* use `-p` but a fresh standard virtual environments.

**Comment by akej74** [comment]
Hi, I did a test with Python 3.5.3 and PyInstaller 3.2.1 and I can reproduce the problem (or something very similar). The problem occurs when "requests" > 2.5.1 is installed. 

**Steps to reproduce:**
1. Install "requests" 2.5.1.
2. Create simple Python script importing the "requests" module.
3. Run the script, verify it works.
4. Run pyinstaller as follows: `pyinstaller main.py` to build the stand alone application.
5. Execure "main.exe", it works without problems.
6. Install latest version of "requests" (I'm using 2.13.0).
7. Clean build and dist folders.
8. Rebuild with PyInstaller.
9. When trying to execute "main.exe", the following errors are displayed:

```
Traceback` (most recent call last):
  File "site-packages\requests\packages\__init__.py", line 27, in <module>
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 28, in <module>
  File "site-packages\requests\packages\urllib3\packages\six.py", line 92, in __get__
  File "site-packages\requests\packages\urllib3\packages\six.py", line 115, in _resolve
  File "site-packages\requests\packages\urllib3\packages\six.py", line 82, in _import_module
ImportError: No module named 'queue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\requests\__init__.py", line 63, in <module>
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\requests\utils.py", line 24, in <module>
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\requests\_internal_utils.py", line 11, in <module>
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\requests\compat.py", line 11, in <module>
  File "c:\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\requests\packages\__init__.py", line 29, in <module>
ImportError: No module named 'urllib3'
Failed to execute script main`
```

**I have the following modules installed:**
```
appdirs (1.4.0)
beautifulsoup4 (4.5.3)
constantly (15.1.0)
cx-Freeze (5.0.1)
future (0.16.0)
incremental (16.10.1)
lxml (3.7.2)
packaging (16.8)
pip (9.0.1)
PyInstaller (3.2.1)
pyparsing (2.1.10)
pypiwin32 (219)
PyQt5 (5.7.1)
pyserial (3.2.1)
requests (2.13.0)
setuptools (28.8.0)
sip (4.19)
six (1.10.0)
WMI (1.4.9)
zope.interface (4.3.3)
```

**Comment by akej74** [comment]
Update, I tried with the latest development version of PyInstaller (3.3.dev0+11f2e7b), now it works!

**Comment by hrchu** [comment]
I encounter the same problem, and the dev version works! Thanks @akej74 and  @htgoebel

**Comment by kianxineki** [comment]
nice! dev version works!
