### ISSUE TITLE
need to load 1 *.pyd dynamically, ok MacOS and Linux, error on Windows

### ISSUE THREAD

**Issue by sglebs** [pyinstaller/pyinstaller#2261]
First of all, thanks for pyinstaller!

I sucessfully packaged and ran my app under MacOS and Linux, but under WIndows it is failing to load a .pyd file. This file will be in a directory that is passed to me at runtime, via command-line. At this point I add it to the sys.path:

```
    dllDir = arguments["--undDir"]
    sys.path.insert(0,dllDir) # add the dir with the DLLs - Qt etc
    os.environ["PATH"] = dllDir + os.pathsep + os.environ["PATH"] # prepend
    sys.path.insert(0,os.path.join(dllDir,"Python")) # also needed, For interop
    sys.path.insert(0,os.path.join(dllDir,"python")) # also needed, For interop with older versions of Understand (which used lowercase)
    try:
        import understand
    except Exception as e:
        print("""\r\nCan' find the Understand native libraries at %s. Use -u to point at Understand's bin dir.\r\n
               On MacOS: Usually /Applications/scitools/bin/macos
               On Windows 64-bits: Usually C:/Program Files/SciTools/bin/pc-win64
               PATH=%s\r\n""" % (dllDir, os.environ["PATH"]))
        print(e)
        print(platform.architecture())
        sys.exit(1)
```

Anyway, this works fine at runtime under MacOS and Linux. But not under Windows:

```
[Out] Can' find the Understand native libraries at C:\Program Files\SciTools-4.0.860-64b\bin\pc-win64. Use -u to point at Understand's bin dir.
[Out] 
[Out] 
[Out]                On MacOS: Usually /Applications/scitools/bin/macos
[Out]                On Windows 64-bits: Usually C:/Program Files/SciTools/bin/pc-win64
[Out]                PATH=C:\Program Files\SciTools-4.0.860-64b\bin\pc-win64;C:\Program Files\Structure101\g\.\.;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;c:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files\Mercurial\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\VMware\CobraWinLDTP\;C:\Program Files\Structure101\g;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;c:\Program Files\TortoiseGit\bin;C:\Users\marcio\apache-maven-3.3.3\bin;C:\Program Files (x86)\AutoIt3\AutoItX;C:\Users\marcio\AppData\Local\Code\bin;C:\Program Files (x86)\GnuWin32\bin;c:\program files\structure101\g\jre\bin
[Out] 
[Out] 
[Out] DLL load failed: The specified module could not be found.
[Out] ('64bit', 'WindowsPE')
```

I run pyinstaller like this:

```
pyinstaller --exclude-module understand -F und2s101.py
```

This makes sure that it does not bundle the understand.pyd which I have on my machine, but will load the one found at runtime - this is a requirement for this app.

I was reading the manual and the section on hooks and apps changing sys.path, but since it is working fine under MacOS and Linux I figured this is not the way to go. This is the packaging running fine:

```

(env) C:\Users\marcio\git\und2s101>pyinstaller --exclude-module understand -F und2s101.py
1250 INFO: PyInstaller: 3.2
1266 INFO: Python: 3.4.4
1297 INFO: Platform: Windows-10-10.0.10586
1422 INFO: wrote C:\Users\marcio\git\und2s101\und2s101.spec
1484 INFO: UPX is not available.
1500 INFO: Extending PYTHONPATH with paths
['C:\\Users\\marcio\\git\\und2s101', 'C:\\Users\\marcio\\git\\und2s101']
1578 INFO: checking Analysis
1641 INFO: Building because excludes changed
1672 INFO: Initializing module dependency graph...
1719 INFO: Initializing module graph hooks...
1750 INFO: Analyzing base_library.zip ...
12488 INFO: Processing pre-find module path hook   distutils
12628 INFO: distutils: retargeting to non-venv dir 'c:\\python34\\Lib\\distutils'
26617 INFO: running Analysis out00-Analysis.toc
39074 INFO: Caching module hooks...
39199 INFO: Analyzing C:\Users\marcio\git\und2s101\und2s101.py
45107 INFO: Processing pre-find module path hook   site
45201 INFO: site: retargeting to fake-dir 'c:\\users\\marcio\\git\\und2s101\\env\\lib\\site-packages\\PyInstaller\\fake-modules'
56439 INFO: Loading module hooks...
56486 INFO: Loading module hook "hook-xml.dom.domreg.py"...
56533 INFO: Loading module hook "hook-pkg_resources.py"...
57080 INFO: Processing pre-safe import module hook   win32com
58158 INFO: Loading module hook "hook-pywintypes.py"...
59753 INFO: Loading module hook "hook-win32com.py"...
61925 INFO: Loading module hook "hook-sysconfig.py"...
61988 INFO: Loading module hook "hook-jinja2.py"...
62050 INFO: Loading module hook "hook-pydoc.py"...
62113 INFO: Loading module hook "hook-xml.py"...
62160 INFO: Loading module hook "hook-lib2to3.py"...
62222 INFO: Loading module hook "hook-pythoncom.py"...
63691 INFO: Loading module hook "hook-distutils.py"...
63691 INFO: Loading module hook "hook-encodings.py"...
63926 INFO: Looking for ctypes DLLs
64082 INFO: Analyzing run-time hooks ...
64192 INFO: Including run-time hook 'pyi_rth_pkgres.py'
64239 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
64364 INFO: Looking for dynamic libraries
73179 INFO: Looking for eggs
73226 INFO: Using Python library C:\WINDOWS\system32\python34.dll
73273 INFO: Found binding redirects:
[]
73445 INFO: Warnings written to C:\Users\marcio\git\und2s101\build\und2s101\warnund2s101.txt
73757 INFO: checking PYZ
73804 INFO: Building because toc changed
73851 INFO: Building PYZ (ZlibArchive) C:\Users\marcio\git\und2s101\build\und2s101\out00-PYZ.pyz
81088 INFO: checking PKG
81088 INFO: Building because toc changed
81088 INFO: Building PKG (CArchive) out00-PKG.pkg
87871 INFO: Bootloader c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
87902 INFO: checking EXE
87934 INFO: Building because manifest changed
87934 INFO: Building EXE from out00-EXE.toc
87949 INFO: Appending archive to EXE C:\Users\marcio\git\und2s101\dist\und2s101.exe

```

And this is inside the file:

```
(env) C:\Users\marcio\git\und2s101>pyi-archive_viewer dist\und2s101.exe
 pos, length, uncompressed, iscompressed, type, name
[(0, 268, 350, 1, 'm', 'struct'),
 (268, 1161, 2004, 1, 'm', 'pyimod01_os_path'),
 (1429, 4018, 8928, 1, 'm', 'pyimod02_archive'),
 (5447, 6103, 15676, 1, 'm', 'pyimod03_importers'),
 (11550, 1616, 3892, 1, 's', 'pyiboot01_bootstrap'),
 (13166, 229, 281, 1, 's', 'pyi_rth_pkgres'),
 (13395, 433, 617, 1, 's', 'pyi_rth_win32comgenpy'),
 (13828, 1756, 3771, 1, 's', 'und2s101'),
 (15584, 383567, 829264, 1, 'b', 'MSVCR100.dll'),
 (399151, 30031, 62976, 1, 'b', '_bz2.pyd'),
 (429182, 43624, 108544, 1, 'b', '_ctypes.pyd'),
 (472806, 94348, 242688, 1, 'b', '_decimal.pyd'),
 (567154, 729478, 1568256, 1, 'b', '_hashlib.pyd'),
 (1296632, 70759, 136192, 1, 'b', '_lzma.pyd'),
 (1367391, 6167, 14848, 1, 'b', '_multiprocessing.pyd'),
 (1373558, 22390, 52224, 1, 'b', '_socket.pyd'),
 (1395948, 998640, 2221568, 1, 'b', '_ssl.pyd'),
 (2394588, 2991, 7680, 1, 'b', '_win32sysloader.pyd'),
 (2397579, 4202, 9216, 1, 'b', 'markupsafe._speedups.pyd'),
 (2401781, 2593364, 5522768, 1, 'b', 'mfc100u.dll'),
 (4995145, 65572, 167936, 1, 'b', 'pyexpat.pyd'),
 (5060717, 1386617, 4063744, 1, 'b', 'python34.dll'),
 (6447334, 178294, 545280, 1, 'b', 'pythoncom34.dll'),
 (6625628, 47193, 130560, 1, 'b', 'pywintypes34.dll'),
 (6672821, 4978, 10752, 1, 'b', 'select.pyd'),
 (6677799, 380, 702, 1, 'b', 'und2s101.exe.manifest'),
 (6678179, 294471, 763392, 1, 'b', 'unicodedata.pyd'),
 (6972650, 46586, 124416, 1, 'b', 'win32api.pyd'),
 (7019236, 161291, 509952, 1, 'b', 'win32com.shell.shell.pyd'),
 (7180527, 6832, 16896, 1, 'b', 'win32trace.pyd'),
 (7187359, 303231, 1030144, 1, 'b', 'win32ui.pyd'),
 (7490590, 11779, 29696, 1, 'b', 'win32wnet.pyd'),
 (7502369,
  0,
  0,
  0,
  'o',
  'pyi-windows-manifest-filename und2s101.exe.manifest'),
 (7502369, 6562, 21821, 1, 'x', 'Include\\pyconfig.h'),
 (7508931, 194267, 737272, 1, 'x', 'base_library.zip'),
 (7703198, 2490, 6794, 1, 'x', 'lib2to3\\Grammar.txt'),
 (7705688, 9091, 21108, 1, 'x', 'lib2to3\\Grammar3.4.4.final.0.pickle'),
 (7714779, 425, 821, 1, 'x', 'lib2to3\\PatternGrammar.txt'),
 (7715204, 887, 1455, 1, 'x', 'lib2to3\\PatternGrammar3.4.4.final.0.pickle'),
 (7716091, 215, 410, 1, 'x', 'lib2to3\\tests\\data\\README.txt'),
 (7716306, 2742497, 2742497, 0, 'z', 'out00-PYZ.pyz')]
```

This is the same thing, for the MacOS version which runs just fine:

```
(env) Marcio-Marchinis-MacBook-Pro-Silver:und2s101 mqm$ pyi-archive_viewer dist/und2s101
 pos, length, uncompressed, iscompressed, type, name
[(0, 272, 355, 1, 'm', 'struct'),
 (272, 1168, 2009, 1, 'm', 'pyimod01_os_path'),
 (1440, 4023, 8933, 1, 'm', 'pyimod02_archive'),
 (5463, 6106, 15681, 1, 'm', 'pyimod03_importers'),
 (11569, 1629, 3910, 1, 's', 'pyiboot01_bootstrap'),
 (13198, 242, 299, 1, 's', 'pyi_rth_pkgres'),
 (13440, 1756, 3771, 1, 's', 'und2s101'),
 (15196, 2040957, 5784824, 1, 'b', '.Python'),
 (2056153, 4483, 27496, 1, 'b', '_bisect.cpython-34m.so'),
 (2060636, 8871, 42664, 1, 'b', '_bz2.cpython-34m.so'),
 (2069507, 197530, 278720, 1, 'b', '_codecs_cn.cpython-34m.so'),
 (2267037, 66476, 298768, 1, 'b', '_codecs_hk.cpython-34m.so'),
 (2333513, 15669, 62888, 1, 'b', '_codecs_iso2022.cpython-34m.so'),
 (2349182, 176313, 484856, 1, 'b', '_codecs_jp.cpython-34m.so'),
 (2525495, 148903, 258192, 1, 'b', '_codecs_kr.cpython-34m.so'),
 (2674398, 123210, 216104, 1, 'b', '_codecs_tw.cpython-34m.so'),
 (2797608, 96395, 284512, 1, 'b', '_ctypes.cpython-34m.so'),
 (2894003, 61011, 185592, 1, 'b', '_datetime.cpython-34m.so'),
 (2955014, 246510, 769496, 1, 'b', '_decimal.cpython-34m.so'),
 (3201524, 11164, 48952, 1, 'b', '_hashlib.cpython-34m.so'),
 (3212688, 10771, 44376, 1, 'b', '_heapq.cpython-34m.so'),
 (3223459, 31148, 91152, 1, 'b', '_json.cpython-34m.so'),
 (3254607, 148263, 410200, 1, 'b', '_lzma.cpython-34m.so'),
 (3402870, 9126, 36840, 1, 'b', '_md5.cpython-34m.so'),
 (3411996, 23774, 81832, 1, 'b', '_multibytecodec.cpython-34m.so'),
 (3435770, 9081, 42488, 1, 'b', '_multiprocessing.cpython-34m.so'),
 (3444851, 2532, 26016, 1, 'b', '_opcode.cpython-34m.so'),
 (3447383, 78644, 233208, 1, 'b', '_pickle.cpython-34m.so'),
 (3526027, 9334, 36816, 1, 'b', '_posixsubprocess.cpython-34m.so'),
 (3535361, 7130, 36248, 1, 'b', '_random.cpython-34m.so'),
 (3542491, 5044, 28264, 1, 'b', '_scproxy.cpython-34m.so'),
 (3547535, 8439, 36888, 1, 'b', '_sha1.cpython-34m.so'),
 (3555974, 10739, 49600, 1, 'b', '_sha256.cpython-34m.so'),
 (3566713, 23734, 86488, 1, 'b', '_sha512.cpython-34m.so'),
 (3590447, 60360, 176432, 1, 'b', '_socket.cpython-34m.so'),
 (3650807, 62847, 181952, 1, 'b', '_ssl.cpython-34m.so'),
 (3713654, 27531, 102328, 1, 'b', '_struct.cpython-34m.so'),
 (3741185, 38560, 116816, 1, 'b', 'array.cpython-34m.so'),
 (3779745, 16123, 59592, 1, 'b', 'binascii.cpython-34m.so'),
 (3795868, 5136, 27520, 1, 'b', 'grp.cpython-34m.so'),
 (3801004, 268336, 762280, 1, 'b', 'libncursesw.5.dylib'),
 (4069340, 4830, 31080, 1, 'b', 'markupsafe._speedups.cpython-34m.so'),
 (4074170, 30974, 100448, 1, 'b', 'math.cpython-34m.so'),
 (4105144, 14991, 57200, 1, 'b', 'mmap.cpython-34m.so'),
 (4120135, 54321, 144256, 1, 'b', 'parser.cpython-34m.so'),
 (4174456, 184578, 564616, 1, 'b', 'pyexpat.cpython-34m.so'),
 (4359034, 17126, 66656, 1, 'b', 'readline.cpython-34m.so'),
 (4376160, 5690, 35656, 1, 'b', 'resource.cpython-34m.so'),
 (4381850, 20160, 66360, 1, 'b', 'select.cpython-34m.so'),
 (4402010, 9445, 41048, 1, 'b', 'termios.cpython-34m.so'),
 (4411455, 17026, 61784, 1, 'b', 'time.cpython-34m.so'),
 (4428481, 591470, 1544792, 1, 'b', 'unicodedata.cpython-34m.so'),
 (5019951, 21629, 73656, 1, 'b', 'zlib.cpython-34m.so'),
 (5041580, 188811, 729531, 1, 'x', 'base_library.zip'),
 (5230391, 9160, 43068, 1, 'x', 'include/python3.4m/pyconfig.h'),
 (5239551, 16316, 63828, 1, 'x', 'lib/python3.4/config-3.4m/Makefile'),
 (5255867, 2449, 6635, 1, 'x', 'lib2to3/Grammar.txt'),
 (5258316, 9016, 20850, 1, 'x', 'lib2to3/Grammar3.4.2.final.0.pickle'),
 (5267332, 9022, 21123, 1, 'x', 'lib2to3/Grammar3.4.3.final.0.pickle'),
 (5276354, 419, 793, 1, 'x', 'lib2to3/PatternGrammar.txt'),
 (5276773, 878, 1455, 1, 'x', 'lib2to3/PatternGrammar3.4.2.final.0.pickle'),
 (5277651, 882, 1455, 1, 'x', 'lib2to3/PatternGrammar3.4.3.final.0.pickle'),
 (5278533, 211, 404, 1, 'x', 'lib2to3/tests/data/README'),
 (5278744, 1784789, 1784789, 0, 'z', 'out00-PYZ.pyz')]
```

Here's bindepend for both platforms:

Windows:
```
(env) C:\Users\marcio\git\und2s101>pyi-bindepend dist\und2s101.exe
dist\und2s101.exe {'KERNEL32.dll', 'msvcrt.dll', 'WS2_32.dll'}
```
MacOS:
```
(env) Marcio-Marchinis-MacBook-Pro-Silver:und2s101 mqm$ pyi-bindepend dist/und2s101 
dist/und2s101 {'/usr/lib/libz.1.dylib', '/usr/lib/libSystem.B.dylib'}
```

Now, I know the pyd file has some C bindings and will load some other DLLs too (Qt DLLs in the same dir, etc).

So... is WIndows special here? Do I need to do something extra under Windows which is not needed under MacOS and Linux?

For the record, it works for me with cxfreeze:

```
cxfreeze und2s101.py --target-dir win
```
 
But I would like to use just pyinstaller on all platforms.

Thanks in advance for your help.

**Comment by tallforasmurf** [comment]
I've nothing to offer (no Windows skills) but just want to say, that was a really nicely prepared report! Just to close the loop, you do know for sure that all the needed modules are present in `C:\Program Files\SciTools-4.0.860-64b\bin\pc-win64` which was at the front of `sys.path`? 

Me, I'd want to annoyingly grind the point home with something in the exception like

    if dllDir:
        print( 'I see', [item for item in os.listdir( dllDir ) if item.startswith( 'under' ) ] )

**Comment by linusg** [comment]
Just to be sure, add `print(os.listdir(dllDir))` right after the `dllDir` definition:

    dllDir = arguments["--undDir"]
    print(os.listdir(dllDir))
    ...

Just like @tallforasmurf has commented.

In my experience, the space in `Program Files` and some slash issues might break the whole thing sometimes.

**Comment by sglebs** [comment]
I added the print and I see the files normally:

```
DLL load failed: The specified module could not be found.
('64bit', 'WindowsPE')
['almd.exe', 'almdntconfig.exe', 'almdservice.exe', 'almdservicealt.exe', 'almfree.exe', 'almhostid.exe', 'almstatus.exe', 'almtest.exe', 'astyle.dll', 'astyle.lib', 'buildspy', 'C', 'crashlog.exe', 'gvlayout.exe', 'Java', 'licenseserver.exe', 'Perl', 'Perl510.dll', 'Plugins', 'Python', 'qt.conf', 'Qt5ConcurrentSciTools.dll', 'Qt5CoreSciTools.dll', 'Qt5GuiSciTools.dll', 'Qt5NetworkSciTools.dll', 'Qt5PrintSupportSciTools.dll', 'Qt5SqlSciTools.dll', 'Qt5WidgetsSciTools.dll', 'Qt5WinExtrasSciTools.dll', 'Qt5XmlSciTools.dll', 'und.exe', 'undcwork.exe', 'understand.exe', 'understand_64.png', 'uperl.exe', 'vcredist_x64.exe']
['understand.pyd']
```

**Comment by sglebs** [comment]
In DepWalker, if I add dllDir and dllDir\Python to the Options-->Configure Module Search, like I do programatically, the only DLL in yellow that I see is Python3.dll. But this one I am assuming it will find, "inside" the EXE produced, right?

I see a bunch of other yellow/missing DLLs in DepWalker but they are API-MS-WIN-*.DLL, which I presume will come from Windows.

Does PyInstaller honor sys.path modified dynamically? It feels like it does not.

**Comment by sglebs** [comment]
Possibly Related: https://github.com/pyinstaller/pyinstaller/issues/1840

**Comment by sglebs** [comment]
I think I found the issue, thanks to using --ondeif instead of o--onefile. The DLL I use links against python3.dll, so it can run against different python versions. Unfortunately PyInstaller only copies python34.dll to the target dir. In fact I had this same issue with cxfreeze - I need to manually copy it myself.

Now I have to figure out how to use --onefile and tell PyInstaller to copy python3.dll as well.

**Comment by sglebs** [comment]
Unfortunately, if I edit the spec file like this:

```
a = Analysis(['geninstability.py'],
             ...,
             binaries= [('C:\\Python34\\DLLs\\python3.dll', '.')],
             ...,
```

I get this, even if the console is open as Administrator:

```
343 INFO: Appending archive to EXE C:\Users\marcio\git\und2s101\build\geninstability\geninstability.exe
406 INFO: checking COLLECT
WARNING: The output directory "C:\Users\marcio\git\und2s101\dist\geninstability" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
2093 INFO: Removing dir C:\Users\marcio\git\und2s101\dist\geninstability
2124 INFO: Building COLLECT out00-COLLECT.toc
2765 ERROR: C:\Users\marcio\AppData\Roaming\pyinstaller\bincache00_py34_64bit\python3.dll
Traceback (most recent call last):
  File "c:\python34\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\marcio\git\und2s101\env\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\building\api.py", line 642, in __init__
    self.__postinit__()
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\building\datastruct.py", line 178, in __postinit__
    self.assemble()
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\building\api.py", line 674, in assemble
    dist_nm=inm)
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\building\utils.py", line 264, in checkCache
    res = winmanifest.GetManifestResources(os.path.abspath(cachedfile))
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1013, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "c:\users\marcio\git\und2s101\env\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 171, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
pywintypes.error: (5, 'LoadLibraryEx', 'Access is denied.')
```

**Comment by sglebs** [comment]
Found the solution. Had to ad it to the *data* section:

```
a = Analysis(['geninstability.py'],
             ...,
             binaries= None,
             datas=[('C:\\Python34\\DLLs\\python3.dll', '.')],
             ...,
```

Why can't PyInstaller copy python3.dll (such a small file) automatically??

**Comment by htgoebel** [comment]
Many thanks for debugging this. I'm closing this issue since implementation will be done in #2293

**Comment by 345161974** [comment]
It takes me several days to find this!!!
Many thanks!

I was wondering why windows pyinstaller still has this bug? it had been so long time when this bug found!
