### ISSUE TITLE
ImportError: No module named apps + pyinstaller + django + linux

### ISSUE THREAD

**Issue by mitulshah44** [pyinstaller/pyinstaller#2263]
I am trying to create executable file for Django using PyInstaller and for that I have keep all installed packages in my project directory on my linux machine.
When I created executable file, it is showing issue of apps which is located in django.
But Django module I have already keep in project directory. still it is showing below issue.

```
Traceback (most recent call last):
  File "django/utils/autoreload.py", line 226, in wrapper
  File "django/core/management/commands/runserver.py", line 113, in inner_run
  File "django/utils/autoreload.py", line 249, in raise_last_exception
  File "django/utils/autoreload.py", line 226, in wrapper
  File "django/__init__.py", line 27, in setup
  File "django/apps/registry.py", line 85, in populate
  File "django/apps/config.py", line 116, in create
  File "importlib/__init__.py", line 37, in import_module
ImportError: No module named apps
```

I also need help for below error 

```
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/home/mitul/projects/asif/asifpro/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "pkg_resources/__init__.py", line 48, in <module>
  File "pkg_resources/extern/__init__.py", line 61, in load_module
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
Failed to execute script pyi_rth_pkgres

```

**Comment by Boco10** [comment]
The import error exists on windows also. Can you provide any useful tip what can be wrong?

**Comment by htgoebel** [comment]
Somebody needs to provide proper hooks, see https://github.com/pyinstaller/pyinstaller/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+django.
