### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by sahina** [pyinstaller/pyinstaller#2281]
```
(build) ➜  pybuild pyinstaller --name=apple_app apple/manage.py
34 INFO: PyInstaller: 3.2
34 INFO: Python: 3.5.2
37 INFO: Platform: Darwin-16.1.0-x86_64-i386-64bit
38 INFO: wrote /Users/sahina/Documents/source/sandbox/pybuild/apple_app.spec
40 INFO: UPX is not available.
41 INFO: Extending PYTHONPATH with paths
['/Users/sahina/Documents/source/sandbox/pybuild/apple',
 '/Users/sahina/Documents/source/sandbox/pybuild']
41 INFO: checking Analysis
41 INFO: Building Analysis because out00-Analysis.toc is non existent
41 INFO: Initializing module dependency graph...
42 INFO: Initializing module graph hooks...
43 INFO: Analyzing base_library.zip ...
1916 INFO: running Analysis out00-Analysis.toc
1921 INFO: Caching module hooks...
1923 INFO: Analyzing /Users/sahina/Documents/source/sandbox/pybuild/apple/manage.py
3394 INFO: Loading module hooks...
3394 INFO: Loading module hook "hook-xml.py"...
3545 INFO: Loading module hook "hook-encodings.py"...
3551 INFO: Loading module hook "hook-django.core.mail.py"...
3582 INFO: Loading module hook "hook-django.core.management.py"...
4139 INFO: Excluding import 'IPython'
4141 WARNING:   Removing import django.core.management.commands.shell from module IPython.IPShell
4141 WARNING:   Removing import django.core.management.commands.shell from module IPython
4141 WARNING:   Removing import django.core.management.commands.shell from module IPython.start_ipython
4142 INFO: Import to be excluded not found: 'matplotlib'
4142 INFO: Import to be excluded not found: 'tkinter'
4142 INFO: Loading module hook "hook-django.core.cache.py"...
4155 INFO: Loading module hook "hook-xml.dom.domreg.py"...
4155 INFO: Loading module hook "hook-django.py"...
4155 INFO: Django root directory /Users/sahina/Documents/source/sandbox/pybuild/apple/apple
Traceback (most recent call last):
  File "/Users/sahina/Documents/source/.envs/build/lib/python3.5/site-packages/PyInstaller/utils/hooks/subproc/django_import_finder.py", line 37, in <module>
    list(settings.TEMPLATE_LOADERS) + \
  File "/Users/sahina/Documents/source/.envs/build/lib/python3.5/site-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'
4596 INFO: Collecting Django migration scripts.
5004 INFO: Loading module hook "hook-django.db.backends.py"...
5037 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
5277 INFO: Loading module hook "hook-pydoc.py"...
5278 INFO: Loading module hook "hook-django.db.backends.mysql.base.py"...
5279 INFO: Loading module hook "hook-sqlite3.py"...
5281 INFO: Loading module hook "hook-django.db.backends.oracle.base.py"...
5323 INFO: Looking for ctypes DLLs
5336 INFO: Analyzing run-time hooks ...
5344 INFO: Including run-time hook 'pyi_rth_django.py'
5358 INFO: Looking for dynamic libraries
5407 INFO: Looking for eggs
5407 INFO: Using Python library /Users/sahina/Documents/source/.envs/build/bin/../.Python
5420 INFO: Warnings written to /Users/sahina/Documents/source/sandbox/pybuild/build/apple_app/warnapple_app.txt
5507 INFO: checking PYZ
5507 INFO: Building PYZ because out00-PYZ.toc is non existent
5507 INFO: Building PYZ (ZlibArchive) /Users/sahina/Documents/source/sandbox/pybuild/build/apple_app/out00-PYZ.pyz
6123 INFO: checking PKG
6123 INFO: Building PKG because out00-PKG.toc is non existent
6123 INFO: Building PKG (CArchive) out00-PKG.pkg
6132 INFO: Bootloader /Users/sahina/Documents/source/.envs/build/lib/python3.5/site-packages/PyInstaller/bootloader/Darwin-64bit/run
6132 INFO: checking EXE
6132 INFO: Building EXE because out00-EXE.toc is non existent
6132 INFO: Building EXE from out00-EXE.toc
6132 INFO: Appending archive to EXE /Users/sahina/Documents/source/sandbox/pybuild/build/apple_app/apple_app
6135 INFO: Fixing EXE for code signing /Users/sahina/Documents/source/sandbox/pybuild/build/apple_app/apple_app
6144 INFO: checking COLLECT
6144 INFO: Building COLLECT because out00-COLLECT.toc is non existent
6144 INFO: Building COLLECT out00-COLLECT.toc
```

Here are the pip packages:

```
(build) ➜  pybuild pip freeze
Django==1.10.3
PyInstaller==3.2
```

When I run the built app:

```
(build) ➜  pybuild ./dist/apple_app/apple_app runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x101e6eae8>
Traceback (most recent call last):
  File "site-packages/django/utils/autoreload.py", line 226, in wrapper
  File "site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
  File "site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
  File "site-packages/django/utils/six.py", line 685, in reraise
  File "site-packages/django/utils/autoreload.py", line 226, in wrapper
  File "site-packages/django/__init__.py", line 27, in setup
  File "site-packages/django/apps/registry.py", line 85, in populate
  File "site-packages/django/apps/config.py", line 116, in create
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'django.contrib.admin.apps'
```

**Comment by rajendra2** [comment]
I am also facing the same issue (AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS').

I am using django 1.10.2 & pyinstaller 3.2.1 ( tried with development version as well).


root@e4f2e3a9e041:/home# pyinstaller --name=app app/manage.py
34 INFO: PyInstaller: 3.2.1
34 INFO: Python: 3.5.2
35 INFO: Platform: Linux-4.9.4-moby-x86_64-with-Ubuntu-16.04-xenial
36 INFO: wrote /home/app.spec
38 INFO: UPX is not available.
41 INFO: Extending PYTHONPATH with paths
['/home/app', '/home']
42 INFO: checking Analysis
42 INFO: Building Analysis because out00-Analysis.toc is non existent
42 INFO: Initializing module dependency graph...
46 INFO: Initializing module graph hooks...
47 INFO: Analyzing base_library.zip ...
2424 INFO: running Analysis out00-Analysis.toc
2448 INFO: Caching module hooks...
2452 INFO: Analyzing /home/app/manage.py
4849 INFO: Loading module hooks...
4849 INFO: Loading module hook "hook-encodings.py"...
4933 INFO: Loading module hook "hook-pydoc.py"...
4934 INFO: Loading module hook "hook-django.core.cache.py"...
5069 INFO: Loading module hook "hook-pytz.py"...
5070 INFO: Loading module hook "hook-PIL.py"...
5072 INFO: Import to be excluded not found: 'FixTk'
5072 INFO: Import to be excluded not found: 'tkinter'
5072 INFO: Excluding import 'PyQt4'
5073 WARNING:   Removing import PIL.ImageQt from module PyQt4
5074 INFO: Excluding import 'PySide'
5075 WARNING:   Removing import PIL.ImageQt from module PySide
5075 INFO: Excluding import 'PyQt5'
5076 WARNING:   Removing import PIL.ImageQt from module PyQt5
5077 INFO: Loading module hook "hook-django.core.management.py"...
6262 INFO: Processing pre-find module path hook   distutils
6878 INFO: Excluding import 'IPython'
6880 WARNING:   Removing import django.core.management.commands.shell from module IPython
6881 INFO: Import to be excluded not found: 'tkinter'
6881 INFO: Import to be excluded not found: 'matplotlib'
6881 INFO: Loading module hook "hook-PIL.Image.py"...
7142 INFO: Loading module hook "hook-xml.dom.domreg.py"...
7142 INFO: Loading module hook "hook-django.py"...
7152 INFO: Django root directory /home/app/app
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/utils/hooks/subproc/django_import_finder.py", line 37, in <module>
    list(settings.TEMPLATE_LOADERS) + \
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'
9413 INFO: Collecting Django migration scripts.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
AttributeError: module 'deepcognition' has no attribute '__file__'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/utils/hooks/__init__.py", line 326, in get_module_file_attribute
    attr = loader.get_filename(package)
AttributeError: 'NoneType' object has no attribute 'get_filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/building/build_main.py", line 470, in assemble
    module_hook.post_graph()
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/building/imphook.py", line 409, in post_graph
    self._load_hook_module()
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/building/imphook.py", line 376, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/compat.py", line 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/hooks/hook-django.py", line 95, in <module>
    mod_dir = os.path.dirname(get_module_file_attribute(mod_name))
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/utils/hooks/__init__.py", line 336, in get_module_file_attribute
    raise ImportError
ImportError

**Comment by LuisHCK** [comment]
Any news about this?

**Comment by xoviat** [comment]
@LuisHCK Would you mind providing a sample "hello world" repository?

**Comment by smorstabilini** [comment]
To fix the "ImportError: No module named django.contrib.admin.apps" problem you have to create a directory, let's call it "your_project/other_hooks". 
Inside that directory create a file called  hook-django.contrib.py with this content:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('django.contrib')
```

Now call pyinstaller in this way:
pyinstaller --name=yourProject --additional-hooks-dir=your_project\other_hooks  your_project\manage.py

While you can use any name for the directory, the file name is mandatory, it has to be "hook-django.contrib.py".

Hope this helps.

References:
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Executable-From-Django
https://github.com/pyinstaller/pyinstaller/issues/2332
https://pythonhosted.org/PyInstaller/hooks.html#how-a-hook-is-loaded

**Comment by LuisHCK** [comment]
@smorstabilini 
It works partially, my solution was to put the entire contrib folder of my env and no more error.
Until I had this new one: 'apps.dashboard.urls'
Perhaps creating another hook for apps

**Comment by smorstabilini** [comment]
@LuisHCK sorry, but at the end I abandoned django 1.10 for django 1.9.
It wasn't straightforward but now my bundle works. I'll do more tests in the next few days and if I have time I'll blog about all the steps I've made so far.

**Comment by htgoebel** [comment]
Somebody needs to provide proper hooks, see https://github.com/pyinstaller/pyinstaller/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+django.

**Comment by Gobiviswa** [comment]
Any news on this ?

**Comment by Ritesh-04** [comment]
i also have same issue,
I had created Exe file of Django project using Pyinstaller, using Django 2.2.3, pyinstaller 3.5.
I am getting below error.

C:\project\t1996\test\ir\dist> .\ir.exe runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\django\utils\autoreload.py", line 54, in wrapper
  File "C:\Users\cceffn\AppData\Local\Temp\_MEI88602\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "site-packages\django\utils\autoreload.py", line 77, in raise_last_exception
  File "site-packages\django\core\management\__init__.py", line 337, in execute
  File "site-packages\django\utils\autoreload.py", line 54, in wrapper
  File "site-packages\django\__init__.py", line 24, in setup
  File "site-packages\django\apps\registry.py", line 91, in populate
  File "site-packages\django\apps\config.py", line 90, in create
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
  File "manage.py", line 17, in main
  File "site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
  File "site-packages\django\core\management\__init__.py", line 375, in execute
  File "site-packages\django\core\management\base.py", line 323, in run_from_argv
  File "C:\Users\cceffn\AppData\Local\Temp\_MEI88602\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "site-packages\django\core\management\base.py", line 364, in execute
  File "C:\Users\cceffn\AppData\Local\Temp\_MEI88602\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\cceffn\AppData\Local\Temp\_MEI88602\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "site-packages\django\utils\autoreload.py", line 587, in run_with_reloader
  File "site-packages\django\utils\autoreload.py", line 572, in start_django
  File "site-packages\django\utils\autoreload.py", line 290, in run
  File "site-packages\django\utils\autoreload.py", line 296, in run_loop
  File "site-packages\django\utils\autoreload.py", line 336, in tick
  File "site-packages\django\utils\autoreload.py", line 352, in snapshot_files
  File "site-packages\django\utils\autoreload.py", line 251, in watched_files
  File "site-packages\django\utils\autoreload.py", line 103, in iter_all_python_module_files
  File "site-packages\django\utils\autoreload.py", line 138, in iter_modules_and_files
  File "pathlib.py", line 1346, in exists
  File "pathlib.py", line 1168, in stat
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
[11888] Failed to execute script manage
