### ISSUE TITLE
raise "Try using 'django.db.backends.XXX'"

### ISSUE THREAD

**Issue by crazylovecat** [pyinstaller/pyinstaller#2282]
I have an application running with django 1.9, it can startup through source code and successfully execute pyinstaller with it, but while running the binary file would raise:
```
[lovecat@bogon dist]$ sudo ./vms
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
  File "site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
  File "site-packages/django/core/management/__init__.py", line 327, in execute
  File "site-packages/django/__init__.py", line 18, in setup
  File "site-packages/django/apps/registry.py", line 108, in populate
  File "site-packages/django/apps/config.py", line 202, in import_models
  File "importlib/__init__.py", line 37, in import_module
  File "/home/lovecat/PyInstaller-3.2/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/django/contrib/auth/models.py", line 4, in <module>
  File "/home/lovecat/PyInstaller-3.2/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/django/contrib/auth/base_user.py", line 49, in <module>
  File "site-packages/django/db/models/base.py", line 108, in __new__
  File "site-packages/django/db/models/base.py", line 307, in add_to_class
  File "site-packages/django/db/models/options.py", line 263, in contribute_to_class
  File "site-packages/django/db/__init__.py", line 36, in __getattr__
  File "site-packages/django/db/utils.py", line 212, in __getitem__
  File "site-packages/django/db/utils.py", line 135, in load_backend
django.core.exceptions.ImproperlyConfigured: 'django.db.backends.mysql' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:

Error was: cannot import name CLIENT
Failed to execute script manage
```

**Comment by htgoebel** [comment]
I assume you need to specify `django.db.backends.mysql` as an hidden import. Please let me know if this worked.

**Comment by htgoebel** [comment]
No answer, I assume this solved the issue.
