### ISSUE TITLE
Python 3.6: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by bayandin** [pyinstaller/pyinstaller#2286]
I try to pack a simple script and with Python 3.6, but packing fails with an error: `IndexError: tuple index out of range`.

Script example:
```
root@868e35a1d67d:~# cat test.py
print("Hello, World!")
```

```
root@868e35a1d67d:~# pyinstaller --debug test.py
31 INFO: PyInstaller: 3.3.dev0+483c819
31 INFO: Python: 3.6.0b4
32 INFO: Platform: Linux-4.4.30-moby-x86_64-with-debian-8.6
32 INFO: wrote /root/test.spec
34 INFO: UPX is not available.
35 INFO: Extending PYTHONPATH with paths
['/root', '/root']
35 INFO: checking Analysis
35 INFO: Building Analysis because out00-Analysis.toc is non existent
35 INFO: Initializing module dependency graph...
36 INFO: Initializing module graph hooks...
37 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.3.dev0+483c819', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1501, in import_hook
    source_package, target_module_partname, level)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1653, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2069, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2159, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2577, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2823, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2723, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

I use docker container: `python:3.6-rc`:
```
root@868e35a1d67d:~# uname -a
Linux 868e35a1d67d 4.4.30-moby #1 SMP Tue Nov 8 10:29:28 UTC 2016 x86_64 GNU/Linux
```
```
root@868e35a1d67d:~# python --version
Python 3.6.0b4
```
```
root@868e35a1d67d:~# pyinstaller --version
3.3.dev0+483c819
```

**Comment by htgoebel** [comment]
Python 3.6 is not supported yet.

**Comment by bayandin** [comment]
It works against the latest dev with merged #2329.

**Comment by rr-** [comment]
It works under Linux, but on Windows the git version still throws an error.

**Comment by htgoebel** [comment]
@rr- *an* error or *this* error?

**Comment by rr-** [comment]
*this* error, sorry for being imprecise.

**Comment by htgoebel** [comment]
Curious, since all CI tests pass even on Windows. If the problem persists on the new machine, please try to dig into the problem and provide more information.

**Comment by rr-** [comment]
It works on the separate machine with W10, sorry for the misinformation...

**Comment by astronouth7303** [comment]
I'm getting this issue with Python v____, PyInstaller v____ on Windows 7:

```
$ pyinstaller myapp.spec
170 INFO: PyInstaller: 3.2.1
170 INFO: Python: 3.6.0
170 INFO: Platform: Windows-7-6.1.7601-SP1
179 INFO: UPX is not available.
180 INFO: Extending PYTHONPATH with paths
['C:\\Users\\James\\code\\myapp']
181 INFO: checking Analysis
195 INFO: Building because C:\Users\James\code\myapp\myapp\__main__.py changed
195 INFO: Initializing module dependency graph...
200 INFO: Initializing module graph hooks...
202 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "C:\Users\James\.virtualenvs\myapp\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\building\build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\depend\analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "c:\users\james\.virtualenvs\myapp\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

**Comment by htgoebel** [comment]
@astronouth7303 RTFM: PyInstaller 3.2.1 does not support Python 3.6

**Comment by waspinator** [comment]
would it be possible to add a check to pyinstaller to check which version of python is running, and show a more useful error?

**Comment by htgoebel** [comment]
@waspinator You mean for those not able to read the docs? SCNR.

**Comment by LiberBear** [comment]
When 3.6.2 will be supported?

**Comment by raviriley** [comment]
So to solve this, do we uninstall python 3.6 and install 3.5?

**Comment by BleedinSweden** [comment]
`    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range`

Hello PyInstaller team. Is there a timeline for 3.6 support? 
If there is a timeline and when to maybe expect support? Your answer influences how I build out my application.
Thanks in advance!

**Comment by htgoebel** [comment]
# PyInstaller 3.2 does not support Python 3.6. Either change to Python3.5 or use the current development version.
