### ISSUE TITLE
Import Error if use use "from. import" or "from .. import"

### ISSUE THREAD

**Issue by roger6blog** [pyinstaller/pyinstaller#2333]
Import Error happens when import Pywinauto module 0.60, latest version:
(https://github.com/pywinauto/pywinauto )
Pyinstaller version is current development version.

```
Traceback (most recent call last):
  File "DeployEnv.py", line 1742, in <module>
  File "C:\temp\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", l
ine 389, in load_module
  File "build\bdist.win32\egg\pywinauto\__init__.py", line 40, in <module>
  File "C:\temp\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", l
ine 389, in load_module
  File "pywinauto\findwindows.py", line 39, in <module>
ImportError: cannot import name win32functions
```

check findwindows.py, it use "." style to import
``from . import win32functions``

Import Error has been fixed after I change to ``import win32functions``

Similar error was happend when pywinauto use ".." style to import module
in uiawrapper.py:
``from .. import backend``
It will cause the Traceback below.
```
Traceback (most recent call last):
  File "DeployEnv.py", line 1742, in <module>
  File "C:\temp\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", l
ine 389, in load_module
  File "build\bdist.win32\egg\pywinauto\__init__.py", line 40, in <module>
  File "C:\temp\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", l
ine 389, in load_module
  File "pywinauto\findwindows.py", line 42, in <module>
  File "C:\temp\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", l
ine 389, in load_module
  File "build\bdist.win32\egg\pywinauto\controls\__init__.py", line 36, in <modu
le>
  File "C:\temp\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", l
ine 389, in load_module
  File "build\bdist.win32\egg\pywinauto\controls\uiawrapper.py", line 40, in <mo
dule>
ImportError: cannot import name backend
``

**Comment by htgoebel** [comment]
Hmm, we have a test-case for this kind of imports, see `py.test tests/functional/test_import.py -k relative`. I wonder what is different in your setup.

Can you please provide a *minimal* example which is failing. E.g. strip down your package to contain only an empty `__init__.py`, a minimal `findwindows.py` and `win32functions` and check if this still fails. Also we need more details, esp. versions, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by htgoebel** [comment]
I just added a test-case on my personal repo and was *not* able to reproduce it. Please provide a test-case showing the failure.

**Comment by roger6blog** [comment]
Here is error reproduce step
1. install pywinauto 0.6 and associated packages
2. import pywinauto module in code
``import pywinauto``

3. Pack this script:
**pyinstaller.py <fie path>**
(Build at windows 2008 x64 and windows 7 x64, both are failed)
Error will occur when import pywinauto:

11:48:00 [464] __init__ -ERROR- Exception happen:
Traceback (most recent call last):
  File "DeployEnv.py", line 1750, in <module>
  File "C:\temp\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", l
ine 389, in load_module
  File "build\bdist.win32\egg\pywinauto\__init__.py", line 40, in <module>
  File "C:\temp\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", l
ine 389, in load_module
  File "build\bdist.win32\egg\pywinauto\findwindows.py", line 39, in <module>
ImportError: cannot import name win32functions

**Comment by htgoebel** [comment]
Since we have test-cases for relative imports and just yesterdays I added another one trying to mimic your package, I assume there is something special about your setup. I do not have a windows system, so I can not reproduce this. **You** need to track down the bug, so I can build a test-case reproducing the problem.

And we still need the versions of the software you are using, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

How exaclty did you install pyautowin? Is it an egg-file, an egg-directory, a wheel, just a plain directory? Did you try reproducing in a clean virtual environment?

**Comment by roger6blog** [comment]
Sorry, I found the root cause, it's caused by pywinauto try to import existing comtypes gen py file but there is no associated UIA py files.  The import error was fixed if I force comtype re-create gen py files.
It should not be caused by pyinstaller. I'm apologized for your inconvenience

**Comment by htgoebel** [comment]
Not much of a problem :-)

**Comment by planzeres** [comment]
I'm having the same exact error with the import failing on win32function
How did you force the comtype to re-create the files for gen folder?

**Comment by planzeres** [comment]
I figured out how to regenerate those but still fails.
