### ISSUE TITLE
win 10 problem build exec

### ISSUE THREAD

**Issue by superlogan72** [pyinstaller/pyinstaller#2344]
D:\Prog_Python\Qt5\Perinetti_Simulator_1_1>pyinstaller.exe --onefile --windowed main.py
125 INFO: PyInstaller: 3.2
125 INFO: Python: 3.5.2
125 INFO: Platform: Windows-10-10.0.14393-SP0
125 INFO: wrote D:\Prog_Python\Qt5\Perinetti_Simulator_1_1\main.spec
125 INFO: UPX is not available.
125 INFO: Extending PYTHONPATH with paths
['D:\\Prog_Python', 'D:\\Prog_Python\\Qt5\\Perinetti_Simulator_1_1']
125 INFO: checking Analysis
125 INFO: Building Analysis because out00-Analysis.toc is non existent
125 INFO: Initializing module dependency graph...
140 INFO: Initializing module graph hooks...
140 INFO: Analyzing base_library.zip ...
4016 INFO: running Analysis out00-Analysis.toc
4125 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-locale-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4688 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-heap-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4703 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-stdio-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4766 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-runtime-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4797 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-math-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4813 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-time-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4828 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-string-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4844 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-process-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4859 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-filesystem-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4859 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-environment-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4875 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-convert-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4875 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-conio-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
4891 INFO: Caching module hooks...
4906 INFO: Analyzing D:\Prog_Python\Qt5\Perinetti_Simulator_1_1\main.py
6797 INFO: Loading module hooks...
6797 INFO: Loading module hook "hook-pydoc.py"...
6797 INFO: Loading module hook "hook-PIL.Image.py"...
6828 INFO: Processing pre-find module path hook   distutils
7360 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
7360 INFO: Loading module hook "hook-PyQt5.py"...
7360 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
7360 INFO: Excluding import 'tkinter'
7360 INFO: Import to be excluded not found: 'FixTk'
7375 INFO: Loading module hook "hook-encodings.py"...
7375 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
7844 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
7907 INFO: Loading module hook "hook-reportlab.pdfbase._fontdata.py"...
7922 INFO: Loading module hook "hook-_tkinter.py"...
8250 INFO: checking Tree
8250 INFO: Building Tree because out00-Tree.toc is non existent
8250 INFO: Building Tree out00-Tree.toc
8391 INFO: checking Tree
8391 INFO: Building Tree because out01-Tree.toc is non existent
8391 INFO: Building Tree out01-Tree.toc
8469 INFO: Loading module hook "hook-reportlab.lib.utils.py"...
8485 INFO: Loading module hook "hook-distutils.py"...
8485 INFO: Loading module hook "hook-PIL.py"...
8485 INFO: Excluding import 'tkinter'
8485 WARNING:   Removing import PIL.ImageTk from module tkinter
8500 INFO: Excluding import 'PySide'
8500 WARNING:   Removing import PIL.ImageQt from module PySide
8500 WARNING:   Removing import PIL.ImageQt from module PySide.QImage
8500 WARNING:   Removing import PIL.ImageQt from module PySide.QPixmap
8500 WARNING:   Removing import PIL.ImageQt from module PySide.qRgba
8500 INFO: Excluding import 'PyQt4'
8500 WARNING:   Removing import PIL.ImageQt from module PyQt4
8500 WARNING:   Removing import PIL.ImageQt from module PyQt4.QImage
8500 WARNING:   Removing import PIL.ImageQt from module PyQt4.qRgba
8500 WARNING:   Removing import PIL.ImageQt from module PyQt4.QPixmap
8500 INFO: Import to be excluded not found: 'FixTk'
8500 INFO: Excluding import 'PyQt5'
8500 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtGui.QImage
8500 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtCore.QIODevice
8500 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtCore.QBuffer
8500 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtGui.qRgba
8500 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtCore
8516 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtGui
8516 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtGui.QPixmap
8516 INFO: Loading module hook "hook-xml.py"...
8516 INFO: Loading module hook "hook-PyQt5.Qt.py"...
8516 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
8611 INFO: Looking for ctypes DLLs
8627 INFO: Analyzing run-time hooks ...
8627 INFO: Including run-time hook 'pyi_rth_qt5.py'
8627 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
8642 INFO: Looking for dynamic libraries
30419 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-utility-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
34247 WARNING: Can not get binary dependencies for file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\api-ms-win-crt-multibyte-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
34247 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt5.QtCore
34247 WARNING: Attempted to add Python module twice with different upper/lowercases: PIL._webp
34247 WARNING: Attempted to add Python module twice with different upper/lowercases: PIL._imagingtk
34247 WARNING: Attempted to add Python module twice with different upper/lowercases: PIL._imaging
34247 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt5.QtGui
34247 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt5.QtWidgets
34247 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt5.Qt
34247 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt5.QtPrintSupport
34247 INFO: Looking for eggs
34247 INFO: Using Python library c:\users\luca\appdata\local\programs\python\python35\python35.dll
34247 INFO: Found binding redirects:
[]
34263 INFO: Warnings written to D:\Prog_Python\Qt5\Perinetti_Simulator_1_1\build\main\warnmain.txt
34294 INFO: checking PYZ
34294 INFO: Building PYZ because out00-PYZ.toc is non existent
34294 INFO: Building PYZ (ZlibArchive) D:\Prog_Python\Qt5\Perinetti_Simulator_1_1\build\main\out00-PYZ.pyz
34919 INFO: checking PKG
34919 INFO: Building PKG because out00-PKG.toc is non existent
34919 INFO: Building PKG (CArchive) out00-PKG.pkg
40998 INFO: Bootloader c:\users\luca\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
40998 INFO: checking EXE
40998 INFO: Building EXE because out00-EXE.toc is non existent
40998 INFO: Building EXE from out00-EXE.toc

I have try also insert in the path  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64

But i get the same error

**Comment by htgoebel** [comment]
No new comments since seven moth, so I'm closing this.
If this is still ans issue for you, please try with PyInstaller 3.2.1. If the issue persists, feel free to add a comment and I'll reopen the issue.
