### ISSUE TITLE
Wrong behavior for handling the Ctrl-C on MacOS

### ISSUE THREAD

**Issue by weyou** [pyinstaller/pyinstaller#2349]
Here is a simple example to reproduce this issue.
```python
import time

try:
    while True:
        time.sleep(0.1)
except KeyboardInterrupt:
    print("stopped by user")
```

Run it with python directly and then enter "Ctrl-C"
```
$ python3 test_ctrlc.py
^Cstopped by user
```
You can see the Ctrl-C is caught correctly.

Pack it with pyinstaller3.2
```
$ python3 -m PyInstaller -c -F test_ctrlc.py
...
$ dist/test_ctrlc 
^CFailed to execute script test_ctrlc
Traceback (most recent call last):
  File "/Users/weyou/Dev/test_ctrlc.py", line 5, in <module>
    time.sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/weyou/Dev/test_ctrlc.py", line 7, in <module>
    print("stopped by user")
KeyboardInterrupt
```

This issue doesn't exist on Windows platform.

**Comment by tallforasmurf** [comment]
Testing with Python 3.4 and PyInstaller 3.2, I get this behavior *sometimes* but not always. The first, 3rd and 6th times I executed `open dist/kbtest` I got this in the console window:

```
Last login: Wed Jan  4 08:59:28 on ttys001
[08:59 ~] /Developer/PyInstallerWork/dist/kbtest ; exit;
^CFailed to execute script kbtest
Traceback (most recent call last):
  File "kbtest.py", line 5, in <module>
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kbtest.py", line 7, in <module>
KeyboardInterrupt
logout

[Process completed]
```
But the 2nd, 4th and 5th tries produced

```
Last login: Wed Jan  4 09:00:19 on ttys001
[09:00 ~] /Developer/PyInstallerWork/dist/kbtest ; exit;
^Cstopped by user
logout

[Process completed]
```
Continuing tests suggest the failure is more frequent than the success but not consistent. So this is a puzzle.

**Comment by tallforasmurf** [comment]
It really seems to be random, it does not matter whether I put in the ^C quickly or wait for a slow count of 3, either way it may fail or not.

It would seem to be that the `try` is not being executed in time to set up the exception handler -- but it's the first thing in the code. Hah! No! Mystery deepens: I add a print:

````
import time
try:
    print('Ready now!')
    while True:
        time.sleep(0.1)
except KeyboardInterrupt:
    print("stopped by user")
````
And the result is:

````
[11:52 ~] /Developer/PyInstallerWork/dist/kbtest ; exit;
Ready now!
^CFailed to execute script kbtest
Traceback (most recent call last):
  File "kbtest.py", line 6, in <module>
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kbtest.py", line 8, in <module>
KeyboardInterrupt
logout

[Process completed]
````

So the user code had definitely set up its exception handler. OK, I'm baffled! Anybody?

**Comment by xoviat** [comment]
If you're looking to solve this problem, you'll need to recompile the bootloader and possibly python with some debug modifications. Specifically, you'll need to add print statements [here][1] and [here][2] to determine how many times each function is being called and what exactly is going on. 

[1]: https://github.com/pyinstaller/pyinstaller/blob/c80fcbd23970a88a2ffc8c4d723112b846727a66/bootloader/src/pyi_utils.c#L753
[2]: https://github.com/python/cpython/blob/7ff93cfe53f1cf1dee0f3427c1e7619b712cffcf/Modules/signalmodule.c#L180

**Comment by schlomo** [comment]
Any news on this? Also seeing this behavior with recent pyinstaller 3.5 and Python 3.7.3 on Mac OS X 10.14.6

**Comment by raulperez** [comment]
Any news on this? I have also this problem.
