### ISSUE TITLE
openpyxl causing import error

### ISSUE THREAD

**Issue by taleinat** [pyinstaller/pyinstaller#2383]
# Description
The import error is caused by the following line in `openpyxl.packaging.extended`:
`from openpyxl import __version__`

The error:
`ImportError: cannot import name '__version__'`

# Workaround:
Editing `openpyxl/packaging/extended.py`, removing the import and replacing the use of `__version__` with a hard-coded string.

# Reproduction:

Command: `pyinstaller.exe --clean --noupx -F --hidden-import=tkinter main.py`

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import openpyxl
  File "_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\openpyxl\__init__.py", line 29, in <module>
  File "_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\openpyxl\workbook\__init__.py", line 5, in <module>
  File "_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\openpyxl\workbook\workbook.py", line 16, in <module>
  File "_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\openpyxl\writer\write_only.py", line 23, in <module>
  File "_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\openpyxl\writer\excel.py", line 36, in <module>
  File "_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\openpyxl\packaging\extended.py", line 4, in <module>
ImportError: cannot import name '__version__'
```

- Windows 10
- Python 3.5.2
- pyinstaller 3.2

**Comment by htgoebel** [comment]
openpyxl is not prepared to been frozen, see [this line in the code](https://bitbucket.org/openpyxl/openpyxl/src/dad834128adcb5ca4330bd2bc4bc714b54ccfbb9/openpyxl/__init__.py?at=default#__init__.py-11). Please contact the author of that module.

Side-note: You should create Open-Document files (.ods) which is an open file format, instead of generating undocumented and prorietery .xlsx files.

**Comment by taleinat** [comment]
So that I can properly inform the developers, what would be required for openpyxl to be prepared for freezing?

Side-note: Great suggestion regarding `.ods`, thanks!

**Comment by tallforasmurf** [comment]
Here you go: https://pythonhosted.org/PyInstaller/runtime-information.html

**Comment by emersonxsu** [comment]
I got the same error when updating openpyxl to the newest version. How should I solve it?

**Comment by VamsidharMuggulla** [comment]
Any solution to fix this in Linux machine

**Comment by pythonwood** [comment]
**same problem with property_cached**


```
    from fs.sshfs import SSHFS
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wilson/local/py3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "fs/sshfs/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wilson/local/py3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "fs/sshfs/sshfs.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wilson/local/py3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "property_cached/__init__.py", line 12, in <module>
  File "pkg_resources/__init__.py", line 1156, in resource_string
  File "pkg_resources/__init__.py", line 1401, in get_resource_string
  File "pkg_resources/__init__.py", line 1570, in _get
  File "/home/wilson/local/py3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 471, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEILPvfcy/property_cached/_version.txt'
```





```
lib/python3.6/site-packages/property_cached$ cat __init__.py
...
__version__ = pkg_resources.resource_string(__name__, "_version.txt").decode('utf-8').strip()
...
```
