### ISSUE TITLE
hook botocore: cannot import 'is_module_satisfies'

### ISSUE THREAD

**Issue by hamadii** [pyinstaller/pyinstaller#2384]
Any body can help me,

I have some error when using pyinstaller.exe in windows.

when I run this command 
      `pyinstaller.exe --onefile --windowed main.spec`
I got this message:
```
208342 INFO: Loading module hook "hook-numpy.core.py"...
208514 INFO: Loading module hook "hook-botocore.py"...
Traceback (most recent call last):
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__

    self.assemble()
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\building\build_main.py", line 470, in assemble
    module_hook.post_graph()
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\building\imphook.py", line 409, in post_graph
    self._load_hook_module()
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\building\imphook.py", line 376, in _load_hook_modu
le
    self.hook_module_name, self.hook_filename)
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\compat.py", line 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "F:\Software\winpython 3.4\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\
lib\site-packages\PyInstaller\hooks\hook-botocore.py", line 22, in <module>
    from PyInstaller.compat import is_py2, is_module_satisfies
ImportError: cannot import name 'is_module_satisfies'
```

here is the main.spec code:
```
# -*- mode: python -*-
import sys
sys.setrecursionlimit(10000)
block_cipher = None


a = Analysis(['main.py'],
             pathex=['F:\\Kantor\\Quote_app'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='main',
          debug=False,
          strip=False,
          upx=True,
          console=False )
```

I am using windows 8.1, winpython 3.4.4.5Qt5, and Tkinter
I have update the botocore.py but the message still appear.
Please help me to fix this problem.
Thankyou.

**Comment by htgoebel** [comment]
@xoviat Your turn, see b2e37d2602898 :-(

@hamadii As a quick work-around, add this to the top of you .spec-file:
```
# work-around a bug in hook-botocore
from PyInstaller.utils.hooks import is_module_satisfies
import PyInstaller.compat
PyInstaller.compat.is_module_satisfies = is_module_satisfies
```

**Comment by nchammas** [comment]
I started hitting this error as well as soon as I upgraded to PyInstaller 3.2.1.

* boto3 1.4.3
* botocore 1.4.91
* Python 3.5.2
* macOS 10.12.2

**Comment by xoviat** [comment]
@htgoebel I am so sorry. I (thought) that I simply applied the changes requested in the relevant issue, but apparently not.

**Comment by xoviat** [comment]
@htgoebel Also, you appear to be experiencing the same issue as me. See appveyor/ci#1263.

**Comment by feuerwelt** [comment]
Just changed my hook-botocore.py to:

```
from PyInstaller.utils.hooks import collect_data_files, is_module_satisfies
from PyInstaller.compat import is_py2

if is_module_satisfies('botocore >= 1.4.36'):
    if is_py2:
        hiddenimports = ['HTMLParser']
    else:
        hiddenimports = ['html.parser']

datas = collect_data_files('botocore')
```
and now everything works fine. :D

**Comment by jwanderson67** [comment]
I'm having this issue, and nothing suggested on this page has resolved.

  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller\hooks\hook-botocore.py", line 22, in <module>
    from PyInstaller.compat import is_py2, is_module_satisfies
ImportError: cannot import name is_module_satisfies

Is this because Python is in the "Program Files (x86)" folder (spaces in the path)? I was building apps previously with no issues. I recently uninstalled and reinstalled Python, pip, and PyInstaller, to verify all of the steps for a knowledge transfer, and I know that Python was previously in the same Program Files (x86) folder.

**Comment by jwanderson67** [comment]
My platform is Windows 8.1

Python 2.7.13 x64
pip 9.0.1
PyInstaller 3.2.1
boto3 1.4.4

**Comment by kyocum** [comment]
Have a similar issue.   PyInstaller 3.2.1, boto3 1.4.7
Looking at 
`.virtual_envs/<your venv name>/lib/python2.7/site-packages/PyInstaller/hooks/hook-botocore.py`
I noticed that it had:
`from PyInstaller.utils.hooks import collect_data_files, is_module_satisfies
from PyInstaller.compat import is_py2, is_module_satisfies`
instead of:
`from PyInstaller.utils.hooks import collect_data_files, is_module_satisfies
from PyInstaller.compat import is_py2`
Changed it to import from hooks and it compiled.

**Comment by htgoebel** [comment]
Is is already fixed. Please use the developement version (and RTFM, which says to do so!)
