### ISSUE TITLE
IndexError: tuple index out of range on Win7 

### ISSUE THREAD

**Issue by shaohua199** [pyinstaller/pyinstaller#2394]
Hi,

When I use pyinstaller3.2.1 to package one test script on Win7 platform, it will report following errors:

test.py:
`print ("test!")`

D:\test>python
`Python 2.7.6 (default, Dec 29 2016, 06:11:13) [MSC v.1500 64 bit (AMD64)] on win32`

D:\test>python D:\Software\PyInstaller-3.2.1\pyinstaller.py test.py
```
155 INFO: PyInstaller: 3.2.1
155 INFO: Python: 2.7.6
155 INFO: Platform: Windows-7-6.1.7601-SP1
155 INFO: wrote D:\test\test.spec
155 INFO: UPX is not available.
155 INFO: Extending PYTHONPATH with paths
['D:\\test', 'D:\\test']
155 INFO: checking Analysis
155 INFO: Building Analysis because out00-Analysis.toc is non existent
155 INFO: Initializing module dependency graph...
155 INFO: Initializing module graph hooks...
Traceback (most recent call last):
  File "D:\Software\PyInstaller-3.2.1\pyinstaller.py", line 15, in <module>
    run()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\__main__.py", line 46, in run_
build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
212, in __init__
    self.__postinit__()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\datastruct.py", line
161, in __postinit__
    self.assemble()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
338, in assemble
    self.graph.add_hiddenimports(self.hiddenimports)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\depend\analysis.py", line 457,
 in add_hiddenimports
    if self.findNode(modnm) is not None:
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1381, in findNode
    m = self._safe_import_hook(name, None, None).pop()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2278, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\depend\analysis.py", line 209,
 in _safe_import_module
    module_basename, module_name, parent_package)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

**Comment by htgoebel** [comment]
PyInstaller fails when trying to add some "hidden import" (PyInstaller\depend\analysis.py", line 457,
 in add_hiddenimports). But you are not specifying any hidden import.

Please run PyInstaller with --log-level=DEBUG, so we can see what it tries to import

**Comment by shaohua199** [comment]
How can I run it with --log-level=DEBUG? I have used it like this but seems nothing change:

```
D:\test>python D:\Software\PyInstaller-3.2.1\pyinstaller.py --log-level=DEBUG test.py
124 INFO: PyInstaller: 3.2.1
124 INFO: Python: 2.7.6
140 INFO: Platform: Windows-7-6.1.7601-SP1
140 INFO: wrote D:\test\test.spec
140 DEBUG: Testing for UPX ...
140 INFO: UPX is not available.
140 DEBUG: script: D:\test\test.py
140 INFO: Extending PYTHONPATH with paths
['D:\\test', 'D:\\test']
140 INFO: checking Analysis
140 INFO: Building Analysis because out00-Analysis.toc is non existent
140 INFO: Initializing module dependency graph...
140 INFO: Initializing module graph hooks...
140 DEBUG: Hidden import: codecs
Traceback (most recent call last):
  File "D:\Software\PyInstaller-3.2.1\pyinstaller.py", line 15, in <module>
    run()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\__main__.py", line 46, in run_
build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
212, in __init__
    self.__postinit__()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\datastruct.py", line
161, in __postinit__
    self.assemble()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
338, in assemble
    self.graph.add_hiddenimports(self.hiddenimports)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\depend\analysis.py", line 457,
 in add_hiddenimports
    if self.findNode(modnm) is not None:
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1381, in findNode
    m = self._safe_import_hook(name, None, None).pop()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2278, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\depend\analysis.py", line 209,
 in _safe_import_module
    module_basename, module_name, parent_package)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

**Comment by shaohua199** [comment]
Hi,

Seems it try to add 'codecs', how can I resolve it?

D:\test>python D:\Software\PyInstaller-3.2.1\pyinstaller.py --hidden-import=code
cs --log-level=DEBUG test.py
125 INFO: PyInstaller: 3.2.1
141 INFO: Python: 2.7.6
141 INFO: Platform: Windows-7-6.1.7601-SP1
141 INFO: wrote D:\test\test.spec
141 DEBUG: Testing for UPX ...
141 INFO: UPX is not available.
141 DEBUG: script: D:\test\test.py
141 INFO: Extending PYTHONPATH with paths
['D:\\test', 'D:\\test']
141 INFO: checking Analysis
141 INFO: Building Analysis because out00-Analysis.toc is non existent
141 INFO: Initializing module dependency graph...
141 INFO: Initializing module graph hooks...
141 DEBUG: Hidden import: codecs
Traceback (most recent call last):
  File "D:\Software\PyInstaller-3.2.1\pyinstaller.py", line 15, in <module>
    run()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\__main__.py", line 46, in run_
..........................

**Comment by htgoebel** [comment]
Duplicate, see #2397

**Comment by htgoebel** [comment]
I'm curious: You are passing `--hidden-import=codecs` and ask how to not add that module?!

**Comment by htgoebel** [comment]
I forgot that debugging for the modulegraph component needs to be enabled differently. Please set the environment variable `MODULEGRAPH_DEBUG`  to `5`. This will flood you with messages, so please try to strip down the output when pasting it here.

**Comment by shaohua199** [comment]
Here is the output after set MODULEGRAPH_DEBUG to 5:

D:\test>python D:\Software\PyInstaller-3.2.1\pyinstaller.py --log-level=DEBUG test.py
141 INFO: PyInstaller: 3.2.1
141 INFO: Python: 2.7.6
141 INFO: Platform: Windows-7-6.1.7601-SP1
141 INFO: wrote D:\test\test.spec
141 DEBUG: Testing for UPX ...
141 INFO: UPX is not available.
141 DEBUG: script: D:\test\test.py
141 INFO: Extending PYTHONPATH with paths
['D:\\test', 'D:\\test']
141 INFO: checking Analysis
141 INFO: Building Analysis because out00-Analysis.toc is non existent
141 INFO: Initializing module dependency graph...
156 INFO: Initializing module graph hooks...
156 DEBUG: Hidden import: codecs
_safe_import_hook 'codecs' None None -1
_import_hook 'codecs' None None -1
determine_parent None
determine_parent -> None
find_head_package None 'codecs' -1
  safe_import_module 'codecs' 'codecs' None
    _find_module_path <- 'codecs' ['D:\\test', 'D:\\test', 'D:\\Software\\PyInst
aller-3.2.1', 'C:\\python27\\lib\\site-packages\\setuptools-6.0.2-py2.7.egg', 'C
:\\python27\\lib\\site-packages\\pillow-2.6.0-py2.7-win-amd64.egg', 'C:\\python2
7\\lib\\site-packages\\plumbum-1.4.2-py2.7.egg', 'C:\\python27\\lib\\site-packag
es\\python_docx-0.8.5-py2.7.egg', 'C:\\python27\\lib\\site-packages\\python_pptx
-0.4.2-py2.7.egg', 'C:\\python27\\lib\\site-packages\\rpyc-3.3.0-py2.7.egg', 'C:
\\python27\\lib\\site-packages\\lxml-3.3.1-py2.7-win-amd64.egg', 'C:\\python27\\
lib\\site-packages\\mysql_python-1.2.3-py2.7-win-amd64.egg', 'C:\\python27\\lib\
\site-packages\\pefile-2016.3.28-py2.7.egg', 'C:\\python27\\lib\\site-packages\\
future-0.16.0-py2.7.egg', 'C:\\python27\\python27.zip', 'C:\\python27\\DLLs', 'C
:\\python27\\lib', 'C:\\python27\\lib\\plat-win', 'C:\\python27\\lib\\lib-tk', '
C:\\python27', 'C:\\python27\\lib\\site-packages', 'C:\\python27\\lib\\site-pack
ages\\win32', 'C:\\python27\\lib\\site-packages\\win32\\lib', 'C:\\python27\\lib
\\site-packages\\Pythonwin', 'D:\\test', 'D:\\test']
    _find_module_path -> (<StringIO.StringIO instance at 0x00000000035ADFC8>, 'C
:\\python27\\lib\\codecs.py', ('.py', 'U', 1))
    load_module 'codecs' 'fp' 'C:\\python27\\lib\\codecs.py'
      addNode SourceModule('codecs',)
Traceback (most recent call last):
  File "D:\Software\PyInstaller-3.2.1\pyinstaller.py", line 15, in <module>
    run()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\__main__.py", line 46, in run_
build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
212, in __init__
    self.__postinit__()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\datastruct.py", line
161, in __postinit__
    self.assemble()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line
338, in assemble
    self.graph.add_hiddenimports(self.hiddenimports)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\depend\analysis.py", line 457,
 in add_hiddenimports
    if self.findNode(modnm) is not None:
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1381, in findNode
    m = self._safe_import_hook(name, None, None).pop()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2278, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\depend\analysis.py", line 209,
 in _safe_import_module
    module_basename, module_name, parent_package)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "D:\Software\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py
", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range

**Comment by shaohua199** [comment]
Hi,

Could you tell me how to fix this error?
I know it is caused by import codecs but it can be imported by python like:
```
D:\test>python
Python 2.7.6 (default, Dec 29 2016, 06:11:13) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import codecs
>>>
```

**Comment by htgoebel** [comment]
Sorry, I thought, I had written a comment. So here is a short version: For some unclear reason the code-object is "corrupt", even if it is created by Python (within modulegraph). I need to get this very code object to have a look.

Please do the following:
- Run pyinstaller under debugger control: e.g. `python -m pdb D:\Software\PyInstaller-3.2.1\pyinstaller.py test.py` - Enter "c" to continue (well, start)
- When the error occurs, you are in the debugger. then enter
```
import marshal
fh = open("co.marshal", "wb")
marshal.dump(module_code_object, fh)
fh.close()
quit
```
- Attach the `co.marshal` file here.

**Comment by shaohua199** [comment]
Attached.


[co.zip](https://github.com/pyinstaller/pyinstaller/files/726073/co.zip)

**Comment by htgoebel** [comment]
I analysed the code object and it is corrupted. So I'm afraid, solving this issue is out of our scope. I have the impression that your Python installation might be corrupted. I have not other explanation for what it going on. Are you using some obfuscating Python interpreter?

If you dissemble the code using (`dis.dis`)[https://docs.python.org/2/library/dis.html], this shows wrong byte-code and fails with an IndexError, too. Here is an excerpt showing parts of the bytecode of `__all__ = [ … ]`
```
 25         148 BUILD_TUPLE             27
            151 BUILD_TUPLE             28
            154 BUILD_MAP               24
            157 DELETE_NAME              7 (__all__)
```
These `BUILD_TUPLE` ought to be `LOAD_CONST` and this `DELETE_NAME` must be a `STORE_GLOBAL`. When disassembling my codecs.pyc, I get this:
```
 25         148 LOAD_CONST              27 ('register_error')
            151 LOAD_CONST              28 ('lookup_error')
            154 BUILD_LIST              24
            157 STORE_NAME               7 (__all__)
```.
So obviously the byte-code in your code-object is wrong.

You can prove this yourself: `import dis; dis.dis(module_code_object, fh)`

**Comment by shaohua199** [comment]
Hi, the python package is generated by myself, use the python-2.7.6 source code, only change some value in include/opcode.h. 
And I have done the same operations for our Linux 64bit python package and Windows 32bit python package, they are both OK with the pyinstaller.
Can we check if there are some difference in pyinstaller for different platform?

**Comment by htgoebel** [comment]
> only change some value in include/opcode.h.

If you are hacking the byte-code, but only changing include/opcode.h, you can not expect Python to work properly. PyInstaller is analyzing the byte-code you incompletely hacked.
