### ISSUE TITLE
IndexError: tuple index out of range with one line 'print("hello" py file

### ISSUE THREAD

**Issue by mingruyue** [pyinstaller/pyinstaller#2397]
hello.py only one line
`print("hello")`
but get error
D:\py>pyinstaller hello.py --log-level=DEBUG
123 INFO: PyInstaller: 3.2.1
125 INFO: Python: 3.6.0
137 INFO: Platform: Windows-10-10.0.14393-SP0
141 INFO: wrote D:\py\hello.spec
142 DEBUG: Testing for UPX ...
146 INFO: UPX is not available.
151 DEBUG: script: D:\py\hello.py
152 INFO: Extending PYTHONPATH with paths
['D:\\py', 'D:\\py']
159 INFO: checking Analysis
163 INFO: Building Analysis because out00-Analysis.toc is non existent
166 INFO: Initializing module dependency graph...
170 INFO: Initializing module graph hooks...
173 INFO: Analyzing base_library.zip ...
176 DEBUG: Collecting submodules for collections
339 DEBUG: collect_submodules - Found submodules: {'collections', 'collections.abc'}
339 DEBUG: Collecting submodules for encodings
509 DEBUG: collect_submodules - Found submodules: {'encodings.cp65001', 'encodings.cp858', 'encodings.iso8859_7', 'encodings.iso2022_jp_2', 'encodings.cp737', 'encodings.iso8859_1', 'encodings.utf_32_be', 'encodings.utf_16_le', 'encodings.cp850', 'encodings.cp855', 'encodings.aliases', 'encodings.utf_8', 'encodings.cp856', 'encodings.cp875', 'encodings.shift_jisx0213', 'encodings.utf_32', 'encodings.koi8_t', 'encodings.hp_roman8', 'encodings.iso8859_6', 'encodings.iso2022_jp_ext', 'encodings.iso8859_8', 'encodings.iso2022_jp_1', 'encodings.cp1006', 'encodings.euc_jis_2004', 'encodings.cp775', 'encodings.cp857', 'encodings.cp863', 'encodings.unicode_internal', 'encodings.mbcs', 'encodings.rot_13', 'encodings.cp932', 'encodings.iso8859_2', 'encodings.mac_romanian', 'encodings.palmos', 'encodings.cp1253', 'encodings.base64_codec', 'encodings.cp950', 'encodings.cp1140', 'encodings.kz1048', 'encodings.iso2022_jp', 'encodings.cp866', 'encodings.cp424', 'encodings.mac_turkish', 'encodings.undefined', 'encodings.mac_roman', 'encodings.big5', 'encodings.zlib_codec', 'encodings.cp861', 'encodings.gb18030', 'encodings.raw_unicode_escape', 'encodings.cp864', 'encodings.iso8859_16', 'encodings.shift_jis', 'encodings.johab', 'encodings.cp720', 'encodings.utf_16', 'encodings.tis_620', 'encodings.iso8859_5', 'encodings.mac_farsi', 'encodings.cp862', 'encodings.cp852', 'encodings.utf_8_sig', 'encodings.cp949', 'encodings', 'encodings.mac_croatian', 'encodings.iso8859_13', 'encodings.mac_latin2', 'encodings.cp869', 'encodings.quopri_codec', 'encodings.cp874', 'encodings.utf_7', 'encodings.hz', 'encodings.mac_greek', 'encodings.cp037', 'encodings.cp437', 'encodings.euc_jisx0213', 'encodings.cp1125', 'encodings.iso8859_4', 'encodings.big5hkscs', 'encodings.cp1254', 'encodings.gb2312', 'encodings.utf_32_le', 'encodings.hex_codec', 'encodings.charmap', 'encodings.iso2022_kr', 'encodings.cp500', 'encodings.koi8_u', 'encodings.cp1255', 'encodings.mac_centeuro', 'encodings.koi8_r', 'encodings.cp1026', 'encodings.euc_kr', 'encodings.iso8859_15', 'encodings.latin_1', 'encodings.cp1256', 'encodings.iso8859_11', 'encodings.euc_jp', 'encodings.iso8859_10', 'encodings.oem', 'encodings.mac_cyrillic', 'encodings.iso8859_3', 'encodings.ascii', 'encodings.unicode_escape', 'encodings.utf_16_be', 'encodings.mac_iceland', 'encodings.mac_arabic', 'encodings.iso8859_14', 'encodings.iso2022_jp_2004', 'encodings.bz2_codec', 'encodings.cp1257', 'encodings.cp1250', 'encodings.cp273', 'encodings.uu_codec', 'encodings.iso8859_9', 'encodings.iso2022_jp_3', 'encodings.cp860', 'encodings.cp1252', 'encodings.cp865', 'encodings.ptcp154', 'encodings.punycode', 'encodings.gbk', 'encodings.shift_jis_2004', 'encodings.idna', 'encodings.cp1251', 'encodings.cp1258'}
Traceback (most recent call last):
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36-32\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\depend\analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "c:\users\liu\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range

D:\py>

**Comment by htgoebel** [comment]
Duplicate, see #2394

**Comment by htgoebel** [comment]
> 125 INFO: Python: 3.6.0

Python 3.6 is not supported.
