### ISSUE TITLE
Anaconda and QtWebEngineCore issue

### ISSUE THREAD

**Issue by juanfcocontreras** [pyinstaller/pyinstaller#2407]
I'm trying to package this simple example in OSX 10.11.6 and Anaconda 4.3.7 (Python 2.7):

https://github.com/r0x0r/pywebview/blob/master/examples/simple_browser.py

I simply execute this:

`pyinstaller simple_browser.py`

But I got the following message:

```
4703 INFO: Loading module hook "hook-PyQt5.QtWebEngineWidgets.py"...
Traceback (most recent call last):
  File "/Users/user/anaconda/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 470, in assemble
    module_hook.post_graph()
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/building/imphook.py", line 409, in post_graph
    self._load_hook_module()
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/building/imphook.py", line 390, in _load_hook_module
    attr_value = sanitizer_func(attr_value)
  File "/Users/user/anaconda/lib/python2.7/site-packages/PyInstaller/building/utils.py", line 466, in format_binaries_and_datas
    src_root_path_or_glob))
PyInstaller.compat.FileNotFoundError: Path or glob "/Users/user/anaconda/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess" not found or matches no files.
```

I have checked and there is not any QtWebEngineCore.framework in Anaconda, so that is the reason of the message. However the following Qt-related packages are installed:

```
pyqt                      5.6.0                    py27_2
qt                        5.6.2                         0
qtawesome                 0.3.3                    py27_0
qtconsole                 4.2.1                    py27_1
qtpy                      1.1.2                    py27_0
```

Anyone can help me? Thanks in advance.

**Comment by xoviat** [comment]
The file is definitely in the anaconda download. Where is the file located on your system?

![image](https://cloud.githubusercontent.com/assets/15351036/22856234/4aab9c32-f053-11e6-9ebf-100291bb1332.png)

**Comment by juanfcocontreras** [comment]
Yes, that file is in my Anaconda distribution:
/Users/user/anaconda/lib/python2.7/site-packages/PyQt5/QtWebEngineCore.so

But the file missing, or at least is showing in the message error, is this one (which is actually missing):
/Users/user/anaconda/lib/QtWebEngineCore.framework

By the way, I'm on OSX, not Windows. I think this is relevant because I don't remember frameworks on Windows.

**Comment by xoviat** [comment]
Duplicate #2276.
