### ISSUE TITLE
File "//anaconda/bin/pyinstaller", line 11, in <module> sys.exit(run())

### ISSUE THREAD

**Issue by abutremutante** [pyinstaller/pyinstaller#2411]
Hi there,

I'm having this same issue bellow when I use these commands:

pyinstaller -onefile windowed file.py
pyinstaller -onefile file.py

Seems to me that it is inside the pyinstaller script. I'm running on a Mac.
Can anyone shine some light on it?

Thanks

Traceback (most recent call last):
  File "//anaconda/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "//anaconda/lib/python2.7/site-packages/PyInstaller/__main__.py", line 73, in run
    args = parser.parse_args(pyi_args)
  File "//anaconda/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "//anaconda/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "//anaconda/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "//anaconda/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "//anaconda/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
TypeError: __call__() takes exactly 4 arguments (5 given)

**Comment by tallforasmurf** [comment]
Something is wrong with this installation. This is occurring at the very beginning of PyInstaller execution, and the error is happening inside standard library code. The relevant code starts on line 63 of `__main__.py`  [here](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/__main__.py#L63).

    parser = argparse.ArgumentParser()
    ...
    args = parser.parse_args(pyi_args)

That's it. all the other traceback is happing inside the standard module `//anaconda/lib/python2.7/argparse.py"`.

**Comment by htgoebel** [comment]
This is caused by our [handling of obsolete options](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/compat.py#L689).

@abutremutante The option has to be written with `--` (two dashes) in front.
