### ISSUE TITLE
SyntaxError: 'yield' inside async function

### ISSUE THREAD

**Issue by mingruyue** [pyinstaller/pyinstaller#2434]
(venv) D:\py\py35>pyinstaller main.py --log-level=DEBUG
109 INFO: PyInstaller: 3.2.1
110 INFO: Python: 3.5.3
110 INFO: Platform: Windows-10-10.0.14393-SP0
111 INFO: wrote D:\py\py35\main.spec
112 DEBUG: Testing for UPX ...
113 INFO: UPX is not available.
114 DEBUG: script: D:\py\py35\main.py
115 INFO: Extending PYTHONPATH with paths
['D:\\py\\py35', 'D:\\py\\py35']
115 INFO: checking Analysis
116 INFO: Building Analysis because out00-Analysis.toc is non existent
117 INFO: Initializing module dependency graph...
122 INFO: Initializing module graph hooks...
127 INFO: Analyzing base_library.zip ...
128 DEBUG: Collecting submodules for encodings
275 DEBUG: collect_submodules - Found submodules: {'encodings.cp1256', 'encodings.iso2022_jp', 'encodings.bz2_codec', 'encodings.cp1255', 'encodings.cp949', 'encodings.cp1254', 'encodings.euc_jisx0213', 'encodings.hex_codec', 'encodings.iso8859_13', 'encodings.cp1140', 'encodings.charmap', 'encodings.utf_16', 'encodings.utf_32_le', 'encodings.cp858', 'encodings.iso8859_10', 'encodings.cp932', 'encodings.cp866', 'encodings.utf_32_be', 'encodings.euc_jis_2004', 'encodings.rot_13', 'encodings.utf_16_be', 'encodings.iso2022_jp_ext', 'encodings.hz', 'encodings.palmos', 'encodings.big5', 'encodings.mac_greek', 'encodings.iso8859_9', 'encodings.cp862', 'encodings.iso2022_jp_2', 'encodings.koi8_t', 'encodings.cp1251', 'encodings.mac_turkish', 'encodings.iso8859_5', 'encodings.latin_1', 'encodings.undefined', 'encodings.koi8_u', 'encodings.aliases', 'encodings.iso8859_15', 'encodings.iso2022_kr', 'encodings.cp856', 'encodings.utf_8_sig', 'encodings.iso8859_14', 'encodings.utf_8', 'encodings.johab', 'encodings.gbk', 'encodings.cp1253', 'encodings.mbcs', 'encodings.cp65001', 'encodings.cp1252', 'encodings.shift_jis', 'encodings.raw_unicode_escape', 'encodings.punycode', 'encodings.mac_farsi', 'encodings.cp273', 'encodings.cp1258', 'encodings.big5hkscs', 'encodings.mac_arabic', 'encodings.utf_7', 'encodings.iso8859_8', 'encodings.hp_roman8', 'encodings.shift_jis_2004', 'encodings.euc_jp', 'encodings.cp737', 'encodings.iso8859_4', 'encodings', 'encodings.cp950', 'encodings.cp852', 'encodings.cp863', 'encodings.cp875', 'encodings.tis_620', 'encodings.mac_roman', 'encodings.cp1006', 'encodings.iso2022_jp_3', 'encodings.unicode_internal', 'encodings.quopri_codec', 'encodings.koi8_r', 'encodings.iso8859_2', 'encodings.iso8859_6', 'encodings.cp869', 'encodings.utf_16_le', 'encodings.cp1250', 'encodings.mac_romanian', 'encodings.mac_centeuro', 'encodings.cp500', 'encodings.cp860', 'encodings.kz1048', 'encodings.euc_kr', 'encodings.cp874', 'encodings.cp1257', 'encodings.iso8859_16', 'encodings.base64_codec', 'encodings.cp437', 'encodings.iso2022_jp_1', 'encodings.gb2312', 'encodings.gb18030', 'encodings.cp037', 'encodings.mac_cyrillic', 'encodings.cp864', 'encodings.cp775', 'encodings.iso8859_7', 'encodings.mac_latin2', 'encodings.cp1026', 'encodings.ptcp154', 'encodings.shift_jisx0213', 'encodings.cp857', 'encodings.iso8859_11', 'encodings.cp850', 'encodings.iso2022_jp_2004', 'encodings.utf_32', 'encodings.zlib_codec', 'encodings.cp1125', 'encodings.idna', 'encodings.ascii', 'encodings.iso8859_3', 'encodings.cp424', 'encodings.mac_croatian', 'encodings.cp865', 'encodings.cp720', 'encodings.cp855', 'encodings.unicode_escape', 'encodings.uu_codec', 'encodings.iso8859_1', 'encodings.mac_iceland', 'encodings.cp861'}
276 DEBUG: Collecting submodules for collections
420 DEBUG: collect_submodules - Found submodules: {'collections.__main__', 'collections.abc', 'collections'}
3022 DEBUG: Adding python files to base_library.zip
3059 DEBUG: Hidden import: codecs
3060 DEBUG: Hidden import 'codecs' already found
3063 INFO: running Analysis out00-Analysis.toc
3064 DEBUG: Analyzing d:\py\py35\venv\scripts\python.exe
3070 DEBUG: Dependent assemblies of d:\py\py35\venv\scripts\python.exe:
3070 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
3071 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\py\py35\venv\scripts\python.exe
3079 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
3158 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python.exe
3166 DEBUG: Skipping KERNEL32.dll dependency of python.exe
3217 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python.exe
3267 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python.exe
3271 DEBUG: Adding python35.dll dependency of python.exe from d:\py\py35\venv\scripts\python35.dll
3276 DEBUG: Skipping VCRUNTIME140.dll dependency of python.exe
3330 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python.exe
3379 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python.exe
3379 DEBUG: Analyzing d:\py\py35\venv\scripts\python35.dll
3385 DEBUG: Dependent assemblies of d:\py\py35\venv\scripts\python35.dll:
3387 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
3388 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
3414 DEBUG: Skipping ADVAPI32.dll dependency of python35.dll
3463 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3467 DEBUG: Skipping KERNEL32.dll dependency of python35.dll
3520 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3569 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3619 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3669 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3718 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3722 DEBUG: Skipping VERSION.dll dependency of python35.dll
3727 DEBUG: Skipping VCRUNTIME140.dll dependency of python35.dll
3776 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3826 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3874 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3924 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3975 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
3979 DEBUG: Skipping WS2_32.dll dependency of python35.dll
4032 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of d:\py\py35\venv\scripts\python35.dll
4036 INFO: Caching module hooks...
4043 INFO: Analyzing D:\py\py35\main.py
4521 INFO: Processing pre-safe import module hook   six.moves
4902 INFO: Processing pre-safe import module hook   win32com
4903 DEBUG: win32com: extending __path__ with dir 'd:\\py\\py35\\venv\\lib\\site-packages\\win32comext'
5030 INFO: Processing pre-find module path hook   distutils
5031 INFO: distutils: retargeting to non-venv dir 'c:\\python35-32\\Lib\\distutils'
5667 INFO: Processing pre-find module path hook   site
5668 INFO: site: retargeting to fake-dir 'd:\\py\\py35\\venv\\lib\\site-packages\\PyInstaller\\fake-modules'
Traceback (most recent call last):
  File "c:\python35-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\py\py35\venv\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\building\build_main.py", line 413, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 144, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1436, in run_script
    self._scan_code(m, co, co_ast)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2592, in _scan_code
    self._process_imports(module)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2881, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2278, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2115, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2951, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2592, in _scan_code
    self._process_imports(module)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2881, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2278, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2115, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2951, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2592, in _scan_code
    self._process_imports(module)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2881, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2278, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1510, in import_hook
    target_module = self._load_tail(target_package, target_module_partname)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1723, in _load_tail
    submodule = self._safe_import_module(head, mname, submodule)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "d:\py\py35\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2164, in _load_module
    co = compile(co_ast, pathname, 'exec', 0, True)
  File "d:\py\py35\venv\lib\site-packages\jinja2\asyncsupport.py", line 35
    yield event
    ^
SyntaxError: 'yield' inside async function

(venv) D:\py\py35>

**Comment by xoviat** [comment]
This issue has already been fixed in develop.

**Comment by htgoebel** [comment]
More specific in 48d5554ae74c2759d1fc099d4b2546288cad59fb

**Comment by mingruyue** [comment]
but after i reinstalled pyinstall,  i got the same error 
how to use the unmerged code @htgoebel

**Comment by xoviat** [comment]
```
git clone https://github.com/pyinstaller/pyinstaller.git
cd pyinstaller
pip install .
```

**Comment by htgoebel** [comment]
… as documented in [the wiki](https://github.com/pyinstaller/pyinstaller/wiki#downloads] since long.

Looks like people are to lazy to read the docs.

**Comment by wcolemorris** [comment]
Just wanted to say I'm very glad somebody opened this ticket, quick and easy fix for me with a google search!  Thank you to both xoviat and htgoebel for the help 👍

**Comment by nateshmbhat** [comment]
thanks for the links and tips guys .

**Comment by angelapriyadharshini** [comment]
Thanks it works :)
