### ISSUE TITLE
3.3.dev0 fails to install due to Pywin32

### ISSUE THREAD

**Issue by LiaungYip** [pyinstaller/pyinstaller#2448]
On Windows 7, Python 3.6.0, using tip of `develop` branch ( 11f2e7b ):

Trying to install latest PyInstaller from GitHub. `setup.py` fails to complete because setup script for dependency `pywin32` is expecting Python 2 (` SyntaxError: Missing parentheses in call to 'print'`.)

On inspection, it's trying to fetch Pywin32 build 219 - there's a build 220 available. Might that fix it?

    PS C:\Users\layip\git\pyinstaller> ./setup.py install
    running install
    [ ... 830 lines snipped ...]
    Installed c:\tools\python\lib\site-packages\pyinstaller-3.3.dev0+g11f2e7b-py3.4.egg
    Processing dependencies for PyInstaller==3.3.dev0+g11f2e7b
    Searching for pypiwin32
    Reading https://pypi.python.org/simple/pypiwin32/
    Best match: pypiwin32 219
    Downloading https://pypi.python.org/packages/2b/ca/5c086c18de8f70222787b3e824e755b68d99272531522e77bb381d4f60c8/pypiwin32-219.zip#md5=eeef354709
    d1681bfb566810a685f66d
    Processing pypiwin32-219.zip
    Writing C:\Users\layip\AppData\Local\Temp\easy_install-mbayh541\pypiwin32-219\setup.cfg
    Running pypiwin32-219\setup.py -q bdist_egg --dist-dir C:\Users\layip\AppData\Local\Temp\easy_install-mbayh541\pypiwin32-219\egg-dist-tmp-0_kv4a
    cf
    Traceback (most recent call last):
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 150, in save_modules
        yield saved
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context
        yield
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 235, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 265, in run
        return func()
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 234, in runner
        _execfile(setup_script, ns)
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        code = compile(script, filename, 'exec')
      File "C:\Users\layip\AppData\Local\Temp\easy_install-mbayh541\pypiwin32-219\setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\layip\git\pyinstaller\setup.py", line 201, in <module>
        'pyi-set_version = PyInstaller.utils.cliutils.set_version:run',
      File "C:\tools\python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\tools\python\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\tools\python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\tools\python\lib\site-packages\setuptools\command\install.py", line 67, in run
        self.do_egg_install()
      File "C:\tools\python\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
        cmd.run()
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 374, in run
        self.easy_install(spec, not self.no_deps)
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 604, in easy_install
        return self.install_item(None, spec, tmpdir, deps, True)
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 655, in install_item
        self.process_distribution(spec, dist, deps)
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 703, in process_distribution
        [requirement], self.local_index, self.easy_install
      File "C:\tools\python\lib\site-packages\pkg_resources\__init__.py", line 797, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\tools\python\lib\site-packages\pkg_resources\__init__.py", line 1047, in best_match
        return self.obtain(req, installer)
      File "C:\tools\python\lib\site-packages\pkg_resources\__init__.py", line 1059, in obtain
        return installer(requirement)
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 838, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 1066, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 1052, in run_setup
        run_setup(setup_script, args)
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 238, in run_setup
        raise
      File "C:\tools\python\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context
        yield
      File "C:\tools\python\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 162, in save_modules
        saved_exc.resume()
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 137, in resume
        compat.reraise(type, exc, self._tb)
      File "C:\tools\python\lib\site-packages\setuptools\compat.py", line 65, in reraise
        raise value.with_traceback(tb)
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 150, in save_modules
        yield saved
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context
        yield
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 235, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 265, in run
        return func()
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 234, in runner
        _execfile(setup_script, ns)
      File "C:\tools\python\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        code = compile(script, filename, 'exec')
      File "C:\Users\layip\AppData\Local\Temp\easy_install-mbayh541\pypiwin32-219\setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'
    PS C:\Users\layip\git\pyinstaller>

**Comment by LiaungYip** [comment]
Closing:
Error was between keyboard and chair.
Was using an old installation of Python 3.4 instead of my new installation of Python 3.6.
