### ISSUE TITLE
Some error to do with ctypes.  Is this on my end or an issue?

### ISSUE THREAD

**Issue by FruitfulApproach** [pyinstaller/pyinstaller#2458]
App build goes okay.

**Upon running:**
```
> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "led_window.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "lsapp_window.py", line 3, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "app.py", line 6, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "proj_mgr.py", line 8, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "lsapp_project.py", line 2, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "led_proj_widget.py", line 3, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "led_toolbox.py", line 10, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "led_item.py", line 6, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)

>   **File "ledgloweffect.py", line 14, in <module>
>   File "ctypes\__init__.py", line 425, in LoadLibrary
>   File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 153, in __init__
>   File "ctypes\__init__.py", line 347, in __init__
> OSError: [WinError 126] The specified module could not be found
> Failed to execute script main**
```

**Upon doing _pip3 install ctypes_:**
```
> Collecting cytypes
>   Could not find a version that satisfies the requirement cytypes (from versions: )
> No matching distribution found for cytypes
```
**However, the app runs just fine when building normally and running.**

**More info:**

- Win 7 64 bit
- Python 3.5.2
- Mostly a PyQt5 5.7.1  app

**Upon _pip3 show ctypes_:**
(Nothing shown)

**However, I can build the DLL just fine and use ctypes to make calls to it.**

**Comment by htgoebel** [comment]
`ctypes` is a Python standard module.

This looks like PyInstaller is not able to detect the DLL `ledgloweffect.py` tries to load in line 14. Please refer to https://github.com/pyinstaller/pyinstaller/wiki/Feature-Ctypes-Dependencies for more information about how PyInstaller handles ctypes. Please also have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for further tips to find out what is missing and how to include he missing files.
