### ISSUE TITLE
pyi-makespec and pyinstaller crash when run on LinuxMint17.3-Rosa

### ISSUE THREAD

**Issue by Caoimhinmg** [pyinstaller/pyinstaller#2491]
So I'm trying to compile a Linux standalone binary for the open source project I work on, as I have a number of times in the past, but when trying to freeze the GUI this time I ran into this set of issues which were not a problem when creating the Windows 10 32 bit binary. My system specs are below followed by the two commands I ran that failed the first trying to make a spec file and the second when using the old spec file ([PmagGUI_Ubuntu14_04x64.spec](https://github.com/pyinstaller/pyinstaller/files/828989/PmagGUI_Ubuntu14_04x64.spec.txt)) from the last time I froze this application. Let me know if you need any more information. I have tried exporting a log file as suggested in the wiki using `pyinstaller [options] --log-level DEBUG > out.txt` but nothing seems to be written to this file.

System Info:
- python version : 2.7.6 **Note:** all python libraries and modules are installed using latest versions from apt or pip
- pyinstaller versions tried : 3.2.1 (installed via pip) and 3.3.dev0+g8b491de (installed by cloning the repo and using setup.py)
- OS info : Linux Mint 17.3 - 14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015
- kernal : 3.19.0-32-generic

Command trying to generate spec file:
```bash
pyi-makespec --onefile --windowed --icon=./programs/images/PmagPy.ico --name=PmagGUI_Ubuntu14_04x64 ./programs/pmag_gui.py
```

Traceback produced by the above command:
```python
Traceback (most recent call last):
  File "/usr/local/bin/pyi-makespec", line 11, in <module>
    load_entry_point('PyInstaller==3.3.dev0+g8b491de', 'console_scripts', 'pyi-makespec')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/utils/cliutils/makespec.py", line 27, in run
    PyInstaller.compat.__add_obsolete_options(p)
AttributeError: 'module' object has no attribute '__add_obsolete_options'
```

Command trying to run using the old spec file:
```bash
pyinstaller --clean PmagGUI_Ubuntu14_04x64.spec
```

Traceback from running the old spec file (not sure if this is something hardware or not I have never encountered IOError [Errno 5]):
```python
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.3.dev0+g8b491de', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/__main__.py", line 87, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/__main__.py", line 45, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/building/api.py", line 406, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/building/api.py", line 195, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/building/api.py", line 280, in assemble
    pylib_name=pylib_name)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/archive/writers.py", line 332, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/archive/writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/archive/writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+g8b491de-py2.7.egg/PyInstaller/archive/writers.py", line 397, in add
    buf = fh.read(16*1024)
IOError: [Errno 5] Input/output error
```

**Comment by Caoimhinmg** [comment]
Okay, forgot to pull the new changes, but as that only pertains to the first error it wasn't a problem. Here is the filehandle you asked for: <open file '/usr/share/icons/hicolor/128x128/apps/skype.png', mode 'rb' at 0x7fd962cf9810>. Which as far as I can tell is a 128x128 skype icon. I have no idea why it would be grabbing this but the file seems to be corrupted as I can't print out anything to terminal which should at least give me garbled characters for a binary. Anyway I've purged skype from my distro and reinstalled their new beta version for linux and everything runs like a charm. Thanks for your help.

**Comment by htgoebel** [comment]
Purging skype is always a good idea , but why did you re-install it? :-\
