### ISSUE TITLE
Failed to pack keras+theano script

### ISSUE THREAD

**Issue by MaratZakirov** [pyinstaller/pyinstaller#2512]
Hello I am trying to make self-contained execution script of tiny keras+theano model.

(This is kind of continue of https://github.com/pyinstaller/pyinstaller/issues/2114)

```
import os
os.environ['KERAS_BACKEND']='theano'

import keras
import theano.tensor.shared_randomstreams

print "Hello keras"

from keras.models import Sequential
from keras.layers import Dense, Activation, LSTM, Input
from keras.models import Model
import numpy

x_data = numpy.array([[1, 3], [4, 5], [6, 7], [8, 9]]).astype('float32')
l_data = numpy.array([0.3, 0.5, -0.7, 0.8]).astype('float32')

model = Sequential([Dense(1, input_dim=2), Activation('linear')])
model.compile(optimizer='sgd', loss='mse')

model.fit(x = x_data, y=l_data)
```

After I compile it as pyinstaller --onefile it fails to start with message

```
===============================
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=corei7 -mcx16 -msahf -mno-movbe -maes -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mno-avx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mno-xsave -mno-xsaveopt --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=12288 -mtune=corei7 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/tmp/_MEI4QhxrM/numpy/core/include -I/tmp/_MEI4QhxrM/include/python2.7 -I/tmp/_MEI4QhxrM/theano/gof -fvisibility=hidden -o /home/zakirov/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-2.7.12-64/tmpox46XN/c25c9ba4db584bf094983a608a1bfc89.so /home/zakirov/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-2.7.12-64/tmpox46XN/mod.cpp -L/home/zakirov/proj/Python-2.7.12/lib/lib -L/tmp/_MEI4QhxrM/lib -lpython2.7
/home/zakirov/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-2.7.12-64/tmpox46XN/mod.cpp:1:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.

Traceback (most recent call last):
  File "cool-exe-ltr.py", line 20, in <module>
    model.fit(x = x_data, y=l_data)
  File "site-packages/keras/models.py", line 845, in fit
  File "site-packages/keras/engine/training.py", line 1457, in fit
  File "site-packages/keras/engine/training.py", line 1007, in _make_train_function
  File "site-packages/keras/backend/theano_backend.py", line 1081, in function
  File "site-packages/keras/backend/theano_backend.py", line 1067, in __init__
  File "site-packages/theano/compile/function.py", line 320, in function
  File "site-packages/theano/compile/pfunc.py", line 479, in pfunc
  File "site-packages/theano/compile/function_module.py", line 1777, in orig_function
  File "site-packages/theano/compile/function_module.py", line 1641, in create
  File "site-packages/theano/gof/link.py", line 690, in make_thunk
  File "site-packages/theano/gof/vm.py", line 1003, in make_all
  File "site-packages/theano/gof/op.py", line 970, in make_thunk
  File "site-packages/theano/gof/op.py", line 879, in make_c_thunk
  File "site-packages/theano/gof/cc.py", line 1200, in make_thunk
  File "site-packages/theano/gof/cc.py", line 1143, in __compile__
  File "site-packages/theano/gof/cc.py", line 1595, in cthunk_factory
  File "site-packages/theano/gof/cmodule.py", line 1142, in module_from_key
  File "site-packages/theano/gof/cc.py", line 1506, in compile_cmodule
  File "site-packages/theano/gof/cmodule.py", line 2204, in compile_str
Exception: ('The following error happened while compiling the node', Elemwise{mul,no_inplace}(InplaceDimShuffle{x,x}.0, InplaceDimShuffle{x,x}.0, InplaceDimShuffle{x,x}.0), '\n', 'Compilation failed (return status=1): /home/zakirov/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-2.7.12-64/tmpox46XN/mod.cpp:1:20: fatal error: Python.h: No such file or directory.  #include <Python.h>.                     ^. compilation terminated.. ', '[Elemwise{mul,no_inplace}(<TensorType(float32, (True, True))>, <TensorType(float32, (True, True))>, <TensorType(float32, (True, True))>)]')
Failed to execute script cool-exe-ltr
```
Maybe I need to take Python.h (and plenty other) in same package? Any suggestions?

**Comment by xoviat** [comment]
> Hello I am trying to make self-contained execution script of tiny keras+theano model.

theano requires a compiler to run so pyinstaller would need to bundle gcc and who knows how many of its dependencies. If you have any ideas on this matter, let us know. Otherwise, it's probably not going anywhere anytime soon.

**Comment by xoviat** [comment]
Duplicate #2114
