### ISSUE TITLE
Problem with Happybase

### ISSUE THREAD

**Issue by Monafree** [pyinstaller/pyinstaller#2537]
While I'm packaging a program  which uses happybase, pyinstaller could successfully package the program.

But when I'm running the program, I encountered some issue with the dependency of happybase

`
Traceback (most recent call last):
  File "CLI_chain_0327.py", line 1, in <module>
  File "/tmp/pip-build-7PQEiI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "happybase/__init__.py", line 10, in <module>
  File "thriftpy/parser/__init__.py", line 30, in load
  File "thriftpy/parser/parser.py", line 489, in parse
IOError: [Errno 2] No such file or directory: '/tmp/_MEIPQpx76/happybase/Hbase.thrift'
`

please help me to fix this issus, thanks

**Comment by shane-Git** [comment]
Having the same problem.

**Comment by xoviat** [comment]
You need to include the datas manually. 

@shane-Git @Monafree It would be very nice if one of you submitted a PR with a hook. See [hook-CLRL29](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-clr.py#L29) for an example.

**Comment by HaydenZain** [comment]
@xoviat how to include the '/Hbase.thrift'? thks
