### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'PyInstaller==3.2.1' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by DyingEcho** [pyinstaller/pyinstaller#2538]
Hello PyInstaller!

This is an issue with running PyInstaller, not with the bundle it produces.
I'm running macOS Sierra with Python 3.5 and the latest PyInstaller (3.12.1 from setup.py)
I have a Python 3.5 program (`main.py`) that I am trying to run `pyinstaller --name myProgram --osx-bundle-identifier my.bundle.identifer` on.
I am getting this:
```
anubis:myProgram DyingEcho$ pyinstaller --name myProgram --osx-bundle-identifier my.bundle.identifier
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyInstaller==3.2.1' distribution was not found and is required by the application
```

Could anyone help me out with this? All help would be greatly appreciated!

**Comment by DyingEcho** [comment]
Installing version 3.1.1 (Python 3.5) from MacPorts gives the same error.

**Comment by xoviat** [comment]
have you installed pyinstaller using pip?

**Comment by DyingEcho** [comment]
No, I downloaded from the Versions Page at GitHub and installed with
```setup.py build```
and then
```setu.py install``

**Comment by xoviat** [comment]
The commmand is:

```
pip install --upgrade git+https://github.com/pyinstaller/pyinstaller.git
```

**Comment by DyingEcho** [comment]
Thanks!

**Comment by davidmnoll** [comment]
I'm having this issue as well on windows 10, upgraded from git as suggested and it hasn't worked.
