### ISSUE TITLE
hook h5py issue

### ISSUE THREAD

**Issue by giumas** [pyinstaller/pyinstaller#2540]
With the current develop branch (https://github.com/pyinstaller/pyinstaller/commit/483dfdebad65679ded59476514c9a5528c4ba3b6), on Win10 and Python 3.6, the hidden imports listed in the hook are not actually bundled.

I attempted to manually copy and rename the 4 pyds (https://github.com/pyinstaller/pyinstaller/blob/a70b20e4de6a6817987d28ca9f3201c8105fd858/PyInstaller/hooks/hook-h5py.py), and it works.

**Comment by xoviat** [comment]
I'll take care of this. Can you post an example?

**Comment by giumas** [comment]
This issue might be somehow similar to https://github.com/pyinstaller/pyinstaller/issues/1522#issuecomment-290959184 .

The (very) minimal example (h5py_pyinstaller.py) is:

`import h5py`
 
Then, under both Conda and vanilla Python 3.6, the command `pyinstaller h5py_pyinstaller.py` outputs:

```
D:\test_data\h5py>pyinstaller h5py_pyinstaller.py
85 INFO: PyInstaller: 3.3.dev0+483dfde
85 INFO: Python: 3.6.0
86 INFO: Platform: Windows-10-10.0.14393-SP0
90 INFO: wrote D:\test_data\h5py\h5py_pyinstaller.spec
93 INFO: UPX is not available.
96 INFO: Extending PYTHONPATH with paths
['D:\\test_data\\h5py', 'D:\\test_data\\h5py']
97 INFO: checking Analysis
97 INFO: Building Analysis because out00-Analysis.toc is non existent
97 INFO: Initializing module dependency graph...
100 INFO: Initializing module graph hooks...
102 INFO: Analyzing base_library.zip ...
3387 INFO: running Analysis out00-Analysis.toc
3389 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\user\AppData\Local\HyOc\py3\x64\python.exe
3774 INFO: Caching module hooks...
3779 INFO: Analyzing D:\test_data\h5py\h5py_pyinstaller.py
4786 INFO: Processing pre-find module path hook   distutils
7109 INFO: Processing pre-find module path hook   site
280180 INFO: site: retargeting to fake-dir 'C:\\Users\\user\\AppData\\Local\\HyOc\\py3\\x64\\lib\\site-packages\\PyInstaller\\fake-modules'
280204 INFO: Processing pre-safe import module hook   win32com
283024 INFO: Processing pre-safe import module hook   six.moves
284297 INFO: Processing pre-safe import module hook   requests.packages.urllib3.packages.six.moves
298884 INFO: Loading module hooks...
298884 INFO: Loading module hook "hook-cryptography.py"...
Traceback (most recent call last):
  File "<string>", line 49, in <module>
  File "<string>", line 23, in walk_packages
  File "<string>", line 20, in walk_packages
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cryptography\hazmat\backends\commoncrypto\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.commoncrypto.backend import backend
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cryptography\hazmat\backends\commoncrypto\backend.py", line 19, in <module>
    from cryptography.hazmat.bindings.commoncrypto.binding import Binding
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cryptography\hazmat\bindings\commoncrypto\binding.py", line 7, in <module>
    from cryptography.hazmat.bindings._commoncrypto import ffi, lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._commoncrypto'
299368 INFO: Loading module hook "hook-distutils.py"...
299369 INFO: Loading module hook "hook-encodings.py"...
299450 INFO: Loading module hook "hook-h5py.py"...
299452 WARNING: Hidden import "_proxy" not found!
299453 WARNING: Hidden import "utils" not found!
299454 WARNING: Hidden import "defs" not found!
299455 WARNING: Hidden import "h5ac" not found!
299455 INFO: Loading module hook "hook-IPython.py"...
299465 INFO: Excluding import 'PySide'
299471 WARNING:   Removing import IPython.external.qt_loaders from module PySide.QtGui
299471 WARNING:   Removing import IPython.external.qt_loaders from module PySide.QtSvg
299471 WARNING:   Removing import IPython.external.qt_loaders from module PySide
299472 WARNING:   Removing import IPython.external.qt_loaders from module PySide.QtCore
299473 INFO: Excluding import 'tkinter'
299478 WARNING:   Removing import IPython.lib.clipboard from module tkinter
299480 INFO: Excluding import 'PyQt5'
299487 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5
299488 INFO: Excluding import 'matplotlib'
299493 WARNING:   Removing import IPython.core.pylabtools from module matplotlib
299493 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.figure
299493 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.pyplot
299494 WARNING:   Removing import IPython.core.pylabtools from module matplotlib._pylab_helpers
299497 INFO: Excluding import 'PyQt4'
299503 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtGui
299503 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtSvg
299504 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtCore
299505 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4
299506 INFO: Excluding import 'gtk'
299513 INFO: Loading module hook "hook-jinja2.py"...
299528 INFO: Loading module hook "hook-jsonschema.py"...
299530 INFO: Loading module hook "hook-lib2to3.py"...
299533 INFO: Loading module hook "hook-matplotlib.backends.py"...
300070 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
300492 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
300770 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
301176 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
301630 INFO:   Matplotlib backend "Qt4Agg": added
302106 INFO:   Matplotlib backend "Qt5Agg": added
302541 INFO:   Matplotlib backend "TkAgg": added
303002 INFO:   Matplotlib backend "WX": added
303477 INFO:   Matplotlib backend "WXAgg": added
303750 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
304150 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
305026 INFO:   Matplotlib backend "WebAgg": added
306072 INFO:   Matplotlib backend "nbAgg": added
306482 INFO:   Matplotlib backend "agg": added
306773 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
307074 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
307477 INFO:   Matplotlib backend "pdf": added
307967 INFO:   Matplotlib backend "pgf": added
308370 INFO:   Matplotlib backend "ps": added
308781 INFO:   Matplotlib backend "svg": added
309177 INFO:   Matplotlib backend "template": added
309522 INFO: Loading module hook "hook-matplotlib.py"...
309805 INFO: Loading module hook "hook-numpy.core.py"...
309869 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
309871 INFO: Loading module hook "hook-PIL.Image.py"...
310228 INFO: Loading module hook "hook-PIL.py"...
310231 INFO: Excluding import 'PySide'
310233 WARNING:   Removing import PIL.ImageQt from module PySide.QtGui
310234 WARNING:   Removing import PIL.ImageQt from module PySide.QtCore
310235 INFO: Excluding import 'tkinter'
310239 WARNING:   Removing import PIL.ImageTk from module tkinter
310239 INFO: Excluding import 'PyQt5'
310242 WARNING:   Removing import PIL.ImageQt from module PyQt5
310243 INFO: Excluding import 'PyQt4'
310245 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtGui
310246 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtCore
310247 INFO: Import to be excluded not found: 'FixTk'
310247 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
310250 INFO: Import to be excluded not found: 'FixTk'
310250 INFO: Excluding import 'tkinter'
310253 INFO: Loading module hook "hook-pkg_resources.py"...
311051 INFO: Loading module hook "hook-pycparser.py"...
311284 INFO: Loading module hook "hook-pydoc.py"...
311285 INFO: Loading module hook "hook-pygments.py"...
312913 INFO: Loading module hook "hook-PyQt4.py"...
312914 INFO: Loading module hook "hook-PyQt4.QtCore.py"...
312982 INFO: Loading module hook "hook-PyQt4.QtGui.py"...
313311 INFO: Loading module hook "hook-PyQt4.QtSvg.py"...
313312 INFO: Loading module hook "hook-PySide.py"...
313313 INFO: Loading module hook "hook-PySide.QtCore.py"...
313401 INFO: Loading module hook "hook-PySide.QtGui.py"...
313818 INFO: Loading module hook "hook-pythoncom.py"...
314197 INFO: Loading module hook "hook-pytz.py"...
314254 INFO: Loading module hook "hook-pywintypes.py"...
314627 INFO: Loading module hook "hook-requests.py"...
314630 INFO: Loading module hook "hook-setuptools.py"...
314632 INFO: Loading module hook "hook-sqlite3.py"...
314714 INFO: Loading module hook "hook-sysconfig.py"...
314715 INFO: Loading module hook "hook-win32com.py"...
314793 INFO: Loading module hook "hook-xml.dom.domreg.py"...
314794 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
314795 INFO: Loading module hook "hook-xml.py"...
314795 INFO: Loading module hook "hook-zmq.py"...
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\_msvccompiler.py", line 382, in compile
    self.spawn(args)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\_msvccompiler.py", line 501, in spawn
    return super().spawn(cmd)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cffi\ffiplatform.py", line 58, in _build
    dist.run_command('build_ext')
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\build_ext.py", line 77, in run
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\Cython\Distutils\old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\Cython\Distutils\old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\build_ext.py", line 198, in build_extension
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\distutils\_msvccompiler.py", line 384, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\zmq\backend\cffi\_cffi.py", line 95, in <module>
    runtime_library_dirs=cfg['runtime_library_dirs'],
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cffi\api.py", line 437, in verify
    lib = self.verifier.load_library()
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cffi\verifier.py", line 113, in load_library
    self._compile_module()
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cffi\verifier.py", line 210, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cffi\ffiplatform.py", line 29, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\cffi\ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 49, in <module>
  File "<string>", line 23, in walk_packages
  File "<string>", line 20, in walk_packages
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\zmq\backend\cffi\__init__.py", line 6, in <module>
    from zmq.backend.cffi import (constants, error, message, context, socket,
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\zmq\backend\cffi\constants.py", line 4, in <module>
    from ._cffi import C, c_constant_names
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\zmq\backend\cffi\_cffi.py", line 100, in <module>
    "Please check that you have zeromq headers and libraries." % e)
ImportError: PyZMQ CFFI backend couldn't find zeromq: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
Please check that you have zeromq headers and libraries.
316319 WARNING: Hidden import "open" not found!
316356 WARNING: Hidden import "file" not found!
316357 WARNING: Hidden import "file:" not found!
316358 WARNING: Hidden import "such" not found!
316359 WARNING: Hidden import "_cffi_ext.c" not found!
316360 WARNING: Hidden import "Cannot" not found!
316361 WARNING: Hidden import "'sys/un.h':" not found!
316362 WARNING: Hidden import "or" not found!
316422 WARNING: Hidden import "directory" not found!
316423 WARNING: Hidden import "No" not found!
316424 WARNING: Hidden import "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(209):" not found!
316425 WARNING: Hidden import "fatal" not found!
316426 WARNING: Hidden import "error" not found!
316427 WARNING: Hidden import "C1083:" not found!
316430 INFO: Excluding import 'zmq.libzmq'
316433 WARNING:   Removing import zmq from module zmq.libzmq
316435 INFO: Loading module hook "hook-_tkinter.py"...
316579 INFO: checking Tree
316579 INFO: Building Tree because out00-Tree.toc is non existent
316579 INFO: Building Tree out00-Tree.toc
316643 INFO: checking Tree
316643 INFO: Building Tree because out01-Tree.toc is non existent
316644 INFO: Building Tree out01-Tree.toc
317752 INFO: checking Tree
317752 INFO: Building Tree because out02-Tree.toc is non existent
317753 INFO: Building Tree out02-Tree.toc
317777 INFO: checking Tree
317778 INFO: Building Tree because out03-Tree.toc is non existent
317778 INFO: Building Tree out03-Tree.toc
317782 INFO: Looking for ctypes DLLs
317860 INFO: Analyzing run-time hooks ...
317875 INFO: Including run-time hook 'pyi_rth_traitlets.py'
317876 INFO: Including run-time hook 'pyi_rth_pkgres.py'
317878 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
317880 INFO: Including run-time hook 'pyi_rth__tkinter.py'
317881 INFO: Including run-time hook 'pyi_rth_cryptography.py'
317883 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
317884 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
317884 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
317886 INFO: Including run-time hook 'pyi_rth_mpldata.py'
317921 INFO: Looking for dynamic libraries
318188 WARNING: lib not found: tbb.dll dependency of C:\Users\user\AppData\Local\HyOc\py3\x64\Library\bin\mkl_tbb_thread.dll
320547 INFO: Looking for eggs
320548 INFO: Using Python library C:\Users\user\AppData\Local\HyOc\py3\x64\python36.dll
320549 INFO: Found binding redirects:
[]
320567 INFO: Warnings written to D:\test_data\h5py\build\h5py_pyinstaller\warnh5py_pyinstaller.txt
320708 INFO: checking PYZ
320708 INFO: Building PYZ because out00-PYZ.toc is non existent
320709 INFO: Building PYZ (ZlibArchive) D:\test_data\h5py\build\h5py_pyinstaller\out00-PYZ.pyz
325186 INFO: Building PYZ (ZlibArchive) D:\test_data\h5py\build\h5py_pyinstaller\out00-PYZ.pyz completed successfully.
325258 INFO: checking PKG
325259 INFO: Building PKG because out00-PKG.toc is non existent
325260 INFO: Building PKG (CArchive) out00-PKG.pkg
325304 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
325309 INFO: Bootloader C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
325309 INFO: checking EXE
325309 INFO: Building EXE because out00-EXE.toc is non existent
325310 INFO: Building EXE from out00-EXE.toc
325310 INFO: Appending archive to EXE D:\test_data\h5py\build\h5py_pyinstaller\h5py_pyinstaller.exe
325342 INFO: Building EXE from out00-EXE.toc completed successfully.
325353 INFO: checking COLLECT
325353 INFO: Building COLLECT because out00-COLLECT.toc is non existent
325353 INFO: Building COLLECT out00-COLLECT.toc
329207 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\pyqt4.qtcore.pyd
329207 INFO: Updating resource type 24 name 2 language 1033
329285 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\pyqt4.qtsvg.pyd
329286 INFO: Updating resource type 24 name 2 language 1033
329372 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\pyqt4.qtgui.pyd
329372 INFO: Updating resource type 24 name 2 language 1033
329469 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\pyside.qtsvg.pyd
329469 INFO: Updating resource type 24 name 2 language 1033
329557 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\cryptography.hazmat.bindings._constant_time.pyd
329558 INFO: Updating resource type 24 name 2 language 1033
329604 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\cryptography.hazmat.bindings._openssl.pyd
329605 INFO: Updating resource type 24 name 2 language 1033
329664 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\_tkinter.pyd
329665 INFO: Updating resource type 24 name 2 language 1033
330144 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\_elementtree.pyd
330144 INFO: Updating resource type 24 name 2 language 1033
330233 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\pil._imagingft.pyd
330233 INFO: Updating resource type 24 name 2 language 1033
330276 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\markupsafe._speedups.pyd
330276 INFO: Updating resource type 24 name 2 language 1033
330512 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\wx.siplib.pyd
330513 INFO: Updating resource type 24 name 2 language 1033
330595 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\wx._core.pyd
330595 INFO: Updating resource type 24 name 2 language 1033
330687 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\win32clipboard.pyd
330687 INFO: Updating resource type 24 name 2 language 1033
330744 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\_sqlite3.pyd
330745 INFO: Updating resource type 24 name 2 language 1033
331350 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\tk86t.dll
331351 INFO: Updating resource type 24 name 1 language 1033
331678 INFO: Updating manifest in C:\Users\user\AppData\Roaming\pyinstaller\bincache00_py36_64bit\sqlite3.dll
331679 INFO: Updating resource type 24 name 2 language 1033
338350 INFO: Building COLLECT out00-COLLECT.toc completed successfully.
```

When executing the one-folder frozen app:

```
D:\test_data\h5py>dist\h5py_pyinstaller\h5py_pyinstaller.exe
Traceback (most recent call last):
  File "h5py_pyinstaller.py", line 1, in <module>
    import h5py
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\h5py\__init__.py", line 34, in <module>
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "h5py\h5r.pxd", line 21, in init h5py._conv (D:\Build\h5py\h5py-2.7.0\h5py\_conv.c:7536)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "h5py\_objects.pxd", line 12, in init h5py.h5r (D:\Build\h5py\h5py-2.7.0\h5py\h5r.c:3222)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "h5py\_objects.pyx", line 1, in init h5py._objects (D:\Build\h5py\h5py-2.7.0\h5py\_objects.c:7748)
ModuleNotFoundError: No module named 'h5py.defs'
Failed to execute script h5py_pyinstaller
```

@xoviat let me know if you need something else!

**Comment by xoviat** [comment]
@giumas part of your problem arises from a corrupt python installation but part of the problem was indeed a PyInstaller failure. The latter part has been resolved (albeit in a less than optimal way) in the referenced PR.

**Comment by giumas** [comment]
@xoviat What does it mean "a corrupt python installation"? I would like to fix it, if I can.

**Comment by htgoebel** [comment]
@giumas Is this still an issue? Did you spot the "ImportError: PyZMQ CFFI backend couldn't find zeromq:"? I assume xoviat it referring to this error.

**Comment by giumas** [comment]
@xoviat : just tested on my machine with the latest development (https://github.com/pyinstaller/pyinstaller/commit/5dc9557c9d2a446ca0965d5946dbb88624a9bd94), and it worked! Thank you and feel free to close this ticket!

**Comment by xoviat** [comment]
Well of course it worked. The PR just adds a test.

**Comment by giumas** [comment]
I see it now! For the other issue (pyZMQ related), it is most likely gone since I have created a clean environment. Do you want to leave open this ticket?

**Comment by giumas** [comment]
Incidentally, I am getting something similar in this ticket: https://github.com/pyinstaller/pyinstaller/issues/1522

I have attempted to add the `_gdal` as hidden import, but no luck! My current solution is to manually copy the `_gdal.cp36-win_amd64.pyd` in the root of the frozen folder.

**Comment by xoviat** [comment]
@giumas That's #2578. Not sure why that one has not been merged yet.

**Comment by davidh-ssec** [comment]
@giumas @xoviat I just got back in to using pyinstaller and I was wondering the same thing about my PR (#2578). Looks like the tests are/were failing. I've asked for them to be restarted now so we'll see if they pass. Looks like they were failing because of an HTTP/requests/pip something non-pyinstaller related.

**Comment by Gletschr** [comment]
I solve this problem by manually adding:

import h5py.defs
import h5py.utils
import h5py.h5ac
import h5py._proxy

(Win 10, python 3.5.2 x64)
