### ISSUE TITLE
Subprocess receipt get error

### ISSUE THREAD

**Issue by ChenghaoQ** [pyinstaller/pyinstaller#2543]
Hello,

I get this error after packaging with pyinstaller subprocess recipe:

```
Traceback (most recent call last):
  File "test3.py", line 63, in <module>
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 711, in run
subprocess.CalledProcessError: Command '['python3', 'test4.py']' returned non-zero exit status 2
Failed to execute script test3
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

 here is my code:

test3.py
```

import subprocess
import os, os.path
import sys


def subprocess_args(include_stdout=True):

    if hasattr(subprocess, 'STARTUPINFO'):
 
        si = subprocess.STARTUPINFO()
        si.dwFlags |= subprocess.STARTF_USESHOWWINDOW
 
        env = os.environ
    else:
        si = None
        env = None


    if include_stdout:
        ret = {'stdout': subprocess.PIPE}
    else:
        ret = {}

    ret.update({'stdin': subprocess.PIPE,
                'stderr': subprocess.PIPE,
                'startupinfo': si,
                'env': env })
    return ret

 
if __name__ == '__main__':
    # Save the output from invoking Python to a text file. This is the only
    # option when running with ``--noconsole``.
    with open('out.txt', 'w') as f:
        try:
            
            txt = subprocess.check_output(['python3', 'test4.py'], #here is different from recipe subprocess
                                          **subprocess_args(False))
            f.write(txt.decode())
            print(txt)
        except OSError as e:
            f.write('Failed: ' + str(e))

```

test4.py

```
def main():

	print('this is a test')
	return 'test success'

main()
```

**Comment by ChenghaoQ** [comment]
solved:

txt = subprocess.check_output(['python3', sys._MEIPASS+os.sep+'test4.py'],

and copy test4.py into bundle.

**Comment by ChenghaoQ** [comment]
But why I cannot directly use the subprocess recipe

**Comment by xoviat** [comment]
> But why I cannot directly use the subprocess recipe

Anything called with the subprocess module that fails is not pyinstaller's fault. If you need multiprocessing functionality, then pyinstaller supports the multiprocessing module.
