### ISSUE TITLE
how i can fix this bug

### ISSUE THREAD

**Issue by devil67** [pyinstaller/pyinstaller#2553]
27 INFO: PyInstaller: 3.3.dev0+gbb9e52fb
27 INFO: Python: 2.7.13
27 INFO: Platform: Linux-4.9.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
28 INFO: wrote /home/kevin/Scaricati/idlex-1.13/prova/keylogger/keyloagger.spec
33 INFO: UPX is available.
34 INFO: Extending PYTHONPATH with paths
['/home/kevin/Scaricati/idlex-1.13/prova/keylogger',
 '/home/kevin/Scaricati/idlex-1.13/prova/keylogger']
35 INFO: checking Analysis
35 INFO: Building Analysis because out00-Analysis.toc is non existent
35 INFO: Initializing module dependency graph...
37 INFO: Initializing module graph hooks...
233 INFO: running Analysis out00-Analysis.toc
252 INFO: Caching module hooks...
258 INFO: Analyzing /home/kevin/Scaricati/idlex-1.13/prova/keylogger/keyloagger.py
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.3.dev0+gbb9e52fb', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 87, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 45, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 413, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/analysis.py", line 196, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1386, in run_script
    co_ast = compile(contents, pathname, 'exec', ast.PyCF_ONLY_AST, True)
  File "/home/kevin/Scaricati/idlex-1.13/prova/keylogger/keyloagger.py", line 10
    subprocess.call("copyexecutable_name + " %userprofile%\\", shell=True)
                                                                         ^
SyntaxError: unexpected character after line continuation character

**Comment by htgoebel** [comment]
This is a syntax error in your code.
