### ISSUE TITLE
IndexError tuple index out of range for python 3.6

### ISSUE THREAD

**Issue by davidh-ssec** [pyinstaller/pyinstaller#2570]
I understand python 3.6 isn't completely supported yet, but it also sounds like it should work all except idlelib which I'm not using. I've installed pyinstaller from the develop branch and get the following error...however it seems to produce a valid package on OSX.

```
956 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "/Users/davidh/anaconda/envs/sift_py36/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller', 'console_scripts', 'pyinstaller')()
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 50, in <module>
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/depend/analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 1501, in import_hook
    source_package, target_module_partname, level)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 1653, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/depend/analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 2040, in _safe_import_module
    module = self.findNode(module_name)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 1376, in findNode
    m = self._safe_import_hook(name, None, None).pop()
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 2270, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 1501, in import_hook
    source_package, target_module_partname, level)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 1653, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/depend/analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 2069, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 2159, in _load_module
    self._scan_code(m, co, co_ast)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 2577, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 2823, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/lib/modulegraph/modulegraph.py", line 2723, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

I added a print statement right above this line and it seems it's trying to use an index of `25864` in a tuple of length `39`. Any ideas what might be causing this? I'm willing to fix this issue myself if I can be pointed in the right direction. Thanks.

**Comment by davidh-ssec** [comment]
Sorry, looks like I didn't actually update to the newest develop...this error no longer exists.

**Comment by top1st** [comment]
Mr. davidh
Did you solve this problem. Please let me know how did you solve this problem?

**Comment by davidh-ssec** [comment]
@top1st As mentioned in my comment this has been fixed in the github repository. At least that was the case when I created this issue. I was using an old version of pyinstaller that didn't support python 3.6 and got this error. After installing from the master branch on github everything seemed to work fine (that's why the issue was closed and why I wrote the comment I did).

**Comment by htgoebel** [comment]
See https://github.com/pyinstaller/pyinstaller/issues/2522#issuecomment-297142057
