### ISSUE TITLE
pyinstaller crashes on Win10 64bit with python3.6.1 64bit

### ISSUE THREAD

**Issue by zhangn1985** [pyinstaller/pyinstaller#2601]
crashes on any py file, simple or complex.

you will get crash
```
pyinstaller 1.py
156 INFO: PyInstaller: 3.2.1
156 INFO: Python: 3.6.1
156 INFO: Platform: Windows-10-10.0.14393-SP0
171 INFO: wrote C:\Users\USER\aaa\1.spec
171 INFO: UPX is not available.
171 INFO: Extending PYTHONPATH with paths
['C:\\Users\\USER\\aaa', 'C:\\Users\\USER\\aaa']
171 INFO: checking Analysis
171 INFO: Building Analysis because out00-Analysis.toc is non existent
187 INFO: Initializing module dependency graph...
187 INFO: Initializing module graph hooks...
187 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\depend\analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "c:\users\USER\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

I have tried many python versions. only python34 works well.

**Comment by thiolliere** [comment]
pyinstaller.org: 
> PyInstaller works with Python 2.7 and 3.3—3.5.

however it should work with 3.5. Can you print the error for python35 ?

also I'm not sure but I think develop branch of pyisntaller works on 3.6 you can try it.
`python36 -m pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`

**Comment by leenyman** [comment]
Using the develop branch solved this issue for me
