### ISSUE TITLE
DistributionNotFound: The 'PyInstaller' distribution was not found

### ISSUE THREAD

**Issue by gwhenne** [pyinstaller/pyinstaller#2627]
Hi pyInstaller!

This error happens when running the app produced by pyinstaller. I'm using Python 2.7.13 with the latest PyInstaller==3.3.dev0+5fd013bfe.

It was working properly with pyInstaller 2.1, but it's time to upgrade!

Here is the error I get at runtime:
```
2017-05-23 11:00:40,059 - root - ERROR - An exception has occurred!
Traceback (most recent call last):
  File "AppStudio.py", line 418, in <module>
  File "wx-3.0-osx_cocoa/wx/_core.py", line 8628, in __init__
  File "wx-3.0-osx_cocoa/wx/_core.py", line 8196, in _BootstrapApp
  File "AppStudio.py", line 142, in OnInit
  File "/Users/george/.pyenv/versions/nsbx/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/PyInstaller/__init__.py", line 67, in <module>
  File "site-packages/pkg_resources/__init__.py", line 552, in get_distribution
  File "site-packages/pkg_resources/__init__.py", line 426, in get_provider
  File "site-packages/pkg_resources/__init__.py", line 968, in require
  File "site-packages/pkg_resources/__init__.py", line 854, in resolve
DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application
```
Any ideas?

**Comment by xoviat** [comment]
Are you importing PyInstaller in your program?

**Comment by gwhenne** [comment]
Yes. We use it to create installers for our users.

**Comment by xoviat** [comment]
I am personally doubtful that PyInstaller can freeze itself.

**Comment by gwhenne** [comment]
It was working in 2.1 (honest). How can we test this hypothesis?

**Comment by xoviat** [comment]
> It was working in 2.1 (honest). How can we test this hypothesis?

I have no doubt that it was. However, there was never a regression test for this and no one used it, so it was probably broken. We have an extensive test suite, so you can just add a test to tests/functional/test_libraries.py, and the test case will probably fail. But then what? Probably a few hours of work to get it working again, if you know what you're doing.

**Comment by gwhenne** [comment]
Looks like we can get around needing to to this. Closing...

**Comment by gwhenne** [comment]
(and thanks for pointing me in the right direction!)
