### ISSUE TITLE
SDL2 Errors

### ISSUE THREAD

**Issue by ErenPhayte** [pyinstaller/pyinstaller#2629]
Not sure if I need to publish this here or on Kivy but I get the following;
Doesn't seem to compile the SDL2 - so it works on my Mac, but when I port it to another mac it complains that it cant find SDL2 (sdl2 - Exception: SDL2: Unable to load image)

PyInstaller Bootloader 3.x
LOADER: executable is /****
LOADER: homepath is /****
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /****
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /****
LOADER [ARGV_EMU]: AppleEvent - processing...
LOADER [ARGV_EMU]: AppleEvent - installed handler.
LOADER [ARGV_EMU]: AppleEvent - calling ReceiveNextEvent
LOADER [ARGV_EMU]: ReceiveNextEvent got an eventLOADER [ARGV_EMU]: processing events failedLOADER [ARGV_EMU]: Out of the event loop.PyInstaller Bootloader 3.x
LOADER: executable is /****
LOADER: homepath is /****
LOADER: _MEIPASS2 is /****
LOADER: archivename is /****
LOADER: Already in the child - running user's code.
LOADER: Python library: //Python
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is //base_library.zip:/***
LOADER: sys.prefix is /***
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is //base_library.zip:/
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_kivy.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth_mplconfig.py
LOADER: Running pyi_rth_mpldata.py
LOADER: Running pyi_rth_gstreamer.py
LOADER: Running pyi_rth_enchant.py
LOADER: Running main.py
[INFO ] [Logger ] Record log in /*****/.kivy/logs/kivy_17-05-25_1.txt
[INFO ] [Kivy ] v1.10.0
[INFO ] [Python ] v3.6.1 (default, Apr 4 2017, 09:40:51)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO ] [Factory ] 194 symbols loaded
[INFO ] [Image ] Providers: img_sdl2, img_pil (img_imageio, img_tex, img_dds, img_ffpyplayer, img_gif ignored)
[INFO ] [Text ] Provider: sdl2
[INFO ] [OSC ] using for socket
[INFO ] [Window ] Provider: sdl2
[INFO ] [GL ] Using the "OpenGL ES 2" graphics system
[INFO ] [GL ] Backend used 
[INFO ] [GL ] OpenGL version <b'2.1 INTEL-10.14.73'>
[INFO ] [GL ] OpenGL vendor <b'Intel Inc.'>
[INFO ] [GL ] OpenGL renderer <b'Intel HD Graphics 5000 OpenGL Engine'>
[INFO ] [GL ] OpenGL parsed version: 2, 1
[INFO ] [GL ] Shading version <b'1.20'>
[INFO ] [GL ] Texture max size <16384>
[INFO ] [GL ] Texture max units <16>
[WARNING] [Image ] Unable to load image </****/kivy_install/data/glsl/default.png>
[CRITICAL] [Window ] Unable to find any valuable Window provider.
sdl2 - Exception: SDL2: Unable to load image
File "kivy/core/init.py", line 67, in core_select_lib
File "kivy/core/window/window_sdl2.py", line 140, in init
File "kivy/core/window/init.py", line 899, in init
File "kivy/core/window/window_sdl2.py", line 291, in create_window
File "kivy/core/window/init.py", line 1051, in create_window
File "kivy/graphics/instructions.pyx", line 758, in kivy.graphics.instructions.RenderContext.init (/private/var/folders/jp/q_vfmdm936d9crkpt15n80tdrn9266/T/pip-build-ff4oqvd4/kivy/kivy/graphics/instructions.c:12580)
File "kivy/core/image/init.py", line 538, in init
File "kivy/core/image/init.py", line 734, in _set_filename
File "kivy/core/image/init.py", line 435, in load
File "kivy/core/image/init.py", line 201, in init
File "kivy/core/image/img_sdl2.py", line 41, in load

Traceback (most recent call last):
File "/main.py", line 38, in 
File "", line 961, in _find_and_load
File "", line 950, in _find_and_load_unlocked
File "", line 655, in _load_unlocked
File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
File "/init.py", line 2, in 
Modules
File "", line 961, in _find_and_load
File "", line 950, in _find_and_load_unlocked
File "", line 655, in _load_unlocked
File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
File "***", line 3, in 
File "", line 961, in _find_and_load
File "", line 950, in _find_and_load_unlocked
File "", line 655, in _load_unlocked
File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
File "cairosvg/init.py", line 29, in 
-------------------
File "", line 961, in _find_and_load
File "", line 950, in _find_and_load_unlocked
File "", line 655, in _load_unlocked
File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
File "cairosvg/surface.py", line 24, in 
File "", line 961, in _find_and_load
File "", line 950, in _find_and_load_unlocked
File "", line 655, in _load_unlocked
File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
File "cairocffi/init.py", line 41, in 
touchring =
File "cairocffi/init.py", line 38, in dlopen

OSError: dlopen() failed to load a library: cairo / cairo-2
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /****

**Comment by htgoebel** [comment]
This looks like PyInstaller is not able to determine that cairocff tries to load the sdl2 shared lib. Please have a look at the respective area in cairocffi/init.py and try to determine what's going wrong here. Maybe we need a hook?

**Comment by ErenPhayte** [comment]
I disabled the CarioSVG module to see if it was that causing the problem. But it seems like its not related.

`
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_kivy.py
LOADER: Running pyi_rth_mplconfig.py
LOADER: Running pyi_rth_mpldata.py
LOADER: Running pyi_rth_gstreamer.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running main.py
[INFO   ] [Logger      ] Record log in /Users/brogale/.kivy/logs/kivy_17-05-29_1.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.1 (default, Apr  4 2017, 09:40:51) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO   ] [Factory     ] 194 symbols loaded
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[DEBUG  ] [Image       ] option <imageio> ignored by config
[DEBUG  ] [Image       ] option <tex> ignored by config
[DEBUG  ] [Image       ] option <dds> ignored by config
[DEBUG  ] [Image       ] option <ffpy> ignored by config
[DEBUG  ] [Image       ] option <gif> ignored by config
[INFO   ] [Image       ] Providers: img_sdl2, img_pil (img_imageio, img_tex, img_dds, img_ffpyplayer, img_gif ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[DEBUG  ] [GL          ] glShaderBinary is not available
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.8.77'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel HD Graphics 4000 OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load <***.app/Contents/MacOS/kivy_install/data/glsl/default.png>
[WARNING] [Image       ] Unable to load image <***.app/Contents/MacOS/kivy_install/data/glsl/default.png>
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - Exception: SDL2: Unable to load image
  File "kivy/core/__init__.py", line 67, in core_select_lib
  File "kivy/core/window/window_sdl2.py", line 140, in __init__
  File "kivy/core/window/__init__.py", line 899, in __init__
  File "kivy/core/window/window_sdl2.py", line 291, in create_window
  File "kivy/core/window/__init__.py", line 1051, in create_window
  File "kivy/graphics/instructions.pyx", line 758, in kivy.graphics.instructions.RenderContext.__init__ (/private/var/folders/jp/q_vfmdm936d9crkpt15n80tdrn9266/T/pip-build-ff4oqvd4/kivy/kivy/graphics/instructions.c:12580)
  File "kivy/core/image/__init__.py", line 538, in __init__
  File "kivy/core/image/__init__.py", line 734, in _set_filename
  File "kivy/core/image/__init__.py", line 435, in load
  File "kivy/core/image/__init__.py", line 201, in __init__
  File "kivy/core/image/img_sdl2.py", line 41, in load

[DEBUG  ] [App         ] Loading kv <./interface.kv>
 Traceback (most recent call last):
   File "/main.py", line 362, in <module>
   File "kivy/app.py", line 802, in run
   File "/main.py", line 346, in build
 AttributeError: 'NoneType' object has no attribute 'bind'
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for ****`
