### ISSUE TITLE
SyntaxError in setup.py under Python 3.2

### ISSUE THREAD

**Issue by JonathonReinhart** [pyinstaller/pyinstaller#2639]
```
$ python --version
Python 3.2.6
$ pip --version
pip 7.1.2 from /home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages (python 3.2)
9.81s$ pip install -r requirements.txt
Collecting pyinstaller (from -r requirements.txt (line 2))
  Downloading PyInstaller-3.2.1.tar.bz2 (2.4MB)
    100% |████████████████████████████████| 2.4MB 221kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-bc9yhm/pyinstaller/setup.py", line 44
        long_description = u'\n\n'.join([read('README.rst'),
                                 ^
    SyntaxError: invalid syntax
```

[Full log](https://travis-ci.org/JonathonReinhart/staticx/jobs/239564572)

**Comment by htgoebel** [comment]
Python 3.2 is not supported, see the manual and the website.

**Comment by JonathonReinhart** [comment]
I missed that. Sorry for the noise.
