### ISSUE TITLE
Problem with assemble on OS X and creating directories

### ISSUE THREAD

**Issue by CPrescher** [pyinstaller/pyinstaller#2670]
Hi,

I cannot create an executable on Mac OS X, even though the same spec file works without problem on  Linux and Windows. I get the following error:

```
50415 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
    File "/Users/clemens/miniconda3/bin/pyinstaller", line 11, in <module>
        load_entry_point('PyInstaller==3.3.dev0+gabfc8066', 'console_scripts', 'pyinstaller')()
    File "/Users/clemens/miniconda3/lib/python3.5/site-packages/PyInstaller/__main__.py", line 87, in run
        run_build(pyi_config, spec_file, **vars(args))
    File "/Users/clemens/miniconda3/lib/python3.5/site-packages/PyInstaller/__main__.py", line 45, in run_build
        PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
    File "/Users/clemens/miniconda3/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 788, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
    File "/Users/clemens/miniconda3/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 734, in build
        exec(text, spec_namespace)
    File "<string>", line 155, in <module>
    File "/Users/clemens/miniconda3/lib/python3.5/site-packages/PyInstaller/building/api.py", line 654, in __init__
        self.__postinit__()
    File "/Users/clemens/miniconda3/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
        self.assemble()
    File "/Users/clemens/miniconda3/lib/python3.5/site-packages/PyInstaller/building/api.py", line 682, in assemble
        os.makedirs(todir)
    File "/Users/clemens/miniconda3/lib/python3.5/os.py", line 241, in makedirs
        mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: 'dist/Dioptas_Mac64_0.3.1+375.g86c776e.dirty/dioptas/calibrants'

```

I am not sure what this means, it seems like pyinstaller is unable to create the new directories? dioptase/calibrants is a folder which I need to copy as an extra resource.

Tell me if you need more information! I am using the latest develop version of pyinstaller.

Best wishes,
Clemens

**Comment by CPrescher** [comment]
Dear all,

i finally found the problem and it was due to my filesystem, which was formatted as HFS+. Apparently this is by default case-insensitive, which did not let pyinstaller to create the dioptas directory because there was already a Dioptas file. 
Oddly this did not happen last year, but maybe apple sometimes changes the defaults.
