### ISSUE TITLE
report error when freeze APScheduler 

### ISSUE THREAD

**Issue by wanghaiqing2015** [pyinstaller/pyinstaller#2673]
APScheduler (3.3.1)
PyInstaller (3.2.1)

but apscheduler==3.0.6 , it worked .

--------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "flask-aim-angle/flask_aim/master.py", line 22, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "flask-aim-angle/flask_aim/controller/timing.py", line 24, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "flask-aim-angle/flask_aim/crontab/cron_handler.py", line 4, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/apscheduler/__init__.py", line 2, in <module>
  File "pkg_resources.py", line 371, in get_distribution
  File "pkg_resources.py", line 243, in get_provider
  File "pkg_resources.py", line 728, in require
  File "pkg_resources.py", line 626, in resolve
pkg_resources.DistributionNotFound: APScheduler
Failed to execute script master

**Comment by wanghaiqing2015** [comment]
http://www.cnblogs.com/ginponson/p/6079928.html
    https://github.com/pyinstaller/pyinstaller/issues/1713

**Comment by htgoebel** [comment]
Duplicate, see #1713
