### ISSUE TITLE
Pyrebase Crash

### ISSUE THREAD

**Issue by thiagofmam** [pyinstaller/pyinstaller#2689]
Hi,

I'm using the lib pyrebase to call services of the Google Firebase but when I make the package, it's impossible run. Exists some problem with the module Crypto.Hash._SHA256.

Below the code:
```
import sys

from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPainterPath, QPixmap
from PyQt5.QtGui import QPen
from PyQt5.QtWidgets import QApplication, QGraphicsPixmapItem
from PyQt5.QtWidgets import QGraphicsPathItem
from PyQt5.QtWidgets import QGraphicsScene
from PyQt5.QtWidgets import QGraphicsView
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtWidgets import QVBoxLayout
from PyQt5.QtWidgets import QWidget
import pyrebase
from PIL import Image
import io, base64


class MainWindow(QMainWindow):

    central_widget = None
    layout_container = None
    shape = None


    def __init__(self):
        super(MainWindow, self).__init__()
        self.central_widget = QWidget()
        self.layout_container = QVBoxLayout()
        self.central_widget.setLayout(self.layout_container)
        self.setCentralWidget(self.central_widget)
        self.gv = GraphicsView()
        self.layout_container.addWidget(self.gv)


class GraphicsView(QGraphicsView):

    start = None
    end = None
    item = None
    path = None

    def __init__(self):
        super(GraphicsView, self).__init__()
        self.setScene(QGraphicsScene())
        self.path = QPainterPath()
        self.item = GraphicsPathItem()
        self.scene().addItem(self.item)
        self.lastadded = None

        config = {
            "apiKey": "<MY-KEY>",
            "authDomain": "<MY-APP>.firebaseapp.com",
            "databaseURL": "https://<MY-APP>.firebaseio.com",
            "storageBucket": "<MY-APP>.appspot.com",
        }

        '''
            initialize app with config
        '''
        firebase = pyrebase.initialize_app(config)
        self.db = firebase.database()
        self.image_stream = self.db.child("drawings/").stream(self.stream_image)

    def stream_image(self, message):
        try:
            print(message["event"])  # put
            print(message["path"])  # /-K7yGTTEp7O549EzTYtI
            print(message["data"]["image"])  # {'title': 'Pyrebase', "body": "etc..."}
            data = message["data"]["image"]
            if self.lastadded:
                self.items().clear()
            im = Image.open(io.BytesIO(base64.b64decode(data.split(',')[1])))
            im.save("image.png")
            pixmap = QPixmap("image.png")
            self.lastadded = self.scene().addPixmap(pixmap)
            self.scene().update()

        except:
            print('exception  %s', sys.exc_info())

    def mousePressEvent(self, event):
        self.start = self.mapToScene(event.pos())
        self.path.moveTo(self.start)

    def mouseMoveEvent(self, event):
        self.end = self.mapToScene(event.pos())
        self.path.lineTo(self.end)
        self.start = self.end
        self.item.setPath(self.path)

class GraphicsPathItem(QGraphicsPathItem):

    def __init__(self):
        super(GraphicsPathItem, self).__init__()
        pen = QPen()
        pen.setColor(Qt.black)
        pen.setWidth(10)
        self.setPen(pen)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    mw = MainWindow()
    mw.show()
    sys.exit(app.exec_())
```

The error:
```
C:\Users\thiago\PycharmProjects\interact-ii\examples>.\FirebaseImage.exe
Traceback (most recent call last):
  File "FirebaseImage.py", line 13, in <module>
    import pyrebase
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\thiago\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyinstaller-3.3.dev0+ge5b43fe-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pyrebase\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\thiago\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyinstaller-3.3.dev0+ge5b43fe-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pyrebase\pyrebase.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\thiago\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyinstaller-3.3.dev0+ge5b43fe-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\oauth2client\service_account.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\thiago\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyinstaller-3.3.dev0+ge5b43fe-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\oauth2client\client.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\thiago\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyinstaller-3.3.dev0+ge5b43fe-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\oauth2client\crypt.py", line 55, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\thiago\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyinstaller-3.3.dev0+ge5b43fe-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\oauth2client\_pycrypto_crypt.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\thiago\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyinstaller-3.3.dev0+ge5b43fe-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Crypto\Hash\SHA256.py", line 55, in <module>
  File "site-packages\Crypto\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Hash._SHA256'
Failed to execute script FirebaseImage
```

**Comment by tallforasmurf** [comment]
Thank you for providing a reasonable size of test case. However I went to try it on Mac OS and had some problems: PIL.Image is not happy. Probably because I installed Pillow instead of PIL? But there are many versions of PIL. Please be specific about the OS, and which level of Python, PyQt, Pyrebase and PIL you are using.

**Comment by thiagofmam** [comment]
Thank you. I was installed pillow too.

S.O: Windows 10 64 bits

pip freeze:

click==6.7
colorama==0.3.9
crypto==1.4.1
Cython==0.25.2
display==1.0.0
Django==1.11.2
enum-compat==0.0.2
eventlet==0.21.0
Flask==0.12.2
Flask-SSE==0.2.1
future==0.16.0
gcloud==0.17.0
googleapis-common-protos==1.5.2
greenlet==0.4.12
httplib2==0.10.3
image==1.5.5
imutils==0.4.3
itsdangerous==0.24
Jinja2==2.9.6
jws==0.1.3
MarkupSafe==1.0
Naked==0.1.31
numpy==1.12.1
oauth2client==3.0.0
olefile==0.44
opencv-python==3.2.0.7
Pillow==4.1.1
protobuf==3.3.0
py==1.4.34
pyasn1==0.2.3
pyasn1-modules==0.0.9
PyAudio==0.2.11
pycryptodome==3.4.3
pyinstaller==3.3.dev0+ge5b43fe
pyocr==0.4.7
pypiwin32==220
PyQt5==5.8.2
PyQtChart==5.8
Pyrebase==3.0.27
pytesseract==0.1.6
pytest==3.1.3
python-engineio==1.5.4
python-firebase==1.2
python-jwt==2.0.1
python-socketio==1.7.5
pytz==2017.2
PyYAML==3.12
redis==2.10.5
requests==2.11.1
requests-toolbelt==0.7.0
rsa==3.4.2
shellescape==3.4.1
sip==4.19.2
six==1.10.0
sse==1.2
Werkzeug==0.12.2

**Comment by htgoebel** [comment]
This looks like https://github.com/thisbejim/Pyrebase/issues/157.

Please provide a **minimal** example and a **minimal** list of installed modules. The problem is not related to any QT stuff, so why does your example include the GUI code. Please
understand that we are not willing to spend our spare time to help you if you
are not willing to help on your side.

**Comment by thiagofmam** [comment]
Sorry my fault.

I only search in pyinstaller repo something with pyrebase.

Thank you.

**Comment by htgoebel** [comment]
I'll take this as "solved".

**Comment by ashkanz77** [comment]
I have the same problem. Here is the minimal code
import crypto
import sys
sys.modules['Crypto'] = crypto
import pyrebase
print('Hello')
