### ISSUE TITLE
Compile error in get_operation_arg_name

### ISSUE THREAD

**Issue by akbhat** [pyinstaller/pyinstaller#2706]
$ pyinstaller jcollect3.py --onefile --log=DEBUG
48 INFO: PyInstaller: 3.2.1
48 INFO: Python: 3.6.1
49 INFO: Platform: Linux-2.6.32-504.el6.x86_64-x86_64-with-centos-6.6-Final
49 INFO: wrote /home/abhat/Desktop/jcollect3/jcollect3.spec
49 DEBUG: Testing for UPX ...
54 INFO: UPX is not available.
57 DEBUG: script: /home/abhat/Desktop/jcollect3/jcollect3.py
58 INFO: Extending PYTHONPATH with paths
['/home/abhat/Desktop/jcollect3', '/home/abhat/Desktop/jcollect3']
58 INFO: checking Analysis
58 INFO: Building Analysis because out00-Analysis.toc is non existent
58 INFO: Initializing module dependency graph...
59 INFO: Initializing module graph hooks...
60 INFO: Analyzing base_library.zip ...
61 DEBUG: Collecting submodules for encodings
118 DEBUG: collect_submodules - Found submodules: {'encodings.punycode', 'encodings.mac_latin2', 'encodings.raw_unicode_escape', 'encodings.cp875', 'encodings.cp1251', 'encodings.mac_iceland', 'encodings.cp1256', 'encodings.base64_codec', 'encodings.ascii', 'encodings.cp273', 'encodings.ptcp154', 'encodings.cp1250', 'encodings.cp1006', 'encodings.utf_16', 'encodings.mbcs', 'encodings.cp1255', 'encodings.quopri_codec', 'encodings.cp1252', 'encodings.cp858', 'encodings.aliases', 'encodings.kz1048', 'encodings.cp1140', 'encodings.cp869', 'encodings.iso8859_1', 'encodings.cp437', 'encodings.mac_cyrillic', 'encodings.big5hkscs', 'encodings.cp862', 'encodings.koi8_u', 'encodings.iso8859_4', 'encodings.cp1125', 'encodings.cp861', 'encodings.utf_32', 'encodings.cp950', 'encodings.shift_jis_2004', 'encodings.hz', 'encodings.iso8859_3', 'encodings.cp949', 'encodings.cp932', 'encodings', 'encodings.charmap', 'encodings.utf_16_be', 'encodings.utf_32_le', 'encodings.cp500', 'encodings.bz2_codec', 'encodings.iso8859_6', 'encodings.palmos', 'encodings.mac_arabic', 'encodings.mac_romanian', 'encodings.mac_greek', 'encodings.oem', 'encodings.cp720', 'encodings.unicode_internal', 'encodings.euc_kr', 'encodings.gb18030', 'encodings.iso8859_5', 'encodings.koi8_r', 'encodings.mac_croatian', 'encodings.iso2022_kr', 'encodings.iso2022_jp_ext', 'encodings.mac_turkish', 'encodings.euc_jp', 'encodings.iso2022_jp_2', 'encodings.iso8859_8', 'encodings.cp65001', 'encodings.iso8859_2', 'encodings.johab', 'encodings.tis_620', 'encodings.cp860', 'encodings.iso8859_11', 'encodings.iso8859_14', 'encodings.latin_1', 'encodings.zlib_codec', 'encodings.uu_codec', 'encodings.utf_7', 'encodings.cp865', 'encodings.gbk', 'encodings.iso2022_jp_2004', 'encodings.hp_roman8', 'encodings.iso2022_jp_3', 'encodings.shift_jisx0213', 'encodings.big5', 'encodings.hex_codec', 'encodings.cp1257', 'encodings.cp874', 'encodings.mac_roman', 'encodings.cp1253', 'encodings.utf_32_be', 'encodings.iso8859_9', 'encodings.iso8859_16', 'encodings.rot_13', 'encodings.cp850', 'encodings.euc_jisx0213', 'encodings.cp1258', 'encodings.euc_jis_2004', 'encodings.iso2022_jp_1', 'encodings.cp775', 'encodings.utf_8', 'encodings.iso8859_10', 'encodings.cp1254', 'encodings.iso8859_7', 'encodings.cp855', 'encodings.idna', 'encodings.cp424', 'encodings.cp737', 'encodings.undefined', 'encodings.cp866', 'encodings.cp856', 'encodings.iso8859_13', 'encodings.utf_8_sig', 'encodings.cp857', 'encodings.iso8859_15', 'encodings.cp037', 'encodings.cp864', 'encodings.mac_farsi', 'encodings.cp1026', 'encodings.shift_jis', 'encodings.koi8_t', 'encodings.cp852', 'encodings.cp863', 'encodings.utf_16_le', 'encodings.unicode_escape', 'encodings.gb2312', 'encodings.mac_centeuro', 'encodings.iso2022_jp'}
119 DEBUG: Collecting submodules for collections
191 DEBUG: collect_submodules - Found submodules: {'collections.abc', 'collections'}
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range

**Comment by htgoebel** [comment]
PyInstaller 3.2.1 *does not* support Python 3.6. Either use Python 3.5 or the current development head, see http://www.pyinstaller.org/downloads.html.
