### ISSUE TITLE
PyInstaller\utils\win32\versioninfo.py struct.error: 

### ISSUE THREAD

**Issue by kojibhy** [pyinstaller/pyinstaller#2715]
When I try to add  --version-file=version.txt
get this error
Python3 windows 10 x64

15742 INFO: Bootloader c:\python34\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
15742 INFO: checking EXE
15743 INFO: Building EXE because out00-EXE.toc is non existent
15743 INFO: Building EXE from out00-EXE.toc
Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.3.dev0+db5e78848', 'console_scripts', 'pyinstaller')()
  File "c:\python34\lib\site-packages\PyInstaller\__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python34\lib\site-packages\PyInstaller\building\build_main.py", line 790, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python34\lib\site-packages\PyInstaller\building\build_main.py", line 736, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "c:\python34\lib\site-packages\PyInstaller\building\api.py", line 419, in __init__
    self.__postinit__()
  File "c:\python34\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\python34\lib\site-packages\PyInstaller\building\api.py", line 508, in assemble
    versioninfo.SetVersion(tmpnm, self.versrsrc)
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 555, in SetVersion
    win32api.UpdateResource(hdst, pefile.RESOURCE_TYPE['RT_VERSION'], 1, vs.toRaw())
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 174, in toRaw
    tmp = b''.join([kid.toRaw() for kid in self.kids ])
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 174, in <listcomp>
    tmp = b''.join([kid.toRaw() for kid in self.kids ])
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 349, in toRaw
    tmp = b''.join([kid.toRaw() for kid in self.kids])
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 349, in <listcomp>
    tmp = b''.join([kid.toRaw() for kid in self.kids])
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 394, in toRaw
    raw = kid.toRaw()
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 448, in toRaw
    + raw_val + b'\000\000')
struct.error: required argument is not an integer

**Comment by codewarrior0** [comment]
Looks like more Py3 fixes are needed in versioninfo.py due to the `/` operator always returning `float`. I'll take care of it.

**Comment by codewarrior0** [comment]
Should be fixed as of b20133197677b963a6a15eccd691318a5e4245b0

**Comment by htgoebel** [comment]
Thanks.
