### ISSUE TITLE
Problem with one librarie (branca) when run  .exe 

### ISSUE THREAD

**Issue by BlackPiouPiou** [pyinstaller/pyinstaller#2748]
* pyinstaller version : 3.2.1
* python version  : 2.7.7
* OS information : Windows 7 SP1 x86 
* Interpreter Python : WingIDE

* one of my multiple try for compilation : `pyinstaller --hidden-import=branca test.py`

Exact Problem : 

* Compilation it's OK, i have no error.
* When I running my test.exe the final message is 

> NotImplementedError Can't perform this operation for unregistered loader type

A minimal example program which shows the error  :
one line  :  `import branca`
script name :  test.py

I have a big program ProgramName.py who's work with my interpreter : WingIDE and work without problem. 
I use a libraire "folium" who's call "branca", "jinja2", etc
With the time i see it's branca who doesn't work with "pyinstaller" After compilation.

Using pyi-archive_viewer  and i see lines :

 'branca': (1, 49717L, 237),
 'branca.colormap': (0, 49954L, 9959),
 'branca.element': (0, 59913L, 7080),
 'branca.six': (0, 66993L, 374),
 'branca.utilities': (0, 67367L, 7167),

i try much more option for pyinstaller and i clean cache too... but it don't know why ?
Please, i hope  my explications are clear for you because I need your help...

**Comment by htgoebel** [comment]
>  NotImplementedError Can't perform this operation for unregistered loader type

Please provide the complete traceback.

**Comment by BlackPiouPiou** [comment]
I build my script "test.py" who contains one line : 

> import folium 

whithout option when I launched pyinstaller : 
> 
> c:\Temp>pyinstaller test.py
> 75 INFO: PyInstaller: 3.2.1
> 75 INFO: Python: 2.7.7
> 75 INFO: Platform: Windows-7-6.1.7601-SP1
> 75 INFO: wrote c:\Temp\test.spec
> 75 INFO: UPX is not available.
> 78 INFO: Extending PYTHONPATH with paths
> ['c:\\Temp', 'c:\\Temp']
> 78 INFO: checking Analysis
> 78 INFO: Building Analysis because out00-Analysis.toc is non existent
> 78 INFO: Initializing module dependency graph...
> 80 INFO: Initializing module graph hooks...
> 113 INFO: running Analysis out00-Analysis.toc
> 116 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
>   required by c:\Python27\python.exe
> 180 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1f
> c8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
> 180 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1f
> c8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
> 182 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1f
> c8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
> 242 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.307
> 29.4940_none ...
> 243 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8
> b3b9a1e18e3b_9.0.30729.4940_none_50916076bcb9a742.manifest
> 243 INFO: Searching for file msvcr90.dll
> 245 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9
> .0.30729.4940_none_50916076bcb9a742\msvcr90.dll
> 246 INFO: Searching for file msvcp90.dll
> 249 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9
> .0.30729.4940_none_50916076bcb9a742\msvcp90.dll
> 252 INFO: Searching for file msvcm90.dll
> 253 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9
> .0.30729.4940_none_50916076bcb9a742\msvcm90.dll
> 312 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1f
> c8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
> 314 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1f
> c8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
> 315 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1f
> c8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
> 317 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0,
> 30729, 4940)
> 373 INFO: Caching module hooks...
> 376 INFO: Analyzing c:\Temp\test.py
> 1947 INFO: Processing pre-find module path hook   distutils
> 2173 INFO: Processing pre-safe import module hook   _xmlplus
> 2399 INFO: Loading module hooks...
> 2399 INFO: Loading module hook "hook-distutils.py"...
> 2400 INFO: Loading module hook "hook-sysconfig.py"...
> 2401 INFO: Loading module hook "hook-xml.py"...
> 2443 INFO: Loading module hook "hook-jinja2.py"...
> 2463 INFO: Loading module hook "hook-httplib.py"...
> 2465 INFO: Loading module hook "hook-pkg_resources.py"...
> 2466 INFO: Loading module hook "hook-encodings.py"...
> 2830 INFO: checking Tree
> 2830 INFO: Building Tree because out00-Tree.toc is non existent
> 2831 INFO: Building Tree out00-Tree.toc
> 2835 INFO: Looking for ctypes DLLs
> 2840 INFO: Analyzing run-time hooks ...
> 2843 INFO: Including run-time hook 'pyi_rth_pkgres.py'
> 2848 INFO: Looking for dynamic libraries
> 3139 INFO: Looking for eggs
> 3140 INFO: Using Python library C:\Windows\system32\python27.dll
> 3140 INFO: Found binding redirects:
> [BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVers
> ion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 4940), publicKeyToken=u'1fc8b3b9a
> 1e18e3b')]
> 3144 INFO: Warnings written to c:\Temp\build\test\warntest.txt
> 3187 INFO: checking PYZ
> 3187 INFO: Building PYZ because out00-PYZ.toc is non existent
> 3187 INFO: Building PYZ (ZlibArchive) c:\Temp\build\test\out00-PYZ.pyz
> 3569 INFO: Building PYZ (ZlibArchive) c:\Temp\build\test\out00-PYZ.pyz completed
>  successfully.
> 3610 INFO: checking PKG
> 3611 INFO: Building PKG because out00-PKG.toc is non existent
> 3611 INFO: Building PKG (CArchive) out00-PKG.pkg
> 3634 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
> 3636 INFO: Bootloader c:\Python27\lib\site-packages\PyInstaller\bootloader\Windo
> ws-32bit\run.exe
> 3636 INFO: checking EXE
> 3637 INFO: Building EXE because out00-EXE.toc is non existent
> 3640 INFO: Building EXE from out00-EXE.toc
> 3641 INFO: Appending archive to EXE c:\Temp\build\test\test.exe
> 3646 INFO: Building EXE from out00-EXE.toc completed successfully.
> 3650 INFO: checking COLLECT
> 3650 INFO: Building COLLECT because out00-COLLECT.toc is non existent
> 3651 INFO: Building COLLECT out00-COLLECT.toc
> 3657 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 307
> 29, 4940)
> 3695 INFO: Building COLLECT out00-COLLECT.toc completed successfully.
> 

When I launch "test.exe" :
> 
> Traceback (most recent call last):
>   File "test.py", line 1, in <module>
>   File "c:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py
>  line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\folium\__init__.py", line 5, in <module>
>   File "c:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py
>  line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\branca\__init__.py", line 5, in <module>
>   File "c:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py
>  line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\branca\colormap.py", line 636, in <module>
>   File "site-packages\branca\colormap.py", line 623, in __init__
>   File "site-packages\branca\colormap.py", line 623, in <dictcomp>
>   File "site-packages\branca\colormap.py", line 379, in __init__
>   File "site-packages\branca\colormap.py", line 283, in __init__
>   File "site-packages\jinja2\environment.py", line 830, in get_template
>   File "site-packages\jinja2\environment.py", line 804, in _load_template
>   File "site-packages\jinja2\loaders.py", line 113, in load
>   File "site-packages\jinja2\loaders.py", line 234, in get_source
>   File "build\bdist.win32\egg\pkg_resources.py", line 1352, in has_resource
>   File "build\bdist.win32\egg\pkg_resources.py", line 1405, in _has
> NotImplementedError: Can't perform this operation for unregistered loader type
> Failed to execute script test

**Comment by htgoebel** [comment]
This looks like jinja2 using custom loaders which are not installed properly. See http://jinja.pocoo.org/docs/2.9/api/#basics, https://github.com/python-visualization/branca/blob/master/branca/colormap.py#L283 and https://github.com/python-visualization/branca/blob/master/branca/element.py#L20

**Comment by htgoebel** [comment]
I digged into this deeper and it looks like PyInstaller is returning a `NullProvider` – which is not good. I'll try to fix it.

**Comment by htgoebel** [comment]
Depends on #2717 to include the data-files.

**Comment by BlackPiouPiou** [comment]
Thank's for you help ! I'll try to understand jinja method :)
