### ISSUE TITLE
[grab_version.py] UnboundLocalError: local variable 'PyInstaller' referenced before assignment

### ISSUE THREAD

**Issue by cztomczak** [pyinstaller/pyinstaller#2769]
Using Pyinstall 3.2.1 on Window 7 with Python 2.7.13. PyInstaller is installed using PyPi and I am successfully making an exe package by typing `pyinstaller my.spec`.

When running `pyi_grab_version.exe` I get this error:
```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pyi-grab_version.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\PyInstaller\utils\cliutils\grab_version.py", line 19, in run
    PyInstaller.log.init()
UnboundLocalError: local variable 'PyInstaller' referenced before assignment
```

When running `grab_version.py` located in `utils/cliutils/` I get this error:
```
Traceback (most recent call last):
  File "grab_version.py", line 45, in <module>
    run()
  File "grab_version.py", line 19, in run
    PyInstaller.log.init()
UnboundLocalError: local variable 'PyInstaller' referenced before assignment
```

**Comment by cztomczak** [comment]
It works fine after changing it to:

```python
from PyInstaller import log


def run():
    log.init()
```

**Comment by cztomczak** [comment]
Looks like this is fixed in master by removing the call to log.init().
