### ISSUE TITLE
[set_version.py] UnboundLocalError: local variable 'PyInstaller' referenced before assignment

### ISSUE THREAD

**Issue by cztomczak** [pyinstaller/pyinstaller#2770]
Error when running `pyi-set_version.exe` tool.

Windows 7 / Python 2.7.13 / PyInstaller 3.2.1 / PyPi install.

Related Issue: #2769 ("[grab_version.py] UnboundLocalError: local variable 'PyInstaller' referenced before assignment").

Error:

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pyi-set_version.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\PyInstaller\utils\cliutils\set_version.py", line 17, in run
    PyInstaller.log.init()
UnboundLocalError: local variable 'PyInstaller' referenced before assignment
```

**Comment by cztomczak** [comment]
Looks like this is fixed in master by removing the call to log.init().
