### ISSUE TITLE
my first app couldn't run?

### ISSUE THREAD

**Issue by jekoie** [pyinstaller/pyinstaller#2771]
**app show  some tracking message "_MEIPASS2 is NULL", "No need to extract files to run;setting extractionpath to homepath", "Already in the child --running user's code", "Python library :\path\python27.dll" 
what happed to this,  someone can help me?**
```

D:\test\AutoTest>pyinstaller -y         --log-level=INFO        --add-data="database;database"  --add-data="module;module"      --add-data="image;image"        --add-data="pywifi;pywifi"      --add-data="sectionlog;sectionlog"      --add-data="seriallog;seriallog"        --add-data="setting;setting"    --add-data="tool;tool"  --add-data="win32wifi;win32wifi"        --noconsole     --clean         --debug         main.py
91 INFO: PyInstaller: 3.2.1
91 INFO: Python: 2.7.13
91 INFO: Platform: Windows-10-10.0.14393
91 INFO: wrote D:\test\AutoTest\main.spec
91 INFO: UPX is not available.
91 INFO: Removing temporary files and cleaning cache in C:\Users\Administrator\AppData\Roaming\pyinstaller
134 INFO: Extending PYTHONPATH with paths
['D:\\test\\AutoTest', 'D:\\test\\AutoTest']
134 INFO: checking Analysis
134 INFO: Building Analysis because out00-Analysis.toc is non existent
134 INFO: Initializing module dependency graph...
134 INFO: Initializing module graph hooks...
200 INFO: running Analysis out00-Analysis.toc
200 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
338 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
338 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
338 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
338 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.5054_none_f47f794af655c7b9.manifest
338 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.7523_none_f47c924cf6585df6.manifest
338 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
481 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9247_none ...
481 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35.manifest
491 INFO: Searching for file msvcr90.dll
491 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcr90.dll
491 INFO: Searching for file msvcp90.dll
491 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcp90.dll
491 INFO: Searching for file msvcm90.dll
491 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcm90.dll
631 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
631 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
631 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
631 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.5054_none_f47f794af655c7b9.manifest
631 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.7523_none_f47c924cf6585df6.manifest
631 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
631 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
710 INFO: Caching module hooks...
720 INFO: Analyzing D:\test\AutoTest\main.py
3713 INFO: Processing pre-safe import module hook   _xmlplus
3843 INFO: Processing pre-find module path hook   distutils
5267 INFO: Processing pre-safe import module hook   six.moves
10767 INFO: Loading module hooks...
10767 INFO: Loading module hook "hook-distutils.py"...
10769 INFO: Loading module hook "hook-sysconfig.py"...
10769 INFO: Loading module hook "hook-xml.py"...
10771 INFO: Loading module hook "hook-PIL.py"...
10773 INFO: Excluding import 'FixTk'
10775 INFO: Excluding import 'Tkinter'
10778 INFO: Excluding import 'PyQt5'
10779 WARNING:   Removing import PIL.ImageQt from module PyQt5
10781 INFO: Excluding import 'PySide'
10782 WARNING:   Removing import PIL.ImageQt from module PySide
10784 INFO: Excluding import 'PyQt4'
10786 WARNING:   Removing import PIL.ImageQt from module PyQt4
10787 INFO: Loading module hook "hook-wx.lib.activex.py"...
10950 INFO: Loading module hook "hook-openpyxl.py"...
10967 INFO: Loading module hook "hook-lxml.etree.py"...
10973 INFO: Loading module hook "hook-httplib.py"...
10975 INFO: Loading module hook "hook-_tkinter.py"...
11148 INFO: checking Tree
11149 INFO: Building Tree because out00-Tree.toc is non existent
11149 INFO: Building Tree out00-Tree.toc
11319 INFO: checking Tree
11320 INFO: Building Tree because out01-Tree.toc is non existent
11321 INFO: Building Tree out01-Tree.toc
11340 INFO: Loading module hook "hook-PIL.Image.py"...
11762 INFO: Loading module hook "hook-xml.dom.domreg.py"...
11879 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
11881 INFO: Excluding import 'FixTk'
11883 INFO: Excluding import 'Tkinter'
11884 INFO: Loading module hook "hook-encodings.py"...
12290 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
12291 INFO: Loading module hook "hook-wx.lib.pubsub.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "c:\python27\lib\site-packages\wx\lib\pubsub\core\arg1\__init__.py", line 16, in <module>
    raise RuntimeError(msg)
RuntimeError: Should not import this directly, used by pubsub.core if applicable
12555 WARNING: Hidden import "wx.lib.pubsub.core.publisher" not found!
12557 WARNING: Hidden import "wx.lib.pubsub.core.listenerimpl" not found!
12557 WARNING: Hidden import "wx.lib.pubsub.core.publishermixin" not found!
12558 WARNING: Hidden import "wx.lib.pubsub.core.datamsg" not found!
12558 WARNING: Hidden import "wx.lib.pubsub.core.topicargspecimpl" not found!
12559 WARNING: Hidden import "wx.lib.pubsub.core.topicmgrimpl" not found!
12590 INFO: Looking for ctypes DLLs
12594 WARNING: library coredll required via ctypes not found
12687 INFO: Analyzing run-time hooks ...
12694 INFO: Including run-time hook 'pyi_rth__tkinter.py'
12707 INFO: Looking for dynamic libraries
14459 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.8.0.microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.4053_none_516e2e610f48bda6.manifest
14460 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.8.0.microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.5592_none_517247830f45081d.manifest
14462 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.8.0.microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.6229_none_516aa8570f4c0657.manifest
14463 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.8.0.microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9268_none_516ec5f90f484987.manifest
14611 INFO: Searching for assembly x86_Microsoft.VC80.CRT_1fc8b3b9a1e18e3b_8.0.50727.9268_none ...
14613 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9268_none_d08e1538442a243e.manifest
14616 INFO: Searching for file msvcr80.dll
14616 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9268_none_d08e1538442a243e\msvcr80.dll
14617 INFO: Searching for file msvcp80.dll
14618 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9268_none_d08e1538442a243e\msvcp80.dll
14619 INFO: Searching for file msvcm80.dll
14620 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9268_none_d08e1538442a243e\msvcm80.dll
14762 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.8.0.microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.4053_none_516e2e610f48bda6.manifest
14763 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.8.0.microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.5592_none_517247830f45081d.manifest
14765 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.8.0.microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.6229_none_516aa8570f4c0657.manifest
14766 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.8.0.microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9268_none_516ec5f90f484987.manifest
14796 INFO: Adding redirect Microsoft.VC80.CRT version (8, 0, 50727, 762) -> (8, 0, 50727, 9268)
14963 INFO: Looking for eggs
14965 INFO: Using Python library C:\WINDOWS\system32\python27.dll
14966 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9247), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC80.CRT', language=None, arch=u'x86', oldVersion=(8, 0, 50727, 762), newVersion=(8, 0, 50727, 9268), publicKeyToken=u'1fc8b3b9a1e18e3b')]
14973 INFO: Warnings written to D:\test\AutoTest\build\main\warnmain.txt
15267 INFO: Appending 'datas' from .spec
15273 INFO: checking PYZ
15273 INFO: Building PYZ because out00-PYZ.toc is non existent
15274 INFO: Building PYZ (ZlibArchive) D:\test\AutoTest\build\main\out00-PYZ.pyz
16503 INFO: Building PYZ (ZlibArchive) D:\test\AutoTest\build\main\out00-PYZ.pyz completed successfully.
16644 INFO: checking PKG
16646 INFO: Building PKG because out00-PKG.toc is non existent
16646 INFO: Building PKG (CArchive) out00-PKG.pkg
16720 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
16723 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Windows-32bit\runw_d.exe
16723 INFO: checking EXE
16725 INFO: Building EXE because out00-EXE.toc is non existent
16725 INFO: Building EXE from out00-EXE.toc
16726 INFO: Appending archive to EXE D:\test\AutoTest\build\main\main.exe
16730 INFO: Building EXE from out00-EXE.toc completed successfully.
16739 INFO: checking COLLECT
16740 INFO: Building COLLECT because out00-COLLECT.toc is non existent
16742 INFO: Removing dir D:\test\AutoTest\dist\main
17105 INFO: Building COLLECT out00-COLLECT.toc
17116 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17169 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17171 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\python27.dll
17171 INFO: Updating resource type 24 name 2 language 1033
17225 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17226 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\wx._stc.pyd
17228 INFO: Updating resource type 24 name 2 language 1033
17279 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17279 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\wx._msw.pyd
17281 INFO: Updating resource type 24 name 2 language 1033
17402 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17404 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\wx._adv.pyd
17404 INFO: Updating resource type 24 name 2 language 1033
17416 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17417 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\wx.siplib.pyd
17419 INFO: Updating resource type 24 name 2 language 1033
17447 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17449 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\wx._core.pyd
17450 INFO: Updating resource type 24 name 2 language 1033
17555 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17557 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\tcl85.dll
17558 INFO: Updating resource type 24 name 2 language 1033
17582 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\tk85.dll
17584 INFO: Updating resource type 24 name 1 language 1033
17592 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
17593 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\tk85.dll
17594 INFO: Updating resource type 24 name 2 language 1033
17618 INFO: Redirecting Microsoft.VC80.CRT version (8, 0, 50727, 762) -> (8, 0, 50727, 9268)
17619 INFO: Updating manifest in C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py27_32bit\oci.dll
17620 INFO: Updating resource type 24 name 2 language 1033
19432 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

```

**Comment by htgoebel** [comment]
The best way to find what is going on is to look at
>  File "c:\python27\lib\site-packages\wx\lib\pubsub\core\arg1\__init__.py", line 16.
