### ISSUE TITLE
Wine + Python 3.5 or 3.6 + Numpy

### ISSUE THREAD

**Issue by philwinder** [pyinstaller/pyinstaller#2797]
**Versions**

- Pyinstaller `3.2.1` or master
- Python `3.5.x` and above
- Wine: wine-devel

**Recrate**

- Any linux, docker, VM, etc.
- Install wine-devel
- Install pyinstaller
- pip install numpy

Example python:
```
import numpy as np
a = np.array([1, 2, 3])
print(a)
```

***Result***

It builds fine. But doesn't work when you execute it.

Executable output after building with `pyinstaller --debug test.py`:

```
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\winderresearch\test\test\test.exe
LOADER: homepath is C:\Users\winderresearch\test\test
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\winderresearch\test\test\test.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\Users\winderresearch\test\test)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\Users\winderresearch\test\test\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Users\winderresearch\test\test\base_library.zip;C:\Users\winderresearch\test\test
LOADER: sys.prefix is C:\Users\winderresearch\test\test
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\winderresearch\test\test\base_library.zip;C:\Users\winderresearch\test\test
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_win32comgenpy.py
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_win32comgenpy.py", line 47, in <module>
  File "c:\Python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\win32com\__init__.py", line 5, in <module>
  File "c:\Python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 573, in load_module
ImportError: DLL load failed: %1 is not a valid Win32 application.
Failed to execute script pyi_rth_win32comgenpy
```

**Workaround**

The only way I've been able to fix this is by downgrading python to `3.4.x`, then everything works fine.

**What I've tried**

Different versions of `3.5.x`. Downloading the mkl versions of the windows binaries. Including lots of other libraries that didn't seem to make a difference. Different wine distributions. Different OS's. Different versions of pyinstaller.

**Comment by xoviat** [comment]
The cause is pywin32, which is currently horribly broken. If you edit `pyi_rth_win32comgenpy` to wrap line 47 in a try...except ImportError block, is the problem resolved?

**Comment by xoviat** [comment]
I should clarify that this file is located in site-packages, so I would recommend using `setup.py develop` to work on PyInstaller source files.

**Comment by philwinder** [comment]
I've just tried my 3.4 workaround with matplot lib, and I get another similar error :-(. So consider that not a workaround.

Ok, I'll give that a try, thanks. Is there any documentation showing how to get a dev evironment setup? Especially notes for wine? I think that would involve installing gcc/clang inside wine, which sounds rather painful.

**Comment by xoviat** [comment]
Setting up a development environment for any python package is:

```
git clone [repo]
cd [repo]
pip install -e .
```

You can then edit the files and running the command "pyinstaller" will use the development tree.

**Comment by xoviat** [comment]
Actually it looks like you cannot load any Python extension. That's a much nastier issue.

**Comment by xoviat** [comment]
@philwinder Please try the develop branch and let us know whether you have the same problem.

**Comment by philwinder** [comment]
Just tested. Both 3.2.1 and develop branch are exactly the same.

I've also tested with standard numpy and matplotlib and with:

`RUN pip install --ignore-installed http://www.silx.org/pub/wheelhouse/numpy-1.13.1+mkl-cp34-cp34m-win32.whl http://www.silx.org/pub/wheelhouse/matplotlib-1.5.2-cp34-cp34m-win32.whl`

The super special windows versions.

All give the same error after importing matplotlib (specifically, `image` from matplotlib, possibly others):

```
[4780] LOADER: Running pyi_rth_mplconfig.py
[4780] LOADER: Running pyi_rth_mpldata.py
[4780] LOADER: Running engtool.py
Traceback (most recent call last):
  File "engtool.py", line 11, in <module>
  File "Z:\src\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "fds_mask.py", line 3, in <module>
  File "Z:\src\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\matplotlib\image.py", line 20, in <module>
  File "Z:\src\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\matplotlib\artist.py", line 14, in <module>
  File "Z:\src\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\matplotlib\transforms.py", line 39, in <module>
  File "Z:\src\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

Thanks for your help. Any other ideas?

**Comment by xoviat** [comment]
The failing method is internal Python so you need to put strace on it.

**Comment by htgoebel** [comment]
[File "site-packages\matplotlib\transforms.py", line 39](https://github.com/matplotlib/matplotlib/blob/v1.5.2/lib/matplotlib/transforms.py#L39) reads `from matplotlib._path import …`

1. Please verify you can `import matplotlib._path` in your environment
2. Try to reproduce this error using a minimal script which is just `import matplotlib._path` – this also simplifies `strace`-ing.

**Comment by scmales** [comment]
`pip install pywin32==224`   (not 225)  may solve the problem!
