### ISSUE TITLE
Django: AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'

### ISSUE THREAD

**Issue by renatobellotti** [pyinstaller/pyinstaller#2808]
I have tried to run pyinstaller on my project (https://github.com/renatobellotti/FreeRun-Desktop) using the command:
```pyinstaller --debug --clean --onedir --name=freerun_desktop freerun_desktop/manage.py```
I was not able to run the file ```dist/freerun_desktop/freerun_desktop``` because of the following error:
```*** Error in `./freerun_desktop': double free or corruption (out): 0x00007f383c505030 ***```

The output of pyinstall during the build was:
```49 INFO: PyInstaller: 3.3.dev0+2d5898c41
49 INFO: Python: 3.6.2
50 INFO: Platform: Linux-4.12.9-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six
50 INFO: wrote /home/renato/programming/freerun_desktop/freerun_desktop.spec
52 INFO: UPX is not available.
52 INFO: Removing temporary files and cleaning cache in /home/renato/.cache/pyinstaller
54 INFO: Extending PYTHONPATH with paths
['/home/renato/programming/freerun_desktop/freerun_desktop',
 '/home/renato/programming/freerun_desktop']
54 INFO: checking Analysis
54 INFO: Building Analysis because out00-Analysis.toc is non existent
54 INFO: Initializing module dependency graph...
55 INFO: Initializing module graph hooks...
56 INFO: Analyzing base_library.zip ...
3204 INFO: running Analysis out00-Analysis.toc
3222 INFO: Caching module hooks...
3228 INFO: Analyzing /home/renato/programming/freerun_desktop/freerun_desktop/manage.py
4024 INFO: Processing pre-find module path hook   distutils
4025 INFO: distutils: retargeting to non-venv dir '/usr/lib64/python3.6/distutils'
6955 INFO: Loading module hooks...
6955 INFO: Loading module hook "hook-xml.py"...
7217 INFO: Loading module hook "hook-sysconfig.py"...
7225 INFO: Loading module hook "hook-pytz.py"...
7247 INFO: Loading module hook "hook-pydoc.py"...
7247 INFO: Loading module hook "hook-pkg_resources.py"...
7725 INFO: Processing pre-safe import module hook   win32com
7728 INFO: Loading module hook "hook-lib2to3.py"...
7729 INFO: Loading module hook "hook-encodings.py"...
7800 INFO: Loading module hook "hook-django.py"...
7801 INFO: Django root directory /home/renato/programming/freerun_desktop/freerun_desktop/freerun_desktop
Traceback (most recent call last):
  File "/home/renato/programming/freerun_desktop/.virtualenv/lib/python3.6/site-packages/PyInstaller/utils/hooks/subproc/django_import_finder.py", line 37, in <module>
    list(settings.TEMPLATE_LOADERS) + \
  File "/home/renato/programming/freerun_desktop/.virtualenv/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'
8423 INFO: Collecting Django migration scripts.
9593 INFO: Loading module hook "hook-django.db.backends.py"...
9673 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
10097 INFO: Loading module hook "hook-django.db.backends.oracle.base.py"...
10100 INFO: Loading module hook "hook-django.db.backends.mysql.base.py"...
10101 INFO: Loading module hook "hook-django.core.management.py"...
10857 INFO: Import to be excluded not found: 'matplotlib'
10857 INFO: Import to be excluded not found: 'tkinter'
10857 INFO: Excluding import 'IPython'
10859 INFO:   Removing import of IPython from module django.core.management.commands.shell
10859 INFO: Loading module hook "hook-django.core.mail.py"...
10930 INFO: Loading module hook "hook-django.core.cache.py"...
11036 INFO: Loading module hook "hook-distutils.py"...
11038 INFO: Loading module hook "hook-xml.dom.domreg.py"...
11039 INFO: Loading module hook "hook-sqlite3.py"...
11150 INFO: Looking for ctypes DLLs
11244 INFO: Analyzing run-time hooks ...
11252 INFO: Including run-time hook 'pyi_rth_django.py'
11254 INFO: Including run-time hook 'pyi_rth_pkgres.py'
11255 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
11283 INFO: Looking for dynamic libraries
11901 INFO: Looking for eggs
11901 INFO: Using Python library /lib64/libpython3.6m.so.1.0
11915 INFO: Warnings written to /home/renato/programming/freerun_desktop/build/freerun_desktop/warnfreerun_desktop.txt
12074 INFO: checking PYZ
12074 INFO: Building PYZ because out00-PYZ.toc is non existent
12074 INFO: Building PYZ (ZlibArchive) /home/renato/programming/freerun_desktop/build/freerun_desktop/out00-PYZ.pyz
12933 INFO: Building PYZ (ZlibArchive) /home/renato/programming/freerun_desktop/build/freerun_desktop/out00-PYZ.pyz completed successfully.
12963 INFO: checking PKG
12963 INFO: Building PKG because out00-PKG.toc is non existent
12963 INFO: Building PKG (CArchive) out00-PKG.pkg
12987 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
12989 INFO: Bootloader /home/renato/programming/freerun_desktop/.virtualenv/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
12989 INFO: checking EXE
12989 INFO: Building EXE because out00-EXE.toc is non existent
12989 INFO: Building EXE from out00-EXE.toc
12989 INFO: Appending archive to ELF section in EXE /home/renato/programming/freerun_desktop/build/freerun_desktop/freerun_desktop
13002 INFO: Building EXE from out00-EXE.toc completed successfully.
13014 INFO: checking COLLECT
13015 INFO: Building COLLECT because out00-COLLECT.toc is non existent
WARNING: The output directory "/home/renato/programming/freerun_desktop/dist/freerun_desktop" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
17255 INFO: Removing dir /home/renato/programming/freerun_desktop/dist/freerun_desktop
17477 INFO: Building COLLECT out00-COLLECT.toc
18127 INFO: Building COLLECT out00-COLLECT.toc completed successfully.```

The warn file is:
```missing module named 'multiprocessing.forking' - imported by /home/renato/programming/freerun_desktop/.virtualenv/lib/python3.6/site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py
missing module named multiprocessing.get_context - imported by multiprocessing, multiprocessing.pool, multiprocessing.managers, multiprocessing.sharedctypes
missing module named multiprocessing.TimeoutError - imported by multiprocessing, multiprocessing.pool
missing module named multiprocessing.BufferTooShort - imported by multiprocessing, multiprocessing.connection
missing module named multiprocessing.AuthenticationError - imported by multiprocessing, multiprocessing.connection
missing module named multiprocessing.set_start_method - imported by multiprocessing, multiprocessing.spawn
missing module named multiprocessing.get_start_method - imported by multiprocessing, multiprocessing.spawn
missing module named pyimod03_importers - imported by /home/renato/programming/freerun_desktop/.virtualenv/lib/python3.6/site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py
missing module named netbios - imported by uuid
missing module named win32wnet - imported by uuid
missing module named __builtin__ - imported by pkg_resources._vendor.pyparsing
missing module named ordereddict - imported by pkg_resources._vendor.pyparsing
missing module named 'pkg_resources.extern.pyparsing' - imported by pkg_resources._vendor.packaging.requirements, pkg_resources._vendor.packaging.markers
missing module named StringIO - imported by django.utils.six, pkg_resources._vendor.six
missing module named 'win32com.shell' - imported by pkg_resources._vendor.appdirs
missing module named 'com.sun' - imported by pkg_resources._vendor.appdirs
missing module named com - imported by pkg_resources._vendor.appdirs
missing module named win32api - imported by pkg_resources._vendor.appdirs
missing module named win32com - imported by pkg_resources._vendor.appdirs
missing module named __main__ - imported by pkg_resources
missing module named pkg_resources.extern.packaging - imported by pkg_resources.extern, pkg_resources
missing module named pkg_resources.extern.appdirs - imported by pkg_resources.extern, pkg_resources
missing module named 'pkg_resources.extern.six.moves' - imported by pkg_resources, pkg_resources._vendor.packaging.requirements
missing module named pkg_resources.extern.six - imported by pkg_resources.extern, pkg_resources
missing module named _systemrestart - imported by django.utils.autoreload
missing module named urlparse - imported by django.utils.http
missing module named cStringIO - imported by pytz.tzfile
missing module named copy_reg - imported by cStringIO
missing module named sets - imported by pytz.tzinfo
missing module named UserDict - imported by pytz.lazy
missing module named sqlparse - imported by django.db.backends.base.operations
missing module named 'MySQLdb.converters' - imported by django.db.backends.mysql.base, django.db.backends.mysql.schema
missing module named 'MySQLdb.constants' - imported by django.db.backends.mysql.base, django.db.backends.mysql.introspection
missing module named MySQLdb - imported by django.db.backends.mysql.base
missing module named 'psycopg2.extras' - imported by django.db.backends.postgresql.base, django.db.backends.postgresql.operations
missing module named 'psycopg2.extensions' - imported by django.db.backends.postgresql.base
missing module named psycopg2 - imported by django.db.backends.postgresql.base, django.db.backends.postgresql.schema
missing module named pysqlite2 - imported by django.db.backends.sqlite3.base
missing module named cx_Oracle - imported by django.db.backends.oracle.base, django.db.backends.oracle.introspection
missing module named pylibmc - imported by django.core.cache.backends.memcached
missing module named memcache - imported by django.core.cache.backends.memcached
missing module named jinja2 - imported by django.template.backends.jinja2, django.test.utils
missing module named UserList - imported by django.forms.utils
missing module named PIL - imported by django.core.validators, django.forms.fields, django.core.files.images, django.db.models.fields.files
missing module named django.db.models.DecimalField - imported by django.db.models, django.db.backends.oracle.functions
missing module named django.db.models.DurationField - imported by django.db.models, django.db.backends.oracle.functions
missing module named django.db.models.AutoField - imported by django.db.models, django.forms.models
missing module named pyinotify - imported by django.utils.autoreload
missing module named 'django.utils.six.moves' - imported by django.utils.encoding, django.urls.base, django.dispatch.dispatcher, django.utils.http, django.utils.html, django.utils.text, django.utils.html_parser, django.http.cookie, django.utils.crypto, django.http.multipartparser, django.http.request, django.templatetags.static, django.core.files.storage, django.contrib.staticfiles.storage, django.forms.widgets, django.middleware.csrf, django.utils.ipv6, django.core.validators, django.forms.fields, django.forms.formsets, django.db.models.lookups, django.db.models.base, django.http.response, django.utils.regex_helper, django.utils.autoreload, django.contrib.admin.templatetags.admin_urls, django.contrib.auth.decorators, django.contrib.auth.views, django.middleware.common, django.db.models.sql.compiler, django.db.backends.base.base, django.db.backends.base.creation, django.db.backends.oracle.creation, django.db.backends.sqlite3.creation, django.test.client, django.core.servers.basehttp, django.test.testcases, django.views.static, django.db.migrations.questioner, django.core.cache.backends.db, django.core.management.templates, django.core.management.commands.flush, django.core.management.commands.makemigrations, django.core.cache.backends.filebased, django.core.cache.backends.locmem
missing module named org - imported by pickle, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py
missing module named _winreg - imported by platform, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py, pkg_resources._vendor.appdirs
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py, unittest.mock
missing module named 'java.lang' - imported by platform, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py
missing module named winreg - imported by platform, mimetypes, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py, urllib.request
missing module named 'org.python' - imported by copy, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py, xml.sax
missing module named nt - imported by os, ntpath, shutil, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py
missing module named msvcrt - imported by subprocess, multiprocessing.spawn, multiprocessing.popen_spawn_win32, django.core.files.locks, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py, getpass
missing module named _winapi - imported by subprocess, multiprocessing.reduction, multiprocessing.connection, multiprocessing.heap, multiprocessing.popen_spawn_win32, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py
missing module named _dummy_threading - imported by dummy_threading, /home/renato/programming/freerun_desktop/freerun_desktop/manage.py
missing module named lxml - imported by gpxpy.parser
missing module named win32evtlog - imported by logging.handlers
missing module named win32evtlogutil - imported by logging.handlers
missing module named mock - imported by django.test
missing module named bpython - imported by django.core.management.commands.shell```

I am using the latest development version of pyinstaller. I guess the error blocks some hooks or something? I'm sorry if this is not a bug, but I thought the goal of this project was to bundle as much as possible out of the box...

**Comment by xoviat** [comment]
We don't support the latest version of django. Someone needs to submit a PR in order to implement support. Do you have time for this?

**Comment by renatobellotti** [comment]
I can take a look at it over the weekend. I'm not quite sure where to start. Do I just need to update the hook file and insert the new hidden imports?

**Comment by xoviat** [comment]
To set up a development environment, fork pyinstaller, and then:
```
git clone pyinstaller.git
cd pyinstaller
git checkout -b django
pip install -e .
```

Then you will need to look at the files in Pyinstaller/hooks and Pyinstaller/loader/rthooks and resolve the errors until it works. Just keep building and running the application until all of the errors are resolved. Then you can submit a PR with the changes.

**Comment by renatobellotti** [comment]
I've started working on the solution. Could it be that the settings were never properly set up? When I try to do this in the Python shell, I get an error message.
What I've done:
```python
import django
django.setup()
```
The error I get:
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/renato/programming/pyinstaller/pyinstaller/.virtualenv/lib/python3.6/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/renato/programming/pyinstaller/pyinstaller/.virtualenv/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/renato/programming/pyinstaller/pyinstaller/.virtualenv/lib/python3.6/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```
This makes debugging a bit cumbersome since you don't see what each setting contains. I think there might be bugs as well caused by this.
To get the path to the the correct settings file in ```PyInstaller/utils/hooks/subproc/django_import_finder.py```, I'd need to include django.py in ```PyInstaller/utils/hooks``` using:
```python
from .. import django
```
But that would overwrite the django module... Would it be ok to rename the file, or do you see a simpler way of including it?

**Comment by xoviat** [comment]
First, do not use relative import paths in any hook files. The hooks are not correctly imported; they are `exec`'ed, which means that you must use absolute import paths. Second, to include conflicting modules, Python has a simple solution:

```
from z import x as y
``

**Comment by renatobellotti** [comment]
I'm not sure if I understood you correctly. I've tried to use:
```python
import import pyinstaller.utils.hooks.django as dj
```
But this kills my python interpreter, saying I should specify a file... Or do you want me to use a construct like the one described in 
https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path/67692#67692? This would be a problem, because the absolute path of pyinstaller is not the same on every system.

**Comment by htgoebel** [comment]
`import import pyinstaller.utils.hooks.django as dj`

Syntax-Error: duplicate `import`.

For more information about writing hooks, please refer to the manual and have a look at other hooks.

**Comment by renatobellotti** [comment]
That's just a typo here in my post. Also, I just realized that the environment variable should be properly set in django.py, i. e. where django_import_finder is called. Therefore I actually don't need to import django.py.
As a general question, what is the reason that this script is not imported regularly, but its output is captured? This makes debugging quite cumbersome...

**Comment by htgoebel** [comment]
> As a general question, what is the reason that this script is not imported regularly, but its output is captured?

Which script you are talking about? Please have a look at the hooks section in the manual.

**Comment by renatobellotti** [comment]
I managed to get even less warnings than the orginal code, which, by the way, does not work when installed in a fresh virtualenv with Django 1.8. The server stops with the following error message:
```shell
Unhandled exception in thread started by <function wrapper at 0x7f77da762410>
Traceback (most recent call last):
  File "django/utils/autoreload.py", line 223, in wrapper
  File "django/core/management/commands/runserver.py", line 112, in inner_run
  File "django/core/management/commands/runserver.py", line 164, in check_migrations
  File "django/db/migrations/executor.py", line 19, in __init__
  File "django/db/migrations/loader.py", line 47, in __init__
  File "django/db/migrations/loader.py", line 174, in build_graph
  File "django/db/migrations/loader.py", line 100, in load_disk
  File "importlib/__init__.py", line 37, in import_module
ImportError: No module named 0001_initial
```
I've applied all migrations.

Concerning my changes:
My code still dies with a memory dump. There are no warnings in the shell, but the ```warntest.txt``` says:
```shell
missing module named 'multiprocessing.forking' - imported by /home/renato/programming/pyinstaller/pyinstaller/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py
missing module named multiprocessing.get_context - imported by multiprocessing, multiprocessing.pool, multiprocessing.managers, multiprocessing.sharedctypes
missing module named multiprocessing.TimeoutError - imported by multiprocessing, multiprocessing.pool
missing module named multiprocessing.BufferTooShort - imported by multiprocessing, multiprocessing.connection
missing module named multiprocessing.AuthenticationError - imported by multiprocessing, multiprocessing.connection
missing module named multiprocessing.get_start_method - imported by multiprocessing, multiprocessing.spawn
missing module named multiprocessing.set_start_method - imported by multiprocessing, multiprocessing.spawn
missing module named pyimod03_importers - imported by /home/renato/programming/pyinstaller/pyinstaller/PyInstaller/loader/rthooks/pyi_rth_pkgres.py
missing module named netbios - imported by uuid
missing module named win32wnet - imported by uuid
missing module named __builtin__ - imported by pkg_resources._vendor.pyparsing
missing module named ordereddict - imported by pkg_resources._vendor.pyparsing
missing module named StringIO - imported by django.utils.six, pkg_resources._vendor.six
missing module named 'win32com.shell' - imported by pkg_resources._vendor.appdirs
missing module named 'com.sun' - imported by pkg_resources._vendor.appdirs
missing module named com - imported by pkg_resources._vendor.appdirs
missing module named win32api - imported by pkg_resources._vendor.appdirs
missing module named win32com - imported by pkg_resources._vendor.appdirs
missing module named 'pkg_resources.extern.pyparsing' - imported by pkg_resources._vendor.packaging.markers, pkg_resources._vendor.packaging.requirements
missing module named __main__ - imported by pkg_resources
missing module named pkg_resources.extern.packaging - imported by pkg_resources.extern, pkg_resources
missing module named pkg_resources.extern.appdirs - imported by pkg_resources.extern, pkg_resources
missing module named 'pkg_resources.extern.six.moves' - imported by pkg_resources, pkg_resources._vendor.packaging.requirements
missing module named pkg_resources.extern.six - imported by pkg_resources.extern, pkg_resources
missing module named _systemrestart - imported by django.utils.autoreload
missing module named urlparse - imported by django.utils.http
missing module named cStringIO - imported by pytz.tzfile
missing module named copy_reg - imported by cStringIO
missing module named sets - imported by pytz.tzinfo
missing module named UserDict - imported by pytz.lazy
missing module named sqlparse - imported by django.db.backends.base.operations
missing module named 'MySQLdb.converters' - imported by django.db.backends.mysql.base, django.db.backends.mysql.schema
missing module named 'MySQLdb.constants' - imported by django.db.backends.mysql.base, django.db.backends.mysql.introspection
missing module named MySQLdb - imported by django.db.backends.mysql.base
missing module named 'psycopg2.extras' - imported by django.db.backends.postgresql.base, django.db.backends.postgresql.operations
missing module named 'psycopg2.extensions' - imported by django.db.backends.postgresql.base
missing module named psycopg2 - imported by django.db.backends.postgresql.base, django.db.backends.postgresql.schema
missing module named pysqlite2 - imported by django.db.backends.sqlite3.base
missing module named cx_Oracle - imported by django.db.backends.oracle.base, django.db.backends.oracle.introspection
missing module named pylibmc - imported by django.core.cache.backends.memcached
missing module named memcache - imported by django.core.cache.backends.memcached
missing module named jinja2 - imported by django.template.backends.jinja2, django.test.utils
missing module named UserList - imported by django.forms.utils
missing module named PIL - imported by django.core.validators, django.forms.fields, django.core.files.images, django.db.models.fields.files
missing module named django.db.models.DecimalField - imported by django.db.models, django.db.backends.oracle.functions
missing module named django.db.models.DurationField - imported by django.db.models, django.db.backends.oracle.functions
missing module named django.db.models.AutoField - imported by django.db.models, django.forms.models
missing module named pyinotify - imported by django.utils.autoreload
missing module named 'django.utils.six.moves' - imported by django.utils.encoding, django.urls.base, django.dispatch.dispatcher, django.utils.http, django.utils.html, django.utils.text, django.utils.html_parser, django.http.cookie, django.utils.crypto, django.http.multipartparser, django.http.request, django.templatetags.static, django.core.files.storage, django.contrib.staticfiles.storage, django.forms.widgets, django.middleware.csrf, django.utils.ipv6, django.core.validators, django.forms.fields, django.forms.formsets, django.db.models.lookups, django.db.models.base, django.http.response, django.utils.regex_helper, django.utils.autoreload, django.core.cache.backends.locmem, django.core.cache.backends.filebased, django.core.cache.backends.db, django.contrib.auth.decorators, django.contrib.auth.views, django.test.client, django.core.servers.basehttp, django.test.testcases, django.views.static, django.db.migrations.questioner, django.core.management.templates, django.core.management.commands.makemigrations, django.core.management.commands.flush, django.contrib.sessions.backends.cache, django.contrib.sessions.serializers, django.contrib.admin.templatetags.admin_urls, django.contrib.staticfiles.views, django.contrib.staticfiles.handlers, django.contrib.contenttypes.management.commands.remove_stale_contenttypes, django.contrib.auth.management.commands.createsuperuser, django.db.backends.base.creation, django.db.backends.sqlite3.creation, django.db.backends.base.base, django.contrib.staticfiles.management.commands.collectstatic, django.middleware.common, django.db.models.sql.compiler, django.db.backends.oracle.creation
excluded module named _frozen_importlib - imported by importlib, importlib.abc, /home/renato/test/simplest_django/mysite/manage.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, /home/renato/test/simplest_django/mysite/manage.py
missing module named _winreg - imported by platform, /home/renato/test/simplest_django/mysite/manage.py, pkg_resources._vendor.appdirs
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, /home/renato/test/simplest_django/mysite/manage.py, unittest.mock
missing module named 'java.lang' - imported by platform, /home/renato/test/simplest_django/mysite/manage.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, /home/renato/test/simplest_django/mysite/manage.py
missing module named msvcrt - imported by subprocess, multiprocessing.spawn, multiprocessing.popen_spawn_win32, django.core.files.locks, /home/renato/test/simplest_django/mysite/manage.py, getpass
missing module named _winapi - imported by subprocess, multiprocessing.reduction, multiprocessing.connection, multiprocessing.heap, multiprocessing.popen_spawn_win32, /home/renato/test/simplest_django/mysite/manage.py
missing module named winreg - imported by platform, mimetypes, /home/renato/test/simplest_django/mysite/manage.py, urllib.request
missing module named _dummy_threading - imported by dummy_threading, /home/renato/test/simplest_django/mysite/manage.py
missing module named nt - imported by os, ntpath, shutil, /home/renato/test/simplest_django/mysite/manage.py
missing module named 'org.python' - imported by copy, /home/renato/test/simplest_django/mysite/manage.py, xml.sax
missing module named org - imported by pickle, /home/renato/test/simplest_django/mysite/manage.py
missing module named mock - imported by django.test
missing module named 'selenium.common' - imported by django.contrib.admin.tests
missing module named 'selenium.webdriver' - imported by django.contrib.admin.tests
missing module named selenium - imported by django.contrib.admin.tests
missing module named win32evtlog - imported by logging.handlers
missing module named win32evtlogutil - imported by logging.handlers
missing module named bpython - imported by django.core.management.commands.shell
```
I don't know how I can debug this. My changes are in my forked repo, if anybody wants to take a look at it. I'm willing to work on this for a couple of days, but I don't have time to dive deep into the inner workings of Pyinstaller, sorry.
I think it wouldn't be a too bad idea to import ```django_import_finder.py``` as a regular module instead of running it in a separate process. You can't even run it on its own because the setup of Django is done elsewhere.

**Comment by grajsor** [comment]
*cackles gleefully* soon you will be a regular pyinstaller contributor,
it's amazing to see how it all began!

**Comment by renatobellotti** [comment]
Well, only time will show that... ;)
But seriously, what is the best approach to figure out where the crash comes from? I want to contribute, but I've no experience in analysing binary files, so I'd be very glad for some pointers where to start.

**Comment by The-Phi** [comment]
I could work on this too but I don't know a lot about the project. Any news about what it is which is not working in fact?

**Comment by htgoebel** [comment]
Somebody needs to provide proper hooks, see https://github.com/pyinstaller/pyinstaller/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+django.

**Comment by bwoodsend** [comment]
We no longer support `Django 1.x`. Please create a new issue if this persists in `django >= 2.0`.
