### ISSUE TITLE
package scrapy module error

### ISSUE THREAD

**Issue by FajunChen** [pyinstaller/pyinstaller#2819]
I have a program using `scrapy` to crawl some pages from the web, and have a `main_some.py` file as the program entry, which includes codes something like this

```shell
from scrapy.utils.project import get_project_settings
from scrapy.crawler import CrawlerProcess
...........

def crawl(uri):
    settings = get_project_settings()
    settings.set('FEED_FORMAT', 'jsonlines')
    settings.set('FEED_URI', uri)
    settings.set('LOG_FILE', './log.txt')

    process = CrawlerProcess(settings)
    process.crawl(SomeSpider)
    process.start()

    return uri

if __name__ == "__main__":
  ...
  crawl(some_uri)
  ...
```

A standalone executable file can be built successfully by the following commands

> pyinstaller -F main_some.py

However, when I want to run the executor under `dist/`, I got the following errors:

```shell
Traceback (most recent call last):
  File "main_some.py", line 6, in <module>
    from scrapy.utils.project import get_project_settings
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Users/fajun/miniconda3/envs/py35/lib/python3.5/site-packages/PyInstaller-3.3.dev0-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/scrapy/__init__.py", line 10, in <module>
  File "pkgutil.py", line 632, in get_data
  File "/Users/fajun/miniconda3/envs/py35/lib/python3.5/site-packages/PyInstaller-3.3.dev0-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 479, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/zh/0bzql5c134gg3_sss0_9t88r0000gn/T/_MEIXSD6o6/scrapy/VERSION'
[60006] Failed to execute script main_some
```
Indeed there is a trick to bypass the error by editing the `scrapy.__init__.py` file as follows:

```shell
import pkgutil
# comment the following two lines
#__version__ = pkgutil.get_data(__package__, 'VERSION').decode('ascii').strip()
#version_info = tuple(int(v) if v.isdigit() else v
                     for v in __version__.split('.'))
# add this new line
__version__ = 1.3.3
del pkgutil
```
After that, new exceptions occurs:

```shell
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/zh/0bzql5c134gg3_sss0_9t88r0000gn/T/_MEIM04stT/scrapy/mime.types'
```

It seems that all non-python files would not be found in the final executor.

Please help to fix it.

**Comment by Germey** [comment]
same error

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by panjunbing** [comment]
@zsweet you can try to edit `scrapy.__init__.py`:
```
......
# Scrapy version
import pkgutil
# __version__ = pkgutil.get_data(__package__, 'VERSION').decode('ascii').strip()
__version__ = "1.2.2"
version_info = tuple(int(v) if v.isdigit() else v
                     for v in __version__.split('.'))
del pkgutil
......
```

**Comment by anshad-tilt** [comment]
@FajunChen  Have you solved the issue ?

**Comment by anshadsm** [comment]
@FajunChen  you can copy and paste scrapy from virtual environment to dist(build) folder

**Comment by ShuaiW** [comment]
+1
