### ISSUE TITLE
ImportError: No module named UserList - future.standard_library.install_aliases()

### ISSUE THREAD

**Issue by Guts** [pyinstaller/pyinstaller#2820]
This is my detailed investigation about my [issue comment](https://github.com/pyinstaller/pyinstaller/issues/1935#issuecomment-328491699), which is occurring when [future module and specifically install_aliases method](http://python-future.org/standard_library_imports.html#aliased-imports) is used within a script to packaged.

I know that seems to be a duplicate of #2327, itself marked as duplicate of #1935 and similar to #1871, but I encountered the same issue using the latest develop version and I'm not able to reopen issues.

I tried to do my best to report the issue. Hope it helps.

**Environment**

Python 2.7.13 32 bits on Windows 8.1 with, inside a virtualenv:

- PyInstaller==3.3.dev0+a43a5d23d
- altgraph==0.14
- dis3==0.1.1
- macholib==1.8
- pefile==2017.9.3
- pypiwin32==219
- **future**==0.16.0

**Script to test**

Following stack trace, I suspected install_aliases() so I created a little script `pyinstaller_UserList.py` to test:

```py
# -*- coding: UTF-8 -*-
#!/usr/bin/env python
from __future__ import (absolute_import, print_function, unicode_literals)

# Python 2 and 3 compatibility
from future.standard_library import install_aliases
install_aliases()

from tkMessageBox import showinfo as info

# Standard library
import logging

print("Nice print dude!")
logging.debug("PyInstaller is working")

info(title="PyInstaller test",
     message="PyInstaller is working")
```

**Error message**

No error during packaging (see out_log.txt file) with command ```pyinstaller .\pyinstaller_UserList.spec -y --clean```

[out_log.txt](https://github.com/pyinstaller/pyinstaller/files/1296434/out_log.txt)

But launching the resulting executable from command line, I obtain:

```py
[7444] PyInstaller Bootloader 3.x
[7444] LOADER: executable is C:\Users\USER\Documents\GitHub\Perso\test\pyinstaller_UserList\dist\PyInstaller Test UserList Import\PyInst Test UserList.exe
[7444] LOADER: homepath is C:\Users\USER\Documents\GitHub\Perso\test\pyinstaller_UserList\dist\PyInstaller Test UserList Import
[7444] LOADER: _MEIPASS2 is NULL
[7444] LOADER: archivename is C:\Users\USER\Documents\GitHub\Perso\test\pyinstaller_UserList\dist\PyInstaller Test UserList Import\PyInst Test UserList.exe
[7444] LOADER: No need to extract files to run; setting extractionpath to homepath
[7444] LOADER: SetDllDirectory(C:\Users\USER\Documents\GitHub\Perso\test\pyinstaller_UserList\dist\PyInstaller Test UserList Import)
[7444] LOADER: Already in the child - running user's code.
[7444] LOADER: Python library: C:\Users\USER\Documents\GitHub\Perso\test\pyinstaller_UserList\dist\PyInstaller Test UserList Import\python27.dll
[7444] LOADER: Loaded functions from Python library.
[7444] LOADER: Manipulating environment (sys.path, sys.prefix)
[7444] LOADER: sys.prefix is C:\Users\JULIEN~1.MOU\DOCUME~1\GitHub\Perso\test\PYINST~1\dist\PYINST~1
[7444] LOADER: Setting runtime options
[7444] LOADER: Initializing python
[7444] LOADER: Overriding Python's sys.path
[7444] LOADER: Post-init sys.path is C:\Users\USER\Documents\GitHub\Perso\test\pyinstaller_UserList\dist\PyInstaller Test UserList Import
[7444] LOADER: Setting sys.argv
[7444] LOADER: setting sys._MEIPASS
[7444] LOADER: importing modules from CArchive
[7444] LOADER: extracted struct
[7444] LOADER: callfunction returned...
[7444] LOADER: extracted pyimod01_os_path
[7444] LOADER: callfunction returned...
[7444] LOADER: extracted pyimod02_archive
[7444] LOADER: callfunction returned...
[7444] LOADER: extracted pyimod03_importers
[7444] LOADER: callfunction returned...
[7444] LOADER: Installing PYZ archive with Python modules.
[7444] LOADER: PYZ archive: out00-PYZ.pyz
[7444] LOADER: Running pyiboot01_bootstrap.py
[7444] LOADER: Running pyi_rth__tkinter.py
[7444] LOADER: Running pyinstaller_UserList.py
Traceback (most recent call last):
  File "pyinstaller_UserList.py", line 23, in <module>
  File "site-packages\future\standard_library\__init__.py", line 457, in install_aliases
ImportError: No module named UserList
[7444] Failed to execute script pyinstaller_UserList
[7444] LOADER: OK.
[7444] LOADER: Cleaning up Python interpreter.
```

**Spec File**

```py
# -*- mode: python -*-

block_cipher = None

a = Analysis(['pyinstaller_UserList.py'],
             pathex=['C:\\Users\\USER\\Documents\\GitHub\\Perso\\test\\pyinstaller_UserList'],
             binaries=[],
             datas=[],
             hiddenimports=["future"],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)

pyz = PYZ(a.pure,
          a.zipped_data,
          cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='PyInst Test UserList',
          debug=True,
          strip=False,
          upx=False,
          console=True,
          windowed=True)

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               name='PyInstaller Test UserList Import'
               )

```

**Comment by Guts** [comment]
Found a similar problem with py2exe and cx_freeze but with old versions of future <0.12 and mine is up to date.

https://github.com/PythonCharmers/python-future/issues/31#issuecomment-33728277

**Comment by leniwiec16** [comment]
I encountered the same issue after making a standalone version of [Rekall 1.7.0RC1 Hurricane Ridge](https://github.com/google/rekall/releases). Tested under virtualenv with pyinstaller 3.3 from pip and future 0.16.0 and:
- Python 2.7.14 32 bit on Windows 7 x86
- Python 2.7.14 64 bit on Windows 10 x64

On both machines I get:
  File "site-packages\future\standard_library\__init__.py", line 457, in install_aliases
ImportError: No module named UserList
[3296] Failed to execute script rekal

Any workaround?

**Comment by scudette** [comment]
This can be worked around e.g. using https://github.com/google/aff4/commit/3e14543654a9776c6c95fc451dc7db22ea19f4d1 but I think the real fix is to add special support in pyinstaller to future.

**Comment by leniwiec16** [comment]
Thanks @scudette! It resolved the issue for me.

**Comment by olivyac** [comment]
Sorry I'm new to Python. How/where do you add the files linked by scudette to fix this?

**Comment by scudette** [comment]
@olivyac You just add this code anywhere in a python file which is imported  from the main script
```
 if 0:
     import UserList
     import UserString
     import UserDict
     import itertools
     import collections
     import future.backports.misc
     import commands
     import base64
     import __buildin__
     import math
     import reprlib
     import functools
     import re
     import subprocess
```
The code doesnt do anything but pyinstaller thinks these imports are needed and does not strip them from the final binary. There is probably a pyinstaller way to include these via a spec file but I tend to not maintain a pyinstaller spec file because its too complicated - it is better to just have code that you can run directly in pyinstaller and it works.

**Comment by olivyac** [comment]
I added this code to the beginning of the _init_.py file from site-packages\future\standard_library\ . However, I'm getting the same error. Was I supposed to add the code to pyinstaller?

**Comment by scudette** [comment]
@olivyac how are you building your binary? You should add it to the script you are building:
```
pyinstaller /path/to/my/script.py
```

**Comment by olivyac** [comment]
I'm not entirely sure. I am using py2exe to build my executable/bundle all the files necessary for the .exe file to work. So I'm not sure which module builds the binary.

**Comment by olivyac** [comment]
It worked, thanks!

**Comment by neherh** [comment]
@nat-goodspeed this makes sense; I attempt to 'import UserList' in my main.py file and it fixes that problem. However, when I use your hook and place that hook file by my main.py, the hook file is not recognized and the original error results.

spec file is in dir: /proj
main.py and hook-future.standard_library.py is in dir: /proj/proj1

command to run:
python -m PyInstaller --name proj1 --additional-hooks-dir=. proj1/main.py

Now I try to put your file by the spec file and still the error results. Can you be more specific as to where to place this file?

Thanks.

**Comment by bwoodsend** [comment]
I'm going to close this as no longer relevant since the world dropped support for Python 2 a long time ago so `futures` is obsolete.
