### ISSUE TITLE
ImportError: No module named msvc

### ISSUE THREAD

**Issue by piyushshri** [pyinstaller/pyinstaller#2824]
I am using Pyinstaller on Ubuntu to create a binary executable for my Python code. This code has a bunch of files and dependencies. One of them is tensorflow. The executable is getting created correctly but when I try to run it, I get the following error:

```
Traceback (most recent call last):
  File "detection_init.py", line 14, in <module>
    import lib.tensorboxDetector as tensorboxDetector
  File "/tmp/pip-build-EuLWEf/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "lib/tensorboxDetector.py", line 20, in <module>
    import tensorflow as tf
  File "/tmp/pip-build-EuLWEf/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "tensorflow/__init__.py", line 24, in <module>
  File "/tmp/pip-build-EuLWEf/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "tensorflow/python/__init__.py", line 104, in <module>
  File "/tmp/pip-build-EuLWEf/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "tensorflow/python/platform/test.py", line 57, in <module>
  File "/tmp/pip-build-EuLWEf/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "mock/__init__.py", line 2, in <module>
  File "/tmp/pip-build-EuLWEf/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "mock/mock.py", line 71, in <module>
  File "pbr/version.py", line 461, in semantic_version
  File "pbr/version.py", line 447, in _get_version_from_pkg_resources
  File "/tmp/pip-build-EuLWEf/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "pbr/packaging.py", line 32, in <module>
  File "/tmp/pip-build-EuLWEf/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "setuptools/__init__.py", line 160, in <module>
  File "setuptools/monkey.py", line 104, in patch_all
  File "setuptools/monkey.py", line 156, in patch_for_msvc_specialized_compiler
  File "importlib/__init__.py", line 37, in import_module
ImportError: No module named msvc
```
How can I resolve this error and run the file correctly?

**Comment by htgoebel** [comment]
```
  File "setuptools/monkey.py", line 104, in patch_all
  File "setuptools/monkey.py", line 156, in patch_for_msvc_specialized_compiler
  File "importlib/__init__.py", line 37, in import_module
```

Looks like setuptools tries to monkey-patch some (hardcoded) modules, one of which (of course) does not exist on Linux. Please have a look and setuptools/monkey.py, line 104 and line 156 what's going on here.

Which version of setuptools are you using? Did you try the most current one or a bit older one?

**Comment by piyushshri** [comment]
@htgoebel Thanks for your reply. I am using setuptools version 36.4.0, which I believe is the latest.
At line 156 of monkey.py, the following line of code is written:
```
msvc = import_module('setuptools.msvc')
```
This code is inside this function:
def patch_for_msvc_specialized_compiler():
 ```
    """
    Patch functions in distutils to use standalone Microsoft Visual C++
    compilers.
    """
    # import late to avoid circular imports on Python < 3.5
    msvc = import_module('setuptools.msvc')

    if platform.system() != 'Windows':
        # Compilers only availables on Microsoft Windows
        return
```

There is no file named setuptools.msvc in the same directory, however there is a file called msvc.py and maybe this is why the import error occurs. But I still don't know how to resolve it on my Ubuntu machine.

**Comment by htgoebel** [comment]
Argl! You did not follow the instruction in the issue template. Our problem is solved in the development version since April *last* year.

Thanks for wasting my time! NOT

**Comment by piyushshri** [comment]
Running with the dev version solved this problem. Sorry for wasting your time. I am very new to Pyinstaller and there is not much support available elsewhere. Thanks.

**Comment by LetsCodeCloud** [comment]
Hi, I am getting same problem on redhat 7.4, while installing Python flask module.
When you say installing with dev version, what does that means?

Thanks
Heera
