### ISSUE TITLE
Import error with module uvloop

### ISSUE THREAD

**Issue by akbhat** [pyinstaller/pyinstaller#2855]
Build log attached. Issue can be replicated with only import uvloop statement.

[build.log](https://github.com/pyinstaller/pyinstaller/files/1325827/build.log)
```
[@localhost]$ ./dist/test 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import uvloop
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/uvloop/__init__.py", line 7, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "uvloop/loop.pyx", line 32, in init uvloop.loop (uvloop/loop.c:129043)
ImportError: cannot import name _noop
```

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

We would appreciate if you'd submit a hook for this. See https://pyinstaller.readthedocs.org/en/latest/hooks.html for more information about how to implement hooks.
