### ISSUE TITLE
pyi 3.3 and freebsd: wscript fails

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#2861]
I used the same build script (Vagrantfile) as with pyi 3.2.1, but with 3.3, it fails:
```
==> freebsd64: HEAD is now at 4e8e0ff7... Finished release 3.3.
==> freebsd64: running install
==> freebsd64: running bdist_egg
==> freebsd64: running build_bootloader
==> freebsd64: Setting top to                           : 
==> freebsd64: /vagrant/borg/pyinstaller/bootloader 
==> freebsd64: Setting out to                           : 
==> freebsd64: /vagrant/borg/pyinstaller/bootloader/build 
==> freebsd64: Checking for 'clang' (C compiler)        : 
==> freebsd64: /usr/bin/clang 
==> freebsd64: Traceback (most recent call last):
==> freebsd64:   File "/vagrant/borg/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 122, in waf_entry_point
==> freebsd64:     run_commands()
==> freebsd64:   File "/vagrant/borg/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 183, in run_commands
==> freebsd64:     ctx=run_command(cmd_name)
==> freebsd64:   File "/vagrant/borg/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 174, in run_command
==> freebsd64:     ctx.execute()
==> freebsd64:   File "/vagrant/borg/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Configure.py", line 85, in execute
==> freebsd64:     super(ConfigurationContext,self).execute()
==> freebsd64:   File "/vagrant/borg/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 88, in execute
==> freebsd64:     self.recurse([os.path.dirname(g_module.root_path)])
==> freebsd64:   File "/vagrant/borg/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 129, in recurse
==> freebsd64:     user_function(self)
==> freebsd64:   File "/vagrant/borg/pyinstaller/bootloader/wscript", line 421, in configure
==> freebsd64:     DESTOS_TO_SYSTEM[ctx.env.DEST_OS])
==> freebsd64: KeyError: 'freebsd'
==> freebsd64: No precompiled bootloader found. Trying to compile it for you ...
==> freebsd64: ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.
```

With pyi 3.2.1 `python setup.py install` didn't run into this (either it had a precompiled bootloader or it built one), so I am asking myself whether this is an expected change with 3.3?

I was using python 3.6.2 and freebsd 10.3 64bit.

**Comment by ThomasWaldmann** [comment]
BTW, Debian Wheezy 32/64bit and OS X worked ok.

**Comment by htgoebel** [comment]
As you can see the wscript fails. This is not intended, but obviously too less freebsd users tested the new version. Please provide a pull-request.

**Comment by ThomasWaldmann** [comment]
@htgoebel guess you meant v3.3 label.

I'll have a look, but I am neither familiar with freebsd, nor with that code.

**Comment by ThomasWaldmann** [comment]
OK, I think I found the issue. PR coming soon.

**Comment by htgoebel** [comment]
> guess you meant v3.3 label.

Of course. thangs for the info.

**Comment by htgoebel** [comment]
Thanks for the fix
