### ISSUE TITLE
Suggestions on how to debug packaging PBR versioning error from tensorflow on OSX

### ISSUE THREAD

**Issue by bw4sz** [pyinstaller/pyinstaller#2868]
I am looking for suggestions from the maintainers on what might cause this error. I hope i've done enough debugging to give enough information.

I am packaging tensorflow on mac OSX, i have the pyinstaller dev branch installed, I've tried moving to a virtual environment, I've updated all packages, and the same code works on windows without a problem. I need a push in a direction. 

I opened a [stackoverflow](https://stackoverflow.com/questions/46369902/pbr-versioning-error-when-packing-tensorflow-with-pyinstaller
) question, but did not get any feedback

calling

```
pyinstaller -c --onedir DeepMeerkat.spec
```

on the following spec

```
# -*- mode: python -*-

block_cipher = None

a = Analysis(['/Users/Ben/Documents/DeepMeerkat/DeepMeerkat/main.py'],
             pathex=['/Users/ben/Documents/DeepMeerkat/DeepMeerkat/'],
             binaries=[],
             datas=[],
             hiddenimports=["google"],
             hookspath=[],
             runtime_hooks=[],
             excludes=[ 'enchant', 'twisted'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='main',
          debug=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe, Tree('/Users/ben/Documents/DeepMeerkat/DeepMeerkat'),
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='Lib')
app = BUNDLE(coll,
             name='main.app',
             icon='/Users/ben/Documents/DeepMeerkat/DeepMeerkat/images/thumbnail.png',
             bundle_identifier=None)
```

yields

```
Last login: Mon Sep 25 12:38:26 on ttys003
Bens-MacBook-Pro:~ ben$ /Users/ben/Documents/DeepMeerkat/Installer/dist/Lib/main ; exit;
Traceback (most recent call last):
  File "DeepMeerkat/main.py", line 7, in <module>
    import Meerkat
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "Meerkat.py", line 4, in <module>
    import Video
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "Video.py", line 12, in <module>
    import predict
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "predict.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/tensorflow/__init__.py", line 24, in <module>
    
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/tensorflow/python/__init__.py", line 107, in <module>
    
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/tensorflow/python/platform/test.py", line 60, in <module>
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/mock/__init__.py", line 2, in <module>
    
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/mock/mock.py", line 71, in <module>
  File "site-packages/pbr/version.py", line 461, in semantic_version
  File "site-packages/pbr/version.py", line 448, in _get_version_from_pkg_resources
  File "site-packages/pbr/packaging.py", line 755, in get_version
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mock was given, but was not able to be found.
[10750] Failed to execute script main
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Pyinstaller log
```
(env) Bens-MacBook-Pro:Installer ben$ bash Pyinstaller.sh 
27 INFO: PyInstaller: 3.4.dev0+54ed99110
27 INFO: Python: 2.7.10
33 INFO: Platform: Darwin-16.7.0-x86_64-i386-64bit
38 INFO: UPX is not available.
39 INFO: Extending PYTHONPATH with paths
['/Users/Ben/Documents/DeepMeerkat',
 '/Users/ben/Documents/DeepMeerkat/DeepMeerkat']
39 INFO: checking Analysis
39 INFO: Building Analysis because out00-Analysis.toc is non existent
39 INFO: Initializing module dependency graph...
41 INFO: Initializing module graph hooks...
91 INFO: running Analysis out00-Analysis.toc
95 INFO: Caching module hooks...
98 INFO: Analyzing /Users/Ben/Documents/DeepMeerkat/DeepMeerkat/main.py
3253 INFO: Processing pre-safe import module hook   _xmlplus
3384 INFO: Processing pre-find module path hook   distutils
3384 INFO: distutils: retargeting to non-venv dir '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils'
5248 INFO: Processing pre-find module path hook   site
5248 INFO: site: retargeting to fake-dir '/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/fake-modules'
8629 INFO: Processing pre-safe import module hook   six.moves
13529 INFO: Loading module hooks...
13529 INFO: Loading module hook "hook-distutils.py"...
13530 INFO: Loading module hook "hook-sysconfig.py"...
13530 INFO: Loading module hook "hook-xml.py"...
13531 INFO: Loading module hook "hook-httplib.py"...
13531 INFO: Loading module hook "hook-pydoc.py"...
13533 INFO: Excluding import 'Tkinter'
13534 INFO:   Removing import of Tkinter from module pydoc
13534 INFO: Loading module hook "hook-encodings.py"...
13966 INFO: Loading module hook "hook-_tkinter.py"...
13971 INFO: checking Tree
13971 INFO: Building Tree because out00-Tree.toc is non existent
13971 INFO: Building Tree out00-Tree.toc
14022 INFO: checking Tree
14022 INFO: Building Tree because out01-Tree.toc is non existent
14022 INFO: Building Tree out01-Tree.toc
14045 INFO: Loading module hook "hook-docutils.py"...
16400 INFO: Loading module hook "hook-kivy.py"...
[INFO   ] [Logger      ] Record log in /Users/ben/.kivy/logs/kivy_17-09-25_15.txt
16406 INFO: [Logger      ] Record log in /Users/ben/.kivy/logs/kivy_17-09-25_15.txt
[INFO   ] [Kivy        ] v1.10.0
16405 INFO: [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
16406 INFO: [Python      ] v2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
[INFO   ] [Factory     ] 194 symbols loaded
16407 INFO: [Factory     ] 194 symbols loaded
[INFO   ] [Logger      ] Record log in /Users/ben/.kivy/logs/kivy_17-09-25_16.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Logger      ] Record log in /Users/ben/.kivy/logs/kivy_17-09-25_17.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
[INFO   ] [AudioGstplayer] Using Gstreamer 1.12.2.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer, audio_avplayer ignored)
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Camera      ] Provider: avfoundation
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_nspaste'] ignored)
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <2.1 INTEL-10.25.17>
[INFO   ] [GL          ] OpenGL vendor <Intel Inc.>
[INFO   ] [GL          ] OpenGL renderer <Intel(R) Iris(TM) Graphics 650>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <1.20>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[CRITICAL] [Spelling    ] Unable to find any valuable Spelling provider.
enchant - ImportError: No module named enchant
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/kivy/core/spelling/spelling_enchant.py", line 6, in <module>
    import enchant

osxappkit - ImportError: No module named AppKit
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/kivy/core/spelling/spelling_osxappkit.py", line 16, in <module>
    from AppKit import NSSpellChecker, NSMakeRange

[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoGstplayer] Using Gstreamer 1.12.2.0
[INFO   ] [Video       ] Provider: gstplayer
18090 INFO: Excluding import 'Tkinter'
18097 INFO: Excluding import 'twisted'
18101 INFO:   Removing import of twisted from module kivy.support
18103 INFO: Excluding import '_tkinter'
18110 INFO: Loading module hook "hook-xml.dom.domreg.py"...
18111 INFO: Loading module hook "hook-pkg_resources.py"...
18329 INFO: Processing pre-safe import module hook   win32com
18563 INFO: Loading module hook "hook-cv2.py"...
18563 INFO: Loading module hook "hook-setuptools.py"...
18604 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
18605 INFO: Loading module hook "hook-numpy.core.py"...
18663 INFO: Loading module hook "hook-pygments.py"...
20229 INFO: Looking for ctypes DLLs
20270 WARNING: library libmtdev.so.1 required via ctypes not found
20287 INFO: Analyzing run-time hooks ...
20296 INFO: Including run-time hook 'pyi_rth__tkinter.py'
20297 INFO: Including run-time hook 'pyi_rth_kivy.py'
20298 INFO: Including run-time hook 'pyi_rth_pkgres.py'
20300 INFO: Including run-time hook 'pyi_rth_gstreamer.py'
20301 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
20325 INFO: Looking for dynamic libraries
20781 INFO: Looking for eggs
20781 INFO: Python library not in binary dependencies. Doing additional searching...
20785 INFO: Using Python library /Users/ben/Documents/DeepMeerkat/env/bin/../.Python
20793 INFO: Warnings written to /Users/ben/Documents/DeepMeerkat/Installer/build/DeepMeerkat/warnDeepMeerkat.txt
20924 INFO: Graph cross-reference written to /Users/ben/Documents/DeepMeerkat/Installer/build/DeepMeerkat/xref-DeepMeerkat.html
21430 INFO: checking PYZ
21430 INFO: Building PYZ because out00-PYZ.toc is non existent
21430 INFO: Building PYZ (ZlibArchive) /Users/ben/Documents/DeepMeerkat/Installer/build/DeepMeerkat/out00-PYZ.pyz
23290 INFO: Building PYZ (ZlibArchive) /Users/ben/Documents/DeepMeerkat/Installer/build/DeepMeerkat/out00-PYZ.pyz completed successfully.
23672 INFO: checking PKG
23672 INFO: Building PKG because out00-PKG.toc is non existent
23672 INFO: Building PKG (CArchive) out00-PKG.pkg
23695 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
23699 INFO: Bootloader /Users/ben/Documents/DeepMeerkat/env/lib/python2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
23699 INFO: checking EXE
23699 INFO: Building EXE because out00-EXE.toc is non existent
23699 INFO: Building EXE from out00-EXE.toc
23699 INFO: Appending archive to EXE /Users/ben/Documents/DeepMeerkat/Installer/build/DeepMeerkat/main
23709 INFO: Fixing EXE for code signing /Users/ben/Documents/DeepMeerkat/Installer/build/DeepMeerkat/main
23713 INFO: Building EXE from out00-EXE.toc completed successfully.
23717 INFO: checking Tree
23717 INFO: Building Tree because out02-Tree.toc is non existent
23717 INFO: Building Tree out02-Tree.toc
23727 INFO: checking COLLECT
23727 INFO: Building COLLECT because out00-COLLECT.toc is non existent
23728 INFO: Building COLLECT out00-COLLECT.toc
28440 INFO: Building COLLECT out00-COLLECT.toc completed successfully.
28578 INFO: checking BUNDLE
28578 INFO: Building BUNDLE because out00-BUNDLE.toc is non existent
28578 INFO: Building BUNDLE out00-BUNDLE.toc
32902 INFO: moving BUNDLE data files to Resource directory
```

The log looks almost identical to the windows log, which builds without a problem.

There is some discussion of this issue, but no reference to pyinstaller. Outside of pyinstaller it works fine

https://stackoverflow.com/questions/44858973/tensorflow-textsum-error-of-versioning
https://roaet.com/2017/02/10/problem-with-pbr-and-sdist-tarball/

**Comment by htgoebel** [comment]
Looks like you need to add some data file:
```
  File "site-packages/pbr/version.py", line 448, in _get_version_from_pkg_resources
```
 I suggest putting `import pdb ; pdb.set_trace()` somewhere before File "site-packages/pbr/version.py", line 461, in semantic_version and step through the code.

HTH.

**Comment by bw4sz** [comment]
For those watching, I'm closing this issue. After some debugging, It is clearly not a PBR problem, i think pyinstaller is struggling to grab tensorflow at all. Expanded here:

https://stackoverflow.com/questions/46369902/distributing-tensorflow-with-pyinstaller-on-macosx-what-is-tensorflow-internal

If I don't get an answer I'll post a new issue. Looks like tensorflow is not being grabbed. Given the importance of this packaging, I imagine I won't be alone on this issue.
