### ISSUE TITLE
Cannot load native module 'Crypto.Cipher._raw_ecb

### ISSUE THREAD

**Issue by TheOtherGuy** [pyinstaller/pyinstaller#2881]
I am using the latest development version `PyInstaller (3.4.dev0+3c87c135a)` on Windows 10 64 bit. Python version is `3.6.2` 64 bit.

My script uses one 3rd party module - [pysnmp](http://pysnmp.sourceforge.net/).
It appears to be correctly imported by Pyinstaller as I see many references to it when I run `pyi-archive_viewer.exe out00-PYZ.pyz`.
[pyi-archive view.txt](https://github.com/pyinstaller/pyinstaller/files/1341474/pyi-archive.view.txt)

Both exes that are compiled using `--onedir` or `--onefile` results in the same error messages shown below when I run the exe.

```
  Traceback (most recent call last):
    File "main.py", line 4, in <module>
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    
    File "c:\users\user3\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
      exec(bytecode, module.__dict__)
    File "site-packages\pysnmp\hlapi\__init__.py", line 10, in <module>
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "c:\users\user3\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
      exec(bytecode, module.__dict__)
    File "site-packages\pysnmp\hlapi\auth.py", line 7, in <module>
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "c:\users\user3\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
      exec(bytecode, module.__dict__)
    File "site-packages\pysnmp\entity\config.py", line 9, in <module>
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "c:\users\user3\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
      exec(bytecode, module.__dict__)
    File "site-packages\pysnmp\proto\secmod\rfc3414\__init__.py", line 7, in <module>
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "c:\users\user3\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
      exec(bytecode, module.__dict__)
    File "site-packages\pysnmp\proto\secmod\rfc3414\service.py", line 11, in <module>
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "c:\users\user3\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
      exec(bytecode, module.__dict__)
    File "site-packages\pysnmp\proto\secmod\rfc3414\priv\des.py", line 16, in <module>
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "c:\users\user3\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
      exec(bytecode, module.__dict__)
    File "site-packages\Crypto\Cipher\__init__.py", line 3, in <module>
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "c:\users\user3\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
      exec(bytecode, module.__dict__)
    File "site-packages\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
    File "site-packages\Crypto\Util\_raw_api.py", line 189, in load_pycryptodome_raw_lib
  OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'
  [19124] Failed to execute script main
```
[DEBUG output.txt](https://github.com/pyinstaller/pyinstaller/files/1341487/DEBUG.output.txt) , hopefully it helps.

Based on a similar issue #2125, a hook for cryptodome is the solution. However, it appears that the [hook](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-Cryptodome.py) is already in the development version of Pyinstaller I am using, hence it doesn't solve the issue.

**Comment by TheOtherGuy** [comment]
The error can be reproduced using a simple sample code [from pysnmp website itself](http://pysnmp.sourceforge.net/quick-start.html):

```
from pysnmp.hlapi import *

errorIndication, errorStatus, errorIndex, varBinds = next(
    getCmd(SnmpEngine(),
           CommunityData('public', mpModel=0),
           UdpTransportTarget(('demo.snmplabs.com', 161)),
           ContextData(),
           ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)))
)

if errorIndication:
    print(errorIndication)
elif errorStatus:
    print('%s at %s' % (errorStatus.prettyPrint(),
                        errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
else:
    for varBind in varBinds:
        print(' = '.join([x.prettyPrint() for x in varBind]))
```

**Comment by TheOtherGuy** [comment]
Resolved this issue.

Firstly, `pysnmp` uses `pycryptodome`, but it uses the drop-in replacement for the old `PyCrypto` library which is results in all its module files being stored under `Crypto` in `site-packages`.

The `pycryptodome` hook is for `pycryptodomex`, which is a library independent of the old PyCrypto. In this case, all modules are installed under the `Cryptodome` in `site-packages`.

In order to use the hook that is present in `Pyinstaller`, I changed all `Crypto` imports to `Cryptodome` imports in all `.py files` in `pysnmp` and installed `pycryptodomex` via `pip`. I then compiled all these modified `.py files` to `.pyc files` as required.

After doing all that, the existing error was replaced by `ImportError: cannot import name exval`.

In order to resolve this error, a custom spec file is required. Many thanks to [the contributors in this stackoverflow question.](https://stackoverflow.com/questions/32944919/pyinstaller-does-not-work-when-including-pysnmp) I modified their answer and here is the working spec file:

```
import PyInstaller.utils.hooks
block_cipher = None

x = Tree('C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages\\pysnmp\\smi\\mibs',prefix='pysnmp/smi/mibs')
y = Tree('C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages\\pysmi',prefix='pysmi')

a = Analysis(['main.py'],
             pathex=['D:\\username\\yourfolder'],
             binaries=[],
             datas=[],
             hiddenimports=PyInstaller.utils.hooks.collect_submodules('pysnmp'),
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='main',
          debug=False,
          strip=False,
          upx=True,
          console=True 
          )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               x,y,
               strip=False,
               upx=True,
               name='main')
```

Cheers.

**Comment by 7sam7** [comment]
hi @TheOtherGuy , I had the same issue as you did, but still I could not fix it, can you tell me more about changing all Crypto imports to Cryptodome imports in all .py files in pysnmp?
I couldn't find any imports in pysnmp that relates to Crypto, thanks!!!

**Comment by nrichardson31** [comment]
I have this same issue, and cant fix it (I'm quite new to this).  My script only references this:

from pysnmp.entity.rfc3413.oneliner import cmdgen

I cant see reference to crypto, doesn't appear to be mentioned in the pysnmp lib but i could be wrong.  Any hints greatly appreciated.

**Comment by 7sam7** [comment]
@nrichardson31 my reference is exactly the same as yours....

**Comment by TheOtherGuy** [comment]
Hi there, 

Search for the following 3 files in the `pysnmp` directory in `site-packages` :
- des3.py
- des.py
- aes.py

Next, for each of the .py files, compile them. One method is `python -m compileall des3.py`.

**Comment by nrichardson31** [comment]
Thanks, I have tried compiling these, then I've tried the custom hooks.  I still get the same error:

OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

I'm trying to find the mentions of crypto module in the Pyinstaller folder, cant seem to find any.  I will admit I'm somewhat stabbing wildly in the dark on this.

**Comment by 7sam7** [comment]
@nrichardson31 you need to find them in the pysnmp folder.

**Comment by 7sam7** [comment]
@TheOtherGuy fixed this issue, thanks a lot. bump into another error though, some import DLL error, will look into that.

**Comment by nrichardson31** [comment]
Thanks @TheOtherGuy I've followed all this, changed the crypto imports to cryptodome in the files listed and the error now seems to have gone.  I've just now got MIB import issue to get through...packaging up this SNMP is proving a battle!

**Comment by ImXron** [comment]
Thanks @TheOtherGuy @7sam7 and @nrichardson31 for all the info so far!

I'm looking into this error now:
```
File "site-packages\pysnmp\entity\engine.py", line 90, in __init__
File "site-packages\pysnmp\smi\builder.py", line 403, in importSymbols
pysnmp.smi.error.MibNotFoundError: No module __SNMP-FRAMEWORK-MIB

```
@nrichardson31 you mentioned you ran into a MIB import? Were you able to get that resolved?

Thanks again!

**Comment by nrichardson31** [comment]
Hi @ImXron I'm afraid I'm still working on this, if you solve it let me know :-)

**Comment by 7sam7** [comment]
@nrichardson31 @ImXron I also met this problem before, you just need to change the spec files the same as theotherguy's and it will work out fine!

**Comment by nrichardson31** [comment]
Success!  Very happy as this is sooo useful.  I made some real bad mistakes, it was messed up - calling the 2.7 pyinstaller.exe instead of 3.6.  2.7 wont work right?  I assume that was the issue anyway.  The only thing I noticed is that using the jolly fine custom spec above seems to negate the --onefile command, I'm sure i can work out why.

Thanks a lot folks!

**Comment by ImXron** [comment]
Wow you all are awesome! I wasn't specifying the spec file in the Pyinstaller command so it kept overwriting my changes to it ¯\_(ツ)_/¯

I'll also check and see why the spec file ignores the options passed to pyinstaller (-F -w -i icon.ico) and report back asap.

Thanks again for all the help!

**Comment by nrichardson31** [comment]
Just FYI to answer my problem above, I read the manual and it says if you use the custom spec it will not modify the spec file for the --onefile command and only include the options in the spec file, which is probably your issue @ImXron ?   Also "In one-file mode, there is no call to COLLECT, and the EXE instance receives all of the scripts, modules and binaries.".  So a "--onefile" version of @TheOtherGuy 's spec file is below:

...
import PyInstaller.utils.hooks
block_cipher = None

x = Tree('C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages\\pysnmp\\smi\\mibs',prefix='pysnmp/smi/mibs')
y = Tree('C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages\\pysmi',prefix='pysmi')

a = Analysis(['main.py'],
             pathex=['D:\\username\\yourfolder'],
             binaries=[],
             datas=[],
             hiddenimports=PyInstaller.utils.hooks.collect_submodules('pysnmp'),
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,		  
		  x,y,
          name='main',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True 
          )
...

**Comment by ImXron** [comment]
@nrichardson31 You are correct. Looks like it's working now thanks!

**Comment by htgoebel** [comment]
Looks like this can be closed.

But maybe one of you wants to submit a hook for pysnmp and pysmi? https://pyinstaller.readthedocs.io/en/latest/hooks.html#useful-items-in-pyinstaller-utils-hooks should give you al the information you need.
