### ISSUE TITLE
No module name "pyexpat"

### ISSUE THREAD

**Issue by gusg21** [pyinstaller/pyinstaller#2908]
When I try to create an executable with this command:
`pyinstaller main.py control.py --debug --onedir`
```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
    import pkg_resources as res
  File "c:\users\user\console\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 34, in <module>
  File "c:\users\user\console\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "plistlib.py", line 65, in <module>
  File "c:\users\user\console\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: No module named 'pyexpat'
```
I'm using Windows 10 64-bit, python 3.5

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by htgoebel** [comment]
No feedback since 5 month, I assume this is solved.

**Comment by chiayunina** [comment]
I have the same problem here. Using Windows 10 x64 python 3.6
