### ISSUE TITLE
Django + PyMySQL = cannot import name FIELD_TYPE

### ISSUE THREAD

**Issue by dwhittle-sfdc** [pyinstaller/pyinstaller#2936]
We are trying to move an old Django app to use MariaDB/MySQL. We've been using PyInstaller against the application with it using SQLite as it's DB for sometime.

The freeze process itself goes as expected and the issue is when we try to run the application where it fails with ```Error was: cannot import name FIELD_TYPE```. We have traced this to this import: ```venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py:from MySQLdb.constants import FIELD_TYPE, CLIENT```.

In our  ```manage.py``` we have ```import pymysql``` and ```pymysql.install_as_MySQLdb()``` as needed for PyMySQL to act as MySQLdb. This setup works as expected when we execute the code directly with Python.

Using ```pyi-archive_viewer``` we can see that PyMySQL has been included in the produced binary as expected:

```
(venv) -bash-4.1$ pyi-archive_viewer django_app --recursive --log | grep -i mysql
 'django.db.backends.mysql': (1, 723048, 101),
 'django.db.backends.mysql.base': (0, 723149, 8367),
 'django.db.backends.mysql.client': (0, 731516, 758),
 'django.db.backends.mysql.compiler': (0, 732274, 950),
 'django.db.backends.mysql.creation': (0, 733224, 1475),
 'django.db.backends.mysql.introspection': (0, 734699, 2222),
 'django.db.backends.mysql.validation': (0, 736921, 690),
 'pymysql': (1, 2372815, 2672),
 'pymysql._compat': (0, 2375487, 425),
 'pymysql._socketio': (0, 2375912, 1898),
 'pymysql.charset': (0, 2377810, 3793),
 'pymysql.connections': (0, 2381603, 19815),
 'pymysql.constants': (1, 2401418, 95),
 'pymysql.constants.CLIENT': (0, 2401513, 603),
 'pymysql.constants.COMMAND': (0, 2402116, 583),
 'pymysql.constants.CR': (0, 2402699, 1187),
 'pymysql.constants.ER': (0, 2403886, 7514),
 'pymysql.constants.FIELD_TYPE': (0, 2411400, 480),
 'pymysql.constants.FLAG': (0, 2411880, 330),
 'pymysql.constants.SERVER_STATUS': (0, 2412210, 325),
 'pymysql.converters': (0, 2412535, 4891),
 'pymysql.cursors': (0, 2417426, 7094),
 'pymysql.err': (0, 2424520, 2119),
 'pymysql.optionfile': (0, 2426639, 501),
 'pymysql.times': (0, 2427140, 361),
 'pymysql.util': (0, 2427501, 380),
```

We have also had ```manage.py``` output ```sys.modules``` for us and both running as the binary and via Python correctly show MySQLdb mapped to pymysql as expected:

- Python: ```'MySQLdb': <module 'pymysql' from 'venv/lib/python2.7/site-packages/pymysql/__init__.py'>,```
- Binary: ```'MySQLdb': <module 'pymysql' from '/tmp/_MEIfnEXMe/pymysql/__init__.pyc'>,```

We tried many variations of inclusions in our ```hiddenimports``` and calling ```hooks.collect_submodules()``` in our hook script as well as importing and calling ```install_as_MySQLdb()``` from various places in manage.py and the hook file.

The only fix we have found for this is to modify ```venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py``` directly and change it's import statements from MySQLdb to pymysql.

Does anyone have other potential solutions other than patching code outside our own code base?

**Exception output:**
```
(venv) -bash-4.1$ django_app syncdb --noinput
Traceback (most recent call last):
  File "<string>", line 121, in <module>
  File "site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
  File "site-packages/django/core/management/__init__.py", line 392, in execute
  File "site-packages/django/core/management/__init__.py", line 261, in fetch_command
  File "site-packages/functools32/functools32.py", line 378, in wrapper
  File "django_pyinstaller_monkey_patch.py", line 106, in get_commands
    app_commands = find_commands(app_name)
  File "django_pyinstaller_monkey_patch.py", line 48, in find_commands
    module = importlib.import_module(commands_import_name)
  File "importlib/__init__.py", line 37, in import_module
  File "venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/django/contrib/admin/__init__.py", line 6, in <module>
  File "venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/django/contrib/admin/sites.py", line 4, in <module>
  File "venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/django/contrib/admin/forms.py", line 6, in <module>
  File "venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/django/contrib/auth/forms.py", line 17, in <module>
  File "venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/django/contrib/auth/models.py", line 48, in <module>
  File "site-packages/django/db/models/base.py", line 96, in __new__
  File "site-packages/django/db/models/base.py", line 264, in add_to_class
  File "site-packages/django/db/models/options.py", line 124, in contribute_to_class
  File "site-packages/django/db/__init__.py", line 34, in __getattr__
  File "site-packages/django/db/utils.py", line 198, in __getitem__
  File "site-packages/django/db/utils.py", line 131, in load_backend
django.core.exceptions.ImproperlyConfigured: 'mariadb' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    
Error was: cannot import name FIELD_TYPE
manage returned -1
```

**Note:** The `mariadb` backend is a subclass of the builtin `django.db.backends.mysql` to allow for the field validation to be overridden.

**Comment by mohanraj-r** [comment]
PyMySQL patches by modifying `sys.modules`

[PyMySQL/__init__.py](https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/__init__.py#L121) :
```python
sys.modules["MySQLdb"] = sys.modules["_mysql"] = sys.modules["pymysql"]
```

Wondering if PyInstaller's [modifications to `sys.modules`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/pyimod03_importers.py) might be making the PyMySQL's patching to be ineffective ?

**Comment by htgoebel** [comment]
Thanks for this useful bugreport :-)

This might be caused by asymmetry between the package names: In the PYZ  archive the module is named `pymysql.constants.FIELD_TYPE`, but the import says `from MySQLdb.constants import FIELD_TYPE, CLIENT`. So maybe PyInstaller tries to find `MySQLdb.constants.FIELD_TYPE`.

To verify this these please add some print-statements to [`find_module`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/pyimod03_importers.py#L251) and try again. Additionally try this in the python interpreter:
```python
import sys, pymysql
sys.modules["MySQLdb"] = sys.modules["_mysql"] = sys.modules["pymysql"]
from MySQLdb.constants import FIELD_TYPE
print [m for m in sys.modules.keys() if 'mysql' in m.lower()]
```

**Comment by htgoebel** [comment]
Any answer? Otherwise I need to close this isuse due to lack of information.

**Comment by dwhittle-sfdc** [comment]
> Any answer? Otherwise I need to close this isuse due to lack of information.

Apologies. A lot has gotten in the way of debugging this issue more and we've worked around it with a patch in the meantime.

I do intend for us to get back to it, but I do not have an ETA at this time. We can close this one and I'll open a new one referencing this one and including the requested information when we get to it.

**Comment by htgoebel** [comment]
Okay. But please re-use this issue, as there is not need to start a new one.
