### ISSUE TITLE
"ImportError: cannot import name _remove_dead_weakref" after packaging

### ISSUE THREAD

**Issue by maroz** [pyinstaller/pyinstaller#2942]
Hi all.

I got an **ImportError** after trying to launch previously packaged binary on my Ubuntu and I don't kwon what to do with it  :(

The traceback is the following:

> (ocr) maroz@map-vm:~/PycharmProjects/OCR_clean/src$ ./dist/ocr_agent_service/ocr_agent_service 
> Traceback (most recent call last):
>   File "site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py", line 61, in <module>
>   File "/home/maroz/.pyenv/versions/2.7.14/envs/ocr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
>     exec(bytecode, module.__dict__)
>   File "multiprocessing/__init__.py", line 65, in <module>
>   File "/home/maroz/.pyenv/versions/2.7.14/envs/ocr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
>     exec(bytecode, module.__dict__)
>   File "multiprocessing/util.py", line 37, in <module>
>   File "/home/maroz/.pyenv/versions/2.7.14/envs/ocr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
>     exec(bytecode, module.__dict__)
>   File "weakref.py", line 14, in <module>
> ImportError: cannot import name _remove_dead_weakref
> [16027] Failed to execute script pyi_rth_multiprocessing

**My configuration is next:**
Ubuntu: 16.04
Python: 2.7.14 (via pyenv)
Pyinstaller: 3.4.dev0+133d18156 (but this error also occurs using Pyinstaller v3.3)

**Pyinstaller command line:**
pyinstaller --log-level=DEBUG --onedir --nowindow ./ocr_agent_service.py

**Output from Pyinstaller** may be found [here](https://pastebin.com/MC40KEiL)

**Comment by maroz** [comment]
Can be closed. Not an issue of Pyinstaller.
