### ISSUE TITLE
Django 1.11:  No module named 'django.contrib.staticfiles.apps'

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#2958]
Another import problem, sorry...

First, I had a problem with :
`No module named 'django.contrib.admin.apps'.

I've added the hook: `hook-django.contrib.py` with inside:
```
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('django.contrib')
```

and now I 've got this error with `django.contrib.staticfiles.apps`.

creating the dist:
```
$ pyinstaller --debug --noupx --additional-hooks-dir=./LingL/pyinstaller/hooks/ --name=LingL LingL/manage.py
49 INFO: PyInstaller: 3.4.dev0+133d18156
50 INFO: Python: 3.6.2
51 INFO: Platform: Linux-4.9.59-1-MANJARO-x86_64-with-glibc2.3.4
52 INFO: wrote /mnt/backup/BACKUP_Aubrey/workspace/LingL.spec
54 INFO: UPX is not available.
55 INFO: Extending PYTHONPATH with paths
['/mnt/backup/BACKUP_Aubrey/workspace/LingL',
 '/mnt/backup/BACKUP_Aubrey/workspace']
55 INFO: checking Analysis
88 INFO: Building because /home/campagne/.Envs/LingL/lib/python3.6/site-packages/PyInstaller/loader/rthooks/pyi_rth_django.py changed
88 INFO: Initializing module dependency graph...
89 INFO: Initializing module graph hooks...
90 INFO: Analyzing base_library.zip ...
3274 INFO: running Analysis out00-Analysis.toc
3297 INFO: Caching module hooks...
3302 INFO: Analyzing /mnt/backup/BACKUP_Aubrey/workspace/LingL/manage.py
3960 INFO: Processing pre-find module path hook   distutils
3961 INFO: distutils: retargeting to non-venv dir '/usr/lib64/python3.6/distutils'
6547 INFO: Loading module hooks...
6547 INFO: Loading module hook "hook-pydoc.py"...
6548 INFO: Loading module hook "hook-django.py"...
6550 INFO: Django root directory /mnt/backup/BACKUP_Aubrey/workspace/LingL/LingL
Traceback (most recent call last):
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/PyInstaller/utils/hooks/subproc/django_import_finder.py", line 37, in <module>
    list(settings.TEMPLATE_LOADERS) + \
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'
7227 INFO: Collecting Django migration scripts.
8502 INFO: Loading module hook "hook-django.core.cache.py"...
8610 INFO: Loading module hook "hook-django.db.backends.py"...
8874 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
9010 INFO: Loading module hook "hook-django.db.backends.oracle.base.py"...
9012 INFO: Loading module hook "hook-lib2to3.py"...
9014 INFO: Loading module hook "hook-distutils.py"...
9016 INFO: Loading module hook "hook-pytz.py"...
9037 INFO: Loading module hook "hook-django.db.backends.mysql.base.py"...
9040 INFO: Loading module hook "hook-sqlite3.py"...
9096 INFO: Loading module hook "hook-xml.py"...
9340 INFO: Loading module hook "hook-django.core.management.py"...
10173 INFO: Import to be excluded not found: 'tkinter'
10174 INFO: Import to be excluded not found: 'matplotlib'
10174 INFO: Excluding import 'IPython'
10175 INFO:   Removing import of IPython from module django.core.management.commands.shell
10176 INFO: Loading module hook "hook-django.core.mail.py"...
10241 INFO: Loading module hook "hook-encodings.py"...
10312 INFO: Loading module hook "hook-sysconfig.py"...
10319 INFO: Loading module hook "hook-pkg_resources.py"...
10769 INFO: Processing pre-safe import module hook   win32com
10772 INFO: Loading module hook "hook-django.contrib.messages.py"...
10853 INFO: Loading module hook "hook-django.contrib.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/django/contrib/gis/admin/__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/django/contrib/gis/admin/options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/django/contrib/gis/admin/widgets.py", line 10, in <module>
    geo_context = {'LANGUAGE_BIDI': translation.get_language_bidi()}
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 199, in get_language_bidi
    return _trans.get_language_bidi()
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 59, in __getattr__
    if settings.USE_I18N:
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/campagne/.Envs/LingL/lib/python3.6/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
12418 INFO: Loading module hook "hook-django.contrib.staticfiles.py"...
12525 INFO: Loading module hook "hook-xml.dom.domreg.py"...
12525 INFO: Loading module hook "hook-selenium.py"...
12589 INFO: Looking for ctypes DLLs
12742 INFO: Analyzing run-time hooks ...
12752 INFO: Including run-time hook 'pyi_rth_django.py'
12754 INFO: Including run-time hook 'pyi_rth_pkgres.py'
12755 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
12778 INFO: Looking for dynamic libraries
13204 INFO: Looking for eggs
13204 INFO: Using Python library /usr/lib/libpython3.6m.so.1.0
13213 INFO: Warnings written to /mnt/backup/BACKUP_Aubrey/workspace/build/LingL/warnLingL.txt
13360 INFO: Graph cross-reference written to /mnt/backup/BACKUP_Aubrey/workspace/build/LingL/xref-LingL.html
13548 INFO: checking PYZ
13555 INFO: Building because toc changed
13555 INFO: Building PYZ (ZlibArchive) /mnt/backup/BACKUP_Aubrey/workspace/build/LingL/out00-PYZ.pyz
14650 INFO: Building PYZ (ZlibArchive) /mnt/backup/BACKUP_Aubrey/workspace/build/LingL/out00-PYZ.pyz completed successfully.
14693 INFO: checking PKG
14694 INFO: Building because /mnt/backup/BACKUP_Aubrey/workspace/build/LingL/out00-PYZ.pyz changed
14694 INFO: Building PKG (CArchive) out00-PKG.pkg
14752 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
14754 INFO: Bootloader /home/campagne/.Envs/LingL/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
14754 INFO: checking EXE
14755 INFO: Building because /home/campagne/.Envs/LingL/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run_d changed
14756 INFO: Building EXE from out00-EXE.toc
14757 INFO: Appending archive to ELF section in EXE /mnt/backup/BACKUP_Aubrey/workspace/build/LingL/LingL
14787 INFO: Building EXE from out00-EXE.toc completed successfully.
14796 INFO: checking COLLECT
14823 INFO: Building COLLECT out00-COLLECT.toc
16279 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

```

**Comment by The-Phi** [comment]
Okay, I've deleted the line:
https://github.com/pyinstaller/pyinstaller/blob/a70b20e4de6a6817987d28ca9f3201c8105fd858/PyInstaller/utils/hooks/subproc/django_import_finder.py#L36

in the source code of Pyinstaller, since apparently, the TEMPLATE_CONTEXT_PROCESSORS setting was deprecated in Django 1.8 and removed in Django 1.10. 
https://stackoverflow.com/questions/41487104/attributeerror-settings-object-has-no-attribute-template-context-processors

Now I've got:
`No module named 'django.contrib.sites.apps'`

**Comment by The-Phi** [comment]
It's the same Django 1.11 compatibility problem than this https://github.com/pyinstaller/pyinstaller/issues/2808

Deleting lines of code is maybe too naive...

**Comment by htgoebel** [comment]
Somebody needs to provide proper hooks, see https://github.com/pyinstaller/pyinstaller/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+django.

**Comment by bwoodsend** [comment]
We no longer support `Django 1.x`. Please create a new issue if this persists in `django >= 2.0`
