### ISSUE TITLE
OSError: [Errno 20] Not a directory:

### ISSUE THREAD

**Issue by 0avasns** [pyinstaller/pyinstaller#2964]
I have been wrestling with an old Tkinter application that works fine on my old iMac (OS X 10.9.5) when run from IDLE. It has also worked fine on Windows since XP and compiles fine there using py2exe. Trying to get a Mac app for distribution, it turns out that py2app has problems with it, possibly due to the ActiveState Tcl 8.5.18, which I just installed because the original Tcl/Tk was misaligning widgets. 
Now pyinstaller won't even compile it, it apparently bombs on a make-directory internal to the in-progress distribution (see last line below). Does this look like a bug or is it something I did?

$ /bin/rm -rf dist
$ pyinstaller --windowed RavenCPM.pyw 
384 INFO: PyInstaller: 3.4.dev0+133d18156
384 INFO: Python: 2.7.14
436 INFO: Platform: Darwin-13.4.0-x86_64-i386-64bit
438 INFO: wrote /Users/protopap/Desktop/Raven CPM/RavenCPM.spec
481 INFO: UPX is not available.
484 INFO: Extending PYTHONPATH with paths
['/Users/protopap/Desktop/Raven CPM', '/Users/protopap/Desktop/Raven CPM']
491 INFO: checking Analysis
703 INFO: checking PYZ
731 INFO: checking PKG
747 INFO: Bootloader /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
747 INFO: checking EXE
763 INFO: checking COLLECT
763 INFO: Building COLLECT because out00-COLLECT.toc is non existent
763 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+133d18156', 'console_scripts', 'pyinstaller')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/building/api.py", line 661, in __init__
    self.__postinit__()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/building/api.py", line 687, in assemble
    os.makedirs(todir)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 20] Not a directory: '/Users/protopap/Desktop/Raven CPM/dist/RavenCPM/tcl/tzdata'

**Comment by miguelHx** [comment]
Read this link and follow the steps to fix the issue, going to make a PR to PyInstaller soon

https://github.com/viotti/pyinstaller/commit/597af5cb01c064620b53ea1ee537e30f56fa481d

**Comment by 0avasns** [comment]
Thank you very much, this fixes the folder creation problem indeed and produces an almost-working bundle.
I still need to add snack manually afterwards because it is not done automatically by PyInstaller:
cp -r /Library/Tcl/snack2.2 ./dist/myapp/tclResources/
This produces a fully working bundle.

Unfortunately, this only works with folder bundle with console launch. If I use this instead:
pyinstaller -w -i myapp.icns myapp.pyw
then I get an app with icon that looks fine and launches normally, but it fails when the snack functionality is needed. Copying the snack folder into tclResources no longer works in this case.

It is not clear if and how I can get the snack library to be correctly included using PyInstaller options (it is not just a file and needs to go under tclResources) so that the no-console app can be properly created.

**Comment by rokm** [comment]
Closing this as the reported version of python (2.7.14) is not supported anymore.

Recent commits should take care of lingering issues with `tkinter` and Tcl/Tk on macOS for supported python versions. If you encounter any `tkinter`-related issues with those, please open a new issue with updated details.
