### ISSUE TITLE
pyinstaller error

### ISSUE THREAD

**Issue by PBShortStop** [pyinstaller/pyinstaller#3023]
When i convert my python script to exe on win10 platform by pyinstaller, i meet the problem.
The exe file is successfully created, but do not open exe file.

my env:
win 10
python 3.6
pyinstaller 3.3

```
Traceback (most recent call last):
File "xxxxx.py", line 2, in <module>
    import xxxxxx
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "..\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "xxxxx\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "..\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "xxxx\api.py", line 19, in <module>
    pose_predictor = dlib.shape_predictor(predictor_model)
RuntimeError: Unable to open
```

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

Also looking arounf xxxx\api.py", line 19 might be helpful.
