### ISSUE TITLE
pyzbar -- ctype module not found.

### ISSUE THREAD

**Issue by Bala93** [pyinstaller/pyinstaller#3056]
File "ctypes\__init__.py", line 363, in __init__                                                                      
WindowsError: [Error 126] 
The specified module could not be found; Failed to execute script.

I am using pyzbar in my code. Pyzbar is to convert barcode image to its respective barcode. WIthout using this module my code works fine. Using that causes the above error during runtime. 

pyinstaller main.spec ran successfully.
main.exe ran into the above error. 

For you information, i dont know whether it is helpful. 
pyzbar has two .dll files in it. 

##Traceback:
Traceback (most recent call last):                                                                                        File "main1.py", line 11, in <module>                                                                                   File "c:\users\bala\appdata\local\temp\pip-build-ocb7qp\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module                                                                                                         File "site-packages\pyzbar\pyzbar.py", line 8, in <module>                                                              File "c:\users\bala\appdata\local\temp\pip-build-ocb7qp\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module                                                                                                         File "site-packages\pyzbar\wrapper.py", line 166, in <module>                                                           File "site-packages\pyzbar\wrapper.py", line 159, in zbar_function                                                      File "site-packages\pyzbar\wrapper.py", line 130, in load_libzbar                                                       File "site-packages\pyzbar\wrapper.py", line 122, in load                                                               File "ctypes\__init__.py", line 442, in LoadLibrary                                                                     File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 136, in __init__                                   File "ctypes\__init__.py", line 363, in __init__                                                                      WindowsError: [Error 126] The specified module could not be found

**Comment by htgoebel** [comment]
Look at  File "site-packages\pyzbar\wrapper.py", line 122 and read https://pyinstaller.readthedocs.io/en/latest/feature-notes.html?highlight=ctypes#ctypes-dependencies

**Comment by Bala93** [comment]
I couldn't understand the documentation. Can you please help me out ? It
says it is supposed to gather the dlls but it not doing so or can you point
me to some thread where this one is clearly explained.

Thank-you

**Comment by htgoebel** [comment]
Read the Ü*whole* section, esp. the gotchas and look at  File "site-packages\pyzbar\wrapper.py", line 122.

**Comment by Bala93** [comment]
deps = [ cdll.LoadLibrary(str(dir.joinpath(dep)) for dep in dependencies ]

This is what i have in line 122. And the code is being run in windows. Is there some path should i set ? There are two dlls in this path. How should i extend this to run time. I kind of getting the idea now. But i dont know how to put it and make it work. 

Thanks for your help.

**Comment by htgoebel** [comment]
I added some more information to https://pyinstaller.readthedocs.io/en/latest/feature-notes.html

**Comment by Bala93** [comment]
I have tried the following procedures: 
SImply ran the pyinstaller main.py
Added the .dll in binary in next case. 

When i added absolute url it showed security issue:adding file outside of dist folder.

What is the idea behind this ctypes loader and how you are solving it ?
How to write the hookspath code ? 

I have read the documentation, i could'nt grasp the idea mentioned. Can ctypes loading be used in windows also ? Since you were mentioning the library path and it is specific to linux. 

The other modules like cv2,numpy,wx,sklearn and inbuilt python modules seems to work.

**Comment by Bala93** [comment]
Thanks for your help. 

The module pyzbar depends on two dll files. While adding to the Analysis binaries i made a mistake.

binaries = [(path,''),(path,'')] worked very well. 
With windows the cache is created in "AppData\Roaming\pyinstaller\bincache00_py27_32bit", when i was trying to rerun the .specfile it did'nt work proper so i went and removed the cache and rerun. Now it worked.
