### ISSUE TITLE
Access is denied.

### ISSUE THREAD

**Issue by Bala93** [pyinstaller/pyinstaller#3062]
Spec file:
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['main1.py'],
             pathex=['D:/OMR/Updated_single_file_code'],
             binaries=[('C:/Users/Bala/Anaconda2/Lib/site-packages/pyzbar/libiconv-2.dll','.'),('C:/Users/Bala/Anaconda2/Lib/site-packages/pyzbar/libzbar-32.dll','.')],
             datas=[],
             hiddenimports=['sklearn.neighbors.typedefs'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
             
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='main',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='main')
```

Traceback (most recent call last):                                                                                                                                        File "c:\users\bala\anaconda2\lib\runpy.py", line 174, in _run_module_as_main                                                                                             "__main__", fname, loader, pkg_name)                                                                                                                                  File "c:\users\bala\anaconda2\lib\runpy.py", line 72, in _run_code                                                                                                        exec code in run_globals                                                                                                                                              File "C:\Users\Bala\Anaconda2\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>                                                                                 File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\__main__.py", line 90, in run                                                                                 run_build(pyi_config, spec_file, **vars(args))                                                                                                                        File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build                                                                           PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)                                                                                                 File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main                                                                    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))                                                                                        File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build                                                                   exec(text, spec_namespace)                                                                                                                                            File "<string>", line 34, in <module>                                                                                                                                   File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\building\api.py", line 650, in __init__                                                                       self.__postinit__()                                                                                                                                                   File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__                                                            self.assemble()                                                                                                                                                       File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\building\api.py", line 682, in assemble                                                                       dist_nm=inm)                                                                                                                                                          File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\building\utils.py", line 268, in checkCache                                                                   res = winmanifest.GetManifestResources(os.path.abspath(cachedfile))                                                                                                   File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1005, in GetManifestResources                                               return winresource.GetResources(filename, [RT_MANIFEST], names, languages)                                                                                            File "c:\users\bala\anaconda2\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 171, in GetResources                                                        hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)                                                                                                pywintypes.error: (5, 'LoadLibraryEx', 'Access is denied.')

**Comment by htgoebel** [comment]
Please reformat the traceback, it's unreadable in this form.

**Comment by Bala93** [comment]
This is due to the cache memory created in App_data. 

Instead of giving [path,''] in binaries i gave [path,'.'] which has difficulty in finding the dll and placing it in te right folder. 

Error is solved.

**Comment by htgoebel** [comment]
Just yesterday I was thinking whether I should change the behavior of  `[path,'']` vs. `[path,'.'] `, since I find this empty string irritating.

**Comment by Bala93** [comment]
Yes. First I didn't realize that. Even after reading documentation one or
two times I missed that. But good work on pyinstaller. Thank you.
