### ISSUE TITLE
Exception: Python.Runtime not found 

### ISSUE THREAD

**Issue by karamjaber** [pyinstaller/pyinstaller#3078]
I want to package some python27 file and make an executable file from it.
While bundling i get the following error:

```
14824 INFO: Loading module hooks...
14840 INFO: Loading module hook "hook-distutils.py"...
14840 INFO: Loading module hook "hook-xml.py"...
15012 INFO: Loading module hook "hook-httplib2.py"...
15028 INFO: Loading module hook "hook-httplib.py"...
15028 INFO: Loading module hook "hook-requests.py"...
15028 INFO: Loading module hook "hook-certifi.py"...
15042 INFO: Loading module hook "hook-clr.py"...
Traceback (most recent call last):
  File "c:\Python27\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+5f92e6d16', 'console_scripts', 'pyin
staller')()
  File "c:\python27\lib\site-packages\PyInstaller\__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_
build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
213, in __init__
    self.__postinit__()
  File "c:\python27\lib\site-packages\PyInstaller\building\datastruct.py", line
161, in __postinit__
    self.assemble()
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
472, in assemble
    module_hook.post_graph()
  File "c:\python27\lib\site-packages\PyInstaller\building\imphook.py", line 410
, in post_graph
    self._load_hook_module()
  File "c:\python27\lib\site-packages\PyInstaller\building\imphook.py", line 377
, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\python27\lib\site-packages\PyInstaller\hooks\hook-clr.py", line 37, i
n <module>
    raise Exception(pyruntime + ' not found')
Exception: Python.Runtime not found
```

I used this command : 
`c:\Python27\Scripts\pyinstaller.exe --hidden-import=clr --onefile --name=send_message.exe --clean proxySend.py`

I'm using Windows8.1, tried to convert my Python file to Python35 and then to build it and it works but for some reason in python27 it doesn't work.

Any idea why ?

**Comment by htgoebel** [comment]
Well, you tell PyInstaller to include `clr` and clr requires Python.Runtime. Just remove `--hidden-import=clr` from your command line.

**Comment by karamjaber** [comment]
Tried this as well...didn't work

**Comment by htgoebel** [comment]
"didn't work" is a bit terse, don't you think, too.
