### ISSUE TITLE
AttributeError: type object 'pandas._libs.tslib._TSObject' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by joelhjalmarsson** [pyinstaller/pyinstaller#3079]
pyinstaller version: PyInstaller-3.4.dev0+5f92e6d16
OS: Windows7 
python version 2.7.14

This is the first time I am trying to use pyinstaller. I get no errors or warnings when running pyinstaller but when trying to execute the resulting .exe file I get the following error:
```
Traceback (most recent call last):
  File "drivers_notes.py", line 8, in <module>
  File "c:\python\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\mdfreader\__init__.py", line 30, in <module>
  File "c:\python\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\mdfreader\mdfreader.py", line 48, in <module>
  File "c:\python\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\mdfreader\mdf3reader.py", line 48, in <module>
  File "c:\python\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\mdfreader\mdf.py", line 26, in <module>
  File "c:\python\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pandas\__init__.py", line 26, in <module>
  File "c:\python\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pandas\_libs\__init__.py", line 4, in <module>
  File "c:\python\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 687, in load_module
    module = imp.load_module(fullname, fp, filename, ext_tuple)
  File "pandas\_libs\tslib.pyx", line 1510, in init pandas._libs.tslib
AttributeError: type object 'pandas._libs.tslib._TSObject' has no attribute '__reduce_cython__'*
```
I am using a module called mdfreader in my program and I guess that is not supported by pyinstaller?

**Comment by htgoebel** [comment]
Please try #2998, which solves another problem with pandas._libs.tslibs.

**Comment by joelhjalmarsson** [comment]
Thanks for the quick reply.
Feeling like a complete n00b here but what is the easiest way to add this hook to my pyinstaller installation?

**Comment by htgoebel** [comment]
Read the fine manual, it should explain everything you need. If something is missing, we'll add it.

**Comment by joelhjalmarsson** [comment]
Yes the manual is really fine, but I am afraid I am too much of a rookie to even know what to look for.
I might have to solve my problem in some other language if I cannot make this python app portable.

**Comment by joelhjalmarsson** [comment]
I switched to python 3 and no longer see this problem. Got some other import problems instead but easier to solve than this.

**Comment by wangym1993** [comment]
@htgoebel Hi there, I am having the same issue here after adding the hook-pandas.py.

Could you please help with locating the tslib.pyx file or give other comments for debugging? I can only see .pyd files which couldn't be opened. 

  File "pandas\_libs\tslib.pyx", line 1514, in init pandas._libs.tslib
AttributeError: type object 'pandas._libs.tslib._TSObject' has no attribute '__reduce_cython__'

**Comment by htgoebel** [comment]
@wangym1993 Please see https://github.com/pyinstaller/pyinstaller/issues/3079#issuecomment-349915762

**Comment by wangym1993** [comment]
@JenOver Hey, I was successful after dumping site packages in the bin folder

**Comment by wangym1993** [comment]
basically, you only need to put those files that was reported missing in the folder after you execute your binary file. Py2exe/Pyinstaller doesn't recognize some files

**Comment by eliaperantoni** [comment]
@wangym1993 I have the same issue, what do you mean by "bin folder"? There's no bin folder in my generated dist/projectname

**Comment by Hellcat1005** [comment]
Please try pandas-0.20.3. It works for me.

**Comment by fctien98** [comment]
I try all the actions including: downgrade to pandas 0.20.3, hidden import, still not working.  Is there thing I can try

**Comment by paulathomas** [comment]
There are two separate but similar problems. Both are in smoothers.py, the first is in line 4 'from pandas.lib import Timesamp' why this line isn't failing with pandas 0.24.2 s beyond me but it does mean the later attempts to use the imported function don't work. A possible correction to this is to remove the '.lib' from this line. I will clone, experiment, and get back. Given this import the main installation problem identified by the OP should be fixed by changing line 14 'pd.tslib.Timestamp,' can be changed to 'Tiimestamp' again I'll clone, experiment, and get back.

**Comment by paulathomas** [comment]
Sorry wrong thread...
