### ISSUE TITLE
Utf-8 codec can't decode

### ISSUE THREAD

**Issue by Goczilla** [pyinstaller/pyinstaller#3083]
Hello, I worked with a previous version of pyinstaller and all was working fine.

But since I installed the last version (for various reasons) and now I have the following error with hook-zmq.py.

Thank you in advance for the help.

Here is the console output of pyinstaller:

```
439 INFO: PyInstaller: 3.3
439 INFO: Python: 3.6.2
440 INFO: Platform: Windows-7-6.1.7601-SP1
551 INFO: UPX is not available.
554 INFO: Extending PYTHONPATH with paths
['C:\\MG\\Projet_CALO', 'C:\\MG\\Projet_CALO\\Interface']
554 INFO: checking Analysis
648 INFO: Building because C:\MG\Projet_CALO\Interface\Lancement_IHM.py changed
648 INFO: Initializing module dependency graph...
651 INFO: Initializing module graph hooks...
653 INFO: Analyzing base_library.zip ...
5585 INFO: running Analysis out00-Analysis.toc
5587 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by c:\users\mg\appdata\local\continuum\anaconda3\python.exe
6444 INFO: Caching module hooks...
6452 INFO: Analyzing Lancement_IHM.py
9140 INFO: Processing pre-find module path hook   distutils
10740 INFO: Processing pre-find module path hook   site
10740 INFO: site: retargeting to fake-dir 'c:\\users\\mg\\appdata\\local\\contin
uum\\anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
21176 INFO: Processing pre-safe import module hook   six.moves
29434 INFO: Processing pre-safe import module hook   requests.packages.urllib3.p
ackages.six.moves
53480 INFO: Processing pre-safe import module hook   win32com
65211 INFO: Loading module hooks...
65211 INFO: Loading module hook "hook-babel.py"...
65406 INFO: Loading module hook "hook-certifi.py"...
65408 INFO: Loading module hook "hook-cryptography.py"...
65945 INFO: Loading module hook "hook-distutils.py"...
65947 INFO: Loading module hook "hook-docutils.py"...
67269 INFO: Loading module hook "hook-encodings.py"...
67363 INFO: Loading module hook "hook-IPython.py"...
67377 INFO: Excluding import 'PyQt5'
67384 INFO:   Removing import of PyQt5.QtGui from module IPython.external.qt_loa
ders
67384 INFO:   Removing import of PyQt5.QtCore from module IPython.external.qt_lo
aders
67384 INFO:   Removing import of PyQt5.QtSvg from module IPython.external.qt_loa
ders
67385 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
67385 INFO:   Removing import of PyQt5.QtWidgets from module IPython.external.qt
_loaders
67386 INFO: Excluding import 'PySide'
67392 INFO:   Removing import of PySide from module IPython.external.qt_loaders
67393 INFO: Excluding import 'matplotlib'
67399 INFO:   Removing import of matplotlib.figure from module IPython.core.pyla
btools
67399 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pyla
btools
67400 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.c
ore.pylabtools
67400 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
67402 INFO: Excluding import 'tkinter'
67407 INFO:   Removing import of tkinter from module IPython.lib.clipboard
67409 INFO: Excluding import 'PyQt4'
67416 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
67417 INFO: Excluding import 'gtk'
67424 INFO: Loading module hook "hook-jinja2.py"...
67444 INFO: Loading module hook "hook-jsonschema.py"...
67446 INFO: Loading module hook "hook-lib2to3.py"...
67450 INFO: Loading module hook "hook-matplotlib.backends.py"...
Traceback (most recent call last):
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\matplotl
ib\__init__.py", line 180, in <module>
    import dateutil
ModuleNotFoundError: No module named 'dateutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\matplotl
ib\__init__.py", line 182, in <module>
    raise ImportError("Matplotlib requires dateutil")
ImportError: Matplotlib requires dateutil
67749 INFO: Loading module hook "hook-matplotlib.py"...
Traceback (most recent call last):
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\matplotl
ib\__init__.py", line 180, in <module>
    import dateutil
ModuleNotFoundError: No module named 'dateutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\matplotl
ib\__init__.py", line 182, in <module>
    raise ImportError("Matplotlib requires dateutil")
ImportError: Matplotlib requires dateutil
69474 INFO: Loading module hook "hook-numpy.core.py"...
69546 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
69552 INFO: Loading module hook "hook-PIL.Image.py"...
70057 INFO: Loading module hook "hook-PIL.py"...
70062 INFO: Excluding import 'PySide'
70065 INFO:   Removing import of PySide from module PIL.ImageQt
70067 INFO: Excluding import 'PyQt5'
70072 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
70072 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
70073 INFO: Excluding import 'tkinter'
70078 INFO:   Removing import of tkinter from module PIL.ImageTk
70078 INFO: Excluding import 'PyQt4'
70083 INFO:   Removing import of PyQt4 from module PIL.ImageQt
70084 INFO: Import to be excluded not found: 'FixTk'
70084 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
70088 INFO: Excluding import 'tkinter'
70092 INFO: Import to be excluded not found: 'FixTk'
70092 INFO: Loading module hook "hook-pkg_resources.py"...
71258 INFO: Loading module hook "hook-pycparser.py"...
71540 INFO: Loading module hook "hook-pydoc.py"...
71541 INFO: Loading module hook "hook-pygments.py"...
73508 INFO: Loading module hook "hook-PyQt5.py"...
73510 INFO: Loading module hook "hook-PyQt5.Qt.py"...
73511 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
73592 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
74055 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
74136 INFO: Loading module hook "hook-PyQt5.QtSvg.py"...
74137 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
74138 INFO: Loading module hook "hook-pytest.py"...
75095 INFO: Loading module hook "hook-pythoncom.py"...
75587 INFO: Loading module hook "hook-pytz.py"...
75671 INFO: Loading module hook "hook-pywintypes.py"...
76157 INFO: Loading module hook "hook-requests.py"...
76162 INFO: Loading module hook "hook-setuptools.py"...
76240 INFO: Loading module hook "hook-sphinx.py"...
80569 INFO: Loading module hook "hook-sqlalchemy.py"...
80786 INFO:   Found 3 sqlalchemy hidden imports
80788 WARNING: Hidden import "MySQLdb" not found!
80798 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
80802 INFO: Excluding import 'sqlalchemy.testing'
80808 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.
orm.util
80808 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng
80809 INFO:   Removing import of sqlalchemy.testing.warnings from module sqlalch
emy.testing
80809 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalche
my.testing
80809 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.
testing
80810 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlal
chemy.testing
80810 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalc
hemy.testing
80810 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlal
chemy.testing
80810 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.
testing
80811 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchem
y.testing
80811 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlal
chemy.testing.warnings
80811 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng.warnings
80811 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng.assertions
80811 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.
testing.assertions
80812 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalc
hemy.testing.assertions
80812 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlal
chemy.testing.assertions
80812 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.
testing.assertions
80812 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchem
y.testing.assertions
80812 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalche
my.testing.util
80812 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchem
y.testing.util
80812 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng.util
80813 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng.config
80813 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.
testing.engines
80813 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlal
chemy.testing.engines
80813 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchem
y.testing.engines
80813 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng.engines
80816 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng.exclusions
80816 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchem
y.testing.exclusions
80816 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng.assertsql
80816 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testi
ng.mock
80817 INFO: Loading module hook "hook-sqlite3.py"...
80913 INFO: Loading module hook "hook-sysconfig.py"...
80914 INFO: Loading module hook "hook-win32com.py"...
81145 INFO: Loading module hook "hook-xml.dom.domreg.py"...
81146 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
81148 INFO: Loading module hook "hook-xml.py"...
81148 INFO: Loading module hook "hook-zmq.py"...
Traceback (most recent call last):
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, i
n _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in
 _run_code
    exec(code, run_globals)
  File "C:\Users\mg\AppData\Local\Continuum\Anaconda3\Scripts\pyinstaller.exe\__
main__.py", line 9, in <module>
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 15, in <module>
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\building\build_main.py", line 472, in assemble
    module_hook.post_graph()
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\compat.py", line 728, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\hooks\hook-zmq.py", line 18, in <module>
    hiddenimports.extend(collect_submodules('zmq.backend'))
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\utils\hooks\__init__.py", line 619, in collect_submodules
    repr(pkg_dir), package))
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\utils\hooks\__init__.py", line 90, in exec_statement
    return __exec_python_cmd(cmd)
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\utils\hooks\__init__.py", line 77, in __exec_python_cmd
    txt = exec_python(*cmd, env=pp_env)
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\compat.py", line 562, in exec_python
    return exec_command(*cmdargs, **kwargs)
  File "c:\users\mg\appdata\local\continuum\anaconda3\lib\site-packages\PyInstal
ler\compat.py", line 369, in exec_command
    out = out.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 181: invali
d start byte
```

**Comment by htgoebel** [comment]
Please add this line in front of PyInstaller\compat.py", line 369:
```
print(repr(out)) ; raise SystemExit(1)
```
and try to spot what might be the problem.

**Comment by Goczilla** [comment]
I am sorry but I can't understand by myself this new output :
```
450 INFO: PyInstaller: 3.3
450 INFO: Python: 3.6.2
451 INFO: Platform: Windows-7-6.1.7601-SP1
524 INFO: UPX is not available.
526 INFO: Extending PYTHONPATH with paths
['C:\\MG\\Projet_CALO', 'C:\\MG\\Projet_CALO\\Interface']
527 INFO: checking Analysis
586 INFO: Building because C:\MG\Projet_CALO\Interface\Lancement_IHM.py changed
587 INFO: Initializing module dependency graph...
590 INFO: Initializing module graph hooks...
592 INFO: Analyzing base_library.zip ...
b'encodings.aliases\r\nencodings.ascii\r\nencodings.base64_codec\r\nencodings.bi
g5\r\nencodings.big5hkscs\r\nencodings.bz2_codec\r\nencodings.charmap\r\nencodin
gs.cp037\r\nencodings.cp1006\r\nencodings.cp1026\r\nencodings.cp1125\r\nencoding
s.cp1140\r\nencodings.cp1250\r\nencodings.cp1251\r\nencodings.cp1252\r\nencoding
s.cp1253\r\nencodings.cp1254\r\nencodings.cp1255\r\nencodings.cp1256\r\nencoding
s.cp1257\r\nencodings.cp1258\r\nencodings.cp273\r\nencodings.cp424\r\nencodings.
cp437\r\nencodings.cp500\r\nencodings.cp65001\r\nencodings.cp720\r\nencodings.cp
737\r\nencodings.cp775\r\nencodings.cp850\r\nencodings.cp852\r\nencodings.cp855\
r\nencodings.cp856\r\nencodings.cp857\r\nencodings.cp858\r\nencodings.cp860\r\ne
ncodings.cp861\r\nencodings.cp862\r\nencodings.cp863\r\nencodings.cp864\r\nencod
ings.cp865\r\nencodings.cp866\r\nencodings.cp869\r\nencodings.cp874\r\nencodings
.cp875\r\nencodings.cp932\r\nencodings.cp949\r\nencodings.cp950\r\nencodings.euc
_jis_2004\r\nencodings.euc_jisx0213\r\nencodings.euc_jp\r\nencodings.euc_kr\r\ne
ncodings.gb18030\r\nencodings.gb2312\r\nencodings.gbk\r\nencodings.hex_codec\r\n
encodings.hp_roman8\r\nencodings.hz\r\nencodings.idna\r\nencodings.iso2022_jp\r\
nencodings.iso2022_jp_1\r\nencodings.iso2022_jp_2\r\nencodings.iso2022_jp_2004\r
\nencodings.iso2022_jp_3\r\nencodings.iso2022_jp_ext\r\nencodings.iso2022_kr\r\n
encodings.iso8859_1\r\nencodings.iso8859_10\r\nencodings.iso8859_11\r\nencodings
.iso8859_13\r\nencodings.iso8859_14\r\nencodings.iso8859_15\r\nencodings.iso8859
_16\r\nencodings.iso8859_2\r\nencodings.iso8859_3\r\nencodings.iso8859_4\r\nenco
dings.iso8859_5\r\nencodings.iso8859_6\r\nencodings.iso8859_7\r\nencodings.iso88
59_8\r\nencodings.iso8859_9\r\nencodings.johab\r\nencodings.koi8_r\r\nencodings.
koi8_t\r\nencodings.koi8_u\r\nencodings.kz1048\r\nencodings.latin_1\r\nencodings
.mac_arabic\r\nencodings.mac_centeuro\r\nencodings.mac_croatian\r\nencodings.mac
_cyrillic\r\nencodings.mac_farsi\r\nencodings.mac_greek\r\nencodings.mac_iceland
\r\nencodings.mac_latin2\r\nencodings.mac_roman\r\nencodings.mac_romanian\r\nenc
odings.mac_turkish\r\nencodings.mbcs\r\nencodings.oem\r\nencodings.palmos\r\nenc
odings.ptcp154\r\nencodings.punycode\r\nencodings.quopri_codec\r\nencodings.raw_
unicode_escape\r\nencodings.rot_13\r\nencodings.shift_jis\r\nencodings.shift_jis
_2004\r\nencodings.shift_jisx0213\r\nencodings.tis_620\r\nencodings.undefined\r\
nencodings.unicode_escape\r\nencodings.unicode_internal\r\nencodings.utf_16\r\ne
ncodings.utf_16_be\r\nencodings.utf_16_le\r\nencodings.utf_32\r\nencodings.utf_3
2_be\r\nencodings.utf_32_le\r\nencodings.utf_7\r\nencodings.utf_8\r\nencodings.u
tf_8_sig\r\nencodings.uu_codec\r\nencodings.zlib_codec\r\n'
```

**Comment by htgoebel** [comment]
Sorry, my fault. This stopped processing much to early.
Please try
```
print(repr(out), flush=True)
```
This should get you an output after `Loading module hook "hook-zmq.py"...` and before the traceback. In this output, position 181 (+2 for `b'`) is the offending one.
If you can not spot the problem your self, please post this output (no traceback needed, no log, just this part).

**Comment by Goczilla** [comment]
I confirm there is more information now :
```
b"_cffi_ext.c\r\nc:\\users\\mg\\appdata\\local\\continuum\\anaconda3\\lib\\site-
packages\\zmq\\backend\\cffi\\__pycache__\\_cffi_ext.c(209): fatal error C1083:
Impossible d'ouvrir le fichier include\xa0: 'sys/un.h'\xa0: No such file or dire
ctory\r\nzmq.backend.cffi\r\nzmq.backend.cython\r\nzmq.backend.cython._device\r\
nzmq.backend.cython._poll\r\nzmq.backend.cython._version\r\nzmq.backend.cython.c
onstants\r\nzmq.backend.cython.context\r\nzmq.backend.cython.error\r\nzmq.backen
d.cython.message\r\nzmq.backend.cython.socket\r\nzmq.backend.cython.utils\r\nzmq
.backend.select\r\n"
```

**Comment by htgoebel** [comment]
The reason for this error message is that the data returned from the subprocess includes `\xa0`, which in ISO-Latin-15 in a non-breaking space. But when decoding the bytes with UTF-8, this is an illegal byte. Well, this is what the error message already says.

This looks like `_cffi_ext` does not honor the `PYTHONIOENCODING` environment variable. Probably this C-module simply writes out some bytes to directly stderr, without using python's mechanisms. This might be okay for the modules point of view, since it is a fatal error.

Prior to digging deeper into the issue, I ask you to check branch [`nice-unicodeerror-infos-3083`](https://github.com/pyinstaller/pyinstaller/tree/nice-unicodeerror-infos-3083), which I just created. This should still show the error, but above of the traceback, there should be a informative message showing part of the text you posted in your last comment. **Please report back if this worked for you**

Regarding the basic issue: Obviously _cffi_ext.c fails with
``
fatal error C1083: Impossible d'ouvrir le fichier include\xa0: 'sys/un.h'\xa0: No such file or directory
```
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing. Esp. try tracing the files accessed but not found (stracent is your friend).

If you fond what is missing, please open a new ticket about that issue. *This* ticket is about the Unicode Decode error. Thanks.

**Comment by Goczilla** [comment]
I am sorry but I am not familiar with Git so what you said is to update pyinstaller with the one of your branch? How to do this? ^^

I thank you for the time you pass with me. On monday I will install all (Anaconda, pyinstaller etc) on another computer also to check if I have this problem.

**Comment by htgoebel** [comment]
Perfectly :-) This I what I just added and wanted to see.
Thanks for reporting this problem. :-)

For you the search after sys/un.h continues. I wish you success.

**Comment by Goczilla** [comment]
Hello,

What do you mean? The problem is still here so what do you want to do with sys/un.h ?

**Comment by htgoebel** [comment]
Well, out need to find out what the error message 
```
fatal error C1083: Impossible d'ouvrir le fichier include\xa0: 'sys/un.h'\xa0:
No such file or directory
```
means and how to solve it. 
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing. Esp. try tracing the files accessed but not found (stracent is your friend).

**Comment by Goczilla** [comment]
I will try some of the things in your link, but after I will try with py2exe because it seems complicated to resolve this issue.

Thank you for the help

**Comment by Goczilla** [comment]
For information I found a workaround :
In C:\Users\myself\AppData\Local\Continuum\anaconda3\Lib\site-packages\Pyinstaller\compat.py, replace 'out = out.decode(encoding)' by 'out = out.decode(encoding, errors="ignore")'

**Comment by tallforasmurf** [comment]
there are two occurrences of that, which did you patch (or both)?

In any case, both are in `try` blocks expecting a UnicodeDecodeError to happen, with informative diagnostics printed in that case.

**Comment by yuanbo1209** [comment]
PyInstaller\lib\modulegraph\modulegraph.py,  src = loader.get_source(partname) 
File "<frozen importlib._bootstrap_external>", line 906, in get_source
  File "<frozen importlib._bootstrap_external>", line 688, in decode_source
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 5736: invalid continuation byte
What is the reason for this error?

**Comment by jafer11** [comment]
> PyInstaller\lib\modulegraph\modulegraph.py, src = loader.get_source(partname) File "", line 906, in get_source File "", line 688, in decode_source UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 5736: invalid continuation byte What is the reason for this error?

I had the same problem. Did you solve it？

**Comment by qian2020** [comment]
> > PyInstaller\lib\modulegraph\modulegraph.py, src = loader.get_source(partname) File "", line 906, in get_source File "", line 688, in decode_source UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 5736: invalid continuation byte What is the reason for this error?
> 
> I had the same problem. Did you solve it？

try to find where you use "with open" in your code. add argument “encoding = "utf-8"”. 
e.g. `with open(coorFilePath, encoding='utf-8')`
