### ISSUE TITLE
pycrypto on osx not working (as unpacked egg)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#309]
**Original date**: 2011/01/10
**Original reporter**: *mgenti AND gentiweb DOT  COOM *

I have an application that I am trying to bundle on the Mac but I can't seem to get pycrypto to work correctly.  I'm using python 2.5 and pycrypto 2.0.1 with pyinstaller svn rev 1295.  I tried the pycrypto test in the buidtests directory, but when I add the following to the spec file it fails:
```
app = BUNDLE(coll,
             name="blah",
             version="2.4.21")
```
Here is the error I am getting:
```

building BUNDLE outBUNDLE5.toc
Traceback (most recent call last):
  File "/Users/mgenti/pyinstaller/Build.py", line 1538, in <module>
    main(args[0], configfilename=opts.configfile)
  File "/Users/mgenti/pyinstaller/Build.py", line 1516, in main
    build(specfile)
  File "/Users/mgenti/pyinstaller/Build.py", line 1421, in build
    execfile(spec)
  File "test-pycrypto.spec", line 27, in <module>
    version="2.4.21")
  File "/Users/mgenti/pyinstaller/Build.py", line 1186, in __init__
    self.__postinit__()
  File "/Users/mgenti/pyinstaller/Build.py", line 298, in __postinit__
    self.assemble()
  File "/Users/mgenti/pyinstaller/Build.py", line 1252, in assemble
    shutil.copy2(fnm, tofnm)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/shutil.py", line 96, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/shutil.py", line 51, in copyfile
    fsrc = open(src, 'rb')
IOError: [Errno 20] Not a directory: '/Library/Python/2.5/site-packages/pycrypto-2.0.1-py2.5-macosx-10.6-i386.egg/Crypto/Cipher/AES.so'
```
It looks to me like it is trying to copy a file out of an egg which it can't do.

**Comment by matysek** [comment]
Closing. Support for unzipped eggs was recently implemented.
