### ISSUE TITLE
DLL libcairo-2.dll won't load in Fresh Windows 7 but works in Windows 10

### ISSUE THREAD

**Issue by leomoon** [pyinstaller/pyinstaller#3156]
Hello,

I'm having a very strange problem with loading libcairo-2.dll in Windows 7. This script works before compiling. I'm using Windows 7 to compile.

This is how I prepared the environment for compiling:
```
setup\python-3.6.4.exe /quiet InstallAllUsers=1 TargetDir=C:\Python
setx path "%path%;C:\Python;"
setup\visualcppbuildtools_full.exe /Passive
C:\Python\python -m pip install pyinstaller
C:\Python\python -m pip install six
C:\Python\python -m pip install cairosvg
pause
```

And here is the very simple main.py I want to compile using Windows 7:
```
import ctypes
import os
import sys
#include dlls
pathname = os.path.dirname(os.path.realpath(sys.argv[0]))
ctypes.windll.kernel32.SetDllDirectoryW(pathname)
ctypes.CDLL(pathname+'\\freetype6.dll')
ctypes.CDLL(pathname+'\\libcairo-2.dll')
ctypes.CDLL(pathname+'\\libexpat-1.dll')
ctypes.CDLL(pathname+'\\libfontconfig-1.dll')
ctypes.CDLL(pathname+'\\libpng14-14.dll')
ctypes.CDLL(pathname+'\\zlib1.dll')
print(pathname)
#import stuff
import cairosvg
#make svg file
svg_code = """
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 1000 1000" direction="rtl" xml:lang="fa">
		<title>...</title>
		<desc>...</desc>
		<text x="0" y="10" font-size = "22" font-family="Arial">
			<tspan x="10" dy="1.2em">Test</tspan>
		</text>
	</svg>
"""
#convert
cairosvg.svg2svg(bytestring=svg_code, write_to="converted.svg")
cairosvg.svg2pdf(bytestring=svg_code, write_to="converted.pdf")
cairosvg.svg2png(bytestring=svg_code, write_to="converted.png")
cairosvg.svg2ps (bytestring=svg_code, write_to="converted.ps")
```

The project files are:
```
main.py
freetype6.dll
libcairo-2.dll
libexpat-1.dll
libfontconfig-1.dll
libpng14-14.dll
zlib1.dll
```

And I use this command to compile:
```
C:\Python\python -m PyInstaller --add-data *.dll;. --clean --onedir --noupx --name "main-win" main.py
```

This compiles without any error and I can run the compiled version on a fresh Windows 10. But when I run the compiled version on a fresh Windows 7, I get the error below:
```
[3000] PyInstaller Bootloader 3.x
[3000] LOADER: executable is C:\Users\Admin\Desktop\main-win_debug\main-win.exe
[3000] LOADER: homepath is C:\Users\Admin\Desktop\main-win_debug
[3000] LOADER: _MEIPASS2 is NULL
[3000] LOADER: archivename is C:\Users\Admin\Desktop\main-win_debug\main-win.exe
[3000] LOADER: No need to extract files to run; setting extractionpath to homepath
[3000] LOADER: SetDllDirectory(C:\Users\Admin\Desktop\main-win_debug)
[3000] LOADER: Already in the child - running user's code.
[3000] LOADER: Python library: C:\Users\Admin\Desktop\main-win_debug\python36.dll
[3000] LOADER: Loaded functions from Python library.
[3000] LOADER: Manipulating environment (sys.path, sys.prefix)
[3000] LOADER: Pre-init sys.path is C:\Users\Admin\Desktop\main-win_debug\base_library.zip;C:\Users\Admin\Desktop\main-win_debug
[3000] LOADER: sys.prefix is C:\Users\Admin\Desktop\main-win_debug
[3000] LOADER: Setting runtime options
[3000] LOADER: Initializing python
[3000] LOADER: Overriding Python's sys.path
[3000] LOADER: Post-init sys.path is C:\Users\Admin\Desktop\main-win_debug\base_library.zip;C:\Users\Admin\Desktop\main-win_debug
[3000] LOADER: Setting sys.argv
[3000] LOADER: setting sys._MEIPASS
[3000] LOADER: importing modules from CArchive
[3000] LOADER: extracted struct
[3000] LOADER: callfunction returned...
[3000] LOADER: extracted pyimod01_os_path
[3000] LOADER: callfunction returned...
[3000] LOADER: extracted pyimod02_archive
[3000] LOADER: callfunction returned...
[3000] LOADER: extracted pyimod03_importers
[3000] LOADER: callfunction returned...
[3000] LOADER: Installing PYZ archive with Python modules.
[3000] LOADER: PYZ archive: out00-PYZ.pyz
[3000] LOADER: Running pyiboot01_bootstrap.py
[3000] LOADER: Running pyi_rth_multiprocessing.py
[3000] LOADER: Running pyi_rth_pkgres.py
[3000] LOADER: Running pyi_rth_win32comgenpy.py
[3000] LOADER: Running main.py
C:\Users\Admin\Desktop\main-win_debug
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\main.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python\lib\site-packages\cairosvg\__init__.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python\lib\site-packages\cairosvg\surface.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python\lib\site-packages\cairocffi\__init__.py", line 41, in <module>
  File "C:\Python\lib\site-packages\cairocffi\__init__.py", line 38, in dlopen
OSError: dlopen() failed to load a library: cairo / cairo-2
[3000] Failed to execute script main
[3000] LOADER: OK.
[3000] LOADER: Cleaning up Python interpreter.
```

I've included the source files here:
[src.zip](https://github.com/pyinstaller/pyinstaller/files/1590595/src.zip)

I have tested MANY different things and I can't figure this out. Could someone please help me?

Thanks.

**Comment by htgoebel** [comment]
What does the code around   File "C:\Python\lib\site-packages\cairocffi\__init__.py", line 41, and  File "C:\Python\lib\site-packages\cairocffi\__init__.py", line 38 do? Maybe this uses a hardcoded path? Or the libcairo-2.dll does not work for Win7?

**Comment by leomoon** [comment]
The compiled version works in fresh Windows 10. Only fresh Windows 7 will give this error. All DLLs are 32-bit and installed python is also 32-bit.

**Comment by leomoon** [comment]
The cairocffi does not have hardcoded paths cuz the compiled version works on Windows 10.
Also libcairo-2.dll works on Windows 7. I compile using Windows 7 and it runs from source.

So the only thing I don't understand is why the compiled version doesn't work on fresh Windows 7 but it does on fresh Windows 10.

**Comment by leomoon** [comment]
Here is a solution. Every time your program runs, it has to load the code below before any cairo call. It's best to put this at the very top of your program:
```
import os
import sys
dllpath = os.path.dirname(os.path.realpath(sys.argv[0]))
if dllpath not in os.environ:
    os.environ["PATH"] += os.pathsep + dllpath
```

**Comment by htgoebel** [comment]
Thanks for sharing the solution. I still wonder why this is necessary, but this might be Windows magic.

A run-time hook would solve this issue for others, too. Would you mind adding it? The rt-hook needs to be listed for module `cairocffi` in `PyInstaller/loader/rthooks.dat`. The rt-hook itself should be called something like `pyi_rth_add-dir-to-PATH.py`, since it may be used by other packages, too.

**Comment by leomoon** [comment]
The cairocffi does not install any DLL files. I copied these DLL files from Inkscape to the root of my python project:
freetype6.dll
libcairo-2.dll
libexpat-1.dll
libfontconfig-1.dll
libpng14-14.dll
zlib1.dll

For macOS it needs the DYLIB files below:
libcairo.dylib
libfontconfig.1.dylib
libfreetype.6.dylib
libpixman-1.0.dylib
libpng16.16.dylib

If I write a hook, how would I include DLL files?
