### ISSUE TITLE
error in hook-sysconfig: TypeError: _get_sysconfigdata_name() missing 1 required positional argument: 'check_exists'

### ISSUE THREAD

**Issue by lzkelley** [pyinstaller/pyinstaller#3192]
Steps to reproduce:

```
virtualenv env
source env/bin/activate
pip install pyinstaller numpy
echo "import numpy; print('Hello!')" >> test.py
pyinstaller test.py
```

And I get the below error message (in this case I tried to development version of pyinstaller; same error):

```
11574 INFO: Loading module hook "hook-sysconfig.py"...
Traceback (most recent call last):
  File "/Users/lzkelley/test/env/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+ab8fd9753', 'console_scripts', 'pyinstaller')()
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
    self.__postinit__()
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 472, in assemble
    module_hook.post_graph()
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/building/imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/building/imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/compat.py", line 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/lzkelley/test/env/lib/python3.6/site-packages/PyInstaller/hooks/hook-sysconfig.py", line 42, in <module>
    hiddenimports = [sysconfig._get_sysconfigdata_name()]
TypeError: _get_sysconfigdata_name() missing 1 required positional argument: 'check_exists'
```

If I comment out the `import numpy` then everything works fine (looks like `hook-sysconfig`) isn't used in that case.  it also works fine for some builtin modules (I tried `os` and `sys`), but fails for external ones (I tried `numpy`, `astropy`, and `matplotlib`).

**Comment by htgoebel** [comment]
`import sysconfig` should trigger the same issue.

Scanning through the [(Python 3.6) `blame` history of sysconfig.py}(https://github.com/python/cpython/blame/3.6/Lib/sysconfig.py) I can not find any version of this function accepting an argument `check_exists`.

Please try
```
import sysconfig
print(sysconfig.__file__)
print(sysconfig._init_posix.func_code)
```
an verify it is the correct file.

**Comment by cateee** [comment]
I have the same problem.
Running the above code I get:

```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> print(sysconfig.__file__)
/Users/cate/miniconda3/envs/RH2/lib/python3.6/sysconfig.py
>>> print(sysconfig._init_posix.func_code)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'func_code'
```

and the function is:
```
def _get_sysconfigdata_name(check_exists):
    res = os.environ.get('_PYTHON_SYSCONFIGDATA_NAME', None)
    if res and check_exists:
        try:
            loader = importlib.util.find_spec(res)
        except:
            res = None
    if res:
        return res
    return '_sysconfigdata_{abi}_{platform}_{multiarch}'.format(
            abi=sys.abiflags,
            platform=sys.platform,
            multiarch=getattr(sys.implementation, '_multiarch', ''))

```

So it seems an anaconda "extension".

**Comment by htgoebel** [comment]
> So it seems an anaconda "extension".

Please get in touch with the anaconda people then. We can not support their distribution an longer if they add incompatible changes.

**Comment by moonshoes87** [comment]
This issue was fixed for me by fully uninstalling and reinstalling Anaconda.  That isn't a very satisfactory answer, but it did allow me to continue using Pyinstaller.

**Comment by FSund** [comment]
I had the same issue on a fresh Miniconda install today, but the issue was solved after updating conda (`conda update conda`) and updating all packages (`conda update --all`).

**Comment by makman09** [comment]
I had the same issue before, changing the conda environment's python to 3.5.1 removed that error.

**Comment by LiBingtao** [comment]
I had the same issue.I just copy the /Users/libingtao/anaconda3/lib/python3.6/sysconfig.py to /Users/libingtao/anaconda3/envs/tensorflow/lib/python3.6 and replace the exited sysconfig.py.

**Comment by htgoebel** [comment]
I suggest you get in touch with the anaconda people. We can not support their distribution any longer if they add incompatible changes.

**Comment by fgoudreault** [comment]
I had the same error (with anaconda as well), but only with python version 3.6.4. If I downgrade to 3.6.3, the error disappears.

**Comment by htgoebel** [comment]
@fgoudreault I suggest you get in touch with the anaconda people. We can not support their distribution any longer if they add incompatible changes.

**Comment by FSund** [comment]
This seems to be fixed in the latest conda version. Not sure what versions are affected, but at least it works.

The following code works fine now. Remember to run `conda update conda` first if you haven't updated conda in a while.

    conda create --name test python=3
    conda activate test
    pip install pyinstaller numpy
    echo "import numpy; print('Hello!')" >> test.py
    pyinstaller test.py

**Comment by gabegm** [comment]
Currently have the same problem. Creating a conda environment with py3.6.4 worked.

**Comment by htgoebel** [comment]
### If you experience this issue, update your conda installation.
