### ISSUE TITLE
--add-binary sourcedir;. is not working with pyhton 2.7.14 and windows 10

### ISSUE THREAD

**Issue by christianhaessler** [pyinstaller/pyinstaller#3237]
If you try to build a package with the option `--add-binary` and you decide to set the target to `.` you get the following `access denied` error. If you are you are using `--add-data` it works. If you are using Python 3.6 it works as well. Same problem without the `--onefile` option:

```
c:\Python27\python.exe -m PyInstaller -y --add-binary C:\some_dir\instantclient-basiclite-windows.x64-12.2.0.1.0\instantclient_12_2;. C:\some_dir\git_scripts\oracle_build\oracle_check.py --onefile
280 INFO: PyInstaller: 3.4.dev0+ab8fd9753
280 INFO: Python: 2.7.14
281 INFO: Platform: Windows-10-10.0.16299
282 INFO: wrote C:\some_dir\pycompile\oracle_check.spec
284 INFO: UPX is not available.
286 INFO: Extending PYTHONPATH with paths
['C:\\some_dir\\git_scripts\\oracle_build',
 'C:\\some_dir\\pycompile']
286 INFO: checking Analysis
299 INFO: Appending 'binaries' from .spec
302 INFO: checking PYZ
315 INFO: checking PKG
317 INFO: Building because toc changed
319 INFO: Building PKG (CArchive) out00-PKG.pkg
497 ERROR: C:\Users\my_user\AppData\Roaming\pyinstaller\bincache00_py27_64bit\oraons.dll
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\lib\site-packages\PyInstaller\__main__.py", line 101, in <module>
    run()
  File "c:\Python27\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "c:\Python27\lib\site-packages\PyInstaller\building\api.py", line 411, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "c:\Python27\lib\site-packages\PyInstaller\building\api.py", line 196, in __init__
    self.__postinit__()
  File "c:\Python27\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\Python27\lib\site-packages\PyInstaller\building\api.py", line 259, in assemble
    dist_nm=inm)
  File "c:\Python27\lib\site-packages\PyInstaller\building\utils.py", line 276, in checkCache
    res = winmanifest.GetManifestResources(os.path.abspath(cachedfile))
  File "c:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1005, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "c:\Python27\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 168, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
pywintypes.error: (5, 'LoadLibraryEx', 'Zugriff verweigert')
```

The reason i need to put the libraries direct to the root directory is the fact i cannot set the PATH (in windows) or the LD_LIBRARY_PATh (in linux) to a subdirectory for example `instantclient`.

**Comment by htgoebel** [comment]
`--add-binary` will try to analyze the binary, while data-files are not analyzed. Please check *why* access is denied. `pywintypes.error: (5` should point you into the direction.

**Comment by christianhaessler** [comment]
Thanks for your reply. The easy solution was to remove this directory:
`C:\Users\my_user\AppData\Roaming\pyinstaller\bincache00_py27_64bit` and start the build again.
