### ISSUE TITLE
GDAL SWIG import broken again

### ISSUE THREAD

**Issue by davidh-ssec** [pyinstaller/pyinstaller#3248]
As the person who originally fixed this issue I was surprised to find that it is broken again. I'm using a conda python 3.6 environment with gdal 2.1.3 and am testing on Linux (CentOS 6). For historical purposes see PRs #3043 and #2578. I'm not sure how this error got passed through last time, but part of it is that I built my project with my own commit in #3043 and then never actually tested it assuming it worked. Regardless, the current develop doesn't work. Simple test script:

```
import gdal
```

Result of executing the created executable:

```
Traceback (most recent call last):
  File "site-packages/osgeo/__init__.py", line 11, in swig_import_helper
  File "imp.py", line 296, in find_module
ImportError: No module named '_gdal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from osgeo import gdal
  File "/data1/users/davidh/repos/git/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/osgeo/__init__.py", line 21, in <module>
  File "site-packages/osgeo/__init__.py", line 13, in swig_import_helper
ModuleNotFoundError: No module named '_gdal'
```

Using `git bisect` I've tracked it down to this commit:

```
2946ad57c5c93d9125e13301d286f78b8d9671ea is the first bad commit
commit 2946ad57c5c93d9125e13301d286f78b8d9671ea
Author: Hartmut Goebel <h.goebel@crazy-compilers.com>
Date:   Tue Nov 28 21:48:41 2017 +0100

    modulegraph: Reimport failed SWIG C module relative to the wrapper module.
    
    The C modules are expected to live beside the wrapper, it should
    always be imported relative to the wrapper.
```

This commit did the following to the `modulegraph.py` module:

```
diff --git a/PyInstaller/lib/modulegraph/modulegraph.py b/PyInstaller/lib/modulegraph/modulegraph.py
index ae2a8ce..578fce4 100644
--- a/PyInstaller/lib/modulegraph/modulegraph.py
+++ b/PyInstaller/lib/modulegraph/modulegraph.py
@@ -2325,10 +2325,10 @@ class ModuleGraph(ObjectGraph):
             # fine to remove because the proper module will be imported and
             # added to the graph in the next line (call to _safe_import_hook).
             self.removeNode(target_module)
-            # Reimport the SWIG C module
+            # Reimport the SWIG C module relative to the wrapper
             target_modules = self._safe_import_hook(
                 target_module_partname, source_module,
-                target_attr_names=None, level=level, edge_attr=edge_attr)
+                target_attr_names=None, level=1, edge_attr=edge_attr)
             # return the output regardless because it would just be
             # duplicating the processing below
             return target_modules
```

Change to `level=level` makes it work for my example. So the question is @htgoebel is this change still necessary? What this change perhaps a guess at a solution when debugging the recursive import, but my commit made it unnecessary? My commit did come after this one of yours in the commit history.

**Comment by davidh-ssec** [comment]
@htgoebel Have you had any time to look at this?

**Comment by giumas** [comment]
I am having the same issue on Windows 10, using PyInstaller (both 3.3.1 and latest `develop`), Python 3.6 and Anaconda's GDAL package (both 2.2.3 and 2.1.3).

Even using the @davidh-ssec 's change (`level=level`), it crashes:

```
  File "site-packages\osgeo\__init__.py", line 25, in <module>
  File "site-packages\osgeo\__init__.py", line 17, in swig_import_helper
  File "c:\users\gmasetti\appdata\local\hyoc\py3\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: DLL load failed: The specified procedure could not be found.
```

but with the @davidh-ssec 's change **AND** using the [Gohlke's GDAL wheel](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal), it works! So @davidh-ssec there might be more than one issue going on there related to the use of Anaconda's GDAL package.

In this latter configuration, I noticed a difference between running PyInstaller 3.3.1 with and without the @davidh-ssec 's change: 

* Without (original 3.3.1), the output folder has a file named `osgeo._gdal.pyd` (while all the other GDAL `.pyd`s do not start with `osgeo.`: e.g., `_osr.pyd`). 
* With `level=level`, there is a file named `_gdal.pyd` (and the frozen app works). It also works if I manually rename `ogeo._gdal.pyd` to `_gdal.pyd`. 

@htgoebel, do you have any thought on this?

**Comment by giumas** [comment]
I can confirm that the above fix (or simply renaming `osgeo._gdal.pyd` as `_gdal.pyd`) works using the following Conda virtual environment (on Windows):
```
altgraph                  0.15                      <pip>
conda                     4.4.10                   py36_0
gdal                      2.2.3                    py36_0    conda-forge
libgdal                   2.2.3                    vc14_3  [vc14]  conda-forge
macholib                  1.9                       <pip>
mkl                       2018.0.1             h2108138_4
numpy                     1.12.1           py36hf30b8aa_1
pefile                    2017.11.5                 <pip>
proj4                     4.9.3                    vc14_5  [vc14]  conda-forge
PyInstaller               3.3.1                     <pip>
python                    3.6.4                h6538335_1
pywin32                   222              py36hfa6e2cd_0
setuptools                38.4.0                   py36_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
```

**Comment by marcofavale** [comment]
Same problem here: Windows 10, Python 3.6, PyInstaller 3.3.1, Gohlke's GDAL wheel. Produces osgeo._gdal.pyd in the output file; renaming to _gdal.pyd works.

**Comment by djhoese** [comment]
@austinorr @marcofavale @swarn Try installing pyinstaller from the `develop` branch on github. This error went away for me from what I could tell with this version of pyinstaller.

**Comment by austinorr** [comment]
@djhoese thanks for the hint, I’ll run a diff on dev tomorrow to try to track this down. Before I do that, do you happen to know of a PR that targeted this specifically, or was the fix on dev a virtuous side effect? I need my production build process to be reproducible, so I prefer to patch a standard install with a hook (if it’s possible) instead of installing from a dev commit.

**Comment by austinorr** [comment]
here's a hack for my .spec file that helped me get this working this morning. I'm posting for posterity for other `gdal` aficionados:
```
from PyInstaller.utils.hooks import collect_data_files
_osgeo_pyds = collect_data_files('osgeo', include_py_files=True)

osgeo_pyds = []
for p, lib in _osgeo_pyds:
    if '.pyd' in p:
        osgeo_pyds.append((p, ''))

binaries = osgeo_pyds + [
    # your binaries if any
]

# add the `osgeo_pyds` to your binaries in your Analysis() function.
a = Analysis(['your_main_script.py'],
    # ... your kwargs
    binaries=binaries,
    # ... your kwargs
)
```
you'll end up with dupes of the ones that were found and placed properly (which I can live with for right now). I tried to rename them in the packaged destination so there wouldn't be dupes, but i couldn't figure out how to add them with a different name. If anyone does know, i'd love to hear.

**Comment by htgoebel** [comment]
@djhoese @giumas @swarn @marcofavale @austinorr To fix this issue (and ensure it will no pop up again) what is needed first of all is a test-case in the test-suite. The test-suite already contains some SWIG related tests, which obviously do not cover this setup (since if they would, this issue would not arise).

Tests are in `tests/unit/test_modulegraph_more.py` and `tests/unit/test_modulegraph/test_swig.py`. Please add new test-cases there. Since we plan to switch to modulegraph2, this will get important soon *).  Many thanks.
