### ISSUE TITLE
'NotImplementedError: the qt4 pyface backend doesn't implement MenuManager' when freezing enthought (mayavi)

### ISSUE THREAD

**Issue by jorgesmok** [pyinstaller/pyinstaller#3274]
I'm trying to freeze a GUI project on python 3.5, it uses PyQt4, matplotlib, mayavi and some others packages. However, it seems like the package that is giving me trouble is mayavi and it's related modules (pyface, traitsui). When I use pyinstaller it actually creates the executable folder (with some warnings), but when I excecute the .exe (from command windows) I get the following: 

`NotImplementedError: the qt4 pyface backend doesn't implement MenuManager`

This is the command I'm using to freeze it:

`pyinstaller.exe --onedir --hidden-import traitsui.qt4 --hidden-import pyface.ui --hidden-import pyface.ui.qt4 --hidden-import pyface.ui.qt4.init --noupx --debug main.pyw`

Wich gives:

```
1246 INFO: PyInstaller: 3.4.dev0+5f9190544
1247 INFO: Python: 3.5.3
1249 INFO: Platform: Windows-10-10.0.16299-SP0
1260 INFO: wrote D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\main.spec
1264 INFO: UPX is not available.
1274 INFO: Extending PYTHONPATH with paths
['D:\\Jorge\\Desktop\\DISANT 4\\dropbox\\descarga\\DISANT4-master',
 'D:\\Jorge\\Desktop\\DISANT 4\\dropbox\\descarga\\DISANT4-master\\DISANT4']
1278 INFO: checking Analysis
1279 INFO: Building Analysis because out00-Analysis.toc is non existent
1280 INFO: Initializing module dependency graph...
1299 INFO: Initializing module graph hooks...
1320 INFO: Analyzing base_library.zip ...
17235 INFO: Analyzing hidden import 'traitsui.qt4'
20021 INFO: Processing pre-safe import module hook   win32com
25476 INFO: Processing pre-find module path hook   distutils
43920 INFO: Processing pre-find module path hook   site
43939 INFO: site: retargeting to fake-dir 'C:\\ProgramData\\Anaconda3\\envs\\py35\\lib\\site-packages\\PyInstaller\\fake-modules'
70618 INFO: Analyzing hidden import 'pyface.ui.qt4.init'
70637 INFO: running Analysis out00-Analysis.toc
70644 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\ProgramData\Anaconda3\envs\py35\python.exe
72135 INFO: Caching module hooks...
72150 INFO: Analyzing D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\main.pyw
72638 INFO: Processing pre-find module path hook   PyQt4.uic.port_v3
72816 INFO: Processing pre-find module path hook   PyQt4.uic.port_v2
89723 INFO: Processing pre-safe import module hook   requests.packages.urllib3.packages.six.moves
102444 INFO: Processing pre-safe import module hook   six.moves
201396 INFO: Loading module hooks...
201396 INFO: Loading module hook "hook-pycparser.py"...
201851 INFO: Loading module hook "hook-setuptools.py"...
201961 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
201961 INFO: Loading module hook "hook-lib2to3.py"...
201976 INFO: Loading module hook "hook-distutils.py"...
201992 INFO: Loading module hook "hook-matplotlib.py"...
203102 INFO: Loading module hook "hook-sysconfig.py"...
203150 INFO: Loading module hook "hook-PIL.Image.py"...
204244 INFO: Loading module hook "hook-_tkinter.py"...
204634 INFO: checking Tree
204634 INFO: Building Tree because out00-Tree.toc is non existent
204634 INFO: Building Tree out00-Tree.toc
204775 INFO: checking Tree
204775 INFO: Building Tree because out01-Tree.toc is non existent
204775 INFO: Building Tree out01-Tree.toc
204813 INFO: Loading module hook "hook-PyQt4.QtSvg.py"...
204823 INFO: Loading module hook "hook-cryptography.py"...
206881 INFO: Loading module hook "hook-pytz.py"...
207006 INFO: Loading module hook "hook-numpy.core.py"...
207150 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
207166 INFO: Loading module hook "hook-xml.py"...
207166 INFO: Loading module hook "hook-encodings.py"...
207338 INFO: Loading module hook "hook-xml.dom.domreg.py"...
207338 INFO: Loading module hook "hook-pygments.py"...
214367 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
214383 INFO: Excluding import 'tkinter'
214383 INFO: Import to be excluded not found: 'FixTk'
214383 INFO: Loading module hook "hook-pythoncom.py"...
215576 INFO: Loading module hook "hook-PIL.py"...
215576 INFO: Excluding import 'PyQt5'
215591 INFO:   Removing import of PyQt5 from module PIL.ImageQt
215591 INFO: Excluding import 'PySide'
215607 INFO: Excluding import 'PyQt4'
215623 INFO:   Removing import of PyQt4.QtGui from module PIL.ImageQt
215623 INFO:   Removing import of PyQt4.QtCore from module PIL.ImageQt
215623 INFO: Excluding import 'tkinter'
215623 INFO:   Removing import of tkinter from module PIL.ImageTk
215623 INFO: Import to be excluded not found: 'FixTk'
215623 INFO: Loading module hook "hook-pywintypes.py"...
216307 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
216307 INFO: Loading module hook "hook-jsonschema.py"...
216323 INFO: Loading module hook "hook-win32com.py"...
217931 INFO: Loading module hook "hook-PyQt4.QtGui.py"...
218603 INFO: Loading module hook "hook-sqlite3.py"...
218811 INFO: Loading module hook "hook-scipy.linalg.py"...
218811 INFO: Loading module hook "hook-jinja2.py"...
218873 INFO: Loading module hook "hook-PyQt4.Qt.py"...
218873 WARNING: Hidden import "PyQt4.QtAssistant" not found!
218873 WARNING: Hidden import "PyQt4.Qt3Support" not found!
218873 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
218889 INFO: Loading module hook "hook-lxml.etree.py"...
218936 INFO: Loading module hook "hook-PyQt4.QtWebKit.py"...
218936 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
218967 INFO: Loading module hook "hook-pydoc.py"...
218983 INFO: Loading module hook "hook-PyQt4.uic.py"...
218998 INFO: Loading module hook "hook-pytest.py"...
222899 INFO: Loading module hook "hook-shelve.py"...
222946 INFO: Loading module hook "hook-requests.py"...
222946 INFO: Loading module hook "hook-zmq.py"...
230132 WARNING: Hidden import "fatal" not found!
230132 WARNING: Hidden import "No" not found!
230132 WARNING: Hidden import "_cffi_ext.c" not found!
230257 WARNING: Hidden import "file" not found!
230257 WARNING: Hidden import "Cannot" not found!
230257 WARNING: Hidden import "'sys/un.h':" not found!
230257 WARNING: Hidden import "directory" not found!
230273 WARNING: Hidden import "C1083:" not found!
230273 WARNING: Hidden import "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(209):" not found!
230273 WARNING: Hidden import "or" not found!
230523 WARNING: Hidden import "error" not found!
230523 WARNING: Hidden import "such" not found!
230523 WARNING: Hidden import "open" not found!
230523 WARNING: Hidden import "file:" not found!
230538 INFO: Excluding import 'zmq.libzmq'
230538 INFO:   Removing import of zmq.libzmq from module zmq
230538 INFO: Loading module hook "hook-IPython.py"...
230570 INFO: Excluding import 'PyQt5'
230585 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
230585 INFO: Excluding import 'gtk'
230601 INFO: Excluding import 'PyQt4'
230617 INFO:   Removing import of PyQt4.QtSvg from module IPython.external.qt_loaders
230617 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
230617 INFO:   Removing import of PyQt4.QtGui from module IPython.external.qt_loaders
230617 INFO:   Removing import of PyQt4.QtCore from module IPython.external.qt_loaders
230632 INFO: Excluding import 'matplotlib'
230632 INFO:   Removing import of matplotlib from module IPython.lib.latextools
230632 INFO:   Removing import of matplotlib.mathtext from module IPython.lib.latextools
230632 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
230632 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
230632 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
230648 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
230648 INFO: Excluding import 'PySide'
230663 INFO:   Removing import of PySide from module IPython.external.qt_loaders
230663 INFO: Excluding import 'tkinter'
230695 INFO:   Removing import of tkinter from module IPython.lib.clipboard
230695 INFO: Loading module hook "hook-PyQt4.QtSql.py"...
230837 INFO: Loading module hook "hook-PyQt4.QtCore.py"...
230978 INFO: Loading module hook "hook-pkg_resources.py"...
232510 INFO: Loading module hook "hook-matplotlib.backends.py"...
233636 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
235867 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
236384 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
237167 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
238076 INFO:   Matplotlib backend "Qt4Agg": added
238963 INFO:   Matplotlib backend "Qt5Agg": added
240062 INFO:   Matplotlib backend "TkAgg": added
240837 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
241603 INFO:   Matplotlib backend "WXAgg": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
242235 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
243139 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
246345 INFO:   Matplotlib backend "WebAgg": added
252954 INFO:   Matplotlib backend "nbAgg": added
253696 INFO:   Matplotlib backend "agg": added
254213 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
254746 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
255591 INFO:   Matplotlib backend "pdf": added
256700 INFO:   Matplotlib backend "pgf": added
257797 INFO:   Matplotlib backend "ps": added
258863 INFO:   Matplotlib backend "svg": added
259641 INFO:   Matplotlib backend "template": added
260301 INFO: Loading module hook "hook-certifi.py"...
260311 INFO: Loading module hook "hook-PyQt4.py"...
260341 INFO: Loading module hook "hook-PyQt4.QtNetwork.py"...
260487 INFO: Loading module hook "hook-PyQt4.QtTest.py"...
260495 INFO: Loading module hook "hook-PyQt4.QtOpenGL.py"...
260503 INFO: Loading module hook "hook-PyQt4.QtXml.py"...
260512 INFO: Loading module hook "hook-gevent.monkey.py"...
260980 INFO: checking Tree
260981 INFO: Building Tree because out02-Tree.toc is non existent
260982 INFO: Building Tree out02-Tree.toc
261061 INFO: Looking for ctypes DLLs
261451 INFO: Analyzing run-time hooks ...
261587 INFO: Including run-time hook 'pyi_rth_pkgres.py'
261614 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
261633 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
261660 INFO: Including run-time hook 'pyi_rth__tkinter.py'
261672 INFO: Including run-time hook 'pyi_rth_traitlets.py'
261681 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
261694 INFO: Including run-time hook 'pyi_rth_mpldata.py'
261705 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
261841 INFO: Looking for dynamic libraries
266482 WARNING: lib not found: mpich2mpi.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_blacs_mpich2_ilp64.dll
286713 WARNING: lib not found: impi.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_blacs_intelmpi_lp64.dll
289943 WARNING: lib not found: pgf90rtl.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_pgi_thread.dll
290052 WARNING: lib not found: pgc14.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_pgi_thread.dll
290157 WARNING: lib not found: pgf90.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_pgi_thread.dll
290343 WARNING: lib not found: impi.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_blacs_intelmpi_ilp64.dll
291969 WARNING: lib not found: msmpi.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_blacs_msmpi_lp64.dll
296836 WARNING: lib not found: mpich2mpi.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_blacs_mpich2_lp64.dll
298023 WARNING: lib not found: msmpi.dll dependency of C:\ProgramData\Anaconda3\envs\py35\Library\bin\mkl_blacs_msmpi_ilp64.dll
334556 INFO: Looking for eggs
334556 INFO: Using Python library C:\ProgramData\Anaconda3\envs\py35\python35.dll
334556 INFO: Found binding redirects:
[]
334634 INFO: Warnings written to D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\build\main\warnmain.txt
335961 INFO: Graph cross-reference written to D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\build\main\xref-main.html
336680 INFO: checking PYZ
336680 INFO: Building PYZ because out00-PYZ.toc is non existent
336680 INFO: Building PYZ (ZlibArchive) D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\build\main\out00-PYZ.pyz
Syntax error in  C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\jinja2\asyncsupport.py
("'yield' inside async function", ('C:\\ProgramData\\Anaconda3\\envs\\py35\\lib\\site-packages\\jinja2\\asyncsupport.py', 35, 12, '            yield event\n'))
347170 INFO: Building PYZ (ZlibArchive) D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\build\main\out00-PYZ.pyz completed successfully.
347404 INFO: checking PKG
347404 INFO: Building PKG because out00-PKG.toc is non existent
347420 INFO: Building PKG (CArchive) out00-PKG.pkg
348098 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
348113 INFO: Bootloader C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run_d.exe
348113 INFO: checking EXE
348113 INFO: Building EXE because out00-EXE.toc is non existent
348113 INFO: Building EXE from out00-EXE.toc
348113 INFO: Appending archive to EXE D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\build\main\main.exe
348337 INFO: Building EXE from out00-EXE.toc completed successfully.
348369 INFO: checking COLLECT
348369 INFO: Building COLLECT because out00-COLLECT.toc is non existent
348369 INFO: Building COLLECT out00-COLLECT.toc
447285 INFO: Building COLLECT out00-COLLECT.toc completed successfully.
```

And when I excecute the .exe this is what I get:

```
[22616] PyInstaller Bootloader 3.x
[22616] LOADER: executable is D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main\main.exe
[22616] LOADER: homepath is D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main
[22616] LOADER: _MEIPASS2 is NULL
[22616] LOADER: archivename is D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main\main.exe
[22616] LOADER: No need to extract files to run; setting extractionpath to homepath
[22616] LOADER: SetDllDirectory(D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main)
[22616] LOADER: Already in the child - running user's code.
[22616] LOADER: Python library: D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main\python35.dll
[22616] LOADER: Loaded functions from Python library.
[22616] LOADER: Manipulating environment (sys.path, sys.prefix)
[22616] LOADER: Pre-init sys.path is D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main\base_library.zip;D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main
[22616] LOADER: sys.prefix is D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main
[22616] LOADER: Setting runtime options
[22616] LOADER: Initializing python
[22616] LOADER: Overriding Python's sys.path
[22616] LOADER: Post-init sys.path is D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main\base_library.zip;D:\Jorge\Desktop\DISANT 4\dropbox\descarga\DISANT4-master\DISANT4\dist\main
[22616] LOADER: Setting sys.argv
[22616] LOADER: setting sys._MEIPASS
[22616] LOADER: importing modules from CArchive
[22616] LOADER: extracted struct
[22616] LOADER: callfunction returned...
[22616] LOADER: extracted pyimod01_os_path
[22616] LOADER: callfunction returned...
[22616] LOADER: extracted pyimod02_archive
[22616] LOADER: callfunction returned...
[22616] LOADER: extracted pyimod03_importers
[22616] LOADER: callfunction returned...
[22616] LOADER: Installing PYZ archive with Python modules.
[22616] LOADER: PYZ archive: out00-PYZ.pyz
[22616] LOADER: Running pyiboot01_bootstrap.py
[22616] LOADER: Running pyi_rth_pkgres.py
[22616] LOADER: Running pyi_rth_multiprocessing.py
[22616] LOADER: Running pyi_rth_win32comgenpy.py
[22616] LOADER: Running pyi_rth__tkinter.py
[22616] LOADER: Running pyi_rth_traitlets.py
[22616] LOADER: Running pyi_rth_mplconfig.py
[22616] LOADER: Running pyi_rth_mpldata.py
[22616] LOADER: Running pyi_rth_qt4plugins.py
[22616] LOADER: Running main.py
Traceback (most recent call last):
  File "DISANT4\main.pyw", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "DISANT4\nec\gui\windows\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "DISANT4\nec\gui\windows\wires.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "DISANT4\nec\gui\tools\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "DISANT4\nec\gui\tools\formayavi.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\api.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\editors\__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\editors\api.py", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\editors\table_editor.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\table_filter.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\menu.py", line 128, in <module>
  File "site-packages\pyface\toolkit.py", line 124, in __init__
NotImplementedError: the qt4 pyface backend doesn't implement MenuManager
[22616] Failed to execute script main
[22616] LOADER: OK.
[22616] LOADER: Cleaning up Python interpreter.
```

As you see I'm already using the latest development version, --onedir mode, --noupx and --debug. Previous to this error I'd gotten some `ImportErrors` which I fixed using the _hidden imports_ I specified in the pyinstaller line.

I've done some research and I found this on SO, which is exactly the same error I'm getting but he was using wx:
https://stackoverflow.com/questions/35561635/packaging-a-python-application-with-enthought-matplotlib-wxpython-into-exec

He solved it by using cx_freeze, but before going that way I thought I would ask here and see if anyone could give me some help.

**Comment by jamanabanana** [comment]
I have a similar issue. Same idea, trying to build a standalone exe which uses mayavi. I too include those hidden imports however I get a different error when trying to run the resultant .exe

`RuntimeError: No traitsui.toolkits plugin found for toolkit qt4`

For reference, I am using pyinstaller 3.3.1 (the lastest development version kept giving me a separate error about 'str' not having an item method or something similar), python 3.6, mayavi 4.5.0+vtk81, and on Windows 10.

The full traceback is below:

```
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\mayavi\mlab.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\mayavi\tools\camera.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\mayavi\tools\engine_manager.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\mayavi\preferences\api.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\mayavi\preferences\preference_manager.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\api.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\editors\__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\editors\api.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\traitsui\editors\code_editor.py", line 37, in <module>
  File "site-packages\traitsui\editors\code_editor.py", line 49, in ToolkitEditorFactory
  File "site-packages\traits\traits.py", line 522, in __call__
  File "site-packages\traits\traits.py", line 1236, in Color
  File "site-packages\traitsui\toolkit_traits.py", line 8, in ColorTrait
  File "site-packages\traitsui\toolkit.py", line 109, in toolkit
  File "site-packages\pyface\base_toolkit.py", line 263, in find_toolkit
  File "site-packages\pyface\base_toolkit.py", line 209, in import_toolkit
RuntimeError: No traitsui.toolkits plugin found for toolkit qt4
```

I posted a question on the traitsui GitHub and they mentioned that it may be due to indirect importing used by traitsui and pyface, but I was under the impression that including the hidden imports should fix that issue. I'm at a loss of what to do... I have searched for missing modules and gone through the "Make sure it is a bug" page but from what I can tell I am including all the hidden imports. I haven't seen anything online mentioning someone successfully building an exe for a mayavi application using pyinstaller either so I would like to write a hook if I can figure out which directories are missing.

**Comment by Legorooj** [comment]
Closing; stale and PyQt4 is no longer supported.
