### ISSUE TITLE
pyinstall cannot build pypcap in windows 10 64bit。

### ISSUE THREAD

**Issue by jackadam1981** [pyinstaller/pyinstaller#3282]
i try build exe with pyinstaller.

the test.py is 
`print('hello')`

the warntest.txt
```
missing module named resource - imported by posix, D:\PythonTest\\test.py
missing module named posix - imported by os, D:\PythonTest\\test.py
missing module named _posixsubprocess - imported by subprocess, D:\PythonTest\\test.py
missing module named 'org.python' - imported by pickle, D:\PythonTest\\test.py, xml.sax
missing module named readline - imported by cmd, code, pdb, D:\PythonTest\\test.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, D:\PythonTest\\test.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, D:\PythonTest\\test.py
missing module named _winreg - imported by platform, D:\PythonTest\\test.py
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, D:\PythonTest\\test.py
missing module named 'java.lang' - imported by platform, D:\PythonTest\\test.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, D:\PythonTest\\test.py
missing module named termios - imported by tty, D:\PythonTest\\test.py, getpass
missing module named grp - imported by shutil, tarfile, D:\PythonTest\\test.py
missing module named pwd - imported by posixpath, shutil, tarfile, http.server, webbrowser, D:\PythonTest\\test.py, netrc, getpass
missing module named _dummy_threading - imported by dummy_threading, D:\PythonTest\\test.py
missing module named org - imported by copy, D:\PythonTest\\test.py
```

dist test.exe work on some computer.

then i try add code with pypcap:
```
import pcap
pc = pcap.pcap()
for d,b in pc:
    print(d,b)
```

pyinstaller test.py

```
the warntest.txt same old one. no missing pcap or pypcap.
missing module named resource - imported by posix, D:\PythonTest\\test.py
missing module named posix - imported by os, D:\PythonTest\\test.py
missing module named _posixsubprocess - imported by subprocess, D:\PythonTest\\test.py
missing module named org - imported by pickle, D:\PythonTest\\test.py
missing module named readline - imported by cmd, code, pdb, D:\PythonTest\\test.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, D:\PythonTest\\test.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, D:\PythonTest\\test.py
missing module named _winreg - imported by platform, D:\PythonTest\\test.py
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, D:\PythonTest\\test.py
missing module named 'java.lang' - imported by platform, D:\PythonTest\\test.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, D:\PythonTest\\test.py
missing module named termios - imported by tty, D:\PythonTest\\test.py, getpass
missing module named grp - imported by shutil, tarfile, D:\PythonTest\\test.py
missing module named pwd - imported by posixpath, shutil, tarfile, http.server, webbrowser, D:\PythonTest\\test.py, netrc, getpass
missing module named _dummy_threading - imported by dummy_threading, D:\PythonTest\\test.py
missing module named 'org.python' - imported by copy, D:\PythonTest\\test.py, xml.sax

```
dist test.exe worked  on my build computer.
the other computer prompt DLL load failed:

```
PS C:\Users\Jack\Desktop\dist\test> .\test.exe
hello
Traceback (most recent call last):
  File "test.py", line 10, in <module>
  File "D:\PythonEnvi\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
ImportError: DLL load failed: 找不到指定的模块。
[2360] Failed to execute script test
```

the line 10 is :
import pcap

so i try other way :
pyinstaller.exe --hidden-import pcap test.py
pyinstaller.exe -p D:\PythonEnvi\Lib\site-packages --hidden-import pcap D:\PythonTest\\test.py

https://github.com/pynetwork/pypcap
the pcap homepage.

windows10 Home 64bit 
python 3.63
pyinstaller 3.3.1
pypcap 1.20
npcap 0.98 installer
npcap sdd 0.1
Microsoft Visual C++ Build Tools 2015

**Comment by jackadam1981** [comment]
https://github.com/pynetwork/pypcap
the pcap homepage.

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing. Esp use `NTstrace` to find which dll is missing.

We would appreciate if you'd submit a hook for this. See https://pyinstaller.readthedocs.org/en/latest/hooks.html for more information about how to implement hooks.

**Comment by jackadam1981** [comment]
my englist is bad.
can't  understand hooks.
so try get some help.

**Comment by Kerang** [comment]
Did you install the [Windows 10 SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk)?

I'm pretty sure I had the same issue with an executable not running on a different computer when I hadn't included the ucrt files:

x86: (32-bit windows)
`pathex=['C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86']`

x64: (64-bit windows)
`pathex=['C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64']`

**Comment by jackadam1981** [comment]
I fix the problem.
pypcap need npcap and winpcap API.
different computer  install npcap with winpcapAPI。
then build exe work on different computer。

**Comment by htgoebel** [comment]
> Accidentally ，I solved the problem

**Comment by arossert** [comment]
Can anyone tell me if this is possible? 
I'm trying to bundle a `winpcap` app ut cannot understand how to include the dlls.

**Comment by htgoebel** [comment]
@arossert See above: You need to create a hook.

**Comment by arossert** [comment]
@htgoebel thanks for the response but can you please point me to how can I achieve this with a hook?

From this conversation, it is hard to understand what needs to be done.
I have created some hooks to some modules but all of them was to include some modules or source files and never external DLLs, so I'm a bit confused about how to begin.

**Comment by htgoebel** [comment]
Just read hte manual an look at other hooks. You need to add the dll as `binaries`.

**Comment by arossert** [comment]
@htgoebel I have tried to manually copy the files that are installed from [Npcap](https://nmap.org/npcap/) to the target PyInstaller directory but still getting the DLL error exception.
The files are `Packet.lib` & `wpcap.lib`, do you have any idea how to make it work?
This is the simple example that i'm trying to build:
```
import pcapy
```

if the target machine has no Npcao/winpcap installed it is throwing the DLL exception.

**Comment by bjones1** [comment]
You don't need `.lib` files (static libraries used to compile an application), but the `.dll` files.

**Comment by arossert** [comment]
@bjones1 thanks, this was my mistake.
I have successfully created a hook that takes the `Packet.dll` & `wpcap.dll` from the system32 lib and includes them in the final directory but when I copied it to another machine it is not working, I'm getting this error:
```
pcapy.PcapError: No valid interfaces to open
```

If I install the winpcap/npcap library and remove the DLLs from my application directory it is working so I'm not sure that it is even possible.

It might be because I have built it on win7 and tested it on win10, is there a way to make it portable?

**Comment by Legorooj** [comment]
What is the status on this?
