### ISSUE TITLE
depend/dylib.py should exclude libdrm

### ISSUE THREAD

**Issue by ljbade** [pyinstaller/pyinstaller#3286]
We have encountered a problem when building an application that uses PySide on Ubuntu 14.04. If you try to run the binary on an Ubuntu 16.04 machine that uses Mesa for graphics (for example Intel GPU but not NVIDIA GPU) you will a symbol not found error like this:
```
ImportError: Unable to import the image backend for the qt4 toolkit (reason: ['ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2\n']).
```

Google reveals similar problems with other Python apps packged using PyInstaller.

The workaround is to go and delete libdrm.so.2 from the package after building it.

However it seems that https://github.com/pyinstaller/pyinstaller/blob/master/PyInstaller/depend/dylib.py has an excludes list to handle these sorts of issues and already excludes libGL.

Can libdrm be added to this list too?

**Comment by htgoebel** [comment]
Please provide a pull-request and describe the (pro & cons) implications of excluding libdrm. Thanks.

**Comment by ljbade** [comment]
I am back from a trip, so I will work on this soon.

**Comment by cefn** [comment]
This is experienced on Ubuntu 17.10 also. The error I encounter is...

```bash
$ ./uPyLoader-linux 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "/home/raven/.local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
```

I have encountered it with binaries from both the Mu project https://codewith.mu/ and the uPyLoader project 

In the case of the Mu project, it is leading them to withdraw use of Pyinstaller altogether, as you can see at https://github.com/mu-editor/mu/issues/299 which would be a shame.

Is the workaround something which can be done with the actual binary? If so, what archive format can I assume to start manipulating the embedded files. Alternatively does this workaround have to be completed before the final binary is produced?
