### ISSUE TITLE
pyinstaller does not work on cygwin

### ISSUE THREAD

**Issue by giampaolo** [pyinstaller/pyinstaller#3328]
```
user@DESKTOP-L9L6URS /cygdrive/z/smartfile/tp/python
$ python3 -V
Python 3.6.4

user@DESKTOP-L9L6URS /cygdrive/z/smartfile/tp/python
$ python3 -m pip install pyinstaller
Collecting pyinstaller
  Using cached PyInstaller-3.3.1.tar.gz
Requirement already satisfied: setuptools in /home/user/.local/lib/python3.6/site-packages (from pyinstaller)
Requirement already satisfied: pefile>=2017.8.1 in /usr/lib/python3.6/site-packages (from pyinstaller)
Requirement already satisfied: macholib>=1.8 in /usr/lib/python3.6/site-packages (from pyinstaller)
Requirement already satisfied: future in /usr/lib/python3.6/site-packages (from pefile>=2017.8.1->pyinstaller)
Requirement already satisfied: altgraph>=0.15 in /usr/lib/python3.6/site-packages (from macholib>=1.8->pyinstaller)
Building wheels for collected packages: pyinstaller
  Running setup.py bdist_wheel for pyinstaller ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r2hc7ejj/pyinstaller/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpon8zol4rpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_bootloader
  No precompiled bootloader found. Trying to compile it for you ...
  Setting top to                           : /tmp/pip-build-r2hc7ejj/pyinstaller/bootloader
  Setting out to                           : /tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/build
  Checking for 'gcc' (C compiler)          : /usr/bin/gcc
  Traceback (most recent call last):
    File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 122, in waf_entry_point
      run_commands()
    File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 183, in run_commands
      ctx=run_command(cmd_name)
    File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 174, in run_command
      ctx.execute()
    File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Configure.py", line 85, in execute
      super(ConfigurationContext,self).execute()
    File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 88, in execute
      self.recurse([os.path.dirname(g_module.root_path)])
    File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 129, in recurse
      user_function(self)
    File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/wscript", line 425, in configure
      DESTOS_TO_SYSTEM[ctx.env.DEST_OS])
  KeyError: 'cygwin'
  ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.py

  ----------------------------------------
  Failed building wheel for pyinstaller
  Running setup.py clean for pyinstaller
Failed to build pyinstaller
Installing collected packages: pyinstaller
  Running setup.py install for pyinstaller ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r2hc7ejj/pyinstaller/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xrisblc7-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_bootloader
    No precompiled bootloader found. Trying to compile it for you ...
    Setting top to                           : /tmp/pip-build-r2hc7ejj/pyinstaller/bootloader
    Setting out to                           : /tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/build
    Checking for 'gcc' (C compiler)          : /usr/bin/gcc
    Traceback (most recent call last):
      File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 122, in waf_entry_point
        run_commands()
      File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 183, in run_commands
        ctx=run_command(cmd_name)
      File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 174, in run_command
        ctx.execute()
      File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Configure.py", line 85, in execute
        super(ConfigurationContext,self).execute()
      File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 88, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 129, in recurse
        user_function(self)
      File "/tmp/pip-build-r2hc7ejj/pyinstaller/bootloader/wscript", line 425, in configure
        DESTOS_TO_SYSTEM[ctx.env.DEST_OS])
    KeyError: 'cygwin'
    ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.py

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r2hc7ejj/pyinstaller/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xrisblc7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-r2hc7ejj/pyinstaller/
```

**Comment by htgoebel** [comment]
This looks like some case is missing in `bootloader/wscript`. Please help fixing it!
Downloading the source and building the bootloader manually as described in https://pyinstaller.readthedocs.io/en/latest/bootloader-building.html. Don't worry, it's easy :-)

**Comment by giampaolo** [comment]
So I was able to build the bootloader with this simple change:

```diff
diff --git a/bootloader/wscript b/bootloader/wscript
index fd0b18b..67654d1 100644
--- a/bootloader/wscript
+++ b/bootloader/wscript
@@ -44,6 +44,7 @@ variants = {
 # map waf's DEST_OS to these values.
 DESTOS_TO_SYSTEM = {
     'linux': 'Linux',
+    'cygwin': 'Cygwin',
     'freebsd': 'FreeBSD',
     'win32': 'Windows',
     'darwin': 'Darwin',
```

A similar attempt has been done in a previous PR which has been closed:
https://github.com/pyinstaller/pyinstaller/pull/2904

With that in place `python ./waf all` completes successfully and produces 2 exe files:

```bash
$ ls PyInstaller/bootloader/Cygwin-64bit/
run_d.exe  run.exe
```

I'm not sure what to do with those. If I try to execute them from the Cygwin shell I get:


```
[8604] Cannot open self /cygdrive/z/pyinstaller/PyInstaller/bootloader/Cygwin-64bit/run or archive /cygdrive/z/pyinstaller/PyInstaller/bootloader/Cygwin-64bit/run.pkg
```

Also, the [doc](https://pyinstaller.readthedocs.io/en/latest/bootloader-building.html) states the following:

> When building the bootloader yourself, you have to carefully choose between three options:
[...]

> Using cygwin and MinGW. This will create executables for cygwin, not for ‘plain’ Windows.
> This description seems to be technically incorrect. I ought to depend on the C++ run-time library. If you know details, please open an issue.

What I want to achieve is the following:
- compile a Python C extension module with Cygwin (I can do this)
- create a `.exe` of a python script importing this extension module by using PyInstaller

**Comment by htgoebel** [comment]
Thanks for the update.
- 2904 was closed since it was wrong and incomplete.
- I assume you also need to add an entry to SYSTEM_TO_BUILDOS in the wscript file.
- The error message you receive when running the bootloader is expected. The bootloader is only a stub and requires the PYZ file to be appended (which is what PyInstalelr does).
- As the docs say: When building in cygwin, this will create executables for cygwin. This is why cygwin1.dll and cygz.dll are required. You should be able to work around this by using `--add-binary`, see the manual.

I't apreacheate a pull-request for you fixes :-)

**Comment by giampaolo** [comment]
> When building in cygwin, this will create executables for cygwin.

Does this mean I need to have cygwin installed on the customer's host? I was hoping to compile my sources with cygwin + installer then produce an "independent" .exe which could be run from cmd.exe.
Is that possible at all?

**Comment by htgoebel** [comment]
I assume adding cygwin1.dll and cygz.dll should be enough. But you need to ask this the Cywin people (or try out).

Anyway, since you are running cygwin, you are on windows anyway. So you could simply run PyInstaller in the windows environment. This will give you an "indenpendent" .exe - but bring you into another dll-hell, see https://pyinstaller.readthedocs.io/en/v3.3.1/usage.html#windows

**Comment by Legorooj** [comment]
Closing due to inactivity

**Comment by Jeklah** [comment]
So whats the laymans terms for the fix for this?
