### ISSUE TITLE
How to load the Django application module?

### ISSUE THREAD

**Issue by marcelodelta** [pyinstaller/pyinstaller#3331]
hook-sistema.apps.py
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('sistema')

ERROR:
(PythonLib): dist\AGTRAN.exe runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x05F03738>
Traceback (most recent call last):
  File "site-packages\django\utils\autoreload.py", line 225, in wrapper
  File "site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
  File "site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
  File "site-packages\django\core\management\__init__.py", line 327, in execute
  File "site-packages\django\utils\autoreload.py", line 225, in wrapper
  File "site-packages\django\__init__.py", line 24, in setup
  File "site-packages\django\apps\registry.py", line 89, in populate
  File "site-packages\django\apps\config.py", line 116, in create
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sistema'

**Comment by htgoebel** [comment]
Duplicate, see https://github.com/pyinstaller/pyinstaller/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+django

You are welcome to work on one or more of these open issues.
