### ISSUE TITLE
ImportError: No module named 'cytoolz.utils': cytoolz.itertoolz

### ISSUE THREAD

**Issue by izgzhen** [pyinstaller/pyinstaller#3365]
steps for reproduction:

1. create a clean Python3 (3.5.2) environment with `virtualenv`
2. install `web3-3.16.5` and `PyInstaller-3.3.1` through local `pip` (pyinstaller's development version `3.4.dev0+de034aa12` has the same issue)
3. `pyinstaller --onefile main.py`, in which `main.py` is only one line: `import web3`
4. run `dist/main`, then you should see an exception

```
-> % ./dist/main 
Traceback (most recent call last):
  File "/home/zhen/new/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 715, in load_module
    module = loader.load_module(fullname)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "cytoolz/itertoolz.pyx", line 19, in init cytoolz.itertoolz
ImportError: No module named 'cytoolz.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import web3
  File "/home/zhen/new/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/web3/__init__.py", line 5, in <module>
  File "/home/zhen/new/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/web3/main.py", line 6, in <module>
  File "/home/zhen/new/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/eth_utils/__init__.py", line 41, in <module>
  File "/home/zhen/new/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/eth_utils/functional.py", line 5, in <module>
  File "/home/zhen/new/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/cytoolz/__init__.py", line 1, in <module>
  File "/home/zhen/new/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 717, in load_module
    raise ImportError('%s: %s' % (e, fullname))
ImportError: No module named 'cytoolz.utils': cytoolz.itertoolz
[19101] Failed to execute script main
```

@lgr150 @stfairy

**Comment by htgoebel** [comment]
Obviously this is a Cython module. Python can not determine if the Cython C object module is importing some Python module. Please [read the manual](https://pyinstaller.readthedocs.io/en/stable/feature-notes.html#cython-support) for details and a solution. We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks.

**Comment by htgoebel** [comment]
The hook should be for `cytoolz.itertoolz` of course.

**Comment by izgzhen** [comment]
cool, I will take a look on how to implement this
