### ISSUE TITLE
Failure to import Cairo into wxPython 4.0.1

### ISSUE THREAD

**Issue by david-hughes** [pyinstaller/pyinstaller#3404]
The problem is illustrated by this two-line sample
```
import wx.lib.wxcairo as wxcairo
print('Cairo version %s' % wxcairo.cairo.version)
```
After adding these Print function calls into `cairocffi.__init__.py`
```
def dlopen(ffi, *names):
    """Try various names for the same library, for different platforms."""
    for name in names:
        for lib_name in [name, 'lib' + name]:
            try:
                print('lib_name is "%s"' % lib_name)
                path = ctypes.util.find_library(lib_name)
                print('path is "%s"' % path)
                if path:
                    print('ffi is ', ffi)
                    print('ffi.dlopen is', ffi.dlopen)
                    lib = ffi.dlopen(path)
                    print('lib is "%s"' % lib)
                    if lib:
                        return lib
            except OSError as e:
                print(e)
                pass
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))


cairo = dlopen(ffi, 'cairo', 'cairo-2')

```
the unfrozen sample produces
```
lib_name is "cairo"
path is "None"
lib_name is "libcairo"
path is "None"
lib_name is "cairo-2"
path is "None"
lib_name is "libcairo-2"
path is "e:\PyDevSrc7\venv-cp36-win32\lib\site-packages\wx\libcairo-2.dll"
ffi is  <CompiledFFI object at 0x06180470>
ffi.dlopen is <built-in method dlopen of CompiledFFI object at 0x06180470>
lib is "<Lib object for 'e:\PyDevSrc7\venv-cp36-win32\lib\site-packages\wx\libcairo-2.dll'>"
Cairo version 1.10.0
```
Running the command:
```
(venv-cp36-win32) E:\PyDevSrc7\Dp710\allsource>pyinstaller --add-binary "E:\PyDevSrc7\venv-cp36-win32\Lib\site-packages\wx\libcairo-2.dll;.\wx" cairo-test.py
```
produces:
```
97 INFO: PyInstaller: 3.4.dev0+36e90ff8e
97 INFO: Python: 3.6.1
99 INFO: Platform: Windows-10-10.0.16299-SP0
100 INFO: wrote E:\PyDevSrc7\Dp710\allsource\cairo-test.spec
106 INFO: UPX is not available.
107 INFO: Extending PYTHONPATH with paths
['E:\\PyDevSrc7\\Dp710\\allsource', 'E:\\PyDevSrc7\\Dp710\\allsource']
108 INFO: checking Analysis
186 INFO: Building because e:\pydevsrc7\venv-cp36-win32\lib\site-packages\cairocffi\__init__.py changed
187 INFO: Initializing module dependency graph...
191 INFO: Initializing module graph hooks...
192 INFO: Analyzing base_library.zip ...
4026 INFO: running Analysis out00-Analysis.toc
4029 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by e:\pydevsrc7\venv-cp36-win32\scripts\python.exe
5022 INFO: Caching module hooks...
5028 INFO: Analyzing E:\PyDevSrc7\Dp710\allsource\cairo-test.py
5835 INFO: Processing pre-find module path hook   distutils
7298 INFO: Processing pre-find module path hook   site
7299 INFO: site: retargeting to fake-dir 'e:\\pydevsrc7\\venv-cp36-win32\\lib\\site-packages\\PyInstaller\\fake-modules'
7993 INFO: Loading module hooks...
7993 INFO: Loading module hook "hook-distutils.py"...
7995 INFO: Loading module hook "hook-encodings.py"...
8155 INFO: Loading module hook "hook-lib2to3.py"...
8169 INFO: Loading module hook "hook-pkg_resources.py"...
8904 INFO: Processing pre-safe import module hook   win32com
9016 INFO: Loading module hook "hook-pycparser.py"...
9291 INFO: Loading module hook "hook-pydoc.py"...
9292 INFO: Loading module hook "hook-pythoncom.py"...
9701 INFO: Loading module hook "hook-pywintypes.py"...
10094 INFO: Loading module hook "hook-setuptools.py"...
10128 INFO: Loading module hook "hook-sysconfig.py"...
10130 INFO: Loading module hook "hook-win32com.py"...
10822 INFO: Loading module hook "hook-xml.py"...
11115 INFO: Looking for ctypes DLLs
11152 INFO: Analyzing run-time hooks ...
11157 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
11160 INFO: Including run-time hook 'pyi_rth_pkgres.py'
11163 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
11173 INFO: Looking for dynamic libraries
12311 INFO: Looking for eggs
12311 INFO: Using Python library e:\pydevsrc7\venv-cp36-win32\scripts\python36.dll
12312 INFO: Found binding redirects:
[]
12317 INFO: Warnings written to E:\PyDevSrc7\Dp710\allsource\build\cairo-test\warncairo-test.txt
12418 INFO: Graph cross-reference written to E:\PyDevSrc7\Dp710\allsource\build\cairo-test\xref-cairo-test.html
12434 INFO: Appending 'binaries' from .spec
12437 INFO: checking PYZ
12440 INFO: Building because toc changed
12440 INFO: Building PYZ (ZlibArchive) E:\PyDevSrc7\Dp710\allsource\build\cairo-test\out00-PYZ.pyz
13687 INFO: Building PYZ (ZlibArchive) E:\PyDevSrc7\Dp710\allsource\build\cairo-test\out00-PYZ.pyz completed successfully.
13701 INFO: checking PKG
13701 INFO: Building because E:\PyDevSrc7\Dp710\allsource\build\cairo-test\out00-PYZ.pyz changed
13702 INFO: Building PKG (CArchive) out00-PKG.pkg
13722 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
13723 INFO: Bootloader e:\pydevsrc7\venv-cp36-win32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
13723 INFO: checking EXE
13725 INFO: Rebuilding out00-EXE.toc because pkg is more recent
13725 INFO: Building EXE from out00-EXE.toc
13726 INFO: Appending archive to EXE E:\PyDevSrc7\Dp710\allsource\build\cairo-test\cairo-test.exe
13730 INFO: Building EXE from out00-EXE.toc completed successfully.
13733 INFO: checking COLLECT
WARNING: The output directory "E:\PyDevSrc7\Dp710\allsource\dist\cairo-test" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
16793 INFO: Removing dir E:\PyDevSrc7\Dp710\allsource\dist\cairo-test
16831 INFO: Building COLLECT out00-COLLECT.toc
17321 INFO: Building COLLECT out00-COLLECT.toc completed successfully.
```
But running the frozen version
`(venv-cp36-win32) E:\PyDevSrc7\Dp710\allsource>.\dist\cairo-test\cairo-test.exe`
produces
```
lib_name is "cairo"
path is "None"
lib_name is "libcairo"
path is "None"
lib_name is "cairo-2"
path is "None"
lib_name is "libcairo-2"
path is "E:\PyDevSrc7\Dp710\allsource\dist\cairo-test\wx\libcairo-2.dll"
ffi is  <CompiledFFI object at 0x0614D1C8>
ffi.dlopen is <built-in method dlopen of CompiledFFI object at 0x0614D1C8>
cannot load library 'E:\PyDevSrc7\Dp710\allsource\dist\cairo-test\wx\libcairo-2.dll': error 0x7e
Traceback (most recent call last):
  File "cairo-test.py", line 1, in <module>
    import wx.lib.wxcairo as wxcairo
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "e:\pydevsrc7\venv-cp36-win32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\wx\lib\wxcairo\__init__.py", line 57, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "e:\pydevsrc7\venv-cp36-win32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\wx\lib\wxcairo\wx_cairocffi.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "e:\pydevsrc7\venv-cp36-win32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\cairocffi\__init__.py", line 47, in <module>
  File "lib\site-packages\cairocffi\__init__.py", line 44, in dlopen
OSError: dlopen() failed to load a library: cairo / cairo-2
[14176] Failed to execute script cairo-test
```
The dll is present in the distribution but `ffi.dlopen()` seems to be failing.

**Comment by Kerang** [comment]
It looks a module is being dynamically loaded and will need a hook. I ran into the same issue with pyttsx3.

[fixed / workaround for pyttsx3 test won't work once compiled with pyinstaller](https://github.com/pyinstaller/pyinstaller/issues/3268)
