### ISSUE TITLE
Python shared library not found on PyPy3

### ISSUE THREAD

**Issue by oberstet** [pyinstaller/pyinstaller#3420]
It seems like [_check_python_library](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/build_main.py#L599) doesn't find the PyPy3 run-time, which is puzzling, because it's there `pypy3/bin/libpypy3-c.so`. Name matching is done versus [PYDYLIB_NAMES](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/compat.py#L58) as far as I see, and indeed, PyPy is unsupported=(

```console
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ make build_step3
pyinstaller  --onefile  --name crossbar  --add-data /home/oberstet/scm/crossbario/crossbar/crossbar/keys:crossbar/keys  --add-data /home/oberstet/scm/crossbario/crossbar/crossbar/web:crossbar/web  --add-data /home/oberstet/scm/crossbario/crossbar/crossbar/templates:crossbar/templates  /home/oberstet/scm/crossbario/crossbar/crossbar/controller/cli.py
501 INFO: PyInstaller: 3.3.1
508 INFO: Python: 3.5.3
532 INFO: Platform: FreeBSD-11.1-RELEASE-amd64-64bit-ELF
535 INFO: wrote /usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/crossbar.spec
559 INFO: UPX is not available.
562 INFO: Extending PYTHONPATH with paths
['/home/oberstet/scm/crossbario/crossbar',
 '/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd']
564 INFO: checking Analysis
603 INFO: Building because _python_version changed
611 INFO: Initializing module dependency graph...
615 INFO: Initializing module graph hooks...
620 INFO: Analyzing base_library.zip ...
11929 INFO: running Analysis out00-Analysis.toc
12235 INFO: Caching module hooks...
12241 INFO: Analyzing /home/oberstet/scm/crossbario/crossbar/crossbar/controller/cli.py
13710 INFO: Processing pre-find module path hook   distutils
21272 INFO: Processing pre-safe import module hook   six.moves
27963 INFO: Processing pre-find module path hook   site
27974 INFO: site: retargeting to fake-dir '/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/fake-modules'
37345 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
41122 INFO: Loading module hooks...
41127 INFO: Loading module hook "hook-lib2to3.py"...
41131 INFO: Loading module hook "hook-sysconfig.py"...
41139 INFO: Loading module hook "hook-encodings.py"...
41652 INFO: Loading module hook "hook-nacl.py"...
41663 INFO: Loading module hook "hook-pydoc.py"...
41665 INFO: Loading module hook "hook-jinja2.py"...
41694 INFO: Loading module hook "hook-xml.py"...
41703 INFO: Loading module hook "hook-cryptography.py"...
43462 INFO: Loading module hook "hook-pkg_resources.py"...
45249 INFO: Processing pre-safe import module hook   win32com
45821 INFO: Loading module hook "hook-certifi.py"...
45833 INFO: Loading module hook "hook-pycparser.py"...
46127 INFO: Loading module hook "hook-distutils.py"...
46129 INFO: Loading module hook "hook-requests.py"...
46132 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
46133 INFO: Loading module hook "hook-setuptools.py"...
46198 INFO: Loading module hook "hook-pygments.py"...
50766 INFO: Looking for ctypes DLLs
51444 INFO: Analyzing run-time hooks ...
51520 INFO: Including run-time hook 'pyi_rth_twisted.py'
51521 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
51526 INFO: Including run-time hook 'pyi_rth_pkgres.py'
51649 INFO: Looking for dynamic libraries
51654 INFO: Looking for eggs
51655 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
    self.__postinit__()
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/building/build_main.py", line 545, in assemble
    self._check_python_library(self.binaries)
  File "/usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd/pypy3/site-packages/PyInstaller/building/build_main.py", line 629, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: libpython3.5.so.1, libpython3.5m.so.1, libpython3.5.so.1.0, libpython3.5m.so.1.0
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)

*** Error code 1

Stop.
make: stopped in /usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ find pypy3 -name "*.so"
pypy3/site-packages/nacl/_sodium.pypy3-59-amd64-freebsd11.so
pypy3/site-packages/_ubjson.pypy3-59-amd64-freebsd11.so
pypy3/site-packages/setproctitle.pypy3-59-amd64-freebsd11.so
pypy3/site-packages/psutil/_psutil_posix.pypy3-59-amd64-freebsd11.so
pypy3/site-packages/psutil/_psutil_bsd.pypy3-59-amd64-freebsd11.so
pypy3/site-packages/cryptography/hazmat/bindings/_openssl.pypy3-59-amd64-freebsd11.so
pypy3/site-packages/cryptography/hazmat/bindings/_constant_time.pypy3-59-amd64-freebsd11.so
pypy3/site-packages/cryptography/hazmat/bindings/_padding.pypy3-59-amd64-freebsd11.so
pypy3/site-packages/lmdb/lmdb_cffi.pypy3-59-amd64-freebsd11.so
pypy3/bin/libpypy3-c.so
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ uname -a
FreeBSD fbsd1 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ 
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ ./pypy3/bin/pypy3 -V
Python 3.5.3 (d72f9800a42b46a8056951b1da2426d2c2d8d502, Mar 15 2018, 01:25:08)
[PyPy 5.9.0-beta0 with GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]
```

**Comment by oberstet** [comment]
Ok, I got over above problem by patching PYDLIB_NAMES, but now I am running into:

```console
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ make check
ls -laG ./dist
total 19946
drwxr-xr-x  2 oberstet  oberstet         3 Mar 22 22:48 .
drwxr-xr-x  7 oberstet  oberstet        11 Mar 22 22:15 ..
-rwxr-xr-x  1 oberstet  oberstet  20695392 Mar 22 22:48 crossbar
ldd ./dist/crossbar
./dist/crossbar:
	libm.so.5 => /lib/libm.so.5 (0x800829000)
	libz.so.6 => /lib/libz.so.6 (0x800a54000)
	libc.so.7 => /lib/libc.so.7 (0x800c6d000)
./dist/crossbar version
[51857] Cannot dlsym for Py_DontWriteBytecodeFlag
*** Error code 255

Stop.
make: stopped in /usr/home/oberstet/scm/crossbario/crossbar-fabric-package/exe/freebsd
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ uname -a
FreeBSD fbsd1 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ ./pypy/bin/pypy3 -V
-bash: ./pypy/bin/pypy3: No such file or directory
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ ./pypy3/bin/pypy3 -V
Python 3.5.3 (d72f9800a42b46a8056951b1da2426d2c2d8d502, Mar 15 2018, 01:25:08)
[PyPy 5.9.0-beta0 with GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]
(pypy3) [oberstet@fbsd1 ~/scm/crossbario/crossbar-fabric-package/exe/freebsd]$ 
```

**Comment by htgoebel** [comment]
You are trying to use PyInstaller with PyPy? Wow! I would be impressed if this works, alone I'm afraid it will not (but I have no clue about PyPy's internals).

Technically speaking, PyInstaller is embedding CPython and relies on parts of the CPython C-API being present. The "Cannot dlsym for Py_DontWriteBytecodeFlag" looks like PyPy is not providing this C-API and PyInstaller will not work wit PyPy.

On the other hanf, a quick grep gave:
```
[thisbe pypy3-v5.10.1-src]$ grep -ril DontWriteBytecodeFlag
pypy/module/cpyext/src/missing.c
pypy/module/cpyext/api.py
pypy/module/cpyext/include/pythonrun.h
```
So maybe there is a chance.

You also can hack the bootloader to not set `Py_DontWriteBytecodeFlag`. and other flags not supported by PyPy. Maybe this helps.

Please let me know what are your results.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved.

**Comment by mosajjal** [comment]
if it's fixed, please provide some documentation on how it could be hacked to work. I still can't use pyinstaller on pypy. Thanks
