### ISSUE TITLE
Hook errors on execution

### ISSUE THREAD

**Issue by CCReese** [pyinstaller/pyinstaller#3452]
Clean install used. Python 3.6. PyQt5 application. Pyinstaller 3.3.1. Windows 10 machine.

Build execution runs file, with some api-ms-***.dll warnings. 

Execution of program yielded first errors with tkinter/tcl hook. After using --exclude-module=tkinter, another hook error appears;

  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "c:\users\colin\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 35, in <module>
  File "c:\users\colin\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "plistlib.py", line 65, in <module>
  File "c:\users\colin\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "xml\parsers\expat.py", line 4, in <module>
ModuleNotFoundError: No module named 'pyexpat'
[1304] Failed to execute script pyi_rth_pkgres

Installing dev version resulted in many, many, other errors in build, rather than execution. These look like potential python versioning error. Reverted to 3.3.1.

**Comment by CCReese** [comment]
Hi. Can someone help at all with this issue with things I might try? Is this a python 3.6 support issue? I did not find documentation on which versions of which libraries/requirements are supported.

**Comment by tallforasmurf** [comment]
Looks like the xml package has some kind of hidden import 'pyexpat' that wasn't included. I would suspect a problem with the xml module, either not properly installed, or possibly you have a newer version and our [xml hook](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-xml.py) needs to be updated?

**Comment by CCReese** [comment]
Thank you. What would you suggest I try? I could try in 3.5?

**Comment by tallforasmurf** [comment]
Since there exists an xml hook other people are using it with PyInstaller. I don't see any outstanding issues that name xml particularly, so there shouldn't be any problem bundling an app with xml. Me personally I'd build a clean VENV with Python 3.5, activate it, and pip install every needed module and PyInstaller. (Just for curiosity I think I'd use Windows "find" to look for files name `pyexpat*` to see if it exists and where it is living.) Then try bundling in that VENV context.

**Comment by CCReese** [comment]
I redid this in 3.5 with a fresh venv and still get the same error. I have tried hidden-import with pyexpat, explicitly importing in the script itself, and including the binary. I am officially stuck. The module imports fine in a 3.5 terminal, so it is there.

**Comment by CCReese** [comment]
I sorted this. Using the binary in build instead of dist.

**Comment by mntfr** [comment]
> 
> 
> I sorted this. Using the binary in build instead of dist.

Hi I am having the same issue how do you use binary in build?

**Comment by pablompa** [comment]
> > I sorted this. Using the binary in build instead of dist.
> 
> Hi I am having the same issue how do you use binary in build?

Find pyexpat.pyd in your project's dist directory (created by PyInstaller). Copy it into the project's build directory.

**Comment by pablompa** [comment]
> > I sorted this. Using the binary in build instead of dist.
> 
> Hi I am having the same issue how do you use binary in build?

Run what's in the dist directory, not what's in the build directory.

**Comment by Kogam22** [comment]
> **@pablompa :**
> Run what's in the dist directory, not what's in the build directory.

Can you give me a link for the pyexpat binary ?

@CCReese 
Which binary ?

**Comment by jeromebelpaire** [comment]
I am having the same issue with Python 3.6 and Pyinstaller 3.6.
On some pc's the application will work just fine, then break on others.
I have tried the hidden imports, importing the package in the main script, but still get the same error on some pc's.

Did anyone get a final solution for this?

**Comment by jfitzpatrick6** [comment]
If anyone runs into this in the future, I am using Python 3.10.7 and Pyinstaller             6.8.0, and pyinstaller-hooks-contrib 2024.7. I was getting this error when running an executable:

Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 170, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 37, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "pkg_resources\__init__.py", line 40, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "plistlib.py", line 70, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed while importing pyexpat: The operating system cannot run %1.

I tried reinstalling Python and clean Conda environments, and I was continuing to get the same error. It may have something to do with my project being poorly organized, alas. I was able to get the program to execute if I added this as my hidden imports:

hiddenimports=['xml.parsers.expat', 'pkg_resources._vendor.packaging', 'pkg_resources']

No idea why this works, but this is what worked for me.

**Comment by m-ad** [comment]
I also had the issue with "ModuleNotFoundError: No module named 'pyexpat'" that only occurred in the pyinstaller-created executable. Using the hidden imports as suggested by @jfitzpatrick6 had no effect. 

- Python 3.12
- pyinstaller 6.11.1
- pyinstaller-hooks-contrib 2025.0

However, I noticed something else: I have a conda environment which i used to build a virtual environment (`python -m venv venv`). When I run my pyinstaller build script from the venv, I get the above error. But when I run it from the conda environment directly, the executable runs fine without issues. During the build process, I see these warnings only from the venv:
```
2025-01-23 08:27:43 WARNING Library not found: could not resolve 'ffi-8.dll', dependency of 'C:\\Users\\mad\\Miniconda3\\envs\\python_312\\DLLs\\_ctypes.pyd'.
2025-01-23 08:27:43 WARNING Library not found: could not resolve 'libcrypto-3-x64.dll', dependency of 'C:\\Users\\mad\\Miniconda3\\envs\\python_312\\DLLs\\_hashlib.pyd'.
2025-01-23 08:27:43 WARNING Library not found: could not resolve 'libcrypto-3-x64.dll', dependency of 'C:\\Users\\mad\\Miniconda3\\envs\\python_312\\DLLs\\_ssl.pyd'.
2025-01-23 08:27:43 WARNING Library not found: could not resolve 'libssl-3-x64.dll', dependency of 'C:\\Users\\mad\\Miniconda3\\envs\\python_312\\DLLs\\_ssl.pyd'.
2025-01-23 08:27:43 WARNING Library not found: could not resolve 'libexpat.dll', dependency of 'C:\\Users\\mad\\Miniconda3\\envs\\python_312\\DLLs\\pyexpat.pyd'.
```
If I look for these DLLs, they are under `...\envs\python_312\Library\bin`. After I added them to my pyinstaller script via `--add-binary` these warnings disappear and so does the `ModuleNotFoundError` error.

**Comment by zlt999** [comment]
> If anyone runs into this in the future, I am using Python 3.10.7 and Pyinstaller 6.8.0, and pyinstaller-hooks-contrib 2024.7. I was getting this error when running an executable:
> 
> Traceback (most recent call last): File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 170, in File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 37, in _pyi_rthook File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module File "pkg_resources__init__.py", line 40, in File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module File "plistlib.py", line 70, in File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module File "xml\parsers\expat.py", line 4, in ImportError: DLL load failed while importing pyexpat: The operating system cannot run %1.
> 
> I tried reinstalling Python and clean Conda environments, and I was continuing to get the same error. It may have something to do with my project being poorly organized, alas. I was able to get the program to execute if I added this as my hidden imports:
> 
> hiddenimports=['xml.parsers.expat', 'pkg_resources._vendor.packaging', 'pkg_resources']
> 
> No idea why this works, but this is what worked for me.

I've met with the same problem.
Using Python 3.11.11, pyinstaller 6.11.1, and also anaconda.
It's interesting that this occuers on one of my laptop, while the other one works totally fine.

And I've allocate the issue code as below.
It raises the error if you inhert VersionNumber, pack with pyinstaller and run the exe.
No issue if it's working alone, with no child class.

```python
class VersionNumber(tuple):
    """A tuple-subclass representing a version number

    Version numbers can be created using one to three positional arguments,
    representing the major, minor, and build number respectively::

        v1 = VersionNumber(1)
        v12 = VersionNumber(1, 2)
        v123 = VersionNumber(1, 2, 3)

    Keyword arguments can also be used::

        v1 = VersionNumber(major=1)
        v12 = VersionNumber(major=1, minor=2)
        v123 = VersionNumber(major=1, minor=2, build=3)

    A fourth number, the release number, can also be given as a keyword-only
    argument::

        v1293 = VersionNumber(major=1, minor=2, release=9, build=3)

    This release number is placed between the minor and build numbers, both for
    the string representation and in the tuple.

    The major number is required and the other numbers are optional in the
    order minor, build, release.

    All numbers can be accessed as attributes (`major`, `minor`, `release`,
    `build`). If the number is unavailable, accessing the attribute returns
    `None`.

    """

    __slots__ = ()

    def __new__(cls, major, minor=None, build=None, release=None):
        # qqqdaca python 2 :: in python 3, release should be keyword-only argument

        if __debug__:
            try:
                if release is not None:
                    assert build is not None
                if build is not None:
                    assert minor is not None
                if minor is not None:
                    assert major is not None
            except AssertionError:
                raise TypeError(
                    "VersionNumber members are optional in the following order: "
                    "[major [minor [[release] build]"
                )

        numbers = (n for n in (major, minor, release, build) if n is not None)
        obj = super().__new__(cls, numbers)
        return obj

    def __str__(self):
        return '.'.join(str(n) for n in self)

    def __repr__(self):
        attrs = (
            f'{name}={getattr(self, name)}'
            for name in ('major', 'minor', 'release', 'build')
        )
        return f"{self.__class__.__name__}({', '.join(attrs)})"

    @property
    def major(self):
        try:
            return self[0]
        except IndexError:
            return None

    @property
    def minor(self):
        try:
            return self[1]
        except IndexError:
            return None

    @property
    def release(self):
        if len(self) > 3:
            return self[2]
        else:
            return None

    @property
    def build(self):
        if len(self) > 2:
            return self[-1]
        else:
            return None

    @property
    def beta(self):
        return False


```
