### ISSUE TITLE
Run keras.preprocessing.image

### ISSUE THREAD

**Issue by AlexandreMPDias** [pyinstaller/pyinstaller#3454]
Im using:
>Python3.6.4
>Pyinstaller 3.3.1
>Windows 10

There's no much to my error... I've run pyinstaller sucessfully on this project, I didnt change the .spec or anything, but out of nowhere, it started giving me erros on scipy when I run:

` from keras.preprocessing.image import image_to_array
`

My .spec file:

` # -*- mode: python -*-

block_cipher = None

a = Analysis(['smile.py'],
             pathex=['C:\\Users\\tijuk\\Projects\\smile',
             'C:\\Users\\tijuk\\Envs\\emotion\\Lib\\site-packages\\scipy\\extra-dll',
             'C:\\Users\\tijuk\\Envs\\emotion\\Lib\\site-packages\\scipy\\optimize'],
             binaries=[],
             datas=[
                ('data\\checkpoints\\epoch_75.hdf5','.\\data\\checkpoints'),
                ('data\\haarcascade_frontalface_default.xml','.\\data'),
                ('data\\png\\*','.\\data\\png')
                ],
             hiddenimports=['scipy._lib.messagestream'
                'scipy.special._ufuncs_cxx',
                'scipy.linalg.cython_blas',
                'scipy.linalg.cython_lapack',
                'scipy.integrate',
                'scipy.integrate.quadrature',
                'scipy.integrate.odepack',
                'scipy.integrate._odepack',
                'scipy.integrate.quadpack',
                'scipy.integrate._quadpack',
                'scipy.integrate._ode',
                'scipy.integrate.vode',
                'scipy.integrate._dop',
                'scipy.integrate.lsoda'
                'scipy.optimize.optimize',
                'scipy.optimize.linesearch'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='smile_cam',
          debug=False,
          strip=False,
          upx=True,
          console=True,
          icon='C:\\Users\\tijuk\\Projects\\Icons\\LogoIcon.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='smile_cam')
`

and the output error:

`Traceback (most recent call last):
  File "smile.py", line 5, in <module>
  File "c:\users\tijuk\envs\smile\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\optimize\__init__.py", line 240, in <module>
  File "c:\users\tijuk\envs\smile\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)

  File "site-packages\scipy\optimize\optimize.py", line 37, in <module>
  File "c:\users\tijuk\envs\smile\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)

  File "site-packages\scipy\optimize\linesearch.py", line 18, in <module>
  File "c:\users\tijuk\envs\smile\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.
[18940] Failed to execute script smile`

> Não foi possível encontrar o módulo especificado. == The specified module could not be found

This is my first time posting an issue, ever... so I'm sorry If I missed anything important ❤️ 
And many thanks

**Comment by AlexandreMPDias** [comment]
You can close this... I changed to another namespace, deleting the {emotion} namespace and forgot to update the virtualenv's name on include paths
