### ISSUE TITLE
PyQt5.WebSockets is missing a hook

### ISSUE THREAD

**Issue by argoneuscze** [pyinstaller/pyinstaller#3455]
Hello,

I tried using PyInstaller (Win 10, Python 3.6) with a project using PyQt5, though when I tried to run the resulting .exe, I got this error:

```
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5.py", line 61, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "D:\Documents\Programming\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
RuntimeError: PyQt5.QtWebSockets cannot import type '����' from PyQt5.QtCore
[228] Failed to execute script pyi_rth_qt5
```

I managed to resolve the error by creating a `hook-PyQt5.QtWebSockets.py` file in the hooks folder, which seems to be missing. I assume this is because it's a rather new feature and it hasn't been noticed yet.

The contents of the hook are as following:

`hiddenimports = ["PyQt5.QtNetwork"]`

After adding this, the program works normally. I wanted to try and create a PR, but it seemed rather complex so I'll leave that to someone more experienced.

**Comment by bjones1** [comment]
@argoneuscze, thanks for reporting this. It should be fixed in the latest master and not need an additional hook. Would you mind testing it? What version of PyInstaller are you using?

**Comment by argoneuscze** [comment]
I've been using version 3.3.1, the latest one on stable pip.

When I try to run it using the development version, I get this error instead:

```
Traceback (most recent call last):
  File "D:\Documents\Programming\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 712, in load_module
    module = loader.load_module(fullname)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ModuleNotFoundError: No module named 'PyQt5.QtNetwork'
```

**Comment by bjones1** [comment]
@argoneuscze, thanks for reporting this. Would you mind posting the build output from PyInstaller for the development version? It should output a list of Qt libraries it searched -- I'm curious to see what it reports for the dependencies of `QtWebSockets`.

**Comment by argoneuscze** [comment]
I'm not really sure what happened exactly, whether I installed the wrong development version somehow or such, but now that I tried it again, it seems to work just fine.

```
>pyinstaller --version
3.4.dev0+eea47968c
```

```
170 INFO: Loading module hooks...
3170 INFO: Loading module hook "hook-encodings.py"...
3227 INFO: Loading module hook "hook-pydoc.py"...
3227 INFO: Loading module hook "hook-PyQt5.py"...
3250 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
3363 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
3491 INFO: Loading module hook "hook-PyQt5.QtMultimedia.py"...
3701 INFO: Loading module hook "hook-PyQt5.QtNetwork.py"...
3788 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
4070 INFO: Loading module hook "hook-PyQt5.uic.py"...
4072 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
4072 INFO: Loading module hook "hook-xml.py"...
```

**Comment by bjones1** [comment]
OK, sounds good.
