### ISSUE TITLE
PyInstaller not creating kivy_install directory

### ISSUE THREAD

**Issue by drscotthawley** [pyinstaller/pyinstaller#3475]
Hi, finished closing issue #3447 here a few weeks ago, (https://github.com/pyinstaller/pyinstaller/issues/3447#issuecomment-379457422) and then posted the remainder of my issue to the Kivy-users group (https://groups.google.com/forum/#!topic/kivy-users/X5F1c_r_5MY), but never got any response from them.

I'm cross-posting here because a) you actually responded last time!   and b) I'm not completely sure whether the 'Issue"' likes with Kivy or with PyInstaller.  
If you're willing to help, I would be very grateful, but I'm not here to assert that PyInstaller has some kind of bug, just that...it refuses to turn my program into an "app" because it's not copying a certain directory that it thinks it needs.

I'm able to follow the instructions for making an OS X package using pyinstaller (https://kivy.org/docs/guide/packaging-osx.html, the "Using PyInstaller and Homebrew" variant) up until the line after you manually edit the .spec file to include a "Tree" definition.  i.e. up until the "Build the spec and create a DMG" section.

After that, running the next line of the instructions "pyinstaller -y --clean --windowed touchtracer.spec", 

...I get an an error saying there's no touchtracer.app/Contents/Resources/kivy_install/data/style.kv'.

In fact, there's no kivy_install directory at all. 

Dumping log. (my app name is 'sorta'):

$ pyinstaller -y --clean --windowed sorta.spec
88 INFO: PyInstaller: 3.4.dev0+956066103
88 INFO: Python: 3.5.5
99 INFO: Platform: Darwin-17.4.0-x86_64-i386-64bit
103 INFO: UPX is not available.
103 INFO: Removing temporary files and cleaning cache in /Users/shawley/Library/Application Support/pyinstaller
158 INFO: Extending PYTHONPATH with paths
['/Users/shawley/github/sorta', '/Users/shawley/github/sorta']
158 INFO: checking Analysis
158 INFO: Building Analysis because Analysis-00.toc is non existent
158 INFO: Initializing module dependency graph...
161 INFO: Initializing module graph hooks...
163 INFO: Analyzing base_library.zip ...
3917 INFO: running Analysis Analysis-00.toc
3930 INFO: Caching module hooks...
3934 INFO: Analyzing /Users/shawley/github/sorta/sorta.py
6850 INFO: Loading module hooks...
6851 INFO: Loading module hook "hook-encodings.py"...
6949 INFO: Loading module hook "hook-xml.py"...
7021 INFO: Loading module hook "hook-PIL.Image.py"...
7123 INFO: Processing pre-find module path hook   distutils
7642 INFO: Loading module hook "hook-pydoc.py"...
7642 INFO: Loading module hook "hook-PIL.py"...
7644 INFO: Excluding import 'PySide'
7645 INFO:   Removing import of PySide from module PIL.ImageQt
7646 INFO: Excluding import 'tkinter'
7647 INFO:   Removing import of tkinter from module PIL.ImageTk
7649 INFO: Excluding import 'PyQt5'
7650 INFO:   Removing import of PyQt5 from module PIL.ImageQt
7651 INFO: Excluding import 'PyQt4'
7652 INFO:   Removing import of PyQt4 from module PIL.ImageQt
7653 INFO: Import to be excluded not found: 'FixTk'
7653 INFO: Loading module hook "hook-kivy.py"...
Purge log fired. Analysing...
Purge 42 log files
Purge finished!
[INFO   ] [Logger      ] Record log in /Users/shawley/.kivy/logs/kivy_18-04-07_51.txt
7694 INFO: [Logger      ] Record log in /Users/shawley/.kivy/logs/kivy_18-04-07_51.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20180407
7668 INFO: [Kivy        ] v1.10.1.dev0, git-Unknown, 20180407
[INFO   ] [Python      ] v3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
7694 INFO: [Python      ] v3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[INFO   ] [Factory     ] 194 symbols loaded
7698 INFO: [Factory     ] 194 symbols loaded
[INFO   ] [Logger      ] Record log in /Users/shawley/.kivy/logs/kivy_18-04-07_52.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20180407
[INFO   ] [Python      ] v3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Logger      ] Record log in /Users/shawley/.kivy/logs/kivy_18-04-07_53.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20180407
[INFO   ] [Python      ] v3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[INFO   ] [AudioGstplayer] Using Gstreamer 1.14.0.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer, audio_avplayer ignored)
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Camera      ] Provider: avfoundation
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_nspaste'] ignored)
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.30.14'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(TM) Graphics 6100'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Spelling    ] Provider: enchant
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoGstplayer] Using Gstreamer 1.14.0.0
[INFO   ] [Video       ] Provider: gstplayer
12171 INFO: Excluding import 'twisted'
12175 INFO:   Removing import of twisted from module kivy.support
12178 INFO: Excluding import 'tkinter'
12184 INFO: Excluding import '_tkinter'
12192 INFO: Loading module hook "hook-pkg_resources.py"...
12732 INFO: Processing pre-safe import module hook   win32com
12824 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
12827 INFO: Excluding import 'tkinter'
12828 INFO: Import to be excluded not found: 'FixTk'
12828 INFO: Loading module hook "hook-lib2to3.py"...
12831 INFO: Loading module hook "hook-pygments.py"...
14570 INFO: Loading module hook "hook-xml.dom.domreg.py"...
14571 INFO: Loading module hook "hook-distutils.py"...
14572 INFO: Loading module hook "hook-docutils.py"...
16211 INFO: Loading module hook "hook-sysconfig.py"...
16213 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
16259 INFO: Looking for ctypes DLLs
16278 WARNING: library libmtdev.so.1 required via ctypes not found
16305 INFO: Analyzing run-time hooks ...
16314 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
16319 INFO: Including run-time hook 'pyi_rth_kivy.py'
16321 INFO: Including run-time hook 'pyi_rth_gstreamer.py'
16322 INFO: Including run-time hook 'pyi_rth_pkgres.py'
16340 INFO: Looking for dynamic libraries
16777 INFO: Looking for eggs
16777 INFO: Using Python library /Users/shawley/anaconda/envs/testpi/lib/libpython3.5m.dylib
16787 INFO: Warnings written to /Users/shawley/github/sorta/build/sorta/warn-sorta.txt
16902 INFO: Graph cross-reference written to /Users/shawley/github/sorta/build/sorta/xref-sorta.html
16960 INFO: checking PYZ
16960 INFO: Building PYZ because PYZ-00.toc is non existent
16960 INFO: Building PYZ (ZlibArchive) /Users/shawley/github/sorta/build/sorta/PYZ-00.pyz
18744 INFO: Building PYZ (ZlibArchive) /Users/shawley/github/sorta/build/sorta/PYZ-00.pyz completed successfully.
18775 INFO: checking PKG
18775 INFO: Building PKG because PKG-00.toc is non existent
18775 INFO: Building PKG (CArchive) PKG-00.pkg
18809 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
18811 INFO: Bootloader /Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
18811 INFO: checking EXE
18811 INFO: Building EXE because EXE-00.toc is non existent
18811 INFO: Building EXE from EXE-00.toc
18811 INFO: Appending archive to EXE /Users/shawley/github/sorta/build/sorta/sorta
18818 INFO: Fixing EXE for code signing /Users/shawley/github/sorta/build/sorta/sorta
18827 INFO: Building EXE from EXE-00.toc completed successfully.
18828 INFO: checking Tree
18828 INFO: Building Tree because Tree-00.toc is non existent
18828 INFO: Building Tree Tree-00.toc
18912 INFO: checking COLLECT
18912 INFO: Building COLLECT because COLLECT-00.toc is non existent
18912 INFO: Removing dir /Users/shawley/github/sorta/dist/sorta
18969 INFO: Building COLLECT COLLECT-00.toc
23901 INFO: Building COLLECT COLLECT-00.toc completed successfully.
23967 INFO: checking BUNDLE
23967 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
23967 INFO: Removing dir /Users/shawley/github/sorta/dist/sorta.app
24038 INFO: Building BUNDLE BUNDLE-00.toc
26796 INFO: moving BUNDLE data files to Resource directory
 Traceback (most recent call last):
28041 WARNING: stderr: Traceback (most recent call last):
   File "/Users/shawley/anaconda/envs/testpi/bin/pyinstaller", line 11, in <module>
28041 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/bin/pyinstaller", line 11, in <module>
     load_entry_point('PyInstaller==3.4.dev0+956066103', 'console_scripts', 'pyinstaller')()
28043 WARNING: stderr:     load_entry_point('PyInstaller==3.4.dev0+956066103', 'console_scripts', 'pyinstaller')()
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/__main__.py", line 94, in run
28043 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/__main__.py", line 94, in run
     run_build(pyi_config, spec_file, **vars(args))
28044 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
28044 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
28046 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 814, in main
28046 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 814, in main
     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
28048 WARNING: stderr:     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 760, in build
28048 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 760, in build
     exec(text, spec_namespace)
28049 WARNING: stderr:     exec(text, spec_namespace)
   File "<string>", line 37, in <module>
28049 WARNING: stderr:   File "<string>", line 37, in <module>
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/osx.py", line 86, in __init__
28050 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/osx.py", line 86, in __init__
     self.__postinit__()
28051 WARNING: stderr:     self.__postinit__()
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
28051 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
     self.assemble()
28052 WARNING: stderr:     self.assemble()
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/osx.py", line 195, in assemble
28052 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/site-packages/PyInstaller/building/osx.py", line 195, in assemble
     shutil.copy(fnm, tofnm)
28053 WARNING: stderr:     shutil.copy(fnm, tofnm)
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/shutil.py", line 241, in copy
28054 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/shutil.py", line 241, in copy
     copyfile(src, dst, follow_symlinks=follow_symlinks)
28055 WARNING: stderr:     copyfile(src, dst, follow_symlinks=follow_symlinks)
   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/shutil.py", line 120, in copyfile
28055 WARNING: stderr:   File "/Users/shawley/anaconda/envs/testpi/lib/python3.5/shutil.py", line 120, in copyfile
     with open(src, 'rb') as fsrc:
28056 WARNING: stderr:     with open(src, 'rb') as fsrc:
 FileNotFoundError: [Errno 2] No such file or directory: '/Users/shawley/github/sorta/dist/sorta.app/Contents/Resources/kivy_install/data/style.kv'
28056 WARNING: stderr: FileNotFoundError: [Errno 2] No such file or directory: '/Users/shawley/github/sorta/dist/sorta.app/Contents/Resources/kivy_install/data/style.kv'
(testpi) Scotts-MacBook-Pro-3:sorta shawley$ ls /Users/shawley/github/sorta/dist/sorta.app/Contents/Resources/kivy_install
ls: /Users/shawley/github/sorta/dist/sorta.app/Contents/Resources/kivy_install: No such file or directory

Tried searching for this in this group and on GitHub/Issues, but nothing was either current or directly relevant. I'm using the latest kivy source from github. (see below) 

Steps to reproduce:

$ rm -rf build dist sorta.spec 
$ pip install Cython==0.26.1
$ pip install pyenchant pillow
$ pip install -U https://github.com/kivy/kivy/archive/master.zip
$ pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip --upgrade
$ pyinstaller -y --clean --windowed --name sorta --exclude-module _tkinter \
  --exclude-module Tkinter --exclude-module enchant --exclude-module twisted \
  /Users/shawley/github/sorta/sorta.py

Edit COLLECT line in sorta.spec to read:

  coll = COLLECT(exe, Tree('/Users/shawley/github/sorta/'),

$ pyinstaller -y --clean --windowed sorta.spec

...get the errors.  Any help?  Thanks. 
I'm using old-anaconda (not anaconda3) and python 3.5.5 after receiving help from PyInstaller developer on GitHub (https://github.com/pyinstaller/pyinstaller/issues/3447#issuecomment-379457422).
Mac OS X High Sierra, 10.13.3 (17D47)

**Comment by htgoebel** [comment]
Please check the paths in your .spec-file. While you are talking about touchtracer
> ...I get an an error saying there's no touchtracer.app/Contents/Resources/kivy_install/data/style.kv'.

the error message is about sorta.app

>  28056 WARNING: stderr: FileNotFoundError: [Errno 2] No such file or directory: '/Users/shawley/github/sorta/dist/sorta.app/Contents/Resources/kivy_install/data/style.kv'
