### ISSUE TITLE
PyQt5 does not work with master

### ISSUE THREAD

**Issue by dashesy** [pyinstaller/pyinstaller#3479]
1411 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py27\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller', 'console_scripts', 'pyinstaller')()
  File "d:\development\pyinstaller\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\development\pyinstaller\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\development\pyinstaller\PyInstaller\building\build_main.py", line 814, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\development\pyinstaller\PyInstaller\building\build_main.py", line 760, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "d:\development\pyinstaller\PyInstaller\building\build_main.py", line 237, in __init__
    self.__postinit__()
  File "d:\development\pyinstaller\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "d:\development\pyinstaller\PyInstaller\building\build_main.py", line 496, in assemble
    module_hook.post_graph()
  File "d:\development\pyinstaller\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "d:\development\pyinstaller\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "d:\development\pyinstaller\PyInstaller\hooks\hook-PyQt5.QtWidgets.py", line 11, in <module>
    hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
  File "d:\development\pyinstaller\PyInstaller\utils\hooks\qt.py", line 490, in add_qt5_dependencies
    more_binaries = qt_plugins_binaries(plugin, namespace=namespace)
  File "d:\development\pyinstaller\PyInstaller\utils\hooks\qt.py", line 118, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "d:\development\pyinstaller\PyInstaller\utils\hooks\qt.py", line 103, in qt_plugins_dir
    """.format(namespace, ", ".join(paths)))
Exception:
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/Users/builder/mc3/conda-bld/qt_1505945264697/_h_env/Library/plugins

**Comment by bjones1** [comment]
@dashesy, what version of PyInstaller, PyQt, and Python are you using?

**Comment by Crazor** [comment]
The same thing happens with Python 3.5.4 and PyQt 5.6 (both installed from the official sites, respectively, and not from anaconda etc.) using the recent develop branch...

**Comment by jeremyherbert** [comment]
I am seeing this on windows10 too. Python 3.6.4 from anaconda, pyinstaller 3.4.dev0+b31794cf1

**Comment by roynielsen17** [comment]
Just an FYI, Python 2.7 is officially supported until January 1, 2020:
https://www.python.org/dev/peps/pep-0373/

Also, Qt4 and PyQt4 are no longer supported on macOS as of the last several
operating system versions.

Regards,
-Roy


*What man is a man who does not make the world better?*
*- Balien of Ibelin, Kingdom of Heaven*

**Comment by bjones1** [comment]
Unfortunately, conda's version of PyQt5 is broken -- it returns invalid paths when querying QLibraryInfo. The pip-installed version would work fine.

@roynielsen17, you're correct that Python 2.7 is supported until 2020; Pyinstaller will support Python 2.7 until that date as well. However, PyQt5 doesn't support Python 2.7 -- that's the core roadblock.

**Comment by roynielsen17** [comment]
This puts people on the Mac in a bind since python3 is no longer a part of
macOS.  Just python 2.7.  PyQt4 hasn't been supported on several of the
last macOS releases.

No more using PyInstaller and PyQt for any current Mac platform with a
clean OS install then?

Regards,
-Roy


*What man is a man who does not make the world better?*
*- Balien of Ibelin, Kingdom of Heaven*

**Comment by bjones1** [comment]
I'm probably missing something, but the obvious (to me) solution is to install Python 3 on the developer's Mac, develop using PyQt5, then package with Pyinstaller and distribute the resulting application to users (who don't need to install Python 3, PyQt5, or anything beyond the packaged app).

**Comment by roynielsen17** [comment]
Hello Bryan,

We originally chose the python/PyQt/Pyinstaller stack because the base tool
(python) was native to the OS on all platforms our App supported (vendor
supported rhel, sles, deb, fedora, ubuntu, macOS, centOS).  All platforms
except macOS, all of the tools are vendor supplied and updated.  We keep
running into tool chain issues on the Mac, having to regularly update tools
manually.  I guess with homebrew, we get that on the Mac platform.

Thank you,
-Roy


*What man is a man who does not make the world better?*
*- Balien of Ibelin, Kingdom of Heaven*

**Comment by bjones1** [comment]
That makes sense. Sigh -- I wish Apple would provide a more modern Python, but as you say, they seem to have passed this work on to homebrew/macports/etc.

**Comment by Kwongrf** [comment]
I have the same problem......Windows10, python3.6.4, pyQt5, pyinstaller-3.4.dev0+a5505747a

**Comment by bjones1** [comment]
By the same problem, do you mean you get the error message `Cannot find existing PyQt5 plugin directories`? If so, are you using PyQt5 installed in Anaconda?

**Comment by xiahaoyun** [comment]
```
  File "c:\program files\anaconda3\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 65, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "c:\program files\anaconda3\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 39, in qt_plugins_dir
    raise Exception('Cannot find {0} plugin directories'.format(namespace))
Exception: Cannot find PyQt5 plugin directories
```
I used to use PyQt5 installed in Anaconda.I  get those errors.
Then,I use Native Python,it's work

**Comment by bjones1** [comment]
@xiahaoyun, thanks for the feedback. That's what I'd expect -- Anaconda's PyQt5 doesn't report its plugin directories correctly.

**Comment by gil123456** [comment]
I am using PyQt5 5.11.2 and PyQt5-sip 4.19.12 and get the same error:
390 INFO: PyInstaller: 3.3.1
391 INFO: Python: 3.5.2
391 INFO: Platform: Windows-7-6.1.7601-SP1
396 INFO: wrote D:\Local_Bazaar_Projects\SW_ATE\Trunk\GUI\gui.spec
403 INFO: UPX is not available.
404 INFO: Extending PYTHONPATH with paths
['D:\\Local_Bazaar_Projects\\SW_ATE\\Trunk\\GUI',
 'D:\\Local_Bazaar_Projects\\SW_ATE\\Trunk\\GUI']
406 INFO: checking Analysis
438 INFO: Building because out00-Analysis.toc is bad
439 INFO: Initializing module dependency graph...
442 INFO: Initializing module graph hooks...
446 INFO: Analyzing base_library.zip ...
6750 INFO: running Analysis out00-Analysis.toc
7609 INFO: Caching module hooks...
7614 INFO: Analyzing D:\Local_Bazaar_Projects\SW_ATE\Trunk\GUI\gui_main.py
7680 INFO: Loading module hooks...
7680 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "C:\Program_Files\Python3_5_2\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\building\build_main.py", line 472, in assemble
    module_hook.post_graph()
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\compat.py", line 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtCore.py", line 15, in <module>
    binaries = qt_plugins_binaries('codecs', namespace='PyQt5')
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 65, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "c:\program_files\python3_5_2\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 39, in qt_plugins_dir
    raise Exception('Cannot find {0} plugin directories'.format(namespace))
Exception: Cannot find PyQt5 plugin directories

What seems to be the issue?
is the import error in the beginning is related ?

7680 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: DLL load failed: The specified procedure could not be found.

any help will be appreciated

**Comment by ThomasHarriesHasselbalch** [comment]
I have the same problem with PyInstaller 3.3.1, PyQt5 5.11.2 and PyQt5-sip 4.19.12, all from pip.

**Comment by htgoebel** [comment]
@thomashh89 Use PyInstaller 3.4 which has been released a few days ago.
