### ISSUE TITLE
Error when running the exe file 

### ISSUE THREAD

**Issue by MakePLAN** [pyinstaller/pyinstaller#3493]
Hi, I have created a project using PyQt5 and open cv2 library. It goes through the process through pyinstaller fine but when I try to run the exe file, there seems to be error which I do not understand. Can anyone help me what is the error about?

Sangs-MacBook-Pro:~ SmrtAsian$ /Users/SmrtAsian/Documents/USC/Projects/A1_Project/score_correction/dist/main_window/main_window ; exit;

Traceback (most recent call last):
  File "main_window.py", line 8, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "auto_correction.py", line 9, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "sat_grader.py", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "imutils/__init__.py", line 8, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "imutils/convenience.py", line 6, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/cv2/__init__.py", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: dlopen(/Users/SmrtAsian/Documents/USC/Projects/A1_Project/score_correction/dist/main_window/cv2.cv2.so, 2): Symbol not found: __ZN10QByteArray11shared_nullE
  Referenced from: /Users/SmrtAsian/Documents/USC/Projects/A1_Project/score_correction/dist/main_window/QtTest
  Expected in: /Users/SmrtAsian/Documents/USC/Projects/A1_Project/score_correction/dist/main_window/QtCore
 in /Users/SmrtAsian/Documents/USC/Projects/A1_Project/score_correction/dist/main_window/QtTest
[19605] Failed to execute script main_window
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by htgoebel** [comment]
Please try with the latest development version.
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please try provide the a *minimal* example to reproduce the error.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved. Otherwise please try PyInstaller v3.4 and the current development version.
