### ISSUE TITLE
Pyinstaller Broken Module Import with Infinisdk

### ISSUE THREAD

**Issue by daramosch** [pyinstaller/pyinstaller#3500]
Hi Folks! 

I've been working with Pyinstaller successfuly up until now while I'm Trying to create an Executable that uses infinisdk (Python Module for Infinidat) 
I have tried the following: 
1) Ran the analysis and check the warn log for module import missing. 
2) Update the .spec file both with the --hidden-import Parameter and by updating the Spec file. 
3) Update the .spec file with pyi-makespec --paths= with the Module Full Path name and also by updating the spec file manually
4) Re compile build by using the pyinstaller [file].spec. 

I'm getting the following error every time. 

**Traceback (most recent call last):
  File "LUN_Creation.py", line 3053, in <module>
  File "LUN_Creation.py", line 662, in host_ex_AMDC_ux
  File "LUN_Creation.py", line 588, in infi_login** ### Above my Script , Below Error###
  File "site-packages\infinisdk\infinibox\infinibox.py", line 229, in login
  File "site-packages\infinisdk\infinibox\infinibox.py", line 257, in _get_clien
t_id
  File "site-packages\pkg_resources\__init__.py", line 557, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 431, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 967, in require
  File "site-packages\pkg_resources\__init__.py", line 853, in resolve
pkg_resources.DistributionNotFound: The 'infinisdk' distribution was not found a
nd is required by the application
[322136] Failed to execute script LUN_Creation

**Comment by htgoebel** [comment]
Looks like you need to create a hook which runs `copy_metadata()`, see e.g. PyInstaller/hooks/hook-distutils.py. I'd appreciate a pull-request for the hook :-)
