### ISSUE TITLE
pynacl is missing the cffi backend

### ISSUE THREAD

**Issue by Berserker66** [pyinstaller/pyinstaller#3525]
Python 3.6.5, 64 Bit
Pyinstaller develop.zip version

the project uses pynacl, however the cffi backend does not get included. 

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 712, in load_module
    module = loader.load_module(fullname)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ModuleNotFoundError: No module named '_cffi_backend'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "main.py", line 98, in <module>
  File "main.py", line 36, in check_licence
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\nacl\signing.py", line 19, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\nacl\bindings\__init__.py", line 17, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\nacl\bindings\crypto_box.py", line 18, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    raise ImportError('%s: %s' % (e, fullname))
ImportError: No module named '_cffi_backend': nacl._sodium
[2768] Failed to execute script main
```

**Comment by teemukataja** [comment]
Hi, I know this is really late, but this solved it for me https://github.com/pyinstaller/pyinstaller/issues/1684#issuecomment-449607479

I gave it as a command line parameter
```
pyinstaller --onefile my_script.py --hidden-import _cffi_backend
```
