### ISSUE TITLE
importing pendulum doesn't work

### ISSUE THREAD

**Issue by jeremyherbert** [pyinstaller/pyinstaller#3528]
Hi,

Pendulum is a date/time library for python. The following code works fine when running from the interpreter:

```
import pendulum

print(pendulum.now().isoformat())
```

However, when compiling it using the latest master version of pyinstaller (only argument is `--onefile`, I get the following error upon running the executable:

```
Traceback (most recent call last):
  File "pendulum_test.py", line 1, in <module>
    import pendulum
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Users\Jeremy\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pendulum\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Users\Jeremy\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pendulum\datetime.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Users\Jeremy\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pendulum\date.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Users\Jeremy\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pendulum\helpers.py", line 29, in <module>
  File "site-packages\pendulum\formatting\difference_formatter.py", line 12, in __init__
  File "site-packages\pendulum\locales\locale.py", line 38, in load
ValueError: Locale [en] does not exist.
[19056] Failed to execute script pendulum_test
```

OS is windows 10.

**Comment by htgoebel** [comment]
This looks like not all required files are packaged. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by NateScarlet** [comment]
@RudolfCardinal 
The hook not work on python2.7.15, pendulum2.0.3
Pendulum can find the locale file but can not import it

```
  File "site-packages\pendulum\helpers.py", line 29, in <module>
  File "site-packages\pendulum\formatting\difference_formatter.py", line 12, in __init__
  File "site-packages\pendulum\locales\locale.py", line 42, in load
  File "importlib\__init__.py", line 37, in import_module
ImportError: No module named en.locale
[8116] Failed to execute script launch
```

**Comment by RudolfCardinal** [comment]
Ah; I was using Python 3.5.6, pendulum 2.0.3, PyInstaller 3.4. I'm surprised even the hook script ran, to be honest; it is syntactically invalid for Python 2. If I make the hook report ``datas`` and crash, I get this (where ``...`` is truncated):

    ('/.../site-packages/pendulum/locales/locale.py', 'pendulum/locales')
    ('/.../site-packages/pendulum/locales/__init__.py', 'pendulum/locales')
    ('/.../site-packages/pendulum/locales/fa/locale.py', 'pendulum/locales/fa')
    ('/.../site-packages/pendulum/locales/fa/__init__.py', 'pendulum/locales/fa')
    ('/.../site-packages/pendulum/locales/fa/custom.py', 'pendulum/locales/fa')
    ('/.../site-packages/pendulum/locales/es/locale.py', 'pendulum/locales/es')
    ('/.../site-packages/pendulum/locales/es/__init__.py', 'pendulum/locales/es')
    ('/.../site-packages/pendulum/locales/es/custom.py', 'pendulum/locales/es')
    ('/.../site-packages/pendulum/locales/ko/locale.py', 'pendulum/locales/ko')
    ('/.../site-packages/pendulum/locales/ko/__init__.py', 'pendulum/locales/ko')
    ('/.../site-packages/pendulum/locales/ko/custom.py', 'pendulum/locales/ko')
    ('/.../site-packages/pendulum/locales/lt/locale.py', 'pendulum/locales/lt')
    ('/.../site-packages/pendulum/locales/lt/__init__.py', 'pendulum/locales/lt')
    ('/.../site-packages/pendulum/locales/lt/custom.py', 'pendulum/locales/lt')
    ('/.../site-packages/pendulum/locales/zh/locale.py', 'pendulum/locales/zh')
    ('/.../site-packages/pendulum/locales/zh/__init__.py', 'pendulum/locales/zh')
    ('/.../site-packages/pendulum/locales/zh/custom.py', 'pendulum/locales/zh')
    ('/.../site-packages/pendulum/locales/fo/locale.py', 'pendulum/locales/fo')
    ('/.../site-packages/pendulum/locales/fo/__init__.py', 'pendulum/locales/fo')
    ('/.../site-packages/pendulum/locales/fo/custom.py', 'pendulum/locales/fo')
    ('/.../site-packages/pendulum/locales/da/locale.py', 'pendulum/locales/da')
    ('/.../site-packages/pendulum/locales/da/__init__.py', 'pendulum/locales/da')
    ('/.../site-packages/pendulum/locales/da/custom.py', 'pendulum/locales/da')
    ('/.../site-packages/pendulum/locales/pt_br/locale.py', 'pendulum/locales/pt_br')
    ('/.../site-packages/pendulum/locales/pt_br/__init__.py', 'pendulum/locales/pt_br')
    ('/.../site-packages/pendulum/locales/pt_br/custom.py', 'pendulum/locales/pt_br')
    ('/.../site-packages/pendulum/locales/de/locale.py', 'pendulum/locales/de')
    ('/.../site-packages/pendulum/locales/de/__init__.py', 'pendulum/locales/de')
    ('/.../site-packages/pendulum/locales/de/custom.py', 'pendulum/locales/de')
    ('/.../site-packages/pendulum/locales/fr/locale.py', 'pendulum/locales/fr')
    ('/.../site-packages/pendulum/locales/fr/__init__.py', 'pendulum/locales/fr')
    ('/.../site-packages/pendulum/locales/fr/custom.py', 'pendulum/locales/fr')
    ('/.../site-packages/pendulum/locales/en/locale.py', 'pendulum/locales/en')
    ('/.../site-packages/pendulum/locales/en/__init__.py', 'pendulum/locales/en')
    ('/.../site-packages/pendulum/locales/en/custom.py', 'pendulum/locales/en')

**Comment by bjones1** [comment]
Taking a guess, would this work?

``` Python
#!/usr/bin/env python
# pyinstaller_hooks/hook-pendulum.py

from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files("pendulum.locales", include_py_files=True)
```

**Comment by sergeod9** [comment]
I'm facing the same issue,
Windows 10
Python 3.7.0 
pendulum 2.0.4
setuptools 40.6.2
Anaconda 3

I'm using an env, it's a small program, so isolating the problem wasn't a big issue, I'm only using tkinter, pendulum and pytz, no problems with tkinter.
I tried the following:
1- Setting the UPX to false in the .spec file
2- Setting pendulum and pytz as hidden modules in .spec file
3- Using --onedir flag instead of --onefile
4- Tried using Python 3.6 in a different env
nothing worked so far, when running the compiled file in cmd I'm getting:

```
Traceback (most recent call last):
  File "world_sessions_tz.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\anaconda3\envs\envpy37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pendulum\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\anaconda3\envs\envpy37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pendulum\datetime.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\anaconda3\envs\envpy37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pendulum\date.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\anaconda3\envs\envpy37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pendulum\helpers.py", line 43, in <module>
  File "site-packages\pendulum\formatting\difference_formatter.py", line 12, in __init__
  File "site-packages\pendulum\locales\locale.py", line 38, in load
ValueError: Locale [en] does not exist.
[24084] Failed to execute script world_sessions_tz

```
I don't know what Locale [en] is, searching for it didn't offer much either

**Comment by sergeod9** [comment]
UPDATE,
After adding the hook mentioned in the comments, I'm getting the following error:

```
PyInstaller cannot check for assembly dependencies.
Please install PyWin32 or pywin32-ctypes.

pip install pypiwin32

```
Installing pypiwin32 didn't solve the problem

**Comment by bjones1** [comment]
Use develop per https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#getting-the-latest-version. Instead, `pip install pywin32-ctypes`.

**Comment by cesarvandevelde** [comment]
Hi everyone. I ran into the same issue, but managed to solve it by adding custom hooks for both pendulum as well as pytzdata (a pendulum dependency).

My setup:
- Python 3.7.0
- PyInstaller: latest dev version
- pendulum 2.0.4
- pytzdata 2018.7

Pendulum hook:
```Python
# pyinstaller_hooks/hook-pendulum.py

from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files("pendulum.locales", include_py_files=True)
```

Pytzdata hook:
```Python
# pyinstaller_hooks/hook-pytzdata.py

from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files("pytzdata", include_py_files=True)
```

Relevant `.spec` options:
```Python
a = Analysis(['main.py'],
             # ...
             hiddenimports=["pytzdata"],
             hookspath=["pyinstaller_hooks"],
             # ...
```

Hope this helps!

**Comment by htgoebel** [comment]
@cesarvandevelde Thans for sharing this. We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.
