### ISSUE TITLE
Need help cant build exe been stuck with same error for days.

### ISSUE THREAD

**Issue by tcampion64** [pyinstaller/pyinstaller#3530]
Sample program:
#!/usr/bin/env python3

import multiprocessing

class SendeventProcess(multiprocessing.Process):
    def __init__(self, resultQueue):
        self.resultQueue = resultQueue
        multiprocessing.Process.__init__(self)
        self.start()

    def run(self):
        print('SendeventProcess')
        self.resultQueue.put((1, 2))
        print('SendeventProcess')

if __name__ == '__main__':
    # On Windows calling this function is necessary.
    # On Linux/OSX it does nothing.
    multiprocessing.freeze_support()
    print('main')
    resultQueue = multiprocessing.Queue()
    SendeventProcess(resultQueue)
    print('main')

The above code runs fine from the command line and produces the following output.
main
main
SendeventProcess
SendeventProcess

build output:
[v800343@pdcd49-tools1a]~/GES_Modules/multi% pyinstaller multi.spec
58 INFO: PyInstaller: 3.4.dev0+1033a8770
58 INFO: Python: 3.6.5
60 INFO: Platform: Linux-2.6.32-504.3.3.el6.x86_64-x86_64-with-redhat-6.6-Santiago
61 INFO: UPX is not available.
63 INFO: Extending PYTHONPATH with paths
['/home/repos/ges/Python/GES_Module/multi',
 '/home/repos/ges/Python/GES_Module/multi']
63 INFO: checking Analysis
68 INFO: Appending 'binaries' from .spec
68 INFO: Appending 'datas' from .spec
71 INFO: checking PYZ
74 INFO: checking PKG
74 INFO: Bootloader /home/repos/ges/Python/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run
74 INFO: checking EXE
75 INFO: checking COLLECT
76 INFO: Building COLLECT COLLECT-00.toc
143 INFO: Building COLLECT COLLECT-00.toc completed successfully.

The error listed below is produced from the exe produced by pyinstaller
Traceback (most recent call last):

  File "/home/repos/ges/Python/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 712, in load_module
    module = loader.load_module(fullname)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/repos/ges/Python/GES_Module/multi/dist/multi/_posixsubprocess.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_set_inheritable_async_safe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py", line 9, in <module>
  File "/home/repos/ges/Python/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "multiprocessing/spawn.py", line 19, in <module>
  File "/home/repos/ges/Python/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "multiprocessing/util.py", line 17, in <module>
  File "/home/repos/ges/Python/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "subprocess.py", line 136, in <module>
  File "/home/repos/ges/Python/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
    raise ImportError('%s: %s' % (e, fullname))
ImportError: /home/repos/ges/Python/GES_Module/multi/dist/multi/_posixsubprocess.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_set_inheritable_async_safe: _posixsubprocess
[5742] Failed to execute script pyi_rth_multiprocessing

Not at all sure what is wrong. I think all the files needed are in the build. I've used strace and dont see any errors except what is above.

**Comment by tcampion64** [comment]
My python is built to a non-standard location. When I test on a machine with a typical python install the code above appears to compile successfully.
