### ISSUE TITLE
Encryption on Python 3 / Windows

### ISSUE THREAD

**Issue by oberstet** [pyinstaller/pyinstaller#3531]
I'm not entirely sure if this is an issue you consider within the scope of PyInstaller at all - so feel free to close! I'll just collect my findings.

So I want to use `--key` on y Windows 10 x64 build host with CPython 3.6, but installing PyCrypto fails, so I install https://github.com/Legrandin/pycryptodome

This claims to be compatible, and the issue I run into is that PyInstaller instantiates a AES key from a `str` (which is even asserted https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/archive/pyz_crypto.py#L46), which is Unicode under Python 3, not bytes what AES expects.

Is `--key` supposed to work on Python 3 on Windows?

> I am aware that "encryption" is considered an "enterprise feature", in which case I am happy to hear about options;)

```
28716 INFO: checking PYZ
28716 INFO: Building PYZ because out00-PYZ.toc is non existent
28716 INFO: Building PYZ (ZlibArchive) C:\projects\crossbarfx\build\crossbarfx\out00-PYZ.pyz
Traceback (most recent call last):
  File "C:\Python36-x64\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "c:\python36-x64\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python36-x64\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\api.py", line 133, in assemble
    pyz = ZlibArchiveWriter(self.name, toc, code_dict=self.code_dict, cipher=self.cipher)
  File "c:\python36-x64\lib\site-packages\PyInstaller\archive\writers.py", line 184, in __init__
    super(ZlibArchiveWriter, self).__init__(archive_path, logical_toc)
  File "c:\python36-x64\lib\site-packages\PyInstaller\archive\writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "c:\python36-x64\lib\site-packages\PyInstaller\archive\writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "c:\python36-x64\lib\site-packages\PyInstaller\archive\writers.py", line 213, in add
    obj = self.cipher.encrypt(obj)
  File "c:\python36-x64\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 58, in encrypt
    return iv + self.__create_cipher(iv).encrypt(data)
  File "c:\python36-x64\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 64, in __create_cipher
    return self._aesmod.new(self.key, self._aesmod.MODE_CFB, iv)
  File "c:\python36-x64\lib\site-packages\Crypto\Cipher\AES.py", line 200, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "c:\python36-x64\lib\site-packages\Crypto\Cipher\__init__.py", line 55, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "c:\python36-x64\lib\site-packages\Crypto\Cipher\_mode_cfb.py", line 230, in _create_cfb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "c:\python36-x64\lib\site-packages\Crypto\Cipher\AES.py", line 100, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "c:\python36-x64\lib\site-packages\Crypto\Util\_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
Command exited with code 1
date
Sun May 20 13:07:13 PDT 2018
```

**Comment by htgoebel** [comment]
`--key` is no longer supported. The requirement for byte-encryption is a commercial one (free software does not require byte-encryption since the code is available anyway), thus somebody with commercial interest shall implement the fix (or pay the development.)

Hmm, maybe I should add a warning to the code :-)

**Comment by htgoebel** [comment]
> A clear warning/exception in the code would be useful. Also updating the online documentation to state the current status would also be useful

@BrendanSimon I agreed. Please submit a pull-request to make this happen soon.

**Comment by BrendanSimon** [comment]
It would be next to pointless me doing any of this because (a) I have no idea what the current status is, and (b) what the design is or is intended to be, etc.  Someone would have to rewrite 110% of it to correct all the mistakes.

After some hunting I've come to the conclusion that encrypting with a self-contained key is next to pointless for obfuscation.  A better option is to use Cython to compile to machine code, which gives the the same (or almost the same) level of obfuscation as a C/C++ compiled app.
