### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by vonlippmann** [pyinstaller/pyinstaller#3551]
Traceback (most recent call last):
  File "g:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "g:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\Python36\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "g:\python36\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "g:\python36\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "g:\python36\lib\site-packages\PyInstaller\building\build_main.py", line 814, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "g:\python36\lib\site-packages\PyInstaller\building\build_main.py", line 760, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "g:\python36\lib\site-packages\PyInstaller\building\build_main.py", line 237, in __init__
    self.__postinit__()
  File "g:\python36\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "g:\python36\lib\site-packages\PyInstaller\building\build_main.py", line 496, in assemble
    module_hook.post_graph()
  File "g:\python36\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "g:\python36\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "g:\python36\lib\site-packages\PyInstaller\compat.py", line 735, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "g:\python36\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtCore.py", line 11, in <module>
    hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
  File "g:\python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 493, in add_qt5_dependencies
    tp = pyqt5_library_info.location['TranslationsPath']
  File "g:\python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 57, in __getattr__
    """ % self.namespace))
  File "g:\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "g:\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "g:\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

what's wrong with it ?

**Comment by htgoebel** [comment]
Looks like your setup has an issue and some json file can not be read. Please start at 
g:\python36\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtCore.py", line 11 to find out which file is effected.

**Comment by vonlippmann** [comment]
i don't understand what you mean, So i don't kown how to execute your suggestion.

**Comment by bjones1** [comment]
What version of Python, Pyinstaller, and PyQt5 are you using? What installation of Python (Anaconda, from python.org, etc.)?

**Comment by vonlippmann** [comment]
win10
Python 3.6 is installed from python.org.etc
Pyinstaller is installed by `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`
PyQt5 5.10

**Comment by htgoebel** [comment]
> i don't understand what you mean, So i don't kown how to execute your suggestion.

The  tracebacks clearly shows that some json file could not be read. Start reading PyInstaller's code at  g:\python36\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtCore.py", line 11 to find out which file it is. Alternativly you can run PyInstaller under debugger controls (`pdb`) and set a breakpoint to that line.

**Comment by bjones1** [comment]
What do you get when you execute

``` Python
import json
from PyQt5.QtCore import QLibraryInfo

paths = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
location = {x: QLibraryInfo.location(getattr(QLibraryInfo, x))
            for x in paths}
try:
    version = QLibraryInfo.version().segments()
except AttributeError:
    version = None
print(str(json.dumps({
    'isDebugBuild': QLibraryInfo.isDebugBuild(),
    'version': version,
    'location': location,
})))
```

on your PC?

**Comment by vonlippmann** [comment]
the process finished with exit code -1073741819 (0xC0000005)
i found this promblem is caused by the `from PyQt5.QtCore import QLibraryInfo`,
the program crashed somehow when execute `from PyQt5.QtCore import QLibraryInfo`

**Comment by bjones1** [comment]
Your PyQt5 installation is broken, then. Fix that, then try PyInstaller again.

**Comment by vonlippmann** [comment]
OK，i wiil try it then.

**Comment by dlml** [comment]
Did you solve this preoblem ？

**Comment by vivekvkt** [comment]
ghdfghdfhdfh
