### ISSUE TITLE
Cannot load native module 'Crypto.Cipher._raw_ecb' 

### ISSUE THREAD

**Issue by sword1984** [pyinstaller/pyinstaller#3559]
I just import web3

```

E:\PycharmProjects\Ethers\dist\main>main.exe
Traceback (most recent call last):
  File "Ethers\main.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\swordc\appdata\local\programs\python\python36\lib\site-packages
\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "Ethers\transiction.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\swordc\appdata\local\programs\python\python36\lib\site-packages
\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\web3\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\swordc\appdata\local\programs\python\python36\lib\site-packages
\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\eth_account\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\swordc\appdata\local\programs\python\python36\lib\site-packages
\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\eth_account\account.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\swordc\appdata\local\programs\python\python36\lib\site-packages
\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\eth_keyfile\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\swordc\appdata\local\programs\python\python36\lib\site-packages
\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\eth_keyfile\keyfile.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\swordc\appdata\local\programs\python\python36\lib\site-packages
\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Crypto\Cipher\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\swordc\appdata\local\programs\python\python36\lib\site-packages
\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
  File "site-packages\Crypto\Util\_raw_api.py", line 258, in load_pycryptodome_r
aw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp
36-win_amd64.pyd': Failed to load dynlib/dll 'E:\\PycharmProjects\\Ethers\\dist\
\main\\Crypto\\Util\\..\\Cipher\\_raw_ecb.cp36-win_amd64.pyd'. Most probably thi
s dynlib/dll was not found when the application was frozen., Trying '_raw_ecb.py
d': Failed to load dynlib/dll 'E:\\PycharmProjects\\Ethers\\dist\\main\\Crypto\\
Util\\..\\Cipher\\_raw_ecb.pyd'. Most probably this dynlib/dll was not found whe
n the application was frozen.
[6516] Failed to execute script main
```

**Comment by OperationJ** [comment]
same problem encountered when executing a file is there any other possible way
