### ISSUE TITLE
ImportError failing to dlopen() Reason: image not found, but file is included. scipy.sparse

### ISSUE THREAD

**Issue by dsentinel** [pyinstaller/pyinstaller#3564]
Running from the `./dist` dir:
```bash
$./debug_nexus
Traceback (most recent call last):
  File "debug_nexus", line 6, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "nexus/nexus.py", line 15, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "obspy/__init__.py", line 45, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "obspy/core/inventory/__init__.py", line 210, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "obspy/core/inventory/response.py", line 25, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/interpolate/__init__.py", line 175, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/interpolate/interpolate.py", line 32, in <module>
  File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/spatial/__init__.py", line 94, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/spatial/kdtree.py", line 8, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/sparse/__init__.py", line 229, in <module>
  File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/sparse/csr.py", line 15, in <module>
ImportError: dlopen(/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse/_sparsetools.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/libc++.1.dylib
  Referenced from: /Users/lloyd/code/nexus/dist/debug_nexus/libc++.1.dylib
  Reason: image not found
[795] Failed to execute script debug_nexus
```
Can't find image, but those paths are correct and in the `./dist` ???? :
```bash
$otool -L /Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse/_sparsetools.cpython-36m-darwin.so
/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse/_sparsetools.cpython-36m-darwin.so:
	@loader_path/../../libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
$otool -L /Users/lloyd/code/nexus/dist/debug_nexus/libc++.1.dylib
/Users/lloyd/code/nexus/dist/debug_nexus/libc++.1.dylib:
	@loader_path/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++abi.dylib (compatibility version 1.0.0, current version 49.1.0)
	@loader_path/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/libc++abi.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```
using latest pyinstaller :
```bash
$pyinstaller -v
3.4.dev0+32a1bf066

$python --version
Python 3.6.5 :: Anaconda, Inc.

$sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F2511
```
python and most deps including scipy are installed via conda.
I was running into the same error with pyqt so's dlopen failures, uninstalling  from conda and install via pip fixed that
```bash
$conda list
# packages in environment at /Users/lloyd/anaconda2/envs/nexus_dev:
#
# Name                    Version                   Build  Channel
altgraph                  0.15                       py_0    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
basemap                   1.1.0                    py36_4    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
clangdev                  6.0.0                 default_0    conda-forge
cryptography              2.2.1                    py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
expat                     2.2.5                         0    conda-forge
freetype                  2.8.1                         0    conda-forge
future                    0.16.0                   py36_0    conda-forge
geos                      3.6.2                         1    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py36_1    conda-forge
intel-openmp              2018.0.3                      0
jpeg                      9b                            2    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
libcxx                    6.0.0                         0    conda-forge
libedit                   3.1.20170329         hb402a30_2
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.1                h93005f0_2
libiconv                  1.15                          0    conda-forge
libopenblas               0.2.20               hdc02c5d_7
libpng                    1.6.34                        0    conda-forge
libxml2                   2.9.8                         0    conda-forge
libxslt                   1.1.32                        0    conda-forge
llvm-meta                 6.0.0                         0    conda-forge
llvmdev                   6.0.0                 default_3    conda-forge
lxml                      4.2.1                    py36_0    conda-forge
macholib                  1.8                        py_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mkl                       2018.0.3                      1
ncurses                   6.1                           0    conda-forge
nexus                     2018.149                  <pip>
numpy                     1.14.3           py36he6379a5_2
numpy-base                1.14.3           py36h7ef55bc_1
obspy                     1.1.1rc1.post0+255.g06906f389b.obspy.master           <pip>
openssl                   1.0.2o                        0    conda-forge
pefile                    2017.11.5                 <pip>
pip                       9.0.3                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pyinstaller               3.3.1                    py36_0    conda-forge
PyInstaller               3.4.dev0+32a1bf066           <pip>
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
PyQt5                     5.10.1                    <pip>
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.5                hc167b69_1
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
qt                        5.9.5                h02808f3_0
readline                  7.0                  hc1231fa_4
requests                  2.18.4                   py36_1    conda-forge
scipy                     1.1.0            py36hcaad992_0
setuptools                39.2.0                   py36_0    conda-forge
sip                       4.19.8                   py36_0    conda-forge
sip                       4.19.8                    <pip>
six                       1.11.0                   py36_1    conda-forge
sqlalchemy                1.2.8                    py36_0    conda-forge
sqlite                    3.23.1               hf1716c9_0
tbb                       2018_20171205                 0    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

```bash
$pip list
altgraph (0.15)
asn1crypto (0.24.0)
basemap (1.1.0)
certifi (2018.4.16)
cffi (1.11.5)
chardet (3.0.4)
cryptography (2.2.1)
cycler (0.10.0)
decorator (4.3.0)
future (0.16.0)
idna (2.6)
kiwisolver (1.0.1)
lxml (4.2.1)
macholib (1.8)
matplotlib (2.2.2)
nexus (2018.149, /Users/lloyd/code/nexus)
numpy (1.14.3)
obspy (1.1.1rc1.post0+255.g06906f389b.obspy.master, /Users/lloyd/code/obspy)
pefile (2017.11.5)
pip (9.0.3)
pycparser (2.18)
pycrypto (2.6.1)
PyInstaller (3.4.dev0+32a1bf066)
pyOpenSSL (18.0.0)
pyparsing (2.2.0)
pyproj (1.9.5.1)
PyQt5 (5.10.1)
pyshp (1.2.12)
PySocks (1.6.8)
python-dateutil (2.7.3)
pytz (2018.4)
requests (2.18.4)
scipy (1.1.0)
setuptools (39.2.0)
sip (4.19.8)
six (1.11.0)
SQLAlchemy (1.2.8)
tornado (5.0.2)
urllib3 (1.22)
wheel (0.31.0)
```

Bundling seems ok, and grabs the libs:
```bash
$pyinstaller -d -y --clean debug_nexus --log-level DEBUG

33778 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
...
37551 DEBUG: Analyzing /Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-darwin.so
37574 DEBUG: Skipping libSystem.B.dylib dependency of _sparsetools.cpython-36m-darwin.so
37574 DEBUG: Adding libc++.1.dylib dependency of _sparsetools.cpython-36m-darwin.so from /Users/lloyd/anaconda2/envs/nexus_dev/lib/libc++.1.dylib
37574 DEBUG: Analyzing /Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/scipy/sparse/_csparsetools.cpython-36m-darwin.so
37579 DEBUG: Skipping libSystem.B.dylib dependency of _csparsetools.cpython-36m-darwin.so
...
42057 INFO: Building EXE from EXE-00.toc completed successfully.
42061 INFO: checking COLLECT
42061 INFO: Building COLLECT because COLLECT-00.toc is non existent
42061 INFO: Building COLLECT COLLECT-00.toc
59811 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```
#
...also and possibly related: 
Is it a bad sign that 
(from output running in the dist posted at top)
```bash
File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module exec(bytecode, module.__dict__)
```
is using a pyinstaller module from installation site and not within `./dist/` ?
#
Thanks for any help OS hero's!
If it's not obvious what's wrong here, I can try to make a minimal failing case.

**Comment by htgoebel** [comment]
I'm afraid, I can only provide some tips:
1) Do all libs reported by otool for libc++.1.dylib exist?
1) try tracking this down using `strace`, thus you can learn with "image" is not found.
1) Try installing scipy from pip, Conda has several issues.

>  (from output running in the dist posted at top)
> File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module exec(bytecode, module.__dict__)
> is using a pyinstaller module from installation site and not within ./dist/ ?

This is irritating, but should only be an artifact. (This is meant to be fixed since long, but in some cases the filepath is still wrong. Gosh!)

**Comment by dsentinel** [comment]
Thanks for the response and tips.

> I'm afraid, I can only provide some tips:
> 
> Do all libs reported by otool for libc++.1.dylib exist?

Yes those paths exist.
> try tracking this down using strace, thus you can learn with "image" is not found.

It's failing to stat()
because @loader_path isn't expanded ??

```
...
getattrlist("/Users\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users/lloyd\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users/lloyd/code\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users/lloyd/code/nexus\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/scipy\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse/_sparsetools.cpython-36m-darwin.so\0", 0x7FFF67F4B2D0, 0x7FFF557CB930)		 = 0 0
getattrlist("/Users\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/scipy\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse/_sparsetools.cpython-36m-darwin.so\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
stat64("/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse/../../libc++.1.dylib\0", 0x7FFF557CBB38, 0x7FFF557CB810)		 = 0 0
open("/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse/../../libc++.1.dylib\0", 0x0, 0x0)		 = 7 0
pread(0x7, "\317\372\355\376\a\0", 0x1000, 0x0)		 = 4096 0
mmap(0xB21081000, 0x88000, 0x5, 0x12, 0x7, 0x0)		 = 0xB21081000 0
mmap(0xB21109000, 0x5000, 0x3, 0x12, 0x7, 0x88000)		 = 0xB21109000 0
mmap(0xB21111000, 0x4D354, 0x1, 0x12, 0x7, 0x8D000)		 = 0xB21111000 0
fcntl(0x7, 0x32, 0x7FFF557C9C70)		 = 0 0
close(0x7)		 = 0 0
getattrlist("/Users\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/scipy\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/scipy/sparse\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
getattrlist("/Users/lloyd/code/nexus/dist/debug_nexus/libc++.1.dylib\0", 0x7FFF67F4B2D0, 0x7FFF557CB810)		 = 0 0
stat64("@loader_path/libc++.1.dylib\0", 0x7FFF557CBA98, 0x7FFF557CB810)		 = -1 Err#2
...
```

> Try installing scipy from pip, Conda has several issues.

I came to this conclusion and tried with a full pip install. I got a bit further, but eventually ran into similar issues.

> (from output running in the dist posted at top)
> File "/Users/lloyd/anaconda2/envs/nexus_dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module exec(bytecode, module.dict)
> is using a pyinstaller module from installation site and not within ./dist/ ?
> 
> This is irritating, but should only be an artifact. (This is meant to be fixed since long, but in some cases the filepath is still wrong. Gosh!)

ok, if you need an issue/PR for it let me know.
