### ISSUE TITLE
No such file or directory 'x' when running under virtualenv, Python 2.7.12

### ISSUE THREAD

**Issue by streamliner18** [pyinstaller/pyinstaller#3567]
I'm having problem running pyinstaller under a virtualenv. It generates the following error message (which I suppose is an internal error) when I tried to create a bundle.

Note that this error does not occur using the system interpreter (also Python 2.7.12), but because it doesn't have many of my dependencies installed the output bundle is unusable.

The system in question is a Ubuntu 16.04 box.

```bash
(venv) root@devbox:/work/watchdog_sst# pyinstaller --clean --debug -n senpai bootstrap.py
45 INFO: PyInstaller: 3.4.dev0+56ee7e504
46 INFO: Python: 2.7.12
46 INFO: Platform: Linux-4.4.0-62-generic-x86_64-with-debian-stretch-sid
47 INFO: wrote /work/watchdog_sst/senpai.spec
53 INFO: UPX is available.
54 INFO: Removing temporary files and cleaning cache in /root/.cache/pyinstaller
55 INFO: Extending PYTHONPATH with paths
['/work/watchdog_sst', '/work/watchdog_sst']
55 INFO: checking Analysis
56 INFO: Building Analysis because Analysis-00.toc is non existent
56 INFO: Initializing module dependency graph...
Traceback (most recent call last):
  File "<pyrun>/pyrun2.7.py", line 862, in <module>
  File "<pyrun>/pyrun2.7.py", line 654, in pyrun_execute_script
  File "<pyrun>/runpy.py", line 252, in **run_path**
  File "<pyrun>/runpy.py", line 82, in _run_module_code
  File "<pyrun>/runpy.py", line 72, in _run_code
  File "/work/watchdog_sst/venv/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+56ee7e504', 'console_scripts', 'pyinstaller')()
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/__main__.py", line 109, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 241, in __init__
    self.__postinit__()
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 347, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/depend/analysis.py", line 598, in initialize_modgraph
    implies=get_implies(),
  File "/work/watchdog_sst/venv/lib/python2.7/site-packages/PyInstaller/lib/modulegraph/find_modules.py", line 96, in get_implies
    files = os.listdir(xml.etree.__path__[0])
OSError: [Errno 2] No such file or directory: 'x'
```

**Comment by htgoebel** [comment]
What does this return, using the python in your virtual env:
```
import xml.etree
print(xml.etree)
print(xml.etree.__path__)
```
How did you setup the virtual env?
