### ISSUE TITLE
Unable to run Linux executable importing python-pillow

### ISSUE THREAD

**Issue by ase1590** [pyinstaller/pyinstaller#3584]
System: Arch Linux
python: 3.6.5
Pyinstaller: develop
Pillow: 5.1.0
setuptools: 39.2.0

if one imports PIL, pyinstaller will build the package and the resulting executable will fail with the following error:

```
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/usr/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/pkg_resources/__init__.py", line 76, in <module>
ModuleNotFoundError: No module named 'packaging.specifiers'
[1510] Failed to execute script pyi_rth_pkgres
```

example code:
```
from PIL import Image
print("hello world")
```

Debug build log: http://ix.io/1dVY

running the debug executable: http://ix.io/1dVW

**Comment by Viech** [comment]
I can confirm this, a Python 3 script that imports `bearlibterminal` as its only nonstandard library gives almost the exact same output when its compiled version is run:
```
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/usr/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/pkg_resources/__init__.py", line 81, in <module>
ModuleNotFoundError: No module named 'packaging.specifiers'
[31724] Failed to execute script pyi_rth_pkgres
```
There is a folder `PIL` next to the compiled binary that was placed there by PyInstaller, not sure why.

**Comment by vfosterm** [comment]
I can also confirm this.
Python: 3.7.1
Pillow: 5.3.0
OS: Arch Linux 4.18.16

Will test on Windows 10 tomorrow

**Comment by Viech** [comment]
We all three happen to be on Arch Linux, then.

**Comment by vfosterm** [comment]
Yea finally got a chance to build on windows 10. Works fine.

**Comment by vfosterm** [comment]
Also works fine on Debian. Seems to be an Arch specific issue.

**Comment by neverlog** [comment]
I am using
Python: 3.6.7
Pillow: 5.3.0
OS: Windows 10
It still give me error when I import PIL library

Code as below:

from PIL import Image, ImageDraw

file_name = '2.jpg'
print("Hello World, Pyinstaller. Test PIL import")
im = Image.open(file_name)
im.save(''test2.jpg')

It give below error when build:

Exception:
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/Miniconda3/conda-bld/qt_1535195524645/_h_env/Library/plugins

**Comment by bjones1** [comment]
What version of PyInstaller are you using?

**Comment by ase1590** [comment]
My initial issue with Arch seems to be resolved for whatever reason. closing the issue.

**Comment by s0lst1ce** [comment]
So I've tried the development branch myself but it didn't work so after looking some more I fell onto this [gist](https://gist.github.com/hangtwenty/b9820fe204eebb0cc5b9aba49f3c8b22)
Updating `setuptools` and `pip` as shown solved the issue for me.

**Comment by hamdyaea** [comment]
ModuleNotFoundError: No module named 'packaging.specifiers'
[12196] Failed to execute script pyi_rth_pkgres

I have the same error in Manjaro with a Python3 code

**Comment by CrazyIlian** [comment]
To fix this on Arch linux I edited file `/usr/lib/python3.7/site-packages/pkg_resources/__init__.py`

Lines 82-85 _(this code may be on other lines)_
```python
__import__('packaging.version')
__import__('packaging.specifiers')
__import__('packaging.requirements')
__import__('packaging.markers')
```
changed to
```python
import packaging.version
import packaging.specifiers
import packaging.requirements
import packaging.markers
```


I know that changing the source is not good, but the problem is solved

**Comment by Krotera** [comment]
> I know that changing the source is not good, but the problem is solved

For me, changing those lines in `/usr/lib/python3.8/site-packages/pkg_resources/` didn't work with Python 3.8.1; I then got this error:

```
Traceback (most recent call last):
  File "foo.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/dash_core_components/__init__.py", line 12, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEILHt3Dp/dash_core_components/package-info.json'
[341365] Failed to execute script foo
```

**Comment by pasbi** [comment]
It took me quite a while to figure out this trick, though it's obvious in the aftermath. Maybe this is helpful for others:
You don't need to fiddle with system files. Use the option `--hidden-import`:

    pyinstaller myscript.py --onefile --hidden-import 'packaging.requirements' --hidden-import 'pkg_resources.py2_warn'

**Comment by Alexander3XL** [comment]
Hello! 
I have the same bug. That looks like regression.

Additional info:
* Linux 5.7.10-arch1-1
* Python 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0] on linux
* python-setuptools 1:49.2.0-1
* pyinstaller 3.6-6

Steps to reproduce:
```
$ echo -e 'import click\nprint("Test")'>f.py
$ pyinstaller f.py
$ ./dist/f/f
Traceback (most recent call last):
File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
File "/usr/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
exec(bytecode, module.__dict__)
File "site-packages/pkg_resources/__init__.py", line 81, in <module>
ModuleNotFoundError: No module named 'packaging.version'
[54156] Failed to execute script pyi_rth_pkgres
$ pacman -Qo /usr/lib/python3.8/site-packages/pkg_resources/__init__.py
/usr/lib/python3.8/site-packages/pkg_resources/__init__.py is owned by python-setuptools 1:49.2.0-1
```
