### ISSUE TITLE
pyinstaller -h is broken

### ISSUE THREAD

**Issue by ase1590** [pyinstaller/pyinstaller#3585]
System: Arch Linux
python: 3.6.5
Pyinstaller: develop

``
pyinstaller -h
``
results in an AssertionError. 

output:

```
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+g2aa0a333', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3.6/site-packages/PyInstaller/__main__.py", line 92, in run
    args = parser.parse_args(pyi_args)
  File "/usr/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1020, in __call__
    parser.print_help()
  File "/usr/lib/python3.6/argparse.py", line 2362, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.6/argparse.py", line 2346, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.6/argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 333, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError
```

**Comment by tallforasmurf** [comment]
confirm on MacOS, any invalid/unknown option does this. As shown, main calls argparse, argparse gets into trouble trying to compose a usage message.

**Comment by hamptus** [comment]
Fixed in https://github.com/pyinstaller/pyinstaller/pull/3587
