### ISSUE TITLE
pyodbc attribute issue

### ISSUE THREAD

**Issue by Nicholas-Hoff** [pyinstaller/pyinstaller#3588]
Hello,

I'm using Python 3.6 with Django 1.11.  I've managed to get all of my modules installed, but i'm having an issue with pyodbc with SQL server.

I get the following error message when attempting to runserver.

```
Traceback (most recent call last):
  File "site-packages\django\utils\autoreload.py", line 228, in wrapper
  File "site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
  File "site-packages\django\utils\autoreload.py", line 251, in raise_last_exception
  File "site-packages\django\utils\six.py", line 685, in reraise
  File "site-packages\django\utils\autoreload.py", line 228, in wrapper
  File "site-packages\django\__init__.py", line 27, in setup
  File "site-packages\django\apps\registry.py", line 108, in populate
  File "site-packages\django\apps\config.py", line 202, in import_models
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\users\hfa9592\appdata\local\programs\python\python36\lib\site-packages\PyInstalle
    exec(bytecode, module.__dict__)
  File "site-packages\django\contrib\auth\models.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\users\hfa9592\appdata\local\programs\python\python36\lib\site-packages\PyInstalle
    exec(bytecode, module.__dict__)
  File "site-packages\django\contrib\auth\base_user.py", line 52, in <module>
  File "site-packages\django\db\models\base.py", line 124, in __new__
  File "site-packages\django\db\models\base.py", line 331, in add_to_class
  File "site-packages\django\db\models\options.py", line 214, in contribute_to_class
  File "site-packages\django\db\__init__.py", line 33, in __getattr__
  File "site-packages\django\db\utils.py", line 211, in __getitem__
  File "site-packages\django\db\utils.py", line 115, in load_backend
  File "importlib\__init__.py", line 126, in import_module
  File "C:\python\dsssecurity\dist\dsssecurity\sql_server\pyodbc\base.py", line 18, in <modu
    pyodbc_ver = tuple(map(int, Database.version.split('.')[:2]))
AttributeError: module 'pyodbc' has no attribute 'version'
```

My dist app is populated with the directory as sql_server\pyodbc where the error is occuring.  I took a copy of pyodbc in the sql_server directory and added it to the root dist app.

Originally I would receive the following error message before I created the copy of pyodbc one directory down.  

```
Traceback (most recent call last):
  File "site-packages\django\utils\autoreload.py", line 228, in wrapper
  File "site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
  File "site-packages\django\utils\autoreload.py", line 251, in raise_last_exception
  File "site-packages\django\utils\six.py", line 685, in reraise
  File "site-packages\django\utils\autoreload.py", line 228, in wrapper
  File "site-packages\django\__init__.py", line 27, in setup
  File "site-packages\django\apps\registry.py", line 108, in populate
  File "site-packages\django\apps\config.py", line 202, in import_models
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\users\hfa9592\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", l
    exec(bytecode, module.__dict__)
  File "site-packages\django\contrib\auth\models.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\users\hfa9592\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", l
    exec(bytecode, module.__dict__)
  File "site-packages\django\contrib\auth\base_user.py", line 52, in <module>
  File "site-packages\django\db\models\base.py", line 124, in __new__
  File "site-packages\django\db\models\base.py", line 331, in add_to_class
  File "site-packages\django\db\models\options.py", line 214, in contribute_to_class
  File "site-packages\django\db\__init__.py", line 33, in __getattr__
  File "site-packages\django\db\utils.py", line 211, in __getitem__
  File "site-packages\django\db\utils.py", line 115, in load_backend
  File "importlib\__init__.py", line 126, in import_module
  File "C:\python\dsssecurity\dist\dsssecurity\sql_server\pyodbc\base.py", line 16, in <module>
    raise ImproperlyConfigured("Error loading pyodbc module: %s" % e)
```
Below is the .spec file:

```
    # -*- mode: python -*-
    
    block_cipher = None
    
    
    a = Analysis(['manage.py'],
                 pathex=['C:\\python\\dsssecurity'],
                 binaries=[],
                 datas=[],
    			 hiddenimports=['django_select2.apps','django.contrib.admin.apps','django.contrib.auth.apps','django.contrib.contenttypes.apps','django.contrib.sessions.apps','django.contrib.messages.apps','django.contrib.staticfiles.apps','django_filters.apps','widget_tweaks.apps'],
                 hookspath=[],
                 runtime_hooks=[],
                 excludes=[],
                 win_no_prefer_redirects=False,
                 win_private_assemblies=False,
                 cipher=block_cipher)
    pyz = PYZ(a.pure, a.zipped_data,
                 cipher=block_cipher)
    exe = EXE(pyz,
              a.scripts,
              exclude_binaries=True,
              name='dsssecurity',
              debug=False,
              strip=False,
              upx=True,
              console=True )
    coll = COLLECT(exe,
                   a.binaries,
                   a.zipfiles,
                   a.datas,
                   strip=False,
                   upx=True,
                   name='dsssecurity')


```

**Comment by Nicholas-Hoff** [comment]
I figured out the issue.  Please delete.

**Comment by Nicholas-Hoff** [comment]
Hello,

I'm using Python 3.6 with Django 1.11.  I've managed to get all of my modules installed, but i'm having an issue with pyodbc with SQL server.

I get the following error message when attempting to runserver.

```
Traceback (most recent call last):
  File "site-packages\django\utils\autoreload.py", line 228, in wrapper
  File "site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
  File "site-packages\django\utils\autoreload.py", line 251, in raise_last_exception
  File "site-packages\django\utils\six.py", line 685, in reraise
  File "site-packages\django\utils\autoreload.py", line 228, in wrapper
  File "site-packages\django\__init__.py", line 27, in setup
  File "site-packages\django\apps\registry.py", line 108, in populate
  File "site-packages\django\apps\config.py", line 202, in import_models
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\users\hfa9592\appdata\local\programs\python\python36\lib\site-packages\PyInstalle
    exec(bytecode, module.__dict__)
  File "site-packages\django\contrib\auth\models.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\users\hfa9592\appdata\local\programs\python\python36\lib\site-packages\PyInstalle
    exec(bytecode, module.__dict__)
  File "site-packages\django\contrib\auth\base_user.py", line 52, in <module>
  File "site-packages\django\db\models\base.py", line 124, in __new__
  File "site-packages\django\db\models\base.py", line 331, in add_to_class
  File "site-packages\django\db\models\options.py", line 214, in contribute_to_class
  File "site-packages\django\db\__init__.py", line 33, in __getattr__
  File "site-packages\django\db\utils.py", line 211, in __getitem__
  File "site-packages\django\db\utils.py", line 115, in load_backend
  File "importlib\__init__.py", line 126, in import_module
  File "C:\python\dsssecurity\dist\dsssecurity\sql_server\pyodbc\base.py", line 18, in <modu
    pyodbc_ver = tuple(map(int, Database.version.split('.')[:2]))
AttributeError: module 'pyodbc' has no attribute 'version'
```

My dist app is populated with the directory as sql_server\pyodbc where the error is occuring.  I took a copy of pyodbc in the sql_server directory and added it to the root dist app.

Originally I would receive the following error message before I created the copy of pyodbc one directory down.  

```
Traceback (most recent call last):
  File "site-packages\django\utils\autoreload.py", line 228, in wrapper
  File "site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
  File "site-packages\django\utils\autoreload.py", line 251, in raise_last_exception
  File "site-packages\django\utils\six.py", line 685, in reraise
  File "site-packages\django\utils\autoreload.py", line 228, in wrapper
  File "site-packages\django\__init__.py", line 27, in setup
  File "site-packages\django\apps\registry.py", line 108, in populate
  File "site-packages\django\apps\config.py", line 202, in import_models
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\users\hfa9592\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", l
    exec(bytecode, module.__dict__)
  File "site-packages\django\contrib\auth\models.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\users\hfa9592\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", l
    exec(bytecode, module.__dict__)
  File "site-packages\django\contrib\auth\base_user.py", line 52, in <module>
  File "site-packages\django\db\models\base.py", line 124, in __new__
  File "site-packages\django\db\models\base.py", line 331, in add_to_class
  File "site-packages\django\db\models\options.py", line 214, in contribute_to_class
  File "site-packages\django\db\__init__.py", line 33, in __getattr__
  File "site-packages\django\db\utils.py", line 211, in __getitem__
  File "site-packages\django\db\utils.py", line 115, in load_backend
  File "importlib\__init__.py", line 126, in import_module
  File "C:\python\dsssecurity\dist\dsssecurity\sql_server\pyodbc\base.py", line 16, in <module>
    raise ImproperlyConfigured("Error loading pyodbc module: %s" % e)
```

**Comment by Nicholas-Hoff** [comment]
Comment this was fixed by adding the info.egg file and running pyinstaller with the new .spec file.
