### ISSUE TITLE
Add file exist check for compile_py_files

### ISSUE THREAD

**Issue by crmchan** [pyinstaller/pyinstaller#3599]
```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

Whether we need to check file exist or not before execute for code below.

\Lib\site-packages\PyInstaller\utils\misc.py
def compile_py_files(toc, workpath):

            #Maybe we need to check obj_fnm file exist or not?  I found that we may got src_fnm = and obj_fnm = -
            needs_compile = ( (mtime(src_fnm) > mtime(obj_fnm) )
                              or
                              (open(obj_fnm, 'rb').read()[:4] != BYTECODE_MAGIC)
                            )

            #Maybe we need to check obj_fnm file exist or not?  
            new_toc.append((nm, obj_fnm, typ))

BR
RUIM

**Comment by htgoebel** [comment]
Thanks for taking your time checking the code and trying to improve PyInstaller. Nevertheless reporting non-issues cost my rare spare time and hinders my from working on actual issues.

Thus my question: Are you experiencing an issue with this code? Since the case you are taking about is already taken care in https://github.com/pyinstaller/pyinstaller/blob/v3.3.1/PyInstaller/utils/misc.py#L92

**Comment by htgoebel** [comment]
Closing, will re-open if it is an actual issue.

**Comment by htgoebel** [comment]
Now I see, this is a follow up to #3598. Thanks for tracking this down. Anyway, please do not open new issues for the same topic - this adds to the pile of open issues and costs my spare time. Thanks.

Anyway, this issue is more clear, so I'll keep this open. From #3598:
```
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 595, in assemble
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):
  File "…\site-packages\PyInstaller\utils\misc.py", line 150, in compile_py_files
    (open(obj_fnm, 'rb').read()[:4] != BYTECODE_MAGIC)
FileNotFoundError: [Errno 2] No such file or directory: '…\site-packages\\html5lib-1.0.1-py3.6.egg\\html5lib\\_utils.pyo'
```

This can happen if in the snippet shown above, the obj file is not older then the src file, but the obj file does not exist at all. Huh? How can this happen?

src | obj | mtime(src_fnm) | mtime(obj_fnm) | mtime(src_fnm) > mtime(obj_fnm)
--- | --- | -------------- | -------------- | -----------------------
exists  | older   | 200 | 190 | True
exists  | same    | 200 | 200 | False
exists  | newer   | 200 | 210 | False
exists  | missing | 200 |  0  | True
missing | older   |  0  | 190 | False
missing | same    |  0  | 200 | False
missing | newer   |  0  | 210 | False
missing | missing |  0  |  0  | False

In all cases where `mtime(src_fnm) > mtime(obj_fnm)` is False, the obj-file exists. There is only one exception: if both the source and the obj file are missing. But this is not the case here, see https://github.com/pyinstaller/pyinstaller/issues/3598#issue-336213868: the src-file exists.

Okay, we can simply wrap the effected lines my `try`-`except`. But I would like to know the root cause instead of piling up code for cases which (theoretically) can not happen.

@crmchan Can you please run Pyinstaller under debugger control (`python -m pdb D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller_main_.py`) and when it crashes check if `src_fnm` and `obj_fnm` match (except of the extension). Also please check the ouput of `mtime(src_fnm)` and `mtime(obj_fnm)`. Thanks.

**Comment by crmchan** [comment]
@htgoebel 
Dear sir, really sorry for it. I would remember what you said.

1  For "AttributeError: 'str' object has no attribute 'items'", I change code in "PyInstaller\hooks\pre_safe_import_module\hook-setuptools.extern". I don't know why it's nok using eval_statement from hook-setuptools.extern.six.moves.py/pre_safe_import_module

  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\depend\analysis.py", line 260, in _safe_import_modu
le
    hook_module.pre_safe_import_module(hook_api)
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\hooks\pre_safe_import_module\hook-setuptools.extern.six.moves.py", line 34, in pre_safe_import_module
    for real_module_name, six_module_name in real_to_six_module_name.items():
AttributeError: 'str' object has no attribute 'items'


2 From #3598, I would collect log.

Appreciate for your reply!!
BR
RUIM

**Comment by crmchan** [comment]
@htgoebel 
Dear sir,
For 2 From #3598,  you can check value of src_fnm /obj_fnm/ mtime(src_fnm) /mtime(obj_fnm) from below. 
I found that there is no folder html5lib-1.0.1-py3.6.egg under "D:\Anaconda3\envs\intel\Lib\site-packages", so after I copy the folder "--workspace\out\Helloword\html5lib-1.0.1-py3.6.egg" to  "D:\Anaconda3\envs\intel\Lib\site-packages", there is no error.

(Pdb) p src_fnm
'D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\html5lib-1.0.1-py3.6.egg\\html5lib\\_utils.py'[0K
(Pdb) p obj_fnm
'D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\html5lib-1.0.1-py3.6.egg\\html5lib\\_utils.pyo'[0K
(Pdb) p mtime(src_fnm)
0
(Pdb) p mtime(obj_fnm)
0



> workpath = 'E:\\Code\\Script\\Python\\Helloword\\release\\out\\helloworld'[0K
(Pdb)[0K
[7G[?25h[?25l
(Pdb) p[0K
[8G[?25h[?25l
[9G[?25h[?25l
(Pdb) p src_fnm[0K
[16G[?25h[?25l
'D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\html5lib-1.0.1-py3.6.egg\\html5lib\\_utils.py'[0K
(Pdb) p obj_fnm[0K
[16G[?25h[?25l
'D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\html5lib-1.0.1-py3.6.egg\\html5lib\\_utils.pyo'[0K
(Pdb) p mtime(src_fnm)[0K
[23G[?25h[?25l
0[0K
(Pdb) p mtime(obj_fnm)[0K
[23G[?25h[?25l
0[0K
(Pdb) c[0K
[8G[?25h[?25l
> d:\anaconda3\envs\intel\lib\site-packages\pyinstaller\utils\misc.py(157)compile_py_files()[0K
-> if needs_compile:[0K
(Pdb)[0K
[7G[?25h[?25l
(Pdb) c[0K
[8G[?25h[?25l
> d:\anaconda3\envs\intel\lib\site-packages\pyinstaller\utils\misc.py(155)compile_py_files()[0K
-> pdb.set_trace()[0K
(Pdb)[0K
[7G[?25h[?25l
(Pdb) c[0K
[8G[?25h[?25l
> d:\anaconda3\envs\intel\lib\site-packages\pyinstaller\utils\misc.py(157)compile_py_files()[0K
-> if needs_compile:[0K
[12G[?25h[?25l
(Pdb) exit()[0K
Traceback (most recent call last):[0K
  File "setup.py", line 412, in <module>[0K
    run(opts)[0K
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\__main__.py", line 111, in run[0K
    run_build(pyi_config, spec_file, **vars(args))[0K
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build[0K
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)[0K
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main[0K
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))[0K
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build[0K
[0K
[1G[?25h[?25l
    exec(text, spec_namespace)[0K
  File "<string>", line 17, in <module>[0K
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__[0K
    self.__postinit__()[0K
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit[0K_
_[0K
    self.assemble()[0K
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 595, in assemble[0K
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):[0K
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\utils\misc.py", line 157, in compile_py_files[0K
    if needs_compile:[0K
  File "D:\Anaconda3\envs\intel\lib
[2018-06-28_142254_mtime(src_fnm) and mtime(obj_fnm) is zero.txt](https://github.com/pyinstaller/pyinstaller/files/2144118/2018-06-28_142254_mtime.src_fnm.and.mtime.obj_fnm.is.zero.txt)
\site-packages\PyInstaller\utils\misc.py", line 157, in 



>

**Comment by htgoebel** [comment]
@crmchan *This* ticket is about "Add file exist check for compile_py_files". Stop mixing issues! This does *not* help solving any of them. Even if for you they look related, they are not, and each if them has their own ticket. Post the relevant information to the ticket where it belongs. Otherwise I will not work any any of them! *angry*

**Comment by htgoebel** [comment]
After calming down, the solution seem to be simple:

> But no folder "html5lib-1.0.1-py3.6.egg" instead of only signal file name "html5lib-1.0.1-py3.6.egg"(egg file) existing , while we found the folder "html5lib-1.0.1-py3.6.egg" existed 

Did I understand you right: There is a *file* `D:\Anaconda3\envs\intel\lib\site-packages\html5lib-1.0.1-py3.6.egg` (which is a zip-file)? PyInstaller currently does not support zipped eggs.

Please install html5lib *unzipped* using `easy_install --always-unzip` or using `pip install`.

**Comment by crmchan** [comment]
@htgoebel 
Sorry, it's misunderstanding, because not familiar with this code, so I encounter with issue #3598 and #3599, which is duplicat to u and I can't clarify with it. You told me issue them in the same topic, so I regard item3 as the same.  I would issue item 3 to another issue.
Sorry!
