### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Administrator\AppData\Roaming\pyinstalle r\bincache00_py36_64bit\out\hellowork\hellowork.exe.manifest'

### ISSUE THREAD

**Issue by crmchan** [pyinstaller/pyinstaller#3604]
* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Administrator\AppData\Roaming\pyinstalle
r\bincache00_py36_64bit\out\hellowork\hellowork.exe.manifest'

I wanna know why does pyinstaller generate the temp date to "C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py36_64bit\out\" instead of the folder I required as below.
Actually we can gennerate the file as folder below, but why there is some dependence on C:\Users\Administrator\AppData\..... instead of on output foulder? For example, use manifest file of temp folder instead of output folder_

        r'--workpath=E:\Code\Script\Python\hellowork\release\out',\
        r'--distpath=E:\Code\Script\Python\hellowork\release\out\dict'
Traceback (most recent call last):
File "setup.py", line 412, in 
run(opts)
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller_main_.py", line 111, in run
run_build(pyi_config, spec_file, **vars(args))
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller_main_.py", line 63, in run_build
PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
exec(text, spec_namespace)
File "", line 35, in 
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\api.py", line 661, in init
self.postinit()
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in _postinit
_
self.assemble()
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\api.py", line 692, in assemble
dist_nm=inm)
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\utils.py", line 247, in checkCache
manifest.writeprettyxml(cachedfile)
File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 948, in writepr
ettyxml
filename_or_file = open(filename_or_file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py36_64bit\out\hellowork\hellowork.exe.manifest'

BR
RUIM

**Comment by htgoebel** [comment]
> why there is some dependence on C:\Users\Administrator\AppData..... instead of on output foulder

The cache is created in %APPDATA%. You can overwrite it  by setting %PYINSTALLER_CONFIG_DIR%, [see the manual](https://pyinstaller.readthedocs.io/en/v3.3.1/search.html?q=PYINSTALLER_CONFIG_DIR&check_keywords=yes&area=default).

I can not tell you why PyInstaller tries to access the manifest here. Maybe your spec-file includes some code changing this? Did you add the manifest as EXTENSION or BINARY? I strongly suggest starting with a basic spefcfile as generated by `pyi-makespec`.

>
    r'--workpath=E:\Code\Script\Python\hellowork\release\out',\
    r'--distpath=E:\Code\Script\Python\hellowork\release\out\dict'

Please use `--workpath=...\out\build`. Pyinstaller might not be prepared to have the `distpath` directory below `workpath`.

Anyway, I strongly suggest to *not* develop software (and build software) as Administrator. This is a security risk.
