### ISSUE TITLE
Can't seem to open my app after building

### ISSUE THREAD

**Issue by araa47** [pyinstaller/pyinstaller#3619]
Output when trying to open the packaged .app
```
Traceback (most recent call last):
  File "/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/__boot__.py", line 355, in <module>
    _run()
  File "/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/__boot__.py", line 340, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/app.py", line 3, in <module>
    from web3 import Web3, HTTPProvider
  File "/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python3.6/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "eth_account/__init__.pyc", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "eth_account/account.pyc", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "eth_keyfile/__init__.pyc", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "eth_keyfile/keyfile.pyc", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "Crypto/Cipher/__init__.pyc", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "Crypto/Cipher/_mode_ecb.pyc", line 46, in <module>
  File "Crypto/Util/_raw_api.pyc", line 258, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-36m-darwin.so': cannot load library '/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.cpython-36m-darwin.so': dlopen(/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.cpython-36m-darwin.so, 2): no suitable image found.  Did find:
	/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.cpython-36m-darwin.so: stat() failed with errno=20.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.cpython-36m-darwin.so', Trying '_raw_ecb.abi3.so': cannot load library '/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.abi3.so': dlopen(/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 2): no suitable image found.  Did find:
	/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.abi3.so: stat() failed with errno=20.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.abi3.so', Trying '_raw_ecb.so': cannot load library '/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.so': dlopen(/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.so, 2): no suitable image found.  Did find:
	/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.so: stat() failed with errno=20.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/akshay/Documents/Work/dec/dist/app.app/Contents/Resources/lib/python36.zip/Crypto/Util/../Cipher/_raw_ecb.so'
2018-07-05 02:39:37.846 app[36919:225145] app Error
(venv) Akhays-MacBook-Pro:dec akshay$ rm ~/Library/Application Support/pyinstaller
rm: /Users/akshay/Library/Application: No such file or directory
rm: Support/pyinstaller: No such file or directory
```
OS Version: 10.13.3
pyInstaller Version: PyInstaller==3.4.dev0+59387c927
cryptodome version: pycryptodome==3.6.3

"setup.py" file

```
from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'packages':['web3', 'tkinter', 'requests', 'cytoolz']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

```

**Comment by htgoebel** [comment]
Please see https://github.com/pyinstaller/pyinstaller/issues/2365#issuecomment-384069038
