### ISSUE TITLE
Compiled Programs Return Fatal Python Errors Upon Running

### ISSUE THREAD

**Issue by Delkarix** [pyinstaller/pyinstaller#3624]
* Windows Version: 10.0.17134.112
* Python Version: 3.7.0
* PyInstaller Version: 3.3.1
* Environment: Administrator Command Prompt

There are actually two problems in this issue. The first is that when I compile everything, running either application causes it to crash. The second is that I can't install the latest developed version.

## First problem

When I checked you're page on "How to report bugs" I tried *EVERYTHING* on that list, even going as far as uninstalling and reinstalling PyInstaller for several of the actions listed there. But none worked. First I tried installing PyInstaller:
`pip install pyinstaller --upgrade`
So far so good. When I actually tried to use it:
`pyinstaller helloworld.py`
It would still act normal (except stream a long line of text saying `WARNING: lib not found...`. I don't know if that's normal)
As usual, it would create two directories, dist and build.
When running the application from build, this happens:
`Error loading Python DLL 'C:\Users\Delkarix\Desktop\build\helloworld\python37.dll'. LoadLibrary: The specified module could not be found.`
I am pretty sure that that is supposed to happen, because I have installed different versions of PyInstaller in different places, all yielding the same result. Except they worked at the dist one.
When running the application from dist, this happens:
```
Fatal Python error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x00006d40 (most recent call first):
```
I tried many, many things to try to get it to work, but nothing did.

## Second Problem
When trying to install the package from `https://github.com/pyinstaller/pyinstaller/archive/develop.zip`, then this error immediately appears:
```
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Downloading https://github.com/pyinstaller/pyinstaller/archive/develop.zip (4.0MB)
    100% |████████████████████████████████| 4.0MB 1.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "c:\users\delkarix\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\core\__init__.py", line 29, in <module>
        import cffi
    ModuleNotFoundError: No module named 'cffi'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DELKARIX~1\AppData\Local\Temp\pip-req-build-5l7w9emk\setup.py", line 20, in <module>
        from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
      File "C:\Users\DELKARIX~1\AppData\Local\Temp\pip-req-build-5l7w9emk\PyInstaller\__init__.py", line 16, in <module>
        from . import compat
      File "C:\Users\DELKARIX~1\AppData\Local\Temp\pip-req-build-5l7w9emk\PyInstaller\compat.py", line 209, in <module>
        from win32ctypes.pywin32 import pywintypes  # noqa: F401
      File "c:\users\delkarix\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\pywin32\__init__.py", line 21, in <module>
        from win32ctypes.pywin32 import win32api
      File "c:\users\delkarix\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\pywin32\win32api.py", line 23, in <module>
        from win32ctypes.core import _common, _kernel32, _backend
      File "c:\users\delkarix\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\core\__init__.py", line 33, in <module>
        from .ctypes import _advapi32, _common, _kernel32
      File "c:\users\delkarix\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\core\ctypes\_advapi32.py", line 134

        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Delkarix\AppData\Local\Temp\pip-req-build-5l7w9emk\
```
I have tried many different methods to fixing it, but none of them worked.

**Comment by Delkarix** [comment]
Edit: Apparently Python 3.7 is not supported :(
