### ISSUE TITLE
Python 3.7.0 does not build with develp branch Win10 x64

### ISSUE THREAD

**Issue by illera88** [pyinstaller/pyinstaller#3634]
Hi there!

I've followed your indications to install the last develop code which states that supports python 3.7.0. Unfortunately I'm getting errors when trying to install it. I've installed `pywin32` as requested in your instructions but i'm still getting this:

```
C:\Users\user\Documents\code\pyinstaller>C:\Python37.0-x64\python.exe setup.py install
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  File "C:\Users\user\Documents\code\pyinstaller\PyInstaller\__init__.py", line 16, in <module>
    from . import compat
  File "C:\Users\user\Documents\code\pyinstaller\PyInstaller\compat.py", line 209, in <module>
    from win32ctypes.pywin32 import pywintypes  # noqa: F401
  File "C:\Python37.0-x64\lib\site-packages\win32ctypes\pywin32\__init__.py", line 21, in <module>
    from win32ctypes.pywin32 import win32api
  File "C:\Python37.0-x64\lib\site-packages\win32ctypes\pywin32\win32api.py", line 23, in <module>
    from win32ctypes.core import _common, _kernel32, _backend
  File "C:\Python37.0-x64\lib\site-packages\win32ctypes\core\__init__.py", line 39, in <module>
    from .cffi import _advapi32, _common, _kernel32
  File "C:\Python37.0-x64\lib\site-packages\win32ctypes\core\cffi\_advapi32.py", line 198

    ^
SyntaxError: invalid syntax
```

Is there anything i'm missing or is Python 3.7.0 not ready for being used with Pyinstaller?

Thanks

**Comment by htgoebel** [comment]
Obviously this syntax error occurs in C:\Python37.0-x64\lib\site-packages\win32ctypes\core\cffi\_advapi32.py, line 198 and is unrelated to PyInstaller. Please check if you have the correct version of win32ctypes insalled.

**Comment by illera88** [comment]
I have the last version. I've seen that Im not the first one to advice that problem:

https://github.com/pyinstaller/pyinstaller/issues/3399

I thing you use 2to3 and it makes the code erroring??

**Comment by AlexanderBV1** [comment]
Delete line 198 in that script and it's all fixed.

> C:\Python37.0-x64\lib\site-packages\win32ctypes\core\cffi_advapi32.py

**Comment by jaraco** [comment]
The issue with win32ctypes is here: https://github.com/enthought/pywin32-ctypes/issues/81

**Comment by Legorooj** [comment]
This is not an issue of PyInstaller
