### ISSUE TITLE
Missing pyimod03_importers when running

### ISSUE THREAD

**Issue by teryakizhang** [pyinstaller/pyinstaller#3645]
I am using the latest dev version to freeze a python 3.7 script. This is what I get from running the .exe generated and I have followed all of the debugging tips but couldn't figure out why this is. Not even sure why the exe is reading from python library. And checking that directory pyimod03_importers.py is in there as well, so not even sure where the problem is.

    (parse-sim) C:\Users\username\py_venvs\parse-sim\Execuetable\dist\parse-sim>parse-sim.exe
    [11372] mod is NULL - structValueError: bad marshal data (unknown type code)
    [11372] mod is NULL - pyimod01_os_pathValueError: bad marshal data (unknown type code)
    [11372] mod is NULL - pyimod02_archiveValueError: bad marshal data (unknown type code)
    [11372] mod is NULL - pyimod03_importersValueError: bad marshal data (unknown type code)
    Traceback (most recent call last):
       File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 15, in <module>
    ModuleNotFoundError: No module named 'pyimod03_importers'
    [11372] Failed to execute script pyiboot01_bootstrap

**Comment by Timx85** [comment]
I have the same issue and did not found a solution for this yet

**Comment by illera88** [comment]
Same thing for me. But on top of that it seems that python37.dll is not copied to the path where the generated `.exe` is.

In addition it seems that the correct modules are not being added to the generated zip file since my python code uses `random` and there is no `random.pyc` in the zip file.

**Comment by melvyn2** [comment]
Pyinstaller doesn't seem to support python 3.7 yet. Are there problems with using 3.6?

**Comment by teryakizhang** [comment]
I was spending too long trying to get Python37 to work so I just downgraded back to 36 and it worked. If you don't have anything backward incompatible downgrading for the time being is probably the fastest fix.

**Comment by Timx85** [comment]
Yes I think thats the best solution for now

**Comment by SwankShire** [comment]
I have built the bootloader and im still getting basically the same error

```

[5704] mod is NULL - structValueError: bad marshal data (unknown type code)
[5704] mod is NULL - pyimod01_os_pathValueError: bad marshal data (unknown type code)
[5704] mod is NULL - pyimod02_archiveValueError: bad marshal data (unknown type code)
[5704] mod is NULL - pyimod03_importersValueError: bad marshal data (unknown type code)
Traceback (most recent call last):
  File "lib\site-packages\pyinstaller-3.4.dev0+6e5c70e06-py3.7.egg\PyInstaller\loader\pyiboot01_bootstrap.py", line 15, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[5704] Failed to execute script pyiboot01_bootstrap

```

**Comment by Paco112** [comment]
Build bootloader not work with python 3.7 :

`~/pyinstaller/bootloader$ python3.7 ./waf all
Traceback (most recent call last):
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Node.py", line 295, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 122, in waf_entry_point
    run_commands()
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 179, in run_commands
    parse_options()
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py", line 152, in parse_options
    Context.create_context('options').execute()
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Options.py", line 149, in execute
    super(OptionsContext,self).execute()
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 88, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 129, in recurse
    user_function(self)
  File "/home/pyinstaller/bootloader/wscript", line 106, in options
    ctx.load('compiler_c')
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 85, in load
    fun(self)
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Tools/compiler_c.py", line 40, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py", line 324, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Node.py", line 344, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/pyinstaller/bootloader/.waf3-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Node.py", line 344, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
`

**Comment by fredrikaverpil** [comment]
I'm getting the same error as @Paco112 when attempting to build the bootloader.

**Comment by dimon222** [comment]
waf that is available as a part of pyinstaller is not compatible with python 3.7 due to breaking changes (check PEP). I installed latest waf from their gitlab, compiled, but even then I get proper build, but fail with error that @SwankShire mentioned, which is entirely pyinstaller's codebase apparently.

**Comment by charlesoblack** [comment]
@bjones1 any preview on when your commit is going to make it onto pyinstaller/develop?

**Comment by bjones1** [comment]
Already pushed (I used a different branch). Tests pass on Appveyor for Python 3.7 x64 and x32.

...but the bootloader binaries aren't included yet. @htgoebel will update those when he's ready. Until then, `python waf all --target-arch=64-bit` from the bootloader/ subdirectory.

**Comment by htgoebel** [comment]
Bootloaders are updated now.
