### ISSUE TITLE
KeyboardInterrupt input

### ISSUE THREAD

**Issue by yamontv** [pyinstaller/pyinstaller#3646]
Hello. I'm using Ubuntu 16.04, Python3.6.5, PyInstaller 3.4.dev0+7817d3fac (latest dev).
My application wait from user a lot of text input data, and if on some stage user want to stop application he should use ctrl+c. Application do a lot of background in different threads. If I run my code with clean Python all works fine. But if I build application with PyInstaller in 80% of cases error occurs after pressing ctrl+c.
I write simple example to show issue.
sigint.py:

> try:
    dt = input("input smth:")
except KeyboardInterrupt:
    pass

Build this application using this command:
`pyinstaller --onefile --specpath=./ --workpath=./build --distpath=./ sigint.py`

Due to no background task this example crashing in 10-20% cases with this error:

> input smth:^CTraceback (most recent call last):
  File "sigint.py", line 2, in <module>
    dt = input("input smth:")
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "sigint.py", line 2, in <module>
    dt = input("input smth:")
KeyboardInterrupt
[16060] Failed to execute script sigint

Is this a bug or I'm doing something wrong?

**Comment by htgoebel** [comment]
PyInstaller currently does not handle all signals.  #3515 is about to solve this.

**Comment by carlosperate** [comment]
PR https://github.com/pyinstaller/pyinstaller/pull/3515/ has been merged a while ago, and in v3.4 this is still occurring, is that correct?
Just wanted to check if this was a known problem, or if maybe I was experiencing something different.

**Comment by yanwugu** [comment]
Any update on this?

**Comment by eric15342335** [comment]
try --onedir?

**Comment by raulperez** [comment]
Any news on this? Did somebody find a solution for this issue?

**Comment by rokm** [comment]
> Any news on this? Did somebody find a solution for this issue?

Have you tried adding `--bootloader-ignore-signals` to your PyInstaller command? This should prevent the parent process in onefile from forwarding the signal to the child, who should receive its own signal due to being in the same process group.

**Comment by raulperez** [comment]
Yes:

pyinstaller --onefile --noconfirm --console --clean --log-level=WARN --bootloader-ignore-signals --key=MySuperSecretPassword --strip tmp/uart-tx-rx-tester.py


And still see this kind of messages randomly:

➜  dist git:(dev) ✗ ./uart-tx-rx-tester --port /dev/cu.usbserial-FT4Y3OGC --file-name test.json
^CTraceback (most recent call last):
  File "subprocess.py", line 69, in <module>
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_subprocess.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "subprocess.py", line 74, in <module>
KeyboardInterrupt
[83897] Failed to execute script 'pyi_rth_subprocess' due to unhandled exception!

**Comment by rokm** [comment]
Hmm, that doesn't look like "`KeyboardInterrupt` while handling `KeyboardInterrupt`" that was originally reported (and which is caused by child process of onefile program receiving the signal twice; once from process group, and once forwarded by the parent process). So it is probably a different issue altogether:

1. when you get the error, is the traceback different each time?

2. does your program run its executable as a sub-process (either directly, or by using `multiprocessing`?).

Because the only scenario I can imagine where `KeyboardInterrupt` would occur while running a run-time hook is if your program is spawning a sub-process, and you Ctrl+C interrupt it while the sub-process is performing bootstrap (either loading bootstrap modules or running run-time hooks)...
