### ISSUE TITLE
Problem with gevent

### ISSUE THREAD

**Issue by dickkniep** [pyinstaller/pyinstaller#3648]
python version 3.6.5
Pyinstaller version 3.3.1

Trying to freeze application with Flask / Connexion / gevent into exe for Windows. The Flask application is run in a separate process:

`class CollectRest(multiprocessing.Process):
    """
    Class to provide a rest api to the collector. Which implies a synchronous
    <-> asynchronous solution

    This is run in a separate http server (Flask). It communicates with the
    collector by Queue. First the request is sent to the backend in a queue and
    when the result comes back it is placed in the filesystem and the name is a
    random number that is assigned to the request.

    The Flask app is run in a separate process to avoid congestion on the cpu.

    The restapifolder is constructed in such a way that if the application is
    run in multiple machines, and a load balancer is used in front, it can
    check all servers so that no stickyconnection is required.
    """
    LOGGER = getLogger(__name__)

    def __init__(self, priority_queues, debug=False):
        # global rest_api_info
        super().__init__()
        self.collectorname = 'collect_rest'
        self.LOGGER.info('Rest api initializing')
        self.daemon = True
        self.flapp = None
        self.customer = CONFIG.customer
        self.debug = debug
        self.priority_queues = priority_queues
        self.documenten = None

    def run(self):
        CONFIG.setup(customer=self.customer)
        initialize_status_object()

        setup_loggers('rest')
        self.LOGGER = getLogger(__name__)
        self.documenten = DocumentC(self.priority_queues)
        self.LOGGER.info('Pid %s Rest interface for customer %s started',
                         getpid(), self.customer)
        specdir = join(CONFIG.base_path, CONFIG.resourcedir, 'openapi')
        self.LOGGER.debug('Swagger to be found at %s', specdir)

        app = connexion.FlaskApp('collect_rest', specification_dir=specdir)
        app.add_api('swagger.yml', strict_validation=True,
                    validate_responses=False, debug=self.debug)

        ssl_keyfile = CONFIG.conf['general']['ssl_keyfile']
        if ssl_keyfile:
            from ssl import SSLContext
            proto = None
            if CONFIG.conf['general']['ssl_protocol'] is not None:
                proto = CONFIG.conf['general']['ssl_protocol'].lower()
            try:
                from ssl import PROTOCOL_TLS
            except ImportError:
                from ssl import PROTOCOL_TLSv1 as PROTOCOL_TLS
            protocol = PROTOCOL_TLS
            if proto == 'tls1':
                from ssl import PROTOCOL_TLSv1
                protocol = PROTOCOL_TLSv1
            elif proto == 'tls11':
                from ssl import PROTOCOL_TLSv1_1
                protocol = PROTOCOL_TLSv1_1
            elif proto == 'tls12':
                from ssl import PROTOCOL_TLSv1_2
                protocol = PROTOCOL_TLSv1_2
            self.LOGGER.debug('using SSL protocol suite  %s (%s)',
                              str(protocol), proto)
            ssl_certfile = CONFIG.conf['general']['ssl_certfile']
            context = SSLContext(protocol)

            context.load_cert_chain(ssl_certfile, ssl_keyfile)
            ciphers = CONFIG.conf['general']['ssl_ciphers']
            if ciphers is not None:
                context.set_ciphers(ciphers)
                self.LOGGER.debug('using custom SSL cipher set: %s', ciphers)

        try:
            if ssl_keyfile:
                http_server = WSGIServer(('', CONFIG.rest_port), app,
                                         ssl_context=context)
            else:
                http_server = WSGIServer(('', CONFIG.rest_port), app)

            http_server.serve_forever()
        except RuntimeError as msg:
            if str(msg) == 'Server is going down':
                pass
            else:
                raise
        except KeyboardInterrupt:
            pass

    def stop_collector(self):
        self.terminate()

`

*No manual changes to spec file. Freeze command with pyinstaller:*

`pyinstaller C:\collector\src\main.py --onefile --distpath C:\collector\dist\bin --workpath C:\AppData\Local\Temp\src --add-data C:\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\swagger_spec_validator/schemas/v2.0/schema.json;./swagger_spec_validator/schemas/v2.0 --hidden-import collector.collect_dir --hidden-import collector.collect_mail --hidden-import collector.collect_xml --hidden-import collector.collect_sharepoint --hidden-import collector.collect_rest --hidden-import restapi.health --hidden-import restapi.document --hidden-import restapi.diff --hidden-import gevent.builtins --hidden-import gevent.os --hidden-import gevent.select --hidden-import gevent.signal --hidden-import gevent.socket --hidden-import gevent.subprocess --hidden-import gevent.ssl --hidden-import gevent.thread --hidden-import gevent.threading --hidden-import greenlet --hidden-import gevent.__hub_local --hidden-import gevent._greenlet --hidden-import gevent.__ident --hidden-import gevent._event --hidden-import gevent.__greenlet_primitives --hidden-import gevent.__waiter --hidden-import gevent.__hub_primitives --hidden-import gevent.libev --hidden-import gevent.libev.corecffi --hidden-import gevent.libev._corecffi --hidden-import win32timezone --hidden-import carp_workflow.abbyy --hidden-import carp_workflow.AfterProcessing --hidden-import carp_workflow.annotator --hidden-import carp_workflow.api --hidden-import carp_workflow.CarpBpmnScriptEngine --hidden-import carp_workflow.check_if_lastfile --hidden-import carp_workflow.classifier --hidden-import carp_workflow.ComposeOutput --hidden-import carp_workflow.Handwritten --hidden-import carp_workflow.JsonOutput --hidden-import carp_workflow.multidocument --hidden-import carp_workflow.powershell --hidden-import carp_workflow.processzip --hidden-import carp_workflow.ReformatOutput --hidden-import carp_workflow.RunSubProcesses --hidden-import carp_workflow.ScriptSteps --hidden-import carp_workflow.textmatcher --hidden-import carp_workflow.UpdateStatus --hidden-import carp_workflow.WFData --hidden-import carp_workflow.XmlOutput --hidden-import carp_workflow.organisation.utrecht.multidoc_condition
C:\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\pywin32_system32;C:/Program Files (x86)/Windows Kits/10/Redist/ucrt/DLLs/x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\AppData\Local\Programs\Python\Python36-32\;C:\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\GnuWin32\bin;C:\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywin32_system32
`

Many gevent modules are included in the hidden-imports. If not included, the application will crash. Now after adding these, I still get a crash as follows:

`Process CollectRest-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "src\collector\collect_rest.py", line 105, in run
  File "site-packages\gevent\pywsgi.py", line 1441, in __init__
  File "site-packages\gevent\server.py", line 109, in __init__
  File "site-packages\gevent\baseserver.py", line 95, in __init__
  File "src\gevent\event.py", line 163, in gevent._event.Event.__init__
  File "src\gevent\event.py", line 45, in gevent._event._AbstractLinkable.__init__
  File "src\gevent\_hub_local.py", line 80, in gevent.__hub_local.get_hub_noargs
  File "site-packages\gevent\hub.py", line 407, in __init__
  File "site-packages\gevent\hub.py", line 419, in loop_class
  File "site-packages\gevent\_config.py", line 51, in getter
  File "site-packages\gevent\_config.py", line 147, in get
  File "site-packages\gevent\_config.py", line 267, in validate
  File "site-packages\gevent\_config.py", line 225, in _import
  File "site-packages\gevent\_config.py", line 250, in _import
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\dickk\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gevent\libev\corecffi.py", line 20, in <module>
ImportError: cannot import name '_corecffi'`

I have checked the gevent hook, but it only adds some hidden imports. I hope someone can help me out here.
Thanks a lot in advance

**Comment by vcruzato** [comment]
I had the same problem, to work around this problem I am using the version of gevent 1.2.2.
https://pypi.org/project/gevent/1.2.2/
pip install gevent == 1.2.2

**Comment by yeraypalma** [comment]
Did you finally managed to solve this problem?
