### ISSUE TITLE
Pyside2 QtQuick build fails

### ISSUE THREAD

**Issue by Jevgenijus** [pyinstaller/pyinstaller#3655]
Hi im using Python 3.5.3 and trying to build a Pyside2 application which uses Qml
And i get the following. Btw tried Python 2.7.15 with the same level of success. 

25677 INFO: Loading module hook "hook-PySide2.QtQuick.py"...
Traceback (most recent call last):
  File "c:\tools\python\3.5\3.5.3-win64\Lib\runpy.py", line 193, in _run_module_
as_main
    "__main__", mod_spec)
  File "c:\tools\python\3.5\3.5.3-win64\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\source\app\.sdcsim_venv_AMD64_3.5.3\Scripts\pyinstaller.exe\__m
ain__.py", line 9, in <module>
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\building\build_main.py", line 472, in assemble
    module_hook.post_graph()
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\compat.py", line 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 817, in load_module
  File "<frozen importlib._bootstrap_external>", line 676, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\hooks\hook-PySide2.QtQuick.py", line 35, in <module>
    qmldir = qt5_qml_dir('PySide2')
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\utils\hooks\qt.py", line 194, in qt5_qml_dir
    qmldir = exec_command(qmake, "-query", "QT_INSTALL_QML").strip()
  File "c:\source\app\.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\compat.py", line 371, in exec_command
    out = subprocess.Popen(cmdargs, stdout=subprocess.PIPE, **kwargs).communicat
e()[0]
  File "c:\tools\python\3.5\3.5.3-win64\Lib\subprocess.py", line 676, in __init_
_
    restore_signals, start_new_session)
  File "c:\tools\python\3.5\3.5.3-win64\Lib\subprocess.py", line 955, in _execut
e_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

After digging a bit deeper it seems that Pyinstaller is looking for Qmake and does not have one

**Comment by banzr** [comment]
@htgoebel There is a bug in file "c:\source\app.sdcsim_venv_amd64_3.5.3\lib\site-packages\PyInstall
er\utils\hooks\qt.py", line 194, in qt5_qml_dir
qmldir = exec_command(qmake, "-query", "QT_INSTALL_QML").strip()

This command creates a suprocess and fails. I encountered a similar traceback and after manually setting the string that 'qmake -query QT_INSTALL_QML' the problem was solved.

I uploaded a fix to PR  #3676.

**Comment by htgoebel** [comment]
The correct fix would be to learn why `get_qmake_path()` returns a qmake which is later not found by windows.

**Comment by bjones1** [comment]
This was fixed in 5b5791285332003940f4bc70c32bb0cf10a32917. Please reopen if there are still problems.
