### ISSUE TITLE
pyinstaller won't run w/ latest source as of 8/16/18

### ISSUE THREAD

**Issue by jmh-aira** [pyinstaller/pyinstaller#3686]
I got pyinstaller from source today, and I installed it into my python 3.7...  I get the below.  how can I get th is fixed so I can use it? I wanted to see if the latest version of pyinstaller would work better for my project.

below is my output: when I run pyinstaller --onefile myfile.py

Microsoft Windows [Version 10.0.17735.1000]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\juan>pip uninstall pywin32_ctypes
Uninstalling pywin32-ctypes-0.1.2:
  Would remove:
    c:\users\juan\python3\lib\site-packages\pywin32_ctypes-0.1.2-py3.7.egg
Proceed (y/n)? y
  Successfully uninstalled pywin32-ctypes-0.1.2

C:\Users\juan>pip install pywin32_ctypes
Collecting pywin32_ctypes
  Downloading https://files.pythonhosted.org/packages/3f/ff/da0e68961128f36b5df94d2442fede4e7c0401488e41db0016278822b01c/pywin32-ctypes-0.1.2.tar.gz
Installing collected packages: pywin32-ctypes
  Running setup.py install for pywin32-ctypes ... done
Successfully installed pywin32-ctypes-0.1.2

C:\Users\juan>
C:\Users\juan>cd sa\sa

C:\Users\juan\sa\sa>pyinstaller --onefile sa.py
Traceback (most recent call last):
  File "C:\users\juan\python3\lib\site-packages\win32ctypes\core\__init__.py", line 29, in <module>
    import cffi
ModuleNotFoundError: No module named 'cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\juan\python3\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+g380ab20f', 'console_scripts', 'pyinstaller')()
  File "C:\users\juan\python3\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\users\juan\python3\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "C:\users\juan\python3\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "C:\users\juan\python3\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\users\juan\python3\lib\site-packages\pyinstaller-3.4.dev0+g380ab20f-py3.7.egg\PyInstaller\__init__.py", line 16, in <module>
    from . import compat
  File "C:\users\juan\python3\lib\site-packages\pyinstaller-3.4.dev0+g380ab20f-py3.7.egg\PyInstaller\compat.py", line 211, in <module>
    from win32ctypes.pywin32 import pywintypes  # noqa: F401
  File "C:\users\juan\python3\lib\site-packages\win32ctypes\pywin32\__init__.py", line 21, in <module>
    from win32ctypes.pywin32 import win32api
  File "C:\users\juan\python3\lib\site-packages\win32ctypes\pywin32\win32api.py", line 23, in <module>
    from win32ctypes.core import _common, _kernel32, _backend
  File "C:\users\juan\python3\lib\site-packages\win32ctypes\core\__init__.py", line 33, in <module>
    from .ctypes import _advapi32, _common, _kernel32
  File "C:\users\juan\python3\lib\site-packages\win32ctypes\core\ctypes\_advapi32.py", line 134

    ^
SyntaxError: invalid syntax

C:\Users\juan\sa\sa>

If you have problems to get your application running, please first

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If your problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for GitHub's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.

**Otherwise we will not be willing to help you.**

Please be aware that PyInstaller is a voluntary project. We spent quite some time
writing these guides to make both of our lives easier. Please
understand that we are not willing to spend our spare time to help you if you
are not willing to help on your side. (Sorry for having to said this, but we
are tired of being asked the same questions over and over again.)

**Comment by bjones1** [comment]
pywin32-ctypes doesn't (yet) support Python 3.7, but it should be released soon. PyInstaller for Windows depends on this, which produces your errors.
