### ISSUE TITLE
PyInstaller generated exe for Python code that uses scipy fails to load due to missing DLL dependency

### ISSUE THREAD

**Issue by leonbrag** [pyinstaller/pyinstaller#3688]
Python version: 3.6

Python code uses sklearn (which uses scipy) like so:

```
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
```

Exe is created from code like so:
`D:\blah>pyinstaller --onefile multinomian.py`

When exe runs, following dependency errors are reported:

```
 Traceback (most recent call last):
  File "multinomian.py", line 5, in <module>
    from sklearn.naive_bayes import MultinomialNB
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\__init__.py", line 134, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\base.py", line 13, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\utils\__init__.py", line 10, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\utils\validation.py", line 18, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\utils\fixes.py", line 144, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\sparse\linalg\isolve\iterative.py", line 10, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by victor-ZLee** [comment]
Similar issue after upgrade to the latest scipy.

**Comment by dails08** [comment]
Same here.

**Comment by lstolcman** [comment]
check whether this hook helps: https://github.com/pyinstaller/pyinstaller/pull/4613

I encountered similar problem today, and hook from PR solved the problem

**Comment by kehuantiantang** [comment]
I found this problem caused by `scipy\sparse`. I successfully compile the exe file according to two steps:
1.  downgrade the scipy package to 1.4.1 by `pip install scipy==1.4.1`
2. add hidden import in `*.spec` file
```python
import os
import scipy
from PyInstaller.utils.hooks import collect_submodules
hidden_imports = collect_submodules('scipy.special.cython_special')
block_cipher = None

# hidden imports same as add extra-dll folder
scipy_libs = os.path.join(os.path.dirname(scipy.__file__), '.libs')

a = Analysis(['main.py'],
             pathex=[scipy_libs],
             binaries=[],
             datas=[],
             hiddenimports=[hidden_imports, scipy_libs],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
```
