### ISSUE TITLE
Numpy cause ImportError in virtualenv 

### ISSUE THREAD

**Issue by kingmo888** [pyinstaller/pyinstaller#3695]
PyInstaller :3.3.1
Anaconda: Python 3.5.5 |Anaconda 4.2.0 (64-bit)

In order to minimize the packaging procedure, I created virtualenv by :
"conda create -n pybuild pip python=3.5"
And the necessary packages were installed.

I succeeded to build the "show.py" When I used the command what is "pyinstaller -F show.py -noconsole".

afterwards,

I needed the pandas package to add some new features, so I installed the numpy and pandas packages, and the encapsulation exe failed.

After I uninstalled numpy, I wrapped exe again and succeeded. After repeated attempts, I confirm that this problem is triggered by numpy. But I don't know how to solve it.

PS：I try to print it, it's: 
"            import PyQt5 as p
            print(p.__file__)"

I‘m not install pyqt5 in virtualenv .

`230 INFO: checking Analysis
230 INFO: Building Analysis because out00-Analysis.toc is non existent
230 INFO: Initializing module dependency graph...
233 INFO: Initializing module graph hooks...
234 INFO: Analyzing base_library.zip ...
6225 INFO: running Analysis out00-Analysis.toc
6228 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by d:\anaconda3\envs\buildexe\python.exe
6909 INFO: Caching module hooks...
6914 INFO: Analyzing F:\python_workspace\案例研究\爬虫\保证金监控中心\界面设计\s
how.py
7041 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
10138 INFO: Loading module hooks...
10139 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
11802 INFO: Loading module hook "hook-pydoc.py"...
11804 INFO: Loading module hook "hook-PySide2.py"...
12316 INFO: Processing pre-find module path hook   distutils
13299 INFO: Processing pre-find module path hook   site
13300 INFO: site: retargeting to fake-dir 'd:\\anaconda3\\envs\\buildexe\\lib\\s
ite-packages\\PyInstaller\\fake-modules'
16360 INFO: Loading module hook "hook-requests.py"...
16362 INFO: Loading module hook "hook-PyQt5.py"...

Traceback (most recent call last):
  File "<string>", line 3, in <module>
AttributeError: module 'PyQt5' has no attribute '__file__'
Traceback (most recent call last):
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\utils\hooks\__i
nit__.py", line 326, in get_module_file_attribute
    attr = loader.get_filename(package)
AttributeError: 'NoneType' object has no attribute 'get_filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda3\envs\buildexe\lib\runpy.py", line 193, in _run_module_as_ma
in
    "__main__", mod_spec)
  File "d:\anaconda3\envs\buildexe\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\envs\buildexe\Scripts\pyinstaller.exe\__main__.py", line 9,
 in <module>
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\__main__.py", l
ine 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\__main__.py", l
ine 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\building\build_
main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\building\build_
main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\building\build_
main.py", line 213, in __init__
    self.__postinit__()
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\building\datast
ruct.py", line 161, in __postinit__
    self.assemble()
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\building\build_
main.py", line 472, in assemble
    module_hook.post_graph()
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\building\imphoo
k.py", line 410, in post_graph
    self._load_hook_module()
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\building\imphoo
k.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\compat.py", lin
e 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 418, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 841, in load_module
  File "<frozen importlib._bootstrap_external>", line 700, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\hooks\hook-PyQt
5.py", line 23, in <module>
    extend_system_path([os.path.join(os.path.dirname(get_module_file_attribute('
PyQt5')),
  File "d:\anaconda3\envs\buildexe\lib\site-packages\PyInstaller\utils\hooks\__i
nit__.py", line 337, in get_module_file_attribute
    raise ImportError
ImportError`

**Comment by kingmo888** [comment]
Anybody can help me? THS.
