### ISSUE TITLE
ImportError: No module named dis3 (pyinstaller 3.4, python 2.7.6)

### ISSUE THREAD

**Issue by phinicota** [pyinstaller/pyinstaller#3731]
Hi,
I think there might be an issue with pyinstaller 3.4 dependencies (**pyinstaller 3.3 works fine**):

```
❯ pip install pyinstaller                                                                                                                                                Collecting pyinstaller
myhome/venv/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:369: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
myhome/venv/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Using cached https://files.pythonhosted.org/packages/40/4c/6aba83d19a1e2a837aeb7822e1bb12b97ad971112eba5bbaed67db8d8d3d/PyInstaller-3.4-py2.py3-none-any.whl
Requirement already satisfied: pefile>=2017.8.1 in myhome/venv/lib/python2.7/site-packages (from pyinstaller) (2018.8.8)
Requirement already satisfied: macholib>=1.8 in myhome/venv/lib/python2.7/site-packages (from pyinstaller) (1.11)
Requirement already satisfied: setuptools in myhome/venv/lib/python2.7/site-packages (from pyinstaller) (40.2.0)
Requirement already satisfied: altgraph in myhome/venv/lib/python2.7/site-packages (from pyinstaller) (0.16.1)
Requirement already satisfied: future in myhome/venv/lib/python2.7/site-packages (from pefile>=2017.8.1->pyinstaller) (0.16.0)
Installing collected packages: pyinstaller
Successfully installed pyinstaller-3.4


❯ pyinstaller --help                                                                                                                                                     
Traceback (most recent call last):
  File "myhome/venv/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "myhome/venv/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 79, in run
    import PyInstaller.building.build_main
  File "myhome/venv/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 33, in <module>
    from ..depend import bindepend
  File "myhome/venv/local/lib/python2.7/site-packages/PyInstaller/depend/bindepend.py", line 26, in <module>
    from . import dylib, utils
  File "myhome/venv/local/lib/python2.7/site-packages/PyInstaller/depend/utils.py", line 25, in <module>
    from ..lib.modulegraph import util, modulegraph
  File "myhome/venv/local/lib/python2.7/site-packages/PyInstaller/lib/modulegraph/util.py", line 16, in <module>
    from ._compat import StringIO, BytesIO, get_instructions, _READ_MODE
  File "myhome/venv/local/lib/python2.7/site-packages/PyInstaller/lib/modulegraph/_compat.py", line 29, in <module>
    from dis3 import get_instructions
ImportError: No module named dis3
```

Running:
- Ubuntu 14.04
- python 2.7.6
- pip 18.0

**Comment by htgoebel** [comment]
The wheel is broken, I removed it just a few minutes ago. Please install PyInstaller again using
```
pip install --force-reinstall --no-binary :all: pyinstaller
```
This should install from source.

**Comment by phinicota** [comment]
it's working now, thanks!

**Comment by mbates14** [comment]
Tried it. Not working on Raspberry Pi. Same error.

**Comment by RamjiW** [comment]
"pip install --force-reinstall --no-binary :all: pyinstaller" This is not working for the python2.7.6 .same error

**Comment by htgoebel** [comment]
"Not working" is nothing one can build an analysis on.

**Comment by thakursc1** [comment]
```
Saurabhs-MacBook-Pro:thakursc1$ pip install --force-reinstall --no-binary :all: pyinstaller
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /usr/bin/python /Library/Python/2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/nx/0b268l893v7_psqhkt9qdbh80000gn/T/tmpbLFBx0:
  Traceback (most recent call last):
    File "/Library/Python/2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/Library/Python/2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Library/Python/2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/nx/0b268l893v7_psqhkt9qdbh80000gn/T/pip-build-env-0pJLaD/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/nx/0b268l893v7_psqhkt9qdbh80000gn/T/pip-build-env-0pJLaD/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/private/var/folders/nx/0b268l893v7_psqhkt9qdbh80000gn/T/pip-build-env-0pJLaD/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ImportError: No module named PyInstaller
  
  ----------------------------------------
Command "/usr/bin/python /Library/Python/2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/nx/0b268l893v7_psqhkt9qdbh80000gn/T/tmpbLFBx0" failed with error code 1 in /private/var/folders/nx/0b268l893v7_psqhkt9qdbh80000gn/T/pip-install-QcTCyW/pyinstaller
```

Get the above error when installing Pyinstaller on Python 2.7? Any way I can solve this ?

**Comment by htgoebel** [comment]
@thakursc1 You issue is *complety* unrelated to this one. Did you even look at the issues before posting? There is an issue pinned, and this is for some good reason. Thanks for wasting my spare time
