### ISSUE TITLE
Unable to open .dat

### ISSUE THREAD

**Issue by hasanparasteh** [pyinstaller/pyinstaller#3760]
I have windows 10 64 bit operating system and when i build the project with pyinstaller I get this error message that it cant open shape_predictor_68_face_landmarks.dat is there any way to fix this by pyinstaller or it's because the library that I am using?

python version: 3.6.6
```
Traceback (most recent call last):
  File "face-cropper.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Program Files\Python36\lib\site-packages\pyinstaller-3.5.dev0+99c68eaee-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\face_recognition\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Program Files\Python36\lib\site-packages\pyinstaller-3.5.dev0+99c68eaee-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\face_recognition\api.py", line 17, in <module>
RuntimeError: Unable to open C:\Users\Hasan\Desktop\FaceCropper\dist\face-cropper\face_recognition_models\models\shape_predictor_68_face_landmarks.dat
```

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by magicshuang** [comment]
解决了么？
