### ISSUE TITLE
Not compile

### ISSUE THREAD

**Issue by hexando** [pyinstaller/pyinstaller#3792]
Hello everyone, yesterday compiled the program using pyinstaller, and I decided today to write a program and compile it but got errors that yesterday was not, and these are not the errors that are associated with api-ms-win-crt

`53 INFO: PyInstaller: 3.4
53 INFO: Python: 3.7.0
54 INFO: Platform: Windows-10-10.0.17134-SP0
54 INFO: wrote C:\Users\hex\Desktop\easyvkbot\bot.spec
56 INFO: UPX is not available.
58 INFO: Extending PYTHONPATH with paths
['C:\\Users\\hex\\Desktop\\easyvkbot', 'C:\\Users\\hex\\Desktop\\easyvkbot']
58 INFO: checking Analysis
58 INFO: Building Analysis because Analysis-00.toc is non existent
58 INFO: Initializing module dependency graph...
60 INFO: Initializing module graph hooks...
62 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\pkgutil.py", line 130, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\pkgutil.py", line 149, in _iter_file_finder_modules
    import inspect
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\inspect.py", line 40, in <module>
    import linecache
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\tokenize.py", line 33, in <module>
    import re
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\pkgutil.py", line 130, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\pkgutil.py", line 149, in _iter_file_finder_modules
    import inspect
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\inspect.py", line 40, in <module>
    import linecache
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\tokenize.py", line 33, in <module>
    import re
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
2902 INFO: running Analysis Analysis-00.toc
2905 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\hex\appdata\local\programs\python\python37-32\python.exe
2968 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python.exe
3024 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python.exe
3082 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python.exe
3139 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python.exe
3201 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python.exe
3417 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3474 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3531 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3589 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3646 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3708 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3765 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3825 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3890 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
3951 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
4012 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
4072 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\python37.dll
4134 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
4190 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
4247 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
4302 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
4358 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\hex\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
4362 INFO: Caching module hooks...
4369 INFO: Analyzing C:\Users\hex\Desktop\easyvkbot\bot.py
4502 INFO: Processing pre-safe import module hook   six.moves
4933 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 3, in <module>
    import logging
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\tokenize.py", line 33, in <module>
    import re
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "C:\Users\hex\AppData\Local\Programs\Python\Python37-32\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 443, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 201, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1348, in run_script
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2028, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2813, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2028, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2813, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2028, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2813, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
    self._process_imports(module)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1422, in import_hook
    target_module = self._load_tail(target_package, target_module_partname)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1635, in _load_tail
    submodule = self._safe_import_module(head, mname, submodule)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 260, in _safe_import_module
    hook_module.pre_safe_import_module(hook_api)
  File "c:\users\hex\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\hooks\pre_safe_import_module\hook-urllib3.packages.six.moves.py", line 31, in pre_safe_import_module
    for real_module_name, six_module_name in real_to_six_module_name.items():
AttributeError: 'str' object has no attribute 'items'`

pls help :(

**Comment by htgoebel** [comment]
You did not take your time to add proper markdown formatting to make your issue readable. Nor did you take your time to search other issues. Thus I'm not taking my time to look at this.

**Comment by htgoebel** [comment]
Duplicate of #3806. Should be fixed now in 0ffa574bf87e2e37b0df2a4e2d60cb616f9ff2f2
