### ISSUE TITLE
[macOS 14.0] gi._gi_cairo not found in PYZ

### ISSUE THREAD

**Issue by geigi** [pyinstaller/pyinstaller#3804]
Hey,

I'm trying to bundle a Gtk application using cairo provided by Gdk on macOS 14.0. Here is a minimal example:
```python
import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
from gi.repository import Gdk, Gtk, GObject, GdkPixbuf



class DemoWindow(Gtk.Window):
  def __init__(self):
    GObject.GObject.__init__(self)

    self.set_title('A Window')
    self.set_default_size(500, 500)
    scale = 1.0
    pixbuf = GdkPixbuf.Pixbuf.new_from_file("demo.png")
    surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, scale, None)
    
    img = Gtk.Image()
    img.set_from_surface(surface)
    self.add(img)
    self.show_all()


def main():
    window = DemoWindow()
    window.connect('destroy', Gtk.main_quit)
    Gtk.main()


if __name__ == "__main__":
    main()
```

The bundled application crashes with the following output:
```
(demo:46639): Gtk-WARNING **: 13:25:18.325: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    main()
  File "demo.py", line 25, in main
    window = DemoWindow()
  File "demo.py", line 16, in __init__
    surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, scale, None)
TypeError: Couldn't find foreign struct converter for 'cairo.Surface'
[46639] Failed to execute script demo
```

I've done the best I can to pinpoint this issue. It seems like `_gi._cairo` can somehow not be found. Things I did:
- I couldn't find an according error in the pyinstaller log
- Ran strace where I found this message right before the crash:
```
FAILED: dyld LOAD of <CSSymbolOwner: 0x7fe371fa7740> AFD91E31-5BFD-3ED6-AB3C-9E517B4DBB05 [0x0000a3db2640a95e 0x7fffffffffffffff]/Users/ju/Downloads/demo/dist/demo.app/Contents/MacOS/gio_modules/libgiognutls.so
```
- Searched for dylib and so dependencies using `objdump`. I couldn't find one that was missing in the bundled app
- Inspected the pyz with `pyi-archive_viewer` where I didn't find any cairo library (list in gist)
- Included verbose for python (log also in gist) where I found the message:
```
...
import 'gi.overrides.Pango' # <pyimod03_importers.FrozenImporter object at 0x1100bd4a8>
# gi.repository.Gio not found in PYZ
import gi.overrides.Gio # PyInstaller PYZ
import gi.overrides.Gio # PyInstaller PYZ
import 'gi.overrides.Gio' # <pyimod03_importers.FrozenImporter object at 0x1100bd4a8>
# gi.repository.GdkPixbuf not found in PYZ
# gi.repository.GModule not found in PYZ
# gi.overrides.GModule not found in PYZ
# destroy gi.repository.GModule
import gi.overrides.GdkPixbuf # PyInstaller PYZ
import gi.overrides.GdkPixbuf # PyInstaller PYZ
import 'gi.overrides.GdkPixbuf' # <pyimod03_importers.FrozenImporter object at 0x1100bd4a8>
import gi.overrides.Gdk # PyInstaller PYZ
import gi.overrides.Gdk # PyInstaller PYZ
import 'gi.overrides.Gdk' # <pyimod03_importers.FrozenImporter object at 0x1100bd4a8>
# gi.repository.Gtk not found in PYZ
# gi.repository.Atk not found in PYZ
# gi.overrides.Atk not found in PYZ
# destroy gi.repository.Atk
import gi.overrides.Gtk # PyInstaller PYZ
import gi.overrides.Gtk # PyInstaller PYZ
import gi._gtktemplate # PyInstaller PYZ
import 'gi._gtktemplate' # <pyimod03_importers.FrozenImporter object at 0x1100bd4a8>

(demo:44443): Gtk-WARNING **: 13:00:12.794: Locale not supported by C library.
	Using the fallback 'C' locale.
import 'gi.overrides.Gtk' # <pyimod03_importers.FrozenImporter object at 0x1100bd4a8>
# gi._gi_cairo not found in PYZ
# cairo not found in PYZ
Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    main()
  File "demo.py", line 25, in main
    window = DemoWindow()
  File "demo.py", line 16, in __init__
    surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, scale, None)
TypeError: Couldn't find foreign struct converter for 'cairo.Surface'
[44443] Failed to execute script demo
...
```

Here is my sysinfo:
```
pyinstaller: commit 0b6f1ec6f22eef9b7275207d4893693f6d8dcbe8
Python 3.7.0

ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
```

And here the gist:
https://gist.github.com/geigi/f8ffbd2cdfa37e89449f12043a44846a

Let me know if there is anything more I can do to help you :)

**Comment by geigi** [comment]
Solved by including `cairo` as hidden import. `Gdk.cairo_surface_create_from_pixbuf` needs the module but it is not explicitly imported.

**Comment by htgoebel** [comment]
What about providing a pull-reqest for a hook for Gdk.cairo_surface_create_from_pixbuf (if this is a module, of course)?

**Comment by geigi** [comment]
> What about providing a pull-reqest for a hook for Gdk.cairo_surface_create_from_pixbuf (if this is a module, of course)?

`cairo_surface_create_from_pixbuf` is a method in the `Gdk` module. What's the best way to fix this? The gdk hook already has some hidden cairo imports in it (`'gi._gi_cairo', 'gi.repository.cairo'`), should we just add `cairo` as well?
