### ISSUE TITLE
Spurious error updating resources on pyd files

### ISSUE THREAD

**Issue by efahl** [pyinstaller/pyinstaller#3809]
This bug is not consistently reproducible, so I can't really give a test script, just report the symptoms.  I've been seeing it every now and then for 5-6 months (at least that's when I started making note of it, and I think it started when we moved from Python 2.7 to 3.6, but I won't commit to that).  I just re-run the build and everything is fine.

Win 10.0.17134.345 x64
cPython 3.6.6 x64

For what it's worth, here's the traceback.  It always happens in the same bit of code, but on various pyd files (say, something in SciPy one time, vtk the next, SQLAlchemy this time).  No other Python processes are running on the build machine when this error occurs.

    193208 ERROR: ...\build\pyinstaller\bincache00_py36_64bit\sqlalchemy.cutils.pyd
    Traceback (most recent call last):
      File "T:\Python36\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "T:\Python36\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "T:\Python36\lib\site-packages\PyInstaller\__main__.py", line 101, in <module>
        run()
      File "T:\Python36\lib\site-packages\PyInstaller\__main__.py", line 94, in run
        run_build(pyi_config, spec_file, **vars(args))
      File "T:\Python36\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
        PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
      File "T:\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
      File "T:\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
        exec(text, spec_namespace)
      File "<string>", line 114, in <module>
      File "T:\Python36\lib\site-packages\PyInstaller\building\api.py", line 661, in __init__
        self.__postinit__()
      File "T:\Python36\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
        self.assemble()
      File "T:\Python36\lib\site-packages\PyInstaller\building\api.py", line 691, in assemble
        dist_nm=inm)
      File "T:\Python36\lib\site-packages\PyInstaller\building\utils.py", line 317, in checkCache
        [language])
      File "T:\Python36\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 939, in update_resources
        languages)
      File "T:\Python36\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1017, in UpdateManifestResourcesFromXML
        languages or [0, "*"])
      File "T:\Python36\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 204, in UpdateResources
        win32api.EndUpdateResource(hdst, 0)
    pywintypes.error: (110, 'EndUpdateResource', 'The system cannot open the device or file specified.')

**Comment by htgoebel** [comment]
Given you today message on the mailinglist, I assume you are building concurrently - which is an important information missing above.

As you can this, this happens in `update_resources`, which means: most probably this is a write access. And of course two concurrent processes must not write to the same file at the same time.

**Comment by efahl** [comment]
Actually, no, PyInstaller is the only process being run at the time the
error occurs.  If Windows is doing something in the background, I have no
way of knowing what or how to detect that, so as I said, it remains
virtually impossible to determine the root cause.
