### ISSUE TITLE
Using Babel with Pyinstaller

### ISSUE THREAD

**Issue by a-slight-breeze** [pyinstaller/pyinstaller#3810]
**Background:**
I'm developing a GUI that utilizes tkinter and the tkcalendar widget. Within the tkcalendar widget, the babel library is imported, however at no point in the remainder of my script do I import any babel libraries. When freezing my application with pyinstaller and running, the script fails to execute citing an import error with the babel.numbers library.

**Versions and System:**

- Babel 2.3.3
- tkcalendar 1.3.1
- Pyinstaller 3.3.1
- Python 3.5.2
-Windows 10

**Solution:**
I ended up getting my frozen script to run via the following steps:

1. Copy the babel library from _/site-packages_ to the directory of the script I was attempting to freeze (this might not be necessary, but I have strange permissions on my work computer and can't change those files without admin approval)
2. Copy the _hook-babel.py_ file from the Pyinstaller folder within /site-packages to the directory of the script I was attempting to freeze.
3. Make the following changes to the hook-babel.py file:
`hiddenimports = ["babel.dates", "babel.numbers"]`
Use the following tag when freezing my script:
`--additional-hooks-dir=.`

**Theory:**
I am honestly not sure what could be going on, but my assumption is that there's likely something up with the standard hook that was being used.

**Request:**
Make the changes so that I don't have to use this roundabout method for usage of the babel library.

**Comment by htgoebel** [comment]
Thanks for the detailed description. Please check the traceback of your app, where this import error occurs to find the reason why this module is not found. Maybe it is imported usng `__import__`?!

BTW:  Instead of changing the hook, you could simply run pyinstaller with `--hidden-import=babel.numbers` to check if this is missing in the hook. In the log run I'd appreciate a pull-request to the improve the hook :-). Thanks.

**Comment by Legorooj** [comment]
Closing due to inactivity - and there's a fix described in the issue

**Comment by apocalypse2012** [comment]
This should never have been closed. This is still a problem. I cannot get my tool that implements tkcalendar to build with pyinstaller.

**Comment by a-slight-breeze** [comment]
You can use the workaround that's in the problem description. But I agree - there really should be a better fix for this!

**Comment by apocalypse2012** [comment]
I've used all the documented fixed in the tkCalendar and Pyinstaller docs. Ive added hidden imports in the spec file and at the commandline. Ive added explicit imports for tkcalendar and babel.numbers to my own code. None of that works.
This bug report mentions a couple of rando things like copying the module out of the site-packages folder, which I am about to attempt, but of everything that is left, it points to something being seriously wrong and worth attention.
TKcalendar is a very simple module. Babel appears to be a widely used low-level set of utility features. TKinter comes with Python and their appears to be only one calendar extension widget for it. 
There is no clear explanation for why this is happening. I have looked at the babel code and cant see any particularly weird import behavior. The OP above does not even know what part of what he did made it work. This has put my project late for 2 weeks. If this does not work, I'm blocked.

**Comment by apocalypse2012** [comment]
I am having this same problem and the posted fix is not working.

pyinstaller --hidden-import babel.numbers main.py

This does not fix the problem. I don't know what has changed, but it is no-longer possible to workaround this.

Python 3.8.5
pip 21.2.4 from p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip (python 3.8)
tkcalendar 1.6.1
pyinstaller 4.5.1

Error message:
(venv) P:\Documents\Depot\autosuspendprocess>dist\main\main
Traceback (most recent call last):
File "main.py", line 1, in
import View
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "View.py", line 3, in
from tkcalendar import DateEntry
ModuleNotFoundError: No module named 'tkcalendar'
[11492] Failed to execute script 'main' due to unhandled exception!

Or if it succeeds in building:
Traceback (most recent call last):
  File "main.py", line 1, in <module>
ModuleNotFoundError: No module named 'tkcalendar'

**Comment by a-slight-breeze** [comment]
This seems like a slightly different issue since it's failing to import the 'tkcalendar' module not the babel module. Did you use pip for tkcalendar?

**Comment by apocalypse2012** [comment]
Yes... However, I am developing in pycharm. I have a virtual environment defined with all of my external modules. All in working order until I freeze. 
However, Pycharm does not seem to want to add pyinstaller to the project. It fails the UI pip install. So, I installed pyinstaller into the system python, which is the parent execution environment. 
My project terminal sees and executes pyinstaller fine. However, in trying the above steps, I tried pip installing tkcalendar to the system python. The error went away for that module went to another external module... dotenv

Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "View.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "Literals.py", line 3, in <module>
ModuleNotFoundError: No module named 'dotenv'

**Comment by bwoodsend** [comment]
@apocalypse2012 You're problem has nothing to do with this. You need to activate your virtual environment that PyCharm is using, install PyInstaller in it then run the build. Mixing system Pythons and virtual environments will just lead to obvious dependencies not being included no matter what.

**Comment by apocalypse2012** [comment]
```
(venv) P:\Documents\Depot\autosuspendprocess>pip install pyinstaller
Collecting pyinstaller
  Using cached pyinstaller-4.5.1-py3-none-win32.whl (1.9 MB)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (0.2.0)
Requirement already satisfied: setuptools in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (57.1.0)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstalle
r) (2021.3)
Requirement already satisfied: pefile>=2017.8.1 in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (2021.5.24)
Requirement already satisfied: altgraph in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (0.17)
Requirement already satisfied: future in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pefile>=2017.8.1->pyinstaller) (0.18.
2)
Installing collected packages: pyinstaller
ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument
```

**Comment by bwoodsend** [comment]
Weird, unreproducible, Windows only OS errors on install usually mean your antivirus is getting in the way by quarantining something pip will still writing. See if you can find any relevant reports from Microsoft Defender or macafee saying they blocked something.

**Comment by apocalypse2012** [comment]
> @apocalypse2012 You're problem has nothing to do with this. You need to activate your virtual environment that PyCharm is using, install PyInstaller in it then run the build. Mixing system Pythons and virtual environments will just lead to obvious dependencies not being included no matter what.

Point taken. Trying to do that. The above post shows the error I get. I guess this is the originating problem that sent me down this rabbit whole. I thought I could work around it by installing into the system python, which did work up to a point.
Not sure if this is a file path name length thing or what. Not sure where pip logs the actual failure info. Thanks for the help.

**Comment by apocalypse2012** [comment]
> Weird, unreproducible, Windows only OS errors on install usually mean your antivirus is getting in the way by quarantining something pip will still writing. See if you can find any relevant reports from Microsoft Defender or macafee saying they blocked something.

I will, but I’m not sure why defender would single out this one install from all the other stuff I have had pip install in this venv.

**Comment by bwoodsend** [comment]
Can you also run `pip show pyinstaller ` from the system environment and post the output here? It wouldn't make sense if it had allowed the same version to be installed there but not in your virtual environment.

**Comment by apocalypse2012** [comment]
> Can you also run `pip show pyinstaller ` from the system environment and post the output here? It wouldn't make sense if it had allowed the same version to be installed there but not in your virtual environment.

Well I am confused...

(venv) P:\Documents\Depot\autosuspendprocess>pip show pyinstaller
WARNING: Package(s) not found: pyinstaller

**Comment by apocalypse2012** [comment]
Here is the output for pip show from the system python install... 

C:\Windows\system32>pip show pyinstaller
Name: pyinstaller
Version: 4.5.1
Summary: PyInstaller bundles a Python application and all its dependencies into a single package.
Home-page: http://www.pyinstaller.org/
Author: Hartmut Goebel, Giovanni Bajo, David Vierra, David Cortesi, Martin Zibricky
Author-email:
License: GPLv2-or-later with a special exception which allows to use PyInstaller to build and distribute non-free programs (including commercial ones)
Location: y:\users\rstewart\appdata\local\programs\python\python38-32\lib\site-packages
Requires: altgraph, pyinstaller-hooks-contrib, pywin32-ctypes, pefile, setuptools
Required-by:

**Comment by apocalypse2012** [comment]
Here is a verbose output from pip install in the venv...

[err_out.txt](https://github.com/pyinstaller/pyinstaller/files/7180276/err_out.txt)

ERROR: Could not install packages due to an OSError.
Traceback (most recent call last):
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\commands\install.py", line 390, in run
    installed = install_given_reqs(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\req\req_install.py", line 758, in install
    install_wheel(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 794, in install_wheel
    _install_wheel(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 637, in _install_wheel
    file.save()
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 406, in save
    shutil.copyfileobj(f, dest)
  File "Y:\Users\rstewart\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 205, in copyfileobj
    fdst_write(buf)
OSError: [Errno 22] Invalid argument

**Comment by apocalypse2012** [comment]
This site mentions there being a problem with %appdata% being readonly, which it is for me... [https://stackoverflow.com/questions/53574590/could-not-install-packages-due-to-an-environmenterror-errno-2-no-such-file-or](url)

The verbose output shows operations in these folder inside my %appdata%...
'Created temporary directory: Y:\Users\rstewart\AppData\Local\Temp\pip-unpack-t5kw0aj7'
and Removed build tracker: 'Y:\\Users\\rstewart\\AppData\\Local\\Temp\\pip-req-tracker-a3d1m6y_'

However, my pyinstaller in my system python is also in this %appdata% folder...
Location: y:\users\rstewart\appdata\local\programs\python\python38-32\lib\site-packages

Could there be a different permissions context stopping the install in one case but not the other?

**Comment by apocalypse2012** [comment]
Ok I am not sure what is going on here, but I am beginning to think that this is all wrong headed. Both the system and the virtual environment pip installs are trying to install pyinstaller into appdata/local. This completely controverts the working theory that my original failing build was occurring because it was installed from the system python. Pip would be putting it in Appdata either way. The only reason to do that would be to use the same pyinstaller from any virtual environment. WTH is going on with this?

**Comment by rokm** [comment]
> WTH is going on with this?

When `pip` builds the wheels, it uses the standard temporary directory, pointed to by `%TEMP%` (or possibly `%TMP%`), for the build process. Then it installs the wheels into the target environment.

Perhaps you should try setting `%TEMP%` to some other, less problematic location?

**Comment by apocalypse2012** [comment]
The %Temp% path is writable and not problematic. The outer folders are not. I am lost with this at this point. I cant install pyinstaller into a virtual environment. I can use the system install of pyinstaller from an activate virtual environment without it blowing up.

**Comment by Usman-Amjad** [comment]
Just do 
--hidden-import "babel.numbers"

**Comment by NatanElkutski** [comment]
> Just do --hidden-import "babel.numbers"

Thank you very much!! it worked like a charm.
