### ISSUE TITLE
 In the end build use .spec,  When the COLLECT-00.toc file is finally built, the dynamic library ucrtbase.dll is missing.

### ISSUE THREAD

**Issue by crowluya** [pyinstaller/pyinstaller#3828]
my project use Pyqt and matplotlib and my cpp dll 

#### but it still doesn't work

Here are the build logs:
```
(env_py36) G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI>pyinstaller main.spec
66 INFO: PyInstaller: 3.4
66 INFO: Python: 3.6.5
67 INFO: Platform: Windows-10-10.0.17134-SP0
81 INFO: UPX is not available.
87 INFO: Extending PYTHONPATH with paths
['G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI',
 'G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI']
88 INFO: checking Analysis
88 INFO: Building Analysis because Analysis-00.toc is non existent
89 INFO: Initializing module dependency graph...
91 INFO: Initializing module graph hooks...
94 INFO: Analyzing base_library.zip ...
4505 INFO: running Analysis Analysis-00.toc
4508 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\ancoda\envs\env_py36\python.exe
5390 INFO: Caching module hooks...
5397 INFO: Analyzing main.py
5523 INFO: Processing pre-find module path hook   distutils
5663 INFO: Processing pre-safe import module hook   six.moves
8674 INFO: Processing pre-find module path hook   site
8674 INFO: site: retargeting to fake-dir 'd:\\ancoda\\envs\\env_py36\\lib\\site-packages\\PyInstaller\\fake-modules'
10511 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
23275 INFO: Loading module hooks...
23275 INFO: Loading module hook "hook-distutils.py"...
23278 INFO: Loading module hook "hook-encodings.py"...
23625 INFO: Loading module hook "hook-lib2to3.py"...
23630 INFO: Loading module hook "hook-matplotlib.backends.py"...
24683 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
25367 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
25897 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
26572 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
27324 INFO:   Matplotlib backend "Qt4Agg": added
28032 INFO:   Matplotlib backend "Qt5Agg": added
28752 INFO:   Matplotlib backend "TkAgg": added
29579 INFO:   Matplotlib backend "WX": added
30351 INFO:   Matplotlib backend "WXAgg": added
30862 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
31515 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
32024 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "d:\ancoda\envs\env_py36\lib\site-packages\matplotlib\backends\backend_webagg.py", line 28, in <module>
    import tornado
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "d:\ancoda\envs\env_py36\lib\site-packages\matplotlib\backends\backend_webagg.py", line 30, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
32528 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'tornado'
33166 INFO:   Matplotlib backend "agg": added
33658 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
34149 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
34861 INFO:   Matplotlib backend "pdf": added
35830 INFO:   Matplotlib backend "pgf": added
36516 INFO:   Matplotlib backend "ps": added
37176 INFO:   Matplotlib backend "svg": added
37846 INFO:   Matplotlib backend "template": added
38271 INFO: Loading module hook "hook-matplotlib.py"...
38683 INFO: Loading module hook "hook-numpy.core.py"...
38759 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
38762 INFO: Loading module hook "hook-numpy.py"...
38764 INFO: Loading module hook "hook-PIL.Image.py"...
39307 INFO: Loading module hook "hook-PIL.py"...
39309 INFO: Excluding import 'PyQt5'
39312 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
39312 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
39313 INFO: Excluding import 'tkinter'
39317 INFO:   Removing import of tkinter from module PIL.ImageTk
39318 INFO: Import to be excluded not found: 'FixTk'
39318 INFO: Excluding import 'PyQt4'
39320 INFO:   Removing import of PyQt4 from module PIL.ImageQt
39321 INFO: Excluding import 'PySide'
39323 INFO:   Removing import of PySide from module PIL.ImageQt
39325 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
39327 INFO: Excluding import 'tkinter'
39329 INFO: Import to be excluded not found: 'FixTk'
39330 INFO: Loading module hook "hook-pkg_resources.py"...
39899 INFO: Processing pre-safe import module hook   win32com
40214 INFO: Loading module hook "hook-pydoc.py"...
40215 INFO: Loading module hook "hook-PyQt5.py"...
40473 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
40606 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
40930 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
41558 INFO: Loading module hook "hook-pythoncom.py"...
41935 INFO: Loading module hook "hook-pytz.py"...
42041 INFO: Loading module hook "hook-pywintypes.py"...
42413 INFO: Loading module hook "hook-scipy.py"...
42415 WARNING: Hidden import "scipy._lib.messagestream" not found!
42415 WARNING: Hidden import "scipy._lib._fpumode" not found!
42416 INFO: Loading module hook "hook-setuptools.py"...
43296 INFO: Loading module hook "hook-sysconfig.py"...
43298 INFO: Loading module hook "hook-win32com.py"...
44099 INFO: Loading module hook "hook-xml.dom.domreg.py"...
44100 INFO: Loading module hook "hook-xml.py"...
44101 INFO: Loading module hook "hook-_tkinter.py"...
44409 INFO: checking Tree
44409 INFO: Building Tree because Tree-00.toc is non existent
44410 INFO: Building Tree Tree-00.toc
44518 INFO: checking Tree
44519 INFO: Building Tree because Tree-01.toc is non existent
44520 INFO: Building Tree Tree-01.toc
44609 INFO: Looking for ctypes DLLs
44701 INFO: Analyzing run-time hooks ...
44712 INFO: Including run-time hook 'pyi_rth_qt5.py'
44714 INFO: Including run-time hook 'pyi_rth__tkinter.py'
44715 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
44719 INFO: Including run-time hook 'pyi_rth_pkgres.py'
44720 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
44722 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
44724 INFO: Including run-time hook 'pyi_rth_mpldata.py'
44745 INFO: Looking for dynamic libraries
60450 INFO: Looking for eggs
60450 INFO: Using Python library d:\ancoda\envs\env_py36\python36.dll
60452 INFO: Found binding redirects:
[]
60488 INFO: Warnings written to G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\warn-main.txt
60729 INFO: Graph cross-reference written to G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\xref-main.html
60840 INFO: Appending 'binaries' from .spec
60844 INFO: checking PYZ
60844 INFO: Building PYZ because PYZ-00.toc is non existent
60845 INFO: Building PYZ (ZlibArchive) G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\PYZ-00.pyz
63737 INFO: Building PYZ (ZlibArchive) G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\PYZ-00.pyz completed successfully.
63790 INFO: checking PKG
63790 INFO: Building PKG because PKG-00.toc is non existent
63791 INFO: Building PKG (CArchive) PKG-00.pkg
63824 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
63829 INFO: Bootloader d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
63829 INFO: checking EXE
63830 INFO: Building EXE because EXE-00.toc is non existent
63831 INFO: Building EXE from EXE-00.toc
63832 INFO: Appending archive to EXE G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\main.exe
63843 INFO: Building EXE from EXE-00.toc completed successfully.
63851 INFO: checking COLLECT
63851 INFO: Building COLLECT because COLLECT-00.toc is non existent
63854 INFO: Building COLLECT COLLECT-00.toc
Traceback (most recent call last):
  File "d:\ancoda\envs\env_py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\ancoda\envs\env_py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ancoda\envs\env_py36\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 40, in <module>
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\api.py", line 676, in __init__
    self.__postinit__()
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\api.py", line 707, in assemble
    dist_nm=inm)
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\utils.py", line 281, in checkCache
    shutil.copy(fnm, cachedfile)
  File "d:\ancoda\envs\env_py36\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "d:\ancoda\envs\env_py36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\AppData\\Roaming\\pyinstaller\\bincache00_py36_64bit\\ucrtbase.dll'

(env_py36) G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI>pyinstaller main.spec
65 INFO: PyInstaller: 3.4
66 INFO: Python: 3.6.5
66 INFO: Platform: Windows-10-10.0.17134-SP0
80 INFO: UPX is not available.
86 INFO: Extending PYTHONPATH with paths
['G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI',
 'G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI']
87 INFO: checking Analysis
87 INFO: Building Analysis because Analysis-00.toc is non existent
87 INFO: Initializing module dependency graph...
89 INFO: Initializing module graph hooks...
92 INFO: Analyzing base_library.zip ...
4421 INFO: running Analysis Analysis-00.toc
4425 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\ancoda\envs\env_py36\python.exe
5303 INFO: Caching module hooks...
5310 INFO: Analyzing main.py
5441 INFO: Processing pre-find module path hook   distutils
5590 INFO: Processing pre-safe import module hook   six.moves
8339 INFO: Processing pre-find module path hook   site
8340 INFO: site: retargeting to fake-dir 'd:\\ancoda\\envs\\env_py36\\lib\\site-packages\\PyInstaller\\fake-modules'
10122 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
22311 INFO: Loading module hooks...
22312 INFO: Loading module hook "hook-distutils.py"...
22314 INFO: Loading module hook "hook-encodings.py"...
22586 INFO: Loading module hook "hook-lib2to3.py"...
22589 INFO: Loading module hook "hook-matplotlib.backends.py"...
23440 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
24240 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
24788 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
25443 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
26174 INFO:   Matplotlib backend "Qt4Agg": added
26913 INFO:   Matplotlib backend "Qt5Agg": added
27615 INFO:   Matplotlib backend "TkAgg": added
28321 INFO:   Matplotlib backend "WX": added
29018 INFO:   Matplotlib backend "WXAgg": added
29589 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
30366 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
30870 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "d:\ancoda\envs\env_py36\lib\site-packages\matplotlib\backends\backend_webagg.py", line 28, in <module>
    import tornado
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "d:\ancoda\envs\env_py36\lib\site-packages\matplotlib\backends\backend_webagg.py", line 30, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
31396 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'tornado'
32104 INFO:   Matplotlib backend "agg": added
32597 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
33085 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
33760 INFO:   Matplotlib backend "pdf": added
34579 INFO:   Matplotlib backend "pgf": added
35332 INFO:   Matplotlib backend "ps": added
36146 INFO:   Matplotlib backend "svg": added
36790 INFO:   Matplotlib backend "template": added
37193 INFO: Loading module hook "hook-matplotlib.py"...
37593 INFO: Loading module hook "hook-numpy.core.py"...
37670 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
37673 INFO: Loading module hook "hook-numpy.py"...
37674 INFO: Loading module hook "hook-PIL.Image.py"...
38224 INFO: Loading module hook "hook-PIL.py"...
38227 INFO: Excluding import 'PyQt4'
38229 INFO:   Removing import of PyQt4 from module PIL.ImageQt
38230 INFO: Excluding import 'tkinter'
38233 INFO:   Removing import of tkinter from module PIL.ImageTk
38234 INFO: Excluding import 'PyQt5'
38236 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
38237 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
38238 INFO: Import to be excluded not found: 'FixTk'
38238 INFO: Excluding import 'PySide'
38241 INFO:   Removing import of PySide from module PIL.ImageQt
38243 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
38245 INFO: Excluding import 'tkinter'
38246 INFO: Import to be excluded not found: 'FixTk'
38246 INFO: Loading module hook "hook-pkg_resources.py"...
38855 INFO: Processing pre-safe import module hook   win32com
39134 INFO: Loading module hook "hook-pydoc.py"...
39135 INFO: Loading module hook "hook-PyQt5.py"...
39343 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
39471 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
39698 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
40180 INFO: Loading module hook "hook-pythoncom.py"...
40560 INFO: Loading module hook "hook-pytz.py"...
40680 INFO: Loading module hook "hook-pywintypes.py"...
41191 INFO: Loading module hook "hook-scipy.py"...
41193 WARNING: Hidden import "scipy._lib.messagestream" not found!
41194 WARNING: Hidden import "scipy._lib._fpumode" not found!
41195 INFO: Loading module hook "hook-setuptools.py"...
42113 INFO: Loading module hook "hook-sysconfig.py"...
42115 INFO: Loading module hook "hook-win32com.py"...
42653 INFO: Loading module hook "hook-xml.dom.domreg.py"...
42653 INFO: Loading module hook "hook-xml.py"...
42656 INFO: Loading module hook "hook-_tkinter.py"...
42950 INFO: checking Tree
42950 INFO: Building Tree because Tree-00.toc is non existent
42951 INFO: Building Tree Tree-00.toc
43060 INFO: checking Tree
43060 INFO: Building Tree because Tree-01.toc is non existent
43062 INFO: Building Tree Tree-01.toc
43150 INFO: Looking for ctypes DLLs
43239 INFO: Analyzing run-time hooks ...
43249 INFO: Including run-time hook 'pyi_rth_qt5.py'
43251 INFO: Including run-time hook 'pyi_rth__tkinter.py'
43252 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
43256 INFO: Including run-time hook 'pyi_rth_pkgres.py'
43257 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
43259 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
43261 INFO: Including run-time hook 'pyi_rth_mpldata.py'
43282 INFO: Looking for dynamic libraries
59071 INFO: Looking for eggs
59071 INFO: Using Python library d:\ancoda\envs\env_py36\python36.dll
59072 INFO: Found binding redirects:
[]
59096 INFO: Warnings written to G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\warn-main.txt
59398 INFO: Graph cross-reference written to G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\xref-main.html
59523 INFO: Appending 'binaries' from .spec
59527 INFO: checking PYZ
59527 INFO: Building PYZ because PYZ-00.toc is non existent
59528 INFO: Building PYZ (ZlibArchive) G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\PYZ-00.pyz
62270 INFO: Building PYZ (ZlibArchive) G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\PYZ-00.pyz completed successfully.
62319 INFO: checking PKG
62319 INFO: Building PKG because PKG-00.toc is non existent
62322 INFO: Building PKG (CArchive) PKG-00.pkg
62365 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
62370 INFO: Bootloader d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
62370 INFO: checking EXE
62371 INFO: Building EXE because EXE-00.toc is non existent
62371 INFO: Building EXE from EXE-00.toc
62374 INFO: Appending archive to EXE G:\CodeSpace\PyinstallerPackageSpace\SAGD\UI\build\main\main.exe
62390 INFO: Building EXE from EXE-00.toc completed successfully.
62402 INFO: checking COLLECT
62402 INFO: Building COLLECT because COLLECT-00.toc is non existent
62405 INFO: Building COLLECT COLLECT-00.toc
Traceback (most recent call last):
  File "d:\ancoda\envs\env_py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\ancoda\envs\env_py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ancoda\envs\env_py36\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 40, in <module>
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\api.py", line 676, in __init__
    self.__postinit__()
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\api.py", line 707, in assemble
    dist_nm=inm)
  File "d:\ancoda\envs\env_py36\lib\site-packages\PyInstaller\building\utils.py", line 281, in checkCache
    shutil.copy(fnm, cachedfile)
  File "d:\ancoda\envs\env_py36\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "d:\ancoda\envs\env_py36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\AppData\\Roaming\\pyinstaller\\bincache00_py36_64bit\\ucrtbase.dll'


```

####  main.spec
```
# main.spec
# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI'],
             binaries=[('G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI\\*.dll','.')],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
a.datas+=(
('arrow_left.png', 'G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI\\image\\icon\\arrow_left.png', 'DATA'),
('arrow_right.png', 'G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI\\image\\icon\\arrow_right.png', 'DATA'),
('double_arrow_left.png', 'G:\\CodeSpace\\PyinstallerPackageSpace\\SAGD\\UI\\image\\icon\\double_arrow_left.png', 'DATA'),
('double_arrow_right.png', 'G:\\CodeSpace\\PyinstallerPackageSpace\\TuChart-master\\Tuchart3.0-beta\\double_arrow_right.png', 'DATA')
)

exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='main',
          debug=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='main')


```

**Comment by htgoebel** [comment]
Please read the manual about this.
