### ISSUE TITLE
ValueError: Read 1488 bytes, header reports 1968 bytes

### ISSUE THREAD

**Issue by dylib** [pyinstaller/pyinstaller#3834]
When building with the following command on `macOS 10.13.6` (MacPorts Python 2/3):
```
$ pyinstaller --windowed example.py
```
An error is always returned:

```
6756 INFO: Building BUNDLE BUNDLE-00.toc
Traceback (most recent call last):
  File "/opt/local/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 40, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/osx.py", line 89, in __init__
    self.__postinit__()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/osx.py", line 169, in assemble
    fnm = checkCache(fnm, strip=self.strip, upx=self.upx, dist_nm=inm)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/utils.py", line 228, in checkCache
    dylib.mac_set_relative_dylib_deps(cachedfile, dist_nm)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/depend/dylib.py", line 308, in mac_set_relative_dylib_deps
    dll = MachO(libname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholib/MachO.py", line 95, in __init__
    self.load(fp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholib/MachO.py", line 110, in load
    self.load_header(fh, 0, size)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholib/MachO.py", line 148, in load_header
    hdr = MachOHeader(self, fh, offset, size, magic, hdr, endian)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholib/MachO.py", line 188, in __init__
    self.load(fh)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholib/MachO.py", line 293, in load
    read_bytes, header.sizeofcmds))
ValueError: Read 1488 bytes, header reports 1968 bytes
```

The bundle is built, although it won't launch.

**Comment by kg-2** [comment]
I encountered this error after I installed upx via `brew install upx`.  To workaround I set `upx=False` in the .spec file for EXE and COLLECT.  It seems the header is being created before upx compresses the file.

**Comment by bwoodsend** [comment]
This should no longer be a problem since PyInstaller now only uses UPX on Windows.
