### ISSUE TITLE
Module problem

### ISSUE THREAD

**Issue by Tomasinjo** [pyinstaller/pyinstaller#3836]
Hi,
I am having some troubles with one specific import. After running .exe, there is exception:
```
C:\Users\Tom\Desktop\Python\mitre>attack_parse.exe -q

Traceback (most recent call last):
  File "attack_parse.py", line 138, in <module>
    main()
  File "attack_parse.py", line 114, in main
    mapping()
  File "attack_parse.py", line 27, in mapping
    Filter('relationship_type','=','mitigates') # find only techniques
  File "site-packages\stix2\datastore\__init__.py", line 98, in query
  File "site-packages\stix2\datastore\filesystem.py", line 323, in query
  File "site-packages\stix2\datastore\filesystem.py", line 323, in <listcomp>
  File "site-packages\stix2\core.py", line 100, in parse
  File "site-packages\stix2\core.py", line 133, in dict_to_stix2
KeyError: 'v20'
[13960] Failed to execute script attack_parse
```

Stix2 is project available here: https://github.com/oasis-open/cti-python-stix2/tree/master/stix2
Closer look at error line 133 in core.py:
`    OBJ_MAP = STIX2_OBJ_MAPS[v]`

There should be key named "v20" and it is missing from dict. This dictionary is filled by those lines in same file:
```
def _collect_stix2_obj_maps():
    """Navigate the package once and retrieve all OBJ_MAP dicts for each v2X
    package."""
    if not STIX2_OBJ_MAPS:
        top_level_module = importlib.import_module('stix2')
        path = top_level_module.__path__
        prefix = str(top_level_module.__name__) + '.'

        for module_loader, name, is_pkg in pkgutil.walk_packages(path=path,
                                                                 prefix=prefix):

            if name.startswith('stix2.v2') and is_pkg:
                mod = importlib.import_module(name, str(top_level_module.__name__))
                STIX2_OBJ_MAPS[name.split('.')[-1]] = mod.OBJ_MAP
```
And the problem is that `pkgutil.walk_packages(path=path, prefix=prefix):` is probably empty. So I printed out path argument:
`'C:\\Users\\Tom\\AppData\\Local\\Temp\\_MEI196122\\stix2'`

I quickly opened MEIxxxxx folder and discovered that stix2 folder was not created / unpacked. 

Can you please help me with that?

**Comment by bwoodsend** [comment]
`--collect-submodules=stix2` should do it.
