### ISSUE TITLE
Offline installs general error when attempting to read https://pypi.python.org/simple/

### ISSUE THREAD

**Issue by simsong** [pyinstaller/pyinstaller#3853]
This is a follow-up of https://github.com/pyinstaller/pyinstaller/issues/2493 .

I am attempting an offline install and have manually resolved all of the dependencies. However, setup.py still generates an error because it is attempting to access the future files:

```
Installed /mnt/apps/Anaconda/lib/python3.6/site-packages/PyInstaller-3.4-py3.6.egg
Processing dependencies for PyInstaller==3.4
Searching for future
Reading https://pypi.python.org/simple/future/
Download error on https://pypi.python.org/simple/future/: [Errno 101] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'future' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
No local packages or working download links found for future
error: Could not find suitable distribution for Requirement.parse('future')

```

This results in an installation that will not work:

```
$ pyinstaller
Traceback (most recent call last):
  File "/apps/Anaconda/bin/pyinstaller", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/apps/Anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/apps/Anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/apps/Anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/apps/Anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/apps/Anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/apps/Anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'future' distribution was not found and is required by pefile
$

```

**Comment by htgoebel** [comment]
Obviously you installation failed. This is not an PyInstaller issue, please check your environment

**Comment by simsong** [comment]
Hi. I do not think that you understood my question. I am attempting an offline installation and the instructions that you provide do not work, because your offline installation still requires access to the Internet.

**Comment by htgoebel** [comment]
AFAIK we do not provide any instruction for offline installation. You referenced to #2493 and you should find all required information there. I'm not tutoring you for how to use pip.

If you thing this should be mentioned in the manual, please provide a pull-request.

**Comment by simsong** [comment]
Well, I did follow those instructions and they did not work. It would be useful to have a list of the dependencies or to have the specific packages that are being sought to be displayed. I will investigate doing so.
