### ISSUE TITLE
Traceback (most recent call last):   File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 43, in _freeze_support   File "Lib\multiprocessing\spawn.py", line 106, in spawn_main SystemExit: 0

### ISSUE THREAD

**Issue by crmchan** [pyinstaller/pyinstaller#3858]
close

**Comment by crmchan** [comment]
If use command below, it would tip error

..\a.exe --multiprocessi
ng-fork -t test -i E:\LOG.isf


```
fail to multiprocessing.freeze_support e= not enough values to unpack (expected
2, got 1)
```
