### ISSUE TITLE
Bundled exe works in Windows Desktop but not in Windows Server

### ISSUE THREAD

**Issue by sundarcodes** [pyinstaller/pyinstaller#3868]
* Does the error occur when bundling the application or when running it?
The error occurs when running the application in a Windows Server 2012 machine. The bundled exe works fine in Windows Desktops (8, 9, 10) but throws an import error when running in Windows Server 2012.
* If you have an import error, please submit the last part of the traceback. This helps a lot to see which modules tried to import which other one
import cv2 # PyInstaller PYZ
 cv2.cv2 not found in PYZ
Traceback (most recent call last):
  File "detect-barcode.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\projects\barcode-detector\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\imutils\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\projects\barcode-detector\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\imutils\convenience.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\projects\barcode-detector\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

The same opencv import works just fine and it is able to load it as an extension module. The below is the output from dev/working systems.
 import cv2 # PyInstaller PYZ
 cv2.cv2 not found in PYZ
 extension module 'cv2.cv2' loaded from 'C:\\Projects\\barcode-detector\\debug\\splitter-one-dir\\cv2\\cv2.cp37-win32.pyd'
 extension module 'cv2.cv2' executed from 'C:\\Projects\\barcode-detector\\debug\\splitter-one-dir\\cv2\\cv2.cp37-win32.pyd'

* Software versions you are using.
```
PyInstaller: 3.4
Python: 3.7.0
Development Platform: Windows-10-10.0.17134-SP0
Platform not working (Deployment platform) - Windows Server 2012 R2
```
* Any other information
As the error shows, it is failing to load the open cv module, I added the opencv_ffmpeg343.dll as a part of exe bundling, But that didn't help as well.  

Would appreciate if you could give me some directions/pointers where I could go and explore to fix this issue. Thanks :)

**Comment by sundarcodes** [comment]
It looks like this could be an issue where one of dll (universal c runtime) not present in the Windows Server 2012. Sorry for raising the issue here. Closing it :)
