### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 8107: character maps to <undefined>

### ISSUE THREAD

**Issue by frakman1** [pyinstaller/pyinstaller#3899]
Issue created from [here](https://github.com/pyinstaller/pyinstaller/issues/3605#issuecomment-442712520)

I get this error when I try to put emojis in my .spec file as a way to generate constants to import into my .py file.  They work in that they render on-screen when used within my .py file and running the program using the python interpreter. When I moved them to the .spec file, I get the error below when launching pyinstaller.

PyInstaller 3.4
Win 7-64 bit (also on Win 10)

```bash
C:\Users\username\AppData\Local\Programs\Python\Python37\PySimpleGUI\Git\frakalog-win>pyinstaller --onefile frakalog.spec
347 INFO: PyInstaller: 3.4
347 INFO: Python: 3.7.0
351 INFO: Platform: Windows-10-10.0.15063-SP0
356 INFO: UPX is not available.
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "c:\users\username\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\username\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\username\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\username\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 783, in build
    text = f.read()
  File "c:\users\username\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 8107: character maps to <undefined>
```
excerpt from .spec file:

```python
# -*- mode: python -*-
# -*- encoding: utf-8 -*-

name_emoji = "👤"
title_emoji = "🎖️"
ID_emoji = "🆔"
office_emoji = "💺"
phone_emoji = "📞"
mobile_emoji = "📱"
email_emoji = "📬"
group_emoji = "👥"
phone2_emoji = "☎️"
room_emoji = "🏠"
username_emoji = "💻"


# Write version info into _constants.py resource file
with open('_constants.py', 'w') as f:
    f.write("name_emoji = {}\n".format(name_emoji))
    f.write("title_emoji = {}\n".format(title_emoji))
    f.write("ID_emoji = {}\n".format(ID_emoji))
    f.write("office_emoji = {}\n".format(office_emoji))
    f.write("phone_emoji = {}\n".format(phone_emoji))
    f.write("mobile_emoji = {}\n".format(mobile_emoji))
    f.write("email_emoji = {}\n".format(email_emoji))
    f.write("group_emoji = {}\n".format(group_emoji))
    f.write("phone2_emoji = {}\n".format(phone2_emoji))
    f.write("room_emoji = {}\n".format(room_emoji))
 

# The rest of the .spec file ...

```

**Comment by htgoebel** [comment]
Thanks for opening this new issue. 

Since there already is a test for an utf-8 encoded spec-file ([function/test_basic.py::test_spec_with_utf8](https://github.com/pyinstaller/pyinstaller/blob/v3.4/tests/functional/test_basic.py#L519), using [this spec-file](https://github.com/pyinstaller/pyinstaller/blob/v3.4/tests/functional/specs/spec-with-utf8.spec)), I wonder what is wrong here or what the test is missing. 

Can you please **attach** the .spec-file (as a file) to avoid any transmission errors. I would like to verify the .spec-file is correct. Maybe python doesn't detect the spec-file's encoding correctly or the emoji-characters are wrong.

Related pull-request: #3895

**Comment by bjones1** [comment]
Looking at the test, I noticed that [test_spec](https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/conftest.py#L150) just calls [test_script](https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/conftest.py#L206), which means it doesn't actually exercise reading a `.spec` file at all. 

The tests are broken.

**Comment by htgoebel** [comment]
Yes, `test_spec` calls `test_script`, same does `test_source`. `test_spec` passes the .spec-filename as argument., wheras `test_source` passes the script-filename.

I just verified whether test_spec_with_utf8 actually uses the spec-file by adding some syntax error to spec-with-utf8.spec.

BTW: When changing code in this ares we should wrap https://github.com/pyinstaller/pyinstaller/blob/v3.4/PyInstaller/building/build_main.py#L781-L784 by some code suppressing the trace-back but printing a nice error message like it is done here https://github.com/pyinstaller/pyinstaller/blob/ad87e72d1596f/PyInstaller/compat.py#L369-L379

**Comment by Ali6259** [comment]
I have an issue of when using pyinstaller --onefile filename.py i get an error: UnicodeDecodeError: 'charmap' codec can't decode byte.

import glob
import os.path, time
from collections import defaultdict
from datetime import datetime
from zipfile import BadZipFile
from openpyxl import load_workbook

FOLDER_PATH = 'K:/' # Relative or absolute Path to the folder to be scanned.
DB_PATH = 'K:/MelnicomUtils/DB.xlsx' # Path to the database excel file.
LOG_PATH = 'K:/MelnicomUtils/log.xlsx'

""" FOLDER_PATH = 'C:/Users/melni/Desktop/לקוחות/momentum/files/' # Relative or absolute Path to the folder to be scanned.
DB_PATH = 'C:/Users/melni/Desktop/לקוחות/momentum/DB.xlsx' # Path to the database excel file.
LOG_PATH = 'C:/Users/melni/Desktop/לקוחות/momentum/log.xlsx' """

logWB = load_workbook(filename=LOG_PATH, data_only=True)
log_row= 2
fileC = 0 #File counter

reports_sheet = 'ניתוח דוחות'
obligo_sheet = 'אובליגו'
analyse_sheet_db = 'ניתוח דוחות-מאזנים'
needed_sheetnames = [reports_sheet, obligo_sheet]
year_cells = ['C2', 'E2', 'G2', 'I2', 'K2']

def isvalid(wb,file):
"""
Checks if the supplied excel workbook is valid.
:param wb: The excel workbook
:type wb: Workbook
:return: Returns True if the workbook is valid and should be used for data extraction.
:rtype: bool
"""
try:
sheetnames = list(map(str.strip, wb.sheetnames))
if not all(elem in sheetnames for elem in needed_sheetnames):
write_to_log_file(file ,"חסר גליון ניתוח דוחות או אובליגו או ניתוח דוחות-מאזנים")
return False

    reports = wb[reports_sheet]
    try:
        if not any('מאזנים' in cell.value for cell in reports['B'] if cell.value is not None):
            write_to_log_file(file,"חסרה המילה מאזנים בעמודה B")
            return False
    except:  
        write_to_log_file(file,"תקלה בזמן חיפוש המילה מאזנים בעמודה B")
        return False

    
    a1 = reports['A1'].value
    if not a1 or 'תאריך הבוחן' not in a1:
        write_to_log_file(file,"חסר תאריך הבוחן")
        return False

    try:
        obligo = wb['אובליגו']
    except KeyError:
        obligo = wb['אובליגו ']  # TODO: Should this be like that?

    if 'שם הבנק:' != obligo['C2'].value:
        write_to_log_file(file,"חסר שם הבנק")
        return False

    return True
except:
    return False
def rec_dd():
return defaultdict(rec_dd)

def get_data(wb):
"""
Gets data from the supplied Excel workbook.
:param wb: The supplied Excel workbook
:type wb: Workbook
:return: Returns a dict containing the extracted data
:rtype: dict
"""
data = rec_dd()

ws = wb[reports_sheet]
try:
    specified_date = ws['C1'].value.date()
    data['date'] = specified_date
except AttributeError:
    return None
last_day_of_year = datetime.today().date().replace(month=12, day=31, year=specified_date.year)

company = ws['E1'].value

# Sheet 1 - Table 1
for i, cell in enumerate(year_cells):
    year = ws[cell].value

    if year == specified_date.year and specified_date != last_day_of_year:
        continue

    for row in ws.iter_rows(min_row=5, max_col=12):

        if row[1].value == 'מאזנים':
            break

        value = row[i * 2 + 2].value
        percentage = row[i * 2 + 3].value
        header = row[1].value

        if not value:
            continue

        data[reports_sheet][company][year][header] = {
            'value': value,
            'percentage': percentage
        }
        #print("Added to sheet " + reports_sheet + " for company " + company + " year " + year + " header " + header + ":")
        #print("Value: " + value + ", Percentage: " + percentage)

for cell in ws['B']:
    if cell.value == 'מאזנים':
        year_row = cell.row + 2
        year_cells_table2 = [s + str(year_row) for s in ['C', 'E', 'G']]

# Sheet 1 - Table 2
for i, cell in enumerate(year_cells_table2):
    year = ws[cell].value

    if year == specified_date.year and specified_date != last_day_of_year:
        continue

    for row in ws.iter_rows(min_row=year_row, max_col=8):

        value = row[i * 2 + 2].value
        percentage = row[i * 2 + 3].value
        header = row[1].value

        if not value or not header:
            continue

        data[analyse_sheet_db][company][year][header] = {
            'value': value,
            'percentage': percentage
        }

# Sheet 2 - Table 3
try:
    ws = wb['אובליגו']
except KeyError:
    ws = wb['אובליגו ']
values = {}
oldest = None
for row in ws.iter_rows(min_row=2, min_col=3):
    header = row[0].value
    if not header:
        break
    elif header == 'מעודכן לתאריך:':
        try:
            oldest = max(entry.value for entry in row if isinstance(entry.value, datetime))
        except ValueError:
            break
        continue
    elif header == 'שם הבנק:':
        try:
            col = next(entry.column for entry in row if entry.value == 'סה"כ') - 3
        except:
            break
        continue

    try:
        value = row[col].value
    except:
        break

    if value == 'סה"כ' or not value:
        continue

    values[header] = value

if oldest is not None:
    data[obligo_sheet] = {
        'company': company,
        'year': oldest.year,
        'values': values
    }
else:
    data[obligo_sheet] = {
    }

return data
def add_reports(ws, data, date=None,file=""):
"""
Adds data to the first two sheets.
:param ws: The worksheet
:param data: The dict containing the data from the original excel file
"""

# set default values
date_column = 5
year_column = 4
company_column = 3
updateF = False
# Get Year column
for row in ws.iter_rows(min_row=1, max_row=1):
    for cell in row:
        if cell.value == 'שנה':
            year_column = cell.column
        elif cell.value == 'shtDate':
            date_column = cell.column
        elif cell.value == 'חפ':
            company_column = cell.column

for company, years in data.items():
    for year, entries in years.items():
        row_to_be_changed = 0
        for row in ws.iter_rows(min_col=company_column, max_col=year_column):
            if row[0].value == company and row[1].value == year:
                row_to_be_changed = row[0].row
                try:
                    if date < row[2].value and date:
                        return False
                except TypeError:
                    write_to_log_file(file,"נכשל שורה 220")
                    pass
                except:
                    pass
                break

        if row_to_be_changed == 0:
            row_to_be_changed = ws.max_row + 1
            ws.cell(row_to_be_changed,date_column).value = date
            updateF = True
        else:
            DBshtDate = ws.cell(row_to_be_changed,date_column).value
            srcShtDate = date
            if DBshtDate is None or str(srcShtDate) >   str(DBshtDate):
                updateF = True

        ws.cell(row_to_be_changed, year_column).value = year  
        ws.cell(row_to_be_changed, company_column).value = company
        # write_to_log_file(file,"sucess")
        
        
        if date:
            ws.cell(row_to_be_changed, year_column + 1).value = date

        for header, entry in entries.items():
            if header == None:
                header = ""
            for row in ws.iter_rows(min_row=1, max_row=1):
                for cell in row:
                    if header == cell.value:
                        ws.cell(row_to_be_changed, cell.column).value = entry['value']
                    elif str(header) + "P" == cell.value:
                        ws.cell(row_to_be_changed, cell.column).value = entry['percentage']
return updateF
def write_to_log_file(FileName,Status):
logWS = logWB['log']
log_row = logWS.max_row+1
logWB['log'].cell(log_row,1).value = FileName
logWB['log'].cell(log_row,2).value = datetime.now()
logWB['log'].cell(log_row,3).value = Status
logWB['log'].cell(log_row,4).value = datetime.fromtimestamp(os.path.getmtime(FileName))
if log_row % 3 == 0:
logWB.save(LOG_PATH)
# logWB.close

def add_obligo_reports(ws, data, file):
"""
Adds data to the third ("obligo") sheet
:param ws: The worksheet
:param data: The dict containing the data from the original excel file
:return:
"""
if not data:
return

for row in ws.iter_rows(min_row=1, max_row=1):
    for cell in row:
        if cell.value == 'שנה':
            year_column = cell.column
        elif cell.value == 'חפ':
            company_column = cell.column

row_to_be_changed = 0
for row in ws.iter_rows(min_col=company_column, max_col=year_column):
    if row[0].value == data['company'] and row[1].value == data['year']:
        row_to_be_changed = row[0].row
        break

if row_to_be_changed == 0:
    row_to_be_changed = ws.max_row + 1
ws.cell(row_to_be_changed, year_column).value = data['year']
ws.cell(row_to_be_changed, company_column).value = data['company']

for header, entry_value in data['values'].items():
    for row in ws.iter_rows(min_row=1, max_row=1):
        for cell in row:
            if header == cell.value:
                ws.cell(row_to_be_changed, cell.column).value = entry_value
def add_to_db(data,file):
"""
Adds the dict data to database excel.
:param data: A dict containing the extracted data
:type data: dict
"""

if add_reports(DBwb[reports_sheet], data[reports_sheet], data['date'],file):
    add_reports(DBwb[analyse_sheet_db], data[analyse_sheet_db],file)
    add_obligo_reports(DBwb[obligo_sheet], data[obligo_sheet],file)
    print("Saving database file to " + DB_PATH)
    DBwb.save(DB_PATH)
def scan_folder(path):
"""
Scans folder and all subfolders of supplied path for .xlsx files.
Then every file is checked for its validity. If it is valid, the
data gets extracted and added to the database excel file.
:param path: Path that should be scanned
:type path: str
"""
global fileC
files = glob.glob(path + '/**/*.xlsx', recursive=True)
print("Scanning " + str(len(files)) + " files.")

for file in files:
    file.__getattribute__
    if '.xlsx' not in file:
        continue

    try:
        wb = load_workbook(filename=file, data_only=True)
    except:
        write_to_log_file(file,"לא מצליח לטעון את הקובץ")
        continue

    if not isvalid(wb,file):
       continue

    write_to_log_file(file,"קובץ תקין")
    fileC += 1
    data = get_data(wb)

    if not data:
        continue

    add_to_db(data,file)
if name == "main":
DBwb = load_workbook(filename=DB_PATH, data_only=True)
scan_folder(FOLDER_PATH)
print("Scan complete.")
#Update log file
""" fo = open(file="./log.txt",mode="a",encoding="utf-8")
dt = datetime.now()
fo.write("\n" + str(dt) + ": Scan of " + str(fileC) + " valid files is complete.")
fo.close()
print("Log updated.") """
else:
print("ERROR, cannot scan.")

**Comment by htgoebel** [comment]
@Ali6259 I suggest you to learn how to contribute to a bug report. Just pasting a *huge* pile of code *does not help* in any way. Not formatting as code and posting the saem huge pile of code to severl issues is even worse,. The only effect is that you are wasting volunteers valuable time.

**Comment by Legorooj** [comment]
Closing due to inactivity. If the error persists, please open a new issue, after testing with a supported version of python and the develop branch

**Comment by frakman1** [comment]
> Closing due to inactivity.

@Legorooj What a cop-out.

**Comment by Legorooj** [comment]
@frakman1 is the issue still present? I'll reopen. (Btw inactive issues can't be dealt with.)

**Comment by frakman1** [comment]
If it isn't fixed, then it's still present.

**Comment by Legorooj** [comment]
@frakman1 I've closed over 100 issues in PyInstaller in the last week and 90% have been fixed. Without the issues being closed, or the members knowing it's been fixed by another PR that's fixed that issue as a side effect. So what you say is not true on a project as large as PyInstaller. If an issue is inactive, I'll close it until it's proved still active.
