### ISSUE TITLE
unable to install on armv7 alpine

### ISSUE THREAD

**Issue by mateodelnorte** [pyinstaller/pyinstaller#3903]
Hi there. I'm attempting to pip install pyinstaller in an armv7 alpine docker container and getting the following error:
```
Building wheels for collected packages: pyinstaller, PyYAML, backports.ssl-match-hostname, dockerpty, texttable, docopt, pefile, dis3, functools32, future
  Running setup.py bdist_wheel for pyinstaller ... error
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bANyBM/pyinstaller/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3zXwLl --python-tag cp27:
  running bdist_wheel
  running build
  running build_bootloader
  No precompiled bootloader found. Trying to compile it for you ...
  Setting top to                           : /tmp/pip-install-bANyBM/pyinstaller/bootloader
  Setting out to                           : /tmp/pip-install-bANyBM/pyinstaller/bootloader/build
  Python Version                           : 2.7.15 (default, Jun 14 2018, 10:43:11) [GCC 6.4.0]
  Checking for 'gcc' (C compiler)          : not found
  Checking for 'clang' (C compiler)        : not found
  Checking for 'icc' (C compiler)          : not found
  could not configure a C compiler!
  (complete log in /tmp/pip-install-bANyBM/pyinstaller/bootloader/build/config.log)
  ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.py

  ----------------------------------------
  Failed building wheel for pyinstaller
``` 
this error is noting that gcc is missing, so I've attempted to solve it by adding gcc to my container image. doing so lends the resulting error: 
```
Building wheels for collected packages: PyInstaller, pefile, dis3, future
  Running setup.py bdist_wheel for PyInstaller: started
  Running setup.py bdist_wheel for PyInstaller: finished with status 'error'
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-2TeDZ_/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-fClE4M --python-tag cp27:
  running bdist_wheel
  running build
  running build_bootloader
  No precompiled bootloader found. Trying to compile it for you ...
  Setting top to                           : /tmp/pip-req-build-2TeDZ_/bootloader
  Setting out to                           : /tmp/pip-req-build-2TeDZ_/bootloader/build
  Python Version                           : 2.7.15 (default, Jun 14 2018, 10:43:11) [GCC 6.4.0]
  Checking for 'gcc' (C compiler)          : /usr/bin/gcc
  Checking size of pointer                 : not found
  Couldn't determine pointer size, only 32 or 64 bit are supported. Please use `--target-arch' to set the pointer size.
  (complete log in /tmp/pip-req-build-2TeDZ_/bootloader/build/config.log)
  ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.py

  ----------------------------------------
  Failed building wheel for PyInstaller
```
What's the appropriate way to build pyinstaller on an arch that does not include gcc by default? Is there a means of specifying the `--target-arch` option, as is being logged?

**Comment by htgoebel** [comment]
> Is there a means of specifying the --target-arch option, as is being logged?

No, you can't specify this option via `pip`. Please install the source archive, unpack, build the bootloader and install from this unpacked archive.

**Comment by mateodelnorte** [comment]
Do you have any links to more detailed instructions on the above?

**Comment by mateodelnorte** [comment]
Found it. https://pyinstaller.readthedocs.io/en/latest/bootloader-building.html

Where should the bootloader be built, and located so that pyinstaller can find it? Does it need to be in PATH?

**Comment by htgoebel** [comment]
The built bootloaders will automatically be put where PyInstaller picks them up: PyInstaller/bootloader/<arch>/

If you think this sall be improvved in the manual, please provide a pull-request.

**Comment by mateodelnorte** [comment]
Currently getting hung up at: 
```
[1/2] Compiling build/.conf_check_5cc9a68621e748f7a0976f9bf2bc023c/test.c

['/usr/bin/gcc', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-U_FORTIFY_SOURCE', '-D_REENTRANT', '-D_BSD_SOURCE', '-D_DEFAULT_SOURCE', '-D_FORTIFY_SOURCE=2', '../test.c', '-c', '-o/pyinstaller/bootloader/build/.conf_check_5cc9a68621e748f7a0976f9bf2bc023c/testbuild/test.c.1.o']
[2/2] Linking build/.conf_check_5cc9a68621e748f7a0976f9bf2bc023c/testbuild/testprog

['/usr/bin/gcc', 'test.c.1.o', '-o/pyinstaller/bootloader/build/.conf_check_5cc9a68621e748f7a0976f9bf2bc023c/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lz']
err: /usr/lib/gcc/armv6-alpine-linux-musleabihf/8.2.0/../../../../armv6-alpine-linux-musleabihf/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status

from /pyinstaller/bootloader: Test does not build: Traceback (most recent call last):
  File "/pyinstaller/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Configure.py", line 324, in run_build
    bld.compile()
  File "/pyinstaller/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

not found
from /pyinstaller/bootloader: The configuration failed
```
Any insight on what the z package is?

**Comment by htgoebel** [comment]
> Any insight on what the z package is? 

zlib, libz - the compression library

**Comment by mateodelnorte** [comment]
alrighty. got through that hurdle: 
```
Step 5/7 : RUN git clone https://github.com/pyinstaller/pyinstaller.git
 ---> Running in b165d9a67027
Cloning into 'pyinstaller'...
Removing intermediate container b165d9a67027
 ---> cbf813b1207f
Step 6/7 : RUN cd pyinstaller/bootloader && python ./waf all --target-arch=32bit
 ---> Running in cd49ae429724
'all' finished successfully (0.006s)
'distclean' finished successfully (0.001s)
Setting top to                           : /pyinstaller/bootloader
Setting out to                           : /pyinstaller/bootloader/build
Python Version                           : 2.7.15 (default, Jun 14 2018, 10:43:11) [GCC 6.4.0]
Checking for 'gcc' (C compiler)          : /usr/bin/gcc
Platform                                 : Linux-32bit manually chosen
Checking for program '/usr/bin/strip'    : /usr/bin/strip
Checking for program 'strip'             : /usr/bin/strip
Checking for library dl                  : yes
Checking for library m                   : yes
Checking for library z                   : yes
Checking for function unsetenv           : yes
Checking for function mkdtemp            : yes
Checking for flags -Wl,--as-needed       : yes
'configure' finished successfully (4.129s)
'make_all' finished successfully (0.037s)
Waf: Entering directory `/pyinstaller/bootloader/build/debug'
[ 1/13] Compiling src/pyi_python.c
[ 2/13] Compiling src/pyi_global.c
[ 3/13] Compiling src/main.c
[ 4/13] Compiling src/pyi_archive.c
[ 5/13] Compiling src/pyi_utils.c
[ 6/13] Compiling src/pyi_launch.c
[ 7/13] Compiling src/pyi_path.c
../../src/pyi_path.c: In function 'pyi_path_join':
../../src/pyi_path.c:143:5: error: 'strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
     strncpy(result, path1, strlen(path1));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/pyi_path.c:156:9: error: 'strncat' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
         strncat(result, path2, len - 2);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/pyi_path.c:152:11: note: length computed here
     len = strlen(path2);
           ^~~~~~~~~~~~~
cc1: all warnings being treated as errors

Waf: Leaving directory `/pyinstaller/bootloader/build/debug'
Build failed
 -> task in 'run_d' failed with exit status 1 (run with -v to display more information)
The command '/bin/sh -c cd pyinstaller/bootloader && python ./waf all --target-arch=32bit' returned a non-zero code: 1
```
any input on the above error?

**Comment by mateodelnorte** [comment]
Got it. Had to ensure I was using gcc version 6.4.0-r9, and not the newer version in edge.

**Comment by htgoebel** [comment]
Fine. maybe you want to provide a pull-request fixing the error showing up with the newer version of gcc.
