### ISSUE TITLE
 Binary dependencies windows 10 python2.exe

### ISSUE THREAD

**Issue by MorningGlory747** [pyinstaller/pyinstaller#3908]
Hello,

I am, 
- Currently trying to run a simple `print('Hello world!')` script called "Setup_testing_script.py"
- Using Windows 10. 
- Using pyinstaller 3.5.dev0+d619fa7d1 with python2.7 (note that I have tried with v3.4 and still receive the same error). 
- Pip installed pyinstaller within the Python script directory. 

From the command prompt, my line is the following:

`>>C:\Python27\Scripts\pyinstaller.exe "C:\Users\***\Documents\Setup_testing_script.py"`

I receive the following error: 

```
Can not get binary dependencies for file: c:\python27\python2.exe
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\PyInstaller\depend\bindepend.py", line 720, in getImports
    return _getImports_pe(pth)
  File "c:\python27\lib\site-packages\PyInstaller\depend\bindepend.py", line 104, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\python27\lib\site-packages\pefile.py", line 1758, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\python27\lib\site-packages\pefile.py", line 1803, in __parse__
    raise PEFormatError('The file is empty')
PEFormatError: 'The file is empty'
635 INFO: Caching module hooks...
642 INFO: Analyzing C:\Users\***\Documents\Setup_testing_script.py
644 INFO: Loading module hooks...
644 INFO: Loading module hook "hook-encodings.py"...
3046 INFO: Looking for ctypes DLLs
3046 INFO: Analyzing run-time hooks ...
3050 INFO: Looking for dynamic libraries
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "c:\python27\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python27\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\python27\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line 565, in assemble
    redirects=self.binding_redirects))
  File "c:\python27\lib\site-packages\PyInstaller\depend\bindepend.py", line 225, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
  File "c:\python27\lib\site-packages\PyInstaller\depend\bindepend.py", line 506, in selectImports
    npth = getfullnameof(lib, xtrapath)
  File "c:\python27\lib\site-packages\PyInstaller\depend\bindepend.py", line 85, in getfullnameof
    if os.path.exists(npth) and matchDLLArch(npth):
  File "c:\python27\lib\site-packages\PyInstaller\depend\bindepend.py", line 188, in matchDLLArch
    exe_pe = pefile.PE(sys.executable, fast_load=True)
  File "c:\python27\lib\site-packages\pefile.py", line 1758, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\python27\lib\site-packages\pefile.py", line 1803, in __parse__
    raise PEFormatError('The file is empty')
pefile.PEFormatError: 'The file is empty'
```

After running the debug
`>> pyinstaller.exe --log-level=DEBUG "C:\Users\***\Documents\Setup_testing_script.py"`
I received the same message. 

I previously setted up python2.7 to my path, hence I can succesfully enter python2.7 when doing the command:
`>>python2.exe`

I can make the script run properly when executing:
```
>>python2.7 "C:\Users\***\Documents\Setup_testing_script.py"
Hello world!
```

I'm clearly doing something wrong, would anybody be able to guide me through it? I've seen previous posts regarding this binary thing and the solution seemed to be within the pyinstaller updates, but even when using the most recent version I still have this issue.

Cheers,

**Comment by htgoebel** [comment]
Looks like something wrong with your python.exe. Please try the latest development version. I added code to report whicl file actuall is causing the problem.
