### ISSUE TITLE
pkg_resources.DistributionNotFound: PyInstaller

### ISSUE THREAD

**Issue by LawOfTime** [pyinstaller/pyinstaller#3909]
I have tried reinstalling pyinstaller, I have tried using PIP to install it, I have tried git installing it, nothing works, here's my error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 7, in <module>
    from PyInstaller.__main__ import run
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__init__.py", line 66, in <module>
    __version__ = pkg_resources.get_distribution('PyInstaller').version
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 330, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 209, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PyInstaller
```

**Comment by htgoebel** [comment]
Something when wrong when installing PyInstaller,. I assumes /usr/local/bin/pyinstaller is from anotehr isntall. Please check your installation.

**Comment by LawOfTime** [comment]
Yeah, this doesn't help -_-
