### ISSUE TITLE
pyinstaller can't found pydensecrf dependecies on Anaconda

### ISSUE THREAD

**Issue by primasanjaya** [pyinstaller/pyinstaller#3918]
Hi!

I can make sure that the pyinstaller runs correctly with simple python code, however, when i try to run with my project directory, i got the error message that pydensecrf dependencies can't be found:

My platform:
Windows 10 [Version 10.0.16299.785]
Anaconda v.4.5.11
Python 3.6.5 via Anaconda [MSC v.1900 64 bit (AMD64)]
PyInstaller v.3.4

These are all my steps:

1. git clone project dir:
git clone [project](https://github.com/primasanjaya/Pytorch-UNet.git)

2. install conda dependency: 
conda install -c conda-forge pydensecrf

version 1.0rc3

3. inside project directory, run:
pyinstaller train.py

I've got my exe file in projectdir/dist/train/train.exe. But when i run it from this directory. I got these error messages:

Traceback (most recent call last):
  File "train.py", line 13, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "utils\__init__.py", line 1, in <module>
    from .crf import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "utils\crf.py", line 2, in <module>
    import pydensecrf.densecrf as dcrf
  File "pydensecrf/eigen.pxd", line 19, in init pydensecrf.densecrf (pydensecrf/densecrf.cpp:19339)
ModuleNotFoundError: No module named 'pydensecrf.eigen'
[9848] Failed to execute script train

Is there any reason why the pydensecrf can't be found? how to solve this?
Thank you

**Comment by primasanjaya** [comment]
solved, pydensecrf problem
