### ISSUE TITLE
Pyinstaller_Plotnine_pyimod03_importers.py_Error

### ISSUE THREAD

**Issue by James-sky** [pyinstaller/pyinstaller#3923]
Dear All,

When i tried to use Pyinstaller to convert .py to .exe for plotnine, i found below error during execute the .exe.

The .py source code just import plotnine only (from plotnine import *). Appreciate if anyone can tell me what happening on it?

PyInstaller : 3.3.1
Python : 3.6.5
Platform : Windows-10-10.0.15063-SP0
Plotnine : 0.5.1
Pandas : 0.23.4

Error :

[8048] LOADER: Running Test_modules.py
Traceback (most recent call last):
File "Test_modules.py", line 1, in 
from plotnine import *
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\plotnine_init.py", line 1, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\plotnine\qplot.py", line 9, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\plotnine\ggplot.py", line 17, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\plotnine\facets_init.py", line 1, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\plotnine\facets\facet_grid.py", line 6, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\plotnine\facets\facet.py", line 12, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\plotnine\scales_init.py", line 2, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\plotnine\scales\scale_alpha.py", line 2, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\mizani\palettes.py", line 23, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\palettable_init.py", line 11, in 
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\palettable\colorbrewer_init.py", line 3, in 
File "", line 971, in find_and_load
File "", line 955, in find_and_load_unlocked
File "", line 665, in load_unlocked
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
exec(bytecode, module.dict)
File "site-packages\palettable\colorbrewer\colorbrewer.py", line 14, in 
File "site-packages\pkg_resources_init.py", line 1149, in resource_string
File "site-packages\pkg_resources_init.py", line 1393, in get_resource_string
File "site-packages\pkg_resources_init.py", line 1469, in _get
File "c:\users\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 479, in get_data
with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Desktop\test\dist\Test_modules\palettable\colorbrewer\data\colorbrewer_all_schemes.json'

**Comment by htgoebel** [comment]
This looks like not all required data files are packages. Please read the manual to learn how to include them.

**Comment by James-sky** [comment]
@htgoebel  Appreciate if you can showed me the link for the manual and hint me what data files is missing.

**Comment by htgoebel** [comment]
The link to the manual can be found a) in the README b) on the website and c) in the wiki resp. FAQ. Do you really expect me to nanny you and to copy the link here?

**Comment by James-sky** [comment]
@htgoebel Got it. Thank you.

**Comment by psandev** [comment]
I haven't been able to find a solution. could you please, post a solution, or at least a more detailed explanation. Thanks a lot.

**Comment by minorsecond** [comment]
I included this in `datas` in my .spec file and it fixed it. Modify as needed and give it a shot.

`("C:\\Users\\rwardrup\\anaconda3\\envs\\TEST\\Lib\site-packages\\palettable\\colorbrewer\\data\\colorbrewer_all_schemes.json", "palettable\\colorbrewer\\data\\")`

**Comment by psandev** [comment]
BLESS YOU, it worked!!! I spent quite many hours and lost hope already(
although, at the end I was close, but not quite there😀). I was using
plotnine from the interpreter and seaborn for the executable. No more!!!
Many thanks!

**Comment by gilmarfrancisco828** [comment]
> I included this in `datas` in my .spec file and it fixed it. Modify as needed and give it a shot.
> 
> `("C:\\Users\\rwardrup\\anaconda3\\envs\\TEST\\Lib\site-packages\\palettable\\colorbrewer\\data\\colorbrewer_all_schemes.json", "palettable\\colorbrewer\\data\\")`

BLESS YOU, it worked!!!²

**Comment by luis-vizcaya-vr** [comment]
Hi guys,
I am not sure if my computer has this palettable folder. How do you got it?

**Comment by davidsasso** [comment]
Hi guys I got the same problem but with pkg_resources instead.
Should I add this package to data list on spec file and then build the application?

Thanks.
