### ISSUE TITLE
dask.distributed support

### ISSUE THREAD

**Issue by janroden** [pyinstaller/pyinstaller#3929]
Hi, 
I'm trying to freeze a Python app that uses Dask.distributed with PyInstaller.

The not frozen version of the app runs fine. 
But the frozen version of the app crashes, showing the following error:
```
13:07:47,039 - STDERR - ERROR - Exception ignored in:
13:07:47,040 - STDERR - ERROR - <object repr() failed>
13:07:47,040 - STDERR - ERROR - Traceback (most recent call last):
13:07:47,040 - STDERR - ERROR -   File "C:\Users\...\dependencies_windows\Anaconda3\lib\site-packages\distributed\deploy\local.py", line 340, in __del__
13:07:47,041 - STDERR - ERROR - self.close()
13:07:47,041 - STDERR - ERROR -   File "C:\Users\...\dependencies_windows\Anaconda3\lib\site-packages\distributed\deploy\local.py", line 280, in close
13:07:47,041 - STDERR - ERROR - self.scheduler.clear_task_state()
13:07:47,041 - STDERR - ERROR - AttributeError
13:07:47,041 - STDERR - ERROR - :
13:07:47,041 - STDERR - ERROR - 'LocalCluster' object has no attribute 'scheduler'
```
The part of the app that uses Dask.distributed is of the form:
```python
from dask.distributed import Client

client = Client(processes=False)

futures = []
for i in range(10): 
    other_futures = [client.submit( crunch_1, some_input[i, j]) for j in range(10)]
    futures.append( client.submit( crunch_2, other_futures))

results = client.gather(futures)
```

Before adding the part using dask.distributed to the app, freezing with PyInstaller worked.

Platform: Windows 10, 64-bit 
Python: 3.6.7, 64-bit (Anaconda)
Dask.distributed: 1.25.0
PyInstaller: 3.4.dev0+ab8fd9753

I would appreciate any hints on how to make this work with PyInstaller. Thank you!

**Comment by htgoebel** [comment]
This looks like not all required modules are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by Jonnyb36** [comment]
This is an old issue, but I just got this working on Windows with the following...

Call ```multiprocessing.freeze_support()``` immediately within the top-level app.py file i.e.

```python
if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()
```
or as the first line in the first function.  I'm also using ```argparse``` so placed the freeze_support call before the argparse calls.  Some more info on [stackoverflow](https://stackoverflow.com/questions/47325297/compiling-executable-with-dask-or-joblib-multiprocessing-with-cython-results-in)

Add following additional data/packages to the pyinstaller build script:

```
--add-data "./.venv/Lib/site-packages/dask/dask.yaml;./dask/" `
--add-data "./.venv/Lib/site-packages/distributed;./distributed/" `
```

**Comment by IsaacUtah1379** [comment]
Are there any plans to officially support dask.distributed with PyInstaller?

**Comment by bwoodsend** [comment]
We don't *plan* to officially support anything. Either someone submits a patch or they don't. (In this case, it would only be possible to address the data collection issue – nothing we can do about `multiprocessing.freeze_support()`.)
