### ISSUE TITLE
PyInstaller cannot build module google.cloud.vision

### ISSUE THREAD

**Issue by neverlog** [pyinstaller/pyinstaller#3935]
My OS is windows 10
Python 3.6
PyInstaller 3.4

I cannot build the exe, my script have import as below:
from google.cloud import vision 
from google.cloud.vision import types

Error below occured when build..
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'google-cloud-core' distribution was not found and is required by the application.

I notice there is no hook-for this google cloud vision in the hook directory.

I have try to add in new hook-google.cloud.vision.py with
from PyInstaller.utils.hooks import copy_metadata

datas = copy_metadata('google-cloud-vision')
datas += copy_metadata('google-cloud-core')
datas += copy_metadata('google-api-core')

but still cannot built the exe. Please help. thank you.

Regards,
Neverlog

**Comment by neverlog** [comment]
Got it worked by reinstall the google-cloud-core!
Install Pyinstaller, then reinstall google-cloud-core!

**Comment by Jaha96** [comment]
It's worked me too. But after exe file generated. The program not working
Error below occurred when double click on the EXE file

> Traceback (most recent call last):
  File "image_version.py", line 27, in <module>
    from google.cloud import vision
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\envs\ocr_check_20191004\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\google\cloud\vision.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\envs\ocr_check_20191004\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\google\cloud\vision_v1\__init__.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\envs\ocr_check_20191004\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\google\cloud\vision_v1\gapic\image_annotator_client.py", line 39, in <module>
  File "site-packages\pkg_resources\__init__.py", line 481, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 357, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 900, in require
  File "site-packages\pkg_resources\__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'google-cloud-vision' distribution was not found and is required by the application
[21488] Failed to execute script image_version

**Comment by sammosummo** [comment]
I'm having the same issue, but with `google-cloud-texttospeech`. Presumably we need to add a "hook" but I don't know how to find the missing distribution(s).

**Comment by Jaha96** [comment]
I successfully compiled my script. I am going to add details of my approach for the future log. 
My OS is windows 10
Python 3.6.10 32bit
PyInstaller 3.6
google-cloud-vision      1.0.0

My script uses google vision API to detect texts from image.

My errors:
_____________________________________________________________________
**Error 1:** 
When I execute pyinstaller the error below occured
```
pkg_resources.DistributionNotFound: The 'google-cloud-core' distribution was not found and is required by the application.
```

Solution: I installed google-cloud-core package from pip.

_____________________________________________________________________
**Error 2:**
The pyinstaller execution finished successfully. But when I execute generated exe file I got error below:
```
pkg_resources.DistributionNotFound: The 'google-cloud-vision' distribution was not found and is required by the application
```

Solution: 

-  I created file called 'hook-google.cloud.vision.py' and saved into new folder. (In my case folder I named 'hooks')
'hook-google.cloud.vision.py' file contents is:
```
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('google-cloud-vision')
```

- When I run pyinstaller I linked to the newly created hooks file using _--additional-hooks-dir_ option

`pyinstaller --onefile --additional-hooks-dir ./hooks/ main.py`

**Comment by Yggy-creator** [comment]
Jaha96 thank you so much for your post. I finally have my app compiled and running!
That last line solved the issues! How did you find out what to do?
from PyInstaller.utils.hooks import copy_metadata, collect_data_files
datas = copy_metadata('google-cloud-vision')
datas += collect_data_files('grpc')

**Comment by viswas-dev** [comment]
> Jaha96 thank you so much for your post. I finally have my app compiled and running!
> That last line solved the issues! How did you find out what to do?
> from PyInstaller.utils.hooks import copy_metadata, collect_data_files
> datas = copy_metadata('google-cloud-vision')
> datas += collect_data_files('grpc')

Yggy-creator and Jaha96 I tried the procedure which you mentioned in the but not working for me , still the error google-cloud-translate distribution package not found persists
