### ISSUE TITLE
Fix for 'cannot find existing PyQt5 plugin directories'

### ISSUE THREAD

**Issue by wilc097** [pyinstaller/pyinstaller#3938]
Due to several compatibility issues I really wanted to make an executable file with the whole environment installed in Anaconda rather than some packages with pip. I use the following setup:

- Python 3.6
- Numpy 1.15.4
- Scipy 1.1.0
- Pyqt 5.9.2
- Matplotlib 3.0.2

Note that this is the highest pyqt version available in conda. However, this gave me the following error:

35374 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
36240 WARNING: Hidden import "PyQt5.sip" not found!
36325 WARNING: Unable to find Qt5 translations C:/qt64/qt_1544645195969/_h_env/Library/translations\qtbase_*.qm. These translations were not packaged.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\designtool\Scripts\pyinstaller-script.py", line 10, in <module>
    sys.exit(run())
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 42, in <module>
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtGui.py", line 11, in <module>
    hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 514, in add_qt5_dependencies
    more_binaries = qt_plugins_binaries(plugin, namespace=namespace)
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 132, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "C:\ProgramData\Anaconda3\envs\designtool\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 117, in qt_plugins_dir
    """.format(namespace, ", ".join(paths)))
Exception: 
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/qt64/qt_1544645195969/_h_env/Library/plugins

Due to the following fix, I was able to get it working:

Edit ~\anaconda3\Lib\site-packages\PyInstaller\utils\hooks\qt.py to the following:

 json_str = exec_statement("""
        import sys

        # exec_statement only captures stdout. If there are
        # errors, capture them to stdout so they can be displayed to the
        # user. Do this early, in case PyQt5 imports produce stderr
        # output.
        sys.stderr = sys.stdout

        import json
        from %s.QtCore import QLibraryInfo, QCoreApplication

        # QLibraryInfo isn't always valid until a QCoreApplication is
        # instantiated.
        app = QCoreApplication([])
        paths = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
        location = {x: QLibraryInfo.location(getattr(QLibraryInfo, x))
                    for x in paths}
        try:
            version = QLibraryInfo.version().segments()
        except AttributeError:
            version = None
        print(str(json.dumps({
            'isDebugBuild': QLibraryInfo.isDebugBuild(),
            'version': version,
            'location': location,
        })))
    """ % self.namespace)

I am not a developer or someone with very much understanding of the PyInstaller module, but I would highly recommend to include a fix like this in a coming version of PyInstaller.

**Comment by bjones1** [comment]
What version of PyInstaller are you using?

**Comment by wilc097** [comment]
Version 3.4, the one that is installed automatically on anaconda when
installing pyinstaller.

Op do 20 dec. 2018 17:54 schreef Bryan A. Jones <notifications@github.com:

**Comment by bjones1** [comment]
Try the [latest](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#getting-the-latest-version) -- the bug may be fixed there.

**Comment by wilc097** [comment]
I already tried later versions, but those only worked with pip, which gave
compatibility issues in other parts of the software.

Op do 20 dec. 2018 om 18:11 schreef Bryan A. Jones <notifications@github.com

**Comment by bjones1** [comment]
OK. I'm closing this since your patch is likely included in the latest version.

**Comment by cslycord** [comment]
I have the same problem. I'm also running anaconda with python3.6 and pyinstaller3.4.

When running pyinstaller, I receive:
`Exception:
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/qt64/qt_1544645195969/_h_env/Library/plugins`

Which means that it is not checking the conda libraries. 
On my installation, the plugins are located at `C:\Anaconda3\Library\plugins\PyQt5`. There is no `C:/qt64` directory that it pyinstaller looks for.

Also, I tried installing the development version as suggested above with "pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip" but that fails as well.

`  Getting requirements to build wheel ... error
  Complete output from command c:\anaconda3\python.exe c:\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py get_requires_for_build_wheel C:\Users\tony\AppData\Local\Temp\tmp9qmsjitd:
  Traceback (most recent call last):
    File "c:\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "c:\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\tony\AppData\Local\Temp\pip-build-env-fkxd6d9y\overlay\Lib\site-packages\setuptools\build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\tony\AppData\Local\Temp\pip-build-env-fkxd6d9y\overlay\Lib\site-packages\setuptools\build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "C:\Users\tony\AppData\Local\Temp\pip-build-env-fkxd6d9y\overlay\Lib\site-packages\setuptools\build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ModuleNotFoundError: No module named 'PyInstaller'`

**Comment by bjones1** [comment]
Use the latest dev version of PyInstaller -- this is hopefully fixed.

**Comment by cslycord** [comment]
I pointed out that the latest development version also fails to install...

**Comment by bjones1** [comment]
Use pip 18, or pip 19 with https://github.com/pypa/pip/issues/6163#issuecomment-456772043.

**Comment by htgoebel** [comment]
I really wonder how many developers are not able to see what is causing an error. I'm no longer wondering about the bad quality of software and the many vulnerabilities, though.
