### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'shadowsocks==2.8.2' distribution was not found and is 

### ISSUE THREAD

**Issue by hktalent** [pyinstaller/pyinstaller#3940]
mac os
```
$ cat make.sh
#!/usr/bin/env bash
# pip install pyinstaller shadowsocks
# ./make.sh src/ssserver-script.py macos
# ./make.sh src/ssserver-script.py linux

set +e
szFile="$1"
szDir="$2"
pyinstaller --hidden-import  shadowsocks --onefile $szFile
x=`ls dist/`
x2=`echo $x|sed 's/\-script//g'`
p=`rm -rf $szDir/$x2`
cp -f dist/$x $szDir/$x2
rm -rf "${x}.spec"
rm -rf dist build
chmod +x $szDir/*

 ./make.sh src/ssserver-script.py macos

$ ./macos/ssserver
Traceback (most recent call last):
  File "ssserver-script.py", line 9, in <module>
  File "pkg_resources/__init__.py", line 484, in load_entry_point
  File "pkg_resources/__init__.py", line 476, in get_distribution
  File "pkg_resources/__init__.py", line 352, in get_provider
  File "pkg_resources/__init__.py", line 895, in require
  File "pkg_resources/__init__.py", line 781, in resolve
pkg_resources.DistributionNotFound: The 'shadowsocks==2.8.2' distribution was not found and is required by the application
[31677] Failed to execute script ssserver-script

```

**Comment by htgoebel** [comment]
Looks like you need to create a hook which runs `copy_metadata()`, see e.g. PyInstaller/hooks/hook-distutils.py. I'd appreciate a pull-request for the hook :-)

**Comment by hktalent** [comment]
@htgoebel thanks
collection default build
