### ISSUE TITLE
Pyinstaller fails when attempting to build exe with icon

### ISSUE THREAD

**Issue by samRiderS** [pyinstaller/pyinstaller#3944]
Keep getting an issue with pyinstalled and building and exe with onfile while attempting to specify icon.
It looks to be a bug, but maybe I am missing something. I am able to build the exe without specifying the icon.

Command that fails: pyinstaller --onefile --icon="myicon.ico" myproj.py
Building without the icon will work and build the exe

When attempting to build an exe out of a project using --icon, pyinstaller throws error:

46 INFO: PyInstaller: 3.4
47 INFO: Python: 3.7.2
47 INFO: Platform: Windows-10-10.0.17134-SP0
77 INFO: wrote H:\docs\myproj.spec
79 INFO: UPX is not available.
80 INFO: Extending PYTHONPATH with paths
['H:\\docs', 'H:\\docs']
80 INFO: checking Analysis
93 INFO: checking PYZ
102 INFO: checking PKG
104 INFO: Bootloader c:\python37\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
104 INFO: checking EXE
104 INFO: Building EXE because EXE-00.toc is non existent
105 INFO: Building EXE from EXE-00.toc
108 INFO: SRCPATH [('myicon.ico', None)]
108 INFO: Updating icons from ['myicon.ico'] to C:\Users\USER\AppData\Local\Temp\tmpttqym5n1
Traceback (most recent call last):
  File "C:\Python37\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "c:\python37\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python37\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 32, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\building\api.py", line 433, in __init__
    self.__postinit__()
  File "c:\python37\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\python37\lib\site-packages\PyInstaller\building\api.py", line 522, in assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "c:\python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 177, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "c:\python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 134, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "c:\python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 104, in __init__
    entry.fromfile(file)
  File "c:\python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 65, in fromfile
    self._fields_ = list(struct.unpack(self._format_, data))
struct.error: unpack requires a buffer of 16 bytes

**Comment by htgoebel** [comment]
Please verify the icon file is not corrupt. Try a different icon file. Try recreating the icon file. If everything else fails attach the icon file here.

**Comment by aoloe** [comment]
the following command:

```
pyinstaller --onefile --windowed --icon assets\zahlen_und_code.icn main.py
```
fails for me with the following files:

[assets.zip](https://github.com/pyinstaller/pyinstaller/files/3249140/assets.zip)

the error is:

```
C:\Users\ale\src\py-zahlen-und-codes>pyinstaller --onefile --windowed --icon assets\zahlen_und_code.icn main.py
46 INFO: PyInstaller: 3.4
46 INFO: Python: 3.7.3
46 INFO: Platform: Windows-10-10.0.17134-SP0
46 INFO: wrote C:\Users\ale\src\py-zahlen-und-codes\main.spec
46 INFO: UPX is not available.
46 INFO: Extending PYTHONPATH with paths
['C:\\Users\\ale\\src\\py-zahlen-und-codes',
 'C:\\Users\\ale\\src\\py-zahlen-und-codes']
46 INFO: checking Analysis
109 INFO: checking PYZ
124 INFO: checking PKG
171 INFO: Bootloader c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
171 INFO: checking EXE
171 INFO: Rebuilding EXE-00.toc because main.exe missing
171 INFO: Building EXE from EXE-00.toc
234 INFO: SRCPATH [('assets\\zahlen_und_code.icn', None)]
234 INFO: Updating icons from assets\zahlen_und_code.icn to C:\Users\ale\AppData\Local\Temp\tmp_wkshutd
Traceback (most recent call last):
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 42, in check_null
    raise make_error(function, function_name)
OSError: [WinError 2] The system cannot find the file specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 189, in CopyIcons
    hsrc = win32api.LoadLibraryEx(srcpath, 0, LOAD_LIBRARY_AS_DATAFILE)
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "c:\users\ale\appdata\local\programs\python\python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (2, 'LoadLibraryExW', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ale\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ale\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ale\AppData\Local\Programs\Python\Python37\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 32, in <module>
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\api.py", line 433, in __init__
    self.__postinit__()
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\api.py", line 522, in assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "c:\users\ale\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 190, in CopyIcons
    except win32api.error as W32E:
AttributeError: module 'win32ctypes.pywin32.win32api' has no attribute 'error'
```

**Comment by aoloe** [comment]
it might be related to the files.

i went to an icons creating sites (https://icoconvert.com/), created an .ico and what i got did work with pyinstaller...

**Comment by gainskills** [comment]
@aoloe , could you please share which size of the ico file you selected?
Thanks,

**Comment by aoloe** [comment]
sorry, i have no experience with icon files...

if i try to use the `.icn` file in the zip file as such i get the error above.  
it might be that that file is in the wrong format or that i'm using the wrong parameters...

if i get an `.ico` file from the site linked above it all works correctly.  
i don't know anymore which size i've used. sorry.

if i'm not supposed to use the `.icn` file (or that there are different types of `.icn` files and only some of them are compatible / usable as icons for exes), it would be nice to have abetter error message...

**Comment by JMSwag** [comment]
Hey, @aoloe Just an FYI.

Mac: icon.icns
Windows: icon.ico

**Comment by gainskills** [comment]
@aoloe , thanks for the details. I tried 48*48 (.ico) and works.
---
as an addition, I also notified that it seemed that the issue of my PC (OS: win2012R2), the icon shown as the old one on my one, but it shown as the new one on another pc.

**Comment by htgoebel** [comment]
Stale since long, closing.

**Comment by alxizr** [comment]
Hi, 
I am encountering the same issue, 
If i am changing the default build and dist folders and include an **ico** icon file then the build exe file fails. I tested all the sizes from 32 to 512 and its all the same.

this is where i got the icon file from: [https://icon-icons.com/](url)
**I will repeat again - if i leave the default build and dist folders it works but if i change it then it fails**. Thanks

**Comment by fabiangeisler** [comment]
Hello,

I got the same issue and I think this happens when a png is hiding inside the ico file (which is a possibility according to wikipedia). I could fix it by saving my icon as a bmp and then back as an ico with XnView. After that building went just fine. Hope that helps someone in the future.

**Comment by ectoanonymous** [comment]
I'm facing the same issue, earlier it was working fine, but now it keeps saying "unable to open icon file icon_name.ico" where icon_name is my icon name.

**Comment by JRitmeester** [comment]
Also had this problem. A build earlier today worked fine, now it gets hung up on the icon. Builds fine if I leave out the --icon option.

**Comment by LcyDev** [comment]
This is also happening to me and along other errors with my automatized script it's driving me insane.

**Comment by Breakthrough** [comment]
This also started failing for me on PyInstaller 5.0, but works fine on 4.10.

**Comment by bwoodsend** [comment]
> This also started failing for me on PyInstaller 5.0, but works fine on 4.10.

You're more likely being hit by #6759.

**Comment by Breakthrough** [comment]
@bwoodsend ah good catch, you are correct (my apologies, I misinterpreted the error message).  Thanks for letting me know!
