### ISSUE TITLE
Windows: Build with --onedir fails

### ISSUE THREAD

**Issue by YakDriver** [pyinstaller/pyinstaller#3977]
### Build scenario
* Windows Server 2016
* Python 3.7
* PyInstaller 3.4
* `pipenv`
* Extremely simple [test app](https://github.com/YakDriver/gravitybee/tree/dev/tests/gbtestapp/src/gbtestapp)
* `--onedir` mode (everything works fine as one file)

### Arguments
I'm using `subprocess.run()` to execute PyInstaller with these arguments:

```python
args = ['pyinstaller', '--noconfirm', '--onedir', '--debug', '--name', 'gbtestapp-4.2.6-standalone-windows-amd64', '--paths', 'src', '--additional-hooks-dir', '.gravitybee\\build\\a2adbb0a14e711e9', '--specpath', '.gravitybee\\build\\a2adbb0a14e711e9', '--workpath', '.gravitybee\\build\\a2adbb0a14e711e9\\build', '--distpath', '.gravitybee\\build\\a2adbb0a14e711e9\\dist', '--hidden-import', 'gbtestapp', '--hidden-import', 'packaging.specifiers', '--hidden-import', 'configparser', '--hidden-import', 'html.parser', '--hidden-import', 'packaging.version', '--hidden-import', 'pkg_resources', '--hidden-import', 'packaging', '.gravitybee\\build\\a2adbb0a14e711e9\\a8f700d214e711e9_gbtestapp.py']
subprocess.run(args)
```

### Expected Result
Builds without error, producing a `onedir` application.

### Actual Result
PyInstaller exits with `returncode=1` and this Traceback:

```
Traceback (most recent call last):
  File "c:\program files\python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\.virtualenvs\gravitybee-RyiVgZ9C\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\.virtualenvs\gravitybee-ryivgz9c\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\administrator\.virtualenvs\gravitybee-ryivgz9c\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\administrator\.virtualenvs\gravitybee-ryivgz9c\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\administrator\.virtualenvs\gravitybee-ryivgz9c\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\users\administrator\.virtualenvs\gravitybee-ryivgz9c\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\users\administrator\.virtualenvs\gravitybee-ryivgz9c\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\administrator\.virtualenvs\gravitybee-ryivgz9c\lib\site-packages\PyInstaller\building\build_main.py", line 595, in assemble
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):
  File "c:\users\administrator\.virtualenvs\gravitybee-ryivgz9c\lib\site-packages\PyInstaller\utils\misc.py", line 150, in compile_py_files
    with open(obj_fnm, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\.virtualenvs\\gravitybee-RyiVgZ9C\\Scripts\\pyinstaller.exe\\__main__.pyo'
```

PyInstaller seems to be looking in the wrong location for `__main__.pyo`. 

It is *not* located here:

```
C:\\Users\\Administrator\\.virtualenvs\\gravitybee-RyiVgZ9C\\Scripts\\pyinstaller.exe\\__main__.pyo
```

It *is* located here:

```
C:\\Users\\Administrator\\.virtualenvs\\gravitybee-RyiVgZ9C\\Lib\\site-packages\\PyInstaller\\__main__.pyo
```

Perhaps this is related to where `pipenv` puts files but with all the same exact configuration (including `pipenv`), PyInstaller works fine in `--onefile` mode.

**Comment by htgoebel** [comment]
The easies way to sole this is not not run PyInstaller as a supbprcess. See <https://pyinstaller.readthedocs.io/en/latest/usage.html#running-pyinstaller-from-python-code>

**Comment by YakDriver** [comment]
@kbuc I was not able to get my code to run as indicated in the [docs](url
https://pyinstaller.readthedocs.io/en/latest/usage.html#running-pyinstaller-from-python-code) so I simply skipped the --onedir option on Windows and left it as a known bug.

**Comment by kbuc** [comment]
Well, it looks like fbs does not use --onedir at all, but still the path is wrong: 
\\winpy_envs\\qt5exe\\scripts\\pyinstaller.exe\\__main__.pyo

**Comment by YakDriver** [comment]
Not sure your exact situation, but [GravityBee](https://github.com/YakDriver/gravitybee) may work. It also uses PyInstaller but works for a single file executable on Windows at the moment.

**Comment by AndCycle** [comment]
this issue is still valid across windows version python 3.6/3.7 with stdlib venv environment.

**Comment by Enteee** [comment]
I am using a to pyinstaller 3.5 upgraded [docker-pyinstaller](https://github.com/cdrx/docker-pyinstaller) container ([docker hub](https://cloud.docker.com/u/enteee/repository/docker/enteee/pyinstaller-windows), [pull request](https://github.com/cdrx/docker-pyinstaller/pull/62)) and I do see the same issue. I don't really use any subprocesses but the container image starts pyinstaller with wine.

**Comment by suneelisk** [comment]
i am getting the same error but in the --onefile mode. can anyone help me with my pyinstaller error
