### ISSUE TITLE
UnboundLocalError: local variable 'features' referenced before assignment

### ISSUE THREAD

**Issue by blshkv** [pyinstaller/pyinstaller#3981]
Hi, I'm upgrading pyinstaller from 3.2 (it were no issues) and facing the following problem:

```
ebuild pyinstaller-3.4.ebuild manifest install 
>>> Creating Manifest for /var/db/overlays/pentoo-overlay/dev-python/pyinstaller
 * PyInstaller-3.4.tar.gz BLAKE2B SHA512 size ;-) ...                                                         [ ok ]
>>> Unpacking source...
>>> Unpacking PyInstaller-3.4.tar.gz to /var/tmp/portage/dev-python/pyinstaller-3.4/work
>>> Source unpacked in /var/tmp/portage/dev-python/pyinstaller-3.4/work
>>> Preparing source in /var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4 ...
 * python2_7: running distutils-r1_run_phase python_configure
CCFLAGS="-march=native -O2 -pipe -frecord-gcc-switches" LINKFLAGS="-march=native -O2 -pipe -frecord-gcc-switches -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0" "./waf" --prefix=/usr  --no-lsb configure
Setting top to                           : /var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader 
Setting out to                           : /var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/build 
Python Version                           : 2.7.15 (default, Dec 15 2018, 11:50:26) [GCC 7.3.0] 
Checking for 'gcc' (C compiler)          : x86_64-pc-linux-gnu-gcc 
Checking size of pointer                 : 8 
Platform                                 : Linux-64bit detected based on compiler 
Checking for flags -m64                  : yes 
Checking for program 'x86_64-pc-linux-gnu-strip' : /usr/bin/x86_64-pc-linux-gnu-strip 
Checking for program 'strip'                     : /usr/bin/x86_64-pc-linux-gnu-strip 
Checking for library dl                          : yes 
Checking for library m                           : yes 
Checking for library z                           : yes 
Checking for function unsetenv                   : yes 
Checking for function mkdtemp                    : yes 
Checking for flags -Wl,--as-needed               : yes 
'configure' finished successfully (0.641s)
 * python3_6: running distutils-r1_run_phase python_configure
CCFLAGS="-march=native -O2 -pipe -frecord-gcc-switches" LINKFLAGS="-march=native -O2 -pipe -frecord-gcc-switches -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0" "./waf" --prefix=/usr  --no-lsb configure
Setting top to                           : /var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader 
Setting out to                           : /var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/build 
Python Version                           : 3.6.5 (default, Dec 15 2018, 11:53:32) [GCC 7.3.0] 
Checking for 'gcc' (C compiler)          : x86_64-pc-linux-gnu-gcc 
Checking size of pointer                 : 8 
Platform                                 : Linux-64bit detected based on compiler 
Checking for flags -m64                  : yes 
Checking for program 'x86_64-pc-linux-gnu-strip' : /usr/bin/x86_64-pc-linux-gnu-strip 
Checking for program 'strip'                     : /usr/bin/x86_64-pc-linux-gnu-strip 
Checking for library dl                          : yes 
Checking for library m                           : yes 
Checking for library z                           : yes 
Checking for function unsetenv                   : yes 
Checking for function mkdtemp                    : yes 
Checking for flags -Wl,--as-needed               : yes 
'configure' finished successfully (0.728s)
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4 ...
 * python2_7: running distutils-r1_run_phase python_compile
"./waf" build_release --verbose --jobs=4
Waf: Entering directory `/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/build/release'
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Scripting.py", line 118, in waf_entry_point
    run_commands()
  File "/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Scripting.py", line 178, in run_commands
    ctx=run_command(cmd_name)
  File "/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Scripting.py", line 169, in run_command
    ctx.execute()
  File "/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Scripting.py", line 366, in execute
    return execute_method(self)
  File "/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Build.py", line 93, in execute
    self.execute_build()
  File "/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Build.py", line 96, in execute_build
    self.recurse([self.run_dir])
  File "/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/.waf-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/var/tmp/portage/dev-python/pyinstaller-3.4/work/PyInstaller-3.4/bootloader/wscript", line 785, in build
    features=features)
UnboundLocalError: local variable 'features' referenced before assignment
```

Do let me know if you need more details

**Comment by blshkv** [comment]
my bad, problem was on my side
