### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEImHg8uh/django/contrib/auth/password_validation.pyc

### ISSUE THREAD

**Issue by leoluopy** [pyinstaller/pyinstaller#3990]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fd66513ef28>
Traceback (most recent call last):
  File "django/utils/autoreload.py", line 225, in wrapper
  File "/tmp/_MEImHg8uh/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "django/utils/autoreload.py", line 248, in raise_last_exception
  File "django/core/management/__init__.py", line 337, in execute
  File "django/utils/autoreload.py", line 225, in wrapper
  File "django/__init__.py", line 24, in setup
  File "django/apps/registry.py", line 112, in populate
  File "django/apps/config.py", line 198, in import_models
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/leo/.local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "django/contrib/auth/models.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/leo/.local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "django/contrib/auth/base_user.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/leo/.local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "django/contrib/auth/password_validation.py", line 160, in <module>
  File "django/contrib/auth/password_validation.py", line 170, in CommonPasswordValidator
  File "pathlib.py", line 1109, in resolve
  File "pathlib.py", line 330, in resolve
  File "pathlib.py", line 315, in _resolve
  File "pathlib.py", line 422, in readlink
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEImHg8uh/django/contrib/auth/password_validation.pyc'

**Comment by leoluopy** [comment]
do any body meet this problem ？ after packing the django program

**Comment by leoluopy** [comment]
i solved this problem by set the version of django at 2.0 . my packing command is :
`
pyinstaller -F manage.py  --hidden-import django --hidden-import rest_framework --hidden-import rest_framework.apps  --hidden-import redis --hidden-import rest_framework.parsers --distpath ./
`
