### ISSUE TITLE
Pyinstaller errors while compiling django application

### ISSUE THREAD

**Issue by NissanAloni** [pyinstaller/pyinstaller#4005]
I'm trying to compile a django application that uses channels 2.1.5 package.

When I run Pyinstaller I get the following errors and I would like to understand what they mean and how to fix them.

35655 INFO: Import to be excluded not found: 'tkinter'
35655 INFO: Loading module hook "hook-django.db.backends.py"...
36962 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
36963 INFO: Loading module hook "hook-django.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "c:\users\nissan\anaconda3\lib\site-packages\django\contrib\gis\admin\__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "c:\users\nissan\anaconda3\lib\site-packages\django\contrib\gis\admin\options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "c:\users\nissan\anaconda3\lib\site-packages\django\contrib\gis\admin\widgets.py", line 3, in <module>
    from django.contrib.gis.gdal import GDALException
  File "c:\users\nissan\anaconda3\lib\site-packages\django\contrib\gis\gdal\__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "c:\users\nissan\anaconda3\lib\site-packages\django\contrib\gis\gdal\datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "c:\users\nissan\anaconda3\lib\site-packages\django\contrib\gis\gdal\driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "c:\users\nissan\anaconda3\lib\site-packages\django\contrib\gis\gdal\prototypes\ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "c:\users\nissan\anaconda3\lib\site-packages\django\contrib\gis\gdal\libgdal.py", line 43, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal202", "gdal201", "gdal20", "gdal111", "gdal110", "gdal19"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
39231 INFO: Determining a mapping of distributions to packages...
129059 INFO: Packages required by django:
['pytz']
129059 INFO: Django root directory C:\git\CoreTigo_IOLWM_Gateway_WebApp\gateway\backend\src\cfehome
Traceback (most recent call last):
  File "c:\users\nissan\anaconda3\lib\site-packages\PyInstaller\utils\hooks\subproc\django_import_finder.py", line 37, in <module>
    list(settings.TEMPLATE_LOADERS) + \
  File "c:\users\nissan\anaconda3\lib\site-packages\django\conf\__init__.py", line 58, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'
131137 INFO: Collecting Django migration scripts.

Here's a summary of the warnings:

- 36962 WARNING: Hidden import "django.db.backends.pycache.base" not found!

- django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal202", "gdal201", "gdal20", "gdal111", "gdal110", "gdal19"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.

- AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'

Thanks.

**Comment by NissanAloni** [comment]
I've made some changes to django_import_finder.py
Attached the updated file.
First fix was based on the [following tip](https://gist.github.com/sadnoodles/ceb13afe8dfcf40e92adc0dfbafface2)

I'm not sure about the impact of these changes. But now the 3rd error changed.
Now I'm getting the same error during build time and run time of the EXE.
It seems like Pyinstaller is loading some piece of code that prevents from Daphne and channels module to load as part of Django.

This is the new message from the build log

120397 INFO: Django root directory C:\cfehome
c:\users\nissan\anaconda3\lib\site-packages\daphne\server.py:13: UserWarning: Something has already installed a **non-asyncio Twisted reactor**. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
  UserWarning,

**Comment by ghost** [comment]
你好，请问解决了吗？
