### ISSUE TITLE
exe file generated with Pyinstaller fails to execute

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#4011]
I just installed Pyinstaller on a virtual machine, windows 10 x64 build via pip 18.1. I compiled my script successfully, but each time I attempt to run it I get an error saying failed to execute filename.

Here are the logs, can anyone please help explain how to fix this?
C:\Users\user\Desktop\Windows\dist>Macro.exe
Traceback (most recent call last):
  File "Windows\Macro.py", line 11, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "Windows\config\manage_modules.py", line 55, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "Windows\softwares\windows\ppypykatz.py", line 10, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\pypykatz\pypykatz.py", line 1, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\pypykatz\commons\common.py", line 9, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\minidump\streams\__init__.py", line 12, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\minidump\streams\MiscInfoStream.py", line 10, in <module>
AttributeError: 'module' object has no attribute 'IntFlag'
[3732] Failed to execute script Macro

How do I give it

**Comment by htgoebel** [comment]
>  File "build\bdist.win32\egg\minidump\streams\MiscInfoStream.py", line 10, in
AttributeError: 'module' object has no attribute 'IntFlag'

This raceback is incomplete. I assume the missing line will tell you the reason.
