### ISSUE TITLE
Hi, I was working on the tutorial on https://github.com/mherrmann/fbs-tutorial

### ISSUE THREAD

**Issue by fionasoon1** [pyinstaller/pyinstaller#4016]
I was trying on this tutorial to package a py file using fbs (https://github.com/mherrmann/fbs-tutorial) but i found the following error. Can someone help please? Thanks.

C:>fbs freeze
Traceback (most recent call last):
File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\FIONA SOON\AppData\Local\Programs\Python\Python36\Scripts\fbs.exe_main.py", line 9, in 
File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs_main.py", line 17, in main
fbs.cmdline.main()
File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\cmdline.py", line 32, in main
fn(*args)
File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\builtin_commands_init.py", line 113, in freeze
freeze_windows(debug=debug)
File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\freeze\windows.py", line 22, in freeze_windows
_add_missing_dlls()
File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\freeze\windows.py", line 53, in _add_missing_dlls
) from None
FileNotFoundError: Could not find msvcr100.dll on your PATH. Please install the Visual C++ Redistributable for Visual Studio 2012 from:
https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by fionasoon1** [comment]
I was trying on this tutorial to package a py file using fbs (https://github.com/mherrmann/fbs-tutorial) but i found the following error. Can someone help please? Thanks.

C:\>fbs freeze
Traceback (most recent call last):
  File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\FIONA SOON\AppData\Local\Programs\Python\Python36\Scripts\fbs.exe\__main__.py", line 9, in <module>
  File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\builtin_commands\__init__.py", line 113, in freeze
    freeze_windows(debug=debug)
  File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\freeze\windows.py", line 22, in freeze_windows
    _add_missing_dlls()
  File "c:\users\fiona soon\appdata\local\programs\python\python36\lib\site-packages\fbs\freeze\windows.py", line 53, in _add_missing_dlls
    ) from None
FileNotFoundError: Could not find msvcr100.dll on your PATH. Please install the Visual C++ Redistributable for Visual Studio 2012 from:
    https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by fionasoon1** [comment]
Yes. I did installed the VC++ Redistrubted for VS 2012. I have version 2012, 2013 and 2015 installed too, Not sure if that cause confusion to the software..

 But , it didn't work.  May want to try on another laptop and see.

**Comment by fionasoon1** [comment]
ase1590>> I think you are right. It is the fbs problem.
I have use the pyinstaller directly and it works to package.

C:\Users\FIONA SOON>cd desktop\file creator

C:\Users\FIONA SOON\Desktop\file creator>pyinstaller gui4.py

**Comment by htgoebel** [comment]
> I was trying on this tutorial to package a py file using fbs (https://github.com/mherrmann/fbs-tutorial) 

If you have problems with this tutorial I suggest o ask there. Thanks for wasting my spare time.
