### ISSUE TITLE
No module named '_struct'

### ISSUE THREAD

**Issue by kanryu** [pyinstaller/pyinstaller#4027]
I'm using python3.7.1 on msys2-amd64, and make exe with pyinstaller 3.4

Although the build of exe succeeds, it fails to start by failing to import the standard library when executed.

spec:

```python
block_cipher = None
a = Analysis(['symlabel.py'],
             pathex=['C:\\Home\\src\\symlabel2'],
             binaries=[],
             datas=[],
             hiddenimports=['resource', '_datetime', '_pickle', 'posix', 'unicodedata', '_multibytecodec', '_json', '_socket', 
              '_struct', 'struct', 'sbpl',  'freetype', 'cpython' ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='symlabel',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='symlabel')
```

Build log:

```
$ pyinstaller symlabel.spec -F --hiddenimport _struct --hiddenimport struct
142 INFO: PyInstaller: 3.4
142 INFO: Python: 3.7.1
142 INFO: Platform: Windows-10-10.0.17134-SP0
145 INFO: UPX is not available.
147 INFO: Extending PYTHONPATH with paths
['C:\\Home\\src\\symlabel2', 'C:\\Home\\src\\symlabel2']
147 INFO: checking Analysis
147 INFO: Building Analysis because Analysis-00.toc is non existent
147 INFO: Initializing module dependency graph...
151 INFO: Initializing module graph hooks...
153 INFO: Analyzing base_library.zip ...
3151 INFO: Analyzing hidden import 'sbpl'
3449 INFO: Analyzing hidden import 'cpython'
3450 ERROR: Hidden import 'cpython' not found
3451 INFO: running Analysis Analysis-00.toc
3454 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Home\local\msys64\mingw64\bin\python3.exe
3588 INFO: Caching module hooks...
3593 INFO: Analyzing symlabel.py
3599 INFO: Loading module hooks...
3599 INFO: Loading module hook "hook-encodings.py"...
3740 INFO: Loading module hook "hook-pydoc.py"...
3741 INFO: Loading module hook "hook-xml.py"...
3956 INFO: Looking for ctypes DLLs
3969 INFO: Analyzing run-time hooks ...
3974 INFO: Looking for dynamic libraries
3974 INFO: Looking for eggs
3975 INFO: Using Python library C:\Home\local\msys64\mingw64\bin\libpython3.7m.dll
3975 INFO: Found binding redirects:
[]
3988 INFO: Warnings written to C:\Home\src\symlabel2\build\symlabel\warn-symlabel.txt
4024 INFO: Graph cross-reference written to C:\Home\src\symlabel2\build\symlabel\xref-symlabel.html
4046 INFO: checking PYZ
4046 INFO: Building PYZ because PYZ-00.toc is non existent
4047 INFO: Building PYZ (ZlibArchive) C:\Home\src\symlabel2\build\symlabel\PYZ-00.pyz
4600 INFO: Building PYZ (ZlibArchive) C:\Home\src\symlabel2\build\symlabel\PYZ-00.pyz completed successfully.
4611 INFO: checking PKG
4612 INFO: Building PKG because PKG-00.toc is non existent
4612 INFO: Building PKG (CArchive) PKG-00.pkg
4632 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
4637 INFO: Bootloader C:\Home\local\msys64\mingw64\lib\python3.7\site-packages\pyinstaller-3.4-py3.7.egg\PyInstaller\bootloader\Windows-64bit\run_d.exe
4637 INFO: checking EXE
4638 INFO: Building EXE because EXE-00.toc is non existent
4641 INFO: Building EXE from EXE-00.toc
4642 INFO: Appending archive to EXE C:\Home\src\symlabel2\build\symlabel\symlabel.exe
4663 INFO: Building EXE from EXE-00.toc completed successfully.
4670 INFO: checking COLLECT
4670 INFO: Building COLLECT because COLLECT-00.toc is non existent
4671 INFO: Building COLLECT COLLECT-00.toc
4844 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

Runtime log:

```
$ dist/symlabel/symlabel
[8648] PyInstaller Bootloader 3.x
[8648] LOADER: executable is C:\Home\src\symlabel2\dist\symlabel\symlabel.exe
[8648] LOADER: homepath is C:\Home\src\symlabel2\dist\symlabel
[8648] LOADER: _MEIPASS2 is NULL
[8648] LOADER: archivename is C:\Home\src\symlabel2\dist\symlabel\symlabel.exe
[8648] LOADER: No need to extract files to run; setting extractionpath to homepath
[8648] LOADER: SetDllDirectory(C:\Home\src\symlabel2\dist\symlabel)
[8648] LOADER: Already in the child - running user's code.
[8648] LOADER: Python library: C:\Home\src\symlabel2\dist\symlabel\libpython3.7m.dll
[8648] LOADER: Loaded functions from Python library.
[8648] LOADER: Manipulating environment (sys.path, sys.prefix)
[8648] LOADER: sys.prefix is C:\Home\src\symlabel2\dist\symlabel
[8648] LOADER: Pre-init sys.path is C:\Home\src\symlabel2\dist\symlabel\base_library.zip;C:\Home\src\symlabel2\dist\symlabel
[8648] LOADER: Setting runtime options
[8648] LOADER: Initializing python
[8648] LOADER: Overriding Python's sys.path
[8648] LOADER: Post-init sys.path is C:\Home\src\symlabel2\dist\symlabel\base_library.zip;C:\Home\src\symlabel2\dist\symlabel
[8648] LOADER: Setting sys.argv
[8648] LOADER: setting sys._MEIPASS
[8648] LOADER: importing modules from CArchive
[8648] LOADER: extracted struct
[8648] LOADER: callfunction returned...
[8648] mod is NULL - structTraceback (most recent call last):
  File "C:\Home\local\msys64\mingw64\lib\python3.7\struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
[8648] LOADER: extracted pyimod01_os_path
[8648] LOADER: callfunction returned...
[8648] LOADER: extracted pyimod02_archive
[8648] LOADER: callfunction returned...
[8648] mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "C:\Home\local\msys64\mingw64\lib\python3.7\site-packages\pyinstaller-3.4-py3.7.egg\PyInstaller\loader\pyimod02_archive.py", line 28, in <module>
    import struct
ModuleNotFoundError: No module named 'struct'
[8648] LOADER: extracted pyimod03_importers
[8648] LOADER: callfunction returned...
[8648] mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "C:\Home\local\msys64\mingw64\lib\python3.7\site-packages\pyinstaller-3.4-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 24, in <module>
    from pyimod02_archive import ArchiveReadError, ZlibArchiveReader
ModuleNotFoundError: No module named 'pyimod02_archive'
[8648] LOADER: Installing PYZ archive with Python modules.
[8648] LOADER: PYZ archive: PYZ-00.pyz
[8648] LOADER: Running pyiboot01_bootstrap.py
Traceback (most recent call last):
  File "site-packages\pyinstaller-3.4-py3.7.egg\PyInstaller\loader\pyiboot01_bootstrap.py", line 15, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[8648] Failed to execute script pyiboot01_bootstrap
[8648] LOADER: OK.
[8648] LOADER: Cleaning up Python interpreter.
```

**Comment by htgoebel** [comment]
There is no need for most of the modules you listed as hidden imports. Since e.g. `_strct` is not frozen even after you added it to hidden-imports, this is a clear sight your environment is mixed up. Please verify your setup using a *minimal* example.

**Comment by htgoebel** [comment]
BTW:
> pyinstaller symlabel.spec -F --hiddenimport _struct --hiddenimport struct

When passing a .spec-file, most other options are ignored.

**Comment by kanryu** [comment]
> There is no need for most of the modules you listed as hidden imports.
Of course, hiddenimport is empty in the spec file output first.
However, I set up this way because errors '_ struct' and 'struct' can not be found are logged at run time.

> this is a clear sight your environment is mixed up. Please verify your setup using a minimal example.
My PC also has multiple versions of Python processing system, both GCC and msvc, which are used separately.
I use python 3 and pip 3 of msys 2 to make it behave like Linux, but there was never a problem with installation of other modules so far.

However, pyinstaller 's setup.py had problems and it was necessary to install it manually because the automatic installation failed when executing pip3 command.

The environment acquisition process of your project clearly has problems. Please do not blame my PC.

**Comment by htgoebel** [comment]
Experience shows that this kind of errors are caused by some mixed up environment. If you had problems installing PyInstaller, this is another sign for issues with your environment.

**Comment by jrezai** [comment]
I have the same issue when attempting to run PyInstaller in MSYS2. I'm trying to create a Python3 GTK3+ executable (PyGObject), but I get this error when I attempt to run the executable:

>   File "C:/msys64/mingw64/lib/python3.7/struct.py", line 13, in <module>
>     from _struct import *
> ModuleNotFoundError: No module named '_struct'

I'm using the development version of PyInstaller. With version 3.4, I could not even get this far.

**Comment by jrezai** [comment]
Were you able to find a solution to this? Thanks.
