### ISSUE TITLE
PyInstaller 3.4 installation failed on windows 10 - 64bit

### ISSUE THREAD

**Issue by alimp5** [pyinstaller/pyinstaller#4032]
I checked below descriptions:

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

Greetings!
'''
PS C:\Users\linux10> pip install pyinstaller
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0c
c/PyInstaller-3.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command c:\python37\python.exe c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py ge
t_requires_for_build_wheel C:\Users\linux10\AppData\Local\Temp\tmpizpy5_3e:
  Traceback (most recent call last):
    File "c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\linux10\AppData\Local\Temp\pip-build-env-jqn7v_86\overlay\Lib\site-packages\setuptools\build_meta.py"
, line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\linux10\AppData\Local\Temp\pip-build-env-jqn7v_86\overlay\Lib\site-packages\setuptools\build_meta.py"
, line 101, in _get_build_requires
      _run_setup()
    File "C:\Users\linux10\AppData\Local\Temp\pip-build-env-jqn7v_86\overlay\Lib\site-packages\setuptools\build_meta.py"
, line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ModuleNotFoundError: No module named 'PyInstaller'

  ----------------------------------------
Command "c:\python37\python.exe c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py get_requires_for_build_w
heel C:\Users\linux10\AppData\Local\Temp\tmpizpy5_3e" failed with error code 1 in C:\Users\linux10\AppData\Local\Temp\pi
p-install-k3ovc536\pyinstaller\
PS C:\Users\linux10>
'''

**Comment by alimp5** [comment]
I checked below descriptions:

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

Greetings!
```
PS C:\Users\linux10> pip install pyinstaller
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0c
c/PyInstaller-3.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command c:\python37\python.exe c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py ge
t_requires_for_build_wheel C:\Users\linux10\AppData\Local\Temp\tmpizpy5_3e:
  Traceback (most recent call last):
    File "c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\linux10\AppData\Local\Temp\pip-build-env-jqn7v_86\overlay\Lib\site-packages\setuptools\build_meta.py"
, line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\linux10\AppData\Local\Temp\pip-build-env-jqn7v_86\overlay\Lib\site-packages\setuptools\build_meta.py"
, line 101, in _get_build_requires
      _run_setup()
    File "C:\Users\linux10\AppData\Local\Temp\pip-build-env-jqn7v_86\overlay\Lib\site-packages\setuptools\build_meta.py"
, line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ModuleNotFoundError: No module named 'PyInstaller'

  ----------------------------------------
Command "c:\python37\python.exe c:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py get_requires_for_build_w
heel C:\Users\linux10\AppData\Local\Temp\tmpizpy5_3e" failed with error code 1 in C:\Users\linux10\AppData\Local\Temp\pi
p-install-k3ovc536\pyinstaller\
PS C:\Users\linux10>
```

**Comment by PGAnonamous** [comment]
It has something to do with pip. For the meantime you can downgrade, install pyinstaller, and then re-upgrade pip.

`pip install pip==18.1`

**Comment by htgoebel** [comment]
@alimp5 Did you even look at the issues before posting? There is an issue pinned, and this is for some good reason. Thanks for wasting my spare time!

This is a pip issue. see #4007.
