### ISSUE TITLE
Installing development version from GitHub fails

### ISSUE THREAD

**Issue by ddzialak** [pyinstaller/pyinstaller#4035]
First step of template when reporting issue:

If you have problems to get your application running, please first

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

but it fails with:
```
dzialak@tad-38 ~/PycharmProjects/pyinstaller_bug $ mkvirtualenv py36 -p `which python3.6`
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /home/dzialak/.virtualenvs/py36/bin/python3.6
Also creating executable in /home/dzialak/.virtualenvs/py36/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
(py36) dzialak@tad-38 ~/PycharmProjects/pyinstaller_bug $ pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Downloading https://github.com/pyinstaller/pyinstaller/archive/develop.zip (4.1MB)
    100% |████████████████████████████████| 4.1MB 12.7MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/dzialak/.virtualenvs/py36/bin/python3.6 /home/dzialak/.virtualenvs/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5htzewj4:
  Traceback (most recent call last):
    File "/home/dzialak/.virtualenvs/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/dzialak/.virtualenvs/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/dzialak/.virtualenvs/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-2302obkg/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-2302obkg/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/tmp/pip-build-env-2302obkg/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ModuleNotFoundError: No module named 'PyInstaller'
  
  ----------------------------------------
Command "/home/dzialak/.virtualenvs/py36/bin/python3.6 /home/dzialak/.virtualenvs/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5htzewj4" failed with error code 1 in /tmp/pip-req-build-_djdxwkl

```

**Comment by htgoebel** [comment]
This is a pip issue. see #4007.
