### ISSUE TITLE
PyInstaller crashes trying to import resources from existing Windows EXE

### ISSUE THREAD

**Issue by gehlhaarPfizer** [pyinstaller/pyinstaller#4054]
Not sure if this is a PyInstaller issue, or a pywin32 issue.  The crash is happening in pywin32.

This is using PyInstaller 3.4, Python 3.6.8, pywin32-ctypes 0.2.0, pywin32 224; Windows 10

When trying to import resources from an existing executable with "-r", I get a crash. The resources are nothing peculiarly crazy; the original RC file (sanitized) is:

```
IDI_ICON1               ICON                    "icons\MVT.ico"
IDI_ICON2               ICON                    "icons\MVT_File.ico"

1 VERSIONINFO
 FILEVERSION 5,0,0,0
 PRODUCTVERSION 5,0,0,0
 FILEFLAGSMASK 0x3fL
#ifdef _DEBUG
 FILEFLAGS 0x1L
#else
 FILEFLAGS 0x0L
#endif
 FILEOS 0x4L
 FILETYPE 0x1L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName", "Company, Inc.\0"
            VALUE "LegalCopyright", "Copyright 2017 Company Inc."
            VALUE "FileDescription", "Application"
            VALUE "FileVersion", "5.0\0"
            VALUE "ProductVersion", "5.0\0"
            VALUE "InternalName", "Application\0"
            VALUE "OriginalFilename", "Application.exe\0"
            VALUE "ProductName", "Application\0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
```
Crash log as follows. It looks like pywin32-ctypes is having trouble decoding a resource name properly, generating a None that it then doesn't handle correctly.

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\win32ctypes\core\ctypes\_resource.py", line 41, in wrapped
    if IS_INTRESOURCE(name):
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\win32ctypes\core\ctypes\_common.py", line 44, in IS_INTRESOURCE
    return x >> 16 == 0
TypeError: unsupported operand type(s) for >>: 'NoneType' and 'int'
71812 ERROR: Error while updating resources in C:\Users\Gehlhaar\AppData\Local\Temp\1\tmpx1ae6zxr from resource file MOVITbase.exe
Traceback (most recent call last):
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 97, in EnumResourceNames
    hModule, resType, _resource.ENUMRESNAMEPROC(callback), 0)
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\win32ctypes\core\ctypes\_resource.py", line 73, in _EnumResourceNames
    _BaseEnumResourceNames(hModule, resource_type, lpEnumFunc, lParam)
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\win32ctypes\core\ctypes\_util.py", line 64, in check_false
    raise make_error(function, function_name)
OSError: [WinError 15106] User stopped resource enumeration.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\PyInstaller\building\api.py", line 544, in assemble
    [reslang or "*"])
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 256, in UpdateResourcesFromResFile
    UpdateResourcesFromDict(dstpath, res)
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 243, in UpdateResourcesFromDict
    type_, [name], [language])
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 183, in UpdateResources
    res = GetResources(dstpath, [type_], names, languages)
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 169, in GetResources
    res = _GetResources(hsrc, types, names, languages)
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 154, in _GetResources
    raise exception
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 125, in _GetResources
    enum_names = win32api.EnumResourceNames(hsrc, type_)
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 97, in EnumResourceNames
    hModule, resType, _resource.ENUMRESNAMEPROC(callback), 0)
  File "c:\home\gehlhaar\svn\all\3rdparty\windows_cl\python\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\home\gehlhaar\svn\all\3rdparty\Windows_cl\python\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (15106, 'EnumResourceNamesW', 'User stopped resource enumeration.')
```

**Comment by htgoebel** [comment]
This looks more like an error in your ressource-file or in win32ctypes. I suggest creating a small script which tries to read the resource using `PyInstaller.utils.win32.winresource.GetResources()` for investigating this further and tracking this down.

**Comment by gehlhaarPfizer** [comment]
I was able to "resolve" this by using a compiled resource file instead of an exe; however it's a lot clumsier because unlike the exe, you have to specify each resource you want to import. So now my build looks like this, and it's a lot more brittle, because every time I add a resource, I need to change this:

              -r APP.res,"Icon",1 \
              -r APP.res,"Icon",2 \
              -r APP.res,"Icon",3 \
              -r APP.res,"Icon",4 \
              -r APP.res,"Icon",5 \
              -r APP.res,"Icon",6 \
              -r APP.res,"Icon",7 \
              -r APP.res,"Icon",8 \
              -r APP.res,"Icon",9 \
              -r APP.res,"Icon",10 \
              -r APP.res,"Icon Group","IDI_ICON1" \
              -r APP.res,"Icon Group","IDI_ICON2" \
              -r APP.res,"Version Info",1 \

It would be VERY nice if there was options for .res files the same as .exe, e.g. automatically import all resources; or if a TYPE is specified, all coresponding NAME objects are updated.

**Comment by gehlhaarPfizer** [comment]
Bug filed against pywin32-ctypes here: https://github.com/enthought/pywin32-ctypes/issues/87

**Comment by htgoebel** [comment]
Thanks for file int bug report in the other project. They already provided a for, waiting four your response. Closing this issue.

**Comment by Legorooj** [comment]
Closing.
