### ISSUE TITLE
scikit-image 0.14.2 broke build (hook to update ?)

### ISSUE THREAD

**Issue by Overdrivr** [pyinstaller/pyinstaller#4061]
Our build pipeline recently broke due to scikit-image updated from 0.14.1 to 0.14.2.
With the new version, we get the following traceback when running pyinstaller's generated exe:

```
Traceback (most recent call last):
  File "nxt/nxt.py", line 5, in <module>
    from xxxxx.main import main as main_fn
  File "xxxxx/main.py", line 20, in init xxxxx.main
  File "xxxxx/preview.py", line 3, in init xxxxx.preview
  File "/root/.local/share/virtualenvs/xxxxx-dtfNOLzS/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/skimage/__init__.py", line 167, in <module>
  File "/root/.local/share/virtualenvs/xxxxx-dtfNOLzS/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/skimage/util/__init__.py", line 8, in <module>
  File "/root/.local/share/virtualenvs/xxxxx-dtfNOLzS/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/skimage/util/arraycrop.py", line 11, in <module>
  File "/root/.local/share/virtualenvs/xxxxx-dtfNOLzS/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "distutils/__init__.py", line 44, in <module>
ImportError: cannot import name 'dist'
```

Do you believe it's something to be fixed inside pyinstaller's hook or in scikit-image ?

**Comment by Overdrivr** [comment]
Nevermind, this was because we also removed the `--system` flag when installing dependencies with pipenv. Restoring the flag fixed it.

```
pipenv install --dev --system
```

Instead of 

```
pipenv install --dev
```

Sorry for the noise
