### ISSUE TITLE
Encode issue happened that PyInstaller failed to compile the Cython .so file, which is generated from the original source code

### ISSUE THREAD

**Issue by oscarriddle** [pyinstaller/pyinstaller#4074]
OS: CentOS7
Python: 3.6
Cython:0.29.5

Hi, I'm trying to compile the original python code to an executable file with hiding the source code.
My plan is to firstly convert the source code into a dynamic lib .so file by Cython, and then use the pyinstaller to compile the .so file into an executable file.

In the second step, I encountered the blow encoding error, which doesn't exists if I directly compile the source file to an executable file. So I start to wondering whether this procedure will somehow cause encoding issues?

```
101 INFO: checking Analysis
101 INFO: Building Analysis because Analysis-00.toc is non existent
101 INFO: Initializing module dependency graph...
103 INFO: Initializing module graph hooks...
104 INFO: Analyzing base_library.zip ...
3859 INFO: Analyzing hidden import 'PIL'
3905 INFO: Analyzing hidden import 'tensorflow'
5633 INFO: Processing pre-find module path hook   distutils
7207 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
7694 INFO: Processing pre-find module path hook   site
7694 INFO: site: retargeting to fake-dir '/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/fake-modules'
12428 INFO: Processing pre-safe import module hook   six.moves
31124 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
53154 INFO: running Analysis Analysis-00.toc
53177 INFO: Caching module hooks...
53181 INFO: Analyzing v3_server.cpython-36m-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/home/web_server/dlpy72/py3.6/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 241, in __init__
    self.__postinit__()
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 443, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 201, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1336, in run_script
    contents = fp.read() + '\n'
  File "/home/web_server/dlpy72/py3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 40: invalid continuation byte 
```

**Comment by ChristianGabs** [comment]
Hi,

I don't think will work like that, by documentation, it says clear ( .so, .dll ) they are binary. In your FIle.spec you can attach v3_server.cpython-36m-x86_64-linux-gnu.so as binary

```
Adding Binary Files
To add binary files, make a list of tuples that describe the files needed. Assign the list of tuples to the binaries= argument of Analysis.

Normally PyInstaller learns about .so and .dll libraries by analyzing the imported modules. Sometimes it is not clear that a module is imported; in that case you use a --hidden-import= command option. But even that might not find all dependencies.

Suppose you have a module special_ops.so that is written in C and uses the Python C-API. Your program imports special_ops, and PyInstaller finds and includes special_ops.so. But perhaps special_ops.so links to libiodbc.2.dylib. PyInstaller does not find this dependency. You could add it to the bundle this way:

a = Analysis(...
         binaries=[ ( '/usr/lib/libiodbc.2.dylib', 'libiodbc.dylib' ) ],
         ...
As with data files, if you have multiple binary files to add, create the list in a separate statement and pass the list by name.
```

So if you try to do like "pyinstaller file.so --onefile" will not work

My results there are same

```
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte

```

Hope this will help you to understand the pyinstaller must be pyx or py

Thanks

**Comment by oscarriddle** [comment]
Solved, only the libs are compiled to dynamic library files and then use the executable file to import it. My previous way is incorrect.
