### ISSUE TITLE
Word Cloud is not working 

### ISSUE THREAD

**Issue by AshishDhadwal** [pyinstaller/pyinstaller#4080]
I tried to create wordcloud using pyinstaller .In exe mode its throwing me an error
`sdf = rdf
comment_words = ' '
stopwords = set(STOPWORDS)
for val in sdf.Sentence:
        val = str(val)
    tokens = val.split()
    for i in range(len(tokens)):
        tokens[i] = tokens[i].lower()
    for words in tokens:
        comment_words = comment_words + words + ' '
wordcloud = WordCloud(width = 100, height = 100, 
            background_color ='grey', 
            stopwords = stopwords, 
            min_font_size = 5).generate(comment_words)
plt.figure(figsize = (8, 8), facecolor = None) 
plt.imshow(wordcloud) 
plt.axis("equal") 
plt.title('Word Cloud', bbox={'facecolor':'0.8', 'pad':4})

Exception in Tkinter callback
Traceback (most recent call last):
File "tkinter\__init__.py", line 1702, in __call__
File "TextTrics V1.0.4.py", line 71, in view_stats
File "visual.py", line 52, in show_visuals
File "wordcloud\wordcloud.py", line 605, in generate
File "wordcloud\wordcloud.py", line 587, in generate_from_text
File "wordcloud\wordcloud.py", line 426, in generate_from_frequencies
File "wordcloud\wordcloud.py", line 473, in generate_from_frequencies
File "PIL\ImageFont.py", line 261, in truetype
File "PIL\ImageFont.py", line 144, in __init__
OSError: cannot open resource`

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.
