### ISSUE TITLE
Google BigQuery Hook

### ISSUE THREAD

**Issue by andresmq35** [pyinstaller/pyinstaller#4083]
PyInstaller fails on google cloud big query import:

```
Traceback (most recent call last):
  File "send_version_info.py", line 2, in <module>
    from google.cloud import bigquery
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/andres/Development/cache-analytics/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "google/cloud/bigquery/__init__.py", line 33, in <module>
  File "pkg_resources/__init__.py", line 472, in get_distribution
  File "pkg_resources/__init__.py", line 344, in get_provider
  File "pkg_resources/__init__.py", line 892, in require
  File "pkg_resources/__init__.py", line 778, in resolve
pkg_resources.DistributionNotFound: The 'google-cloud-bigquery' distribution was not found and is required by the application
```

After fixing with hook file, it then fails on requests library required by big query:

```
Traceback (most recent call last):
  File "google/resumable_media/requests/__init__.py", line 665, in <module>
  File "pkg_resources/__init__.py", line 892, in require
  File "pkg_resources/__init__.py", line 778, in resolve
pkg_resources.DistributionNotFound: The 'requests>=2.18.0' distribution was not found and is required by the application

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "send_version_info.py", line 2, in <module>
    from google.cloud import bigquery
  File "/Users/andres/Development/cache-analytics/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "google/cloud/bigquery/__init__.py", line 35, in <module>
  File "/Users/andres/Development/cache-analytics/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "google/cloud/bigquery/client.py", line 32, in <module>
  File "/Users/andres/Development/cache-analytics/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "google/resumable_media/requests/__init__.py", line 673, in <module>
  File "<string>", line 3, in raise_from
ImportError: ``requests >= 2.18.0`` is required by the ``google.resumable_media.requests`` subpackage.
```

Will submit a pull request to fix.

**Comment by bwoodsend** [comment]
Fixed in #4084.
