### ISSUE TITLE
Pyinstaller：json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by QiPython** [pyinstaller/pyinstaller#4089]
I created an application with the help of pyinstaller,but it produced error. The program was simple and just used for testing, and worked fine with pycharm. 
But, when generated a executable application with pyinstaller,it gave the following traceback。

**(python 3.6;pyqt5 5.12; pyinstaller 3.4;Windows-7)**

**the program:**
# -*- coding: utf-8 -*-

import sys
from PyQt5.QtWidgets import QApplication, QPushButton, QColorDialog , QWidget
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QColor

class ColorDialog ( QWidget):
    def __init__(self ):
        super().__init__()
        color = QColor(0, 0, 0)
        self.setGeometry(300, 300, 350, 280)
        self.setWindowTitle('colorselection')
        self.button = QPushButton('Dialog', self)
        self.button.setFocusPolicy(Qt.NoFocus)
        self.button.move(20, 20)
        self.button.clicked.connect(self.showDialog)
        self.setFocus()
        self.widget = QWidget(self)
        self.widget.setStyleSheet('QWidget{background-color:%s} '%color.name())
        self.widget.setGeometry(130, 22, 100, 100)

    def showDialog(self):
        col = QColorDialog.getColor()
        if col.isValid():
            self.widget.setStyleSheet('QWidget {background-color:%s}'%col.name())

if __name__ == "__main__":
    app = QApplication(sys.argv)
    qb = ColorDialog()
    qb.show()
    sys.exit(app.exec_())

**traceback:**

80 INFO: PyInstaller: 3.4
81 INFO: Python: 3.6.0
81 INFO: Platform: Windows-7-6.1.7601-SP1
83 INFO: wrote C:\Users\Administrator\Desktop\c.spec
139 INFO: UPX is not available.
142 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Administrator\\Desktop', 'C:\\Users\\Administrator\\Desktop']
142 INFO: checking Analysis
142 INFO: Building Analysis because Analysis-00.toc is non existent
142 INFO: Initializing module dependency graph...
145 INFO: Initializing module graph hooks...
148 INFO: Analyzing base_library.zip ...
3637 INFO: running Analysis Analysis-00.toc
3661 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by c:\users\administrator\appdata\local\programs\python\python36\pyth
on.exe
4397 INFO: Caching module hooks...
4404 INFO: Analyzing C:\Users\Administrator\Desktop\c.py
4466 INFO: Loading module hooks...
4467 INFO: Loading module hook "hook-encodings.py"...
4568 INFO: Loading module hook "hook-pydoc.py"...
4569 INFO: Loading module hook "hook-PyQt5.py"...
4669 WARNING: Cannot read QLibraryInfo output: raised Expecting value: line 1 co
lumn 1 (char 0) when decoding:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\py
installer-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.3', 'console_scripts', 'pyinstaller')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\Administrator\Desktop\c.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\building\build_main.py", line 502, in assemble
    module_hook.post_graph()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\compat.py", line 792, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\hooks\hook-PyQt5.py", line 23, in <module>
    collect_system_data_files(pyqt5_library_info.location['PrefixPath'],
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\PyInstaller\utils\hooks\qt.py", line 70, in __getattr__
    qli = json.loads(json_str)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\json\_
_init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\json\d
ecoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\json\d
ecoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

So, what's wrong? I am new one for pyinstaller and Github. **Any help is appreciated!**

**Comment by QiPython** [comment]
I fix this problem with the help of [PyQt5 Cannot read QLibraryInfo output: raised Expecting value: line 1 column 1 (char 0) when decoding #3971](url). 

Though the standalone application is generated successfully, when the application is opened, the following error pop up in CMD and the exe is stopping working:

**Fatal Python error: Py_Initialize: unable to load the file system codec
LookupError: unknown encoding: utf-8

Current thread 0x00001a14 (most recent call first):**

what's wrong with it？

**Comment by QiPython** [comment]
For above problem，I referred [Py_Initialize: unable to load the file system codec LookupError: unknown encoding: utf-8 #3146](url) . But, it doesn't help，enum34 is not installed in my computer.
