### ISSUE TITLE
Error running the bin file in Linux，undefined symbol: PyUnicodeUCS2_Replace

### ISSUE THREAD

**Issue by VeblenXSYK** [pyinstaller/pyinstaller#4094]
development environment as follow:
```
486 INFO: PyInstaller: 3.4
488 INFO: Python: 2.7.13
491 INFO: Platform: Linux-3.8.13-bone70-armv7l-with-debian-7.8
```

when I exec the file, the error message out as follow:
```
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/tmp/pip-install-J1zAaU/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 22, in <module>
  File "/tmp/pip-install-J1zAaU/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "io.py", line 51, in <module>
  File "/tmp/pip-install-J1zAaU/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 684, in load_module
ImportError: /tmp/_MEIOmOsza/_io.so: undefined symbol: PyUnicodeUCS2_Replace
[10959] Failed to execute script pyi_rth_pkgres
```

Thanks in advance for your feedback!!!

**Comment by htgoebel** [comment]
Since `_io.so` is a standard module, this looks like the Python installation you used for freezing you application is somehow corrupted.

**Comment by VeblenXSYK** [comment]
I have two different static python version in debian system, one is python2.7.3 and the other one is python2.7.13. I don't know if this will have any effect

**Comment by htgoebel** [comment]
I can't tell you either :-)
