### ISSUE TITLE
Image ImportErrot DLL load failed

### ISSUE THREAD

**Issue by semgilo** [pyinstaller/pyinstaller#4097]
windows 7
pyinstaller 3.4

**### spec file content**
# -*- mode: python -*-
block_cipher = None
a = Analysis(['tools.py'],
             pathex=['E:\\git\\tools\\bin'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='tools',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='tools')

**### using shell code** 
E:\git\tools\bin>pyinstaller tools.spec
531 INFO: PyInstaller: 3.4
531 INFO: Python: 2.7.11
532 INFO: Platform: Windows-7-6.1.7601-SP1
541 INFO: UPX is not available.
546 INFO: Extending PYTHONPATH with paths
['E:\\git\\tools\\bin', 'E:\\git\\tools\\bin']
546 INFO: checking Analysis
546 INFO: Building Analysis because Analysis-00.toc is non existent
547 INFO: Initializing module dependency graph...
554 INFO: Initializing module graph hooks...
793 INFO: running Analysis Analysis-00.toc
805 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
1065 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
1066 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
1069 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
1069 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.7523_none_f47c924cf6585df6.manifest
1491 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30
729.7523_none ...
1493 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc
8b3b9a1e18e3b_9.0.30729.7523_none_508f21ccbcbbb7a8.manifest
1494 INFO: Searching for file msvcr90.dll
1495 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.30729.7523_none_508f21ccbcbbb7a8\msvcr90.dll
1495 INFO: Searching for file msvcp90.dll
1496 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.30729.7523_none_508f21ccbcbbb7a8\msvcp90.dll
1497 INFO: Searching for file msvcm90.dll
1498 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.30729.7523_none_508f21ccbcbbb7a8\msvcm90.dll
1904 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
1905 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
1907 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
1909 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.7523_none_f47c924cf6585df6.manifest
1911 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0,
 30729, 7523)
2404 INFO: Caching module hooks...
2414 INFO: Analyzing tools.py
8053 INFO: Processing pre-find module path hook   distutils
12974 INFO: Processing pre-safe import module hook   _xmlplus
20819 INFO: Loading module hooks...
20820 INFO: Loading module hook "hook-distutils.py"...
20822 INFO: Loading module hook "hook-sysconfig.py"...
20824 INFO: Loading module hook "hook-xml.py"...
20947 INFO: Loading module hook "hook-PIL.py"...
20948 INFO: Excluding import 'FixTk'
20951 INFO: Excluding import 'Tkinter'
20953 INFO: Excluding import 'PyQt5'
20955 INFO:   Removing import of PyQt5 from module PIL.ImageQt
20957 INFO: Excluding import 'PySide'
20958 INFO:   Removing import of PySide from module PIL.ImageQt
20958 INFO: Excluding import 'PyQt4'
20960 INFO:   Removing import of PyQt4 from module PIL.ImageQt
20961 INFO: Loading module hook "hook-httplib.py"...
20962 INFO: Loading module hook "hook-encodings.py"...
23619 INFO: Loading module hook "hook-_tkinter.py"...
24953 INFO: checking Tree
24953 INFO: Building Tree because Tree-00.toc is non existent
24954 INFO: Building Tree Tree-00.toc
25743 INFO: checking Tree
25744 INFO: Building Tree because Tree-01.toc is non existent
25744 INFO: Building Tree Tree-01.toc
25807 INFO: Loading module hook "hook-PIL.Image.py"...
27125 INFO: Loading module hook "hook-pkg_resources.py"...
28707 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
28710 INFO: Excluding import 'FixTk'
28711 INFO: Excluding import 'Tkinter'
28791 INFO: checking Tree
28792 INFO: Building Tree because Tree-02.toc is non existent
28793 INFO: Building Tree Tree-02.toc
28875 INFO: checking Tree
28876 INFO: Building Tree because Tree-03.toc is non existent
28876 INFO: Building Tree Tree-03.toc
29866 INFO: checking Tree
29866 INFO: Building Tree because Tree-04.toc is non existent
29868 INFO: Building Tree Tree-04.toc
29870 INFO: Looking for ctypes DLLs
29921 INFO: Analyzing run-time hooks ...
29927 INFO: Including run-time hook 'pyi_rth__tkinter.py'
29928 INFO: Including run-time hook 'pyi_rth_pkgres.py'
29945 INFO: Looking for dynamic libraries
30467 INFO: Looking for eggs
30467 INFO: Using Python library C:\Windows\system32\python27.dll
30467 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVers
ion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 7523), publicKeyToken=u'1fc8b3b9a
1e18e3b')]
30475 INFO: Warnings written to E:\git\tools\bin\build\tools\warn-tools.txt
30556 INFO: Graph cross-reference written to E:\git\tools\bin\build\tools\xref-t
ools.html
30941 INFO: checking PYZ
30941 INFO: Building PYZ because PYZ-00.toc is non existent
30942 INFO: Building PYZ (ZlibArchive) E:\git\tools\bin\build\tools\PYZ-00.pyz
31921 INFO: Building PYZ (ZlibArchive) E:\git\tools\bin\build\tools\PYZ-00.pyz c
ompleted successfully.
32036 INFO: checking PKG
32036 INFO: Building PKG because PKG-00.toc is non existent
32036 INFO: Building PKG (CArchive) PKG-00.pkg
32067 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
32072 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Wind
ows-32bit\run_d.exe
32072 INFO: checking EXE
32073 INFO: Building EXE because EXE-00.toc is non existent
32074 INFO: Building EXE from EXE-00.toc
32075 INFO: Appending archive to EXE E:\git\tools\bin\build\tools\tools.exe
32078 INFO: Building EXE from EXE-00.toc completed successfully.
32087 INFO: checking COLLECT
32088 INFO: Building COLLECT because COLLECT-00.toc is non existent
32089 INFO: Building COLLECT COLLECT-00.toc
32101 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30
729, 7523)
39728 INFO: Building COLLECT COLLECT-00.toc completed successfully.

**### running info:**
[8756] PyInstaller Bootloader 3.x
[8756] LOADER: executable is E:\git\tools\bin\dist\tools\tools.exe
[8756] LOADER: homepath is E:\git\tools\bin\dist\tools
[8756] LOADER: _MEIPASS2 is NULL
[8756] LOADER: archivename is E:\git\tools\bin\dist\tools\tools.exe
[8756] LOADER: No need to extract files to run; setting extractionpath to homepa
th
[8756] LOADER: SetDllDirectory(E:\git\tools\bin\dist\tools)
[8756] LOADER: Already in the child - running user's code.
[8756] LOADER: Python library: E:\git\tools\bin\dist\tools\python27.dll
[8756] LOADER: Loaded functions from Python library.
[8756] LOADER: Manipulating environment (sys.path, sys.prefix)
[8756] LOADER: sys.prefix is E:\git\tools\bin\dist\tools
[8756] LOADER: Setting runtime options
[8756] LOADER: Initializing python
[8756] LOADER: Overriding Python's sys.path
[8756] LOADER: Post-init sys.path is E:\git\tools\bin\dist\tools
[8756] LOADER: Setting sys.argv
[8756] LOADER: setting sys._MEIPASS
[8756] LOADER: importing modules from CArchive
[8756] LOADER: extracted struct
[8756] LOADER: callfunction returned...
[8756] LOADER: extracted pyimod01_os_path
[8756] LOADER: callfunction returned...
[8756] LOADER: extracted pyimod02_archive
[8756] LOADER: callfunction returned...
[8756] LOADER: extracted pyimod03_importers
[8756] LOADER: callfunction returned...
[8756] LOADER: Installing PYZ archive with Python modules.
[8756] LOADER: PYZ archive: PYZ-00.pyz
[8756] LOADER: Running pyiboot01_bootstrap.py
[8756] LOADER: Running pyi_rth__tkinter.py
[8756] LOADER: Running pyi_rth_pkgres.py
[8756] LOADER: Running tools.py
Traceback (most recent call last):
  File "tools.py", line 31, in <module>
    from PackageUtils import PackageUtils
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "PackageUtils.py", line 14, in <module>
    from ImageUtils import ImageUtils
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "ImageUtils.py", line 18, in <module>
    from PIL import Image, ImageDraw, ImageFont
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "PIL\Image.py", line 67, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "PIL\_imaging.py", line 7, in <module>
  File "PIL\_imaging.py", line 6, in __bootstrap__
ImportError: DLL load failed: 找不到指定的模块。
[8756] Failed to execute script tools
[8756] LOADER: OK.
[8756] LOADER: Cleaning up Python interpreter.

**Comment by semgilo** [comment]
upgrade pillow and it is fine.
