### ISSUE TITLE
Can't create package: FileNotFoundError: [Errno 2] No such file or directory: '-'

### ISSUE THREAD

**Issue by brycenaddison** [pyinstaller/pyinstaller#4127]
Using Python 3.7.2, and Pyinstaller 3.4, running on Windows 10.

This is one of the strangest errors I've seen. I have a project I can run through pipenv, but I want to package it as an exe so I can share it with people without them having to install pipenv. However, when I install pyinstaller and then run the pyinstaller command, I'm getting a weird error that includes a comment in the traceback:
```Traceback (most recent call last):
  File "C:\Users\Brycen\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Brycen\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Brycen\.virtualenvs\code-jam-4-IpGnem57\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
    # https://stackoverflow.com/questions/34363552/python-process-finished-with-exit-code-1-when-using-pycharm-and-pyqt5
  File "c:\users\brycen\.virtualenvs\code-jam-4-ipgnem57\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\brycen\.virtualenvs\code-jam-4-ipgnem57\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\brycen\.virtualenvs\code-jam-4-ipgnem57\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\brycen\.virtualenvs\code-jam-4-ipgnem57\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\users\brycen\.virtualenvs\code-jam-4-ipgnem57\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\users\brycen\.virtualenvs\code-jam-4-ipgnem57\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\brycen\.virtualenvs\code-jam-4-ipgnem57\lib\site-packages\PyInstaller\building\build_main.py", line 595, in assemble
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):
  File "c:\users\brycen\.virtualenvs\code-jam-4-ipgnem57\lib\site-packages\PyInstaller\utils\misc.py", line 150, in compile_py_files
    with open(obj_fnm, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '-'
```
In terms of the exact procedure, I installed pyinstaller as a developer package in the pipenv, and ran `pyinstaller --debug -i crocpad\crocpad.ico crocpad\__main__.py'. The file tree is attached below:
![Capture](https://user-images.githubusercontent.com/36745803/54404166-080d0880-46a9-11e9-8489-956828cf6433.PNG)
](url)
If you want to recreate this exact scenario, the repository of this project is https://github.com/syntaxaire/code-jam-4. 

This project has a settings file (notepad.ini) that is written and read in configuration.py. I know that I need to make the notepad.ini file outside the exe, but I can't really test that considering I can't build the exe in the first place, an error brought up by this should occur when running the exe with a FileNotFound error or something. 

Not really sure whats causing the error, and the error traceback isn't helping either.

**Comment by judge2020** [comment]
For me, this error was caused by importing from a folder without an `__init__.py` file (not a 'package') and only happens with `--debug=noarchive` or `--debug=all` (which includes `noarchive`).

```
from ui.launcher import Ui_MainWindow
```

Debugging [misc.py#L152](https://github.com/pyinstaller/pyinstaller/blob/6d4cce1f8eb80c0bf49d35876d28daa55a05800f/PyInstaller/utils/misc.py#L152) with the below changes on Python 3.7.8:
```diff
         needs_compile = mtime(src_fnm) > mtime(obj_fnm)
         if not needs_compile:
+            print(nm, fnm, typ)
             with open(obj_fnm, 'rb') as fh:
                 needs_compile = fh.read()[:4] != BYTECODE_MAGIC
```

![image](https://user-images.githubusercontent.com/8601934/88706242-989d8a80-d0de-11ea-8570-48c12ba932f9.png)

it's trying to compile `ui.pyc` but it isn't a module, so `fnm` is just a `-`. Creating an `__init__.py` module in the `ui` folder fixed this. See https://docs.python.org/3/tutorial/modules.html#packages

Going up the stack a bit, `path` is `-` in `self.pure` here as well:

https://github.com/pyinstaller/pyinstaller/blob/6d4cce1f8eb80c0bf49d35876d28daa55a05800f/PyInstaller/building/build_main.py#L486-L489

So I'm not sure where the root cause is, but maybe either a check for `-` or a try/except for FileNotFound error here is in order.

**Comment by bwoodsend** [comment]
See #4034.
