### ISSUE TITLE
sckit-cuda failing because of pkg_resources, but "What about pkg_resources" section doesn't point to relevant issue?

### ISSUE THREAD

**Issue by Cazadorro** [pyinstaller/pyinstaller#4129]
I've had an issue with pyinstaller not working with scikit-cuda, presumably because of the issue described [here](https://github.com/lebedov/scikit-cuda/issues/262).  It appears as if it is just impossible to use it with with pyinstaller, mainly because of the apparent[ `pkg_resources` issue](https://github.com/pyinstaller/pyinstaller/wiki/FAQ#misc).   I thought maybe I could help solve this problem or figure out a way around this, but instead of being brought to a relevant issue surrounding installer incompatibilities with pkg_resources, I was brought to this issue: https://github.com/pyinstaller/pyinstaller/issues/183 . Issue 183 apparently was caused by unrelated problems and since has been closed, that leaves py-installer with no direct issue calling pkg_resources a problem for pyinstaller.  Are these types of issues still caused by pkg_resources?  Since egg packaging doesn't work, what can I actually do to fix this? 

The actual error when ever I run is:

```
./main 
Traceback (most recent call last):
  File "my_project/main.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/myproject/envs/myproject/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "my_project/server_manager.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/myproject/envs/myproject/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "my_project/servers/server_name_table.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/myproject/envs/myproject/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "my_project/servers/daq_server.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/myproject/envs/myproject/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "my_project/servers/signal_processor_server.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/myproject/envs/myproject/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "pysoundaware/gpu/gpu.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/myproject/envs/myproject/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/skcuda/__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/myproject/envs/myproject/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/skcuda/version.py", line 2, in <module>
  File "site-packages/pkg_resources/__init__.py", line 900, in require
  File "site-packages/pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'scikit-cuda' distribution was not found and is required by the application
[28938] Failed to execute script main
```

**Comment by Cazadorro** [comment]
So I tried to use hooks, and that didn't seem to work, however scikit cuda module is not called scikit-cuda, it is called skcuda in python, in the version.py file which causes the error this is what I see:

```
import pkg_resources
__version__ = pkg_resources.require('scikit-cuda')[0].version
```

I'm not sure what pkg_resources is actually doing, or how I can create a hook that reconciles this is this some file located on path that it is trying to find?

**Comment by Cazadorro** [comment]
Okay I figured it out, I think I can submit a pull request soon, but basically I needed to copy the metadata name for scikit-cuda seen[ here ](https://pyinstaller.readthedocs.io/en/latest/hooks.html?highlight=pkg_resources)  I still think the documentation here should be updated to show that you don't need to use eggs to do this.

**Comment by Cazadorro** [comment]
fixed here: https://github.com/pyinstaller/pyinstaller/pull/4131#issue-262097179
