### ISSUE TITLE
RuntimeError: Should not import this directly, used by pubsub.core

### ISSUE THREAD

**Issue by leileigong** [pyinstaller/pyinstaller#4134]
Dear pyinstaller,
I've been trying to import the pubsub module but had problems with that...
My import is done like this :
```
try:
    from pubsub import pub
except ImportError:
    # wx.lib.pubsub is now deprecated may will be removed from wxpython 4.0.4 later.
    from wx.lib.pubsub import pub
```
I use hiddenimports like this:
`  hiddenimports=['wx', 'wx.adv', 'pubsub'],`

I run Pyinstaller, the the console print error message:
```
27583 INFO: Loading module hook "hook-pubsub.core.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "c:\users\lei\.virtualenvs\testtool-gkaj8wo0\lib\site-packages\pubsub\core\arg1\__init__.py", line 16, in <module>
    raise RuntimeError(msg)
RuntimeError: Should not import this directly, used by pubsub.core if applicable
27828 WARNING: Hidden import "pubsub.core.topicargspecimpl" not found!
27829 WARNING: Hidden import "pubsub.core.publishermixin" not found!
27832 WARNING: Hidden import "pubsub.core.listenerimpl" not found!
27878 WARNING: Hidden import "pubsub.core.topicmgrimpl" not found!
27879 WARNING: Hidden import "pubsub.core.datamsg" not found!
27881 WARNING: Hidden import "pubsub.core.publisher" not found!
```

I run the exe packaged by PyInstaller, it complains that :
```
Traceback (most recent call last):
  File "ClientWin.py", line 26, in <module>
    from wx.lib.pubsub import pub
  File "c:\users\lei\appdata\local\temp\pip-install-zqjb3d\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "site-packages\wx\lib\pubsub\__init__.py", line 41, in <module>
ImportError: Stand-alone pubsub not found. Use `pip install PyPubSub`
[29616] Failed to execute script 
```

**Comment by ntirupathirao18** [comment]
May be hook file is not created for it

**Comment by bwoodsend** [comment]
Looks like your environment is not the same as your PyInstaller one.

- Activate your virtual env.
- `pip install pyinstaller`
- `pip install PyPubSub`
- Verify your code works with `python your_code.py`
- Build it with `python -m PyInstaller your_code.py`

It should work then.
