### ISSUE TITLE
TypeError crash while packaging the most basic script.

### ISSUE THREAD

**Issue by ricpol** [pyinstaller/pyinstaller#4146]
It appears that Pyinstaller just... won't work right from the start, on Python 3.7.2 / win10 ?! 
I'm basically trying to package a "hello world" python script from scratch... no imports, no dependencies, nothing fancy... And here is what happens: 
```shell
d:\venvs> python -m venv testvenv

d:\venvs> d:/venvs/testvenv/scripts/activate

(testvenv) d:\venvs> pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
[.........]
Successfully installed PyInstaller-3.5.dev0+8c27d2668 altgraph-0.16.1 future-0.17.1 macholib-1.11 pefile-2018.8.8 pywin32-ctypes-0.2.0

(testvenv) d:\venvs> cd ../repos/

(testvenv) d:\repos> mkdir test && cd test

(testvenv) d:\repos\test> echo print("hello world") >> test.py

(testvenv) d:\repos\test> pyinstaller test.py
46 INFO: PyInstaller: 3.5.dev0+8c27d2668
46 INFO: Python: 3.7.2
46 INFO: Platform: Windows-10-10.0.17134-SP0
46 INFO: wrote d:\repos\test\test.spec
62 INFO: UPX is not available.
62 INFO: Extending PYTHONPATH with paths
['d:\\repos\\test', 'd:\\repos\\test']
62 INFO: checking Analysis
62 INFO: Building Analysis because Analysis-00.toc is non existent
62 INFO: Initializing module dependency graph...
62 INFO: Initializing module graph hooks...
62 INFO: Analyzing base_library.zip ...
2827 INFO: running Analysis Analysis-00.toc
2835 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\venvs\test2\scripts\python.exe
2845 INFO: Caching module hooks...
2845 INFO: Analyzing d:\repos\test\test.py
2857 INFO: Loading module hooks...
2857 INFO: Loading module hook "hook-encodings.py"...
2938 INFO: Loading module hook "hook-pydoc.py"...
2954 INFO: Loading module hook "hook-xml.py"...
3128 INFO: Looking for ctypes DLLs
3128 INFO: Analyzing run-time hooks ...
3136 INFO: Looking for dynamic libraries
7857 INFO: Looking for eggs
7857 INFO: Using Python library C:\Program Files\Python37\python37.dll
7857 INFO: Found binding redirects:
[]
7859 INFO: Warnings written to d:\repos\test\build\test\warn-test.txt
7893 INFO: Graph cross-reference written to d:\repos\test\build\test\xref-test.html
7924 INFO: checking PYZ
7924 INFO: Building PYZ because PYZ-00.toc is non existent
7924 INFO: Building PYZ (ZlibArchive) d:\repos\test\build\test\PYZ-00.pyz
8310 INFO: Building PYZ (ZlibArchive) d:\repos\test\build\test\PYZ-00.pyz completed successfully.
8318 INFO: checking PKG
8318 INFO: Building PKG because PKG-00.toc is non existent
8318 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "d:\venvs\test2\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.5.dev0+8c27d2668', 'console_scripts', 'pyinstaller')()
  File "d:\venvs\test2\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\venvs\test2\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\venvs\test2\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\venvs\test2\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "d:\repos\test\test.spec", line 29, in <module>
    console=True )
  File "d:\venvs\test2\lib\site-packages\PyInstaller\building\api.py", line 430, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "d:\venvs\test2\lib\site-packages\PyInstaller\building\api.py", line 196, in __init__
    self.__postinit__()
  File "d:\venvs\test2\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "d:\venvs\test2\lib\site-packages\PyInstaller\building\api.py", line 273, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "C:\Program Files\Python37\lib\ntpath.py", line 214, in basename
    return split(p)[1]
  File "C:\Program Files\Python37\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Which seems similar to #2014 and/or #2184, but not quite.
Oh well, that was my very first try at Pyinstaller. Short and sweet...

**Comment by MyDataIsReady** [comment]
PyInstaller won't work with virtual environments starting Python 3.7.2 so you'll need to use your system site directory. Alternatively, you could try Python 3.7.1.

**Comment by ricpol** [comment]
Ok thanks for clarifying, this explains a lot... Obviously nobody wants to litter their system Python with random packages (that's why we have venvs after all) so this bug basically makes Pyinstaller a non-starter.

**Comment by MyDataIsReady** [comment]
I understand your frustration. Best thing we can do right now is to use Python 3.7.1, donate and wait.

**Comment by htgoebel** [comment]
This basically means `get_python_library_path()` does not find the python library. Now we nned to find out, why. The [release notes](https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-2-final) don't give any hint.

@MyDataIsReady Since you already tracked this down to a specific version of Python: 
- Are you using conda or anaconda?
- Are you able to track down why the python lib is not found? Adding `import pdb ; pdb.set_trace()` just before the breaking line allows debugging.

**Comment by MyDataIsReady** [comment]
So sorry for the late reply.

I have tested this again in a couple of virtual machines and it seems Pyinstaller 3.5 finally fixes this issue. It may have been related to [venv](https://docs.python.org/3/library/venv.html) changes in Python 3.7.2. I was not using conda or anaconda.

Thanks!
