### ISSUE TITLE
Cross dist executable

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4151]
I'm using PyInstaller to pack my python application and I need it to work on multiple ubuntu distributions (ubuntu12, ubuntu14, ubuntu16, ubuntu18)

To create the executable i'm using the `python:2.7.16` docker images, copy all the python files, installing the latest pyinstaller and build using pyinstaller:
`pyinstaller script.py`

It is working fine on all destibutions except `ubuntu12`, this is the error thay i'm getting:
```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "updater.py", line 15, in <module>
  File "/tmp/pip-install-4BuE5C/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/sbupdater/services/update_manager.py", line 8, in <module>
  File "/tmp/pip-install-4BuE5C/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/sbupdater/controllers/manifest_analyzer.py", line 7, in <module>
  File "/tmp/pip-install-4BuE5C/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/Crypto/PublicKey/RSA.py", line 78, in <module>
  File "/tmp/pip-install-4BuE5C/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/Crypto/Random/__init__.py", line 29, in <module>
  File "/tmp/pip-install-4BuE5C/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
  File "/tmp/pip-install-4BuE5C/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 37, in <module>
  File "/tmp/pip-install-4BuE5C/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/Crypto/Random/Fortuna/SHAd256.py", line 41, in <module>
  File "/tmp/pip-install-4BuE5C/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/Crypto/Hash/SHA256.py", line 46, in <module>
AttributeError: 'module' object has no attribute 'sha256'
[5968] Failed to execute script updater
```

Can you point me on what can cause this error only on this distribution? maybe it is the `libc` version?

The `python:2.7.16` image uses`Debian9`.

**Comment by htgoebel** [comment]
Maybe some dll is missing in ubuntu12? Maybe a different version of the package is used? Read `site-packages/Crypto/Hash/SHA256.py` **on utbuntu12* to learn more.
