### ISSUE TITLE
Loader FrozenImporter cannot handle module os

### ISSUE THREAD

**Issue by evilvlso** [pyinstaller/pyinstaller#4170]
env:
python : 3.7
pyinstaller :3.4
pyinstaller -F python.py
get this error:
```
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 438, in get_code
    return self._pyz_archive.extract(fullname)[1]
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive.py", line 371, in extract
    obj = zlib.decompress(obj)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 25, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 607, in exec_module
    bytecode = self.get_code(spec.loader_state)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 440, in get_code
    raise ImportError('Loader FrozenImporter cannot handle module ' + fullname)
ImportError: Loader FrozenImporter cannot handle module os
[5836] Failed to execute script pyiboot01_bootstrap
```

**Comment by evilvlso** [comment]
Why is this a problem ?   how to solve it ?  thinks very much

**Comment by raza-elahi** [comment]
PyInstaller: 3.4

`
Traceback (most recent call last):
  File "/home/raza/.pyenv/versions/anaconda3-4.2.0/envs/mizuho/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 438, in get_code
    return self._pyz_archive.extract(fullname)[1]
  File "/home/raza/.pyenv/versions/anaconda3-4.2.0/envs/mizuho/lib/python3.7/site-packages/PyInstaller/loader/pyimod02_archive.py", line 371, in extract
    obj = zlib.decompress(obj)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 25, in <module>
  File "/home/raza/.pyenv/versions/anaconda3-4.2.0/envs/mizuho/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 607, in exec_module
    bytecode = self.get_code(spec.loader_state)
  File "/home/raza/.pyenv/versions/anaconda3-4.2.0/envs/mizuho/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 440, in get_code
    raise ImportError('Loader FrozenImporter cannot handle module ' + fullname)
ImportError: Loader FrozenImporter cannot handle module os
[187467] Failed to execute script pyiboot01_bootstrap
`

**Comment by eputin2** [comment]
Having this exact issue. No idea what's causing it and don't know where to look.

...

Have any of you figured out what's causing this issue? It's clear it's just been ignored.

**Comment by raza-elahi** [comment]
I can't call it a solution but I got past the error using command line to add all the data instead of using the spec file.

**Comment by eputin2** [comment]
What data did you add to make this error go away?

**Comment by raza-elahi** [comment]
I was using PyInstaller to first generate a spec, modify it to add some files that my code needed, and then ran PyInstaller on the spec file to bundle the code. This wasn't working and causing the error. 

I tried using the command line notation for adding the file (pyinstaler code.py --add-data path/to/data) and that worked.

**Comment by eputin2** [comment]
I’m familiar with the errror - I was just wondering what paths to data you used to fix the OS error?

**Comment by parthkumargadhiya** [comment]
I was getting the same error. But I have solved it. Can you please post also the .spec file so I can help you.

**Comment by MakeBigWorldSmall** [comment]
I got the same error. I just want to use --key to encrypt the exe. 

Don't use any files or datas:
`

import requests
from bs4 import BeautifulSoup


def get_page_source(page_num):
    print('当前请求第%d页' % page_num)

    # 将页码传入构造url
    url = 'http://books.toscrape.com/catalogue/page-%d.html' % page_num
    r = requests.get(url)
    return r.text


def get_book_info(page_source):
    soup = BeautifulSoup(page_source, features='lxml')
    titles = soup.select('h3 > a')
    for title in titles:
        print(title.get('title'))


if __name__ == '__main__':
    # 1-50
    for i in range(1, 51):
        page_source = get_page_source(i)
        get_book_info(page_source)`

**Comment by parthkumargadhiya** [comment]
I think you are using pycryptodome. Use pycrypto module to avoid **Loader FrozenImporter cannot handle module os** error.

**Installing on Windows**

1. Install Python 3.x  
2. Install Visual C++ Build Tools
3. Install pycrypto module
`cd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
vcvarsall.bat x86_amd64
cd %VCINSTALLDIR%
for /R %f in (*stdint.h) do set CL=-FI"%f"
pip install pycrypto`

This will work and able to encrypt the executable file using the .spec file.

**Comment by htgoebel** [comment]
@evilvlso 
1. Try removing the build and dist directory, then run PyInstaller with `--clean`.
2. `--key` is is not supported.

Otherwise please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by htgoebel** [comment]
No response for 4 month. closing.

**Comment by px528** [comment]
If this issue happened in linux, just replace pycryptodome with pycrypto.

**Comment by fengerzh** [comment]
My case is Windows Defender automatically delete my exe file caused this error. If disable Windows Defender, everything works fine.
