### ISSUE TITLE
google-cloud-pubsub import calls  pkg_resources.get_distribution, throws pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by jpvelez** [pyinstaller/pyinstaller#4180]
**Software versions you are using.**
Python version 3.5.0 installed via pyenv.
Pyinstaller version 3.4.0.

**Platform**
OSX 10.13.4

*Minimal program to reproduce the error*
`pip install google-cloud-core==0.29.1 google-cloud-pubsub==0.40.0 PyInstaller==3.4 && echo "from google.cloud import pubsub_v1" > test.py && pyinstaller --debug=imports --onefile test.py && ./dist/test`

**What is the exact problem?**

I'm trying to package a command line tool that happens to use the `google-cloud-pubsub` package.

As seen in the one-liner above, it is enough to reproduce the problem to have a single script file that contains the following import: `from google.cloud import pubsub_v1`

 It builds fine. The problem is when I run the resulting binary, I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from google.cloud import pubsub_v1
  File "<frozen importlib._bootstrap>", line 1016, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Users/jpvelez/.pyenv/versions/3.5.0/envs/test.3.5.0/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "google/cloud/pubsub_v1/__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1016, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Users/jpvelez/.pyenv/versions/3.5.0/envs/test.3.5.0/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "google/cloud/pubsub_v1/publisher/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Users/jpvelez/.pyenv/versions/3.5.0/envs/test.3.5.0/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "google/cloud/pubsub_v1/publisher/client.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1016, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Users/jpvelez/.pyenv/versions/3.5.0/envs/test.3.5.0/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "google/cloud/pubsub_v1/gapic/publisher_client.py", line 41, in <module>
  File "pkg_resources/__init__.py", line 481, in get_distribution
  File "pkg_resources/__init__.py", line 357, in get_provider
  File "pkg_resources/__init__.py", line 900, in require
  File "pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'google-cloud-pubsub' distribution was not found and is required by the application
```

I think I know what the error is: one of the modules on the import path of the `google-cloud-pubsub` library (`from google.cloud import pubsub_v1`) tries to use `pkg_resources` to import the `google-cloud-pubsub` package at runtime: https://github.com/googleapis/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/gapic/publisher_client.py#L42

`_GAPIC_LIBRARY_VERSION = pkg_resources.get_distribution("google-cloud-pubsub").version`

I'm not sure how `pkg_resources.get_distribution` works, but I'm guessing that even though the `google-cloud-pubsub` library are actually in the binary - they are being executed, after all - `get_distribution` is not able to resolve the official package / `Distribution` object (https://setuptools.readthedocs.io/en/latest/pkg_resources.html#getting-or-creating-distributions)? 

(Note that if I start a python shell in the virtualenv that I'm using, `pkg_resources.get_distribution("google-cloud-pubsub`) works fine. It just doesn't work once the `publisher_client.py` module is inside the binary after build time.) 

Is there a known way to address this, other than patching the library?

**Comment by ericzolf** [comment]
We have the same issue when using setuptools-scm in our project [rdiff-backup](https://github.com/rdiff-backup/rdiff-backup/blob/master/src/rdiff_backup/Globals.py#L27) and would also be interested in a solution or at least a workaround (our program doesn't fail because we capture the exception, but it doesn't have a version on Windows).

My guess is that pyinstaller should package the wheel/egg dist-info/METADATA resp. egg-info/PKG-INFO information, which it might not do today.

**Comment by RS357** [comment]
This can't be reproduced with Pyinstaller 4.2

**Comment by RS357** [comment]
This can't be reproduced with Pyinstaller 4.2
