### ISSUE TITLE
Fails when running pyinstaller from embedded python

### ISSUE THREAD

**Issue by wheelerlaw** [pyinstaller/pyinstaller#4181]
PyInstaller fails when running from the embedded version of Python for Windows:

```
C:\Users\IEUser\Downloads\px>..\python-3.7.3-embed-amd64\Scripts\pyinstaller.exe --clean --noupx -w -F -i px.ico px.py --hidden-import win32timezone --exclude-module win32ctypes
57 INFO: PyInstaller: 3.5.dev0+b54a15d72e
57 INFO: Python: 3.7.3
59 INFO: Platform: Windows-10-10.0.17763-SP0
66 INFO: wrote C:\Users\IEUser\Downloads\px\px.spec
68 INFO: UPX is not available.
68 INFO: Removing temporary files and cleaning cache in C:\Users\IEUser\AppData\Roaming\pyinstaller
70 INFO: Extending PYTHONPATH with paths
['C:\\Users\\IEUser\\Downloads\\px', 'C:\\Users\\IEUser\\Downloads\\px']
71 INFO: checking Analysis
71 INFO: Building Analysis because Analysis-00.toc is non existent
72 INFO: Initializing module dependency graph...
Traceback (most recent call last):
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\IEUser\Downloads\python-3.7.3-embed-amd64\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\IEUser\Downloads\px\px.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\building\build_main.py", line 349, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\depend\analysis.py", line 598, in initialize_modgraph
    implies=get_implies(),
  File "c:\users\ieuser\downloads\python-3.7.3-embed-amd64\lib\site-packages\PyInstaller\lib\modulegraph\find_modules.py", line 100, in get_implies
    files = os.listdir(xml.etree.__path__[0])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\ieuser\\downloads\\python-3.7.3-embed-amd64\\python37.zip\\xml\\etree'
```

It appears to be because [this](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/modulegraph/find_modules.py#L100) line in the `find_modules.py`:
```python
        import xml.etree
        files = os.listdir(xml.etree.__path__[0])
```

Since the standard library for the embedded version is in a zip, `os.listdir` doesn't work. Some other way of iterating over the files in the module will be needed. 

### Steps to reproduce:
- Download the Python embedded version [here](https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-amd64.zip) and unzip it (to `./python37` for example)
- Delete the `"python37._pth" file inside the folder where you unzipped Python. 
- Download and install pip using [`get-pip.py`](https://bootstrap.pypa.io/get-pip.py)
- Install some dependencies: 
  ```
  .\python37\Scripts\pip.exe install keyring netaddr ntlm-auth psutil pywin32 winkerberos futures
  ```
- Install latest version of PyInstaller: 
  ```
  .\python37\Scripts\pip.exe install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  ```
- Clone the repo that uses PyInstaller: 
  ```
  git clone git@github.com:wheelerlaw/px.git
  ```
- Go into the repo and run PyInstaller:
  ```
  cd px
  ..\python37\Scripts\pyinstaller.exe --clean --noupx -w -F -i px.ico px.py --hidden-import win32timezone --exclude-module win32ctypes
  ```
It will yield the error. Running the same command with the non-embedded version of Python works fine. 

Alternatively, you can run the same steps in a Docker container with Wine:

First run the container: `docker run --rm -it ubuntu bash`

Then run the following commands:
```bash
cd ~
apt-get update && apt-get install -y curl software-properties-common gnupg1 unzip git
curl -fsSL https://dl.winehq.org/wine-builds/winehq.key | apt-key add -
dpkg --add-architecture i386
apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
apt-get install -y --install-recommends winehq-staging
curl -fsSL https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-amd64.zip -O
unzip python*.zip -d python37
cd python37
mv python37._pth python37._pth.bak
curl -fsSL https://bootstrap.pypa.io/get-pip.py -O
wine python.exe get-pip.py
wine ./Scripts/pip.exe install keyring netaddr ntlm-auth psutil pywin32 winkerberos futures
wine ./Scripts/pip.exe install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
cd ..
git clone https://github.com/wheelerlaw/px.git
cd px
wine ../python37/Scripts/pyinstaller.exe --clean --noupx -w -F -i px.ico px.py --hidden-import win32timezone --exclude-module win32ctypes
```

**Comment by htgoebel** [comment]
Closed by #4182, but that pull-request did not reference here properly
