### ISSUE TITLE
typeError: from_buffer() cannot return the address 

### ISSUE THREAD

**Issue by KaiOuYang** [pyinstaller/pyinstaller#4197]
**I can't  produce a exe file, so how can i solve this?**
*Configure below:
   python 3.5.2 
   Anaconda 4.2.0(64-bit)
   setuptools-41.0.1
   pywin32(224)
   pywin32-ctypes(0.2.0)
   prefile-2019.4.18
   win7 64-bit*

```shell
145409 ERROR: C:\Users\Administrator\AppData\Roaming\pyinstaller\bincache00_py35
_64bit\libpng16.dll
Traceback (most recent call last):
  File "D:\Pycharm_pro\Anaconda_install\Scripts\pyinstaller-script.py", line 11,
 in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 32, in <module>
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\building\api.py", line 424, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\building\api.py", line 196, in __init__
    self.__postinit__()
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\building\api.py", line 259, in assemble
    dist_nm=inm)
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\building\utils.py", line 340, in checkCache
    [language])
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\utils\win32\winmanifest.py", line 939, in update_resources
    names, languages)
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\utils\win32\winmanifest.py", line 1017, in UpdateManifestResourc
esFromXML
    languages or [0, "*"])
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\pyinstaller-3.4-py3.5.
egg\PyInstaller\utils\win32\winresource.py", line 202, in UpdateResources
    win32api.UpdateResource(hdst, type_, name, data, language)
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\win32ctypes\pywin32\wi
n32api.py", line 269, in UpdateResource
    handle, type, name, language, lp_data, len(lp_data))
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\win32ctypes\core\cffi\
_resource.py", line 129, in _UpdateResource
    lpData = ffi.from_buffer(cData)
  File "D:\Pycharm_pro\Anaconda_install\lib\site-packages\cffi\api.py", line 340
, in from_buffer
    return self._backend.from_buffer(self.BCharA, python_buffer)
TypeError: from_buffer() cannot return the address of the raw string within a by
tes or unicode object
```

**Comment by vbty** [comment]
I have the same question and hope to get an answer.

**Comment by vbty** [comment]
I solve this problem,cryptography module version is too old.Just update this package.
```
pip uninstall cryptography -y 
pip install --upgrade cryptography
```
可以试一下

**Comment by htgoebel** [comment]
solved
