### ISSUE TITLE
Pyinstaller executable fails importing torchvision

### ISSUE THREAD

**Issue by deepinstruction** [pyinstaller/pyinstaller#4251]
This is my **main.py**:

```
import torchvision
input("Press key")
```

It runs correctly in the command line: `python main.py`
I need an executable for windows. So I did : `pyinstaller main.py`

But when I launched the **main.exe**, inside `/dist/main` I got this error:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>

  ... (omitted)

  File "site-packages\torchvision\ops\misc.py", line 135, in <module>
  File "site-packages\torchvision\ops\misc.py", line 148, in FrozenBatchNorm2d
  File "site-packages\torch\jit\__init__.py", line 850, in script_method
  File "site-packages\torch\jit\frontend.py", line 152, in get_jit_def
  File "inspect.py", line 973, in getsource
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code
[2836] Failed to execute script main
```

It seems that the torchvision source code is not correctly imported from pyinstaller.

**Additional info:**

I recently installed Visual Studio 2019

**System info:**

Window 10
Python 3.7 (tryed also 3.6.8)
torch-1.1.0
torchvision-0.3.0_

**Comment by deepinstruction** [comment]
Downgrade torchvision to the previous version fix the error.

pip uninstall torchvision
pip install torchvision==0.2.2.post3
