### ISSUE TITLE
PackageNotFoundError: importlib_metadata with Pluggy 0.12.0

### ISSUE THREAD

**Issue by henriquegemignani** [pyinstaller/pyinstaller#4258]
After upgrading to pluggy 0.12.0, the program fails to finda dependency.

Error output:
```
Traceback (most recent call last):
  File "pluggyissue\__main__.py", line 1, in <module>
    import pluggy
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\henri\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pluggy\__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\henri\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pluggy\manager.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\henri\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\importlib_metadata\__init__.py", line 466, in <module>
  File "site-packages\importlib_metadata\__init__.py", line 433, in version
  File "site-packages\importlib_metadata\__init__.py", line 406, in distribution
  File "site-packages\importlib_metadata\__init__.py", line 180, in from_name
importlib_metadata.PackageNotFoundError: importlib_metadata
[15928] Failed to execute script __main__
```

Test case:
[pyinst-test.zip](https://github.com/pyinstaller/pyinstaller/files/3244214/pyinst-test.zip)

requirements.txt
```
altgraph==0.16.1
future==0.17.1
importlib-metadata==0.17
macholib==1.11
pefile==2019.4.18
pluggy==0.12.0
PyInstaller==3.4
pywin32-ctypes==0.2.0
zipp==0.5.1
```

Upgrading to latest devel of PyInstaller makes no changes.

I'm not sure if this is an issue on PyInstaller or on Pluggy, but reverting to the previous version fixes the issue.
This issue was identified in my project by just updating Pluggy:
https://github.com/randovania/randovania/pull/250
https://ci.appveyor.com/project/henriquegemignani/randovania/builds/24923556

**Comment by astrofrog** [comment]
Just FYI I reported this to the ``importlib_metadata`` developers in https://gitlab.com/python-devs/importlib_metadata/issues/71

**Comment by danyeaw** [comment]
I ran across this issue as well. In https://gitlab.com/python-devs/importlib_metadata/issues/71, on of the solutions to patch the __init__.py file from the package seems to be a workaround:
```
modified   importlib_metadata/__init__.py
@@ -469,3 +469,6 @@ def requires(package):
 
 
-__version__ = version(__name__)
+try:
+    __version__ = version(__name__)
+except PackageNotFoundError:  # for frozen app support, enter correct version here
+    __version__ = '0.18'
```
The maintainer of importlib_metadata suggests one of the two solutions:

1. pyinstaller should include metadata in a format that's already recognized by importlib_metadata's [MetadataPathFinder](https://gitlab.com/python-devs/importlib_metadata/blob/35c25b43114062b43b0e60baa8782bef17eafb53/importlib_metadata/__init__.py#L338)
2. pyinstaller should register and install another DistributionFinder per [the docs](https://importlib-metadata.readthedocs.io/en/latest/using.html#extending-the-search-algorithm).

Does anyone have any thoughts on what the best way is to go about fixing this?

**Comment by htgoebel** [comment]
Looks like this package requires a hook for collection the meta-data. Please the the PyInstaller manual and take otehr hooks as an example.

**Comment by danyeaw** [comment]
I think @htgoebel that you already resolved this issue with 1dda9dc, which copies the metadata in for importlib_metadata with a hook. 🎉
@henriquegemignani Could you test out the latest develop branch?

**Comment by htgoebel** [comment]
@danyeaw ACK, 1dda9dc63239fc16dbe0ea74b6df46d88304f87d should  solve this.

**Comment by henriquegemignani** [comment]
I haven't been able to reproduce the exact original error, but latest dev works properly for me and I don't have any errors in the original context.
