### ISSUE TITLE
The "mips64" structure is not supported

### ISSUE THREAD

**Issue by efynn** [pyinstaller/pyinstaller#4273]
1、My machine information:
```sh
[root@localhost OmniDB]# uname -a
Linux localhost.localdomain 3.10.0-2.nd7.17.mips64el #1 SMP PREEMPT Sat Nov 24 01:42:14 CST 2018 mips64 mips64 mips64 GNU/Linux
[root@localhost OmniDB]# getconf LONG_BIT
64
[root@localhost OmniDB]#
```
2、I used the command `pip3 install pyinstaller`and then I was ready to pack my program:
```sh
[root@localhost OmniDB]# pyinstaller OmniDB-lin.spec 
146 INFO: PyInstaller: 3.4
146 INFO: Python: 3.6.7
157 INFO: Platform: Linux-3.10.0-2.nd7.17.mips64el-mips64-with-glibc2.0
160 INFO: UPX is not available.
164 INFO: Extending PYTHONPATH with paths
['/opt/5431/OmniDB', '/opt/5431/OmniDB/OmniDB_app/include']
164 INFO: checking Analysis
176 INFO: Building because /usr/local/lib/python3.6/site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py changed
176 INFO: Initializing module dependency graph...
179 INFO: Initializing module graph hooks...
183 INFO: Analyzing base_library.zip ...
13505 INFO: Analyzing hidden import 'psycopg2'
14917 INFO: Analyzing hidden import 'paramiko'
16818 INFO: running Analysis Analysis-00.toc
16852 INFO: Caching module hooks...
16869 INFO: Analyzing omnidb-server.py
26285 INFO: Loading module hooks...
26287 INFO: Loading module hook "hook-psycopg2.py"...
26288 WARNING: Hidden import "mx.DateTime" not found!
26289 INFO: Loading module hook "hook-xml.py"...
26495 INFO: Loading module hook "hook-pydoc.py"...
26497 INFO: Loading module hook "hook-encodings.py"...
26701 INFO: Loading module hook "hook-sqlite3.py"...
26949 INFO: Looking for ctypes DLLs
27132 INFO: Analyzing run-time hooks ...
27151 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
27194 INFO: Looking for dynamic libraries
28386 INFO: Looking for eggs
28386 INFO: Using Python library /usr/local/lib/libpython3.6m.so.1.0
28416 INFO: Warnings written to /opt/5431/OmniDB/build/OmniDB-lin/warn-OmniDB-lin.txt
28626 INFO: Graph cross-reference written to /opt/5431/OmniDB/build/OmniDB-lin/xref-OmniDB-lin.html
28668 INFO: Appending 'datas' from .spec
28745 INFO: checking PYZ
28756 INFO: Building because toc changed
28756 INFO: Building PYZ (ZlibArchive) /opt/5431/OmniDB/build/OmniDB-lin/PYZ-00.pyz
31129 INFO: Building PYZ (ZlibArchive) /opt/5431/OmniDB/build/OmniDB-lin/PYZ-00.pyz completed successfully.
31160 INFO: checking PKG
31161 INFO: Building because /opt/5431/OmniDB/build/OmniDB-lin/PYZ-00.pyz changed
31161 INFO: Building PKG (CArchive) PKG-00.pkg
31205 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
31208 INFO: Bootloader /usr/local/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run
31208 INFO: checking EXE
31209 INFO: Building EXE because EXE-00.toc is non existent
31209 INFO: Building EXE from EXE-00.toc
31210 INFO: Appending archive to ELF section in EXE /opt/5431/OmniDB/build/OmniDB-lin/omnidb-server
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 35, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/api.py", line 433, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/api.py", line 594, in assemble
    raise SystemError("objcopy Failure: %s" % stderr)
SystemError: objcopy Failure: objcopy: Unable to recognise the format of the input file `/opt/5431/OmniDB/build/OmniDB-lin/omnidb-server'

```
I got an error of` 'SystemError: objcopy Failure'`. I planned to recompile bootloader on this machine after checking the relevant issue, but it seems that I have a lot of libraries missing and can't download using the command `yum groupinstall "Development Tools"`.
```sh
[root@localhost bootloader]# python3 ./waf distclean all
'distclean' finished successfully (0.001s)
'all' finished successfully (0.000s)
'distclean' finished successfully (0.000s)
Setting top to                           : /opt/5431/pyinstaller-3.4/bootloader 
Setting out to                           : /opt/5431/pyinstaller-3.4/bootloader/build 
Python Version                           : 3.6.7 (default, Jun 13 2019, 17:31:51) [GCC 4.9.3 20150626 (NeoKylin 4.9.3-3)] 
Checking for 'gcc' (C compiler)          : /usr/lib64/ccache/gcc 
Checking size of pointer                 : 8 
Platform                                 : Linux-64bit detected based on compiler 
Checking for flags -m64                  : yes 
Checking for program '/usr/lib64/ccache/strip' : /usr/lib64/ccache/strip 
Checking for program 'strip'                   : /usr/lib64/ccache/strip 
Checking for library dl                        : not found 
The configuration failed
(complete log in /opt/5431/pyinstaller-3.4/bootloader/build/config.log)
[root@localhost bootloader]# 
[root@localhost bootloader]# yum groupinstall "Development Tools"
No installation group information file
Maybe run: yum groups mark convert (see man yum)
Warning: group Development Tools does not exist.
Maybe run: yum groups mark install (see man yum)
Error: there are no installable or upgradable packages in the specified group
[root@localhost bootloader]# 
```
Unfortunately, I don't know much about these libraries, so I hope to get some help here, mainly because of the `mips64` architecture.And how to recompile the bootloader.

**Comment by efynn** [comment]
I got the following error when using Anaconda3 installation.So I built python-3.6.7 from source code

```sh
Anaconda3 will now be installed into this location:
/root/anaconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/root/anaconda3] >>> 
PREFIX=/root/anaconda3
installing: python-3.7.3-h0371630_0 ...
Anaconda3-2019.03-Linux-x86_64.sh:line377: /root/anaconda3/pkgs/python-3.7.3-h0371630_0/bin/python: cannot execute binary file: Executable file format error
```
In the virtual environment, I also got the `SystemError: objcopy Failure: objcopy: Unable to recognise the format of the input file  '/opt/5431/OmniDB/build/OmniDB-Lin/OmniDB-server' `mistakes

**Comment by efynn** [comment]
The file type:
```sh
[root@localhost opt]# df -hT
文件系统       类型      容量  已用  可用 已用% 挂载点
/dev/sda1      ext3       50G   18G   30G   37% /
devtmpfs       devtmpfs  7.7G     0  7.7G    0% /dev
tmpfs          tmpfs     7.7G  224K  7.7G    1% /dev/shm
tmpfs          tmpfs     7.7G  5.0M  7.7G    1% /run
tmpfs          tmpfs     7.7G     0  7.7G    0% /sys/fs/cgroup
tmpfs          tmpfs     7.7G  5.0M  7.7G    1% /etc/machine-id
/dev/sda6      ext4      114G   60M  108G    1% /diskE
/dev/sda5      ext4      221G   87M  209G    1% /home
tmpfs          tmpfs     1.6G  192K  1.6G    1% /run/user/1000
tmpfs          tmpfs     1.6G     0  1.6G    0% /run/user/0
```

**Comment by htgoebel** [comment]
I suggest you first to become able to build teh bootloader. Please ask your colleges or shearch the internet on how to to install the required tools and libraries.

BTW: You are working a root. This is a *huge* security risk. One should never ever develop code as root. What if PyInstaller would include some trojan?

**Comment by htgoebel** [comment]
Stale since long, closing.
