### ISSUE TITLE
./waf configure fails if GCC does not support ‘-m64’

### ISSUE THREAD

**Issue by efynn** [pyinstaller/pyinstaller#4278]
For some reasons the GCC we used did not have the -m64 parameter, and we need to recompile bootloader, But executing the command`./waf configure` times is wrong, the following is the error information, so I would like to ask how I can remove the -m64 parameter in the precheck.(At least this parameter is not available for this machine)

```sh
----------------------------------------
Checking for library dl
==>

int main(int argc, char **argv) {
        (void)argc; (void)argv;
        return 0;
}

<==
[1/2] Compiling ^[[32mbuild/.conf_check_e10294f62c26a728688c156b9420cd34/test.c^[[0m

['/usr/bin/gcc', '-m64', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-U_FORTIFY_SOURCE', '-D_REENTRANT', '-D_BSD_SOURCE', '-D_DEFAULT_SOURCE', '-D_FORTIFY_SOURCE=2', '../test.c', '-c', '-o/opt/123/pyinstaller/bootloader/build/.conf_check_e10294f62c26a728688c156b9420cd34/testbuild/test.c.1.o']
err: gcc: error: unrecognized command line option ‘-m64’

from /opt/123/pyinstaller/bootloader: Test does not build: Traceback (most recent call last):
  File "/opt/123/pyinstaller/bootloader/.waf3-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Configure.py", line 324, in run_build
    bld.compile()
  File "/opt/123/pyinstaller/bootloader/.waf3-2.0.9-6b5f17f340ec613b295ffa3dedcecc80/waflib/Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

not found
from /opt/123/pyinstaller/bootloader: The configuration failed
```

```sh
[root@localhost bootloader]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/mips64el-neokylin-linux/4.9.3/lto-wrapper
Target: mips64el-neokylin-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.cs2c.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --build=mips64el-neokylin-linux --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-arch=loongson3a --enable-languages=c,c++,objc,obj-c++,fortran,go,lto --enable-plugin --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.3/obj-mips64el-neokylin-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.3/obj-mips64el-neokylin-linux/cloog-install --enable-gnu-indirect-function --with-long-double-128 --build=mips64el-neokylin-linux
Thread model: posix
gcc version 4.9.3 20150626 (NeoKylin 4.9.3-5) (GCC) 

```

```sh
[root@localhost bootloader]# uname -a
Linux localhost 3.10.0-862.9.1.ns7_4.37.mips64el #1 SMP PREEMPT Tue Feb 26 19:23:39 CST 2019 mips64el mips64el mips64el GNU/Linux
```

**Comment by htgoebel** [comment]
I'm curious hwo this can happen since the `wscript` should contain code to detect whether the flag is available. Maybe this code is wrong or some unpaned execution path is taken.

Please try to debug the wscript. The wscript is an ordinary python script, thus you can add `import pdb; pdb.set_trace()` near the top of `set_arch_flags()`

**Comment by htgoebel** [comment]
I discovered that the checks actually have not been performed in the `configure` phase..

Well, this does not actually solve this issue, as set_arch_flags still needs to take care for your case.

**Comment by htgoebel** [comment]
Should be fixed now, too.

**Comment by efynn** [comment]
Thank you very much for your help!
