### ISSUE TITLE
"RecursionError: maximum recursion depth exceeded while calling a Python object" using the multiprocessing fix

### ISSUE THREAD

**Issue by Minabsapi** [pyinstaller/pyinstaller#4294]
### OS: Windows
Python version: 3.6.2

I bundled a working script using `pyinstaller -F myscript.py` (so as one file)
This script contains the multiprocessing module, which is known to be kind of buggy when bundled with this tool.
I applied the [following recipe](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing) to work around the problem, and followed the comment under [this answer](https://stackoverflow.com/a/27694505) to fix it.
But when I run the resulting program I get something like this:
```Traceback (most recent call last):
  File "myscript.py", line 91, in <module>
  File "multiprocessing\process.py", line 105, in start
  File "myscript.py", line 20, in __init__
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 71, in __init__
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 71, in __init__
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 71, in __init__
  [Previous line repeated 327 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
[3968] Failed to execute script myscript
```
The crash actually happen when I launch a Process object with `Process(...).start()`.
(The \_\_init\_\_ in line 20 found in the stack trace is actually a part of the fix, this piece of code: `super(_Popen, self).__init__(*args, **kw)`)

**Comment by Legorooj** [comment]
Can you try with the latest PyInstaller development version?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
