### ISSUE TITLE
IPython windows10

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4316]
I'm trying to embed IPython in my application, it is working fine in Win7 but raise an exception on Win10.

Code to reproduce:
```
import IPython
IPython.embed()
```
Error on windows10:
```
C:\Users\SAFEBR~1\IPYTHO~2\dist\test\win_unicode_console\__init__.py:31: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == 'cp850', readline hook consumer may assume they are the same
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    IPython.embed()
  File "site-packages\IPython\terminal\embed.py", line 383, in embed
  File "site-packages\traitlets\config\configurable.py", line 412, in instance
  File "site-packages\IPython\terminal\embed.py", line 158, in __init__
  File "site-packages\IPython\terminal\interactiveshell.py", line 441, in __init__
  File "site-packages\IPython\terminal\interactiveshell.py", line 276, in init_prompt_toolkit_cli
  File "site-packages\prompt_toolkit\shortcuts.py", line 118, in create_output
  File "site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
  File "site-packages\prompt_toolkit\terminal\win32_output.py", line 172, in get_win32_screen_buffer_info
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
[7740] Failed to execute script test
```

**Comment by Legorooj** [comment]
How did you build?
