### ISSUE TITLE
Failed to  execute script.

### ISSUE THREAD

**Issue by kirancrazy99** [pyinstaller/pyinstaller#4317]
Hi Folks,

I'm creating a tkinter application by using Pyinstaller,code works well if I execute in python IDE or Jupyter notebook but when I  try to execute the exe file it throwing me an error like Failed to execute script.

Here I noticed one thing when I create an exe file by importing the module pandas_profiling or spark_df_profiling in the script then only I'm encountering  this error. if I remove importing these modules, then application opening without any error.

**My Sample Code:**
from tkinter import *
import tkinter as tk
import pandas_profiling
master = tk.Tk()
tk.Label(master, text="Query").grid(row=9, column=0)
#tk.Label(master, text="server address").grid(row=0, column=0)
tk.Label(master, text="database").grid(row=2, column=0)
tk.Label(master, text="enter the file path here").grid(row=4, column=0)

master.mainloop().

I have tried to figure out the error by creating the app with Pyinstaller by using below syntax:
pyinstaller -F app.py
later ran this app from the command prompt and I got the below error.

C:\Users\hz3\Kiran\Tkinter\app\dist>app.exe
Traceback (most recent call last):
  File "app.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\hz3\appdata\local\continuum\anaconda3\lib\site-packages\PyInst
    exec(bytecode, module.__dict__)
  File "site-packages\pandas_profiling\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\hz3\appdata\local\continuum\anaconda3\lib\site-packages\PyInst
    exec(bytecode, module.__dict__)
  File "site-packages\pandas_profiling\templates.py", line 64, in <module>
  File "site-packages\pandas_profiling\templates.py", line 60, in template
  File "site-packages\jinja2\environment.py", line 830, in get_template
  File "site-packages\jinja2\environment.py", line 804, in _load_template
  File "site-packages\jinja2\loaders.py", line 113, in load
  File "site-packages\jinja2\loaders.py", line 234, in get_source
  File "site-packages\pkg_resources\__init__.py", line 1404, in has_resource
  File "site-packages\pkg_resources\__init__.py", line 1457, in _has
NotImplementedError: Can't perform this operation for unregistered loader type
Failed to execute the script.

Plat form:
Windows:7 64bit
Python 3.7
Pyinstaller (latest version downloaded from Github)

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by joanteixi** [comment]
hi! @kirancrazy99 did you found a solution to this particular problem with pandas_profiling and pyinstaller?

**Comment by MathijssYDev** [comment]
Hi, I had the same error. I tried to run the .exe file as an administrator and it worked for me! So i hope its helpfull.
