### ISSUE TITLE
Pyinstaller Packaged Executable Behaves Differently between Windows 10 and Windows 7 Specifically Using ibm_db Package

### ISSUE THREAD

**Issue by adcContrib** [pyinstaller/pyinstaller#4319]
I have seen similar issues prompted but there seems to be insufficient information to go on. As a result I am hoping my issue will fill that gap in.

As titled, however I have issue specifically with the utilization of ibm_db package.  I know ibm_db package is a bit precarious. But based on what I was able to collect and gather integrating solution outlined in the following posts I was able to get a working build in Windows 7.

* https://stackoverflow.com/questions/55839589/importerror-dll-load-failed-the-specified-module-could-not-be-found-ibm-db2
* https://developer.ibm.com/answers/questions/448999/python-3-db2-windows-10-problems-and-script-compil/

You will see presence of these solution in the following processes.

Following is the bare bone code I start with
```
#!/usr/bin/python3

import ibm_db
import sys
import platform

print ("* Python version {0}".format(sys.version_info))
print ("* OS Platform {0}, {1}, {2}".format(platform.system(), platform.release(), platform.version()))
print ("* IBM DB version {0} \n\n".format(ibm_db.__version__))

print ("Veni, vidi, vici!!!")
```
Executing it from source file yields the following
```
c:\Software\ibmdb-win10-sample>python.exe ibmdb-sample.py
* Python version sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
* OS Platform Windows, 10, 10.0.17763
* IBM DB version 3.0.1


Veni, vidi, vici!!!
```
The following is the command I used to build the file
```
pyinstaller --clean ^
   --add-binary "C:\Users\<username>\AppData\Roaming\Python\Python37\site-packages\ibm_db_dlls;.\ibm_db_dlls" ^
   --onefile ibmdb-sample.py
```
Here's the Pyinstaller output
```
c:\Software\ibmdb-win10-sample>pyinstaller --clean    --add-binary "C:\Software\ibm_db\ibm_db.dll;.\ibm_db_dlls"    --onefile ibmdb-sample.py
51 INFO: PyInstaller: 3.5
65 INFO: Python: 3.7.3
65 INFO: Platform: Windows-10-10.0.17763-SP0
68 INFO: wrote c:\Software\ibmdb-win10-sample\ibmdb-sample.spec
68 INFO: UPX is not available.
68 INFO: Removing temporary files and cleaning cache in C:\Users\<username>\AppData\Roaming\pyinstaller
85 INFO: Extending PYTHONPATH with paths
['c:\\Software\\ibmdb-win10-sample', 'c:\\Software\\ibmdb-win10-sample']
85 INFO: checking Analysis
85 INFO: Building Analysis because Analysis-00.toc is non existent
85 INFO: Initializing module dependency graph...
85 INFO: Initializing module graph hooks...
85 INFO: Analyzing base_library.zip ...
2251 INFO: running Analysis Analysis-00.toc
2251 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\<username>\appdata\local\programs\python\python37\python.exe
2489 INFO: Caching module hooks...
2491 INFO: Analyzing c:\Software\ibmdb-win10-sample\ibmdb-sample.py
2595 INFO: Processing pre-find module path hook   distutils
2612 INFO: Processing pre-find module path hook   site
2612 INFO: site: retargeting to fake-dir 'C:\\Users\\<username>\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyInstaller\\fake-modules'
3403 INFO: Loading module hooks...
3403 INFO: Loading module hook "hook-distutils.py"...
3416 INFO: Loading module hook "hook-encodings.py"...
3489 INFO: Loading module hook "hook-pkg_resources.py"...
3678 INFO: Processing pre-safe import module hook   win32com
3884 INFO: Loading module hook "hook-pydoc.py"...
3884 INFO: Loading module hook "hook-pythoncom.py"...
4073 INFO: Loading module hook "hook-pywintypes.py"...
4276 INFO: Loading module hook "hook-sysconfig.py"...
4278 INFO: Loading module hook "hook-win32com.py"...
4640 INFO: Loading module hook "hook-xml.dom.domreg.py"...
4640 INFO: Loading module hook "hook-xml.py"...
4657 INFO: Looking for ctypes DLLs
4674 INFO: Analyzing run-time hooks ...
4674 INFO: Including run-time hook 'pyi_rth_pkgres.py'
4674 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
4674 INFO: Looking for dynamic libraries
4881 INFO: Looking for eggs
4881 INFO: Using Python library c:\users\<username>\appdata\local\programs\python\python37\python37.dll
4881 INFO: Found binding redirects:
[]
4898 INFO: Warnings written to c:\Software\ibmdb-win10-sample\build\ibmdb-sample\warn-ibmdb-sample.txt
4949 INFO: Graph cross-reference written to c:\Software\ibmdb-win10-sample\build\ibmdb-sample\xref-ibmdb-sample.html
4966 INFO: Appending 'binaries' from .spec
4980 INFO: checking PYZ
4980 INFO: Building PYZ because PYZ-00.toc is non existent
4984 INFO: Building PYZ (ZlibArchive) c:\Software\ibmdb-win10-sample\build\ibmdb-sample\PYZ-00.pyz
5568 INFO: Building PYZ (ZlibArchive) c:\Software\ibmdb-win10-sample\build\ibmdb-sample\PYZ-00.pyz completed successfully.
5585 INFO: checking PKG
5585 INFO: Building PKG because PKG-00.toc is non existent
5585 INFO: Building PKG (CArchive) PKG-00.pkg
9109 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
9109 INFO: Bootloader C:\Users\<username>\AppData\Roaming\Python\Python37\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
9109 INFO: checking EXE
9109 INFO: Building EXE because EXE-00.toc is non existent
9109 INFO: Building EXE from EXE-00.toc
9109 INFO: Appending archive to EXE c:\Software\ibmdb-win10-sample\dist\ibmdb-sample.exe
9229 INFO: Building EXE from EXE-00.toc completed successfully.
```
Here's the script that execute this particular setup. Based on the forum posting above, it is necessary that the **clidriver** folder from the ibm_db package to be within the accessible path. The following MS-DOS command line script ensures that **clidriver** folder is within path provided that **clidriver** directory is copied to the same directory as the executable. 
```
SET CLIDRIVER="%~dp0clidriver\bin"
echo %CLIDRIVER%

SET PATH=%PATH%;%CLIDRIVER%

echo %path%

ibmdb-sample.exe
```
Here's what happen when I try to execute the packaged file in Windows 10 environment
```
c:\Software\ibmdb-win10-sample\dist>ibmdb-sample.exe
Traceback (most recent call last):
  File "ibmdb-sample.py", line 3, in <module>
  File "C:\Users\<username>\AppData\Roaming\Python\Python37\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "ibm_db.py", line 10, in <module>
  File "ibm_db.py", line 9, in __bootstrap__
  File "imp.py", line 342, in load_dynamic
ImportError: DLL load failed: The specified module could not be found.
[3456] Failed to execute script ibmdb-sample
```
Interestingly, taking the same packaged executable to windows 7 proves to be fruitful.
```
c:\local\vm\vmshare\test-win7\dist>ibmdb-sample.exe
* Python version sys.version_info(major=3, minor=7, micro=3, releaselevel='final
', serial=0)
* OS Platform Windows, 7, 6.1.7601
* IBM DB version 3.0.1


Veni, vidi, vici!!!
```
I hope this is enough information to work with. Please feel free to get in touch with me should you need me to try things or to provide you with more information and thank you in advance.

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.
