### ISSUE TITLE
FileNotFoundError python_slugify==3.0.2

### ISSUE THREAD

**Issue by eeriks** [pyinstaller/pyinstaller#4327]
PyInstaller==3.5 (also tried development version PyInstaller-4.0.dev0+7350d4c85)

Problem occurs when using python-slugify 3

Compilation to both onefile and onedir is without problems,  but when executing file which has python-slugify > 2.0.1 getting FileNotFound error.

Steps to reproduce:
```
$ pip install -U python_slugify
$ pyinstaller -F --clean --distpath dist --workpath work versions.py 
$ ./dist/versions/versions 
Traceback (most recent call last):
  File "versions.py", line 1, in <module>
    import requests, pytz, slugify
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/eeriks/PycharmProjects/installer/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "slugify/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/eeriks/PycharmProjects/installer/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "slugify/slugify.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/eeriks/PycharmProjects/installer/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "text_unidecode/__init__.py", line 6, in <module>
  File "pkgutil.py", line 637, in get_data
  File "/Users/eeriks/PycharmProjects/installer/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 469, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/eeriks/PycharmProjects/installer/dist/versions/text_unidecode/data.bin'
[4365] Failed to execute script versions

$ pip install -U "python_slugify<3.0.0"
$ pyinstaller -F --clean --distpath dist --workpath work versions.py 
$ ./dist/versions 
slugify  =  2.0.1
```

versions.py:
``` python
import slugify
print("slugify  = ", slugify.__version__)
```

**Comment by htgoebel** [comment]
Obviously some date file are not bundeld. Please red the manual how to write a hook and consider providing a pull-request for this hook.
