### ISSUE TITLE
Problems generating to UniqueBible

### ISSUE THREAD

**Issue by prsolucoes** [pyinstaller/pyinstaller#4358]
I tried to generate it for app UniqueBible (https://github.com/eliranwong/UniqueBible) using:

```
pyinstaller main.py
```

But get the error:

```
pyinstaller main.py 
92 INFO: PyInstaller: 3.5
92 INFO: Python: 3.7.3
100 INFO: Platform: Darwin-18.7.0-x86_64-i386-64bit
101 INFO: wrote /Users/paulo/Developer/workspaces/python/UniqueBible/main.spec
104 INFO: UPX is not available.
105 INFO: Extending PYTHONPATH with paths
['/Users/paulo/Developer/workspaces/python/UniqueBible',
 '/Users/paulo/Developer/workspaces/python/UniqueBible']
105 INFO: checking Analysis
105 INFO: Building Analysis because Analysis-00.toc is non existent
106 INFO: Initializing module dependency graph...
109 INFO: Initializing module graph hooks...
111 INFO: Analyzing base_library.zip ...
3037 INFO: running Analysis Analysis-00.toc
3045 INFO: Caching module hooks...
3049 INFO: Analyzing /Users/paulo/Developer/workspaces/python/UniqueBible/main.py
3408 INFO: Processing pre-find module path hook   distutils
3652 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
5556 INFO: Processing pre-safe import module hook   six.moves
9731 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
10212 INFO: Processing pre-find module path hook   site
10213 INFO: site: retargeting to fake-dir '/usr/local/lib/python3.7/site-packages/PyInstaller/fake-modules'
40198 INFO: Loading module hooks...
40198 INFO: Loading module hook "hook-scipy.linalg.py"...
40199 INFO: Loading module hook "hook-zmq.py"...
/Users/paulo/Library/Python/3.7/lib/python/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:216:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^~~~~~~
1 error generated.
41377 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
41614 INFO: Loading module hook "hook-sqlite3.py"...
41684 INFO: Loading module hook "hook-pkg_resources.py"...
41967 INFO: Processing pre-safe import module hook   win32com
42227 INFO: Loading module hook "hook-pandas.py"...
Segmentation fault: 11
```

Thanks for any help.

**Comment by prsolucoes** [comment]
Hi,

I tried with develop version and python 3.7.4:

```
49 INFO: PyInstaller: 4.0.dev0+269779f91
49 INFO: Python: 3.7.4
57 INFO: Platform: Darwin-18.7.0-x86_64-i386-64bit
58 INFO: wrote /Users/paulo/Developer/workspaces/python/UniqueBible/main.spec
60 INFO: UPX is not available.
62 INFO: Extending PYTHONPATH with paths
['/Users/paulo/Developer/workspaces/python/UniqueBible',
 '/Users/paulo/Developer/workspaces/python/UniqueBible']
63 INFO: checking Analysis
63 INFO: Building Analysis because Analysis-00.toc is non existent
63 INFO: Initializing module dependency graph...
67 INFO: Initializing module graph hooks...
68 INFO: Analyzing base_library.zip ...
2850 INFO: running Analysis Analysis-00.toc
2863 INFO: Caching module hooks...
2869 INFO: Analyzing /Users/paulo/Developer/workspaces/python/UniqueBible/main.py
3215 INFO: Processing pre-find module path hook   distutils
3454 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
5326 INFO: Processing pre-safe import module hook   six.moves
8960 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
9390 INFO: Processing pre-find module path hook   site
9390 INFO: site: retargeting to fake-dir '/usr/local/lib/python3.7/site-packages/PyInstaller/fake-modules'
36480 INFO: Loading module hooks...
36480 INFO: Loading module hook "hook-scipy.linalg.py"...
36481 INFO: Loading module hook "hook-zmq.py"...
/Users/paulo/Library/Python/3.7/lib/python/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:216:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^~~~~~~
1 error generated.
37017 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
37169 INFO: Loading module hook "hook-sqlite3.py"...
37231 INFO: Loading module hook "hook-pkg_resources.py"...
37688 INFO: Processing pre-safe import module hook   win32com
37733 INFO: Loading module hook "hook-pandas.py"...
Segmentation fault: 11
```

Same error.

**Comment by prsolucoes** [comment]
Hi,

I have installed zeromq with:

```
brew install zeromq
```

But the segmentation fault happen:

```
60 INFO: PyInstaller: 4.0.dev0+269779f91
61 INFO: Python: 3.7.4
69 INFO: Platform: Darwin-18.7.0-x86_64-i386-64bit
70 INFO: wrote /Users/paulo/Developer/workspaces/python/UniqueBible/main.spec
72 INFO: UPX is not available.
73 INFO: Extending PYTHONPATH with paths
['/Users/paulo/Developer/workspaces/python/UniqueBible',
 '/Users/paulo/Developer/workspaces/python/UniqueBible']
73 INFO: checking Analysis
74 INFO: Building Analysis because Analysis-00.toc is non existent
74 INFO: Initializing module dependency graph...
78 INFO: Initializing module graph hooks...
81 INFO: Analyzing base_library.zip ...
2791 INFO: running Analysis Analysis-00.toc
2799 INFO: Caching module hooks...
2805 INFO: Analyzing /Users/paulo/Developer/workspaces/python/UniqueBible/main.py
3145 INFO: Processing pre-find module path hook   distutils
3390 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
5265 INFO: Processing pre-safe import module hook   six.moves
8921 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
9352 INFO: Processing pre-find module path hook   site
9352 INFO: site: retargeting to fake-dir '/usr/local/lib/python3.7/site-packages/PyInstaller/fake-modules'
36472 INFO: Loading module hooks...
36472 INFO: Loading module hook "hook-scipy.linalg.py"...
36473 INFO: Loading module hook "hook-zmq.py"...
/Users/paulo/Library/Python/3.7/lib/python/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:243:3: warning: code will never be executed [-Wunreachable-code]
  _cffi_check__zmq_msg_t(0);
  ^~~~~~~~~~~~~~~~~~~~~~
/Users/paulo/Library/Python/3.7/lib/python/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:276:3: warning: code will never be executed [-Wunreachable-code]
  _cffi_check__zmq_pollitem_t(0);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
39750 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
39977 INFO: Loading module hook "hook-sqlite3.py"...
40043 INFO: Loading module hook "hook-pkg_resources.py"...
40570 INFO: Processing pre-safe import module hook   win32com
40597 INFO: Loading module hook "hook-pandas.py"...
Segmentation fault: 11
```

And the dist folder is empty.

**Comment by prsolucoes** [comment]
Hi,

After a lot of searching i have updated the PySide2 to 5.13 and it work with develop version. But when i execute the app i get this error:

```
~/Developer/workspaces/python/UniqueBible/dist (master) $ ./main
Traceback (most recent call last):
  File "main.py", line 127, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "gui.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "gdown/__init__.py", line 12, in <module>
  File "pkg_resources/__init__.py", line 481, in get_distribution
  File "pkg_resources/__init__.py", line 357, in get_provider
  File "pkg_resources/__init__.py", line 900, in require
  File "pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'gdown' distribution was not found and is required by the application
[91126] Failed to execute script main
```

Can anyone help me?

**Comment by prsolucoes** [comment]
Now this is the problem:

```
./main
Traceback (most recent call last):
  File "main.py", line 126, in <module>
ImportError: dlopen(/var/folders/64/9s0r4g290ns84t9wbzj047qr0000gn/T/_MEIWerJEB/PySide2/QtWidgets.abi3.so, 2): Library not loaded: @loader_path/../QtWidgets
  Referenced from: /var/folders/64/9s0r4g290ns84t9wbzj047qr0000gn/T/_MEIWerJEB/PySide2/QtWidgets.abi3.so
  Reason: Incompatible library version: QtWidgets.abi3.so requires version 5.13.0 or later, but QtWidgets provides version 5.11.0
[93483] Failed to execute script main
```

**Comment by prsolucoes** [comment]
Hi,

This is crazy. Now when i execute i get:
```
./main
Traceback (most recent call last):
  File "main.py", line 127, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "gui.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "gdown/__init__.py", line 12, in <module>
  File "pkg_resources/__init__.py", line 481, in get_distribution
  File "pkg_resources/__init__.py", line 357, in get_provider
  File "pkg_resources/__init__.py", line 900, in require
  File "pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'gdown' distribution was not found and is required by the application
[95156] Failed to execute script main
```

**Comment by htgoebel** [comment]
This issue talks about very different problems. I suggest you to track this down to **a single error** and open en new issue for that.

This is not a forum, but a bug-tracker. When posting half-evaluated issues your are wasting out rare spare time - which is then missing to actually solve issues.

**Comment by prsolucoes** [comment]
Ok, created one:
https://github.com/pyinstaller/pyinstaller/issues/4361
