### ISSUE TITLE
Could not effectively use channels

### ISSUE THREAD

**Issue by pppigg** [pyinstaller/pyinstaller#4393]
This is the information when you package it:
```62 INFO: PyInstaller: 3.5
62 INFO: Python: 3.7.0
63 INFO: Platform: Windows-10-10.0.16299-SP0
69 INFO: UPX is not available.
70 INFO: Extending PYTHONPATH with paths
['C:\\Users\\76923\\Desktop\\project\\RecordConsole',
 'C:\\Users\\76923\\Desktop\\project\\RecordConsole']
70 INFO: checking Analysis
155 INFO: Building because pathex changed
155 INFO: Initializing module dependency graph...
160 INFO: Initializing module graph hooks...
162 INFO: Analyzing base_library.zip ...
2706 INFO: Analyzing hidden import 'channels.apps'
2765 INFO: Processing pre-find module path hook   distutils
2765 INFO: distutils: retargeting to non-venv dir 'd:\\py37\\Lib'
3622 INFO: Processing pre-find module path hook   site
3622 INFO: site: retargeting to fake-dir 'd:\\envs\\record\\lib\\site-packages\\PyInstaller\\fake-modules'
4782 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
9450 INFO: Processing pre-safe import module hook   six.moves
12037 INFO: Analyzing hidden import 'channels_redis'
12054 INFO: Analyzing hidden import 'RecordConsole.routing'
20799 INFO: Analyzing hidden import 'RecordConsole.urls'
21160 INFO: Analyzing hidden import 'standalone.urls'
21652 INFO: Analyzing hidden import 'commandset.urls'
21658 INFO: Analyzing hidden import 'corsheaders'
21681 INFO: Analyzing hidden import 'django_filters.apps'
21681 ERROR: Hidden import 'django_filters.apps' not found
21682 INFO: Analyzing hidden import 'django.contrib.admin.apps'
21685 INFO: Analyzing hidden import 'django.contrib.auth.apps'
21691 INFO: Analyzing hidden import 'django.contrib.contenttypes.apps'
21710 INFO: Analyzing hidden import 'django.contrib.messages.apps'
21712 INFO: Analyzing hidden import 'django.contrib.staticfiles.apps'
21715 INFO: Analyzing hidden import 'django.contrib.sessions.models'
21721 INFO: Analyzing hidden import 'django.contrib.sessions.apps'
21723 INFO: Analyzing hidden import 'django.contrib.messages.middleware'
21724 INFO: Analyzing hidden import 'django.contrib.auth.middleware'
21728 INFO: Analyzing hidden import 'django.contrib.sessions.middleware'
21731 INFO: Analyzing hidden import 'django.contrib.sessions.serializers'
21732 INFO: running Analysis Analysis-00.toc
21748 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\envs\record\scripts\python.exe
22846 INFO: Caching module hooks...
22852 INFO: Analyzing manage.py
22870 INFO: Loading module hooks...
22870 INFO: Loading module hook "hook-cryptography.py"...
23287 INFO: Loading module hook "hook-distutils.py"...
23288 INFO: Loading module hook "hook-django.contrib.sessions.py"...
23442 INFO: Loading module hook "hook-django.core.cache.py"...
23610 INFO: Loading module hook "hook-django.core.mail.py"...
23642 INFO: Loading module hook "hook-django.core.management.py"...
23659 INFO: Excluding import 'tkinter'
23662 INFO: Excluding import 'matplotlib'
23664 INFO: Excluding import 'IPython'
23667 INFO: Loading module hook "hook-django.db.backends.py"...
24203 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
24203 INFO: Loading module hook "hook-django.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "d:\envs\record\lib\site-packages\django\contrib\gis\admin\__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "d:\envs\record\lib\site-packages\django\contrib\gis\admin\options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "d:\envs\record\lib\site-packages\django\contrib\gis\admin\widgets.py", line 3, in <module>
    from django.contrib.gis.gdal import GDALException
  File "d:\envs\record\lib\site-packages\django\contrib\gis\gdal\__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "d:\envs\record\lib\site-packages\django\contrib\gis\gdal\datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "d:\envs\record\lib\site-packages\django\contrib\gis\gdal\driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "d:\envs\record\lib\site-packages\django\contrib\gis\gdal\prototypes\ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "d:\envs\record\lib\site-packages\django\contrib\gis\gdal\libgdal.py", line 43, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal203", "gdal202", "gdal201", "gdal20", "gdal111"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
25572 INFO: Determining a mapping of distributions to packages...
33744 INFO: Packages required by django:
['pytz', 'sqlparse']
33751 INFO: Django root directory C:\Users\76923\Desktop\project\RecordConsole\RecordConsole
Traceback (most recent call last):
  File "d:\envs\record\lib\site-packages\PyInstaller\utils\hooks\subproc\django_import_finder.py", line 37, in <module>
    list(settings.TEMPLATE_LOADERS) + \
  File "d:\envs\record\lib\site-packages\django\conf\__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'
35008 INFO: Collecting Django migration scripts.
37383 INFO: Loading module hook "hook-encodings.py"...
37566 INFO: Loading module hook "hook-IPython.py"...
37576 INFO: Excluding import 'tkinter'
37580 INFO:   Removing import of tkinter from module IPython.lib.clipboard
37581 INFO: Import to be excluded not found: 'PyQt5'
37582 INFO: Import to be excluded not found: 'PySide'
37582 INFO: Excluding import 'matplotlib'
37587 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
37587 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
37588 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
37589 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
37590 INFO: Import to be excluded not found: 'PyQt4'
37591 INFO: Import to be excluded not found: 'gtk'
37591 INFO: Loading module hook "hook-jedi.py"...
37706 INFO: Loading module hook "hook-lib2to3.py"...
37711 INFO: Loading module hook "hook-matplotlib.backends.py"...
38313 INFO:   Matplotlib backend "GTK3Agg": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
38678 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
39136 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx' from 'matplotlib.backends' (d:\envs\record\lib\site-packages\matplotlib\backends\__init__.py)
d:\envs\record\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
40393 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'ipykernel'
40772 INFO:   Matplotlib backend "Qt4Agg": ignored
    Failed to import any qt binding
41124 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
41495 INFO:   Matplotlib backend "Qt5Agg": ignored
    Failed to import any qt binding
41870 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
42334 INFO:   Matplotlib backend "TkAgg": added
42789 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
43137 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "d:\envs\record\lib\site-packages\matplotlib\backends\backend_webagg.py", line 26, in <module>
    import tornado
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "d:\envs\record\lib\site-packages\matplotlib\backends\backend_webagg.py", line 28, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
43571 INFO:   Matplotlib backend "WX": ignored
    No module named 'wx'
43918 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
44270 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
44633 INFO:   Matplotlib backend "agg": added
45078 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
45549 INFO:   Matplotlib backend "pdf": added
46003 INFO:   Matplotlib backend "pgf": added
46363 INFO:   Matplotlib backend "ps": added
46746 INFO:   Matplotlib backend "svg": added
47187 INFO:   Matplotlib backend "template": added
47424 INFO: Loading module hook "hook-matplotlib.py"...
47677 INFO: Loading module hook "hook-numpy.core.py"...
47735 INFO: Loading module hook "hook-numpy.py"...
47736 INFO: Loading module hook "hook-pkg_resources.py"...
48075 INFO: Processing pre-safe import module hook   win32com
48340 INFO: Loading module hook "hook-pycparser.py"...
48340 INFO: Loading module hook "hook-pydoc.py"...
48342 INFO: Loading module hook "hook-pygments.py"...
49907 INFO: Loading module hook "hook-pythoncom.py"...
50236 INFO: Loading module hook "hook-pytz.py"...
50292 INFO: Loading module hook "hook-pywintypes.py"...
50632 INFO: Loading module hook "hook-setuptools.py"...
51215 INFO: Loading module hook "hook-sqlite3.py"...
51358 INFO: Loading module hook "hook-sysconfig.py"...
51359 INFO: Loading module hook "hook-win32com.py"...
51671 INFO: Loading module hook "hook-xml.dom.domreg.py"...
51672 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
51674 INFO: Loading module hook "hook-xml.py"...
51675 INFO: Loading module hook "hook-_tkinter.py"...
52022 INFO: checking Tree
52067 INFO: checking Tree
52078 INFO: Loading module hook "hook-asgiref.py"...
52285 INFO: Loading module hook "hook-channels.py"...
d:\envs\record\lib\site-packages\daphne\server.py:14: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
  UserWarning,
53306 INFO: Loading module hook "hook-channels_redis.py"...
53661 INFO: Loading module hook "hook-commandset.py"...
53818 INFO: Loading module hook "hook-corsheaders.py"...
53969 INFO: Loading module hook "hook-daphne.py"...
54142 INFO: Loading module hook "hook-rest_framework.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 20, in walk_packages
  File "d:\envs\record\lib\site-packages\rest_framework\schemas\__init__.py", line 32, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "d:\envs\record\lib\site-packages\rest_framework\settings.py", line 220, in __getattr__
    val = self.user_settings[attr]
  File "d:\envs\record\lib\site-packages\rest_framework\settings.py", line 211, in user_settings
    self._user_settings = getattr(settings, 'REST_FRAMEWORK', {})
  File "d:\envs\record\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "d:\envs\record\lib\site-packages\django\conf\__init__.py", line 64, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting REST_FRAMEWORK, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
55050 INFO: Loading module hook "hook-standalone.py"...
55300 INFO: Loading module hook "hook-django.db.backends.mysql.base.py"...
55303 INFO: Loading module hook "hook-django.db.backends.oracle.base.py"...
55422 INFO: Looking for ctypes DLLs
55482 WARNING: library riffa.dll required via ctypes not found
55540 INFO: Analyzing run-time hooks ...
55557 INFO: Including run-time hook 'pyi_rth_twisted.py'
55559 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
55561 INFO: Including run-time hook 'pyi_rth_mpldata.py'
55563 INFO: Including run-time hook 'pyi_rth_traitlets.py'
55565 INFO: Including run-time hook 'pyi_rth__tkinter.py'
55567 INFO: Including run-time hook 'pyi_rth_django.py'
55570 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
55573 INFO: Including run-time hook 'pyi_rth_pkgres.py'
55575 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
55613 INFO: Looking for dynamic libraries
70024 INFO: Looking for eggs
70024 INFO: Using Python library d:\envs\record\scripts\python37.dll
70026 INFO: Found binding redirects:
[]
70094 INFO: Warnings written to C:\Users\76923\Desktop\project\RecordConsole\build\manage\warn-manage.txt
70464 INFO: Graph cross-reference written to C:\Users\76923\Desktop\project\RecordConsole\build\manage\xref-manage.html
70726 INFO: checking PYZ
70746 INFO: Building because toc changed
70746 INFO: Building PYZ (ZlibArchive) C:\Users\76923\Desktop\project\RecordConsole\build\manage\PYZ-00.pyz
74455 INFO: Building PYZ (ZlibArchive) C:\Users\76923\Desktop\project\RecordConsole\build\manage\PYZ-00.pyz completed successfully.
74515 INFO: checking PKG
74515 INFO: Building because PKG-00.toc is bad
74515 INFO: Building PKG (CArchive) PKG-00.pkg
74546 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
74548 INFO: Bootloader d:\envs\record\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
74549 INFO: checking EXE
74550 INFO: Building because toc changed
74551 INFO: Building EXE from EXE-00.toc
74553 INFO: Appending archive to EXE C:\Users\76923\Desktop\project\RecordConsole\build\manage\manage.exe
74564 INFO: Building EXE from EXE-00.toc completed successfully.
74577 INFO: checking COLLECT
WARNING: The output directory "C:\Users\76923\Desktop\project\RecordConsole\dist\manage" and ALL ITS CONTENTS will be REMOVED! Continue? (y/N)y
136369 INFO: Removing dir C:\Users\76923\Desktop\project\RecordConsole\dist\manage
142729 INFO: Building COLLECT COLLECT-00.toc
165209 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

[#4002](https://github.com/pyinstaller/pyinstaller/issues/4002)The same problem follows...
Does a packaging error affect the process..

**Comment by sumanth-manchala** [comment]
Same issue here. Any Fix?

**Comment by soufisouf** [comment]
Same issue. Any fix please?

**Comment by bwoodsend** [comment]
None of you have actually said what the issue is. Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) so we know what you're talking about.
