### ISSUE TITLE
Security-Alert: try to store file outside of dist-directory on Msys2

### ISSUE THREAD

**Issue by welitonfreitas** [pyinstaller/pyinstaller#4402]
Error on rum example above in msys2.

teste.py
```python
  import gevent
  from gevent.queue import Queue
```
Result:
```python
984 INFO: PyInstaller: 3.5
1000 INFO: Python: 3.7.4
1000 INFO: Platform: Windows-10-10.0.18362-SP0
1000 INFO: wrote Y:/dev/se7e-Installer/teste.spec
1000 INFO: UPX is not available.
1000 INFO: Removing temporary files and cleaning cache in C:\Users\notilew\AppData\Roaming/pyinstaller
1031 INFO: Extending PYTHONPATH with paths
['Y:/dev/se7e-Installer', 'Y:/dev/se7e-Installer']
1031 INFO: checking Analysis
1031 INFO: Building Analysis because Analysis-00.toc is non existent
1031 INFO: Initializing module dependency graph...
1046 INFO: Initializing module graph hooks...
1062 INFO: Analyzing base_library.zip ...
6390 INFO: running Analysis Analysis-00.toc
6437 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:/msys32/mingw32/bin/python3.exe
6593 INFO: Caching module hooks...
6593 INFO: Analyzing Y:/dev/se7e-Installer/teste.py
7515 INFO: Processing pre-safe import module hook   six.moves
7687 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
7844 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
8093 INFO: Processing pre-find module path hook   distutils
8281 INFO: Processing pre-find module path hook   site
8281 INFO: site: retargeting to fake-dir 'C:/msys32/mingw32/lib/python3.7/site-packages/PyInstaller/fake-modules'
17359 INFO: Loading module hooks...
17359 INFO: Loading module hook "hook-appdirs.py"...
17374 INFO: Import to be excluded not found: 'win32com'
17374 INFO: Loading module hook "hook-distutils.py"...
17390 INFO: Loading module hook "hook-encodings.py"...
17578 INFO: Loading module hook "hook-gevent.py"...
18500 INFO: Determining a mapping of distributions to packages...
65984 WARNING: Unable to find package for requirement greenlet from package gevent.
65984 INFO: Packages required by gevent:
['cffi']
66937 WARNING: Hidden import "gevent.__greenlet_primitives" not found!
67953 WARNING: Hidden import "gevent._queue" not found!
68078 WARNING: Hidden import "gevent.__semaphore" not found!
68390 WARNING: Hidden import "gevent.resolver.cares" not found!
68390 WARNING: Hidden import "gevent.__abstract_linkable" not found!
68671 WARNING: Hidden import "gevent._greenlet" not found!
68765 WARNING: Hidden import "gevent.libev.corecext" not found!
68985 WARNING: Hidden import "gevent._event" not found!
69078 WARNING: Hidden import "gevent.__hub_local" not found!
69187 WARNING: Hidden import "gevent.__ident" not found!
69218 WARNING: Hidden import "gevent.__tracer" not found!
69218 WARNING: Hidden import "gevent.__hub_primitives" not found!
69218 WARNING: Hidden import "gevent.__waiter" not found!
69359 WARNING: Hidden import "gevent.__imap" not found!
69468 WARNING: Hidden import "gevent._local" not found!
69562 INFO: Loading module hook "hook-lib2to3.py"...
69562 INFO: Loading module hook "hook-pkg_resources.py"...
69578 INFO: Loading module hook "hook-pycparser.py"...
69578 INFO: Loading module hook "hook-pydoc.py"...
69593 INFO: Loading module hook "hook-setuptools.py"...
70188 INFO: Loading module hook "hook-sysconfig.py"...
70203 INFO: Loading module hook "hook-xml.dom.domreg.py"...
70203 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
70218 INFO: Loading module hook "hook-xml.py"...
70266 INFO: Looking for ctypes DLLs
70328 INFO: Analyzing run-time hooks ...
70328 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
70344 INFO: Including run-time hook 'pyi_rth_pkgres.py'
70359 INFO: Looking for dynamic libraries
70828 INFO: Looking for eggs
70828 INFO: Using Python library c:/msys32/mingw32/bin/libpython3.7m.dll
70828 INFO: Found binding redirects:
[]
70843 INFO: Warnings written to Y:/dev/se7e-Installer/build/teste/warn-teste.txt
71047 INFO: Graph cross-reference written to Y:/dev/se7e-Installer/build/teste/xref-teste.html
71124 INFO: checking PYZ
71140 INFO: Building PYZ because PYZ-00.toc is non existent
71140 INFO: Building PYZ (ZlibArchive) Y:/dev/se7e-Installer/build/teste/PYZ-00.pyz
74968 INFO: Building PYZ (ZlibArchive) Y:/dev/se7e-Installer/build/teste/PYZ-00.pyz completed successfully.
75031 INFO: checking PKG
75031 INFO: Building PKG because PKG-00.toc is non existent
75031 INFO: Building PKG (CArchive) PKG-00.pkg
75187 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
75203 INFO: Bootloader C:/msys32/mingw32/lib/python3.7/site-packages/PyInstaller/bootloader/Windows-32bit/run.exe
75203 INFO: checking EXE
75203 INFO: Building EXE because EXE-00.toc is non existent
75203 INFO: Building EXE from EXE-00.toc
75203 INFO: Appending archive to EXE Y:/dev/se7e-Installer/build/teste/teste.exe
75468 INFO: Building EXE from EXE-00.toc completed successfully.
75484 INFO: checking COLLECT
75484 INFO: Building COLLECT because COLLECT-00.toc is non existent
75484 INFO: Building COLLECT COLLECT-00.toc
Security-Alert: try to store file outside of dist-directory. Aborting. 'C:/msys32/mingw32/lib/python3.7/site-packages/gevent/_queue-cpython-37m.dll'

```

workaround on utils\hooks\init.py on line 319.
```python
    try:
        loader = pkgutil.find_loader(package)
        attr = loader.get_filename(package).replace('\\', '/')
```

**Comment by htgoebel** [comment]
Thansk for reporting this. Looks like you already tracked this down as you are proposing a solution. Can you please explain this a bit more in detail:
- That wrong path to you get?
- Where exaclty does this wrong path come from? Is it inside PyInstaller? Is this caused by Msys2?
- Why does changing the path separator from Winodws-style (backslash) to Unix-Style (slash) fix this?
- Would this code work too (which might handle possible backslash-escapes):
```
attr = os.path.join(*os.path.split(loader.get_filename(package))
```

**Comment by apockill** [comment]
Hi! I was wondering if this is something that has been fixed in the develop version of pyinstaller?
