### ISSUE TITLE
MacOS Illegal instruction: 4

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4412]
I'm facing a similar issue as this #2249, when building on one machine it is working perfectly but when copied to another it is giving me the `Illegal instruction: 4` error.

My Python version is the official python downloaded from the Python website.

I want to be able to create a portable app for all MacOS versions, some of my scripts are working on different machines, is it a specific module that can cause this? 

Build on `macOS 10.13.6`
Run on `macOS 10.12.6`
PyInstaller: 3.5
Python: 2.7.16

Tested it with `pyenv` now and I'm getting a different error:
```ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_certifi.py", line 11, in <module>
  File "/private/var/folders/58/hb00vzxn1hj2sbrcdppkvz640000gn/T/pip-install-RnrUCU/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "ssl.py", line 98, in <module>
  File "/private/var/folders/58/hb00vzxn1hj2sbrcdppkvz640000gn/T/pip-install-RnrUCU/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 684, in load_module
ImportError: dlopen(/Users/safebreach/updater/_ssl.so, 2): Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Users/safebreach/updater/libcrypto.1.0.0.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/safebreach/updater/libcrypto.1.0.0.dylib
[21048] Failed to execute script pyi_rth_certifi
```

Are the Mac builds not backward compatible like Linux and `glibc`? Do I have to build on the oldest version that I want to support?

**Comment by atvKumar** [comment]
Coming from my mac experience, you need to build on 10.12 and lower

**Comment by arossert** [comment]
Thanks, so when building with Pyinstaller the oldest is supported it the one that is used for the build?
Will I experience any forward compatibility?

**Comment by atvKumar** [comment]
I am sorry to say the oldest does not support forward, too many changes on mac for it. So you have to maintain different build systems, or have your clients update to a minimum version.
I had to go through a simillar situation recently, and had a real headache when i found this out.

**Comment by arossert** [comment]
Oh, this is quite disappointing, maintaining different builds will be hard. 
I really want to support all versions but it will be enough to support the latest 3 (Sierra, High-sierra and Mojave), is this possible to do in one build?

**Comment by atvKumar** [comment]
10.12 and above should be ok, you can build on Mojave and it will be compatible till 10.12.6. But anything lower example 10.12.4 (boom you break), you need another build setup (Crazy, yes i know but thats the reality, as i have tried it myself). This is excluding your third party libs, that is another whole story.

Overall, it seems best to switch out to a web app using GO or move over to C++ or JAVA. (Oh the shudder! i know, but i am seriously considering, since the lack of packaging stuff in python)

Oh and by the way, i am slowly moving over to numba for packaging. You might want to try it out as opposed to pyinstaller.

**Comment by BoboTiG** [comment]
FTR you only need to build on 10.12 and it will work fine on 10.12 and newer. Only one build is needed ;)
