### ISSUE TITLE
Update hook for pendulum (Import error: pendulum.locales)

### ISSUE THREAD

**Issue by mrBoomDev** [pyinstaller/pyinstaller#4414]
```
Traceback (most recent call last):
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.5', 'console_scripts', 'pyinstaller')()
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\ilegit\Desktop\dokkan-battle-bot-master\dokkan.spec", line 17, in <module>
    noarchive=False)
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 502, in assemble
    module_hook.post_graph()
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\compat.py", line 793, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\hooks\hook-pendulum.py", line 16, in <module>
    datas = collect_data_files("pendulum.locales", include_py_files=True)
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 721, in collect_data_files
    pkg_base, pkg_dir = get_package_paths(package)
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 535, in get_package_paths
    file_attr = get_module_file_attribute(package)
  File "C:\Users\ilegit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 337, in get_module_file_attribute
    raise ImportError
ImportError
```

**Comment by Seggan** [comment]
Did you use the --onefile option?

**Comment by htgoebel** [comment]
This looks like the hook for `pendulum` is incompatible with the version of pendulum you are using.

What version of pendulum are you using? Is it a current version? Is there a module `pendulum.locales` in your version of pendulum`?


We would appreciate if you'd submit a pull-request for an updated hook `pendulum`, which handles the case this file is not existing. You might want to use `is_module_sadisfies() to check for the version of pendulum  within the hook.

See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.
