### ISSUE TITLE
Packaging QGIS standalone app

### ISSUE THREAD

**Issue by Djedouas** [pyinstaller/pyinstaller#4421]
Hi,
Maybe it's not a pyinstaller issue, but I give a try:

This is a problem when running the packaged app, after running `pyinstaller --noupx main.py`
The error message is:

```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from qgis.gui import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Program Files\QGIS 3.4\apps\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "qgis\gui\__init__.py", line 27, in <module>
RuntimeError: qgis._gui cannot import type '����' from PyQt5.QtCore
[1596] Failed to execute script main
```

Environment:
--------------

- Windows 10
- QGIS 3.4 ltr packaged with python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Steps to reproduce:
--------------------

- Install QGIS 3.4 from [here](https://qgis.org/downloads/QGIS-OSGeo4W-3.4.11-1-Setup-x86_64.exe)
- adapt the QGIS installation path in `reproduce-issue-qgis.bat` attached file 
- open a command line window and `call reproduce-issue-qgis.bat` that will:
    - setup the environment
    - create the python minimal script
    - call pyinstaller
    - call the dist app

[reproduce-issue-qgis.txt](https://github.com/pyinstaller/pyinstaller/files/3589545/reproduce-issue-qgis.txt)

**Comment by Djedouas** [comment]
When QGIS installed from miniconda environment (conda-forge channel), everything works fine
