### ISSUE TITLE
Is there a way, how to instruct pyinstaller to not use some package (cffi) during freezing?

### ISSUE THREAD

**Issue by zdenop** [pyinstaller/pyinstaller#4435]
Hello,

my problem is that pyinstaller fails on windows for one of my projects. I found out that when I uninstall cffi package, pyinstaller create successfully my application (this application does not use cffi, so I have no clue, why it is used in build process). 
So I would like to use pyinstaller without need to uninstall cffi package (and than to re-install it). Is there a way, how to instruct pyinstaller to not use some package (cffi) during freezing?

Root of the problem is not in cffi, but in [pycparser](https://github.com/eliben/pycparser/issues/291). Putting cffi&pycparser to excludes does not helped.

For record: pyinstaller produce this error:
```
C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:20: RuntimeWarning: parsing methods must have __doc__ for pycparser to work properly
  class CParser(PLYParser):
WARNING: There was a problem loading the table file: KeyError('p_direct_id_declarator_1',)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:513: No documentation string specified in function 'p_translation_unit_or_empty' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:522: No documentation string specified in function 'p_translation_unit_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:529: No documentation string specified in function 'p_translation_unit_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:541: No documentation string specified in function 'p_external_declaration_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:546: No documentation string specified in function 'p_external_declaration_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:551: No documentation string specified in function 'p_external_declaration_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:557: No documentation string specified in function 'p_external_declaration_4' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:562: No documentation string specified in function 'p_pp_directive' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:568: No documentation string specified in function 'p_pppragma_directive' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:580: No documentation string specified in function 'p_function_definition_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:597: No documentation string specified in function 'p_function_definition_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:608: No documentation string specified in function 'p_statement' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:661: No documentation string specified in function 'p_pragmacomp_or_statement' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:681: No documentation string specified in function 'p_decl_body' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:741: No documentation string specified in function 'p_declaration' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:750: No documentation string specified in function 'p_declaration_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:761: No documentation string specified in function 'p_declaration_specifiers_no_type_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:766: No documentation string specified in function 'p_declaration_specifiers_no_type_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:771: No documentation string specified in function 'p_declaration_specifiers_no_type_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:777: No documentation string specified in function 'p_declaration_specifiers_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:782: No documentation string specified in function 'p_declaration_specifiers_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:787: No documentation string specified in function 'p_declaration_specifiers_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:792: No documentation string specified in function 'p_declaration_specifiers_4' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:797: No documentation string specified in function 'p_declaration_specifiers_5' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:802: No documentation string specified in function 'p_declaration_specifiers_6' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:808: No documentation string specified in function 'p_storage_class_specifier' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:817: No documentation string specified in function 'p_function_specifier' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:822: No documentation string specified in function 'p_type_specifier_no_typeid' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:838: No documentation string specified in function 'p_type_specifier' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:846: No documentation string specified in function 'p_type_qualifier' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:853: No documentation string specified in function 'p_init_declarator_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:862: No documentation string specified in function 'p_init_declarator' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:868: No documentation string specified in function 'p_id_init_declarator_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:874: No documentation string specified in function 'p_id_init_declarator' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:882: No documentation string specified in function 'p_specifier_qualifier_list_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:887: No documentation string specified in function 'p_specifier_qualifier_list_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:892: No documentation string specified in function 'p_specifier_qualifier_list_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:897: No documentation string specified in function 'p_specifier_qualifier_list_4' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:906: No documentation string specified in function 'p_struct_or_union_specifier_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:917: No documentation string specified in function 'p_struct_or_union_specifier_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:935: No documentation string specified in function 'p_struct_or_union_specifier_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:954: No documentation string specified in function 'p_struct_or_union' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:962: No documentation string specified in function 'p_struct_declaration_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:971: No documentation string specified in function 'p_struct_declaration_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1009: No documentation string specified in function 'p_struct_declaration_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1014: No documentation string specified in function 'p_struct_declaration_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1019: No documentation string specified in function 'p_struct_declarator_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1028: No documentation string specified in function 'p_struct_declarator_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1033: No documentation string specified in function 'p_struct_declarator_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1042: No documentation string specified in function 'p_enum_specifier_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1048: No documentation string specified in function 'p_enum_specifier_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1053: No documentation string specified in function 'p_enum_specifier_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1059: No documentation string specified in function 'p_enumerator_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1072: No documentation string specified in function 'p_enumerator' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1088: No documentation string specified in function 'p_declarator' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1200: No documentation string specified in function 'p_pointer' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1230: No documentation string specified in function 'p_type_qualifier_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1236: No documentation string specified in function 'p_parameter_type_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1245: No documentation string specified in function 'p_parameter_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1265: No documentation string specified in function 'p_parameter_declaration_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1277: No documentation string specified in function 'p_parameter_declaration_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1308: No documentation string specified in function 'p_identifier_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1318: No documentation string specified in function 'p_initializer_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1323: No documentation string specified in function 'p_initializer_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1332: No documentation string specified in function 'p_initializer_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1344: No documentation string specified in function 'p_designation' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1352: No documentation string specified in function 'p_designator_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1358: No documentation string specified in function 'p_designator' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1364: No documentation string specified in function 'p_type_name' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1375: No documentation string specified in function 'p_abstract_declarator_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1383: No documentation string specified in function 'p_abstract_declarator_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1388: No documentation string specified in function 'p_abstract_declarator_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1398: No documentation string specified in function 'p_direct_abstract_declarator_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1402: No documentation string specified in function 'p_direct_abstract_declarator_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1413: No documentation string specified in function 'p_direct_abstract_declarator_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1422: No documentation string specified in function 'p_direct_abstract_declarator_4' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1433: No documentation string specified in function 'p_direct_abstract_declarator_5' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1442: No documentation string specified in function 'p_direct_abstract_declarator_6' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1452: No documentation string specified in function 'p_direct_abstract_declarator_7' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1463: No documentation string specified in function 'p_block_item' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1471: No documentation string specified in function 'p_block_item_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1478: No documentation string specified in function 'p_compound_statement_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1484: No documentation string specified in function 'p_labeled_statement_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1488: No documentation string specified in function 'p_labeled_statement_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1492: No documentation string specified in function 'p_labeled_statement_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1496: No documentation string specified in function 'p_selection_statement_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1500: No documentation string specified in function 'p_selection_statement_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1504: No documentation string specified in function 'p_selection_statement_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1509: No documentation string specified in function 'p_iteration_statement_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1513: No documentation string specified in function 'p_iteration_statement_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1517: No documentation string specified in function 'p_iteration_statement_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1521: No documentation string specified in function 'p_iteration_statement_4' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1526: No documentation string specified in function 'p_jump_statement_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1530: No documentation string specified in function 'p_jump_statement_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1534: No documentation string specified in function 'p_jump_statement_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1538: No documentation string specified in function 'p_jump_statement_4' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1544: No documentation string specified in function 'p_expression_statement' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1551: No documentation string specified in function 'p_expression' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1564: No documentation string specified in function 'p_typedef_name' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1568: No documentation string specified in function 'p_assignment_expression' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1582: No documentation string specified in function 'p_assignment_operator' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1597: No documentation string specified in function 'p_constant_expression' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1601: No documentation string specified in function 'p_conditional_expression' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1610: No documentation string specified in function 'p_binary_expression' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1636: No documentation string specified in function 'p_cast_expression_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1640: No documentation string specified in function 'p_cast_expression_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1644: No documentation string specified in function 'p_unary_expression_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1648: No documentation string specified in function 'p_unary_expression_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1655: No documentation string specified in function 'p_unary_expression_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1664: No documentation string specified in function 'p_unary_operator' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1674: No documentation string specified in function 'p_postfix_expression_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1678: No documentation string specified in function 'p_postfix_expression_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1682: No documentation string specified in function 'p_postfix_expression_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1688: No documentation string specified in function 'p_postfix_expression_4' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1697: No documentation string specified in function 'p_postfix_expression_5' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1703: No documentation string specified in function 'p_postfix_expression_6' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1709: No documentation string specified in function 'p_primary_expression_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1713: No documentation string specified in function 'p_primary_expression_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1717: No documentation string specified in function 'p_primary_expression_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1723: No documentation string specified in function 'p_primary_expression_4' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1727: No documentation string specified in function 'p_primary_expression_5' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1735: No documentation string specified in function 'p_offsetof_member_designator' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1750: No documentation string specified in function 'p_argument_expression_list' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1760: No documentation string specified in function 'p_identifier' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1764: No documentation string specified in function 'p_constant_1' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1773: No documentation string specified in function 'p_constant_2' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1790: No documentation string specified in function 'p_constant_3' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1802: No documentation string specified in function 'p_unified_string_literal' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1813: No documentation string specified in function 'p_unified_wstring_literal' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1824: No documentation string specified in function 'p_brace_open' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1830: No documentation string specified in function 'p_brace_close' (ignored)
WARNING: C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py:1836: No documentation string specified in function 'p_empty' (ignored)
ERROR: start symbol translation_unit_or_empty undefined
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python36\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\__init__.py", line 16, in <module>
    from . import compat
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\compat.py", line 245, in <module>
    from win32ctypes.pywin32 import pywintypes  # noqa: F401
  File "C:\Program Files\Python36\lib\site-packages\win32ctypes\pywin32\__init__.py", line 11, in <module>
    from win32ctypes.pywin32 import win32api
  File "C:\Program Files\Python36\lib\site-packages\win32ctypes\pywin32\win32api.py", line 12, in <module>
    from win32ctypes.core import (
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Program Files\Python36\lib\site-packages\win32ctypes\core\__init__.py", line 36, in load_module
    module = importlib.import_module(self.redirect_module)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files\Python36\lib\site-packages\win32ctypes\core\cffi\_common.py", line 12, in <module>
    from ._util import ffi
  File "C:\Program Files\Python36\lib\site-packages\win32ctypes\core\cffi\_util.py", line 17, in <module>
    ffi.set_unicode(True)
  File "C:\Program Files\Python36\lib\site-packages\cffi\api.py", line 556, in set_unicode
    self.cdef("typedef wchar_t TBYTE;"
  File "C:\Program Files\Python36\lib\site-packages\cffi\api.py", line 112, in cdef
    self._cdef(csource, override=override, packed=packed, pack=pack)
  File "C:\Program Files\Python36\lib\site-packages\cffi\api.py", line 126, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "C:\Program Files\Python36\lib\site-packages\cffi\cparser.py", line 347, in parse
    self._internal_parse(csource)
  File "C:\Program Files\Python36\lib\site-packages\cffi\cparser.py", line 352, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "C:\Program Files\Python36\lib\site-packages\cffi\cparser.py", line 294, in _parse
    ast = _get_parser().parse(fullcsource)
  File "C:\Program Files\Python36\lib\site-packages\cffi\cparser.py", line 52, in _get_parser
    _parser_cache = pycparser.CParser()
  File "C:\Program Files\Python36\lib\site-packages\pycparser\c_parser.py", line 117, in __init__
    outputdir=taboutputdir)
  File "C:\Program Files\Python36\lib\site-packages\pycparser\ply\yacc.py", line 3352, in yacc
    raise YaccError('Unable to build parser')
pycparser.ply.yacc.YaccError: Unable to build parser
```

**Comment by bjones1** [comment]
Create a venv, install PyInstaller and only the libs you want to package. Then cffi (and whatever else you don't want) won't be packaged.

**Comment by zdenop** [comment]
Thanks. Yes, this help.
