### ISSUE TITLE
window installing fail

### ISSUE THREAD

**Issue by aligoglos** [pyinstaller/pyinstaller#4444]
I tried to install `pyinstaller `with command `pip install pyinstaller` but this error occurred:
```
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\127051\appdata\local\programs\python\python35\python.exe' 'c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\127051\AppData\Local\Temp\pip-build-env-z85bnzw_\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (31 lines):
  Traceback (most recent call last):
    File "c:\users\127051\appdata\local\programs\python\python35\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\users\127051\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\__init__.py", line 40, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\cli\autocompletion.py", line 8, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\cli\main_parser.py", line 11, in <module>
      from pip._internal.commands import (
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\commands\__init__.py", line 6, in <module>
      from pip._internal.commands.completion import CompletionCommand
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\commands\completion.py", line 6, in <module>
      from pip._internal.cli.base_command import Command
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\cli\base_command.py", line 26, in <module>
      from pip._internal.index import PackageFinder
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\index.py", line 38, in <module>
      from pip._internal.wheel import Wheel
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\wheel.py", line 7, in <module>
      import compileall
    File "c:\users\127051\appdata\local\programs\python\python35\lib\compileall.py", line 20, in <module>
      from concurrent.futures import ProcessPoolExecutor
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\concurrent\futures\_base.py", line 381
      raise exception_type, self._exception, self._traceback
                          ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\127051\appdata\local\programs\python\python35\python.exe' 'c:\users\127051\appdata\local\programs\python\python35\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\127051\AppData\Local\Temp\pip-build-env-z85bnzw_\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by danyeaw** [comment]
@aligoglos I think there has to be something messed up with your environment. Are you using a [virtual environment](https://docs.python.org/3/tutorial/venv.html)? It looks like you are using a [backport](https://github.com/agronholm/pythonfutures) of concurrent.futures to Python2. The syntax error is showing Python2 syntax in Python 3.5 site-packages. I don't think this is a PyInstaller issue.

**Comment by aligoglos** [comment]
I couldn't install it on python 3.5.4 and I have no idea why. but I install it on python 3.8 successfully.
