### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by goog** [pyinstaller/pyinstaller#4449]
19555 INFO: Including run-time hook 'pyi_rth_mpldata.py'
19555 INFO: Including run-time hook 'pyi_rth__tkinter.py'
19569 INFO: Looking for dynamic libraries
20664 INFO: Looking for eggs
20665 INFO: Using Python library C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python37.dll
20665 INFO: Found binding redirects:
[]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\PycharmProjects\uxdar\venv\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\pycharmprojects\uxdar\venv\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\administrator\pycharmprojects\uxdar\venv\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\administrator\pycharmprojects\uxdar\venv\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\administrator\pycharmprojects\uxdar\venv\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "main.spec", line 23, in <module>
    noarchive=True)
  File "c:\users\administrator\pycharmprojects\uxdar\venv\lib\site-packages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "c:\users\administrator\pycharmprojects\uxdar\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\administrator\pycharmprojects\uxdar\venv\lib\site-packages\PyInstaller\building\build_main.py", line 597, in assemble
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):
  File "c:\users\administrator\pycharmprojects\uxdar\venv\lib\site-packages\PyInstaller\utils\misc.py", line 150, in compile_py_files
    with open(obj_fnm, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\administrator\\pycharmprojects\\uxdar\\venv\\lib\\site-packages\\setuptools-40.8.0-py3.7.egg\\pkg_resources\\__init__.py
o'

(venv) C:\Users\Administrator\PycharmProjects\uxdar>

**Comment by goog** [comment]
![2525](https://user-images.githubusercontent.com/1488374/65687528-17c7c980-e09c-11e9-95a3-64814ab53c3d.png)

**Comment by danyeaw** [comment]
@goog This sounds like an issue with your virtualenv to me, not with pyinstaller. Does the `setuptools-40.8.0-py3.7.egg\pkg_resources\init.py` file exist in your virtualenv? What are you trying to package?

**Comment by goog** [comment]
tinker

**Comment by deshpandeyash** [comment]
I found that for me the naming of the lib folder was the problem. My Lib folder was named with a capital 'L' while the import was searching for the site-packages withing the folder lib.
