### ISSUE TITLE
Failed to execute script 

### ISSUE THREAD

**Issue by MohamadZohoori** [pyinstaller/pyinstaller#4454]
Hi,

I have tried all of the solutions written on pyinstaller website and github. But still face the "failed to execute script " error

my python version is 3.7.3
I have installed the latet version of pyinstaller from github

The Error:

(base) C:\Users\lenovo\Desktop\GUI of Scanner\dist\code2>code2.exe
Traceback (most recent call last):
  File "code2.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\lenovo\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\lenovo\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\base.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\lenovo\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\units.py", line 15, in <module>
  File "site-packages\trimesh\resources\__init__.py", line 20, in get_resource
  File "site-packages\pkg_resources\__init__.py", line 1157, in resource_string
  File "site-packages\pkg_resources\__init__.py", line 1401, in get_resource_str
ing
  File "site-packages\pkg_resources\__init__.py", line 1560, in _get
  File "c:\users\lenovo\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 469, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lenovo\\Desk
top\\GUI of Scanner\\dist\\code2\\trimesh\\resources\\units_to_inches.json'
[8200] Failed to execute script code2

Thanks in advance for your help

**Comment by MohamadZohoori** [comment]
b1 = QtWidgets.QRadioButton("Right")
        b1.toggled.connect(lambda:self.btnstate(self,b1))
        
        b2 = QtWidgets.QRadioButton("Left")
        b2.toggled.connect(lambda:self.btnstate(self,b2))

**Comment by lkollar** [comment]
You are attempting to open a file (`units_to_inches.json`) which does not exist in the created package, or is not where you expect it to be. Check the documentation on [adding data files](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-data-files) on how to do this correctly. I recommend using `pkgutil.get_data` to load the resource once you successfully packaged it.

Feel free to reopen if this doesn't solve your issue.

**Comment by MohamadZohoori** [comment]
Hi,

units_to_inches.json was related to a package called trimesh. Since that time I have changed my code a bit and I don't use that package anymore. The Error I get right now is this:

qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initiali
zed. Reinstalling the application may fix this problem.

And I have read nearly all related Forums about this problem, non of which actually helped me. My question is:

Should I add any script in the spec file? the Qt path or something like that? how?

Thanks in advance for your help.
