### ISSUE TITLE
Invalid Module

### ISSUE THREAD

**Issue by enchainingrealm** [pyinstaller/pyinstaller#4459]
My project structure is as follows:

```
- src
  - main.py
  - helper.py
```

`main.py` imports `helper.py`. However, if I run Pyinstaller with the command `pyinstaller main.py`, running the compiled executable gives a module not found error referring to `helper.py`. I used pyi-archive_viewer to examine the generated executable and `helper.py` is indeed not in the executable. In the `warn-all.txt` file in the `build` folder, there is a line stating that `helper.py` is an "invalid module."

**Comment by lkollar** [comment]
Can you post the full output of the warn file and snippets of the relevant import statements of your code? Also, can you confirm that your application works when invoking with `python`?

**Comment by enchainingrealm** [comment]
The full structure of my project is actually:

```
- src
  - anchors_frame.py
  - candidate_frame.py
  - fs.py
  - gui.py
  - main.py
```

The import statements in `src/anchors_frame.py` are:

```
import os

from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QFrame, QListWidget, QVBoxLayout, QListWidgetItem
```

The import statements in `src/candidate_frame.py` are:

```
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QFrame, QVBoxLayout, QPushButton, QLabel
```

The import statements in `src/fs.py` are:

```
import os
```

The import statements in `src/gui.py` are:

```
import os
import shutil
import sys

from PyQt5.QtWidgets import QHBoxLayout, QFrame, QInputDialog, QMessageBox

from src.anchors_frame import AnchorsFrame
from src.candidate_frame import CandidateFrame
from src.fs import get_image_filepaths
```

The import statements in `src/main.py` are:

```
import sys

from PyQt5.QtWidgets import QMainWindow, QApplication

from src.gui import GUI
```

After compiling with `pyinstaller src/main.py`, running the compiled executable gives:

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
ImportError: No module named 'src.gui'
[23866] Failed to execute script main
```

The full output of the `warn-main.txt` file is:

```

This file lists modules PyInstaller was not able to find. This does not
necessarily mean this module is required for running you program. Python and
Python 3rd-party packages include a lot of conditional or optional module. For
example the module 'ntpath' only exists on Windows, whereas the module
'posixpath' only exists on Posix systems.

Types if import:
* top-level: imported at the top-level - look at these first
* conditional: imported within an if-statement
* delayed: imported from within a function
* optional: imported within a try-except-statement

IMPORTANT: Do NOT post this list to the issue-tracker. Use it as a basis for
           yourself tracking down the missing module. Thanks!

missing module named 'org.python' - imported by pickle (optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level), xml.sax (delayed, conditional)
excluded module named _frozen_importlib - imported by importlib (optional), importlib.abc (optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named _frozen_importlib_external - imported by importlib._bootstrap (delayed), importlib (optional), importlib.abc (optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named _winreg - imported by platform (delayed, optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named _scproxy - imported by urllib.request (conditional)
missing module named java - imported by platform (delayed), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named 'java.lang' - imported by platform (delayed, optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level), xml.sax._exceptions (conditional)
missing module named vms_lib - imported by platform (delayed, conditional, optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named winreg - imported by platform (delayed, optional), mimetypes (optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level), urllib.request (delayed, conditional, optional)
missing module named nt - imported by os (conditional, optional), ntpath (conditional, optional), shutil (conditional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named ce - imported by os (conditional, optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named msvcrt - imported by subprocess (conditional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level), getpass (optional)
missing module named _winapi - imported by subprocess (conditional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named org - imported by copy (optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
missing module named _dummy_threading - imported by dummy_threading (optional), /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
invalid module named src.gui - imported by /home/william/Desktop/AnchorLabeler/src/main.py (top-level)
```

Running `python -m src.main` produces the expected behaviour. However, running `python src/main.py` gives:

```
Traceback (most recent call last):
  File "src/main.py", line 5, in <module>
    from src.gui import GUI
ModuleNotFoundError: No module named 'src'
```

**Comment by rwxian** [comment]
me too!!!

**Comment by danyeaw** [comment]
If you want to import `src.gui` this way, don't you need an `__init__.py` file to make src a package?

**Comment by htgoebel** [comment]
You Pyhton program is invalid.

`src` is a package, since you use e..g `src.gui` to import. But `src/main.py` is not your main program, but some module with the package.

Please improve sour knowledge about Python packages, then you will be able to freeze you application.n Sorry for sounding harsh, but this is an issue tracker and not a tutorial forum.

**Comment by rwxian** [comment]
> You Pyhton program is invalid.
> 
> `src` is a package, since you use e..g `src.gui` to import. But `src/main.py` is not your main program, but some module with the package.
> 
> Please improve sour knowledge about Python packages, then you will be able to freeze you application.n Sorry for sounding harsh, but this is an issue tracker and not a tutorial forum.


Already solved, thank you

**Comment by rwxian** [comment]
> If you want to import `src.gui` this way, don't you need an `__init__.py` file to make src a package?


Already solved, thank you
