### ISSUE TITLE
pywintypes.error: (3, 'StartService', 'The system cannot find the path specified.') when using pywinio

### ISSUE THREAD

**Issue by Raymon9** [pyinstaller/pyinstaller#4464]
pywinio version:0.3.1
Python version:3.7
Operating System:win10,64bit
Description

An exception occur when i pack the py file to an exe file using pyinstaller.
But the py file run well before packed.

What I Did

I packed the pywinio code as  keypress.py, and import it in the main.py, 'import keypress', the error throwed when i run the exe file:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "presser.py", line 257, in run
  File "keypress.py", line 53, in key_press
  File "keypress.py", line 37, in key_down
  File "keypress.py", line 17, in get_winio
  File "site-packages\pywinio\pywinio.py", line 133, in __init__
  File "site-packages\pywinio\pywinio.py", line 401, in __initialize
  File "site-packages\pywinio\pywinio.py", line 352, in __start_driver
pywintypes.error: (3, 'StartService', 'The system cannot find the path specified.')

Anyone can help me? thanks for advance.

**Comment by Raymon9** [comment]
up

**Comment by Raymon9** [comment]
need help

**Comment by danyeaw** [comment]
@Raymon9 Thanks for submitting the issue!

Could you please help us triage this by making sure you have gone through the [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) page? Have you tried this with the latest development version and do you have a minimum example? Can you attach the log output of building it with debug enabled? Thanks for your help better isolating where this issue might be :gift:.

**Comment by Raymon9** [comment]
@danyeaw Could you give me a email adress?  It is just a small app using a little code, i will send it to you.

**Comment by danyeaw** [comment]
@Raymon9 could you please add it to a gist as described in that Wiki page? That would allow everyone to help troubleshoot the issue.

**Comment by Raymon9** [comment]
@danyeaw 

There is an  example copy from the  PyPI page of pywinio, pack it by pyinstaller, it will show the exception properly .

`import pywinio
import time
import atexit

# KeyBoard Commands
# Command port
KBC_KEY_CMD = 0x64
# Data port
KBC_KEY_DATA = 0x60

g_winio = None

def get_winio():
    global g_winio

    if g_winio is None:
            g_winio = pywinio.WinIO()
            def __clear_winio():
                    global g_winio
                    g_winio = None
            atexit.register(__clear_winio)

    return g_winio

def wait_for_buffer_empty():
    '''
    Wait keyboard buffer empty
    '''

    winio = get_winio()

    dwRegVal = 0x02
    while (dwRegVal & 0x02):
            dwRegVal = winio.get_port_byte(KBC_KEY_CMD)

def key_down(scancode):
    winio = get_winio()

    wait_for_buffer_empty();
    winio.set_port_byte(KBC_KEY_CMD, 0xd2);
    wait_for_buffer_empty();
    winio.set_port_byte(KBC_KEY_DATA, scancode)

def key_up(scancode):
    winio = get_winio()

    wait_for_buffer_empty();
    winio.set_port_byte( KBC_KEY_CMD, 0xd2);
    wait_for_buffer_empty();
    winio.set_port_byte( KBC_KEY_DATA, scancode | 0x80);

def key_press(scancode, press_time = 1):
    key_down( scancode )
    time.sleep( press_time )
    key_up( scancode )


# Press 'A' key
# Scancodes references : https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html
for i in range(10):
    key_press(0x1E)`

**Comment by Raymon9** [comment]
Can anyone help me? Does this  a bug?

**Comment by MorgenZhu** [comment]
I also found this problem, not solved
