### ISSUE TITLE
I used pyinstaller to package it into an exe file and then run an error.

### ISSUE THREAD

**Issue by liu978079474** [pyinstaller/pyinstaller#4469]
Error log：
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 149, in __init__
  File "ctypes\__init__.py", line 348, in __init__
OSError: [WinError 126] 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "change_EXIF.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\python3.6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "gai_EXIF.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\python3.6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pyexiv2\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\python3.6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pyexiv2\core.py", line 22, in <module>
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\JZ\\AppData\\Local\\Temp\\_MEI206762\\pyexiv2\\lib\\exiv2.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[22184] Failed to execute script change_EXIF

**Comment by lkollar** [comment]
Unfortunately your issue does not contain sufficient information to be able to help you. Please open a new issue and make sure you follow the steps outlined in the issue template. As mentioned in the template, please provide the information requested in the [When submitting a bug](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#when-submitting-a-bug) section of the manual.

You might want to have a look at the [When things go wrong](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html) section of the manual as well for general troubleshooting tips.
