### ISSUE TITLE
 raise SystemError("objcopy Failure: %s" % stderr)

### ISSUE THREAD

**Issue by azuredsky** [pyinstaller/pyinstaller#4479]
I download pyinstaller package from https://github.com/pyinstaller/pyinstaller/releases/download/v3.5/PyInstaller-3.5.tar.gz
then：

cd bootloader
python ./waf distclean all

Then install PyInstaller:

python setup.py install

I want to compiler:   https://github.com/qqwweee/keras-yolo3 
 pyinstaller  --clean -F  yolo_video.py
but I got the error:

```
(base) [sky@localhost keras-yolo3]$ pyinstaller  --clean -F  yolo_video.py
27 INFO: PyInstaller: 3.5
28 INFO: Python: 3.6.5
28 INFO: Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core
46 INFO: wrote /work/workspace/keras-yolo3/yolo_video.spec
47 INFO: UPX is not available.
48 INFO: Removing temporary files and cleaning cache in /home/sky/.cache/pyinstaller
154 INFO: Extending PYTHONPATH with paths
['/work/workspace/keras-yolo3', '/work/workspace/keras-yolo3']
155 INFO: checking Analysis
155 INFO: Building Analysis because Analysis-00.toc is non existent
155 INFO: Initializing module dependency graph...
156 INFO: Initializing module graph hooks...
157 INFO: Analyzing base_library.zip ...
2493 INFO: running Analysis Analysis-00.toc
2500 INFO: Caching module hooks...
2503 INFO: Analyzing /work/workspace/keras-yolo3/yolo_video.py
3241 INFO: Processing pre-find module path hook   distutils
4316 INFO: Processing pre-safe import module hook   six.moves
4836 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
5181 INFO: Processing pre-find module path hook   site
5181 INFO: site: retargeting to fake-dir '/work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/fake-modules'
12327 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
92500 INFO: Loading module hooks...
92500 INFO: Loading module hook "hook-numpy.core.py"...
92607 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
92608 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
92608 INFO: Loading module hook "hook-bokeh.py"...
93292 INFO: Loading module hook "hook-h5py.py"...
93293 INFO: Loading module hook "hook-openpyxl.py"...
93294 INFO: Loading module hook "hook-jedi.py"...
93295 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
93295 INFO: Loading module hook "hook-IPython.py"...
93304 INFO: Excluding import 'matplotlib'
93310 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
93310 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
93310 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
93310 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
93311 INFO: Excluding import 'PySide'
93318 INFO:   Removing import of PySide from module IPython.external.qt_loaders
93318 INFO: Excluding import 'PyQt5'
93325 INFO:   Removing import of PyQt5.QtWidgets from module IPython.external.qt_loaders
93325 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
93325 INFO:   Removing import of PyQt5.QtSvg from module IPython.external.qt_loaders
93325 INFO:   Removing import of PyQt5.QtGui from module IPython.external.qt_loaders
93325 INFO:   Removing import of PyQt5.QtCore from module IPython.external.qt_loaders
93325 INFO: Excluding import 'gtk'
93333 INFO: Excluding import 'PyQt4'
93340 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
93340 INFO: Loading module hook "hook-jsonschema.py"...
93341 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
93415 INFO: Loading module hook "hook-docutils.py"...
94022 INFO: Loading module hook "hook-cryptography.py"...
94191 INFO: Loading module hook "hook-cytoolz.itertoolz.py"...
94207 INFO: Loading module hook "hook-setuptools.py"...
94770 INFO: Loading module hook "hook-PyQt5.QtSvg.py"...
94919 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
94938 INFO: Loading module hook "hook-lxml.etree.py"...
94940 INFO: Loading module hook "hook-xml.dom.domreg.py"...
94941 INFO: Loading module hook "hook-encodings.py"...
95019 INFO: Loading module hook "hook-numpy.py"...
95019 INFO: Loading module hook "hook-pygments.py"...
96229 INFO: Loading module hook "hook-pytz.py"...
96240 INFO: Loading module hook "hook-pycparser.py"...
96485 INFO: Loading module hook "hook-pkg_resources.py"...
96780 INFO: Processing pre-safe import module hook   win32com
96893 INFO: Loading module hook "hook-PIL.Image.py"...
97273 INFO: Loading module hook "hook-babel.py"...
97287 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
97287 INFO: Loading module hook "hook-nbconvert.py"...
97290 INFO: Loading module hook "hook-xml.py"...
97290 INFO: Loading module hook "hook-lib2to3.py"...
97291 INFO: Loading module hook "hook-_tkinter.py"...
97374 INFO: checking Tree
97374 INFO: Building Tree because Tree-00.toc is non existent
97374 INFO: Building Tree Tree-00.toc
97379 INFO: checking Tree
97379 INFO: Building Tree because Tree-01.toc is non existent
97379 INFO: Building Tree Tree-01.toc
97381 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
97473 INFO: Loading module hook "hook-sphinx.py"...
99534 INFO: Loading module hook "hook-pytest.py"...
100180 INFO: Loading module hook "hook-jinja2.py"...
100202 INFO: Loading module hook "hook-pydoc.py"...
100202 INFO: Loading module hook "hook-sklearn.metrics.cluster.py"...
100255 WARNING: Hidden import "sklearn.utils.sparsetools._graph_validation" not found!
100255 WARNING: Hidden import "sklearn.utils.sparsetools._graph_tools" not found!
100255 INFO: Loading module hook "hook-distutils.py"...
100256 INFO: Loading module hook "hook-zmq.py"...
100940 INFO: Loading module hook "hook-notebook.py"...
101530 INFO: Loading module hook "hook-cv2.py"...
101530 INFO: Loading module hook "hook-certifi.py"...
101530 INFO: Loading module hook "hook-sqlite3.py"...
101579 INFO: Loading module hook "hook-matplotlib.backends.py"...
101933 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
102243 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
102428 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
102698 INFO:   Matplotlib backend "GTK3Agg": ignored
    The Gtk3 backend requires PyGObject or pgi
102874 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
103145 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
103749 INFO:   Matplotlib backend "nbAgg": ignored
    cannot import name 'create_prompt_application'
104071 INFO:   Matplotlib backend "Qt4Agg": added
104295 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
104617 INFO:   Matplotlib backend "Qt5Agg": added
104837 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
105118 INFO:   Matplotlib backend "TkAgg": added
105339 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
105642 INFO:   Matplotlib backend "WebAgg": added
105961 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython>=2.9
106146 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
106327 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
106586 INFO:   Matplotlib backend "agg": added
106763 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
106950 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
107264 INFO:   Matplotlib backend "pdf": added
107715 INFO:   Matplotlib backend "pgf": added
107975 INFO:   Matplotlib backend "ps": added
108311 INFO:   Matplotlib backend "svg": added
108574 INFO:   Matplotlib backend "template": added
108892 INFO: Loading module hook "hook-sqlalchemy.py"...
109118 INFO:   Found 3 sqlalchemy hidden imports
109118 WARNING: Hidden import "MySQLdb" not found!
109119 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
109137 INFO: Excluding import 'sqlalchemy.testing'
109144 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.orm.util
109144 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing.warnings from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing
109144 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.warnings
109144 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.warnings
109144 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing.assertions
109144 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.assertions
109145 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing.assertions
109145 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertions
109145 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.assertions
109145 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing.assertions
109145 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.util
109145 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing.util
109145 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.util
109145 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.config
109145 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.engines
109145 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.engines
109145 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.engines
109145 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.engines
109146 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.exclusions
109146 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.exclusions
109146 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertsql
109146 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.mock
109147 INFO: Loading module hook "hook-nbformat.py"...
109148 INFO: Loading module hook "hook-scipy.linalg.py"...
109148 INFO: Loading module hook "hook-tables.py"...
109149 INFO: Loading module hook "hook-PIL.py"...
109155 INFO: Import to be excluded not found: 'FixTk'
109155 INFO: Excluding import 'PySide'
109161 INFO:   Removing import of PySide from module PIL.ImageQt
109161 INFO: Excluding import 'PyQt5'
109167 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
109168 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
109168 INFO: Excluding import 'tkinter'
109175 INFO:   Removing import of tkinter from module PIL.ImageTk
109175 INFO: Excluding import 'PyQt4'
109181 INFO:   Removing import of PyQt4 from module PIL.ImageQt
109182 INFO: Loading module hook "hook-scipy.py"...
109182 INFO: Loading module hook "hook-pandas.py"...
109535 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
109547 INFO: Import to be excluded not found: 'FixTk'
109547 INFO: Excluding import 'tkinter'
109552 INFO: Loading module hook "hook-PyQt5.py"...
109561 INFO: Loading module hook "hook-matplotlib.py"...
109742 INFO: Loading module hook "hook-sysconfig.py"...
109753 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
109800 INFO: Loading module hook "hook-gevent.py"...
109872 INFO: Determining a mapping of distributions to packages...
156402 WARNING: Unable to find package for requirement greenlet from package gevent.
156402 INFO: Packages required by gevent:
[]
156852 INFO: checking Tree
156852 INFO: Building Tree because Tree-02.toc is non existent
156852 INFO: Building Tree Tree-02.toc
156859 INFO: Looking for ctypes DLLs
157263 WARNING: library user32 required via ctypes not found
157879 INFO: Analyzing run-time hooks ...
157923 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
157925 INFO: Including run-time hook 'pyi_rth_pkgres.py'
157926 INFO: Including run-time hook 'pyi_rth__tkinter.py'
157927 INFO: Including run-time hook 'pyi_rth_pyqt5.py'
157927 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
157928 INFO: Including run-time hook 'pyi_rth_mpldata.py'
157928 INFO: Including run-time hook 'pyi_rth_traitlets.py'
157929 INFO: Including run-time hook 'pyi_rth_certifi.py'
158010 INFO: Looking for dynamic libraries
/work/local/anaconda3/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /work/local/anaconda3/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so)
167637 INFO: Looking for eggs
167638 INFO: Using Python library /work/local/anaconda3/lib/python3.6/site-packages/markupsafe/../../../libpython3.6m.so.1.0
167708 INFO: Warnings written to /work/workspace/keras-yolo3/build/yolo_video/warn-yolo_video.txt
168198 INFO: Graph cross-reference written to /work/workspace/keras-yolo3/build/yolo_video/xref-yolo_video.html
168415 INFO: checking PYZ
168415 INFO: Building PYZ because PYZ-00.toc is non existent
168416 INFO: Building PYZ (ZlibArchive) /work/workspace/keras-yolo3/build/yolo_video/PYZ-00.pyz
173107 INFO: Building PYZ (ZlibArchive) /work/workspace/keras-yolo3/build/yolo_video/PYZ-00.pyz completed successfully.
173236 INFO: checking PKG
173236 INFO: Building PKG because PKG-00.toc is non existent
173236 INFO: Building PKG (CArchive) PKG-00.pkg
425317 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
425402 INFO: Bootloader /work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/bootloader/Linux-64bit/run
425402 INFO: checking EXE
425402 INFO: Building EXE because EXE-00.toc is non existent
425402 INFO: Building EXE from EXE-00.toc
425403 INFO: Appending archive to ELF section in EXE /work/workspace/keras-yolo3/dist/yolo_video
Traceback (most recent call last):
  File "/work/local/anaconda3/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5', 'console_scripts', 'pyinstaller')()
  File "/work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/work/workspace/keras-yolo3/yolo_video.spec", line 33, in <module>
    console=True )
  File "/work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/building/api.py", line 444, in __init__
    self.__postinit__()
  File "/work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/work/local/anaconda3/lib/python3.6/site-packages/PyInstaller-3.5-py3.6.egg/PyInstaller/building/api.py", line 610, in assemble
    raise SystemError("objcopy Failure: %s" % stderr)
SystemError: objcopy Failure: objcopy:/work/workspace/keras-yolo3/dist/yolo_video: File format not recognized
```
>

**Comment by danyeaw** [comment]
@azuredsky Thanks for submitting an issue :heart:.

Unfortunately, it doesn't look like you have followed the [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) page.

1. Have you tried packaging this using the latest development version?
2. In your pyinstaller output, it looks like there are 6 warnings for packages not found, have you tried to resolve these issues?
3. Do you have a minimum example that we could use to reproduce the bug?
