### ISSUE TITLE
TypeError: an integer is required (got type bytes) pyinstaller

### ISSUE THREAD

**Issue by Joaorms** [pyinstaller/pyinstaller#4480]
Estou tentando converter um programa .py para .exe para poder abrir o mesmo sem utilizar o python, mas ele esta dando o erro 🥇 TypeError: an integer is required (got type bytes)

C:\Users\pedro\PycharmProjects\untitled1>pyinstaller vida.py
489 INFO: PyInstaller: 3.5
489 INFO: Python: 3.8.0
489 INFO: Platform: Windows-10-10.0.18362-SP0
489 INFO: wrote C:\Users\pedro\PycharmProjects\untitled1\vida.spec
504 INFO: UPX is not available.
504 INFO: Extending PYTHONPATH with paths
['C:\\Users\\pedro\\PycharmProjects\\untitled1',
 'C:\\Users\\pedro\\PycharmProjects\\untitled1']
504 INFO: checking Analysis
667 INFO: checking PYZ
667 INFO: Building PYZ because PYZ-00.toc is non existent
667 INFO: Building PYZ (ZlibArchive) C:\Users\pedro\PycharmProjects\untitled1\build\vida\PYZ-00.pyz
Traceback (most recent call last):
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python38-32\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\pedro\PycharmProjects\untitled1\vida.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble
    self.code_dict = {
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)

**Comment by Joaorms** [comment]
o código do programa é esse:
from tkinter import *
class Application:
    def __init__(self, master=None):
        self.widget1 = Frame(master)
        self.widget1.pack()
        self.msg = Label(self.widget1, text="Primeiro widget")
        self.msg["font"] = ("Verdana", "10", "italic", "bold")
        self.msg.pack ()
        self.sair = Button(self.widget1)
        self.sair["text"] = "Clique aqui"
        self.sair["font"] = ("Calibri", "9")
        self.sair["width"] = 10
        self.sair["command"] = self.mudarTexto
        self.sair.pack()

    def mudarTexto(self):
        if self.msg["text"] == "Primeiro widget":
            self.msg["text"] = "O botão recebeu um clique"
        else:
            self.msg["text"] = "Primeiro widget"
root = Tk()
Application(root)
root.mainloop()

**Comment by pusto-tauranth** [comment]
Mi pensas, ke vi devas kontroli vian version de Python. Ĝi devas esti subtenata de Pyinstaller.

**Comment by pusto-tauranth** [comment]
> Mi pensas, ke vi devas kontroli vian version de Python. Ĝi devas esti subtenata de Pyinstaller.

Mi volas diri, ke Python: 3.8.0 estas tro alta. La oficiala paĝo (https://pypi.org/project/PyInstaller/) priskribas subtenatajn versiojn de Python. Eble vi provu t.e. Python 3.6.7.

**Comment by pusto-tauranth** [comment]
> Mi pensas, ke vi devas kontroli vian version de Python. Ĝi devas esti subtenata de Pyinstaller.

Mi volas diri, ke Python: 3.8.0 estas tro alta. La oficiala paĝo (https://pypi.org/project/PyInstaller/) priskribas subtenatajn versiojn de Python. Eble vi provu ekz. Python 3.6.7.

**Comment by danyeaw** [comment]
@Joaorms thanks for submitting the issue!

Have you seen the [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) page? Could you please verify that you have verified the items on this page including trying using the latest development version? It would be helpful if you move your minimum example to a gist so that we could try to reproduce it, or at least fix the Markdown so that the formatting is correct.

**Comment by betson-fernando** [comment]
Hello!

I had the same trouble in build my exe. I was using auto-py-to-exe, that call pyinstaller.
I solved that installing:

`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz` (upgraded to version 4.0)

Python version: 3.8.0 for 32 bits.

**Comment by htgoebel** [comment]
Closing as invalid. Python 3.8 is not yet supported.
