### ISSUE TITLE
Hook for gi.repository.GdkPixbuf Looks for gdk-pixbuf-query-loaders on PATH

### ISSUE THREAD

**Issue by danyeaw** [pyinstaller/pyinstaller#4485]
I am trying to troubleshoot issues with packaging up [Gaphor](https://github.com/gaphor/gaphor) for Windows using MSYS2 by first trying to get it to execute in Linux.

When executing a GTK app that uses a png image, I am getting an error:
`gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “temp-icon.png” (3)`

This seems like a regression from the fix in #1833.

I am using the master version of PyInstaller (4.0.dev0+ga9b29999)
Python: 3.7.5
Platform: Ubuntu 19.10 Linux-5.3.0-18-generic-x86_64-with-debian-buster-sid
GTK 3.24.12

I have created a [simple example](https://gist.github.com/danyeaw/faa74e21e188a33c3817fcb8400ab3df) posted to gist. 

```
[9159] LOADER: Running pyiboot01_bootstrap.py
[9159] LOADER: Running pyi_rth_gtk.py
[9159] LOADER: Running pyi_rth_glib.py
[9159] LOADER: Running pyi_rth_gdkpixbuf.py
[9159] LOADER: Running pyi_rth_gio.py
[9159] LOADER: Running pyi_rth_gi.py
[9159] LOADER: Running simple-example.py
Gtk-Message: 09:49:45.114: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "win-installer/simple-example.py", line 8, in <module>
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “temp-icon.png” (3)
[9159] Failed to execute script simple-example
[9159] LOADER: OK.
[9159] LOADER: Cleaning up Python interpreter.
[9158] LOADER: Restoring signal handlers
[9158] LOADER: freeing args
[9158] LOADER: returning child exit status 255
[9158] LOADER: Back to parent (RC: 255)
[9158] LOADER: Doing cleanup
[9158] LOADER: Freeing archive status for /home/dan/Projects/gaphor/win-installer/dist/simple-example/simple-example
```
Running with strace gives:
```
[9216] LOADER: Running pyi_rth_gi.py
[9216] LOADER: Running simple-example.py
strace: Process 9217 attached
strace: Process 9218 attached
Gtk-Message: 09:51:29.339: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "win-installer/simple-example.py", line 8, in <module>
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “temp-icon.png” (3)
[9216] Failed to execute script simple-example
[9216] LOADER: OK.
[9216] LOADER: Cleaning up Python interpreter.
[pid  9218] +++ exited with 255 +++
[pid  9217] +++ exited with 255 +++
[pid  9216] +++ exited with 255 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=9216, si_uid=1000, si_status=255, si_utime=21, si_stime=4} ---
```
I would be glad to submit a PR if someone could help point me in the right direction. @virtuald you helped with the last issue, is this something you could assist with as well?

**Comment by danyeaw** [comment]
I was able to resolve this myself. I noticed that there was a warning that I missed:
`7416 WARNING: "hook-gi.repository.GdkPixbuf" ignored, since GDK not found (i.e., "gdk-pixbuf-query-loaders" not in $PATH).`

In Ubuntu and Debian, gdk-pixbuf-query-loaders is not on the PATH. For example on my system it is located `/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders`.

A workaround is to run pyinstaller with:
`$ env PATH="$PATH:/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0" pyinstaller -y simple-example.spec`

I can submit a PR to fix this, any thoughts on how we should find the location of gdk-pixbuf-query-loaders from the hook?
