### ISSUE TITLE
PyQt5 not bundled properly on Windows 10

### ISSUE THREAD

**Issue by K3nn3th2** [pyinstaller/pyinstaller#4489]
Hey folks,

i have a working python script using pyqt5.
it runs under windows using python after running
`pip install python-qt5`

when i try to package it using PyInstaller, i end up with a lot of Qt5 .dll files in my build folder but i get the following error when executing the main binary:

`qtpy.PythonQtError: No Qt bindings could be found`

I dont understand why it runs unpackaged, but not after packaging.

is it something with the qt5 hooks and the 'unoffical' python-qt5?
or am i missing something?

any help gladly appreceated!
thanks,

Kenneth

edit:
Its the same on Windows 7 and Windows 10. 
Are all python 2.7 PyQt5 PyInstaller users building their own? :(

**Comment by j9ac9k** [comment]
First step would be to install the official pyqt5 package and go from there and see what happens, also I'm wondering if this is a case where you need to set the environment variable `QT_API=pyqt5` per the README:

https://github.com/spyder-ide/qtpy#requirements

**Comment by K3nn3th2** [comment]
I forgot to add:
I'm using Python 2.7 and therefore there is no PyQt5 package on pip (for windows)
I would have to build it myself..

**Comment by j9ac9k** [comment]
There is a PySide2 package that will work for Python 2.7, might be easier to use that instead of PyQt5... be aware that help with python 2.7 at this point is going to be somewhat hard to come by.

**Comment by Metallicow** [comment]
@j9ac9k why am I getting this message?

**Comment by Metallicow** [comment]
Must be an automated messsage from the NSA...

**Comment by Metallicow** [comment]
If you are a Navy person, and you ask questions, they dont give a shit!, therefore dont give a shit about your country.

**Comment by Legorooj** [comment]
@K3nn3th2, I'm going to have to close this, as we no longer support python 2. If the error persists on python 3(.5/6/7), I'll reopen.

**Comment by srevinsaju** [comment]
Yes, I can reproduce the error while using PySIde2 and Qtpy on Ubuntu Xenial with Python 3.8. 
```bash
Traceback (most recent call last):
  File "qtpy/__init__.py", line 204, in <module>
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "entrypoint.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/github/.local/lib/python3.8/site-packages/pyinstaller-4.1.dev0-py3.8.egg/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "guiscrcpy/cli.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/github/.local/lib/python3.8/site-packages/pyinstaller-4.1.dev0-py3.8.egg/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "guiscrcpy/launcher.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/github/.local/lib/python3.8/site-packages/pyinstaller-4.1.dev0-py3.8.egg/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "qtpy/__init__.py", line 210, in <module>
qtpy.PythonQtError: No Qt bindings could be found
[67] Failed to execute script entrypoint
```

The PySIde2 libraries are bundled, but I am not sure why QtPy is not able to find them.

**Comment by Legorooj** [comment]
@bjones1 we only support PyQt5/PySide2 right?

**Comment by srevinsaju** [comment]
No, but I actually want to use PySide2. The Qtpy api first checks for PyQt5 -> PySide2 -> PyQt4 -> PySide -> Crash
The last step is shown in the traceback.

**Comment by srevinsaju** [comment]
By the way, building on PySide2 works on Windows, but not on ALinux. I can reproduce on Ubuntu Xenial, Bionic, Arch Linux (latest) and Manjaro (latest)

**Comment by Legorooj** [comment]
@srevinsaju can you post your `*-xref.html` file from `build`?
