### ISSUE TITLE
pyinstaller fails to resolve mounted volume in docker container

### ISSUE THREAD

**Issue by chris-t-w** [pyinstaller/pyinstaller#4496]
I have a docker container with pyinstaller installed, and source mounted in a volume to `c:\dev\source`:

```> dir c:\dev
Directory of c:\dev

... <SYMLINKD>     source [\\?\ContainerMappedDirectories\62C69617-9D75-4FA6-B2CA-D7E078AABEBC]
```

When running `pyinstaller`, I see the following error:

```
INFO: Analyzing C:\dev\source\program.py
  Traceback (most recent call last):
    File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\python38\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "C:\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
    File "c:\python38\lib\site-packages\PyInstaller\__main__.py", line 112, in run
      run_build(pyi_config, spec_file, **vars(args))
    File "c:\python38\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
      PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
    File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 732, in main
      build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
    File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 679, in build
      exec(code, spec_namespace)
    File "C:\dev\source\source.spec", line 6, in <module>
      a = Analysis(['C:/dev/source/program.py'],
    File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
      self.__postinit__()
    File "c:\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
      self.assemble()
    File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 414, in assemble
      priority_scripts.append(self.graph.run_script(script))
    File "c:\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 247, in run_script
      self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
    File "c:\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1384, in run_script
      with open(pathname, 'rb') as fp:
  FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\C:\\ContainerMappedDirectories\\62C69617-9D75-4FA6-B2CA-D7E078AABEBC\\program.py'
```

The problem appears to be the following line in `modulegraph.py`:

```
pathname = os.path.realpath(pathname)
```

This is not correctly dealing with the symlink.

**Comment by chris-t-w** [comment]
Possibly related to this ("os.path.realpath on Windows does not follow symbolic links")?

https://bugs.python.org/issue9949

**Comment by htgoebel** [comment]
Closing as invalid. Python 3.8 is not yet supported.
