### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by superstring** [pyinstaller/pyinstaller#4503]
I use latest pyinstaller to build spark standalone application, but got an error when I running it:

```
9489 INFO: checking EXE
9489 INFO: Building EXE because EXE-00.toc is non existent
9490 INFO: Building EXE from EXE-00.toc
9492 INFO: Appending archive to EXE target/dist\neuron.exe
9502 INFO: Building EXE from EXE-00.toc completed successfully.

(demo-g4PmrKgb) C:\Users\Gundam\Desktop\spark\python\demo>target\dist\neuron.exe
Traceback (most recent call last):
  File "src\main.py", line 4, in <module>
    import pyspark
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Users\Gundam\.virtualenvs\demo-g4PmrKgb\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pyspark\__init__.py", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Users\Gundam\.virtualenvs\demo-g4PmrKgb\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pyspark\conf.py", line 72, in <module>
  File "C:\Users\Gundam\.virtualenvs\demo-g4PmrKgb\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
[15948] Failed to execute script main
```

here is test code
```
from pyspark.sql import SparkSession

if __name__ == '__main__':
    print('spark test')
```

I have google for some solutions, but doesn't work.

**Comment by danyeaw** [comment]
@superstring What is your platform and which version of pyinstaller are you using? Have you followed the steps to ensure everything is [packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs)?

**Comment by superstring** [comment]
@danyeaw 
Here is my platform and pyinstaller version:
```
Host Name:                 DESKTOP-R7UI1CH
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
```
and
```
 "pyinstaller": {
        "hashes": [
            "sha256:ee7504022d1332a3324250faf2135ea56ac71fdb6309cff8cd235de26b1d0a96"
        ],
        "index": "pypi",
        "version": "==3.5"
},
```
I have packaged some projects with pyinstaller in production, everything is OK, but got error when I ran the packaged project with pyspark.

here is a simple project demo without pyspark: [demo](https://github.com/superstring/scaffold-python-simple)

**Comment by htgoebel** [comment]
This is not related to PyInstaller, but by "pyspark\conf.py"
```
  File "site-packages\pyspark\conf.py", line 72, in <module>
  File "C:\Users\Gundam\.virtualenvs\demo-g4PmrKgb\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

Please check your installation.
