### ISSUE TITLE
pyinstaller can't use at Windows-10-10.0.18362-SP0

### ISSUE THREAD

**Issue by mikumiku2468** [pyinstaller/pyinstaller#4507]
I also try pyinstaller3.5 and PyInstaller: 4.0.dev0 
it didnt work
64 INFO: PyInstaller: 4.0.dev0+a9b299995
65 INFO: Python: 3.7.5
66 INFO: Platform: Windows-10-10.0.18362-SP0
69 INFO: wrote D:\python_code\arbor_api_test\Arbor_api_proflieing.spec
70 INFO: UPX is not available.
76 INFO: Extending PYTHONPATH with paths
['D:\\python_code\\arbor_api_test', 'D:\\python_code\\arbor_api_test']
76 INFO: checking Analysis
76 INFO: Building Analysis because Analysis-00.toc is non existent
78 INFO: Initializing module dependency graph...
81 INFO: Caching module graph hooks...
88 INFO: Analyzing base_library.zip ...
2823 INFO: Caching module dependency graph...
2918 INFO: running Analysis Analysis-00.toc
Traceback (most recent call last):
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\core\ctypes\_util.py", line 42, in check_null
    raise make_error(function, function_name)
OSError: [WinError 1920] 系統無法存取該檔案。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\__main__.py", line 112, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\build_main.py", line 732, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\build_main.py", line 679, in build
    exec(code, spec_namespace)
  File "D:\python_code\arbor_api_test\Arbor_api_proflieing.spec", line 17, in <module>
    noarchive=False)
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\build_main.py", line 393, in assemble
    redirects=self.binding_redirects)[1:])
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\depend\bindepend.py", line 226, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\depend\bindepend.py", line 402, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\depend\bindepend.py", line 353, in getAssemblies
    res = GetManifestResources(pth)
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1005, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\utils\win32\winresource.py", line 168, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\miku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1920, 'LoadLibraryExW', '系統無法存取該檔案。')
系統無法存取該檔案。means 'system cannot access the file'

**Comment by danyeaw** [comment]
@mikumiku2468 Do you have a minimum example for us to reproduce this with? From the title of the Issue, it sounds like you think this is an issue caused by the version of Windows you are using, do you have some reason to suspect that?

**Comment by mikumiku2468** [comment]
I forgot to say 
I have two computer
ver 1903 build number 18362.418  doesn't work 
but
ver 1803  build number 17134.950 is work
so I think is os problem

**Comment by ncwtf** [comment]
我也遇到了这个问题
我是win10 1903
我的解决方法是：

```
# 第一个地方
# 根据错误信息提示找到"win32api.py"文件
# 修改大约40行
def LoadLibraryEx(fileName, handle, flags):
    # 添加这一行,改为你的python路径
    fileName = r"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\python.exe"
    if not handle == 0:
        raise ValueError("handle != 0 not supported")
    with _pywin32error():
        return _dll._LoadLibraryEx(fileName, 0, flags)


def EnumResourceTypes(hModule):
```

```
# 第二个地方
# 修改完第一个错误运行会报第二个同样的错误
# 根据错误提示修改"pefile.py"文件
# 修改大约1795行
    def __parse__(self, fname, data, fast_load):
        """Parse a Portable Executable file.

        Loads a PE file, parsing all its structures and making them available
        through the instance's attributes.
        """
        # 添加这一行,同样改为你的python路径
        fname = r"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\python.exe"
        if fname is not None:
            stat = os.stat(fname)
            if stat.st_size == 0:
                raise PEFormatError('The file is empty')
            fd = None
```
ps：可能会在某些地方可以修改为全局的python路径吧，我没有找到。

**Comment by ncwtf** [comment]
I have this problem, too
This is win10 1903
My solution is:

```
# First place
# Find the "win32api. py" file according to the error message prompt
# Modify about 40 lines
def LoadLibraryEx(fileName, handle, flags):
    # Add this line and change it to your Python path
    fileName = r"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\python.exe"
    if not handle == 0:
        raise ValueError("handle != 0 not supported")
    with _pywin32error():
        return _dll._LoadLibraryEx(fileName, 0, flags)


def EnumResourceTypes(hModule):
```

```
# Second place
# After modifying the first error, the second error will be reported
# Modify the "pefile. py" file according to the error prompt
# Modify about 1795 lines
    def __parse__(self, fname, data, fast_load):
        """Parse a Portable Executable file.

        Loads a PE file, parsing all its structures and making them available
        through the instance's attributes.
        """
        # Add this line and change it to your Python path
        fname = r"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\python.exe"
        if fname is not None:
            stat = os.stat(fname)
            if stat.st_size == 0:
                raise PEFormatError('The file is empty')
            fd = None
```
ps：Maybe it can be changed to global Python path in some places. I didn't find it.

**Comment by ncwtf** [comment]
it not good idea

**Comment by keelung-yang** [comment]
Hard-coded path is a bad idea

**Comment by ncwtf** [comment]
> 
> 
> Hard-coded path is a bad idea

那你有更好的解决办法吗？

**Comment by EffortlessFury** [comment]
Also having this issue, though this is my first attempt to use pyinstaller.

**Comment by keelung-yang** [comment]
This Works:
- Python: 3.8.1 64bit
- Windows 10: 10.0.17134.1009
- PyInstaller: latest master branch

**Comment by mrnuke** [comment]
Has this been fixed? I'm still seeing this with pyinstaller 3.6

**Comment by kevinhalgren** [comment]
Seeing this as well
Python 3.8.1 64-bit
Windows 10 v1909: 10.0.18363.592

**Comment by Legorooj** [comment]
@kevinhalgren we don't support 3.8 yet!

**Comment by mrnuke** [comment]
@Legorooj I just tried pyinstaller 3.6 with python 3.7.6, and I'm still seeing the exact problem

**Comment by Legorooj** [comment]
@mrnuke hmm. Is everyone getting this error using `win32api` or one of its sister modules under `pywin32`?

**Comment by mrnuke** [comment]
@Legorooj  Not sure how to tell. [This gist](https://gist.github.com/mrnuke/7aa3942715bdee451f87326d0a4e7791) is the output that I'm getting

**Comment by Legorooj** [comment]
Hmm. Try a build with the `--uac-admin` option? @mrnuke

**Comment by mrnuke** [comment]
I get the same result if I use `--uac-admin'

**Comment by Legorooj** [comment]
@mrnuke I know now that it's an error caused by pyenv. Could you try running it in a venv venv? (ie python(3) -m venv venv)

**Comment by mrnuke** [comment]
Bingo! I used the `python.exe` and `pip3.exe` under `venv\Scripts` to install the modules and run PyInstaller

> vend\Scripts\python.exe -m PyInstaller test.py

And it worked.

**Comment by Legorooj** [comment]
??? This needs working out. Can you run with `--log-level=TRACE` - make sure to redirect the output to a file (it'll be thousands of lines long) - and the log files to legorooj@protonmail.com?

**Comment by iestatic** [comment]
> Bingo! I used the `python.exe` and `pip3.exe` under `venv\Scripts` to install the modules and run PyInstaller
> 
> > vend\Scripts\python.exe -m PyInstaller test.py
> 
> And it worked.

Help more with this please! i'm not sure what you mean to do here.

**Comment by Legorooj** [comment]
@iestatic please try:

 * Entering your virtual environment (eg `venv/Scripts/activate.bat`)
 * Then running the same compilation command that failed, replacing `pyinstaller` with `python -m PyInstaller myscript.py --option`. Does this work? If so, we may have found more of the error.

**Comment by mrnuke** [comment]
@Legorooj  Failing log in [this gist](https://gist.github.com/mrnuke/1cf4b89231b2e8a927ec73ef3118585a)

**Comment by Legorooj** [comment]
@mrnuke that gist either is incomplete or *not* failing. Which command are you calling, and does the executable work?

**Comment by mrnuke** [comment]
@Legorooj It is complete. You have to [View the full file](https://gist.githubusercontent.com/mrnuke/1cf4b89231b2e8a927ec73ef3118585a/raw/e2deee93ef8d4eed0b909a216b2750e52e8a54f7/gistfile1.txt)

**Comment by Legorooj** [comment]
@mrnuke thanks for pointing that out 🙄. I'll have a good read later - it's not easy on a mobile.

**Comment by Legorooj** [comment]
@mrnuke I've had a look through the log. The issue is definitely a windows permissions error. And I can't believe I didn't notice this before. 

@keelung-yang @EffortlessFury @iestatic @kevinhalgren @mikumiku2468 @ncwtf

Are you all using python from the windows store?

**Comment by mrnuke** [comment]
@Legorooj Yes, from windows store.

**Comment by Legorooj** [comment]
@mrnuke I'm now quite sure what the problem is... Lets wait until a couple more if the above mentioned answer.

**Comment by Legorooj** [comment]
Ok @mrnuke can you try python not from the windows store? I've a feeling that it's (Indirectly) because of the windows store version. You'll need to uninstall from windows store and reinstall from https://python.org/download. 

Once thats done, go into `settings > Apps and Features > App execution aliases` and toggle the python switches to off. See the below images for details.
![AppsAndFeatures - Copy](https://user-images.githubusercontent.com/50370070/75109554-81aec400-5678-11ea-8af8-f9cc2ec475fb.png)
![AppsAndFeaturesExecutionsAliases - Copy](https://user-images.githubusercontent.com/50370070/75109555-84a9b480-5678-11ea-86af-d72b4bcfc403.png)

Then you'll need to get your enviroment working again. I'm willing to bet that this will fix said error. (I think that its that damned `WindowsApps` directory. Even when using admin, you can't open it.)

**Comment by nancwang** [comment]
> I have this problem, too
> This is win10 1903
> My solution is:
> 
> ```
> # First place
> # Find the "win32api. py" file according to the error message prompt
> # Modify about 40 lines
> def LoadLibraryEx(fileName, handle, flags):
>     # Add this line and change it to your Python path
>     fileName = r"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\python.exe"
>     if not handle == 0:
>         raise ValueError("handle != 0 not supported")
>     with _pywin32error():
>         return _dll._LoadLibraryEx(fileName, 0, flags)
> 
> 
> def EnumResourceTypes(hModule):
> ```
> 
> ```
> # Second place
> # After modifying the first error, the second error will be reported
> # Modify the "pefile. py" file according to the error prompt
> # Modify about 1795 lines
>     def __parse__(self, fname, data, fast_load):
>         """Parse a Portable Executable file.
> 
>         Loads a PE file, parsing all its structures and making them available
>         through the instance's attributes.
>         """
>         # Add this line and change it to your Python path
>         fname = r"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\python.exe"
>         if fname is not None:
>             stat = os.stat(fname)
>             if stat.st_size == 0:
>                 raise PEFormatError('The file is empty')
>             fd = None
> ```
> 
> ps：Maybe it can be changed to global Python path in some places. I didn't find it.

The solution works. Thank you!

**Comment by Legorooj** [comment]
@nancwang please don't edit that module; please instead use a virtual environment.

**Comment by kexul** [comment]
I'm using python from miniconda and encountered the same problem

**Comment by Legorooj** [comment]
@kexul please open a new issue about this.
