### ISSUE TITLE
pyinstaller 3.5 do not support Python embed 3.7.5 and 3.8.0

### ISSUE THREAD

**Issue by ivysrono** [pyinstaller/pyinstaller#4513]
Windows 10 x64

`.\pip.exe install pyinstaller`

```
  ERROR: Command errored out with exit status 1:
   command: '\python-3.8.0-embed-win32\python.exe' '\python-3.8.0-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel \AppData\Local\Temp\tmpskw1gu_e'
       cwd: C:\Users\Pp\AppData\Local\Temp\pip-install-xtexejmg\pyinstaller
  Complete output (4 lines):
  Traceback (most recent call last):
    File "\python-3.8.0-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 26, in <module>
      import compat
  ModuleNotFoundError: No module named 'compat'
  ----------------------------------------
ERROR: Command errored out with exit status 1: '\python-3.8.0-embed-win32\python.exe' '\python-3.8.0-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel \AppData\Local\Temp\tmpskw1gu_e' Check the logs for full command output.
```

```
  ERROR: Command errored out with exit status 1:
   command: '\python-3.7.5-embed-win32\python.exe' '\python-3.7.5-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel '\AppData\Local\Temp\tmp9peew29x'
       cwd: \AppData\Local\Temp\pip-install-sqtcsiq1\pyinstaller
  Complete output (4 lines):
  Traceback (most recent call last):
    File "\python-3.7.5-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 26, in <module>
      import compat
  ModuleNotFoundError: No module named 'compat'
  ----------------------------------------
ERROR: Command errored out with exit status 1: '\python-3.7.5-embed-win32\python.exe' '\python-3.7.5-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel '\AppData\Local\Temp\tmp9peew29x' Check the logs for full command output.
```

**Comment by danyeaw** [comment]
@ivysrono Have you tried the [latest development version](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#getting-the-latest-version)?

**Comment by ivysrono** [comment]
@danyeaw 
```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: '\python-3.8.0-embed-win32\python.exe' '\python-3.8.0-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel '\AppData\Local\Temp\tmp9e5gii7f'
       cwd: \AppData\Local\Temp\pip-req-build-1pzdcopd
  Complete output (4 lines):
  Traceback (most recent call last):
    File "\python-3.8.0-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 26, in <module>
      import compat
  ModuleNotFoundError: No module named 'compat'
  ----------------------------------------
ERROR: Command errored out with exit status 1: '\python-3.8.0-embed-win32\python.exe' '\python-3.8.0-embed-win32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel '\AppData\Local\Temp\tmp9e5gii7f' Check the logs for full command output.
```

**Comment by The-Compiler** [comment]
That sounds like an issue with your `pip` which is unrelated to PyInstaller. Can you install any other packages?

**Comment by ivysrono** [comment]
Yes, I can install other packages like yapf wxPython pywin32 and so on.

**Comment by htgoebel** [comment]
Duplicate #4311
