### ISSUE TITLE
ImportError: unable to find Qt5Core.dll on PATH

### ISSUE THREAD

**Issue by vyuschuk** [pyinstaller/pyinstaller#4551]
Seems the same as closed issue #4293:
Workaround:
`--add-data site-packages\\PyQt5\\Qt\\bin;PyQt5\\Qt\\bin`

_Originally posted by @sz2723 in https://github.com/pyinstaller/pyinstaller/issues/4293#issuecomment-516560142_

To reproduce with PyInstaller 3.5:
created helloworld app with the line:
import PyQt5.QtCore

Result:
(Qt64) C:\venv\Qt64\Lib>pyinstaller C:\Users\c4admin\Documents\temp\helloworld1\helloworld1\helloworld1.py
156 INFO: PyInstaller: 3.5
156 INFO: Python: 3.7.4
156 INFO: Platform: Windows-10-10.0.18362-SP0
171 INFO: wrote C:\venv\Qt64\Lib\helloworld1.spec
177 INFO: UPX is not available.
177 INFO: Extending PYTHONPATH with paths
['C:\\Users\\c4admin\\Documents\\temp\\helloworld1\\helloworld1',
 'C:\\venv\\Qt64\\Lib']
177 INFO: checking Analysis
286 INFO: checking PYZ
349 INFO: checking PKG
364 INFO: Building because C:\venv\Qt64\Lib\build\helloworld1\helloworld1.exe.manifest changed
364 INFO: Building PKG (CArchive) PKG-00.pkg
458 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
458 INFO: Bootloader c:\venv\qt64\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
458 INFO: checking EXE
476 INFO: Rebuilding EXE-00.toc because pkg is more recent
476 INFO: Building EXE from EXE-00.toc
480 INFO: Appending archive to EXE C:\venv\Qt64\Lib\build\helloworld1\helloworld1.exe
645 INFO: Building EXE from EXE-00.toc completed successfully.
661 INFO: checking COLLECT
WARNING: The output directory "C:\venv\Qt64\Lib\dist\helloworld1" and ALL ITS CONTENTS will be REMOVED! Continue? (y/N)y
10739 INFO: Removing dir C:\venv\Qt64\Lib\dist\helloworld1
10813 INFO: Building COLLECT COLLECT-00.toc
16994 INFO: Building COLLECT COLLECT-00.toc completed successfully.

(Qt64) C:\venv\Qt64\Lib>dist\helloworld1\helloworld1.exe
Traceback (most recent call last):
  File "helloworld1.py", line 1, in <module>
  File "c:\venv\qt64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\PyQt5\__init__.py", line 41, in <module>
  File "lib\site-packages\PyQt5\__init__.py", line 33, in find_qt
ImportError: unable to find Qt5Core.dll on PATH
[14344] Failed to execute script helloworld1

**Comment by vyuschuk** [comment]
Just noticed 
https://github.com/pyinstaller/pyinstaller/issues/4416
mentions this may not be an issue if PyQt 5.13.1 is used.  
I'm going to close this since others did the same.  I'm new to this so I'll assume others know better.

However, it should be noted that the latest stable pyqt5-tools (needed for tools like the GUI designer) does not yet support PyQt 5.13.1 so folks may be stuck with PyQt5 5.13.0 and the workaround for now.
