### ISSUE TITLE
Import error scipy.special from SciPy 1.3.3 on Windows

### ISSUE THREAD

**Issue by janheindejong** [pyinstaller/pyinstaller#4559]
I'm getting a DLL import error when I compile a Python script that uses ``scipy.special``. 

The script I compile is: 

```
import scipy.special 
print("'ello, world!")
```

I get the following error message in debug mode. 

```
# scipy.special._ufuncs not found in PYZ
Traceback (most recent call last):
  File "scipy_problem.py", line 1, in <module>
    import scipy.special
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\soft_dev\meuk\scipy_dll_problem\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\scipy\special\__init__.py", line 641, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
[11560] Failed to execute script scipy_problem
```

I tried adding ``scipy.special._ufuncs`` to the hidden imports, and also tried the hidden imports listed in issue #3197, which did not solve the issue. 

SciPy 1.3.0 works just fine.  

Any idea how to solve this, or what I am missing? 

Attached my requirements file, spec file, and Python script. 

[scipy_problem.zip](https://github.com/pyinstaller/pyinstaller/files/3912396/scipy_problem.zip)

**Comment by SherabWangchuk** [comment]
Hi, have you tried adding an additional hook, which contains something like:
```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files("scipy.special")
```
Hope this helps :)

**Comment by janheindejong** [comment]
Hmm... where should I include this? In the script, or the spec file? I tried adding it to the script, but running the compiled program now returns the following console output: 

```
PyInstaller cannot check for assembly dependencies.
Please install pywin32-ctypes.

pip install pywin32-ctypes
```

**Comment by janheindejong** [comment]
Nevermind... figured out I had to include it in the spec file. Thanks!
