### ISSUE TITLE
Failed to execute script pyiboot01_bootstrap when using key

### ISSUE THREAD

**Issue by kivdev** [pyinstaller/pyinstaller#4575]
pyinstaller --key=IbMAD1f53Ol1Ej78 --onefile test.py

77 INFO: PyInstaller: 4.0.dev0+9dd34bdfba
77 INFO: Python: 3.7.4
78 INFO: Platform: Windows-10-10.0.17763-SP0
...
81 INFO: UPX is not available.
120 INFO: Extending PYTHONPATH with paths
...
...
121 INFO: Will encrypt Python bytecode with key: IbMAD1f53Ol1Ej78

test.py:
`import sys
import os

    def resource_path(relative_path):
        try:
            base_path = sys._MEIPASS
        except Exception:
            base_path = os.path.abspath(".")

        return os.path.join(base_path, relative_path)

    print(resource_path('icon_disabled.ico'))
    print(resource_path('icon_enabled.ico'))`

ERROR:
`Traceback (most recent call last):
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 432, in get_code
    return self._pyz_archive.extract(fullname)[1]
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive.py", line 367, in extract
    obj = zlib.decompress(obj)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 25, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 601, in exec_module
    bytecode = self.get_code(spec.loader_state)
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 434, in get_code
    raise ImportError('Loader FrozenImporter cannot handle module ' + fullname)
ImportError: Loader FrozenImporter cannot handle module os
[8864] Failed to execute script pyiboot01_bootstrap`

Without using the key works fine, but I need the key.

**Comment by htgoebel** [comment]
Encrypting the code is currently unsupported. See the other issues about this.
