### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by johanndavel** [pyinstaller/pyinstaller#4580]
Hi guys, i get this error when executing the installer. is there something wrong with my python code or is this an installer error ?

**Comment by danyeaw** [comment]
@johanndavel which version are you using? Have you tried with the development version?

**Comment by amirymax** [comment]
I also had this problem, and just installed the latest version. Use the following:

pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz

**Comment by mc-gary** [comment]
i think it May not be compatible with Python 3.8

**Comment by yangmijun** [comment]
I got same problem，python 3.8.1

**Comment by mc-gary** [comment]
> I got same problem，python 3.8.1
my bro
i think you can try install the development version of pyinstaller
`pip install https://github.com/pyinstaller/pyinstaller/tarball/develop`

**Comment by Legorooj** [comment]
@mc-gary I would recommend not installing that for building executables.

@johanndavel @amirymax @yangmijun :

PyInstaller currently doesn't support 3.8.
I suggest you build with 3.7 or earlier until python 3.8 is supported

**Comment by Legorooj** [comment]
Can this be closed?

**Comment by Rhandall** [comment]
xception ignored in thread started by: <function check_errors.<locals>.wrapper at 0x7f96f302bd30>
Traceback (most recent call last):
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/core/management/base.py", line 376, in check
    all_issues = self._run_checks(
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/rhandall/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/rhandall/Documents/GitHub/school_new/base/urls.py", line 5, in <module>
    from schoolio import views as schoolio_views
  File "/Users/rhandall/Documents/GitHub/school_new/schoolio/views.py", line 81, in <module>
    from .standard_matching import match_standard, match_activity, fetch_single_classroom, match_standard_to_international
  File "/Users/rhandall/Documents/GitHub/school_new/schoolio/standard_matching.py", line 1, in <module>
    from sklearn.feature_extraction.text import CountVectorizer
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/sklearn/__init__.py", line 80, in <module>
    from .base import clone
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/sklearn/base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 21, in <module>
    import joblib
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 152, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/Users/rhandall/Documents/GitHub/school_new/venv/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 133, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

Please anyone help
