### ISSUE TITLE
unable to find a folder/file while parsing pd.read_csv

### ISSUE THREAD

**Issue by girmax** [pyinstaller/pyinstaller#4597]
When running exe receiving the following error message:
```

[11056] WARNING: file already exists but should not: C:\Users\max\AppData\Local\Temp\_MEI110562\scipy\optimize\moduleTNC.cp37-win_amd64.pyd
Traceback (most recent call last):
  File "app.py", line 24, in <module>
  File "app.py", line 16, in load_ipex_data
  File "site-packages\pandas\io\parsers.py", line 685, in parser_f
  File "site-packages\pandas\io\parsers.py", line 457, in _read
  File "site-packages\pandas\io\parsers.py", line 895, in __init__
  File "site-packages\pandas\io\parsers.py", line 1135, in _make_engine
  File "site-packages\pandas\io\parsers.py", line 1917, in __init__
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/data.csv' does not exist: b'data/data.csv'
[9472] Failed to execute script app
```
the add file is set in the spec file as follows:
`a.datas += Tree('data', 'data')`

**Comment by Legorooj** [comment]
Try adding the files *without* `Tree`? The docs say how.
