### ISSUE TITLE
I have a problem trying to convert .py files to .exe

### ISSUE THREAD

**Issue by Aeneator** [pyinstaller/pyinstaller#4600]
I'm using python 3.8.1,
I know you can use pyinstaller to get the exe file but it doesn't seem to work on python 3.8.1
I always get this error:
TypeError: an integer is required (got type bytes)

Are there any other options?

**Comment by Aeneator** [comment]
C:\Users\Emil\PycharmProjects\The 8th Gate>pyinstaller -d all game.py
69 INFO: PyInstaller: 3.5
69 INFO: Python: 3.8.1
70 INFO: Platform: Windows-10-10.0.18362-SP0
71 INFO: wrote C:\Users\Emil\PycharmProjects\The 8th Gate\game.spec
73 INFO: UPX is not available.
75 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Emil\\PycharmProjects\\The 8th Gate',
 'C:\\Users\\Emil\\PycharmProjects\\The 8th Gate']
75 INFO: checking Analysis
76 INFO: Building Analysis because Analysis-00.toc is non existent
76 INFO: Initializing module dependency graph...
78 INFO: Initializing module graph hooks...
81 INFO: Analyzing base_library.zip ...
3079 INFO: Processing pre-find module path hook   distutils
4830 INFO: running Analysis Analysis-00.toc
4833 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\emil\appdata\local\programs\python\python38-32\python.exe
5691 INFO: Caching module hooks...
5698 INFO: Analyzing C:\Users\Emil\PycharmProjects\The 8th Gate\game.py
6055 INFO: Loading module hooks...
6056 INFO: Loading module hook "hook-distutils.py"...
6059 INFO: Loading module hook "hook-encodings.py"...
6170 INFO: Loading module hook "hook-lib2to3.py"...
6175 INFO: Loading module hook "hook-PIL.Image.py"...
6481 INFO: Loading module hook "hook-PIL.py"...
6482 INFO: Import to be excluded not found: 'FixTk'
6482 INFO: Import to be excluded not found: 'PySide'
6483 INFO: Excluding import 'PyQt5'
6484 INFO:   Removing import of PyQt5 from module PIL.ImageQt
6485 INFO: Import to be excluded not found: 'PyQt4'
6485 INFO: Excluding import 'tkinter'
6486 INFO:   Removing import of tkinter from module PIL.ImageTk
6487 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
6488 INFO: Import to be excluded not found: 'FixTk'
6488 INFO: Excluding import 'tkinter'
6489 INFO: Loading module hook "hook-pydoc.py"...
6490 INFO: Loading module hook "hook-sysconfig.py"...
6492 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
6492 INFO: Loading module hook "hook-xml.py"...
6537 INFO: Loading module hook "hook-_tkinter.py"...
6767 INFO: checking Tree
6767 INFO: Building Tree because Tree-00.toc is non existent
6768 INFO: Building Tree Tree-00.toc
6866 INFO: checking Tree
6866 INFO: Building Tree because Tree-01.toc is non existent
6867 INFO: Building Tree Tree-01.toc
6913 INFO: Looking for ctypes DLLs
6952 INFO: Analyzing run-time hooks ...
6956 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
6959 INFO: Including run-time hook 'pyi_rth__tkinter.py'
6968 INFO: Looking for dynamic libraries
10784 INFO: Looking for eggs
10784 INFO: Using Python library c:\users\emil\appdata\local\programs\python\python38-32\python38.dll
10785 INFO: Found binding redirects:
[]
12481 INFO: Warnings written to C:\Users\Emil\PycharmProjects\The 8th Gate\build\game\warn-game.txt
12551 INFO: Graph cross-reference written to C:\Users\Emil\PycharmProjects\The 8th Gate\build\game\xref-game.html
12617 INFO: checking PYZ
12618 INFO: Building PYZ because PYZ-00.toc is non existent
12619 INFO: Building PYZ (ZlibArchive) C:\Users\Emil\PycharmProjects\The 8th Gate\build\game\PYZ-00.pyz
12620 INFO: Building PYZ (ZlibArchive) C:\Users\Emil\PycharmProjects\The 8th Gate\build\game\PYZ-00.pyz completed successfully.
12624 INFO: checking PKG
12624 INFO: Building PKG because PKG-00.toc is non existent
12624 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Emil\AppData\Local\Programs\Python\Python38-32\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\Emil\PycharmProjects\The 8th Gate\game.spec", line 20, in <module>
    exe = EXE(pyz,
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 432, in __init__
    self.pkg = PKG(self.toc, cdict=kwargs.get('cdict', None),
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 197, in __init__
    self.__postinit__()
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 283, in assemble
    archive = CArchiveWriter(self.name, srctoc + mytoc,
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\archive\writers.py", line 334, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\archive\writers.py", line 61, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\archive\writers.py", line 86, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\archive\writers.py", line 376, in add
    code = strip_paths_in_code(code)
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "c:\users\emil\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)

**Comment by ewerybody** [comment]
Hey @Aeneator welcome to github! 😃
When you have an issue with a piece of software like PyInstaller here you can try and search for the very last error message line. [Like this](https://github.com/pyinstaller/pyinstaller/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+an+integer+is+required+%28got+type+bytes%29).

You see there are now 3 issues listed. Where the 2nd has **exactly your** error message as a **title**! Which is already MUCH better than such a general title here.

Still its redundant and **searching first** is always recommened!!!

I'm sure you find answers in the other issues.
Cheers!
