### ISSUE TITLE
Failed to execute: pyi_rth_nltk.py

### ISSUE THREAD

**Issue by gakhilbabu7983** [pyinstaller/pyinstaller#4648]
I'm using nltk,tkinter and sklearn trying create a executable file. But I'm facing issues  unable to execute pyi_rth_nltk.py anyone have idea... thanks in advance

**Comment by sirmichal** [comment]
What version of setuptools do you use? Probably it is >= 45.0.0. If yes, try to downgrade setuptools package to 44.0.0.

**Comment by gakhilbabu7983** [comment]
I'm using setup tools 41.0.1 and python =3.7.4 but still there is no luck. I can able to create an exe but when i'm trying to run its showing popup Failed to execute pyi_rth_nltk.py

**Comment by gakhilbabu7983** [comment]
> What version of setuptools do you use? Probably it is >= 45.0.0. If yes, try to downgrade setuptools package to 44.0.0.
> But this is only a workaround unfortunately.

**Comment by Legorooj** [comment]
Is it giving you an error? If it is, and it's too quick to read, please run the executable from a command line. Then post the traceback.

**Comment by Legorooj** [comment]
@gakhilbabu7983 pinging

**Comment by gelodefaultbrain** [comment]
hello @gakhilbabu7983  I have the same problem as you. How did you solved it? Thank youu :) badly needed it :(

**Comment by DanielKrolopp** [comment]
I had the same issue earlier today and finally got it to work using the following software versions:

Python 3.6.8, nltk 3.5 and a dev version of pyinstaller:
```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Additionally, I used scikit-learn version 0.21.1.

**Comment by Legorooj** [comment]
@DanielKrolopp yes, a fix was merged in in... March? It'll be out in the next stable release - hopefully June.

**Comment by DanielKrolopp** [comment]
> @DanielKrolopp yes, a fix was merged in in... March? It'll be out in the next stable release - hopefully June.

@Legorooj Maybe I spoke too soon. The error occurs in a Windows 10 VM with Python 3.6.8:

```
Traceback (most recent call last):
File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 167, in __init__                            
File "ctypes\__init__.py", line 348, in __init__                                                                   
OSError: [WinError 126] The specified module could not be found                                                                                                                                                                           
During handling of the above exception, another exception occurred:                                                                                                                                                                       
Traceback (most recent call last):                                                                                     
File "lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_nltk.py", line 15, in <module>                             
File "<frozen importlib._bootstrap>", line 971, in _find_and_load                        
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                           
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                  
File "c:\users\user\desktop\shakra\detection\.build_dist\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module                                                                                              
exec(bytecode, module.__dict__)                                                                                    
File "lib\site-packages\nltk\__init__.py", line 142, in <module>                                                     
File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                    
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                           
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                    
File "c:\users\user\desktop\shakra\detection\.build_dist\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module                                                                                              
exec(bytecode, module.__dict__)                                                                                    
File "lib\site-packages\nltk\chunk\__init__.py", line 157, in <module>                                               
File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                    
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                           
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                    
File "c:\users\user\desktop\shakra\detection\.build_dist\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module                                                                                              
exec(bytecode, module.__dict__)                                                                                    
File "lib\site-packages\nltk\chunk\api.py", line 13, in <module>                                                     
File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                    
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                           
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                    
File "c:\users\user\desktop\shakra\detection\.build_dist\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module                                                                                              
exec(bytecode, module.__dict__)                                                                                    
File "lib\site-packages\nltk\parse\__init__.py", line 100, in <module>                                               
File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                    
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                           
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                    
File "c:\users\user\desktop\shakra\detection\.build_dist\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module                                                                
exec(bytecode, module.__dict__)                                                                                    
File "lib\site-packages\nltk\parse\transitionparser.py", line 19, in <module>                                        
File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                    
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                           
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                    
File "c:\users\user\desktop\shakra\detection\.build_dist\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module                                                                                              
exec(bytecode, module.__dict__)                                                                                    
File "lib\site-packages\sklearn\__init__.py", line 80, in <module>                                                   
File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                    
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                           
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                    
File "c:\users\user\desktop\shakra\detection\.build_dist\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module                                                                
exec(bytecode, module.__dict__)                                                                                    
File "lib\site-packages\sklearn\_distributor_init.py", line 18, in <module>                                          
File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 169, in __init__                          
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\User\\Desktop\\shakra\\detection\\.build_dist\\dist\\scan\\sklearn\\.libs\\vcomp140.dll'. Most probably this dynlib/dll was not found when the application was frozen.                                                                                                                  
[8912] Failed to execute script pyi_rth_nltk
```

**Comment by Legorooj** [comment]
@DanielKrolopp can I have a minimal code snippet so I can try and reproduce?

**Comment by DanielKrolopp** [comment]
I've narrowed it down to seemingly being an issue with importing an nltk module when pip has both scikit-learn and nltk installed. Everything compiles and runs just fine with either one of them installed by themselves. It's funny, because this worked just fine on my Ubuntu 18.04 installation, but not on Windows 10. Here is the output of `pip freeze` from inside a venv:
```
altgraph==0.17
click==7.1.2
future==0.18.2
joblib==0.15.1
nltk==3.5
numpy==1.18.4
pandas==1.0.3
pefile==2019.4.18
pyinstaller==4.0.dev0 (From the most recent commit on the develop branch)
python-dateutil==2.8.1
pytz==2020.1
pywin32-ctypes==0.2.0
regex==2020.5.14
scikit-learn==0.22.1
scipy==1.4.1
six==1.15.0
sklearn==0.0
threadpoolctl==2.0.0
tqdm==4.46.0
```
Python version 3.6.8
OS: Windows 10

This is the minimal snippet that seemed to break it:
```python3
from nltk import ngrams

print('hello world')
```

I got the error I pasted above when I tried to run the .exe file generated from this snippet. Thanks for your help.

**Comment by Legorooj** [comment]
Been able to reproduce this locally. This is the relevant part of the code in sklearn that is causing the issue:
```python
if os.name == 'nt':
    # Pre-load the DLL stored in sklearn/.libs by convention.
    dll_path = op.join(op.dirname(__file__), '.libs', 'vcomp140.dll')
    WinDLL(op.abspath(dll_path))
```

Apparently `sklearn` needs a hook. Would anyone be able to provide a new hook at [this repo](https://github.com/pyinstaller/pyinstaller-hooks-contrib) via PR?

**Comment by InanisV** [comment]
So is there any solution to this error now? Or just wait for an update? I have the same problem.

**Comment by Legorooj** [comment]
@InanisV 
>Would anyone be able to provide a new hook at [this repo](https://github.com/pyinstaller/pyinstaller-hooks-contrib) via PR?

**Comment by InanisV** [comment]
@Legorooj 
Thank you for your reply. I solved the problem by adding a similar file like other hooks named `Python37\Lib\site-packages\PyInstaller\hooks\hook-sklearn.py`.
```python
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('sklearn')
```
I understand that the added code tells the hook script to include all the files (except .py and .pyc) in `Python37\Lib\site-packages\sklearn`. This action solves the dependency problem. Is it right?
Additionally, could I create a pull request in [pyinstaller-hooks-contrib](https://github.com/pyinstaller/pyinstaller-hooks-contrib) to upload the hook file?

**Comment by Legorooj** [comment]
@InanisV Yes, that hook looks great, and yes, please provide a PR. Guidelines are in the hooks-contrib wiki. Please give feedback on the guidelines - they're very much incomplete. Add the hook in the `stdhooks` directory.
