### ISSUE TITLE
app bundle is unable to load pyvisa-sim extensions

### ISSUE THREAD

**Issue by lucabecchetti** [pyinstaller/pyinstaller#4653]
## Unable to load pyvisa-sim from app bundle

I have an application running good when launched with:

Pipenv run python engine.py, it includes PyVISA and Pyvisa-sim package, but I'm unable to run it executing bundle generated from Pyinstaller:

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python:  ``3.7.5```
* Platform: Mac osx catalina
* Did you also try this on another platform? Does it work there? not tested

### A minimal example program which shows the error

```
import visa
import pyvisa
from pyvisa import *

# Initializa pyvisa resource manager
rm = visa.ResourceManager('@sim')

# Get all connected resources
resources = rm.list_resources()
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "site-packages/pyvisa/highlevel.py", line 1466, in get_wrapper_class
ModuleNotFoundError: No module named 'pyvisa-sim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server/engine/engine.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/frind/.local/share/virtualenvs/zeta+--YxoTR6t/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "server/utils/VisaConnection.py", line 6, in <module>
  File "site-packages/pyvisa/highlevel.py", line 1553, in __new__
  File "site-packages/pyvisa/highlevel.py", line 1522, in open_visa_library
  File "site-packages/pyvisa/highlevel.py", line 1470, in get_wrapper_class
ValueError: Wrapper not found: No package named pyvisa-sim
[58002] Failed to execute script engine
```

### Pipenv graph

```
PyInstaller==3.6
  - altgraph [required: Any, installed: 0.17]
  - macholib [required: >=1.8, installed: 1.14]
    - altgraph [required: >=0.15, installed: 0.17]
  - setuptools [required: Any, installed: 45.1.0]
pyserial==3.4
python-socketio==4.4.0
  - python-engineio [required: >=3.9.0, installed: 3.11.2]
    - six [required: >=1.9.0, installed: 1.14.0]
  - six [required: >=1.9.0, installed: 1.14.0]
pyusb==1.0.2
PyVISA-sim==0.3
  - pyvisa [required: >=1.8, installed: 1.10.1]
  - pyyaml [required: Any, installed: 5.3]
  - stringparser [required: Any, installed: 0.5]
requests-mock==1.7.0
  - requests [required: >=2.3,<3, installed: 2.22.0]
    - certifi [required: >=2017.4.17, installed: 2019.11.28]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.8]
  - six [required: Any, installed: 1.14.0]
termcolor==1.1.0
timeloop==1.0.2
tornado==6.0.3
yaspin==0.16.0
```

### Command to generate bundle

sudo pipenv run pyinstaller src/server/engine/engine.py  --windowed --noconfirm --clean --onefile --hidden-import 'pkg_resources.py2_warn'

**Comment by Legorooj** [comment]
We don't support `pipenv`, and you will need to write a hook for the modules. Please refer to the docs.
