### ISSUE TITLE
pkg_resources has a new hidden import as of setuptools 45.0.0

### ISSUE THREAD

**Issue by efahl** [pyinstaller/pyinstaller#4672]
Create tiny test script:
```
import pkg_resources
print('Hello')
```

Crash at startup:
```
> dist/bort/bort.exe
[18964] Failed to execute script pyi_rth_pkgres
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
  File "C:\PROGRA~1\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
```
Python 3.7.4
PyInstaller 3.6
setuptools 45.0.0 (and 45.1.0, same issue)
Windows 10 Pro x64

Hack in a change to Python37/Lib/site-packages/PyInstaller/hooks/hook-pkg_resources.py
```
hiddenimports = collect_submodules('pkg_resources._vendor') + ['pkg_resources.py2_warn'] # Added py2_warn for setuptools 45.0 and later.
```

Rebuild and try again:
```
> dist/bort/bort.exe
Hello
```

**Comment by efahl** [comment]
Oops, I see Harmut already addressed this.

**Comment by vashek** [comment]
> Oops, I see Harmut already addressed this.

@efahl , would you share how/where, please? I can't find anything. Thanks.

**Comment by efahl** [comment]
> 
> 
> > Oops, I see Harmut already addressed this.
> 
> @efahl , would you share how/where, please? I can't find anything. Thanks.

@vashek, it's in https://github.com/pyinstaller/pyinstaller/commit/91481570517707fc70aa70dca9eb986c61eac35d

**Comment by vashek** [comment]
I see, thanks! So it's not released yet. (But also, not mentioned in https://pyinstaller.readthedocs.io/en/latest/CHANGES.html)

**Comment by Syed-Osama-Hussain** [comment]
Hello. I'm getting the same error when I try to run my django app's executable file. I tried the suggested solution but it doesn't work. Following is the traceback:

```Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
  File "e:\webdevelopment\backend\supply_chain\supply_chain_proj\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[7960] Failed to execute script pyi_rth_pkgres```

**Comment by alexeast99** [comment]
I tried this method as well as the one mentioned here: [9148157](https://github.com/pyinstaller/pyinstaller/commit/91481570517707fc70aa70dca9eb986c61eac35d) and neither of them worked for me. I would **greatly** appreciate if I could get some help with this :-)
