### ISSUE TITLE
e2etests hanoi5 to 8 fail

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#469]
**Original date**: 2011/11/30

These are build with --onefile.

-_hanoi5_\* and 6

```
$ ./hanoi5
thisfile is /tmp/hanoi/t5/dist/hanoi
homepath is /tmp/hanoi/t5/dist/
_MEIPASS2 is NULL
Extracting binaries
Executing self as child with /tmp//_MEIOIGUVn/
/tmp/hanoi/t5/dist/:/tmp//_MEIOIGUVn/
thisfile is /tmp/hanoi/t5/dist/hanoi
homepath is /tmp/hanoi/t5/dist/
_MEIPASS2 is /tmp//_MEIOIGUVn/
Already in the child - running!
/tmp//_MEIOIGUVn/libpython2.6.so.1.0
Manipulating evironment
PYTHONPATH=/tmp//_MEIOIGUVn:/tmp/hanoi/t5/dist
importing modules from CArchive
extracted iu
extracted struct
extracted archive
Installing import hooks
outPYZ1.pyz
Running scripts
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "PyInstaller/loader/iu.py", line 468, in importHook
    raise ImportError("No module named %s" % fqname)
ImportError: No module named carchive
RC: -1 from unpackTK
OK.
Back to parent...
```

-_hanoi7_\* and 8

```
$ ./hanoi7
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "PyInstaller/loader/iu.py", line 468, in importHook
    raise ImportError("No module named %s" % fqname)
ImportError: No module named carchive
```

**Comment by Legorooj** [comment]
Closing due to inactivity.
