### ISSUE TITLE
Failed to execute script pyi_rth_multiprocessing, ImportError on elder win7x86

### ISSUE THREAD

**Issue by Elendiar** [pyinstaller/pyinstaller#4706]
#4244  Description of the issue
Cant run frozen python script on some windows 7 installations.

### Stacktrace / full error message
....
multiprocessing.reduction not found in PYZ

code object from 'D:\\main2\\multiprocessing\\reduction.pyc'

pickle not found in PYZ
code object from 'D:\\main2\\pickle.pyc'
_compat_pickle not found in PYZ
code object from 'D:\\main2\\_compat_pickle.pyc'
import '_compat_pickle' # "_frozen_importlib_external.SourcelessFileLoader objec
t at 0x00B8FE50"
import '_pickle' # "class '_frozen_importlib.BuiltinImporter'"
org not found in PYZ
import 'pickle' # "_frozen_importlib_external.SourcelessFileLoader object at 0x0
0B7BDA8"
socket not found in PYZ
code object from 'D:\\main2\\socket.pyc'
_socket not found in PYZ
Traceback (most recent call last):
  File C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\si
te-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py, line 17, in
"module"
  File "frozen importlib._bootstrap", line 991, in _find_and_load
  File "frozen importlib._bootstrap", line 975, in _find_and_load_unlocked
  File "frozen importlib._bootstrap", line 671, in _load_unlocked
  File "frozen importlib._bootstrap_external"", line 783, in exec_module
  File "frozen importlib._bootstrap", line 219, in _call_with_frames_removed
  File c:\users\user\appdata\local\programs\python\python38-32\lib\mu
ltiprocessing\__init__.py", line 16, in "module"
  File "frozen importlib._bootstrap", line 1042, in _handle_fromlist
  File "frozen importlib._bootstrap", line 219, in _call_with_frames_removed
  File "frozen importlib._bootstrap", line 991, in _find_and_load
  File "frozen importlib._bootstrap", line 975, in _find_and_load_unlocked
  File "frozen importlib._bootstrap", line 671, in _load_unlocked
  File "frozen importlib._bootstrap_external"", line 783, in exec_module
  File "frozen importlib._bootstrap", line 219, in _call_with_frames_removed
  File c:\users\user\appdata\local\programs\python\python38-32\lib\mu
ltiprocessing\context.py", line 6, in "module"
  File "frozen importlib._bootstrap", line 1042, in _handle_fromlist
  File "frozen importlib._bootstrap", line 219, in _call_with_frames_removed
  File "frozen importlib._bootstrap", line 991, in _find_and_load
  File "frozen importlib._bootstrap", line 975, in _find_and_load_unlocked
  File "frozen importlib._bootstrap", line 671, in _load_unlocked
  File "frozen importlib._bootstrap_external"", line 783, in exec_module
  File "frozen importlib._bootstrap", line 219, in _call_with_frames_removed
  File c:\users\user\appdata\local\programs\python\python38-32\lib\mu
ltiprocessing\reduction.py, line 16, in "module"
  File "frozen importlib._bootstrap", line 991, in _find_and_load
  File "frozen importlib._bootstrap", line 975, in _find_and_load_unlocked
  File "frozen importlib._bootstrap", line 671, in _load_unlocked
  File "frozen importlib._bootstrap_external"", line 783, in exec_module
  File "frozen importlib._bootstrap", line 219, in _call_with_frames_removed
  File c:\users\user\appdata\local\programs\python\python38-32\lib\so
cket.py, line 49, in "module"
  File "frozen importlib._bootstrap", line 991, in _find_and_load
  File "frozen importlib._bootstrap", line 975, in _find_and_load_unlocked
  File "frozen importlib._bootstrap", line 657, in _load_unlocked
  File "frozen importlib._bootstrap", line 556, in module_from_spec
  File "frozen importlib._bootstrap_external"", line 1101, in create_module
  File "frozen importlib._bootstrap", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _socket: Параметр хибний. # (translation - **the parameter is wrong**)
[2404] Failed to execute script pyi_rth_multiprocessing
[2404] LOADER: OK.
[2404] LOADER: Cleaning up Python interpreter.`

## This is where all ok, _extension module '_socket' loaded from_ successfully.
multiprocessing.reduction not found in PYZ

code object from 'C:\\Users\\user\\Documents\\Python\\productivity-mao\\dist\\main2\\multiprocessing\\reduction.pyc'
pickle not found in PYZ

code object from 'C:\\Users\\user\\Documents\\Python\\productivity-mao\\dist\\main2\\pickle.pyc'
 _compat_pickle not found in PYZ
code object from 'C:\\Users\\user\\Documents\\Python\\productivity-mao\\dist\\main2\\_compat_pickle.pyc'
import '_compat_pickle' # "_frozen_importlib_external.SourcelessFileLoader object at 0x036EC238"
import '_pickle' # "class '_frozen_importlib.BuiltinImporter'"
 org not found in PYZ
import 'pickle' # "_frozen_importlib_external.SourcelessFileLoader object at 0x036DA190"
socket not found in PYZ
code object from 'C:\\Users\\user\\Documents\\Python\\productivity-mao\\dist\\main2\\socket.pyc'
_socket not found in PYZ
extension module '_socket' loaded from 'C:\\Users\\user\\Documents\\Python\\productivity-mao\\dist\\main2\\_socket.pyd'
extension module '_socket' executed from 'C:\\Users\\user\\Documents\\Python\\productivity-mao\\dist\\main2\\_socket.pyd'
import '_socket' # "_frozen_importlib_external.ExtensionFileLoader object at 0x036EC7D8"
selectors not found in PYZ
...
## Without verbose mode error like:
`D:\productivity-indicator\main.exe
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Lib\si
te-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 17, in
"module"
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\si
te-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "multiprocessing\__init__.py", line 16, in "module"
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\si
te-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "multiprocessing\context.py", line 6, in "module"
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\si
te-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "multiprocessing\reduction.py", line 16, in "module"
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\si
te-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "socket.py", line 49, in "module"
ImportError: DLL load failed while importing _socket: Параметр хибний. # (translation - **the parameter is wrong**)
[1536] Failed to execute script pyi_rth_multiprocessing
##############

* Output of `pyinstaller --version`: ```4.0.dev0+a1f92c6a08```
* Version of Python: e.g. `Python 3.8.2rc2 [MSC v.1916 32 bit (Intel)] on win32`
* Platform: e.g `Windows 7 x86 (uk-ua)`
* Did you also try this on another platform? Does it work there?

 It work on updated win7 and win10. Only problem with old, unupdated win7. I only installed `vc_redist.x86.exe` and `Windows6.1-KB2999226-x86.msu`, because without them did not even start. Only problem with that _socket.pyd import.

**Comment by Legorooj** [comment]
You can't build exes on windows 7 and port them strait over to windows 10. You need to install the windows SDK or something. @htgoebel thoughts?

**Comment by Elendiar** [comment]
> You can't build exes on windows 7 and port them strait over to windows 10. You need to install the windows SDK or something. @htgoebel thoughts?

No! I build on win10 with installed windows sdk, but cant run exe on some win7. I tried copy all dlls from sdk folder to work directory, but it  only fix api-...dll missing, that also can be done with redist installation. After that something bad happens with importing _socked.pyd.

**Comment by erezsh** [comment]
I'm getting the same error on Windows 7 32-bit, for PyInstaller compiled on Windows 10 64-bit.

**Comment by Legorooj** [comment]
Apologies for not getting back sooner. 

A decision was made a few weeks back, and we dropped free support for Windows 7; it's EOL. Sorry!

**Comment by erezsh** [comment]
Does that mean there is paid support?

**Comment by Legorooj** [comment]
@erezsh maybe; http://crazy-compilers.com/contact.html. You need to contact Hartmut.

**Comment by Elendiar** [comment]
Must say that only solution is update windows 7 to sp1. If error still exist, on SP1 must be installed KB2533623 (reboot required) and vc_redist.x86.exe. After this i get worked my program.  I could not get to work with some missing win*.dll packed with pyinstaller.

**Comment by gerbal1337** [comment]
> Must say that only solution is update windows 7 to sp1. If error still exist, on SP1 must be installed KB2533623 (reboot required) and vc_redist.x86.exe. After this i get worked my program. I could not get to work with some missing win*.dll packed with pyinstaller.

Thank you my friend, it worked for me.
Direct link for this update: http://web.archive.org/web/20200203192654/http://download.microsoft.com/download/f/1/0/f106e158-89a1-41e3-a9b5-32feb2a99a0b/windows6.1-kb2533623-x64.msu
