### ISSUE TITLE
cannot bundle sklearn package on Raspbian "no module named joblib"

### ISSUE THREAD

**Issue by ArefAz** [pyinstaller/pyinstaller#4710]
## Description of the issue

Hello,

I already read the docs and If-Things-Go-Wrong, so excuse me if I missed something. 
I am using sklearn svm.SVC class and train_test_split in my code (not any other packages from sklearn). So I found that the error relates to sklearn by testing pyinstaller on my main.py and reading the errors.

I should mention that I tried `--hidden-import` and `-p` to fix the issue, as I did for the other errors I encountered (like when using OpenCV) but this time around I had no luck.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 2.7.16
* Platform:
RasbperryPi 3
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l
* Did you also try this on another platform? Does it work there? Yes it worked on my laptop(Ubuntu 18.04.4 LTS (Bionic Beaver) after adding some `--add-binary` and `-p` s)

### A minimal example program which shows the error

```
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

print SVC
```

### Error log using --debug imports
```
# sklearn.utils.scipy not found in PYZ
# sklearn.utils.murmurhash not found in PYZ
dlopen("/home/pi/obf_test/dist/test/sklearn.utils.murmurhash.arm-linux-gnueabihf.so", 2);
import sklearn.utils.murmurhash # dynamically loaded from /home/pi/obf_test/dist/test/sklearn.utils.murmurhash.arm-linux-gnueabihf.so
import sklearn.utils.class_weight # PyInstaller PYZ
import sklearn.utils._joblib # PyInstaller PYZ
import sklearn.externals.joblib # PyInstaller PYZ
# sklearn.externals.imp not found in PYZ
# sklearn.externals.imp not found in PYZ
Traceback (most recent call last):
  File "test.py", line 17, in <module>
  File "/tmp/pip-unpacked-wheel-9WaSCN/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "dist-packages/sklearn/__init__.py", line 64, in <module>
  File "/tmp/pip-unpacked-wheel-9WaSCN/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "dist-packages/sklearn/base.py", line 13, in <module>
  File "/tmp/pip-unpacked-wheel-9WaSCN/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "dist-packages/sklearn/utils/__init__.py", line 14, in <module>
  File "/tmp/pip-unpacked-wheel-9WaSCN/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "dist-packages/sklearn/utils/_joblib.py", line 22, in <module>
  File "/tmp/pip-unpacked-wheel-9WaSCN/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "dist-packages/sklearn/externals/joblib.py", line 15, in <module>
    locals().update(import_non_local('joblib').__dict__)
  File "dist-packages/sklearn/externals/joblib.py", line 7, in import_non_local
    f, pathname, desc = imp.find_module(name, sys.path[1:])
ImportError: No module named joblib
[20684] Failed to execute script test
# clear __builtin__._

```

/usr/lib/python2.7/dist-packages/sklearn/externals/joblib.py is as follows:

```shell
import imp
import sys

def import_non_local(name, custom_name=None):
    custom_name = custom_name or name

    f, pathname, desc = imp.find_module(name, sys.path[1:])
    module = imp.load_module(custom_name, f, pathname, desc)
    if f is not None:
        f.close()
        
    return module


locals().update(import_non_local('joblib').__dict__)

```
I am not sure what exactly this file is doing, but as far as I could understand it is trying to import the "joblib" package indirectly because the filename is also "joblib.py" but I got no idea why this is the case.

**Comment by Legorooj** [comment]
Python 2 is not supported. Please try with python 3. (I will reopen if the issue persists)
