### ISSUE TITLE
Python library not found in conda-forge environment on CentOS 7

### ISSUE THREAD

**Issue by djhoese** [pyinstaller/pyinstaller#4714]
## Description of the issue

Running pyinstaller on a simple script results in it not being able to find the python library. Running `pyinstaller test.py` on a script with:

```
print("Hello")
```

Results in:

```
Traceback (most recent call last):
  File "/data/users/davidh/miniconda3/envs/sift_dist/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller', 'console_scripts', 'pyinstaller')()
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 241, in __init__
    self.__postinit__()
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 573, in assemble
    self._check_python_library(self.binaries)
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/building/build_main.py", line 676, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: libpython3.7m.so.1.0, libpython3.7.so.1.0, libpython3.7mu.so.1.0
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

The libraries are there:

```
$ ll /data/users/davidh/miniconda3/envs/sift_dist/lib/libpython3.*
-rwxrwxr-x 1 davidh domain users 26963664 Feb 27 17:04 /data/users/davidh/miniconda3/envs/sift_dist/lib/libpython3.7m.a
-rw-rw-r-- 1 davidh domain users 24670152 Feb 27 17:04 /data/users/davidh/miniconda3/envs/sift_dist/lib/libpython3.7m.nolto.a
lrwxrwxrwx 1 davidh domain users       20 Feb 27 17:04 /data/users/davidh/miniconda3/envs/sift_dist/lib/libpython3.7m.so -> libpython3.7m.so.1.0
-rwxrwxr-x 1 davidh domain users  3805216 Feb 27 17:04 /data/users/davidh/miniconda3/envs/sift_dist/lib/libpython3.7m.so.1.0
-rwxrwxr-x 2 davidh domain users    15616 Jan  7 22:41 /data/users/davidh/miniconda3/envs/sift_dist/lib/libpython3.so
```

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.4.dev0+g7817d3f.mod```
* Version of Python: 3.7 from conda-forge in miniconda environment
* Platform: CentOS 7
* Did you also try this on another platform? Does it work there? No, not yet.

My version of pyinstaller is modified because I was planning on fixing some hooks to work with conda packages.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

See above

**Comment by djhoese** [comment]
This seems familiar to https://github.com/pyinstaller/pyinstaller/issues/4210 that @aixtools filed.

**Comment by Legorooj** [comment]
Please try PyInstaller `3.6` & `4.0dev0` (Dev branch). PyInstaller 3.4 is unsupported.

**Comment by djhoese** [comment]
:man_facepalming: I thought I was using the newest version because I installed it from a local git repository, but it turns out my local `develop` was tracking my fork which hadn't been updated since 2018. Oh boy.

Well it still looks like I'm having issues with shapely (and probably dask too), but those I can put in PRs when I fix them. Thanks. I'll close this for now. If I fix up all the other libraries and get this error again I'll reopen it.

**Comment by Legorooj** [comment]
@djhoese great!
