### ISSUE TITLE
ImportError: cannot import name 'is_py2' from 'PyInstaller.compat' (on AIX)

### ISSUE THREAD

**Issue by aixtools** [pyinstaller/pyinstaller#4732]
## Context information (for bug reports)

* 110 INFO: PyInstaller: 4.0.dev0+g96897fc7.mod
* 111 INFO: Python: 3.7.4
* 161 INFO: Platform: AIX-1-00C291F54C00-powerpc-32bit

* Did you also try this on another platform? Does it work there?
No, specifically working on AIX

* try the latest development version, using the following command:
Is the latest version, plus PR4731

  * [ ] Package your program in **--onedir mode**
```
(py37) aixtools@x064:[/home/aixtools/tests]pyinstaller --onedir hello.py
110 INFO: PyInstaller: 4.0.dev0+g96897fc7.mod
111 INFO: Python: 3.7.4
161 INFO: Platform: AIX-1-00C291F54C00-powerpc-32bit
172 INFO: wrote /home/aixtools/tests/hello.spec
214 INFO: UPX is not available.
557 INFO: Extending PYTHONPATH with paths
['/home/aixtools/tests', '/home/aixtools/tests']
557 INFO: checking Analysis
557 INFO: Building Analysis because Analysis-00.toc is non existent
558 INFO: Initializing module dependency graph...
561 INFO: Caching module graph hooks...
577 INFO: Analyzing base_library.zip ...
9926 INFO: Caching module dependency graph...
10748 INFO: running Analysis Analysis-00.toc
12301 INFO: Analyzing /home/aixtools/tests/hello.py
12307 INFO: Processing module hooks...
12308 INFO: Loading module hook "hook-encodings.py"...
12488 INFO: Loading module hook "hook-pydoc.py"...
Traceback (most recent call last):
  File "/home/aixtools/py37/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==4.0.dev0+g96897fc7.mod', 'console_scripts', 'pyinstaller')()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/build_main.py", line 729, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/build_main.py", line 676, in build
    exec(code, spec_namespace)
  File "/home/aixtools/tests/hello.spec", line 17, in <module>
    noarchive=False)
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/build_main.py", line 241, in __init__
    self.__postinit__()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/build_main.py", line 418, in assemble
    self.graph.process_post_graph_hooks()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/depend/analysis.py", line 297, in process_post_graph_hooks
    module_hook.post_graph()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/depend/imphook.py", line 418, in post_graph
    self._load_hook_module()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/depend/imphook.py", line 385, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/compat.py", line 608, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/hooks/hook-pydoc.py", line 19, in <module>
    from PyInstaller.compat import is_py2, modname_tkinter
ImportError: cannot import name 'is_py2' from 'PyInstaller.compat' (/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/compat.py)

```
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
same as above
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.
(py37) aixtools@x064:[/home/aixtools/tests]pyi-makespec --debug all hello.py
wrote /home/aixtools/tests/hello.spec
now run pyinstaller.py to build the executable
(py37) aixtools@x064:[/home/aixtools/tests]pyinstaller --specpath . hello.py
* same results...

### A minimal example program which shows the error

```
print("hello")
```

### Stacktrace / full error message

```

12488 INFO: Loading module hook "hook-pydoc.py"...
Traceback (most recent call last):
  File "/home/aixtools/py37/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==4.0.dev0+g96897fc7.mod', 'console_scripts', 'pyinstaller')()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/build_main.py", line 729, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/build_main.py", line 676, in build
    exec(code, spec_namespace)
  File "/home/aixtools/tests/hello.spec", line 17, in <module>
    noarchive=False)
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/build_main.py", line 241, in __init__
    self.__postinit__()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/building/build_main.py", line 418, in assemble
    self.graph.process_post_graph_hooks()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/depend/analysis.py", line 297, in process_post_graph_hooks
    module_hook.post_graph()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/depend/imphook.py", line 418, in post_graph
    self._load_hook_module()
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/depend/imphook.py", line 385, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/compat.py", line 608, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/hooks/hook-pydoc.py", line 19, in <module>
    from PyInstaller.compat import is_py2, modname_tkinter
ImportError: cannot import name 'is_py2' from 'PyInstaller.compat' (/home/aixtools/py37/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g96897fc7.mod-py3.7.egg/PyInstaller/compat.py)

```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by Legorooj** [comment]
Thanks for spotting this. The hook will need updating.

**Comment by aixtools** [comment]
Since you already fixed this - closing.

**Comment by Legorooj** [comment]
@aixtools I'll fix the hook in my py2 cleanup PR. (#4729)

**Comment by htgoebel** [comment]
Even if this is already closed:
1. `is_py` is not in 96897fc7:
```
$ git checkout 96897fc
…
$ git grep is_py2
Binary file PyInstaller/bootloader/Darwin-64bit/run matches
Binary file PyInstaller/bootloader/Darwin-64bit/run_d matches
Binary file PyInstaller/bootloader/Darwin-64bit/runw matches
Binary file PyInstaller/bootloader/Darwin-64bit/runw_d matches
```
2. A simple `print("Hello")` script should never trigger `hook-pydoc`. I assume there is something wrong in your setup.

**Comment by Legorooj** [comment]
@htgoebel sometimes PyInstaller includes unused libraries. I'm not sure why yet; I'll add a bug report when I can nail it down.

**Comment by privateOmega** [comment]
@Legorooj I am facing the issue in Python 3.6.9, I went through related issues and PRs and seems like a py2 cleanup PR was merged, but any reason why this could still be occuring?

**Comment by Legorooj** [comment]
@privateOmega try running the latest version - 4.0 was released yesterday. I can't find a `hook-pydoc` in our codebase so can't fix it.

**Comment by privateOmega** [comment]
@Legorooj Seems like I am already on it,

>  $ pyinstaller --version
> 4.0

**Comment by Legorooj** [comment]
Huh. Please open an issue on pyinstaller-hooks-contrib with your build log.

**Comment by privateOmega** [comment]
@Legorooj PTAL https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/28
