### ISSUE TITLE
Problem importing shibokensupport:No module named 'typing'

### ISSUE THREAD

**Issue by niuzhenjiang** [pyinstaller/pyinstaller#4737]
It was normal to use pyinstaller before, and it will report an error today. Changing a lot of versions will not work, I hope someone can give a solution

Problem importing shibokensupport:
No module named 'typing'
Traceback (most recent call last):
  File "(builtin)", line 93, in ensure_shibokensupport
  File "(builtin)", line 133, in bootstrap
  File "C:\Users\PandaQzz\AppData\Local\Temp\embedded.gm24pf8v.zip\shibokensupport\signature\loader.py", line 156, in <module>
    import typing
ModuleNotFoundError: No module named 'typing'
sys.path:
  C:\Users\PandaQzz\AppData\Local\Temp\embedded.gm24pf8v.zip
  C:\Users\PandaQzz\Desktop\DEL_DATABASE\dist\DEL_DATABASE_GUI\base_library.zip
  C:\Users\PandaQzz\Desktop\DEL_DATABASE\dist\DEL_DATABASE_GUI
Traceback (most recent call last):
  File "(builtin)", line 93, in ensure_shibokensupport
  File "(builtin)", line 133, in bootstrap
  File "C:\Users\PandaQzz\AppData\Local\Temp\embedded.gm24pf8v.zip\shibokensupport\signature\loader.py", line 156, in <module>
ModuleNotFoundError: No module named 'typing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "(builtin)", line 133, in bootstrap
  File "contextlib.py", line 99, in __exit__
  File "(builtin)", line 102, in ensure_shibokensupport
SystemExit: -1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "(builtin)", line 147, in bootstrap
UnboundLocalError: local variable 'loader' referenced before assignment
SystemError: could not initialize part 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "DEL_DATABASE_GUI.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\python3.6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\PySide2\__init__.py", line 51, in <module>
  File "site-packages\PySide2\__init__.py", line 21, in _setupQtDirectories
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\python3.6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
SystemError: PyEval_EvalFrameEx returned a result with an error set

**Comment by Legorooj** [comment]
Try with the option `--hidden-import=typing`? Does that work?
