### ISSUE TITLE
Pyinstaller not working with torchvision >= 3.0.0

### ISSUE THREAD

**Issue by Sstrap** [pyinstaller/pyinstaller#4740]
## Description of the issue

Pyinstaller frozen application that needs torchvision can't be properly run. The message error comes from `site-packages/torchvision/ops/misc.py`:

```
OSError: Can't get source for site-packages/torchvision/ops/misc.py. TorchScript requires source access in order to carry out compilation. Make sure original .py files are available. Original error: could not get source code
```
## Context information (for bug reports)

* Output of `pyinstaller --version`: `3.5`
* Version of Python: 3.6.10
* Pytorch version: 1.3.1
* torchvision version: 0.4.2
* Platform: e.g GNU/Linux (Ubuntu 16.04)

I simply run PyInstaller on the entry point of my program (`pyinstaller main.py`), the packaging run without throwing any error. 
I previously used `torchvision==0.2.2` and never encountered such an issue. Unfortunately, things  have changed with more recent version of torchvision.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "site-packages/torch/_utils_internal.py", line 46, in get_source_lines_and_file
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from transormators import get_transforms
  File "site-packages/torchvision/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/py36/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/torchvision/models/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/py36/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/py36/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/py36/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/torchvision/ops/misc.py", line 135, in <module>
  File "site-packages/torchvision/ops/misc.py", line 148, in FrozenBatchNorm2d
  File "site-packages/torch/jit/__init__.py", line 1280, in script_method
  File "site-packages/torch/jit/frontend.py", line 160, in get_jit_def
  File "site-packages/torch/_utils_internal.py", line 50, in get_source_lines_and_file
OSError: Can't get source for site-packages/torchvision/ops/misc.py. TorchScript requires source access in order to carry out compilation. Make sure original .py files are available. Original error: could not get source code
```

Has anyone encountered this issue ?

**Comment by nlowell11** [comment]
I have also been running into this issue, have not found a solution.

**Comment by Legorooj** [comment]
Please write a hook for PyInstaller & torch vision. The hook docs are available [here](https://pyinstaller.readthedocs.io/en/stable/hooks.html). The Dev team doesn't have time to write these.

**Comment by MengHao233** [comment]
I have also been running into this issue, have not found a solution. +1

**Comment by Amar-Unitek** [comment]
I am also stuck at the same issue. Please let me know if anyone has the solution

**Comment by Sstrap** [comment]
I posted a workaround here: https://github.com/pytorch/vision/issues/1899#issuecomment-598200938

Hope this will help you !
