### ISSUE TITLE
Error while packaging sentry with pyinstaller

### ISSUE THREAD

**Issue by harshithdwivedi** [pyinstaller/pyinstaller#4755]
## Description of the issue
I'm trying to package sentry_sdk with pyinstaller but it doesn't seem to work as I can't see it packaged in my app and running it throws an error about missing files related to sentry.

Version of the sentry sdk: 0.14.2

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7
* Platform: OS X

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. 

### A minimal example program which shows the error

Install the sentry-sdk
```
pip install sentry-sdk==0.14.2
```
Create and package a test main.py file
```
import sentry_sdk
# the contents of the init method don't matter
sentry_sdk.init("https://786465347564378658438684@sentry.io/7865487")

def main():
    print("Hello World")
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "aftershoot.py", line 17, in <module>
  File "sentry_sdk/hub.py", line 80, in _init
  File "sentry_sdk/client.py", line 80, in __init__
  File "sentry_sdk/client.py", line 110, in _init_impl
  File "sentry_sdk/integrations/__init__.py", line 106, in setup_integrations
  File "sentry_sdk/integrations/__init__.py", line 42, in iter_default_integrations
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sentry_sdk.integrations.logging'
[33776] Failed to execute script aftershoot
```

**Comment by Legorooj** [comment]
You'll need to write a hook for `sentry_sdk`. Please see https://pyinstaller.readthedocs.io/en/stable/hooks.html and submit a PR

**Comment by ohadlahav** [comment]
This did the trick for me:

add `hook-sentry_sdk.py` with:
`hiddenimports = [
    "sentry_sdk.integrations.stdlib",
    "sentry_sdk.integrations.excepthook",
    "sentry_sdk.integrations.dedupe",
    "sentry_sdk.integrations.atexit",
    "sentry_sdk.integrations.modules",
    "sentry_sdk.integrations.argv",
    "sentry_sdk.integrations.logging",
    "sentry_sdk.integrations.threading"
]`
