### ISSUE TITLE
PLease help urgent pkg_resources.DistributionNotFound: The 'checksumdir'

### ISSUE THREAD

**Issue by themeswordpress** [pyinstaller/pyinstaller#4757]
Dears, 

I have faced the following issue plz help urgently!

Traceback (most recent call last):
  File "fim2.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "checksumdir/__init__.py", line 19, in <module>
  File "pkg_resources/__init__.py", line 900, in require
  File "pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'checksumdir' distribution was not found and is required by the application
[7663] Failed to execute script fim2

**Comment by Legorooj** [comment]
@themeswordpress please create minimal, reproducible example.
