### ISSUE TITLE
Path of pyconfig.h in pyenv venv is outside of excpected scope

### ISSUE THREAD

**Issue by poudro** [pyinstaller/pyinstaller#4775]
## Description of the issue

When using `pyinstaller` within a `pyenv` virtualenv, `_find_prefix` raises an error.

The error is linked to `pyconfig.h` not being properly located within venv path by pyenv.

To be more precise, the `filename` parameter passed to `_find_prefix` is 
```
~/.pyenv/versions/3.7.6/include/python3.7m/pyconfig.h
```

When allowd prefixes is following list
```
 ['~/.pyenv/versions/3.7.6/envs/pyinst', '~/.pyenv/versions/3.7.6/Python.framework/Versions/3.7']
```

Thus `possible_prefixes` is an empty list when the function tries to return `possible_prefixes[0]` and thus exception is raised.

I have, locally, managed to fix this error by editing `PyInstaller/utils/hooks/__init__.py` and by adding 
```
    if not possible_prefixes:
        return os.path.dirname(filename)
```
before current return in `_find_prefix`.

I would be happy to issue a PR for this but I'm unsure it might have unwanted side-effects in other environments and/or platforms. So please let me know what I should do.

Thanks

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.6
* Platform: OS X
* pyenv: 1.2.16

### A minimal example program which shows the error

Very minimal flask app `api.py`:
```
from flask import Flask
from flask_restful import Resource, Api

app = Flask(__name__)
api = Api(app)

@api.resource('/')
class HelloWorld(Resource):
    def get(self):
        return {'hello': 'world'}

if __name__ == "__main__":
    app.run()
```

```
pyenv virtualenv 3.7.6 pyinst
pyenv activate pyinst
pip install pyinstaller flask flask_restful
pyinstaller --hidden-import='pkg_resources.py2_warn' api.py
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "~/.pyenv/versions/pyinst/bin/pyinstaller", line 10, in <module>
    sys.exit(run())
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "~/repos/continuity/pocs/lepton/api.spec", line 17, in <module>
    noarchive=False)
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 244, in __init__
    self.__postinit__()
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 422, in assemble
    self.graph.process_post_graph_hooks()
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 311, in process_post_graph_hooks
    module_hook.post_graph()
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 417, in post_graph
    self._load_hook_module()
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 384, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/compat.py", line 797, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/hooks/hook-sysconfig.py", line 32, in <module>
    datas = [(_CONFIG_H, relpath_to_config_or_make(_CONFIG_H))]
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/utils/hooks/__init__.py", line 808, in relpath_to_config_or_make
    prefix = _find_prefix(filename)
  File "~/.pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/utils/hooks/__init__.py", line 797, in _find_prefix
    return possible_prefixes[0]
IndexError: list index out of range
```

**Comment by poudro** [comment]
Here's the patch if it can help:
```
--- .pyenv/versions/3.7.6/lib/python3.7/site-packages/PyInstaller/utils/hooks/__init__.py	2020-03-31 10:31:17.000000000 +0200
+++ .pyenv/versions/3.7.6/envs/pyinst/lib/python3.7/site-packages/PyInstaller/utils/hooks/__init__.py	2020-03-31 10:40:38.000000000 +0200
@@ -793,6 +793,8 @@
         if common == prefix:
             possible_prefixes.append(prefix)
     possible_prefixes.sort(key=lambda p: len(p), reverse=True)
+    if not possible_prefixes:
+        return os.path.dirname(filename)
     return possible_prefixes[0]
```

**Comment by cooperbenson-qz** [comment]
This patched fixed the same exception when I was trying to build from a virtualenv created from a PyEnv executable.

**Comment by zivkasper** [comment]
also waiting for a fix for this..

**Comment by markine** [comment]
Same problem here with OS 10.15.5 and Python 3.6.6. Same patch for __init__.py resolves the issue.
