### ISSUE TITLE
Unpacked module wx._html

### ISSUE THREAD

**Issue by p-virex** [pyinstaller/pyinstaller#4785]
Hi. Faced a problem that the pyinstaller does not pack the wx._html module, and the application cannot start

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.5```
* Version of Python: 2.7.16
* Platform:  Windows-10-10.0.17763
* Did you also try this on another platform? Does it work there?
Only windows specific boot-loader.

### A minimal example program which shows the error

```
Traceback (most recent call last):
  File "myApps\myApps.py", line 7, in <module>
  File "c:\users\user\appdata\local\temp\pip-install-vfpn3q\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "myApps\module\PanelUi.py", line 2, in <module>
  File "c:\users\user\appdata\local\temp\pip-install-vfpn3q\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "site-packages\wx\richtext.py", line 17, in <module>
  File "c:\users\user\appdata\local\temp\pip-install-vfpn3q\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 684, in load_module
ImportError: No module named _html
[15740] Failed to execute script myApps
```

I tried to add hidden import to my spec file, but this did not work
```
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='myApps',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          hidden= "import wx._html",
          console=True , icon=os.path.join(cwd_path, 'res', 'logo.ico'))
```
This module is imported from wx.richtext
richtext.py
from ._richtext import *
_richtext\_init__.py

imports
import sip as __sip
import wx._adv as __wx__adv
import wx._core as __wx__core
import wx._html as __wx__html

**Comment by Legorooj** [comment]
As a wxPython lover myself, I can say it works fine on the latest version. Can you try installing the development release?

**Comment by p-virex** [comment]
Thank you!!! Solution:
```
 hiddenimports=["wx._html", "wx._xml"],
a = Analysis(['myApps.py'],
             pathex=[cwd_path],
             binaries=[],
             datas=[],
             hiddenimports=["wx._html", "wx._xml"],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
```
I'm just not attentive, excuse me
