### ISSUE TITLE
PyInstaller No module named 'tensorflow.lite.python.interpreter_wrapper'

### ISSUE THREAD

**Issue by tuvolon** [pyinstaller/pyinstaller#4792]
Running Tensorflow 1.14 on Pyinstaller runs into following error on execute:

Traceback (most recent call last):
  File "run.py", line 52, in <module>
  File "hand_tracker.py", line 33, in __init__
  File "tensorflow\lite\python\interpreter.py", line 205, in __init__
  File "tensorflow\python\util\lazy_loader.py", line 62, in __getattr__
  File "tensorflow\python\util\lazy_loader.py", line 45, in _load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow.lite.python.interpreter_wrapper'
[1020] Failed to execute script run
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

TF Version: 1.14
Python Version: 3.6.8
Pyinstaller Version: 3.5

**Comment by Legorooj** [comment]
PyInstaller 3.5 doesn't support tensorflow. Only the beta/development version - v4.0 - supports tensorflow, and only tensorflow 2.

**Comment by Legorooj** [comment]
You'll need to write a custom hook to fix this.
