### ISSUE TITLE
ImportError: DLL load failed while importing _socket: The parameter is incorrect.

### ISSUE THREAD

**Issue by waleedhammam** [pyinstaller/pyinstaller#4812]
## Description of the issue
-  I built my app using pyinstaller and worked on my machine, tried on different machine gave me the error.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: e.g. 3..8.2
* Platform: Windows 10
* Did you also try this on another platform? Does it work there?
tried on ubuntu 18.04 and worked

### Stacktrace / full error message

```
PS C:\Users\WDAGUtilityAccount\Desktop> .\3sdk.exe
Traceback (most recent call last):
  File "C:\Users\walee\AppData\Local\Programs\Python\Python38\Lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
  File "c:\users\walee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\pkg_resources\__init__.py", line 36, in <module>
  File "c:\users\walee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "email\parser.py", line 12, in <module>
  File "c:\users\walee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "email\feedparser.py", line 27, in <module>
  File "c:\users\walee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "email\_policybase.py", line 9, in <module>
  File "c:\users\walee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "email\utils.py", line 29, in <module>
  File "c:\users\walee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: The parameter is incorrect.
[3200] Failed to execute script pyi_rth_pkgres
```

**Comment by sergava** [comment]
Same issue on different machine on Windows 7. Pyinstaller version = 3.6

**Comment by waleedhammam** [comment]
Already resolved by adding it to hidden imports hooks file

**Comment by sergava** [comment]
> Already resolved by adding it to hidden imports hooks file

can you, please, explain details? How to do it?

**Comment by waleedhammam** [comment]
> > Already resolved by adding it to hidden imports hooks file
> 
> can you, please, explain details? How to do it?

used https://github.com/pyinstaller/pyinstaller/pull/3901
and created a hooks file with this hidden imports
hiddenimports = [your libaries]

don't know if it may works with the hidden imports int the spec file or not but that worked for me

**Comment by sergava** [comment]
hi, could you help me, I don't know what to import.
tried _socket, socket and it didn't work for me.

**Comment by Hvjoensenn** [comment]
me too. The same problem

**Comment by xiaojeff721** [comment]
This problem exists in Python 3.8.3, and I fall back to 3.7.8 to solve the problem.

**Comment by xiaojeff721** [comment]
This problem exists in Python 3.8.3, and I fall back to 3.7.8 to solve the problem.

**Comment by ManPython** [comment]
I sugesting to check this
https://github.com/pyinstaller/pyinstaller/issues/4855#issuecomment-676851508
