### ISSUE TITLE
hook-matplotlib.py broken when pathlib is installed via pip

### ISSUE THREAD

**Issue by auge** [pyinstaller/pyinstaller#4842]
## hook-matplotlib.py broken when pathlib is installed via pip

Although pathlib is now shipped with Python (>=3.4), one can still install it via pip - and there is no (easy?) way to prevent this.
Usually, we don't care since when we run `python -c "import pathlib; print(pathlib)"`, the Python-included module is loaded and used.
However, the hooks in pyinstaller seem to use the pip-version, which breaks the build procedure: e.g, the `matplotlib._get_data_path()` raises an exception and returns and empty string ...

the *simple* fix is to `pip uninstall pathlib` ... but it may cost other devs also many hours of hunting down this issue ... (at least now it should be documented)

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6``` (and on ```4.0.dev0+3010fdfaa0```
* Version of Python: e.g. 3.8.2
* Platform: GNU/Linux (Docker image: python:latest), Windows 10 (German/Austria)
* Did you also try this on another platform? Does it work there?
** tried on Windows 10 and Docker on Linux host

* try the latest development version, using the following command:
** done

* follow *all* the instructions in our "If Things Go Wrong" Guide
** the error happens way earlier ... in the hook phase

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
cli.py
```py
import matplotlib; print(matplotlib._get_data_path())
```
steps to reproduce
```sh
# prepare virtualenv (you may skip this)
pip install virtualenv
virtualenv venv
source venv/bin/activate

# install deps
pip install pyinstaller matplotlib pathlib

# build exe
pyinstaller --clean --console --onedir --noconfirm --noupx \
	--hidden-import=pkg_resources.py2_warn \
	--name=broken \
	cli.py
```

### Stacktrace / full error message

```
[...]
27337 INFO: Loading module hook "hook-matplotlib.backends.py"...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 1015, in <module>
    rcParams = rc_params()
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 878, in rc_params
    return rc_params_from_file(matplotlib_fname(), fail_on_error)
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 731, in matplotlib_fname
    for fname in gen_candidates():
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 728, in gen_candidates
    yield os.path.join(get_configdir(), 'matplotlibrc')
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 276, in wrapper
    ret = func(**kwargs)
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 609, in get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 562, in _get_xdg_config_dir
    return os.environ.get('XDG_CONFIG_HOME') or str(Path.home() / ".config")
AttributeError: type object 'Path' has no attribute 'home'
27827 INFO: Loading module hook "hook-matplotlib.py"...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 1015, in <module>
    rcParams = rc_params()
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 878, in rc_params
    return rc_params_from_file(matplotlib_fname(), fail_on_error)
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 731, in matplotlib_fname
    for fname in gen_candidates():
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 728, in gen_candidates
    yield os.path.join(get_configdir(), 'matplotlibrc')
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 276, in wrapper
    ret = func(**kwargs)
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 609, in get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "/builds/auge/mpl/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 562, in _get_xdg_config_dir
    return os.environ.get('XDG_CONFIG_HOME') or str(Path.home() / ".config")
AttributeError: type object 'Path' has no attribute 'home'
[...]
```

**Comment by Legorooj** [comment]
Hmm. How interesting. I'll add a note in the documentation - and the wiki.

Also, python 3.8 is unsupported. Support will arrive soon though.

**Comment by lemoncalamitous** [comment]
This also happened to me. I am using `Python 3.7.6`, `PyInstaller dev branch`, and `matplotlib==3.2.x`. I think there are breaking changes on `matplotlib 3.x.x`.

By using `matplotlib==2.2.5`, this worked on my end. Hope this helps.

**Comment by Legorooj** [comment]
@lemoncalamitous there are. We need to update the hook. Unfortunately, there are other more pressing bugs, but if you could fix the hook for matplotlib we'd happily accept the PR.

**Comment by Legorooj** [comment]
Closing: https://www.google.com/search?q=pyinstaller+matplotlib+pathlib+error&oq=pyinstaller+matplotlib+pathlib+error&aqs=chrome..69i57.13289j0j7&client=ms-android-hmd-rev2&sourceid=chrome-mobile&ie=UTF-8
