### ISSUE TITLE
Numpy Import Error

### ISSUE THREAD

**Issue by asrabon** [pyinstaller/pyinstaller#4862]
I have tried packaging an application with numpy and some computers the executable is working without issues other computers it fails on startup. Below is the output I get when creating the exe in debugging mode. I opened an issue with the numpy developers and they suspect the issue resides with Pyinstaller. Here is the thread from numpy: https://github.com/numpy/numpy/issues/16163

[23492] PyInstaller Bootloader 3.x
[23492] LOADER: executable is C:\Program Files (x86)\test\test\test.exe
[23492] LOADER: homepath is C:\Program Files (x86)\test\test
[23492] LOADER: _MEIPASS2 is NULL
[23492] LOADER: archivename is C:\Program Files (x86)\test\test\test.exe
[23492] LOADER: Extracting binaries
[23492] LOADER: Executing self as child
[23492] LOADER: set _MEIPASS2 to C:\Users\arabon\AppData\Local\Temp_MEI234922
[23492] LOADER: Setting up to run child
[23492] LOADER: Creating child process
[23492] LOADER: Waiting for child process to finish...
[16968] PyInstaller Bootloader 3.x
[16968] LOADER: executable is C:\Program Files (x86)\test\test\test.exe
[16968] LOADER: homepath is C:\Program Files (x86)\test\test
[16968] LOADER: _MEIPASS2 is C:\Users\arabon\AppData\Local\Temp_MEI234922
[16968] LOADER: archivename is C:\Program Files (x86)\test\test\test.exe
[16968] LOADER: SetDllDirectory(C:\Users\arabon\AppData\Local\Temp_MEI234922)
[16968] LOADER: Already in the child - running user's code.
[16968] LOADER: manifestpath: C:\Users\arabon\AppData\Local\Temp_MEI234922\test.exe.manifest
[16968] LOADER: Error activating the context: ActivateActCtx:
An attempt to set the process default activation context failed because the process default activation context was already set.

[16968] LOADER: ucrtbase.dll is exists: C:\Users\arabon\AppData\Local\Temp_MEI234922\ucrtbase.dll
[16968] LOADER: Python library: C:\Users\arabon\AppData\Local\Temp_MEI234922\python37.dll
[16968] LOADER: Loaded functions from Python library.
[16968] LOADER: Manipulating environment (sys.path, sys.prefix)
[16968] LOADER: sys.prefix is C:\Users\arabon\AppData\Local\Temp_MEI234922
[16968] LOADER: Pre-init sys.path is C:\Users\arabon\AppData\Local\Temp_MEI234922\base_library.zip;C:\Users\arabon\AppData\Local\Temp_MEI234922
[16968] LOADER: Setting runtime options
[16968] LOADER: Bootloader option: pyi-windows-manifest-filename test.exe.manifest
[16968] LOADER: Initializing python
[16968] LOADER: Overriding Python's sys.path
[16968] LOADER: Post-init sys.path is C:\Users\arabon\AppData\Local\Temp_MEI234922\base_library.zip;C:\Users\arabon\AppData\Local\Temp_MEI234922
[16968] LOADER: Setting sys.argv
[16968] LOADER: setting sys.MEIPASS
[16968] LOADER: importing modules from CArchive
[16968] LOADER: extracted struct
[16968] LOADER: callfunction returned...
[16968] LOADER: extracted pyimod01_os_path
[16968] LOADER: callfunction returned...
[16968] LOADER: extracted pyimod02_archive
[16968] LOADER: callfunction returned...
[16968] LOADER: extracted pyimod03_importers
[16968] LOADER: callfunction returned...
[16968] LOADER: Installing PYZ archive with Python modules.
[16968] LOADER: PYZ archive: PYZ-00.pyz
[16968] LOADER: Running pyiboot01_bootstrap.py
[16968] LOADER: Running pyi_rth_pkgres.py
[16968] LOADER: Running pyi_rth_win32comgenpy.py
[16968] LOADER: Running pyi_rth_mplconfig.py
[16968] LOADER: Running pyi_rth_mpldata.py
[16968] LOADER: Running pyi_rth_certifi.py
[16968] LOADER: Running pyi_rth__tkinter.py
[16968] LOADER: Running pyi_rth_multiprocessing.py
[16968] LOADER: Running SHUNTWin.py
Traceback (most recent call last):
File "site-packages\numpy\core_init.py", line 24, in
File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\numpy\core\multiarray.py", line 14, in
File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\numpy\core\overrides.py", line 7, in

**Comment by Legorooj** [comment]
We're missing the last half of the traceback. I can't help without it.

**Comment by Legorooj** [comment]
@asrabon hello? I can't help without this traceback.

**Comment by Legorooj** [comment]
Stale.
