### ISSUE TITLE
wxPython breaks locale

### ISSUE THREAD

**Issue by cwassert** [pyinstaller/pyinstaller#4874]
## Description of the issue
When using wxpython, datetime.strptime does not work anymore.

## Context information (for bug reports)
* Output of `pyinstaller --version`: 3.5
* Version of Python: e.g. 3.7.1

### A minimal example program which shows the error
```
import wx, datetime
app = wx.App(False)
print(datetime.datetime.strptime('2000-01-02T03:04:05', '%Y-%m-%dT%H:%M:%S'))
```

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "check.py", line 3, in <module>
    print(datetime.datetime.strptime('2000-01-02T03:04:05', '%Y-%m-%dT%H:%M:%S'))
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\python\python-3.7.1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "_strptime.py", line 277, in <module>
  File "_strptime.py", line 191, in __init__
  File "_strptime.py", line 69, in __init__
  File "_strptime.py", line 28, in _getlang
  File "C:\python\python-3.7.1\lib\locale.py", line 587, in getlocale
  File "C:\python\python-3.7.1\lib\locale.py", line 495, in _parse_localename
ValueError: unknown locale: en-US
[192] Failed to execute script check
```

**Comment by Legorooj** [comment]
Please upgrade PyInstaller to 3.6 and try again. I

**Comment by cwassert** [comment]
Confirmed for PyInstaller-3.6 with wxPython-4.1.0.

I tried to bisect the issue, because I am sure it was working at some point.
The culprit seems to be the 4.1.0 release of wxPython.

PyInstaller==3.4 wxPython==4.0.4 good
PyInstaller==3.6 wxPython==4.0.4 good
PyInstaller==3.6 wxPython==4.0.7 good
PyInstaller==3.6 wxPython==4.0.7.post2 good
PyInstaller==3.6 wxPython==4.1.0 bad

**Comment by Legorooj** [comment]
Let's focus on wxWidgets/Phoenix#1637 for now. If this is occurring when unfrozen, then fix that first. The chances are that fixing that will fix this.

**Comment by nauticalcoder** [comment]
I was also running into this on the Windows build.  This is not a permanent fix, but it is a fix for now until it gets resolved.  Immediately your instance of `wx.App` is created, add the following:
`    app = wx.App(False)
    import locale
    locale.setlocale(locale.LC_ALL, 'en_US')`
Of course this only works for English.  Apparently it is an issue with how Windows is returning the locale, en-US vs en_US.

**Comment by nauticalcoder** [comment]
Also see this ongoing discussion about the issue:
https://discuss.wxpython.org/t/what-is-wxpython-doing-to-the-locale-to-makes-pandas-crash/34606/5
