### ISSUE TITLE
No module named 'pkg_resources.py2_warn'

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#4910]
## Description of the issue
Getting the below error when running the script created with pyinstaller. 

Traceback (most recent call last):
  File "venvs\poker\Lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
  File "c:\users\dickr\python38\venvs\poker\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[21852] Failed to execute script pyi_rth_pkgres

## Context information (for bug reports)
328 INFO: PyInstaller: 3.6
328 INFO: Python: 3.8.3
330 INFO: Platform: Windows-10-10.0.18362-SP0
344 INFO: UPX is not available.

**Comment by Legorooj** [comment]
This has already been fixed. It'll be released in 4.0; hopefully this month.
