### ISSUE TITLE
GstPlayerException: Unable to create a playbin

### ISSUE THREAD

**Issue by DaytonaJohn** [pyinstaller/pyinstaller#4911]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
Kivy VideoPlayer works fine if not in a frozen exe. But when running the exe produced by Pyinstaller, I get the subject error.

## Context information (for bug reports)
This is an old bug that was reportedly fixed, but I am seeing it again. It also appears when I used the current stable version of Pyinstaller (3.6).

* Output of `pyinstaller --version`: ```(4.0.dev0)```
* Version of Python: 3.6.2
* Kivy version: 1.11.1
* Platform: Windows 10
* Did you also try this on another platform? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import sys
import kivy
from kivy.app import App
from kivy.uix.videoplayer import VideoPlayer

if hasattr(sys, '_MEIPASS'):
    print('running in a PyInstaller bundle at', sys._MEIPASS)
    kivy.resources.resource_add_path(sys._MEIPASS)

class TestApp(App):
    def build(self):
        return VideoPlayer(source='cityCC0.mpg')

if __name__ == "__main__":
    TestApp().run()
```

Here is my main.spec:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\Users\\John\\Documents\\PyCharmProjects\\PyinstallerVideoBug'],
             binaries=[],
             datas=[('cityCC0.mpg', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=1,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )

```

and my Pyinstaller output.log is at https://gist.github.com/DaytonaJohn/38b2631ddc0698eb03eb7b4f14ae0864

### Stacktrace / full error message

```

[14928] PyInstaller Bootloader 3.x
[14928] LOADER: executable is C:\Users\John\Documents\PyCharmProjects\PyinstallerVideoBug\dist\main.exe
[14928] LOADER: homepath is C:\Users\John\Documents\PyCharmProjects\PyinstallerVideoBug\dist
[14928] LOADER: _MEIPASS2 is NULL
[14928] LOADER: archivename is C:\Users\John\Documents\PyCharmProjects\PyinstallerVideoBug\dist\main.exe
[14928] LOADER: Extracting binaries
[14928] LOADER: Executing self as child
[14928] LOADER: set _MEIPASS2 to C:\Users\John\AppData\Local\Temp\_MEI149282
[14928] LOADER: Setting up to run child
[14928] LOADER: Creating child process
[14928] LOADER: Waiting for child process to finish...
[7884] PyInstaller Bootloader 3.x
[7884] LOADER: executable is C:\Users\John\Documents\PyCharmProjects\PyinstallerVideoBug\dist\main.exe
[7884] LOADER: homepath is C:\Users\John\Documents\PyCharmProjects\PyinstallerVideoBug\dist
[7884] LOADER: _MEIPASS2 is C:\Users\John\AppData\Local\Temp\_MEI149282
[7884] LOADER: archivename is C:\Users\John\Documents\PyCharmProjects\PyinstallerVideoBug\dist\main.exe
[7884] LOADER: SetDllDirectory(C:\Users\John\AppData\Local\Temp\_MEI149282)
[7884] LOADER: Already in the child - running user's code.
[7884] LOADER: manifestpath: C:\Users\John\AppData\Local\Temp\_MEI149282\main.exe.manifest
[7884] LOADER: Activation context created
[7884] LOADER: Activation context activated
[7884] LOADER: Python library: C:\Users\John\AppData\Local\Temp\_MEI149282\python36.dll
[7884] LOADER: Loaded functions from Python library.
[7884] LOADER: Manipulating environment (sys.path, sys.prefix)
[7884] LOADER: sys.prefix is C:\Users\John\AppData\Local\Temp\_MEI149282
[7884] LOADER: Pre-init sys.path is C:\Users\John\AppData\Local\Temp\_MEI149282\base_library.zip;C:\Users\John\AppData\Local\Temp\_MEI149282
[7884] LOADER: Setting runtime options
[7884] LOADER: Bootloader option: pyi-windows-manifest-filename main.exe.manifest
[7884] LOADER: Initializing python
[7884] LOADER: Overriding Python's sys.path
[7884] LOADER: Post-init sys.path is C:\Users\John\AppData\Local\Temp\_MEI149282\base_library.zip;C:\Users\John\AppData\Local\Temp\_MEI149282
[7884] LOADER: Setting sys.argv
[7884] LOADER: setting sys._MEIPASS
[7884] LOADER: importing modules from CArchive
[7884] LOADER: extracted struct
[7884] LOADER: callfunction returned...
[7884] LOADER: extracted pyimod01_os_path
[7884] LOADER: callfunction returned...
[7884] LOADER: extracted pyimod02_archive
[7884] LOADER: callfunction returned...
[7884] LOADER: extracted pyimod03_importers
[7884] LOADER: callfunction returned...
[7884] LOADER: Installing PYZ archive with Python modules.
[7884] LOADER: PYZ archive: PYZ-00.pyz
[7884] LOADER: Running pyiboot01_bootstrap.py
[7884] LOADER: Running pyi_rth_multiprocessing.py
[7884] LOADER: Running pyi_rth_pkgres.py
[7884] LOADER: Running pyi_rth_win32comgenpy.py
[7884] LOADER: Running pyi_rth_gstreamer.py
[7884] LOADER: Running pyi_rth_kivy.py
[7884] LOADER: Running main.py
[INFO   ] [Logger      ] Record log in C:\Users\John\.kivy\logs\kivy_20-06-01_31.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\John\AppData\Local\Temp\_MEI149282\kivy\__init__.pyc"
[INFO   ] [Python      ] v3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\John\Documents\PyCharmProjects\PyinstallerVideoBug\dist\main.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoGstplayer] Using Gstreamer 1.16.0.0
[INFO   ] [Video       ] Provider: gstplayer
running in a PyInstaller bundle at C:\Users\John\AppData\Local\Temp\_MEI149282
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.4.0 - Build 20.19.15.5058'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 5500'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <b'4.40 - Build 20.19.15.5058'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[WARNING] [Image       ] Unable to load image <C:\Users\John\AppData\Local\Temp\_MEI149282\cityCC0.mpg>
[ERROR  ] [Image       ] Error loading texture cityCC0.mpg
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 15, in <module>
   File "site-packages\kivy\app.py", line 855, in run
   File "site-packages\kivy\base.py", line 504, in runTouchApp
   File "site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
   File "site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
   File "site-packages\kivy\base.py", line 348, in idle
   File "site-packages\kivy\clock.py", line 598, in tick_draw
   File "kivy\_clock.pyx", line 427, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 467, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 465, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "site-packages\kivy\uix\video.py", line 183, in _do_video_load
   File "site-packages\kivy\core\video\video_gstplayer.py", line 62, in __init__
   File "site-packages\kivy\core\video\__init__.py", line 84, in __init__
     def stop(win, ctx):
   File "site-packages\kivy\core\video\__init__.py", line 116, in <lambda>

   File "site-packages\kivy\core\video\__init__.py", line 113, in _set_filename
     def __repr__(self):
   File "site-packages\kivy\core\video\video_gstplayer.py", line 74, in load
   File "kivy\lib\gstplayer\_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load
 kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin. Consider setting the environment variable GST_REGISTRY to a user accesible path, such as ~/registry.bin
[7884] Failed to execute script main
[7884] LOADER: OK.
[7884] LOADER: Cleaning up Python interpreter.
[14928] LOADER: Back to parent (RC: -1)
[14928] LOADER: Doing cleanup
[14928] LOADER: Freeing archive status for C:\Users\John\Documents\PyCharmProjects\PyinstallerVideoBug\dist\main.exe
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by Legorooj** [comment]
I managed to replicate. I'll get to fixing this when I have time.
