### ISSUE TITLE
I made an executable using pyinstaller. It works fine on my PC. But on another PC it gives the following error

### ISSUE THREAD

**Issue by Srujan-Patel** [pyinstaller/pyinstaller#4923]
```
Traceback (most recent call last):
  File "Classifier.py", line 6, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\keras\__init__.py", line 3, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\keras\utils\__init__.py", line 6, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\keras\utils\conv_utils.py", line 9, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\keras\backend\__init__.py", line 1, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\keras\backend\load_backend.py", line 90, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\tensorflow\__init__.py", line 101, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\tensorflow_core\__init__.py", line 40, in <module>
  File "site-packages\tensorflow\__init__.py", line 50, in __getattr__
  File "site-packages\tensorflow\__init__.py", line 44, in _load
  File "importlib\__init__.py", line 127, in import_module
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
  File "c:\users\srujan\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 30, in <module>
  File "site-packages\tensorflow_core\python\platform\self_check.py", line 60, in preload_check
ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
[7612] Failed to execute script Classifier
```

**Comment by Legorooj** [comment]
Which version of tensorflow are you using? And can you `pip install -U https://github.com/pyinstaller/pyinstaller/archive/develop.zip` and try building again?

**Comment by Srujan-Patel** [comment]
My tensorflow version is 2.0.0

**Comment by Legorooj** [comment]
Can you try installing the development version of PyInstaller with the above command and upgrading to tensorflow 2.1?

**Comment by Srujan-Patel** [comment]
it worked thanks!
