### ISSUE TITLE
Conda in macOS gives "TypeError: expected str, bytes or os.PathLike object, not NoneType"

### ISSUE THREAD

**Issue by thekswenson** [pyinstaller/pyinstaller#4925]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0dev0```
* Version of Python: 3.7.7
* Platform: OS X, conda
* Did you also try this on another platform? Does it work there?

My first attempt was with homebrew. Pyinstaller terminated and created the appropriate .app directory. The frozen program ran but was buggy, probably because homebrew's default python is now 3.8.  It is very difficult to downgrade all the necessary packages to 3.7 in homebrew. The only other solution I have thought of is conda, since it's easy to force everything to 3.7.

### A minimal example program which shows the error

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

win = Gtk.Window()

hbox = Gtk.Box()
hbox.pack_start(Gtk.Label(label='Will this work?'), False, False, 0)

win.add(hbox)
win.show_all()

win.connect("delete-event", Gtk.main_quit)
Gtk.main()
```

### Stacktrace / full error message

```
13065 INFO: Loading module hook 'hook-gi.repository.Gio.py' from '/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/hooks'...
Traceback (most recent call last):
  File "/Users/kms/opt/miniconda3/envs/alpha/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 713, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 660, in build
    exec(code, spec_namespace)
  File "/Users/kms/pyinstaller_bug/minimal_gtk.spec", line 17, in <module>
    noarchive=False)
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 238, in __init__
    self.__postinit__()
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 415, in assemble
    self.graph.process_post_graph_hooks()
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 359, in process_post_graph_hooks
    module_hook.post_graph()
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 420, in post_graph
    self._load_hook_module()
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 387, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/compat.py", line 588, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/hooks/hook-gi.repository.Gio.py", line 32, in <module>
    libdir = get_gi_libdir('Gio', '2.0')
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/site-packages/PyInstaller/utils/hooks/gi.py", line 46, in get_gi_libdir
    return os.path.normpath(os.path.dirname(path))
  File "/Users/kms/opt/miniconda3/envs/alpha/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by thekswenson** [comment]
Two similar bugs are the following:

- https://github.com/pyinstaller/pyinstaller/issues/4200
- https://github.com/mhallsmoore/qstrader/issues/322

One of the solution was to run pyinstaller outside of the virtual environment. This doesn't seem to be an option on macOS because conda is necessary for installing all of the dependencies. Or should I leave the environment and set PATH and PYTHONPATH to the virtual environment? Would this work?

**Comment by thekswenson** [comment]
I've been digging into it...
  it turns out that depend.binddepend.findSystemLibrary() uses ctypes.util.find_library() to find the system libraries, but find_library() is broken in conda:

https://github.com/ContinuumIO/anaconda-issues/issues/1716

The bug seems to be open still (from 2017) although there is a patch proposed. The proposed workaround of setting DYLD_LIBRARY_PATH either does not work, or I don't set it properly.

**Comment by thekswenson** [comment]
Setting DYLD_FALLBACK_LIBRARY_PATH to my `lib/` directory in my conda environment is a viable workaround for this minimal example.

I'm not sure how to fix pyinstaller to avoid setting this variable. The conda issue has been around since 2017.

**Comment by thekswenson** [comment]
I've reproduced the setup in conda on ubuntu 20.04, and I don't need to set DYLD_FALLBACK_LIBRARY_PATH.

**Comment by furrerc** [comment]
I ran into this same issue, but I'm not sure it's because find_library is "broken". 

If you add a little print statement in the ```bindepend.py``` file, you'll see the library name passed to find_library includes both the "lib" and ".dylib" or ".so" suffix. In my case, it was doing

```
cytpes.util.find_library("libgio-2.0.0.dylib")
```

ctypes documentation specifies that we must only pass the library name in, without prefix or suffix. If you strip the prefix and suffix in the source code, doing something like:

```
replace_strs = [".dylib",".so","lib"]
for replace_str in replace_strs: name = name.replace(replace_str, "")
return ctypes.util.find_library(name)
```

The script works successfully, as it produces a valid search for ```ctypes.util.find_library("gio-2.0.0")``` I'm not sure what to do about this fix. I don't have much experience with open source software.
