### ISSUE TITLE
pyinstaller not working with ssl import

### ISSUE THREAD

**Issue by DEEP7696** [pyinstaller/pyinstaller#4927]
pyinstaller not working with ssl import

## Context information (for bug reports)

* Output of `pyinstaller --version`: 3.6
* Version of Python:  3.7
* Platform: Windows 7, conda
just working on development system

Not working on: win7,win10

* try the latest development version, using the following command:
tried and encountered with same error:
version :  4.0.dev0

### A minimal example program which shows the error
just trying with this:

import ssl
print(ssl.__file__)

### Stacktrace / full error message

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "c:\programdata\anaconda3\envs\scrap\lib\site-packages\PyInstaller\loader
\pyimod03_importers.py", line 623, in exec_module
  File "ssl.py", line 98, in <module>
ImportError: DLL load failed: The specified module could not be found.
[2232] Failed to execute script test

**Comment by DEEP7696** [comment]
Tried with python3.6 and issue resolved.
I think there is issue with python 3.7=<
