### ISSUE TITLE
 Failed to load dynlib/dll 'D:\\Users\\16886\\Desktop\\molpy\\caffe2_detectron_ops.dll'.

### ISSUE THREAD

**Issue by caiyingchun** [pyinstaller/pyinstaller#4935]
The code successfully works while executing using CMD , but when it is binded to *.exe file using Pyinstaller, It throws an error and stops executing (the Message is given below). I tried all possible solutions by linking the path library and other stuff too. Any tries failed, although the file ```caffe2_detectron_ops.dll``` was included in the right folder.
OS system: win10
Python 3.7
Pyinstaller3.6
Pytorch1.5.0
PyQt5

```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 151, in __init__
  File "ctypes\__init__.py", line 364, in __init__
OSError: [WinError 126] 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MolPy\molpy.py", line 21, in <module>
    from dgljtnn.molecule_generation import generate
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\Program\PyMOL-2.3.4_121-Win64-portable-py37\PyMOL\envs\molpy\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "MolPy\dgljtnn\molecule_generation.py", line 4, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\Program\PyMOL-2.3.4_121-Win64-portable-py37\PyMOL\envs\molpy\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torch\__init__.py", line 81, in <module>
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 153, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'D:\\Users\\16886\\Desktop\\molpy\\caffe2_detectron_ops.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[20848] Failed to execute script molpy
```
Who can help me? Thanks very much.

**Comment by JStuckner** [comment]
Did you ever solve this problem?  I have the same problem?

**Comment by caiyingchun** [comment]
@JStuckner Yes, I solved the problem. inter-openmp is needed by pytorch. 
You can check https://github.com/pytorch/pytorch/issues/35803
```pip install intel-openmp```
After installing this library, copy ```libiomp5md.dll```, ```libiomp5md.pdb```, and ```libiompstubs5md.dll``` from ../Library/bin to your *.exe folder. It will work.

**Comment by maisonhai3** [comment]
I solved this problem by:
1. Conda uninstall torch, torchvision and relatings. I used conda to install torch as guided by pytorch.com
2. Using pip to install torch, torchvision.

**Comment by KiteFlyKid** [comment]
> I solved this problem by:
> 
> 1. Conda uninstall torch, torchvision and relatings. I used conda to install torch as guided by pytorch.com
> 2. Using pip to install torch, torchvision.

It works. The [solution provided by Anaconda](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment) doesn't work at all. Just refuse conda.
