### ISSUE TITLE
Cannot run succesfully frozen project because of _audio_microfrontend.so (Tensorflow)

### ISSUE THREAD

**Issue by JRitmeester** [pyinstaller/pyinstaller#4937]
## Description of the issue
Cannot freeze project using tensorflow, because it keeps missing a very specific .so file. I have tried adding it as a binary, but the error persists. I have been scouring the internet for 3 days now, and it is crucial I get this working, so any help is greatly appreciated!

## Context information (for bug reports)

* Output of `pyinstaller --version`: `3.6`
* Version of Python:  `Python 3.8.0`
* Platform: Windows 10
* Did you also try this on another platform? Does it work there?
I haven't tried.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Already tried.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong)
Tried.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### main.spec
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['E:\\Programmeren\\FER_Origin\\venv\\Lib\\site-packages', 'E:\\Programmeren\\FER_Origin\\venv'],
             binaries=[('E:/Programmeren/FER_Origin/venv/Lib/site-packages/tensorflow/lite/experimental/microfrontend/python/ops/_audio_microfrontend_op.so', '.')],
             datas=[('emotions', 'emotions'),
             ('logs', 'logs')],
             hiddenimports=['pkg_resources.py2_warn', 'tensorflow'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
```
### Stacktrace / full error message

```
E:\Programmeren\FER_Origin\venv\dist>main.exe
[8476] PyInstaller Bootloader 3.x
[8476] LOADER: executable is E:\Programmeren\FER_Origin\venv\dist\main.exe
[8476] LOADER: homepath is E:\Programmeren\FER_Origin\venv\dist
[8476] LOADER: _MEIPASS2 is NULL
[8476] LOADER: archivename is E:\Programmeren\FER_Origin\venv\dist\main.exe
[8476] LOADER: Extracting binaries
[8476] LOADER: Executing self as child
[8476] LOADER: set _MEIPASS2 to C:\Users\Jeroen\AppData\Local\Temp\_MEI84762
[8476] LOADER: Setting up to run child
[8476] LOADER: Creating child process
[8476] LOADER: Waiting for child process to finish...
[12528] PyInstaller Bootloader 3.x
[12528] LOADER: executable is E:\Programmeren\FER_Origin\venv\dist\main.exe
[12528] LOADER: homepath is E:\Programmeren\FER_Origin\venv\dist
[12528] LOADER: _MEIPASS2 is C:\Users\Jeroen\AppData\Local\Temp\_MEI84762
[12528] LOADER: archivename is E:\Programmeren\FER_Origin\venv\dist\main.exe
[12528] LOADER: SetDllDirectory(C:\Users\Jeroen\AppData\Local\Temp\_MEI84762)
[12528] LOADER: Already in the child - running user's code.
[12528] LOADER: manifestpath: C:\Users\Jeroen\AppData\Local\Temp\_MEI84762\main.exe.manifest
[12528] LOADER: Activation context created
[12528] LOADER: Activation context activated
[12528] LOADER: Python library: C:\Users\Jeroen\AppData\Local\Temp\_MEI84762\python38.dll
[12528] LOADER: Loaded functions from Python library.
[12528] LOADER: Manipulating environment (sys.path, sys.prefix)
[12528] LOADER: sys.prefix is C:\Users\Jeroen\AppData\Local\Temp\_MEI84762
[12528] LOADER: Pre-init sys.path is C:\Users\Jeroen\AppData\Local\Temp\_MEI84762\base_library.zip;C:\Users\Jeroen\AppData\Local\Temp\_MEI84762
[12528] LOADER: Setting runtime options
[12528] LOADER: Bootloader option: pyi-windows-manifest-filename main.exe.manifest
[12528] LOADER: Initializing python
[12528] LOADER: Overriding Python's sys.path
[12528] LOADER: Post-init sys.path is C:\Users\Jeroen\AppData\Local\Temp\_MEI84762\base_library.zip;C:\Users\Jeroen\AppData\Local\Temp\_MEI84762
[12528] LOADER: Setting sys.argv
[12528] LOADER: setting sys._MEIPASS
[12528] LOADER: importing modules from CArchive
[12528] LOADER: extracted struct
[12528] LOADER: callfunction returned...
[12528] LOADER: extracted pyimod01_os_path
[12528] LOADER: callfunction returned...
[12528] LOADER: extracted pyimod02_archive
[12528] LOADER: callfunction returned...
[12528] LOADER: extracted pyimod03_importers
[12528] LOADER: callfunction returned...
[12528] LOADER: Installing PYZ archive with Python modules.
[12528] LOADER: PYZ archive: PYZ-00.pyz
[12528] LOADER: Running pyiboot01_bootstrap.py
[12528] LOADER: Running pyi_rth_multiprocessing.py
[12528] LOADER: Running pyi_rth_pkgres.py
[12528] LOADER: Running pyi_rth_mplconfig.py
[12528] LOADER: Running pyi_rth_mpldata.py
[12528] LOADER: Running pyi_rth_certifi.py
[12528] LOADER: Running pyi_rth__tkinter.py
[12528] LOADER: Running main.py
e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:489: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
2020-06-15 16:37:33.372523: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-15 16:37:33.467590: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "emotions.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\__init__.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\_api\v2\compat\__init__.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\_api\v2\compat\v1\compat\v1\__init__.py", line 51, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\_api\v2\compat\v1\lite\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\_api\v2\compat\v1\lite\experimental\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\_api\v2\compat\v1\lite\experimental\nn\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\lite\python\lite.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "e:\programmeren\fer_origin\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\tensorflow\lite\experimental\microfrontend\python\ops\audio_microfrontend_op.py", line 29, in <module>
  File "Lib\site-packages\tensorflow\python\framework\load_library.py", line 58, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\Jeroen\AppData\Local\Temp\_MEI84762\tensorflow\lite\experimental\microfrontend\python\ops\_audio_microfrontend_op.so not found
[12528] Failed to execute script main
[12528] LOADER: OK.
[12528] LOADER: Cleaning up Python interpreter.
[8476] LOADER: Back to parent (RC: -1)
[8476] LOADER: Doing cleanup
[8476] LOADER: Freeing archive status for E:\Programmeren\FER_Origin\venv\dist\main.exe
```

**Comment by Legorooj** [comment]
The latest development version should give you a different error because hooks have been added to PyInstaller for tensorflow. You're sure you tried the development version?

**Comment by Legorooj** [comment]
@JRitmeester pinging

**Comment by JRitmeester** [comment]
Yes, I am sure. I installed it directly from a URL. However I am not going to need help anymore, as Ive already distributed my software is unfrozen. Thankd anyway.

**Comment by Angeloabrita** [comment]
I'm with same problem, is there solution for this?

My pip setup:

- pyinstaller              4.0.dev0
- tensorboard              2.2.2
- tensorboard-plugin-wit   1.6.0.post2
- tensorflow               2.2.0
- tensorflow-estimator     2.2.0
- tensorflow-gpu           1.15.0
- tensorflow-gpu-estimator 2.1.0
- termcolor                1.1.0
- tf-estimator-nightly     2.3.0.dev2020032201

_output// ....\tensorflow\lite\experimental\microfrontend\python\ops\_audio_microfrontend_op.so not found_

It is my spec:
```
block_cipher = None
from kivy_deps import sdl2, glew, gstreamer


a = Analysis(['Main.py'],
             pathex=['C:\\Users\\blabla\\Desktop\\detector\\'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='MaskDetector',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True , icon='icons\\icoagta.ico')
coll = COLLECT(exe,Tree('C:\\Users\\blabla\Desktop\\detector'),
               a.binaries,
               a.zipfiles,
               a.datas,
              *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins + gstreamer.dep_bins)],
               strip=False,
               upx=True,
               upx_exclude=[],
               name='Detector')

```
