### ISSUE TITLE
RuntimeError: Attempted implicit compile of a cffi module

### ISSUE THREAD

**Issue by tamil07** [pyinstaller/pyinstaller#4956]
I am trying to create a Binary in the Redhat 7.2 machine and it is failing due to the below error.

RuntimeError: Attempted implicit compile of a cffi module

The detailed log below

```
[root@rhel72-base latest_code_Windows_1]# pyinstaller  --onefile script_name_new.py --name PackageName_RHEL72
45 INFO: PyInstaller: 3.6
45 INFO: Python: 2.7.5
45 INFO: Platform: Linux-3.10.0-327.el7.x86_64-x86_64-with-redhat-7.2-Maipo
46 INFO: wrote /root/latest_code_Windows_1/PackageName_RHEL72.spec
49 INFO: UPX is not available.
50 INFO: Extending PYTHONPATH with paths
['/root', '/root/latest_code_Windows_1']
50 INFO: checking Analysis
57 INFO: Building because /usr/lib/python2.7/site-packages/requests/__init__.py changed
57 INFO: Initializing module dependency graph...
59 INFO: Caching module graph hooks...
63 INFO: Caching module dependency graph...
74 INFO: running Analysis Analysis-00.toc
84 INFO: Analyzing /root/latest_code_Windows_1/axinstall_new.py
1269 INFO: Processing pre-safe import module hook   _xmlplus
1689 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
3589 INFO: Processing pre-find module path hook   distutils
3589 INFO: distutils: retargeting to non-venv dir '/usr/lib64/python2.7'
5030 INFO: Processing pre-safe import module hook   win32com
5050 INFO: Processing pre-find module path hook   site
5050 INFO: site: retargeting to fake-dir '/usr/lib/python2.7/site-packages/PyInstaller/fake-modules'
6559 INFO: Processing module hooks...
6560 INFO: Loading module hook "hook-distutils.py"...
6560 INFO: Loading module hook "hook-sysconfig.py"...
6561 INFO: Loading module hook "hook-pycparser.py"...
6561 INFO: Loading module hook "hook-httplib.py"...
6561 INFO: Loading module hook "hook-xml.py"...
6622 INFO: Loading module hook "hook-pkg_resources.py"...
6623 INFO: Excluding import '__main__'
6624 INFO:   Removing import of __main__ from module pkg_resources
6624 INFO: Loading module hook "hook-certifi.py"...
6625 INFO: Loading module hook "hook-setuptools.py"...
6640 WARNING: Hidden import "setuptools.msvc" not found!
6640 INFO: Loading module hook "hook-cryptography.py"...
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecImportExportPassphrase' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecImportExportKeychain' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecImportExportAccess' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecEncryptionMode' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecEncryptKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecIVKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecModeCBCKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecModeCFBKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecModeECBKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecModeNoneKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecModeOFBKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecOAEPEncodingParametersAttributeName' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingNoneKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingOAEPKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingPKCS1Key' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingPKCS5Key' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingPKCS7Key' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecInputIsAttributeName' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecInputIsPlainText' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecInputIsDigest' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/lib64/python2.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecInputIsRaw' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 20, in walk_packages
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/commoncrypto/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.commoncrypto.backend import backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/commoncrypto/backend.py", line 244, in <module>
    backend = Backend()
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/commoncrypto/backend.py", line 44, in __init__
    self._binding = Binding()
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/commoncrypto/binding.py", line 43, in __init__
    self._ensure_ffi_initialized()
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/commoncrypto/binding.py", line 55, in _ensure_ffi_initialized
    modules=cls._modules,
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 104, in load_library
    self._compile_module()
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 127, in _compile_module
    "Attempted implicit compile of a cffi module. All cffi modules should "
RuntimeError: Attempted implicit compile of a cffi module. All cffi modules should be pre-compiled at installation time.
6930 INFO: Loading module hook "hook-encodings.py"...
7349 INFO: Looking for ctypes DLLs
7380 INFO: Analyzing run-time hooks ...
7386 INFO: Including run-time hook 'pyi_rth_certifi.py'
7387 INFO: Including run-time hook 'pyi_rth_pkgres.py'
7394 INFO: Looking for dynamic libraries
7780 INFO: Looking for eggs
7780 INFO: Using Python library /lib64/libpython2.7.so.1.0
7786 INFO: Warnings written to /root/latest_code_Windows_1/build/PackageName_RHEL72/warn-PackageName_RHEL72.txt
7834 INFO: Graph cross-reference written to /root/latest_code_Windows_1/build/PackageName_RHEL72/xref-PackageName_RHEL72.html
7928 INFO: checking PYZ
7933 INFO: Building because /usr/lib/python2.7/site-packages/requests/__init__.py changed
7933 INFO: Building PYZ (ZlibArchive) /root/latest_code_Windows_1/build/PackageName_RHEL72/PYZ-00.pyz
8509 INFO: Building PYZ (ZlibArchive) /root/latest_code_Windows_1/build/PackageName_RHEL72/PYZ-00.pyz completed successfully.
8598 INFO: checking PKG
8599 INFO: Building because /root/latest_code_Windows_1/build/PackageName_RHEL72/PYZ-00.pyz changed
8599 INFO: Building PKG (CArchive) PKG-00.pkg
11509 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
11522 INFO: Bootloader /usr/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
11522 INFO: checking EXE
11524 INFO: Rebuilding EXE-00.toc because PackageName_RHEL72 missing
11524 INFO: Building EXE from EXE-00.toc
11524 INFO: Appending archive to ELF section in EXE /root/latest_code_Windows_1/dist/PackageName_RHEL72
11536 INFO: Building EXE from EXE-00.toc completed successfully.
```

Please find the list of modules available in the machine right now. Looking forward to your help

```
[root@rhel72-base dist]# python -m pip freeze
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: Could not generate requirement for distribution -ipap11helper 0.1 (/usr/lib64/python2.7/site-packages): Parse error at "'-ipap11h'": Expected W:(abcd...)
altgraph==0.17
backports.ssl-match-hostname==3.4.0.2
blivet==0.61.15.37
Brlapi==0.6.0
certifi @ file:///root/latest_code_Windows_1/dist/certifi-2020.6.20-py2.py3-none-any.whl
cffi==1.14.0
chardet @ file:///root/latest_code_Windows_1/dist/chardet-3.0.4-py2.py3-none-any.whl
configobj==4.7.2
configshell-fb==1.1.18
coverage==3.6b3
cryptography==0.8.2
cupshelpers==1.0
decorator==3.4.0
di==0.3
dis3==0.1.3
dnspython==1.12.0
enum34==1.0.4
ethtool==0.8
firstboot==19.5
freeipa==2.0.0a0
fros==1.0
idna==2.10
iniparse==0.4
initial-setup==0.3.9.30
iotop==0.6
ipaddr==2.1.9
ipaplatform==4.2.0
ipapython==4.2.0
IPy==0.75
javapackages==1.0.0
jsonpointer==1.9
kdcproxy==0.3.2
kerberos==1.1
kitchen==1.1.1
kmod==0.1
langtable==0.0.31
lvm===2.02.130-2-RHEL7.-2015-10-14-
lxml==3.2.1
M2Crypto==0.21.1
Magic-file-extensions==0.2
netaddr==0.7.5
ntplib==0.3.2
openlmi==0.5.0
openlmi-software==0.5.0
openlmi-storage==0.8.0
pciutils==1.7.3
pcp==1.0
perf==0.1
ply==3.4
policycoreutils-default-encoding==0.1
pyasn1==0.1.6
pycparser==2.20
pycups==1.9.63
pycurl==7.19.0
pygobject==3.14.0
pygpgme==0.3
pyinotify==0.9.4
PyInstaller==3.6
pykickstart==1.99.66.6
pyliblzma==0.5.3
pyOpenSSL==0.13.1
pyparsing==1.5.6
pyparted==3.9
pysmbc==1.0.13
python-augeas==0.5.0
python-dateutil==1.5
python-default-encoding==0.1
python-dmidecode==3.10.13
python-ldap==2.4.15
python-meh==0.25.2
python-memcached==1.48
python-nss==0.16.0
python-yubico==1.2.3
pytz===2012d
pyudev==0.15
pyusb==1.0.0b1
pywbem==0.7.0
pyxattr==0.5.1
PyYAML==3.10
qrcode==5.0.1
redhat-access-insights==1.0.6
requests==2.24.0
rhnlib==2.5.65
rhsm==1.15.4
rtslib-fb==2.1.57
scdate==1.10.6
seobject==0.1
sepolicy==1.1
setproctitle==1.1.6
setroubleshoot==1.1
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
SSSDConfig==1.13.0
targetcli-fb===2.1.fb41
targetd==0.7
urlgrabber==3.10
urllib3 @ file:///root/latest_code_Windows_1/dist/urllib3-1.25.9-py2.py3-none-any.whl
urwid==1.1.1
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4

```

**Comment by Legorooj** [comment]
Try updating your version of `cryptography`: `python -m pip install cryptography==2.9.2`. This version still supports python 2.7.

**Comment by tamil07** [comment]
Thank you, that helped a lot. When trying to run the converted binary out of a python package - we are facing issues.  As a program, things are working fine.

The error which we get while running the binary is below. Let us know if this can be fixed? 

```
/tmp/_MEI6wpVdI/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.19.1) or chardet (3.0.4) doesn't match a supported version!
Traceback (most recent call last):
  File "latest_code_Windows_1/axinstall_new.py", line 14, in <module>
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "latest_code_Windows_1/main.py", line 7, in <module>
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "latest_code_Windows_1/searchsort.py", line 8, in <module>
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "latest_code_Windows_1/checkCompatibility.py", line 5, in <module>
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "latest_code_Windows_1/RequestInfo.py", line 10, in <module>
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 157, in load_module
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "urllib3/exceptions.py", line 2, in <module>
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 157, in load_module
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "urllib3/packages/__init__.py", line 3, in <module>
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 157, in load_module
  File "/tmp/pip-unpacked-wheel-tAZjpV/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
  File "urllib3/packages/ssl_match_hostname/__init__.py", line 1, in <module>
  File "requests/packages/__init__.py", line 95, in load_module
ImportError: No module named 'requests.packages.urllib3.packages.ssl_match_hostname.sys'
[5643] Failed to execute script axinstall_new

```

**Comment by Legorooj** [comment]
Can you run the PyInstaller command with the `--clean` option? What's the output after that?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
