### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.compiler.tf2tensorrt'

### ISSUE THREAD

**Issue by LumaRay** [pyinstaller/pyinstaller#4962]
Hello.

I have created a small python application using tensorflow 2.2.0 and can run it with no problem using python 3.7.4
Then I use pyinstaller to make a package of my project.
But when I try to run pyinstaller compiled version, I get this error (line 14 is "import tensorflow as tf").

```
Traceback (most recent call last):
  File "test_wx1.py", line 14, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/__init__.py", line 41, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/__init__.py", line 74, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/ops/standard_ops.py", line 117, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/compiler/tensorrt/__init__.py", line 22, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/compiler/tensorrt/trt_convert.py", line 79, in <module>
  File "tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
  File "tensorflow/python/util/lazy_loader.py", line 45, in _load
  File "importlib/__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'tensorflow.compiler.tf2tensorrt'
```

I cannot find any information Googling, so maybe you could help?

**Comment by Legorooj** [comment]
Please either use the development version or wait a few weeks for the next  release, which includes tensorflow support.
