### ISSUE TITLE
Raise AtributeError - using PySide2 on windows 64

### ISSUE THREAD

**Issue by Nurul-GC** [pyinstaller/pyinstaller#4963]
Hii.. Nurul GC
i am trying to use pyinstaller with pyside2 and my script raise AtributeError please somebody could help me fix this bug..

156 INFO: PyInstaller: 3.6
156 INFO: Python: 3.8.3
157 INFO: Platform: Windows-10-10.0.14393-SP0
169 INFO: UPX is not available.
211 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Nurul GC\\scriptPython\\GC-importPyQt',
 'C:\\Users\\Nurul GC\\scriptPython\\GC-importPyQt']
212 INFO: checking Analysis
212 INFO: Building Analysis because Analysis-00.toc is non existent
213 INFO: Initializing module dependency graph...
227 INFO: Caching module graph hooks...
246 INFO: Analyzing base_library.zip ...
7679 INFO: Processing pre-find module path hook   distutils
7681 INFO: distutils: retargeting to non-venv dir 'c:\\users\\nurul gc\\appdata\\local\\programs\\python\\python38\\lib'
18693 INFO: Caching module dependency graph...
19096 INFO: running Analysis Analysis-00.toc
19175 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\nurul gc\appdata\local\programs\python\python38\python.exe
19539 INFO: Analyzing Ex01(rotulo_demo).py
19818 INFO: Analyzing hidden import 'PySide2'
20291 INFO: Processing module hooks...
20292 INFO: Loading module hook "hook-distutils.py"...
20295 INFO: Loading module hook "hook-encodings.py"...
20632 INFO: Loading module hook "hook-lib2to3.py"...
20666 INFO: Loading module hook "hook-pydoc.py"...
20668 INFO: Loading module hook "hook-PyQt5.py"...
20980 WARNING: Cannot read QLibraryInfo output: raised Expecting value: line 1 column 1 (char 0) when decoding:
False
20980 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
20982 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
20983 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
20984 INFO: Loading module hook "hook-PySide2.py"...
21376 WARNING: Cannot read QLibraryInfo output: raised Expecting value: line 1 column 1 (char 0) when decoding:
PySide2/__init__.py: Unable to import shiboken2 from , C:\Users\Nurul GC\scriptPython\GC-importPyQt, c:\users\nurul gc\appdata\local\programs\python\python38\lib\sit
e-packages, c:\users\nurul gc\appdata\local\programs\python\python38\python38.zip, c:\users\nurul gc\appdata\local\programs\python\python38\DLLs, c:\users\nurul gc\a
ppdata\local\programs\python\python38\lib, c:\users\nurul gc\appdata\local\programs\python\python38, C:\Users\Nurul GC\AppData\Roaming\Python\Python38\site-packages,
 c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\win32, c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\win32\l
ib, c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\Pythonwin
False
Traceback (most recent call last):
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nurul GC\AppData\Local\Programs\Python\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
    #
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "Ex01(rotulo_demo).spec", line 6, in <module>
    a = Analysis(['Ex01(rotulo_demo).py'],
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
    self.__postinit__()
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 422, in assemble
    self.graph.process_post_graph_hooks()
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 311, in process_post_graph_hooks
    module_hook.post_graph()
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 417, in post_graph
    self._load_hook_module()
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 383, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\compat.py", line 797, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\hooks\hook-PySide2.py", line 26, in <module>
    collect_system_data_files(pyside2_library_info.location['PrefixPath'],
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 89, in __getattr__
    return getattr(self, name)
  File "c:\users\nurul gc\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 91, in __getattr__
    raise AttributeError

Please use the mailing list see <http://www.pyinstaller.org/support.html#mailing-list> for details.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker, but closed.

**Comment by bjones1** [comment]
Sorry, I don't support PySide2.

**Comment by unknown989** [comment]
hey there, pyinstaller only supports pyside 1 not 2

**Comment by Legorooj** [comment]
@unknown989 not true; we support PySide2 and PyQt5 only - no other python Qt variants are supported.
