### ISSUE TITLE
Cannot install development version

### ISSUE THREAD

**Issue by LumaRay** [pyinstaller/pyinstaller#4966]
Hello.

In this issue you suggested that I install dev version: https://github.com/pyinstaller/pyinstaller/issues/4962

I use Debian 10.4, python 3.7.4

I run:

`sudo pip3 install https://github.com/pyinstaller/pyinstaller/tarball/develop`

And get this error:

```
Collecting https://github.com/pyinstaller/pyinstaller/tarball/develop
  Using cached https://github.com/pyinstaller/pyinstaller/tarball/develop
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-913xfpak/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/usr/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1356, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1004, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-913xfpak/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by Legorooj** [comment]
Can you try `sudo pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`? Does that work?

**Comment by LumaRay** [comment]
```
$ sudo pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Using cached https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-4vqvoai0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/usr/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1356, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1004, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-4vqvoai0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by Legorooj** [comment]
Please update `pip` and your computer - `sudo apt update && sudo apt upgrade`.

**Comment by LumaRay** [comment]
Done. The result is the same:

```
jure@debian:~$ sudo apt update
Сущ:1 http://security.debian.org/debian-security buster/updates InRelease
Сущ:2 http://deb.debian.org/debian buster InRelease                                                          
Сущ:3 http://deb.debian.org/debian buster-updates InRelease                                                  
Сущ:4 https://packages.microsoft.com/repos/vscode stable InRelease                                           
Чтение списков пакетов… Готово                                     
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Все пакеты имеют последние версии.
W: Цель Packages (main/binary-amd64/Packages) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Packages (main/binary-all/Packages) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Translations (main/i18n/Translation-ru_RU) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Translations (main/i18n/Translation-ru) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Translations (main/i18n/Translation-en) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Packages (main/binary-amd64/Packages) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Packages (main/binary-all/Packages) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Translations (main/i18n/Translation-ru_RU) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Translations (main/i18n/Translation-ru) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
W: Цель Translations (main/i18n/Translation-en) настроена несколько раз: в /etc/apt/sources.list:21 и в /etc/apt/sources.list.d/vscode.list:3
jure@debian:~$ sudo apt upgrade
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Расчёт обновлений… Готово
Следующие пакеты устанавливались автоматически и больше не требуются:
  meteo-qt-l10n python3-bs4 python3-html5lib python3-lxml python3-soupsieve python3-webencodings
Для их удаления используйте «sudo apt autoremove».
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
jure@debian:~$ sudo pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Using cached https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp /pip-build-env-y6d0abuv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simp le -- 'setuptools>=40.8.0' wheel                                                                                           
       cwd: None                                                                                                           
  Complete output (44 lines):                                                                                              
  Traceback (most recent call last):                                                                                       
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main                                                   
      "__main__", mod_spec)                                                                                                
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code                                                              
      exec(code, run_globals)                                                                                              
    File "/usr/local/lib/python3.7/dist-packages/pip/__main__.py", line 26, in <module>                                    
      sys.exit(_main())                                                                                                    
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main.py", line 73, in main                              
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))                                              
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/__init__.py", line 104, in create_command          
      module = importlib.import_module(module_path)                                                                        
    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module                                            
      return _bootstrap._gcd_import(name[level:], package, level)                                                          
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                       
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                     
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                            
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                     
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                               
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                          
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 24, in <module>                 
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup                                          
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 16, in <module>                  
      from pip._internal.index.package_finder import PackageFinder                                                        
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>             
      from pip._internal.index.collector import parse_links                                                               
    File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/collector.py", line 14, in <module>                  
      from pip._vendor import html5lib, requests                                                                          
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/__init__.py", line 114, in <module>                 
      from . import utils                                                                                                 
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/utils.py", line 25, in <module>                     
      from . import certs                                                                                                 
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/requests/certs.py", line 15, in <module>                     
      from pip._vendor.certifi import where                                                                               
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>                    
      from .core import contents, where                                                                                   
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/certifi/core.py", line 12, in <module>                       
      from importlib.resources import read_text                                                                           
    File "/usr/lib/python3.7/importlib/resources.py", line 11, in <module>                                                
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401                                          
    File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1356, in <module>                                       
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):                                             
    File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1004, in __new__                                        
      self._abc_registry = extra._abc_registry                                                                            
  AttributeError: type object 'Callable' has no attribute '_abc_registry'                                                 
  ----------------------------------------                                                                                
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-y6d0abuv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output. 
```

**Comment by Legorooj** [comment]
`sudo pip3 --version`?

**Comment by LumaRay** [comment]
`pip 20.1.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)`

**Comment by Legorooj** [comment]
@LumaRay please open an issue in pypa/pip. Tag me and reference this issue in it.

**Comment by LumaRay** [comment]
Just opened the issue: https://github.com/pypa/pip/issues/8563

**Comment by Legorooj** [comment]
See pypa/pip#8563.
