### ISSUE TITLE
Unable to build executable using embedded zip Python

### ISSUE THREAD

**Issue by ruudkassing** [pyinstaller/pyinstaller#4989]
## Description of the issue
The official Python embeddable zip file distributions for Windows from Python.org contain a zip file (pythonXX.zip) that contains the pre-compiled and optimized .pyc files to run Python isolated on a machine. I've installed the embedded Python on a local agent that we use in our azure devops pipeline, following the [Microsoft docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#how-can-i-configure-a-self-hosted-agent-to-use-this-task).

However, building on this agent using PyInstaller fails, see Stacktrace below. This failure occurs because the requirements for `base_library.zip` are located inside a zip. Thus, PyInstaller tries to do an `os.stat()` on a path inside a zip folder, which fails.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.7
* Platform: Windows 10
* Same failure occurs on newest development version of PyInstaller
* Followed all the instructions in the "If Things Go Wrong" Guide and checked that everything is packaged correctly. The error occurs regardless of PyInstaller settings or spec file content.

### A minimal example program which shows the error
- Download embedded Python from [Python.org](https://www.python.org/downloads/)
- Add pip using [get-pip](https://michlstechblog.info/blog/python-install-python-with-pip-on-windows-by-the-embeddable-zip-file/)
- Install PyInstaller
- Create `helloworld.py`
   ```
   print("Hello World!")
   ```
- Try to run PyInstaller on `helloworld.py` using any settings.

### Stacktrace / full error message
```
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
python -m PyInstaller --distpath "%cd%\exe" SPECFILENAME.spec
========================== Starting Command Output ===========================
"C:\WINDOWS\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "agent2\_work\_temp\44e0b0b7-f2f9-4990-a3ee-31bbec9a0c70.cmd""
285 INFO: PyInstaller: 3.6
285 INFO: Python: 3.7.7
285 INFO: Platform: Windows-10-10.0.18362-SP0
291 INFO: UPX is not available.
303 INFO: checking Analysis
307 INFO: Building Analysis because Analysis-00.toc is non existent
307 INFO: Initializing module dependency graph...
313 INFO: Caching module graph hooks...
326 INFO: Analyzing base_library.zip ...
1791 INFO: Processing pre-find module path hook   distutils
1804 INFO: distutils: retargeting to non-venv dir 'agent2\\_work\\_tool\\Python\\3.7.7\\x64\\python37.zip'
2579 INFO: Caching module dependency graph...
2629 ERROR: base_library.zip could not be created!
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\__main__.py", line 121, in <module>
    run()
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "SPECFILENAME.spec", line 24, in <module>
    noarchive=False)
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
    self.__postinit__()
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\building\build_main.py", line 352, in assemble
    create_py3_base_library(libzip_filename, graph=self.graph)
  File "agent2\_work\_tool\Python\3.7.7\x64\lib\site-packages\PyInstaller\depend\utils.py", line 74, in create_py3_base_library
    st = os.stat(mod.filename)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'agent2\\_work\\_tool\\Python\\3.7.7\\x64\\python37.zip\\encodings\\__init__.pyc'
##[error]Cmd.exe exited with code '1'.
```

**Comment by Ruud-K** [comment]
I manually adjusted `depends\utils.py` in the PyInstaller package to handle files inside a zip folder. However, this did not solve the issue as PyInstaller would then continue to load the `hook-distutils.py` and attempt to get `Include\pyconfig.h` which does not exist for embedded zip Python:

```
169 INFO: PyInstaller: 3.6
169 INFO: Python: 3.7.7
169 INFO: Platform: Windows-10-10.0.18362-SP0
184 INFO: UPX is not available.
184 INFO: checking Analysis
200 INFO: Building Analysis because Analysis-00.toc is non existent
200 INFO: Initializing module dependency graph...
200 INFO: Caching module graph hooks...
222 INFO: Analyzing base_library.zip ...
1140 INFO: Processing pre-find module path hook   distutils
1156 INFO: distutils: retargeting to non-venv dir 'Python\\3.7.7\\x64\\python37.zip'
1689 INFO: Caching module dependency graph...
1742 INFO: running Analysis Analysis-00.toc
1742 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by Python\3.7.7\x64\python.exe
1990 INFO: Analyzing FILE_TO_BUILD_TO_EXECUTABLE.py
3078 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
3627 INFO: Processing pre-find module path hook   site
3633 INFO: site: retargeting to fake-dir 'Python\\3.7.7\\x64\\lib\\site-packages\\PyInstaller\\fake-modules'
7645 INFO: Processing module hooks...
7645 INFO: Loading module hook "hook-distutils.py"...
Unable to find "Python\3.7.7\x64\Include\pyconfig.h" when adding binary and data files.This would mean your Python installation doesn't come with proper library files. This usually happens by missing development package, or unsuitable build parameters of Python installation.
* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with
`--enable-shared` (or, `--enable-framework` on Darwin)
```

**Comment by Legorooj** [comment]
@Ruud-K this is indeed a bug. I shall fix this in the next few days before the next release.

**Comment by menteora** [comment]
Hi, is there temporary o manual workaround to bypass error using embedded python?

**Comment by Legorooj** [comment]
@menteora nope - sorry this got buried. I'll do this next - it's now top of my to-do list.

**Comment by bwoodsend** [comment]
@Ruud-K Do you still have the changes you made to get PyInstaller to handle the zipped libs? The `pyconfig.h` issue should be fixed by #5218 once it goes through. So if we apply your changes afterwards, this issue will hopefully be fixed.

**Comment by shouldsee** [comment]
I ran into similar issues when using pyinstaller with embedded python3.7.9. The solution was to use the `--onedir` option and then copy `python37.zip` into `dist\{appname}\base_library.zip`

**Comment by ivysrono** [comment]
I can't install pyinstaller with embedded python3.9.2
Same issue: https://github.com/pyinstaller/pyinstaller/issues/4513

```
PS .\python-3.9.2-embed-win32\Scripts> .\pip.exe install PyInstaller
Collecting PyInstaller
  Using cached pyinstaller-4.2.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pefile>=2017.8.1
  Using cached pefile-2019.4.18.tar.gz (62 kB)
Requirement already satisfied: setuptools in .\python-3.9.2-embed-win32\lib\site-packages (from PyInstaller) (54.0.0)
Collecting altgraph
  Using cached altgraph-0.17-py2.py3-none-any.whl (21 kB)
Collecting pywin32-ctypes>=0.2.0
  Using cached pywin32_ctypes-0.2.0-py2.py3-none-any.whl (28 kB)
Collecting pyinstaller-hooks-contrib>=2020.6
  Using cached pyinstaller_hooks_contrib-2020.11-py2.py3-none-any.whl (172 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 9.3 kB/s
    ERROR: Command errored out with exit status 1:
     command: '.\python-3.9.2-embed-win32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-9vawqxb2\\future_9b8fa746c9154bcfaeefa5052459ef26\\setup.py'"'"'; __file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-9vawqxb2\\future_9b8fa746c9154bcfaeefa5052459ef26\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Pp\AppData\Local\Temp\pip-pip-egg-info-ii740vam'
         cwd: C:\Users\Pp\AppData\Local\Temp\pip-install-9vawqxb2\future_9b8fa746c9154bcfaeefa5052459ef26\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Pp\AppData\Local\Temp\pip-install-9vawqxb2\future_9b8fa746c9154bcfaeefa5052459ef26\setup.py", line 86, in <module>
        import src.future
    ModuleNotFoundError: No module named 'src'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz#sha256=b1bead90b70cf6ec3f0710ae53a525360fa360d306a86583adc6bf83a4db537d (from https://pypi.org/simple/future/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading future-0.18.1.tar.gz (828 kB)
     |████████████████████████████████| 828 kB 12 kB/s
    ERROR: Command errored out with exit status 1:
     command: '.\python-3.9.2-embed-win32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-9vawqxb2\\future_4dcf1af6e72e4c628c9ec644891b1b62\\setup.py'"'"'; __file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-9vawqxb2\\future_4dcf1af6e72e4c628c9ec644891b1b62\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Pp\AppData\Local\Temp\pip-pip-egg-info-e7joukw2'
         cwd: C:\Users\Pp\AppData\Local\Temp\pip-install-9vawqxb2\future_4dcf1af6e72e4c628c9ec644891b1b62\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Pp\AppData\Local\Temp\pip-install-9vawqxb2\future_4dcf1af6e72e4c628c9ec644891b1b62\setup.py", line 86, in <module>
        import src.future
    ModuleNotFoundError: No module named 'src'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3f/bf/57733d44afd0cf67580658507bd11d3ec629612d5e0e432beb4b8f6fbb04/future-0.18.1.tar.gz#sha256=858e38522e8fd0d3ce8f0c1feaf0603358e366d5403209674c7b617fa0c24093 (from https://pypi.org/simple/future/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading future-0.18.0.tar.gz (830 kB)
     |████████████████████████████████| 830 kB 8.7 kB/s
    ERROR: Command errored out with exit status 1:
     command: '.\python-3.9.2-embed-win32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-9vawqxb2\\future_76c985a6ad4845e2a7f677a3105b95bc\\setup.py'"'"'; __file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-9vawqxb2\\future_76c985a6ad4845e2a7f677a3105b95bc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Pp\AppData\Local\Temp\pip-pip-egg-info-lhi96ezz'
         cwd: C:\Users\Pp\AppData\Local\Temp\pip-install-9vawqxb2\future_76c985a6ad4845e2a7f677a3105b95bc\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Pp\AppData\Local\Temp\pip-install-9vawqxb2\future_76c985a6ad4845e2a7f677a3105b95bc\setup.py", line 86, in <module>
        import src.future
    ModuleNotFoundError: No module named 'src'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f6/85/c273089eb6efa5644c0a1382ea553554bc0d40e00a46d989ec67f123f8b5/future-0.18.0.tar.gz#sha256=6142ef79e2416e432931d527452a1cab3aa4a754a0a53d25b2589f79e1106f34 (from https://pypi.org/simple/future/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading future-0.17.1.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 10 kB/s
    ERROR: Command errored out with exit status 1:
     command: '.\python-3.9.2-embed-win32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-9vawqxb2\\future_3276ab4dfd654d748f287ae4c5a8b856\\setup.py'"'"'; __file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-9vawqxb2\\future_3276ab4dfd654d748f287ae4c5a8b856\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Pp\AppData\Local\Temp\pip-pip-egg-info-x2hi6_ig'
         cwd: C:\Users\Pp\AppData\Local\Temp\pip-install-9vawqxb2\future_3276ab4dfd654d748f287ae4c5a8b856\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Pp\AppData\Local\Temp\pip-install-9vawqxb2\future_3276ab4dfd654d748f287ae4c5a8b856\setup.py", line 87, in <module>
        import src.future
    ModuleNotFoundError: No module named 'src'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz#sha256=67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8 (from https://pypi.org/simple/future/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading future-0.17.0.tar.gz (827 kB)
     |███████████████████████▌        | 604 kB 14 kB/s eta 0:00:16ERROR: Exception:
Traceback (most recent call last):
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'future'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "http\client.py", line 458, in read
  File "http\client.py", line 502, in readinto
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\commands\install.py", line 316, in run
    requirement_set = resolver.resolve(
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 199, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 82, in from_requirement
    if not cands:
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 124, in __bool__
    return bool(self._sequence)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 38, in _iter_built
    candidate = func()
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 300, in __init__
    super().__init__(
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 311, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\operations\prepare.py", line 457, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\operations\prepare.py", line 480, in _prepare_linked_requirement
    local_file = unpack_url(
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\operations\prepare.py", line 230, in unpack_url
    file = get_http_url(
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\operations\prepare.py", line 108, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\network\download.py", line 163, in __call__
    for chunk in chunks:
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\cli\progress_bars.py", line 159, in iter
    for x in it:
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_internal\network\utils.py", line 64, in response_chunks
    for chunk in response.raw.stream(
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "contextlib.py", line 135, in __exit__
  File ".\python-3.9.2-embed-win32\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Comment by shouldsee** [comment]
This seems to be a long-running issue and the content of `base_library.zip` has been updated several times

- #3397, f101f6f, March 2018, added warnings module 
- #1705, e7fc427, Dec 2015, added functools and a bunch, and holds an informative discussion

I have a naive suggestion here: maybe we can consider using embeddable python.zip directly as base_library.zip? Otherwise we might ends up updating `PY3_BASE_MODULES` once anyone runs into a missing module problem. And because `--onefile` mode exe erase its temporary directory, it's even harder for the user to find out the actual reason of a `Cannot import ... Errorr` .

Also configuring embeddable python alone is already a demanding task and I need to thank the creator of this post https://dev.to/fpim/setting-up-python-s-windows-embeddable-distribution-properly-1081

**Comment by parinavputhran** [comment]
I'll work on this to fix the bug right away

**Comment by wsc0615** [comment]
I  successfully generated the exe file through an ad hoc solution like this: in the embeddable python, there is a pythonxx .zip of the package, extract the package and rename it to the pyhonxx.zip folder, and run the pyinstaller again. Witness the miracle. 
Of course, I still hope to completely solve this bug and facilitate the use of embeddable Python.

**Comment by listenerri** [comment]
still

**Comment by SimoLRepo** [comment]
No definitive solution?

In my case it appears:
FileNotFoundError: [Errno 2] No such file or directory: 'Python_amd64\\python311.zip\\struct.pyc'
