### ISSUE TITLE
Matplotlib - NameError: name 'defaultParams' is not defined

### ISSUE THREAD

**Issue by 8bit-Dude** [pyinstaller/pyinstaller#5012]
## Description of the issue
pyInstaller succesfully compiles the simple Matplotlib 2D graph example, and even copies over the "mpl-data" folder.
However, the exe fails to run. It complains about the defaultParams list, which is use by __init__.py of Matplotlib.
Note: Strangely the application tries to invoke files located in my miniconda3 installation folder...?

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.6 (Miniconda3 4.8.3) (Matplotlib 3.3.0)
* Platform: e.g Windows (english)
* Did you also try this on another platform? NO

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
plt.show()

### Stacktrace / full error message
C:\Miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:623: MatplotlibDeprecationWarning: Matplotlib installs where the data is not in the mpl-data subdirectory of the package are deprecated since 3.2 and support for them will be removed two minor releases later.
  exec(bytecode, module.__dict__)
Traceback (most recent call last):
  File "plot.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\matplotlib\__init__.py", line 898, in <module>
  File "site-packages\matplotlib\cbook\__init__.py", line 480, in _get_data_path
  File "site-packages\matplotlib\__init__.py", line 239, in wrapper
  File "site-packages\matplotlib\__init__.py", line 534, in get_data_path
  File "site-packages\matplotlib\__init__.py", line 239, in wrapper
  File "site-packages\matplotlib\__init__.py", line 563, in _get_data_path
NameError: name 'defaultParams' is not defined
[5576] Failed to execute script plot

**Comment by bwoodsend** [comment]
This is the same issue as #5004. We're midway through fixing it. For now just `pip install matplotlib==3.2.2`.

**Comment by 8bit-Dude** [comment]
Thanks for the heads up!
