### ISSUE TITLE
python2.7 pyinstaller build wx.lib.pubsub cannot work

### ISSUE THREAD

**Issue by Jamesoli-ch** [pyinstaller/pyinstaller#5015]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```(PS C:\Project\Light\scripts> pyinstaller --version
3.6
PS C:\Project\Light\scripts>```
* Version of Python: e.g. 3.7
* Platform: Windows 10
* Did you also try this on another platform? Does it work there?
No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [v] start with clean installation
  * [v] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
class LightAPP(wx.Frame):
    global uut
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, id=wx.ID_ANY, title=u"TPCBA Testing", pos=wx.DefaultPosition,
                          size=wx.Size(1340, 888), style=wx.DEFAULT_FRAME_STYLE | wx.TAB_TRAVERSAL)
        self.SetSizeHints(wx.DefaultSize, wx.DefaultSize)
        fgSizer2 = wx.FlexGridSizer(0, 2, 0, 0)
        fgSizer2.SetFlexibleDirection(wx.BOTH)
        fgSizer2.SetNonFlexibleGrowMode(wx.FLEX_GROWMODE_SPECIFIED)

        bSizer4 = wx.BoxSizer(wx.VERTICAL)

        self.Start = wx.Button(self, wx.ID_ANY, u"Start", wx.Point(-1, -1), wx.DefaultSize, 0)
        bSizer4.Add(self.Start, 0, wx.ALL, 5)
        self.Bind(wx.EVT_BUTTON, self.start_test, self.Start)

        self.Stop = wx.Button(self, wx.ID_ANY, u"Stop", wx.DefaultPosition, wx.DefaultSize, 0)
        bSizer4.Add(self.Stop, 0, wx.ALL, 5)
        self.Bind(wx.EVT_BUTTON, self.stop_test, self.Stop)

        gSizer5 = wx.GridSizer(0, 2, 0, 0)

        bSizer5 = wx.BoxSizer(wx.VERTICAL)

        self.label_user = wx.StaticText(self, wx.ID_ANY, u"用户", wx.DefaultPosition, wx.DefaultSize, 0)
        self.label_user.Wrap(-1)
        bSizer5.Add(self.label_user, 0, wx.ALL, 5)

        self.user = wx.TextCtrl(self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.Size(125, 25), 0)
        bSizer5.Add(self.user, 0, wx.ALL, 5)

        self.label_order = wx.StaticText(self, wx.ID_ANY, u"工单:", wx.DefaultPosition, wx.DefaultSize, 0)
        self.label_order.Wrap(-1)
        bSizer5.Add(self.label_order, 0, wx.ALL, 5)

        self.order = wx.TextCtrl(self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.Size(125, 25), 0)
        bSizer5.Add(self.order, 0, wx.ALL, 5)

        self.label_type = wx.StaticText(self, wx.ID_ANY, u"型号:", wx.DefaultPosition, wx.DefaultSize, 0)
        self.label_type.Wrap(-1)
        bSizer5.Add(self.label_type, 0, wx.ALL, 5)

        self.uut_type = wx.TextCtrl(self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.Size(125, 25), 0)
        bSizer5.Add(self.uut_type, 0, wx.ALL, 5)

        self.label_sn = wx.StaticText(self, wx.ID_ANY, u"产品SN:", wx.DefaultPosition, wx.DefaultSize, 0)
        self.label_sn.Wrap(-1)
        bSizer5.Add(self.label_sn, 0, wx.ALL, 5)

        self.serial_number = wx.TextCtrl(self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.Size(125, 25), 0)
        bSizer5.Add(self.serial_number, 0, wx.ALL, 5)

        self.label_mac = wx.StaticText(self, wx.ID_ANY, u"产品MAC:", wx.DefaultPosition, wx.DefaultSize, 0)
        self.label_mac.Wrap(-1)
        bSizer5.Add(self.label_mac, 0, wx.ALL, 5)

        self.mac = wx.TextCtrl(self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.Size(125, 25), 0)
        bSizer5.Add(self.mac, 0, wx.ALL, 5)

        self.label_status = wx.StaticText(self, wx.ID_ANY, u"测试状态:", wx.DefaultPosition, wx.DefaultSize, 0)
        self.label_sn.Wrap(-1)
        bSizer5.Add(self.label_status, 0, wx.ALL, 5)

        self.status_button = wx.ToggleButton(self, wx.ID_ANY, u"Status", wx.Point(-1, 500), wx.DefaultSize, 0)
        bSizer5.Add(self.status_button, 0, wx.ALL, 5)

        gSizer5.Add(bSizer5, 1, wx.EXPAND, 5)

        bSizer4.Add(gSizer5, 1, wx.EXPAND, 5)

        self.Test_log = wx.TextCtrl(self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.Size(200, 100), 0)
        bSizer4.Add(self.Test_log, 0, wx.ALL, 5)

        self.m_gauge1 = wx.Gauge(self, wx.ID_ANY, 100, wx.DefaultPosition, wx.DefaultSize, wx.GA_HORIZONTAL)
        # self.m_gauge1.SetValue(90)
        bSizer4.Add(self.m_gauge1, 0, wx.ALL, 5)

        fgSizer2.Add(bSizer4, 1, wx.EXPAND, 5)

        self.Test_sequence = wx.grid.Grid(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, 0)

        # Grid
        self.Test_sequence.CreateGrid(50, 5)
        #self.Test_sequence.SetRowSize(4, 70)
        self.Test_sequence.EnableEditing(True)
        self.Test_sequence.EnableGridLines(True)
        self.Test_sequence.EnableDragGridSize(True)
        self.Test_sequence.SetMargins(0, 0)

        # Columns
        self.Test_sequence.SetColSize(0, 200)
        self.Test_sequence.SetColSize(1, 80)
        self.Test_sequence.SetColSize(2, 300)
        self.Test_sequence.SetColSize(3, 280)
        self.Test_sequence.SetColSize(4, 80)
        self.Test_sequence.EnableDragColMove(True)
        self.Test_sequence.EnableDragColSize(True)
        self.Test_sequence.SetColLabelSize(50)
        self.Test_sequence.SetColLabelValue(0, u"Test Steps")
        self.Test_sequence.SetColLabelValue(1, u"Test satus")
        self.Test_sequence.SetColLabelValue(2, u"Test value")
        self.Test_sequence.SetColLabelValue(3, u"Test Limit")
        self.Test_sequence.SetColLabelValue(4, u"Test Time")
        self.Test_sequence.SetColLabelAlignment(wx.ALIGN_CENTRE, wx.ALIGN_CENTRE)

        # Rows
        self.Test_sequence.EnableDragRowSize(True)
        self.Test_sequence.SetRowLabelSize(100)
        self.Test_sequence.SetRowLabelAlignment(wx.ALIGN_CENTRE, wx.ALIGN_CENTRE)

        # Label Appearance

        # Cell Defaults
        self.Test_sequence.SetDefaultCellAlignment(wx.ALIGN_LEFT, wx.ALIGN_TOP)
        fgSizer2.Add(self.Test_sequence, 0, wx.ALL, 5)

        self.SetSizer(fgSizer2)
        self.Layout()
        self.m_statusBar1 = self.CreateStatusBar(1, wx.STB_SIZEGRIP, wx.ID_ANY)
        self.TestRun = wx.Timer()
        self.TestRun.SetOwner(self, wx.ID_ANY)
        self.TestRun.Start(1000)
        self.Centre(wx.BOTH)
        pub.subscribe(self.update_test_status, "test_finish")

class TestThread(Thread):
    def __init__(self):
        Thread.__init__(self)
        Thread.daemon = True
        self.start()

    def run(self):
        self.loop_test()

    def loop_test(self):
        if all(steps_result):
            uut['test_status'] = 'PASS'
            self.client.stop()
            self.client.power_off()
            self.record.update_record('outcome', 'PASS')
            self.record.save_log(area=test_station)
            wx.CallAfter(pub.sendMessage, "test_finish", msg=uut['test_status'])
        else:
            uut['test_status'] = 'FAIL'
            self.client.stop()
            self.client.power_off()
            self.record.update_record('outcome', 'FAIL')
            self.record.save_log(area=test_station)
            wx.CallAfter(pub.sendMessage, "test_finish", msg=uut['test_status'])
```

### Stacktrace / full error message

```
87980 INFO: checking Tree
88000 INFO: Loading module hook "hook-pubsub.core.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "C:\Python27\lib\site-packages\pubsub\core\arg1\__init__.py", line 16, in <module>
    raise RuntimeError(msg)
RuntimeError: Should not import this directly, used by pubsub.core if applicable
88483 WARNING: Hidden import "pubsub.core.topicargspecimpl" not found!
88486 WARNING: Hidden import "pubsub.core.publishermixin" not found!
88487 WARNING: Hidden import "pubsub.core.listenerimpl" not found!
88654 WARNING: Hidden import "pubsub.core.topicmgrimpl" not found!
88658 WARNING: Hidden import "pubsub.core.datamsg" not found!
88661 WARNING: Hidden import "pubsub.core.publisher" not found!
88661 INFO: Loading module hook "hook-Crypto.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named Math
88910 INFO: Loading module hook "hook-wx.xrc.py"...
88914 INFO: Loading module hook "hook-wx.lib.pubsub.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "C:\Python27\lib\site-packages\wx\lib\pubsub\core\arg1\__init__.py", line 16, in <module>
    raise RuntimeError(msg)
RuntimeError: Should not import this directly, used by pubsub.core if applicable
90487 WARNING: Hidden import "wx.lib.pubsub.core.publisher" not found!
90492 WARNING: Hidden import "wx.lib.pubsub.core.listenerimpl" not found!
90493 WARNING: Hidden import "wx.lib.pubsub.core.publishermixin" not found!
90496 WARNING: Hidden import "wx.lib.pubsub.core.datamsg" not found!
90497 WARNING: Hidden import "wx.lib.pubsub.core.topicargspecimpl" not found!
90502 WARNING: Hidden import "wx.lib.pubsub.core.topicmgrimpl" not found!
90532 INFO: Looking for ctypes DLLs

and exe excute:
pip-install-zcjp2y\pyinstaller\PyInstaller\loader\pyimod03_importers.py' line 396, in load_module
File "site-jpackages\wx\lib\pubsub\core\__init.py" line 45, im <module>
importError: No module named publisher
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by Legorooj** [comment]
Which version of wxPython are you using?

**Comment by Jamesoli-ch** [comment]
I have tried latest 4.1 and old version 4.0.1. Current is 4.0.1

**Comment by Legorooj** [comment]
@Jamesoli-ch can you list all of the `import` statements you're using? I can't see them in the code you posted.

**Comment by Jamesoli-ch** [comment]
import wx
import wx.xrc
import wx.grid
# import numpy as np
import binascii
from datetime import datetime
import time
from threading import Thread
from wx.lib.pubsub import pub

This what I imported to code

**Comment by Legorooj** [comment]
Please read https://docs.wxpython.org/MigrationGuide.html#wx-lib-pubsub-is-deprecated, and use `pypubsub` instead.

**Comment by Jamesoli-ch** [comment]
Yes, I have tried it, It is the same.

**Comment by Jamesoli-ch** [comment]
PyPubSub                           3.3.0

**Comment by Jamesoli-ch** [comment]
19631 INFO: Loading module hook "hook-pubsub.core.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "C:\Python27\lib\site-packages\pubsub\core\arg1\__init__.py", line 16, in <module>
    raise RuntimeError(msg)
RuntimeError: Should not import this directly, used by pubsub.core if applicable
19963 WARNING: Hidden import "pubsub.core.topicargspecimpl" not found!
19964 WARNING: Hidden import "pubsub.core.publishermixin" not found!
19966 WARNING: Hidden import "pubsub.core.listenerimpl" not found!
20095 WARNING: Hidden import "pubsub.core.topicmgrimpl" not found!
20096 WARNING: Hidden import "pubsub.core.datamsg" not found!
20098 WARNING: Hidden import "pubsub.core.publisher" not found!
20098 INFO: Loading module hook "hook-Crypto.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named Math
20263 INFO: Loading module hook "hook-wx.xrc.py"...
20284 INFO: Looking for ctypes DLLs
20397 INFO: Analyzing run-time hooks ...
20401 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
20407 INFO: Including run-time hook 'pyi_rth__tkinter.py'
20415 INFO: Looking for dynamic libraries
21165 INFO: Looking for eggs

**Comment by Legorooj** [comment]
@Jamesoli-ch let me try and reproduce. I don't think I'll have much luck - I use Py3 - but we'll see.

**Comment by Legorooj** [comment]
Umm ok this is really weird. Modulegraph isn't seeing this import. At all. Let me do some more digging...

**Comment by Legorooj** [comment]
I managed to find the source of this issue. Give me a while to fix this - it should be working how it is, but for some reason our knife is failing to cut this Gordian Knot - which it was doing just fine a few versions of `pypubsub` back AFAIK.

**Comment by Jamesoli-ch** [comment]
Cool, Thanks @Legorooj
