### ISSUE TITLE
My .exe for Django project doesn't run the server.

### ISSUE THREAD

**Issue by felipefariasdasilva** [pyinstaller/pyinstaller#5022]
Hi guys!

I'm trying to generate a .exe for my Django Project. But after I execute the following command

```
pyinstaller --name=teste manage.py
``` 

and execute my runserver command using

```
dist/teste/teste.exe runserver
```

nothing happens, neither an error message.

This is the log builder:

```
125 INFO: PyInstaller: 3.6
125 INFO: Python: 3.8.3
125 INFO: Platform: Windows-10-10.0.16299-SP0
137 INFO: wrote C:\Users\felipe\Desktop\my-project\my-api-django\teste.spec
147 INFO: UPX is not available.
150 INFO: Extending PYTHONPATH with paths
['C:\\Users\\felipe\\Desktop\\my-project\\my-api-django',
 'C:\\Users\\felipe\\Desktop\\my-project\\my-api-django']
151 INFO: checking Analysis
151 INFO: Building Analysis because Analysis-00.toc is non existent
151 INFO: Initializing module dependency graph...
157 INFO: Caching module graph hooks...
166 INFO: Analyzing base_library.zip ...
4986 INFO: Processing pre-find module path hook   distutils
4991 INFO: distutils: retargeting to non-venv dir 'c:\\users\\felipe\\appdata\\local\\programs\\python\\python38-32\\lib'
10216 INFO: Caching module dependency graph...
10499 INFO: running Analysis Analysis-00.toc
10508 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\felipe\appdata\local\programs\python\python38-32\python.exe
10708 INFO: Analyzing C:\Users\felipe\Desktop\my-project\my-api-django\manage.py
12105 INFO: Processing pre-find module path hook   site
12110 INFO: site: retargeting to fake-dir 'c:\\users\\felipe\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\fake-modul
es'
17447 INFO: Processing module hooks...
17448 INFO: Loading module hook "hook-distutils.py"...
17453 INFO: Loading module hook "hook-django.core.cache.py"...
17827 INFO: Loading module hook "hook-django.core.mail.py"...
17956 INFO: Loading module hook "hook-django.core.management.py"...
18124 INFO: Excluding import 'tkinter'
18125 INFO: Import to be excluded not found: 'IPython'
18126 INFO: Import to be excluded not found: 'matplotlib'
18126 INFO: Loading module hook "hook-django.db.backends.py"...
19469 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
19469 INFO: Loading module hook "hook-django.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\contrib\gis\admin\__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\contrib\gis\admin\options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\contrib\gis\admin\widgets.py", line 3, in <module>
    from django.contrib.gis.gdal import GDALException
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\contrib\gis\gdal\__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\contrib\gis\gdal\datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\contrib\gis\gdal\driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\contrib\gis\gdal\prototypes\ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\contrib\gis\gdal\libgdal.py", line 39, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal204", "gdal203", "gdal202", "gdal201", "gdal20"). Is GDAL install
ed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
23773 INFO: Determining a mapping of distributions to packages...
32199 INFO: Packages required by django:
['pytz', 'sqlparse', 'asgiref']
32200 INFO: Django root directory C:\Users\felipe\Desktop\my-project\my-api-django\myApiProject
Traceback (most recent call last):
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\utils\hooks\subproc\django_import_finder.py", line 38, i
n <module>
    list(settings.TEMPLATE_CONTEXT_PROCESSORS) + \
  File "c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\django\conf\__init__.py", line 77, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'
34118 INFO: Collecting Django migration scripts.
41137 INFO: Loading module hook "hook-encodings.py"...
41433 INFO: Loading module hook "hook-jinja2.py"...
41475 INFO: Loading module hook "hook-lib2to3.py"...
41483 INFO: Loading module hook "hook-pkg_resources.py"...
42400 INFO: Processing pre-safe import module hook   win32com
42559 INFO: Excluding import '__main__'
42561 INFO:   Removing import of __main__ from module pkg_resources
42561 INFO: Loading module hook "hook-psycopg2.py"...
42566 WARNING: Hidden import "mx.DateTime" not found!
42567 INFO: Loading module hook "hook-pydoc.py"...
42571 INFO: Loading module hook "hook-pythoncom.py"...
43163 INFO: Loading module hook "hook-pytz.py"...
43291 INFO: Loading module hook "hook-pywintypes.py"...
43855 INFO: Loading module hook "hook-sqlite3.py"...
44144 INFO: Loading module hook "hook-sysconfig.py"...
44148 INFO: Loading module hook "hook-win32com.py"...
44716 INFO: Loading module hook "hook-xml.dom.domreg.py"...
44720 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
44724 INFO: Loading module hook "hook-xml.py"...
44728 INFO: Loading module hook "hook-_tkinter.py"...
45292 INFO: checking Tree
45294 INFO: Building Tree because Tree-00.toc is non existent
45294 INFO: Building Tree Tree-00.toc
45416 INFO: checking Tree
45417 INFO: Building Tree because Tree-01.toc is non existent
45417 INFO: Building Tree Tree-01.toc
45462 INFO: Loading module hook "hook-django.db.backends.mysql.base.py"...
45471 INFO: Loading module hook "hook-django.db.backends.oracle.base.py"...
45475 WARNING: Hidden import "django.db.backends.oracle.compiler" not found!
45598 INFO: Looking for ctypes DLLs
45759 INFO: Analyzing run-time hooks ...
45771 INFO: Including run-time hook 'pyi_rth__tkinter.py'
45777 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
45786 INFO: Including run-time hook 'pyi_rth_pkgres.py'
45791 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
45798 INFO: Including run-time hook 'pyi_rth_django.py'
45831 INFO: Looking for dynamic libraries
47057 INFO: Looking for eggs
47057 INFO: Using Python library c:\users\felipe\appdata\local\programs\python\python38-32\python38.dll
47057 INFO: Found binding redirects:
[]
47076 INFO: Warnings written to C:\Users\felipe\Desktop\my-project\my-api-django\build\teste\warn-teste.txt
47310 INFO: Graph cross-reference written to C:\Users\felipe\Desktop\my-project\my-api-django\build\teste\xref-teste.html
47733 INFO: checking PYZ
47733 INFO: Building PYZ because PYZ-00.toc is non existent
47734 INFO: Building PYZ (ZlibArchive) C:\Users\felipe\Desktop\my-project\my-api-django\build\teste\PYZ-00.pyz
49893 INFO: Building PYZ (ZlibArchive) C:\Users\felipe\Desktop\my-project\my-api-django\build\teste\PYZ-00.pyz completed successfully.
49957 INFO: checking PKG
49957 INFO: Building PKG because PKG-00.toc is non existent
49958 INFO: Building PKG (CArchive) PKG-00.pkg
50018 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
50025 INFO: Bootloader c:\users\felipe\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
50026 INFO: checking EXE
50026 INFO: Building EXE because EXE-00.toc is non existent
50026 INFO: Building EXE from EXE-00.toc
50027 INFO: Appending archive to EXE C:\Users\felipe\Desktop\my-project\my-api-django\build\teste\teste.exe
50099 INFO: Building EXE from EXE-00.toc completed successfully.
50124 INFO: checking COLLECT
50124 INFO: Building COLLECT because COLLECT-00.toc is non existent
50126 INFO: Building COLLECT COLLECT-00.toc
170716 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

And, this is the .spec that was automatically generated:

```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['manage.py'],
             pathex=['C:\\Users\\felipe\\Desktop\\my-project\\my-api-django'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='teste',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='teste')
```
Could anyone help me?

Thanks!!

**Comment by bwoodsend** [comment]
Can you please provide a minimal example Python script we can use to reproduce this issue? We can't do anything with just a build log. Also should warn you that PyInstaller doesn't support Python 3.8 yet.

**Comment by felipefariasdasilva** [comment]
It's a regular Django project. My entry point is by the manage.py file:

```
#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def main():
    os.environ["DJANGO_SETTINGS_MODULE"] = "myApiProject.settings"
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()

```

> Can you please provide a minimal example Python script we can use to reproduce this issue? We can't do anything with just a build log. Also should warn you that PyInstaller doesn't support Python 3.8 yet.

**Comment by bwoodsend** [comment]
I'm afraid I can't reproduce at all. It all works fine on my machine. I'm using the following on Windows 8, Python 3.8.3:

```shell
pip install django PyInstaller==3.6
django-admin.exe startproject myApiProject
cd myApiProject\
PyInstaller --name=teste manage.py
dist\teste\teste runserver
```
Which gives what it's supposed to give:
```
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

July 27, 2020 - 17:07:33
Django version 3.0.8, using settings 'myApiProject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
```
It complains a lot during the build but still works. @felipefariasdasilva Can you confirm this hello world example doesn't work for you?

**Comment by Legorooj** [comment]
Stale
