### ISSUE TITLE
pyinstaller with click leads to error ModuleNotFoundError

### ISSUE THREAD

**Issue by Alexander3XL** [pyinstaller/pyinstaller#5023]
Hello! 
I have ModuleNotFoundError: No module named 'packaging.version'.
That looks like regression https://github.com/pyinstaller/pyinstaller/issues/3584

Additional info:
* Linux 5.7.10-arch1-1
* Python 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0] on linux
* python-setuptools 1:49.2.0-1
* pyinstaller 3.6-6

Steps to reproduce:
```
$ echo -e 'import click\nprint("Test")'>f.py
$ pyinstaller f.py
$ ./dist/f/f
Traceback (most recent call last):
File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
File "/usr/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
exec(bytecode, module.__dict__)
File "site-packages/pkg_resources/__init__.py", line 81, in <module>
ModuleNotFoundError: No module named 'packaging.version'
[54156] Failed to execute script pyi_rth_pkgres
$ pacman -Qo /usr/lib/python3.8/site-packages/pkg_resources/__init__.py
/usr/lib/python3.8/site-packages/pkg_resources/__init__.py is owned by python-setuptools 1:49.2.0-1
```

_Originally posted by @Alexander3XL in https://github.com/pyinstaller/pyinstaller/issues/3584#issuecomment-663554804_

**Comment by bwoodsend** [comment]
Have you tried passing `--hidden-import=packaging.version`?

**Comment by Alexander3XL** [comment]
```
pyinstaller --hidden-import 'packaging.version' --hidden-import 'packaging.specifiers' --hidden-import 'packaging.requirements' --hidden-import 'pkg_resources.markers' f.py
```
It works!

**Comment by bwoodsend** [comment]
Thanks for that. I'll bung that into a hook now to hopefully fix it more permanently.

**Comment by bwoodsend** [comment]
@Alexander3XL Could you share your `xref` file with us as I'm unable to reproduce your issue? Find it under `build/f/xref-f.html`.
