### ISSUE TITLE
Pyinstaller with python 3.85 not works

### ISSUE THREAD

**Issue by isdito** [pyinstaller/pyinstaller#5033]
Hello,

The exe give me this error, I not find the solution. reggards

```
Python path configuration:
  PYTHONHOME = 'C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo'
  PYTHONPATH = (not set)
  program name = 'C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\interface.exe'
  isolated = 0
  environment = 0
  user site = 0
  import site = 0
  sys._base_executable = 'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo\\interface.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo\\interface.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo\\base_library.zip',
    'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000007e0 (most recent call first):
<no Python frame>

```

**Comment by bwoodsend** [comment]
Have you tried `--hidden-import=encodings`?

**Comment by isdito** [comment]
no I'm unpacking version 3.85 and going back to a 3.7

**Comment by isdito** [comment]
hello,

`pyinstaller interface.py --hidden-import=encodings`

not works. Any solution?

**Comment by bwoodsend** [comment]
Can you share your `xref` file with us. Find it in the `build` folder.

**Comment by isdito** [comment]
Hello.

[](https://www.video-boda.es/xref-interface.htmll)

Thank you

**Comment by bwoodsend** [comment]
OK, so contrary to what it says, `encodings` is being found and bundled fine but something else is upsetting it. Can we have the full output from running your exe?

**Comment by isdito** [comment]
hello.
it is posible send you private?
it is a work for a enterprise and it is not protected know

**Comment by bwoodsend** [comment]
@isdito Can we have the source `globales.py`  too?

**Comment by isdito** [comment]
Hello from Spain

https://we.tl/t-TV9UbymXqI

Give me error with a little example I put you

reggards

**Comment by bwoodsend** [comment]
I get no error when I build your example. Do you know your filesystem encoding? Use `sys.getfilesystemencoding()` if you don't.

Also you are aware that you can't just copy the `exe` file out from the rest of the app like you sent? Use `--onefile` to make a single file executable.

**Comment by isdito** [comment]
Hello,

The error it is not the file.py, see the video

https://youtu.be/UYeclCNJU6U

reggards

**Comment by bwoodsend** [comment]
Your using the executable  from the `build` folder. That's all just intermediate temporary files and build logs. You should be using the executable from the `dist` folder.

**Comment by isdito** [comment]
Hello say me the same

C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales2>pyinstaller globales2.exe --onefile
49 INFO: PyInstaller: 4.0.dev0
49 INFO: Python: 3.7.8
50 INFO: Platform: Windows-10-10.0.18362-SP0
51 INFO: wrote C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales2\globales2.spec
54 INFO: UPX is not available.
55 INFO: Extending PYTHONPATH with paths
['C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo\\build\\globales2',
 'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo\\build\\globales2']
62 INFO: checking Analysis
63 INFO: Building Analysis because Analysis-00.toc is non existent
63 INFO: Initializing module dependency graph...
65 INFO: Caching module graph hooks...
74 INFO: Analyzing base_library.zip ...
1476 INFO: Processing pre-find module path hook distutils from 'C:\\python37\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
1477 INFO: distutils: retargeting to non-venv dir 'C:\\Python37\\Lib'
2329 INFO: Caching module dependency graph...
2415 INFO: running Analysis Analysis-00.toc
2433 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python37\python.exe
2501 INFO: Analyzing C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales2\globales2.exe
Traceback (most recent call last):
  File "C:\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\python37\Lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\python37\Lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\python37\Lib\site-packages\PyInstaller\building\build_main.py", line 716, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\python37\Lib\site-packages\PyInstaller\building\build_main.py", line 663, in build
    exec(code, spec_namespace)
  File "C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales2\globales2.spec", line 17, in <module>
    noarchive=False)
  File "C:\python37\Lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "C:\python37\Lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\python37\Lib\site-packages\PyInstaller\building\build_main.py", line 412, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "C:\python37\Lib\site-packages\PyInstaller\depend\analysis.py", line 302, in run_script
    pathname)
  File "C:\python37\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1390, in run_script
    contents = fp.read() + '\n'
  File "C:\Python37\Lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

**Comment by isdito** [comment]
ufff I install python version 3.7 and Pyinstaller 3.6  but the error persists


C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales>pyinstaller globales.exe --onefile
56 INFO: PyInstaller: 3.6
56 INFO: Python: 3.7.8
58 INFO: Platform: Windows-10-10.0.18362-SP0
59 INFO: wrote C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales\globales.spec
60 INFO: UPX is not available.
62 INFO: Extending PYTHONPATH with paths
['C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo\\build\\globales',
 'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo\\build\\globales']
62 INFO: checking Analysis
63 INFO: Building Analysis because Analysis-00.toc is non existent
63 INFO: Initializing module dependency graph...
65 INFO: Caching module graph hooks...
71 INFO: Analyzing base_library.zip ...
1404 INFO: Processing pre-find module path hook   distutils
1405 INFO: distutils: retargeting to non-venv dir 'c:\\python37\\lib'
2243 INFO: Caching module dependency graph...
2328 INFO: running Analysis Analysis-00.toc
2347 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python37\python.exe
2416 INFO: Analyzing C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales\globales.exe
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales\globales.spec", line 17, in <module>
    noarchive=False)
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
    self.__postinit__()
  File "c:\python37\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 416, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "c:\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 249, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "c:\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1395, in run_script
    contents = fp.read() + '\n'
  File "c:\python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales>

**Comment by bwoodsend** [comment]
Now your trying to compile an `exe` from `globales.exe`. Should be `PyInstaller --onefile globales.py`.

**Comment by isdito** [comment]
hello, not give me exe.


```
C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo>PyInstaller --onefile globales.py
54 INFO: PyInstaller: 3.6
54 INFO: Python: 3.7.8
55 INFO: Platform: Windows-10-10.0.18362-SP0
56 INFO: wrote C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\globales.spec
58 INFO: UPX is not available.
59 INFO: Extending PYTHONPATH with paths
['C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo',
 'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo']
59 INFO: checking Analysis
163 INFO: checking PYZ
200 INFO: checking PKG
202 INFO: Building because toc changed
202 INFO: Building PKG (CArchive) PKG-00.pkg
7146 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
7172 INFO: Bootloader c:\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
7172 INFO: checking EXE
7174 INFO: Rebuilding EXE-00.toc because globales.exe missing
7174 INFO: Building EXE from EXE-00.toc
7175 INFO: Appending archive to EXE C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\dist\globales.exe
7207 INFO: Building EXE from EXE-00.toc completed successfully.
```

**Comment by bwoodsend** [comment]
`PyInstaller --onefile --hidden-import=pkg_resources.py2_warn globales.py`

**Comment by isdito** [comment]
```
C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo>PyInstaller --onefile --hidden-import=pkg_resources.py2_warn globales.py
63 INFO: PyInstaller: 3.6
64 INFO: Python: 3.7.8
65 INFO: Platform: Windows-10-10.0.18362-SP0
66 INFO: wrote C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\globales.spec
68 INFO: UPX is not available.
69 INFO: Extending PYTHONPATH with paths
['C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo',
 'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo']
69 INFO: checking Analysis
82 INFO: Building because hiddenimports changed
82 INFO: Initializing module dependency graph...
86 INFO: Caching module graph hooks...
92 INFO: Analyzing base_library.zip ...
1649 INFO: Processing pre-find module path hook   distutils
1650 INFO: distutils: retargeting to non-venv dir 'c:\\python37\\lib'
2492 INFO: Caching module dependency graph...
2595 INFO: running Analysis Analysis-00.toc
2611 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python37\python.exe
2685 INFO: Analyzing C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\globales.py
5213 INFO: Processing pre-find module path hook   site
5214 INFO: site: retargeting to fake-dir 'c:\\python37\\lib\\site-packages\\PyInstaller\\fake-modules'
6112 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
8970 INFO: Analyzing hidden import 'pkg_resources.py2_warn'
8971 INFO: Processing module hooks...
8971 INFO: Loading module hook "hook-distutils.py"...
8971 INFO: Loading module hook "hook-encodings.py"...
9042 INFO: Loading module hook "hook-lib2to3.py"...
9045 INFO: Loading module hook "hook-numpy.core.py"...
9130 INFO: Loading module hook "hook-numpy.py"...
9131 INFO: Loading module hook "hook-PIL.Image.py"...
9390 INFO: Loading module hook "hook-PIL.py"...
9391 INFO: Import to be excluded not found: 'FixTk'
9391 INFO: Excluding import 'PyQt5'
9393 INFO:   Removing import of PyQt5 from module PIL.ImageQt
9393 INFO: Excluding import 'tkinter'
9395 INFO:   Removing import of tkinter from module PIL.ImageTk
9395 INFO: Import to be excluded not found: 'PyQt4'
9395 INFO: Import to be excluded not found: 'PySide'
9396 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
9397 INFO: Excluding import 'tkinter'
9398 INFO: Import to be excluded not found: 'FixTk'
9398 INFO: Loading module hook "hook-pkg_resources.py"...
9640 INFO: Processing pre-safe import module hook   win32com
9856 INFO: Excluding import '__main__'
9857 INFO:   Removing import of __main__ from module pkg_resources
9857 INFO: Loading module hook "hook-pycparser.py"...
9858 INFO: Loading module hook "hook-pydoc.py"...
9859 INFO: Loading module hook "hook-pythoncom.py"...
10165 INFO: Loading module hook "hook-pywintypes.py"...
10523 INFO: Loading module hook "hook-setuptools.py"...
10979 INFO: Loading module hook "hook-sysconfig.py"...
10981 INFO: Loading module hook "hook-win32com.py"...
11209 INFO: Loading module hook "hook-xml.dom.domreg.py"...
11210 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
11211 INFO: Loading module hook "hook-xml.py"...
11211 INFO: Loading module hook "hook-_tkinter.py"...
11329 INFO: checking Tree
11368 INFO: checking Tree
11398 INFO: Looking for ctypes DLLs
11444 INFO: Analyzing run-time hooks ...
11448 INFO: Including run-time hook 'pyi_rth_pkgres.py'
11449 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
11451 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
11453 INFO: Including run-time hook 'pyi_rth__tkinter.py'
11464 INFO: Looking for dynamic libraries
12108 INFO: Looking for eggs
12108 INFO: Using Python library c:\python37\python37.dll
12109 INFO: Found binding redirects:
[]
12115 INFO: Warnings written to C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales\warn-globales.txt
12193 INFO: Graph cross-reference written to C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales\xref-globales.html
12220 INFO: checking PYZ
12224 INFO: Building because toc changed
12224 INFO: Building PYZ (ZlibArchive) C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales\PYZ-00.pyz
13457 INFO: Building PYZ (ZlibArchive) C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\globales\PYZ-00.pyz completed successfully.
13471 INFO: checking PKG
13479 INFO: Building because toc changed
13479 INFO: Building PKG (CArchive) PKG-00.pkg
20534 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
20551 INFO: Bootloader c:\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
20551 INFO: checking EXE
20559 INFO: Building because toc changed
20559 INFO: Building EXE from EXE-00.toc
20562 INFO: Appending archive to EXE C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\dist\globales.exe
20586 INFO: Building EXE from EXE-00.toc completed successfully.
```
In this moment globales not give me error?

**Comment by bwoodsend** [comment]
So it's working now?

**Comment by isdito** [comment]
I think yes, not give me error when execute, I am cheking with big py

**Comment by isdito** [comment]
I check with another py that interact and it is working.

What is the problem? reggards

**Comment by bwoodsend** [comment]
The `pkg_resources.py2_warn` issue is due to a hidden module inside `pkg_resources` but we've already fixed that one in the PyInstaller 4.0.

**Comment by isdito** [comment]
hello, I could update via github?

**Comment by bwoodsend** [comment]
`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`

**Comment by isdito** [comment]
hello,

I install but the error persist

```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000019d4 (most recent call first):
```

**Comment by bwoodsend** [comment]
Again, can we have the full error message. Not just the last few lines...

**Comment by isdito** [comment]
hi,

I execute
pyinstaller interface.py

```
86 INFO: PyInstaller: 4.0.dev0
86 INFO: Python: 3.7.8
86 INFO: Platform: Windows-10-10.0.18362-SP0
88 INFO: wrote C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\interface.spec
90 INFO: UPX is not available.
91 INFO: Extending PYTHONPATH with paths
['C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo',
 'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo']
101 INFO: checking Analysis
118 INFO: Building because C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\interface.py changed
118 INFO: Initializing module dependency graph...
120 INFO: Caching module graph hooks...
134 INFO: Analyzing base_library.zip ...
1818 INFO: Processing pre-find module path hook distutils from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
1821 INFO: distutils: retargeting to non-venv dir 'c:\\python37\\lib'
2961 INFO: Caching module dependency graph...
3062 INFO: running Analysis Analysis-00.toc
3079 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python37\python.exe
3145 INFO: Analyzing C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\interface.py
4896 INFO: Processing pre-safe import module hook six.moves from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
6205 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
8016 INFO: Processing pre-find module path hook site from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
8017 INFO: site: retargeting to fake-dir 'c:\\python37\\lib\\site-packages\\PyInstaller\\fake-modules'
8858 INFO: Processing pre-safe import module hook setuptools.extern.six.moves from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-setuptools.extern.six.moves.py'.
13200 INFO: Processing module hooks...
13200 INFO: Loading module hook 'hook-certifi.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13206 INFO: Loading module hook 'hook-cryptography.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13479 INFO: Loading module hook 'hook-lxml.etree.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13483 INFO: Loading module hook 'hook-markdown.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13643 INFO: Loading module hook 'hook-pycparser.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13644 INFO: Loading module hook 'hook-wx.xrc.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13646 INFO: Loading module hook 'hook-distutils.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
13648 INFO: Loading module hook 'hook-encodings.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
13718 INFO: Loading module hook 'hook-importlib_metadata.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
13720 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
13771 INFO: Loading module hook 'hook-numpy.core.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
14047 INFO: Loading module hook 'hook-numpy.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
14049 INFO: Loading module hook 'hook-PIL.Image.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
14336 INFO: Loading module hook 'hook-PIL.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
14338 INFO: Import to be excluded not found: 'PySide'
14339 INFO: Excluding import 'tkinter'
14341 INFO:   Removing import of tkinter from module PIL.ImageTk
14341 INFO: Import to be excluded not found: 'PyQt4'
14342 INFO: Excluding import 'PyQt5'
14343 INFO:   Removing import of PyQt5 from module PIL.ImageQt
14344 INFO: Import to be excluded not found: 'FixTk'
14344 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
14347 INFO: Excluding import 'tkinter'
14349 INFO: Import to be excluded not found: 'FixTk'
14349 INFO: Loading module hook 'hook-pkg_resources.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
14786 INFO: Processing pre-safe import module hook win32com from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
14876 INFO: Excluding import '__main__'
14877 INFO:   Removing import of __main__ from module pkg_resources
14878 INFO: Loading module hook 'hook-setuptools.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
15431 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
15434 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
15435 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
15436 INFO: Loading module hook 'hook-xml.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
15437 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
15575 INFO: checking Tree
15667 INFO: checking Tree
15694 INFO: Loading module hook 'hook-pythoncom.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
15992 INFO: Loading module hook 'hook-pywintypes.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
16279 INFO: Loading module hook 'hook-win32com.py' from 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
16625 INFO: Looking for ctypes DLLs
16671 INFO: Analyzing run-time hooks ...
16678 INFO: Including run-time hook 'c:\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_certifi.py'
16680 INFO: Including run-time hook 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
16682 INFO: Including run-time hook 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
16684 INFO: Including run-time hook 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
16686 INFO: Including run-time hook 'c:\\python37\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
16702 INFO: Looking for dynamic libraries
17110 WARNING: lib not found: libmysql.dll dependency of c:\python37\lib\site-packages\_mysql_connector.cp37-win_amd64.pyd
17876 INFO: Looking for eggs
17876 INFO: Using Python library c:\python37\python37.dll
17878 INFO: Found binding redirects:
[]
17888 INFO: Warnings written to C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\interface\warn-interface.txt
18034 INFO: Graph cross-reference written to C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\interface\xref-interface.html
18079 INFO: checking PYZ
18088 INFO: Building because toc changed
18088 INFO: Building PYZ (ZlibArchive) C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\interface\PYZ-00.pyz
19846 INFO: Building PYZ (ZlibArchive) C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\interface\PYZ-00.pyz completed successfully.
19876 INFO: checking PKG
19895 INFO: Building because toc changed
19895 INFO: Building PKG (CArchive) PKG-00.pkg
19962 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
19965 INFO: Bootloader c:\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
19965 INFO: checking EXE
19980 INFO: Building because name changed
19980 INFO: Building EXE from EXE-00.toc
19983 INFO: Appending archive to EXE C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\build\interface\interface.exe
19997 INFO: Building EXE from EXE-00.toc completed successfully.
20003 INFO: checking COLLECT
WARNING: The output directory "C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\dist\interface" and ALL ITS CONTENTS will be REMOVED! Continue? (y/N)y
On your own risk, you can use the option `--noconfirm` to get rid of this question.
23386 INFO: Removing dir C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\dist\interface
23951 INFO: Building COLLECT COLLECT-00.toc
31461 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```
and  I will go to build folder

```

C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo>interface.exe
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004f0c (most recent call first):

C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo>

```
I execute
PyInstaller --onefile interface.py
```

83 INFO: PyInstaller: 4.0.dev0
83 INFO: Python: 3.7.8
83 INFO: Platform: Windows-10-10.0.18362-SP0
84 INFO: wrote C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\interface.spec
87 INFO: UPX is not available.
89 INFO: Extending PYTHONPATH with paths
['C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo',
 'C:\\Users\\video-boda\\Desktop\\PROYECTO-PHOTO\\mi-codigo']
101 INFO: checking Analysis
257 INFO: checking PYZ
325 INFO: checking PKG
326 INFO: Building because toc changed
328 INFO: Building PKG (CArchive) PKG-00.pkg
11050 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
11068 INFO: Bootloader c:\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
11068 INFO: checking EXE
11069 INFO: Building because name changed
11070 INFO: Building EXE from EXE-00.toc
11071 INFO: Appending archive to EXE C:\Users\video-boda\Desktop\PROYECTO-PHOTO\mi-codigo\dist\interface.exe
11105 INFO: Building EXE from EXE-00.toc completed successfully.
```

and in dist folder de exe file works well.

![image](https://user-images.githubusercontent.com/602151/89126764-9c6b4b80-d4e8-11ea-81aa-b5be499800c7.png)

**Comment by Legorooj** [comment]
@isdito can you please run `pip install -U PyInstaller`. Does the issue persist or is it fixed?

**Comment by isdito** [comment]
Hello, @Legorooj  nop the erro persist.

I compile all with pyinstaller --onfile <name>   -->> this works

**Comment by Legorooj** [comment]
@isdito please ask this on StackOverflow or Reddit; we can't help any more.
