### ISSUE TITLE
centos 6.6 python3.7.0 fails packaging tkinter program

### ISSUE THREAD

**Issue by wym2010** [pyinstaller/pyinstaller#5036]
## Description of the issue
when packaging tkinter program, it fails
## Context information (for bug reports)
I am trying to packaging python script with tkinter, but met one issue when doing this, I can not search any information from internet, could you help me out?

* Output of `pyinstaller --version`: ```v3.6```
* Version of Python:  3.7.0
* Platform:  Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-6.6-Final
* Did you also try this on another platform? Does it work there?
centos 7 works for me

### A minimal example program which shows the error

```
Cannot find ('tcl/tclAppInit.c', '/usr/share/tcl8.5/tclAppInit.c', 1, 'x')


```

### Stacktrace / full error message

```
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python3.7 -m pip install --upgrade pip' command.
pyinstaller -F gui.py && pyinstaller -D gui.spec
45 INFO: PyInstaller: 3.6
45 INFO: Python: 3.7.0
46 INFO: Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-6.6-Final
46 INFO: wrote /src/gui.spec
48 INFO: UPX is not available.
50 INFO: Extending PYTHONPATH with paths
['/src', '/src']
50 INFO: checking Analysis
56 INFO: Building because inputs changed
57 INFO: Initializing module dependency graph...
58 INFO: Caching module graph hooks...
62 INFO: Analyzing base_library.zip ...
3126 INFO: Caching module dependency graph...
3212 INFO: running Analysis Analysis-00.toc
3228 INFO: Analyzing /src/gui.py
4763 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
5862 INFO: Processing module hooks...
5862 INFO: Loading module hook "hook-_tkinter.py"...
5938 INFO: checking Tree
5945 INFO: checking Tree
5949 INFO: Loading module hook "hook-certifi.py"...
5950 INFO: Loading module hook "hook-encodings.py"...
6000 INFO: Loading module hook "hook-pydoc.py"...
6001 INFO: Loading module hook "hook-xml.dom.domreg.py"...
6002 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
6002 INFO: Loading module hook "hook-xml.py"...
6018 INFO: Looking for ctypes DLLs
6018 INFO: Analyzing run-time hooks ...
6022 INFO: Including run-time hook 'pyi_rth_certifi.py'
6024 INFO: Including run-time hook 'pyi_rth__tkinter.py'
6031 INFO: Looking for dynamic libraries
6509 INFO: Looking for eggs
6509 INFO: Using Python library /usr/lib/libpython3.7m.so.1.0
6515 INFO: Warnings written to /src/build/gui/warn-gui.txt
6549 INFO: Graph cross-reference written to /src/build/gui/xref-gui.html
6571 INFO: checking PYZ
6574 INFO: Building because toc changed
6574 INFO: Building PYZ (ZlibArchive) /src/build/gui/PYZ-00.pyz
7152 INFO: Building PYZ (ZlibArchive) /src/build/gui/PYZ-00.pyz completed successfully.
7160 INFO: checking PKG
7163 INFO: Building because toc changed
7164 INFO: Building PKG (CArchive) PKG-00.pkg
Cannot find ('tcl/tclAppInit.c', '/usr/share/tcl8.5/tclAppInit.c', 1, 'x')
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "/src/gui.spec", line 33, in <module>
    console=True )
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/building/api.py", line 436, in __init__
    upx_exclude=self.upx_exclude
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/building/api.py", line 199, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/building/api.py", line 284, in assemble
    pylib_name=pylib_name)
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/archive/writers.py", line 336, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/archive/writers.py", line 63, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/archive/writers.py", line 88, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/archive/writers.py", line 383, in add
    fh = open(pathnm, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/tcl8.5/tclAppInit.c'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
Could you also tell us how you installed python and tkinter? There are quite a few possible ways on linux.

**Comment by Legorooj** [comment]
Stale
