### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by pro-clock-t** [pyinstaller/pyinstaller#5038]
71 INFO: PyInstaller: 3.6
72 INFO: Python: 3.7.3
72 INFO: Platform: Windows-10-10.0.18362-SP0
73 INFO: wrote C:\Windows\system32\pyinstaller.spec
76 INFO: UPX is not available.
Traceback (most recent call last):
  File "c:\users\owner\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\owner\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python38-32\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\owner\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\owner\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\owner\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\owner\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "C:\Windows\system32\pyinstaller.spec", line 6, in <module>
    a = Analysis(['pyinstaller.py'],
  File "c:\users\owner\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 191, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'C:\Windows\system32\pyinstaller.py' not found

**Comment by bwoodsend** [comment]
>  a = Analysis(['pyinstaller.py'],

Why are you trying to freeze PyInstaller?
