### ISSUE TITLE
gmplot not work after doing Pyinstaller 

### ISSUE THREAD

**Issue by tingweichien** [pyinstaller/pyinstaller#5041]
Everything works fine in .py file and I also successfully convert .py to .exe . But when I execute the exe file gmplot.draw, it shows error about gmplot.draw and FileNotFound

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "test.py", line 792, in plotmap
    gmap.draw('map.html')
  File "site-packages\gmplot\gmplot.py", line 1050, in draw
  File "site-packages\gmplot\gmplot.py", line 1121, in _write_html
  File "site-packages\gmplot\gmplot.py", line 1187, in write_points
  File "site-packages\gmplot\gmplot.py", line 1228, in write_point
  File "site-packages\gmplot\gmplot.py", line 164, in __init__
  File "site-packages\gmplot\utility.py", line 68, in _get_embeddable_image
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI366362\\gmplot\\markers/000000.png'
```
I I tried to fix it by adding
`gmp.coloricon = "http://www.googlemapsmarkers.com/v1/%s/"`
but still in vain

Here is my code
```
import gmplot
import webbrowser
from tkinter import *
import tkinter as tk

import os

def plotmap():
    gmp = gmplot.GoogleMapPlotter(24.28270434307802, 121.02747201919554, 14, apikey="")
    gmp.coloricon = "http://www.googlemapsmarkers.com/v1/%s/"
    gmp.marker(24.28270434307802, 121.02747201919554)
    gmp.draw("map.html")

    webbrowser.open('map.html')


root = tk.Tk()
b = tk.Button(root, text= "plot on map", command=plotmap)
b.pack()
root.mainloop()
```

How could I fix it ????

**Comment by amifunny** [comment]
@tingweichien It looks like error is due to `gmplot` looking for its custom marker image in the wrong place.
When converting to .exe, pyinstaller bundles the packages in use. So relative path used in source code of gmplot-
`os.path.join(os.path.dirname(__file__), 'markers/%s.png')`
will not work.
Simply use a marker by putting it in the directory same as your `.py` file will resolve the issue. If you don't want to create your own marker, just go to `site-packages\gmplot\markers` and copy your favorite marker.

**Comment by Legorooj** [comment]
@amifunny good try, but you've actually got it completely wrong. If you see the path in the error: `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI366362\\gmplot\\markers/000000.png'` you'll notice it's inside a `_MEIxxxxx` directory. OneFile bundles extract to a location like this, so the `gmplot` source code isn't the issue. 

If you create a one directory bundle and examine the `gmplot/markers` folder, you'll find that all of the PNG files are missing, whereas if you find the `gmplot` directory in your site-packages folder the files exist.

The error is caused by PyInstaller not including the data files of `gmplot`. This error can be fixed by writing a hook for `gmplot`. See [here](https://pyinstaller.rtfd.io/en/latest/hooks.html) and a hook similar to what you'd need [here](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dclab.py).
