### ISSUE TITLE
 cannot import name '_create_cipher'

### ISSUE THREAD

**Issue by xiaopeng-han** [pyinstaller/pyinstaller#5053]
Please use the mailing list see <http://www.pyinstaller.org/support.html#mailing-list> for details.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker, but closed.
08-04-2020 10:32:29 +0000 WARNING service.py@dce-ctl:123 - Traceback (most recent call last):
  File "flask/app.py", line 1813, in full_dispatch_request
  File "flask/app.py", line 1799, in dispatch_request
  File "dce/api/auth.py", line 40, in decorated
  File "dce/common/utils.py", line 933, in wrapper
  File "Crypto/PublicKey/RSA.py", line 750, in import_key
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "Crypto/IO/PEM.py", line 41, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "Crypto/Cipher/DES.py", line 36, in <module>
ImportError: cannot import name '_create_cipher'

when i use pycryptodome==3.9.8. It makes some error ，how to do import   '_create_cipher' ？

**Comment by Legorooj** [comment]
@xiaopeng-han what package manager are you using? - `pip`, `conda`, etc. Also, please post the build log.

**Comment by Legorooj** [comment]
Please ask on StackOverflow or another forum - we can't help with this.
