### ISSUE TITLE
Pyinstaller not able to include the dlls in executable even though it is defined in .spec file and executable is created with -F option

### ISSUE THREAD

**Issue by vitsensei** [pyinstaller/pyinstaller#5057]
Hi. I would like to create an executable from my script. The idea is to give that executable to my colleagues without giving them all the necessary *.dll.

Here's the setup of my .spec:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['Project.py'],
             pathex=['C:\\dev\\Desmond'],
             binaries=[('Core\\shared_library\\*.dll','.'), ('*.dll','.')],
             datas=[],
             hiddenimports=[],
             hookspath=['.\\pyinstaller_test'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='Project',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
```
This created an executable that I can put anywhere in my computer and it would still be able to run. However, as soon as I put it in another computer, it failed completely (cannot find dlls).

Here is the command I used: pyinstaller -F Project.spec

Here is an example of how I loaded in my dll through ctypes:

```
import ctypes
lib = ctypes.cdll.LoadLibrary("my_lib.dll")
```

**Comment by vitsensei** [comment]
After digging a bit further, I managed to get this error message when running the executable on another computer:
```
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 151, in __init__
  File "ctypes\__init__.py", line 364, in __init__
OSError: [WinError 193] %1 is not a valid Win32 application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Project.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1035, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "Core\Parts.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "Core\Polyhole.py", line 16, in <module>
  File "ctypes\__init__.py", line 442, in LoadLibrary
  File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 153, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'F:\\PROJECT_X\\skel.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[14308] Failed to execute script Project
```

**Comment by vitsensei** [comment]
Closed because bad bug report.
