### ISSUE TITLE
Current head development is not compatible with pyqtgraph

### ISSUE THREAD

**Issue by vitsensei** [pyinstaller/pyinstaller#5061]
**OS**: Windows 10
**Python version**: 3.7.5
**Pyinstaller version**: current head
Minimal .py file:
```
from pyqtgraph.opengl import GLViewWidget

print("Helloo!")
```
Custom .spec file:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['pyinstaller_test.py'],
             pathex=['C:\\dev\\Desmond\\pyinstaller_test'],
             binaries=[],
             datas=[],
             hiddenimports=['pyqtgraph.opengl.GLViewWidget'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='pyinstaller_test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               upx_exclude=[],
               name='pyinstaller_test')
```
Error output:

```
Traceback (most recent call last):
  File "pyinstaller_test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pyqtgraph\opengl\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pyqtgraph\opengl\GLViewWidget.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "OpenGL\GL\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "OpenGL\error.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "OpenGL\platform\__init__.py", line 36, in <module>
  File "OpenGL\platform\__init__.py", line 30, in _load
TypeError: 'NoneType' object is not callable
[15412] Failed to execute script pyinstaller_test
```

Observation: I don't encounter this error in the previous version of pyinstaller (the one on PyPI). When upgrading into this version, I encounter the ImportError: cannot import name 'opengl_arrays_modules' from 'PyInstaller.utils.hooks' and then follow the advice from [here](https://stackoverflow.com/questions/63052345/pyinstaller-and-opengl-error-importerror-cannot-import-name-opengl-arrays-mod). That fix the ImportError, but now I have this problem instead.

If you would like to me provide any extra information, I will gladly do so. Thank you :).

**Comment by Legorooj** [comment]
I'm transferring this to hooks-contrib. Could @bwoodsend take a look at this?
