### ISSUE TITLE
WinError87 while running .EXE file

### ISSUE THREAD

**Issue by timurkanaz** [pyinstaller/pyinstaller#5063]
Hello everyone! Maybe it is an offtop but I am a bit puzzled.. Just generated exe file for my GUI python program for working with some geospatial data and use folium,geopandas,shapely etc. However, while running an error occured:

```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\timna\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\geopandas\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\timna\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\geopandas\io\file.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\timna\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\fiona\__init__.py", line 88, in <module>
  File "contextlib.py", line 113, in __enter__
  File "site-packages\fiona\_loading.py", line 54, in add_gdal_dll_directories
  File "os.py", line 1109, in add_dll_directory
OSError: [WinError 87]  The parameter is incorrect: ''
[15176] Failed to execute script main
```
The line 9 in main.py is "import geopandas as gpd"
Geopandas imports fiona and error occurs, as I understand this error message. 

What is the reason?Are there any possible ways to resolve this problem?

Thanks for response and help!

**Comment by Legorooj** [comment]
@vitsensei if you can take a look at this?

**Comment by vitsensei** [comment]
@timurkanaz Can you provide a minimal example where the same behavior is present?

**Comment by vitsensei** [comment]
@timurkanaz I just take a brief look at the geopandas package and I can see that there is some differences between the Windows version and the Linux/Mac version.  

```
fiona provides binary wheels with the dependencies included for Mac and Linux, but not for Windows.

pyproj and shapely provide binary wheels with dependencies included for Mac, Linux, and Windows.

rtree does not provide wheels.

Windows wheels for shapely, fiona, pyproj and rtree can be found at Christopher Gohlke’s website.
```

Are you using unofficial wheels for these dependencies? If yes, what is your Python version?

**Comment by timurkanaz** [comment]
@vitsensei , Good day, thanks for response . I could not install geopandas with the help of pip or conda so I have downloaded all wheels from Christoph Gohlke website (https://www.lfd.uci.edu/~gohlke/pythonlibs)  and installed them . The interesting moment is when I use geopandas in Jupyter , for example, everything is ok, but when I make exe with pyinstaller, an error occurs . Yes, I have found wheels for fiona too  on his website.

**Comment by vitsensei** [comment]
@timurkanaz It seems like the fiona package is causing a bit of problem here.
From these lines:
  ```
File "site-packages\fiona\__init__.py", line 88, in <module>
  File "contextlib.py", line 113, in __enter__
  File "site-packages\fiona\_loading.py", line 54, in add_gdal_dll_directories
  File "os.py", line 1109, in add_dll_directory
```
my guess is fiona trying to load some dlls here. In specific, the GDAL dll. Now, here is the sad new from Fiona's Github page:

`Note: The GDAL DLL (gdal111.dll or similar) and gdal-data directory need to be in your Windows PATH otherwise Fiona will fail to work.`

If I understand correctly, Fiona official wheel does not include the binaries (a common theme with Toblerity). And I can't seem to find ```add_dll_directory``` in Fiona's head. So I can only assume that the ```add_dll_directory``` comes from the unofficial wheel, which probably requires some digging through to really understand which dll is being searched for.

**Comment by timurkanaz** [comment]
@vitsensei  Oh,thank you , now everything become clearer and much more interesting :) So , as I understand , the obvious way is to try to add gdal data  to Windows Path ? 

On the other hand ,  why I can import geopandas with full functionality in my Jupyter projects without any problems?

**Comment by Legorooj** [comment]
@vitsensei try a `collect_all` hook.

**Comment by vitsensei** [comment]
Ok, I will document my process as much as I can (TLDR at the end).
Initially, I thought that the problem lies with Fiona. I downloaded the (unofficial) GDAL and Fiona library (Fiona requires CDAL to work). I tried a simple script:
```
import fiona

print("Hello!")
```
After a few trial and error, I managed to get all the hidden import and put it into my .spec file:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['fiona_test.py'],
             pathex=['C:\\dev\\pyinstaller_test'],
             binaries=[],
             datas=[],
             hiddenimports=["fiona._shim", "fiona.schema"],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='fiona_test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='fiona_test')
```
Ok, it works, while I'm expecting it to not work. So I think geopandas might have invoked some Fiona's functions in its import which causes the error you are seeing. Well, let's go back to the build log:

```
9497 INFO: Looking for dynamic libraries
9743 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\schema.cp37-win_amd64.pyd
9753 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_shim.cp37-win_amd64.pyd
9763 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_err.cp37-win_amd64.pyd
9773 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_geometry.cp37-win_amd64.pyd
9786 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\ogrext.cp37-win_amd64.pyd
9798 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_env.cp37-win_amd64.pyd
9809 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_crs.cp37-win_amd64.pyd
```

Classic. Let's try to find a way to expose gdal301.dll to Pyinstaller. Following @Legorooj suggestion, let's try adding a hook file (hook-fiona) for our friend Fiona:
```
from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all('fiona')
```
And also update our .spec file to reflect this change:
```
...
hookspath=['.'] # I put hook-fiona in the same folder as fiona_test.py
...
```
Ok, seems like we are having a clean build. Let's try installing geopandas and give it a go. I already have rtree, shapely prior, plus fiona for this test. Install straight from PyPi, nothing special here. Let's do another simple test:

```
import geopandas as gpd

print("Hellooooo!")
```
And just use ```pyinstaller geopandas_test.py```, see if we have the same error.
Nope.

```
Traceback (most recent call last):
  File "geopandas_test.py", line 1, in <module>
  File "c:\dev\pyinstaller_test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\geopandas\__init__.py", line 3, in <module>
  File "c:\dev\pyinstaller_test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\geopandas\geoseries.py", line 9, in <module>
  File "c:\dev\pyinstaller_test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\pyproj\__init__.py", line 50, in <module>
  File "pyproj\_datadir.pyx", line 6, in init pyproj._datadir
ModuleNotFoundError: No module named 'pyproj.datadir'
[21744] Failed to execute script geopandas_test
```

Another hidden import!! Let's change our spec file to reflect this.
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['geopandas_test.py'],
             pathex=['C:\\dev\\pyinstaller_test'],
             binaries=[],
             datas=[],
             hiddenimports=["pyproj.datadir", "fiona._shim", "fiona.schema"], # The last two are from our little fiona experiment
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='geopandas_test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='geopandas_test')
```
Will it work this time? Nope.

```
Traceback (most recent call last):
  File "geopandas_test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\dev\pyinstaller_test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\geopandas\__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\dev\pyinstaller_test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\geopandas\datasets\__init__.py", line 6, in <module>
StopIteration
[21772] Failed to execute script geopandas_test
```
You know what, let's just bring in the big gun. Let's write a hook file for geopandas.

```
from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all('geopandas')
```

Now it works. HA!

### **To sum up**:
geopandas_test.spec:

```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['geopandas_test.py'],
             pathex=['C:\\dev\\pyinstaller_test'],
             binaries=[],
             datas=[],
             hiddenimports=["pyproj.datadir", "fiona._shim", "fiona.schema"],
             hookspath=["."],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='geopandas_test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='geopandas_test')
```

What hook file did I have: hook-geopandas.py and hook-fiona.py
**hook-geopandas.py**
```
from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all('geopandas')
```

**hook-fiona**
```
from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all('fiona')
```
**Command I used**: ```pyinstaller geopandas_test.spec```
**OS**: Windows 10
**Python**: 3.7
**Virtual Env**: Yes.
**IDE**: Pycharm
**Pyinstaller version**: The one on PyPI.

Try it and let me know if it works.

**Comment by vitsensei** [comment]
What I find strange is I still have not managed to solve the warning:
```
18034 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\schema.cp37-win_amd64.pyd
18044 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_crs.cp37-win_amd64.pyd
18064 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_transform.cp37-win_amd64.pyd
18077 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_err.cp37-win_amd64.pyd
18088 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_geometry.cp37-win_amd64.pyd
18132 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\ogrext.cp37-win_amd64.pyd
18143 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_env.cp37-win_amd64.pyd
18313 WARNING: lib not found: gdal301.dll dependency of c:\dev\pyinstaller_test\venv\lib\site-packages\fiona\_shim.cp37-win_amd64.pyd
```
I have a feeling that this will cause some error if you evoke some function that depends on gdal301.dll. Good luck.

**Comment by timurkanaz** [comment]
@vitsensei  Wow! Thank you! Now line with geopandas library import is successfully overcome ! However, another problem appeared : 

```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\timna\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\branca\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\timna\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\branca\colormap.py", line 62, in <module>
  File "site-packages\branca\colormap.py", line 74, in ColorMap
  File "site-packages\jinja2\environment.py", line 883, in get_template
  File "site-packages\jinja2\environment.py", line 857, in _load_template
  File "site-packages\jinja2\loaders.py", line 115, in load
  File "site-packages\jinja2\loaders.py", line 248, in get_source
  File "site-packages\pkg_resources\__init__.py", line 1404, in has_resource
  File "site-packages\pkg_resources\__init__.py", line 1473, in _has
NotImplementedError: Can't perform this operation for unregistered loader type
[15596] Failed to execute script main
```

As I understand , It is a problem with **branca** library which I import too. It's built over **jinja2** library. So,to overcome this problem I need to make a hook for branca?  I'm really sorry to bother you

**Comment by vitsensei** [comment]
@timurkanaz we need people to bother us so we can make the project better!
If I were you, I probably start small. Just create a script that only import branca and then create a hook for that. See how that goes.
It would help you to create a (test) exe much faster => less frustrating. I'm less familiar with branca package so you might have better luck tackle this than I am.

**Comment by Legorooj** [comment]
@timurkanaz also, if you could submit any hooks you do write to our hooks-contrib repository, that would be helpful.

**Comment by timurkanaz** [comment]
I have found similiar issue , however, no compromise was not find  
https://github.com/pyinstaller/pyinstaller/issues/1898

**Comment by Legorooj** [comment]
Sigh. That issue. See #4881. Long story short `branca` won't work with PyInstaller until I tackle that. Either of you can have a go, but it's a major issue. It also won't make it to the 4.0 release - though I'm going to speed up the release schedule after that.

**Comment by Legorooj** [comment]
Seeing as the original issue raised here has been fixed, I'm going to close this. The pkg_resources upgrade is already planned.
