### ISSUE TITLE
Error when using "-d noarchive"

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#5080]
I'm trying to build my app with the `noarchive` flag and getting an error:
```
676190 INFO: Using Python library c:\Python27\python27.dll
676255 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 21022, 8), publicKeyToken=u'1fc8b3b9a1e18e3b')]
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\Python27\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python27\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "Z:\src\sbsimulation.spec", line 17, in <module>
    noarchive=True)
  File "c:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
    self.__postinit__()
  File "c:\Python27\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):
  File "c:\Python27\lib\site-packages\PyInstaller\utils\misc.py", line 152, in compile_py_files
    with open(obj_fnm, 'rb') as fh:
IOError: [Errno 2] No such file or directory: '-'
```
The build is working without the `noarchive` flag and this flag is working on other apps so maybe it is an issue with external module.

Running the build with `--log-level DEBUG` generated the same output at the error.
Is there anything else I can do to debug this?

PyInstaller version: 3.6
OS: Windows
Python version: 2.7.18

**Comment by arossert** [comment]
Ok, after further digging it seems that this issue was resolved in `4.0` release by this commit https://github.com/pyinstaller/pyinstaller/commit/f7168c866d7f2d583bf6eb00fbab647a513f64c1

The issue is that `4.0` dropped support in Python2, unfortunately, we still in a process of migrating to Python3 but not there yet.

Will you consider applying this fix to `3.6` and release a `3.6.1` version so it will work in Python2?
I will be happy to help and provide a PR if needed.

**Comment by Legorooj** [comment]
@arossert maybe - we're having and internal changeup at the moment so we need some time to figure out what's going on. After that I'll look at doing this. In the meantime, just apply the fix locally.

**Comment by arossert** [comment]
@Legorooj Thank you very much, it will be nice seeing it in an official release.
In the meanwhile, I will work with a fork.
