### ISSUE TITLE
This is to the developers of the PyInstaller package

### ISSUE THREAD

**Issue by LokotamaTheMastermind** [pyinstaller/pyinstaller#5086]
**Is your feature request related to a problem? Please describe.**
The issue of the package not working on **`>Python 3.8`**
For all developers pip announced the way that installing packages will change before December 2020.
To prove it try installing another package with the latest version of pip and it will suggest that all packages should be tested with **`use-feature=2020-resolver`** for those developing packages

**Describe the solution you'd like**
The solution is for the developers to just test the command --use-feature=2020-resolver on their package before it becomes the default.

**Describe alternatives you've considered**
The method above is the only option I have that may work.

**Comment by Legorooj** [comment]
@amifunny or @vitsensei please take a look at [this](https://discuss.python.org/t/announcement-pip-20-2-release/4863) and check the new dependency resolver works with PyInstaller. If it doesn't, then submit a PR to fix it.

**Comment by amifunny** [comment]
@Legorooj Are you working on it?

**Comment by bwoodsend** [comment]
@amifunny No this ones all yours...

**Comment by LokotamaTheMastermind** [comment]
**Please what build dependencies are you using?**

**Seems there's a bug with it**

**Comment by LokotamaTheMastermind** [comment]
**`Strange thing setting up the package from within the cloned repo is not giving errors`**

**Comment by LokotamaTheMastermind** [comment]
**Are you meant to import pyinstaller?**

**Because I found out some packages that it uses but don't automatically install if they are not found in the setup.py file**

**Comment by LokotamaTheMastermind** [comment]
**Found a temporary solution to the problem until it is properly fixed!**

**First run the command `git clone --branch --single-branch develop https://github.com/pyinstaller/pyinstaller.git` in the terminal**

**Then `cd pyinstaller`**

**Then specifically run the commands after this sections:**

1. **`pip install --upgrade setuptools wheel pip` for windows or `pip3 install --upgrade setuptools wheel pip` for mac or linux**
2. **`python3 setup.py sdist bdist_wheel` for mac and linux or `python sdist bdist_wheel` for windows**
3. **`cd dist`**

## Explanation

1. The first one upgrades needed dependencies for the following commands after to work

**The following dependencies are needed:**
**The {version_number} is a placeholder to the actual version numbers. Also note this listed here must be the latest**

```txt 
Package                        Version
------------------------------ --------
setuptools                     {version_number}
wheel                          {version_number}
pip                            {version_number}
```

2. The number `2.` command run the setup and builds dependencies and all. All you just need to do is wait.

3. Changes directory to where the files where built.

## Next Steps after previous ones

1. Follow the picture below ...

![Screenshot_26](https://user-images.githubusercontent.com/57059138/90447035-6332fe00-e0da-11ea-9cc6-e0dd4f036ad1.png)

**Comment by LokotamaTheMastermind** [comment]
_**Sorry the picture is blurry**_

**Comment by LokotamaTheMastermind** [comment]
**I suggest putting the 4.0 release in `beta` mode**

**Comment by LokotamaTheMastermind** [comment]
Did the suggestion work

**Comment by LokotamaTheMastermind** [comment]
**cus I am not good at writing C code and it will be buggy, but the suggested method actually works well and the `--onefile` flag works as well as the `normal method`**

**Comment by bwoodsend** [comment]
@LokotamaTheMastermind I'm afraid that you've lost all of us. You'll need to explain...

I gather that by _new dependency solver_ you mean [this](https://pip.pypa.io/en/stable/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020). Now I've run their [prescribed list of checks](https://pip.pypa.io/en/stable/user_guide/#how-to-test) and I haven't noticed any problems. Can you explain exactly what exactly (shell command you input -> unwanted error/stacktrace that is output) issue you believe you've found.

> The issue of the package not working on >Python 3.8

Python 3.9 doesn't exist yet. Do you mean `>=3.8` or the (very much still in development) pre-release for 3.9.0?

**Comment by LokotamaTheMastermind** [comment]
I mean`Python 3.8 and above if any`

**Comment by LokotamaTheMastermind** [comment]
**And you really want the full traceback of the error while installing right ...**

```txt
Collecting pyinstaller
  Using cached pyinstaller-4.0.tar.gz (3.5 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\lokot\appdata\local\programs\python\python38-32\python.exe' 'c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\lokot\AppData\Local\Temp\pip-build-env-xmvt7fwc\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\__init__.py", line 125, in <module>
      from . import utils
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
      from . import certs
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1, in <module>
      from .core import contents, where
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\certifi\core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\importlib\resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\lokot\appdata\local\programs\python\python38-32\python.exe' 'c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\lokot\AppData\Local\Temp\pip-build-env-xmvt7fwc\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Here you go, `hope you can read it`**

**Comment by LokotamaTheMastermind** [comment]
**For the full the log ...**
**Good luck reading it**

```txt
2020-08-18T16:00:52,491 Using pip 20.2.2 from c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)
2020-08-18T16:00:52,509 Non-user install because site-packages writeable
2020-08-18T16:00:52,955 Created temporary directory: C:\Users\lokot\AppData\Local\Temp\pip-ephem-wheel-cache-zcm553qg
2020-08-18T16:00:52,958 Created temporary directory: C:\Users\lokot\AppData\Local\Temp\pip-req-tracker-5ikznatt
2020-08-18T16:00:52,959 Initialized build tracking at C:\Users\lokot\AppData\Local\Temp\pip-req-tracker-5ikznatt
2020-08-18T16:00:52,959 Created build tracker: C:\Users\lokot\AppData\Local\Temp\pip-req-tracker-5ikznatt
2020-08-18T16:00:52,960 Entered build tracker: C:\Users\lokot\AppData\Local\Temp\pip-req-tracker-5ikznatt
2020-08-18T16:00:52,962 Created temporary directory: C:\Users\lokot\AppData\Local\Temp\pip-install-y_pcsv6x
2020-08-18T16:00:53,390 1 location(s) to search for versions of pyinstaller:
2020-08-18T16:00:53,390 * https://pypi.org/simple/pyinstaller/
2020-08-18T16:00:53,391 Fetching project page and analyzing links: https://pypi.org/simple/pyinstaller/
2020-08-18T16:00:53,391 Getting page https://pypi.org/simple/pyinstaller/
2020-08-18T16:00:53,392 Found index url https://pypi.org/simple
2020-08-18T16:00:53,400 Getting credentials from keyring for https://pypi.org/simple
2020-08-18T16:00:53,403 Getting credentials from keyring for pypi.org
2020-08-18T16:00:54,193   Found link https://files.pythonhosted.org/packages/ec/a3/dc7bc8c48a873c3156866df709a23078a6dda86db88328df5cf639385527/pyinstaller-2.0.tar.bz2#sha256=ffbfb6e2b9db50b6efbf785b83f315b5daffd56fb85d92fe82969e5d8f4e8425 (from https://pypi.org/simple/pyinstaller/), version: 2.0
2020-08-18T16:00:54,194   Found link https://files.pythonhosted.org/packages/52/e5/0ce68034f3441bda11538162796dac5a8e5873e8af5d23aaea65e81c7e51/pyinstaller-2.0.zip#sha256=7f944ff131f6488ebad68e8db4a6f53f2d8054c618b6095d7cbba3ca0f733bab (from https://pypi.org/simple/pyinstaller/), version: 2.0
2020-08-18T16:00:54,194   Found link https://files.pythonhosted.org/packages/c3/a3/d50648bc99a8d5d6c533fc5c1101cc18014d0782e7ddbe9744ad2d56ad49/PyInstaller-2.1.tar.gz#sha256=feff03a3212d984882432ff81c6afcdcf04d8f636fd4beb131b7a027653b3b05 (from https://pypi.org/simple/pyinstaller/), version: 2.1
2020-08-18T16:00:54,195   Found link https://files.pythonhosted.org/packages/0b/87/4758831a995645873f72c51ec09f8e51db607ed89a336b0afe12702c4329/PyInstaller-2.1.zip#sha256=d73d4a69ffc92827a6fedfeca49415f805f674a599c67f8f6a8571fae19725d9 (from https://pypi.org/simple/pyinstaller/), version: 2.1
2020-08-18T16:00:54,196   Found link https://files.pythonhosted.org/packages/43/a5/ed7a830f3e8bec1231ed50d9eafe24b6e5873a5a194dfddf272518baf947/PyInstaller-3.0.tar.gz#sha256=8f9f9836ffebe71f9d9ced24001f8b27c0492574ed12a7a97c2c8810fb3fa210 (from https://pypi.org/simple/pyinstaller/), version: 3.0
2020-08-18T16:00:54,196   Found link https://files.pythonhosted.org/packages/33/e8/3fed48b82122c81f4db22a8be70de0b3482beff154800d65e1131a5600fb/PyInstaller-3.1.zip#sha256=d4eec0f145e712c0f0e8c8fe27ad645480709903222204157e78420e374cae81 (from https://pypi.org/simple/pyinstaller/), version: 3.1
2020-08-18T16:00:54,197   Found link https://files.pythonhosted.org/packages/51/7f/e2f744ba13d7a27360a43b62d3d9aeff7df1d7fa346f746fc040a0caf9e3/PyInstaller-3.1.1.tar.gz#sha256=b111d35d836237bf954e9b47dcb338da48a40210c318b2b0bc163dba8ca8e096 (from https://pypi.org/simple/pyinstaller/), version: 3.1.1
2020-08-18T16:00:54,197   Found link https://files.pythonhosted.org/packages/f8/d4/06cbe4304fb25f95ecc02a313792b9fd222d6ca3bfd17722bf4bbfb6f36d/PyInstaller-3.1.1.zip#sha256=7b3d9884cd806b31570950c5d9ad4aaaac1bbe9f374ab3d10e61f9f499642910 (from https://pypi.org/simple/pyinstaller/), version: 3.1.1
2020-08-18T16:00:54,198   Found link https://files.pythonhosted.org/packages/33/f9/034a89276301ef5e88efd11e5ea592e3d3b2324706e65bdff7445d271077/PyInstaller-3.2.tar.gz#sha256=7598d4c9f5712ba78beb46a857a493b1b93a584ca59944b8e7b6be00bb89cabc (from https://pypi.org/simple/pyinstaller/), version: 3.2
2020-08-18T16:00:54,199   Found link https://files.pythonhosted.org/packages/d5/ca/f4916fe37d0a372c530c144f6cbd4d5b81f4be0ab709309ab8ea82f3583a/PyInstaller-3.2.zip#sha256=e27ad7e840d49924f375d3ffa4e0d67b9340f4d78c8279378dd5f4a89dbf6318 (from https://pypi.org/simple/pyinstaller/), version: 3.2
2020-08-18T16:00:54,199   Found link https://files.pythonhosted.org/packages/3f/d2/3515242cc5cfed12706506d17728a7ee0b8cf33840e250357fd793a94607/PyInstaller-3.2.1.tar.bz2#sha256=f08ca806bc26e62034bca181a4b85de22568a3d39bdb062f05927c6e86c2a48c (from https://pypi.org/simple/pyinstaller/), version: 3.2.1
2020-08-18T16:00:54,200   Found link https://files.pythonhosted.org/packages/cc/c2/5d9a7756419f47ef378add16c7c50c9d7794ae7a39b71b68b00bd7d3ae20/PyInstaller-3.3.tar.gz#sha256=b6c95cdbb45ac78a44723fa2992b58e14637cbefecafc22d3790af262a7fad6f (from https://pypi.org/simple/pyinstaller/), version: 3.3
2020-08-18T16:00:54,200   Found link https://files.pythonhosted.org/packages/3c/86/909a8c35c5471919b3854c01f43843d9b5aed0e9948b63e560010f7f3429/PyInstaller-3.3.1.tar.gz#sha256=715f81f24b1ef0e5fe3b3c71e7540551838e46e9de30882aa7c0a521147fd1ce (from https://pypi.org/simple/pyinstaller/), version: 3.3.1
2020-08-18T16:00:54,202   Found link https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz#sha256=a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*), version: 3.4
2020-08-18T16:00:54,203   Found link https://files.pythonhosted.org/packages/e2/c9/0b44b2ea87ba36395483a672fddd07e6a9cb2b8d3c4a28d7ae76c7e7e1e5/PyInstaller-3.5.tar.gz#sha256=ee7504022d1332a3324250faf2135ea56ac71fdb6309cff8cd235de26b1d0a96 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*), version: 3.5
2020-08-18T16:00:54,205   Found link https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz#sha256=3730fa80d088f8bb7084d32480eb87cbb4ddb64123363763cf8f2a1378c1c4b7 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*), version: 3.6
2020-08-18T16:00:54,205   Found link https://files.pythonhosted.org/packages/82/96/21ba3619647bac2b34b4996b2dbbea8e74a703767ce24192899d9153c058/pyinstaller-4.0.tar.gz#sha256=970beb07115761d5e4ec317c1351b712fd90ae7f23994db914c633281f99bab0 (from https://pypi.org/simple/pyinstaller/), version: 4.0
2020-08-18T16:00:54,207 Given no hashes to check 17 links for project 'pyinstaller': discarding no candidates
2020-08-18T16:00:54,213 Using version 4.0 (newest of versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0)
2020-08-18T16:00:54,216 Collecting pyinstaller
2020-08-18T16:00:54,220   Created temporary directory: C:\Users\lokot\AppData\Local\Temp\pip-unpack-01rbb3kw
2020-08-18T16:00:54,224   Getting credentials from keyring for files.pythonhosted.org
2020-08-18T16:00:54,272   Using cached pyinstaller-4.0.tar.gz (3.5 MB)
2020-08-18T16:01:00,685   Added pyinstaller from https://files.pythonhosted.org/packages/82/96/21ba3619647bac2b34b4996b2dbbea8e74a703767ce24192899d9153c058/pyinstaller-4.0.tar.gz#sha256=970beb07115761d5e4ec317c1351b712fd90ae7f23994db914c633281f99bab0 to build tracker 'C:\\Users\\lokot\\AppData\\Local\\Temp\\pip-req-tracker-5ikznatt'
2020-08-18T16:01:00,698   Created temporary directory: C:\Users\lokot\AppData\Local\Temp\pip-build-env-p6_vt15b
2020-08-18T16:01:00,703   Running command 'c:\users\lokot\appdata\local\programs\python\python38-32\python.exe' 'c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\lokot\AppData\Local\Temp\pip-build-env-p6_vt15b\overlay' --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
2020-08-18T16:01:05,624   Traceback (most recent call last):
2020-08-18T16:01:05,625     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
2020-08-18T16:01:05,625       return _run_code(code, main_globals, None,
2020-08-18T16:01:05,626     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
2020-08-18T16:01:05,626       exec(code, run_globals)
2020-08-18T16:01:05,626     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\__main__.py", line 26, in <module>
2020-08-18T16:01:05,627       sys.exit(_main())
2020-08-18T16:01:05,627     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
2020-08-18T16:01:05,627       command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
2020-08-18T16:01:05,628     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
2020-08-18T16:01:05,628       module = importlib.import_module(module_path)
2020-08-18T16:01:05,628     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
2020-08-18T16:01:05,629       return _bootstrap._gcd_import(name[level:], package, level)
2020-08-18T16:01:05,629     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-08-18T16:01:05,629     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-08-18T16:01:05,630     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-08-18T16:01:05,630     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-08-18T16:01:05,630     File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-08-18T16:01:05,631     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-08-18T16:01:05,631     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\install.py", line 17, in <module>
2020-08-18T16:01:05,631       from pip._internal.cli.req_command import RequirementCommand, with_cleanup
2020-08-18T16:01:05,631     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
2020-08-18T16:01:05,632       from pip._internal.index.collector import LinkCollector
2020-08-18T16:01:05,632     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
2020-08-18T16:01:05,632       from pip._vendor import html5lib, requests
2020-08-18T16:01:05,632     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\__init__.py", line 125, in <module>
2020-08-18T16:01:05,633       from . import utils
2020-08-18T16:01:05,633     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
2020-08-18T16:01:05,633       from . import certs
2020-08-18T16:01:05,633     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\certs.py", line 15, in <module>
2020-08-18T16:01:05,634       from pip._vendor.certifi import where
2020-08-18T16:01:05,634     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1, in <module>
2020-08-18T16:01:05,634       from .core import contents, where
2020-08-18T16:01:05,635     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\certifi\core.py", line 12, in <module>
2020-08-18T16:01:05,635       from importlib.resources import path as get_path, read_text
2020-08-18T16:01:05,635     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\importlib\resources.py", line 11, in <module>
2020-08-18T16:01:05,635       from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
2020-08-18T16:01:05,636     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\typing.py", line 1359, in <module>
2020-08-18T16:01:05,636       class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
2020-08-18T16:01:05,636     File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\typing.py", line 1007, in __new__
2020-08-18T16:01:05,636       self._abc_registry = extra._abc_registry
2020-08-18T16:01:05,637   AttributeError: type object 'Callable' has no attribute '_abc_registry'
2020-08-18T16:01:05,687 ERROR: Command errored out with exit status 1: 'c:\users\lokot\appdata\local\programs\python\python38-32\python.exe' 'c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\lokot\AppData\Local\Temp\pip-build-env-p6_vt15b\overlay' --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
2020-08-18T16:01:05,689 Exception information:
2020-08-18T16:01:05,689 Traceback (most recent call last):
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\base_command.py", line 216, in _main
2020-08-18T16:01:05,689     status = self.run(options, args)
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
2020-08-18T16:01:05,689     return func(self, options, args)
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\install.py", line 324, in run
2020-08-18T16:01:05,689     requirement_set = resolver.resolve(
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 183, in resolve
2020-08-18T16:01:05,689     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 388, in _resolve_one
2020-08-18T16:01:05,689     abstract_dist = self._get_abstract_dist_for(req_to_install)
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 340, in _get_abstract_dist_for
2020-08-18T16:01:05,689     abstract_dist = self.preparer.prepare_linked_requirement(req)
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
2020-08-18T16:01:05,689     abstract_dist = _get_prepared_distribution(
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\operations\prepare.py", line 91, in _get_prepared_distribution
2020-08-18T16:01:05,689     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\distributions\sdist.py", line 38, in prepare_distribution_metadata
2020-08-18T16:01:05,689     self._setup_isolation(finder)
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\distributions\sdist.py", line 66, in _setup_isolation
2020-08-18T16:01:05,689     self.req.build_env.install_requirements(
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\build_env.py", line 205, in install_requirements
2020-08-18T16:01:05,689     call_subprocess(args, spinner=spinner)
2020-08-18T16:01:05,689   File "c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\utils\subprocess.py", line 242, in call_subprocess
2020-08-18T16:01:05,689     raise InstallationError(exc_msg)
2020-08-18T16:01:05,689 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: 'c:\users\lokot\appdata\local\programs\python\python38-32\python.exe' 'c:\users\lokot\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\lokot\AppData\Local\Temp\pip-build-env-p6_vt15b\overlay' --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
2020-08-18T16:01:06,319 Removed pyinstaller from https://files.pythonhosted.org/packages/82/96/21ba3619647bac2b34b4996b2dbbea8e74a703767ce24192899d9153c058/pyinstaller-4.0.tar.gz#sha256=970beb07115761d5e4ec317c1351b712fd90ae7f23994db914c633281f99bab0 from build tracker 'C:\\Users\\lokot\\AppData\\Local\\Temp\\pip-req-tracker-5ikznatt'
2020-08-18T16:01:06,320 Removed build tracker: 'C:\\Users\\lokot\\AppData\\Local\\Temp\\pip-req-tracker-5ikznatt'
```

**Comment by bwoodsend** [comment]
@LokotamaTheMastermind I'm not seeing this error. I'm using the following on both a 32-bit and 64-bit clean installation of Python (as well as my messy home environment):
```shell
python38 -m pip install -U pip setuptools wheel
pip38 install --use-feature=2020-resolver PyInstaller
```
Can you tell us the command you are using?

**Comment by LokotamaTheMastermind** [comment]
**I'm using a Windows**

**I may try it Kali too see the result**

**Comment by bwoodsend** [comment]
No I mean what are you typing into `cmd`?

**Comment by LokotamaTheMastermind** [comment]
**Well _`pip install pyinstaller`_ like normal people would do ...**
