### ISSUE TITLE
Failed to execute script pyiboot01_bootstrap

### ISSUE THREAD

**Issue by glennra** [pyinstaller/pyinstaller#5104]
## Description of the issue
When launched the frozen executable displays a message box with "Failed to execute script pyiboot01_bootstrap" .

## Context information (for bug reports)

* Output of `pyinstaller --version`:

```pyinstaller.py --version
Traceback (most recent call last):
  File "C:\path\to\pyinstaller-git\pyinstaller.py", line 16, in <module>
    from PyInstaller.__main__ import run
  File "C:\path\to\pyinstaller-git\PyInstaller\__init__.py", line 18, in <module>
    from . import compat
  File "C:\path\to\pyinstaller-git\PyInstaller\compat.py", line 306
    print('--' * 20, file=sys.stderr)
                         ^
SyntaxError: invalid syntax
```
Wasn't expecting the above error. The version is the 4.0 tagged version from the github master branch

* Version of Python :3.7.8
* Platform: Windows 10 build 2004
* Did you also try this on another platform? Does it work there? 
Same error with the latest develop version

### A minimal example program which shows the error

```
import sys
from PyQt5 import QtWidgets
from PyQt5 import QtCore

app = QtWidgets.QApplication(sys.argv)
title = "PyQt5 test"
label = QtWidgets.QLabel(title, None)
label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
label.setWindowTitle(title)
label.resize(800, 400)
edit = QtWidgets.QLineEdit(label)

label.show()

app.exec_()
```

```
import sys
import os

path = [
    os.path.join('${CMAKE_CURRENT_SOURCE_DIR}', 'lineedit.py'),
    ]        

debug = False

app_name="lineedit"
exe_name="lineedit"
if sys.platform.startswith("win"):
    exe_name += ".exe"

a = Analysis(path,
             pathex=['${CMAKE_CURRENT_SOURCE_DIR}'],
             hiddenimports=[],
             hookspath=None)
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts + [('v', '', 'OPTION')], #, ('O', '', 'OPTION')],
          exclude_binaries=1,
          name=exe_name,
          debug=debug,
          strip=None,
          upx=False,
          console=debug )

extralibs = []
extrafiles = []

coll = COLLECT(exe,
               a.binaries + extralibs,
               a.zipfiles,
               a.datas + extrafiles,
               strip=None,
               upx=False,
               name=app_name)
```

**Comment by bwoodsend** [comment]
```
    print('--' * 20, file=sys.stderr)
                         ^
SyntaxError: invalid syntax
```
Looks like your `PATH` and/or venv is a mess because I'm pretty certain you're running Python2 without realising.

Try running the following to check your Python is Python3 and you have a PyInstaller installed on it:
```shell
python -VV
python -m PyInstaller --version
```
Also check the following paths point inside the same Python installation:
```shell
where pyinstaller
python -m pip show PyInstaller | grep Location
```

`pyiboot01_bootstrap` errors just means something went wrong but you've disabled `stderr` using `console=debug` with `debug=False` so you can't see what. Set `console=True` until your confident your app behaves itself or you have a fancy way of redirecting errors to logs or error pop-up windows (not recommended).

**Comment by glennra** [comment]
This machine does have both Python27 and Python37 installed but only Python37 appears in the path. However #!/usr/bin/env python finds Python27.
I always use `python <scriptpath>` and that uses the correct Python version so I think the Python 2 thing is a red herring. I only did it the other way that time because I was following the instructions.
Running it the 'right' way, I get: 

`>python \path\to\pyinstaller.py --version`
`4.0`

The reason I have `console=False` is because that is how to produce the problem. It doesn't happen if `console=True`. That is a key piece of information that I should have specifically mentioned, not sure why it slipped my mind at the time, sorry about that.

With `console=False` and `debug=True` after I close the initial error box another one appears that has the message `Error: <NULL>` and on closing that the app exits.

**Comment by bwoodsend** [comment]
OK, I've just tested your example and I get the error. But I believe this is all just a typo in your spec. Applying the following fixes it.
```diff
exe = EXE(pyz,
-          a.scripts + [('v', '', 'OPTION')], #, ('O', '', 'OPTION')],
+          a.scripts, [('v', '', 'OPTION')], #, ('O', '', 'OPTION')],
          exclude_binaries=1,
          name=exe_name,
```

**Comment by bwoodsend** [comment]
OK, I've just tested your example and I get the error. But I believe this is all just a typo in your spec. Applying the following fixes it.
```diff
exe = EXE(pyz,
-          a.scripts + [('v', '', 'OPTION')], #, ('O', '', 'OPTION')],
+          a.scripts, [('v', '', 'OPTION')], #, ('O', '', 'OPTION')],
          exclude_binaries=1,
          name=exe_name,
```

**Comment by glennra** [comment]
Thanks and well spotted. I've been using that code for many years so would never have thought to suspect it.

The fix you suggested didn't work for me, but removing the  [('v', '', 'OPTION')] line altogether did work.

I guess that makes sense as evidently in --windowed mode Windows has trouble with stdout, etc.

It would be useful if there was a warning in the build output or even some guidance in the documentation about this,

**Comment by bwoodsend** [comment]
> The fix you suggested didn't work for me, 

Did you remember to clear you `build` folder and use the `--clean` option?

And yes, `EXE` really should've caught that invalid value.

**Comment by bwoodsend** [comment]
@Legorooj Any objections to adding some `raise ValueError` checks to `EXE`'s inputs to catch mistakes like the one [above](https://github.com/pyinstaller/pyinstaller/issues/5104#issuecomment-682346900)?

**Comment by Legorooj** [comment]
@bwoodsend go ahead - that's exactly the sort of thing we need for debugging.
