### ISSUE TITLE
pyinstaller throws exception : dump_all() got an unexpected keyword argument 'sort_keys'

### ISSUE THREAD

**Issue by erickyi2006** [pyinstaller/pyinstaller#5136]
if I used pure python, it works
but if i generate the binary in windows, it failed with "dump_all() got an unexpected keyword argument 'sort_keys'"

Code fragement
`            with open(output_file_yaml, 'w') as outf:
                yaml.safe_dump(formatted_json, outf, default_flow_style=False, sort_keys=False, width=float("inf"), allow_unicode=True)
`

I am using the anaconda and here is my pip list. Note I am using the latest pyyaml which supports sort_keys.
`
Package             Version
------------------- ---------
autopep8            1.4.4
certifi             2020.6.20
chardet             3.0.4
Click               7.0
configparser        3.7.4
decorator           4.4.0
et-xmlfile          1.0.1
Flask               1.1.1
idna                2.8
importlib-resources 3.0.0
iniparse            0.5
itsdangerous        1.1.0
jdcal               1.4.1
Jinja2              2.10.1
jsonify             0.5
jsonpatch           1.24
jsonpath-rw         1.4.0
jsonpointer         2.0
MarkupSafe          1.1.1
netaddr             0.8.0
numpy               1.16.3
openpyxl            2.6.2
pandas              0.24.2
pip                 19.1.1
ply                 3.11
prettytable         0.7.2
progressbar2        3.39.3
pyasn1              0.4.7
pycodestyle         2.5.0
pycryptodome        3.8.1
pycryptodomex       3.9.0
pysmi               0.3.4
pysnmp              4.4.12
PySocks             1.7.0
python-dateutil     2.8.0
python-utils        2.3.0
pytz                2019.1
PyYAML              5.3.1
recordtype          1.3
redfish             2.1.1
requests            2.21.0
rope                0.14.0
setuptools          41.0.1
six                 1.12.0
urllib3             1.24.3
urlparse2           1.1.1
Werkzeug            1.0.0
wheel               0.33.2
wincertstore        0.2
zipp                3.1.0
`

**Comment by bwoodsend** [comment]
Please fill in the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md). In particular we need a minimal test example and the stack trace. I've written a test but it's working fine.

```python
import yaml

output_file_yaml = "yaml.yaml"
formatted_json = dict(zip("abc", range(3)))

with open(output_file_yaml, 'w') as outf:
  yaml.safe_dump(formatted_json, outf, default_flow_style=False, sort_keys=False, width=float("inf"), allow_unicode=True)
```

**Comment by erickyi2006** [comment]
Thank you Brénainn

Here is the simple test example

```
import json
import yaml
import os
import sys
import traceback
import yaml

if __name__ == "__main__":
    output_file_yaml = "test.yaml"
    formatted_json = {
        "joe" : {
            "message": "hello 1"
        },
        "zorro" : {
            "message": "hello 2"
        },
        "fred" : {
            "message": "hello 3"
        }
    }
    with open(output_file_yaml, 'w') as outf:
        yaml.safe_dump(formatted_json, outf, default_flow_style=False, sort_keys=False, width=float("inf"), allow_unicode=True)


```

Test results on binary
```
c:\temp>testyaml.exe
Traceback (most recent call last):
  File "testyaml.py", line 22, in <module>
  File "site-packages\yaml\__init__.py", line 216, in safe_dump
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
[9812] Failed to execute script testyaml
```

I found the root cause. pyinstaller were pulling in an older yaml from the anaconda3\Lib\site-packages\yaml  (dated 15th Sep 2018)
I have the newer yaml (PyYAML v5.3.1 - see pip list above) at anaconda3\envs\ccm-automation3\Lib\site-packages\yaml (dated 2nd Sep 2020)

How do I configure pyinstaller to skip the older instance of yaml and to use the newer instance of yaml? Is this possible?

**Comment by erickyi2006** [comment]
Success!!! .Sharing my solution. This may not be the most ideal so please feel free to suggest.

1. Rename anaconda3\Lib\site-packages\yaml to something else
2. In spec file, specify these two fields in Analysis

- pathex - add the correct site-packages path
- hiddenimports - add 'yaml'

```
a = Analysis(['testyaml.py'],
             **pathex**=['', 'C:\\tools\\Continuum\\anaconda3\\envs\\ccm-automation3\\Lib\\site-packages'],
             binaries=[],
             datas=[],
             **hiddenimports**=['yaml'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

```

**Comment by htgoebel** [comment]
THis is not a PyInstaller issue, but caused by your environment.

**Comment by bwoodsend** [comment]
@erickyi2006 You shouldn't need to monkeypatch in `site-packages` like that. If you're finding that helps then you're misunderstanding how to use your environment manager. You need to be in the same environment when you build with PyInstaller that you run Python in normally. i.e. Your workflow if your using an environment manager like venv or conda should be:

Activate your environment:
```shell
conda activate ccm-automation3
```
Check python works normally. If this doesn't do exactly what you expect it to do then PyInstaller can only make it worse...
```
python testyaml.py 
```
Build (with the environment still active):
```shell
PyInstaller testyaml.py
```
If you're in anyway uncertain how `PATH` works then you should get into the habit of using `python -m PyInstaller testyaml.py` instead. This guarantees that you're not using a PyInstaller from the wrong environment.

Then deactivate your environment and test your application. Warning for conda users:  `conda deactivate` doesn't deactivate fully - you must create a new terminal. Testing in the same terminal will make a broken app that is missing binary dependencies appear to be working.

**Comment by erickyi2006** [comment]
thank you  Brénainn for the insight. 

```
c:\>where pyinstaller
C:\tools\Continuum\anaconda3\Scripts\pyinstaller.exe

```
I assumed (that was a total incorrect assumption) that pyinstaller will use my conda environment.  I would take advise of using the "new" habit
`pyhton -m PyInstaller testyaml.py`

Thank you again
