### ISSUE TITLE
Pyinstaller Django app

### ISSUE THREAD

**Issue by zlac116** [pyinstaller/pyinstaller#5140]
Hi Team,

I have created a Django app which connects to a Microsoft SQL server.

I've being trying to convert the app into an EXE file, which will launch into a users localhost, using pyinstaller.

I initially had a few import errors, which I resolved with a combination of importing some of the modules in the Django manage.py script and updating some of the hooks files.

Now I am experiencing an attribution error, when I attempt to run the EXE file in my localhost - details below. I'd appreciate any help that you can provide. Thanks

**Error:**

```
(pyinstaller) C:\Dev\>app.exe runserver localhost:8000
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):

...

    exec(bytecode, module.__dict__)
  File "statsmodels\tsa\statespace\tools.py", line 14, in <module>
  File "stringsource", line 105, in init statsmodels.tsa.statespace._kalman_filt
er
AttributeError: type object 'statsmodels.tsa.statespace._kalman_filter.array' ha
s no attribute '__reduce_cython__'

```
**Versions:**
OS: Windows
Python: Python 3.6.9
Pyinstaller: pyinstaller 4.0
Pyinstaller-hooks-contrib: 2020.7

**Libraries in Django App:**

altgraph==0.17
asgiref==3.2.7
bokeh==2.0.2
certifi==2018.4.16
cycler==0.10.0
Django==3.0.3
django-picklefield==2.1.1
djangorestframework==3.11.0
future==0.18.2
Jinja2==2.11.2
joblib
kiwisolver==1.2.0
MarkupSafe==1.1.1
matplotlib
mkl-fft
mkl-random
mkl-service
numpy==1.18.1
olefile==0.46
packaging==20.3
pandas==1.0.3
patsy==0.5.1
pefile==2019.4.18
Pillow==7.1.1
pyodbc==4.0.30
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2019.3
pywin32-ctypes==0.2.0
PyYAML==5.3.1
scikit-learn==0.23.0
scipy==1.4.1
seaborn==0.10.0
six==1.14.0
SQLAlchemy==1.3.18
sqlparse==0.3.1
statsmodels==0.11.0
threadpoolctl==2.0.0
tornado==6.0.4
typing-extensions
wincertstore==0.2

**Comment by bwoodsend** [comment]
Please provide a minimal example. Looking at your stacktrace the problem appears to originate from statsmodels and has nothing to do with django but it's impossible for use to test because we don't know what you're doing.

**Comment by zlac116** [comment]
Thanks. Will provide a minimal example and revert back.

**Comment by zlac116** [comment]
While working on a minimal example, I managed to resolve the statsmodels attribute error. I basically uninstalled and reinstalled the module in my virtual envt and added this hook-statsmodels.py file. I'd appreciate any suggestions on how this error can be resolved.

Many thanks

**hook-statsmodels.py**

```
hiddenimports=[
#all your previous hidden imports
'statsmodels.tsa.statespace._kalman_initialization',
'statsmodels.tsa.statespace._kalman_filter',
'statsmodels.tsa.statespace._kalman_smoother',
'statsmodels.tsa.statespace._representation',
'statsmodels.tsa.statespace._simulation_smoother',
'statsmodels.tsa.statespace._statespace',
'statsmodels.tsa.statespace._tools',
'statsmodels.tsa.statespace._filters._conventional',
'statsmodels.tsa.statespace._filters._inversions',
'statsmodels.tsa.statespace._filters._univariate',
'statsmodels.tsa.statespace._filters._univariate_diffuse',
'statsmodels.tsa.statespace._smoothers._alternative',
'statsmodels.tsa.statespace._smoothers._classical',
'statsmodels.tsa.statespace._smoothers._conventional',
'statsmodels.tsa.statespace._smoothers._univariate',
'statsmodels.tsa.statespace._smoothers._univariate_diffuse'
]
```


**The attribute error that I am experiencing now is per below. Matplotlib attribute error.**

```
  File "C:\Apps\app-dev\dist\app\django\core\management\commands\runserver.py", line 117
, in inner_run
    self.check(display_num_errors=True)
  File "django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_impo
rters.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "revenue_forecast_project\urls.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_impo
rters.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "revenue_app\views.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_impo
rters.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "revenue_app\apps.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_impo
rters.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "matplotlib\__init__.py", line 905, in <module>
  File "matplotlib\cbook\__init__.py", line 480, in _get_data_path
  File "matplotlib\__init__.py", line 239, in wrapper
  File "matplotlib\__init__.py", line 534, in get_data_path
  File "matplotlib\__init__.py", line 239, in wrapper
  File "matplotlib\__init__.py", line 561, in _get_data_path
  File "matplotlib\__init__.py", line 552, in get_candidate_paths
AttributeError: module 'matplotlib' has no attribute 'afm'
```

**hook-matplotlib.py file.**

```
from PyInstaller.utils.hooks import exec_statement

mpl_data_dir = exec_statement(
    "import matplotlib; print(matplotlib._get_data_path())")

datas = [
    (mpl_data_dir, "mpl-data"),
]

```

**Comment by bwoodsend** [comment]
The matplotlib issue is known to us. Currently you just have to downgrade to `matplotlib<3.3`. 

We have a utility for modules with large numbers of hidden imports. Your statsmodel hook could be written as:

```python
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules("statsmodel")
```

And I see you're using numpy and Conda. This is hopelessly incompatible with PyInstaller. Any PyInstaller app that contains Conda's numpy is broken in nastily subtle ways that you won't detect by just running it on your own computer. Please use a vanilla Python with PyInstaller.

**Comment by zlac116** [comment]
Thanks for highlighting this, I will use a matplotlib version < 3.3 and use this format for importing statsmodels via the hooks file.
Wrt to numpy, would you suggest using pip to install numpy, instead of conda? I will recreate my virtual envt and do this instead.
FYI - I'm still working on getting a minimal example.
thanks again!

**Comment by bwoodsend** [comment]
> would you suggest using pip to install numpy, instead of conda?

That would get you past the mine field of hidden binary dependencies for numpy but might be incompatible with Conda's scipy or sklearn. In which case you should also use pip for any modules than depend  on numpy.

**Comment by bwoodsend** [comment]
Also if you could PR your hook for statsmodels to [our hooks repo](https://github.com/pyinstaller/pyinstaller-hooks-contrib/pulls) we can include it in PyInstaller which would fix it permanently for everyone.

**Comment by zlac116** [comment]
I've recreated my python environment using pip for all modules.
Sure, I'll add the statsmodels hook to the hooks repo.

**Comment by bwoodsend** [comment]
Does that mean everything is working...?

**Comment by zlac116** [comment]
Almost everything, all module import errors seem to be resolved now - thanks.
Just working through errors relating to importing certain config files and modules within the Django project. Apologies for the qu as this library is new to me but is the best practice to specify these in the app.spec file?
Thanks

**Comment by bwoodsend** [comment]
I certainly prefer using the spec to the command line. But I've never used Django so I can't be of much help.

**Comment by zlac116** [comment]
No worries. Just an fyi - the statsmodels hook file, in the format that you mentioned below, doesn't seem to work compared with the older format that I showed you earlier in this thread.

```
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules("statsmodel")
```

Also, I am at now at a stage where all external dependencies are being imported - thanks! However, the Django app is comprised with a number of different modules which interact with each other so when I run my EXE file I am now getting a **ModuleNotFoundError** relating to the mysite.urls module (urls in the below image), which is part of my Django app. Note that Pyinstaller is run over the manage.py file, which fires up the Django app. 

Any idea how I can import this, even though it is part of the app? Thanks

ModuleNotFoundError: No module named 'mysite.urls'

**Django structure**

![image](https://user-images.githubusercontent.com/66669459/92620311-67f26880-f2ba-11ea-88d9-e7f8abb410f4.png)

**Error**

```
(pyinstaller) C:\Dev\MyPythonScripts\Scripts\Python\Apps\dist\mysite>revenue_app.exe runserver localhost:8000
Watching for file changes with StatReloader
Performing system checks...

c:\dev\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py
:493: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and wil
l be removed in 3.3.
  exec(bytecode, module.__dict__)
C:\Dev\MyPythonScripts\Scripts\Python\Apps\
dist\mysite\dbconnect_odbc.py:10: YAMLLoadWarning: calling yaml.load() with
out Loader=... is deprecated, as the default Loader is unsafe. Please read https
://msg.pyyaml.org/load for full details.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:Dev\MyPythonScripts\Scripts\Python\Apps\dist\mysite\django\core\management\commands\runserver.py", line 117
, in inner_run
    self.check(display_num_errors=True)
  File "django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\dev\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_impo
rters.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "revenue_forecast_project\urls.py", line 24, in <module>
  File "django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mysite.urls'


```

**Comment by zlac116** [comment]
**UPDATE**
I added `import mysite.urls` to the manage.py script. This seemed to resolve this error. Thanks

**Comment by bwoodsend** [comment]
OK. Just out of interest, is there anything in [your explicit list of hidden imports](https://github.com/pyinstaller/pyinstaller/issues/5140#issuecomment-688673182) that `collect_submodules("statsmodels")` fails to include? It's unusual for that not to fix it and I'd like to track down the cause.

**Comment by soufisouf** [comment]
Im using django 3. Python 3.8 and i Heard that pyinstaller does not work with 3.8 so i undergrade it to 3.5 since its enough for my programs. I use also pymongo and not sql as database. Packages used : 

Plotly
Numpy
Pandas
Channels_redis
Django-channels (for websockets)
Pymongo

Thats all for the moment. 

I want to convert it to exe and I always had  an error saying settings.pyc not found. So i ran a minimalistic example with juste a single template and sqlite.. The very basic project on django, but it does not work neither. 

I really need a recipe to work with pyinstaller. How to add hooks and where ? Steps to follow... Im beginner on that and there are very few tutorials on the net..

You will be very kind if you do that for me.

**Comment by zlac116** [comment]
@bwoodsend, thanks - all of my explicit list of hidden imports are related to django imports. Will send a sample of my spec file.

**Comment by bwoodsend** [comment]
@soufisouf I'm sorry but this is an issue board - not a support forum. We're far too short-staffed to give personalised tutorials to every passing user. And, to be honest, it sounds like you're out of your depth anyway. 

We are just starting writing some a complete guide to using PyInstaller. If you wait a few months hopefully you can use that instead.

**Comment by zlac116** [comment]
list of hidden import are below. thanks

`hiddenimports=['django.contrib.admin.apps', 'django.contrib.auth.apps', 'django.contrib.contenttypes.apps', 'django.contrib.sessions.apps', 'django.contrib.messages.apps', 'django.contrib.staticfiles.apps', 'django.contrib.messages.middleware', 'django.contrib.sessions.middleware', 'django.contrib.sessions.serializers', 'django.template.loaders', 'django.contrib.auth.context_processors', 'django.contrib.messages.context_processors',],`

**Comment by zlac116** [comment]
@bwoodsend - finally managed to get the entire app to work. Thanks again for your help and let me know if there’s anything else that I can provide to assist with dev.
