### ISSUE TITLE
Django 3.1.1 based apps fail to package correctly - Failed to execute script manage

### ISSUE THREAD

**Issue by seekersmash** [pyinstaller/pyinstaller#5145]
## Context information (for bug reports)
Performing the same steps using Django 2.2 work as expected

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: 3.8
* Platform: Windows-10-10.0.19041-SP0
* Did you also try this on another platform? Does it work there?
Yes - Ubuntu via WSL produced a stack trace building the package with pyinstaller.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
The following in a Windows batch file or executed at a command line will exhibit the issue.
```
py -3.8 -m venv py38_env
CALL .\py38_env\Scripts\activate.bat
pip install django==3.1.1
pip install pyinstaller
django-admin startproject djpkg
pyinstaller --name=djpkg djpkg/manage.py
CD dist/djpkg
djpkg.exe```

### Stacktrace / full error message

```
(py38_env) C:\repro\dist\djpkg>djpkg.exe
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
  File "manage.py", line 18, in main
  File "django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "django\conf\__init__.py", line 83, in __getattr__
    self._setup(name)
  File "django\conf\__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "django\conf\__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\repro\py38_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "djpkg\settings.py", line 16, in <module>
  File "pathlib.py", line 1177, in resolve
  File "pathlib.py", line 200, in resolve
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\repro\\dist\\djpkg\\djpkg\\settings.pyc'
[15148] Failed to execute script manage
```

**Comment by adigunsherif** [comment]
return _old_restart_with_reloader(*args)
  File "django\utils\autoreload.py", line 242, in restart_with_reloader
  File "django\utils\autoreload.py", line 229, in get_child_arguments
RuntimeError: Script runserver does not exist.
[16844] Failed to execute script manage

**Comment by AndyZdbuke** [comment]
> return _old_restart_with_reloader(*args)
> File "django\utils\autoreload.py", line 242, in restart_with_reloader
> File "django\utils\autoreload.py", line 229, in get_child_arguments
> RuntimeError: Script runserver does not exist.
> [16844] Failed to execute script manage

Did you got any solution here?

**Comment by adigunsherif** [comment]
No, I didn't. I eventually gave up on the project to later.

**Comment by SunnyBingoMe** [comment]
For "RuntimeError: Script runserver does not exist", use:
`manage runserver --noreload`
Ref: [#5294](https://github.com/pyinstaller/pyinstaller/issues/5294#issuecomment-741640137)
