### ISSUE TITLE
Add hook for flask_restx missing template files.

### ISSUE THREAD

**Issue by mrf345** [pyinstaller/pyinstaller#5162]
**Is your feature request related to a problem? Please describe.**
After packaging a `flask` app that utilizes `flask-restx` extension, I'm getting an error that indicates the package template files are missing.

**Describe the solution you'd like**
Add a hook file to include the extension files.

**Describe alternatives you've considered**
Running the hook file locally.

**Additional context**
```log
Traceback (most recent call last):
  File "flask/app.py", line 2292, in wsgi_app
  File "flask/app.py", line 1815, in full_dispatch_request
  File "flask_restx/api.py", line 639, in error_router
  File "flask/app.py", line 1718, in handle_user_exception
  File "flask/_compat.py", line 35, in reraise
  File "flask/app.py", line 1813, in full_dispatch_request
  File "flask/app.py", line 1799, in dispatch_request
  File "flask_restx/api.py", line 426, in render_doc
  File "flask_restx/apidoc.py", line 38, in ui_for
  File "flask/templating.py", line 134, in render_template
  File "jinja2/environment.py", line 869, in get_or_select_template
  File "jinja2/environment.py", line 830, in get_template
  File "jinja2/environment.py", line 804, in _load_template
  File "jinja2/loaders.py", line 113, in load
  File "flask/templating.py", line 58, in get_source
  File "flask/templating.py", line 86, in _get_source_fast
jinja2.exceptions.TemplateNotFound: swagger-ui.html
```

**Comment by mrf345** [comment]
Community hooks seem to have been moved to a different repo.
