### ISSUE TITLE
Not able to create mac executable if we have used PyautoGUI in python script

### ISSUE THREAD

**Issue by Shraddha-gami-source** [pyinstaller/pyinstaller#5178]
I am facing issue in pyinstaller if I try to make executable file from mac when I use pyautogui library in Python script(Working fine on windows).
After debugging I got to know that issue is when I use pyautogui and pyinstaller together.
So, I've tried this simple program which has just import of pyautogui
demo.py
```
import pyautogui as pg
if __name__ == "__main__":
    `print("Hello,` WOrld!")
```

It was giving me below error if I just type pyinstaller demo.py --onefile
exit;
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth__tkinter.py", line 20, in <module>
FileNotFoundError: Tcl data directory "/var/folders/83/vlr93lcs4bg1r6ytzy1vvjy40000gn/T/_MEIyqvIJz/tcl" not found.
[57142] Failed to execute script pyi_rth__tkinter

So, I've tried this
pyinstaller --onefile --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' demo.py

below is the stacktrace of error:

exit;
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes/__init__.py", line 348, in __init__
OSError: dlopen(/var/folders/83/vlr93lcs4bg1r6ytzy1vvjy40000gn/T/_MEIjmFz1e/Foundation, 6): no suitable image found.  Did find:
	/var/folders/83/vlr93lcs4bg1r6ytzy1vvjy40000gn/T/_MEIjmFz1e/Foundation: not a file
	/private/var/folders/83/vlr93lcs4bg1r6ytzy1vvjy40000gn/T/_MEIjmFz1e/Foundation: not a file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demo.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/admin/Documents/django_infoware/venv_demo/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pyautogui/__init__.py", line 241, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/admin/Documents/django_infoware/venv_demo/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "mouseinfo/__init__.py", line 100, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/admin/Documents/django_infoware/venv_demo/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "rubicon/objc/__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/admin/Documents/django_infoware/venv_demo/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "rubicon/objc/runtime.py", line 81, in <module>
  File "rubicon/objc/runtime.py", line 58, in load_library
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 146, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll '/var/folders/83/vlr93lcs4bg1r6ytzy1vvjy40000gn/T/_MEIjmFz1e/Foundation'. Most probably this dynlib/dll was not found when the application was frozen.
[57474] Failed to execute script demo

[Process completed]

It seems like there is some windows dependency when I use pyautoGUI. Even I am on mac

**Comment by Shraddha-gami-source** [comment]
@bwoodsend Why their is dependency of windows library on mac when I use pyinstaller?

**Comment by bwoodsend** [comment]
Ahh, fair point. Could you fill out the issue template properly.

**Comment by rokm** [comment]
There is no dependency on Windows library - `Foundation` is a system library on OSX, found in `/System/Library/Frameworks/Foundation.framework/Foundation`.

However, it is not found due to a subtle bug in the pyinstaller's library loading, which prevents a system library from being found if a directory with a same name exists in the program's directory (and `Foundation` directory ends up created due to one of pyautoGUI's dependencies, probably `pyobjc` or `rubicon`).

I'll shorty prepare a fix for this.

**Comment by rokm** [comment]
Can you try installing pyinstaller via `pip install https://github.com/rokm/pyinstaller/archive/fix-dir-shadow-syslib.zip`, and see if that fixes the missing `Framework` error?

**Comment by Shraddha-gami-source** [comment]
```
import pyautogui as pg
if __name__ == "__main__":
    `print("Hello,` WOrld!")
```

This is fixed.

But the place where I am actually using pyautogui still causing error.
Below is the stacktrace for that
dist/broadcast ; exit;
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_win32comgenpy.py", line 61, in <module>
ModuleNotFoundError: No module named 'win32com.gen_py'
[9585] Failed to execute script pyi_rth_win32comgenpy

**Comment by Shraddha-gami-source** [comment]
Not sure what caused this issue pyi_rth_win32comgenpy
But I have moved my scripts to another place and your fix worked. Thanks @rokm!!
