### ISSUE TITLE
Jetson nano - include opencv when compiled from source

### ISSUE THREAD

**Issue by dhgokul** [pyinstaller/pyinstaller#5191]
@krunal704  I am also facing same issue. after include paths argument 

Platform: Jetson Nano running on Ubuntu 18.04 - jetson pack (4.4)
>>> import cv2
>>> cv2.__version__
'4.3.0'
>>> print(cv2.__file__)
/root/opencv-4.3.0/release/lib/python3/cv2.cpython-36m-aarch64-linux-gnu.so

**cmd:**
pyinstaller --onefile sample.py --paths "/root/opencv-4.3.0/release/lib/python3/cv2.cpython-36m-aarch64-linux-gnu.so"

**Error :**
Traceback (most recent call last):
  File "tt.py", line 12, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "cv2/__init__.py", line 96, in <module>
  File "cv2/__init__.py", line 58, in bootstrap
  File "cv2/__init__.py", line 56, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.

_Originally posted by @dhgokul in https://github.com/pyinstaller/pyinstaller/issues/4564#issuecomment-696063865_

**Comment by krunal704** [comment]
Don't include file name in path argument
Include only folder path like this:
`pyinstaller --onefile sample.py --paths "/root/opencv-4.3.0/release/lib/python3"`

**Comment by dhgokul** [comment]
Thanks @krunal704  opencv issue is fixed. But when execute tensorRT in jetson nano board . I got below issue

[TensorRT] ERROR: /home/jenkins/workspace/TensorRT/helpers/rel-7.1/L1_Nightly_Internal/build/source/rtSafe/resources.h (460) - Cuda Error in loadKernel: 3 (initialization error)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "utils/yolo_with_plugins.py", line 253, in __init__
    self.context = self.engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sample.py", line 323, in <module>
    main()
  File "sample.py", line 310, in main
    trt_yolo = TrtYOLO(args.model, (h, w), args.category_num)
  File "utils/yolo_with_plugins.py", line 259, in __init__
    raise RuntimeError('fail to allocate CUDA resources') from e
RuntimeError: fail to allocate CUDA resources
[17625] Failed to execute script trt_yolo_car
Exception ignored in: <bound method TrtYOLO.__del__ of <utils.yolo_with_plugins.TrtYOLO object at 0x7f600ffb38>>
Traceback (most recent call last):
  File "utils/yolo_with_plugins.py", line 266, in __del__
    del self.outputs
AttributeError: outputs

**Comment by andy-landy** [comment]
Any progress with a solution? I've got the same problem

**Comment by tushardhadiwal** [comment]
@dhgokul @andy-landy @krunal704 Any Idea on how to get past the Cuda Error in loadKernel: 3 (initialization error)?

**Comment by andy-landy** [comment]
Still no idea: https://stackoverflow.com/questions/64608796/tensorrt-pyinstaller-on-nvidia-jetson-nano-deserialize-engine-causes-cuda-err
