### ISSUE TITLE
binCache interferes with concurrent runs of pyinstaller

### ISSUE THREAD

**Issue by Siron777** [pyinstaller/pyinstaller#5195]
Hi,

I am using pyinstaller to build concurrently several executables, and there are some errors due to interference in the binCache folder. I guess for example that one build clean the folder while another build is using it. If I do not do concurrent call to pyinstaller, everything is working fine.

I understand the idea of speeding up the build with the binCache, but this kind of interferences was not expected for me and looks like a limitation. 

If you confirm that limitation, a possible solution I see could be to provide an argument to discard totally the binCache, or to configure its location.

As a workaround for my build, I monkey path the function PyInstaller.configure._get_pyinst_cache_dir to relocate the binCache folder at a different location per job.

Simon

## Context information (for bug reports)
* pyinstaller 4.0
* Version of Python: 3.8.5
* Platform: Windows 10

**Comment by bwoodsend** [comment]
You can override PyInstaller's temp directory with the `PYINSTALLER_CONFIG_DIR` environment variable. Assuming Windows:
```shell
set PYINSTALLER_CONFIG_DIR=.
PyInstaller your_code.py
```
puts the binCache at `./pyinstaller/bincache00_py38_64bit/` (obviously with different version numbers).

**Comment by sancelot** [comment]
I suppose I have had the same problem in my parallel jobs in jenkins.
for unknown reasons, it stopped working reporting :
```
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python38\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "Main.spec", line 59, in <module>
    coll = COLLECT(exe,
  File "c:\python38\lib\site-packages\PyInstaller\building\api.py", line 699, in __init__
    self.__postinit__()
  File "c:\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\python38\lib\site-packages\PyInstaller\building\api.py", line 733, in assemble
    fnm = checkCache(fnm, strip=self.strip_binaries,
  File "c:\python38\lib\site-packages\PyInstaller\building\utils.py", line 190, in checkCache
    cache_index = load_py_data_struct(cacheindexfn)
  File "c:\python38\lib\site-packages\PyInstaller\utils\misc.py", line 227, in load_py_data_struct
    return eval(f.read())
  File "<string>", line 180
    )}
    ^
SyntaxError: unmatched ')'
```

I had to investigate where was the problem and found the problem coming from this file : 
C:\Windows\system32\config\systemprofile\AppData\Roaming\pyinstaller\bincache00_py38_64bit\index.dat

**Comment by Siron777** [comment]
Thank you very much for that precision @bwoodsend . It is indeed a lot cleaner. 
I think it would still be better to make it more explicit through a configuration parameter instead of an environment variable.  And to explain the limitation with concurrent run of pyinstaller. But beside that, if you do not share my opinion on the subject, I can understand if this issue is closed.

**Comment by bwoodsend** [comment]
@Siron777 I don't suppose you're launching all your concurrent builds from the same working directory? In which case `PYINSTALLER_CONFIG_DIR` would need to be dependent on the build so as to be unique. 

And, to be honest, yes. This is a bit too niche to get much priority. If I want concurrency I use CI/CD...

**Comment by Siron777** [comment]
@bwoodsend, the jobs are part of a cmake build and the concurrency is orchestrated by ninja. Actually two of our targets are triggering pyinstallers.  For my case the configuration of PYINSTALLER_CONFIG_DIR did solve the issue, and I configure it indeed with different target folder for each target.
Concerning CI/CD for concurrency, this is exactly the circumstance of the occurrence of @sancelot.

**Comment by bwoodsend** [comment]
Oops. I completely failed to notice I was talking to two different people. That explains a lot. In which case @sancelot my [above question](https://github.com/pyinstaller/pyinstaller/issues/5195#issuecomment-699940139) is meant for you then.

**Comment by sancelot** [comment]
it is now working , that was only a pb to correctly set the variable inthe jenkins pipeline :  
```
powershell(returnStdout:false,
                            encoding:'UTF-8',
                            script:  '''
                                    \$env:PYINSTALLER_CONFIGDIR = '.'
                                    pyinstaller Main.spec --noconfirm
                                    ''')
```

**Comment by mercibac** [comment]
> ```shell
> set PYINSTALLER_CONFIG_DIR=.
> ```

Thank you very much. I had the same problem. But now the compilation is done successfully.

**Comment by maburlik** [comment]
Thank you, had the same issue and this resolved it.
