### ISSUE TITLE
Pyinstaller wont package with pdf2image

### ISSUE THREAD

**Issue by amazer07** [pyinstaller/pyinstaller#5209]
I can run my code perfectly in the editor but when i package it and run the exe file, i get the following error: 

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "main.py", line 40, in pdfConvert
  File "site-packages\pdf2image\pdf2image.py", line 94, in convert_from_path
  File "site-packages\pdf2image\pdf2image.py", line 445, in pdfinfo_from_path
pdf2image.exceptions.PDFPageCountError: Unable to get page count.

Any insight on this would be appreciated.

**Comment by rokm** [comment]
Can you provide a minimum example to reproduce the error? And some details about your environment - OS, python version, `pdf2image` version, how `poppler` was installed?

**Comment by Legorooj** [comment]
Stale.
