### ISSUE TITLE
How Can I Fix "The 'google-api-python-client' distribution was not found and is required by the application"

### ISSUE THREAD

**Issue by floating-in-space** [pyinstaller/pyinstaller#5215]
I get an error while trying to package an app using tensorflow: `pkg_resources.DistributionNotFound: The 'google-api-python-client' distribution was not found and is required by the application`

I ran `pyinstaller {filename}.py` which had `import tensorflow`

**Comment by rokm** [comment]
Looks like `google-api-python-client` is being pulled in because it's imported in some part of `tensorflow` (which you may or may not be actually using).

If you're not using `google-api-python-client`, try removing it from your environment (or build your program using a clean virtual environment with only required packages installed). Or try downgrading it to 1.8.0, as per googleapis/google-api-python-client#876.

**Comment by bwoodsend** [comment]
`pkg_resources.DistributionNotFound: name` in PyInstaller translates to *need to use `datas=copy_metadata("name")`". See [this nabble thread](http://pyinstaller.47505.x6.nabble.com/PyInstaller-not-working-with-module-pycountry-td3064.html) which does exactly the same thing for `pycountry`.

**Comment by floating-in-space** [comment]
> `pkg_resources.DistributionNotFound: name` in PyInstaller translates to _you need to use `datas=copy_metadata("name")`_. See [this nabble thread](http://pyinstaller.47505.x6.nabble.com/PyInstaller-not-working-with-module-pycountry-td3064.html) which does exactly the same thing for `pycountry`.

it works, but now i get `Traceback (most recent call last):
  File "resonance.py", line 6, in <module>
    from magenta.models.performance_rnn import performance_sequence_generator
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "magenta/__init__.py", line 25, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "magenta/pipelines/drum_pipelines.py", line 19, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "note_seq/__init__.py", line 20, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "note_seq/audio_io.py", line 21, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "librosa/__init__.py", line 14, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "librosa/decompose.py", line 19, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "sklearn/decomposition/__init__.py", line 17, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "sklearn/decomposition/dict_learning.py", line 5, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "sklearn/decomposition/_dict_learning.py", line 21, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "sklearn/linear_model/__init__.py", line 11, in <module>
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "sklearn/linear_model/_least_angle.py", line 23, in <module>
  File "sklearn/utils/arrayfuncs.pyx", line 1, in init sklearn.utils.arrayfuncs
ModuleNotFoundError: No module named 'sklearn.utils._cython_blas'
[16010] Failed to execute script resonance`

**Comment by rokm** [comment]
Add `sklearn.utils._cython_blas` to `hiddenimports` in your spec file. (Or use `--hidden-import sklearn.utils._cython_blas` if you're building from source).

**Comment by floating-in-space** [comment]
It took some time to do that but finally it works! Thank you both!
