### ISSUE TITLE
Installation Error (exit status 2)

### ISSUE THREAD

**Issue by gbe3hunna** [pyinstaller/pyinstaller#5234]
Hi there,

- Running over Windows10 in Python3.8.5
- Got `wheel` and `setuptools` updated in last version
- PIP version `pip 20.2.3`
- After installing Pyinstaller via pip I got the next exception (I obviously have everything on path):

`pip install pyinstaller` or `pip3 install pyinstaller` or `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`

```
Collecting pyinstaller
  Using cached pyinstaller-4.0.tar.gz (3.5 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 2:
   command: 'c:\users\x\appdata\local\programs\python\python38\python.exe' 'c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\x\AppData\Local\Temp\pip-build-env-bld3o_ja\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (22 lines):
  Collecting setuptools>=40.8.0
    Using cached setuptools-50.3.0-py3-none-any.whl (785 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Installing collected packages: setuptools, wheel
  ERROR: Exception:
  Traceback (most recent call last):
    File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
      status = self.run(options, args)
    File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py", line 397, in run
      installed = install_given_reqs(
    File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\req\__init__.py", line 82, in install_given_reqs
      requirement.install(
    File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\req\req_install.py", line 779, in install
      scheme = get_scheme(
    File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\locations.py", line 185, in get_scheme
      scheme = distutils_scheme(
    File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\locations.py", line 118, in distutils_scheme
      assert not (home and prefix), "home={} prefix={}".format(home, prefix)
  AssertionError: home=C:\Users\x\AppData\Local\Temp\pip-target-st4fstvd prefix=C:\Users\x\AppData\Local\Temp\pip-build-env-bld3o_ja\overlay
  ----------------------------------------
ERROR: Command errored out with exit status 2: 'c:\users\x\appdata\local\programs\python\python38\python.exe' 'c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\x\AppData\Local\Temp\pip-build-env-bld3o_ja\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by Legorooj** [comment]
This isn't a problem with PyInstaller. Please contact the developers of pip, setuptools, or wheel.
