### ISSUE TITLE
The crash app at start-up

### ISSUE THREAD

**Issue by joelvis-maker** [pyinstaller/pyinstaller#5243]
I use kivy 1.11.1 with python 3.7.6 windows 10 and Pyinstall 4.0. My app works perfectly, and when I pyinstall pyinstall everything works properly. But when I launch the file, exe the crash application at startup.

My file is as follows:

test : 
  main.py
  music
  images_bg
  levels_images
  other_img
  
And I want to copy these folders in the dist

I have files that are not stored in the dist file.

main.spec:

`# -*- mode: python ; coding: utf-8 -*-
from kivy.tools.packaging.pyinstaller_hooks import install_hooks
install_hooks(globals())
from kivy_deps import sdl2, glew
import kivy.core.audio 
import kivy.core.image 

block_cipher = None

a = Analysis(['main.py'],
             pathex=['C:\\Users\\acer\\Downloads\\test'],
             binaries=[],
             datas=[('C:\\Users\\acer\\Downloads\\test\\images_bg', '.'), 
			('C:\\Users\\acer\\Downloads\\test\\levels_images', '.'),
			('C:\\Users\\acer\\Downloads\\test\\music', '.'),
			('C:\\Users\\acer\\Downloads\\test\\other_img', '.'),
			('C:\\Users\\acer\\Downloads\\test\\Progress_bar_img', '.'),
			('C:\\Users\\acer\\Downloads\\test\\Roboto', '.'),
			('C:\\Users\\acer\\Downloads\\test\\Texture', '.')
			],
             hiddenimports=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False , icon='test.ico')
coll = COLLECT(exe, Tree('C:\\Users\\acer\\Downloads\\test\\'),
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
	       *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
               upx=True,
               upx_exclude=[],
               name='main')
`
I get this error:

`[WARNING] [Image       ] Unable to load image <C:\Users\acer\Downloads\test\dist\test\images_bg\help_bg.jpg>
 Traceback (most recent call last):
   File "kivy\lang\builder.py", line 921, in _build_canvas
   File "kivy\graphics\instructions.pyx", line 366, in kivy.graphics.instructions.VertexInstruction.source.__set__
   File "kivy\graphics\context_instructions.pyx", line 430, in kivy.graphics.context_instructions.BindTexture.source.__set__
   File "kivy\core\image\__init__.py", line 561, in __init__
   File "kivy\core\image\__init__.py", line 756, in _set_filename
   File "kivy\core\image\__init__.py", line 460, in load
   File "kivy\core\image\__init__.py", line 223, in __init__
     self.deactivate_module(name, win)
   File "kivy\core\image\img_sdl2.py", line 47, in load
 Exception: SDL2: Unable to load image

 During handling of the above exception, another exception occurred:
Traceback (most recent call last):
   File "main.py", line 1623, in <module>
   File "kivy\uix\relativelayout.py", line 265, in __init__
   File "kivy\uix\floatlayout.py", line 65, in __init__
   File "kivy\uix\layout.py", line 76, in __init__
   File "kivy\uix\widget.py", line 361, in __init__
   File "kivy\uix\widget.py", line 469, in apply_class_lang_rules
   File "kivy\lang\builder.py", line 538, in apply
   File "kivy\lang\builder.py", line 659, in _apply_rule
   File "kivy\lang\builder.py", line 592, in _apply_rule
   File "kivy\lang\builder.py", line 926, in _build_canvas
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 12:
 ...
      10:                pos: self.pos
      11:                size: self.size
 >>   12:                source: "images_bg/help_bg.jpg"
      13:        orientation: 'vertical'
      14:        padding: 50
 ...
 Exception: SDL2: Unable to load image
   File "kivy\lang\builder.py", line 921, in _build_canvas
`

**Comment by Legorooj** [comment]
Please fill out our issue template in a new issue, and follow all the steps there, or we can't help.
