### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'metpy' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by mishrakeshav** [pyinstaller/pyinstaller#5247]
This is the description of the system and OS I am using 

- Output of pyinstaller --version: 4
- Version of Python: 3.8.5
- Platform: Ubuntu 20.04.1 LTS

A minimal example of my application 

```
import metpy 
print('Hello world')
```

This the output I am getting when I run the executable file

```
/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py:493: MatplotlibDeprecationWarning: 
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Traceback (most recent call last):
  File "metpy/_version.py", line 14, in get_version
ModuleNotFoundError: No module named 'setuptools_scm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "metpy/__init__.py", line 36, in <module>
  File "metpy/_version.py", line 19, in get_version
  File "pkg_resources/__init__.py", line 481, in get_distribution
  File "pkg_resources/__init__.py", line 357, in get_provider
  File "pkg_resources/__init__.py", line 900, in require
  File "pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'metpy' distribution was not found and is required by the application

```
Someone already got the same issue but with a different package. So tried the solution mentioned in the link below: 
[https://github.com/pyinstaller/pyinstaller/issues/4809](https://github.com/pyinstaller/pyinstaller/issues/4809)

After making the changes suggest this is the output I am getting.

```
/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py:493: MatplotlibDeprecationWarning: 
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "/tmp/embedded.li33p3zx.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "app/views/StartMenuWindow.py", line 9, in <module>
  File "/tmp/embedded.li33p3zx.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "app/views/PortSelectionWindow.py", line 10, in <module>
  File "/tmp/embedded.li33p3zx.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "app/views/ParameterInputWindow.py", line 11, in <module>
  File "/tmp/embedded.li33p3zx.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "app/views/Dashboard.py", line 11, in <module>
  File "/tmp/embedded.li33p3zx.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "metpy/plots/__init__.py", line 11, in <module>
  File "/tmp/embedded.li33p3zx.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/newenv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "metpy/plots/ctables.py", line 287, in <module>
  File "metpy/plots/ctables.py", line 148, in scan_resource
  File "pkg_resources/__init__.py", line 1162, in resource_listdir
  File "pkg_resources/__init__.py", line 1441, in resource_listdir
  File "pkg_resources/__init__.py", line 1482, in _listdir
NotImplementedError: Can't perform this operation for unregistered loader type
[30277] Failed to execute script main
```
This is the first time I am using pyinstaller so someone please help me out.

**Comment by rokm** [comment]
Can you post the output of `pip list` for your environment?

**Comment by mishrakeshav** [comment]
> Can you post the output of `pip list` for your environment?

Here is the output of pip list of my env

```
Package                   Version  
------------------------- ---------
altgraph                  0.17     
appdirs                   1.4.4    
branca                    0.4.1    
certifi                   2020.6.20
chardet                   3.0.4    
cycler                    0.10.0   
folium                    0.11.0   
idna                      2.10     
ipython-genutils          0.2.0    
Jinja2                    2.11.2   
kiwisolver                1.2.0    
MarkupSafe                1.1.1    
matplotlib                3.2.2    
MetPy                     0.12.2   
numpy                     1.19.2   
packaging                 20.4     
pandas                    1.1.2    
Pillow                    7.2.0    
Pint                      0.16.1   
pip                       20.0.2   
pkg-resources             0.0.0    
pooch                     1.2.0    
pyinstaller               4.0      
pyinstaller-hooks-contrib 2020.8   
pyparsing                 2.4.7    
pyserial                  3.4      
pyside-material           1.16     
PySide2                   5.15.1   
python-dateutil           2.8.1    
pytz                      2020.1   
requests                  2.24.0   
scipy                     1.5.2    
setuptools                44.0.0   
setuptools-scm            4.1.2    
shiboken2                 5.15.1   
six                       1.15.0   
tephi                     0.2.4    
traitlets                 5.0.4    
urllib3                   1.25.10  
xarray                    0.16.1
```

**Comment by rokm** [comment]
@bwoodsend, that was the original issue they were facing. 

But after working around that with `collect_all()` in a custom hook (`copy_metadata()` would have also done the trick), there's another issue: `metpy.plots.ctables` is using `pkg_resources.resource_listdir` to list the data files. And within `pkg_resources.resource_listdir()`, `pkg_resources.get_provider()` raises `NotImplementedError: Can't perform this operation for unregistered loader type`. It seems to get the module (`<module 'metpy' from '/home/rok/tmp/pyi-metpy2/dist/program/metpy/__init__.pyc'>`) and the loader (`<pyimod03_importers.FrozenImporter object at 0x7f752f1182b0>˙) but then `_find_adapter()` call errors out.

**Comment by bwoodsend** [comment]
Oops sorry. In that case, this boils down to #4881 again which has been pretty neglected. To be honest I think it would be easier if `metpy` just switched to using `__file__` to get its data files. The whole `pkg_resources` data getting palaver was only to support packages in zipped egg format which I have never seen anyone use. Certainly `metpy` don't - they're just plain whls).

**Comment by rokm** [comment]
@mishrakeshav to work around this issue for now, you could patch the `metpy` in your venv. Open `${venv_prefix}/lib/python3.8/site-packages/metpy/plots/ctables.py`, and change the block at the end of the file from:

```python
registry = ColortableRegistry()
registry.scan_resource('metpy.plots', 'colortable_files')
registry.scan_dir(os.path.curdir)
```

to

```python
import sys

registry = ColortableRegistry()

if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    bundle_dir = getattr(sys, '_MEIPASS')
    data_dir = os.path.abspath(os.path.join(bundle_dir, 'metpy', 'plots', 'colortable_files'))
    registry.scan_dir(data_dir)
else:
    registry.scan_resource('metpy.plots', 'colortable_files')

registry.scan_dir(os.path.curdir)
```

**Comment by mishrakeshav** [comment]
@rokm Thank you. It worked after making the changes in the ctables.py file and also changing the *.spec file as suggested by [Link](https://groups.google.com/g/pyinstaller/c/OYhJdeZ9010/m/vLhYAWUzAQAJ)

I got this as output after running the executables 

```
/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py:493: MatplotlibDeprecationWarning: 
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "/tmp/embedded.62wg7yk7.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "app/views/StartMenuWindow.py", line 9, in <module>
  File "/tmp/embedded.62wg7yk7.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "app/views/PortSelectionWindow.py", line 10, in <module>
  File "/tmp/embedded.62wg7yk7.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "app/views/ParameterInputWindow.py", line 11, in <module>
  File "/tmp/embedded.62wg7yk7.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "app/views/Dashboard.py", line 10, in <module>
  File "/tmp/embedded.62wg7yk7.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "metpy/calc/__init__.py", line 7, in <module>
  File "/tmp/embedded.62wg7yk7.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "metpy/calc/cross_sections.py", line 14, in <module>
  File "/tmp/embedded.62wg7yk7.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "metpy/calc/tools.py", line 14, in <module>
  File "/tmp/embedded.62wg7yk7.zip/shibokensupport/__feature__.py", line 146, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "metpy/cbook.py", line 28, in <module>
  File "pooch/core.py", line 565, in load_registry
FileNotFoundError: [Errno 2] No such file or directory: '/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/src/dist/main/metpy/static-data-manifest.txt'
[76904] Failed to execute script main
```

I downloaded the static-data-manifest.txt file from metpy and placed it in the directory and included it in data by  changing the main.spec file as shown below. Please let me know if there is a better way to do this. 
```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import copy_metadata
block_cipher = None


added_files = [
    ( 'static-data-manifest.txt', 'metpy' ),
    
]
a = Analysis(['main.py'],
             pathex=['/home/keshav/Desktop/application/Radiosonde-Ground-Station-Software/src'],
             binaries=[],
             datas=copy_metadata('metpy') + added_files,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='main')

```

**Comment by rokm** [comment]
I think you might be better off using `collect_all()` like you were in the beginning than just `copy_metadata()`. You could do it in an external hook:
```python
from PyInstaller.utils.hooks import collect_all, copy_metadata
datas, binaries, hiddenimports = collect_all('metpy')
#datas += copy_metadata('metpy')  # Probably redundant
```
but you could also do this in a spec file and then pass all three variables into `Analysis`.

**Comment by mishrakeshav** [comment]
@rokm Thank you. This worked.
