### ISSUE TITLE
ModuleNotFoundError when trying to run the created .exe file

### ISSUE THREAD

**Issue by mulaixi** [pyinstaller/pyinstaller#5253]
I'm having the same issue mentioned [here](https://github.com/pyinstaller/pyinstaller/issues/5197). I've read all conversation but for my case couldn't understand how to fix it. Pyinstaller successfully creates the .exe file. But when I try to run the exe file I encounter ModuleNotFoundError. This is a simple code in test.py file

```
from pywebcopy import WebPage, config
import tkinter as tk
from tkinter import filedialog
import time

print('this is a dummy code')
input('Please enter an input:')
print('thanks')

time.sleep(2)
root = tk.Tk()
root.withdraw()

path = filedialog.askdirectory(title='Select Folder')
print(path)
```

I used `pyinstaller --onefile test.py`  to create .exe file. The code above works correctly in Python. But when I try to run the exe file it gives error. This is the traceback:

```
C:\Users\test\Desktop\dummy\dist>test.exe
Traceback (most recent call last):
  File "test.py", line 12, in <module>
  File "c:\users\test\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pywebcopy\__init__.py", line 49, in <module>
  File "c:\users\test\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pywebcopy\configs.py", line 20, in <module>
  File "c:\users\test\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pywebcopy\structures.py", line 15, in <module>
  File "six.py", line 92, in __get__
  File "six.py", line 160, in _resolve
  File "six.py", line 82, in _import_module
ModuleNotFoundError: No module named 'urllib.robotparser'
[13056] Failed to execute script test
```

When I comment out `from pywebcopy import WebPage, config`, the .exe file also works. But I need that [package](https://pypi.org/project/pywebcopy/).

This is the `pip freeze` output:

```
alabaster==0.7.12
altgraph==0.17
astroid==2.4.2
async-generator==1.10
atomicwrites==1.4.0
attrs==20.2.0
autopep8==1.5.4
Babel==2.8.0
backcall==0.2.0
bcrypt==3.2.0
beautifulsoup4==4.9.3
bleach==3.2.1
bs4==0.0.1
CacheControl==0.12.6
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.3
cryptography==3.1.1
cssselect==1.1.0
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch==20200713
docutils==0.16
easygui==0.98.1
entrypoints==0.3
fire==0.3.1
flake8==3.8.4
Flask==1.1.2
future==0.18.2
helpdev==0.7.1
idna==2.10
imagesize==1.2.0
intervaltree==3.1.0
ipykernel==5.3.4
ipython==7.18.1
ipython-genutils==0.2.0
isort==5.5.4
itsdangerous==1.1.0
jedi==0.17.1
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-core==4.6.3
jupyterlab-pygments==0.1.2
keyring==21.4.0
lazy-object-proxy==1.4.3
lxml==4.5.2
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
msgpack==1.0.0
nbclient==0.5.0
nbconvert==6.0.7
nbformat==5.0.7
nest-asyncio==1.4.1
numpydoc==1.1.0
packaging==20.4
pandocfilters==1.4.2
paramiko==2.7.2
parse==1.18.0
parso==0.7.0
pathtools==0.1.2
pefile==2019.4.18
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
prompt-toolkit==3.0.7
psutil==5.7.2
ptyprocess==0.6.0
pycodestyle==2.6.0
pycparser==2.20
pydocstyle==5.1.1
pyflakes==2.2.0
Pygments==2.7.1
pyinstaller==4.0
pyinstaller-hooks-contrib==2020.9
pylint==2.6.0
PyNaCl==1.4.0
pyparsing==2.4.7
PyQt5==5.12.3
PyQt5-sip==12.8.1
PyQtWebEngine==5.12.1
pyquery==1.4.1
pyrsistent==0.17.3
python-dateutil==2.8.1
python-jsonrpc-server==0.4.0
python-language-server==0.35.1
pytz==2020.1
pywebcopy==6.3.0
pywin32==228
pywin32-ctypes==0.2.0
pyzmq==19.0.2
QDarkStyle==2.8.1
QtAwesome==1.0.1
qtconsole==4.7.7
QtPy==1.9.0
requests==2.24.0
rope==0.17.0
six==1.15.0
snowballstemmer==2.0.0
sortedcontainers==2.2.2
soupsieve==2.0.1
Sphinx==3.2.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder==4.1.5
spyder-kernels==1.9.4
termcolor==1.1.0
testpath==0.4.4
toml==0.10.1
tornado==6.0.4
traitlets==5.0.4
ujson==3.2.0
urllib3==1.25.10
w3lib==1.22.0
watchdog==0.10.3
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
wget==3.2
wrapt==1.12.1
yapf==0.30.0
```
Python version 3.8.6. Win10. 
And, as an additional info, pywebcopy wasn't working correctly. So, I made some changes in one of is file. But I don't think it would be the problem. It was about threading. But if necessary, I can share changes as well. Do you have any idea how to fix this?

**Comment by rokm** [comment]
Have you tried adding `urllib.robotparser` to hidden imports?

**Comment by mulaixi** [comment]
I missed that part, that conversation was too messy. Yes, it solved my problem. Thanks.
