### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by zhousteven** [pyinstaller/pyinstaller#5273]
My environment is Win10 , Pytorch:1.6.0+cpu、Torchvision:0.7.0+cpu、numpy：1.19.2,use pyinstaller:4.0 to make an .exe file, have try to change numpy to 1.18.5 or 1.17.5 or 1.15.0 still have this error :
Traceback (most recent call last):
  File "vgg.py", line 9, in <module>
  File "d:\programdata\anaconda3\envs\vgg\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torch\__init__.py", line 189, in <module>
ImportError: numpy.core.multiarray failed to import
[20924] Failed to execute script vgg

**Comment by zhousteven** [comment]
below method solved my error:
before input package commandline, enter "chcp 65001", after that
enter "pyinstaller -F vgg.py"

**Comment by zhousteven** [comment]
below method solved my error:
before input package commandline, enter "chcp 65001", after that
enter "pyinstaller -F vgg.py"

**Comment by zhousteven** [comment]
below method solved my error:
before input package commandline, enter "chcp 65001", after that
enter "pyinstaller -F vgg.py"
