### ISSUE TITLE
numpy import -> ImportError: No module named multiarray on SVN, mac 10.6, python 2.7

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#529]
**Original date**: 2012/03/11
**Original reporter**: *pinchies AND gmail DOT  COOM *

I am experiencing a similar problem to http://www.pyinstaller.org/ticket/363. I created a test script with one line to demonstrate:

'''import numpy
'''
running this script from IDLE works perfectly. When I compile (from pyinstaller SVN version, using Jon Baer's excellent scipy superpack)

I get: 

Last login: Sun Mar 11 23:10:51 on ttys003
/Users/pinchies/Desktop/Speed/pyinstaller/test/dist/test ; exit;
pinchiess-mac:~ pinchies$ /Users/pinchies/Desktop/Speed/pyinstaller/test/dist/test ; exit;
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 437, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 527, in doimport
    exec co in mod.__dict__
  File "/Users/pinchies/Desktop/Speed/pyinstaller/test/build/pyi.darwin/test/out01-PYZ.pyz/numpy", line 137, in <module>
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 437, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 527, in doimport
    exec co in mod.__dict__
  File "/Users/pinchies/Desktop/Speed/pyinstaller/test/build/pyi.darwin/test/out01-PYZ.pyz/numpy.add_newdocs", line 9, in <module>
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 437, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 527, in doimport
    exec co in mod.__dict__
  File "/Users/pinchies/Desktop/Speed/pyinstaller/test/build/pyi.darwin/test/out01-PYZ.pyz/numpy.lib", line 4, in <module>
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 437, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 527, in doimport
    exec co in mod.__dict__
  File "/Users/pinchies/Desktop/Speed/pyinstaller/test/build/pyi.darwin/test/out01-PYZ.pyz/numpy.lib.type_check", line 8, in <module>
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 437, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 527, in doimport
    exec co in mod.__dict__
  File "/Users/pinchies/Desktop/Speed/pyinstaller/test/build/pyi.darwin/test/out01-PYZ.pyz/numpy.core", line 5, in <module>
  File "/Users/pinchies/Desktop/Speed/pyinstaller/PyInstaller/loader/iu.py", line 456, in importHook
    raise ImportError("No module named %s" % fqname)
ImportError: No module named multiarray
logout

[Process completed]

I have checked, and the multiarray files are all there?

**Comment by matysek** [comment]
Numpy test is working with latest dev version.
