### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by shaoshenchen** [pyinstaller/pyinstaller#5290]
I made an OCR model with PyQt5 and wanted to package it as an EXE program. This model translate a image into strings, it could be run with a Python interpreter.  I had tried many ways and failed. Here's my environment：
- **Win10-x64**
- **pyinstaller：4.0**
- **PyQt5：5.15.1**
- PaddlePaddle：1.8.5    # deep learning framework
- PaddleHub：1.8.2    # a toolkit for managing pretrained models of PaddlePaddle

I use `cmd` to package this model, it seemed to have succeeded and create two folder `build` `dist`
and a file `main.spec`. Then I use cmd to run the EXE program, error started to occur.
```
$ pyinstaller -D main.py
$ dist/main/main.exe
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import screen_rec
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "screen_rec.py", line 6, in <module>
    import paddlehub as hub
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddlehub\__init__.py", line 27, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddlehub\module\__init__.py", line 16, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddlehub\module\module.py", line 28, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\__init__.py", line 37, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\complex\__init__.py", line 15, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\complex\tensor\__init__.py", line 15, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\complex\tensor\math.py", line 15, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\common_ops_import.py", line 15, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\fluid\__init__.py", line 35, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\fluid\framework.py", line 35, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\fluid\core.py", line 273, in <module>
  File "paddle\fluid\core.py", line 243, in <module>
ImportError: DLL load failed: 找不到指定的模块。
[10328] Failed to execute script main

$ build/main/main.exe
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 17, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "multiprocessing\__init__.py", line 16, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "multiprocessing\context.py", line 6, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "multiprocessing\reduction.py", line 16, in <module>
  File "d:\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "socket.py", line 49, in <module>
ModuleNotFoundError: No module named '_socket'
[16516] Failed to execute script pyi_rth_multiprocessing
```
***
Also, I tried another way.
```
$ pyinstaller -F -w main.py
$ dist/main.exe
```
![image](https://user-images.githubusercontent.com/45918719/97301742-1cf4da80-1893-11eb-90e4-abce1ea4222a.png)

I spent two days searching for relevant information, but none has been effectively addressed. In other words, how to use pyinstaller to package PyQt5 in Win10. Thanks for response and help in advance!

**Comment by lstolcman** [comment]
1. build with `--debug` switch
2. add additional missing .dll files using `-add-data` : https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-data-files

**Comment by shaoshenchen** [comment]
I don't know how to understand these two steps. I run the code `pyinstaller -F -w main.py --debug all` and don't find any .dll related information. Could you please tell me the specific idea of the solution?

**Comment by kakkarja** [comment]
Please allow me 🙏
@shaoshenchen 
I had many compiling problem before, because i did not know how to see the result of the error message with -F -w. Than i use -F -c, so that the error message can be capture in console. However the process is so fast, that you cannot see it for few seconds. As window user, i use keys 'window + prt sc' button on my keyboard. It will create a capture of your desktop. Hope this information is useful to you. 🙏

**Comment by real-yfprojects** [comment]
@shaoshenchen What about sharing the output?

**Comment by shaoshenchen** [comment]
output？

**Comment by real-yfprojects** [comment]
> output？

> I run the code `pyinstaller -F -w main.py --debug all` and don't find any `.dll` related information.
The ouput of this command might be useful.

**Comment by bwoodsend** [comment]
Please never use the `-w` option when debugging. It essentially means *provide no output* which when debugging means *don't give me any clue as to what went wrong*. The `ModuleNotFoundError` should be easily fixable with `--hiddenimport=socket`. The dll load error is because you're using Conda. PyInstaller can't track binary dependencies for Conda. Please use a normal distribution of Python.
