### ISSUE TITLE
RuntimeError: Script runserver does not exist. Issue for Django 3.1.2/Py 3.7 Project

### ISSUE THREAD

**Issue by AndyZdbuke** [pyinstaller/pyinstaller#5294]
## When running the dist/exe getting the RuntimeError: Script runserver does not exist. Issue for Django Project
Django ver - 3.1.2

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: e.g. 3.7
* Platform: Windows 10
* Did you also try this on another platform? Does it work there?

* tried the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [Y] start with clean installation
  * [Y] use the latest development version
  * [Y] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [Y] Package your program in **--onedir mode**
  * [Y] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [Y] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
  File "django\utils\autoreload.py", line 616, in run_with_reloader
    exit_code = restart_with_reloader()
  File "PyInstaller\hooks\rthooks\pyi_rth_django.py", line 72, in _restart_with_reloader
  File "django\utils\autoreload.py", line 242, in restart_with_reloader
    args = get_child_arguments()
  File "django\utils\autoreload.py", line 229, in get_child_arguments
    raise RuntimeError('Script %s does not exist.' % py_script)
RuntimeError: Script runserver does not exist.
[62884] Failed to execute script manage
[62884] LOADER: OK.
[62884] LOADER: Manually flushing stdout and stderr
[62884] LOADER: Cleaning up Python interpreter.

### Stacktrace / full error message

```
(env) C:\Users\....\dist\manage>sva runserver
[62884] PyInstaller Bootloader 3.x
[62884] LOADER: executable is C:\Users\....\dist\manage\SVA.exe
[62884] LOADER: homepath is C:\Users\....\dist\manage
[62884] LOADER: _MEIPASS2 is NULL
[62884] LOADER: archivename is C:\Users\....\dist\manage\SVA.exe
[62884] LOADER: No need to extract files to run; setting extractionpath to homepath
[62884] LOADER: SetDllDirectory(C:\Users\....\dist\manage)
[62884] LOADER: Already in the child - running user's code.
[62884] LOADER: Python library: C:\Users\....\dist\manage\python37.dll
[62884] LOADER: Loaded functions from Python library.
[62884] LOADER: Manipulating environment (sys.path, sys.prefix)
[62884] LOADER: sys.prefix is C:\Users\....\dist\manage
[62884] LOADER: Pre-init sys.path is C:\Users\....\dist\manage\base_library.zip;C:\Users\....\dist\manage
[62884] LOADER: Setting runtime options
[62884] LOADER: Initializing python
[62884] LOADER: Overriding Python's sys.path
[62884] LOADER: Post-init sys.path is C:\Users\....\dist\manage\base_library.zip;C:\Users\....\dist\manage
[62884] LOADER: Setting sys.argv
[62884] LOADER: setting sys._MEIPASS
[62884] LOADER: importing modules from CArchive
[62884] LOADER: extracted struct
[62884] LOADER: callfunction returned...
[62884] LOADER: extracted pyimod01_os_path
[62884] LOADER: callfunction returned...
[62884] LOADER: extracted pyimod02_archive
[62884] LOADER: callfunction returned...
[62884] LOADER: extracted pyimod03_importers
[62884] LOADER: callfunction returned...
[62884] LOADER: Installing PYZ archive with Python modules.
[62884] LOADER: PYZ archive: PYZ-00.pyz
[62884] LOADER: Running pyiboot01_bootstrap.py
[62884] LOADER: Running pyi_rth_multiprocessing.py
[62884] LOADER: Running pyi_rth_pkgres.py
[62884] LOADER: Running pyi_rth_django.py
[62884] LOADER: Running manage.py
Traceback (most recent call last):
  File "manage.py", line 25, in <module>
  File "manage.py", line 21, in main
  File "django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\....\dist\manage\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\....\dist\manage\django\core\management\commands\runserver.py", line 96, in handle
    self.run(**options)
  File "C:\Users\....\dist\manage\django\core\management\commands\runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "django\utils\autoreload.py", line 616, in run_with_reloader
    exit_code = restart_with_reloader()
  File "PyInstaller\hooks\rthooks\pyi_rth_django.py", line 72, in _restart_with_reloader
  File "django\utils\autoreload.py", line 242, in restart_with_reloader
    args = get_child_arguments()
  File "django\utils\autoreload.py", line 229, in get_child_arguments
    raise RuntimeError('Script %s does not exist.' % py_script)
RuntimeError: Script runserver does not exist.
[62884] Failed to execute script manage
[62884] LOADER: OK.
[62884] LOADER: Manually flushing stdout and stderr
[62884] LOADER: Cleaning up Python interpreter.
```

**Comment by AndyZdbuke** [comment]
My manage.spec

# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['manage.py'],
             pathex=['C:\\Users\\.....\\SVA_Project'],
             binaries=[],
             datas=[],
             hiddenimports=['django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'SVA_App',
            'rest_framework',
            'import_export',],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='SVA',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='manage')

**Comment by AndyZdbuke** [comment]
Need help stuck for long

**Comment by gilbertomarcano** [comment]
Hey, I found a solution but with Py3.5/Django2.2, does it work for you?

**Comment by Harshdeep007** [comment]
yes please i am getting the same error

**Comment by rocchidavide** [comment]
I have the same problem

**Comment by nerseswolf** [comment]
Same here. Does anyone solve this problem? Please help

**Comment by liujin834** [comment]
> Hey, I found a solution but with Py3.5/Django2.2, does it work for you?

It is not working for Django 3.x

**Comment by Harshdeep007** [comment]
yup it doesn't work for higher versions  of Django .I spent a good amount of time figuring it out, configuring the manage.spec but it didn't  work(or it maybe because of higher version of python). 
Since my project was not so massive and  I just wanted the .exe file  for demonstration purpose for my college project, I choose an alternative solution and hosted the project on pythonanywhere.com.
It is free and 512MB data storage was more than  enough for me.

**Comment by mbalslow** [comment]
I can get it to work with Django v3.0.X and the latest version of Pyinstaller. However, I am unable to get it working with Django v3.1.X.

**Comment by liujin834** [comment]
I pass the `--noreload` to the `runserver` command then it is working great. (Django v3.1.4)

```bash
./dist/manage/manage runserver --noreload
```

Now it is not my trouble. I just used the Pyinstaller in my Dockerfile.

**Comment by nerseswolf** [comment]
It works! Thank you very much !!

**Comment by Harshdeep007** [comment]
> I pass the `--noreload` to the `runserver` command then it is working great. (Django v3.1.4)
> 
> ```shell
> ./dist/manage/manage runserver --noreload
> ```
> 
> Now it is not my trouble. I just used the Pyinstaller in my Dockerfile.

Thanks! I would have never guessed noreload would do the thing.I still don't understand how it got fixed with that command.
