### ISSUE TITLE
qt and PySide hook error in Pyinstaller (Python 3.7)

### ISSUE THREAD

**Issue by LFCrushTeam** [pyinstaller/pyinstaller#5305]
- Python 3.7
- Pyinstaller 4.0
- Windows 10 Version 1903(Russian)
**Full error message**

```
C:\Users\mrwit\OneDrive\Рабочий стол\Краш\MyFolder\LF Soft\Discord Bots\BackCord\ExeBackCord\DoubleBackCord\Test>pyinstaller --hidden-import=pyttsx3.drivers --hidden-import=pyttsx3.drivers.dummy --hidden-import=pyttsx3.drivers.espeak --hidden-import=pyttsx3.drivers.nsss --hidden-import=pyttsx3.drivers.sapi5 -F DiscordBot.py
79 INFO: PyInstaller: 4.0
80 INFO: Python: 3.7.0
80 INFO: Platform: Windows-10-10.0.18362-SP0
82 INFO: wrote C:\Users\mrwit\OneDrive\Рабочий стол\Краш\MyFolder\LF Soft\Discord Bots\BackCord\ExeBackCord\DoubleBackCord\Test\DiscordBot.spec
84 INFO: UPX is not available.
86 INFO: Extending PYTHONPATH with paths
['C:\\Users\\mrwit\\OneDrive\\Рабочий стол\\Краш\\MyFolder\\LF Soft\\Discord '
 'Bots\\BackCord\\ExeBackCord\\DoubleBackCord\\Test',
 'C:\\Users\\mrwit\\OneDrive\\Рабочий стол\\Краш\\MyFolder\\LF Soft\\Discord '
 'Bots\\BackCord\\ExeBackCord\\DoubleBackCord\\Test']
118 INFO: checking Analysis
118 INFO: Building Analysis because Analysis-00.toc is non existent
118 INFO: Initializing module dependency graph...
124 INFO: Caching module graph hooks...
142 INFO: Analyzing base_library.zip ...
4612 INFO: Caching module dependency graph...
4746 INFO: running Analysis Analysis-00.toc
4768 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\mrwit\appdata\local\programs\python\python37\python.exe
4865 INFO: Analyzing C:\Users\mrwit\OneDrive\Рабочий стол\Краш\MyFolder\LF Soft\Discord Bots\BackCord\ExeBackCord\DoubleBackCord\Test\DiscordBot.py
6093 INFO: Processing pre-find module path hook distutils from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
6094 INFO: distutils: retargeting to non-venv dir 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib'
8902 INFO: Processing pre-find module path hook site from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
8903 INFO: site: retargeting to fake-dir 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\fake-modules'
19002 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
21075 INFO: Processing pre-safe import module hook six.moves from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
29789 INFO: Analyzing hidden import 'pyttsx3.drivers'
29914 INFO: Analyzing hidden import 'pyttsx3.drivers.dummy'
29921 INFO: Analyzing hidden import 'pyttsx3.drivers.espeak'
29966 INFO: Analyzing hidden import 'pyttsx3.drivers.nsss'
29973 INFO: Analyzing hidden import 'pyttsx3.drivers.sapi5'
31003 INFO: Processing module hooks...
31003 INFO: Loading module hook 'hook-certifi.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
31013 INFO: Loading module hook 'hook-cryptography.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
31341 INFO: Loading module hook 'hook-cv2.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
31346 INFO: Loading module hook 'hook-pycparser.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
31347 INFO: Loading module hook 'hook-pythoncom.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
31928 INFO: Loading module hook 'hook-pywintypes.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
32486 INFO: Loading module hook 'hook-sounddevice.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
32489 INFO: Loading module hook 'hook-soundfile.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
32491 INFO: Loading module hook 'hook-distutils.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
32493 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
32599 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
32687 INFO: Loading module hook 'hook-numpy.core.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
32830 INFO: Loading module hook 'hook-numpy.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
32832 INFO: Loading module hook 'hook-PIL.Image.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
33212 INFO: Loading module hook 'hook-PIL.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
33215 INFO: Excluding import 'tkinter'
33219 INFO:   Removing import of tkinter from module PIL.ImageTk
33221 INFO: Excluding import 'PyQt5'
33224 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
33224 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
33225 INFO: Excluding import 'PyQt4'
33231 INFO: Import to be excluded not found: 'FixTk'
33231 INFO: Import to be excluded not found: 'PySide'
33233 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
33238 INFO: Excluding import 'tkinter'
33241 INFO: Import to be excluded not found: 'FixTk'
33242 INFO: Loading module hook 'hook-pkg_resources.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
34047 INFO: Processing pre-safe import module hook win32com from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
34452 WARNING: Hidden import "pkg_resources.py2_warn" not found!
34828 WARNING: Hidden import "pkg_resources.markers" not found!
34832 INFO: Excluding import '__main__'
34835 INFO:   Removing import of __main__ from module pkg_resources
34836 INFO: Loading module hook 'hook-PyQt5.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
35030 WARNING: Hidden import "sip" not found!
35031 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
35134 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
35325 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
35735 INFO: Loading module hook 'hook-PySide2.py' from 'c:\\users\\mrwit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks'...
35861 WARNING: Cannot read QLibraryInfo output: raised Expecting value: line 1 column 1 (char 0) when decoding:
PySide2/__init__.py: Unable to import shiboken2 from , C:\Users\mrwit\OneDrive\Рабочий стол\Краш\MyFolder\LF Soft\Discord Bots\BackCord\ExeBackCord\DoubleBackCord\Test, c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages, c:\users\mrwit\appdata\local\programs\python\python37\python37.zip, c:\users\mrwit\appdata\local\programs\python\python37\DLLs, c:\users\mrwit\appdata\local\programs\python\python37\lib, c:\users\mrwit\appdata\local\programs\python\python37, c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\pycrypto-2.6.1-py3.7-win-amd64.egg, c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\win32, c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\win32\lib, c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\Pythonwin
False
Traceback (most recent call last):
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mrwit\AppData\Local\Programs\Python\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "C:\Users\mrwit\OneDrive\Рабочий стол\Краш\MyFolder\LF Soft\Discord Bots\BackCord\ExeBackCord\DoubleBackCord\Test\DiscordBot.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 419, in assemble
    self.graph.process_post_graph_hooks()
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 365, in process_post_graph_hooks
    module_hook.post_graph()
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\depend\imphook.py", line 440, in post_graph
    self._load_hook_module()
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\depend\imphook.py", line 407, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\compat.py", line 588, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\hooks\hook-PySide2.py", line 26, in <module>
    collect_system_data_files(pyside2_library_info.location['PrefixPath'],
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 89, in __getattr__
    return getattr(self, name)
  File "c:\users\mrwit\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 91, in __getattr__
    raise AttributeError

AttributeError

```
Help would be very much appreciated.

Thank you.

**Comment by rokm** [comment]
Can you provide a minimal example that triggers this issue? The import section of your program should probably do the trick...

Alternatively, does building a simple PySide2 application work in your environment?
```python
from PySide2 import QtCore, QtWidgets
app = QtWidgets.QApplication([])
window = QtWidgets.QWidget()
window.show()
app.exec_()
```

If not, can you post the output of `pip freeze` for your environment?

**Comment by LFCrushTeam** [comment]
> Can you provide a minimal example that triggers this issue? The import section of your program should probably do the trick...
> 
> Alternatively, does building a simple PySide2 application work in your environment?
> 
> ```python
> from PySide2 import QtCore, QtWidgets
> app = QtWidgets.QApplication([])
> window = QtWidgets.QWidget()
> window.show()
> app.exec_()
> ```
> 
> If not, can you post the output of `pip freeze` for your environment?

It is discord bot and I didn't use PySide2 or PyQt5

**Comment by rokm** [comment]
> I didn't use PySide2 or PyQt5

Does that mean that PySide2 and PyQt5 are not installed in your environment? Can you provide output of `pip freeze` for the reference?

Something seems to be (perhaps indirectly) pulling PySide2 and PyQt5 in... could you copy the import statements from your bot into a small stand-alone example (and check that it also triggers this error during build)?

**Comment by LFCrushTeam** [comment]
> > I didn't use PySide2 or PyQt5
> 
> Does that mean that PySide2 and PyQt5 are not installed in your environment? Can you provide output of `pip freeze` for the reference?
> 
> Something seems to be (perhaps indirectly) pulling PySide2 and PyQt5 in... could you copy the import statements from your bot into a small stand-alone example (and check that it also triggers this error during build)?

I had PyQt5 and PySide2 installed, and when I've uninstalled them pyinstaller started working normally
