### ISSUE TITLE
pkg_resources.DistributionNotFound:

### ISSUE THREAD

**Issue by Park-HyeongGyu** [pyinstaller/pyinstaller#5332]
## Description of the issue
I was trying to make exe files using pyinstaller. When I execute `pyinstaller -F .\GetPickle.py` in anaconda powershell prompt, It did work and made exe file in dist folder. But there was some error messages when I execute exe file in windows cmd(The code ran well in pycharm).

I'm so sorry about that I can't write a minimal example program which shows the error. I copied code from 'https://developers.google.com/calendar/quickstart/python' so I can't find the part that error arised. Please understand me who is struggling with google api.......(English so hard......)

+I tried to solve this problem with the information from https://github.com/pyinstaller/pyinstaller/issues/4809, but a method in that issue report doesn't work.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.1```
* Version of Python: 3.9.0
* Platform: Windows (Korean)

### A minimal example program which shows the error

```
import datetime
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/calendar']

CREDENTIALS_FILE = 'credentials.json'

def get_calendar_service():
   creds = None
   # The file token.pickle stores the user's access and refresh tokens, and is
   if os.path.exists('token.pickle'):
       with open('token.pickle', 'rb') as token:
           creds = pickle.load(token)
   # If there are no (valid) credentials available, let the user log in.
   if not creds or not creds.valid:
       if creds and creds.expired and creds.refresh_token:
           creds.refresh(Request())
       else:
           flow = InstalledAppFlow.from_client_secrets_file(
               CREDENTIALS_FILE, SCOPES)
           creds = flow.run_local_server(port=0)

       # Save the credentials for the next run
       with open('token.pickle', 'wb') as token:
           pickle.dump(creds, token)

   service = build('calendar', 'v3', credentials=creds)
   input=("Press any key to exit program......")
   return service

if __name__=='__main__':
   # created automatically when the authorization flow completes for the first
   # time.
    get_calendar_service()
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "GetPickle.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\users\user\anaconda3\envs\cdr\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "googleapiclient\discovery.py", line 68, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\users\user\anaconda3\envs\cdr\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "googleapiclient\http.py", line 67, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\users\user\anaconda3\envs\cdr\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "googleapiclient\model.py", line 36, in <module>
  File "pkg_resources\__init__.py", line 465, in get_distribution
  File "pkg_resources\__init__.py", line 341, in get_provider
  File "pkg_resources\__init__.py", line 884, in require
  File "pkg_resources\__init__.py", line 770, in resolve
pkg_resources.DistributionNotFound: The 'google-api-python-client' distribution was not found and is required by the application
[14204] Failed to execute script GetPickle
```

+
Below is a output of `pyinstaller -F --debug-all .\GetPickle.py`
```
106 INFO: PyInstaller: 4.1
107 INFO: Python: 3.9.0 (conda)
108 INFO: Platform: Windows-10-10.0.18362-SP0
163 INFO: wrote D:\Python_cont\cdr\GetPickle.spec
166 INFO: UPX is not available.
167 INFO: Extending PYTHONPATH with paths
['D:\\Python_cont\\cdr', 'D:\\Python_cont\\cdr']
189 INFO: checking Analysis
197 INFO: Building because hiddenimports changed
198 INFO: Initializing module dependency graph...
202 INFO: Caching module graph hooks...
228 INFO: Analyzing base_library.zip ...
3431 INFO: Processing pre-find module path hook distutils from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
3432 INFO: distutils: retargeting to non-venv dir 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib'
5940 INFO: Caching module dependency graph...
6090 INFO: running Analysis Analysis-00.toc
6107 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\user\anaconda3\envs\cdr\python.exe
6215 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of c:\users\user\anaconda3\envs\cdr\python39.dll
6407 INFO: Analyzing D:\Python_cont\cdr\GetPickle.py
6481 INFO: Processing pre-safe import module hook six.moves from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
8704 INFO: Processing pre-find module path hook site from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
8705 INFO: site: retargeting to fake-dir 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\fake-modules'
11233 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
12935 INFO: Processing module hooks...
12935 INFO: Loading module hook 'hook-certifi.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
12943 INFO: Loading module hook 'hook-cryptography.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13302 INFO: Loading module hook 'hook-google.api_core.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13304 INFO: Loading module hook 'hook-httplib2.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13309 INFO: Loading module hook 'hook-pycparser.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13310 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13494 INFO: Loading module hook 'hook-difflib.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13495 INFO: Excluding import of doctest from module difflib
13496 INFO: Loading module hook 'hook-distutils.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13497 INFO: Loading module hook 'hook-distutils.util.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13500 INFO: Excluding import of lib2to3.refactor from module distutils.util
13500 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13590 INFO: Loading module hook 'hook-heapq.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13593 INFO: Excluding import of doctest from module heapq
13593 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13638 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13641 INFO: Excluding import of test from module multiprocessing.util
13641 INFO: Excluding import of test.support from module multiprocessing.util
13641 INFO: Loading module hook 'hook-pickle.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13644 INFO: Excluding import of argparse from module pickle
13645 INFO: Loading module hook 'hook-pkg_resources.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
13986 INFO: Processing pre-safe import module hook win32com from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
14055 INFO: Processing pre-safe import module hook win32com from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
14278 WARNING: Hidden import "pkg_resources.py2_warn" not found!
14278 WARNING: Hidden import "pkg_resources.markers" not found!
14281 INFO: Excluding import of __main__ from module pkg_resources
14281 INFO: Loading module hook 'hook-setuptools.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
14882 INFO: Import to be excluded not found: 'setuptools.py33compat'
14882 INFO: Import to be excluded not found: 'setuptools.py27compat'
14883 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
14884 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
14885 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
14886 INFO: Loading module hook 'hook-xml.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
14887 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
15078 INFO: checking Tree
15166 INFO: checking Tree
15283 INFO: checking Tree
15288 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks'...
15290 INFO: Excluding import of numpy from module setuptools.msvc
15325 INFO: Looking for ctypes DLLs
15375 INFO: Analyzing run-time hooks ...
15380 INFO: Including run-time hook 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_certifi.py'
15381 INFO: Including run-time hook 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
15384 INFO: Including run-time hook 'c:\\users\\user\\anaconda3\\envs\\cdr\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
15394 INFO: Looking for dynamic libraries
15614 INFO: Looking for eggs
15614 INFO: Using Python library c:\users\user\anaconda3\envs\cdr\python39.dll
15615 INFO: Found binding redirects:
[]
18370 INFO: Warnings written to D:\Python_cont\cdr\build\GetPickle\warn-GetPickle.txt
18522 INFO: Graph cross-reference written to D:\Python_cont\cdr\build\GetPickle\xref-GetPickle.html
18544 INFO: checking PYZ
18549 INFO: Building because toc changed
18549 INFO: Building PYZ (ZlibArchive) D:\Python_cont\cdr\build\GetPickle\PYZ-00.pyz
18550 INFO: Building PYZ (ZlibArchive) D:\Python_cont\cdr\build\GetPickle\PYZ-00.pyz completed successfully.
18556 INFO: checking PKG
18558 INFO: Building because toc changed
18558 INFO: Building PKG (CArchive) PKG-00.pkg
22090 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
22110 INFO: Bootloader c:\users\user\anaconda3\envs\cdr\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run_d.exe
22110 INFO: checking EXE
22112 INFO: Building because debug changed
22112 INFO: Building EXE from EXE-00.toc
22114 INFO: Appending archive to EXE D:\Python_cont\cdr\dist\GetPickle.exe
22123 INFO: Building EXE from EXE-00.toc completed successfully.
```

**Comment by rokm** [comment]
You will need to collect the metadata for `google_api_python_client`, either by modifying your .spec file or by creating an additional hook.

If you are building via .spec file, you can add the following lines to it

```python
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('google_api_python_client')
```
and then pass the `datas` to `Analysis`. 

Or, if you want to use the hook, create a directory (e.g., `extra-hooks`) with a file called `hook-googleapiclient.py` with following content: 
```python
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('google_api_python_client')
```

And then when you're building your program, pass the extra hooks directory to pyinstaller via `--additional-hooks-dir`. E.g.,
`pyinstaller -F --additional-hooks-dir .\extra-hooks\ .\GetPickle.py`

**Comment by Park-HyeongGyu** [comment]
> You will need to collect the metadata for `google_api_python_client`, either by modifying your .spec file or by creating an additional hook.
> 
> If you are building via .spec file, you can add the following lines to it
> 
> ```python
> from PyInstaller.utils.hooks import copy_metadata
> datas = copy_metadata('google_api_python_client')
> ```
> 
> and then pass the `datas` to `Analysis`.
> 
> Or, if you want to use the hook, create a directory (e.g., `extra-hooks`) with a file called `hook-googleapiclient.py` with following content:
> 
> ```python
> from PyInstaller.utils.hooks import copy_metadata
> datas = copy_metadata('google_api_python_client')
> ```
> 
> And then when you're building your program, pass the extra hooks directory to pyinstaller via `--additional-hooks-dir`. E.g.,
> `pyinstaller -F --additional-hooks-dir .\extra-hooks\ .\GetPickle.py`

It worked! Thank you so much^^.
