### ISSUE TITLE
Installation issue with pip > 18.1

### ISSUE THREAD

**Issue by JafferWilson** [pyinstaller/pyinstaller#5339]
I was trying to install pyinstaller using pip on Windows 10. Here is what error I got:
```

C:\Users\AIMS-RESEARCH\AppData\Roaming\MetaQuotes\Terminal\F5EC6124DFC414901C9F2B0C5815057F\MQL5\Indicators\TRENDLINES_AIMS\Python>pip install pyinstaller
Collecting pyinstaller
  Downloading pyinstaller-4.1.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 402 kB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python37\python.exe' 'c:\python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\AIMS-R~1\AppData\Local\Temp\pip-build-env-qo3qyuwa\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\python37\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "c:\python37\lib\site-packages\pip\__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "c:\python37\lib\site-packages\pip\_internal\cli\main.py", line 5, in <module>
      import locale
    File "c:\python37\lib\locale.py", line 16, in <module>
      import re
    File "c:\python37\lib\re.py", line 145, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python37\python.exe' 'c:\python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\AIMS-R~1\AppData\Local\Temp\pip-build-env-qo3qyuwa\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

I have searched for the reason and I found this StackOverflow link: https://stackoverflow.com/questions/54352077/pyinstaller-failing-to-install-through-pip

Please check why is this happening with the Upgraded version of pip.

**Comment by BoboTiG** [comment]
Maybe https://stackoverflow.com/a/48125118/1117028?

**Comment by JafferWilson** [comment]
It helped. But why it is happening? Previously I had used pyinstaller on Python 3.5.0, I never faced any issues. Recently, I have shifted to Python 3.7. And had this sort of issue.

**Comment by BoboTiG** [comment]
The issue happens starting with Python 3.6. Not related to PyInstaller though.
