### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by telekompen** [pyinstaller/pyinstaller#5340]
## Description of the issue
Tried to pack .py file with pyinstaller.  Everything works on the system where I built the exe. When starting .exe on another system this error appears:

### Error

```
C:\predict>predict.exe
Traceback (most recent call last):
  File "predict.py", line 1, in <module>
  File "c:\users\pc\anaconda3\envs\audio\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\__init__.py", line 41, in <module>
  File "c:\users\pc\anaconda3\envs\audio\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\__init__.py", line 40, in <module>
  File "c:\users\pc\anaconda3\envs\audio\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\eager\context.py", line 35, in <module>
  File "c:\users\pc\anaconda3\envs\audio\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tfe.py", line 29, in <module>
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
[10436] Failed to execute script predict
```

### Environment
Windows 10
Python 3.7.9
Tensorflow 2.3.1
Pyinstaller 4.1
conda 4.8.3

Thanks for response and help in advance.

**Comment by bwoodsend** [comment]
We don't support Conda. If you want to use PyInstaller then use a proper version of Python.
