### ISSUE TITLE
Missing dll files on Windows

### ISSUE THREAD

**Issue by AndLvovSky** [pyinstaller/pyinstaller#5353]
After I run:
```
pyupdater build -F --app-version 0.0.1 app.py
```
I get an error:
```
[INFO] PyUpdater 3.1.1
[INFO] Compiling...
Python library not found: libpython3.7.dll, libpython37m.dll, libpython3.7m.dll, python37.dll, libpython37.dll
    This would mean your Python installation doesn't come with proper library files.
    This usually happens by missing development package, or unsuitable build parameters of Python installation.
    * On Debian/Ubuntu, you would need to install Python development packages
      * apt-get install python3-dev
      * apt-get install python-dev
    * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```
Environment:
- Windows 10
- Python 3.7.9
- PyUpdater 3.1.1
- Pyinstaller 4.1

**Comment by rokm** [comment]
Is this Python 3.7.9 from MS app store?

**Comment by AndLvovSky** [comment]
No, it's from the official site: https://www.python.org/downloads/release/python-379/

**Comment by rokm** [comment]
Hmm... what's the output of `where python`, `where pip`, `where pyupdater` and `where pyinstaller`?

Also, can you try building the application directly with `pyinstaller`, without `pyupdater`?

**Comment by AndLvovSky** [comment]
```
where python
C:\Users\username\workspace\pyupdater-demo\env\Scripts\python.exe
C:\Program Files (x86)\Python37-32\python.exe
C:\Program Files (x86)\Python39-32\python.exe
C:\Users\username\AppData\Local\Microsoft\WindowsApps\python.exe

where pip
C:\Users\username\workspace\pyupdater-demo\env\Scripts\pip.exe
C:\Program Files (x86)\Python37-32\Scripts\pip.exe
C:\Program Files (x86)\Python39-32\Scripts\pip.exe
C:\Users\username\AppData\Local\Microsoft\WindowsApps\pip.exe

where pyupdater
C:\Users\username\workspace\pyupdater-demo\env\Scripts\pyupdater.exe

where pyinstaller
C:\Users\username\workspace\pyupdater-demo\env\Scripts\pyinstaller.exe
```

**Comment by rokm** [comment]
I can't seem to reproduce this with a venv created from a 32-bit python that's been installed for all users, either...

What happens if you try to build directly using `pyinstaller`? If that fails as well, please attach the build log as a file here.

**Comment by AndLvovSky** [comment]
```
> pyinstaller app.py

8947 WARNING: Can not get binary dependencies for file: C:\Users\username\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe
8947 WARNING:   Reason: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\username\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_qbz5n2
kfra8p0\\python.exe'
Traceback (most recent call last):
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\depend\bindepend.py", line 727, in getImports
    return _getImports_pe(pth)
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\depend\bindepend.py", line 99, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\pefile.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\pefile.py", line 1797, in __parse__
    stat = os.stat(fname)
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\username\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\python
.exe'
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\workspace\pyupdater-demo\env\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "C:\Users\username\workspace\pyupdater-demo\app.spec", line 29, in <module>
    console=True )
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\building\api.py", line 439, in __init__
    upx_exclude=self.upx_exclude
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\building\api.py", line 200, in __init__
    self.__postinit__()
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\building\api.py", line 279, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "c:\users\username\workspace\pyupdater-demo\env\lib\site-packages\PyInstaller\depend\bindepend.py", line 945, in get_python_library_path
    raise IOError(msg)
OSError: Python library not found: libpython3.7m.dll, libpython37.dll, python37.dll, libpython37m.dll, libpython3.7.dll
    This would mean your Python installation doesn't come with proper library files.
    This usually happens by missing development package, or unsuitable build parameters of Python installation.
```

**Comment by rokm** [comment]
`8947 WARNING: Can not get binary dependencies for file: C:\Users\username\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe
8947 WARNING:   Reason: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\username\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_qbz5n2
kfra8p0\\python.exe'`

This means the Python from MS app store is being used. 

I suspect your virtual environment (`c:\users\username\workspace\pyupdater-demo\env`) was created using that version of python instead of the one from `C:\Program Files (x86)\Python37-32`

**Comment by AndLvovSky** [comment]
I've removed all python versions and installed the one from the official site and it seems to be working, thanks!
