### ISSUE TITLE
pyusb doesn't work, can't find DLL

### ISSUE THREAD

**Issue by skoehler** [pyinstaller/pyinstaller#5358]
I am using Python 3.8 64-Bit on Windows 10. I installed PyInstaller and pyusb as follows:
`py -3-64 -m pip install --user PyInstaller pyusb`
At the time of writing, that installs PyInstaller 4.1 and pyusb 1.1.0.

Consider the following Python program `usbtest.py`:
```
import usb
r = usb.core.find(find_all=True)
print(list(r))
```

In the same directory as `usbtest.py`, I have libusb-1.0.dll. When running `py -3-64 usbtest.py`, the script works just fine (if you have no USB devices connected, it prints the empty list).

I then try to create an EXE file with the following command:
```
py -3-64 ^
    -OO -m PyInstaller ^
    --specpath dist --distpath dist --workpath dist/build ^
    --noupx --onefile --clean --console ^
    --add-binary ../libusb-1.0.dll;. ^
    "usbtest.py"
```

The resulting EXE will contain the DLL, but the program will fail with the following messages:
```
Traceback (most recent call last):
  File "\\thecount\plc2_git\OWIS-Mainboard-Software\ps90_test\python_scripts\usbtest.py", line 2, in <module>
    r = usb.core.find(find_all=True)
  File "usb\core.py", line 1297, in find
usb.core.NoBackendError: No backend available
[468] Failed to execute script usbtest
```

This error message is typically issued if the DLL is not found.

**Comment by skoehler** [comment]
I upgraded to python 3.9. For now, I cannot reproduce the problem anymore. Also turns out that `--add-binary ../libusb-1.0.dll;.` is not required. Probably some trivial mistake on my side.
