### ISSUE TITLE
ModuleNotFoundError xml.etree

### ISSUE THREAD

**Issue by StefanoGITA** [pyinstaller/pyinstaller#5365]
## Description of the issue  
Hi,
when i try to use pyinstaller with my script that use the libs **xmlschema** and **lxml** on the run of the exe that I created i gotten this error:
`ModuleNotFoundError: No module named 'xml.etree'`

## Context information (for bug reports)
INFO: PyInstaller: 4.1
INFO: Python: 3.7.2
INFO: Platform: Windows-10-10.0.18362-SP0
INFO: UPX is not available.
INFO: Extending PYTHONPATH with paths

## General Info
To try to avoid the issue I added to my spec the hiddenimports for that libs: `hiddenimports=['xmlschema', 'lxml'],`  
but this haven't resolved the issue.  
I'm using **--onedir mode** and I've also setted: `upx=False`
I've tryed with the developing version (4.2.dev0) but i got the same error.
The debug mode don't give me more detailts (of the error) compared to _standard_ compile execution.

The error rise in on the row where there is the import of the xmlschema.

### Python script import stack  
This is the import stack of my script:
```
from datetime import datetime
from lib.encdec import EncryptDecrypt, base64
from copy import deepcopy
import json, os, sys
import argparse, glob, shutil
import webbrowser
import xmlschema
import lxml.etree as ET
```

### Error Gotten
This is the error on fattEle.exe calls:
```
fattEle.exe -h
Traceback (most recent call last):
  File "fattEle.py", line 17, in <module>
  File "d:\home-pyprojects\fattele\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
    exec(bytecode, module.__dict__)
  File "xmlschema\__init__.py", line 13, in <module>
  File "d:\home-pyprojects\fattele\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
    exec(bytecode, module.__dict__)
  File "xmlschema\etree.py", line 56, in <module>
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'xml.etree'
[19696] Failed to execute script fattEle
```

### pyinstaller.exe output   
This is the output of the pyinstaller.exe:
```
63 INFO: PyInstaller: 4.2.dev0
63 INFO: Python: 3.7.2
65 INFO: Platform: Windows-10-10.0.18362-SP0
69 DEBUG: Testing for UPX ...
71 INFO: UPX is not available.
105 DEBUG: script: fattEle.py
106 INFO: Extending PYTHONPATH with paths
['d:\\Home-pyProjects\\FattEle',
 'C:\\Windows\\SysWOW64\\downlevel\\api-ms-win-core-path-l1-1-0.dll',
 'd:\\Home-pyProjects\\FattEle\\lib']
115 INFO: checking Analysis
116 INFO: Building Analysis because Analysis-00.toc is non existent
116 INFO: Initializing module dependency graph...
125 INFO: Caching module graph hooks...
140 INFO: Analyzing base_library.zip ...
141 DEBUG: Collecting submodules for collections
253 DEBUG: collect_submodules - Found submodules: {'collections', 'collections.abc'}
253 DEBUG: Collecting submodules for encodings
349 DEBUG: collect_submodules - Found submodules: {'encodings.shift_jis', 'encodings.mac_greek', 'encodings.cp862', 'encodings.iso8859_9', 'encodings.cp850', 'encodings.utf_32', 'encodings.latin_1', 'encodings.mac_roman', 'encodings.cp932', 'encodings.koi8_u', 'encodings.cp500', 'encodings.mac_latin2', 'encodings.cp1256', 'encodings.cp1140', 'encodings.iso2022_jp_2004', 'encodings.mac_arabic', 'encodings.cp864', 'encodings.cp273', 'encodings.big5', 'encodings.iso8859_4', 'encodings.cp856', 'encodings.utf_16', 'encodings.cp1255', 'encodings.idna', 'encodings.shift_jis_2004', 'encodings.undefined', 'encodings.cp865', 'encodings.iso8859_6', 'encodings.cp949', 'encodings.aliases', 'encodings.cp1006', 'encodings.iso2022_jp_ext', 'encodings.shift_jisx0213', 'encodings.kz1048', 'encodings.mac_cyrillic', 'encodings.cp869', 'encodings.mac_croatian', 'encodings.rot_13', 'encodings.cp866', 'encodings', 'encodings.gbk', 'encodings.iso2022_jp_1', 'encodings.cp1026', 'encodings.quopri_codec', 'encodings.cp855', 'encodings.iso8859_14', 'encodings.cp1253', 'encodings.iso8859_1', 'encodings.mac_turkish', 'encodings.iso8859_7', 'encodings.cp1258', 'encodings.euc_jis_2004', 'encodings.cp874', 'encodings.cp950', 'encodings.utf_32_le', 'encodings.cp737', 'encodings.mac_iceland', 'encodings.palmos', 'encodings.hp_roman8', 'encodings.cp1251', 'encodings.iso8859_16', 'encodings.cp852', 'encodings.raw_unicode_escape', 'encodings.cp1250', 'encodings.iso8859_11', 'encodings.punycode', 'encodings.cp037', 'encodings.hex_codec', 'encodings.iso8859_10', 'encodings.cp65001', 'encodings.charmap', 'encodings.cp775', 'encodings.utf_8', 'encodings.zlib_codec', 'encodings.utf_7', 'encodings.cp437', 'encodings.uu_codec', 'encodings.iso8859_2', 'encodings.johab', 'encodings.unicode_escape', 'encodings.utf_16_be', 'encodings.euc_kr', 'encodings.iso2022_kr', 'encodings.utf_32_be', 'encodings.iso2022_jp', 'encodings.mac_romanian', 'encodings.mbcs', 'encodings.iso8859_8', 'encodings.iso8859_3', 'encodings.base64_codec', 'encodings.cp861', 'encodings.cp863', 'encodings.cp1254', 'encodings.cp1257', 'encodings.mac_centeuro', 'encodings.oem', 'encodings.cp875', 'encodings.ascii', 'encodings.bz2_codec', 'encodings.cp1252', 'encodings.cp860', 'encodings.iso8859_15', 'encodings.iso2022_jp_2', 'encodings.tis_620', 'encodings.koi8_t', 'encodings.cp857', 'encodings.euc_jp', 'encodings.mac_farsi', 'encodings.unicode_internal', 'encodings.gb2312', 'encodings.cp424', 'encodings.cp720', 'encodings.big5hkscs', 'encodings.iso8859_13', 'encodings.iso8859_5', 'encodings.utf_8_sig', 'encodings.cp858', 'encodings.hz', 'encodings.euc_jisx0213', 'encodings.gb18030', 'encodings.cp1125', 'encodings.utf_16_le', 'encodings.iso2022_jp_3', 'encodings.koi8_r', 'encodings.ptcp154'}
3149 INFO: Caching module dependency graph...
3195 DEBUG: Adding python files to base_library.zip
3310 INFO: running Analysis Analysis-00.toc
3310 DEBUG: Analyzing d:\home-pyprojects\fattele\venv\scripts\python.exe
3314 DEBUG: Dependent assemblies of d:\home-pyprojects\fattele\venv\scripts\python.exe:
3315 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
3315 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\home-pyprojects\fattele\venv\scripts\python.exe
3316 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
3324 DEBUG: Skipping ADVAPI32.dll dependency of python.exe
3328 DEBUG: Skipping VERSION.dll dependency of python.exe
3331 DEBUG: Skipping KERNEL32.dll dependency of python.exe
3340 INFO: Analyzing fattEle.py
5045 DEBUG: Hidden import 'xmlschema' already found
5045 DEBUG: Hidden import 'lxml' already found
5045 DEBUG: Hidden import 'codecs' already found
5045 INFO: Processing module hooks...
5045 INFO: Loading module hook 'hook-lxml.etree.py' from 'd:\\home-pyprojects\\fattele\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
5052 INFO: Loading module hook 'hook-difflib.py' from 'd:\\home-pyprojects\\fattele\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
5052 INFO: Excluding import of doctest from module difflib
5052 INFO: Loading module hook 'hook-encodings.py' from 'd:\\home-pyprojects\\fattele\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
5052 DEBUG: Collecting submodules for encodings
5152 DEBUG: collect_submodules - Found submodules: {'encodings.shift_jis', 'encodings.mac_greek', 'encodings.cp862', 'encodings.iso8859_9', 'encodings.cp850', 'encodings.utf_32', 'encodings.latin_1', 'encodings.mac_roman', 'encodings.cp932', 'encodings.koi8_u', 'encodings.cp500', 'encodings.mac_latin2', 'encodings.cp1256', 'encodings.cp1140', 'encodings.iso2022_jp_2004', 'encodings.mac_arabic', 'encodings.cp864', 'encodings.cp273', 'encodings.big5', 'encodings.iso8859_4', 'encodings.cp856', 'encodings.utf_16', 'encodings.cp1255', 'encodings.idna', 'encodings.shift_jis_2004', 'encodings.undefined', 'encodings.cp865', 'encodings.iso8859_6', 'encodings.cp949', 'encodings.aliases', 'encodings.cp1006', 'encodings.iso2022_jp_ext', 'encodings.shift_jisx0213', 'encodings.kz1048', 'encodings.mac_cyrillic', 'encodings.cp869', 'encodings.mac_croatian', 'encodings.rot_13', 'encodings.cp866', 'encodings', 'encodings.gbk', 'encodings.iso2022_jp_1', 'encodings.cp1026', 'encodings.quopri_codec', 'encodings.cp855', 'encodings.iso8859_14', 'encodings.cp1253', 'encodings.iso8859_1', 'encodings.mac_turkish', 'encodings.iso8859_7', 'encodings.cp1258', 'encodings.euc_jis_2004', 'encodings.cp874', 'encodings.cp950', 'encodings.utf_32_le', 'encodings.cp737', 'encodings.mac_iceland', 'encodings.palmos', 'encodings.hp_roman8', 'encodings.cp1251', 'encodings.iso8859_16', 'encodings.cp852', 'encodings.raw_unicode_escape', 'encodings.cp1250', 'encodings.iso8859_11', 'encodings.punycode', 'encodings.cp037', 'encodings.hex_codec', 'encodings.iso8859_10', 'encodings.cp65001', 'encodings.charmap', 'encodings.cp775', 'encodings.utf_8', 'encodings.zlib_codec', 'encodings.utf_7', 'encodings.cp437', 'encodings.uu_codec', 'encodings.iso8859_2', 'encodings.johab', 'encodings.unicode_escape', 'encodings.utf_16_be', 'encodings.euc_kr', 'encodings.iso2022_kr', 'encodings.utf_32_be', 'encodings.iso2022_jp', 'encodings.mac_romanian', 'encodings.mbcs', 'encodings.iso8859_8', 'encodings.iso8859_3', 'encodings.base64_codec', 'encodings.cp861', 'encodings.cp863', 'encodings.cp1254', 'encodings.cp1257', 'encodings.mac_centeuro', 'encodings.oem', 'encodings.cp875', 'encodings.ascii', 'encodings.bz2_codec', 'encodings.cp1252', 'encodings.cp860', 'encodings.iso8859_15', 'encodings.iso2022_jp_2', 'encodings.tis_620', 'encodings.koi8_t', 'encodings.cp857', 'encodings.euc_jp', 'encodings.mac_farsi', 'encodings.unicode_internal', 'encodings.gb2312', 'encodings.cp424', 'encodings.cp720', 'encodings.big5hkscs', 'encodings.iso8859_13', 'encodings.iso8859_5', 'encodings.utf_8_sig', 'encodings.cp858', 'encodings.hz', 'encodings.euc_jisx0213', 'encodings.gb18030', 'encodings.cp1125', 'encodings.utf_16_le', 'encodings.iso2022_jp_3', 'encodings.koi8_r', 'encodings.ptcp154'}
5152 INFO: Loading module hook 'hook-heapq.py' from 'd:\\home-pyprojects\\fattele\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
5152 INFO: Excluding import of doctest from module heapq
5152 INFO: Loading module hook 'hook-pickle.py' from 'd:\\home-pyprojects\\fattele\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
5152 INFO: Excluding import of argparse from module pickle
5152 INFO: Loading module hook 'hook-xml.py' from 'd:\\home-pyprojects\\fattele\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
5230 DEBUG: Looking for egg data files...
5230 INFO: Looking for ctypes DLLs
5230 INFO: Analyzing run-time hooks ...
5253 INFO: Looking for dynamic libraries
5254 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\_bz2.pyd
5255 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\_bz2.pyd:
5257 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5258 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5266 DEBUG: Adding python37.dll dependency of _bz2.pyd from c:\Program Files\Python\Python37\python37.dll
5271 DEBUG: Adding VCRUNTIME140.dll dependency of _bz2.pyd from c:\Program Files\Python\Python37\VCRUNTIME140.dll
5274 DEBUG: Skipping KERNEL32.dll dependency of _bz2.pyd
5281 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\unicodedata.pyd
5282 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\unicodedata.pyd:
5283 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5286 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5300 DEBUG: Skipping KERNEL32.dll dependency of unicodedata.pyd
5305 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\select.pyd
5307 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\select.pyd:
5307 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5308 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5318 DEBUG: Skipping KERNEL32.dll dependency of select.pyd
5324 DEBUG: Skipping WS2_32.dll dependency of select.pyd
5325 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\_hashlib.pyd
5326 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\_hashlib.pyd:
5329 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5330 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5342 DEBUG: Adding libcrypto-1_1-x64.dll dependency of _hashlib.pyd from c:\Program Files\Python\Python37\DLLs\libcrypto-1_1-x64.dll
5345 DEBUG: Skipping KERNEL32.dll dependency of _hashlib.pyd
5348 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\_socket.pyd
5349 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\_socket.pyd:
5350 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5351 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5368 DEBUG: Skipping KERNEL32.dll dependency of _socket.pyd
5374 DEBUG: Skipping WS2_32.dll dependency of _socket.pyd
5374 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\_ssl.pyd
5376 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\_ssl.pyd:
5379 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5380 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5389 DEBUG: Adding libssl-1_1-x64.dll dependency of _ssl.pyd from c:\Program Files\Python\Python37\DLLs\libssl-1_1-x64.dll
5401 DEBUG: Skipping KERNEL32.dll dependency of _ssl.pyd
5407 DEBUG: Skipping CRYPT32.dll dependency of _ssl.pyd
5411 DEBUG: Skipping WS2_32.dll dependency of _ssl.pyd
5411 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\pyexpat.pyd
5413 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\pyexpat.pyd:
5414 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5415 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5431 DEBUG: Skipping KERNEL32.dll dependency of pyexpat.pyd
5436 DEBUG: Analyzing d:\home-pyprojects\fattele\venv\lib\site-packages\lxml\etree.cp37-win_amd64.pyd
5461 DEBUG: Skipping ADVAPI32.dll dependency of etree.cp37-win_amd64.pyd
5468 DEBUG: Skipping KERNEL32.dll dependency of etree.cp37-win_amd64.pyd
5475 DEBUG: Skipping WS2_32.dll dependency of etree.cp37-win_amd64.pyd
5479 DEBUG: Analyzing d:\home-pyprojects\fattele\venv\lib\site-packages\lxml\_elementpath.cp37-win_amd64.pyd
5492 DEBUG: Skipping KERNEL32.dll dependency of _elementpath.cp37-win_amd64.pyd
5493 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\_contextvars.pyd
5501 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\_contextvars.pyd:
5501 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5504 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5514 DEBUG: Skipping KERNEL32.dll dependency of _contextvars.pyd
5516 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\_decimal.pyd
5519 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\_decimal.pyd:
5520 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5521 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5540 DEBUG: Skipping KERNEL32.dll dependency of _decimal.pyd
5548 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\_lzma.pyd
5549 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\DLLs\_lzma.pyd:
5549 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5550 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5564 DEBUG: Skipping KERNEL32.dll dependency of _lzma.pyd
5567 DEBUG: Analyzing c:\Program Files\Python\Python37\python37.dll
5568 DEBUG: Dependent assemblies of c:\Program Files\Python\Python37\python37.dll:
5568 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5570 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
5592 DEBUG: Skipping VERSION.dll dependency of python37.dll
5602 DEBUG: Skipping SHLWAPI.dll dependency of python37.dll
5611 DEBUG: Skipping ADVAPI32.dll dependency of python37.dll
5623 DEBUG: Skipping KERNEL32.dll dependency of python37.dll
5629 DEBUG: Skipping WS2_32.dll dependency of python37.dll
5631 DEBUG: Analyzing c:\Program Files\Python\Python37\VCRUNTIME140.dll
5643 DEBUG: Skipping KERNEL32.dll dependency of VCRUNTIME140.dll
5648 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\libcrypto-1_1-x64.dll
5683 DEBUG: Skipping USER32.dll dependency of libcrypto-1_1-x64.dll
5694 DEBUG: Skipping ADVAPI32.dll dependency of libcrypto-1_1-x64.dll
5700 DEBUG: Skipping KERNEL32.dll dependency of libcrypto-1_1-x64.dll
5706 DEBUG: Skipping WS2_32.dll dependency of libcrypto-1_1-x64.dll
5709 DEBUG: Analyzing c:\Program Files\Python\Python37\DLLs\libssl-1_1-x64.dll
5722 DEBUG: Skipping KERNEL32.dll dependency of libssl-1_1-x64.dll
5729 INFO: Looking for eggs
5730 INFO: Using Python library c:\Program Files\Python\Python37\python37.dll
5730 INFO: Found binding redirects:
[]
5753 INFO: Warnings written to ..\build\fattEle\warn-fattEle.txt
5875 INFO: Graph cross-reference written to ..\build\fattEle\xref-fattEle.html
5922 INFO: Graph drawing written to ..\build\fattEle\graph-fattEle.dot
5967 INFO: Appending 'datas' from .spec
6000 DEBUG: compiled c:\Program Files\Python\Python37\lib\struct.py
6002 INFO: checking PYZ
6003 INFO: Building PYZ because PYZ-00.toc is non existent
6006 INFO: Building PYZ (ZlibArchive) ..\build\fattEle\PYZ-00.pyz
6989 INFO: Building PYZ (ZlibArchive) ..\build\fattEle\PYZ-00.pyz completed successfully.
7004 INFO: checking PKG
7004 INFO: Building PKG because PKG-00.toc is non existent
7004 INFO: Building PKG (CArchive) PKG-00.pkg
7020 DEBUG: Compiling d:\home-pyprojects\fattele\venv\lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py
7020 DEBUG: Compiling d:\home-pyprojects\fattele\venv\lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py
7020 DEBUG: Compiling d:\Home-pyProjects\FattEle\fattEle.py
7020 DEBUG: Compiling d:\Home-pyProjects\FattEle\fattEle.py
7321 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
7336 INFO: Bootloader d:\home-pyprojects\fattele\venv\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
7336 INFO: checking EXE
7336 INFO: Building EXE because EXE-00.toc is non existent
7336 INFO: Building EXE from EXE-00.toc
7336 INFO: Appending archive to EXE ..\build\fattEle\fattEle.exe
8493 INFO: Building EXE from EXE-00.toc completed successfully.
8508 INFO: checking COLLECT
8508 INFO: Building COLLECT because COLLECT-00.toc is non existent
8524 INFO: Building COLLECT COLLECT-00.toc
9327 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

## Help request
How is possibile to do to resolve thi issue?

Thanks

Stefano G.

**Comment by rokm** [comment]
You'll need to add `xml.etree` and `xml.etree.ElementTree` to `hiddenimports`. You can do it on command-line `pyinstaller --hidden-import xml.etree --hidden-import xml.etree.ElementTree ...`

But it's probably better to do it your .spec file because you'll also need to collect data files for `xmlschema`.

So add this at the top of your .spec file:
```python
from PyInstaller.utils.hooks import collect_data_files
hiddenimports = ['xml.etree', 'xml.etree.ElementTree']
datas = collect_data_files('xmlschema')

...
```
and then pass `hiddenimports` and `datas` to `Analysis`.

(If you encounter any other missing modules from `xml.etree`, then you can use `hiddenimports = collect_submodules('xml.etree')` to try automatically collecting them all)

**Comment by alxdrdelaporte** [comment]
Hi,
I am experiencing a very similar issue but the workarounds provided didn't solve it.
Should I open a new issue or can I describe it here?

**Comment by rokm** [comment]
@alxdrdelaporte please open a new issue, as this one will be closed soon due to stale-by-author state.
