### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Slimer210** [pyinstaller/pyinstaller#5387]
This is the output. I'm not sure why I can't compile the project.
> 90 INFO: PyInstaller: 4.1
90 INFO: Python: 3.9.0
91 INFO: Platform: Windows-10-10.0.19041-SP0
97 INFO: wrote C:\Users\dell\Documents\Python Music Player\python-music-player\main.spec
104 INFO: UPX is not available.
112 INFO: Extending PYTHONPATH with paths
['C:\\Users\\dell\\Documents\\Python Music Player\\python-music-player',
 'C:\\Users\\dell\\Documents\\Python Music Player\\python-music-player']
pygame 2.0.0 (SDL 2.0.12, python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
169 INFO: checking Analysis
174 INFO: Building Analysis because Analysis-00.toc is non existent
174 INFO: Initializing module dependency graph...
178 INFO: Caching module graph hooks...
190 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
196 INFO: Analyzing base_library.zip ...
Error processing line 1 of c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\matplotlib-3.3.3-py3.9-nspkg.pth:

>Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 169, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "c:\users\dell\appdata\local\programs\python\python39\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "c:\users\dell\appdata\local\programs\python\python39\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "c:\users\dell\appdata\local\programs\python\python39\lib\typing.py", line 26, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "c:\users\dell\appdata\local\programs\python\python39\lib\re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 589, in <module>
    main()
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 576, in main
    known_paths = addsitepackages(known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 359, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 179, in addpackage
    import traceback
  File "c:\users\dell\appdata\local\programs\python\python39\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\dell\appdata\local\programs\python\python39\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\dell\appdata\local\programs\python\python39\lib\tokenize.py", line 32, in <module>
    import re
  File "c:\users\dell\appdata\local\programs\python\python39\lib\re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Error processing line 1 of c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\matplotlib-3.3.3-py3.9-nspkg.pth:

>Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 169, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "c:\users\dell\appdata\local\programs\python\python39\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "c:\users\dell\appdata\local\programs\python\python39\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "c:\users\dell\appdata\local\programs\python\python39\lib\typing.py", line 26, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "c:\users\dell\appdata\local\programs\python\python39\lib\re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 589, in <module>
    main()
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 576, in main
    known_paths = addsitepackages(known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 359, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 179, in addpackage
    import traceback
  File "c:\users\dell\appdata\local\programs\python\python39\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\dell\appdata\local\programs\python\python39\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\dell\appdata\local\programs\python\python39\lib\tokenize.py", line 32, in <module>
    import re
  File "c:\users\dell\appdata\local\programs\python\python39\lib\re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
3208 INFO: Processing pre-find module path hook distutils from 'c:\\users\\dell\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
3210 INFO: distutils: retargeting to non-venv dir 'c:\\users\\dell\\appdata\\local\\programs\\python\\python39\\lib'
6798 INFO: Caching module dependency graph...
6896 INFO: running Analysis Analysis-00.toc
6929 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\dell\appdata\local\programs\python\python39\python.exe
7047 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of c:\users\dell\appdata\local\programs\python\python39\python39.dll
7051 INFO: Analyzing C:\Users\dell\Documents\Python Music Player\python-music-player\main.py
8394 INFO: Processing pre-find module path hook site from 'c:\\users\\dell\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
8395 INFO: site: retargeting to fake-dir 'c:\\users\\dell\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\fake-modules'
15465 INFO: Processing module hooks...
15466 INFO: Loading module hook 'hook-pycparser.py' from 'c:\\users\\dell\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
15468 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'c:\\users\\dell\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
Error processing line 1 of c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\matplotlib-3.3.3-py3.9-nspkg.pth:

>Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 169, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "c:\users\dell\appdata\local\programs\python\python39\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "c:\users\dell\appdata\local\programs\python\python39\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "c:\users\dell\appdata\local\programs\python\python39\lib\typing.py", line 26, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "c:\users\dell\appdata\local\programs\python\python39\lib\re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 589, in <module>
    main()
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 576, in main
    known_paths = addsitepackages(known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 359, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site.py", line 179, in addpackage
    import traceback
  File "c:\users\dell\appdata\local\programs\python\python39\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\dell\appdata\local\programs\python\python39\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\dell\appdata\local\programs\python\python39\lib\tokenize.py", line 32, in <module>
    import re
  File "c:\users\dell\appdata\local\programs\python\python39\lib\re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dell\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "C:\Users\dell\Documents\Python Music Player\python-music-player\main.spec", line 6, in <module>
    a = Analysis(['main.py'],
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 419, in assemble
    self.graph.process_post_graph_hooks()
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\depend\analysis.py", line 367, in process_post_graph_hooks
    module_hook.post_graph()
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\depend\imphook.py", line 447, in post_graph
    self._load_hook_module()
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\depend\imphook.py", line 408, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\compat.py", line 593, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 469, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 969, in load_module
  File "<frozen importlib._bootstrap_external>", line 794, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-win32ctypes.core.py", line 18, in <module>
    cffi_available = exec_statement(
IndexError: list index out of range

**Comment by BoboTiG** [comment]
Maybe https://stackoverflow.com/a/48125118/1117028?

**Comment by real-yfprojects** [comment]
> Maybe https://stackoverflow.com/a/48125118/1117028?

That post links to this [one](https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag).

#### Summary:
Check the out put of the following program:
```python3
import enum
print(enum.__file__)
```

**Comment by BoboTiG** [comment]
My point was `pip uninstall enum34`. It should fix the issue.

**Comment by real-yfprojects** [comment]
This issue should be renamed to `AttributeError: module 'enum' has no attribute 'IntFlag'`.

**Comment by NRVIE** [comment]
I got the same issue, but 'pip uninstall enum34' cannot fix it. CMD just told me that enum34 is not installed at all.

**Comment by bwoodsend** [comment]
Either  pip  and PyInstaller aren't in the same environment or you don't have this issue.
