### ISSUE TITLE
ImportError: DLL load failed while importing qhull

### ISSUE THREAD

**Issue by yao-zheng-yi** [pyinstaller/pyinstaller#5397]
I use pyinstaller in python3.8, the exe can work by using powershell, but not work by cmd and another computer, error information as follow:

Traceback (most recent call last):
  File "detect.py", line 10, in <module>
  File "c:\users\cwy\anaconda3\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "utils_all.py", line 41, in <module>
  File "c:\users\cwy\anaconda3\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "scipy\cluster\__init__.py", line 25, in <module>
  File "c:\users\cwy\anaconda3\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "scipy\cluster\vq.py", line 71, in <module>
  File "c:\users\cwy\anaconda3\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "scipy\spatial\__init__.py", line 98, in <module>
ImportError: DLL load failed while importing qhull: 找不到指定的模块。
[8372] Failed to execute script detect

Anyone know how to slove it?

**Comment by rokm** [comment]
>  ImportError: DLL load failed while importing qhull: 找不到指定的模块。

There's one or more DLLs missing from the frozen application's distribution.

Since you're using anaconda and numpy (either directly or indirectly), that's a likely source of the problem, as our current support for conda is rather broken.

**Comment by yao-zheng-yi** [comment]
@rokm Hi! Thanks for your reply!
If the current support for conda is broken, what can I use instead of conda? Don't most people use conda for pyinstaller?

**Comment by bwoodsend** [comment]
> what can I use instead of conda?

Good old [normal Python](https://www.python.org/downloads/).

> Don't most people use conda for pyinstaller?

Not if they want it to work...

**Comment by rokm** [comment]
>  If the current support for conda is broken, what can I use instead of conda? Don't most people use conda for pyinstaller?

The target setup for PyInstaller (what we mostly develop and test against) is actually official python from python.org and packages from PyPI (i.e., installed via `pip install ...`).

A lot of people probably are trying to use conda and pyinstaller, but results may vary (even more than usual) and support for that is limited, so if you want to use conda, you're mostly on your own. For projects using `numpy`, a very common issue is that `libiomp5md` is not collected, which leads to silent crashes - see https://github.com/pyinstaller/pyinstaller/issues/4968#issuecomment-662075970. 

With your error, this is probably not the cause (yet), but based on the error message, another DLL is missing. `qhull` doesn't seem to have a lot of direct dependencies, so either this is an issue with `mkl` (do you get any errors about `mkl-service` before that last error?) or a mismatch between base microsoft runtime dlls (since conda ships their own copy, one of the files might not be collected, and is also missing (or at incompatible version) on the target system). You will probably have to inspect the DLLs for missing dependencies, e.g., using [dependency walker](https://www.dependencywalker.com/), starting with the `qhull` extension module file in `scipy\spatial`.

**Comment by yao-zheng-yi** [comment]
@rokm @bwoodsend Thanks! I create a new conda env with python 3.7.8 and have solved my problem.
But when I use the exe in computers without CUDA, it can't work. The error as follow
Traceback (most recent call last):
File "detect.py", line 233, in
File "detect.py", line 38, in detect
File "utils_all.py", line 2492, in select_device
AssertionError: CUDA unavailable, invalid device 1 requested

It can work normally if I run my exe with cpu. 
pyinstaller did not include CUDA when run pyinstaller -D  detect.spec?

**Comment by bwoodsend** [comment]
It won't pull in CUDA automatically (irregardless of whether you use the spec or not). You need to `--add-binary=C:\path\to\cuda.dll;.` for every file in CUDA that you need. I've never tried it on CUDA myself but as you're using the spec file you can probably just use something like:
```python
from pathlib import Path

a = Analysis(
    ...,
    binaries=[(str(i), ".") for i in Path(r"C:\path\to\CUDA\installation").rglob("*.dll")],
    ...
)

**Comment by yao-zheng-yi** [comment]
> It won't pull in CUDA automatically (irregardless of whether you use the spec or not). You need to `--add-binary=C:\path\to\cuda.dll;.` for every file in CUDA that you need. I've never tried it on CUDA myself but as you're using the spec file you can probably just use something like:
> 
> ```python
> from pathlib import Path
> 
> a = Analysis(
>     ...,
>     binaries=[(str(i), ".") for i in Path(r"C:\path\to\CUDA\installation").rglob("*.dll")],
>     ...
> )
> ```

Thank you! I have tried your solution and didn't work. I will search another solution, thanks!

**Comment by bwoodsend** [comment]
Oh, well. Do us a favour and post the solution if you find one. You're definitely not the 1st to try to ship CUDA.

**Comment by rokm** [comment]
What DLLs did you try to copy, and from where?

In the `pip` version of `pytorch`, CUDA DLLs are actually included in `site-packages\torch\lib` and since `torch` hook brute-force collects everything, they end up collected as well (in `_MEIPASS\torch\lib`).

In the `conda` version, the CUDA DLLs are installed as part of external `cuda` package into environment's Library directory, e.g. `%USERPROFILE%\anaconda3\envs\%ENV_NAME%\Library\bin`, so you will need to copy them manually (or instruct PyInstaller to do so). At a quick glance, at least the following will need to be copied (either into `_MEIPASS` or into `_MEIPASS\torch\lib`):

* `cublas64_10.dll`
* `cublasLt64_10.dll`
* `cudart64_102.dll`
* `cufft64_10.dll`
* `cufftw64_10.dll`
* `curand64_10.dll`
* `cusolver64_10.dll`
* `cusparse64_10.dll`
* `libiomp5md.dll`
* `libiompstubs5md.dll`
* `nvrtc64_102_0.dll`

(perhaps also: `npp*.dll`, `nvblas64_10.dll`, `nvgraph64_10.dll`, `nvrtc-builtins64_102.dll`, `nvToolsExt64_1.dll`, `nvvm64_33_0.dll`)

**Comment by yao-zheng-yi** [comment]
> What DLLs did you try to copy, and from where?
> 
> In the `pip` version of `pytorch`, CUDA DLLs are actually included in `site-packages\torch\lib` and since `torch` hook brute-force collects everything, they end up collected as well (in `_MEIPASS\torch\lib`).
> 
> In the `conda` version, the CUDA DLLs are installed as part of external `cuda` package into environment's Library directory, e.g. `%USERPROFILE%\anaconda3\envs\%ENV_NAME%\Library\bin`, so you will need to copy them manually (or instruct PyInstaller to do so). At a quick glance, at least the following will need to be copied (either into `_MEIPASS` or into `_MEIPASS\torch\lib`):
> 
> * `cublas64_10.dll`
> * `cublasLt64_10.dll`
> * `cudart64_102.dll`
> * `cufft64_10.dll`
> * `cufftw64_10.dll`
> * `curand64_10.dll`
> * `cusolver64_10.dll`
> * `cusparse64_10.dll`
> * `libiomp5md.dll`
> * `libiompstubs5md.dll`
> * `nvrtc64_102_0.dll`
> 
> (perhaps also: `npp*.dll`, `nvblas64_10.dll`, `nvgraph64_10.dll`, `nvrtc-builtins64_102.dll`, `nvToolsExt64_1.dll`, `nvvm64_33_0.dll`)

I copy all DLLs in Anaconda3\envs\%ENV_NAME%\lib\site-packages\torch\lib, and I also tried to copy all DLLs in Anaconda3\envs\%ENV_NAME%\lib\site-packages\torch\lib and Anaconda3\envs\%ENV_NAME%\Library\bin , still can't success.
And I try to copy the DLLs you said above, could not find cusolver64_10.dll, npp*.dll, nvblas64_10.dll, nvgraph64_10.dll, nvvm64_33_0.dll.

**Comment by bwoodsend** [comment]
There'll be a bunch sitting in `Anaconda3\envs\%ENV_NAME%\Library\bin` too. Unfortunately they're not grouped by what package they're for so you're basically guessing which you need.

**Comment by rokm** [comment]
How did you install `torch` into your environment? 

I think all those DLLs should come with `cudatoolkit-10.2.89` which is what you get if you follow the instructions on https://pytorch.org/get-started/locally - i.e., `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`. 

And I find it odd that `cusolver64_10.dll` would be missing...

**Comment by yao-zheng-yi** [comment]
I installed torch by 
pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by rokm** [comment]
I've now tried to freeze a following test program:
```python
import numpy as np  # or use hiddenimport
import torch
assert torch.cuda.is_available(), 'CUDA not available!'
print('CUDA available')
```
with both python.org+pip and conda+pip environment (in a Windows VM), where everything is installed via pip:
```
[create a venv or a new conda environment, and activate it]

pip install numpy==1.19.3  # 1.19.4 fails a sanity check
pip install pyinstaller
pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

pyinstaller program.py
```
Running the frozen application on my laptop with WIndows and NVIDIA card in both cases reports that CUDA is available.

**Comment by yao-zheng-yi** [comment]
In Windows with CUDA, my exe can work. But in Windows without conda environment and CUDA, it can't work. I want to use my exe in any computers wether it has conda environment, CUDA or python.
So, if I want to run my exe with GPU, the computer must have CUDA?

**Comment by rokm** [comment]
> In Windows with CUDA, my exe can work. 

Is this the same machine that you built on, or a different one? Can you try running on a different machine without conda but with CUDA toolkit installed, just to eliminate any conda-related issues?

> But in Windows without conda environment and CUDA, it can't work.

What GPU are you using there, and what's the version of NVIDIA driver?

>  So, if I want to run my exe with GPU, the computer must have CUDA?

You shouldn't need a CUDA toolkit installed on the target computer (but it does need a NVIDIA driver of sufficient version) - as long as all required CUDA runtime DLLs are bundled with the application.

So if your frozen program works on another computer that does not have conda and python installed, but has CUDA toolkit (10.1) installed, and it doesn't work if CUDA toolkit is not installed, then my guess would be that one of CUDA DLLs is misisng from the frozen application, but I cannot think of why that would happen.

Just to be sure, can try to install python.org (not conda) python and pytorch with pip on your problematic target machine (the one that does not have CUDA nor conda) and try running a simple pytorch demo script there to see if it works?

**Comment by yao-zheng-yi** [comment]
Thank you! I will try your method.

**Comment by bwoodsend** [comment]
@yao-zheng-yi Did you ever get it working?

**Comment by yao-zheng-yi** [comment]
> @yao-zheng-yi Did you ever get it working?

finally, my exe can work on Windows, but if I want to run on GPU, it still can't success.

**Comment by Min-cod** [comment]
delate scipy package and re-download it use command:

pip3 install scipy

**Comment by dengxuankun** [comment]
> @rokm @bwoodsend Thanks! I create a new conda env with python 3.7.8 and have solved my problem. But when I use GPU in computers without CUDA, my exe can't work. The error as follow Traceback (most recent call last): File "detect.py", line 233, in File "detect.py", line 38, in detect File "utils_all.py", line 2492, in select_device AssertionError: CUDA unavailable, invalid device 1 requested
> 
> It can work normally if I run my exe with cpu. pyinstaller did not include CUDA when run pyinstaller -D detect.spec?

How did you solve this problem? Can you describe it in more detail,I have the same problem

**Comment by jrassoul** [comment]
for me i just installed this package (on windows) with conda
`conda install -c conda-forge/label/cf202003 qhull`

website : [anaconda.org/conda-forge/qhull](https://anaconda.org/conda-forge/qhull)
