### ISSUE TITLE
Issue when building a Pytorch based program using Pyinstaller

### ISSUE THREAD

**Issue by piyumalranawaka** [pyinstaller/pyinstaller#5402]
I get the following error when I am trying to build pytorch based program. Any advise on fixing this issue would be greatly appreciated:

Traceback (most recent call last):
  File "/home/piyumal/anaconda3/envs/pytorchenv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "/media/piyumal/UUI/Research/Image Classification/PyTorch/resnet/script.spec", line 20, in <module>
    exe = EXE(pyz,
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 436, in __init__
    self.pkg = PKG(self.toc, cdict=kwargs.get('cdict', None),
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 200, in __init__
    self.__postinit__()
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 286, in assemble
    archive = CArchiveWriter(self.name, srctoc + mytoc,
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/archive/writers.py", line 332, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/archive/writers.py", line 64, in __init__
    self._finalize()
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/archive/writers.py", line 96, in _finalize
    self.save_trailer(toc_pos)
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/archive/writers.py", line 439, in save_trailer
    tocstr = self.toc.tobinary()
  File "/home/piyumal/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/PyInstaller/archive/writers.py", line 262, in tobinary
    rslt.append(struct.pack(self.ENTRYSTRUCT + '%is' % nmlen,
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by bwoodsend** [comment]
@rokm Is that not the error you used to get if you try to squeeze too big a package (>2GB) into a one-file?

**Comment by rokm** [comment]
> @rokm Is that not the error you used to get if you try to squeeze too big a package (>2GB) into a one-file?

It is.

@piyumalranawaka  You're hitting the maximum size limit of 2 GB for `onefile` mode. Take a look at #3939 for possible solutions.

**Comment by piyumalranawaka** [comment]
Thank you very much indeed for your kind advise, I will check into possible solutions :)
