### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by euler0104** [pyinstaller/pyinstaller#5444]
```
from manim import *
config["tex_template"] = TexTemplateLibrary.simple

class OpeningManimExample(Scene):
    def construct(self):
        title = Tex("This is some \\LaTeX")
        basel = MathTex("\\sum_{n=1}^\\infty " "\\frac{1}{n^2} = \\frac{\\pi^2}{6}")
        VGroup(title, basel).arrange(DOWN)
        self.play(
            Write(title),
            FadeInFrom(basel, UP),
        )
        self.wait()

        transform_title = Tex("That was a transform")
        transform_title.to_corner(UP + LEFT)
        self.play(
            Transform(title, transform_title),
            LaggedStart(*map(FadeOutAndShift, basel)),
        )
        self.wait()

        grid = NumberPlane()
        grid_title = Tex("This is a grid")
        grid_title.scale(1.5)
        grid_title.move_to(transform_title)

        self.add(grid, grid_title)  # Make sure title is on top of grid
        self.play(
            FadeOut(title),
            FadeInFrom(grid_title),
            ShowCreation(grid, run_time=3, lag_ratio=0.1),
        )
        self.wait()

        grid_transform_title = Tex(
            "That was a non-linear function \\\\" "applied to the grid"
        )
        grid_transform_title.move_to(grid_title, UL)
        grid.prepare_for_nonlinear_transform()
        self.play(
            grid.animate.apply_function(
                lambda p: p
                        + np.array(
                    [
                        np.sin(p[1]),
                        np.sin(p[0]),
                        0,
                    ]
                )
            ),
            run_time=3,
        )
        self.wait()
        self.play(Transform(grid_title, grid_transform_title))
        self.wait()

OpeningManimExample().render()
```

this is my code. If I run it in pycharm, it works.
but when I convert that to .exe file, it gives me this error

```
Traceback (most recent call last):
  File "main.py", line 3, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 359, in exec_module
  File "manim\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 359, in exec_module
  File "manim\_config\__init__.py", line 17, in <module>
  File "manim\_config\utils.py", line 106, in make_config_parser
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cklee\\AppData\\Local\\Temp\\_MEI87802\\manim\\_config\\default.cfg'
[15776] Failed to execute script main
```

why is this happening?

**Comment by bwoodsend** [comment]
You need to `--add-data="C:\path\to\manim\_config\default.cfg;manim\_config\default.cfg`.

**Comment by euler0104** [comment]
> You need to `--add-data="C:\path\to\manim\_config\default.cfg;manim\_config\default.cfg"`.

gives me

```
101039 INFO: Warnings written to C:\Users\cklee\Desktop\temp\build\asdf\warn-asdf.txt
101631 INFO: Graph cross-reference written to C:\Users\cklee\Desktop\temp\build\asdf\xref-asdf.html
101716 INFO: Appending 'datas' from .spec
Unable to find "C:\path\to\manim\_config\default.cfg" when adding binary and data files.
```

**Comment by euler0104** [comment]
oh btw I did
`pyinstaller -F --add-data="C:\path\to\manim\_config\default.cfg;manim\_config\default.cfg main.py`

**Comment by bwoodsend** [comment]
You have to replace `C:\path\to\manim...` with the real path to that config file inside the `Lib/sitepackages` folder of your Python installation.

**Comment by euler0104** [comment]
> You have to replace `C:\path\to\manim...` with the real path to that config file inside the `Lib/sitepackages` folder of your Python installation.

it used to work fine, just giving other error like AttributeError. but when I installed developer version of pyinstaller to solve that error, it gives
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from manim import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\cklee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "manim\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\cklee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "manim\_config\__init__.py", line 18, in <module>
  File "manim\_config\utils.py", line 107, in make_config_parser
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\cklee\\AppData\\Local\\Temp\\_MEI150002\\manim\\_config\\default.cfg'
[8452] Failed to execute script test
```

**Comment by rokm** [comment]
The destination path for --add-data should probably omit the filename: `--add-data="C:\path\to\manim\_config\default.cfg;manim\_config"`, otherwise you get `manim\_config\default.cfg\default.cfg` in your dist.

**Comment by euler0104** [comment]
> The destination path for --add-data should probably omit the filename: `--add-data="C:\path\to\manim\_config\default.cfg;manim\_config"`, otherwise you get `manim\_config\default.cfg\default.cfg` in your dist.

that gives me
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from manim import *
  File "c:\users\cklee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "manim\__init__.py", line 12, in <module>
  File "c:\users\cklee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "manim\animation\composition.py", line 8, in <module>
  File "c:\users\cklee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "manim\scene\scene.py", line 21, in <module>
  File "c:\users\cklee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "manim\camera\camera.py", line 13, in <module>
  File "c:\users\cklee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "scipy\spatial\__init__.py", line 107, in <module>
  File "c:\users\cklee\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "scipy\spatial\transform\__init__.py", line 19, in <module>
  File "rotation.pyx", line 5, in init scipy.spatial.transform.rotation
ModuleNotFoundError: No module named 'scipy.spatial.transform._rotation_groups'
[5692] Failed to execute script test
```

**Comment by rokm** [comment]
> that gives me
> ModuleNotFoundError: No module named 'scipy.spatial.transform._rotation_groups'

This next issue is the same as #5440, so look there for a fix.

**Comment by TomOfHelatrobus** [comment]
A possible problem might be if you are running pyinstaller outside of a virtual environment and using it to freeze a program in a virtual environment. Exit your virtual environment, uninstall pyinstaller, navigate to your project folder, restart the the virtual environment, then install pyinstaller. inside the virtual environment. You should have a separate install of pyinstaller for each virtual environment. I don't know if you've already thought of that... but if you haven't, it might work.

**Comment by euler0104** [comment]
> A possible problem might be if you are running pyinstaller outside of a virtual environment and using it to freeze a program in a virtual environment. Exit your virtual environment, uninstall pyinstaller, navigate to your project folder, restart the the virtual environment, then install pyinstaller. inside the virtual environment. You should have a separate install of pyinstaller for each virtual environment. I don't know if you've already thought of that... but if you haven't, it might work.

I solved manim issue, now theres new problem
I used
pyinstaller -F --uac-admin --icon=function.ico --add-data="C:\Users\cklee\AppData\Local\Programs\Python\Python38\Lib\site-packages\manim\_config\default.cfg;manim\_config" --add-data="C:\Users\cklee\AppData\Local\Programs\Python\Python38\Lib\site-packages\cairocffi\VERSION;cairocffi" --hidden-import="scipy.spatial.transform._rotation_groups" main.py
for pyinstaller, error is
![image](https://user-images.githubusercontent.com/65996056/106387957-99adcc80-641f-11eb-80e0-eba485e1112d.png)

**Comment by rokm** [comment]
> I solved manim issue, now theres new problem

`cairocffi` is missing the `cairo˙ shared library (DLL). For the unfrozen version, you probably had to ensure that `libcairo-2.dll` was installed and its path was added to `PATH`, as per [docs](https://cairocffi.readthedocs.io/en/stable/overview.html#installing-cairo-on-windows).

You'll probably need to collect this DLL manually for the frozen application (maybe collecting it into program's base directory will suffice, otherwise you may need to adjust `PATH` before you import `cairocffi`.
