### ISSUE TITLE
Modules loaded from local C:\Python27\Lib\site-packages

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#5485]
I'm using PyInstaller in a way where I have 2 `exe` bundled, one is the main program and the other is executed in runtime from the main program using `subprocess.Popen()`.

Everything is work almost every time but in some rare cases the second process is raising and exception while importing a 3rd party module named `networkx` and I get `EOFError` while pickling some data (I assume):
```
[3260] Failed to execute script sbsimulation
Traceback (most recent call last):
  File "sbsimulation.py", line 7, in <module>
  File "C:\PROGRA~1\SAFEBR~1\SAFEBR~1\app\503~1.438\SIMULA~2\safebreach_simulation\simulation.py", line 83, in main
    from safebreach_simulation.task_action_runner import run_action_logic
  File "C:\PROGRA~1\SAFEBR~1\SAFEBR~1\app\503~1.438\SIMULA~2\safebreach_simulation\task_action_runner.py", line 20, in <module>
    from safebreach_simulation.runners import generate_runner, generate_basic_runner
  File "C:\PROGRA~1\SAFEBR~1\SAFEBR~1\app\503~1.438\SIMULA~2\safebreach_simulation\runners\__init__.py", line 1, in <module>
    from safebreach_simulation.runners.runner import Runner, BasicRunner
  File "C:\PROGRA~1\SAFEBR~1\SAFEBR~1\app\503~1.438\SIMULA~2\safebreach_simulation\runners\runner.py", line 1, in <module>
    import pythonect
  File "C:\PROGRA~1\SAFEBR~1\SAFEBR~1\app\503~1.438\SIMULA~2\pythonect\__init__.py", line 34, in <module>
    from pythonect.internal.eval import eval, parse, PythonectException
  File "C:\PROGRA~1\SAFEBR~1\SAFEBR~1\app\503~1.438\SIMULA~2\pythonect\internal\eval.py", line 54, in <module>
    from networkx import DiGraph
  File "`c:\Python27\Lib\site-packages\networkx/__init__.py", line 87, in <module>
  File "c:\Python27\Lib\site-packages\networkx/readwrite/__init__.py", line 14, in <module>
  File "c:\Python27\Lib\site-packages\networkx/readwrite/gml.py", line 46, in <module>
  File "c:\Python27\lib\lib2to3\refactor.py", line 28, in <module>
  File "c:\Python27\lib\lib2to3\fixer_util.py", line 9, in <module>
  File "c:\Python27\lib\lib2to3\pygram.py", line 39, in <module>
  File "c:\Python27\lib\lib2to3\pgen2\driver.py", line 159, in load_packaged_grammar
  File "c:\Python27\lib\lib2to3\pgen2\driver.py", line 134, in load_grammar
  File "c:\Python27\lib\lib2to3\pgen2\grammar.py", line 108, in load
  File "c:\Python27\lib\pickle.py", line 1384, in load
  File "c:\Python27\lib\pickle.py", line 864, in load
  File "c:\Python27\lib\pickle.py", line 886, in load_eof
EOFError
``` 

I'm using an old version of `networkx` and now in a process to upgrade it to a newer one to see if this will fix it, what I can't understands is why in the stacktrace I see that the code is loaded from my bundled dir but the `networkx` is loaded from `c:\Python27\Lib\site-packages\networkx`, is it really loaded from there or is it an issue with how the stack is printed?

I'm not really sure how to reproduce this because it happens on rare cases.

PyInstaller: 3.6
Platform: Windows
Python: 2.7

**Comment by bwoodsend** [comment]
It can only import those modules if `c:\Python27\Lib\site-packages` has somehow found its way into `sys.path`. Do you have `PYTHONPATH` set?
```shell
set PYTHONPATH
```

**Comment by heuripedes** [comment]
@bwoodsend
I believe something similar is happening to me in that some directories not present in or straight out removed from `PYTHONPATH` and `sys.path` still get searched/found by  `_find_module_path` (as reported in the log when using `--log-level=TRACE`). What could be going on?

**Comment by bwoodsend** [comment]
I don't understand what you're saying.

**Comment by arossert** [comment]
@bwoodsend sorry for the late response. 
I’m not manipulating the PATH or PYTHONPATH when running the app, this trace is from a 3rd party module that I do not use directly, can it just be that that traceback is incorrect and show the path from where the module was installed when bundled with pyinstaller? 
(The start of the trace does show the correct path)

**Comment by bwoodsend** [comment]
Hang on, are you trying to use Python 2.7 then? I originally thought that you weren't and that was the error you were reporting but looking back, I dont see where I got that from.

**Comment by arossert** [comment]
Yes, I’m still using Python2.7 for this specific project, does it matter?

**Comment by rokm** [comment]
Are you using `--debug noarchive` or `--debug all` when freezing the application?

It seems that will prevent absolute paths from being removed from collected modules (at least with PyInstaller 3.6 and Python 2.7). For example:

```python
import pickle

obj = {
    'a': 1,
    'b': 2,
    'c': 'test'
}

buf = pickle.dumps(obj)
obj2 = pickle.loads(buf[:-2])
```

Non-debug version:
```
>pyinstaller --clean --noconfirm program.py
[...]
>dist\program\program.exe
Traceback (most recent call last):
  File "program.py", line 10, in <module>
    obj2 = pickle.loads(buf[:-2])
  File "pickle.py", line 1388, in loads
  File "pickle.py", line 864, in load
  File "pickle.py", line 886, in load_eof
EOFError
[5604] Failed to execute script program
```
Debug version:
```
>pyinstaller --clean --noconfirm program.py --debug noarchive
[...]
>dist\program\program.exe
Traceback (most recent call last):
  File "program.py", line 10, in <module>
    obj2 = pickle.loads(buf[:-2])
  File "c:\python27\lib\pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "c:\python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "c:\python27\lib\pickle.py", line 886, in load_eof
    raise EOFError
EOFError
[1672] Failed to execute script program
```

**Comment by arossert** [comment]
@rokm Yes, I do use `--debug noarchive` when building my app (only for develop), is this what caused the traceback to include the local computer path?

**Comment by rokm** [comment]
I think so, because the paths are removed during PYZ archive creation (which is skipped in `noarchive` mode):

https://github.com/pyinstaller/pyinstaller/blob/d7726545e7401a4f8c7ea2eb34317b98168daf82/PyInstaller/building/api.py#L114-L139

But if you want to be really sure, you can try temporarily renaming `c:\python27`  before running the frozen application and see if it still works. Or conversely, try removing `pickle.pyc` or `pickle.pyo` from your frozen application's dist dir while keeping the `c:\python27` intact.

**Comment by arossert** [comment]
Ok, that looks like this is it, I’m using noarchive when for develop so the code can be manipulated, maybe you know if there is a way to only keep some modules not archived? I mean I want my code to be kept out of the archive but I don’t need the 3rd party modules.
