### ISSUE TITLE
Crash when running executable for the first time only with pywinauto

### ISSUE THREAD

**Issue by sharpordie** [pyinstaller/pyinstaller#5512]
## Description of the issue

I am using latest pywinauto and pyinstaller.  
I have this weird error when I run the produced one-file or one-dir executable for the **first time only**.
```
Traceback (most recent call last):
  File "autostudio.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\admin\documents\projects\autostudio\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
    exec(bytecode, module.__dict__)
  File "packages\android_studio.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\admin\documents\projects\autostudio\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
    exec(bytecode, module.__dict__)
  File "pywinauto\__init__.py", line 89, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\admin\documents\projects\autostudio\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
    exec(bytecode, module.__dict__)
  File "pywinauto\findwindows.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\admin\documents\projects\autostudio\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
    exec(bytecode, module.__dict__)
  File "pywinauto\controls\__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\admin\documents\projects\autostudio\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
    exec(bytecode, module.__dict__)
  File "pywinauto\controls\uiawrapper.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\admin\documents\projects\autostudio\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
    exec(bytecode, module.__dict__)
  File "pywinauto\uia_defines.py", line 181, in <module>
  File "pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
  File "pywinauto\uia_defines.py", line 50, in __call__
  File "pywinauto\uia_defines.py", line 60, in __init__
  File "comtypes\client\_generate.py", line 118, in GetModule
  File "comtypes\client\_generate.py", line 183, in _CreateWrapper
  File "comtypes\tools\tlbparser.py", line 750, in generate_module
  File "comtypes\tools\codegenerator.py", line 261, in generate_code
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'UIAutomationCore.dll'
[9132] Failed to execute script autostudio
```
I can reproduce the error by purging the `comtypes_cache` directory from the Windows temp directory.

So it seems the executable extracts something to the temp directory but can't use it directly.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: 3.8.7
* Platform: Windows 10

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**.

I have exactly the same issue.

### A minimal example program which shows the error

```
from pywinauto import *

if __name__ == "__main__":
    desktop = Desktop(backend="uia")
```

**Comment by sharpordie** [comment]
It seems that it is comtypes the culprit.
Installing the previous version of comtypes `1.1.7` solves the problem.

**Comment by rokm** [comment]
This indeed looks related to `comtypes` - the same issue also occurs with unfrozen version of your minimal example when it is run for the first time after `comtypes` 1.1.8 is installed in a clean environment. That failing first run creates `site-apckages\comtypes\gen` folder, which is probably why the failing codepath is avoided on subsequent runs. And as you say, it seems to pass without error with `comtypes` 1.1.7.

At any rate, this has nothing to do with pyinstaller.
