### ISSUE TITLE
Problem with https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong

### ISSUE THREAD

**Issue by RS357** [pyinstaller/pyinstaller#5520]
When I run this command:
`pip install google-cloud-core==0.29.1 google-cloud-pubsub==0.40.0 PyInstaller==3.4 && echo "from google.cloud import pubsub_v1" > test.py && pyinstaller --debug=imports --onefile test.py && ./dist/test`

or this command:

`pip install google-cloud-core==0.29.1 google-cloud-pubsub==0.40.0 PyInstaller && echo "from google.cloud import pubsub_v1" > test.py && pyinstaller --debug=imports --onefile test.py && ./dist/test`

...the following TraceBack is returned:

```Bash
5239 INFO: Building PYZ because PYZ-00.toc is non existent
5239 INFO: Building PYZ (ZlibArchive) /home/riz/Desktop/new/build/test/PYZ-00.pyz
Traceback (most recent call last):
  File "/home/riz/.virtualenvs/pyinstaller/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 654, in strip_paths_in_code
    consts = tuple(
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 655, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/home/riz/.virtualenvs/pyinstaller/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 662, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
```

**Comment by RS357** [comment]
Opened in error
