### ISSUE TITLE
ImportError: Loader FrozenImporter cannot handle module

### ISSUE THREAD

**Issue by git-chenjiqing** [pyinstaller/pyinstaller#5587]
Hello，I work on raspberry pie 4B
After packing, I still ran it on raspberry pie. At first, it was OK. Suddenly, one day later, he made a mistake
#### ERROR ####
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyinstaller-4.0-py3.7.egg/PyInstaller/loader/pyimod03_impers.py", line 302, in get_code
    return self._pyz_archive.extract(fullname)[1]
  File "/usr/local/lib/python3.7/dist-packages/pyinstaller-4.0-py3.7.egg/PyInstaller/loader/pyimod02_arce.py", line 325, in extract
    obj = zlib.decompress(obj)
zlib.error: Error -3 while decompressing data: incorrect data check

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "qt5-browser.py", line 12, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pyinstaller-4.0-py3.7.egg/PyInstaller/loader/pyimod03_impers.py", line 473, in exec_module
    bytecode = self.get_code(spec.loader_state)
  File "/usr/local/lib/python3.7/dist-packages/pyinstaller-4.0-py3.7.egg/PyInstaller/loader/pyimod03_impers.py", line 306, in get_code
    ) from e
ImportError: Loader FrozenImporter cannot handle module qt5Source
[932] Failed to execute script qt5-browser
```
pyrcc5 -o qt5Source.py qt5-source.qrc
In Qt5 browser, I import qt5source

**Comment by rokm** [comment]
Does it work again if you rebuild the application?

>  After packing, I still ran it on raspberry pie. At first, it was OK. Suddenly, one day later, he made a mistake

If it worked fine at first but stopped working later, this probably means that (part of) executable got corrupted. Filesystem integrity issues, perhaps?
