### ISSUE TITLE
How PyInstaller packing librosa

### ISSUE THREAD

**Issue by door5719** [pyinstaller/pyinstaller#5588]
In mac10.15, python3.7.10,librosa ==0.8.0
I just use code as：
...
from PyQt5 import QtCore
import librosa
import sys
...

and command line : pyinstaller -F player.py
completed successfully.
After this process ,i run ./player, I get as follow
,

Traceback (most recent call last):
File "player.py", line 5, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "librosa/init.py", line 211, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "librosa/core/init.py", line 5, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "librosa/core/convert.py", line 7, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "librosa/core/notation.py", line 8, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "librosa/util/init.py", line 84, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "librosa/util/files.py", line 34, in
File "pooch/core.py", line 600, in load_registry
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/7s/qrf9bqgj7k988g8t0g7m_vrr0000gn/T/_MEIa7KVri/librosa/util/example_data/registry.txt'

how to deal with this?

**Comment by rokm** [comment]
You need to collect data files from `librosa`, e.g. by creating a hook for it. Create a file called `extra-hooks/hook-librosa.py` with the following contents:
```python
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('librosa')
```
and the run `pyinstaller --additional-hooks=extra-hooks [...]`

**Comment by door5719** [comment]
> You need to collect data files from `librosa`, e.g. by creating a hook for it. Create a file called `extra-hooks/hook-librosa.py` with the following contents:
> 
> ```python
> from PyInstaller.utils.hooks import collect_data_files
> datas = collect_data_files('librosa')
> ```
> 
> and the run `pyinstaller --additional-hooks=extra-hooks [...]`

I run hook-librosa.py and get：
[('/usr/local/lib/python3.7/site-packages/librosa/util/example_data/index.json', 'librosa/util/example_data'), ('/usr/local/lib/python3.7/site-packages/librosa/util/example_data/registry.txt', 'librosa/util/example_data')]

your means is 
run pyinstaller --additional-hooks= [('/usr/local/lib/python3.7/site-packages/librosa/util/example_data/index.json', 'librosa/util/example_data'), ('/usr/local/lib/python3.7/site-packages/librosa/util/example_data/registry.txt', 'librosa/util/example_data')]？
could you  give me a  detailed way to write it？
Thank you

**Comment by rokm** [comment]
Once you create `extra-hook/hook-librosa.py`, don't run it - run your pyinstaller command like this:

```
pyinstaller -F player.py --additional-hooks=extra-hooks
```

**Comment by door5719** [comment]
> Once you create `extra-hook/hook-librosa.py`, don't run it. Instead, run `pyinstaller` command and pass it the `extra-hooks` directory as `--additional-hooks` argument, like this:
> 
> ```
> pyinstaller -F player.py --additional-hooks=extra-hooks
> ```

Thanks for your detailed  demo, your way works well.

from PyInstaller.utils.hooks import collect_data_files, collect_submodules
datas = collect_data_files('librosa')
hiddenimports = collect_submodules('sklearn')

when using:
pyinstaller -F player.py --additional-hooks=extra-hooks

...
ERROR: Can not find path ./libtbb.dylib (needed by /usr/local/lib/python3.7/site-packages/numba/np/ufunc/tbbpool.cpython-37m-darwin.so)
....
INFO: Building EXE from EXE-00.toc completed successfully.

and 
./player
this package is working.

**Comment by rokm** [comment]
>  ERROR: Can not find path ./libtbb.dylib (needed by /usr/local/lib/python3.7/site-packages/numba/np/ufunc/tbbpool.cpython-37m-darwin.so)

It seems to me that `numba` package doesn't actually provide `libtbb.dylib` (it's linked as `@rpath/libtbb.dylib`, but `tbbpool.cpython-37m-darwin.so` doesn't actually have any `rpath` set, either). So you probably can't do `from numba.np.ufunc import tbbpool` in python, anyway. 

Which means that you can ignore that error message as irrelevant.
