### ISSUE TITLE
Cannot run exe on different machine- FileNotFound on embedded subfolder

### ISSUE THREAD

**Issue by PouncingZebra** [pyinstaller/pyinstaller#5595]
## Description of the issue
**Importing of modules is working as expected, sub folder inside module is not importing correctly.**
## Context information (for bug reports)

* Output of `pyinstaller --version`: **4.2**
* Version of Python:  **3.9.2**
* Platform: **Windows 10**
* Did you also try this on another platform? Does it work there? **Works on my Windows 10 machine, does not work on other machines.**

### A minimal example program which shows the error

```
from canlib import Frame #this one works
from canlib import canlib
from canlib.canlib import ChannelData
import pandas as pd
import sys
print("Hello")
```
**Please note: removing the second and third import statements enables this executable to run on other machines. The executable runs perfectly on my machine with all 5 imports. Canlib was installed using pip, everything is up to date.

Lib/site-packagers/canlib is a folder that contains Frame.py and another subfolder, also called canlib. Lib/site-packagers/canlib/canlib contains channeldata.py

Both canlib and canlib/canlib have __init__.py in them.
**
### Stacktrace / full error message

```
ReoTest.exe
Traceback (most recent call last):
  File "ReoTest.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "canlib\canlib\__init__.py", line 13, in <module>
    from ._channel import canChannel
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "canlib\canlib\_channel.py", line 2, in <module>
    from . import channel
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "canlib\canlib\channel.py", line 11, in <module>
    from . import iopin
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "canlib\canlib\iopin.py", line 12, in <module>
    from . import wrapper
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "canlib\canlib\wrapper.py", line 14, in <module>
    _ct_dll = dllLoader.load_dll(win_name='canlib32.dll',
  File "canlib\dllLoader.py", line 147, in load_dll
    aKey = winreg.OpenKey(aReg, aKeyName)
FileNotFoundError: [WinError 2] The system cannot find the file specified
[7860] Failed to execute script ReoTest
```

**Comment by rokm** [comment]
```python
[...]

def load_dll(win_name=None, linux_name=None):
    """Load dll or shared object file as appropriate.

    On Windows:
        If environment variable 'KVDLLPATH' is set, will try and load DLL named
        win_name from that directory. Otherwise checks registry for CANlib SDK
        installation directory.

    On Linux:
        If environment variable 'KVDLLPATH' is set, will try and load shared
        object library named linux_name from that directory. Otherwise let
        the OS try and find a matching shared library object.
    """
    dir = os.getcwd()
    kvdllpath = os.environ.get('KVDLLPATH')
    installDir = kvdllpath
    if installDir is None or installDir == '':
        if sys.platform.startswith('win'):
            if (platform.architecture()[0] == '32bit'):
                aKeyName = r"SOFTWARE\KVASER AB\CanlibSDK"
            else:
                aKeyName = r"SOFTWARE\Wow6432Node\KVASER AB\CanlibSDK"
            aReg = winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE)
            aKey = winreg.OpenKey(aReg, aKeyName)
            [...]
```

So either you need to set `KVDLLPATH` to point to to the `canlib32.dll` (which is very likely not automatically collected anyway, so you'll need to collect it yourself) or you'll need to ensure that the target machine has `Kvaser Drivers for Windows` installed, as per [instructions on pypi page](https://pypi.org/project/canlib). 

The error you're currently getting is because `KVDLLPATH` is not set, so the `canlib` loader is trying to fall back to reading the registry key, which does not exist, either.

Setting `KVDLLPATH` can probably be done inside your python code via `os.environ['KVDLLPATH]' = ...` before you do `import canlib.calib`. And you'll probably [have to tie the path to `sys._MEIPASS`](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html?ld-library-path-libpath-considerations#using-file).

**Comment by PouncingZebra** [comment]
Thank you.

Added: 
`import os
from os import path

bundle_dir = getattr(sys, '_MEIPASS', path.abspath(path.dirname(__file__)))
path_to_dat = path.abspath(path.join(bundle_dir, 'C:\Program Files\Kvaser\Drivers\32\canlib32.dll'))
os.environ['KVDLLPATH'] = path_to_dat
print(os.environ['KVDLLPATH'])`

before importing canlib and that did the trick.
