### ISSUE TITLE
using pyinstaller with pydantic>1.7.2

### ISSUE THREAD

**Issue by lowmann15** [pyinstaller/pyinstaller#5603]
## Description of the issue

We encountered an issue trying to use pyinstaller for our project that is using the pydantic library (version >1.7.2). Older versions are working as expected.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: 3.8.7
* Platform: Windows 10

### A minimal example program which shows the error

main.py:
```
import pydantic # using a pydantic version > 1.7.2 e.g. 1.8.1

print("Hello!")
```
run pyinstaller:
```
pyinstaller main.py
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 3, in init pydantic.dataclasses
  File "pydantic\class_validators.py", line 8, in init pydantic.class_validators
  File "pydantic\errors.py", line 5, in init pydantic.errors
  File "pydantic\typing.py", line 23, in init pydantic.typing
ModuleNotFoundError: No module named 'typing_extensions'
[23924] Failed to execute script main
```

**Comment by bwoodsend** [comment]
Ughh not pydantic again.... Have you tried adding `--hiddenimport=typing_extensions`?

**Comment by lowmann15** [comment]
Yeah we did that and it's working, was just wondering if this is a topic that will be addressed in future to avoid this extra parameter while installing.

**Comment by rokm** [comment]
Yeah, we'll update the `pydantic` hook to address this.
