### ISSUE TITLE
check_hostname requires server_hostname

### ISSUE THREAD

**Issue by yunfei2020** [pyinstaller/pyinstaller#5647]
- [Traceback (most recent call last):
  File "spider_data.py", line 71, in <module>
  File "spider_data.py", line 42, in main
  File "spider_data.py", line 22, in get_html
  File "lib\site-packages\requests\sessions.py", line 555, in get
  File "lib\site-packages\requests\sessions.py", line 542, in request
  File "lib\site-packages\requests\sessions.py", line 655, in send
  File "lib\site-packages\requests\adapters.py", line 449, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "lib\site-packages\urllib3\connection.py", line 359, in connect
  File "lib\site-packages\urllib3\connection.py", line 506, in _connect_tls_proxy
  File "lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 407, in wrap_socket
  File "ssl.py", line 773, in __init__
ValueError: check_hostname requires server_hostname
[3040] Failed to execute script spider_data ] 

An error occurred when I used PyInstaller ( Windows 10 )

**Comment by rokm** [comment]
What's the URL being used in`get_html` in `spider_data.py`, line 22?

**Comment by yunfei2020** [comment]
`https://wkretype.bdimg.com/retype/zoom/88bbec9158fb770bf68a55af?pn=3&o=jpg_6&md5sum=b0f1a5ff45100044576ea19526244797&sign=f98c2214d9&png=83651-194335&jpg=188438-454447`

These links, I have tens of thousands of them, need to be downloaded to the local hard drive

**Comment by rokm** [comment]
Well, the error is being raised from [here](https://github.com/python/cpython/blob/4134f154ae2f621f25c5d698cc0f1748035a1b88/Lib/ssl.py#L773), due to `server_hostname` missing (being `None` or otherwise falsy). You'll have to trace your way through the call to see why that happens. 

It could be a problem with PyInstaller, although by the look of things I'm disinclined to believe so. Unless you can provide a minimal example that consistently triggers the issue when frozen (and not when unfrozen).

**Comment by yunfei2020** [comment]
I've worked it out. Thank you. Change the packaging environment. PyInstaller 4.1, Python3.7, VS2019
