### ISSUE TITLE
pyd, UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

### ISSUE THREAD

**Issue by yunfei2020** [pyinstaller/pyinstaller#5653]
```shell
(venv_python37-32) C:\Users\fz010\Desktop\g>pyinstaller -F --key xxxxxxxxxxxxxxxxxxx -i 1.ico --version-file version Spider.pyd
113 INFO: PyInstaller: 4.1
113 INFO: Python: 3.7.9
114 INFO: Platform: Windows-10-10.0.18362-SP0
118 INFO: wrote C:\Users\fz010\Desktop\g\Spider.spec
132 INFO: UPX is not available.
135 INFO: Extending PYTHONPATH with paths
['C:\\Users\\fz010\\Desktop\\g', 'C:\\Users\\fz010\\Desktop\\g']
154 INFO: Will encrypt Python bytecode with key: lVWkavwZ7ESFbHTY
155 INFO: checking Analysis
155 INFO: Building Analysis because Analysis-00.toc is non existent
155 INFO: Initializing module dependency graph...
159 INFO: Caching module graph hooks...
195 INFO: Analyzing base_library.zip ...
2397 INFO: Processing pre-find module path hook distutils from 'c:\\users\\fz010\\desktop\\g\\venv_python37-32\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2398 INFO: distutils: retargeting to non-venv dir 'D:\\Program Files\\Python\\Python37-32\\lib'
3873 INFO: Caching module dependency graph...
4011 INFO: running Analysis Analysis-00.toc
4015 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\fz010\desktop\g\venv_python37-32\scripts\python.exe
4032 INFO: Analyzing C:\Users\fz010\Desktop\g\Spider.pyd
Traceback (most recent call last):
  File "D:\Program Files\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\fz010\Desktop\g\venv_python37-32\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "C:\Users\fz010\Desktop\g\Spider.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 413, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 304, in run_script
    pathname)
  File "c:\users\fz010\desktop\g\venv_python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in run_script
    contents = fp.read() + '\n'
  File "D:\Program Files\Python\Python37-32\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

When my 'pyd' file wanted to be packaged as an exe file, and I used a password, the program failed.
When I packaged the 'py' file, everything worked fine.

**Comment by bwoodsend** [comment]
You can't do this I'm afraid. You can have `.pyd` files but not as the entry script. PyInstaller can't scan them so even if you could have them as the entry script it would be a disaster because none of your `import`s would be recognised.
