### ISSUE TITLE
ModuleNotFoundError: No module named 'checking.urls'

### ISSUE THREAD

**Issue by triple07even** [pyinstaller/pyinstaller#5671]
## ModuleNotFoundError: No module named 'checking.urls'
I tried to export a Django 3.1.4 manage.py on Linux. It only contains one app (checking), but it keeps telling me no modules name checking.urls, but the server runs fine when not exported. Although, some modules were still not detected in the --hidden-import, even after been flag as an argument with the Pyinstaller

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: e.g. 3.
* Platform: e.g GNU/Linux (distribution),

```build.sh
python -m PyInstaller --name 'mysite' \
--add-data 'templates/*.html:templates' \
--add-data 'staticfiles:staticfiles'   \
--add-data 'static:static'   \
--add-data 'checking/migrations:checking/migrations' \
--hidden-import='django.contrib.admin' \
--hidden-import='django.contrib.auth' \
--hidden-import='django.contrib.sessions' \
--hidden-import='django.contrib.contenttype' \
--hidden-import='django.contrib.messages' \
--hidden-import='django.contrib.staticfiles' \
--hidden-import='sqlparse' \
--hidden-import='altgraph' \
--hidden-import='asgiref' \
--hidden-import='pkg-resources' \
--hidden-import='checking.urls' \
--clean \
manage.py \
```

### PyInstaller compling process log
```
98 INFO: PyInstaller: 4.2
99 INFO: Python: 3.6.9
101 INFO: Platform: Linux-4.18.0-15-generic-x86_64-with-Ubuntu-18.04-bionic
102 INFO: wrote /home/imiebaka/Documents/Python_Project/pyinstaller_check/mysite.spec
111 INFO: UPX is not available.
113 INFO: Removing temporary files and cleaning cache in /home/imiebaka/.cache/pyinstaller
128 INFO: Extending PYTHONPATH with paths
['/home/imiebaka/Documents/Python_Project/pyinstaller_check',
 '/home/imiebaka/Documents/Python_Project/pyinstaller_check']
153 INFO: checking Analysis
153 INFO: Building Analysis because Analysis-00.toc is non existent
153 INFO: Initializing module dependency graph...
156 INFO: Caching module graph hooks...
178 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
189 INFO: Analyzing base_library.zip ...
6518 INFO: Caching module dependency graph...
6726 INFO: running Analysis Analysis-00.toc
6827 INFO: Analyzing /home/imiebaka/Documents/Python_Project/pyinstaller_check/manage.py
6881 INFO: Processing pre-find module path hook distutils from '/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/PyInstaller/hooks/pre_find_module_pat
h/hook-distutils.py'.
6883 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.6'
14784 INFO: Analyzing hidden import 'django.contrib.sessions'
14806 INFO: Analyzing hidden import 'django.contrib.contenttype'
14806 ERROR: Hidden import 'django.contrib.contenttype' not found
14807 INFO: Analyzing hidden import 'sqlparse'
15127 INFO: Analyzing hidden import 'altgraph'
15139 INFO: Analyzing hidden import 'pkg-resources'
15139 ERROR: Hidden import 'pkg-resources' not found
15140 INFO: Analyzing hidden import 'checking'
15151 INFO: Analyzing hidden import 'checking.urls'
15156 INFO: Processing module hooks...
15157 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/PyInstaller/hooks'...
15160 INFO: Import to be excluded not found: 'test'
15160 INFO: Loading module hook 'hook-xml.py' from '/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/PyInstaller/hooks'...
15728 INFO: Loading module hook 'hook-pickle.py' from '/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/PyInstaller/hooks'...
15732 INFO: Excluding import of argparse from module pickle
15733 INFO: Loading module hook 'hook-django.core.mail.py' from '/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/PyInstaller/hooks'...
15870 INFO: Loading module hook 'hook-django.py' from '/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/PyInstaller/hooks'...
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/admin/__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/admin/options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/admin/widgets.py", line 3, in <module>

    from django.contrib.gis.gdal import GDALException
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 46, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0").
 Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
collect_submodules: failed to import 'django.contrib.gis.admin'!
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/db/models/__init__.py", line 3, in <module>
    import django.contrib.gis.db.models.functions  # NOQA
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/db/models/functions.py", line 3, in <module>
    from django.contrib.gis.db.models.fields import BaseSpatialField, GeometryField
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/db/models/fields.py", line 3, in <module>
    from django.contrib.gis import forms, gdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
    from .fields import (  # NOQA
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
    from django.contrib.gis.gdal import GDALException
File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 46, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0").

 Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
collect_submodules: failed to import 'django.contrib.gis.db.models'!
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
    from .fields import (  # NOQA
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
    from django.contrib.gis.gdal import GDALException
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 46, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0").
 Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
collect_submodules: failed to import 'django.contrib.gis.forms'!
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>

    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 46, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0").
 Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
collect_submodules: failed to import 'django.contrib.gis.gdal'!
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/geos/__init__.py", line 5, in <module>
    from .collections import (  # NOQA
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/geos/collections.py", line 8, in <module>
    from django.contrib.gis.geos.geometry import GEOSGeometry, LinearGeometryMixin
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 8, in <module>
    from django.contrib.gis import gdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 46, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0").
 Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
collect_submodules: failed to import 'django.contrib.gis.geos'!
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/sitemaps/__init__.py", line 2, in <module>
    from django.contrib.gis.sitemaps.kml import KMLSitemap, KMZSitemap
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/sitemaps/kml.py", line 2, in <module>
    from django.contrib.gis.db.models import GeometryField
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/db/models/__init__.py", line 3, in <module>
    import django.contrib.gis.db.models.functions  # NOQA
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/db/models/functions.py", line 3, in <module>

    from django.contrib.gis.db.models.fields import BaseSpatialField, GeometryField
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/db/models/fields.py", line 3, in <module>
    from django.contrib.gis import forms, gdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
    from .fields import (  # NOQA
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
    from django.contrib.gis.gdal import GDALException
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 46, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0").
 Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
collect_submodules: failed to import 'django.contrib.gis.sitemaps'!
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/utils/__init__.py", line 4, in <module>
    from django.contrib.gis.utils.ogrinfo import ogrinfo  # NOQA
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/utils/ogrinfo.py", line 7, in <module>
    from django.contrib.gis.gdal import DataSource
File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource

  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 46, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0").
 Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
collect_submodules: failed to import 'django.contrib.gis.utils'!
24509 INFO: Determining a mapping of distributions to packages...
26865 INFO: Packages required by django:
['sqlparse', 'asgiref', 'pytz']
26866 INFO: Django root directory /home/imiebaka/Documents/Python_Project/pyinstaller_check/mysite
30971 INFO: Collecting Django migration scripts.
37458 WARNING: Hidden import "django.contrib.staticfiles.templatetags" not found!
37461 WARNING: Hidden import "django.contrib.staticfiles.context_processors" not found!
37463 WARNING: Hidden import "django.contrib.contenttypes.context_processors" not found!
37464 WARNING: Hidden import "django.contrib.messages.templatetags" not found!
37574 WARNING: Hidden import "django.contrib.sessions.context_processors" not found!
37575 WARNING: Hidden import "django.contrib.admin.context_processors" not found!
37588 WARNING: Hidden import "django.contrib.contenttypes.templatetags" not found!
37589 WARNING: Hidden import "checking.context_processors" not found!
37619 WARNING: Hidden import "django.contrib.sessions.templatetags" not found!
37619 WARNING: Hidden import "django.contrib.auth.templatetags" not found!
37620 WARNING: Hidden import "checking.templatetags" not found!
.....
40116 INFO: Looking for dynamic libraries
40910 INFO: Looking for eggs
40911 INFO: Python library not in binary dependencies. Doing additional searching...
40991 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
41023 INFO: Warnings written to /home/imiebaka/Documents/Python_Project/pyinstaller_check/build/mysite/warn-mysite.txt
41311 INFO: Graph cross-reference written to /home/imiebaka/Documents/Python_Project/pyinstaller_check/build/mysite/xref-mysite.html
41814 INFO: Appending 'datas' from .spec
41832 INFO: checking PYZ
41833 INFO: Building PYZ because PYZ-00.toc is non existent
41840 INFO: Building PYZ (ZlibArchive) /home/imiebaka/Documents/Python_Project/pyinstaller_check/build/mysite/PYZ-00.pyz
43910 INFO: Building PYZ (ZlibArchive) /home/imiebaka/Documents/Python_Project/pyinstaller_check/build/mysite/PYZ-00.pyz completed successfully.
43994 INFO: checking PKG
43994 INFO: Building PKG because PKG-00.toc is non existent
43995 INFO: Building PKG (CArchive) PKG-00.pkg
44094 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
44096 INFO: Bootloader /home/imiebaka/Documents/Python_Project/pyinstaller_check/env/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run
44096 INFO: checking EXE
44097 INFO: Building EXE because EXE-00.toc is non existent
44097 INFO: Building EXE from EXE-00.toc
44098 INFO: Appending archive to ELF section in EXE /home/imiebaka/Documents/Python_Project/pyinstaller_check/build/mysite/mysite
44132 INFO: Building EXE from EXE-00.toc completed successfully.
44155 INFO: checking COLLECT
44156 INFO: Building COLLECT because COLLECT-00.toc is non existent
WARNING: The output directory "/home/imiebaka/Documents/Python_Project/pyinstaller_check/dist/mysite" and ALL ITS CONTENTS will be REMOVED! Continue? (y/N)y
On your own risk, you can use the option `--noconfirm` to get rid of this question.
74001 INFO: Removing dir /home/imiebaka/Documents/Python_Project/pyinstaller_check/dist/mysite
74757 INFO: Building COLLECT COLLECT-00.toc
77541 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```
Although the app compiled successfully but, on running the file in the dist dir, I got this error
```
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
  File "manage.py", line 22, in main
  File "django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/imiebaka/.local/share/Trash/files/dist.26/mysite/django/core/management/commands/runserver.py", line 61, in execute

    super().execute(*args, **options)
  File "django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/imiebaka/.local/share/Trash/files/dist.26/mysite/django/core/management/commands/runserver.py", line 96, in handle
    self.run(**options)
  File "/home/imiebaka/.local/share/Trash/files/dist.26/mysite/django/core/management/commands/runserver.py", line 105, in run
    self.inner_run(None, **options)
  File "/home/imiebaka/.local/share/Trash/files/dist.26/mysite/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "django/core/management/base.py", line 396, in check
    databases=databases,
  File "django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
 File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "mysite/urls.py", line 9, in <module>
  File "django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'checking.urls'
[12482] Failed to execute script manage
```
I'll be glad if you anyone help me solve this issue, 
Here is what the project urls.py look like
```
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('checking.urls', namespace='checking_app')),
]
if settings.DEBUG:
    # url(r'^static/(?P.*)$', views.serve),
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

```
Any help will be really appreciated
[12482] Failed to execute script manage

**Comment by rokm** [comment]
Hmm, can you check `build/<name>/Analysis-00.toc` and `PYZ-00.toc` to see if there's any mention of `checking.urls` (or any modules from `checking`, for that matter) in there?
