### ISSUE TITLE
Struggling with ray import

### ISSUE THREAD

**Issue by yolking** [pyinstaller/pyinstaller#5682]
System information
Windows 10
python 3.8.8
pyinstaller 4.2
ray 1.2.0

Basically I am trying to create an .exe file based on python script, where [ray](https://ray.io/) library is used, which parallelizes code execution between several processes. Script works perfectly fine in python, but I need .exe to launch this code on another computer.
I create .exe using `pyinstaller` with several manually added hidden dependencies for `ray` to work (otherwise I get ImportError)
hiddenimports=['ray.async_compat','msgpack']
Unfortunately, exe application crashes on 
```
import ray
ray.init(num_cpus=2) 
```
with
Traceback (most recent call last):
File "myscript.py", line 2, in
File "ray_private\client_mode_hook.py", line 47, in wrapper
File "ray\worker.py", line 714, in init
File "ray\node.py", line 220, in init
File "ray\node.py", line 827, in start_head_processes
File "ray\node.py", line 632, in start_redis
File "ray_private\services.py", line 833, in start_redis
File "ray_private\services.py", line 942, in _start_redis_instance
AssertionError

When `ray.init()` is called, it tries to launch it's dependency redis-server.exe and fails. I tried changing location of redis-server.exe in `ray` services.py source file and place it together with resulting exe file, but it didn't help. Additional files are called by services.py, which may be required for redis-server to run. Is there a way to fix it with right imports or `ray` can't be packed by `pyinstaller` due to its dependencies or parallel nature?

**Comment by bwoodsend** [comment]
Hmm,  this looks like it will get ugly.

https://github.com/ray-project/ray/blob/e5caaa7d1f6456cde31628ff048d68928bfe9337/python/ray/_private/services.py#L987-L989

Those assertions will fail in PyInstaller because modules are not files - rather they're zipped up into an archive embedded in the EXE. I'll have a go at bullying my way through with `collect_data_files(..., py_files=True)` but I doubt it'll work...

**Comment by bwoodsend** [comment]
Setting `datas=collect_data_files("ray", include_py_files=True)` in the spec file fixes the assertion but causes a huge infinite loop which crashed my terminal. Looking at my process manager I see it's firing off all kinds of sub processes so this loop will be hard to trace.
