### ISSUE TITLE
Cannot run my file and error akinator [6272] Failed to execute script

### ISSUE THREAD

**Issue by congaterori** [pyinstaller/pyinstaller#5689]
Cannot run my file and error akinator
i use `pip install akinator.py`
```
Traceback (most recent call last):
  File "Vevoast.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "akinator\__init__.py", line 32, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DELL\\Desktop\\pythonA.I-beta-for-windows-10-new\\dist\\Vevoast\\akinator\\VERSION.txt'
[6272] Failed to execute script Vevoast
```
## in line 5
`from akinator.async_aki import Akinator`

**Comment by bwoodsend** [comment]
`--add-data="C:\Users\DELL\Desktop\pythonA.I-beta-for-windows-10-new\dist\Vevoast\akinator\VERSION.txt;akinator`
