### ISSUE TITLE
Windows 10 - pyinstaller did not build a "exe" - TypeError: an integer is required (got type bytes)`

### ISSUE THREAD

**Issue by ds2k5** [pyinstaller/pyinstaller#5712]
Hi,
wanna build a "ONFILE" for Windows.

Have a Windows 10 (64bit) with pythton 3.9.4 64bit and tyed Version 3.8.9 too
a little python script.

PyInstaller Version 3.3.1

But the Build will not work, did not get a file in dist directory-

`Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble
    self.code_dict = {
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\utils.py", line 624, in strip_paths_in_code
    consts = tuple(
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\utils.py", line 625, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\utils.py", line 632, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)`

python -m pip --proxy http://User:Pasword@192.168.1.111:3128 install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 6.8 MB/s
Installing collected packages: pip
  WARNING: The scripts pip.exe, pip3.9.exe and pip3.exe are installed in 'C:\Users\admin\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-21.0.1
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.

C:\Users\admin>python -m pip --proxy http://User:Password@192.168.1.111:3128 install pyinstaller
Defaulting to user installation because normal site-packages is not writeable
Collecting pyinstaller
  Downloading pyinstaller-4.2.tar.gz (3.6 MB)
     |████████████████████████████████| 3.6 MB 6.8 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-6v2e3w_t\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000254D5DC1190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000254D5DC13A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000254D5DC1550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000254D5DC1700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000254D5DC18B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0
  ERROR: No matching distribution found for setuptools>=40.8.0
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b4/83/9f6ff034650abe9778c9a4f86bcead63f89a62acf02b1b47fc2bfc6bf8dd/pyinstaller-4.2.tar.gz#sha256=f5c0eeb2aa663cce9a5404292c0195011fa500a6501c873a466b2e8cad3c950c (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.5). Command errored out with exit status 1: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-6v2e3w_t\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
  Downloading pyinstaller-4.1.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 6.4 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-0wmqcch4\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021FDFCA1190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021FDFCA13A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021FDFCA1550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021FDFCA1700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021FDFCA18B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0
  ERROR: No matching distribution found for setuptools>=40.8.0
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9e/ed/fbdad7f5d8f794c901076b814b8e9f5ce31d32c0bc3b63ddd27b61db9530/pyinstaller-4.1.tar.gz#sha256=954ae81de9a4bc096ff02433b3e245b9272fe53f27cac319e71fe7540952bd3d (from https://pypi.org/simple/pyinstaller/). Command errored out with exit status 1: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-0wmqcch4\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
  Downloading pyinstaller-4.0.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 6.4 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-5b8hhzv3\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001669F831190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001669F8313A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001669F831550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001669F831700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001669F8318B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0
  ERROR: No matching distribution found for setuptools>=40.8.0
  ----------------------------------------153.3.1.40
WARNING: Discarding https://files.pythonhosted.org/packages/82/96/21ba3619647bac2b34b4996b2dbbea8e74a703767ce24192899d9153c058/pyinstaller-4.0.tar.gz#sha256=970beb07115761d5e4ec317c1351b712fd90ae7f23994db914c633281f99bab0 (from https://pypi.org/simple/pyinstaller/). Command errored out with exit status 1: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-5b8hhzv3\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
  Downloading PyInstaller-3.6.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 6.4 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-g6yncc27\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000147BE651190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000147BE6513A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000147BE651550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000147BE651700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000147BE6518B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0
  ERROR: No matching distribution found for setuptools>=40.8.0
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz#sha256=3730fa80d088f8bb7084d32480eb87cbb4ddb64123363763cf8f2a1378c1c4b7 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*). Command errored out with exit status 1: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-g6yncc27\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
  Downloading PyInstaller-3.5.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB ...
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-sf8kgqbz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000028776CD1190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000028776CD13A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000028776CD1550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000028776CD1700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000028776CD18B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0
  ERROR: No matching distribution found for setuptools>=40.8.0
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e2/c9/0b44b2ea87ba36395483a672fddd07e6a9cb2b8d3c4a28d7ae76c7e7e1e5/PyInstaller-3.5.tar.gz#sha256=ee7504022d1332a3324250faf2135ea56ac71fdb6309cff8cd235de26b1d0a96 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-sf8kgqbz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
  Downloading PyInstaller-3.4.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB ...
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-qywdav0e\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000215E79793D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000215E79795E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000215E7979790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000215E7979940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000215E7979AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz#sha256=a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: 'C:\Program Files\Python39\python.exe' 'C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-qywdav0e\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Check the logs for full command output.
  Downloading PyInstaller-3.3.1.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB ...
Requirement already satisfied: setuptools in c:\program files\python39\lib\site-packages (from pyinstaller) (49.2.1)
Collecting pefile>=2017.8.1
  Downloading pefile-2019.4.18.tar.gz (62 kB)
     |████████████████████████████████| 62 kB 139 kB/s
Collecting macholib>=1.8
  Downloading macholib-1.14-py2.py3-none-any.whl (37 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 6.4 MB/s
Collecting pypiwin32
  Downloading pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting altgraph>=0.15
  Downloading altgraph-0.17-py2.py3-none-any.whl (21 kB)
Collecting pywin32>=223
  Downloading pywin32-300-cp39-cp39-win_amd64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 6.4 MB/s
Using legacy 'setup.py install' for pyinstaller, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pefile, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Installing collected packages: pywin32, future, altgraph, pypiwin32, pefile, macholib, pyinstaller
    Running setup.py install for future ... done
    Running setup.py install for pefile ... done
  WARNING: The scripts macho_dump.exe, macho_find.exe and macho_standalone.exe are installed in 'C:\Users\admin\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for pyinstaller ... done
Successfully installed altgraph-0.17 future-0.18.2 macholib-1.14 pefile-2019.4.18 pyinstaller-3.3.1 pypiwin32-223 pywin32-300

C:\Users\admin>python -m pip --proxy http://User:Password@192.168.1.111:3128 install pywin32-ctypes

C:\Users\admin\AppData\Roaming\Python\Python39\Scripts>pyinstaller.exe --version
3.3.1

**Comment by ds2k5** [comment]
I solved it:

solution was to set the env like this:

set http_proxy=http://User:Password@192.168.1.111:3128
set https_proxy=http://User:Password@192.168.1.111:3128

python -m pip install --upgrade pyinstaller

now the Version 4.2 is running... and build the packages
