### ISSUE TITLE
scikit-image problem 

### ISSUE THREAD

**Issue by PawelDarlak** [pyinstaller/pyinstaller#5721]
Hello,

I am using python 3.9.4 and last version of scikit-image.

When I want to run exe file program crash and show error:

PS C:\Users\neoca> E:\Python\DiopomatCalc\dist\diopomat\diopomat.exe
Traceback (most recent call last):
  File "Diopomat.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "mydicom\PoreSize.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "skimage\filters\__init__.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "skimage\filters\rank\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "skimage\filters\rank\generic.py", line 58, in <module>
  File "skimage\filters\rank\generic_cy.pyx", line 1, in init skimage.filters.rank.generic_cy
ModuleNotFoundError: No module named 'skimage.filters.rank.core_cy_3d'
[14272] Failed to execute script Diopomat

Thanks for advance
Pavel

**Comment by bwoodsend** [comment]
`--hiddenimport skimage.filters.rank.core_cy_3d`
