### ISSUE TITLE
Installing build dependencies causes errors 

### ISSUE THREAD

**Issue by lushythedev** [pyinstaller/pyinstaller#5728]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```Python 3.8.1```
* Version of Python: Python 3.8.1
* Platform: e.g GNU/Linux (distribution), Windows (language settings), OS X, conda, FreeBSD: ```Windows 10```
* Did you also try this on another platform? ```No``` Does it work there? ```N/A```

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Tried this, hasn't worked, I also tried ```https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz```
The same error happens when installing by ```pip install pyinstaller```
* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
pip install https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz
Collecting https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz
  Downloading https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz
     / 3.2 MB 3.0 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\mint\AppData\Local\Temp\pip-build-env-ytura15w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\python38\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "c:\python38\lib\site-packages\pip\__main__.py", line 21, in <module>
      from pip._internal.cli.main import main as _main
    File "c:\python38\lib\site-packages\pip\_internal\cli\main.py", line 3, in <module>
      import locale
    File "c:\python38\lib\locale.py", line 16, in <module>
      import re
    File "c:\python38\lib\re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
WARNING: Discarding https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz. Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\mint\AppData\Local\Temp\pip-build-env-ytura15w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\mint\AppData\Local\Temp\pip-build-env-ytura15w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output
```

### Stacktrace / full error message

```
pip install https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz
Collecting https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz
  Downloading https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz
     / 3.2 MB 3.0 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\mint\AppData\Local\Temp\pip-build-env-ytura15w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\python38\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "c:\python38\lib\site-packages\pip\__main__.py", line 21, in <module>
      from pip._internal.cli.main import main as _main
    File "c:\python38\lib\site-packages\pip\_internal\cli\main.py", line 3, in <module>
      import locale
    File "c:\python38\lib\locale.py", line 16, in <module>
      import re
    File "c:\python38\lib\re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
WARNING: Discarding https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz. Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\mint\AppData\Local\Temp\pip-build-env-ytura15w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\mint\AppData\Local\Temp\pip-build-env-ytura15w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
That's probably caused by having `enum34` package installed in your environment. Uninstall it, as it is incompatible with python 3.8 (and its own `enum` module).

**Comment by lushythedev** [comment]
> That's probably caused by having `enum34` package installed in your environment. Uninstall it, as it is incompatible with python 3.8 (and its own `enum` module).

Awesome, this seems have done the trick. Thanks, rokm.
