### ISSUE TITLE
Can't find libpython3.8 withoud "m" flag

### ISSUE THREAD

**Issue by liry** [pyinstaller/pyinstaller#5749]
## Description of the issue

Pyinstaller is searching for `libpython3.8m.so`, but python38-devel package installs only `libpython3.8.so`.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3``` (the same with latest development version 5.0.dev0)
* Version of Python: 3.8.6
* Platform: GNU/Linux CentOS 7
* Did you also try this on another platform? Does it work there? Haven't tried

### A minimal example program which shows the error

```
$ docker run -it centos:7
```

Inside container:
```
$ yum update -y
$ yum install -y epel-release centos-release-scl scl-utils make
$ yum install -y rh-python38 rh-python38-python-devel
$ scl enable rh-python38 'pip install --upgrade pip'
$ scl enable rh-python38 'pip install pyinstaller'
$ scl enable rh-python38 'pyinstaller ...'
```

```
$ ls -l /opt/rh/rh-python38/root/usr/lib64/
total 3812
dr-xr-xr-x  2 root root    4096 Mar 30  2020 X11
dr-xr-xr-x  2 root root    4096 Mar 30  2020 games
lrwxrwxrwx  1 root root      31 Apr 19 07:00 libpython3.8.so -> libpython3.8.so.rh-python38-1.0
-rwxr-xr-x  1 root root 3846208 Oct 27 09:16 libpython3.8.so.rh-python38-1.0
-rwxr-xr-x  1 root root   14848 Oct 27 09:16 libpython3.so.rh-python38
drwxr-xr-x  2 root root    4096 Apr 19 07:00 pkgconfig
dr-xr-xr-x  5 root root    4096 Apr 19 07:00 pm-utils
drwxr-xr-x 31 root root   12288 Apr 19 07:00 python3.8
dr-xr-xr-x  2 root root    4096 Mar 30  2020 sse2
dr-xr-xr-x  2 root root    4096 Mar 30  2020 tls
```

### Stacktrace / full error message

```
28267 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "cmd.spec", line 7, in <module>
    a = Analysis(['gooddata/cmd/__main__.py'],
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 242, in __init__
    self.__postinit__()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 476, in assemble
    self._check_python_library(self.binaries)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 581, in _check_python_library
    python_lib = bindepend.get_python_library_path()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 956, in get_python_library_path
    raise IOError(msg)
OSError: Python library not found: libpython3.8m.so.1.0, libpython3.8mu.so.1.0, libpython3.8m.so, libpython3.8.so.1.0
    This would mean your Python installation doesn't come with proper library files.
    This usually happens by missing development package, or unsuitable build parameters of Python installation.

    * On Debian/Ubuntu, you would need to install Python development packages
      * apt-get install python3-dev
      * apt-get install python-dev
    * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

**Comment by rokm** [comment]
Yeah, that's an issue that's specific to python installed from RHEL SCL, due to how the python library is named (`libpython3.8.so.rh-python38-1.0` instead of `libpython3.8.so.1.0` that would be found in non-SCL packages). 

I'd say that not checking for `libpython3.X.so` is simply an oversight; b748881a703806d946428f509f7c5f24df8a7488 explictly added check for `libpython3.Xm.so` for SCL compatibility; but that was in the days when m suffix also present in the name (AFAICT, python 3.7 and earlier).

**Comment by adabuleanu** [comment]
Is this fix is available in any stable version? I have the same issue with python 3.8.12 and pyinstaller 4.5.1 on centos 7
```
error	22-Sep-2021 10:33:15	24691 INFO: Looking for dynamic libraries
error	22-Sep-2021 10:33:17	26356 INFO: Looking for eggs
error	22-Sep-2021 10:33:17	26357 INFO: Python library not in binary dependencies. Doing additional searching...
error	22-Sep-2021 10:33:17	Traceback (most recent call last):
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/bin/pyinstaller", line 8, in <module>
error	22-Sep-2021 10:33:17	    sys.exit(run())
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/__main__.py", line 126, in run
error	22-Sep-2021 10:33:17	    run_build(pyi_config, spec_file, **vars(args))
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
error	22-Sep-2021 10:33:17	    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 815, in main
error	22-Sep-2021 10:33:17	    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 762, in build
error	22-Sep-2021 10:33:17	    exec(code, spec_namespace)
error	22-Sep-2021 10:33:17	  File "/home/bamboo/bamboo-agent-home/xml-data/build-dir/NCICOMMON-PYMONOREPO483-JOB1/unstripped-nci.bin.spec", line 7, in <module>
error	22-Sep-2021 10:33:17	    a = Analysis(['src/python/nci_installer/installer/nci.py'],
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 294, in __init__
error	22-Sep-2021 10:33:17	    self.__postinit__()
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 159, in __postinit__
error	22-Sep-2021 10:33:17	    self.assemble()
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 540, in assemble
error	22-Sep-2021 10:33:17	    self._check_python_library(self.binaries)
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 645, in _check_python_library
error	22-Sep-2021 10:33:17	    python_lib = bindepend.get_python_library_path()
error	22-Sep-2021 10:33:17	  File "/root/.local/share/virtualenvs/binaries-cPg7fnji/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 967, in get_python_library_path
error	22-Sep-2021 10:33:17	    raise IOError(msg)
error	22-Sep-2021 10:33:17	OSError: Python library not found: libpython3.8m.so.1.0, libpython3.8mu.so.1.0, libpython3.8m.so, libpython3.8.so.1.0, libpython3.8.so
error	22-Sep-2021 10:33:17	    This would mean your Python installation doesn't come with proper library files.
error	22-Sep-2021 10:33:17	    This usually happens by missing development package, or unsuitable build parameters of Python installation.
error	22-Sep-2021 10:33:17	
error	22-Sep-2021 10:33:17	    * On Debian/Ubuntu, you would need to install Python development packages
error	22-Sep-2021 10:33:17	      * apt-get install python3-dev
error	22-Sep-2021 10:33:17	      * apt-get install python-dev
error	22-Sep-2021 10:33:17	    * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

**Comment by rokm** [comment]
> Is this fix is available in any stable version?

Yes, the fix was released as part of PyInstaller 4.4.

Building on CentOS 7 with python 3.8.11 installed from SCL seems to work as expected as well (with 4.5.1).

From where/how did you install your python 3.8.**12**?

**Comment by adabuleanu** [comment]
I installed python from source. I will try from SCL

**Comment by rokm** [comment]
> I installed python from source.

Then you need to build with `--enable-shared`, like the error message is telling you to.

**Comment by anhTuan0712** [comment]
Or try this: 
sudo apt-get install libpython3.7-dev
it worked for me
