### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Texnocom** [pyinstaller/pyinstaller#5761]
`bot.py:649:` SyntaxWarning: "is" with a literal. Did you mean "=="?
  if game.players_won is 0:
C:\Users\Samil\Desktop\mau_mau_bot-master\internationalization.py:69: SyntaxWarn
ing: "is" with a literal. Did you mean "=="?
  if n is 1:
Traceback (most recent call last):
  File "bot.py", line 32, in <module>
    from results import (add_call_bluff, add_choose_color, add_draw, add_gameinf
o,
  File "C:\Users\Samil\Desktop\mau_mau_bot-master\results.py", line 29, in <modu
le>
    from utils import display_color, display_color_group, display_name
  File "C:\Users\Samil\Desktop\mau_mau_bot-master\utils.py", line 26, in <module
>
   ` from internationalization import _, __`
  File "C:\Users\Samil\Desktop\mau_mau_bot-master\internationalization.py", line
 81, in <module>
    _ = _Underscore()
  File "C:\Users\Samil\Desktop\mau_mau_bot-master\internationalization.py", line
 36, in __init__
    self.translators = {
  File "C:\Users\Samil\Desktop\mau_mau_bot-master\internationalization.py", line
 38, in <dictcomp>
    open(gettext.find(
TypeError: expected str, bytes or os.PathLike object, not `NoneType`

![2021-04-23_17-04-19](https://user-images.githubusercontent.com/76031213/115875220-0b614980-a456-11eb-8c3a-b5d803b16820.png)

**Comment by rokm** [comment]
And what does this have to do with PyInstaller?
