### ISSUE TITLE
Creating exe-file with pandas_ta module not possible

### ISSUE THREAD

**Issue by Rapid1898-code** [pyinstaller/pyinstaller#5784]
## Description of the issue
I want to create an exe-file using pyinstaller

The py-file is very-simple (and runs when i start it in vscode or from the terminal)
import pandas_ta as ta
print("It works!")

I create the exe-file with:
pyinstaller --onefile temp5.py
also tried: pyinstaller --onefile --hidden-import pandas_ta temp5.py (with the same result)
(the building of the the exe-file works fine without errors)

But when i start the exe-file it get this error message:
Traceback (most recent call last): File "temp5.py", line 3, in <module> import pandas_ta as ta File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module File "pandas_ta\__init__.py", line 10, in <module> File "pkg_resources\__init__.py", line 466, in get_distribution File "pkg_resources\__init__.py", line 342, in get_provider File "pkg_resources\__init__.py", line 886, in require File "pkg_resources\__init__.py", line 772, in resolve pkg_resources.DistributionNotFound: The 'pandas_ta' distribution was not found and is required by the application [17468] Failed to execute script temp5

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.9.
* Platform: Windows (german)
* Did you also try this on another platform?  No

## A minimal example program which shows the error

```
import pandas_ta as ta
print("It works!")
```

### Stacktrace / full error message

```
Traceback (most recent call last): File "temp5.py", line 3, in <module> import pandas_ta as ta File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module File "pandas_ta\__init__.py", line 10, in <module> File "pkg_resources\__init__.py", line 466, in get_distribution File "pkg_resources\__init__.py", line 342, in get_provider File "pkg_resources\__init__.py", line 886, in require File "pkg_resources\__init__.py", line 772, in resolve pkg_resources.DistributionNotFound: The 'pandas_ta' distribution was not found and is required by the application [17468] Failed to execute script temp5
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
You need to collect `pandas_ta` metadata, for example by using `--copy-metadata` switch that was introduced in 4.3:
`pyinstaller --copy-metadata pandas_ta --onefile temp5.py`

**Comment by Rapid1898-code** [comment]
Thanks for the fast response - this works great for me!
