### ISSUE TITLE
A Module Error Bug

### ISSUE THREAD

**Issue by sancho1952007** [pyinstaller/pyinstaller#5799]
Traceback (most recent call last):
  File "Movie Editor.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "moviepy\editor.py", line 87, in <module>
  File "<string>", line 1, in <module>
AttributeError: module 'moviepy.audio.fx.all' has no attribute 'audio_fadein'
[14852] Failed to execute script Movie Editor

The Line 4 is: "import moviepy.editor"
The python file works all fine.

Why is it showing such a error???

**Comment by rokm** [comment]
It's because [`moviepy.audio.fx.all` in moviepy 1.0.3](https://github.com/Zulko/moviepy/blob/v1.0.3/moviepy/audio/fx/all/__init__.py) is supposed to load all submodules using `pkgutil.iter_modules()`, which is currently unsupported by PyInstaller (looks like we have an open issue about that already, too - #1905). Therefore, `moviepy.audio.fx.all.audio_fadein`, which is supposed to be a submodule, does not exist, resulting in that `AttributeError`.

It seems `moviepy` changed that approach in their [git `master`](https://github.com/Zulko/moviepy/blob/master/moviepy/audio/fx/all/__init__.py), although the change is not part of any release yet. So I guess your best bet at the moment is trying to install `moviepy` from their git master. Or wait for new `moviepy` release. Or wait until someone adds support for pkgutil.iter_modules() to PyInstaller...

**Comment by rokm** [comment]
Or, a possible work-around would also be to build with `--collect-submodules moviepy --debug noarchive` arguments added to your PyInstaller command. This will collect all submodules from `moviepy` and also write all collected modules directly into application's directory instead of into embedded archive, which should make them discoverable by built-in importers used by `pkgutil.iter_modules`.

**Comment by sancho1952007** [comment]
Thank You and please repair this problem...
