### ISSUE TITLE
ValueError: Unknown load command: 42 in Mach-O loader

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#582]
**Original date**: 2012/07/30
**Original reporter**: *doug DOT johnston AND gmail DOT  COOM *

It seems llvm 4.0, which Apple introduced with OS X 10.8, Mountain Lion/ XCode 4.4, introduced new Mach-O headers. This causes loading of Mach-O binaries to fail in OS X 10.8.

```
# llvm-g++ --version
i686-apple-darwin11-llvm-g++-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
```

Traceback:

```
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/build.py", line 389, in __init__
    self.__postinit__()
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/build.py", line 315, in __postinit__
    self.assemble()
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/build.py", line 451, in assemble
    manifest=depmanifest)[1:])
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/bindepend.py", line 158, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/bindepend.py", line 381, in selectImports
    dlls = getImports(pth)
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/bindepend.py", line 573, in getImports
    return _getImports_macholib(pth)
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/bindepend.py", line 474, in _getImports_macholib
    m = MachO(pth)
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/lib/macholib/MachO.py", line 63, in __init__
    self.load(open(filename, 'rb'))
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/lib/macholib/MachO.py", line 73, in load
    self.load_fat(fh)
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/lib/macholib/MachO.py", line 84, in load_fat
    self.load_header(fh, arch.offset, arch.size)
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/lib/macholib/MachO.py", line 108, in load_header
    hdr = MachOHeader(self, fh, offset, size, magic, hdr, endian)
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/lib/macholib/MachO.py", line 148, in __init__
    self.load(fh)
  File "/Users/dvj/dev/downloads/pyinstaller/PyInstaller/lib/macholib/MachO.py", line 180, in load
    raise ValueError("Unknown load command: %d" % (cmd_load.cmd,))
```

**Comment by bittner** [comment]
I'm getting a similar error on [a macOS build on Travis CI](https://travis-ci.org/cool-RR/PythonTurtle/jobs/436957765):
```python
ValueError: Unknown Mach-O header: 0x00000100 in <_io.BufferedReader name='icon.ico'>
```
Is this a problem of PyInstaller on macOS in general, or does this relate to Travis CI macOS builds [having issues with Python](https://github.com/travis-ci/travis-ci/issues/9744) for the last few months or years?

On Ubuntu PyInstaller works just fine (also on Travis in the very same build), I can tell though whether it works on a local macOS (as I have none available).

The source code is non-spectacular (see https://github.com/cool-RR/PythonTurtle/pull/123). Full stack trace of the error:
```python
Traceback (most recent call last):
  File "./setup.py", line 133, in <module>
    'PythonTurtle = pythonturtle.__main__:application.run',
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "./setup.py", line 41, in run
    os.path.join('pythonturtle', '__main__.py'),
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 32, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/api.py", line 424, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/api.py", line 196, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/api.py", line 259, in assemble
    dist_nm=inm)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/utils.py", line 359, in checkCache
    dylib.mac_set_relative_dylib_deps(cachedfile, dist_nm)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/depend/dylib.py", line 308, in mac_set_relative_dylib_deps
    dll = MachO(libname)
  File "/usr/local/lib/python3.6/site-packages/macholib/MachO.py", line 95, in __init__
    self.load(fp)
  File "/usr/local/lib/python3.6/site-packages/macholib/MachO.py", line 110, in load
    self.load_header(fh, 0, size)
  File "/usr/local/lib/python3.6/site-packages/macholib/MachO.py", line 147, in load_header
    header, fh))
ValueError: Unknown Mach-O header: 0x00000100 in <_io.BufferedReader name='/Users/travis/Library/Application Support/pyinstaller/bincache00_py36_64bit/pythonturtle/resources/icon.ico'>
```
