### ISSUE TITLE
pyinstaller gevent breaks

### ISSUE THREAD

**Issue by ahmed4end** [pyinstaller/pyinstaller#5826]
680 INFO: PyInstaller: 5.0.dev0
680 INFO: Python: 3.6.4
680 INFO: Platform: Windows-8.1-6.3.9600-SP0
681 INFO: wrote F:\Python\mathar\app.spec
751 INFO: UPX is available.
script 'F:\Python\mathar\app' not found

(vvenv) F:\Python\mathar>python -m eel app.py web --upx-dir=F:\Python\mathar\upx

Building executable with main script 'app.py' and web folder 'web'...

Running:
pyinstaller app.py --hidden-import bottle_websocket --add-data F:\Python\mathar\
vvenv\lib\site-packages\eel\eel.js;eel --add-data web;web --upx-dir=F:\Python\ma
thar\upx

677 INFO: PyInstaller: 5.0.dev0
678 INFO: Python: 3.6.4
678 INFO: Platform: Windows-8.1-6.3.9600-SP0
679 INFO: wrote F:\Python\mathar\app.spec
750 INFO: UPX is available.
752 INFO: Extending PYTHONPATH with paths
['F:\\Python\\mathar', 'F:\\Python\\mathar']
810 INFO: checking Analysis
810 INFO: Building Analysis because Analysis-00.toc is non existent
810 INFO: Initializing module dependency graph...
813 INFO: Caching module graph hooks...
834 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take ca
re they do not conflict.
840 INFO: Analyzing base_library.zip ...
7217 INFO: Caching module dependency graph...
7641 INFO: running Analysis Analysis-00.toc
7684 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by F:\Python\mathar\vvenv\Scripts\python.exe
8165 INFO: Analyzing F:\Python\mathar\app.py
9219 INFO: Processing pre-find module path hook distutils from 'F:\\Python\\math
ar\\vvenv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-di
stutils.py'.
9220 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\John\\AppData\\Loc
al\\Programs\\Python\\Python36-32\\lib'
16648 INFO: Processing pre-safe import module hook setuptools.extern.six.moves f
rom 'F:\\Python\\mathar\\vvenv\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe
_import_module\\hook-setuptools.extern.six.moves.py'.
17558 INFO: Processing pre-find module path hook site from 'F:\\Python\\mathar\\
vvenv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.p
y'.
17559 INFO: site: retargeting to fake-dir 'F:\\Python\\mathar\\vvenv\\lib\\site-
packages\\PyInstaller\\fake-modules'
17622 INFO: Processing pre-safe import module hook win32com from 'F:\\Python\\ma
thar\\vvenv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_imp
ort_module\\hook-win32com.py'.
28352 INFO: Analyzing hidden import 'bottle_websocket'
28549 INFO: Processing module hooks...
28550 INFO: Loading module hook 'hook-eel.py' from 'F:\\Python\\mathar\\vvenv\\l
ib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
28558 INFO: Loading module hook 'hook-pycparser.py' from 'F:\\Python\\mathar\\vv
env\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
28560 INFO: Loading module hook 'hook-difflib.py' from 'F:\\Python\\mathar\\vven
v\\lib\\site-packages\\PyInstaller\\hooks'...
28567 INFO: Loading module hook 'hook-distutils.py' from 'F:\\Python\\mathar\\vv
env\\lib\\site-packages\\PyInstaller\\hooks'...
28568 INFO: Loading module hook 'hook-distutils.util.py' from 'F:\\Python\\matha
r\\vvenv\\lib\\site-packages\\PyInstaller\\hooks'...
28573 INFO: Loading module hook 'hook-encodings.py' from 'F:\\Python\\mathar\\vv
env\\lib\\site-packages\\PyInstaller\\hooks'...
28697 INFO: Loading module hook 'hook-gevent.py' from 'F:\\Python\\mathar\\vvenv
\\lib\\site-packages\\PyInstaller\\hooks'...
Traceback (most recent call last):
  File "C:\Users\John\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", l
ine 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\John\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", l
ine 85, in _run_code
    exec(code, run_globals)
  File "F:\Python\mathar\vvenv\lib\site-packages\eel\__main__.py", line 36, in <
module>
    pyi.run(full_args)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\__main__.py", line
114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\__main__.py", line
65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\building\build_main
.py", line 740, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\building\build_main
.py", line 687, in build
    exec(code, spec_namespace)
  File "F:\Python\mathar\app.spec", line 18, in <module>
    noarchive=False)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\building\build_main
.py", line 245, in __init__
    self.__postinit__()
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\building\datastruct
.py", line 159, in __postinit__
    self.assemble()
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\building\build_main
.py", line 423, in assemble
    self.graph.process_post_graph_hooks()
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\depend\analysis.py"
, line 367, in process_post_graph_hooks
    module_hook.post_graph()
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\depend\imphook.py",
 line 447, in post_graph
    self._load_hook_module()
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\depend\imphook.py",
 line 409, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\compat.py", line 62
8, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\hooks\hook-gevent.p
y", line 22, in <module>
    exclude_datas=["**/tests"])
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\utils\hooks\__init_
_.py", line 1129, in collect_all
    filter=filter_submodules)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\utils\hooks\__init_
_.py", line 667, in collect_submodules
    repr(pkg_dir), package))
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\utils\hooks\__init_
_.py", line 87, in exec_statement
    return __exec_statement(statement, capture_stdout=True)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\utils\hooks\__init_
_.py", line 79, in __exec_statement
    return __exec_python_cmd(cmd, capture_stdout=capture_stdout)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\utils\hooks\__init_
_.py", line 70, in __exec_python_cmd
    txt = compat.exec_python(*cmd, env=pp_env)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\compat.py", line 56
1, in exec_python
    return exec_command(*cmdargs, **kwargs)
  File "F:\Python\mathar\vvenv\lib\site-packages\PyInstaller\compat.py", line 32
8, in exec_command
    out = proc.communicate(timeout=60)[0]
  File "C:\Users\John\AppData\Local\Programs\Python\Python36-32\lib\subprocess.p
y", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Users\John\AppData\Local\Programs\Python\Python36-32\lib\subprocess.p
y", line 1094, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '('F:\\Python\\mathar\\vvenv\\Scripts\\python
.exe', '-c', '\nimport sys\nimport pkgutil\nimport traceback\n\n# ``pkgutil.walk
_packages`` doesn\'t walk subpackages of zipped files\n# per https://bugs.python
.org/issue14209. This is a workaround.\ndef walk_packages(path=None, prefix=\'\'
, onerror=None):\n    def seen(p, m={}):\n        if p in m:\n            return
 True\n        m[p] = True\n\n    for importer, name, ispkg in pkgutil.iter_modu
les(path, prefix):\n        if not name.startswith(prefix):   ## Added\n
    name = prefix + name          ## Added\n        yield importer, name, ispkg\
n\n        if ispkg:\n            try:\n                __import__(name)\n
      except ImportError:\n                if onerror is not None:\n
        onerror(name)\n            except Exception:\n                if onerror
 is not None:\n                    onerror(name)\n                else:\n
             traceback.print_exc(file=sys.stderr)\n                    print("co
llect_submodules: failed to import %r!" %\n                          name, file=
sys.stderr)\n            else:\n                path = getattr(sys.modules[name]
, \'__path__\', None) or []\n\n                # don\'t traverse path items we\'
ve seen before\n                path = [p for p in path if not seen(p)]\n\n
           ## Use Py2 code here. It still works in Py3.\n                for ite
m in walk_packages(path, name+\'.\', onerror):\n                    yield item\n
                ## This is the original Py3 code.\n                #yield from w
alk_packages(path, name+\'.\', onerror)\n\nfor module_loader, name, ispkg in wal
k_packages([\'F:\\\\Python\\\\mathar\\\\vvenv\\\\lib\\\\site-packages\\\\gevent\
'], \'gevent.\'):\n    print(\'\\n$_pyi:\' + name + \'*\')\n')' timed out after
60 seconds

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).
