### ISSUE TITLE
Pyinstaller fails to load PIL after using hiding imports

### ISSUE THREAD

**Issue by assassinsorrow** [pyinstaller/pyinstaller#5856]
## Description of the issue
When the program is run with normal python PIL is loaded but once run after using pyinstaller it raises error `ModuleNotFoundError: no module name 'PIL'`

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.7
* Platform: GNU/Linux (Arch)
* Did you also try this on another platform? Does it work there? this problem is non existent on windows and only happens on Linux

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
from PIL import Image


def ResizeImage(Xsize, Ysize, image):
    """Resizes images for use in tkinter"""
    image = Image.open(image)
    image.convert("LA")
    new_image = image.resize((Xsize, Ysize), Image.ANTIALIAS)
    return new_image

```

### Stacktrace / full error message

```
[25305] PyInstaller Bootloader 3.x
[25305] LOADER: executable is /home/*******/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
[25305] LOADER: homepath is /home/*******/Git/RhythmPy/dist/RhythmPyDev
[25305] LOADER: _MEIPASS2 is NULL
[25305] LOADER: archivename is /home/*******/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
[25305] LOADER: Cookie found at offset 0x355DE2
[25305] LOADER: Extracting binaries
[25305] LOADER: Executing self as child
[25305] LOADER: set _MEIPASS2 to /home/assassin/Git/RhythmPy/dist/RhythmPyDev
[25305] LOADER: linux: storing process name into _PYI_PROCNAME: RhythmPyDev
[25305] LOADER: LD_LIBRARY_PATH=/home/*******/Git/RhythmPy/dist/RhythmPyDev
[25305] LOADER: Registering signal handlers
[25306] PyInstaller Bootloader 3.x
[25306] LOADER: executable is /home/*******/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
[25306] LOADER: homepath is /home/*******/Git/RhythmPy/dist/RhythmPyDev
[25306] LOADER: _MEIPASS2 is /home/*******/Git/RhythmPy/dist/RhythmPyDev
[25306] LOADER: archivename is /home/*******/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
[25306] LOADER: Cookie found at offset 0x355DE2
[25306] LOADER: restoring linux process name from _PYI_PROCNAME: RhythmPyDev
[25306] LOADER: Already in the child - running user's code.
[25306] LOADER: Python library: /home/*******/Git/RhythmPy/dist/RhythmPyDev/libpython3.9.so.1.0
[25306] LOADER: Loaded functions from Python library.
[25306] LOADER: Manipulating environment (sys.path, sys.prefix)
[25306] LOADER: sys.prefix is /home/*******/Git/RhythmPy/dist/RhythmPyDev
[25306] LOADER: Pre-init sys.path is /home/*******/Git/RhythmPy/dist/RhythmPyDev/base_library.zip:/home/*******/Git/RhythmPy/dist/RhythmPyDev/lib-dynload:/home/*******/Git/RhythmPy/dist/RhythmPyDev
[25306] LOADER: Setting runtime options
[25306] LOADER: Initializing python
[25306] LOADER: Overriding Python's sys.path
[25306] LOADER: Post-init sys.path is /home/*******/Git/RhythmPy/dist/RhythmPyDev/base_library.zip:/home/*******/Git/RhythmPy/dist/RhythmPyDev/lib-dynload:/home/*******/Git/RhythmPy/dist/RhythmPyDev
[25306] LOADER: Setting sys.argv
[25306] LOADER: setting sys._MEIPASS
[25306] LOADER: importing modules from CArchive
[25306] LOADER: extracted struct
[25306] LOADER: callfunction returned...
[25306] LOADER: extracted pyimod01_os_path
[25306] LOADER: callfunction returned...
[25306] LOADER: extracted pyimod02_archive
[25306] LOADER: callfunction returned...
[25306] LOADER: extracted pyimod03_importers
[25306] LOADER: callfunction returned...
[25306] LOADER: Installing PYZ archive with Python modules.
[25306] LOADER: PYZ archive: PYZ-00.pyz
[25306] LOADER: Running pyiboot01_bootstrap.py
[25306] LOADER: Running pyi_rth_multiprocessing.py
[25306] LOADER: Running pyi_rth__tkinter.py
[25306] LOADER: Running __main__.py

name 'exit' is not defined

Traceback (most recent call last):
  File "__main__.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "__init__.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "Gui/__init__.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "Gui/ResizeImage.py", line 1, in <module>
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
NameError: name 'exit' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 71, in <module>
NameError: name 'exit' is not defined
[25306] Failed to execute script __main__
[25306] LOADER: OK.
[25306] LOADER: Manually flushing stdout and stderr
[25306] LOADER: Cleaning up Python interpreter.
[25305] LOADER: Restoring signal handlers
[25305] LOADER: freeing args
[25305] LOADER: returning child exit status 1
[25305] LOADER: Back to parent (RC: 1)
[25305] LOADER: Doing cleanup
[25305] LOADER: Freeing archive status for /home/******/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
```

**Comment by rokm** [comment]
`PIL` should pretty much be discoverable, unless you have virtual environments mixed up.

Does it work if you run pyinstaller as `python3 -m PyInstaller [...]` instead of `pyinstaller [...]`?

**Comment by assassinsorrow** [comment]
I am still getting a similar message
```
[37859] PyInstaller Bootloader 3.x
[37859] LOADER: executable is /home/assassin/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
[37859] LOADER: homepath is /home/assassin/Git/RhythmPy/dist/RhythmPyDev
[37859] LOADER: _MEIPASS2 is NULL
[37859] LOADER: archivename is /home/assassin/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
[37859] LOADER: Cookie found at offset 0x35D3C2
[37859] LOADER: Extracting binaries
[37859] LOADER: Executing self as child
[37859] LOADER: set _MEIPASS2 to /home/assassin/Git/RhythmPy/dist/RhythmPyDev
[37859] LOADER: linux: storing process name into _PYI_PROCNAME: RhythmPyDev
[37859] LOADER: LD_LIBRARY_PATH=/home/assassin/Git/RhythmPy/dist/RhythmPyDev
[37859] LOADER: Registering signal handlers
[37860] PyInstaller Bootloader 3.x
[37860] LOADER: executable is /home/assassin/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
[37860] LOADER: homepath is /home/assassin/Git/RhythmPy/dist/RhythmPyDev
[37860] LOADER: _MEIPASS2 is /home/assassin/Git/RhythmPy/dist/RhythmPyDev
[37860] LOADER: archivename is /home/assassin/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
[37860] LOADER: Cookie found at offset 0x35D3C2
[37860] LOADER: restoring linux process name from _PYI_PROCNAME: RhythmPyDev
[37860] LOADER: Already in the child - running user's code.
[37860] LOADER: Python library: /home/assassin/Git/RhythmPy/dist/RhythmPyDev/libpython3.9.so.1.0
[37860] LOADER: Loaded functions from Python library.
[37860] LOADER: Manipulating environment (sys.path, sys.prefix)
[37860] LOADER: sys.prefix is /home/assassin/Git/RhythmPy/dist/RhythmPyDev
[37860] LOADER: Pre-init sys.path is /home/assassin/Git/RhythmPy/dist/RhythmPyDev/base_library.zip:/home/assassin/Git/RhythmPy/dist/RhythmPyDev/lib-dynload:/home/assassin/Git/RhythmPy/dist/RhythmPyDev
[37860] LOADER: Setting runtime options
[37860] LOADER: Initializing python
[37860] LOADER: Overriding Python's sys.path
[37860] LOADER: Post-init sys.path is /home/assassin/Git/RhythmPy/dist/RhythmPyDev/base_library.zip:/home/assassin/Git/RhythmPy/dist/RhythmPyDev/lib-dynload:/home/assassin/Git/RhythmPy/dist/RhythmPyDev
[37860] LOADER: Setting sys.argv
[37860] LOADER: setting sys._MEIPASS
[37860] LOADER: importing modules from CArchive
[37860] LOADER: extracted struct
[37860] LOADER: callfunction returned...
[37860] LOADER: extracted pyimod01_os_path
[37860] LOADER: callfunction returned...
[37860] LOADER: extracted pyimod02_archive
[37860] LOADER: callfunction returned...
[37860] LOADER: extracted pyimod03_importers
[37860] LOADER: callfunction returned...
[37860] LOADER: Installing PYZ archive with Python modules.
[37860] LOADER: PYZ archive: PYZ-00.pyz
[37860] LOADER: Running pyiboot01_bootstrap.py
[37860] LOADER: Running pyi_rth_multiprocessing.py
[37860] LOADER: Running pyi_rth_certifi.py
[37860] LOADER: Running pyi_rth__tkinter.py
[37860] LOADER: Running __main__.py

Traceback (most recent call last):
  File "PIL/ImageTk.py", line 176, in paste
_tkinter.TclError: invalid command name "PyImagingPhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gui/__main__.py", line 144, in Create_Widgets
  File "PIL/ImageTk.py", line 115, in __init__
  File "PIL/ImageTk.py", line 180, in paste
ModuleNotFoundError: No module named 'PIL._tkinter_finder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gui/__main__.py", line 253, in __init__
  File "Gui/__main__.py", line 48, in __init__
  File "Gui/__main__.py", line 159, in Create_Widgets
  File "CloseGlobal.py", line 22, in CloseGlobal
SystemExit
[37860] LOADER: OK.
[37860] LOADER: Manually flushing stdout and stderr
[37860] LOADER: Cleaning up Python interpreter.
[37859] LOADER: Restoring signal handlers
[37859] LOADER: freeing args
[37859] LOADER: returning child exit status 0
[37859] LOADER: Back to parent (RC: 0)
[37859] LOADER: Doing cleanup
[37859] LOADER: Freeing archive status for /home/assassin/Git/RhythmPy/dist/RhythmPyDev/RhythmPyDev
```

**Comment by rokm** [comment]
And if you add `PIL._tkinter_finder` to hiddenimports?

**Comment by assassinsorrow** [comment]
this has resolved the issue.
is there any reason as to why `PIL._tkinter_finder` is not included in the `PIL` hidden import?

**Comment by rokm** [comment]
Adding `PIL` to hiddenimports does not automatically add all `PIL` submodules; it might, if they are all imported from `PIL` in a way that PyInstaller can keep track of, but that's not necessarily the case. 

In this case,  [line 180 of `PIL/ImageTk.py` imports `PIL._imagingtk`](https://github.com/python-pillow/Pillow/blob/cc2db17271cea6a8d44c7166ab5de3aef4a2657e/src/PIL/ImageTk.py#L180), which is C extension. This C extension in turn imports `PIL._tkinter_finder`, but because PyInstaller cannot analyze C extensions, that module ends up missing.

**Comment by assassinsorrow** [comment]
Thank you for clarifying this and helping me resolve this issue!
