### ISSUE TITLE
Highest TF version currently supported

### ISSUE THREAD

**Issue by wangwenchao-job** [pyinstaller/pyinstaller#5860]
Please use the mailing list see <http://www.pyinstaller.org/support.html#mailing-list> for details.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker, but closed.

* system info
ubuntu 18.04
pyinstaller 3.6
tensorflow 2.4.0
docker 19.03

* errors
** in docker
```
no module named '_ssl'
```

** out docker
```
[22986] mod is NULL - structTraceback (most recent call last):
  File "/home/jianzhi/anaconda3/lib/python3.7/struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
[22986] mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "/home/jianzhi/anaconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod02_archive.py", line 30, in <module>
    import struct
ModuleNotFoundError: No module named 'struct'
[22986] mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "/home/jianzhi/anaconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 26, in <module>
    from pyimod02_archive import ArchiveReadError, ZlibArchiveReader
ModuleNotFoundError: No module named 'pyimod02_archive'
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[22986] Failed to execute script pyiboot01_bootstrap

```

I have tried:
```
pyinstaller main.py --hidden_import xxx
```
or

change the main.spec file as :
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['/home/jianzhi/govion/feature/full_classifier'],
             binaries=[],
             datas=[],
             hiddenimports=['pkg_resources.py2_warn','numpy.core._dtype_ctypes','tensorflow.contrib','_struct','struct','pyimod02_archive','pyimod03_importers'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='main')

```

But none of that solves the problem.

So I would like to know what the highest version of TF is currently supported. I saw it in an issue in 2019, but it only supports 1.14. I don't know what it is now, and how to solve the above problems?

**Comment by bwoodsend** [comment]
> Please use the mailing list see http://www.pyinstaller.org/support.html#mailing-list for details.

> Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker, but closed.

Tensorflow is dealt with in the hooks repo. I suggest you look through [its changelog](https://github.com/diepholz/pyinstaller-hooks-contrib/blob/master/CHANGELOG.rst) for what package versions have been known to work when.
