### ISSUE TITLE
ImportError: Loader FrozenImporter cannot handle module os

### ISSUE THREAD

**Issue by thread-liu** [pyinstaller/pyinstaller#5882]
I used PyInstaller to package in GitLab CI, the packaging was successful, but this error occurred when executing EXE. Could you tell me what caused it? `Building EXE from EXE-00.toc completed successfully`

```
$ python3 -V
Python 3.8.3
$ c:\python38\python.exe -m venv venv
$ venv/Scripts/activate.bat
$ venv/Scripts/python -m pip install --upgrade pip
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting pip
  Downloading https://mirrors.aliyun.com/pypi/packages/cd/82/04e9aaf603fdbaecb4323b9e723f13c92c245f6ab2902195c53987848c78/pip-21.1.2-py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-21.1.2
$ venv/Scripts/python -m pip install -r dev_requirements.txt
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Obtaining file:///C:/Gitlab-Runner/builds/k1-53foi/0/toolkits/udb-tools (from -r dev_requirements.txt (line 1))
Collecting pyserial~=3.4
  Using cached https://mirrors.aliyun.com/pypi/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting click~=7.1.2
  Using cached https://mirrors.aliyun.com/pypi/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting setuptools~=50.3.2
  Using cached https://mirrors.aliyun.com/pypi/packages/6d/38/c21ef5034684ffc0412deefbb07d66678332290c14bb5269c85145fbd55e/setuptools-50.3.2-py3-none-any.whl (785 kB)
Collecting libusb~=1.0.23b7
  Using cached https://mirrors.aliyun.com/pypi/packages/bf/95/f8e4eb37bd8ce02aff9dba1cff8823498f18366866ab769ced916ce68315/libusb-1.0.23b7.zip (251 kB)
Collecting pyinstaller
  Using cached pyinstaller-4.3-py3-none-any.whl
Collecting tinyaes==1.0.1
  Using cached https://mirrors.aliyun.com/pypi/packages/8d/ff/3c4b908f063cbc3b8f61fc56ea85cf68b586eda572fb219b04aedea912d4/tinyaes-1.0.1-cp38-cp38-win_amd64.whl (21 kB)
Collecting pyinstaller-hooks-contrib>=2020.6
  Using cached https://mirrors.aliyun.com/pypi/packages/27/c7/58a634d861e4744ac62dca4a4992ace8def8b05dab91e6b25e5043e79acf/pyinstaller_hooks_contrib-2021.1-py2.py3-none-any.whl (181 kB)
Collecting altgraph
  Using cached https://mirrors.aliyun.com/pypi/packages/ee/3d/bfca21174b162f6ce674953f1b7a640c1498357fa6184776029557c25399/altgraph-0.17-py2.py3-none-any.whl (21 kB)
Collecting pefile>=2017.8.1
  Using cached https://mirrors.aliyun.com/pypi/packages/dc/8e/99fde2fe50afebbb1ef6f46508203e66e45c6e3966caacd219152c8a52e1/pefile-2021.5.24.tar.gz (66 kB)
Collecting pywin32-ctypes>=0.2.0
  Using cached https://mirrors.aliyun.com/pypi/packages/9e/4b/3ab2720f1fa4b4bc924ef1932b842edf10007e4547ea8157b0b9fc78599a/pywin32_ctypes-0.2.0-py2.py3-none-any.whl (28 kB)
Collecting future
  Using cached https://mirrors.aliyun.com/pypi/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829 kB)
Using legacy 'setup.py install' for libusb, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pefile, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Installing collected packages: future, setuptools, pywin32-ctypes, pyinstaller-hooks-contrib, pefile, click, altgraph, usb, tinyaes, pyserial, pyinstaller, libusb
    Running setup.py install for future: started
    Running setup.py install for future: finished with status 'done'
  Attempting uninstall: setuptools
    Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
    Running setup.py install for pefile: started
    Running setup.py install for pefile: finished with status 'done'
  Running setup.py develop for usb
    Running setup.py install for libusb: started
    Running setup.py install for libusb: finished with status 'done'
Successfully installed altgraph-0.17 click-7.1.2 future-0.18.2 libusb-1.0.23b7 pefile-2021.5.24 pyinstaller-4.3 pyinstaller-hooks-contrib-2021.1 pyserial-3.5 pywin32-ctypes-0.2.0 setuptools-50.3.2 tinyaes-1.0.1 usb-0.1.dev128+g42c06ae
$ venv/Scripts/python -m pip list
Package                   Version             Location
------------------------- ------------------- -----------------------------------------------------
altgraph                  0.17
click                     7.1.2
future                    0.18.2
libusb                    1.0.23b7
pefile                    2021.5.24
pip                       21.1.2
pyinstaller               4.3
pyinstaller-hooks-contrib 2021.1
pyserial                  3.5
pywin32-ctypes            0.2.0
setuptools                50.3.2
tinyaes                   1.0.1
usb                       0.1.dev128+g42c06ae c:\gitlab-runner\builds\k1-53foi\0\toolkits\usb-tools
$ venv/Scripts/python release_project.py
31 INFO: PyInstaller: 3.6
31 INFO: Python: 3.8.3
45 INFO: Platform: Windows-10-10.0.19041-SP0
46 INFO: wrote C:\Gitlab-Runner\builds\k1-53foi\0\toolkits\usb-tools\usb.exe.spec
47 INFO: UPX is not available.
47 INFO: Removing temporary files and cleaning cache in C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\pyinstaller
75 INFO: Extending PYTHONPATH with paths
['C:\\Gitlab-Runner\\builds\\k1-53foi\\0\\toolkits',
 'C:\\Gitlab-Runner\\builds\\k1-53foi\\0\\toolkits\\usb-tools']
75 INFO: Will encrypt Python bytecode with key: 8SDkIzYyiQSdVx8U
83 INFO: Adding dependencies on pyi_crypto.py module
83 INFO: checking Analysis
83 INFO: Building Analysis because Analysis-00.toc is non existent
83 INFO: Initializing module dependency graph...
85 INFO: Caching module graph hooks...
90 INFO: Analyzing base_library.zip ...
1703 INFO: Processing pre-find module path hook   distutils
1712 INFO: distutils: retargeting to non-venv dir 'c:\\python38\\lib'
3429 INFO: Caching module dependency graph...
3504 INFO: running Analysis Analysis-00.toc
3515 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python38\python3.exe
3549 INFO: Analyzing C:\Gitlab-Runner\builds\k1-53foi\0\toolkits\usb-tools\usb-tools.py
3827 INFO: Processing pre-find module path hook   site
3837 INFO: site: retargeting to fake-dir 'c:\\python38\\lib\\site-packages\\PyInstaller\\fake-modules'
4762 INFO: Analyzing hidden import 'Crypto.Cipher.AES'
4914 INFO: Processing module hooks...
4914 INFO: Loading module hook "hook-Crypto.py"...
4926 INFO: Loading module hook "hook-distutils.py"...
4927 INFO: Loading module hook "hook-encodings.py"...
4971 INFO: Loading module hook "hook-lib2to3.py"...
4977 INFO: Loading module hook "hook-pkg_resources.py"...
5154 INFO: Processing pre-safe import module hook   win32com
5319 INFO: Excluding import '__main__'
5327 INFO:   Removing import of __main__ from module pkg_resources
5327 INFO: Loading module hook "hook-pydoc.py"...
5328 INFO: Loading module hook "hook-pythoncom.py"...
5466 INFO: Loading module hook "hook-pywintypes.py"...
5633 INFO: Loading module hook "hook-sysconfig.py"...
5640 INFO: Loading module hook "hook-win32com.py"...
5857 INFO: Loading module hook "hook-xml.dom.domreg.py"...
5861 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
5861 INFO: Loading module hook "hook-xml.py"...
5861 INFO: Loading module hook "hook-_tkinter.py"...
5938 INFO: checking Tree
5938 INFO: Building Tree because Tree-00.toc is non existent
5938 INFO: Building Tree Tree-00.toc
5980 INFO: checking Tree
5980 INFO: Building Tree because Tree-01.toc is non existent
5989 INFO: Building Tree Tree-01.toc
6002 INFO: Looking for ctypes DLLs
6058 INFO: Analyzing run-time hooks ...
6069 INFO: Including run-time hook 'pyi_rth__tkinter.py'
6070 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
6072 INFO: Including run-time hook 'pyi_rth_pkgres.py'
6073 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
6078 INFO: Looking for dynamic libraries
6573 INFO: Looking for eggs
6573 INFO: Using Python library c:\python38\python38.dll
6573 INFO: Found binding redirects: 
[]
6582 INFO: Warnings written to C:\Gitlab-Runner\builds\k1-53foi\0\toolkits\usb-tools\build\usb.exe\warn-usb.exe.txt
6627 INFO: Graph cross-reference written to C:\Gitlab-Runner\builds\k1-53foi\0\toolkits\usb-tools\build\usb.exe\xref-usb.exe.html
6652 INFO: Appending 'binaries' from .spec
6656 INFO: checking PYZ
6656 INFO: Building PYZ because PYZ-00.toc is non existent
6656 INFO: Building PYZ (ZlibArchive) C:\Gitlab-Runner\builds\k1-53foi\0\toolkits\usb-tools\build\usb.exe\PYZ-00.pyz
7367 INFO: Building PYZ (ZlibArchive) C:\Gitlab-Runner\builds\k1-53foi\0\toolkits\usb-tools\build\usb.exe\PYZ-00.pyz completed successfully.
7379 INFO: checking PKG
7379 INFO: Building PKG because PKG-00.toc is non existent
7379 INFO: Building PKG (CArchive) PKG-00.pkg
11477 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
11499 INFO: Bootloader c:\python38\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
11499 INFO: checking EXE
11499 INFO: Building EXE because EXE-00.toc is non existent
11499 INFO: Building EXE from EXE-00.toc
11500 INFO: Copying icons from ['icon.ico']
11529 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
11529 INFO: Writing RT_ICON 1 resource with 16936 bytes
11548 INFO: Updating manifest in C:\Gitlab-Runner\builds\k1-53foi\0\toolkits\usb-tools\build\usb.exe\run.exe.a_8q072d
11576 INFO: Updating resource type 24 name 1 language 0
11593 INFO: Appending archive to EXE C:\Gitlab-Runner\builds\k1-53foi\0\toolkits\usb-tools\dist\usb.exe
11636 INFO: Building EXE from EXE-00.toc completed successfully.
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 434, in get_code
    return self._pyz_archive.extract(fullname)[1]
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod02_archive.py", line 369, in extract
    obj = zlib.decompress(obj)
zlib.error: Error -3 while decompressing data: incorrect header check
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 27, in <module>
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 603, in exec_module
    bytecode = self.get_code(spec.loader_state)
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 436, in get_code
    raise ImportError('Loader FrozenImporter cannot handle module ' + fullname)
ImportError: Loader FrozenImporter cannot handle module os
[464] Failed to execute script pyiboot01_bootstrap
```

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by rokm** [comment]
> $ venv/Scripts/python release_project.py
31 INFO: PyInstaller: 3.6
31 INFO: Python: 3.8.3

I very much doubt PyInstaller 3.6 supported python 3.8. If I recall correctly, that was added in 4.1.

But seeing how your pip install is actually installing PyInstaller 4.3, I'd say that your `release_project.py` is calling wrong version of PyInstaller (3.6 that's installed somewhere else instead of 4.3 that's installed within the venv).
