### ISSUE TITLE
ModuleNotFoundError: No module named 'models.yolo'

### ISSUE THREAD

**Issue by wantaoliu** [pyinstaller/pyinstaller#5928]
Traceback (most recent call last):
  File "shipDetectMain.py", line 74, in resultWindows
  File "view\resultShp.py", line 61, in __init__
  File "view\resultShp.py", line 129, in infraneDetect
  File "detect.py", line 204, in mianDetect
  File "detect.py", line 54, in detect
  File "models\experimental.py", line 138, in attempt_load
  File "torch\serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models.yolo'

I find the file in the project, why the program did not find the  YOLO file ，packed using pyinstaller，it is right  running on pycharm

**Comment by rokm** [comment]
Your program probably does not directly import `models.yolo` (and very likely other modules as well) and instead relies on deserialization (`unpickler`) to do so. This means that PyInstaller cannot automatically determine the required imports, and you'll need to add them to `hiddenimports` yourself.
