### ISSUE TITLE
Error when trying to run an application when using dash

### ISSUE THREAD

**Issue by martimm00** [pyinstaller/pyinstaller#5930]
## Description of the issue
Hi there!

My python script tries to build a Dash app that provides an implementation of great_expectations with a GUI, and now I need to make it a Windows executable. I'm currently using Windows 10, Python 3.9 with dash_core_components version 1.16.0 (cannot downgrade this one).

The .exe apparently builds successfully from the .py, but it won't ever start because of this error:
```
pkg_resources.DistributionNotFound:` The 'flask-compress' distribution was not found and is required by the application
[18164] Failed to execute script entrypoint
```

I tried many things, starting from changing versions of dash (current is 1.20.0), no need to say flask_compress is installed in the environment (current is 1.9.0) and downgrading Python from 3.9 to 3.6... and no result yet.

I'm new here, more than pleased to join the community!

Let's see if anyone has experienced this issue before and found a feasible solution. Thanks in advance.
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python:  3.9
* Platform:  Windows 10 (English)
### Stacktrace / full error message

```
Traceback (most recent call last):
  File "src\entrypoint.py", line 1, in <module>
    from src.app import create_app
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "src\app.py", line 2, in <module>
    import dash
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "dash\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "dash\dash.py", line 53, in <module>
  File "pkg_resources\__init__.py", line 466, in get_distribution
  File "pkg_resources\__init__.py", line 342, in get_provider
  File "pkg_resources\__init__.py", line 886, in require
  File "pkg_resources\__init__.py", line 772, in resolve
pkg_resources.DistributionNotFound: The 'flask-compress' distribution was not found and is required by the application
[18164] Failed to execute script entrypoint
```

**Comment by rokm** [comment]
You need to collect metadata for `flask-compress`; try adding `--copy-metadata flask-compress` to your PyInstaller command line.
