### ISSUE TITLE
import module requests doesn't work with --strip

### ISSUE THREAD

**Issue by eric15342335** [pyinstaller/pyinstaller#5933]
## Description of the issue
When using argument `--strip` with a `import requests` code, it won't run.
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: `3.8.10`
* Platform: Windows `10`
* How you installed Python: `python.org`
* Did you also try this on another platform? Does it work there?

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import requests
print("1")

```

### Stacktrace / full error message
running:
```
pyinstaller --onedir --noupx --debug imports --strip --clean strip.py
```
and run the produced executable:
```
import ssl # PyInstaller PYZ
# _ssl not found in PYZ
Traceback (most recent call last):
  File "venv\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\rthooks\pyi_rth_certifi.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "ssl.py", line 98, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _ssl: Invalid access to memory location.
[5040] Failed to execute script 'pyi_rth_certifi' due to unhandled exception!
```
[--debug running message](https://gist.github.com/eric15342335/2e68f83f0f9f1ff8652e54823af63284)
[building message](https://gist.github.com/eric15342335/384e4eda1918243fc75a014fd54e3a55)
[bincache10_py38_64bit.zip](https://github.com/pyinstaller/pyinstaller/files/6680404/bincache10_py38_64bit.zip)
[diffoscope?](https://try.diffoscope.org/fdhtqdrskgac.html)

**Comment by bwoodsend** [comment]
It does say in [the docs for `--strip`](https://pyinstaller.readthedocs.io/en/latest/usage.html#cmdoption-s) that it's not recommended for Windows but I've not seen a case for it until now. Out of curiosity, what flavour of `strip` do you have (run `where strip` and `strip -V`)?

**Comment by eric15342335** [comment]
its mingw-w64
```
E:\>strip -V
GNU strip (Binutils for MinGW-W64 x86_64, built by Brecht Sanders) 2.36.1
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```
