### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\maxm~1.m\\Local\\Temp\\_MEI75642\\dash_html_components\\package-info.json'

### ISSUE THREAD

**Issue by martimm00** [pyinstaller/pyinstaller#5960]
## Description of the issue

Hi there!

I'm developing a Python app that uses Dash, html components (dash_core_components, dash_html_components and dash_bootstrap_components) and Great Expectations, in case that matters. Now I need to get a Windows executable from it, and everything seems to be fine while doing so, but when I try to launch the app a FileNotFoundError fires. Here's the whole error:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\maxm~1.m\\AppData\\Local\\Temp\\_MEI75642\\dash_html_components\\package-info.json'

I've tried downgrading Python to 3.6.8 but the same happens.

Anyone knows why could this error fire? I've not managed to find this path in any way, and my username is max so I don't know why it seems to be looking for maxm~1.m neither.

Thank you so much in advance!

### Context information (for bug reports)

* Output of `pyinstaller --version`: 4.3
* Version of Python:  3.9.4
* Platform:  Windows 10

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "src\entrypoint.py", line 1, in <module>
    from src.app import create_app
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocke
d
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module

  File "src\app.py", line 4, in <module>
    import dash_uploader as du
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "dash_uploader\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "dash_uploader\configure_upload.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "dash_html_components\__init__.py", line 12, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MARTIM~1.M
OR\\AppData\\Local\\Temp\\_MEI75642\\dash_html_components\\package-info.json'
[4236] Failed to execute script entrypoint
```

**Comment by bwoodsend** [comment]
Add `--collect-data=dash_html_components` to your build command. And don't diagnose `FileNotFoundError`s ins onefile mode.

**Comment by rokm** [comment]
Also, the latest release of `pyinstaller-hooks-contrib` (v2021.2) [should have a hook for that](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dash_html_components.py).

**Comment by martimm00** [comment]
Thank you!! It worked! The same parameter can be applied to whatever package in case someone has the same error with a different one.
