### ISSUE TITLE
This probably means that tcl wasn't installed properly.

### ISSUE THREAD

**Issue by pokemonchw** [pyinstaller/pyinstaller#5969]
## Description of the issue
The windows environment of the user is windows10(Traditional Chinese), currently, in the feedback received, if and only if the packaged program runs in the environment of this part of users, there will be "This probably means that Tcl wasn‘t installed properly"

### Context information (for bug reports)

* Output of `pyinstaller --version`: 4.3
* Version of Python: 3.9.5
* Platform: Windows Server 2019
* How you installed Python: githun action virtual-env
* Did you also try this on another platform? Does it work there?
No other feedback has been received so far. It works well in simplified Chinese, English, Japanese and other language areas.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message`

```
Traceback (most recent call last):
  File "game.py", line 27 , in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>" , line 986 , in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_ module
  File "Script\Design\start_flow.py", line 2 , in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>" , line 986 , in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_ module
  File "Script\Core\py_cmd.py", line 1 , in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>" , line 986 , in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_ module
  File "Script\Core\flow_handle.py", line 4 , in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>" , line 986 , in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_ module
  File "Script\Core\io_init.py", line 6 , in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>" , line 986 , in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_ module
  File "Script\Core\main_frame.py", line 45 , in <module>
  File "tkinter\__init__.py" line 227  in init
_tkinter.TclError:Can't find a usbale init.tcl in the following directories:
    {C:\Users\a%x{c8 e8\AppData\Local\Temp\_MEI286762\tcl} C:/Users/a%x{c8 e8/AppData/Local/Temp/_MEI26762/tcl8.6 C:/Users/使用者/AppData/Local/Temp/1ib/tcl8.6 D:/lib/tcl8.6 D:/library D:/library D:/tcl8 6.9/library D:/tcl8.6.9/library

This probably means that Tcl wasn't installed properly .[21232] Failed to execute script game

[21232] Failed to execute script game
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
Can we have an example workflow?

**Comment by rokm** [comment]
This indeed looks like filesystem encoding issue with username containing Chinese characters.

But I'm not sure the problem is in PyInstaller's side (e.g., bootloader mangling the path), because if that was the case, the `_tkinter` rthook would have errored out (due to "missing" `tcl` or `tk` dirs) before the entry-point script is ran. So considering the program made it to Tcl initialization, this could also be a problem with Tcl/Tk itself.

@pokemonchw, can you set up a Traditional Chinese machine where the frozen application fails, and then install python (make sure it is installed in user's directory) and then check if the original unfrozen application works? In particular, we want you to test whether Python, tkinter, and Tcl/Tk themselves work on a Traditional Chinese system, when installed in a path that contains those Chinese characters.

**Comment by pokemonchw** [comment]
@rokm OK, I'm contacting bug feeders to try to get the conditions of the recurrence environment. It may take a few more days

**Comment by bwoodsend** [comment]
I'll reopen this if/when you're able pin down a reproducer.

**Comment by fluentmoheshwar** [comment]
Same thing happening to me

**Comment by bwoodsend** [comment]
> I'll reopen this if/when you're able pin down a reproducer.
