### ISSUE TITLE
Error loading Python lib libpython3.7m.dll

### ISSUE THREAD

**Issue by eychei** [pyinstaller/pyinstaller#6000]
## Description of the issue

When executing a generated exe file using the cmd promt in windows the python library files can not be found. 
Executing the same file works in cygwin.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python:  Python 3.7.7
* Platform:  Windows
* How you installed Python:  Sagemath Python
* Did you also try this on another platform? Does it work there? 

Yes

* try the latest development version, using the following command:

Tried the latest develop and also older versions.

### A minimal example program which shows the error

```python
def talk(message):
    return "Talk " + message


def main():
    print(talk("Hello World"))


if __name__ == "__main__":
    main()
```

Build with the following command:

```python
(sage-sh) Think@DESKTOP-48B4LC2:pyinstaller$ pyinstaller --onefile -d bootloader hello.py
155 INFO: PyInstaller: 4.3
156 INFO: Python: 3.7.7
214 INFO: Platform: CYGWIN_NT-10.0-19042-3.1.7-340.x86_64-x86_64-64bit-WindowsPE
217 INFO: wrote /cygdrive/c/pyinstaller/hello.spec
266 INFO: UPX is not available.
270 INFO: Extending PYTHONPATH with paths
['/cygdrive/c/pyinstaller', '/cygdrive/c/pyinstaller']
336 INFO: checking Analysis
337 INFO: Building Analysis because Analysis-00.toc is non existent
338 INFO: Initializing module dependency graph...
360 INFO: Caching module graph hooks...
394 INFO: Analyzing base_library.zip ...
4491 INFO: Processing pre-find module path hook distutils from '/opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
4496 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.7'
8817 INFO: Caching module dependency graph...
9142 INFO: running Analysis Analysis-00.toc
9666 INFO: Analyzing /cygdrive/c/pyinstaller/hello.py
9669 INFO: Processing module hooks...
9670 INFO: Loading module hook 'hook-difflib.py' from '/opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/hooks'...
9674 INFO: Loading module hook 'hook-distutils.py' from '/opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/hooks'...
9686 INFO: Loading module hook 'hook-encodings.py' from '/opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/hooks'...
9922 INFO: Loading module hook 'hook-heapq.py' from '/opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/hooks'...
9925 INFO: Loading module hook 'hook-pickle.py' from '/opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/hooks'...
9928 INFO: Loading module hook 'hook-sysconfig.py' from '/opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/hooks'...
9931 INFO: Loading module hook 'hook-xml.py' from '/opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/hooks'...
10502 INFO: Looking for ctypes DLLs
10503 INFO: Analyzing run-time hooks ...
10514 INFO: Looking for dynamic libraries
14709 INFO: Looking for eggs
14709 INFO: Using Python library /usr/bin/libpython3.7m.dll
14714 INFO: Warnings written to /cygdrive/c/pyinstaller/build/hello/warn-hello.txt
15230 INFO: Graph cross-reference written to /cygdrive/c/pyinstaller/build/hello/xref-hello.html
15241 INFO: checking PYZ
15242 INFO: Building PYZ because PYZ-00.toc is non existent
15243 INFO: Building PYZ (ZlibArchive) /cygdrive/c/pyinstaller/build/hello/PYZ-00.pyz
15763 INFO: Building PYZ (ZlibArchive) /cygdrive/c/pyinstaller/build/hello/PYZ-00.pyz completed successfully.
15769 INFO: checking PKG
15770 INFO: Building PKG because PKG-00.toc is non existent
15771 INFO: Building PKG (CArchive) PKG-00.pkg
18679 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
18683 INFO: Bootloader /opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/bootloader/CYGWIN_NT-10.0-19042-64bit/run_d.exe
18683 INFO: checking EXE
18684 INFO: Building EXE because EXE-00.toc is non existent
18685 INFO: Building EXE from EXE-00.toc
18686 INFO: Appending archive to EXE /cygdrive/c/pyinstaller/dist/hello.exe
18697 INFO: Building EXE from EXE-00.toc completed successfully.

```

### Stacktrace / full error message

```

C:\pyinstaller\dist>hello.exe
[1459] PyInstaller Bootloader 3.x
[1459] LOADER: executable is /dist/hello
[1459] LOADER: homepath is /dist
[1459] LOADER: _MEIPASS2 is NULL
[1459] LOADER: archivename is /dist/hello
[1459] LOADER: Cookie found at offset 0x72DBA4
[1459] LOADER: Extracting binaries
[1459] LOADER: Executing self as child
[1459] LOADER: set _MEIPASS2 to /cygdrive/c/Users/Think/AppData/Local/Temp/_MEIiQ3Gwl
[1459] LOADER: LD_LIBRARY_PATH=/cygdrive/c/Users/Think/AppData/Local/Temp/_MEIiQ3Gwl
[1459] LOADER: Registering signal handlers
[1460] PyInstaller Bootloader 3.x
[1460] LOADER: executable is /dist/hello
[1460] LOADER: homepath is /dist
[1460] LOADER: _MEIPASS2 is /cygdrive/c/Users/Think/AppData/Local/Temp/_MEIiQ3Gwl
[1460] LOADER: archivename is /dist/hello
[1460] LOADER: Cookie found at offset 0x72DBA4
[1460] LOADER: Already in the child - running user's code.
[1460] LOADER: Python library: /cygdrive/c/Users/Think/AppData/Local/Temp/_MEIiQ3Gwl/libpython3.7m.dll
[1460] Error loading Python lib '/cygdrive/c/Users/Think/AppData/Local/Temp/_MEIiQ3Gwl/libpython3.7m.dll': dlopen: No such file or directory
[1459] LOADER: Restoring signal handlers
[1459] LOADER: freeing args
[1459] LOADER: returning child exit status 255
[1459] LOADER: Back to parent (RC: 255)
[1459] LOADER: Doing cleanup
[1459] LOADER: Freeing archive status for /dist/hello

```

_MEI directory is being generated and lib files are present.

Using cygwin to execute the same file works:

```
(sage-sh) Think@DESKTOP-48B4LC2:dist$ ./hello.exe
[1115] PyInstaller Bootloader 3.x
[1115] LOADER: executable is /cygdrive/c/pyinstaller/dist/hello
[1115] LOADER: homepath is /cygdrive/c/pyinstaller/dist
[1115] LOADER: _MEIPASS2 is NULL
[1115] LOADER: archivename is /cygdrive/c/pyinstaller/dist/hello
[1115] LOADER: Cookie found at offset 0x72DBA4
[1115] LOADER: Extracting binaries
[1115] LOADER: Executing self as child
[1115] LOADER: set _MEIPASS2 to /tmp/_MEICgxm44
[1115] LOADER: LD_LIBRARY_PATH_ORIG=/opt/sagemath-9.2/local/bin:
[1115] LOADER: LD_LIBRARY_PATH=/tmp/_MEICgxm44:/opt/sagemath-9.2/local/bin:
[1115] LOADER: Registering signal handlers
[1116] PyInstaller Bootloader 3.x
[1116] LOADER: executable is /cygdrive/c/pyinstaller/dist/hello
[1116] LOADER: homepath is /cygdrive/c/pyinstaller/dist
[1116] LOADER: _MEIPASS2 is /tmp/_MEICgxm44
[1116] LOADER: archivename is /cygdrive/c/pyinstaller/dist/hello
[1116] LOADER: Cookie found at offset 0x72DBA4
[1116] LOADER: Already in the child - running user's code.
[1116] LOADER: Python library: /tmp/_MEICgxm44/libpython3.7m.dll
[1116] LOADER: Loaded functions from Python library.
[1116] LOADER: Manipulating environment (sys.path, sys.prefix)
[1116] LOADER: sys.prefix is /tmp/_MEICgxm44
[1116] LOADER: Pre-init sys.path is /tmp/_MEICgxm44/base_library.zip:/tmp/_MEICgxm44/lib-dynload:/tmp/_MEICgxm44
[1116] LOADER: Setting runtime options
[1116] LOADER: Initializing python
[1116] LOADER: Overriding Python's sys.path
[1116] LOADER: Post-init sys.path is /tmp/_MEICgxm44/base_library.zip:/tmp/_MEICgxm44/lib-dynload:/tmp/_MEICgxm44
[1116] LOADER: Setting sys.argv
[1116] LOADER: setting sys._MEIPASS
[1116] LOADER: importing modules from CArchive
[1116] LOADER: extracted struct
[1116] LOADER: callfunction returned...
[1116] LOADER: extracted pyimod01_os_path
[1116] LOADER: callfunction returned...
[1116] LOADER: extracted pyimod02_archive
[1116] LOADER: callfunction returned...
[1116] LOADER: extracted pyimod03_importers
[1116] LOADER: callfunction returned...
[1116] LOADER: Installing PYZ archive with Python modules.
[1116] LOADER: PYZ archive: PYZ-00.pyz
[1116] LOADER: Running pyiboot01_bootstrap.py
[1116] LOADER: Running hello.py
Talk Hello World
[1116] LOADER: OK.
[1116] LOADER: Manually flushing stdout and stderr
[1116] LOADER: Cleaning up Python interpreter.
[1115] LOADER: Restoring signal handlers
[1115] LOADER: freeing args
[1115] LOADER: returning child exit status 0
[1115] LOADER: Back to parent (RC: 0)
[1115] LOADER: Doing cleanup
[1115] LOADER: Freeing archive status for /cygdrive/c/pyinstaller/dist/hello
```

**Comment by bwoodsend** [comment]
Does it work without `--onefile`? These issues are 100x easier to diagnose in `--onedir` mode.

**Comment by eychei** [comment]
Yes it does work with --onedir mode because the libs are within the executable directory.
Also changing the tmp directory with --runtime-tmpdir PATH gives the same error.
It seems that the files are not found because of the directory format? Maybe the backslash?

This is the output when using a different folder with the following command: 
(sage-sh) Think@DESKTOP-48B4LC2:pyinstaller$ pyinstaller --onefile --runtime-tmpdir '' -d bootloader hello.py
107 INFO: PyInstaller: 4.3
107 INFO: Python: 3.7.7
171 INFO: Platform: CYGWIN_NT-10.0-19042-3.1.7-340.x86_64-x86_64-64bit-WindowsPE
174 INFO: wrote /cygdrive/c/pyinstaller/hello.spec
236 INFO: UPX is not available.
239 INFO: Extending PYTHONPATH with paths
['/cygdrive/c/pyinstaller', '/cygdrive/c/pyinstaller']
301 INFO: checking Analysis
372 INFO: checking PYZ
386 INFO: checking PKG
389 INFO: Building because toc changed
389 INFO: Building PKG (CArchive) PKG-00.pkg
3228 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
3235 INFO: Bootloader /opt/sagemath-9.2/local/lib/python3.7/site-packages/PyInstaller/bootloader/CYGWIN_NT-10.0-19042-64bit/run_d.exe
3236 INFO: checking EXE
3238 INFO: Building because toc changed
3239 INFO: Building EXE from EXE-00.toc
3241 INFO: Appending archive to EXE /cygdrive/c/pyinstaller/dist/hello.exe
3259 INFO: Building EXE from EXE-00.toc completed successfully.


Output of  windows cmd when executing:

C:\pyinstaller\dist>hello.exe
[1825] PyInstaller Bootloader 3.x
[1825] LOADER: executable is /dist/hello
[1825] LOADER: homepath is /dist
[1825] LOADER: _MEIPASS2 is NULL
[1825] LOADER: archivename is /dist/hello
[1825] LOADER: Cookie found at offset 0x72DBD4
[1825] LOADER: Extracting binaries
[1825] LOADER: Found runtime-tmpdir
[1825] LOADER: Executing self as child
[1825] LOADER: set _MEIPASS2 to /_MEIY5IZTm
[1825] LOADER: LD_LIBRARY_PATH=/_MEIY5IZTm
[1825] LOADER: Registering signal handlers
[1826] PyInstaller Bootloader 3.x
[1826] LOADER: executable is /dist/hello
[1826] LOADER: homepath is /dist
[1826] LOADER: _MEIPASS2 is /_MEIY5IZTm
[1826] LOADER: archivename is /dist/hello
[1826] LOADER: Cookie found at offset 0x72DBD4
[1826] LOADER: Already in the child - running user's code.
[1826] LOADER: Python library: /_MEIY5IZTm/libpython3.7m.dll
[1826] Error loading Python lib '/_MEIY5IZTm/libpython3.7m.dll': dlopen: No such file or directory
[1825] LOADER: Restoring signal handlers
[1825] LOADER: freeing args
[1825] LOADER: returning child exit status 255
[1825] LOADER: Back to parent (RC: 255)
[1825] LOADER: Doing cleanup
[1825] LOADER: Freeing archive status for /dist/hello

**Comment by rokm** [comment]
>  It seems that the files are not found because of the directory format? Maybe the backslash?

That's a good guess, but the truth is a bit more sinister; the dlopen() call is failing because dependent DLLs of libpython3.7m.dll cannot be resolved. It turns out that [LD_LIBRARY_PATH does not have the same effect under Cygwin](https://cygwin.cygwin.narkive.com/07lSLoHQ/dlopen-doesn-t-use-ld-library-path-was-dlopen-and-cygcheck-inconsistency) as it does on linux, and we need to either add _MEIPASS to `PATH` or pass it to `SetDllDirectory`.

@eychei Can you give #6002 a try and see if it fixes the problem in your environment?

**Comment by eychei** [comment]
First thanks for the fast patch. 
I did try to build but got errors. Maybe I am doing something wrong.
Did the following:

Cloned the repo at: https://github.com/pyinstaller/pyinstaller/tree/37adc3ef5e2adc7d8cade3248fe0942ed5430345
Build the bootloader with: 
cd bootloader
python ./waf all

Build pyinstaller with: python setup.py install
No errors so far.

Trying to build the exe I got errors:

(sage-sh) Think@DESKTOP-48B4LC2:pyinstaller$ pyinstaller --onefile -d bootloader hello.py
72 INFO: PyInstaller: 5.0.dev0
73 INFO: Python: 3.7.7
114 INFO: Platform: CYGWIN_NT-10.0-19042-3.1.7-340.x86_64-x86_64-64bit-WindowsPE
117 INFO: wrote /cygdrive/c/pyinstaller/hello.spec
150 INFO: UPX is not available.
152 INFO: Extending PYTHONPATH with paths
['/cygdrive/c/pyinstaller', '/cygdrive/c/pyinstaller']
183 INFO: checking Analysis
229 INFO: checking PYZ
238 INFO: checking PKG
240 INFO: Building because toc changed
241 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "/opt/sagemath-9.2/local/bin/pyinstaller", line 33, in <module>
    sys.exit(load_entry_point('pyinstaller==5.0.dev0', 'console_scripts', 'pyinstaller')())
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/building/build_main.py", line 758, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/building/build_main.py", line 705, in build
    exec(code, spec_namespace)
  File "/cygdrive/c/pyinstaller/hello.spec", line 40, in <module>
    entitlements_file=None )
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/building/api.py", line 515, in __init__
    entitlements_file=self.entitlements_file
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/building/api.py", line 208, in __init__
    self.__postinit__()
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/building/datastruct.py", line 159, in __postinit__
    self.assemble()
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/building/api.py", line 302, in assemble
    pylib_name=pylib_name)
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/archive/writers.py", line 338, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/archive/writers.py", line 64, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/archive/writers.py", line 89, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/archive/writers.py", line 379, in add
    code = get_code_object(nm, pathnm)
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/building/utils.py", line 657, in get_code_object
    co = _load_code(modname, filename)
  File "/opt/sagemath-9.2/local/lib/python3.7/site-packages/pyinstaller-5.0.dev0-py3.7.egg/PyInstaller/building/utils.py", line 614, in _load_code
    loader = importer.find_module(modname)
AttributeError: 'NoneType' object has no attribute 'find_module'


Maybe I am missing something.

**Comment by bwoodsend** [comment]
Can you use `pip install -e .` instead of `setup.py install`. The latter was deprecated ages ago and does some pretty weird stuff.

**Comment by eychei** [comment]
How do I use that?

pip install -e https://github.com/pyinstaller/pyinstaller/tree/37adc3ef5e2adc7d8cade3248fe0942ed5430345

Does not work.

**Comment by rokm** [comment]
```
pip install -e pyinstaller/
```
or 
```
cd pyinstaller/
pip install -e .
```

**Comment by eychei** [comment]
just installed and got the same error:

(sage-sh) Think@DESKTOP-48B4LC2:pyinstaller$ pyinstaller --onefile -d bootloader hello.py
632 INFO: PyInstaller: 5.0.dev0+37adc3ef5e
634 INFO: Python: 3.7.7
683 INFO: Platform: CYGWIN_NT-10.0-19042-3.1.7-340.x86_64-x86_64-64bit-WindowsPE
686 INFO: wrote /cygdrive/c/pyinstaller/hello.spec
734 INFO: UPX is not available.
736 INFO: Extending PYTHONPATH with paths
['/cygdrive/c/pyinstaller', '/cygdrive/c/pyinstaller']
769 INFO: checking Analysis
833 INFO: checking PYZ
853 INFO: checking PKG
856 INFO: Building because toc changed
857 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "/opt/sagemath-9.2/local/bin/pyinstaller", line 33, in <module>
    sys.exit(load_entry_point('pyinstaller', 'console_scripts', 'pyinstaller')())
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/building/build_main.py", line 758, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/building/build_main.py", line 705, in build
    exec(code, spec_namespace)
  File "/cygdrive/c/pyinstaller/hello.spec", line 40, in <module>
    entitlements_file=None )
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/building/api.py", line 515, in __init__
    entitlements_file=self.entitlements_file
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/building/api.py", line 208, in __init__
    self.__postinit__()
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/building/datastruct.py", line 159, in __postinit__
    self.assemble()
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/building/api.py", line 302, in assemble
    pylib_name=pylib_name)
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/archive/writers.py", line 338, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/archive/writers.py", line 64, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/archive/writers.py", line 89, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/archive/writers.py", line 379, in add
    code = get_code_object(nm, pathnm)
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/building/utils.py", line 657, in get_code_object
    co = _load_code(modname, filename)
  File "/cygdrive/c/users/think/downloads/pyinstaller-37adc3ef5e2adc7d8cade3248fe0942ed5430345/PyInstaller/building/utils.py", line 614, in _load_code
    loader = importer.find_module(modname)
AttributeError: 'NoneType' object has no attribute 'find_module'

**Comment by rokm** [comment]
What if you uninstall it (`pip uninstall pyinstaller`), then install without `-e` argument (i.e., `pip install .`)?

**Comment by eychei** [comment]
Great! It worked.
The errors are gone and the exe is working properly.

Thank you!
