### ISSUE TITLE
After  converting  .py to .exe using pyinstaller and running the .py file I am getting this error.

### ISSUE THREAD

**Issue by Gaurav7004** [pyinstaller/pyinstaller#6009]
[548 rows x 83 columns]]
83 83 83
Traceback (most recent call last):
  File "UserInterface.py", line 1846, in export
  File "UserInterface.py", line 1559, in summaryReport
  File "pandas\core\frame.py", line 1151, in style
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "pandas\io\formats\style.py", line 51, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "pandas\io\formats\style_render.py", line 62, in <module>
  File "pandas\io\formats\style_render.py", line 67, in StylerRenderer
  File "jinja2\loaders.py", line 310, in __init__
ValueError: The 'pandas' package was not installed in a way that PackageLoader understands.

----------------------------------------------------------------------------------------------------------------------------------
![Screenshot (85)](https://user-images.githubusercontent.com/31065924/125654737-01dcda63-2c8f-4aa1-988c-bd28550c67a5.png)

**Comment by rokm** [comment]
I think that's caused by missing data; try adding `--hiddenimport jinja2 --collect-data "pandas.io.formats"` to your pyinstaller command-line.

**Comment by Gaurav7004** [comment]
Thanks man that worked for me...

**Comment by Gaurav7004** [comment]
> I think that's caused by missing data; try adding `--hiddenimport jinja2 --collect-data "pandas.io.formats"` to your pyinstaller command-line.

Thanks that worked ....
