### ISSUE TITLE
runw.exe file not found

### ISSUE THREAD

**Issue by NHades** [pyinstaller/pyinstaller#6095]
## Description of the issue
After installing pyinstaller V4.5, I am getting a new error. 

### Context information (for bug reports)
previous version (4.4) of Pyinstaller worked fine. 

* Output of `pyinstaller --version`: ```4.5```
* Version of Python: 3.9.6
* Platform: Windows English
* How you installed Python: pip
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "C:\python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39-32\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\python39-32\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\python39-32\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\python39-32\lib\site-packages\PyInstaller\building\build_main.py", line 813, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\python39-32\lib\site-packages\PyInstaller\building\build_main.py", line 760, in build
    exec(code, spec_namespace)
  File "CAE_Analysis_Utilities_Launcher.spec", line 45, in <module>
    exe = EXE(pyz,
  File "C:\python39-32\lib\site-packages\PyInstaller\building\api.py", line 524, in __init__
    self.__postinit__()
  File "C:\python39-32\lib\site-packages\PyInstaller\building\datastruct.py", line 159, in __postinit__
    self.assemble()
  File "C:\python39-32\lib\site-packages\PyInstaller\building\api.py", line 617, in assemble
    self._copyfile(exe, tmpnm)
  File "C:\python39-32\lib\site-packages\PyInstaller\building\api.py", line 794, in _copyfile
    with open(infile, 'rb') as infh:
OSError: [Errno 22] Invalid argument: 'C:\\python39-32\\lib\\site-packages\\PyInstaller\\bootloader\\Windows-32bit\\runw.exe'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by NHades** [comment]
Found out that the "runw.exe" file have been deleted by Microsoft Antivirus file.  the exe file needs to be submitted for windows to certify as valid.
