### ISSUE TITLE
Failed to process hooks and time out after 60 seconds

### ISSUE THREAD

**Issue by arslan437** [pyinstaller/pyinstaller#6101]
## Description of the issue
Not able to convert the code to exe file

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: <3.9.6>
* Platform:  windows 10
* How you installed Python:python.org/downloads  

```
D:\projects\scale\copy>Pyinstaller.exe --onefile  --icon=copy.ico copy.py --upx-dir d:\upx
119 INFO: PyInstaller: 4.5.1
119 INFO: Python: 3.9.6
137 INFO: Platform: Windows-10-10.0.19043-SP0
145 INFO: wrote D:\projects\scale\copy\copy.spec
210 INFO: UPX is available.
210 INFO: Extending PYTHONPATH with paths
['D:\\projects\\scale\\copy', 'D:\\projects\\scale\\copy']
Traceback (most recent call last):
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC 13\AppData\Local\Programs\Python\Python39\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "D:\projects\scale\copy\copy.spec", line 7, in <module>
    a = Analysis(['copy.py'],
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 260, in __init__
    self.hookspath += discover_hook_directories()
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 113, in discover_hook_directories
    output = exec_statement("""
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 98, in exec_statement
    return __exec_statement(statement, capture_stdout=True)
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 79, in __exec_statement
    return __exec_python_cmd(cmd, capture_stdout=capture_stdout)
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 70, in __exec_python_cmd
    txt = compat.exec_python(*cmd, env=pp_env)
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\compat.py", line 565, in exec_python
    return exec_command(*cmdargs, **kwargs)
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\compat.py", line 332, in exec_command
    out = proc.communicate(timeout=60)[0]
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "c:\users\pc 13\appdata\local\programs\python\python39\lib\subprocess.py", line 1510, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '('c:\\users\\pc 13\\appdata\\local\\programs\\python\\python39\\python.exe', '-c', '\nimport sys\nimport pkg_resources\n\nentry_points = pkg_resources.iter_entry_points(\n    \'pyinstaller40\', \'hook-dirs\')\nfor entry_point in entry_points:\n    try:\n        hook_dirs = entry_point.load()()\n        for hook_dir in hook_dirs:\n            print(\'\\n$_pyi:\' + hook_dir + \'*\')\n    except Exception as e:\n        print("discover_hook_directories: Failed to process hook "\n              "entry point \'%s\': %s" % (entry_point, e),\n              file=sys.stderr)\n')' timed out after 60 seconds
```

**Comment by bwoodsend** [comment]
What happens if you run that block of code it got stuck on directly?
```python
import sys
import pkg_resources
entry_points = pkg_resources.iter_entry_points(
    'pyinstaller40', 'hook-dirs')
for entry_point in entry_points:
    try:
        hook_dirs = entry_point.load()()
        for hook_dir in hook_dirs:
            print('\\n$_pyi:' + hook_dir + '*')
    except Exception as e:
        print("discover_hook_directories: Failed to process hook "
              "entry point '%s': %s" % (entry_point, e),
              file=sys.stderr)
```
Presumably, something being loaded from your environment is calling `input()` or something else which causes it to hang but you'll need to track down the offending module yourself.

**Comment by arslan437** [comment]
I have checked my program and I am using input() function in my program. If there is any input function in the project/program then we can bundle it? When I commented that line it worked without any issue.

Basically I have made a console application. I used the input function so that after completing the task console window stays open. can you suggest any alternative?

**Comment by arslan437** [comment]
I have tried 

`os.system("pause")`

it also created the same output. is there any work around to this problem?

**Comment by rokm** [comment]
Does the same problem occur if you rename your entry-point script from `copy.py` to something else, e.g., `program.py`? 

The only way I can imagine that an input or a pause in your program affects hook discovery is if it manages to shadow one of python's modules that PyInstaller uses (in this case, the `copy` module).

**Comment by arslan437** [comment]
After changing the name it worked without any issue. 
Thanks

**Comment by guilmon2009** [comment]
> 更改名称后，它没有任何问题。 谢谢

Which name  do you change？could you please say that in detail？Thank you
