### ISSUE TITLE
PyInstaller 4.5.1 PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by xzhacker123** [pyinstaller/pyinstaller#6135]
## When I go to freeze the program, it can’t be packaged successfully. Does pyinstaller still don’t support aiohttp?
I am a newbie, please give me some suggestions, thank you very much

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: ```3.8.0```
* Platform:  ```macOS Catalina 10.15.7```
* How you installed Python: ```python.org/downloads```
* Did you also try this on another platform? Does it work there?  ```no```

### pip list

```
Package                   Version
------------------------- -----------
aiohttp                   3.7.4.post0
altgraph                  0.17
async-timeout             3.0.1
attrs                     21.2.0
chardet                   4.0.0
idna                      3.2
macholib                  1.14
multidict                 5.1.0
pip                       21.2.4
pyinstaller               4.5.1
pyinstaller-hooks-contrib 2021.2
PyQt5                     5.15.4
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.9.0
setuptools                57.4.0
typing-extensions         3.10.0.0
yarl                      1.6.3
```

### command:
```pyinstaller -D --noupx --windowed main.py```

### main.py

```
import sys
import asyncio
import aiohttp
import time
from PyQt5 import QtWidgets
from PyQt5 import QtCore


class UiMain(QtWidgets.QWidget):
    def __init__(self):
        super(UiMain, self).__init__()
        self.btn = QtWidgets.QPushButton('add', self)
        self.edit = QtWidgets.QTextEdit()

        self.lay = QtWidgets.QVBoxLayout(self)
        self.lay.addWidget(self.edit)
        self.lay.addWidget(self.btn)

        self.btn.clicked.connect(self.slot_start)

        #start task
        self.task = Task()
        self.task.start()
        self.task.sig_task.connect(self.slot_set_text)

    def slot_set_text(self, text):
        self.edit.append(text)

    def slot_start(self):
        self.btn.setText('Running...')
        self.data_creator = DataCreator()
        self.data_creator.sig_data.connect(self.task.slot_add_task)
        self.data_creator.start()


class Task(QtCore.QThread):
    sig_task = QtCore.pyqtSignal(str)


    def __init__(self):
        super(Task, self).__init__()
        self.host = 'http://test/api/{}'
        self.loop = asyncio.new_event_loop()
        pass

    def run(self):
        asyncio.set_event_loop(self.loop)
        self.sig_task.emit("start loop {}".format(time.time()))
        self.loop.run_forever()

    def slot_add_task(self, n):
        asyncio.run_coroutine_threadsafe(self.do_some_work(n), self.loop)

    async def do_some_work(self, x):
        pass

class DataCreator(QtCore.QThread):
    sig_data = QtCore.pyqtSignal(int)

    def __init__(self):
        super(DataCreator, self).__init__()
        self.metaids = [339]*3

    def run(self):
        for meatid in self.metaids:
            self.sig_data.emit(meatid)

app = QtWidgets.QApplication(sys.argv)
window = UiMain()
window.show()
sys.exit(app.exec_())
```

### Stacktrace / full error message

```
(qtasync38) Alex9527-MacBook-Pro:qtasync alex$ pkg.sh
80 INFO: PyInstaller: 4.5.1
81 INFO: Python: 3.8.0
86 INFO: Platform: macOS-10.15.7-x86_64-i386-64bit
86 INFO: wrote /Users/alex/PycharmProjects/qtasync/main.spec
90 INFO: UPX is not available.
92 INFO: Extending PYTHONPATH with paths
['/Users/alex/PycharmProjects/qtasync', '/Users/alex/PycharmProjects/qtasync']
233 INFO: checking Analysis
234 INFO: Building Analysis because Analysis-00.toc is non existent
234 INFO: Initializing module dependency graph...
236 INFO: Caching module graph hooks...
243 INFO: Analyzing base_library.zip ...
3604 INFO: Caching module dependency graph...
3722 INFO: running Analysis Analysis-00.toc
3728 INFO: Analyzing /Users/alex/PycharmProjects/qtasync/main.py
5363 INFO: Processing module hooks...
5363 INFO: Loading module hook 'hook-PyQt5.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5500 WARNING: Hidden import "sip" not found!
5500 INFO: Loading module hook 'hook-encodings.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5557 INFO: Loading module hook 'hook-pickle.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5559 INFO: Loading module hook 'hook-heapq.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5561 INFO: Loading module hook 'hook-difflib.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5562 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5617 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5618 INFO: Import to be excluded not found: 'test'
5618 INFO: Loading module hook 'hook-xml.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5661 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5669 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks'...
5704 INFO: Looking for ctypes DLLs
5710 INFO: Analyzing run-time hooks ...
5713 INFO: Including run-time hook '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
5716 INFO: Including run-time hook '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
5717 INFO: Including run-time hook '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
5719 INFO: Including run-time hook '/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
5730 INFO: Looking for dynamic libraries
5967 INFO: Looking for eggs
5967 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.8/Python
5971 INFO: Warnings written to /Users/alex/PycharmProjects/qtasync/build/main/warn-main.txt
6005 INFO: Graph cross-reference written to /Users/alex/PycharmProjects/qtasync/build/main/xref-main.html
6019 INFO: checking PYZ
6019 INFO: Building PYZ because PYZ-00.toc is non existent
6019 INFO: Building PYZ (ZlibArchive) /Users/alex/PycharmProjects/qtasync/build/main/PYZ-00.pyz
6469 INFO: Building PYZ (ZlibArchive) /Users/alex/PycharmProjects/qtasync/build/main/PYZ-00.pyz completed successfully.
6476 INFO: EXE target arch: x86_64
6476 INFO: Code signing identity: None
6476 INFO: checking PKG
6476 INFO: Building PKG because PKG-00.toc is non existent
6476 INFO: Building PKG (CArchive) PKG-00.pkg
6495 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
6496 INFO: Bootloader /Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/bootloader/Darwin-64bit/run
6496 INFO: checking EXE
6496 INFO: Building EXE because EXE-00.toc is non existent
6496 INFO: Building EXE from EXE-00.toc
6496 INFO: Copying bootloader exe to /Users/alex/PycharmProjects/qtasync/build/main/main
6497 INFO: Converting EXE to target arch (x86_64)
6518 INFO: Removing signature(s) from EXE
6562 INFO: Rewriting executable's macOS SDK version (11.1.0) to match the SDK version of the Python library (10.9.0) in order to avoid inconsistent behavior and potential UI issues in the frozen application.
6563 INFO: Fixing EXE for code signing /Users/alex/PycharmProjects/qtasync/build/main/main
6565 INFO: Re-signing the EXE
6609 INFO: Building EXE from EXE-00.toc completed successfully.
6611 INFO: checking COLLECT
6611 INFO: Building COLLECT because COLLECT-00.toc is non existent
6611 INFO: Building COLLECT COLLECT-00.toc
Traceback (most recent call last):
  File "/Users/alex/venv/qtasync38/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "/Users/alex/PycharmProjects/qtasync/main.spec", line 37, in <module>
    coll = COLLECT(exe,
  File "/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/building/api.py", line 855, in __init__
    self.__postinit__()
  File "/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 159, in __postinit__
    self.assemble()
  File "/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/building/api.py", line 890, in assemble
    fnm = checkCache(fnm, strip=self.strip_binaries,
  File "/Users/alex/venv/qtasync38/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 304, in checkCache
    os.makedirs(os.path.dirname(cachedfile))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/alex/Library/Application Support/pyinstaller/bincache00_py38_64bit/x86_64/adhoc/no-entitlements/yarl'
```

**Comment by rokm** [comment]
Can you check ownership and permissions on the offending parent directory, i.e., `/Users/alex/Library/Application Support/pyinstaller/bincache00_py38_64bit/x86_64/adhoc/no-entitlements`?

Also, try removing the whole `/Users/alex/Library/Application Support/pyinstaller` directory and try running PyInstaller again.

**Comment by xzhacker123** [comment]
this is my ownership and permissions :
```
Alex9527-MacBook-Pro:adhoc alex$ pwd
/Users/alex/Library/Application Support/pyinstaller/bincache00_py38_64bit/x86_64/adhoc
Alex9527-MacBook-Pro:adhoc alex$ ls -l 
total 0
drwxr-xr-x  24 root  staff  768  8 17 14:38 no-entitlements
```
removing the whole `Library/Application Support/pyinstaller` is worked. tks
What causes this?

**Comment by rokm** [comment]
>  What causes this?

Since the owner is `root`, my guess would be that ran PyInstaller via `sudo` at some point (not necessarily freezing the same script/project).

And as you can see from permissions on the directory, only the owner (=root) has the write permissions on that directory, so when you run PyInstaller again as a regular user, it cannot write to it.
