### ISSUE TITLE
win32ctypes.pywin32.pywintypes.error: (1813, 'EnumResourceNamesW')

### ISSUE THREAD

**Issue by Albert337** [pyinstaller/pyinstaller#6140]
when i try to run the follwing code 

`pyi-grab_version ocr.exe`

i get the error,

`Traceback (most recent call last):
  File "D:\anaconda\content\envs\ocr\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "D:\anaconda\content\envs\ocr\lib\site-packages\win32ctypes\pywin32\win32api.py", line 97, in EnumResourceNames
    hModule, resType, _resource.ENUMRESNAMEPROC(callback), 0)
  File "D:\anaconda\content\envs\ocr\lib\site-packages\win32ctypes\core\ctypes\_resource.py", line 73, in _EnumResourceNames
    _BaseEnumResourceNames(hModule, resource_type, lpEnumFunc, lParam)
  File "D:\anaconda\content\envs\ocr\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 64, in check_false
    raise make_error(function, function_name)
OSError: [WinError 1813] 找不到映像文件中指定的资源类型。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\content\envs\ocr\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda\content\envs\ocr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\content\envs\ocr\Scripts\pyi-grab_version.exe\__main__.py", line 7, in <module>
  File "D:\anaconda\content\envs\ocr\lib\site-packages\PyInstaller\utils\cliutils\grab_version.py", line 33, in run
    vs = PyInstaller.utils.win32.versioninfo.decode(args.exe_file)
  File "D:\anaconda\content\envs\ocr\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 136, in decode
    res = win32api.EnumResourceNames(h, pefile.RESOURCE_TYPE['RT_VERSION'])
  File "D:\anaconda\content\envs\ocr\lib\site-packages\win32ctypes\pywin32\win32api.py", line 97, in EnumResourceNames
    hModule, resType, _resource.ENUMRESNAMEPROC(callback), 0)
  File "D:\anaconda\content\envs\ocr\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\anaconda\content\envs\ocr\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1813, 'EnumResourceNamesW', '找不到映像文件中指定的资源类型。')`

i try all my hard to solve the problem,but it failed! Is there any suggestion?thanks!

**Comment by rokm** [comment]
找不到映像文件中指定的资源类型 = The resource type specified in the image file cannot be found.

You are trying to run `the pyi_grab_version` utility against an exe that does not have embedded version information.

**Comment by Albert337** [comment]
> 找不到映像文件中指定的资源类型 = The resource type specified in the image file cannot be found.
> 
> You are trying to run `the pyi_grab_version` utility against an exe that does not have embedded version information.

sorry , but how to solve it ? I just want to add version information into .exe file,thanks!

**Comment by rokm** [comment]
> > 找不到映像文件中指定的资源类型 = The resource type specified in the image file cannot be found.
> > You are trying to run `the pyi_grab_version` utility against an exe that does not have embedded version information.
> 
> sorry , but how to solve it ? I just want to add version information into .exe file,thanks!

This utility *reads* existing version information from a file. So you need to run it against a file that actually contains one.

**Comment by bwoodsend** [comment]
You should be using the `pyi_set_version` command.
