### ISSUE TITLE
Pyinstaller gives me this error

### ISSUE THREAD

**Issue by onurjkk** [pyinstaller/pyinstaller#6207]
Error:

```
C:\Users\{USER}\OneDrive\Desktop\{DIR}>pyinstaller --onefile -w 'app.py'
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pyinstaller.exe\__main__.py", line 4, in <module>
  File "c:\python39\lib\site-packages\PyInstaller\__init__.py", line 54, in <module>
    import pkg_resources
  File "c:\python39\lib\site-packages\pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

I have already tried to uninstall the module and reinstall it but it doesn't work.

Pyinstaller: 4.5
Python: 3.9.6
Platform: Windows 10

**Comment by bwoodsend** [comment]
What's your setuptools version? It appears to be that `import pkg_resources` is the breaking line.

**Comment by onurjkk** [comment]
ok bro, thanks
