### ISSUE TITLE
`AtributeError` raised while tried to freeze a program using `PyQt6` with `PyQt5` uninstalled

### ISSUE THREAD

**Issue by Nurul-GC** [pyinstaller/pyinstaller#6208]
## Description of the issue

```
Hello Great Guys, hope y'all doing very well.

I apreciate a lot your work with this amazing framework
I've been using it since I started my career as Pythonista
and it allowed me to release many wonderful programs..

but unfortunately today I tried to update my codes using PyQt6 instead of PyQt5
so I uninstalled PyQt5 and installed PyQt6 (thought that it was unnecessary)
but I noticed that I was wrong, somehow, PyInstaller depends of the PyQt5
to freeze a program based on PyQt6..

I couldn't understand why, so I made my own tests,
I tried to freeze my program with PyQt5 UNINSTALLED
and then I REINSTALLED it and tried to freeze again
well, it worked, much lighter and complete..

but I still don't understand why needs PyQt5 to freeze a program based on PyQt6!?

thank you very much,
keep safe and awesome!
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: 
	* `4.5.1`
* Version of Python: 
	* `3.7 (on Ubuntu)` and `3.9 (on Windows)`
* Platform: 
	* `GNU/Linux (Ubuntu)` and `Windows 10 (x64)`
* How you installed Python:
	* `python.org/downloads` and `apt`
* Did you also try this on another platform? Does it work there?
	* `Yes, I tried on windows-10-x64, but it raised the same Exception!`

### Stacktrace / full error message

* PyQt5 `UNINSTALLED`

```
83 INFO: PyInstaller: 4.5.1
83 INFO: Python: 3.8.10
99 INFO: Platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.29
102 INFO: UPX is not available.
103 INFO: Removing temporary files and cleaning cache in /home/nurul-gc/.cache/pyinstaller
104 INFO: Extending PYTHONPATH with paths
['/home/nurul-gc/PycharmProjects/Adivinha-Palavra',
 '/home/nurul-gc/PycharmProjects/Adivinha-Palavra']
654 INFO: checking Analysis
655 INFO: Building Analysis because Analysis-00.toc is non existent
655 INFO: Initializing module dependency graph...
660 INFO: Caching module graph hooks...
672 INFO: Analyzing base_library.zip ...
5421 INFO: Processing pre-find module path hook distutils from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
5422 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'
10930 INFO: Caching module dependency graph...
11184 INFO: running Analysis Analysis-00.toc
11233 INFO: Analyzing ap.py
11537 INFO: Processing module hooks...
11538 INFO: Loading module hook 'hook-PyQt6.QtSql.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "ap.spec", line 7, in <module>
    a = Analysis(['ap.py'],
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/build_main.py", line 294, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/datastruct.py", line 159, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/build_main.py", line 473, in assemble
    self.graph.process_post_graph_hooks(self)
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/depend/analysis.py", line 373, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/depend/imphook.py", line 451, in post_graph
    self._load_hook_module()
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/depend/imphook.py", line 408, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/compat.py", line 632, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1027, in load_module
  File "<frozen importlib._bootstrap_external>", line 852, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks/hook-PyQt6.QtSql.py", line 11, in <module>
    from PyInstaller.utils.hooks.qt import add_qt6_dependencies
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/utils/hooks/qt.py", line 162, in <module>
    pyqt5_library_info = QtLibraryInfo('PyQt5')
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/utils/hooks/qt.py", line 54, in __init__
    if hooks.is_module_satisfies("PyQt5 >= 5.15.4"):
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/utils/hooks/__init__.py", line 502, in is_module_satisfies
    version = get_module_attribute(module_name, version_attr)
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/utils/hooks/__init__.py", line 352, in get_module_attribute
    raise AttributeError(
AttributeError: Module 'PyQt5' has no attribute '__version__'
```

### Possible Solution

* PyQt5 `INSTALLED`

```
87 INFO: PyInstaller: 4.5.1
87 INFO: Python: 3.8.10
102 INFO: Platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.29
106 INFO: UPX is not available.
107 INFO: Removing temporary files and cleaning cache in /home/nurul-gc/.cache/pyinstaller
109 INFO: Extending PYTHONPATH with paths
['/home/nurul-gc/PycharmProjects/Adivinha-Palavra',
 '/home/nurul-gc/PycharmProjects/Adivinha-Palavra']
668 INFO: checking Analysis
668 INFO: Building Analysis because Analysis-00.toc is non existent
668 INFO: Initializing module dependency graph...
672 INFO: Caching module graph hooks...
685 INFO: Analyzing base_library.zip ...
5521 INFO: Processing pre-find module path hook distutils from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
5522 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'
11104 INFO: Caching module dependency graph...
11357 INFO: running Analysis Analysis-00.toc
11410 INFO: Analyzing ap.py
11716 INFO: Processing module hooks...
11717 INFO: Loading module hook 'hook-PyQt6.QtSql.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12025 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12051 INFO: Loading module hook 'hook-encodings.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12187 INFO: Loading module hook 'hook-heapq.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12190 INFO: Loading module hook 'hook-PyQt6.QtWidgets.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12340 INFO: Loading module hook 'hook-distutils.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12370 INFO: Loading module hook 'hook-PyQt6.QtGui.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12439 INFO: Loading module hook 'hook-PyQt6.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12455 INFO: Loading module hook 'hook-lib2to3.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12520 INFO: Loading module hook 'hook-sysconfig.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12521 INFO: Loading module hook 'hook-pickle.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12524 INFO: Loading module hook 'hook-sqlite3.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12618 INFO: Loading module hook 'hook-xml.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12863 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12876 INFO: Loading module hook 'hook-distutils.util.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12889 INFO: Loading module hook 'hook-PyQt6.QtCore.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12943 INFO: Loading module hook 'hook-difflib.py' from '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks'...
12964 INFO: Looking for ctypes DLLs
13394 INFO: Analyzing run-time hooks ...
13401 INFO: Including run-time hook '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
13434 INFO: Including run-time hook '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
13452 INFO: Including run-time hook '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
13458 INFO: Including run-time hook '/usr/local/lib/python3.8/dist-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt6.py'
13469 INFO: Looking for dynamic libraries
13504 WARNING: Cannot find libQt6EglFsKmsSupport.so.6 (needed by /usr/local/lib/python3.8/dist-packages/PyQt6/Qt6/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so)
13504 WARNING: Cannot find libQt6EglFSDeviceIntegration.so.6 (needed by /usr/local/lib/python3.8/dist-packages/PyQt6/Qt6/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so)
13539 WARNING: Cannot find libQt6EglFSDeviceIntegration.so.6 (needed by /usr/local/lib/python3.8/dist-packages/PyQt6/Qt6/plugins/egldeviceintegrations/libqeglfs-emu-integration.so)
13569 WARNING: Cannot find libQt6EglFSDeviceIntegration.so.6 (needed by /usr/local/lib/python3.8/dist-packages/PyQt6/Qt6/plugins/egldeviceintegrations/libqeglfs-x11-integration.so)
14282 WARNING: Cannot find libQt6EglFSDeviceIntegration.so.6 (needed by /usr/local/lib/python3.8/dist-packages/PyQt6/Qt6/plugins/platforms/libqeglfs.so)
15180 WARNING: Cannot find libicuuc.so.56 (needed by /usr/local/lib/python3.8/dist-packages/PyQt6/Qt6/plugins/egldeviceintegrations/../../lib/libicui18n.so.56)
15181 WARNING: Cannot find libicudata.so.56 (needed by /usr/local/lib/python3.8/dist-packages/PyQt6/Qt6/plugins/egldeviceintegrations/../../lib/libicui18n.so.56)
15323 WARNING: Cannot find libicudata.so.56 (needed by /usr/local/lib/python3.8/dist-packages/PyQt6/Qt6/plugins/egldeviceintegrations/../../lib/libicuuc.so.56)
17373 INFO: Looking for eggs
17373 INFO: Python library not in binary dependencies. Doing additional searching...
17550 INFO: Using Python library /lib/x86_64-linux-gnu/libpython3.8.so.1.0
17559 INFO: Warnings written to /home/nurul-gc/PycharmProjects/Adivinha-Palavra/build/ap/warn-ap.txt
17610 INFO: Graph cross-reference written to /home/nurul-gc/PycharmProjects/Adivinha-Palavra/build/ap/xref-ap.html
17662 INFO: checking PYZ
17662 INFO: Building PYZ because PYZ-00.toc is non existent
17662 INFO: Building PYZ (ZlibArchive) /home/nurul-gc/PycharmProjects/Adivinha-Palavra/build/ap/PYZ-00.pyz
18325 INFO: Building PYZ (ZlibArchive) /home/nurul-gc/PycharmProjects/Adivinha-Palavra/build/ap/PYZ-00.pyz completed successfully.
18332 INFO: checking PKG
18332 INFO: Building PKG because PKG-00.toc is non existent
18332 INFO: Building PKG (CArchive) PKG-00.pkg
61367 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
61376 INFO: Bootloader /usr/local/lib/python3.8/dist-packages/PyInstaller/bootloader/Linux-64bit-intel/run_d
61377 INFO: checking EXE
61377 INFO: Building EXE because EXE-00.toc is non existent
61377 INFO: Building EXE from EXE-00.toc
61419 INFO: Appending archive to ELF section in EXE /home/nurul-gc/PycharmProjects/Adivinha-Palavra/dist/adivinhapalavra
62442 INFO: Building EXE from EXE-00.toc completed successfully.
```

**Comment by rokm** [comment]
Did you uninstall only `PyQt5` package, or also `PyQt5-sip` and `PyQt5-Qt` / `PyQt5-Qt5`?

This sounds like PyQt5 equivalent of what's described in #6141 (and should be fixed by #6114).

**Comment by rokm** [comment]
> but I still don't understand why needs PyQt5 to freeze a program based on PyQt6!?

It's not really needed, but the `qt` hook utilities [initialize the library info for all four variants (PySide2, PyQt5, PySide6 and PyQt6)](https://github.com/pyinstaller/pyinstaller/blob/a6f41dc99b2647b5bc68fc150599e2d4a697de97/PyInstaller/utils/hooks/qt.py#L150-L154). This usually works well with packages installed or uninstalled; the only problem are partial installations of PyQt5/PyQt6, which cause the reported error that then brings down the import of the whole `qt` hook utils module. But that should be under control now by the two PRs I referenced above.

**Comment by Nurul-GC** [comment]
> Did you uninstall only PyQt5 package, or also PyQt5-sip and PyQt5-Qt / PyQt5-Qt5?

I uninstalled all of them, I thought that with them maybe, some exception could raise and break the execution..

understood now
thanks again!
