### ISSUE TITLE
Pyinstaller does not work with Virtualenv

### ISSUE THREAD

**Issue by apocalypse2012** [pyinstaller/pyinstaller#6221]
## Description of the issue

I am using a virtualenv spawned in pycharm. With this virtualenv activated, I cannot pip install pyinstaller into the project. It installs fine from the system python, but in my virtualenv it gives the following error in verbose:

`Installing collected packages: pyinstaller
ERROR: Could not install packages due to an OSError.
Traceback (most recent call last):
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\commands\install.py", line 390, in run
    installed = install_given_reqs(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\req\req_install.py", line 758, in install
    install_wheel(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 794, in install_wheel
    _install_wheel(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 637, in _install_wheel
    file.save()
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 406, in save
    shutil.copyfileobj(f, dest)
  File "Y:\Users\rstewart\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 205, in copyfileobj
    fdst_write(buf)
OSError: [Errno 22] Invalid argument
Removed build tracker: 'Y:\\Users\\rstewart\\AppData\\Local\\Temp\\pip-req-tracker-2mzn19di'
`

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: Python 3.8.5
* Platform:  Windows 10 Enterprise v.1903 build 18362.900
* How you installed Python:  Windows App Store
* Did you also try this on another platform? Does it work there?
No. Building my application executable is only a requirement for windows users.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(venv) P:\Documents\Depot\autosuspendprocess>pip -v -v -v install pyinstaller
Using pip 21.2.4 from p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: Y:\Users\rstewart\AppData\Local\Temp\pip-ephem-wheel-cache-w6k99aiq
Created temporary directory: Y:\Users\rstewart\AppData\Local\Temp\pip-req-tracker-30df9ys_
Initialized build tracking at Y:\Users\rstewart\AppData\Local\Temp\pip-req-tracker-30df9ys_
Created build tracker: Y:\Users\rstewart\AppData\Local\Temp\pip-req-tracker-30df9ys_
Entered build tracker: Y:\Users\rstewart\AppData\Local\Temp\pip-req-tracker-30df9ys_
Created temporary directory: Y:\Users\rstewart\AppData\Local\Temp\pip-install-ub67d3c1
1 location(s) to search for versions of pyinstaller:
* https://pypi.org/simple/pyinstaller/
Fetching project page and analyzing links: https://pypi.org/simple/pyinstaller/
Getting page https://pypi.org/simple/pyinstaller/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pyinstaller/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pyinstaller/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/ec/a3/dc7bc8c48a873c3156866df709a23078a6dda86db88328df5cf639385527/pyinstaller-2.0.tar.bz2#sha256=ffbfb6e2b9db50b6efbf785b83f315b5daffd56fb85d92fe82969e5d8f4e8425 (from https://pypi.org/simple/pyinstaller/), version: 2.0
  Found link https://files.pythonhosted.org/packages/52/e5/0ce68034f3441bda11538162796dac5a8e5873e8af5d23aaea65e81c7e51/pyinstaller-2.0.zip#sha256=7f944ff131f6488ebad68e8db4a6f53f2d8054c618b6095d7cbba3ca0f733bab (from https://pypi.org/simple/pyinstaller/), version: 2.0
  Found link https://files.pythonhosted.org/packages/c3/a3/d50648bc99a8d5d6c533fc5c1101cc18014d0782e7ddbe9744ad2d56ad49/PyInstaller-2.1.tar.gz#sha256=feff03a3212d984882432ff81c6afcdcf04d8f636fd4beb131b7a027653b3b05 (from https://pypi.org/simple/pyinstaller/), version: 2.1
  Found link https://files.pythonhosted.org/packages/0b/87/4758831a995645873f72c51ec09f8e51db607ed89a336b0afe12702c4329/PyInstaller-2.1.zip#sha256=d73d4a69ffc92827a6fedfeca49415f805f674a599c67f8f6a8571fae19725d9 (from https://pypi.org/simple/pyinstaller/), version: 2.1
  Found link https://files.pythonhosted.org/packages/43/a5/ed7a830f3e8bec1231ed50d9eafe24b6e5873a5a194dfddf272518baf947/PyInstaller-3.0.tar.gz#sha256=8f9f9836ffebe71f9d9ced24001f8b27c0492574ed12a7a97c2c8810fb3fa210 (from https://pypi.org/simple/pyinstaller/), version: 3.0
  Found link https://files.pythonhosted.org/packages/33/e8/3fed48b82122c81f4db22a8be70de0b3482beff154800d65e1131a5600fb/PyInstaller-3.1.zip#sha256=d4eec0f145e712c0f0e8c8fe27ad645480709903222204157e78420e374cae81 (from https://pypi.org/simple/pyinstaller/), version: 3.1
  Found link https://files.pythonhosted.org/packages/51/7f/e2f744ba13d7a27360a43b62d3d9aeff7df1d7fa346f746fc040a0caf9e3/PyInstaller-3.1.1.tar.gz#sha256=b111d35d836237bf954e9b47dcb338da48a40210c318b2b0bc163dba8ca8e096 (from https://pypi.org/simple/pyinstaller/), version: 3.1.1
  Found link https://files.pythonhosted.org/packages/f8/d4/06cbe4304fb25f95ecc02a313792b9fd222d6ca3bfd17722bf4bbfb6f36d/PyInstaller-3.1.1.zip#sha256=7b3d9884cd806b31570950c5d9ad4aaaac1bbe9f374ab3d10e61f9f499642910 (from https://pypi.org/simple/pyinstaller/), version: 3.1.1
  Found link https://files.pythonhosted.org/packages/33/f9/034a89276301ef5e88efd11e5ea592e3d3b2324706e65bdff7445d271077/PyInstaller-3.2.tar.gz#sha256=7598d4c9f5712ba78beb46a857a493b1b93a584ca59944b8e7b6be00bb89cabc (from https://pypi.org/simple/pyinstaller/), version: 3.2
  Found link https://files.pythonhosted.org/packages/d5/ca/f4916fe37d0a372c530c144f6cbd4d5b81f4be0ab709309ab8ea82f3583a/PyInstaller-3.2.zip#sha256=e27ad7e840d49924f375d3ffa4e0d67b9340f4d78c8279378dd5f4a89dbf6318 (from https://pypi.org/simple/pyinstaller/), version: 3.2
  Found link https://files.pythonhosted.org/packages/3f/d2/3515242cc5cfed12706506d17728a7ee0b8cf33840e250357fd793a94607/PyInstaller-3.2.1.tar.bz2#sha256=f08ca806bc26e62034bca181a4b85de22568a3d39bdb062f05927c6e86c2a48c (from https://pypi.org/simple/pyinstaller/), version: 3.2.1
  Found link https://files.pythonhosted.org/packages/cc/c2/5d9a7756419f47ef378add16c7c50c9d7794ae7a39b71b68b00bd7d3ae20/PyInstaller-3.3.tar.gz#sha256=b6c95cdbb45ac78a44723fa2992b58e14637cbefecafc22d3790af262a7fad6f (from https://pypi.org/simple/pyinstaller/), version: 3.3
  Found link https://files.pythonhosted.org/packages/3c/86/909a8c35c5471919b3854c01f43843d9b5aed0e9948b63e560010f7f3429/PyInstaller-3.3.1.tar.gz#sha256=715f81f24b1ef0e5fe3b3c71e7540551838e46e9de30882aa7c0a521147fd1ce (from https://pypi.org/simple/pyinstaller/), version: 3.3.1
  Found link https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz#sha256=a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*), version: 3.4
  Found link https://files.pythonhosted.org/packages/e2/c9/0b44b2ea87ba36395483a672fddd07e6a9cb2b8d3c4a28d7ae76c7e7e1e5/PyInstaller-3.5.tar.gz#sha256=ee7504022d1332a3324250faf2135ea56ac71fdb6309cff8cd235de26b1d0a96 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*), version: 3.5
  Found link https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz#sha256=3730fa80d088f8bb7084d32480eb87cbb4ddb64123363763cf8f2a1378c1c4b7 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*), version: 3.6
  Found link https://files.pythonhosted.org/packages/82/96/21ba3619647bac2b34b4996b2dbbea8e74a703767ce24192899d9153c058/pyinstaller-4.0.tar.gz#sha256=970beb07115761d5e4ec317c1351b712fd90ae7f23994db914c633281f99bab0 (from https://pypi.org/simple/pyinstaller/), version: 4.0
  Found link https://files.pythonhosted.org/packages/9e/ed/fbdad7f5d8f794c901076b814b8e9f5ce31d32c0bc3b63ddd27b61db9530/pyinstaller-4.1.tar.gz#sha256=954ae81de9a4bc096ff02433b3e245b9272fe53f27cac319e71fe7540952bd3d (from https://pypi.org/simple/pyinstaller/), version: 4.1
  Found link https://files.pythonhosted.org/packages/b4/83/9f6ff034650abe9778c9a4f86bcead63f89a62acf02b1b47fc2bfc6bf8dd/pyinstaller-4.2.tar.gz#sha256=f5c0eeb2aa663cce9a5404292c0195011fa500a6501c873a466b2e8cad3c950c (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.5), version: 4.2
  Found link https://files.pythonhosted.org/packages/b6/27/a006fcadba0db30819c968eb8decb4937cda398ca7a44d8874172cdc228a/pyinstaller-4.3.tar.gz#sha256=5ecf8bbc230d7298a796e52bb745b95eee12878d141f1645612c99246ecd23f2 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6), version: 4.3
  Skipping link: none of the wheel's tags (py3-none-macosx_10_13_universal2) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/4e/c5/92f5346f5a09e4df3e8087b06f3586f889b1f9711a69a82307d4e733b0f0/pyinstaller-4.4-py3-none-macosx_10_13_universal2.whl#sha256=0e802c082487719aab6b2a93575819944c008e6e1ba44c7836fc45660a9586c0 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/b8/a3/a1c3ae0462e5b8e9825acb4769c994d415d32ec481c192ca335751f1d3c9/pyinstaller-4.4-py3-none-manylinux2014_aarch64.whl#sha256=2ef691eeb360073075b6c355535a15dcdedac28d2ecc8448d34bce671ec2dff4 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_i686) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/90/7d/4c8358a73c7869946baadd3108ff3676bb84c915fcaa060bc6c79d2a7a50/pyinstaller-4.4-py3-none-manylinux2014_i686.whl#sha256=2cfef29a878fc54040e2287c19ea4bdc667f473b59918fcb51a1e68366ecb814 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/dd/e4/93166ad003c36345c049054b5b99f12402c87b105dbfa3c498f914bc0121/pyinstaller-4.4-py3-none-manylinux2014_x86_64.whl#sha256=b0f13d0a33b9a21659967db65b475c14645b456dc70ba68fa9cebf4bc29ef58e (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Found link https://files.pythonhosted.org/packages/22/b0/8c5f3b9e6cdc317e5f688a87c7a089c8cd3317fb6a4e38012bdcdc647b4a/pyinstaller-4.4-py3-none-win32.whl#sha256=d0b35f885650b9dc69072adf948b608bcb506c5256dd7f0d0967c1f177bb41b1 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6), version: 4.4
  Skipping link: none of the wheel's tags (py3-none-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/64/ef/059a2a7aaa60483685bf501d0aa8d9f7d5aba1cda21bf2d87b2732fd5407/pyinstaller-4.4-py3-none-win_amd64.whl#sha256=4485046ca929e15f6a2db746ce183c14e1fc3c1e8d2102aad8f1403b25d9ebdf (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Found link https://files.pythonhosted.org/packages/56/68/fcf288abb7985d17c4d5802aa76cbc6e00cd85d084230338cf4ef8696a38/pyinstaller-4.4.tar.gz#sha256=af3ef0b9f265a2d3859357a25ab16743fbb6143c89fd7c3570cb84b8d24db0ba (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6), version: 4.4
  Skipping link: none of the wheel's tags (py3-none-macosx_10_13_universal2) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/91/86/35230422461031e91eb2a5c059fa61c2cb1fd072030d648506dc32bb9df7/pyinstaller-4.5-py3-none-macosx_10_13_universal2.whl#sha256=0129e5ea77c5eb6b2e0de8b1f7ec006238991ac712e3c0e877b995a289e4d8ea (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_i686) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/69/01/3948e7f3a32c66449cd525de13db2ba1889906ea0d323aefc54d43ed5ecb/pyinstaller-4.5-py3-none-manylinux2014_i686.whl#sha256=3228e1c7d823c5e786ee41194171e19fc985c4d6074610e4876479697a97b60f (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/6e/3f/b48b86fbfbf07e09e0c33a6e48aee2660febebc01f0d82a4953af2d3a8ac/pyinstaller-4.5-py3-none-manylinux2014_x86_64.whl#sha256=8b22656d2eaf5141c20afa3b98422cce17bf05ff9ef4fa8b232b47853b18e4b9 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Found link https://files.pythonhosted.org/packages/e5/3c/d905a6c2cdc366738847d81ecdfca71aa1e2e03d21d6b485d881cfd24ffc/pyinstaller-4.5-py3-none-win32.whl#sha256=9d78452652a27a20a7126fdb93fe7abe731b82dc2a6c163a67fd98bd2a9c44f5 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6), version: 4.5
  Skipping link: none of the wheel's tags (py3-none-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/0f/19/73dd9833a972777b8304667752167fb4ec7803b8d0252bcc14d606bd1585/pyinstaller-4.5-py3-none-win_amd64.whl#sha256=df294f6579443924774e7c987deccca47a5f6386137972c8f3f31983db37a43e (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Found link https://files.pythonhosted.org/packages/cc/d7/dad3efb75106db94b47545efaf32a98498d0565512af9b531e3584cab8a4/pyinstaller-4.5.tar.gz#sha256=86f694faec78a08c3893aacef84b1a49cb53d4e2880559c6124beefd196a3a74 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6), version: 4.5
  Skipping link: none of the wheel's tags (py3-none-macosx_10_13_universal2) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/ba/d5/331cbbee7aa8f3b62051d8be714e2e8c208536abfe558e61e9c4b09a6ae4/pyinstaller-4.5.1-py3-none-macosx_10_13_universal2.whl#sha256=ecc2baadeeefd2b6fbf39d13c65d4aa603afdda1c6aaaebc4577ba72893fee9e (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/28/0d/89e847020fe6514dec7d18d1ca78d9b9cbbabfa17f1d38b8122bc9be8d14/pyinstaller-4.5.1-py3-none-manylinux2014_aarch64.whl#sha256=4d848cd782ee0893d7ad9fe2bfe535206a79f0b6760cecc5f2add831258b9322 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_i686) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/e8/60/cbfcd60f99c8814bb314910953b4cd56c4bf3a5d8099516066cd839443e8/pyinstaller-4.5.1-py3-none-manylinux2014_i686.whl#sha256=8f747b190e6ad30e2d2fd5da9a64636f61aac8c038c0b7f685efa92c782ea14f (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/36/eb/e30b66fd38d80a4d45f2dbfea3f0985002c66aa08b855b61f08bce50891c/pyinstaller-4.5.1-py3-none-manylinux2014_x86_64.whl#sha256=c587da8f521a7ce1b9efb4e3d0117cd63c92dc6cedff24590aeef89372f53012 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Found link https://files.pythonhosted.org/packages/79/ba/fbd0f192e1d711bf391e44a42875fc3ecffaf4529d7d7d9604fc79027327/pyinstaller-4.5.1-py3-none-win32.whl#sha256=fed9f5e4802769a416a8f2ca171c6be961d1861cc05a0b71d20dfe05423137e9 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6), version: 4.5.1
  Skipping link: none of the wheel's tags (py3-none-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/12/a9/91a182d5b2541d8b89396f4371151e412246f8e8d6e65954871548a2a14b/pyinstaller-4.5.1-py3-none-win_amd64.whl#sha256=aae456205c68355f9597411090576bb31b614e53976b4c102d072bbe5db8392a (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6)
  Found link https://files.pythonhosted.org/packages/a9/d9/9fdfb0ac2354d059e466d562689dbe53a23c4062019da2057f0eaed635e0/pyinstaller-4.5.1.tar.gz#sha256=30733baaf8971902286a0ddf77e5499ac5f7bf8e7c39163e83d4f8c696ef265e (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6), version: 4.5.1
Skipping link: not a file: https://pypi.org/simple/pyinstaller/
Given no hashes to check 26 links for project 'pyinstaller': discarding no candidates
Collecting pyinstaller
  Created temporary directory: Y:\Users\rstewart\AppData\Local\Temp\pip-unpack-rh2n39yr
  Looking up "https://files.pythonhosted.org/packages/79/ba/fbd0f192e1d711bf391e44a42875fc3ecffaf4529d7d7d9604fc79027327/pyinstaller-4.5.1-py3-none-win32.whl" in the cache
  Current age based on date: 1829817
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 1829817
  Using cached pyinstaller-4.5.1-py3-none-win32.whl (1.9 MB)
  Added pyinstaller from https://files.pythonhosted.org/packages/79/ba/fbd0f192e1d711bf391e44a42875fc3ecffaf4529d7d7d9604fc79027327/pyinstaller-4.5.1-py3-none-win32.whl#sha256=fed9f5e4802769a416a8f2ca171c6be961d1861cc05a0b71d20dfe05423137e9 to build tracker 'Y:\\Users\\rstewart\\AppData\\Local\\Temp\\pip-req-tracker-30df9ys_'
  Removed pyinstaller from https://files.pythonhosted.org/packages/79/ba/fbd0f192e1d711bf391e44a42875fc3ecffaf4529d7d7d9604fc79027327/pyinstaller-4.5.1-py3-none-win32.whl#sha256=fed9f5e4802769a416a8f2ca171c6be961d1861cc05a0b71d20dfe05423137e9 from build tracker 'Y:\\Users\\rstewart\\AppData\\Local\\Temp\\pip-req-tracker-30df9ys_'
Requirement already satisfied: setuptools in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (57.1.0)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (0.2.0)
Requirement already satisfied: pefile>=2017.8.1 in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (2021.5.24)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (2021.3)
Requirement already satisfied: altgraph in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pyinstaller) (0.17)
Requirement already satisfied: future in p:\documents\depot\autosuspendprocess\venv\lib\site-packages (from pefile>=2017.8.1->pyinstaller) (0.18.2)
Created temporary directory: Y:\Users\rstewart\AppData\Local\Temp\pip-unpack-e9w714bc
Installing collected packages: pyinstaller
ERROR: Could not install packages due to an OSError.
Traceback (most recent call last):
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\commands\install.py", line 390, in run
    installed = install_given_reqs(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\req\req_install.py", line 758, in install
    install_wheel(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 794, in install_wheel
    _install_wheel(
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 637, in _install_wheel
    file.save()
  File "p:\documents\depot\autosuspendprocess\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 406, in save
    shutil.copyfileobj(f, dest)
  File "Y:\Users\rstewart\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 205, in copyfileobj
    fdst_write(buf)
OSError: [Errno 22] Invalid argument
Removed build tracker: 'Y:\\Users\\rstewart\\AppData\\Local\\Temp\\pip-req-tracker-30df9ys_'

```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Have you ruled out locally running anti-virus program (if any)?

What kind of drive/partition is `Y:\`? (i.e., is it a network share with host-running anti-virus program, by any chance?)

**Comment by apocalypse2012** [comment]
There is no locally running anti-virus. Defender is disabled by policy and our anti-virus is cloud based? New one on me.
The system environment is VM based running on an OnPrem cloud infrastructure. The Y drive is a network drive that hosts user profiles wholly. 
If this were a problem, does it make sense to only effect virtual environments? The Y: drive paths are the same whether I am installing successfully to the system Python, or unsuccessfully to the virtual environment.

**Comment by rokm** [comment]
> If this were a problem, does it make sense to only effect virtual environments?

I don't know; I have no idea about the details of your setup and the policies that are in the play. (It is clearly not a "standard" setup, though...).

Can you try setting TEMP to some other, local, location before running `pip`, to see if it makes any difference?

Although on the other hand, it could be that the drive `Y:\` is alright, and that pip is getting an error when trying to copy files to the venv on drive `P:\`... In this case, can you try creating the venv on a local drive and see if that works?

> How you installed Python: Windows App Store
> File "Y:\Users\rstewart\AppData\Local\Programs\Python\Python38-32\lib\shutil.py"

Is your "system" python where installation worked the one from the Windows App Store, or the one in `Y:\Users\rstewart\AppData\Local\Programs\Python\Python38-32`? This location looks like the one that python.org installers use...

**Comment by apocalypse2012** [comment]
Honestly, I don’t remember if I installed it from the store or not. I can tell you that the store does detect that Python is installed. So it might be reasonable to assume that it is listed in the store apps internal manifest.
I will try to put a git clone of my project on the local C: drive on Monday. I am not sure if this will work as their and no user profile specific artifacts on the local drive, so I may not be able to create local folders. However, IT admin has given me local admin privileges so it’s worth a try.
I wish I could stay in Linux, but it’s a requirement to get this project packaged for windows users that has me needing this in the first place. (SMH) thanks for the help.

**Comment by apocalypse2012** [comment]
Recloned my project from the local C:. After full configuration pyinstaller worked as designed. I'm closing this now as the problem is clearly an artifact of my cloud environment and unrelated to pyinstaller... Thanks for all the help...
