### ISSUE TITLE
Pyinstaller run is failing in __init__.py with imports defined in __all__

### ISSUE THREAD

**Issue by apocalypse2012** [pyinstaller/pyinstaller#6228]
## Description of the issue

The title explains it all. I have a module library with a package definition file that defines a list of imports in the __all__ variable and then imports that list as follows...

__all__ = ["strategy_conn_pgsql", "strategy_conn_mssql"]
from connection import *

Pyinstaller compiles fine but dies on execution of the exe with the following error...

`Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "ViewController.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "BuildingTokenQuery.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "connection\__init__.py", line 2, in <module>
AttributeError: partially initialized module 'connection' has no attribute 'strategy_conn_pgsql' (most likely due to a circular import)
`

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "ViewController.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "BuildingTokenQuery.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "connection\__init__.py", line 2, in <module>
AttributeError: partially initialized module 'connection' has no attribute 'strategy_conn_pgsql' (most likely due to a circular import)

```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
You're going to have to provide minimum example that exhibits the problem, I'm afraid.

Based on your description, you have something like this:

```python
# program.py
from connection import *

print('strategy_conn_pgsql:', strategy_conn_pgsql)
print('strategy_conn_mssql:', strategy_conn_mssql)
```

```python
# connection/__init__.py
__all__ = ["strategy_conn_pgsql", "strategy_conn_mssql"]

strategy_conn_pgsql = 'str1'
strategy_conn_mssql = 'str2'
```

And this example works as expected.

So I guess the question is:
* does your code start working if you avoid doing `import *` (but just import the `connection` package, or those two objects from it)?
* where do `strategy_conn_pgsql` and `strategy_conn_mssql` in `connection/__init__.py` come from? Are they defined in there, or are they imported from somewhere else?

**Comment by rokm** [comment]
Or are the two lines you provided,

```python
__all__ = ["strategy_conn_pgsql", "strategy_conn_mssql"]
from connection import *
```

actually the first two lines of `connection/__init__.py`? 

That doesn't work in unfrozen python script either, unless you define `strategy_conn_pgsql` and `strategy_conn_mssql` before doing `from connection import *`...

**Comment by apocalypse2012** [comment]
This line...
__all__ = ["strategy_conn_pgsql", "strategy_conn_mssql"]
defines the meaning of '*' in this line...
from connection import *

This works because both modules are in the connection package definition. This purpose of this is to exclude additional modules in the package from the import. This is all pretty standard stuff.

However, to follow up... The/A solution is to call pyinstaller with --hidden-import for each module with the full package namespace path...
--hidden-import=connection.strategy_conn_pgsql
This allowed both of these imports to pass without error. I will now close this as fixed. Thanks.
