### ISSUE TITLE
Import Error When Running Hook

### ISSUE THREAD

**Issue by tokaisuDev** [pyinstaller/pyinstaller#6283]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.51```
* Version of Python: 3.8.10
* Platform: Windows 7
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
Running auto-py-to-exe v2.10.1
Building directory: C:\Users\ADMINI~1\AppData\Local\Temp\tmpbulaq9j9
Provided command: pyinstaller --noconfirm --onefile --windowed  "V:\Coding Files Library\Python\Tutorial\Convert from video to audio (designed for exe)\converter.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --windowed V:\Coding Files Library\Python\Tutorial\Convert from video to audio (designed for exe)\converter.py --distpath C:\Users\ADMINI~1\AppData\Local\Temp\tmpbulaq9j9\application --workpath C:\Users\ADMINI~1\AppData\Local\Temp\tmpbulaq9j9\build --specpath C:\Users\ADMINI~1\AppData\Local\Temp\tmpbulaq9j9

33040 INFO: PyInstaller: 4.5.1
33046 INFO: Python: 3.8.10
33058 INFO: Platform: Windows-7-6.1.7601-SP1
33066 INFO: wrote C:\Users\ADMINI~1\AppData\Local\Temp\tmpbulaq9j9\converter.spec
33073 INFO: UPX is not available.
33083 INFO: Extending PYTHONPATH with paths
['V:\\Coding Files Library\\Python\\Tutorial\\Convert from video to audio '
 '(designed for exe)',
 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpbulaq9j9']
33934 INFO: checking Analysis
33940 INFO: Building Analysis because Analysis-00.toc is non existent
33949 INFO: Initializing module dependency graph...
33958 INFO: Caching module graph hooks...
33989 INFO: Analyzing base_library.zip ...
38667 INFO: Processing pre-find module path hook distutils from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
38671 INFO: distutils: retargeting to non-venv dir 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib'
46796 INFO: Caching module dependency graph...
47212 INFO: running Analysis Analysis-00.toc
47251 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\administrator\appdata\local\programs\python\python38\python.exe
47591 INFO: Analyzing V:\Coding Files Library\Python\Tutorial\Convert from video to audio (designed for exe)\converter.py
62314 INFO: Processing pre-find module path hook site from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
62350 INFO: site: retargeting to fake-dir 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\fake-modules'
131118 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
142796 INFO: Processing pre-safe import module hook six.moves from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
197177 INFO: Processing pre-safe import module hook win32com from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
206724 INFO: Processing module hooks...
206753 INFO: Loading module hook 'hook-argon2.py' from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
206765 INFO: Loading module hook 'hook-botocore.py' from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
212393 INFO: Loading module hook 'hook-certifi.py' from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
212458 INFO: Loading module hook 'hook-clr.py' from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
An error occurred while packaging
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 408, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\compat.py", line 632, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1027, in load_module
  File "<frozen importlib._bootstrap_external>", line 852, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py", line 30, in <module>
    filepaths = [f for f in files('pythonnet') if 'Python.Runtime.dll' in str(f)]
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\metadata.py", line 555, in files
    return distribution(distribution_name).files
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pythonnet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmpbulaq9j9\converter.spec", line 7, in <module>
    a = Analysis(['V:\\Coding Files Library\\Python\\Tutorial\\Convert from video to audio (designed for exe)\\converter.py'],
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 294, in __init__
    self.__postinit__()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 159, in __postinit__
    self.assemble()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 473, in assemble
    self.graph.process_post_graph_hooks(self)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 373, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 451, in post_graph
    self._load_hook_module()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 412, in _load_hook_module
    raise ImportErrorWhenRunningHook(
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_clr required by hook for module c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py. Please check whether module __PyInstaller_hooks_0_clr actually exists and whether the hook is compatible with your version of c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.

Project output will not be moved to output folder
Complete.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Does your program make use of the `clr` module from the `pythonnet` package? 

Or, do you have your own module called `clr` that your program is using (which is triggering the `pythonnet` hook)?

**Comment by tokaisuDev** [comment]
No, I'm doesn't have any of those

**Comment by rokm** [comment]
Well, something is triggering the `hook-clr.py`; if you are not using `pythonnet`, you can temporarily (re)move or rename the file `c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py`.

**Comment by tokaisuDev** [comment]
Thanks, it worked. I very thankful for your help!

**Comment by ughstudios** [comment]
This error still exists. Was this ever fixed in more detail?

**Comment by rokm** [comment]
> This error still exists. Was this ever fixed in more detail?

No, because based on the provided information, we could not figure out what the underlying cause was. So if you're getting that error, is your code using the `pythonnet` package and its `clr` module? If not, is it using [this clr](https://pypi.org/project/clr/) package? Is there another top-level module or package named `clr` in your `sys.path` that your code (or one of its imports) is using? Or perhaps being placed next to you entry-point script?

I guess the proper fix would be to check for the presence of the `pythonnet` package in the `clr` hook, in case the module is not referring to `pythonnet`'s `clr` but some other module/package with the same name...
