### ISSUE TITLE
Detect usages of torch.jit and collect its required source files automatically

### ISSUE THREAD

**Issue by RaminNateghi** [pyinstaller/pyinstaller#6290]
I am trying to create an executable. My code test.py works well when running with python, but the generated executable file fails with OsError error. I tried to add some hiddenimports and data to the spec file, but I am still getting the same error.

![image](https://user-images.githubusercontent.com/65801650/136775477-ee1dfe04-a0dc-4f5c-a329-528895fc0a79.png)

You can find my test.py and test.spec files here.

**test.py**
```
from lungmask import mask
import SimpleITK as sitk
import nibabel as nib
import glob
import shutil
from ttictoc import tic,toc
import os
import torch.multiprocessing as mp
import sys
import cv2
import numpy as np
import albumentations as albu
import torch
import segmentation_models_pytorch as smp
import efficientnet_pytorch


if __name__ == '__main__':
    print('hello world')
```
_________________________________________________________________________________________________________________________

**test.spec**

```
# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path
import torch
import inspect
import efficientnet_pytorch
from os import path

block_cipher = None

#Excluded_modules = ['Torch.Distributions'] # Add this line
site_packages='C:\\Users\\pc\\Anaconda3\\envs\\pytorch-3.7\\Lib\\site-packages'

def collect_source_files(modules):
    datas = []
    for module in modules:
        source = inspect.getsourcefile(module)
        dest = f"src.{module.__name__}"  # use "src." prefix
        datas.append((source, dest))
    return datas

a = Analysis(['test.py'],
             pathex=['E:\\COVID-19\\New folder'],
             binaries=[('C:\\Users\\pc\\Anaconda3\\envs\\pytorch-3.7\\Lib\\site-packages\\torch\\lib\\caffe2_nvrtc.dll','.')],
             datas=[(path.join(site_packages,"torch"), "torch"),
                    (path.join(site_packages,"torchvision"), "torchvision"),
                    (path.join(site_packages,"efficientnet_pytorch"), "efficientnet_pytorch")],
             hiddenimports=['pydicom', 'pydicom.encoders', 'pydicom.encoders.gdcm', 'pydicom.encoders.pylibjpeg', 'fill_voids', 'fastremap', 'nibabel', 'nibabel.nifti1','torch','av', 'fvcore','torchvision', 'detectron2','efficientnet_pytorch','segmentation_models_pytorch'],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes= [],  #Excluded_modules
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
             
             
             
MISSING_LIBS = (
Path(r'C:\Windows\System32\nvcuda.dll'),
)

a.binaries += TOC([(lib.name, str(lib.resolve()),'BINARY') for lib in MISSING_LIBS])

MISSING_LIBS = (
Path(r'C:\Users\pc\Anaconda3\envs\pytorch-3.7\Library\bin\nvrtc64_101_0.dll'),
)

a.binaries += TOC([(lib.name, str(lib.resolve()),'BINARY') for lib in MISSING_LIBS])

source_files = collect_source_files([torch])  # return same structure as `collect_data_files()`
source_files_toc = TOC((name, path, 'DATA') for path, name in source_files)

pyz = PYZ(a.pure, a.zipped_data, source_files_toc,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts, 
          [],
          exclude_binaries=True,
          name='test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               upx=True,
               upx_exclude=[],
               name='test')
```

**Comment by rokm** [comment]
If you use a package that makes use of `torch`'s JIT, you need to collect the sources of that package, too. In this case, those of `timm` package.

**Comment by rokm** [comment]
Also, I suspect this snippet:





> ```
> def collect_source_files(modules):
>     datas = []
>     for module in modules:
>         source = inspect.getsourcefile(module)
>         dest = f"src.{module.__name__}"  # use "src." prefix
>         datas.append((source, dest))
>     return datas
> ```

came from #4764, but this doesn't work unless you also patch the PyInstaller's loader to read those `src.`-prefixed files.

But since then, we've added support for loading collected .py files directly, so you just need to ensure that they are collected, for example via:

```
datas = collect_data_files('timm', include_py_files=True)
```

**Comment by bwoodsend** [comment]
> If you use a package that makes use of `torch`'s JIT, you need to collect the sources of that package, too. In this case, those of `timm` package.

I suppose a permanent fix to `torch.jit` is to do another `PyInstaller.depend.bytecode` analysis to detect usages of `torch.jit` decorators and collect source files for them implicitly...

**Comment by rokm** [comment]
> > If you use a package that makes use of `torch`'s JIT, you need to collect the sources of that package, too. In this case, those of `timm` package.
> 
> I suppose a permanent fix to `torch.jit` is to do another `PyInstaller.depend.bytecode` analysis to detect usages of `torch.jit` decorators and collect source files for them implicitly...

Yeah, that's how we could (try to) handle this automatically. Alternative would be to have hooks for all such packages, which might be feasible for packages that require some other functionality provided by hooks (e.g., metadata or data files collection)...

**Comment by RaminNateghi** [comment]
@bwoodsend, how can I do PyInstaller.depend.bytecode analysis? and how to collect sources automatically?

**Comment by bwoodsend** [comment]
You can't yet. I was thinking we (PyInstaller devs) could set it up in the future so that users don't have to worry about torch's jit. In the mean time, [do it manually like Rok suggested](https://github.com/pyinstaller/pyinstaller/issues/6290#issuecomment-940099473).

**Comment by RaminNateghi** [comment]
@rokm, this is the updated **spec**. I am still getting the same error.
[test.spec.txt](https://github.com/pyinstaller/pyinstaller/files/7325301/test.spec.txt)

Here is also the output **debug log**.
[out.txt](https://github.com/pyinstaller/pyinstaller/files/7325305/out.txt)

**Comment by rokm** [comment]
Is it 100% identical error as the one you've originally reported, or a slight variation thereof?

**Comment by RaminNateghi** [comment]
It's 100% identical error that I am getting. You can regenerate it by running **test.py** and **test.spec** which I mentioned earlier.

**Comment by rokm** [comment]
> It's 100% identical error that I am getting. You can regenerate it by running **test.py** and **test.spec** which I mentioned earlier.

Well yeah, but the example you provided is far from minimal in terms of packages it pulls in. The error you initially reported can be reproduced by:

```python
# program.py
# pip install timm (-> numpy-1.21.2 pillow-8.3.2 timm-0.4.12 torch-1.9.1 torchvision-0.10.1)
import timm.models.byoanet
print("Hello")
```
and a clean onedir spec:
<details><summary>Spec file</summary>
<p>

```python
# program.spec
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['program.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='program',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='program',
)
```
</p></details>

Building the spec using PyInstaller `develop` and running the program results in the error:
<details><summary>Lengthy traceback</summary>
<p>

```
> dist\program\program.exe
Traceback (most recent call last):
  File "torch\_utils_internal.py", line 55, in get_source_lines_and_file
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "program.py", line 1, in <module>
    import timm.models.byoanet
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\byoanet.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\byobnet.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\helpers.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\layers\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\layers\conv_bn_act.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\layers\create_norm_act.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\layers\norm_act.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\layers\create_act.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "timm\models\layers\activations_jit.py", line 19, in <module>
  File "torch\jit\_script.py", line 1140, in script
  File "torch\jit\frontend.py", line 269, in get_jit_def
  File "torch\_utils_internal.py", line 62, in get_source_lines_and_file
OSError: Can't get source for <function swish_jit at 0x0000023F78488B88>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
[5348] Failed to execute script 'program' due to unhandled exception!
```

</p></details>

That's because `swish_jit` function in `timm\models\layers\activations_jit.py` is annotated as `@torch.jit.script`, therefore this source file needs to be collected.

Therefor, collecting all source files:
<details><summary>Modified spec file</summary>
<p>

```python
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

datas  = []
datas += collect_data_files('timm', include_py_files=True)

a = Analysis(
    ['program.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='program',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='program',
)

```
</p></details>

and rebuilding the program fixes this particular problem:

```
> dist\program\program.exe
Hello
```

-----

So if you are still getting the exactly same error as you originally reported, try checking if the `activations_jit.py` source file was collected into `dist\test\timm\models\layers\activations_jit.py`. If not, try performing a clean build (use `--clean` or manually remove `build` and `dist` folders before rebuilding).

**Comment by RaminNateghi** [comment]
You explained well. It actually resolved with pyinstaller==4.5.1.
thanks

**Comment by JefferyChiang** [comment]
Thanks
This solution still work for pyinstaller==4.5.1. and timm==0.5.4.

**Comment by adam-kosinski** [comment]
Thank you so much, this worked for me using pyinstaller==5.13.0 and timm==0.6.12

**Comment by jamesdbrock** [comment]
Adding these lines to the `.spec` file worked for me for PyInstaller v6.2.0.

```
datas += collect_data_files('timm', include_py_files=True)
datas += collect_data_files('torchvision', include_py_files=True)
```

**Comment by raghotham007** [comment]
> Adding these lines to the `.spec` file worked for me for PyInstaller v6.2.0.
> 
> ```
> datas += collect_data_files('timm', include_py_files=True)
> datas += collect_data_files('torchvision', include_py_files=True)
> ```

The above method worked collect_data_files thank you for timm.models.** issues

I also added this in main file

```
def script_method(fn, _rcb=None):
    return fn
def script(obj, optimize=True, _frames_up=0, _rcb=None):
    return obj    
import torch.jit
torch.jit.script_method = script_method 
torch.jit.script = script
```
