### ISSUE TITLE
Unknown error, while compiling app.

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#6319]
When i running next command in Powershell.
`pyinstaller -F --noconsole --icon="icon.ico" console_quest_constructor.py`

I getting next error.
`54 INFO: PyInstaller: 4.5.1
54 INFO: Python: 3.9.7
63 INFO: Platform: Windows-10-10.0.19042-SP0
64 INFO: wrote C:\Users\IonE\OneDrive\Рабочий стол\ConsoleQuestEngine\console_quest_constructor.spec
66 INFO: UPX is not available.
67 INFO: Extending PYTHONPATH with paths
['C:\\Users\\IonE\\OneDrive\\Рабочий стол\\ConsoleQuestEngine',
 'C:\\Users\\IonE\\OneDrive\\Рабочий стол\\ConsoleQuestEngine']
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "D:\Python\lib\site-packages\pkg_resources\__init__.py", line 23, in <module>
    import zipfile
  File "D:\Python\lib\zipfile.py", line 7, in <module>
    import importlib.util
  File "D:\Python\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "D:\Python\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "D:\Python\lib\site-packages\typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "D:\Python\lib\site-packages\typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
117 INFO: checking Analysis
118 INFO: Building Analysis because Analysis-00.toc is non existent
118 INFO: Initializing module dependency graph...
120 INFO: Caching module graph hooks...
124 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "D:\Python\lib\pkgutil.py", line 6, in <module>
    import importlib.util
  File "D:\Python\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "D:\Python\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "D:\Python\lib\site-packages\typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "D:\Python\lib\site-packages\typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "D:\Python\lib\pkgutil.py", line 6, in <module>
    import importlib.util
  File "D:\Python\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "D:\Python\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "D:\Python\lib\site-packages\typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "D:\Python\lib\site-packages\typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
1960 INFO: Processing pre-find module path hook distutils from 'D:\\Python\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
1961 INFO: distutils: retargeting to non-venv dir 'D:\\Python\\lib'
4085 INFO: Caching module dependency graph...
4164 INFO: running Analysis Analysis-00.toc
4177 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by D:\Python\python.exe
4217 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of D:\Python\python39.dll
4235 INFO: Analyzing C:\Users\IonE\OneDrive\Рабочий стол\ConsoleQuestEngine\console_quest_constructor.py
4393 INFO: Processing pre-find module path hook PyQt5.uic.port_v2 from 'D:\\Python\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-PyQt5.uic.port_v2.py'.
4751 INFO: Processing pre-find module path hook site from 'D:\\Python\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
4751 INFO: site: retargeting to fake-dir 'D:\\Python\\lib\\site-packages\\PyInstaller\\fake-modules'
13195 INFO: Processing pre-safe import module hook six.moves from 'D:\\Python\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "D:\Python\lib\site-packages\six.py", line 75, in <module>
    from importlib.util import spec_from_loader
  File "D:\Python\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "D:\Python\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "D:\Python\lib\site-packages\typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "D:\Python\lib\site-packages\typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
pre-safe-import-module hook failed, needs fixing.`

I installed pyinstaller via this command.
`pip install pyinstaller`

Python version is.
3.9

What to do?

**Comment by rokm** [comment]
Try removing the obsolete `typing` package.

**Comment by ghost** [comment]
@rokm, thank you!
