### ISSUE TITLE
Pyinstaller not working on 4.5.1

### ISSUE THREAD

**Issue by nikeedev** [pyinstaller/pyinstaller#6321]
## Description of the issue
Error with pyinstaller....?(what do i know???!!?)

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: 3.10.0
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there:  ***nope***

* try the latest development version: That works!

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
C:\Users\nikgon07\OneDrive - Tysvær kommune\Desktop\Script>pyinstaller $o$.py
131 INFO: PyInstaller: 4.5.1
131 INFO: Python: 3.10.0
138 INFO: Platform: Windows-10-10.0.19042-SP0
153 INFO: wrote C:\Users\nikgon07\OneDrive - Tysvær kommune\Desktop\Script\$o$.spec
153 INFO: UPX is not available.
169 INFO: Extending PYTHONPATH with paths
['C:\\Users\\nikgon07\\OneDrive - Tysvær kommune\\Desktop\\Script',
 'C:\\Users\\nikgon07\\OneDrive - Tysvær kommune\\Desktop\\Script']
701 INFO: checking Analysis
701 INFO: Building Analysis because Analysis-00.toc is non existent
701 INFO: Initializing module dependency graph...
717 INFO: Caching module graph hooks...
739 INFO: Analyzing base_library.zip ...
9064 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\nikgon07\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
9064 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\nikgon07\\AppData\\Local\\Programs\\Python\\Python310\\lib'
Traceback (most recent call last):
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "C:\Users\nikgon07\OneDrive - Tysvær kommune\Desktop\Script\$o$.spec", line 7, in <module>
    a = Analysis(['$o$.py'],
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 294, in __init__
    self.__postinit__()
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 159, in __postinit__
    self.assemble()
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 394, in assemble
    self.graph = initialize_modgraph(
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 882, in initialize_modgraph
    graph = PyiModuleGraph(
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 122, in __init__
    self._analyze_base_modules()
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 289, in _analyze_base_modules
    self._base_modules = [mod
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 291, in <listcomp>
    for mod in self.import_hook(req)]
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "C:\Users\nikgon07\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1711, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by nikeedev** [comment]
It works using Dev version but i want to work with stable one(4.5.1)....:(

**Comment by bwoodsend** [comment]
4.5.1 didn't support Python 3.10. The development branch does. Either wait for the next release  of PyInstaller, use the development branch or downgrade to Python 3.9.

**Comment by nikeedev** [comment]
> 4.5.1 didn't support Python 3.10. The development branch does. Either wait for the next release  of PyInstaller, use the development branch or downgrade to Python 3.9.  

Okay
