### ISSUE TITLE
Could not find a suitable TLS CA certificate bundle, invalid path

### ISSUE THREAD

**Issue by NeilRiver** [pyinstaller/pyinstaller#6352]
pyinstaller 4.6

Python 3.9.0 

Windows 10 from torrent 

**everything would be fine, but the certificate is not in the root, but in the certifi folder, why is your installer trying to find the certificate in the root?**

**I had to extract the certificate from the folder and put it in the root**

```
C:\Users\WDAGUtilityAccount\Desktop\213\dist\main>main.exe
Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "gspread\client.py", line 122, in open
  File "gspread\client.py", line 99, in list_spreadsheet_files
  File "gspread\client.py", line 64, in request
  File "requests\sessions.py", line 555, in get
  File "google\auth\transport\requests.py", line 476, in request
  File "google\auth\credentials.py", line 133, in before_request
  File "google\oauth2\service_account.py", line 410, in refresh
  File "google\oauth2\_client.py", line 193, in jwt_grant
  File "google\oauth2\_client.py", line 161, in _token_endpoint_request
  File "google\oauth2\_client.py", line 115, in _token_endpoint_request_no_throw
  File "google\auth\transport\requests.py", line 183, in __call__
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 416, in send
  File "requests\adapters.py", line 227, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\WDAGUtilityAccount\Desktop\213\dist\main\cacert.pem
[6704] Failed to execute script 'main' due to unhandled exception!
```

**Comment by rokm** [comment]
Do the following two applications display correct `cacert.pem` path (i.e., in `certifi` subdirectory) when frozen with PyInstaller, or do they also search in top-level directory?

```python
# app1.py
import certifi
print(certifi.where())
```

```python
# app2.py
import requests
print(requests.utils.DEFAULT_CA_BUNDLE_PATH)
```

**Comment by NeilRiver** [comment]
gg wp, i shall delete python and reinstal again

1) C:\Users\WDAGUtilityAccount\Desktop\213\dist\main\cacert.pem

2) C:\Users\WDAGUtilityAccount\Desktop\213\dist\main\cacert.pem

**Comment by bwoodsend** [comment]
> gg wp, i shall delete python and reinstal again

No. That is never the answer.

**Comment by rokm** [comment]
Are you using a patched/modified version of `certifi`? The original `certifi.where()` implementation should look like [this](https://github.com/certifi/python-certifi/blob/ff23c47fe88b21efa8099d9f957f91bcd4089fbd/certifi/core.py#L19-L41). I.e., it should be using `importlib.resources.path("certifi", "cacert.pem")`, and should therefore end up looking in `certifi` sub-directory, not the top-level directory...

**Comment by rokm** [comment]
What about this frozen application:
```python
import importlib.resources
import certifi # hiddenimport

with importlib.resources.path("certifi", "cacert.pem") as ca_path:
    print(ca_path)
```
