### ISSUE TITLE
`try/except` works in pycharm but doesn't work in exe after compiling using pyinstaller

### ISSUE THREAD

**Issue by xie186** [pyinstaller/pyinstaller#6409]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.7```
* Version of Python: Python 3.7.8
* Platform: Windows 10,
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? NO. 

### A minimal example program which shows the error

```
## file name: test.py
import scanpy as sc
print(sc.__version__)
```

Then install scanpy using pip
```
pip install scanpy==1.8.2
pip install pyinstaller==4.7
```
I generated the exe file using the command line below:
```
python -m PyInstaller --noupx test.py
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "scanpy\_metadata.py", line 28, in <module>
  File "pathlib.py", line 1221, in read_text
  File "pathlib.py", line 1208, in open
  File "pathlib.py", line 1063, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xie186\\PycharmProjects\\pitaya\\test_exe\\dist\\test\\pyproject.toml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scanpy\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scanpy\_metadata.py", line 38, in <module>
  File "scanpy\_compat.py", line 25, in pkg_metadata
  File "importlib_metadata\__init__.py", line 984, in metadata
  File "importlib_metadata\__init__.py", line 561, in from_name
importlib_metadata.PackageNotFoundError: No package metadata was found for scanpy
[20028] Failed to execute script 'test' due to unhandled exception!

```

When I run this script in pycharm, it works fine. I checked the code related to this error: https://github.com/theislab/scanpy/blob/16e62d1336a95966238113cdb5ab50f7d9f880ce/scanpy/_metadata.py#L24

In pycharm, the `try` part will fail and the code in `except` part will be executed. But in the `exe` file, it seems that the app will exit after the `try` part fails.

Any help will be appreciated!

**Comment by rokm** [comment]
Try adding `--collect-metadata scanpy` to your PyInstaller command.

**Comment by xie186** [comment]
Thanks, @rokm. I tried `python -m PyInstaller --copy-metadata scanpy --noupx test.py`. Same error message was thrown.

**Comment by bwoodsend** [comment]
Can you verify that just `python test.py` works? PyCharm manages environments for you in ways that make it unsuitable for testing if your code really works.

**Comment by xie186** [comment]
Yes. This is what I got:
```
PS C:\Users\xie186\PycharmProjects\pitaya> python test.py
1.8.2

```

**Comment by xie186** [comment]
I also tried to modify `_metadata.py`(https://github.com/theislab/scanpy/blob/16e62d1336a95966238113cdb5ab50f7d9f880ce/scanpy/_metadata.py#L24) to see how it behaves in PyCharm. It seemed that in Pycharm it would first execute the `try` part upto https://github.com/theislab/scanpy/blob/16e62d1336a95966238113cdb5ab50f7d9f880ce/scanpy/_metadata.py#L28 and then it would execute  `except` part. But in exe file, the app would crash after `try` failed.

**Comment by bwoodsend** [comment]
The `try: except:` is a red herring. It's failing [here](https://github.com/theislab/scanpy/blob/16e62d1336a95966238113cdb5ab50f7d9f880ce/scanpy/_compat.py#L25). Mind injecting a `print(package)` just before that line and rerunning?

**Comment by xie186** [comment]
Thanks @bwoodsend This is what I got in PyCharm:
```
C:\Users\xie186\PycharmProjects\pitaya\venv\Scripts\python.exe C:/Users/xie186/PycharmProjects/pitaya/test.py
scanpy
1.8.2
```

When I ran exe file, here is what I got:
```
PS C:\Users\xie186\PycharmProjects\pitaya\test_exe\dist\test> .\test.exe
scanpy
Traceback (most recent call last):
  File "anndata\_metadata.py", line 28, in <module>
  File "setuptools_scm\__init__.py", line 173, in get_version
  File "setuptools_scm\__init__.py", line 177, in _get_version
  File "setuptools_scm\__init__.py", line 143, in _do_parse
LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\xie186\\PycharmProjects\\pitaya\\test_exe\\dist\\test'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scanpy\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scanpy\_utils\__init__.py", line 21, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "anndata\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "anndata\_metadata.py", line 35, in <module>
  File "importlib_metadata\__init__.py", line 984, in metadata
  File "importlib_metadata\__init__.py", line 561, in from_name
importlib_metadata.PackageNotFoundError: No package metadata was found for anndata
[19148] Failed to execute script 'test' due to unhandled exception!

```

I'm confused. I thought the `except` part was not executed. But it seems that actually It was executed based the injected line.

**Comment by bwoodsend** [comment]
> importlib_metadata.PackageNotFoundError: No package metadata was found for anndata

That's not the same error as before. Try `--recursive-copy-metadata scany` instead of just `--copy-metadata`.

**Comment by xie186** [comment]
Thank you very much. It works.
