### ISSUE TITLE
Pyinstaller throws error when building, because Dropbox is syncing the files.

### ISSUE THREAD

**Issue by josephalway** [pyinstaller/pyinstaller#6414]
Pyinstaller throws an error when building, if Dropbox is syncing. Which it automatically does when Pyinstaller starts building the executable.

Pausing Dropbox, then running Pyinstaller fixes the problem.

Created a simple hello_world.py file:
<code>
print('Hello World')
input('Press Enter to Exit')
</code>

Then ran the following command on the hello_world.spec:
<code>
pyinstaller --onefile --clean --windowed hello_world.spec
</code>

.spec file
==================
<code>
# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(['C:\\Users\\my_user_name\\Dropbox\\Programming\\Python\\Exercises\\hello_world.py'],
             pathex=[],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='hello_world',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
</code>
=============
Error Received
=============
<code>
Traceback (most recent call last):
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\win32ctypes\pywin32\win32api.py", line 229, in EndUpdateResource
    _resource._EndUpdateResource(handle, discard)
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 64, in check_false
    raise make_error(function, function_name)
OSError: [WinError 5] Access is denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\my_user_name\Dropbox\Programming\Python\Exercises\venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\building\build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\building\build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "C:\Users\my_user_name\Dropbox\Programming\Python\Exercises\hello_world.spec", line 23, in <module>
    exe = EXE(pyz,
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\building\api.py", line 507, in __init__
    self.__postinit__()
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\building\api.py", line 603, in assemble
    icon.CopyIcons(self.name, self.icon)
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\utils\win32\icon.py", line 208, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\PyInstaller\utils\win32\icon.py", line 158, in CopyIcons_FromIco
    win32api.EndUpdateResource(hdst, 0)
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\win32ctypes\pywin32\win32api.py", line 229, in EndUpdateResource
    _resource._EndUpdateResource(handle, discard)
  File "C:\Program Files\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\my_user_name\dropbox\programming\python\exercises\venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (5, 'EndUpdateResourceW', 'Access is denied.')
</code>

**Comment by rokm** [comment]
Nothing we can do here, though; if Dropbox locks the file immediately after change for the duration of the sync, that makes it inherently incompatible with PyInstaller's build process (where we do several successive updates on a file).
