### ISSUE TITLE
deploying kivymd application 

### ISSUE THREAD

**Issue by osama-ammar** [pyinstaller/pyinstaller#6450]
after creating the exe format of my app and running it I got this error :

` Traceback (most recent call last):
   File "main.py", line 21, in <module>
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivymd\uix\pickers\__init__.py", line 1, in <module>
     '''
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivymd\uix\pickers\colorpicker\__init__.py", line 1, in <module>
     '''
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivymd\uix\pickers\colorpicker\colorpicker.py", line 115, in <module>
 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\osama\\AppData\\Local\\Temp\\_MEI24402\\kivymd\\uix\\pickers\\colorpicker\\colorpicker.kv'
[2404] Failed to execute script 'main' due to unhandled exception!`

knowing that the missed file in this error (colorpicker.kv) already exists in my virtual env
and when running my code with the virtual env it works normally without errors

**Comment by rokm** [comment]
I cannot reproduce this - with today's git master checkout of `kivymd` (kivymd/KivyMD@d7ee598d7b4d810eea875cfc849079871b8eab35), the .kv files are properly collected. 

I assume you are also using a git checkout, because the latest `kivymd` release does not have `kivymd\uix\pickers\colorpicker\colorpicker.py` yet. So perhaps you need to update your `kivymd` - it seems kivymd/KivyMD@1d61604eb8ea0d2619245de1be8dad1ef654a24f was the commit that added collection of .kv files to their PyInstaller hook.
