### ISSUE TITLE
Error pyinstaller

### ISSUE THREAD

**Issue by ccimarp1990** [pyinstaller/pyinstaller#6452]
Error after clic in the exe file

Traceback (most recent call last):
  File "warning.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "geopandas\__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "geopandas\datasets\__init__.py", line 6, in <module>
StopIteration

**Comment by rokm** [comment]
`pyinstaller --collect-data geopandas.datasets ...`
