### ISSUE TITLE
No module named 'numpy.distutils'

### ISSUE THREAD

**Issue by xo-HADES-xo** [pyinstaller/pyinstaller#6485]
### Context information (for bug reports)

* Output of `pyinstaller --version`:  4.7
* Version of Python:  3.9.9
* Platform: Windows 10
* How you installed Python: python.org/downloads

After updating Numpy to latest version (numpy.__version__ = '1.22.0'), running executable gives this error: 

 ```
 Traceback (most recent call last):
  File "xxx.pyw", line 76, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\__init__.py", line 401, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_minimize.py", line 27, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_constraints.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "numpy\testing\__init__.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "numpy\testing\_private\extbuild.py", line 11, in <module>
  ModuleNotFoundError: No module named 'numpy.distutils'
```

**Comment by rokm** [comment]
Already fixed in both `v4` and `develop` branch by #6474. So it will be fixed once next 4.x release comes out.

**Comment by valtynikov** [comment]
@rokm is there any workaround available in the meantime?

**Comment by rokm** [comment]
> @rokm is there any workaround available in the meantime?

You can patch your local PyInstaller installation; edit `PyInstaller/hooks/hook-numpy.py` and remove `distutils` and `numpy.distutils` from `excludedimports`:
https://github.com/pyinstaller/pyinstaller/blob/41842f5ad31dd33d7ba4ae03daace2287c80dcb7/PyInstaller/hooks/hook-numpy.py#L44-L53

**Comment by valtynikov** [comment]
@rokm ok, thanks! I was hoping there's a way to override this via a command argument. We are running PyInstaller in a Conda environment as part of the build process so the environment gets built and destroyed on the fly. I guess we'll have to wait for the next release.

**Comment by rokm** [comment]
Can you check if adding `--hiddenimport distutils --hiddenimport numpy.distutils` to your PyInstaller command works around the problem?

**Comment by valtynikov** [comment]
> Can you check if adding `--hiddenimport distutils --hiddenimport numpy.distutils` to your PyInstaller command works around the problem?

Yes, I've tried that but it still fails with a slightly different stack trace:
```
Traceback (most recent call last):
  File "MyApplication.py", line 15, in <module>
    import MyApplicationBL as businesslogic
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "MyApplicationBL.py", line 10, in <module>
    from scipy.stats.mstats import winsorize
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\stats\__init__.py", line 441, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\stats\stats.py", line 43, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\stats\distributions.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\stats\_distn_infrastructure.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\__init__.py", line 401, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_minimize.py", line 27, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_constraints.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "numpy\testing\__init__.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "numpy\testing\_private\extbuild.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "numpy\distutils\__init__.py", line 24, in <module>
ImportError: cannot import name 'ccompiler' from partially initialized module 'numpy.distutils' (most likely due to a circular import) (C:\Users\MyUser\AppData\Local\Temp\2\_MEI187842\numpy\distutils\__init__.pyc)
[28812] Failed to execute script 'MyApplication' due to unhandled exception!
```

**Comment by rokm** [comment]
A `--hiddenimport distutils --collect-submodules numpy.distutils`, then?

**Comment by valtynikov** [comment]
> A `--hiddenimport distutils --collect-submodules numpy.distutils`, then?

Thanks for the suggestion! Adding `--collect-submodules numpy.distutils` still errored with
```
  File "numpy\distutils\unixccompiler.py", line 11, in <module>
ModuleNotFoundError: No module named 'distutils.unixccompiler'
```
but using `--collect-submodules distutils --collect-submodules numpy.distutils` did the trick.
