### ISSUE TITLE
pyinstaller support for tensorflow-2.6 and tensorflow-2.7

### ISSUE THREAD

**Issue by aininot260** [pyinstaller/pyinstaller#6538]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: 3.8
* Platform: Microsoft Windows [pro 10.0.22000.434]
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
Not yet.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
yes

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [√] start with clean installation
  * [ √] use the latest development version
  * [ √] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ √] Package your program in **--onedir mode**
  * [ √] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

my code like this:
```
import tensorflow as tf
from tensorflow import keras

loaded_model = keras.models.load_model(saved_model_keras_dir)
```
It works well on tensorflow-2.5.0

When I upgrade tensorflow to 2.6.0. It failed during build step.

If I change my code to this type:
```
import tensorflow as tf

loaded_model = tf.keras.models.load_model(saved_model_keras_dir)
```
It can pass the build step but failed during runtime shows in output1

When I upgrade tensorflow to tensorflow-2.7
The above two types of codes can pass the build type but failed during runtime like output2

### Stacktrace / full error message

output1
```
Traceback (most recent call last):
  File "main.py", line 29, in pushButton_2
  File "model_type.py", line 9, in saved_model_keras_to_hdf5
  File "tensorflow\python\util\lazy_loader.py", line 62, in __getattr__
  File "tensorflow\python\util\lazy_loader.py", line 45, in _load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keras'
```

output2

```
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
debug:  C:/Users/aininot260/ModelType/demo/models/keras_saved_model
Traceback (most recent call last):
  File "main.py", line 29, in pushButton_2
  File "model_type.py", line 9, in saved_model_keras_to_hdf5
  File "tensorflow\python\util\lazy_loader.py", line 62, in __getattr__
  File "tensorflow\python\util\lazy_loader.py", line 45, in _load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keras'
```

**Comment by rokm** [comment]
See #6519. We'll update the tensorflow hook in `pyinstaller-hooks-contrib` to automatically collect `keras`.
