### ISSUE TITLE
clr_loader - cannot load library ClrLoader.dll

### ISSUE THREAD

**Issue by Knocks83** [pyinstaller/pyinstaller#6572]
## Description of the issue
When trying to freeze a basic pywebview interface it compiles succesfully, but when I run it it cannot find a dll (CrlLoader.dll)

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.9```
* Version of Python: `3.10.2`
* Platform: `Windows 11`
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import webview

window = webview.create_window('web', '')
webview.start()
```

### Stacktrace / full error message

```
# code object from 'C:\\Users\\Knocks\\Desktop\\test\\dist\\test\\ctypes\\util.pyc'
import 'ctypes.util' # <_frozen_importlib_external.SourcelessFileLoader object at 0x0000015576E42590>
Traceback (most recent call last):
  File "test.py", line 4, in <module>
  File "C:\Program Files\Python310\lib\site-packages\webview\__init__.py", line 122, in start
    guilib = initialize(gui)
  File "C:\Program Files\Python310\lib\site-packages\webview\guilib.py", line 98, in initialize
    if not try_import(guis):
  File "C:\Program Files\Python310\lib\site-packages\webview\guilib.py", line 62, in try_import
    if import_func():
  File "C:\Program Files\Python310\lib\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python310\lib\site-packages\webview\platforms\winforms.py", line 30, in <module>
    import clr
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python310\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Program Files\Python310\lib\site-packages\pythonnet\__init__.py", line 36, in load
    set_default_runtime()
  File "C:\Program Files\Python310\lib\site-packages\pythonnet\__init__.py", line 20, in set_default_runtime
    set_runtime(clr_loader.get_netfx())
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\__init__.py", line 55, in get_netfx
    impl = NetFx(name=name, config_file=config_file)
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\netfx.py", line 10, in __init__
    initialize()
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\netfx.py", line 35, in initialize
    _FW = load_netfx()
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\ffi\__init__.py", line 51, in load_netfx
    return ffi.dlopen(path)
  File "C:\Program Files\Python310\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Program Files\Python310\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Program Files\Python310\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'C:\Users\Knocks\Desktop\test\dist\test\clr_loader\ffi\dlls\amd64\ClrLoader.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\Knocks\\Desktop\\test\\dist\\test\\clr_loader\\ffi\\dlls\\amd64\\ClrLoader.dll'
[17168] Failed to execute script 'test' due to unhandled exception!
```

I also tried adding the `--hidden-import=_cffi_backend` switch, but it makes no difference.

**Comment by rokm** [comment]
How about `--collect-binaries clr_loader`?

**Comment by Knocks83** [comment]
> How about `--collect-binaries clr_loader`?

@rokm you're my lord and savior, thanks a lot!

**Comment by ironmann250** [comment]
i faced the same issue, am running python 3.9.7, PyInstaller 4.10.
i added --collect-binaries clr_loader and still it did not work

**a minimal code to show the error**

`
import toga
from toga.style import Pack
from toga.style.pack import COLUMN

class ChineseDictionary(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

def main():
    return ChineseDictionary('sample app', 'com.example.example')
if __name__ == '__main__':
    main().main_loop() `

**my stack trace is here**

` 
[29424] PyInstaller Bootloader 3.x
[29424] LOADER: executable is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\app_one_file.exe
[29424] LOADER: homepath is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file
[29424] LOADER: _MEIPASS2 is NULL
[29424] LOADER: archivename is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\app_one_file.exe
[29424] LOADER: Cookie found at offset 0x37E0EA
[29424] LOADER: No need to extract files to run; setting extractionpath to homepath
[29424] LOADER: SetDllDirectory(D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file)
[29424] LOADER: Already in the child - running user's code.
[29424] LOADER: Python library: D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\python39.dll
[29424] LOADER: Loaded functions from Python library.
[29424] LOADER: Manipulating environment (sys.path, sys.prefix)
[29424] LOADER: sys.prefix is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file
[29424] LOADER: Pre-init sys.path is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\base_library.zip;D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\lib-dynload;D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file
[29424] LOADER: Setting runtime options
[29424] LOADER: Initializing python
[29424] LOADER: Overriding Python's sys.path
[29424] LOADER: Post-init sys.path is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\base_library.zip;D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\lib-dynload;D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file
[29424] LOADER: Setting sys.argv
[29424] LOADER: setting sys._MEIPASS
[29424] LOADER: importing modules from CArchive
[29424] LOADER: extracted struct
[29424] LOADER: running unmarshalled code object for struct...
[29424] LOADER: extracted pyimod01_os_path
[29424] LOADER: running unmarshalled code object for pyimod01_os_path...
[29424] LOADER: extracted pyimod02_archive
[29424] LOADER: running unmarshalled code object for pyimod02_archive...
[29424] LOADER: extracted pyimod03_importers
[29424] LOADER: running unmarshalled code object for pyimod03_importers...
[29424] LOADER: extracted pyimod04_ctypes
[29424] LOADER: running unmarshalled code object for pyimod04_ctypes...
[29424] LOADER: Installing PYZ archive with Python modules.
[29424] LOADER: PYZ archive: PYZ-00.pyz
[29424] LOADER: Running pyiboot01_bootstrap.py
[29424] LOADER: Running pyi_rth_subprocess.py
[29424] LOADER: Running pyi_rth_pkgutil.py
[29424] LOADER: Running pyi_rth_multiprocessing.py
[29424] LOADER: Running pyi_rth_inspect.py
[29424] LOADER: Running pyi_rth_pkgres.py
[29424] LOADER: Running pyi_rth_win32api.py
[29424] LOADER: Running pyi_rth_win32comgenpy.py
[29424] LOADER: Running app_one_file.py
Traceback (most recent call last):
  File "chinesedictionary\app_one_file.py", line 191, in <module>
  File "chinesedictionary\app_one_file.py", line 189, in main
  File "toga\app.py", line 272, in __init__
  File "toga\platform.py", line 53, in get_platform_factory
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\factory.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\app.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\keys.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\libs\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\libs\fonts.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\libs\winforms.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 36, in load
  File "pythonnet\__init__.py", line 20, in set_default_runtime
  File "clr_loader\__init__.py", line 55, in get_netfx
  File "clr_loader\netfx.py", line 10, in __init__
  File "clr_loader\netfx.py", line 35, in initialize
  File "clr_loader\ffi\__init__.py", line 51, in load_netfx
  File "cffi\api.py", line 150, in dlopen
  File "cffi\api.py", line 832, in _make_ffi_library
  File "cffi\api.py", line 827, in _load_backend_lib
OSError: cannot load library 'D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\clr_loader\ffi\dlls\amd64\ClrLoader.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'D:\\school\\python and ai\\chinesedictionary\\src\\chinesedictionary\\dist\\app_one_file\\clr_loader\\ffi\\dlls\\amd64\\ClrLoader.dll'
[29424] Failed to execute script 'app_one_file' due to unhandled exception!
[29424] LOADER: OK.
[29424] LOADER: Manually flushing stdout and stderr
[29424] LOADER: Cleaning up Python interpreter.
Exception ignored in: <function NetFx.__del__ at 0x000001C4826F0940>
Traceback (most recent call last):
  File "clr_loader\netfx.py", line 26, in __del__
AttributeError: 'NetFx' object has no attribute '_domain' `
