### ISSUE TITLE
Can Pyinstaller build exe on the windows arm64 architecture?

### ISSUE THREAD

**Issue by Jan5566** [pyinstaller/pyinstaller#6588]
### Problem: I need pyinstaller to create an exe on Windows arm64 architecture.

Python version: 3.11.0a5
Pyinstaller version: 5.0.dev0

### Error:
C:\Users\HCKTest\Desktop\p>pyinstaller -F test.py
Traceback (most recent call last):
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Scripts\pyinstaller-script.py", line 33, in <module>
    sys.exit(load_entry_point('pyinstaller==5.0.dev0', 'console_scripts', 'pyinstaller')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\__main__.py", line 108, in run
    parser = generate_parser()
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\__main__.py", line 76, in generate_parser
    import PyInstaller.building.build_main
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\building\build_main.py", line 27, in <module>
    from PyInstaller.building.api import COLLECT, EXE, MERGE, PYZ
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\building\api.py", line 26, in <module>
    from PyInstaller.archive.writers import CArchiveWriter, ZlibArchiveWriter
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\archive\writers.py", line 28, in <module>
    from PyInstaller.building.utils import fake_pyc_timestamp, get_code_object, strip_paths_in_code
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\building\utils.py", line 31, in <module>
    from PyInstaller.depend.bindepend import match_binding_redirect
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\depend\bindepend.py", line 26, in <module>
    from PyInstaller.depend import dylib, utils
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\depend\utils.py", line 29, in <module>
    from PyInstaller.depend import bytecode
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\depend\bytecode.py", line 85, in <module>
    _call_function_bytecode = bytecode_regex(
                              ^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\depend\bytecode.py", line 52, in bytecode_regex
    pattern = re.sub(
              ^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\re.py", line 189, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\depend\bytecode.py", line 54, in <lambda>
    lambda m: _instruction_to_regex(m[1].decode()),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCKTest\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pyinstaller-5.0.dev0-py3.11.egg\PyInstaller\depend\bytecode.py", line 35, in _instruction_to_regex
    return re.escape(bytes([dis.opmap[x]]))
                            ~~~~~~~~~^^^
KeyError: 'CALL_FUNCTION'


Is there a better way to do this? Please let me know. Thanks.

**Comment by bwoodsend** [comment]
We've never tested it and we don't ship precompiled bootloaders for it so the short answer is we don't know.

In your case, PyInstaller doesn't support Python 3.11. Switching to Python 3.10 will get you past your current error. How did you install PyInstaller? It should have blocked an install on Python 3.11 but I see you've not only bypassed that but somehow installed PyInstaller into the long dead egg format. I ask because how you install PyInstaller will affect whether or not it compiled `arm64` compatible bootloaders which is where it's most likely to break.

**Comment by Jan5566** [comment]
Hi @bwoodsend ,

I install pyinstaller as following:
- git clone https://github.com/pyinstaller/pyinstaller.git
- cd bootloader and python ./waf all
- cd .. and python setup.py install

It can build exe and run after switching to Python 3.10.2. But the exe not work in the WinPE environment. Is there a better way to do this?

**Comment by bwoodsend** [comment]
> Is there a better way to do this?

Like I say, we've never tried this before so I wouldn't know if there was.

> But the exe not work in the WinPE environment.

You're going to have to be way more specific than that. How does it fail? What's the stacktrace? Is it specific to your application or does it still fail if you try to build something trivial like `print("hello")`? What is this *WinPE environment* environment - is it even still `arm64`?

**Comment by rokm** [comment]
First check if the bootloader was actually built for `arm64` (i.e., by inspecting the executable) - I wouldn't be surprised if you actually ended up with `x86_64` build...
