### ISSUE TITLE
On Debian/Ubuntu, you would need to install Python development packages

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#6594]
I have **termux** and my termux is aarch81. I already installed pyinstaller version **3.6**.
When I encrypt pyinstaller in python. Here comes the error.
```
$ pyinstaller libfile.py --onefile

204 INFO: PyInstaller: 3.6
204 INFO: Python: 2.7.18
207 INFO: Platform: Linux-4.9.190+-armv8l-with-libc
209 INFO: wrote /data/data/com.termux/files/home/libfile.spec
252 INFO: UPX is not available.
260 INFO: Extending PYTHONPATH with paths
['/data/data/com.termux/files/home', '/data/data/com.termux/files/home']
260 INFO: checking Analysis
261 INFO: Building Analysis because Analysis-00.toc is non existent
261 INFO: Initializing module dependency graph...
271 INFO: Caching module graph hooks...
311 INFO: Caching module dependency graph...
417 INFO: running Analysis Analysis-00.toc
562 INFO: Analyzing /data/data/com.termux/files/home/libfile.py
17964 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
36887 INFO: Processing pre-safe import module hook   _xmlplus
37412 INFO: Processing pre-find module path hook   distutils
37415 INFO: distutils: retargeting to non-venv dir '/data/data/com.termux/files/usr/lib/python2.7'
45653 INFO: Processing pre-safe import module hook   six.moves
57437 INFO: Processing module hooks...
57439 INFO: Loading module hook "hook-distutils.py"...
57453 INFO: Loading module hook "hook-sysconfig.py"...
57459 INFO: Loading module hook "hook-xml.py"...
57466 INFO: Loading module hook "hook-httplib.py"...
57471 INFO: Loading module hook "hook-pkg_resources.py"...
59287 INFO: Processing pre-safe import module hook   win32com
61215 INFO: Excluding import '__main__'
61222 INFO:   Removing import of __main__ from module pkg_resources
61226 INFO: Loading module hook "hook-xml.dom.domreg.py"...
61231 INFO: Loading module hook "hook-certifi.py"...
61240 INFO: Loading module hook "hook-pytz.py"...
61483 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
61488 INFO: Loading module hook "hook-encodings.py"...
65184 INFO: Looking for ctypes DLLs
66154 WARNING: Ignoring /usr/lib/libc.dylib imported from /data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/monotonic.py - ctypes imports are only supported using bare filenames
66842 INFO: Analyzing run-time hooks ...
66879 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
66913 INFO: Including run-time hook 'pyi_rth_pkgres.py'
66925 INFO: Including run-time hook 'pyi_rth_certifi.py'
67000 INFO: Looking for dynamic libraries
72287 INFO: Looking for eggs
72291 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "/data/data/com.termux/files/home/libfile.spec", line 17, in <module>
    noarchive=False)
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 244, in __init__
    self.__postinit__()
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 478, in assemble
    self._check_python_library(self.binaries)
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 568, in _check_python_library
    python_lib = bindepend.get_python_library_path()
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/home-YTx_54AN/lib/python2.7/site-packages/PyInstaller/depend/bindepend.py", line 945, in get_python_library_path
    raise IOError(msg)
IOError: Python library not found: libpython2.7.so.1.0, libpython2.7mu.so.1.0, libpython2.7m.so.1.0, libpython2.7m.so
    This would mean your Python installation doesn't come with proper library files.
    This usually happens by missing development package, or unsuitable build parameters of Python installation.

    * On Debian/Ubuntu, you would need to install Python development packages
      * apt-get install python3-dev
      * apt-get install python-dev
    * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
    ```

**Comment by bwoodsend** [comment]
You need to do what it says. Run `apt-get install python-dev`.

**Comment by ghost** [comment]
> 

Hmm. I have android Termux. But this modules ```apt install python-dev``` not works in termux. 
**Here comes the error**
```
$ apt install python-dev

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python

E: Package 'python-dev' has no installation candidate

**Comment by bwoodsend** [comment]
You'll have to search around for the termux equivalent then. This isn't a support service.

**Comment by ghost** [comment]
> You'll have to search around for the termux equivalent then. This isn't a support service.

Hmmm okay sir.

**Comment by ghost** [comment]
But our team needs such a pyinstaller. Which works in python2.
I have already installed pyinstaller 3.0 version. This pyinstaller 3.0 also works in python2.
But my question is why pyinstaller doesn't work in python2

**Comment by ghost** [comment]
@bwoodsend reply? 👆

**Comment by rokm** [comment]
While PyInstaller 3.6 does indeed still support python 2.7, it probably doesn't support termux linux library search paths. If you really want to use PyInstaller 3.6 and python 2.7, you'll probably have to backport #6484 (at least).

But since you're using unsupported/EOL python version and unsupported PyInstaller version, you're pretty much on your own.

**Comment by ghost** [comment]
> While PyInstaller 3.6 does indeed still support python 2.7, it probably doesn't support termux linux library search paths. If you really want to use PyInstaller 3.6 and python 2.7, you'll probably have to backport #6484 (at least).
> 
> But since you're using unsupported/EOL python version and unsupported PyInstaller version, you're pretty much on your own.

Hmmm, it's mean that my termux is not found ```libpython2.7.so.1.0``` . I also check using ```objdump -x `which python` ```.
**Here display on termux**

```
$ objdump -x `which python`                          
/data/data/com.termux/files/usr/bin/python:     file format elf64-littleaarch64
/data/data/com.termux/files/usr/bin/python                 architecture: aarch64, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED                                 start address 0x00000000000017f4                                                                                      Program Header:                                                PHDR off    0x0000000000000040 vaddr 0x0000000000000040 paddr 0x0000000000000040 align 2**3
         filesz 0x0000000000000268 memsz 0x0000000000000268 flags r--
  INTERP off    0x00000000000002a8 vaddr 0x00000000000002a8 paddr 0x00000000000002a8 align 2**0                                filesz 0x0000000000000015 memsz 0x0000000000000015 flags r--
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**12
         filesz 0x00000000000007f4 memsz 0x00000000000007f4 flags r--
    LOAD off    0x00000000000007f4 vaddr 0x00000000000017f4 paddr 0x00000000000017f4 align 2**12
         filesz 0x000000000000010c memsz 0x000000000000010c flags r-x
    LOAD off    0x0000000000000900 vaddr 0x0000000000002900 paddr 0x0000000000002900 align 2**12
         filesz 0x0000000000000278 memsz 0x0000000000000278 flags rw-
    LOAD off    0x0000000000000b78 vaddr 0x0000000000003b78 paddr 0x0000000000003b78 align 2**12
         filesz 0x0000000000000000 memsz 0x0000000000000008 flags rw-
 DYNAMIC off    0x0000000000000930 vaddr 0x0000000000002930 paddr 0x0000000000002930 align 2**3
         filesz 0x00000000000001f0 memsz 0x00000000000001f0 flags rw-
   RELRO off    0x0000000000000900 vaddr 0x0000000000002900 paddr 0x0000000000002900 align 2**0
         filesz 0x0000000000000278 memsz 0x0000000000000700 flags r--
EH_FRAME off    0x0000000000000720 vaddr 0x0000000000000720 paddr 0x0000000000000720 align 2**2
         filesz 0x0000000000000034 memsz 0x0000000000000034 flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**0
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
    NOTE off    0x00000000000002c0 vaddr 0x00000000000002c0 paddr 0x00000000000002c0 align 2**2
         filesz 0x0000000000000098 memsz 0x0000000000000098 flags r--

Dynamic Section:
  RUNPATH              /data/data/com.termux/files/usr/lib:/data/data/com.termux/files/usr/lib
  NEEDED               libandroid-support.so
  NEEDED               libpython3.10.so.1.0
  NEEDED               libc.so
```

**Comment by ghost** [comment]
can we export **libpython2.7.so.1.0**. is any possible?
