### ISSUE TITLE
PermissionError[Errno 13] on Windows11

### ISSUE THREAD

**Issue by Dragon-GCS** [pyinstaller/pyinstaller#6615]
**When I using 'pyinstaller myfile.py' as administrator on win11, encountered the following error**

```
16537 INFO: Emedding manifest in EXE
16537 INFO: Updating manifest in F:\Dragon\Desktop\pack\dist\punch.exe
16541 INFO: Updating resource type 24 name 1 language 0
16542 INFO: Appending PKG archive to EXE
Traceback (most recent call last):
  File "D:\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Dragon\Desktop\pack\.venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "f:\dragon\desktop\pack\.venv\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "f:\dragon\desktop\pack\.venv\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "f:\dragon\desktop\pack\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 793, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "f:\dragon\desktop\pack\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 725, in build
    exec(code, spec_namespace)
  File ".\punch.spec", line 23, in <module>
    exe = EXE(pyz,
  File "f:\dragon\desktop\pack\.venv\lib\site-packages\PyInstaller\building\api.py", line 508, in __init__
    self.__postinit__()
  File "f:\dragon\desktop\pack\.venv\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "f:\dragon\desktop\pack\.venv\lib\site-packages\PyInstaller\building\api.py", line 740, in assemble
    with open(self.name, 'ab') as outf:
PermissionError: [Errno 13] Permission denied: 'F:\\Dragon\\Desktop\\pack\\dist\\punch.exe'
```
punch is my filename. And these are my modules

```
eth_abi==2.1.1
eth_account==0.5.6
loguru==0.5.3
python_telegram_bot==13.8.1
PyYAML==6.0
requests==2.21.0
retrying==1.3.3
telegram==0.0.1
web3==5.24.0
```

**Comment by Dragon-GCS** [comment]
I's sorry for choosing a wrong tag. 
And I figure out that closing the Realtime Protection of Microsoft Defender can avoid the error. I think this error is due to some strategy's change between win10 and win11, because I never meet this error on windows10.
