### ISSUE TITLE
PyInstaller fails to bundle Django application in OSX

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#667]
**Original date**: 2013/02/08
**Original reporter**: *kevinlondon AND gmail DOT  COOM *

I am using the latest code from the github repository and I can successfully bundle the default Django project generated by "django-admin.py startproject" but when I go to use it on my own application, it does not work. Here's the trace:

```
(sentinel)klondon:pyinstaller-develop kevinlondon$ python pyinstaller.py ~/dropbox/programming/python/django/sentinel/manage.py --name=sentinel
23 INFO: wrote /Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/sentinel/sentinel.spec
44 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /Users/kevinlondon/.virtualenvs/sentinel/bin/python

4058 INFO: UPX is not available.
4085 INFO: Processing hook hook-os
4219 INFO: Processing hook hook-time
4222 INFO: Processing hook hook-cPickle
4305 INFO: Processing hook hook-_sre
4461 INFO: Processing hook hook-cStringIO
4592 INFO: Processing hook hook-encodings
4609 INFO: Processing hook hook-codecs
5085 INFO: Extending PYTHONPATH with /Users/kevinlondon/dropbox/programming/python/django/sentinel
5085 INFO: checking Analysis
5085 INFO: building Analysis because out00-Analysis.toc non existent
5085 INFO: running Analysis out00-Analysis.toc
5103 INFO: Analyzing /Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/loader/_pyi_bootstrap.py
5118 INFO: Processing hook hook-os
5131 INFO: Processing hook hook-site
5279 INFO: Processing hook hook-time
5282 INFO: Processing hook hook-cPickle
5366 INFO: Processing hook hook-_sre
5520 INFO: Processing hook hook-cStringIO
5640 INFO: Processing hook hook-encodings
5656 INFO: Processing hook hook-codecs
6173 INFO: Processing hook hook-pydoc
6336 INFO: Processing hook hook-email
6410 INFO: Processing hook hook-httplib
6457 INFO: Processing hook hook-email.message
6847 INFO: Analyzing /Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/loader/pyi_importers.py
6905 INFO: Analyzing /Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/loader/pyi_archive.py
6962 INFO: Analyzing /Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/loader/pyi_carchive.py
7018 INFO: Analyzing /Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/loader/pyi_os_path.py
7024 INFO: Analyzing /Users/kevinlondon/dropbox/programming/python/django/sentinel/manage.py
7033 INFO: Django root directory /Users/kevinlondon/dropbox/programming/python/django/sentinel/sentinel
125 INFO: Sentinel launched.
Traceback (most recent call last):
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/hooks/utils/django-import-finder.py", line 50, in <module>
    hiddenimports += find_url_callbacks(urls)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/hooks/utils/django-import-finder.py", line 35, in find_url_callbacks
    hid_list += find_url_callbacks(pattern.urlconf_module)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/hooks/utils/django-import-finder.py", line 28, in find_url_callbacks
    urlpatterns = urls_module.urlpatterns
AttributeError: 'list' object has no attribute 'urlpatterns'
Traceback (most recent call last):
  File "pyinstaller.py", line 83, in <module>
    main()
  File "pyinstaller.py", line 78, in main
    run_build(opts, spec_file)
  File "pyinstaller.py", line 42, in run_build
    PyInstaller.build.main(spec_file, **opts.__dict__)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/build.py", line 1665, in main
    build(specfile, buildpath)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/build.py", line 1622, in build
    execfile(spec)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/sentinel/sentinel.spec", line 6, in <module>
    runtime_hooks=None)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/build.py", line 403, in __init__
    self.__postinit__()
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/build.py", line 305, in __postinit__
    self.assemble()
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/build.py", line 556, in assemble
    importTracker.analyze_script(script)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/depend/imptracker.py", line 247, in analyze_script
    return self.analyze_r('__main__')
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/depend/imptracker.py", line 140, in analyze_r
    newnms = self.analyze_one(name, nm, imptyp, level)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/depend/imptracker.py", line 201, in analyze_one
    mod = self.doimport(nm, ctx, fqname)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/depend/imptracker.py", line 298, in doimport
    hooks = __import__('PyInstaller.hooks', globals(), locals(), [hookmodnm])
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller-develop/PyInstaller/hooks/hook-django.py", line 35, in <module>
    package_name + '.wsgi',
TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by matysek** [comment]
Closing since it was fixed.
