### ISSUE TITLE
pyinstaller 4.0-4.3 fails to install 

### ISSUE THREAD

**Issue by TarynScharf** [pyinstaller/pyinstaller#6704]
I've been  using pyinstaller 4.0 to build an executable via a [github workflow](https://github.com/TarynScharf/AnalyZr/blob/3818a3dec92a98e8daa90b4100889ecfbee9d15c/.github/workflows/buildapp.yml#L89). The last successful build was in Dec 2021. However, it has now stopped working as the installation of Pyinstaller fails with  the error message below. 

The error can be reproduced on my local machine. I can install pyinstaller 4.4 and above, however, this is not an option as the executable no longer builds correctly with these versions of pyinstaller. Installations of 4.0 and above work on Ubuntu, thus the problem appears to be  Windows specific. 

The github workflow runs on Windows Server 2022. My local machine runs on Windows 10. I am running Python 3.7 with pip 20.1.1. 

I am a bit confused about why the installation has stopped working, because as far as I'm aware, nothing has changed in my  build setup.

```
C:\Users\20023951\Documents\PhD>pip install pyinstaller==4.0
Collecting pyinstaller==4.0
  Using cached pyinstaller-4.0.tar.gz (3.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\20023951\appdata\local\programs\python\python37\python.exe' 'c:\users\20023951\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\20023951\AppData\Local\Temp\tmpa8531om8'
         cwd: C:\Users\20023951\AppData\Local\Temp\pip-install-6yh3x6wg\pyinstaller
    Complete output (42 lines):
    Traceback (most recent call last):
      File "c:\users\20023951\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\users\20023951\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\users\20023951\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\build_meta.py", line 282, in run_setup
        self).run_setup(setup_script=setup_script)
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 78, in <module>
        'build': MyBuild,
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\__init__.py", line 79, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 122, in setup
        dist.parse_config_files()
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\dist.py", line 833, in parse_config_files
        self, self.command_options, ignore_option_errors=ignore_option_errors
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 167, in parse_configuration
        meta.parse()
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 446, in parse
        section_parser_method(section_options)
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 417, in parse_section
        self[name] = value
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 238, in __setitem__
        value = parser(value)
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 552, in _parse_version
        return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 372, in _parse_attr
        return expand.read_attr(attr_desc, package_dir, root_dir)
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\config\expand.py", line 194, in read_attr
        module = _load_spec(spec, module_name)
      File "C:\Users\20023951\AppData\Local\Temp\pip-build-env-jtrwgyak\overlay\Lib\site-packages\setuptools\config\expand.py", line 214, in _load_spec
        spec.loader.exec_module(module)  # type: ignore
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\20023951\AppData\Local\Temp\pip-install-6yh3x6wg\pyinstaller\PyInstaller.py", line 16, in <module>
        from PyInstaller.__main__ import run
    ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\20023951\appdata\local\programs\python\python37\python.exe' 'c:\users\20023951\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\20023951\AppData\Local\Temp\tmpa8531om8' Check the logs for full command output.
```

**Comment by rokm** [comment]
The problem is caused by the latest `setuptools` in combination with sdist containing both `pyinstaller.py` script and `PyInstaller` package (which end up shadowing each other on case-insensitive OSes, i.e., Windows in macOS). In current versions of pyinstaller, the fix was to remove the script as it is not used anyway (there are auto-generated entry-point scripts) - take a look at #6701. 

We generally don't support old PyInstaller versions, so if you want to continue using 4.0~4.3, you'll need to backport the fix yourself. (EDIT: or pin `setuptools` to an earlier version).

**Comment by mungojam** [comment]
I get this same error from pipenv when using it with the latest pyinstaller 5. It doesn't seem to actually impact anything though and everything works as expected.

> 
>   File "C:\Users\gg\AppData\Local\Temp\pip-build-env-888ppfjt\overlay\Lib\site-packages\setuptools\config\expand.py
> ", line 194, in read_attr
>     module = _load_spec(spec, module_name)
>   File "C:\Users\gg\AppData\Local\Temp\pip-build-env-888ppfjt\overlay\Lib\site-packages\setuptools\config\expand.py
> ", line 214, in _load_spec
>     spec.loader.exec_module(module)  # type: ignore
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "C:\Users\gg\AppData\Local\Temp\pipenv-zb5tngvo-build\pyinstaller_efa5744cb7a94aa3863426d640cf73cd\PyInstall
> er.py", line 16, in <module>
>     from PyInstaller.__main__ import run
> ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
