### ISSUE TITLE
PyInstaller upgrade/downgrade failed with pip

### ISSUE THREAD

**Issue by JiayangZhou** [pyinstaller/pyinstaller#6707]
## Description of the issue
The upgrade and downgrade operations via pip (22.0.4) on pyinstaller are failed on Windows. It used to be working but started to have consistent issues since March 24, 2022. 

I am currently have pyinstaller version 4.2 installed but when I run `pip install pyinstaller==4.1` I got the below error. On another machine of mine, I don't have pyinstaller installed and I tried to run `pip install pyinstaller==4.2` and got the exact same error as posted below.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2``
* Version of Python: 3.9.7
* Platform: Windows (EN)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Tried on both windows 10 and windows-base:2019-1.0, none working

* try the latest development version, using the following command: worked

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Stacktrace / full error message

```
PS C:\Users\jzhou1\CM3\self-hosted-butler> pip install pyinstaller==4.1
Collecting pyinstaller==4.1
  Using cached pyinstaller-4.1.tar.gz (3.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      Traceback (most recent call last):
        File "C:\Users\jzhou1\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\jzhou1\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\jzhou1\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 75, in <module>
          setup(
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 122, in setup
          dist.parse_config_files()
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\dist.py", line 850, in parse_config_files
          setupcfg.parse_configuration(
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 167, in parse_configuration
          meta.parse()
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 446, in parse
          section_parser_method(section_options)
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 417, in parse_section
          self[name] = value
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 238, in __setitem__
          value = parser(value)
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 552, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 372, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\config\expand.py", line 194, in read_attr
          module = _load_spec(spec, module_name)
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-build-env-46mk3hja\overlay\Lib\site-packages\setuptools\config\expand.py", line 214, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "C:\Users\jzhou1\AppData\Local\Temp\pip-install-1n9yraq0\pyinstaller_5e5ac0a8cc7a48488847f967c0f89295\PyInstaller.py", line 16, in <module>
          from PyInstaller.__main__ import run
      ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by JiayangZhou** [comment]
The issue with executing this command `pip install pyinstaller==4.X` seems to only occur on pyinstaller versions between 4.0 to 4.3, but worked fine for later version of pyinstaller

**Comment by rokm** [comment]
See #6704.
