### ISSUE TITLE
Using special characters in "Braizilian PT-BR" in comments or print, break the build

### ISSUE THREAD

**Issue by diegomontania** [pyinstaller/pyinstaller#6712]
## Description of the issue

I did some comments in my program, but using my native language (Portuguese PT-BR). And when the pyinstaller was building, the cmd give me a error in the file 'codecs.py' :
```
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 18: invalid continuation byte
```
So after many hours, I solved the problem just removing all special characters and the build works. I dont tested the .exe yet. Just one character break everthing.

I dont see any coments on internet or stackoverflow about this problem. 

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.10```
* Version of Python: 3.9.7 (64-bit)
* Platform: Windows-10-10.0.19043-SP0
* IDE : Microsoft Visual Studio Community 2022 (64-bit) - Version 17.0.6
* How you installed Python: pip 22.0.4 from C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\pip (python 3.9)

### A minimal example program which shows the error

```
C:\Users\diego\source\repos\teste.extracaotabelas.python\teste.extracaotabelas.python>pyinstaller --onefile a.py
```

```
def main():
    #ã ç ó í

if __name__ == "__main__":
    main()
```

### Stacktrace / full error message

```
480 INFO: PyInstaller: 4.10
480 INFO: Python: 3.9.7
688 INFO: Platform: Windows-10-10.0.19043-SP0
690 INFO: wrote C:\Users\diego\source\repos\teste.extracaotabelas.python\teste.extracaotabelas.python\a.spec
701 INFO: UPX is not available.
721 INFO: Extending PYTHONPATH with paths
['C:\\Users\\diego\\source\\repos\\teste.extracaotabelas.python\\teste.extracaotabelas.python']
1208 INFO: checking Analysis
1209 INFO: Building Analysis because Analysis-00.toc is non existent
1209 INFO: Initializing module dependency graph...
1214 INFO: Caching module graph hooks...
1233 INFO: Analyzing base_library.zip ...
4086 INFO: Processing pre-find module path hook distutils from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python39_64\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
4088 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python39_64\\lib'
7750 INFO: Caching module dependency graph...
7990 INFO: running Analysis Analysis-00.toc
8011 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe
8106 INFO: Analyzing C:\Users\diego\source\repos\teste.extracaotabelas.python\teste.extracaotabelas.python\a.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\building\build_main.py", line 803, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\building\build_main.py", line 725, in build
    exec(code, spec_namespace)
  File "C:\Users\diego\source\repos\teste.extracaotabelas.python\teste.extracaotabelas.python\a.spec", line 7, in <module>
    a = Analysis(['a.py'],
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\building\build_main.py", line 277, in __init__
    self.__postinit__()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\building\build_main.py", line 439, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\depend\analysis.py", line 265, in add_script
    self._top_script_node = super().add_script(pathname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1419, in add_script
    contents = fp.read() + '\n'
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 18: invalid continuation byte
```
[file-python.zip](https://github.com/pyinstaller/pyinstaller/files/8374835/file-python.zip)

**Comment by rokm** [comment]
The `a.py` in the attached archive is not using UTF-8 encoding - it doesn't run under python interpreter for me, either:
```
python a.py
  File "a.py", line 2
SyntaxError: Non-UTF-8 code starting with '\xe3' in file a.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by rokm** [comment]
If I copy your minimal example,
```python
def main():
    #ã ç ó í
    pass

if __name__ == "__main__":
    main()
```
and save it in a new file (defaulting to UTF-8), there's no error.

**Comment by bwoodsend** [comment]
Ughh, Windows and its encodings.... I'm surprised that this one hasn't shown up sooner. I would strongly recommend that you write all source files in utf-8.

**Comment by bwoodsend** [comment]
@diegomontania Does `python a.py` work for you? I'd be very surprised if it does.

**Comment by rokm** [comment]
0xe3 is ã, and 0xe7 is ç in  [iso-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) or [windows-1252](https://en.wikipedia.org/wiki/Windows-1252). So declaring the encoding, 

```python
# coding=ansi
```
on top of `a.py` also does the trick.

Either way, that's not our bug, but incorrectly configured text editor on user's side.

**Comment by diegomontania** [comment]
> @diegomontania Does `python a.py` work for you? I'd be very surprised if it does.

Yes, work without any problems.

**Comment by bwoodsend** [comment]
What if you run:
```python
with open("a.py", "rb") as f:
    compile(f.read(), "a.py", "exec")
```
