### ISSUE TITLE
Window EXE: ModuleNotFoundError: No module named

### ISSUE THREAD

**Issue by darrencl** [pyinstaller/pyinstaller#6730]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.10```
* Version of Python:  3.8.12
* Platform:  Windows 10
* How you installed Python:  miniconda
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Looking at the error message below, the last code of mine in the stacktrace is from `mrspectroproc\io\cosyobjects.py`, which is `import suspect.base` and then it went to `suspect.py` when they use Parsley.py. So, I'll just put this line in. Note that I have also explicitly use `--hidden-import=Parsley`, which I saw it has been properly propagated to the SPEC file.

```
import suspect.base
```

### Stacktrace / full error message

The exe was created successfully, but upon running it, I got this error from Parsley, a dependency of [`suspect.py`](https://github.com/openmrslab/suspect).

```
(base) C:\Users\darrencl\Documents\mrspectroproc\mrspectroproc\dist>mrspectroproc.exe
Traceback (most recent call last):
  File "ometa\grammar.py", line 24, in loadGrammar
ModuleNotFoundError: No module named 'ometa._generated.parsley_termactions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mrspectroproc\mrspectroproc.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "mrspectroproc\mrspectroproc_lib.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "mrspectroproc\processing\pipeline.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "mrspectroproc\processing\pipeline_lib.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "mrspectroproc\processing\channel_combination.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "mrspectroproc\io\cosyobjects.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "suspect\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "suspect\io\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "suspect\io\lcmodel.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "parsley.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "ometa\grammar.py", line 33, in <module>
  File "ometa\grammar.py", line 28, in loadGrammar
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\darrencl\\AppData\\Local\\Temp\\_MEI62802\\ometa\\parsley_termactions.parsley'
[7840] Failed to execute script 'mrspectroproc' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by forctis** [comment]
Seeing...

_No such file or directory: 'C:\\Users\\darrencl\\AppData\\Local\\Temp\\_MEI62802\\ometa\\parsley_termactions.parsley'_

have you included the not found folder/file(s) upon compilation? (using --add-data option)

**Comment by darrencl** [comment]
Hi @forctis , thank you for such a quick reply!

To be honest, I am unsure which folder to add. From my understanding the `.exe` searches on this temporary folder (which was temporarily added when PyInstaller compiles/builds and it is is removed as I'm not in a compile/build process), and looks for `parsley_termactions.parsley` file. 

I tried looking which folder has `parsley_termactions.parsley` file and the first obvious thing to do is look into Parsley folder in site-package directory, but it's not there. So, I'm not sure which folder I should pass in `--add-data` option. 

Could you help?

```sh
darrencl@DESKTOP-9UML5S2 MINGW64 ~/Documents/mrspectroproc/dist (master)
$ ls ~/miniconda3/Lib/site-packages/Parsley-1.3.dist-info/
DESCRIPTION.rst  METADATA  REQUESTED  metadata.json
INSTALLER        RECORD    WHEEL      top_level.txt
```

**Comment by rokm** [comment]
Does adding `--collect-submodules ometa._generated --collect-submodules terml._generated` to your PyInstaller command help?

**Comment by darrencl** [comment]
@rokm Yes, it helped! Thank you so much.
