### ISSUE TITLE
pyinstaller package exe not working

### ISSUE THREAD

**Issue by shun-dgut** [pyinstaller/pyinstaller#6731]
enviroment : 
win10 
pyinstaller                       4.10
pyinstaller-hooks-contrib         2022.3

code
```
import clr
print("hello world")
```

cmd
```
python -m PyInstaller -F test.py

```
error message
```
testclr\dist>test.exe
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 36, in load
  File "pythonnet\__init__.py", line 20, in set_default_runtime
  File "clr_loader\__init__.py", line 55, in get_netfx
  File "clr_loader\netfx.py", line 10, in __init__
  File "clr_loader\netfx.py", line 35, in initialize
  File "clr_loader\ffi\__init__.py", line 51, in load_netfx
  File "cffi\api.py", line 150, in dlopen
  File "cffi\api.py", line 832, in _make_ffi_library
  File "cffi\api.py", line 827, in _load_backend_lib
OSError: cannot load library 'C:\Users\WUCHUS~1\AppData\Local\Temp\_MEI685482\clr_loader\ffi\dlls\amd64\ClrLoader.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\WUCHUS~1\\AppData\\Local\\Temp\\_MEI685482\\clr_loader\\ffi\\dlls\\amd64\\ClrLoader.dll'
[15328] Failed to execute script 'test' due to unhandled exception!
Exception ignored in: <function NetFx.__del__ at 0x0000021C6ABC1C10>
Traceback (most recent call last):
  File "clr_loader\netfx.py", line 26, in __del__
AttributeError: 'NetFx' object has no attribute '_domain
```

**Comment by rokm** [comment]
> `OSError: cannot load library 'C:\Users\WUCHUS~1\AppData\Local\Temp\_MEI685482\clr_loader\ffi\dlls\amd64\ClrLoader.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\WUCHUS~1\\AppData\\Local\\Temp\\_MEI685482\\clr_loader\\ffi\\dlls\\amd64\\ClrLoader.dll'`

You need to ensure that this DLL is collected. 

Probably the easiest way is to add `--collect-binaries clr_loader` to your pyinstaller command.

**Comment by bwoodsend** [comment]
See #6572.

**Comment by bwoodsend** [comment]
https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/406 (which I just released) will fix this globally.
