### ISSUE TITLE
i faced the same issue as in 6572 cannot import clrloader, the fix did not work 

### ISSUE THREAD

**Issue by ironmann250** [pyinstaller/pyinstaller#6739]
i faced the same issue, am running python 3.9.7, PyInstaller 4.10.
i added --collect-binaries clr_loader and still it did not work

**a minimal code to show the error**

```python
import toga
from toga.style import Pack
from toga.style.pack import COLUMN

class ChineseDictionary(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

def main():
    return ChineseDictionary('sample app', 'com.example.example')
if __name__ == '__main__':
    main().main_loop() `
```

**my stack trace is here**

```python
[29424] PyInstaller Bootloader 3.x
[29424] LOADER: executable is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\app_one_file.exe
[29424] LOADER: homepath is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file
[29424] LOADER: _MEIPASS2 is NULL
[29424] LOADER: archivename is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\app_one_file.exe
[29424] LOADER: Cookie found at offset 0x37E0EA
[29424] LOADER: No need to extract files to run; setting extractionpath to homepath
[29424] LOADER: SetDllDirectory(D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file)
[29424] LOADER: Already in the child - running user's code.
[29424] LOADER: Python library: D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\python39.dll
[29424] LOADER: Loaded functions from Python library.
[29424] LOADER: Manipulating environment (sys.path, sys.prefix)
[29424] LOADER: sys.prefix is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file
[29424] LOADER: Pre-init sys.path is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\base_library.zip;D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\lib-dynload;D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file
[29424] LOADER: Setting runtime options
[29424] LOADER: Initializing python
[29424] LOADER: Overriding Python's sys.path
[29424] LOADER: Post-init sys.path is D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\base_library.zip;D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\lib-dynload;D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file
[29424] LOADER: Setting sys.argv
[29424] LOADER: setting sys._MEIPASS
[29424] LOADER: importing modules from CArchive
[29424] LOADER: extracted struct
[29424] LOADER: running unmarshalled code object for struct...
[29424] LOADER: extracted pyimod01_os_path
[29424] LOADER: running unmarshalled code object for pyimod01_os_path...
[29424] LOADER: extracted pyimod02_archive
[29424] LOADER: running unmarshalled code object for pyimod02_archive...
[29424] LOADER: extracted pyimod03_importers
[29424] LOADER: running unmarshalled code object for pyimod03_importers...
[29424] LOADER: extracted pyimod04_ctypes
[29424] LOADER: running unmarshalled code object for pyimod04_ctypes...
[29424] LOADER: Installing PYZ archive with Python modules.
[29424] LOADER: PYZ archive: PYZ-00.pyz
[29424] LOADER: Running pyiboot01_bootstrap.py
[29424] LOADER: Running pyi_rth_subprocess.py
[29424] LOADER: Running pyi_rth_pkgutil.py
[29424] LOADER: Running pyi_rth_multiprocessing.py
[29424] LOADER: Running pyi_rth_inspect.py
[29424] LOADER: Running pyi_rth_pkgres.py
[29424] LOADER: Running pyi_rth_win32api.py
[29424] LOADER: Running pyi_rth_win32comgenpy.py
[29424] LOADER: Running app_one_file.py
Traceback (most recent call last):
  File "chinesedictionary\app_one_file.py", line 191, in <module>
  File "chinesedictionary\app_one_file.py", line 189, in main
  File "toga\app.py", line 272, in __init__
  File "toga\platform.py", line 53, in get_platform_factory
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\factory.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\app.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\keys.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\libs\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\libs\fonts.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "toga_winforms\libs\winforms.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 36, in load
  File "pythonnet\__init__.py", line 20, in set_default_runtime
  File "clr_loader\__init__.py", line 55, in get_netfx
  File "clr_loader\netfx.py", line 10, in __init__
  File "clr_loader\netfx.py", line 35, in initialize
  File "clr_loader\ffi\__init__.py", line 51, in load_netfx
  File "cffi\api.py", line 150, in dlopen
  File "cffi\api.py", line 832, in _make_ffi_library
  File "cffi\api.py", line 827, in _load_backend_lib
OSError: cannot load library 'D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\clr_loader\ffi\dlls\amd64\ClrLoader.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'D:\\school\\python and ai\\chinesedictionary\\src\\chinesedictionary\\dist\\app_one_file\\clr_loader\\ffi\\dlls\\amd64\\ClrLoader.dll'
[29424] Failed to execute script 'app_one_file' due to unhandled exception!
[29424] LOADER: OK.
[29424] LOADER: Manually flushing stdout and stderr
[29424] LOADER: Cleaning up Python interpreter.
Exception ignored in: <function NetFx.__del__ at 0x000001C4826F0940>
Traceback (most recent call last):
  File "clr_loader\netfx.py", line 26, in __del__
AttributeError: 'NetFx' object has no attribute '_domain' `
```
_Originally posted by @ironmann250 in https://github.com/pyinstaller/pyinstaller/issues/6572#issuecomment-1094291583_

**Comment by rokm** [comment]
This implies that `D:\school\python and ai\chinesedictionary\src\chinesedictionary\dist\app_one_file\clr_loader\ffi\dlls\amd64\ClrLoader.dll` does not exist (i.e., was not collected). Can you try rebuilding with `--clean --collect-binaries clr_loader`? 

If that makes no difference, can you try opening python console in your build environment, and check the output of the following snippet:
```python
from PyInstaller.utils.hooks import collect_dynamic_libs
collect_dynamic_libs('clr_loader')
```

**Comment by ironmann250** [comment]
**the output of that is:**

`[('C:\\ProgramData\\Miniconda3\\lib\\site-packages\\clr_loader\\ffi\\dlls\\amd64\\ClrLoader.dll', 'clr_loader\\ffi\\dlls\\amd64'), ('C:\\ProgramData\\Miniconda3\\lib\\site-packages\\clr_loader\\ffi\\dlls\\amd64\\NXPorts.Attributes.dll', 'clr_loader\\ffi\\dlls\\amd64'), ('C:\\ProgramData\\Miniconda3\\lib\\site-packages\\clr_loader\\ffi\\dlls\\x86\\ClrLoader.dll', 'clr_loader\\ffi\\dlls\\x86'), ('C:\\ProgramData\\Miniconda3\\lib\\site-packages\\clr_loader\\ffi\\dlls\\x86\\NXPorts.Attributes.dll', 'clr_loader\\ffi\\dlls\\x86')]`

**when it finished building it lacked python39.dll the stack trace is as follows:**

`[21896] PyInstaller Bootloader 3.x
[21896] LOADER: executable is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\app_one_file.exe
[21896] LOADER: homepath is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file
[21896] LOADER: _MEIPASS2 is NULL
[21896] LOADER: archivename is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\app_one_file.exe
[21896] LOADER: Cookie found at offset 0x37E0E6
[21896] LOADER: No need to extract files to run; setting extractionpath to homepath
[21896] LOADER: SetDllDirectory(D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file)
[21896] LOADER: Already in the child - running user's code.
[21896] LOADER: Python library: D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\python39.dll
Error loading Python DLL 'D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\python39.dll'.
LoadLibrary: The specified module could not be found.`

**later i added the DLL manually in that folder and the stack trace became this:**

`[22696] PyInstaller Bootloader 3.x
[22696] LOADER: executable is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\app_one_file.exe
[22696] LOADER: homepath is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file
[22696] LOADER: _MEIPASS2 is NULL
[22696] LOADER: archivename is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\app_one_file.exe
[22696] LOADER: Cookie found at offset 0x37E0E6
[22696] LOADER: No need to extract files to run; setting extractionpath to homepath
[22696] LOADER: SetDllDirectory(D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file)
[22696] LOADER: Already in the child - running user's code.
[22696] LOADER: Python library: D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\python39.dll
[22696] LOADER: Loaded functions from Python library.
[22696] LOADER: Manipulating environment (sys.path, sys.prefix)
[22696] LOADER: sys.prefix is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file
[22696] LOADER: Pre-init sys.path is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\base_library.zip;D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\lib-dynload;D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file
[22696] LOADER: Setting runtime options
[22696] LOADER: Initializing python
[22696] LOADER: Overriding Python's sys.path
[22696] LOADER: Post-init sys.path is D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\base_library.zip;D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file\lib-dynload;D:\school\python and ai\chinesedictionary\src\chinesedictionary\build\app_one_file
[22696] LOADER: Setting sys.argv
[22696] LOADER: setting sys._MEIPASS
[22696] LOADER: importing modules from CArchive
[22696] LOADER: extracted struct
[22696] LOADER: running unmarshalled code object for struct...
[22696] LOADER: extracted pyimod01_os_path
[22696] LOADER: running unmarshalled code object for pyimod01_os_path...
[22696] LOADER: extracted pyimod02_archive
[22696] LOADER: running unmarshalled code object for pyimod02_archive...
[22696] LOADER: extracted pyimod03_importers
[22696] LOADER: running unmarshalled code object for pyimod03_importers...
[22696] LOADER: extracted pyimod04_ctypes
[22696] LOADER: running unmarshalled code object for pyimod04_ctypes...
[22696] LOADER: Installing PYZ archive with Python modules.
[22696] LOADER: PYZ archive: PYZ-00.pyz
[22696] LOADER: Running pyiboot01_bootstrap.py
[22696] LOADER: Running pyi_rth_subprocess.py
[22696] LOADER: Running pyi_rth_pkgutil.py
[22696] LOADER: Running pyi_rth_multiprocessing.py
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'
[22696] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
[22696] LOADER: OK.
[22696] LOADER: Manually flushing stdout and stderr
[22696] LOADER: Cleaning up Python interpreter.`

**Comment by rokm** [comment]
> when it finished building it lacked python39.dll the stack trace is as follows:

If it lacked `python39.dll`, then you were trying to run incomplete bundle from the `build` directory instead of complete one from the `dist` directory. (And therefore adding `python39.dll` manually got you only as far as the next missing file). The final bundle is in `dist` directory, so use that.
