### ISSUE TITLE
Dot files break Collect in OSX

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#676]
**Original date**: 2013/02/27
**Original reporter**: *kevinlondon AND gmail DOT  COOM *

I'm running the latest Develop code as of today, 02/26/13, python 2.7.2, Django 1.4.3, and OSX 10.8.2. When I was ran Pyinstaller, it crashed a few times trying to copy a .DS_Store file. I put a check to see if the file started with a period and, if not, let it copy the file, which helped prevent the crash. I think there may be an issue with my particular version of Python's shutil but I am not sure.

Here is the error message:

```
Traceback (most recent call last):
  File "pyinstaller.py", line 83, in <module>
    main()
  File "pyinstaller.py", line 78, in main
    run_build(opts, spec_file)
  File "pyinstaller.py", line 42, in run_build
    PyInstaller.build.main(spec_file, **opts.__dict__)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller/PyInstaller/build.py", line 1672, in main
    build(specfile, buildpath)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller/PyInstaller/build.py", line 1629, in build
    execfile(spec)
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller/sentinel/sentinel.spec", line 22, in <module>
    name=os.path.join('dist', 'sentinel'))
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller/PyInstaller/build.py", line 1216, in __init__
    self.__postinit__()
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller/PyInstaller/build.py", line 305, in __postinit__
    self.assemble()
  File "/Users/kevinlondon/dropbox/programming/python/pyinstaller/PyInstaller/build.py", line 1249, in assemble
    shutil.copy2(fnm, tofnm)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 127, in copy2
    copyfile(src, dst)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 81, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/kevinlondon/dropbox/programming/python/django/sentinel/sentinel/.DS_Store'
```

I have submitted a pull request on Github.

**Comment by matysek** [comment]
Not much information to reproduce.
