### ISSUE TITLE
Stdnum library does not work

### ISSUE THREAD

**Issue by Jaime02** [pyinstaller/pyinstaller#6770]
## Description of the issue

Missing "iban.dat" file due to [stdnum ](https://pypi.org/project/python-stdnum/) module. I guess this is due to nobody has needed the stdnum module yet and pyinstaller doesn't know how to package it.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```pyinstaller 4.10```
* Version of Python: 3.10.4
* Platform: Windows 11
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No, I don't have any other OS.

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
# main.py
import stdnum
# This should be enough to trigger the import error
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "modules\__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "modules\ui_functions.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "aValidation.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "stdnum\iban.py", line 56, in <module>
  File "stdnum\numdb.py", line 166, in get
  File "pkg_resources\__init__.py", line 1136, in resource_stream
  File "pkg_resources\__init__.py", line 1385, in get_resource_stream
  File "pkg_resources\__init__.py", line 1388, in get_resource_string
  File "pkg_resources\__init__.py", line 1555, in _get
  File "PyInstaller\loader\pyimod03_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jaime\\AppData\\Local\\Temp\\_MEI211842\\stdnum\\iban.dat'
```

**Comment by bwoodsend** [comment]
Adding `--collect-data=stdnum` to your build command should do it.
