### ISSUE TITLE
dateutil.tz.win failed to scan during compilation ('This is a bug.  Please report it')

### ISSUE THREAD

**Issue by glewis-cs** [pyinstaller/pyinstaller#6809]
I'm trying to use PyInstall 5.0.1 to compile a script that uses the `python-dateutil` library (2.8.2) on a MacOS EC2 instance (Running Monterey 12.3.1 with Python 3.9.12 installed by default) and we keep getting the follwing exceptions:

```
8216 INFO: Loading module hook 'hook-distutils.py' from '/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
8242 INFO: Looking for ctypes DLLs
Traceback (most recent call last):
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 506, in assemble
    ctypes_binaries = scan_code_for_ctypes(co)
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/depend/utils.py", line 124, in scan_code_for_ctypes
    binaries = _resolveCtypesImports(binaries)
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/depend/utils.py", line 292, in _resolveCtypesImports
    if not include_library(cbin):
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/depend/dylib.py", line 320, in include_library
    if exclude_list.search(libname) and not include_list.search(libname):
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/depend/dylib.py", line 286, in search
    return util.in_system_path(libname)
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/macholib/util.py", line 179, in in_system_path
    fn = sdk_normalize(os.path.realpath(filename))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/posixpath.py", line 392, in realpath
    return abspath(path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/posixpath.py", line 379, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/private/tmp/xxxx/osx/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 845, in main
    build(specfile, distpath, workpath, clean_build)
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 767, in build
    exec(code, spec_namespace)
  File "./specs/xxxx.spec", line 7, in <module>
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 319, in __init__
    self.__postinit__()
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/private/tmp/xxxx/osx/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 509, in assemble
    raise RuntimeError(f"Failed to scan the module '{name}'. " f"This is a bug. Please report it.") from ex
RuntimeError: Failed to scan the module 'dateutil.tz.win'. This is a bug. Please report it.
```
Opening this issue based on the last error message, any help would be greatly appreciated.

**Comment by bwoodsend** [comment]
> cwd = os.getcwd()
> FileNotFoundError: [Errno 2] No such file or directory

Have you deleted the directory your terminal is open in or something?

**Comment by bwoodsend** [comment]
And is there a reason why you appear to have installed your virtual environment in a temporary folder?

**Comment by glewis-cs** [comment]
> Have you deleted the directory your terminal is open in or something?

Not that I'm aware of, I can try it in a different folder; but we haven't had to do that before, so it would be interesting to see the results.

> And is there a reason why you appear to have installed your virtual environment in a temporary folder?

We use PyInstaller in the context of a MacOS EC2 just to build a binary that's compatiable; I know this probably isn't super helpful, but our script has always worked before this, and the only thing I can think of is that something changed in PyInstaller that may have possibly caused it?

**Comment by rokm** [comment]
That error occurs while trying to resolve ctype-imported `user32.dll` in a Windows-specific codepath in `dateutil.tz.win` (because it has just a basename, the corresponding code eventually tries to resolve it to absolute path, leading to the failing `os.getcwd()` call). I cannot reproduce it locally, though:
```
8633 INFO: Loading module hook 'hook-distutils.py' from [...]/python3.9/site-packages/PyInstaller/hooks'...
8663 INFO: Looking for ctypes DLLs
8703 WARNING: Library user32 required via ctypes not found
8709 INFO: Analyzing run-time hooks ...
```

The only reason for `cwd = os.getcwd()` to raise `FileNotFoundError: [Errno 2] No such file or directory` I can think of is that the current working directory ended up deleted during the build (by some external actor). But it must have existed at the beginning of the build, because otherwise [this call](https://github.com/pyinstaller/pyinstaller/blob/0d9a1d3db898db2090499668cb69b74ace008634/PyInstaller/__init__.py#L52) would have failed as well...

What is your working directory when you run pyinstaller?
