### ISSUE TITLE
Project_folder path doesn't seem to be a valid path.

### ISSUE THREAD

**Issue by OlMi1** [pyinstaller/pyinstaller#6818]
This is the log:
```
G:\Systempfads\Desktop>pyinstaller --onefile bruter.py
95 INFO: PyInstaller: 5.0.1
95 INFO: Python: 3.9.1
96 INFO: Platform: Windows-10-10.0.19041-SP0
97 INFO: wrote G:\Systempfads\Desktop\bruter.spec
100 INFO: UPX is not available.
103 INFO: Extending PYTHONPATH with paths
['G:\\Systempfads\\Desktop']
Domain: com.deez.nuts
Traceback (most recent call last):
  File "g:\programs\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "g:\programs\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "G:\Programs\python\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "g:\programs\python\lib\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "g:\programs\python\lib\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "g:\programs\python\lib\site-packages\PyInstaller\building\build_main.py", line 845, in main
    build(specfile, distpath, workpath, clean_build)
  File "g:\programs\python\lib\site-packages\PyInstaller\building\build_main.py", line 767, in build
    exec(code, spec_namespace)
  File "G:\Systempfads\Desktop\bruter.spec", line 7, in <module>
    a = Analysis(
  File "g:\programs\python\lib\site-packages\PyInstaller\building\build_main.py", line 287, in __init__
    self.hookspath += discover_hook_directories()
  File "g:\programs\python\lib\site-packages\PyInstaller\isolated\_parent.py", line 269, in wrapped
    return call(function, *args, **kwargs)
  File "g:\programs\python\lib\site-packages\PyInstaller\isolated\_parent.py", line 238, in call
    return isolated.call(function, *args, **kwargs)
  File "g:\programs\python\lib\site-packages\PyInstaller\isolated\_parent.py", line 176, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to discover_hook_directories() failed with:
  File "g:\programs\python\lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
  File "g:\programs\python\lib\site-packages\PyInstaller\building\build_main.py", line 104, in discover_hook_directories
    import pkg_resources
  File "g:\programs\python\lib\site-packages\pkg_resources\__init__.py", line 83, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "g:\programs\python\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "g:\programs\python\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
    __import__(extant)
  File "g:\programs\python\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 83, in <module>
    import copy
  File "G:\Systempfads\Desktop\copy.py", line 9, in <module>
    save_website(
  File "g:\programs\python\lib\site-packages\pywebcopy\__init__.py", line 157, in save_website
    config = get_config(url, project_folder, project_name, bypass_robots, debug, delay, threaded)
  File "g:\programs\python\lib\site-packages\pywebcopy\configs.py", line 283, in get_config
    ans.setup_config(
  File "g:\programs\python\lib\site-packages\pywebcopy\configs.py", line 211, in setup_config
    self.setup_paths(project_folder, project_name)
  File "g:\programs\python\lib\site-packages\pywebcopy\configs.py", line 177, in setup_paths
    raise ConfigError("Project_folder path doesn't seem to be a valid path.")
pywebcopy.configs.ConfigError: Project_folder path doesn't seem to be a valid path.
```
This is my command: `pyinstaller --onefile bruter.py`

I can't even find the snippet in the code. What's going wrong?

**Comment by rokm** [comment]
> `G:\Systempfads\Desktop\copy.py`

This `copy.py` script is shadowing the module with same name from the python standard library, leading to undefined behavior of modules that make use of the standard `copy` module.
