### ISSUE TITLE
QDesktopServices.openUrl() fails to open local PDF files in Ubuntu

### ISSUE THREAD

**Issue by EfremBraun** [pyinstaller/pyinstaller#6825]
## Description of the issue
I'm using PyInstaller to bundle a PySide6 application. In my application, I use QDesktopServices.openUrl (https://doc.qt.io/qtforpython/PySide6/QtGui/QDesktopServices.html#PySide6.QtGui.PySide6.QtGui.QDesktopServices.openUrl) to open a PDF version of the user manual when the user clicks on the Help menu.

This works fine when I run the PySide6 application from terminal, whether it's on my Mac, Windows, or Ubuntu machines; it opens the manual in Preview, Microsoft Edge, and Evince, respectively. However, when I use PyInstaller to bundle the application via `pyinstaller MainWindow.py`, I get the following error on Ubuntu when I try to open the PDF:
`evince: error while loading shared libraries: libgtk-3.so.0: failed to map segment from shared object`

If I remove libgtk-3.so from the application bundle, I get the error:
`evince: error while loading shared libraries: libpangocairo-1.0.so.0: failed to map segment from shared object`
And this error continues with a different library if I then remove [libpangocairo-1.0.so](http://libpangocairo-1.0.so/). I tried doing that through about 20 different libraries before I stopped trying to see when the issue would end.

The workaround given in https://github.com/pyinstaller/pyinstaller/issues/3668#issuecomment-428951753 works, so I've been testing whether the user is running Linux, and if so, I use that workaround; otherwise, I use the regular QDesktopServices.openUrl() function. Nonetheless, it's annoying having to use that workaround.

I was hoping that the fix given to https://github.com/pyinstaller/pyinstaller/issues/3668 would solve this issue, but it appears that it has not.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.1```
* Version of Python: 3.9
* Platform: Ubuntu 20.04.4
* How you installed Python: Anaconda
* Did you also try this on another platform? Does it work there? : Works on both Mac and Windows. Only fails on Ubuntu (didn't test other Linux distros)

### A minimal example program which shows the error

```
import sys
from os.path import dirname, join, realpath, abspath, isfile
from PySide6.QtWidgets import QApplication, QMainWindow, QPushButton
from PySide6.QtGui import QDesktopServices
from PySide6.QtCore import QUrl

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("My App")
        button = QPushButton("Press Me!")
        button.setCheckable(True)
        button.clicked.connect(self.the_button_was_clicked)
        self.setCentralWidget(button)

    def the_button_was_clicked(self):
        file_path = "dummy.pdf"
        file_path_bin = join(dirname(sys.executable), file_path)  # PyInstaller
        file_path_py = abspath(join(dirname(realpath(__file__)), file_path))  # Python from console
        if isfile(file_path_bin):
            filename = file_path_bin
        else:
            filename = file_path_py
        QDesktopServices.openUrl(QUrl.fromLocalFile(filename))

app = QApplication(sys.argv)
window = MainWindow()
window.show()
app.exec()
```

Any `dummy.pdf` files works, e.g., https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf.

### Stacktrace / full error message

When I run the application via `python app.py`, clicking the button opens the dummy.pdf file.

When I run the application via `pyinstaller --add-data="dummy.pdf:." app.py`, and then `.dist/app/app`, upon clicking the button I get the error message:
```
evince: error while loading shared libraries: libgtk-3.so.0: failed to map segment from shared object
```

**Comment by bwoodsend** [comment]
I imagine that this is the same issue as #6334. Are you able to get anything to behave using something like https://github.com/pyinstaller/pyinstaller/issues/6334#issuecomment-959763644 replacing `webbrowser.open()` with `QDesktopServices.openUrl(QUrl.fromLocalFile(filename))`?

**Comment by EfremBraun** [comment]
Inserting at the start of the_button_was_clicked() the lines:
```
        lp_key = "LD_LIBRARY_PATH"
        print(f"lp: {os.environ.get(lp_key)}")
        lp_orig = os.environ.get(f"{lp_key}_ORIG")
        print(f"lp_orig: {lp_orig}")
        if lp_orig is not None:
            os.environ[lp_key] = lp_orig
        else:
            del os.environ[lp_key]
```
just gives me the error:
```
lp: None
lp_orig: None
Traceback (most recent call last):
  File "/home/edbraun/app/app.py", line 30, in the_button_was_clicked
    del os.environ[lp_key]
  File "/home/edbraun/anaconda3/envs/myenv/lib/python3.9/os.py", line 695, in __delitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'
```
