### ISSUE TITLE
ModuleNotFoundError: No module named 'yt_dlp.compat._legacy'

### ISSUE THREAD

**Issue by aliencaocao** [pyinstaller/pyinstaller#6838]
Unable to launch compiled exe using [yt_dlp ](https://github.com/yt-dlp/yt-dlp) library. If I run the python .py file, works fine.
Was able to do it in PyInstaller 5.0.

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import yt_dlp
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp\__init__.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp\compat\__init__.py", line 14, in <module>
  File "yt_dlp\compat\compat_utils.py", line 36, in passthrough_module
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'yt_dlp.compat._legacy'
[22836] Failed to execute script 'main' due to unhandled exception!
```

Code:
```
import yt_dlp
```

Compiled with `pyinstaller --log-level DEBUG -F --add-data "libopus-0.dll;." --distpath ./ --clean --upx-dir upx/ --noconfirm main.py`

**Comment by aliencaocao** [comment]
Adding `--hidden-import=yt_dlp.compat._legacy` solved the issue. I guess it has to do with yt_dlp's update. But I think it is worth to update the hooks for yt_dlp to handle this.

**Comment by jlw4049** [comment]
On the latest pyinstaller do we still need to  add `--hidden-import=yt_dlp.compat._legacy`?
Is this an issue with yt-dlp or pyinstaller?

**Comment by aliencaocao** [comment]
Yes im using the latest version and I still need to add

**Comment by jlw4049** [comment]
Thanks for the response. Is this something that should always be added going forward?

**Comment by aliencaocao** [comment]
this one you got to ask the devs here. Maybe I should reopen this and let them respond.

**Comment by jlw4049** [comment]
Thank you! I'll be awaiting their response.
