### ISSUE TITLE
AccessViolationException when importing clr

### ISSUE THREAD

**Issue by wlongphilips** [pyinstaller/pyinstaller#6882]
I am getting the exact same error as in this previously reported [issue](https://github.com/pyinstaller/pyinstaller/issues/4953) and cannot for the life of me figure it out. I have a very simple clrpyinstaller.py script that runs successfully in Python: 
```
import clr
print("success")
```

But running pyinstaller clrpyinstaller.py and opening the output .exe I get the following error:
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyObject_GetAttrString(IntPtr pointer, String name)
   at Python.Runtime.Runtime.InitializePlatformData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.PyInit_clr()
```

My specs:
```
164 INFO: PyInstaller: 5.1
164 INFO: Python: 3.8.0
166 INFO: Platform: Windows-10-10.0.19041-SP0
```

**Comment by rokm** [comment]
Confirmed. This looks like a regression between PyInstaller 5.0 and 5.1, and is almost certainly related to #6798. 

As a work-around, you can add `--hidden-import doctest` to your PyInstaller command. 

For the proper fix, I'll update the `clr` hook to include the missing modules that were previously collected due to doctest being collected - once I figure out which ones are required.

**Comment by rokm** [comment]
Looks like `platform` is the missing module; so instead of `--hidden-import doctest`, `--hidden-import platform` should also do the trick.
