### ISSUE TITLE
Pyinstaller does not work with the great expectations library

### ISSUE THREAD

**Issue by GeorgeAzaru** [pyinstaller/pyinstaller#6883]
When trying to convert a python program that uses the great expectations library I receive the error:
"ValueError: The 'great_expectations' package was not installed in a way that PackageLoader understands."

Full traceback:
Traceback (most recent call last):
  File "flask\app.py", line 2077, in wsgi_app
  File "flask\app.py", line 1525, in full_dispatch_request
  File "flask\app.py", line 1523, in full_dispatch_request
  File "flask\app.py", line 1509, in dispatch_request
  File "dash\dash.py", line 1468, in dispatch
  File "dash\_callback.py", line 151, in add_context
  File "dash_app.py", line 294, in update_output
  File "great_expectations\core\usage_statistics\usage_statistics.py", line 289, in usage_statistics_wrapped_method
  File "great_expectations\data_context\data_context\base_data_context.py", line 3301, in run_checkpoint
  File "great_expectations\checkpoint\checkpoint.py", line 625, in run_with_runtime_args
  File "great_expectations\core\usage_statistics\usage_statistics.py", line 289, in usage_statistics_wrapped_method
  File "great_expectations\checkpoint\checkpoint.py", line 161, in run
  File "great_expectations\checkpoint\checkpoint.py", line 359, in _run_validation
  File "great_expectations\core\async_executor.py", line 102, in submit
  File "great_expectations\validation_operators\validation_operators.py", line 385, in run
  File "great_expectations\validation_operators\validation_operators.py", line 466, in _run_actions
  File "great_expectations\validation_operators\validation_operators.py", line 447, in _run_actions
  File "great_expectations\checkpoint\actions.py", line 72, in run
  File "great_expectations\checkpoint\actions.py", line 1067, in _run
  File "great_expectations\core\usage_statistics\usage_statistics.py", line 289, in usage_statistics_wrapped_method
  File "great_expectations\data_context\data_context\base_data_context.py", line 2653, in build_data_docs
  File "great_expectations\data_context\util.py", line 117, in instantiate_class_from_config
  File "great_expectations\render\renderer\site_builder.py", line 226, in __init__
  File "great_expectations\data_context\util.py", line 117, in instantiate_class_from_config
  File "great_expectations\render\renderer\site_builder.py", line 390, in __init__
  File "great_expectations\data_context\util.py", line 117, in instantiate_class_from_config
  File "great_expectations\render\view\view.py", line 62, in __init__
  File "jinja2\loaders.py", line 319, in __init__
ValueError: The 'great_expectations' package was not installed in a way that PackageLoader understands.

I would like pyinstaller to work with the GE library because GE has a great future and is starting to gain traction.
https://greatexpectations.io/

**Comment by rokm** [comment]
> I would like pyinstaller to work with the GE library because GE has a great future and is starting to gain traction.

Once you cross into the PyInstaller territory, you ought to keep your expectations low - you can't expect things to just work for any random package out there without some additional tweaks...

> File "great_expectations\data_context\util.py", line 117, in instantiate_class_from_config
> File "great_expectations\render\view\view.py", line 62, in **init**
> File "jinja2\loaders.py", line 319, in **init**

If you check the [offending code lines](https://github.com/great-expectations/great_expectations/blob/a57dc70f1fb6f613de78de2eb28010078e0378f9/great_expectations/render/view/view.py#L62), you'll see that it tries to load bundled data (templates and styles), so you'll need to ensure those are collected.

Either add [`--collect-data great_expectations`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-data) to your PyInstaller command, or write a custom [hook](https://pyinstaller.org/en/stable/hooks.html) for `great_expectations` that calls [`collect_data_files`](https://pyinstaller.org/en/stable/hooks.html#PyInstaller.utils.hooks.collect_data_files).

**Comment by GeorgeAzaru** [comment]
Thank you for saving me from days of research.
