### ISSUE TITLE
Executable fails on import setuptools

### ISSUE THREAD

**Issue by dennisvang** [pyinstaller/pyinstaller#6911]
## Description of the issue

PyInstaller executable fails with `AssertionError: ...\distutils\core.pyc` when trying to `import setuptools`.

The `setuptools` override of `distutils` does not seem to be loaded, see [ensure_local_distutils][3] in setuptools source.

Same as [setuptools issue 3089][1], but, as far as I know, the issue only arises when running as a PyInstaller executable.

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.1
* Version of Python: 3.8.13
* Platform: Windows 10
* How you installed Python: conda
* Did you also try this on another platform? Does it work there? 

  did not try

* try the latest development version

  done, see below

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ x ] start with clean installation
  * [ x ] use the latest development version
  * [ x ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ x ] Package your program in **--onedir mode**
  * [ x ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ x ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Similar to what is described in this [comment to the setuptools issue][2].

Create `repro.py` file with content:

```
import setuptools
``` 

Then on the command line:
```
conda create -n temp python=3.8
conda activate temp
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
pyinstaller --onedir --debug imports --noupx repro.py
dist\repro\repro.exe
```

Using conda here for convenience, but issue also arises using a normal python installation.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "repro.py", line 1, in <module>
    import setuptools
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "setuptools\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "_distutils_hack\override.py", line 1, in <module>
  File "_distutils_hack\__init__.py", line 77, in do_override
  File "_distutils_hack\__init__.py", line 64, in ensure_local_distutils
AssertionError: C:\Users\me\Desktop\temp\setuptools-issue-3089\dist\repro\distutils\core.pyc
[6064] Failed to execute script 'repro' due to unhandled exception!
```

[1]: https://github.com/pypa/setuptools/issues/3089
[2]: https://github.com/pypa/setuptools/issues/3089#issuecomment-1032305835
[3]: https://github.com/pypa/setuptools/blob/main/_distutils_hack/__init__.py#L51-L65

**Comment by rokm** [comment]
Yes, we currently do not properly support `setuptools`-provided `distutils` in the frozen application (the custom loader would have to be installed via runtime hook, but if I remember correctly, we do not collect the required modules, either).

The work-around is to force the use of stdlib distutils by setting `SETUPTOOLS_USE_DISTUTILS` environment variable before importing `setuptools`.

You can also try #6866 if you are feeling brave...

**Comment by dennisvang** [comment]
@rokm Thanks, that clears things up. 

The `SETUPTOOLS_USE_DISTUTILS` workaround does the job, for now.

Cmd:
```
set SETUPTOOLS_USE_DISTUTILS=stdlib
```
Powershell:
```
$Env:SETUPTOOLS_USE_DISTUTILS = 'stdlib'
```

Actually any value other than `local` should work, judging from [_distutils_hack][1] (also see e.g. [setuptools tests][2]).

[1]: https://github.com/pypa/setuptools/blob/3d5588d4b3b948da24e93405b253c6de90eccd55/_distutils_hack/__init__.py#L48
[2]: https://github.com/pypa/setuptools/blob/270904f630e9f2142f47d0f701bd225ad149cc00/setuptools/tests/test_distutils_adoption.py#L52

**Comment by beniroquai** [comment]
@dennisvang thanks for the solution. Is there any work around that is "permanent" to ship the executable without always defining the system variable?

**Comment by rokm** [comment]
> @dennisvang thanks for the solution. Is there any work around that is "permanent" to ship the executable without always defining the system variable?

Downgrade your `setuptools` to < 60.0.

Or use PyInstaller 5.4.1 that has #7075.
