### ISSUE TITLE
Executable does not run; dgl library problem

### ISSUE THREAD

**Issue by paddy-r** [pyinstaller/pyinstaller#6916]
I have a larger project that I'm trying to package with ```pyinstaller```. However, the executable fails and ```dgl``` seems to be causing an issue. I created a minimal bit of code, which runs fine as a script (n.b. line numbers are increased by 6 in the traceback as I removed some lines, so ```line 7``` corresponds to ```import dgl```):

```
import dgl
# import torch
import time
print('Hiyer!')
time.sleep(10)
```

However, when I run the executable, I get the following, which I captured via ```tester.exe > tester.txt && type tester.txt```:

```
Traceback (most recent call last):
  File "tester.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dgl\__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dgl\backend\__init__.py", line 109, in <module>
  File "dgl\backend\__init__.py", line 43, in load_backend
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dgl\_ffi\base.py", line 45, in <module>
  File "dgl\_ffi\base.py", line 34, in _load_lib
  File "dgl\_ffi\libinfo.py", line 83, in find_lib_path
RuntimeError: Cannot find the files.
List of candidates:
C:\***\dist\tester\dgl\libdgl.dll
C:\***\dist\build\libdgl.dll
C:\***\dist\build\Release\libdgl.dll
C:\***\dist\lib\libdgl.dll
C:\***\libdgl.dll
C:\***\dist\tester\dgl\dgl.dll
C:\***\dist\build\dgl.dll
C:\***\dist\build\Release\dgl.dll
C:\***\dist\lib\dgl.dll
C:\***\dgl.dll
[46236] Failed to execute script 'tester' due to unhandled exception!
```

I'm stumped! Can you help? Environment details below.

```
altgraph                  0.17.2                   pypi_0    pypi
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
certifi                   2022.6.15        py39hcbf5309_0    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.2           py39h7bc7c5c_0    conda-forge
dgl                       0.8.1                    py39_0    dglteam
future                    0.18.2                   pypi_0    pypi
idna                      3.3                pyhd8ed1ab_0    conda-forge
libblas                   3.9.0           5_hd5c7e75_netlib    conda-forge
libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numpy                     1.23.0           py39h1a62c8c_0    conda-forge
openssl                   1.1.1p               h8ffe710_0    conda-forge
pefile                    2022.5.30                pypi_0    pypi
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyinstaller               5.1                      pypi_0    pypi
pyinstaller-hooks-contrib 2022.7                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hcbf5309_5    conda-forge
python                    3.9.0           h7840368_5_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pywin32-ctypes            0.2.0                    pypi_0    pypi
requests                  2.28.0             pyhd8ed1ab_1    conda-forge
scipy                     1.8.1            py39hc0c34ad_0    conda-forge
setuptools                62.6.0           py39hcbf5309_0    conda-forge
sqlite                    3.39.0               h8ffe710_0    conda-forge
torch                     1.12.0                   pypi_0    pypi
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.2.0                    pypi_0    pypi
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
```

**Comment by rokm** [comment]
Well, PyInstaller is not aware of shared libraries that are loaded dynamically at runtime, so you'll need to ensure that `dgl.dll` is collected. The easiest way is to add `--collect-binaries dgl` to your pyinstaller command.

Similarly, PyInstaller is also not aware of python modules that are lazily loaded, so if you encounter missing module errors at runtime, you will need to add the missing modules to hidden imports to ensure they are collected.

For example, a basic `import dgl` program seems to require the following switches to collect everything:
```
pyinstaller --clean --noconfirm test_program.py --collect-binaries dgl --hiddenimport dgl.backend.pytorch --hiddenimport dgl.distributed.nn.pytorch --hiddenimport dgl.distributed.optim.pytorch --hiddenimport dgl.optim.pytorch
```
(that's assuming you're using `pytorch` backend, based on the commented import in your example code snippet). Usually I'd say to use `--collect-submodules dgl` instead of individual `--hiddenimport` switches, but it seems PyInstaller cannot fully walk that package...

**Comment by paddy-r** [comment]
@rokm Thanks so much for getting back so quickly. Your suggestion has indeed solved the problem. Could you explain how you determined that ```dgl``` requires those specific switches?
