### ISSUE TITLE
Executable ImportError; grakel problem

### ISSUE THREAD

**Issue by paddy-r** [pyinstaller/pyinstaller#6919]
I have an issue related ```grakel```, output is below. Similar script to #6916, also below. Apologies for two issues in rapid succession.

```
# import dgl
import grakel
# import torch
import time
print('Hiyer!')
time.sleep(10)
```

```
Traceback (most recent call last):
  File "tester.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grakel\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grakel\graph_kernels.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grakel\kernels\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grakel\kernels\graphlet_sampling.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grakel\kernels\_isomorphism\__init__.py", line 7, in <module>
  File "grakel\kernels\_isomorphism\bliss.pyx", line 12, in init grakel.kernels._isomorphism.bliss
ImportError: cannot import name intpybliss
[63476] Failed to execute script 'tester' due to unhandled exception!
```

I added some switches (see below) but to no avail.

```
pyinstaller --clean tester.py --collect-binaries dgl --hiddenimport dgl.backend.pytorch --hiddenimport dgl.distributed.nn.pytorch --hiddenimport dgl.distributed.optim.pytorch --hiddenimport dgl.optim.pytorch --hidden-import grakel --collect-binaries grakel
```

Slightly different environment to #6916 (added ```grakel``` and dependencies).

```
altgraph                  0.17.2                   pypi_0    pypi
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
certifi                   2022.6.15        py39hcbf5309_0    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.2           py39h7bc7c5c_0    conda-forge
dgl                       0.8.1                    py39_0    dglteam
future                    0.18.2                   pypi_0    pypi
idna                      3.3                pyhd8ed1ab_0    conda-forge
libblas                   3.9.0           5_hd5c7e75_netlib    conda-forge
libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numpy                     1.23.0           py39h1a62c8c_0    conda-forge
openssl                   1.1.1p               h8ffe710_0    conda-forge
pefile                    2022.5.30                pypi_0    pypi
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyinstaller               5.1                      pypi_0    pypi
pyinstaller-hooks-contrib 2022.7                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hcbf5309_5    conda-forge
python                    3.9.0           h7840368_5_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pywin32-ctypes            0.2.0                    pypi_0    pypi
requests                  2.28.0             pyhd8ed1ab_1    conda-forge
scipy                     1.8.1            py39hc0c34ad_0    conda-forge
setuptools                62.6.0           py39hcbf5309_0    conda-forge
sqlite                    3.39.0               h8ffe710_0    conda-forge
torch                     1.12.0                   pypi_0    pypi
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.2.0                    pypi_0    pypi
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
```

**Comment by rokm** [comment]
> Traceback (most recent call last):
>   File "tester.py", line 8, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "grakel\__init__.py", line 6, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "grakel\graph_kernels.py", line 13, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "grakel\kernels\__init__.py", line 6, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "grakel\kernels\graphlet_sampling.py", line 18, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "grakel\kernels\_isomorphism\__init__.py", line 7, in <module>
>   File "grakel\kernels\_isomorphism\bliss.pyx", line 12, in init grakel.kernels._isomorphism.bliss
> ImportError: cannot import name intpybliss
> [63476] Failed to execute script 'tester' due to unhandled exception!


The top-level `grakel` package is not missing, nor are the shared libraries from the package (there aren't any), so adding

> `--hidden-import grakel --collect-binaries grakel`

predictably has no effect.

What is missing, as per error message, is `intpybliss` module, which is actually `grakel.kernels._isomorphism.intpybliss`.

So what you need to add is `--hidden-import grakel.kernels._isomorphism.intpybliss`.

PS: if you get missing `sklearn` modules errors afterwards, you will need to update `pyinstaller-hooks-contrib` to latest development version (`pip install git+https://github.com/pyinstaller/pyinstaller-hooks-contrib.git`) that added support for `scikit-learn` 1.0.x and 1.1.x in pyinstaller/pyinstaller-hooks-contrib#457.

**Comment by paddy-r** [comment]
Thanks @rokm, the ```grakel``` issue was solved with ```--hidden-import grakel.kernels._isomorphism.intpybliss```, and I did indeed then get this error: ```ModuleNotFoundError: No module named 'sklearn.utils._typedefs'```.

After installing the development version as you suggested (```Successfully installed pyinstaller-hooks-contrib-2022.8```), the executable runs without errors. Thanks again!
