### ISSUE TITLE
Improve distutils hook

### ISSUE THREAD

**Issue by ofek** [pyinstaller/pyinstaller#6928]
## Description of the issue

Hook needs more hidden imports https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-distutils.py

It dynamically imports https://github.com/python/cpython/tree/3.10/Lib/distutils/command

https://github.com/python/cpython/blob/3.10/Lib/distutils/dist.py#L823-L829

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.1```
* Version of Python: 3.8.1
* Platform: Windows 10
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?: No

### A minimal example program which shows the error

```
git clone https://github.com/pypa/hatch
cd hatch/src
pyinstaller --name hatch ./hatch/__main__.py
./dist/hatch/hatch.exe env create
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "hatch\__main__.py", line 6, in <module>
  File "hatch\cli\__init__.py", line 202, in main
  File "click\core.py", line 1128, in __call__
  File "click\core.py", line 1053, in main
  File "click\core.py", line 1659, in invoke
  File "click\core.py", line 1659, in invoke
  File "click\core.py", line 1395, in invoke
  File "click\core.py", line 754, in invoke
  File "click\decorators.py", line 38, in new_func
  File "hatch\cli\env\create.py", line 36, in create
  File "hatch\cli\application.py", line 72, in prepare_environment
  File "hatch\env\virtual.py", line 50, in create
  File "hatch\venv\core.py", line 47, in create
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "virtualenv\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "virtualenv\run\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "virtualenv\run\plugin\creators.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "virtualenv\create\via_global_ref\builtin\builtin_way.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "virtualenv\create\creator.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "virtualenv\discovery\cached_py_info.py", line 29, in <module>
  File "virtualenv\discovery\py_info.py", line 90, in __init__
  File "virtualenv\discovery\py_info.py", line 165, in _distutils_install
  File "distutils\command\install.py", line 366, in finalize_options
  File "distutils\cmd.py", line 286, in set_undefined_options
  File "distutils\dist.py", line 857, in get_command_obj
  File "distutils\dist.py", line 843, in get_command_class
distutils.errors.DistutilsModuleError: invalid command 'build'
[43672] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
Realistically, I don't think that there is any chance of Python build tools passing through PyInstaller - in particular ones that build virtual environments since PyInstaller does not bundle Python's main entrypoint making every every shim entrypoint installed into `env/bin` invalid.

I'm not super opposed to fixing that missing import, but if you're trying to do what I think you're trying to do then I'd rather turn you away now. It's not going to work!

**Comment by ofek** [comment]
Ah bummer, thanks for explaining though!
