### ISSUE TITLE
Tkcode isn't imported

### ISSUE THREAD

**Issue by Moosems** [pyinstaller/pyinstaller#6939]
## Description of the issue

When a windowed app tis run hat imports tkcode and uses the CodeEditor module the app breaks as tkcode isn't imported.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.2```
* Version of Python: 3.10.4
* Platform: OS X
* How you installed Python: python.org/downloads
* Did you also try this on another platform? No. I don't own any other computers to test from

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Prerequisite: `pip install tkcode`

```python
from tkcode import CodeEditor
from tkinter import Tk
root = Tk()
CodeEditor(root).pack()
root.mainloop()
```

Packaging: `pyinstaller file.py --windowed`

### Stacktrace / full error message

```
/Users/Moosems/Desktop/DIP-dev/dist/DIP.app/Contents/MacOS/DIP ; exit;
MBP:~ Moosems$ /Users/Moosems/Desktop/DIP-dev/dist/DIP.app/Contents/MacOS/DIP ; exit;
Traceback (most recent call last):
  File "DIP.py", line 57, in <module>
  File "DIP.py", line 53, in create_application
  File "DIP.py", line 34, in __init__
  File "LangEditors.py", line 144, in __init__
  File "LangEditors.py", line 25, in __init__
  File "tkcode/codeeditor.py", line 23, in __init__
  File "tkcode/codebox.py", line 94, in __init__
  File "tkcode/codebox.py", line 263, in update_highlighter
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Moosems/Desktop/DIP-dev/dist/DIP.app/Contents/MacOS/tkcode/schemes'
[4690] Failed to execute script 'DIP' due to unhandled exception: [Errno 2] No such file or directory: '/Users/Moosems/Desktop/DIP-dev/dist/DIP.app/Contents/MacOS/tkcode/schemes'
[4690] Traceback:
Traceback (most recent call last):
  File "DIP.py", line 57, in <module>
  File "DIP.py", line 53, in create_application
  File "DIP.py", line 34, in __init__
  File "LangEditors.py", line 144, in __init__
  File "LangEditors.py", line 25, in __init__
  File "tkcode/codeeditor.py", line 23, in __init__
  File "tkcode/codebox.py", line 94, in __init__
  File "tkcode/codebox.py", line 263, in update_highlighter
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Moosems/Desktop/DIP-dev/dist/DIP.app/Contents/MacOS/tkcode/schemes'

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
Try:
```
pyinstaller --collect-data=tkcode.schemes --windowed file.py
```

**Comment by Moosems** [comment]
@bwoodsend That worked
