### ISSUE TITLE
Pyinstaller Executable says module not found.

### ISSUE THREAD

**Issue by hakunaMatataHub** [pyinstaller/pyinstaller#6949]
### Discussed in https://github.com/orgs/pyinstaller/discussions/6948

<div type='discussions-op-text'>

<sup>Originally posted by **hakunaMatataHub** July 15, 2022</sup>
I have a python script for which I want to create execuable binaries using pyinstaller. It imports a packgae called 'rclpy'. I am able to run the script using python3 'script.py' but when I create a binary using pyinstaller it says modeule not found.

While running pyinstaller it does not show any errors.

Here is the error :

Traceback (most recent call last):
  File "operator_dashboard.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "rclpy/node.py", line 41, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "rclpy/client.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "rclpy/impl/implementation_singleton.py", line 31, in <module>
  File "rclpy/impl/__init__.py", line 28, in _import
  File "importlib/__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'rclpy._rclpy'
The C extension '/home/kewal/mowito_ws/arm_ws/src/order_control/scripts/output/operator_dashboard/rclpy/_rclpy.cpython-38-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions
[166554] Failed to execute script 'operator_dashboard' due to unhandled exception!

There is no directory created for rclpy inside dist either. I am able to locate the pyhton package at /opt/ros/foxy/lib/python3.8/site-packages in my pc.

Please help. Also if I remove all dependecy from this particular package it just works fine.</div>

**Comment by rokm** [comment]
Please don't open duplicated issues/discussions.
