### ISSUE TITLE
\torch\lib\shm.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by emoto-yasushi** [pyinstaller/pyinstaller#6960]
I was able to create an exe file using Pyinstaller.
However, when I run the exe file, I get the following error

```
Traceback (most recent call last):
  File "MyApp.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "ifacialmocap_puppeteer.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "load_poser.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\__init__.py", line 140, in <module>
    raise err
OSError: [WinError 126] The specified module cannot be found. Error loading "C:\Users\username\Documents\hold\MyApp-main\dist\MyApp\torch\lib\shm.dll" or one of its dependencies.

```

When I run the `"python MyApp.py"` before making the exe file, there is no error and my app works.
Is this due to the fact that I am using PyTorch?

[My environment]
Python version 3.8
Windows11
Anaconda Navigator 2.2.0
conda
Pyinstaller version 4.8

**Comment by rokm** [comment]
>  Is this due to the fact that I am using PyTorch?

Due to the limited support for conda & torch combination, some DLL probably did not get collected (I think last time I saw a similar problem, it was `uv.dll`). Use [Dependency walker](https://www.dependencywalker.com/) (or an equivalent tool) to check what dependency of `MyApp\torch\lib\shm.dll` is missing, and then ensure it is collected.

**Comment by yiyingsheng07** [comment]
> 

Hi, I got this too. Did you solve this problem?

**Comment by VERISBABY** [comment]
I ran .exe file and I got the same error but is " `...lib\torch_cpu.dll"` or one of its dependencies."
