### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdeploy.mmcv'

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [pyinstaller/pyinstaller#6982]
When I run the packaged python file on the ubuntu system, the following problem occurs, I need your help, thank you.

(mmdeploy) zhang@zhang-QiTianM540-A739:/media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx/dist$ ./trans_segmask3onnx_exe3
[12940] WARNING: file already exists but should not: /tmp/_MEImLB5ej/torch/_C.cpython-39-x86_64-linux-gnu.so
[12940] WARNING: file already exists but should not: /tmp/_MEImLB5ej/torch/_dl.cpython-39-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "trans_segmask3onnx_exe3.py", line 9, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "mmdeploy/__init__.py", line 14, in <module>
  File "importlib/__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'mmdeploy.mmcv'
[12941] Failed to execute script 'trans_segmask3onnx_exe3' due to unhandled exception!

**Comment by rokm** [comment]
The code in `mmdeploy` is performing indirect imports, so you need to add those modules to hiddenimports. In this case, add `--hiddenimport mmdeploy.mmcv` to your PyInstaller command. If there are many such indirectly imported modules in that package, use `--collect-submodules mmdeploy` instead.

**Comment by rokm** [comment]
> If there are many such indirectly imported modules in that package, use `--collect-submodules mmdeploy` instead.

Or perhaps avoid using `--collect-submodules`, since the package seems to have many backends and you probably don't want to collect them all...
