### ISSUE TITLE
"IndexError: tuple index out of range" when importing the library beautifulsoup4 on MacOs

### ISSUE THREAD

**Issue by kanewi11** [pyinstaller/pyinstaller#6990]
INFO: PyInstaller: 5.2
INFO: Python: 3.10.0

When I import bs4 into any of the projects, pyinstaller throws this out:

```
2855 INFO: Analyzing hidden import 'bs4'
Traceback (most recent call last):
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "main.spec", line 7, in <module>
    a = Analysis(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 319, in __init__
    self.__postinit__()
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 484, in assemble
    self.graph.add_hiddenimports(self.hiddenimports)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 632, in add_hiddenimports
    nodes = self.import_hook(modnm)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2061, in _safe_import_module
    n = self._scan_code(module, co, co_ast)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2645, in _scan_code
    self._scan_bytecode(
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2749, in _scan_bytecode
    for inst in util.iterate_instructions(module_code_object):
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/util.py", line 147, in iterate_instructions
    yield from iterate_instructions(constant)
  File "/Users/nikita/PycharmProjects/Kwork_edit_parser/venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/util.py", line 139, in iterate_instructions
    yield from get_instructions(code_object)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/dis.py", line 338, in _get_instructions_bytes
    argval, argrepr = _get_const_info(arg, constants)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/dis.py", line 292, in _get_const_info
    argval = const_list[const_index]
IndexError: tuple index out of range

```

**Comment by rokm** [comment]
> INFO: Python: 3.10.0

This is a python 3.10.0 bug - see https://github.com/pyinstaller/pyinstaller/issues/6301.

Upgrade to 3.10.1 or later.
