### ISSUE TITLE
FreeLibrary on user32.dll causes exception

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#700]
**Original date**: 2014/04/15

run: 

python pyinstaller.py  C:\soft\pyinstaller-pyinstaller-6195cc3\teecons\teecons.spec
```
hsrc filename c:\python27\DLLs\_ctypes.pyd
hsrc filename C:\Windows\system32\user32.dll
Traceback (most recent call last):
  File "pyinstaller.py", line 18, in <module>
    run()
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\build.py", line 1737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\build.py", line 1686, in build
    execfile(spec)
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\teecons\teecons.spec", line 6, in <module>
    runtime_hooks=None)
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\build.py", line 403, in __init__
    self.__postinit__()
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\build.py", line 305, in __postinit__
    self.assemble()
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\build.py", line 631, in assemble
    manifest=depmanifest))
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\bindepend.py", line 157, in Dependencies
    for ftocnm, fn in selectAssemblies(pth, manifest):
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\bindepend.py", line 323, in selectAssemblies
    for assembly in getAssemblies(pth):
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\bindepend.py", line 282, in getAssemblies
    res = GetManifestResources(pth)
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\utils\winmanifest.py", line 944, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\utils\winresource.py", line 174, in GetResources
    win32api.FreeLibrary(hsrc)
pywintypes.error: (2, 'FreeLibrary', 'The system cannot find the file specified.')
```

I have monkey-patched winresource.py to display hsrc and it displays it as hsrc filename C:\Windows\system32\user32.dll as you can see.

Brutal non-production fix:
```
     try:
        win32api.FreeLibrary(hsrc)
    except Exception, e:
        print 'Exception found: %s' % e
    return res
```
After this change the exe is built.

I have downloaded latest dev version from here: https://github.com/pyinstaller/pyinstaller/zipball/develop

I'm not sure which Milestone/version it relates to.

**Comment by matysek** [comment]
Simple helloworld usually works. You are using Enthough Python Distribution (EPD) that includes some customization to pywin32 modules.

This looks like an issue with the EPD python distribution.

The fix would be to find out how pywin32 is bundled in EPD.
