### ISSUE TITLE
Missing module "aspose.pydrawing"

### ISSUE THREAD

**Issue by MarcDreamer** [pyinstaller/pyinstaller#7011]
I created a small program but after I created the exe file (onedir mode) it doesn't work.
I mean, the exe file opens and closes immediately after without giving me any details.
I even tried the 'onefile' mode but I encountered some errors:

````
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load  
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked   
File "<frozen importlib._bootstrap>", line 672, in _load_unlocked   
File "<frozen importlib._bootstrap>", line 640, in _load_backward_compatible 
KeyError: 'aspose.pydrawing'
The above exception was the direct cause of the following exception:
ImportError: Unable to import module dependencies. Cannot import the aspose.pydrawing module. The module not found or errors occured while inizializing it. 

The above exception was the direct cause of the following exception: Traceback (most recent call last):  
File "CombinaPDF_004.py" , line 1, in <module>
File "aspose\__init__.py", line 44, in load_module   
File "aspose\__init__.py", line 76, in _load_native_module 
ImportError: One or more errors occurred while loading the module 'aspose.words' (-1009) 
 [4932] Failed to execute script 'CombinaPDF_004' due to unhandled exception!```
``
My imports are:
```
import aspose
from aspose import words as aw
import PyPDF2
import tkinter as tk
from tkinter import *
from tkinter import filedialog
import os
import tkinter.messagebox as sms
import PIL
from PIL import Image, ImageTk
import pdf2image
from pdf2image import convert_from_path as cfp
```

one more thing:
In the warning txt, it's written that frozen_importlib_external is missing while frozen_importlib is excluded


What could I do to fix this problem?

**Comment by bwoodsend** [comment]
Adding `--hiddenimport=aspose.pydrawing --hiddenimport=aspose.pygc --collect-binaries=aspose` to the build command gets it past the `aspose` imports.

That said, `aspose` looks like one of the most confused packaging messes I've ever seen. It's Linux wheels are inproperly labeled as Python version independent which is then hacked around by lumping extension libraries for all Python versions into one wheel, and it contains a vendored copy of dotnet for Windows. I would replace this dependency if I were you...

<details><summary>Wheel contents</summary>

```
env/lib/python3.10/site-packages/aspose
env/lib/python3.10/site-packages/aspose/pyio.cpython-310-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/assemblies
env/lib/python3.10/site-packages/aspose/assemblies/pydrawing
env/lib/python3.10/site-packages/aspose/assemblies/pydrawing/Microsoft.Win32.SystemEvents.dll
env/lib/python3.10/site-packages/aspose/assemblies/pydrawing/System.Drawing.Common.dll
env/lib/python3.10/site-packages/aspose/assemblies/pydrawing/WrpInterop.Aspose.PyDrawing.dll
env/lib/python3.10/site-packages/aspose/assemblies/pygc
env/lib/python3.10/site-packages/aspose/assemblies/pygc/Aspose.PyGC.dll
env/lib/python3.10/site-packages/aspose/assemblies/words
env/lib/python3.10/site-packages/aspose/assemblies/words/Aspose.Words.dll
env/lib/python3.10/site-packages/aspose/assemblies/words/Aspose.Words.Pdf2Word.dll
env/lib/python3.10/site-packages/aspose/assemblies/words/libSkiaSharp.so
env/lib/python3.10/site-packages/aspose/assemblies/words/SkiaSharp.dll
env/lib/python3.10/site-packages/aspose/assemblies/words/WrpInterop.Aspose.Words.dll
env/lib/python3.10/site-packages/aspose/netcore
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/createdump
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libaspose.embed.coreclrwrap.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libclrjit.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libcoreclr.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libcoreclrtraceptprovider.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libdbgshim.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libhostfxr.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libhostpolicy.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libmscordaccore.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/libmscordbi.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/Microsoft.CSharp.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/Microsoft.VisualBasic.Core.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/Microsoft.VisualBasic.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/Microsoft.Win32.Primitives.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/Microsoft.Win32.Registry.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/mscorlib.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/netstandard.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/SOS_README.md
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.AppContext.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Buffers.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Collections.Concurrent.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Collections.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Collections.Immutable.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Collections.NonGeneric.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Collections.Specialized.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ComponentModel.Annotations.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ComponentModel.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ComponentModel.EventBasedAsync.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ComponentModel.Primitives.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ComponentModel.TypeConverter.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Configuration.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Console.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Core.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Data.Common.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Data.DataSetExtensions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Data.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.Contracts.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.Debug.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.DiagnosticSource.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.Process.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.StackTrace.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.TextWriterTraceListener.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.Tools.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.TraceSource.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.Tracing.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Drawing.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Drawing.Primitives.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Dynamic.Runtime.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Globalization.Calendars.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Globalization.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Globalization.Extensions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Globalization.Native.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.Compression.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.Compression.FileSystem.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.Compression.Native.a
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.Compression.Native.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.Compression.ZipFile.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.FileSystem.AccessControl.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.FileSystem.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.FileSystem.DriveInfo.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.FileSystem.Primitives.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.FileSystem.Watcher.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.IsolatedStorage.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.MemoryMappedFiles.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.Pipes.AccessControl.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.UnmanagedMemoryStream.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Linq.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Linq.Expressions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Linq.Parallel.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Linq.Queryable.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Memory.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Native.a
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Native.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Http.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Http.Native.a
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Http.Native.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.HttpListener.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Mail.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.NameResolution.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Ping.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Primitives.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Requests.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Security.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Security.Native.a
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Security.Native.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.ServicePoint.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.Sockets.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.WebClient.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.WebHeaderCollection.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.WebProxy.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.WebSockets.Client.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.WebSockets.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Numerics.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ComponentModel.DataAnnotations.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Diagnostics.FileVersionInfo.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.Compression.Brotli.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.IO.Pipes.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Net.NetworkInformation.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Numerics.Vectors.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.Primitives.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Loader.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.Csp.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Text.Encoding.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Transactions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ObjectModel.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Private.CoreLib.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Private.DataContractSerialization.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Private.Uri.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Private.Xml.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Private.Xml.Linq.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.DispatchProxy.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.Emit.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.Emit.ILGeneration.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.Emit.Lightweight.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.Extensions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.Metadata.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Reflection.TypeExtensions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Resources.Reader.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Resources.ResourceManager.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Resources.Writer.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.CompilerServices.Unsafe.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.CompilerServices.VisualC.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Extensions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Handles.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.InteropServices.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.InteropServices.RuntimeInformation.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.InteropServices.WindowsRuntime.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Intrinsics.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Numerics.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Serialization.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Serialization.Formatters.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Serialization.Json.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Serialization.Primitives.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.Serialization.Xml.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.WindowsRuntime.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Runtime.WindowsRuntime.UI.Xaml.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.AccessControl.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Claims.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.Algorithms.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.Cng.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.Encoding.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.Native.OpenSsl.a
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.Native.OpenSsl.so
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.OpenSsl.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.Primitives.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Cryptography.X509Certificates.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Principal.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.Principal.Windows.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Security.SecureString.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ServiceModel.Web.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ServiceProcess.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Text.Encoding.CodePages.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Text.Encoding.Extensions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Text.Encodings.Web.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Text.Json.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Text.RegularExpressions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.Channels.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.Overlapped.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.Tasks.Dataflow.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.Tasks.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.Tasks.Extensions.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.Tasks.Parallel.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.Thread.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.ThreadPool.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Threading.Timer.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Transactions.Local.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.ValueTuple.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Web.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Web.HttpUtility.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Windows.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.Linq.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.ReaderWriter.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.Serialization.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.XDocument.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.XmlDocument.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.XmlSerializer.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.XPath.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/System.Xml.XPath.XDocument.dll
env/lib/python3.10/site-packages/aspose/netcore/netcore3.1/WindowsBase.dll
env/lib/python3.10/site-packages/aspose/pydrawing.cpython-310-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pydrawing.cpython-35m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pydrawing.cpython-36m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pydrawing.cpython-37m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pydrawing.cpython-38-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pydrawing.cpython-39-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pygc.cpython-310-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pygc.cpython-35m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pygc.cpython-36m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pygc.cpython-37m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pygc.cpython-38-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pygc.cpython-39-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pyio.cpython-35m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pyio.cpython-36m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pyio.cpython-37m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pyio.cpython-38-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/pyio.cpython-39-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/words.cpython-310-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/words.cpython-35m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/words.cpython-36m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/words.cpython-37m-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/words.cpython-38-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/words.cpython-39-x86_64-linux-gnu.so
env/lib/python3.10/site-packages/aspose/__init__.py
env/lib/python3.10/site-packages/aspose/__pycache__
env/lib/python3.10/site-packages/aspose/__pycache__/__init__.cpython-310.pyc
```

</details>
