### ISSUE TITLE
get an error running the .exe file

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [pyinstaller/pyinstaller#7015]
Hello, when I package with pyinstaller“pyinstaller -D onnx2tensorrt.py  --add-data D:\work_dir\TensorRT\trans_segmask3onnx\trt_dynamic.py;. --hidden-import mmdeploy.pytorch --hidden-import mmdeploy.mmcv”, I get an error running the .exe file, while the Python file works, is it because it was hidden when packaged? 
I don't know how to modify it, thanks for your reply
(mmdeploy) D:\work_dir\TensorRT\trans_segmask3onnx\dist\onnx2tensorrt>onnx2tensorrt.exe
2022-08-04 18:01:45,469 - mmdeploy - WARNING - Could not load the library of tensorrt plugins.             Because the file does not exist:
[08/04/2022-18:01:45] [TRT] [I] [MemUsageChange] Init CUDA: CPU +171, GPU +0, now: CPU 7183, GPU 776 (MiB)
[08/04/2022-18:01:45] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 7204 MiB, GPU 776 MiB
[08/04/2022-18:01:45] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 7225 MiB, GPU 776 MiB
[08/04/2022-18:01:45] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/04/2022-18:01:45] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[08/04/2022-18:01:48] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[08/04/2022-18:01:48] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[08/04/2022-18:01:49] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[08/04/2022-18:01:49] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace:
Traceback (most recent call last):
  File "onnx2tensorrt.py", line 42, in <module>
  File "onnx2tensorrt.py", line 27, in main
  File "mmdeploy\backend\tensorrt\utils.py", line 113, in from_onnx
RuntimeError: Failed to parse onnx, In node 1065 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

[16808] Failed to execute script 'onnx2tensorrt' due to unhandled exception!

**Comment by rokm** [comment]
Yes, plugins are usually imported directly or lazy-loaded, so PyInstaller cannot analyze them. `mmdeploy` also seems to contain some shared libraries (or possibly python extensions) that are probably not automatically collected, either:

> 2022-08-04 18:01:45,469 - mmdeploy - WARNING - Could not load the library of tensorrt plugins. Because the file does not exist: 

This warning originates from [here](https://github.com/open-mmlab/mmdeploy/blob/83b11bc1ca7227497928a57b56653b76501b1368/mmdeploy/backend/tensorrt/init_plugins.py#L37), and [further up in this file](https://github.com/open-mmlab/mmdeploy/blob/83b11bc1ca7227497928a57b56653b76501b1368/mmdeploy/backend/tensorrt/init_plugins.py#L15-L18) there are candidates it tries to load.

So check if that file is missing, and ensure it is collected if necessary. Adding [`--collect-binaries  mmdeploy`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-binaries) to your PyInstaller command might do the trick.

At any rate, if you want to use `mmdeploy` with `PyInstaller`, I suggest you to familiarize yourself with both, because you are likely to keep running into problems like that, and walking you through that is beyond the support we provide here.

**Comment by jiaqizhang123-stack** [comment]
ok, thanks a lot for your answer
