### ISSUE TITLE
Compiled binary crashes after adding jpegtran lib

### ISSUE THREAD

**Issue by nazikus** [pyinstaller/pyinstaller#7025]
Project I'm working on [labelme][1] is compiled with PyInstaller without problems. After adding my code based on [jpegtran-cffi][2] lib (which in turn requires [libjpeg-turbo][3] shared lib) PyInstaller compiles binary without any errors, but when binary is run it crashes right away.

```
$ dist/labelme --version
Traceback (most recent call last):
  File "__main__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "__init__.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "label_file.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "jpegtran/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "jpegtran/transform.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "jpegtran/lib.py", line 33, in <module>
  File "cffi/api.py", line 468, in verify
  File "cffi/verifier.py", line 105, in load_library
  File "cffi/verifier.py", line 202, in _compile_module
  File "cffi/ffiplatform.py", line 22, in compile
  File "cffi/ffiplatform.py", line 51, in _build
  File "distutils/dist.py", line 984, in run_command
  File "distutils/cmd.py", line 107, in ensure_finalized
  File "distutils/command/build_ext.py", line 133, in finalize_options
  File "distutils/cmd.py", line 286, in set_undefined_options
  File "distutils/dist.py", line 857, in get_command_obj
  File "distutils/dist.py", line 843, in get_command_class
distutils.errors.DistutilsModuleError: invalid command 'build'
[73534] Failed to execute script '__main__' due to unhandled exception!

```

And if I run app's uncompiled entrypoint, it works:
```
$ pip install .
$ labelme --version
labelme 5.0.1
``` 

I analyzed all the build logs, no errors or references to `jpegtran` or `libjpeg-turbo` libs. And the error stack does not ring a bell to me. Any suggestions how to fix this?

Thank you

  [1]: https://github.com/wkentaro/labelme
  [2]: https://pypi.org/project/jpegtran-cffi/
  [3]: https://libjpeg-turbo.org/

**Comment by rokm** [comment]
Looks like `jpegtran` is trying to do some compilation at runtime, due to use of `cffi.FFI.verify` call [here](https://github.com/jbaiter/jpegtran-cffi/blob/e95a221f43b4df8e27aa4ea750bf002540b3c089/jpegtran/lib.py#L33), and it looks like the required part of `distutils` might not have been fully collected (perhaps a `--collect-submodules distutils` might help?). But the runtime compilation has implications for the frozen application as well (i.e., it will require the presence of python header on the target machine).

It looks like the git HEAD of [jpegtran-cffi](https://github.com/jbaiter/jpegtran-cffi) removed those verify calls. I can get that version working (i.e., a simple `import jpegtran` program works) by installing via `pip install git+https://github.com/jbaiter/jpegtran-cffi.git`. This requires `_cffi_backend` to be added as a hidden import, though (`--hiddenimport _cffi_backend`).

**Comment by bwoodsend** [comment]
```fish
> pip wheel --no-deps jpegtran-cffi
> unzip -l jpegtran_cffi-0.5.2-cp310-cp310-linux_x86_64.whl 
Archive:  jpegtran_cffi-0.5.2-cp310-cp310-linux_x86_64.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    54088  2022-08-11 21:21   _cffi__x93684ce7x364e3adb.cpython-310-x86_64-linux-gnu.so
   131920  2022-08-11 21:21   _cffi__xac4389b6x37649c1c.cpython-310-x86_64-linux-gnu.so
       63  2014-06-18 11:50   jpegtran/__init__.py
    21500  2014-11-30 20:20   jpegtran/lib.py
     7953  2015-05-24 10:16   jpegtran/transform.py
      281  2022-08-11 21:21   jpegtran_cffi-0.5.2.dist-info/METADATA
      105  2022-08-11 21:21   jpegtran_cffi-0.5.2.dist-info/WHEEL
       61  2022-08-11 21:21   jpegtran_cffi-0.5.2.dist-info/top_level.txt
      779  2022-08-11 21:21   jpegtran_cffi-0.5.2.dist-info/RECORD
---------                     -------
   216750                     9 files
```
Those `_cffi_*.cpython-310-x86_64-linux-gnu.so` modules need to be collected.

**Comment by rokm** [comment]
> Those `_cffi_*.cpython-310-x86_64-linux-gnu.so` modules need to be collected.

Ah, good call! `--hiddenimport _cffi__x93684ce7x364e3adb --hiddenimport _cffi__xac4389b6x37649c1c` should do the trick, then.

**Comment by nazikus** [comment]
thank you for the prompt responses. It worked!

But I had to do it via spec file:
```python
from PyInstaller.utils.hooks import collect_submodules

hiddenimports = collect_submodules("_cffi__x7dbae04axcdb1023") + collect_submodules("_cffi__xe5a15ceax994e4538")

Analysis(
...
    hiddenimports=hiddenimports
)
```

**Comment by nazikus** [comment]
now when I run app (with `jpegtran-cffi` submodule as in the comment above), directory `jpegtran-cffi` is created in current working dir everytime this lib is ivoked.

```bash
# running pyinstaller app in ~/dev
./labelme
# do manipulations that invokes jpegtran-cffi lib,
# following dir tree is created everytime in current dir
~/dev/jpegtran/
└── __pycache__
    └── _cffi__x30e896f0xf3ca0677.c
```

Any ideas how to avoid it?

**Comment by rokm** [comment]
Looks like this is triggered by actually using the `jpegtran` (and not just importing it), which is the piece of info that was missing from #7117...

From what I can tell, the problem originates from [here](https://foss.heptapod.net/pypy/cffi/-/blob/branch/default/cffi/verifier.py#L245-260):
```python
_TMPDIR = None

def _caller_dir_pycache():
    if _TMPDIR:
        return _TMPDIR
    result = os.environ.get('CFFI_TMPDIR')
    if result:
        return result
    filename = sys._getframe(2).f_code.co_filename
    return os.path.abspath(os.path.join(os.path.dirname(filename),
                           '__pycache__'))

def set_tmpdir(dirname):
    """Set the temporary directory to use instead of __pycache__."""
    global _TMPDIR
    _TMPDIR = dirname
``` 

In frozen application, the `filename` obtained via `sys._getframe(2).f_code.co_filename` is "just" `jpegtran/lib.py` (presumably because we strip the absolute paths), so the temporary temporary directory returned by `_caller_dir_pycache` ends up being `jpegtran/__pycache__` in the current working directory. 

Judging by the code, you could either try setting `CFFI_TEMPDIR` environment variable to something reasonable at the start of your program (before importing `jpegtran`). Or using `cffi.verifier.set_tmpdir` looks like a valid option, too. In either case, you could opt for a path inside `sys._MEIPASS` or inside the global temporary directory.

**Comment by nazikus** [comment]
@rokm once again, thank you for prompt response and working solution

I chose the simplest way, added at the beginning of app init: `os.environ["CFFI_TMPDIR"]="/tmp/"`
