### ISSUE TITLE
llvmlite.dll is not found after building

### ISSUE THREAD

**Issue by ayalalazaro** [pyinstaller/pyinstaller#7050]
## Description:
I have built an application with numba, no errors when running pyinstaller. When trying to execute the resulting file the library llvmlite.dll is not found.
I can verify that it is collected in the folder llvmlite\binding but it is linked to Library\bin. Manually creating the path and copying the file works.

### Context information 

* Output of `pyinstaller --version`: ```5.3``` also tried 5.1
* Version of Python:  3.10.6
* Platform: Windows
* How you installed Python: python installed with conda, pyinstaller  5.1 installed with conda as well, 5.3 with pip
* Did you also try this on another platform? Does it work there? No other platforms

### Stacktrace / full error message
Traceback (most recent call last):
  File "app.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "triple_channel.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "numba\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "numba\core\config.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "llvmlite\binding\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "llvmlite\binding\dylib.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "llvmlite\binding\ffi.py", line 162, in <module>
  File "os.py", line 1117, in add_dll_directory
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ME\\project_path\\dist\\film_analysis\\Library\\bin'

**Comment by rokm** [comment]
This problem is specific to `llvmlite` installed from conda - they patch their `site-packages\llvmlite\binding\ffi.py` to include this block,

```python
if os.name == 'nt':
    # Append DLL directory to PATH, to allow loading of bundled CRT libraries
    # (Windows uses PATH for DLL loading, see http://msdn.microsoft.com/en-us/library/7d83bc18.aspx).  # noqa E501
    os.environ['PATH'] += ';' + _lib_dir
    import sys
    if sys.version_info >= (3, 8):
        os.add_dll_directory(os.path.join(os.path.normpath(sys.prefix), 'Library', 'bin'))
``` 
which calls `os.add_dll_directory()` without first checking that the directory exists  - presumably because it always does in a conda environment. 

Installing PyPI wheel for `llvmlite` via `pip` will avoid this problem.

As this is purely conda-induced and as there is no reason for `Library/bin` directory to exist in the frozen application (and in fact, PyInstaller's internals do not allow collection/creation of empty directories in the bundle), I am closing this a `wontfix`.

**Comment by ayalalazaro** [comment]
I can corroborate that pip installation works. Thanks!
