### ISSUE TITLE
gstreamer webrtc dependencies (gst-plugins-bad) are not being packaged

### ISSUE THREAD

**Issue by petergerten** [pyinstaller/pyinstaller#7070]
PyInstaller: 5.3
OS: Ubuntu 22.04

When packaging an application that depends on the webrtcbin gstreamer module (in gst-plugins-bad),
the resulting binary is not working:

`ValueError: Namespace GstWebRTC not available`

This can be fixed with `apt-get install gstreamer-plugins-bad`, so it seems that webrtcbin / plugins-bad is not being installed.
According to the docs, all available gstreamer plugins should be automatically packaged.

**Comment by rokm** [comment]
Can we see the whole traceback? Are you explicitly trying to perform a `from gi.repository import GstWebRTC` in your code, or is this done by some other component?

We probably need the hook for `gi.repository.GstWebRTC` either way, but we need to know if there's also a hidden import that needs to be taken care of somewhere...

**Comment by petergerten** [comment]
yes, I explicitly do a `from gi.repository import GstWebRTC`

```
Traceback (most recent call last):
  File "cli.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "streamingclient.py", line 17, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace GstWebRTC not available
```
Line 17,18 in `streamingclient.py`:
```
gi.require_version('GstWebRTC', '1.0')
from gi.repository import GstWebRTC
```

**Comment by petergerten** [comment]
@rokm thanks - much appreciate the quick fix. Works great!
