### ISSUE TITLE
No module named 'numpy.distutils'

### ISSUE THREAD

**Issue by sunnowrun** [pyinstaller/pyinstaller#7076]
## Description of the issue
I make a file named print_data.py contain only `import pyscf`, then I `pyinstaller print_data.py`, and run the output file in dist folder by `./print_data`, but get an error as below.

Traceback (most recent call last):
  File "print_data.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pyscf/__init__.py", line 113, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pyscf/lib/__init__.py", line 24, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pyscf/lib/numpy_helper.py", line 39, in <module>
  File "pyscf/lib/misc.py", line 55, in load_library
  File "numpy/ctypeslib.py", line 137, in load_library
ModuleNotFoundError: No module named 'numpy.distutils'
[17316] Failed to execute script 'print_data' due to unhandled exception!

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.9```
* Version of Python: 3.8.8
* Platform: WSL (windows subsystem linux)
* How you installed Python: Anaconda

**Comment by bwoodsend** [comment]
Does upgrading numpy help? This sounds like https://github.com/numpy/numpy/issues/20769 which is done and fixed months ago.

**Comment by bwoodsend** [comment]
Actually, forget that. Following through that stacktrace I see it's something else. There's a `numpy.distutils` import [here](https://github.com/numpy/numpy/blob/397b6e51b446647839f548529d06dc80bf0a4c53/numpy/ctypeslib.py#L137) although the function it's loading is a depressingly trivial one. Adding `--hiddenimport=numpy.distutils` to your build command would be the quick way out.

**Comment by rokm** [comment]
The problematic part is that we now have two versions of the `numpy` hook; one is [ours](https://github.com/pyinstaller/pyinstaller/blob/v4.9/PyInstaller/hooks/hook-numpy.py), the [other comes from numpy itself](https://github.com/numpy/numpy/blob/main/numpy/_pyinstaller/hook-numpy.py). And the latter still excludes `numpy.distutils` and `distutils` whereas ours does not. Which I suppose shows a disadvantage of pushing hooks upstream, because we are actually in a better position to fix/work-around things like that (both because we have more experience, and because we have control over our release cadence).

----

Either way, to get `pyscf` import working in a frozen application on my linux system, I have to add `--collect-submodules numpy.distutils --hiddenimport distutils.unixccompiler --collect-binaries pyscf`.

**Comment by sunnowrun** [comment]
> The problematic part is that we now have two versions of the `numpy` hook; one is [ours](https://github.com/pyinstaller/pyinstaller/blob/v4.9/PyInstaller/hooks/hook-numpy.py), the [other comes from numpy itself](https://github.com/numpy/numpy/blob/main/numpy/_pyinstaller/hook-numpy.py). And the latter still excludes `numpy.distutils` and `distutils` whereas ours does not. Which I suppose shows a disadvantage of pushing hooks upstream, because we are actually in a better position to fix/work-around things like that (both because we have more experience, and because we have control over our release cadence).
> 
> Either way, to get `pyscf` import working in a frozen application on my linux system, I have to add `--collect-submodules numpy.distutils --hiddenimport distutils.unixccompiler --collect-binaries pyscf`.

Don't work in my Linux system.
Give error `No module named 'setuptools._distutils'`

**Comment by sunnowrun** [comment]
> 

Also error `cannot import name 'ccompiler' from partially initialized module 'numpy.distutils'`

**Comment by rokm** [comment]
> Don't work in my Linux system.
> Give error `No module named 'setuptools._distutils'`

For setuptools-provided `distutils`, you will need PyInstaller 5.4 (#7075)...

**Comment by sunnowrun** [comment]
> > Don't work in my Linux system.
> > Give error `No module named 'setuptools._distutils'`
> 
> For setuptools-provided `distutils`, you will need PyInstaller 5.4 (#7075)...

I upgrade pyinstaller to 5.4, still get the same error.
I `pip install setuptools` then get other error.
I am T_T

**Comment by sunnowrun** [comment]
> > > Don't work in my Linux system.
> > > Give error `No module named 'setuptools._distutils'`
> > 
> > 
> > For setuptools-provided `distutils`, you will need PyInstaller 5.4 (#7075)...
> 
> I upgrade pyinstaller to 5.4, still get the same error. I `pip install setuptools` then get other error. I am T_T

Now, I run `pyinstaller print_data.py`, then run `./print_data`, will get following error
Traceback (most recent call last):
  File "print_data.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pyscf/__init__.py", line 113, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pyscf/lib/__init__.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pyscf/lib/numpy_helper.py", line 39, in <module>
  File "pyscf/lib/misc.py", line 55, in load_library
  File "numpy/ctypeslib.py", line 153, in load_library
OSError: no file with expected extension

**Comment by rokm** [comment]
That's because the shared libs that are supposed to be loaded via `ctypes` are not collected. If you installed `pyscf` via  `pip` (i.e., you are using PyPI wheel), then `--collect-binaries pyscf` should take care of that. If you installed `pypcf` via conda, then you'll need to figure it out yourself.

**Comment by sunnowrun** [comment]
> That's because the shared libs that are supposed to be loaded via `ctypes` are not collected. If you installed `pyscf` via `pip` (i.e., you are using PyPI wheel), then `--collect-binaries pyscf` should take care of that. If you installed `pypcf` via conda, then you'll need to figure it out yourself.

I install the pyscf by pip, and add `--collect-binaries pyscf` when use pyinstaller.
But get below error


Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 381, in __init__
OSError: libgomp-f7e03b3e.so.1.0.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyscf/lib/misc.py", line 55, in load_library
  File "numpy/ctypeslib.py", line 158, in load_library
  File "ctypes/__init__.py", line 456, in __getitem__
  File "ctypes/__init__.py", line 451, in __getattr__
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.PyInstallerImportError: Failed to load dynlib/dll '/tmp/_MEIgghw1H/pyscf/lib/libnp_helper.so'. Most likely this dynlib/dll was not found when the application was frozen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 381, in __init__
OSError: libgomp-f7e03b3e.so.1.0.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "print_data.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pyscf/__init__.py", line 113, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pyscf/lib/__init__.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pyscf/lib/numpy_helper.py", line 39, in <module>
  File "pyscf/lib/misc.py", line 63, in load_library
  File "numpy/ctypeslib.py", line 158, in load_library
  File "ctypes/__init__.py", line 456, in __getitem__
  File "ctypes/__init__.py", line 451, in __getattr__
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.PyInstallerImportError: Failed to load dynlib/dll '/tmp/_MEIgghw1H/pyscf/lib/libnp_helper.so'. Most likely this dynlib/dll was not found when the application was frozen.
[8128] Failed to execute script 'print_data' due to unhandled exception!

**Comment by rokm** [comment]
Hmm, you are right, I am getting this error now as well.

It looks like `collect_binaries` does not pick up `pyscf/lib/libgomp-f7e03b3e.so.1.0.0` and `lib/libgfortran-139be63a.so.3.0.0˙ because their suffix does not match `.so`. So you need to collect those libraries manually (where you should replace `venv/lib/python3.8/site-packages` with path to your environment's site packages, e.g.:
```
pyinstaller  \
  program.py
  --clean \
  --noconfirm  \
  --collect-submodules numpy.distutils \
  --hiddenimport distutils.unixccompiler \ 
  --collect-binaries pyscf \
  --add-binary venv/lib/python3.8/site-packages/pyscf/lib/libgomp-f7e03b3e.so.1.0.0:pyscf/lib \
  --add-binary venv/lib/python3.8/site-packages/pyscf/lib/libgfortran-139be63a.so.3.0.0:pyscf/lib
```

**Comment by rokm** [comment]
Atlernatively, you can try creating a directory `extra-hooks` in your current working directory, and place the following hook file into it (`extra-hooks/hook-pyscf.py`):
```python
# extra-hooks/hook-pyscf.py
from PyInstaller.utils.hooks import collect_dynamic_libs, get_module_file_attribute
binaries = collect_dynamic_libs('pyscf')
```
And then run
```
pyinstaller  \
  program.py
  --clean \
  --noconfirm  \
  --collect-submodules numpy.distutils \
  --hiddenimport distutils.unixccompiler \ 
  --additional-hooks-dir ./extra-hooks
```

This might work without explicitly collecting `libgomp-f7e03b3e.so.1.0.0` and `libgfortran-139be63a.so.3.0.0`...

I'm starting to suspect that binaries passed to `Analysis()` via `binaries` argument (which is what the command line switch effectively does) do not undergo binary analysis, while those returned from the hook do...

**Comment by sunnowrun** [comment]
> Atlernatively, you can try creating a directory `extra-hooks` in your current working directory, and place the following hook file into it (`extra-hooks/hook-pyscf.py`):
> 
> ```python
> # extra-hooks/hook-pyscf.py
> from PyInstaller.utils.hooks import collect_dynamic_libs, get_module_file_attribute
> binaries = collect_dynamic_libs('pyscf')
> ```
> 
> And then run
> 
> ```
> pyinstaller  \
>   program.py
>   --clean \
>   --noconfirm  \
>   --collect-submodules numpy.distutils \
>   --hiddenimport distutils.unixccompiler \ 
>   --additional-hooks-dir ./extra-hooks
> ```
> 
> This might work without explicitly collecting `libgomp-f7e03b3e.so.1.0.0` and `libgfortran-139be63a.so.3.0.0`...
> 
> I'm starting to suspect that binaries passed to `Analysis()` via `binaries` argument (which is what the command line switch effectively does) do not undergo binary analysis, while those returned from the hook do...

Thank you, this method is useful.

**Comment by sunnowrun** [comment]
But now I am in another trouble.
When I run the output file created by pyinstaller, it give me error as below

File "pyscf/pbc/gto/pseudo/parse_cp2k.py", line 78, in search_seg
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/f/python_usage/Python_Usage/example_pyinstaller/dist/my_program/pyscf/pbc/gto/pseudo/gth-pade.dat'

I find that in `parse_cp2k.py` there is `fin = open(pseudofile, 'r')` in line 78 in the source of PySCF.
I don't know how to deal with it. If `pyinstaller` have a guide to handle with this file-read process?

**Comment by rokm** [comment]
You need to ensure that any data files that come with the package are collected. Either try adding `--collect-data pyscf` to your PyInstaller command, or extend the `hook-psycf.py`:
```python
# extra-hooks/hook-pyscf.py
from PyInstaller.utils.hooks import collect_dynamic_libs, get_module_file_attribute, collect_data_files
binaries = collect_dynamic_libs('pyscf')
datas = collect_data_files('pyscf')

**Comment by sunnowrun** [comment]
> You need to ensure that any data files that come with the package are collected. Either try adding `--collect-data pyscf` to your PyInstaller command, or extend the `hook-psycf.py`:
> 
> ```python
> # extra-hooks/hook-pyscf.py
> from PyInstaller.utils.hooks import collect_dynamic_libs, get_module_file_attribute, collect_data_files
> binaries = collect_dynamic_libs('pyscf')
> datas = collect_data_files('pyscf')
> ```

Thank you! All is right now.
