### ISSUE TITLE
exe file created from py program that uses asciidoc is still call asciidoc import

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#708]
**Original date**: 2013/04/19
**Original reporter**: *igorft AND yahoo DOT  COOM *

I have the following in my source code:

    from asciidocapi import AsciiDocAPI
    asciidoc = asciidocapi.AsciiDocAPI()

When I run an exe file, I get:

Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "C:\pyinstaller-2.0\CeSaR\build\pyi.win32\CeSaR\out00-PYZ.pyz\asciidocapi", line 179, in __init__
  File "C:\pyinstaller-2.0\CeSaR\build\pyi.win32\CeSaR\out00-PYZ.pyz\asciidocapi", line 200, in __import_asciidoc
asciidocapi.AsciiDocError: failed to import C:\Python27\asciidoc-8.6.8\asciidoc.py

What's wrong? I asciidoc supported?

**Comment by matysek** [comment]
@htgoebel he probably meant this: http://asciidoc.org/asciidocapi.html
