### ISSUE TITLE
Support compiled scripts in Analysis()

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#709]
**Original date**: 2013/04/20
**Original reporter**: _eliot2 AND umbc DOT edu_

```
463 INFO: Testing for ability to set icons, version resources...
629 INFO: ... resource update available
634 INFO: UPX is not available.
3808 INFO: checking Analysis
3809 INFO: building Analysis because out00-Analysis.toc non existent
3809 INFO: running Analysis out00-Analysis.toc
3812 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable

11688 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.2
1022.8_none ...
11690 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1f
c8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91.manifest
11700 INFO: Searching for file msvcr90.dll
11701 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b
_9.0.21022.8_none_bcb86ed6ac711f91\msvcr90.dll
11701 INFO: Searching for file msvcp90.dll
11703 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b
_9.0.21022.8_none_bcb86ed6ac711f91\msvcp90.dll
11703 INFO: Searching for file msvcm90.dll
11706 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b
_9.0.21022.8_none_bcb86ed6ac711f91\msvcm90.dll
12161 INFO: Analyzing C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\s
upport\_pyi_bootstrap.py
SCRIIIIIIIIPT: C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\support\
_pyi_bootstrap.py
13569 INFO: Analyzing C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\P
yInstaller\loader\archive.py
SCRIIIIIIIIPT: C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstal
ler\loader\archive.py
13706 INFO: Analyzing C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\P
yInstaller\loader\carchive.py
SCRIIIIIIIIPT: C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstal
ler\loader\carchive.py
13898 INFO: Analyzing C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\P
yInstaller\loader\iu.py
SCRIIIIIIIIPT: C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstal
ler\loader\iu.py
13935 INFO: Analyzing C:\Users\eliot\Documents\RGB\src\main\game\main.pyc
SCRIIIIIIIIPT: C:\Users\eliot\Documents\RGB\src\main\game\main.pyc
Traceback (most recent call last):
  File "pyinstaller.py", line 91, in <module>
    main()
  File "pyinstaller.py", line 86, in main
    run_build(opts, spec_file)
  File "pyinstaller.py", line 50, in run_build
    PyInstaller.build.main(spec_file, **opts.__dict__)
  File "C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstaller\bui
ld.py", line 1626, in main
    build(specfile, buildpath)
  File "C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstaller\bui
ld.py", line 1583, in build
    execfile(spec)
  File "rgb.spec", line 26, in <module>
    'encodings.encodings', 'encodings.__builtin__', 'encodings.utf_8'],
  File "C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstaller\bui
ld.py", line 389, in __init__
    self.__postinit__()
  File "C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstaller\bui
ld.py", line 315, in __postinit__
    self.assemble()
  File "C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstaller\bui
ld.py", line 476, in assemble
    importTracker.analyze_script(script)
  File "C:\Users\eliot\Documents\pyinstaller-2.0\pyinstaller-2.0\PyInstaller\dep
end\imptracker.py", line 199, in analyze_script
    co = compile(stuff, fnm, 'exec')
TypeError: compile() expected string without null bytes
```

**Comment by htgoebel** [comment]
Since the code has changed since this ticket war opened, the place to implement this is in modulegraph.run_script.

**Comment by Legorooj** [comment]
Stale
