### ISSUE TITLE
packaging Django with Jinja shows ValueError: The 'coreschema' package was not installed in a way that PackageLoader understands.

### ISSUE THREAD

**Issue by kostasmarkakis** [pyinstaller/pyinstaller#7115]
## Description of the issue

The problem comes when i bundle Jinja into my Django application. More specifically it happens with Jinja versions above 3.0, versions below 3.0 work.
It is an old issue, i had it since Pyinstaller 4.0 or even earlier versions as well as older versions of Django. Currently i use Django 4.1.1. The non package application works fine so the problem comes from the packaging. 

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.1.1
* Version of Python: 3.9 and 3.10
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Havent tried we only use windows

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

Did everything in the guide

### A minimal example program which shows the error

Sorry not sure what to put here. its a huge django app 

### Stacktrace / full error message

[16048] PyInstaller Bootloader 5.x
[16048] LOADER: executable is W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd\vodd.exe
[16048] LOADER: homepath is W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd
[16048] LOADER: _MEIPASS2 is NULL
[16048] LOADER: archivename is W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd\vodd.exe
[16048] LOADER: Cookie found at offset 0xB88AAF
[16048] LOADER: No need to extract files to run; setting extractionpath to homepath
[16048] LOADER: SetDllDirectory(W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd)
[16048] LOADER: Already in the child - running user's code.
[16048] LOADER: Python library: W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd\python310.dll
[16048] LOADER: Loaded functions from Python library.
[16048] LOADER: Manipulating environment (sys.path, sys.prefix)
[16048] LOADER: sys.prefix is W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd
[16048] LOADER: Pre-init sys.path is W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd\base_library.zip;W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd\lib-dynload;W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd
[16048] LOADER: Setting runtime options
[16048] LOADER: Initializing python
[16048] LOADER: Overriding Python's sys.path
[16048] LOADER: Post-init sys.path is W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd\base_library.zip;W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd\lib-dynload;W:\Geeglee\GEP\standalone\packaging\GEP\resources\vodd
[16048] LOADER: Setting sys.argv
[16048] LOADER: setting sys._MEIPASS
[16048] LOADER: importing modules from CArchive
[16048] LOADER: extracted struct
[16048] LOADER: running unmarshalled code object for struct...
[16048] LOADER: extracted pyimod01_os_path
[16048] LOADER: running unmarshalled code object for pyimod01_os_path...
[16048] LOADER: extracted pyimod02_archive
[16048] LOADER: running unmarshalled code object for pyimod02_archive...
[16048] LOADER: extracted pyimod03_importers
[16048] LOADER: running unmarshalled code object for pyimod03_importers...
[16048] LOADER: extracted pyimod04_ctypes
[16048] LOADER: running unmarshalled code object for pyimod04_ctypes...
[16048] LOADER: Installing PYZ archive with Python modules.
[16048] LOADER: PYZ archive: PYZ-00.pyz
[16048] LOADER: Running pyiboot01_bootstrap.py
[16048] LOADER: Running pyi_rth_pkgutil.py
[16048] LOADER: Running pyi_rth_subprocess.py
[16048] LOADER: Running pyi_rth_multiprocessing.py
[16048] LOADER: Running pyi_rth_pkgres.py
[16048] LOADER: Running pyi_rth_win32api.py
[16048] LOADER: Running pyi_rth_win32comgenpy.py
[16048] LOADER: Running pyi_rth_pywintypes.py
[16048] LOADER: Running pyi_rth_pythoncom.py
[16048] LOADER: Running pyi_rth_django.py
[16048] LOADER: Running pyi_rth_inspect.py
[16048] LOADER: Running manage.py
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
  File "django\core\management\__init__.py", line 446, in execute_from_command_line
  File "django\core\management\__init__.py", line 440, in execute
  File "django\core\management\base.py", line 402, in run_from_argv
  File "django\core\management\base.py", line 443, in execute
  File "django\core\management\base.py", line 475, in check
  File "django\core\checks\registry.py", line 88, in run_checks
  File "django\core\checks\urls.py", line 42, in check_url_namespaces_unique
  File "django\core\checks\urls.py", line 61, in _load_all_namespaces
  File "django\utils\functional.py", line 57, in __get__
  File "django\urls\resolvers.py", line 715, in url_patterns
  File "django\utils\functional.py", line 57, in __get__
  File "django\urls\resolvers.py", line 708, in urlconf_module
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "vodd\urls.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "rest_framework\documentation.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "rest_framework\renderers.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "rest_framework\serializers.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "rest_framework\compat.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "coreapi\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "coreapi\codecs\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "coreapi\codecs\corejson.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "coreschema\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "coreschema\encodings\html.py", line 5, in <module>
  File "jinja2\loaders.py", line 323, in __init__
ValueError: The 'coreschema' package was not installed in a way that PackageLoader understands.
[16048] Failed to execute script 'manage' due to unhandled exception!
[16048] LOADER: OK.
[16048] LOADER: Manually flushing stdout and stderr
[16048] LOADER: Cleaning up Python interpreter.

**Comment by rokm** [comment]
The problem has nothing to do with `django`, but rather with `coreschema` not finding its data files (as PyInstaller is not aware of those and therefore does not collect them). Adding [`--collect-data coreschema`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-data) to your PyInstaller command should solve this particular problem, which can be reproduced by freezing the following minimal program:
```python
import coreschema
print("Hello world!")
```
If you are building via spec file, then you should either collect the data files in your spec using [`collect_data_files`](https://pyinstaller.org/en/stable/hooks.html#PyInstaller.utils.hooks.collect_data_files) and pass it them to `Analysis` instance, or write [a hook](https://pyinstaller.org/en/stable/hooks.html) for `coreschema` that does that.

**Comment by kostasmarkakis** [comment]
I am not sure it is a simple problem of coreschema bundling. 
That would be easy by just adding coreschema to the hidden imports, no need for a hook or collect_data_files i think.
adding coreschema to hidden imports was already tried.
Anyways i tried to create a simple hook:

```
from PyInstaller.utils.hooks import collect_data_files

hiddenimports = ["coreschema"]

datas = collect_data_files('coreschema')
```

which is what other simple hooks look like, inside the Pyinstaller repository. but then i get a strange error:

pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application
[9944] Failed to execute script 'hook-coreschema' due to unhandled exception!

my hook needs pyinstaller? not sure what that means.

**Comment by rokm** [comment]
> I am not sure it is a simple problem of coreschema bundling.
> That would be easy by just adding coreschema to the hidden imports, no need for a hook or collect_data_files

hiddenimports collects python modules, not data files.


> pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application
> [9944] Failed to execute script 'hook-coreschema' due to unhandled exception!

Sounds like you created a runtime hook instead of standard, build-time hook.

---

Create a directory called `extra-hooks` and create the following file inside it:
```python
# extra-hooks/hook-coreschema.py
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('coreschema')
```

Then pass the directory to pyinstaller via `--additional-hooks-dir`, e.g.
```
pyinstaller --clean --noconfirm --additional-hooks-dir extra-hooks program.py
```

**Comment by kostasmarkakis** [comment]
yes you are absolutelly correct.
i am using a spec file so in addition to hookspath i added the name of the hook to the runtime_hooks.
in all fairness this is not properly documended. if you want a build type hook you just pass the path to the hookspath  in the spec file and it apparently runs all the hooks it finds inside. 
anyway, problem solved thanks
