### ISSUE TITLE
[MacOS] maximum recursion depth exceeded at Runtime

### ISSUE THREAD

**Issue by RobinFrcd** [pyinstaller/pyinstaller#7152]
Hi,
The app itself works fine, I tested to compile and run in on Linux.

I'm now trying to compile it from my (M1) mac. I'm getting a `RecursionError: maximum recursion depth exceeded while calling a Python object` while running my app from the console on MacOS.

Here's my `.spec`:
```python
# -*- mode: python ; coding: utf-8 -*-

# Run `pyinstaller pyinstaller.spec` to generate the binary.
import sys
from PyInstaller.utils.hooks import collect_data_files

import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)

block_cipher = None

a = Analysis(
    ["app.py"],
    pathex=["."],
    binaries=[],
    datas=[
        *collect_data_files("grapheme"),
    ],
    hiddenimports=["pydicom.encoders.gdcm", "pydicom.encoders.pylibjpeg"],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="testapp",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='app'
)

app = BUNDLE(
    coll,
    name='testapp',
    bundle_identifier='com.testapp.app.pkg',
    info_plist={
        'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': False,
        'LSBackgroundOnly': False,
        'NSRequiresAquaSystemAppearance': 'No',
        'CFBundlePackageType': 'APPL',
        'CFBundleSupportedPlatforms': ['MacOSX'],
        'CFBundleIdentifier': 'com.testapp.app.pkg',
        'CFBundleVersion': '0.0.5',
        'LSMinimumSystemVersion': '10.15',
        'LSApplicationCategoryType': 'public.app-category.utilities',
    }
)
```

The installer runs fine, it fails like this once I try to run the binary:

```
  File "PySimpleGUI/PySimpleGUI.py", line 10072, in read
  File "PySimpleGUI/PySimpleGUI.py", line 10143, in _read
  File "PySimpleGUI/PySimpleGUI.py", line 9883, in _Show
  File "PySimpleGUI/PySimpleGUI.py", line 16863, in StartupTK
  File "PySimpleGUI/PySimpleGUI.py", line 16750, in _convert_window_to_tk
  File "PySimpleGUI/PySimpleGUI.py", line 15863, in PackFormIntoFrame
  File "PySimpleGUI/PySimpleGUI.py", line 20928, in _error_popup_with_traceback
  File "PySimpleGUI/PySimpleGUI.py", line 20947, in _error_popup_with_code
  File "PySimpleGUI/PySimpleGUI.py", line 10072, in read
  File "PySimpleGUI/PySimpleGUI.py", line 10143, in _read
  File "PySimpleGUI/PySimpleGUI.py", line 9883, in _Show
  File "PySimpleGUI/PySimpleGUI.py", line 16863, in StartupTK
  File "PySimpleGUI/PySimpleGUI.py", line 16750, in _convert_window_to_tk
  File "PySimpleGUI/PySimpleGUI.py", line 15863, in PackFormIntoFrame
  File "PySimpleGUI/PySimpleGUI.py", line 20928, in _error_popup_with_traceback
  File "PySimpleGUI/PySimpleGUI.py", line 20947, in _error_popup_with_code
  File "PySimpleGUI/PySimpleGUI.py", line 10072, in read
  File "PySimpleGUI/PySimpleGUI.py", line 10143, in _read
  File "PySimpleGUI/PySimpleGUI.py", line 9883, in _Show
  File "PySimpleGUI/PySimpleGUI.py", line 16863, in StartupTK
  File "PySimpleGUI/PySimpleGUI.py", line 16750, in _convert_window_to_tk
  File "PySimpleGUI/PySimpleGUI.py", line 15863, in PackFormIntoFrame
  File "PySimpleGUI/PySimpleGUI.py", line 20928, in _error_popup_with_traceback
  File "PySimpleGUI/PySimpleGUI.py", line 20947, in _error_popup_with_code
  File "PySimpleGUI/PySimpleGUI.py", line 10072, in read
  File "PySimpleGUI/PySimpleGUI.py", line 10143, in _read
  File "PySimpleGUI/PySimpleGUI.py", line 9883, in _Show
  File "PySimpleGUI/PySimpleGUI.py", line 16863, in StartupTK
  File "PySimpleGUI/PySimpleGUI.py", line 16750, in _convert_window_to_tk
  File "PySimpleGUI/PySimpleGUI.py", line 15863, in PackFormIntoFrame
  File "PySimpleGUI/PySimpleGUI.py", line 20928, in _error_popup_with_traceback
  File "PySimpleGUI/PySimpleGUI.py", line 20947, in _error_popup_with_code
  File "PySimpleGUI/PySimpleGUI.py", line 10072, in read
  File "PySimpleGUI/PySimpleGUI.py", line 10143, in _read
  File "PySimpleGUI/PySimpleGUI.py", line 9883, in _Show
  File "PySimpleGUI/PySimpleGUI.py", line 16863, in StartupTK
  File "PySimpleGUI/PySimpleGUI.py", line 16750, in _convert_window_to_tk
  File "PySimpleGUI/PySimpleGUI.py", line 15863, in PackFormIntoFrame
  File "PySimpleGUI/PySimpleGUI.py", line 20928, in _error_popup_with_traceback
  File "PySimpleGUI/PySimpleGUI.py", line 20947, in _error_popup_with_code
  File "PySimpleGUI/PySimpleGUI.py", line 10072, in read
  File "PySimpleGUI/PySimpleGUI.py", line 10143, in _read
  File "PySimpleGUI/PySimpleGUI.py", line 9883, in _Show
  File "PySimpleGUI/PySimpleGUI.py", line 16863, in StartupTK
  File "PySimpleGUI/PySimpleGUI.py", line 16750, in _convert_window_to_tk
  File "PySimpleGUI/PySimpleGUI.py", line 15863, in PackFormIntoFrame
  File "PySimpleGUI/PySimpleGUI.py", line 20928, in _error_popup_with_traceback
  File "PySimpleGUI/PySimpleGUI.py", line 20947, in _error_popup_with_code
  File "PySimpleGUI/PySimpleGUI.py", line 10072, in read
  File "PySimpleGUI/PySimpleGUI.py", line 10143, in _read
  File "PySimpleGUI/PySimpleGUI.py", line 9883, in _Show
  File "PySimpleGUI/PySimpleGUI.py", line 16863, in StartupTK
  File "PySimpleGUI/PySimpleGUI.py", line 16750, in _convert_window_to_tk
  File "PySimpleGUI/PySimpleGUI.py", line 15863, in PackFormIntoFrame
  File "PySimpleGUI/PySimpleGUI.py", line 20928, in _error_popup_with_traceback
  File "PySimpleGUI/PySimpleGUI.py", line 20947, in _error_popup_with_code
  File "PySimpleGUI/PySimpleGUI.py", line 10072, in read
  File "PySimpleGUI/PySimpleGUI.py", line 10143, in _read
  File "PySimpleGUI/PySimpleGUI.py", line 9883, in _Show
  File "PySimpleGUI/PySimpleGUI.py", line 16863, in StartupTK
  File "PySimpleGUI/PySimpleGUI.py", line 16750, in _convert_window_to_tk
  File "PySimpleGUI/PySimpleGUI.py", line 15863, in PackFormIntoFrame
  File "PySimpleGUI/PySimpleGUI.py", line 20905, in _error_popup_with_traceback
  File "traceback.py", line 197, in format_stack
  File "traceback.py", line 211, in extract_stack
  File "traceback.py", line 366, in extract
  File "traceback.py", line 288, in line
  File "linecache.py", line 30, in getline
  File "linecache.py", line 46, in getlines
  File "linecache.py", line 86, in updatecache
RecursionError: maximum recursion depth exceeded while calling a Python object
[37427] Failed to execute script 'app' due to unhandled exception!
```

I'm running PyInstaller 5.5 on Python 3.9:
```
Python 3.9.10 (main, Mar 10 2022, 15:30:30)
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
```

**Comment by rokm** [comment]
That stack trace sure looks like a legit infinite recursion. Based on the names of symbols, I would guess that there's an error, and in response PySimpleGUI tries to open a window with traceback information, which also hits an error; in response to that, it tries to open a window with traceback information, only to hit an error again, and so it gets stuck in infinite loop. The subsequent errors might be caused by source code not being available in the frozen application (so `_error_popup_with_code` fails).

Since you provided no code, you'll have to figure out what's causing the very first error, though.

**Comment by RobinFrcd** [comment]
It's a big package with a lot of private dependencies, it'll be complicated to share it I think :/

However, if I lower the recursion limit, I'm able to see the beginning of the stack trace:

```
PySimpleGUI/PySimpleGUI.py:24842: UserWarning: You are running a VERY old version of tkinter 8.5.9. You cannot use PNG formatted images for example.  Please upgrade to 8.6.x
Mac OS Version is 12.6 and patch enabled so applying the patch
Applyting Mac OS 12.3+ Alpha Channel fix.  Your default Alpha Channel is now 0.99
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "PySimpleGUI/PySimpleGUI.py", line 15854, in PackFormIntoFrame
  File "tkinter/__init__.py", line 4064, in __init__
  File "tkinter/__init__.py", line 4009, in __init__
_tkinter.TclError: couldn't recognize image data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PySimpleGUI/PySimpleGUI.py", line 15854, in PackFormIntoFrame
  File "tkinter/__init__.py", line 4064, in __init__
  File "tkinter/__init__.py", line 4009, in __init__
_tkinter.TclError: couldn't recognize image data
```

Maybe related to https://github.com/PySimpleGUI/PySimpleGUI/issues/153 ?

I use base64 images in `sg.Image()`, could it be the problem ?

**Comment by rokm** [comment]
Looks like `tkinter` is failing to load an image - perhaps an image file that should be loaded in the UI is not collected? Or, it could be this warning about outdated `tkinter`/`Tk` being used `You cannot use PNG formatted images for example`.

I don't think any recent macOS python (python.org nor homebrew) is using the outdated `tkinter`/`Tk` 8.5.x - is this the python3 that's provided by macOS itself (or its command-line XCode tools)?

**Comment by rokm** [comment]
> Maybe related to [PySimpleGUI/PySimpleGUI#153](https://github.com/PySimpleGUI/PySimpleGUI/issues/153) ?
> 
> I use base64 images in `sg.Image()`, could it be the problem ?

If the image is in format not supported by Tk 8.5, then yes. Have you tried running your unfrozen code on macOS?

**Comment by RobinFrcd** [comment]
I'm using latest `3.9.14` from [pyenv](https://github.com/pyenv/pyenv) which ships with Tk 8.5. I found this [Stackoverflow answser](https://stackoverflow.com/a/60469203/5692012) which explains how to install a more up-to-date version of Tk. I just had to enable shared libs to make it work with PyInstaller too:

```
env \
  PATH="$(brew --prefix tcl-tk)/bin:$PATH" \
  LDFLAGS="-L$(brew --prefix tcl-tk)/lib" \
  CPPFLAGS="-I$(brew --prefix tcl-tk)/include" \
  PKG_CONFIG_PATH="$(brew --prefix tcl-tk)/lib/pkgconfig" \
  CFLAGS="-I$(brew --prefix tcl-tk)/include" \
  PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I$(brew --prefix tcl-tk)/include' --with-tcltk-libs='-L$(brew --prefix tcl-tk)/lib -ltcl8.6 -ltk8.6' --enable-shared" \
  pyenv install 3.9.14
```

```
$ python -c 'import tkinter; print(tkinter.TkVersion);'
8.6
```

Everything works now, thanks !
