### ISSUE TITLE
Can not run with pytorch

### ISSUE THREAD

**Issue by ILG2021** [pyinstaller/pyinstaller#7160]
Hello, I use auto-py-to-exe to package a project with pytorch. The error is below:
`Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "process_order.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "ETF\edge_tangent_flow.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "torch\nn\modules\__init__.py", line 1, in <module>
    from .module import Module
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "torch\nn\modules\module.py", line 7, in <module>
    from ..parameter import Parameter
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "torch\nn\parameter.py", line 2, in <module>
    from torch._C import _disabled_torch_function_impl
ModuleNotFoundError: No module named 'torch._C'
`
Anyone know how to solve it ?

**Comment by bwoodsend** [comment]
Add `--hiddenimport=torch._C` to your build command.
