### ISSUE TITLE
PyInstaller not picking up the package sounddevice on Linux (does not exist)

### ISSUE THREAD

**Issue by hash3liZer** [pyinstaller/pyinstaller#7178]
I am using the package `sounddevice` in my script. While building, pyinstaller is not picking the package resources. My specs: 

```
Python: 3.10
Pyinstaller: 5.5
```

I am doing the straightforward compilation: 

```
pyinstaller --noconsole --clean --noconfirm -i "NONE" script.py
```

But this is what i get: 

```python
307 INFO: PyInstaller: 5.5
308 INFO: Python: 3.10.5
309 INFO: Platform: Linux-5.18.0-kali7-amd64-x86_64-with-glibc2.34
309 INFO: wrote /home/hash3lizer/Documents/Projects/212-linux/agent.spec
311 INFO: UPX is available.
311 INFO: Removing temporary files and cleaning cache in /root/.cache/pyinstaller
312 INFO: Extending PYTHONPATH with paths
['/home/hash3lizer/Documents/Projects/212-linux']
pygame 2.1.2 (SDL 2.0.22, Python 3.10.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
1084 INFO: checking Analysis
1084 INFO: Building Analysis because Analysis-00.toc is non existent
1084 INFO: Initializing module dependency graph...
1086 INFO: Caching module graph hooks...
1092 INFO: Analyzing base_library.zip ...
2433 INFO: Loading module hook 'hook-heapq.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
2597 INFO: Loading module hook 'hook-encodings.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
4337 INFO: Loading module hook 'hook-pickle.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
5418 INFO: Caching module dependency graph...
5518 INFO: running Analysis Analysis-00.toc
5539 INFO: Analyzing /home/hash3lizer/Documents/Projects/212-linux/agent.py
5657 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
6003 INFO: Loading module hook 'hook-xml.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
6850 INFO: Loading module hook 'hook-PIL.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
6909 INFO: Loading module hook 'hook-PIL.Image.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
7473 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
7612 INFO: Loading module hook 'hook-xml.dom.domreg.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
8120 INFO: Loading module hook 'hook-platform.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
8135 INFO: Loading module hook 'hook-sysconfig.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
8536 INFO: Loading module hook 'hook-pycparser.py' from '/usr/local/lib/python3.10/dist-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
8966 INFO: Processing pre-find module path hook distutils from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
9514 INFO: Loading module hook 'hook-distutils.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
9556 INFO: Loading module hook 'hook-distutils.util.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
9877 INFO: Loading module hook 'hook-setuptools.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
11863 INFO: Loading module hook 'hook-pkg_resources.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
13363 INFO: Loading module hook 'hook-importlib_metadata.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
13879 INFO: Loading module hook 'hook-packaging.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
14368 INFO: Loading module hook 'hook-jinja2.py' from '/usr/local/lib/python3.10/dist-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
16447 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
17551 INFO: Loading module hook 'hook-numpy.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
18257 INFO: Loading module hook 'hook-numpy._pytesttester.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
18489 INFO: Loading module hook 'hook-difflib.py' from '/usr/local/lib/python3.10/dist-packages/PyInstaller/hooks'...
19813 INFO: Loading module hook 'hook-cv2.py' from '/usr/local/lib/python3.10/dist-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
19960 INFO: Loading module hook 'hook-sounddevice.py' from '/usr/local/lib/python3.10/dist-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/building/build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/building/build_main.py", line 885, in build
    exec(code, spec_namespace)
  File "/home/hash3lizer/Documents/Projects/212-linux/agent.spec", line 7, in <module>
    a = Analysis(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/building/build_main.py", line 410, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/building/build_main.py", line 573, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 268, in add_script
    self._top_script_node = super().add_script(pathname)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1433, in add_script
    self._process_imports(n)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 381, in _safe_import_hook
    return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 428, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 381, in _safe_import_hook
    return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 428, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 381, in _safe_import_hook
    return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 428, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 381, in _safe_import_hook
    return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 428, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 368, in _safe_import_hook
    excluded_imports = self._find_all_excluded_imports(source_module.identifier)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/analysis.py", line 356, in _find_all_excluded_imports
    excluded_imports.update(module_hook.excludedimports)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/imphook.py", line 320, in __getattr__
    self._load_hook_module()
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/depend/imphook.py", line 387, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/compat.py", line 609, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sounddevice.py", line 24, in <module>
    sfp = get_package_paths("sounddevice")
  File "/usr/local/lib/python3.10/dist-packages/PyInstaller/utils/hooks/__init__.py", line 591, in get_package_paths
    raise ValueError(f"Package '{package}' does not exist or is not a package!")
ValueError: Package 'sounddevice' does not exist or is not a package!
```

**Comment by rokm** [comment]
What is the version of `sounddevice` and how did you install it into your environment?

**Comment by rokm** [comment]
Hmm, actually, that doesn't matter. What matters is what version of `pyinstaller-hook-contrib` you are using - you should be using at least [2022.06](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/CHANGELOG.rst#20226-2022-05-26), which had pyinstaller/pyinstaller-hooks-contrib#433 merged. Any older version will likely produce that error.

**Comment by hash3liZer** [comment]
The version of sounddevice package i am using is `0.4.5` and i installed it with pip. The linux distro i am using is Kali 2022. What's strange is if i port back to pyinstaller version 4.9, the pyinstaller is detecting the package but then there's an other error in `hook-pydivert.py` that it was trying to import a module `GetLastError` which i know is available under window machines but not in Linux machines.

**Comment by rokm** [comment]
You need `pyinstaller-hooks-contrib` >= 2022.06 if you want `sounddevice` hook to work with `PyInstaller` >= 5.1. So try running `pip install --upgrade pyinstaller-hooks-contrib` to update it to the latest version.

**Comment by hash3liZer** [comment]
NVM, i think the issue was definitely the older version of `pyinstaller-hook-contrib`. I checked and it was `2022.0`. I upgraded it using pip: 

```
$ pip3 install --upgrade pyinstaller-hooks-contrib==2022.10
```
Worked like a charm. Thanks.
Closing it now.
