### ISSUE TITLE
I use the pyinstaller 5.x version to generate .exe, but AttributeError:__enter__

### ISSUE THREAD

**Issue by DeepSpace98** [pyinstaller/pyinstaller#7186]
```
220525 INFO: Updating manifest in D:\Game\Defect_AI\build\start\start.exe.notanexecutable
220577 INFO: Updating resource type 24 name 1 language 0
220578 INFO: Appending PKG archive to EXE
220601 INFO: Fixing EXE headers
Traceback (most recent call last):
  File "D:\conda\envs\anomalib_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\conda\envs\anomalib_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\conda\envs\anomalib_env\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\building\build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\building\build_main.py", line 885, in build
    exec(code, spec_namespace)
  File "start.spec", line 31, in <module>
    exe = EXE(
  File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\building\api.py", line 545, in __init__
    self.__postinit__()
  File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\building\api.py", line 790, in assemble
    winutils.set_exe_build_timestamp(build_name, build_timestamp)
  File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\utils\win32\winutils.py", line 157, in set_exe_build_timestamp
    with pefile.PE(exe_path, fast_load=True) as pe:
AttributeError: __enter__
```
I don't know this error means what? I use pyinstaller 4.8 can normally work.Can you help me?

**Comment by rokm** [comment]
> ```
> File "D:\conda\envs\anomalib_env\lib\site-packages\PyInstaller\utils\win32\winutils.py", line 157, in set_exe_build_timestamp
>     with pefile.PE(exe_path, fast_load=True) as pe:
> AttributeError: __enter__
> ```

This means the `pefile` package you have installed is too old, and lacks the context manager support. This was introduced in `pefile` `v2022.5.30` - try upgrading your `pefile` package. Seeing that this is anaconda environment, you may need to get the latest version from [conda-forge](https://anaconda.org/conda-forge/pefile) instead of [base anaconda repository](https://anaconda.org/anaconda/pefile).
