### ISSUE TITLE
matplotlib: Child process call to mpl_data_dir() failed

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#7209]
**Describe the bug**
* Which hook/library isn't working?

`matplotlib`, I guess.

* Does the error get raised while building or when running?

Building

**To Reproduce**

A minimal example file:
(Sorry, don't have that yet - cannot reproduce the problem locally, as it happens only on some private GitLab CI)

Error:
```
23339 INFO: Loading module hook 'hook-matplotlib.py' from 'C:\\Python\\Lib\\site-packages\\PyInstaller\\hooks'...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Python\Lib\site-packages\PyInstaller\__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python\Lib\site-packages\PyInstaller\__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python\Lib\site-packages\PyInstaller\building\build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Python\Lib\site-packages\PyInstaller\building\build_main.py", line 885, in build
    exec(code, spec_namespace)
  File "project.spec", line 15, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\building\build_main.py", line 410, in __init__
    self.__postinit__()
  File "C:\Python\Lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Python\Lib\site-packages\PyInstaller\building\build_main.py", line 573, in assemble
    priority_scripts.append(self.graph.add_script(script))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\depend\analysis.py", line 268, in add_script
    self._top_script_node = super().add_script(pathname)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1433, in add_script
    self._process_imports(n)
  File "C:\Python\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\depend\analysis.py", line 381, in _safe_import_hook
    return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\depend\analysis.py", line 428, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "C:\Python\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\depend\analysis.py", line 368, in _safe_import_hook
    excluded_imports = self._find_all_excluded_imports(source_module.identifier)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\depend\analysis.py", line 356, in _find_all_excluded_imports
    excluded_imports.update(module_hook.excludedimports)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\depend\imphook.py", line 320, in __getattr__
    self._load_hook_module()
  File "C:\Python\Lib\site-packages\PyInstaller\depend\imphook.py", line 387, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\compat.py", line 609, in importlib_load_source
    return mod_loader.load_module()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python\Lib\site-packages\PyInstaller\hooks\hook-matplotlib.py", line 22, in <module>
    (mpl_data_dir(), "matplotlib/mpl-data"),
     ^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\isolated\_parent.py", line 368, in wrapped
    return call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\isolated\_parent.py", line 337, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\isolated\_parent.py", line 275, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to mpl_data_dir() failed with:
  File "C:\Python\Lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\hooks\hook-matplotlib.py", line 17, in mpl_data_dir
    import matplotlib
  File "C:\Python\Lib\site-packages\matplotlib\__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Python\Lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Python\Lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Python\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Python\Lib\site-packages\matplotlib\ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Python\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: DLL load failed while importing _path: The specified module could not be found.
```

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version: 3.11
 - Version of `pyinstaller-hooks-contrib`: 2022.11 (the last successful run was 4 days ago, with 2022.10 - but not 100% sure this change is the cause)
 - Version of PyInstaller [e.g. 4.0]: 5.6.1

**Comment by bersbersbers** [comment]
Hmm -  the `matplotlib` hook is in https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-matplotlib.py, right? Could the update of `pyinstaller-hooks-contrib` still have an influence on this one?

**Comment by bwoodsend** [comment]
This is unlikely to have anything to do with the hooks repo. I've move this over to the main one.

**Comment by bwoodsend** [comment]
That stacktrace is insinuating that `import matplotlib` is all it's essentially doing. What does just running `python -c "import matplotlib; print(matplotlib.__file__)"` on your CI server produce?

**Comment by bwoodsend** [comment]
Also, can you check if matplotlib was built from source? You'll see a _Building wheel for matplotlib_ message in the output of `pip install` if it did.

**Comment by bersbersbers** [comment]
@bwoodsend thanks, you are absolutely right - `import matplotlib` fails, even on its own. `matplotlib` is installed from a wheel as far as I can see:

```
Collecting matplotlib>=3.5.0
  Downloading matplotlib-3.6.1-cp311-cp311-win_amd64.whl (7.2 MB)
     ---------------------------------------- 7.2/7.2 MB 30.8 MB/s eta 0:00:00
...
Installing collected packages: funcy, six, shiboken6, pyparsing, pillow, numpy, kiwisolver, humanize, fonttools, cycler, python-dateutil, PySide6-Essentials, packaging, contourpy, matplotlib
Successfully installed PySide6-Essentials-6.4.0.1 contourpy-1.0.6 cycler-0.11.0 fonttools-4.38.0 funcy-1.17 humanize-4.4.0 kiwisolver-1.4.4 matplotlib-3.6.1 numpy-1.23.4 packaging-21.3 pillow-9.3.0 pyparsing-3.0.9 python-dateutil-2.8.2 shiboken6-6.4.0.1 six-1.16.0
```

I also reran the successful run from last Friday, that also failed. There must be something else going on that has changed since last Friday, maybe some PATH settings or similar. I'll close this one as it's unlikely it has to do with `pyinstaller`, thanks anyway!

**Comment by bersbersbers** [comment]
For the record: not sure what changed, but installing VC++ Redistributables fixed it, compare https://stackoverflow.com/a/67073261. In GitLab CI (via `powershell`):

```
    - Invoke-WebRequest https://aka.ms/vs/17/release/vc_redist.x64.exe -OutFile vc_redist.x64.exe
    - .\vc_redist.x64.exe /install /quiet /norestart
    - python -c "import matplotlib; print(matplotlib.__file__)"
```
