### ISSUE TITLE
Can't build app on Windows 11 ARM

### ISSUE THREAD

**Issue by liorp** [pyinstaller/pyinstaller#7218]
## Description of the issue
When building an app on Windows 11 ARM it fails with `Cannot find ('pyi_rth_win32api', 'C:\Temp\agent-venv\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32api.py', 1, 's')`
It fails under pyinstaller 5.6, but works with 5.4.1

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.6```
* Version of Python: 3.10
* Platform: Windows
* How you installed Python: python.org but it is a venv
* Did you also try this on another platform? Does it work there? It works on macos

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
Cannot find ('pyi_rth_win32api', 'C:\Temp\agent-venv\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32api.py', 1, 's')
Traceback (most recent call last):
  File "C:\Users\Lior\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lior\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\__main__.py", line 189, in <module>
    run()
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\building\build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\building\build_main.py", line 885, in build
    exec(code, spec_namespace)
  File "main.spec", line 78, in <module>
    exe = EXE(pyz,
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\building\api.py", line 527, in __init__
    self.pkg = PKG(
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\building\api.py", line 218, in __init__
    self.__postinit__()
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\building\api.py", line 309, in assemble
    CArchiveWriter(self.name, srctoc + mytoc, pylib_name=pylib_name)
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\archive\writers.py", line 313, in __init__
    super().__init__(archive_path, logical_toc)
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\archive\writers.py", line 51, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\archive\writers.py", line 75, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\archive\writers.py", line 347, in add
    code = get_code_object(dest, source)
  File "C:\Temp\agent-venv\lib\site-packages\PyInstaller\building\utils.py", line 606, in get_code_object
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Temp\\agent-venv\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
`PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py` was removed in v5.5 - but perhaps some part of the cached build results from a build with earlier version retained the reference to it. Can you try adding `--clean` flag to your PyInstaller command?

**Comment by bwoodsend** [comment]
This is unlikely to have anything to do with ARM since you'll be running in emulation mode.

**Comment by liorp** [comment]
Damn that was quick. Thank you for your guidance, made me feel a bit rushing to action. Godspeed.
