### ISSUE TITLE
I can't create DATAPREP EDA LIBRARY executable

### ISSUE THREAD

**Issue by daekka** [pyinstaller/pyinstaller#7233]
When I run the following code in Python it works without problems. I use this library:
https://github.com/sfu-db/dataprep

```
import pandas as pd
from dataprep.eda import create_report

#assign data of lists. 
data = {'Name': ['Tom', 'Joseph', 'Krish', 'John'], 'Age': [20, 21, 19, 18]}  
  
#Create DataFrame  
df = pd.DataFrame(data)  
a =  create_report(df)
a.show_browser()
```

But when I run the file (.exe) created with PYINSTALLER the following error occurs:

```
Traceback (most recent call last):
  File "report.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "dataprep\eda\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "dataprep\eda\correlation\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "dataprep\eda\container.py", line 22, in <module>
  File "jinja2\loaders.py", line 325, in __init__
ValueError: The 'dataprep' package was not installed in a way that PackageLoader understands.
```

I have modified the Loaders-Jinja2 library and forced to find the templates but still get errors. For example it does not find the file: country_data.tsv

**Comment by rokm** [comment]
You need to ensure that arbitrary data that comes with an arbitrary python package is collected, by adding [`--collect-data dataprep`](https://pyinstaller.org/en/latest/usage.html#cmdoption-collect-data) to your PyInstaller command (or writing [a hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib) for that package).

---

Although to get your example running on linux, I had to use: `--collect-data dataprep --collect-submodules pycrfsuite --collect-data wordcloud`
