### ISSUE TITLE
Pyinstaller Fails to import pywin32

### ISSUE THREAD

**Issue by jjacobson95** [pyinstaller/pyinstaller#7255]
## Description of the issue

My application uses Docker and Docker SDK (python). These require pywin32 for the exec_run function. For some reason, Pyinstaller does not recognize that these are required or fails to import. When manually trying to import into the python script, all attempts have been unsuccessful.

Attempts - 
import pywintypes
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
from win32ctypes import win32api
import win32api
import win32pipe
import win32process
import pywintypes

I've also tried to use --hidden-imports with the same options to no avail.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.1```
* Version of Python: 3.9.12
* Platform: Windows
* How you installed Python: conda

Error Messages:
```
Exception in thread Thread-2:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 125, in worker
  File "multiprocessing\pool.py", line 48, in mapstar
  File "PW_step.py", line 74, in process
  File "docker\models\containers.py", line 198, in exec_run
    exec_output = self.client.api.exec_start(
  File "docker\utils\decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "docker\api\exec_api.py", line 167, in exec_start
    return self._read_from_socket(res, stream, tty=tty, demux=demux)
  File "docker\api\client.py", line 424, in _read_from_socket
    return consume_socket_output(gen, demux=demux)
  File "docker\utils\socket.py", line 135, in consume_socket_output
    return bytes().join(frames)
  File "docker\api\client.py", line 418, in <genexpr>
    gen = (data for (_, data) in gen)
  File "docker\utils\socket.py", line 92, in frames_iter_no_tty
    (stream, n) = next_frame_header(socket)
  File "docker\utils\socket.py", line 64, in next_frame_header
    data = read_exactly(socket, 8)
  File "docker\utils\socket.py", line 49, in read_exactly
    next_data = read(socket, n - len(data))
  File "docker\utils\socket.py", line 33, in read
    return socket.recv(n)
  File "docker\transport\npipesocket.py", line 22, in wrapped
    return f(self, *args, **kwargs)
  File "docker\transport\npipesocket.py", line 116, in recv
    err, data = win32file.ReadFile(self._handle, bufsize)
pywintypes.error: (109, 'ReadFile', 'The pipe has been ended.')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "UI_V2.py", line 771, in run_workflow
  File "Pipeline_V2.py", line 108, in execute_workflow
  File "PW_step.py", line 128, in run_container
  File "multiprocessing\pool.py", line 364, in map
  File "multiprocessing\pool.py", line 771, in get
pywintypes.error: (109, 'ReadFile', 'The pipe has been ended.')
```

Pyinstaller Readout:
See: **6341 WARNING**
```
99 INFO: PyInstaller: 5.0.1
99 INFO: Python: 3.9.13
115 INFO: Platform: Windows-10-10.0.19042-SP0
131 INFO: wrote C:\Users\jaco059\OneDrive - PNNL\Desktop\Dorrestein_Project\ion-mob-ms\UserInterfaceV2\UI_V2.spec
131 INFO: UPX is not available.
616 INFO: Determining a mapping of distributions to packages...
6341 WARNING: Unable to find package for requirement websocket-client from package docker.
6341 WARNING: Unable to find package for requirement pywin32 from package docker.
6344 INFO: Packages required by docker:
['requests']
6344 INFO: Extending PYTHONPATH with paths
['C:\\Users\\jaco059\\OneDrive - '
 'PNNL\\Desktop\\Dorrestein_Project\\ion-mob-ms\\UserInterfaceV2']
6790 INFO: checking Analysis
6790 INFO: Building Analysis because Analysis-00.toc is non existent
6790 INFO: Initializing module dependency graph...
6790 INFO: Caching module graph hooks...
6806 INFO: Analyzing base_library.zip ...
9073 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
9073 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib'
10966 INFO: Caching module dependency graph...
11157 INFO: running Analysis Analysis-00.toc
11159 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\python.exe
11383 INFO: Analyzing C:\Users\jaco059\OneDrive - PNNL\Desktop\Dorrestein_Project\ion-mob-ms\UserInterfaceV2\UI_V2.py
12859 INFO: Processing pre-find module path hook site from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
12859 INFO: site: retargeting to fake-dir 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\fake-modules'
18346 INFO: Processing pre-safe import module hook six.moves from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
24870 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
29294 INFO: Analyzing hidden import 'pywin32'
29294 ERROR: Hidden import 'pywin32' not found
29294 INFO: Analyzing hidden import 'docker.utils.ports'
29294 INFO: Processing module hooks...
29294 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
29304 INFO: Loading module hook 'hook-pywintypes.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
29707 INFO: Loading module hook 'hook-ttkthemes.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
31039 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31047 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31047 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31047 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31220 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31220 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31336 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31336 INFO: Matplotlib backend selection method: automatic discovery of used backends
31360 INFO: Selected matplotlib backends: ['TkAgg']
31393 INFO: Loading module hook 'hook-matplotlib.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31874 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31874 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31952 INFO: Import to be excluded not found: 'f2py'
31975 INFO: Loading module hook 'hook-numpy._pytesttester.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31975 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
31975 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
32719 INFO: Loading module hook 'hook-pandas.plotting.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
32914 INFO: Loading module hook 'hook-pandas.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
34975 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
34990 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
35403 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
35403 INFO: Loading module hook 'hook-PIL.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
35424 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
35432 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
36700 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
37148 WARNING: Hidden import "pkg_resources.py2_warn" not found!
37209 WARNING: Hidden import "pkg_resources.markers" not found!
37209 INFO: Loading module hook 'hook-pytz.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
37481 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
39351 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
39511 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
39511 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
40234 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
40234 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
40234 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
40234 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
40572 INFO: checking Tree
40572 INFO: Building Tree because Tree-00.toc is non existent
40572 INFO: Building Tree Tree-00.toc
40688 INFO: checking Tree
40688 INFO: Building Tree because Tree-01.toc is non existent
40688 INFO: Building Tree Tree-01.toc
40884 INFO: checking Tree
40884 INFO: Building Tree because Tree-02.toc is non existent
40884 INFO: Building Tree Tree-02.toc
40907 INFO: Loading module hook 'hook-pythoncom.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
41335 INFO: Loading module hook 'hook-win32com.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
C:\Users\jaco059\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\win32com\client\makepy.py:369: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if path is not '' and not os.path.exists(path):
41756 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks'...
41931 INFO: Looking for ctypes DLLs
42019 INFO: Analyzing run-time hooks ...
42030 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
42038 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
42038 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
42038 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py'
42038 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
42048 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
42048 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
42048 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
42048 INFO: Including run-time hook 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
42079 INFO: Looking for dynamic libraries
C:\Users\jaco059\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\building\build_main.py:156: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
45101 INFO: Looking for eggs
45101 INFO: Using Python library C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\python39.dll
45101 INFO: Found binding redirects:
[]
45111 INFO: Warnings written to C:\Users\jaco059\OneDrive - PNNL\Desktop\Dorrestein_Project\ion-mob-ms\UserInterfaceV2\build\UI_V2\warn-UI_V2.txt
45362 INFO: Graph cross-reference written to C:\Users\jaco059\OneDrive - PNNL\Desktop\Dorrestein_Project\ion-mob-ms\UserInterfaceV2\build\UI_V2\xref-UI_V2.html
45556 INFO: Appending 'datas' from .spec
45585 INFO: checking PYZ
45585 INFO: Building PYZ because PYZ-00.toc is non existent
45585 INFO: Building PYZ (ZlibArchive) C:\Users\jaco059\OneDrive - PNNL\Desktop\Dorrestein_Project\ion-mob-ms\UserInterfaceV2\build\UI_V2\PYZ-00.pyz
48653 INFO: Building PYZ (ZlibArchive) C:\Users\jaco059\OneDrive - PNNL\Desktop\Dorrestein_Project\ion-mob-ms\UserInterfaceV2\build\UI_V2\PYZ-00.pyz completed successfully.
48704 INFO: checking PKG
48704 INFO: Building PKG because PKG-00.toc is non existent
48704 INFO: Building PKG (CArchive) UI_V2.pkg
62539 INFO: Building PKG (CArchive) UI_V2.pkg completed successfully.
62743 INFO: Bootloader C:\Users\jaco059\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
62743 INFO: checking EXE
62743 INFO: Building EXE because EXE-00.toc is non existent
62751 INFO: Building EXE from EXE-00.toc
62751 INFO: Copying bootloader EXE to C:\Users\jaco059\OneDrive - PNNL\Desktop\Dorrestein_Project\ion-mob-ms\UserInterfaceV2\dist\UI_V2.exe.notanexecutable
62765 INFO: Copying icon to EXE
62765 INFO: Copying icons from ['C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
62765 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
62765 INFO: Writing RT_ICON 1 resource with 3752 bytes
62765 INFO: Writing RT_ICON 2 resource with 2216 bytes
62765 INFO: Writing RT_ICON 3 resource with 1384 bytes
62765 INFO: Writing RT_ICON 4 resource with 37019 bytes
62765 INFO: Writing RT_ICON 5 resource with 9640 bytes
62765 INFO: Writing RT_ICON 6 resource with 4264 bytes
62765 INFO: Writing RT_ICON 7 resource with 1128 bytes
62765 INFO: Copying 0 resources to EXE
62765 INFO: Embedding manifest in EXE
62765 INFO: Updating manifest in C:\Users\jaco059\OneDrive - PNNL\Desktop\Dorrestein_Project\ion-mob-ms\UserInterfaceV2\dist\UI_V2.exe.notanexecutable
63578 INFO: Updating resource type 24 name 1 language 0
63594 INFO: Appending PKG archive to EXE
83432 INFO: Building EXE from EXE-00.toc completed successfully.

```

**Comment by rokm** [comment]
Where do you see `pywin32` failing to import? What I see are runtime errors caused by a closed pipe, and my first guess would be that this is due to `multiprocessing` being used without `multiprocessing.freeze_support` being called (which you need to do in your frozen program if you (or a package you use) want to use `multiprocessing`).

If you are referring to this line:
> 6341 WARNING: Unable to find package for requirement pywin32 from package docker.

This is likely caused by pywin32 not being installed via conda, or the distribution name being incorrectly declared. But it's unlikely to have any impact on your program, because most of collection is done without conda dist names.

**Comment by jjacobson95** [comment]
I assumed it was pywin32 based on issues I had running this as a python script.  With the recent docker updates, I started getting the same pipe (109) error message in my python script. After resolving dependancies (pywin32), this issue was resolved. No changes were needed to the python script besides imports and environment updates. Then when I rebuilt this using pyinstaller, the pipe 109 error message returned.

I can try to make those changes to `multiprocessing` however, this has never been an issue for the application in past versions.

**Comment by rokm** [comment]
Hmmm, alright. Now that I look at your build log, I see that you are *not* using Anaconda python

>    Output of pyinstaller --version: 5.0.1
>    Version of Python: 3.9.12
>    Platform: Windows
>    How you installed Python: conda

> 99 INFO: Python: 3.9.13
> 9073 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib'

The above path seems imply python from Windows App store.

Is this intended, or do you have multiple python installations on your system, and are using the wrong one?

**Comment by rokm** [comment]
I think this warning:
```
616 INFO: Determining a mapping of distributions to packages...
6341 WARNING: Unable to find package for requirement websocket-client from package docker.
6341 WARNING: Unable to find package for requirement pywin32 from package docker.
```
might be triggered by some extra arguments you are using - perhaps `--collect-all docker`?  But like I said, it is likely harmless.

You can check the `build/<name>/Analysis-00.toc` and see if `pywin32` is detected and its files are being collected. I suspect they are, because I see hooks for `pywintypes`, `pythoncom`, and `win32com` being ran:
> 29304 INFO: Loading module hook 'hook-pywintypes.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
> 40907 INFO: Loading module hook 'hook-pythoncom.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
> 41335 INFO: Loading module hook 'hook-win32com.py' from 'C:\\Users\\jaco059\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...

So whatever the problem is, if you want us to help you debug it, you will need to provide a minimal example that triggers the error, so we can reproduce it on our side.

**Comment by jjacobson95** [comment]
Thank you for the support, I really appreciate it. You are correct, I have multiple python versions installed and it appears I used a different one than I thought.  I'm not positive if it is related to pywin but as I mentioned, the same issue existed when I ran this as a python script until I installed pywin, so I do suspect it.

I've created a minimal example in the attached [repository](https://github.com/jjacobson95/Pyinstaller_Docker_Minimal_Application), please let me know if I could provide any more details or information. To start, I recommend running this in python to see the GUI (just a large button), basic print statements, and docker behavior. Then build and run with pyinstaller. Thanks for looking into this!

**Comment by bwoodsend** [comment]
I just installed that repository into a clean venv environment on Windows and it runs fine for me.

```bat
D:\notebooks\pyi-issues\7255\Pyinstaller_Docker_Minimal_Application(main -> origin)
(env) λ .\dist\FrontEnd\FrontEnd.exe
name is main
name is main
Preparing to run  Test_container_1
name is main
Preparing to run  Test_container_2
name is main
Preparing to run  Test_container_3
Container started:  Test_container_1
Container started:  Test_container_3
Container started:  Test_container_2
Container stopped:  Test_container_1
Container stopped:  Test_container_3
Container stopped:  Test_container_2

D:\notebooks\pyi-issues\7255\Pyinstaller_Docker_Minimal_Application(main -> origin)
(env) λ python -V
Python 3.10.4

D:\notebooks\pyi-issues\7255\Pyinstaller_Docker_Minimal_Application(main -> origin)
(env) λ pip freeze
altgraph==0.17.3
certifi==2022.9.24
charset-normalizer==2.1.1
contourpy==1.0.6
cycler==0.11.0
docker==6.0.1
fonttools==4.38.0
future==0.18.2
idna==3.4
kiwisolver==1.4.4
matplotlib==3.6.2
numpy==1.23.5
packaging==21.3
pandas==1.5.1
pefile==2022.5.30
Pillow==9.3.0
pyinstaller==5.6.2
pyinstaller-hooks-contrib==2022.13
PyMuPDF==1.21.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.6
pywin32==305
pywin32-ctypes==0.2.0
requests==2.28.1
six==1.16.0
tkPDFViewer==0.1
ttkthemes==3.2.2
urllib3==1.26.12
websocket-client==1.4.2
```
