### ISSUE TITLE
Can i change dll directory manually when pyinstaller make .exe file?

### ISSUE THREAD

**Issue by PeterKim1** [pyinstaller/pyinstaller#7272]
Hello. 

I have a problem to run pyinstaller program.

I made pyinstaller .exe file, and no problem existed at same computer.

But when i run .exe file at another computer, problem has arisen.

Traceback (most recent call last):
  File "PyQt_training_main_2.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "Padim_train.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pycuda\autoinit.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pycuda\driver.py", line 59, in <module>
  File "pycuda\driver.py", line 35, in _add_cuda_libdir_to_dll_path
  File "os.py", line 1109, in add_dll_directory
FileNotFoundError: [WinError 3] the system cannot find the path specified: 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2;\\bin'
[80796] Failed to execute script 'PyQt_training_main_2' due to unhandled exception!

I think specified path 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2;\\bin' has ';' in front of \\bin is problem.

So i want to try change dll path from 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2;\\bin' to 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin'.

How can i do this?

**Comment by rokm** [comment]
Judging by the code that raised the exception ([here](https://github.com/inducer/pycuda/blob/e4122c771009cf1a2912c3b58c446fc51afd0116/pycuda/driver.py#L29-L50)), that path is taken from `CUDA_PATH` environment variable, and then `\bin` is added to it. So if there is a `;` in the resulting path, this probably means that your path in `CUDA_PATH` environment variable has `;` at the end, and you should clean it up.
