### ISSUE TITLE
The problem with termux and pyinstaller

### ISSUE THREAD

**Issue by Wendors** [pyinstaller/pyinstaller#7283]
When using python3.11 and pyinstaller 5.6.2 an an error occurs 
pyinstaller test.py                     626 INFO: PyInstaller: 5.6.2
626 INFO: Python: 3.11.0                    643 INFO: Platform: Linux-4.14.186+-aarch64-with-libc
644 INFO: wrote /data/data/com.termux/files/home/test.spec                              648 INFO: UPX is not available.
652 INFO: Extending PYTHONPATH with paths   ['/data/data/com.termux/files/home']        1357 INFO: checking Analysis
1357 INFO: Building Analysis because Analysis-00.toc is non existent                    1358 INFO: Initializing module dependency graph...                                      1370 INFO: Caching module graph hooks...    1427 INFO: Analyzing base_library.zip ...
6260 INFO: Loading module hook 'hook-heapq.py' from '/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/hooks'...                                         6577 INFO: Loading module hook 'hook-encodings.py' from '/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/hooks'...                                     12490 INFO: Loading module hook 'hook-pickle.py' from '/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/hooks'...
20130 INFO: Caching module dependency graph...                                          20466 INFO: running Analysis Analysis-00.toc
Traceback (most recent call last):            File "/data/data/com.termux/files/usr/bin/pyinstaller", line 8, in <module>
    sys.exit(run())                                      ^^^^^                            File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/__main__.py", line 179, in run                         run_build(pyi_config, spec_file, **vars(args))                                        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/__main__.py", line 60, in run_build                    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 885, in build            exec(code, spec_namespace)
  File "/data/data/com.termux/files/home/test.spec", line 7, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 410, in __init__         self.__postinit__()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__     self.assemble()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 553, in assemble
    bindepend.Dependencies([('', python, '')], manifest=depmanifest, redirects=self.binding_redirects)[1:]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/depend/bindepend.py", line 289, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/depend/bindepend.py", line 548, in selectImports
    dlls = getImports(pth)                             ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/depend/bindepend.py", line 791, in getImports          return _getImports_ldd(pth)
           ^^^^^^^^^^^^^^^^^^^^               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/depend/bindepend.py", line 615, in _getImports_ldd
    p = subprocess.run(['ldd', pth], stderr=subprocess.PIPE, stdout=subprocess.PIPE, universal_newlines=True)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 546, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^          File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1022, in __init__                                           self._execute_child(args, executable, preexec_fn, close_fds,                          File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1897, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ldd'

**Comment by rokm** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'ldd'

You need to install `ldd` on your termux system. While you're at it, make sure `binutils` are installed as well.
