### ISSUE TITLE
Please fix this Error

### ISSUE THREAD

**Issue by AswAstropyYt** [pyinstaller/pyinstaller#7297]
Dear Pyinstaller Community!, I am just a python programmer and I want make my programm  py to exe I used your module called Pyinstaller in Kali Linux but your module is making errors. Can you fix  the error? 
Error:
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/kali/Desktop/HypoTitan /hyTitanTerminal/HypoTitanTerminal.spec", line 6, in <module>
    a = Analysis(['HypoTitanTerminal.py'],
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 243, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 348, in assemble
    self.graph = initialize_modgraph(
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/analysis.py", line 613, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1473, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1657, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale

THANKS!
Newest Version

**Comment by rokm** [comment]
> PyInstaller==3.5+498e6ee058'

You are using old PyInstaller version, which is incompatible with the (newer) python version that you are using (presumably python 3.10 or later).

**Comment by AswAstropyYt** [comment]
I use python 3.10

**Comment by rokm** [comment]
> I use python 3.10

Yes, and PyInstaller 3.5 (which was released in July 2019, long before python 3.10 was released) is not compatible with python 3.10. The first PyInstaller version with python 3.10 support was PyInstaller 4.6. If your PyInstaller 3.5 is packaged by Kali linux, you'll have to ask them to update their packages.

**Comment by AswAstropyYt** [comment]
Okay! thanks!
