### ISSUE TITLE
ImportError : Dll load failed while importing QtCore: the [14292] Failed to execute scripts due to unhandled exception

### ISSUE THREAD

**Issue by samuelokpor** [pyinstaller/pyinstaller#7311]
ImportError : Dll load failed while importing QtCore: the [14292] Failed to execute scripts due to unhandled exception.

i am trying to convert my python script to an exe but gives me this error when i run the application

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by samuelokpor** [comment]
pyinstaller version : 5.6.2
pyinstaller-hooks-contrib: 2022.13
python version: 3 .8.5
platform : Windows 10
python installed from anaconda: conda base


pyqt5: 5.15.3
pyqt5- plugine 5.15.3.2.2
pyqt5-qt 5.15.2
pyqt5-sip  12.11.0
pyqt5-tools  5.15.3.3.0.3
pyqtwebengine   5.15.3
pyqtwebengine-qt  5.15.2


these are all my dependencies used at this time, i suspect its a dependency conflict, however it converted part of my python script to exe and was running successfully, when i include the deeplearning part of my python script, it fails to run succesfully.

[22432] Warning: file already exists but should not: C:\Users\.......\torch\_C.cp38-win_amd64.pyd
[22432] Warning: file already exists but should not: C:\Users\.......\torch\_C_flatbuffer.cp38-win_amd64.pyd
Traceback (most recent call last):
     File "mypythonscript.py",line 1,  in <module>
         From PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL Load  failed while importing QtCore: The specidied procedure could not be found.
[22040] Failed to execute script 'mypythonscript' due to unhandled exception


again, because i had to locate the root cause, i had to split my code into bits, it successfully converted and ran as an exe, the non deep learning part, as soon as i include the deep learning codes. this error came out

**Comment by rokm** [comment]
The deep learning part is using `torch`? In that case, if you try to freeze the following example
```python
# example1.py
from PyQt5 import QtCore, QtGui, QtWidgets
print("Hello")
```
in your environment, it works? And if you modify it into
```python
# example2.py
from PyQt5 import QtCore, QtGui, QtWidgets
import torch
print("Hello")
```
it stops working and gives you that error?

If that's the case, can you freeze both (in **onedir** mode instead of onefile, to make it easier to debug), archive both `build` and `dist` directories and upload them somewhere so we can take a look at them?

Also, if python is conda base, how are pyqt5* and torch installed? Via conda or via pip?

**Comment by samuelokpor** [comment]
pyqt5 and torch is installed via pip 

remember the code works perfectly inside my vscode as a .py script, however errors arise when coverted to .exe

**Comment by rokm** [comment]
> remember the code works perfectly inside my vscode as a .py script, however errors arise when coverted to .exe

That's why we're trying to find a minimal working and minimal non-working examples, so we can isolate the problem (which I suspect is combination of conda and pip, because PyQt5 per-se works on our CI).

**Comment by samuelokpor** [comment]
how should i install my dependencies via conda or via pip?

**Comment by rokm** [comment]
Can you first try freezing the examples that I gave you in your existing environment, to see if they reproduce the problem?

**Comment by samuelokpor** [comment]
i used the --onedir to freeze my script, it reproduced an error :

A RecursionError (maximum recursion depth exceeded), i followed the instructions and added a line to my spec file and try to build the program using my .spec file, this other error came out:


Error loading Python Dll
''D:\....\myprogram\python38.dll'.
LoadLibrary: The specified module could not be found.

**Comment by rokm** [comment]
> ```
> Error loading Python Dll ''D:....\myprogram\python38.dll'. 
> LoadLibrary: The specified module could not be found.
> ```

Failing to load python shared library in onedir build usually means that you're either trying to run executable in `build\myprogram\` instead of `dist\myprogram\`, or you've copied the executable somewhere else without copying the accompanying files.

But I've asked you to freeze the two examples that I gave you, not your script. Do those work when frozen in your environment or not?

**Comment by samuelokpor** [comment]
how can i freeze in my current environment should i make all dependencies in a text file then pip freeze requirements text?

**Comment by bwoodsend** [comment]
No, just run `pyinstaller example1.py` in your conda base environment like you did with your own project.

**Comment by samuelokpor** [comment]
i have just run the program as you instructed, i am currently not using an environment,working on my local computer using vscode. i ran the code pyinstaller myprogram.py, the executable is found in build/myprogram.py yet still dont run successfully. 

no error message this time, runs quickly and terminates.

**Comment by rokm** [comment]
The executable should be in the dist directory, not the build one. Also, how were you running the executable? If you run by double-clicking it, then yes, it should "close" immediately, even if there is an error. Try running it from command prompt, so you can see the output in the console...

**Comment by samuelokpor** [comment]
after much updates tomy programe, the executable is now in the dist directory. it shows that my gpu is enagaged by showing my cuda properties then it produces an error.

importError: DLL load failed while importing _iterative: the specified module could not be found.

could this _iterative error be due to a recursion limit error?

**Comment by rokm** [comment]
> could this _iterative error be due to a recursion limit error?

If you successfully mitigated the recursion limit error by increasing the recursion limit, then I don't think so.

> importError: DLL load failed while importing _iterative: the specified module could not be found.

This probably means that a dependency of `_iterative` (which is probably an extension) is not properly collected. Could also be that the dependencies of `_iterative` are not discovered at runtime, which might happen if you use conda python 3.8 or 3.9 (which use patched version of `os.add_dll_directory`) in combination with PyPI wheels that use `os.add_dll_directory`.

But either way, you are providing insufficient details for us to guess what is really going on (e.g., at least full error backtrace).

**Comment by samuelokpor** [comment]
this is the full stack error
Traceback (most recent call last):
  File "tensorflow_io\core\python\ops\__init__.py", line 95, in <module>
  File "tensorflow_io\core\python\ops\__init__.py", line 68, in _load_library
NotImplementedError: unable to open file: libtensorflow_io_plugins.so, from paths: ['tensorflow_io\\core\\python\\ops\\libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: 'tensorflow_io\\\\core\\\\python\\\\ops\\\\libtensorflow_io_plugins.so'"]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "error7.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "object_detection\builders\model_builder.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "object_detection\meta_architectures\deepmac_meta_arch.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tensorflow_io\__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tensorflow_io\core\python\api\v0\__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tensorflow_io\core\python\ops\__init__.py", line 98, in <module>
  File "tensorflow_io\core\python\ops\__init__.py", line 68, in _load_library
NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['tensorflow_io\\core\\python\\ops\\libtensorflow_io.so']
caused by: ['tensorflow_io\\core\\python\\ops\\libtensorflow_io.so not found']

**Comment by rokm** [comment]
You'll need to ensure that this missing file (`tensorflow_io\core\python\ops\libtensorflow_io.so`) is collected. 

We do not have a hook for `tensorflow_io` package, so it is expected that there are files missing...

**Comment by bwoodsend** [comment]
This isn't a support service. Either provide us with a concise and reproducible bug report (without unsuppoted conda environments in the mix) or stop leeching on developer's time.
