### ISSUE TITLE
Kivy 2.1.0 with Pyinstaller 5.7.0 kivy\logger.py RecursionError

### ISSUE THREAD

**Issue by Marcinosoft** [pyinstaller/pyinstaller#7329]
I did upgrade from Pyinstaller 5.6.2 to 5.7.0 to make exe of Kivy 2.1.0 project based on Python 3.8 on Windows 10 x64 Pro.

    pip install -U pyinstaller==5.7.0
    pip install -U pyinstaller-hooks-contrib==2022.14

Exe produced by Pyinstaller 5.7.0 ends with following exceptions after run:
244 times:

	Traceback (most recent call last):
	  File "logging\__init__.py", line 1088, in emit
	AttributeError: 'NoneType' object has no attribute 'write'

	During handling of the above exception, another exception occurred:

then:

	File "main.py", line 1, in <module>
	File "<frozen importlib._bootstrap>", line 991, in _find_and_load
	File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
	File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
	File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
	File "kivy\__init__.py", line 509, in <module>
	File "logging\__init__.py", line 1446, in info
	File "logging\__init__.py", line 1589, in _log
	File "logging\__init__.py", line 1599, in handle
	File "logging\__init__.py", line 1661, in callHandlers
	File "logging\__init__.py", line 954, in handle
	File "kivy\logger.py", line 257, in emit

then 242 times:

	File "kivy\logger.py", line 338, in write
	File "logging\__init__.py", line 1458, in warning
	File "logging\__init__.py", line 1589, in _log
	File "logging\__init__.py", line 1599, in handle
	File "logging\__init__.py", line 1661, in callHandlers
	File "logging\__init__.py", line 954, in handle
	File "logging\__init__.py", line 1093, in emit
	File "logging\__init__.py", line 1006, in handleError

and the end of exception is:

	File "kivy\logger.py", line 291, in format
	File "copy.py", line 172, in deepcopy
	File "copy.py", line 264, in _reconstruct
	RecursionError: maximum recursion depth exceeded

My main.spec file:

	# -*- mode: python ; coding: utf-8 -*-
	from kivy_deps import sdl2, glew, gstreamer

	block_cipher = None

	a = Analysis(
		['main.py'],
		pathex=[],
		binaries=[],
		datas=[],
		hiddenimports=[],
		hookspath=[],
		hooksconfig={},
		runtime_hooks=[],
		excludes=['kivy.core.video.video_gstplayer', 'kivy.lib.gstplayer', 'kivy.core.audio.audio_gstplayer'],
		win_no_prefer_redirects=False,
		win_private_assemblies=False,
		cipher=block_cipher,
		noarchive=False,
	)
	pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

	exe = EXE(
		pyz,
		a.scripts,
		a.binaries,
		a.zipfiles,
		a.datas,
		*[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
		[],
		name='main',
		debug=False,
		bootloader_ignore_signals=False,
		strip=False,
		upx=True,
		upx_exclude=[],
		runtime_tmpdir=None,
		console=False,
		disable_windowed_traceback=False,
		argv_emulation=False,
		target_arch=None,
		codesign_identity=None,
		entitlements_file=None,
	)

My main.py:

	from kivy.app import App
	import os
	import sys
	from kivy.resources import resource_add_path, resource_find

	if hasattr(sys, '_MEIPASS'):
		resource_add_path(os.path.join(sys._MEIPASS))

	class MyApp(App):
		pass

	MyApp().run()

Requirements:

	pip install -U kivy[full]==2.1.0 pyinstaller==5.7.0 pyinstaller-hooks-contrib==2022.14

Exactly same Kivy project exe run's fine after downgrade Pyinstaller to:

    pip install -U pyinstaller==5.6.2
    pip install -U pyinstaller-hooks-contrib==2022.13

or by change:

	console=True,

within spec file.

BTW. Increasing recursion limit using sys.setrecursionlimit() doesn't help. Same issue no matter how huge limit is set.

**Comment by lordwelch** [comment]
I tried your example and it appeared to run correctly on macOS
[Terminal Saved Output.txt](https://github.com/pyinstaller/pyinstaller/files/10250054/Terminal.Saved.Output.txt)

**Comment by bwoodsend** [comment]
This is because PyInstaller no longer creates a fake `sys.stdout`/`sys.stderr` in windowed mode. Instead, both are left as `None` which matches what `pythonw.exe` does. If kivy.logger blindly writes to `sys.stderr` without first checking that it's there then this is kivy's bug.
