### ISSUE TITLE
Windows: Namespace Gtk not Available when Building PyGObject from Source with pip

### ISSUE THREAD

**Issue by danyeaw** [pyinstaller/pyinstaller#7333]
## Description of the issue
On Windows, I am using [gvsbuild](https://github.com/wingtk/gvsbuild) to build GTK 4 and Cairo. Optionally, it can also build PyGObject and pycairo using `python -m build` including creating wheels.

1. If I install PyGObject and pycairo with ` pip install --no-binary :pycairo: pycairo pygobject pyinstaller` then when I freeze the app I am getting a `ValueError: Namespace Gtk not Available` error. The reason I am using the `--no-binary` option is because pycairo has wheels on PyPI which are statically built against Cairo. This won't work with GTK because they need to dynamically linked together.
2. If I build the wheels using gvsbuild and then install them with `pip install (Resolve-Path C:\gtk-build\build\x64\release\*\dist\*.whl)` then the frozen app works great.

The differences between 1 and 2 above is that 1 is missing the following files:
```
api-ms-win-crt-multibyte-l1-1-0.dll
cairo-2.dll
cairo-gobject-2.dll
cairo-script-interpreter-2.dll
epoxy-0.dll
fontconfig-1.dll
freetype-6.dll
fribidi-0.dll
gdk_pixbuf-2.0-0.dll
gi_typelibs
graphene-1.0-0.dll
gspawn-win64-helper-console.exe
gspawn-win64-helper.exe
gtk-4-1.dll
harfbuzz-gobject.dll
harfbuzz.dll
jpeg62.dll
lib
libexpat.dll
libpng16.dll
libxml2.dll
pango-1.0-0.dll
pangocairo-1.0-0.dll
pangoft2-1.0-0.dll
pangowin32-1.0-0.dll
pixman-1-0.dll
rsvg-2.0-vs17.dll
share
tiff.dll
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.7.0 (latest develop)```
* Version of Python: 3.11.1
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Yes, works fine in macOS and Linux

Environmental variables set:
1. `C:\gtk-build\gtk\x64\release\bin` is in the `$env:Path`
2. `$env:INCLUDE = C:\gtk-build\gtk\x64\release\include;C:\gtk-build\gtk\x64\release\include\cairo;C:\gtk-build\gtk\x64\release\include\glib-2.0;C:\gtk-build\gtk\x64\release\include\gobject-introspection-1.0;C:\gtk-build\gtk\x64\release\lib\glib-2.0\include;`
4. `$env:LIB = C:\gtk-build\gtk\x64\release\lib`

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import os

os.add_dll_directory("C:\\gtk-build\\gtk\\x64\\release\\bin")
import cairo
import gi

gi.require_version("Gtk", "4.0")
from gi.repository import Gtk

SIZE = 30


def bowtie(ctx):
    ctx.move_to(0, 0)
    ctx.rel_line_to(2 * SIZE, 2 * SIZE)
    ctx.rel_line_to(-2 * SIZE, 0)
    ctx.rel_line_to(2 * SIZE, -2 * SIZE)
    ctx.close_path()


def draw_shapes(ctx, x, y):
    ctx.save()
    ctx.new_path()
    ctx.translate(x + SIZE, y + SIZE)
    bowtie(ctx)
    ctx.stroke()
    ctx.restore()


def draw(da, ctx, w, h, data):
    ctx.set_source_rgb(0, 0, 0)

    ctx.set_line_width(SIZE / 4)
    ctx.set_tolerance(0.1)

    ctx.set_line_join(cairo.LINE_JOIN_ROUND)
    draw_shapes(ctx, 0, 0)


def on_activate(app):
    win = Gtk.ApplicationWindow(application=app, title="GTK4 Bowtie")

    drawingarea = Gtk.DrawingArea()
    drawingarea.set_draw_func(draw, None)
    win.set_child(drawingarea)
    win.present()


app = Gtk.Application()
app.connect("activate", on_activate)

app.run(None)
```

### Stacktrace / full error message

```
(.venv) PS C:\Users\dan\Projects\pycairo-example> .\dist\main\main.exe
[12112] PyInstaller Bootloader 5.x
[12112] LOADER: executable is C:\Users\dan\Projects\pycairo-example\dist\main\main.exe
[12112] LOADER: homepath is C:\Users\dan\Projects\pycairo-example\dist\main
[12112] LOADER: _MEIPASS2 is NULL
[12112] LOADER: archivename is C:\Users\dan\Projects\pycairo-example\dist\main\main.exe
[12112] LOADER: Cookie found at offset 0x2A24E5
[12112] LOADER: No need to extract files to run; setting extractionpath to homepath
[12112] LOADER: SetDllDirectory(C:\Users\dan\Projects\pycairo-example\dist\main)
[12112] LOADER: Already in the child - running user's code.
[12112] LOADER: Python library: C:\Users\dan\Projects\pycairo-example\dist\main\python311.dll
[12112] LOADER: Loaded functions from Python library.
[12112] LOADER: Manipulating environment (sys.path, sys.prefix)
[12112] LOADER: sys.prefix is C:\Users\dan\Projects\pycairo-example\dist\main
[12112] LOADER: Pre-init sys.path is C:\Users\dan\Projects\pycairo-example\dist\main\base_library.zip;C:\Users\dan\Projects\pycairo-example\dist\main\lib-dynload;C:\Users\dan\Projects\pycairo-example\dist\main
[12112] LOADER: Setting runtime options
[12112] LOADER: Initializing python
[12112] LOADER: Overriding Python's sys.path
[12112] LOADER: Post-init sys.path is C:\Users\dan\Projects\pycairo-example\dist\main\base_library.zip;C:\Users\dan\Projects\pycairo-example\dist\main\lib-dynload;C:\Users\dan\Projects\pycairo-example\dist\main
[12112] LOADER: Setting sys.argv
[12112] LOADER: setting sys._MEIPASS
[12112] LOADER: importing modules from CArchive
[12112] LOADER: extracted struct
[12112] LOADER: running unmarshalled code object for struct...
[12112] LOADER: extracted pyimod01_archive
[12112] LOADER: running unmarshalled code object for pyimod01_archive...
[12112] LOADER: extracted pyimod02_importers
[12112] LOADER: running unmarshalled code object for pyimod02_importers...
[12112] LOADER: extracted pyimod03_ctypes
[12112] LOADER: running unmarshalled code object for pyimod03_ctypes...
[12112] LOADER: extracted pyimod04_pywin32
[12112] LOADER: running unmarshalled code object for pyimod04_pywin32...
[12112] LOADER: Installing PYZ archive with Python modules.
[12112] LOADER: PYZ archive: PYZ-00.pyz
[12112] LOADER: Running pyiboot01_bootstrap.py
[12112] LOADER: Running pyi_rth_inspect.py
[12112] LOADER: Running pyi_rth_gtk.py
[12112] LOADER: Running pyi_rth_pkgutil.py
[12112] LOADER: Running pyi_rth_gi.py
[12112] LOADER: Running pyi_rth_pkgres.py
[12112] LOADER: Running main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    gi.require_version("Gtk", "4.0")
  File "gi\__init__.py", line 126, in require_version
ValueError: Namespace Gtk not available
[12112] Failed to execute script 'main' due to unhandled exception!
[12112] LOADER: OK.
[12112] LOADER: Manually flushing stdout and stderr
[12112] LOADER: Cleaning up Python interpreter.
```

**Comment by rokm** [comment]
> The differences between 1 and 2 above is that 1 is missing the following files:
> 
> ```
> ...
> gi_typelibs
> ...
> ```

So the typelibs are not collected at all?

**Comment by rokm** [comment]
> ```
> os.add_dll_directory("C:\\gtk-build\\gtk\\x64\\release\\bin")
> ```

Does your unfrozen script work in that environment if you take this `os.add_dll_directory` call out? If it does not, I see no reason for PyInstaller's hooks to work, either (although it should if you have `C:\gtk-build\gtk\x64\release\bin` in `PATH`).

**Comment by danyeaw** [comment]
Thanks for the response @rokm! No it doesn't work without the `os` call in Python 3.8+ due to Python no longer searching for DLLs in the path automatically. This issue exists in PyGObject and pycairo. I have an open merge request to fix the one in PyGObject here:
https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/211

If you think that is the issue, then that is also why it works with the gvsbuild wheels, since gvsbuild patches this downstream.

Would it be possible to manually add an extra DLL search path with PyInstaller?

**Comment by rokm** [comment]
I think the problem is that without the DLL path being added to search directory, the import attempts made in the hooks fail (same as they would fail in your unfrozen scrip), and therefore hooks become no-op. PyInstaller itself would honor `PATH` during later binary dependency analysis (although with python >= 3.8, perhaps it really *shouldn't*...), but that makes no difference here because the preceding analysis step failed to pick up GI typelibs and referenced Gtk DLLs to hooks being no-op.

I don't see a clean way to solve this. I suppose we could take the paths passed via `--paths` PyInstaller argument and also add them to DLL search path via `os.add_dll_directory` call (on Windows and for python >= 3.8). This feels just about as dirty as the existence of the `--paths` argument itself, but I suppose it's still better than having an *additional* command line argument for extending DLL search paths.

I suppose since this is not really our bug, I would really prefer seeing it handled outside of PyInstaller's codebase; for example, if you created a simple wrapper for `PyInstaller` that calls the `os.add_dll_directory` with paths specific to your build environment, and then calls `PyInstaller.__main__.run()`.

**Comment by rokm** [comment]
Now that I thought about this some more, I think none of the approaches I outlined above will really work.

That's because the hooks perform their analysis in an isolated subprocess, and there's no way to propagate the DLL search paths added via `os.add_dll_directory` into subprocesses. We could try to propagate the paths set via `--paths`, but that seems a lot of hassle for what is essentially a broken package.

**Comment by danyeaw** [comment]
Thanks @rokm! I will take another run at trying to convince the upstream projects to fix this 👍
