### ISSUE TITLE
No such file or directory TEMP\MEIxxxx folder

### ISSUE THREAD

**Issue by superkido511** [pyinstaller/pyinstaller#7335]
Hello, I built a simple app to load a model from transformers library. The build seems fine but when I run the exe file I get this error 
```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "transformers\utils\import_utils.py", line 896, in __getattr__
  File "transformers\utils\import_utils.py", line 895, in __getattr__
  File "transformers\utils\import_utils.py", line 910, in _get_module
RuntimeError: Failed to import transformers.models.wav2vec2.processing_wav2vec2 because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI63602\\transformers\\__init__.py'
[17060] Failed to execute script 'app' due to unhandled exception!
```

Here is my script

app.py
```
from huggingface_hub import repository, hf_api
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
import librosa
import torch
import sounddevice
from scipy.io.wavfile import write
import tkinter as Tkinter
import tkinter.messagebox
from thefuzz import fuzz
from thefuzz import process

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

processor = Wav2Vec2Processor.from_pretrained("khanhld/wav2vec2-base-vietnamese-160h")
model = Wav2Vec2ForCTC.from_pretrained("khanhld/wav2vec2-base-vietnamese-160h")
model.to(device)

def record(second=6, fs=16000, outfile='out.wav'):
    import sounddevice
    from scipy.io.wavfile import write
    record_voice = sounddevice.rec( int ( second * fs ) , samplerate = fs , channels = 2 )
    sounddevice.wait()
    write(outfile,fs,record_voice)

def transcribe(wav):
    input_values = processor(wav, sampling_rate=16000, return_tensors="pt").input_values
    logits = model(input_values.to(device)).logits
    pred_ids = torch.argmax(logits, dim=-1)
    pred_transcript = processor.batch_decode(pred_ids)[0]
    return pred_transcript

def get_apps_list(root="C://Users/Admin/Desktop"):
    apps = [x for x in os.listdir(root) if x.endswith('.exe')]
    apps_dict = {}
    for i, x in enumerate(len(apps)):
        apps_dict[i+1] = x
    return apps_dict

def start_word():
    desk = r'C://Users/Admin/Desktop'
    l = os.listdir('C://Users/Admin/Desktop')
    os.startfile(os.path.join(desk, process.extractOne('word', l)[0]))

def start_word():
    desk = r'C://Users/Admin/Desktop'
    l = os.listdir('C://Users/Admin/Desktop')
    os.startfile(os.path.join(desk, process.extractOne('excel', l)[0]))

def search_command(text):
    from unidecode import unidecode
    
    commands = [
        'khoa may',
        'tim kiem',
        'chay phan mem',
        'thoat chuong trinh',
        'soan van ban',
        'soan bang tinh'
    ]
    text = unidecode(text).lower()
    cmd, conf = process.extractOne(text, commands)
    if conf < 80:
        cmd = 'khong ro'
    return cmd

def find_files(filename, search_path=r'C:\Users\Admin'):
    from unidecode import unidecode
    import subprocess
    import os
    subprocess.Popen(f'explorer /root,"search-ms:query={unidecode(filename)}&crumb=folder:{search_path}&"')

def logout():
    import ctypes
    ctypes.windll.user32.LockWorkStation()
    

top = Tkinter.Tk()

show = Tkinter.messagebox.showinfo

def sst():
    record()
    wav, _ = librosa.load('out.wav', sr = 16000)
    text = transcribe(wav)
    return text

def input_cmd():
    command = sst()
    cmd = search_command(command)
    print(cmd)
    return cmd

def helloCallBack():
    cmd = input_cmd()
    if cmd == 'khoa may':
        logout()
    elif cmd == 'tim kiem':
        show( "Hello", r"Hãy đọc file cần tìm kiếm")
        # print("ok")
        cmd = sst()
        print(cmd)
        find_files(cmd)
    elif cmd == 'chay phan mem':
        show( "Hello", r"Hãy đọc tên phần mềm")
        cmd = sst()
        print(cmd)
    elif cmd == 'soan van ban':
        start_word()
    elif cmd == 'soan bang tinh':
        start_excel()
    elif cmd == 'khong ro':
        show( "Hello", r"Hãy đọc lệnh to hơn")
    elif cmd == 'thoat chuong trinh':
        top.destroy()
        
        

B = Tkinter.Button(top, text =r"Ghi âm", command = helloCallBack)

B.pack()
top.mainloop()
```

and my spec file:

```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata

datas=[
    ('khanhld', '.'),
]

datas += collect_data_files('torch')
datas += copy_metadata('torch')
datas += copy_metadata('tqdm')
datas += copy_metadata('requests')
datas += copy_metadata('packaging')
datas += copy_metadata('importlib_metadata')
datas += copy_metadata('regex')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')


block_cipher = None


a = Analysis(
    ['app.py'],
    pathex=['C:\\Users\\Admin\\Anaconda3\\envs\\torch170\\Lib\\site-packages', 'C:\\Users\\Admin\\Anaconda3\\envs\\torch170\\Lib\\site-packages\\torch\\lib'],
    binaries=[],
    datas=datas,
    hiddenimports=['pkg_resources.py2_warn', 'torch'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=True,
    cipher=block_cipher,
    noarchive=False,
)

for d in a.datas:
    if '_C.cp37-win_amd64.pyd' in d[0]:
        a.datas.remove(d)
        break


pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

```

I googled the whole day and fixed some error related to missing package but I can't fix this one. Please help!

**Comment by rokm** [comment]
You need to ensure that `transformers` source code is collected (which is not by default). 

As you are using spec file, you can probably add:
```
datas += collect_data_files('transformers', include_py_files=True, includes=['**/*.py'])
```

**Comment by superkido511** [comment]
> You need to ensure that `transformers` source code is collected (which is not by default).
> 
> As you are using spec file, you can probably add:
> 
> ```
> datas += collect_data_files('transformers', include_py_files=True, includes=['**/*.py'])
> ```

Thanks. I tried this but It didn't work (I also added --clean option). What works for me is moving the whole transformers folder into project dir and add it as resource. Like this:
```
datas=[
    ('khanhld', 'khanhld'),
    ('transformers', 'transformers'),
    ('librosa', 'librosa'),
]
```
Not a perfect solution but It worked for me so I'm good.
