### ISSUE TITLE
Error when building the package `tensorflow-cpu` and `tensorflow-directml-plugin`

### ISSUE THREAD

**Issue by Neizvestnyj** [pyinstaller/pyinstaller#7347]
**System:**

- OS: Windows 10 Pro
- Python: 3.9.15
- tensorflow-cpu: 2.10.0
- tensorflow-directml-plugin: latest
- pyinstaller: latest (from develop branch)

**Error:**
```
Traceback (most recent call last):
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 621, in collect_submodules
    modules, subpackages, on_error = isolated_python.call(_collect_submodules, name, on_error)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<PATH>\anaconda3\envs\direct_ml\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "<PATH>\anaconda3\envs\direct_ml\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<PATH>\anaconda3\envs\direct_ml\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\build_main.py", line 972, in main
    build(specfile, distpath, workpath, clean_build)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\build_main.py", line 894, in build
    exec(code, spec_namespace)
  File "gpu_test.spec", line 6, in <module>
    a = Analysis(
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\build_main.py", line 411, in __init__
    self.__postinit__()
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\build_main.py", line 574, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 269, in add_script
    self._top_script_node = super().add_script(pathname)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1433, in add_script
    self._process_imports(n)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 382, in _safe_import_hook
    return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 429, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 369, in _safe_import_hook
    excluded_imports = self._find_all_excluded_imports(source_module.identifier)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 357, in _find_all_excluded_imports
    excluded_imports.update(module_hook.excludedimports)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\imphook.py", line 320, in __getattr__
    self._load_hook_module()
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\imphook.py", line 387, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\compat.py", line 612, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-tensorflow.py", line 66, in <module>
    hiddenimports = collect_submodules('tensorflow',
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 629, in collect_submodules
    todo.append(subpackage_name)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\isolated\_parent.py", line 244, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 621, in collect_submodules
    modules, subpackages, on_error = isolated_python.call(_collect_submodules, name, on_error)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<PATH>\anaconda3\envs\direct_ml\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "<PATH>\anaconda3\envs\direct_ml\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<PATH>\anaconda3\envs\direct_ml\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\build_main.py", line 972, in main
    build(specfile, distpath, workpath, clean_build)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\build_main.py", line 894, in build
    exec(code, spec_namespace)
  File "gpu_test.spec", line 6, in <module>
    a = Analysis(
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\build_main.py", line 411, in __init__
    self.__postinit__()
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\building\build_main.py", line 574, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 269, in add_script
    self._top_script_node = super().add_script(pathname)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1433, in add_script
    self._process_imports(n)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 382, in _safe_import_hook
    return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 429, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 369, in _safe_import_hook
    excluded_imports = self._find_all_excluded_imports(source_module.identifier)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\analysis.py", line 357, in _find_all_excluded_imports
    excluded_imports.update(module_hook.excludedimports)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\imphook.py", line 320, in __getattr__
    self._load_hook_module()
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\depend\imphook.py", line 387, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\compat.py", line 612, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-tensorflow.py", line 66, in <module>
    hiddenimports = collect_submodules('tensorflow',
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 629, in collect_submodules
    todo.append(subpackage_name)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\isolated\_parent.py", line 244, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument
```

[All dependencies](https://github.com/pyinstaller/pyinstaller/files/10297610/full_req.txt)
[log.txt](https://github.com/pyinstaller/pyinstaller/files/10297615/log.txt)
[main.spec](https://github.com/pyinstaller/pyinstaller/files/10297621/main.txt)

**Comment by rokm** [comment]
From the attached log:
```
...
2022-12-24 01:54:16.299596: I tensorflow/c/logging.cc:34] DirectML device enumeration: found 1 compatible adapters.
2022-12-24 01:54:16.300245: F tensorflow/c/experimental/stream_executor/stream_executor.cc:808] Non-OK-status: stream_executor::MultiPlatformManager::RegisterPlatform( std::move(cplatform)) status: INTERNAL: platform is already registered with name: "DML"
Traceback (most recent call last):
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 621, in collect_submodules
    modules, subpackages, on_error = isolated_python.call(_collect_submodules, name, on_error)
  File "<PATH>\anaconda3\envs\direct_ml\lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:
```

Looks like our attempt at walking the `tensorflow` submodules triggers this fatal error (presumably this is the DirectML plugin?):
```
2022-12-24 01:54:16.300245: F tensorflow/c/experimental/stream_executor/stream_executor.cc:808] Non-OK-status: stream_executor::MultiPlatformManager::RegisterPlatform( std::move(cplatform)) status: INTERNAL: platform is already registered with name: "DML"
```
which kills the child process, hence subsequent EOF errors in subprocess communication.

**Comment by rokm** [comment]
Hmmm... I seem to be able to reproduce this fatal error with just
```
import PyInstaller.utils.hooks
import tensorflow
```
in interactive python prompt.

Whereas for example 
```
import PyInstaller.utils
import tensorflow
```
works. 

Will look into it.

**Comment by rokm** [comment]
It looks like the problem is this [import of `distutils.sysconfig` in `PyInstaller.depend.bindepend`](https://github.com/pyinstaller/pyinstaller/blob/f57e15ae14d2370cba7a14cfae97d2c29b5c8154/PyInstaller/depend/bindepend.py#L36), which reduces the reproducer to:
```
import distutils.sysconfig
import tensorflow
```
@Neizvestnyj, can you check if this is also the case in your environment?

**Comment by Neizvestnyj** [comment]
> It looks like the problem is this [import of `distutils.sysconfig` in `PyInstaller.depend.bindepend`](https://github.com/pyinstaller/pyinstaller/blob/f57e15ae14d2370cba7a14cfae97d2c29b5c8154/PyInstaller/depend/bindepend.py#L36), which reduces the reproducer to:
> 
> ```
> import distutils.sysconfig
> import tensorflow
> ```
> 
> @Neizvestnyj, can you check if this is also the case in your environment?

just add these imports in the test file?

**Comment by rokm** [comment]
> just add these imports in the test file?

No, create a script with these two lines and run it in your python environment (no PyInstaller involved); or open python interpreter and run these two lines, one after another.

**Comment by Neizvestnyj** [comment]
> > just add these imports in the test file?
> 
> No, create a script with these two lines and run it in your python environment (no PyInstaller involved); or open python interpreter and run these two lines, one after another.
```
>>> import distutils.sysconfig
>>> import tensorflow
2022-12-24 04:16:21.317554: I tensorflow/c/logging.cc:34] Successfully opened dynamic library C:\Users\pikro\anaconda3\envs\direct_ml\Lib\site-packages\tensorflow-plugins/directml/directml.d6f03b303ac3c4f2eeb8ca631688c9757b361310.dll
2022-12-24 04:16:21.318393: I tensorflow/c/logging.cc:34] Successfully opened dynamic library dxgi.dll
2022-12-24 04:16:21.320587: I tensorflow/c/logging.cc:34] Successfully opened dynamic library d3d12.dll
2022-12-24 04:16:21.811621: I tensorflow/c/logging.cc:34] DirectML device enumeration: found 1 compatible adapters.
2022-12-24 04:16:21.812470: F tensorflow/c/experimental/stream_executor/stream_executor.cc:808] Non-OK-status: stream_executor::MultiPlatformManager::RegisterPlatform( std::move(cplatform)) status: INTERNAL: platform is already registered with name: "DML"
```
but the script terminates with the code `Process finished with exit code -1073740791 (0xC0000409)`

**Comment by rokm** [comment]
> > > just add these imports in the test file?
> > 
> > 
> > No, create a script with these two lines and run it in your python environment (no PyInstaller involved); or open python interpreter and run these two lines, one after another.
> 
> ```
> >>> import distutils.sysconfig
> >>> import tensorflow
> 2022-12-24 04:16:21.317554: I tensorflow/c/logging.cc:34] Successfully opened dynamic library C:\Users\pikro\anaconda3\envs\direct_ml\Lib\site-packages\tensorflow-plugins/directml/directml.d6f03b303ac3c4f2eeb8ca631688c9757b361310.dll
> 2022-12-24 04:16:21.318393: I tensorflow/c/logging.cc:34] Successfully opened dynamic library dxgi.dll
> 2022-12-24 04:16:21.320587: I tensorflow/c/logging.cc:34] Successfully opened dynamic library d3d12.dll
> 2022-12-24 04:16:21.811621: I tensorflow/c/logging.cc:34] DirectML device enumeration: found 1 compatible adapters.
> 2022-12-24 04:16:21.812470: F tensorflow/c/experimental/stream_executor/stream_executor.cc:808] Non-OK-status: stream_executor::MultiPlatformManager::RegisterPlatform( std::move(cplatform)) status: INTERNAL: platform is already registered with name: "DML"
> ```
> 
> but the script terminates with the code `Process finished with exit code -1073740791 (0xC0000409)`

Yeah, that's my point exactly. Importing `tensorflow` after importing `distutils.sysconfig` causes Tensorflow to hit that fatal `INTERNAL: platform is already registered with name: "DML"` error, which crashes the python process (or more likely, the fatal message handler calls `abort()` and terminates the process).

So whatever weirdness is going on in there, it is a `tensorflow` issue (or the directml plugin one), and it has nothing really to do with us.

PyInstaller's initialization happens to import `distutils.sysconfig` [here](https://github.com/pyinstaller/pyinstaller/blob/f57e15ae14d2370cba7a14cfae97d2c29b5c8154/PyInstaller/depend/bindepend.py#L36), and therefore analysis that imports `tensorflow` triggers the same issue.

On the other hand, we could probably avoid this problem altogether by not using `distutils.sysconfig.get_python_lib`, since there are better ways to locate the [`pywin32_system32` directory](https://github.com/pyinstaller/pyinstaller/blob/f57e15ae14d2370cba7a14cfae97d2c29b5c8154/PyInstaller/depend/bindepend.py#L53-L56)...

**Comment by bwoodsend** [comment]
> On the other hand, we could probably avoid this problem altogether by not using distutils.sysconfig.get_python_lib, since there are better ways to locate the [pywin32_system32 directory](https://github.com/pyinstaller/pyinstaller/blob/f57e15ae14d2370cba7a14cfae97d2c29b5c8154/PyInstaller/depend/bindepend.py#L53-L56)...

I think so. distutils is set for removal in Python 3.12 (I think) and that whole `getfullnameof()` function looks dubious to me.

**Comment by Neizvestnyj** [comment]
> > > > just add these imports in the test file?
> > > 
> > > 
> > > No, create a script with these two lines and run it in your python environment (no PyInstaller involved); or open python interpreter and run these two lines, one after another.
> > 
> > 
> > ```
> > >>> import distutils.sysconfig
> > >>> import tensorflow
> > 2022-12-24 04:16:21.317554: I tensorflow/c/logging.cc:34] Successfully opened dynamic library C:\Users\pikro\anaconda3\envs\direct_ml\Lib\site-packages\tensorflow-plugins/directml/directml.d6f03b303ac3c4f2eeb8ca631688c9757b361310.dll
> > 2022-12-24 04:16:21.318393: I tensorflow/c/logging.cc:34] Successfully opened dynamic library dxgi.dll
> > 2022-12-24 04:16:21.320587: I tensorflow/c/logging.cc:34] Successfully opened dynamic library d3d12.dll
> > 2022-12-24 04:16:21.811621: I tensorflow/c/logging.cc:34] DirectML device enumeration: found 1 compatible adapters.
> > 2022-12-24 04:16:21.812470: F tensorflow/c/experimental/stream_executor/stream_executor.cc:808] Non-OK-status: stream_executor::MultiPlatformManager::RegisterPlatform( std::move(cplatform)) status: INTERNAL: platform is already registered with name: "DML"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but the script terminates with the code `Process finished with exit code -1073740791 (0xC0000409)`
> 
> Yeah, that's my point exactly. Importing `tensorflow` after importing `distutils.sysconfig` causes Tensorflow to hit that fatal `INTERNAL: platform is already registered with name: "DML"` error, which crashes the python process (or more likely, the fatal message handler calls `abort()` and terminates the process).
> 
> So whatever weirdness is going on in there, it is a `tensorflow` issue (or the directml plugin one), and it has nothing really to do with us.
> 
> PyInstaller's initialization happens to import `distutils.sysconfig` [here](https://github.com/pyinstaller/pyinstaller/blob/f57e15ae14d2370cba7a14cfae97d2c29b5c8154/PyInstaller/depend/bindepend.py#L36), and therefore analysis that imports `tensorflow` triggers the same issue.
> 
> On the other hand, we could probably avoid this problem altogether by not using `distutils.sysconfig.get_python_lib`, since there are better ways to locate the [`pywin32_system32` directory](https://github.com/pyinstaller/pyinstaller/blob/f57e15ae14d2370cba7a14cfae97d2c29b5c8154/PyInstaller/depend/bindepend.py#L53-L56)...

Since you understand this more, could you then open the issue in tensorflow?

**Comment by saulthu** [comment]
I'm having this same problem. [This issue](https://github.com/tensorflow/tensorflow/issues/55497) on TensorFlow GitHub may be a possible resolution, though that leaves us without a work-around until that is resolved -- and it was last updated over one year ago.

**Comment by saulthu** [comment]
As a really horrible work-around for this exact case:

- uninstall tensorflow-directml-plugin
- run pyinstaller
- reinstall tensorflow-directml-plugin
- copy `site-packages\tensorflow-plugins\` to packaged folder `tensorflow\tensorflow-plugins\`

This avoids TF crashing during packaging, which is happening due to the plugin being loaded multiple times (a TF problem).

And to make TensorFlow actually load the plugin, add this code to somewhere very early in your program (of course, before doing the above packaging):
```
import site
site.ENABLE_USER_SITE = True
site.USER_SITE = 'tensorflow'
```

The plugin loading would normally not work in a packaged build due to the way that TF is checking whether to load plugins or not. The problem is that [`tensorflow\__init__.py`](https://github.com/tensorflow/tensorflow/blob/38df17edd258230580415121eba6275cd6c3905e/tensorflow/api_template.__init__.py#L140) will only load plugins if it thinks that the tensorflow package is `_running_from_pip_package()`, so setting `site.USER_SITE = 'tensorflow'` and copying the plugins to the tensorflow folder makes it work. Ew.
