### ISSUE TITLE
`Is not a fat binary!` with `target_arch="universal2"`

### ISSUE THREAD

**Issue by Neizvestnyj** [pyinstaller/pyinstaller#7354]
When I trying to create app for MacOSX with `target_arch="universal2"` I get an error:
```shell
Traceback (most recent call last):
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 971, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 893, in build
    exec(code, spec_namespace)
  File "mac.spec", line 51, in <module>
    coll = COLLECT(
           ^^^^^^^^
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/building/api.py", line 892, in __init__
    self.__postinit__()
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/building/api.py", line 932, in assemble
    fnm = checkCache(
          ^^^^^^^^^^^
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/building/utils.py", line 373, in checkCache
    osxutils.binary_to_target_arch(cachedfile, target_arch, display_name=fnm)
  File "/Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/site-packages/PyInstaller/utils/osx.py", line 312, in binary_to_target_arch
    raise IncompatibleBinaryArchError(f"{display_name} is not a fat binary!")
PyInstaller.utils.osx.IncompatibleBinaryArchError: /Users/neizvestnyj/opt/anaconda3/envs/py_311/lib/python3.11/lib-dynload/zlib.cpython-311-darwin.so is not a fat binary!
```

**System:**

- python: 3.9.15, 3.10.5, 3.11.0
- pyinstaller: develop
- OS: MacOS Monterey 12.3

I know about it https://github.com/actions/setup-python/issues/439 But what should I do to build app for M1/M2 on Intel processor?

**Comment by rokm** [comment]
See the [docs](https://pyinstaller.org/en/stable/feature-notes.html#macos-multi-arch-support).

In order to build `universal2` application, you need your python and all non-pure python packages to be `universal2`. So building under single-arch python environments such as anaconda or Homebrew is out of question.

If your python environment was fully `universal2`, you could at least in theory create a thin `arm64`-only build in it, even on `x86_64`. But in general, you cannot cross-compile for `arm64` in `x86_64` environment. So to build for M1/M2, you need an M1/M2 machine. Similarly, you cannot cross-compile for `x86_64` in `arm64` python environment, but even on M1/M2, you can run a `x86_64` environment and compile for that (and the resulting `x86_64` build will run natively on Intel, and under Rosetta on M1/M2).
