### ISSUE TITLE
Can't using kombu with pyinstaller

### ISSUE THREAD

**Issue by YaroslavPavlovich** [pyinstaller/pyinstaller#7371]
I want to start rabbit consumer using kombu with pyinstaller. Example script:

```
import socket

from kombu import Connection, Exchange, Queue, Consumer

rabbit_url = 'amqp://guest:guest@192.168.1.42:5673/'
conn = Connection(rabbit_url)
exchange = Exchange('exchange', type='direct')
queue = Queue(name='settings', exchange=exchange, routing_key='settings')


def process_message(body, message):
    print('{}'.format(body))
    message.ack()


while True:
    try:
        with Consumer(conn, queues=queue, callbacks=[process_message], accept=["text/plain"]):
            conn.drain_events()
    except socket.timeout:
        pass
```
I installed pyinstaller by pip.
pyinstaller version 5.7.0.
kombu version 4.6.10
I started:
`pyinstaller -D -F -n main -c "main.py"`

In dist folder I get main file
I started it:
`./main`

Result:
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "kombu/connection.py", line 189, in __init__
  File "kombu/transport/__init__.py", line 87, in get_transport_cls
  File "kombu/transport/__init__.py", line 72, in resolve_transport
  File "kombu/utils/imports.py", line 57, in symbol_by_name
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kombu.transport.pyamqp'
[284188] Failed to execute script 'main' due to unhandled exception!
```

**Comment by rokm** [comment]
Current implementation of modulegraph analysis used by PyInstaller cannot automatically pick up imports other than plain "import module_name". Therefore, if you have code that uses different import mechanisms, you need to use [`--hiddenimport`](https://pyinstaller.org/en/stable/usage.html#cmdoption-hidden-import) to specify such modules that end up missing; e.g., `--hiddenimport kombu.transport.pyamqp`. Or, if the packge uses multiple such imports, use [`--collect-submodules kombu`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-submodules) to ensure that all submodules are collected.
