### ISSUE TITLE
cygwin pyinstaller missing win32api

### ISSUE THREAD

**Issue by eychei** [pyinstaller/pyinstaller#7382]
Hi everyone,

cygwin 3.4.3
Python 3.9.10

I do have to following problem:

git clone https://github.com/pyinstaller/pyinstaller
cd bootloader
python ./waf all
python -m pip install .

All works just fine. 

pyinstaller --version 

gives the following error:

$ pyinstaller --version
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 161, in run
    parser = generate_parser()
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 128, in generate_parser
    import PyInstaller.building.build_main
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 28, in <module>
    from PyInstaller.building.api import COLLECT, EXE, MERGE, PYZ
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/api.py", line 26, in <module>
    from PyInstaller.archive.writers import CArchiveWriter, ZlibArchiveWriter
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/archive/writers.py", line 28, in <module>
    from PyInstaller.building.utils import get_code_object, strip_paths_in_code
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/utils.py", line 37, in <module>
    from PyInstaller.utils.win32 import versioninfo, winmanifest, winresource
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/utils/win32/versioninfo.py", line 17, in <module>
    from PyInstaller.compat import win32api
ImportError: cannot import name 'win32api' from 'PyInstaller.compat' (/usr/local/lib/python3.9/site-packages/PyInstaller/compat.py)

Hope someone can help me.

-e

**Comment by eychei** [comment]
I did try some older commits because this was working in 2021 :).

So I tested going back in commits and found the first version which is still working!

https://github.com/pyinstaller/pyinstaller/tree/790f5691010b2e121a082713fc6f8e15fbe9a4b5

Cloning this directory I was able to install pyinstaller in cygwin 3.4.3 and Python 3.9.10.

BUT I did have to downgrade setuptools to setuptools==49.6.0.

So I did the following:


1. pip install setuptools==49.6.0
2. Grap zip from https://github.com/pyinstaller/pyinstaller/tree/790f5691010b2e121a082713fc6f8e15fbe9a4b5
3. unpack into folder
4. cd pyinstaller
5. python setup.py install

After that pyinstaller works just fine.

Hope someone can help with the newest pyinstaller version and the described problem in the first post.

**Comment by rokm** [comment]
Looks like the problem was introduced with addition of several `is_cygwin` checks in PyInstaller/building/utils.py, which trigger Windows-specific codepaths (with dependencies that are not available in cygwin environment).

https://github.com/pyinstaller/pyinstaller/blob/2653893de7f6bfe05be30f9a60923987094e9091/PyInstaller/building/utils.py#L36
https://github.com/pyinstaller/pyinstaller/blob/2653893de7f6bfe05be30f9a60923987094e9091/PyInstaller/building/utils.py#L238
https://github.com/pyinstaller/pyinstaller/blob/2653893de7f6bfe05be30f9a60923987094e9091/PyInstaller/building/utils.py#L270
https://github.com/pyinstaller/pyinstaller/blob/2653893de7f6bfe05be30f9a60923987094e9091/PyInstaller/building/utils.py#L308

Can you try removing them (reducing them to only `is_win` checks), and see if that works for you?

**Comment by eychei** [comment]
Thank you!
It worked. I just deleted the is_cygwin checks an installed with:
pip install .

But I do have a strange behavior.
When I use following command:

pyinstaller test.py

The package is build and everything seems to be fine.
But if I use following command:

pyinstaller -F test.py

It just hangs at: 9462 INFO: Looking for dynamic libraries

Now comes the strange part.
If I first execute pyinstaller test.py and afterwards pyinstaller -F test.py it does not hang and the exe works.

-e

**Comment by rokm** [comment]
Hmmm, yeah, I can see this in my test environment, too. The `ldd` process that keep spawning to analyze shared libraries seems to freeze when ran against some python extension for some reason (and it seems to be a different extension each time).

**Comment by rokm** [comment]
I don't think this freeze is our fault, though. I can (non-deterministically) reproduce it with the following minimal example that runs ldd on all python extension modules:

```python
import pathlib
import subprocess

import zlib

extensions_dir = pathlib.Path(zlib.__file__).parent
print("Scanning directory:", extensions_dir)

for extension_file in extensions_dir.iterdir():
    if not extension_file.is_file():
        continue
    print("Scanning:", extension_file)

    p = subprocess.run(['ldd', str(extension_file)], stderr=subprocess.PIPE, stdout=subprocess.PIPE, universal_newlines=True)
    
    print("ldd stderr:")
    print(p.stderr)
    print("ldd stdout:")
    print(p.stdout)
    print("--------")
```

And when it gets stuck, Ctrl+C gives the following traceback:
```
Traceback (most recent call last):
  File "/home/Rok/develop/lib_scanner.py", line 14, in <module>
    p = subprocess.run(['ldd', str(extension_file)], stderr=subprocess.PIPE, stdout=subprocess.PIPE, universal_newlines=True)
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1979, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

Interestingly, adding timeout to the `subprocess.run()` does not trigger the timeout, either - although a timeout exception is shown once the script is interrupted with Ctrl+C (but the code seems to have gotten stuck in handling of the timeout):
``` 
Traceback (most recent call last):
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1980, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.9/subprocess.py", line 1178, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['ldd', '/usr/lib/python3.9/lib-dynload/_crypt.cpython-39-x86_64-cygwin.dll']' timed out after 5 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Rok/develop/lib_scanner.py", line 14, in <module>
    p = subprocess.run(['ldd', str(extension_file)], stderr=subprocess.PIPE, stdout=subprocess.PIPE, universal_newlines=True, timeout=5)
  File "/usr/lib/python3.9/subprocess.py", line 520, in run
    process.wait()
  File "/usr/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1917, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.9/subprocess.py", line 1875, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by bwoodsend** [comment]
Can you reproduce it with something like:
```bash
while :; do ldd /usr/lib/python3.9/lib-dynload/_crypt.cpython-39-x86_64-cygwin.dll ; done
```

**Comment by rokm** [comment]
```bash
#!/usr/bin/env bash
DLL_DIR=/usr/lib/python3.9/lib-dynload
for ext_file in ${DLL_DIR}/*.dll; do
    echo "----"
    echo "Scanning $ext_file"
    ldd $ext_file;
    echo "----"
done
``` 

gets non-deterministically stuck as well.

And when it does, I can see `ldd` (`c:\cygwin64\bin\ldd.exe`) process eating ~20% CPU and `ldh` (`c:\cygwin64\bin\ldh.exe -- c:\cygwin64\lib\python3.9\lib-dynload\_lsprof.cpython-39-x86_64-cygwin.dll`) eating ~40% CPU. Which doesn't say much since this is a VM with 2 vCPUs, but those processes are definitely stuck spinning somewhere.
