### ISSUE TITLE
TypeError: 'bytes' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by internetrvze** [pyinstaller/pyinstaller#7391]
When I'm try to compile any script, I get TypeError
Log:
```
┌──(admin㉿ctOS)-[~/Desktop]
└─$ pyinstaller VKChecker.py --exclude-module _bootlocale
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.4-py1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.9.20-kali is an invalid version and will not be supported in a future release
  warnings.warn(
1072 INFO: PyInstaller: 3.5+498e6ee058
1072 INFO: Python: 3.10.9
1075 INFO: Platform: Linux-6.0.0-kali6-amd64-x86_64-with-glibc2.36
1075 INFO: wrote /home/admin/Desktop/VKChecker.spec
1080 INFO: UPX is available.
1082 INFO: Extending PYTHONPATH with paths
['/home/admin/Desktop', '/home/admin/Desktop']
1082 INFO: checking Analysis
1121 INFO: checking PYZ
1121 INFO: Building PYZ because PYZ-00.toc is non existent
1121 INFO: Building PYZ (ZlibArchive) /home/admin/Desktop/build/VKChecker/PYZ-00.pyz
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/admin/Desktop/VKChecker.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "/usr/lib/python3/dist-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/usr/lib/python3/dist-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/usr/lib/python3/dist-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: 'bytes' object cannot be interpreted as an integer
```

**Comment by rokm** [comment]
> 1072 INFO: PyInstaller: 3.5+498e6ee058
> 1072 INFO: Python: 3.10.9

You are using an outdated version of PyInstaller (3.5), which is not compatible with python 3.10. 

Open a a bug report with Kali linux and ask them to update the PyInstaller package in their package repositories. Or, install PyInstaller from PyPI using `pip install` instead of using Kali package.
