### ISSUE TITLE
importlib_metadata.PackageNotFoundError when using variable

### ISSUE THREAD

**Issue by michaelgr22** [pyinstaller/pyinstaller#7399]
## Description of the issue
Exception:
```
C:\Users\micha\tests\python\try_pyinstaller\dist>main.exe
Traceback (most recent call last):
  File "importlib_metadata\__init__.py", line 381, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try_pyinstaller\main.py", line 14, in <module>
  File "try_pyinstaller\main.py", line 10, in main
  File "try_pyinstaller\main.py", line 6, in get_version
  File "importlib_metadata\__init__.py", line 832, in version
  File "importlib_metadata\__init__.py", line 805, in distribution
  File "importlib_metadata\__init__.py", line 383, in from_name
importlib_metadata.PackageNotFoundError: No package metadata was found for try_pyinstaller
[2576] Failed to execute script 'main' due to unhandled exception!

```

### Steps to reprodue:

1. Create new poetry project
2. create file main.py
```
import importlib_metadata

PACKAGE_NAME = 'try_pyinstaller'

def get_version():
    version = importlib_metadata.version(PACKAGE_NAME)
    return version

def main():
    version = get_version()
    print(version)

if __name__ == "__main__":
    main()
```

3. create conda env and install pyinstaller and importlib_metadata
4. run `pyinstaller --onefile --name main try_pyinstaller\main.py --clean` 
5. When I change the line `version = importlib_metadata.version(PACKAGE_NAME)` in main.py to `version = importlib_metadata.version('try_pyinstaller')` so hardcode the variable and run the created .exe file again it works fine.

### Expected behavior
it shouldn't make any difference using a variable or not when building the .exe file

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.7.0```
* Version of Python: 3.10.9
* Platform: Windows
* How you installed Python: pip in a miniconda environment

### Stacktrace / full error message

```
C:\Users\micha\tests\python\try_pyinstaller\dist>main.exe
Traceback (most recent call last):
  File "importlib_metadata\__init__.py", line 381, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try_pyinstaller\main.py", line 14, in <module>
  File "try_pyinstaller\main.py", line 10, in main
  File "try_pyinstaller\main.py", line 6, in get_version
  File "importlib_metadata\__init__.py", line 832, in version
  File "importlib_metadata\__init__.py", line 805, in distribution
  File "importlib_metadata\__init__.py", line 383, in from_name
importlib_metadata.PackageNotFoundError: No package metadata was found for try_pyinstaller
[2576] Failed to execute script 'main' due to unhandled exception!
```

**Comment by rokm** [comment]
If you use `importlib_metadata.version('try_pyinstaller')`, PyInstaller's bytecode scanning can infer that metadata for `try_pyinstaller` needs to be collected. If you use a variant with non-literal argument, `importlib_metadata.version(PACKAGE_NAME)`, it cannot do that, and you need to explicitly instruct it to collect metadata via [`--copy-metadata try_pyinstaller`](https://pyinstaller.org/en/stable/usage.html#cmdoption-copy-metadata).

**Comment by michaelgr22** [comment]
@rokm thank you, this worked. Can you please briefly explain what "metadata" actually get's copied? I don't realy understand what the term "metadata" means in this context. Thank you!

**Comment by bwoodsend** [comment]
If you look in your Python environment's site-packages directory you should see a load of `*.dist-info` directories. Those are the distribution metadata which get copied into your application.
