### ISSUE TITLE
Importing `tables==3.8.0` leads to missing `libblosc2.so`

### ISSUE THREAD

**Issue by m-danya** [pyinstaller/pyinstaller#7408]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.7.0``` or ```4.10``` (remains in both versions + in development version)
* Version of Python: 3.9
* Platform: GNU/Linux
* How you installed Python: from apt repositories: `python3.9` + `python3.9-venv`
* Did you also try this on another platform? Does it work there? No, I didn't try

* (DONE) try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* (DONE almost everything) follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
python3.9 -m venv venv
source venv/bin/activate
pip install tables # installs 3.8.0, the newest one
pip install pyinstaller==4.10 # or 5.7.0, or the develop.zip, it works the same
echo 'import tables' > main.py
pyinstaller --onedir main.py
./dist/main/main
```

### Stacktrace / full error message
A part of stacktrace of executing `./dist/main/main`, packaged with `--noupx --debug all`

```
# tables not found in PYZ
# code object from '/home/dmikhaltsov_/code/test/dist/main/tables/__init__.pyc'
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 374, in __init__
OSError: libblosc2.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tables/__init__.py", line 26, in <module>
  File "ctypes/__init__.py", line 452, in LoadLibrary
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'libblosc2.so'. Most likely this dynlib/dll was not found when the application was frozen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 374, in __init__
OSError: /home/dmikhaltsov_/code/test/dist/main/tables/libblosc2.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from test_pb2 import MyObject, MyObjectsList, MyObjectsListAsBytes
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "tables/__init__.py", line 28, in <module>
  File "ctypes/__init__.py", line 452, in LoadLibrary
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll '/home/dmikhaltsov_/code/test/dist/main/tables/libblosc2.so'. Most likely this dynlib/dll was not found when the application was frozen.
[213596] Failed to execute script 'main' due to unhandled exception!
[213596] LOADER: OK.
[213596] LOADER: Manually flushing stdout and stderr
[213596] LOADER: Cleaning up Python interpreter.

```

**Comment by bwoodsend** [comment]
Just add `--collect-binaries=tables` to your pyinstaller command.

**Comment by m-danya** [comment]
Thanks, I'll try!
