### ISSUE TITLE
Pythonnet could not loaded on other PC

### ISSUE THREAD

**Issue by bls-lehoai** [pyinstaller/pyinstaller#7412]
I get this error when running our packaged app on other PC:

```
[6260] LOADER: Running main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "routers\script_router.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "services\xxxx_service.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "repositories\yyyy_repository.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 64, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
[6260] Failed to execute script 'main' due to unhandled exception!
[6260] LOADER: OK.
[6260] LOADER: Manually flushing stdout and stderr
[6260] LOADER: Cleaning up Python interpreter.
```
this line :   File "repositories\yyyy_repository.py", line 6, in <module> is:
```import clr```

I've tried many ways but didn't work. There are some PC when I unblock dll file (python.runtime.dll, etc..) then it worked, but there are some PC don't (i also tested it on windows 11). I'm pretty sure it is related to security.

**Comment by rokm** [comment]
If it is related to security (e.g., your local security policy preventing program from loading collected DLLs, or your anti-virus program blocking them), there's nothing we can really do about it. 

Same goes for cases when .NET runtime is missing on the target machine. What .NET runtime are you supposed to be using? Unless specified via `PYTHONNET_RUNTIME`, [pythonnet seems to be using the legacy .NET framework by default](https://github.com/pythonnet/pythonnet/blob/e28dd80c3a8fb60bd62671b765ff41c98ac5b1e9/pythonnet/__init__.py#L107-L109). Do you have that installed on the target machines?

**Comment by bls-lehoai** [comment]
@rokm 
I found that if my application folder path has special Japanese characters then an error happens.
Move to the normal English name folder then it works!
I don't know why, no clue at all :(

**Comment by rokm** [comment]
Does this happen with just Japanese characters, or any non-ASCII character? 

Can you provide a minimal example that triggers the error for you? E.g., is error triggered by
```python
import clr
print("Hello world!")
```
or does it require some additional code (like explicitly choosing particular runtime before importing `clr`)?

**Comment by bls-lehoai** [comment]
@rokm 
I've tried to create a main.py with your sample code and running pyinstaller main.py, then moving the binary to the folder:
`D:\アプリ\あのた　　　ｂｂ\main`

then run main.exe:
![image](https://user-images.githubusercontent.com/93567706/219234056-2c7029c6-4bb0-4ba5-b1dd-69ea2054b204.png)

**Comment by rokm** [comment]
OK, I've reproduced the problem. Let's reopen this until I figure whether it's our bug or not.

**Comment by rokm** [comment]
I don't think this is our bug, because I can reproduce the same error with `pythonnet` installed in a virtual environment that is located in a path that contains non-ASCII characters.

E.g., trying to run this code:
```python
import sys

if len(sys.argv) > 1 and sys.argv[1] == 'coreclr':
    # Use .NET core runtime
    from clr_loader import get_coreclr
    from pythonnet import set_runtime
    set_runtime(get_coreclr())
else:
    # Use .NET framework runtime - this is the default
    #from clr_loader import get_netfx
    #from pythonnet import set_runtime
    #set_runtime(get_netfx())
    pass

import clr

from System import String
s = String("Hello world!")
print(s)
``` 

fails with (the default) .NET Framework runtime:

```
(venv) C:\Users\Rok\Development\pyi-pythonnet>python program.py
Traceback (most recent call last):
  File "C:\Users\Rok\Development\pyi-pythonnet\program.py", line 15, in <module>
    import clr
  File "C:\Users\Rok\Development\pyi-pythonnet\dir-čšž\venv\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Users\Rok\Development\pyi-pythonnet\dir-čšž\venv\lib\site-packages\pythonnet\__init__.py", line 143, in load
    if func(b"") != 0:
  File "C:\Users\Rok\Development\pyi-pythonnet\dir-čšž\venv\lib\site-packages\clr_loader\types.py", line 64, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

but works with the .NET Core runtime:

``` 
(venv) C:\Users\Rok\Development\pyi-pythonnet>python program.py coreclr
Hello world!
```

Which seems to imply that either `pythonnet`'s path handling in `netfx` codepath is problematic, or perhaps that .NET Framework itself has problems with non-ASCII paths. Either way, nothing we can do about that.

If switching to .NET Core runtime is an option for you, you could do that to take care of non-ASCII paths.

**Comment by bls-lehoai** [comment]
@rokm 
Thanks for your support.
it turns out that Pythonet 3.0 didn't work well. I have to revert to 2.xx version then it works! have no idea why
