### ISSUE TITLE
Getting IOError: Python Library not found!

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#744]
**Original date**: 2014/04/22

Every time that I run pyinstaller I get the following traceback from pyinstaller. (including part of the normal output for some context)
```
5109 INFO: Looking for run-time hooks
Traceback (most recent call last):
  File "pyinstaller.py", line 18, in <module>
    run()
  File "/home/jgreen/pyinstaller/PyInstaller/main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "/home/jgreen/pyinstaller/PyInstaller/main.py", 46 in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/home/jgreen/pyinstaller/PyInstaller/build.py", line 1915, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/jgreen/pyinstaller/PyInstaller/build.py", line 1864, in build
    execfile(spec)
  File "/home/jgreen/pyinstaller/PyInstaller/minion_client.spec", line 6, in <module>
    runtime_hooks=None)
  File "/home/jgreen/pyinstaller/PyInstaller/build.py", line 442, in __init__
    self.__postinit__()
  File "/home/jgreen/pyinstaller/PyInstaller/build.py", line 305, in __postinit__
    self.assemble()
  File "/home/jgreen/pyinstaller/PyInstaller/build.py", line 673, in assemble
    self._check_python_library(binaries)
  File "/home/jgreen/pyinstaller/PyInstaller/build.py", line 723, in _check_python_library
    raise IOError("Python library not found!")
IOError: Python library not found!
```
The only information I've found to solve this error involves ensuring that you're using a dynamic python library however I'm already using a dynamic library so I'm not sure where the error is.  Any help with this would be appreciated.

**Comment by matysek** [comment]
This should be fixed.
