### ISSUE TITLE
Having error when running pyinstaller 

### ISSUE THREAD

**Issue by pharoah-ui** [pyinstaller/pyinstaller#7450]
Having problem when running pyinstalller , I m using python  3.11.0a5

pyinstaller main.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
    ^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 161, in run
    parser = generate_parser()
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 128, in generate_parser
    import PyInstaller.building.build_main
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 28, in <module>
    from PyInstaller.building.api import COLLECT, EXE, MERGE, PYZ
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\api.py", line 26, in <module>
    from PyInstaller.archive.writers import CArchiveWriter, ZlibArchiveWriter
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\archive\writers.py", line 28, in <module>
    from PyInstaller.building.utils import get_code_object, strip_paths_in_code
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\utils.py", line 33, in <module>
    from PyInstaller.depend.bindepend import match_binding_redirect
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\bindepend.py", line 27, in <module>
    from PyInstaller.depend import dylib, utils
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\utils.py", line 28, in <module>
    from PyInstaller.depend import bytecode
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\bytecode.py", line 130, in <module>
    _cache_instruction_filter = bytecode_regex(rb"(`CACHE`.)|(..)")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\bytecode.py", line 53, in bytecode_regex
    pattern = re.sub(
              ^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\re.py", line 189, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\bytecode.py", line 55, in <lambda>
    lambda m: _instruction_to_regex(m[1].decode()),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\bytecode.py", line 36, in _instruction_to_regex
    return re.escape(bytes([opmap[x]]))
                            ~~~~~^^^
KeyError: 'CACHE'

**Comment by rokm** [comment]
> I m using python 3.11.0a5

We don't really support alpha releases due to changes that are done during the development cycle. For example, `CACHE` instruction was added in 3.11.0a7.

So you'll have to use at least 3.11.0a7, or switch to a release version of 3.11.
