### ISSUE TITLE
EOFError: EOF read where object expected when using pyinstaller with PyQt5 and pyqtgraph

### ISSUE THREAD

**Issue by wavelolz** [pyinstaller/pyinstaller#7452]
### Discussed in https://github.com/orgs/pyinstaller/discussions/7451

<div type='discussions-op-text'>

<sup>Originally posted by **wavelolz** February 21, 2023</sup>
When freezing the application I built using PyQt5 and pyqtgraph, the EOFError occurs. The program can run on my computer without any problem. However, when I use `pyinstaller test.py`, the error occurs.

### A minimal example program which shows the error

```python
 from PyQt5 import QtWidgets
 import pyqtgraph
 import sys

 class MainWindow(QtWidgets.QMainWindow):
   def __init__(self):
      super().__init__()
      self.setWindowTitle("Hello World")
      l = QtWidgets.QLabel("My simple app.")
      self.setCentralWidget(l)
      self.show()

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    app.exec()
```
Although I don't use pyqtgraph here but I have to use it in another program. Also, when I remove `import pyqtgraph`, then the error won't occur. So I think something might have do with this.

### Context Information
-  Output of `pyinstaller --version`: 5.8.0
- Version of Python: pyenv 3.10.4
- Platform: Windows

### Context of Error
```
D:\project\IRT\.venv\lib\site-packages\PyInstaller\building\build_main.py:175: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
Traceback (most recent call last):
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\isolated\_parent.py", line 373, in call
    return isolated.call(function, *args, **kwargs)
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rayhs\.pyenv\pyenv-win\versions\3.10.4\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rayhs\.pyenv\pyenv-win\versions\3.10.4\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\project\IRT\.venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 977, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 899, in build
    exec(code, spec_namespace)
  File "D:\project\IRT\test\test.spec", line 7, in <module>
    a = Analysis(
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 412, in __init__
    self.__postinit__()
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 695, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    with Python() as isolated:
  File "D:\project\IRT\.venv\lib\site-packages\PyInstaller\isolated\_parent.py", line 244, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument
```

### Packages installed in .venv
```
Package                   Version
------------------------- ---------
altgraph                  0.17.3   
asttokens                 2.2.1    
backcall                  0.2.0    
colorama                  0.4.6    
comm                      0.1.2    
contourpy                 1.0.6    
cycler                    0.11.0   
debugpy                   1.6.6
decorator                 5.1.1
et-xmlfile                1.1.0
executing                 1.2.0
fonttools                 4.38.0
future                    0.18.2
girth                     0.8.0
ipykernel                 6.21.1
ipython                   8.9.0
jedi                      0.18.2
Jinja2                    3.1.2
jupyter_client            8.0.2
jupyter_core              5.2.0
kiwisolver                1.4.4
MarkupSafe                2.1.1
matplotlib                3.6.2
matplotlib-inline         0.1.6
nest-asyncio              1.5.6
numpy                     1.24.1
openpyxl                  3.0.10
packaging                 23.0
pandas                    1.5.2
parso                     0.8.3
pefile                    2022.5.30
pickleshare               0.7.5
Pillow                    9.4.0
pip                       23.0.1
platformdirs              3.0.0
prompt-toolkit            3.0.36
psutil                    5.9.4
pure-eval                 0.2.2
Pygments                  2.14.0
pyinstaller               5.8.0
pyinstaller-hooks-contrib 2022.14
pyparsing                 3.0.9
PyQt5                     5.15.7
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.11.0
PyQt6                     6.4.2
PyQt6-Qt6                 6.4.2
PyQt6-sip                 13.4.1
pyqtgraph                 0.13.0
python-dateutil           2.8.2
pytz                      2022.7
pywin32                   305
pywin32-ctypes            0.2.0
pyzmq                     25.0.0
scipy                     1.10.0
setuptools                58.1.0
six                       1.16.0
stack-data                0.6.2
tornado                   6.2
traitlets                 5.9.0
wcwidth                   0.2.6
xlrd                      2.0.1
```

**Comment by jdegenstein** [comment]
I am seeing the same error in my build related to pyqtgraph and PyQt5. I do NOT have PyQt6 in my application though. I get this error message just before the exception though:
```
WARNING: Failed to collect submodules for 'pyqtgraph.opengl' because importing 'pyqtgraph.opengl' raised: ModuleNotFoundError: No module named 'OpenGL'
```

**Comment by rokm** [comment]
Nah, that's unrelated. What's happening is that this import sequence:
```python
import matplotlib_inline
import pyqtgraph.canvas
```
crashes python process during analysis. Do you use `IPython`, `jupyter`, and `matplotlib_inline` in your application?

**Comment by rokm** [comment]
If not, try adding `--exclude IPython` to your PyInstaller command (in lieu of removing unnecessary packages from the environment).

**Comment by wavelolz** [comment]
> If not, try adding `--exclude IPython` to your PyInstaller command (in lieu of removing unnecessary packages from the environment).

Thanks, it works. Because I have to use `PyQt6` in my application, but Pyinstaller still crash if I removed `PyQt5` from my environment. But after I removed `IPython` from my environment, Pyinstaller works smoothly. 
Very thanks for your answer

**Comment by jdegenstein** [comment]
I am still struggling with this error, and it is breaking builds for me on Linux only (not MacOS or Windows which are working fine). I think it may be an issue with the pyqtgraph hook, but I am not sure. I have attached the complete build log, and the relevant line starts around 1870. I have tried changing the versions of ipython and pyqtgraph and it has not helped.

```
2023-02-27T18:24:28.3075026Z 49726 INFO: Loading module hook 'hook-pyqtgraph.py' from '/home/runner/micromamba-root/envs/test/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
2023-02-27T18:24:28.7719148Z 323 INFO: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2023-02-27T18:24:29.2222225Z qt.qpa.xcb: could not connect to display 
2023-02-27T18:24:29.2222662Z qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
2023-02-27T18:24:29.2223182Z This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
2023-02-27T18:24:29.2223471Z 
2023-02-27T18:24:29.2224173Z Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
2023-02-27T18:24:29.2224515Z 
2023-02-27T18:24:29.4411141Z Traceback (most recent call last):
2023-02-27T18:24:29.4412535Z   File "/home/runner/micromamba-root/envs/test/lib/python3.10/site-packages/PyInstaller/utils/hooks/__init__.py", line 621, in collect_submodules
2023-02-27T18:24:29.4413368Z     modules, subpackages, on_error = isolated_python.call(_collect_submod
[linux_pyqtgraph_log.txt](https://github.com/pyinstaller/pyinstaller/files/10842943/linux_pyqtgraph_log.txt)
ules, name, on_error)
2023-02-27T18:24:29.4464313Z   File "/home/runner/micromamba-root/envs/test/lib/python3.10/site-packages/PyInstaller/isolated/_parent.py", line 302, in call
2023-02-27T18:24:29.4464781Z     ok, output = loads(b64decode(self._read_handle.readline()))
2023-02-27T18:24:29.4465076Z EOFError: EOF read where object expected
```

[linux_pyqtgraph_log.txt](https://github.com/pyinstaller/pyinstaller/files/10842946/linux_pyqtgraph_log.txt)

My pyinstaller builds are run on GH actions, so all the files feeding them are public at this link https://github.com/jdegenstein/jmwright-CQ-Editor

**Comment by rokm** [comment]
@jdegenstein Thanks for additional info! 

Looks like the problem caused by `pyqtgraph` hook recursing into `pyqtgraph.examples` sub-package while scanning for submodules; and loading `pyqtgraph.examples` triggers instantiation of `QApplication`, which would require a valid X or Wayland session (hence `qt.qpa.xcb: could not connect to display`).

**Comment by familyfan** [comment]
When I package torch using pyinstaller, I got the error as follow:
torch\\lib']
Traceback (most recent call last):
  File "xxx\PyInstaller\isolated\_child.py", line 21, in <module>
    import types
  File "d:\xxx\torch\types.py", line 1, in <module>
    import torch
  File "d:\xxx\torch\__init__.py", line 14, in <module>
    import platform
  File "xxx\lib\platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "xxx\re.py", line 122, in <module>
    import enum
  File "xxx\lib\enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' 
Traceback (most recent call last):
  File "xxx\PyInstaller\isolated\_parent.py", line 373, in call
    return isolated.call(function, *args, **kwargs)
  File "xxx\PyInstaller\isolated\_parent.py", line 302, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
PyInstaller\isolated\_parent.py", line 244, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument

**Comment by bwoodsend** [comment]
> d:\xxx\torch_init_.py

If you're going to obfuscate your filenames, can you at least leave enough so that we can tell which come from Python environments and which are your own modules.

That said, given that this issue is specific to pyqtgraph and has been fixed and should have been closed, whereas yours has nothing to do with, I'd prefer you to create a new one.
