### ISSUE TITLE
OSError: [Errno 5] Input/output error when building inside a shared vmware folder

### ISSUE THREAD

**Issue by properchopsticks** [pyinstaller/pyinstaller#7478]
hi, i have a problem with building a test project inside a vmware shared folder. whenever i try to build i get an `OSError: [Errno 5] Input/output error` message `4079 ERROR: base_library.zip could not be created!`.
if i copy the folder onto the local vm drive then it works but inside the vm shared folder it always gives this error.
i checked the file permissions and the all have write permissions
```
total 10K
drwxrwxrwx 1 root root 4,0K Mär  8 12:18 .
drwxrwxrwx 1 root root 4,0K Mär  7 19:25 ..
drwxrwxrwx 1 root root    0 Mär  7 19:33 build
-rwxrwxrwx 1 root root  197 Mär  8 12:34 compile.py
drwxrwxrwx 1 root root    0 Mär  7 19:33 dist
-rwxrwxrwx 1 root root   86 Mär  7 19:48 main_file.py
-rwxrwxrwx 1 root root  900 Mär  8 12:42 main_file.spec
-rwxrwxrwx 1 root root    0 Mär  8 12:18 pyinstaller.log
drwxrwxrwx 1 root root    0 Mär  8 11:52 .vscode
```
i also used `--onedir` but it also didn't work. `sudo` doesn't recognize pyinstaller but i did `python3 /home/my_username/.local/bin/pyinstaller main_file.py` but that didn't work either.
the only thing that worked was copying the folder to the local vm drive but that's not an option because i need access to it from other machines.
i have here an debug trace:
```
171 INFO: PyInstaller: 5.8.0
171 INFO: Python: 3.10.6
176 INFO: Platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
178 INFO: wrote /mnt/hgfs/projects/python/test_compiler/main_file.spec
179 DEBUG: Testing for UPX ...
184 INFO: UPX is not available.
187 DEBUG: script: /mnt/hgfs/projects/python/test_compiler/main_file.py
188 INFO: Extending PYTHONPATH with paths
['/mnt/hgfs/projects/python/test_compiler']
77 DEBUG: discover_hook_directories: Hook directories: ['/home/my_username/.local/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks', '/home/my_username/.local/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks/__pycache__', '/home/my_username/.local/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks', '/home/my_username/.local/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/__pycache__', '/home/my_username/.local/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks']
399 INFO: checking Analysis
399 INFO: Building Analysis because Analysis-00.toc is non existent
399 INFO: Initializing module dependency graph...
401 INFO: Caching module graph hooks...
408 INFO: Analyzing base_library.zip ...
408 DEBUG: Collecting submodules for urllib
92 DEBUG: collect_submodules - scanning (sub)package urllib
92 DEBUG: collect_submodules - scanning (sub)package urllib in location(s): ['/usr/lib/python3.10/urllib']
627 DEBUG: collect_submodules - found submodules: ['urllib', 'urllib.error', 'urllib.parse', 'urllib.request', 'urllib.response', 'urllib.robotparser']
627 DEBUG: Collecting submodules for encodings
93 DEBUG: collect_submodules - scanning (sub)package encodings
93 DEBUG: collect_submodules - scanning (sub)package encodings in location(s): ['/usr/lib/python3.10/encodings']
829 DEBUG: collect_submodules - found submodules: ['encodings', 'encodings.aliases', 'encodings.ascii', 'encodings.base64_codec', 'encodings.big5', 'encodings.big5hkscs', 'encodings.bz2_codec', 'encodings.charmap', 'encodings.cp037', 'encodings.cp1006', 'encodings.cp1026', 'encodings.cp1125', 'encodings.cp1140', 'encodings.cp1250', 'encodings.cp1251', 'encodings.cp1252', 'encodings.cp1253', 'encodings.cp1254', 'encodings.cp1255', 'encodings.cp1256', 'encodings.cp1257', 'encodings.cp1258', 'encodings.cp273', 'encodings.cp424', 'encodings.cp437', 'encodings.cp500', 'encodings.cp720', 'encodings.cp737', 'encodings.cp775', 'encodings.cp850', 'encodings.cp852', 'encodings.cp855', 'encodings.cp856', 'encodings.cp857', 'encodings.cp858', 'encodings.cp860', 'encodings.cp861', 'encodings.cp862', 'encodings.cp863', 'encodings.cp864', 'encodings.cp865', 'encodings.cp866', 'encodings.cp869', 'encodings.cp874', 'encodings.cp875', 'encodings.cp932', 'encodings.cp949', 'encodings.cp950', 'encodings.euc_jis_2004', 'encodings.euc_jisx0213', 'encodings.euc_jp', 'encodings.euc_kr', 'encodings.gb18030', 'encodings.gb2312', 'encodings.gbk', 'encodings.hex_codec', 'encodings.hp_roman8', 'encodings.hz', 'encodings.idna', 'encodings.iso2022_jp', 'encodings.iso2022_jp_1', 'encodings.iso2022_jp_2', 'encodings.iso2022_jp_2004', 'encodings.iso2022_jp_3', 'encodings.iso2022_jp_ext', 'encodings.iso2022_kr', 'encodings.iso8859_1', 'encodings.iso8859_10', 'encodings.iso8859_11', 'encodings.iso8859_13', 'encodings.iso8859_14', 'encodings.iso8859_15', 'encodings.iso8859_16', 'encodings.iso8859_2', 'encodings.iso8859_3', 'encodings.iso8859_4', 'encodings.iso8859_5', 'encodings.iso8859_6', 'encodings.iso8859_7', 'encodings.iso8859_8', 'encodings.iso8859_9', 'encodings.johab', 'encodings.koi8_r', 'encodings.koi8_t', 'encodings.koi8_u', 'encodings.kz1048', 'encodings.latin_1', 'encodings.mac_arabic', 'encodings.mac_croatian', 'encodings.mac_cyrillic', 'encodings.mac_farsi', 'encodings.mac_greek', 'encodings.mac_iceland', 'encodings.mac_latin2', 'encodings.mac_roman', 'encodings.mac_romanian', 'encodings.mac_turkish', 'encodings.mbcs', 'encodings.oem', 'encodings.palmos', 'encodings.ptcp154', 'encodings.punycode', 'encodings.quopri_codec', 'encodings.raw_unicode_escape', 'encodings.rot_13', 'encodings.shift_jis', 'encodings.shift_jis_2004', 'encodings.shift_jisx0213', 'encodings.tis_620', 'encodings.undefined', 'encodings.unicode_escape', 'encodings.utf_16', 'encodings.utf_16_be', 'encodings.utf_16_le', 'encodings.utf_32', 'encodings.utf_32_be', 'encodings.utf_32_le', 'encodings.utf_7', 'encodings.utf_8', 'encodings.utf_8_sig', 'encodings.uu_codec', 'encodings.zlib_codec']
829 DEBUG: Collecting submodules for collections
109 DEBUG: collect_submodules - scanning (sub)package collections
109 DEBUG: collect_submodules - scanning (sub)package collections in location(s): ['/usr/lib/python3.10/collections']
1047 DEBUG: collect_submodules - found submodules: ['collections', 'collections.abc']
1215 INFO: Loading module hook 'hook-heapq.py' from '/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/hooks'...
1217 DEBUG: Suppressing import of 'doctest' from module 'heapq' due to excluded import 'doctest' specified in a hook for 'heapq' (or its parent package(s)).
1296 INFO: Loading module hook 'hook-encodings.py' from '/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/hooks'...
1299 DEBUG: Collecting submodules for encodings
95 DEBUG: collect_submodules - scanning (sub)package encodings
95 DEBUG: collect_submodules - scanning (sub)package encodings in location(s): ['/usr/lib/python3.10/encodings']
1546 DEBUG: collect_submodules - found submodules: ['encodings', 'encodings.aliases', 'encodings.ascii', 'encodings.base64_codec', 'encodings.big5', 'encodings.big5hkscs', 'encodings.bz2_codec', 'encodings.charmap', 'encodings.cp037', 'encodings.cp1006', 'encodings.cp1026', 'encodings.cp1125', 'encodings.cp1140', 'encodings.cp1250', 'encodings.cp1251', 'encodings.cp1252', 'encodings.cp1253', 'encodings.cp1254', 'encodings.cp1255', 'encodings.cp1256', 'encodings.cp1257', 'encodings.cp1258', 'encodings.cp273', 'encodings.cp424', 'encodings.cp437', 'encodings.cp500', 'encodings.cp720', 'encodings.cp737', 'encodings.cp775', 'encodings.cp850', 'encodings.cp852', 'encodings.cp855', 'encodings.cp856', 'encodings.cp857', 'encodings.cp858', 'encodings.cp860', 'encodings.cp861', 'encodings.cp862', 'encodings.cp863', 'encodings.cp864', 'encodings.cp865', 'encodings.cp866', 'encodings.cp869', 'encodings.cp874', 'encodings.cp875', 'encodings.cp932', 'encodings.cp949', 'encodings.cp950', 'encodings.euc_jis_2004', 'encodings.euc_jisx0213', 'encodings.euc_jp', 'encodings.euc_kr', 'encodings.gb18030', 'encodings.gb2312', 'encodings.gbk', 'encodings.hex_codec', 'encodings.hp_roman8', 'encodings.hz', 'encodings.idna', 'encodings.iso2022_jp', 'encodings.iso2022_jp_1', 'encodings.iso2022_jp_2', 'encodings.iso2022_jp_2004', 'encodings.iso2022_jp_3', 'encodings.iso2022_jp_ext', 'encodings.iso2022_kr', 'encodings.iso8859_1', 'encodings.iso8859_10', 'encodings.iso8859_11', 'encodings.iso8859_13', 'encodings.iso8859_14', 'encodings.iso8859_15', 'encodings.iso8859_16', 'encodings.iso8859_2', 'encodings.iso8859_3', 'encodings.iso8859_4', 'encodings.iso8859_5', 'encodings.iso8859_6', 'encodings.iso8859_7', 'encodings.iso8859_8', 'encodings.iso8859_9', 'encodings.johab', 'encodings.koi8_r', 'encodings.koi8_t', 'encodings.koi8_u', 'encodings.kz1048', 'encodings.latin_1', 'encodings.mac_arabic', 'encodings.mac_croatian', 'encodings.mac_cyrillic', 'encodings.mac_farsi', 'encodings.mac_greek', 'encodings.mac_iceland', 'encodings.mac_latin2', 'encodings.mac_roman', 'encodings.mac_romanian', 'encodings.mac_turkish', 'encodings.mbcs', 'encodings.oem', 'encodings.palmos', 'encodings.ptcp154', 'encodings.punycode', 'encodings.quopri_codec', 'encodings.raw_unicode_escape', 'encodings.rot_13', 'encodings.shift_jis', 'encodings.shift_jis_2004', 'encodings.shift_jisx0213', 'encodings.tis_620', 'encodings.undefined', 'encodings.unicode_escape', 'encodings.utf_16', 'encodings.utf_16_be', 'encodings.utf_16_le', 'encodings.utf_32', 'encodings.utf_32_be', 'encodings.utf_32_le', 'encodings.utf_7', 'encodings.utf_8', 'encodings.utf_8_sig', 'encodings.uu_codec', 'encodings.zlib_codec']
2449 INFO: Loading module hook 'hook-pickle.py' from '/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/hooks'...
2457 DEBUG: Suppressing import of 'doctest' from module 'pickle' due to excluded import 'doctest' specified in a hook for 'pickle' (or its parent package(s)).
2457 DEBUG: Suppressing import of 'argparse' from module 'pickle' due to excluded import 'argparse' specified in a hook for 'pickle' (or its parent package(s)).
3583 INFO: Caching module dependency graph...
3626 DEBUG: Adding python files to base_library.zip
4079 ERROR: base_library.zip could not be created!
Traceback (most recent call last):
  File "/home/my_username/.local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 977, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 899, in build
    exec(code, spec_namespace)
  File "/mnt/hgfs/projects/python/test_compiler/main_file.spec", line 7, in <module>
    a = Analysis(
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 412, in __init__
    self.__postinit__()
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 517, in assemble
    create_py3_base_library(libzip_filename, graph=self.graph)
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/depend/utils.py", line 84, in create_py3_base_library
    zf.writestr(info, fc.getvalue())
  File "/usr/lib/python3.10/zipfile.py", line 1815, in writestr
    dest.write(data)
  File "/usr/lib/python3.10/zipfile.py", line 1139, in write
    self._fileobj.write(data)
OSError: [Errno 5] Input/output error
```
and here is the test program i tried to compile:
```py
import time

if __name__ == "__main__":
    print(f"current time is: {time.time()}")
```
i also tried running running it in a debugger but it doesn't hook to pyinstaller for some reason.

**Comment by rokm** [comment]
This looks like a low-level error coming from python's `zipfile`, so I doubt there's really anything we can do about it.

Does manually removing the `build` and `dist` directories before starting the build make any difference?

If it does not, can you reproduce the error while trying to manually create a zip file in the current working directory (in the vmware shared folder) with the following script?

```python
# zipfile test
import zipfile

entries = {
    "test1": b"Data 1",
    "test2": b"Data 2",
    "test3": b"Data 3",
}

with zipfile.ZipFile('test.zip', mode='w') as zf:
    zf.debug = 3

    for entry_name, entry_data in entries.items():
        info = zipfile.ZipInfo(entry_name)
        zf.writestr(info, entry_data)
``` 


>  the only thing that worked was copying the folder to the local vm drive but that's not an option because i need access to it from other machines.

What do you need access to - the source (e.g., to build in different VMs), or the result? If the former, you could always relocate the working and output directories to your local home directory using the `--workpath` and `--distpath` command-line switches. And even if the latter, you could relocate the working/output dir to your local home directory and then move the result back to your shared folder...

**Comment by properchopsticks** [comment]
i tried the script but it said the same thing. also settings the paths with --distpath and --workpath to a different folder gave me a different error but it still didn't work.
```
135 INFO: PyInstaller: 5.8.0
135 INFO: Python: 3.10.6
137 INFO: Platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
139 INFO: wrote /mnt/hgfs/projects/python/test_compiler/main_file.spec
140 INFO: UPX is not available.
143 INFO: Extending PYTHONPATH with paths
['/mnt/hgfs/projects/python/test_compiler']
390 INFO: checking Analysis
391 INFO: Building Analysis because Analysis-00.toc is non existent
391 INFO: Initializing module dependency graph...
394 INFO: Caching module graph hooks...
401 INFO: Analyzing base_library.zip ...
1111 INFO: Loading module hook 'hook-heapq.py' from '/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/hooks'...
1189 INFO: Loading module hook 'hook-encodings.py' from '/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/hooks'...
2277 INFO: Loading module hook 'hook-pickle.py' from '/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/hooks'...
3426 INFO: Caching module dependency graph...
3522 INFO: running Analysis Analysis-00.toc
3584 INFO: Analyzing /mnt/hgfs/projects/python/test_compiler/main_file.py
3588 INFO: Processing module hooks...
3598 INFO: Looking for ctypes DLLs
3601 INFO: Analyzing run-time hooks ...
3604 INFO: Including run-time hook '/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
3611 INFO: Looking for dynamic libraries
4116 INFO: Looking for eggs
4116 INFO: Python library not among binary dependencies. Performing additional search...
4147 INFO: Using Python library /lib/x86_64-linux-gnu/libpython3.10.so.1.0
4148 INFO: Warnings written to /home/my_username/Documents/main_file/warn-main_file.txt
4163 INFO: Graph cross-reference written to /home/my_username/Documents/main_file/xref-main_file.html
4182 INFO: checking PYZ
4182 INFO: Building PYZ because PYZ-00.toc is non existent
4183 INFO: Building PYZ (ZlibArchive) /home/my_username/Documents/main_file/PYZ-00.pyz
4392 INFO: Building PYZ (ZlibArchive) /home/my_username/Documents/main_file/PYZ-00.pyz completed successfully.
4395 INFO: checking PKG
4396 INFO: Building PKG because PKG-00.toc is non existent
4397 INFO: Building PKG (CArchive) main_file.pkg
7248 INFO: Building PKG (CArchive) main_file.pkg completed successfully.
7249 INFO: Bootloader /home/my_username/.local/lib/python3.10/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
7249 INFO: checking EXE
7249 INFO: Building EXE because EXE-00.toc is non existent
7249 INFO: Building EXE from EXE-00.toc
WARNING: The output directory "/home/my_username/Documents/main_file" and ALL ITS CONTENTS will be REMOVED! Continue? (y/N)y
On your own risk, you can use the option `--noconfirm` to get rid of this question.
15067 INFO: Removing dir /home/my_username/Documents/main_file
15069 INFO: Copying bootloader EXE to /home/my_username/Documents/main_file
15070 INFO: Appending PKG archive to custom ELF section in EXE
Traceback (most recent call last):
  File "/home/my_username/.local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 977, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 899, in build
    exec(code, spec_namespace)
  File "/mnt/hgfs/projects/python/test_compiler/main_file.spec", line 24, in <module>
    exe = EXE(
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/api.py", line 594, in __init__
    self.__postinit__()
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/home/my_username/.local/lib/python3.10/site-packages/PyInstaller/building/api.py", line 797, in assemble
    raise SystemError(f"objcopy Failure: {p.returncode} {p.stdout}")
SystemError: objcopy Failure: 1 objcopy: cannot open: /home/my_username/Documents/main_file/main_file.pkg: Not a directory
```
this does seem to be heavily related to vmware's access rights because i get similar errors in other apps when working from a shared folder. 🤔

**Comment by rokm** [comment]
> i tried the script but it said the same thing

Then the problem is either with python's zipfile implementation or with vmware's shared folder (or, most likely, the combination of the two).

> also settings the paths with --distpath and --workpath to a different folder gave me a different error but it still didn't work.

What was your PyInstaller command? Did you perhaps point `--workpath` and `--distpath` to the same directory (they should different directories, and one should also not be sub-directory of the other)?

**Comment by properchopsticks** [comment]
yes, it is definitely a vmware access issue, not sure what or why but that's what it is. neither cargo nor npm work either in the shared folder.
also, yes, the distpath and workpath were the same folder. i tried different folders and it worked this time.
i'll go ahead and close the ticket since on pyinstaller's end it's all good.
