### ISSUE TITLE
Problems with PyInstaller 2.0 waf call on AIX

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#748]
**Original date**: 2013/08/12
**Original reporter**: *egame DOT expert AND gmail DOT  COOM *

I am unable to build the bootloader under AIX 7.1 (same on AIX 5.3).
I followed all instruction for requierement and installation.
Python 2.7.5 interpreter and script work like a charme on both AIX.

coredump append when checking for libray python2.7

this is the output in verbose mode on AIX 7.1:

```
root@aixserver /tmp/python/packages/pyinstaller-2.0/source # python ./waf configure -vvv
AIX-32bit detected
Checking for program xlc_r or xlc        : /usr/vac/bin/xlc_r
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
09:33:10 action
def f(task):
        env = task.env
        wd = getattr(task, 'cwd', None)
        def to_list(xx):
                if isinstance(xx, str): return [xx]
                return xx
        lst = []
        lst.extend(to_list(env['CC']))
        lst.extend(to_list(env['CCFLAGS']))
        lst.extend(to_list(env['CPPFLAGS']))
        lst.extend(to_list(env['_CCINCFLAGS']))
        lst.extend(to_list(env['_CCDEFFLAGS']))
        lst.extend(to_list(env['CC_SRC_F']))
        lst.extend([a.srcpath(env) for a in task.inputs])
        lst.extend(to_list(env['CC_TGT_F']))
        lst.extend([a.bldpath(env) for a in task.outputs])
        lst = [x for x in lst if x]
        return task.exec_command(lst, cwd=wd)

09:33:10 action
def f(task):
        env = task.env
        wd = getattr(task, 'cwd', None)
        def to_list(xx):
                if isinstance(xx, str): return [xx]
                return xx
        lst = []
        lst.extend(to_list(env['LINK_CC']))
        lst.extend(to_list(env['CCLNK_SRC_F']))
        lst.extend([a.srcpath(env) for a in task.inputs])
        lst.extend(to_list(env['CCLNK_TGT_F']))
        lst.append(task.outputs[0].abspath(env))
        lst.extend(to_list(env['LINKFLAGS']))
        lst = [x for x in lst if x]
        return task.exec_command(lst, cwd=wd)

Checking for xlc                         : ok
Checking for program python              : /usr/bin/python
09:33:10 python Running python command ['/usr/bin/python', '-c', 'import sys\nfor x in sys.version_info: print(str(x))']
Checking for Python version              : 2.7.5
Checking for library python2.7           : 09:33:10 build Build cache loading failed
09:33:10 build srcnode is .conf_check_0 and srcdir /tmp/python/packages/pyinstaller-2.0/source/build/.conf_check_0
09:33:10 build init variants
09:33:10 build list of variants is ['default']
09:33:10 build compile called
09:33:10 build delayed operation TaskGen.flush() called
09:33:10 task_gen posting objects (normal)
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/opt/freeware/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/tmp/python/packages/pyinstaller-2.0/source/.waf-1.5.18-402a8e0721eb718ff717906f130db0f4/wafadmin/Logs.py", line 64, in format
    return logging.Formatter.format(self,rec)
  File "/opt/freeware/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/opt/freeware/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file Logs.py, line 69
09:33:10 group <task_gen 'testprog' of type task_gen defined in dir:///tmp/python/packages/pyinstaller-2.0/source/build/.conf_check_0>
09:33:10 task_gen posting <task_gen 'testprog' of type task_gen defined in dir:///tmp/python/packages/pyinstaller-2.0/source/build/.conf_check_0> 810647576
09:33:10 task_gen -> add_extra_flags (810647576)
09:33:10 task_gen -> default_cc (810647576)
09:33:10 task_gen -> init_cc (810647576)
09:33:10 task_gen -> apply_type_vars (810647576)
09:33:10 task_gen -> exec_rule (810647576)
09:33:10 task_gen -> vars_target_cprogram (810647576)
09:33:10 task_gen -> apply_core (810647576)
Illegal instruction(coredump)

```

Could it be a librabries problem? how can i solve this? any ideas?

Kind regards

Alex

**Comment by htgoebel** [comment]
Too less information.
