### ISSUE TITLE
ImportError: DLL load failed while importing _ssl

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#7484]
Getting this issue when running the executable that was generated by pyinstaller

Traceback (most recent call last):
File "poker\main.py", line 21, in ‹module>
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "poker\gui \action_and_signals.py", line 17, in ‹module>
File "PyInstaller\loader\pyimod@2_importers.py", line 352, in exec module
File "poker \gui\plots\funds_change_plot.py", line 7, in ‹module>
File "PyInstaller\loader\pyimod@2_importers.py", line 352, in exec _module
File "poker\tools\game_logger.py", line 9, in ‹module>
File "PyInstaller\loader\pyimod@2_importers.py", line 352, in exec_module
File "fastapi\__init__.py", line 7, in ‹module>
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec module
File "fastapi \applications.py", line 15, in ‹module>
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_ module
File "fastapi \routing.py", line 23, in ‹module>
File "PyInstaller\loader\pyimod@2_importers.py", line 352, in exec _module
File "fastapi \datastructures.py". line 3, in ‹module>
File "PyInstaller\loader\pyimod02 importers.py", line 352, in exec_ module
File "starlette\datastructures.py"
line 6, in ‹module>
File "PyInstaller\loader\pyimod@2_importers.py", line 352, in exec_module
File "starlette\concurrency.py", line 6, in ‹module>
File "PyInstaller\loader\pyimod@2_importers.py", line 352, in exec_module
File anyio\__init__.py", line 104, in ‹module>
File "PyInstaller\loader\pyimod@2_importers.py", line 352, in exec_module
File "anyio\ _core\_sockets.py", line 2, in ‹module>
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "ssl.py", line 100, in ‹module>
ImportError: DLL load failed while importing _ssl: The specified module could not be found.
[19008] Failed to execute script 'main' due to unhandled exception!

**Comment by bwoodsend** [comment]
Are you using Anaconda by any chance?

**Comment by dickreuter** [comment]
yes

From: Brénainn Woodsend ***@***.***>
Date: Friday, 10 March 2023 at 10:43
To: pyinstaller/pyinstaller ***@***.***>
Cc: Nicolas Dickreuter ***@***.***>, Author ***@***.***>
Subject: Re: [pyinstaller/pyinstaller] ImportError: DLL load failed while importing _ssl (Issue #7484)

Are you using Anaconda by any chance?

**Comment by bwoodsend** [comment]
Anaconda is not supported. This kind of issue is precisely why.

**Comment by dickreuter** [comment]
Although fastapi is installed via pip

**Comment by dickreuter** [comment]
I created a venv without anaconda and still have issues with fastapi:

C:\Users\dickr\AppData\Roaming\DeepMind Pokerbot>main
Traceback (most recent call last):
  File "poker\main.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "poker\gui\action_and_signals.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "poker\gui\plots\funds_change_plot.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "poker\tools\game_logger.py", line 9, in <module>
ModuleNotFoundError: No module named 'fastapi'

**Comment by rokm** [comment]
> I created a venv without anaconda and still have issues with fastapi:
> 
> C:\Users\dickr\AppData\Roaming\DeepMind Pokerbot>main Traceback (most recent call last): File "poker\main.py", line 21, in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "poker\gui\action_and_signals.py", line 17, in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "poker\gui\plots\funds_change_plot.py", line 7, in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "poker\tools\game_logger.py", line 9, in ModuleNotFoundError: No module named 'fastapi'

That looks like a [direct import](https://github.com/dickreuter/Poker/blob/bd04bd5a31e4ef63f82a90633eaf2ae1f02553ce/poker/tools/game_logger.py#L9), so it should have been picked up by analysis. 

Do you have `fastapi` installed in your environment, and are you running PyInstaller that's installed in the same environment?

**Comment by dickreuter** [comment]
fixed it by adding fastapi as hidden import

**Comment by dickreuter** [comment]
the error is back, even when adding fastapi as hidden import and not using any anaconda

**Comment by rokm** [comment]
> the error is back, even when adding fastapi as hidden import and not using any anaconda

See https://github.com/pyinstaller/pyinstaller/issues/7510#issuecomment-1478248109. If you can reproduce the problem with simple `import ssl`, then upload the build of that test program somewhere so we can take a look at it. If not, provide the minimum reproducer.
