### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by TheUnknownMystery** [pyinstaller/pyinstaller#7516]
## Description of the issue
Pyinstaller gives "Attribute Error: 'NoneType' object has no attribute 'groups' when compiling python files"

### Context information (for bug reports)
I am using the latest version of pyinstaller (5.9.0)

* Output: 5.9.0
* Python Version: 3.11.2
* Platform: Kali Linux (Debian)
* How you installed Python:  linux package manager (apt install)
* It works on my windows machine but not on my linux machine

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
import subprocess as sb

sb.run(f"pyinstaller --exclude-module _bootlocale --onefile --name {file_name_exe} path_to_folder/{file_name}",shell=True)
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/user/Desktop/path/python-payload-2023-03-25-1679734113.176003.exe.spec", line 6, in <module>
    a = Analysis(['/home/user/Desktop/path/payloads/python-file.py'],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 243, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 575, in assemble
    self._check_python_library(self.binaries)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 666, in _check_python_library
    python_lib = bindepend.get_python_library_path()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/bindepend.py", line 914, in get_python_library_path
    python_libname = findLibrary(name)
                     ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/bindepend.py", line 778, in findLibrary
    utils.load_ldconfig_cache()
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/utils.py", line 375, in load_ldconfig_cache
    path = m.groups()[-1]
           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Based on the traceback, you are not using PyInstaller 5.9, because the lines around 375 should be:

https://github.com/pyinstaller/pyinstaller/blob/77022483b440448c62efd264ab5c5d5dd26b2e03/PyInstaller/depend/utils.py#L371-L383

(i.e., `path = m.groups()[-1]` happens only in line 383).

And this line in the traceback:
```
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
```
further confirms that you are running an outdated version of PyInstaller that's packaged by Kali Linux.
