### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted when --add-binary

### ISSUE THREAD

**Issue by escoolioinglesias** [pyinstaller/pyinstaller#7519]
## Expected behavior
```
pyinstaller --windowed --name "myApp" --additional-hooks-dir=. --add-binary "ffmpeg:." --add-data "logo.png:." --icon=icon.ico myScript.py
```

Successful build that includes ffmpeg binary so user doesn't require ffmpeg installed.

#### Locating ffmpeg in python script:
```
import sys
import os
if getattr(sys, 'frozen', False):
    # Running as a bundled executable (e.g. PyInstaller)
    bundle_dir = sys._MEIPASS
    ffmpeg_binary = os.path.join(bundle_dir, 'ffmpeg')
    os.environ['IMAGEIO_FFMPEG_EXE'] = ffmpeg_binary
```

## Error
```
Traceback (most recent call last):
  File "/opt/miniconda3/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 979, in main
    build(specfile, distpath, workpath, clean_build)
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 901, in build
    exec(code, spec_namespace)
  File "/Users/currentUser/scripts/myScript/myScript.spec", line 42, in <module>
    coll = COLLECT(
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/api.py", line 934, in __init__
    self.__postinit__()
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/api.py", line 977, in assemble
    src_name = checkCache(
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/utils.py", line 233, in checkCache
    os.remove(cachedfile)
PermissionError: [Errno 1] Operation not permitted: '/Users/currentUser/Library/Application Support/pyinstaller/bincache00_py39_64bit/arm64/adhoc/no-entitlements/ffmpeg
```

## System

- macOS Monterey 12.6 M1
- pyInstaller: 5.9.0
- python: 3.9

**Comment by bwoodsend** [comment]
> '/~/Library/Application Support/pyinstaller/bincache00_py39_64bit/arm64/adhoc/no-entitlements/ffmpeg'

How are you locating ffmpeg in your Python code? It's broken - `/~/` is not a valid path.

**Comment by rokm** [comment]
Can you paste the whole traceback so we can see where exactly the error originates from?

**Comment by escoolioinglesias** [comment]
>  '/~/Library/Application Support/pyinstaller/bincache00_py39_64bit/arm64/adhoc/no-entitlements/ffmpeg'

> How are you locating ffmpeg in your Python code? It's broken - /~/ is not a valid path. 

So sorry, that should have read `PermissionError: [Errno 1] Operation not permitted: '/Users/currentUser/Library/Application Support/pyinstaller/bincache00_py39_64bit/arm64/adhoc/no-entitlements/ffmpeg'`

```
import sys
import os
if getattr(sys, 'frozen', False):
    # Running as a bundled executable (e.g. PyInstaller)
    bundle_dir = sys._MEIPASS
    ffmpeg_binary = os.path.join(bundle_dir, 'ffmpeg')
    os.environ['IMAGEIO_FFMPEG_EXE'] = ffmpeg_binary
```

Thank you, I've updated the original post.

**Comment by escoolioinglesias** [comment]
> Can you paste the whole traceback so we can see where exactly the error originates from?

```
Traceback (most recent call last):
  File "/opt/miniconda3/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 979, in main
    build(specfile, distpath, workpath, clean_build)
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 901, in build
    exec(code, spec_namespace)
  File "/Users/currentUser/scripts/myScript/myScript.spec", line 42, in <module>
    coll = COLLECT(
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/api.py", line 934, in __init__
    self.__postinit__()
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/api.py", line 977, in assemble
    src_name = checkCache(
  File "/opt/miniconda3/lib/python3.9/site-packages/PyInstaller/building/utils.py", line 233, in checkCache
    os.remove(cachedfile)
PermissionError: [Errno 1] Operation not permitted: '/Users/currentUser/Library/Application Support/pyinstaller/bincache00_py39_64bit/arm64/adhoc/no-entitlements/ffmpeg
```

Thank you, I've updated the original post.

**Comment by bwoodsend** [comment]
Is `/Users/currentUser/Library/Application Support/pyinstaller/bincache00_py39_64bit/arm64/adhoc/no-entitlements/ffmpeg` owned by root perhaps? Everything you've shown us so far seems pretty benign.

**Comment by rokm** [comment]
> Is `/Users/currentUser/Library/Application Support/pyinstaller/bincache00_py39_64bit/arm64/adhoc/no-entitlements/ffmpeg` owned by root perhaps?

That would be my guess as well.

Try deleting the whole pyinstaller bincache  `/Users/currentUser/Library/Application Support/pyinstaller` (as root, if necessary), and try building again.

**Comment by escoolioinglesias** [comment]
Thank you, deleting it did the trick. Don't know why the permissions got all screwy.

The build was successful, but now I'm having permission issues when using the bundled app, but I'll work on it and if I can't figure it out I'll raise it in another issue.

Thanks again!
