### ISSUE TITLE
MAcOSx codesign

### ISSUE THREAD

**Issue by kteh123** [pyinstaller/pyinstaller#7533]
Hi

I'm using Python 3.9.7 and latest pyinstaller. My commands is:

```
pyinstaller --name app --clean --onefile --noconsole --additional-hooks-dir=. --noconfirm main.py
```

The error i get is as below:

```
Traceback (most recent call last):
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 979, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 901, in build
    exec(code, spec_namespace)
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/wezel.spec", line 24, in <module>
    exe = EXE(
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/api.py", line 576, in __init__
    self.pkg = PKG(
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/api.py", line 233, in __init__
    self.__postinit__()
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/api.py", line 284, in assemble
    src_name = checkCache(
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/utils.py", line 371, in checkCache
    osxutils.sign_binary(cachedfile, codesign_identity, entitlements_file)
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/utils/osx.py", line 359, in sign_binary
    raise SystemError(f"codesign command ({cmd_args}) failed with error code {p.returncode}!\noutput: {p.stdout}")
SystemError: codesign command (['codesign', '-s', '-', '--force', '--all-architectures', '--timestamp', '/Users/kteh/Library/Application Support/pyinstaller/bincache00_py39_64bit/x86_64/adhoc/no-entitlements/PyQt5/Qt/plugins/imageformats/libqmacheif.dylib']) failed with error code 109!
output: The following arguments were not expected: --timestamp --all-architectures
Run with --help for more information.
```
I've seen a lot of other issues similar but sounds like they were resolved when pyinstaller was upgraded? Has anyone got a quick solution as I'm not fussed with codesigning and just need to get an app out. Thank you

Kevin

**Comment by rokm** [comment]
What version of macOS is that?

**Comment by bwoodsend** [comment]
And what xcode version?

**Comment by kteh123** [comment]
Hi I'm on Monterey 12.6.4 and Xcode is version: 14.2.0.0.1.1668646533

**Comment by rokm** [comment]
> Hi I'm on Monterey 12.6.4 and Xcode is version: 14.2.0.0.1.1668646533

Nothing out of ordinary there...

So if you try manually running (after checking that the file still exists there):
```
codesign -s - --force --all-architectures --timestamp "/Users/kteh/Library/Application Support/pyinstaller/bincache00_py39_64bit/x86_64/adhoc/no-entitlements/PyQt5/Qt/plugins/imageformats/libqmacheif.dylib"
```

do you get the same `The following arguments were not expected: --timestamp --all-architectures` error?

What if you try to run it against some other file in that directory?

What version of PyQt5 is that, and how did you install it (the recent versions should have `PyQt5/Qt5/plugins` instead of `PyQt5/Qt/plugins`)?

**Comment by kteh123** [comment]
Running  on terminal

codesign -s - --force --all-architectures --timestamp "/Users/kteh/Library/Application Support/pyinstaller/bincache00_py39_64bit/x86_64/adhoc/no-entitlements/PyQt5/Qt/plugins/imageformats/libqmacheif.dylib"

Gives me:

The following arguments were not expected: --timestamp --all-architecture

That directory only has libqmacheif.dylib. Should I try upgrading PyQt5?

**Comment by rokm** [comment]
What if you copy the original .dylib file from your venv somewhere (i.e., not the copy from PyInstaller's bincache), and try to run that codesign command on the copy? And then check some other plugin .dylib, if the same happens?

I'd like to figure out if this happens for a specific plugin .dylib, or for any of them.

If you tell me the PyQt5 version you are using, I can try reproducing the problem locally as well...

**Comment by kteh123** [comment]
Hi I'm using PyQt5  version 5.13.1. So copied from .venv/.../imageformats/.. to desktop and ran the commands got as below:

(base) kteh@dyn140176 Application Support % codesign -s - --force --all-architectures --timestamp "/Users/kteh/Desktop/pyinstaller_debug/libqmacheif.dylib" 
The following arguments were not expected: --timestamp --all-architectures
Run with --help for more information.
(base) kteh@dyn140176 Application Support % codesign -s - --force --all-architectures --timestamp "/Users/kteh/Desktop/pyinstaller_debug/libqgif.dylib" 
The following arguments were not expected: --timestamp --all-architectures
Run with --help for more information.

**Comment by kteh123** [comment]
Not sure if this helps. I'e deleted PyQt5 from my app and tried Pyside2 and have the same issues as below:

Traceback (most recent call last):
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 979, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 901, in build
    exec(code, spec_namespace)
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/wezel.spec", line 24, in <module>
    exe = EXE(
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/api.py", line 576, in __init__
    self.pkg = PKG(
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/api.py", line 233, in __init__
    self.__postinit__()
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/api.py", line 284, in assemble
    src_name = checkCache(
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/building/utils.py", line 371, in checkCache
    osxutils.sign_binary(cachedfile, codesign_identity, entitlements_file)
  File "/Users/kteh/Desktop/AFFIRM/Github/AFiRM/.venv/lib/python3.9/site-packages/PyInstaller/utils/osx.py", line 359, in sign_binary
    raise SystemError(f"codesign command ({cmd_args}) failed with error code {p.returncode}!\noutput: {p.stdout}")
SystemError: codesign command (['codesign', '-s', '-', '--force', '--all-architectures', '--timestamp', '/Users/kteh/Library/Application Support/pyinstaller/bincache00_py39_64bit/x86_64/adhoc/no-entitlements/PySide2/Qt/plugins/imageformats/libqwebp.dylib']) failed with error code 109!
output: The following arguments were not expected: --timestamp --all-architectures

**Comment by rokm** [comment]
Hmmm, so perhaps it is not tied to the target binary, but rather to the `codesign` command itself (I cannot reproduce this, but my test system is 12.6.3, and the GA runners run the same version).

Just to verify, can you try running the same codesign command against a copy of some other shared library (e.g., a python shared library), or some executable?

Can you also check the output of `codesign --help` and paste it here? And maybe see if `man codesign` contains any mention of `--timestamp` and `--all-architectures`?

----

FWIW, we could probably omit `--timestamp` for ad-hoc signing, nonetheless because it requires internet connection to reach (default) Apple's time server. And from the man page on my test system, it seems that `--all-architectures` is redundant anyway (because it is the default).

So for a quick attempt at fix, you can try removing those arguments from the following places in your local PyInstaller:

https://github.com/pyinstaller/pyinstaller/blob/fe73e51cebeb595b7923b3eda3da8ec14c08e7c3/PyInstaller/utils/osx.py#L356

https://github.com/pyinstaller/pyinstaller/blob/fe73e51cebeb595b7923b3eda3da8ec14c08e7c3/PyInstaller/utils/osx.py#L334

**Comment by kteh123** [comment]
Hi Not sure about your question. I'm trying to run pyinstaller on a github repo with pyside2 (reason why it failed?) 

(.venv) (base) kteh@dyn140176 AFiRM % codesign --help
codesign
Usage: codesign [OPTIONS] [files...]

Positionals:
  files TEXT ...              Files to sign

Options:
  -h,--help                   Print this help message and exit
  -s,--sign TEXT REQUIRED     Code signing identity
  -i,--identifier TEXT        File identifier
  -f,--force                  Replace any existing signatures
  --entitlements TEXT         Entitlements plist

Hi below are my outputs of timestamp and all architecture when i do a man codesign:

OPTIONS
     The options are as follows:

     --all-architectures
             When verifying a code signature on code that has a universal ("fat") Mach-O binary, separately verify each architecture contained. This is the default unless overridden with the -a (--architecture) option.

 --timestamp [=URL]
             During signing, requests that a timestamp authority server be contacted to authenticate the time of signing. The server contacted is given by the URL value.  If this option is given without a value, a default
             server provided by Apple is used.  Note that this server may not support signatures made with identities not furnished by Apple.  If the timestamp authority service cannot be contacted over the Internet, or it
             malfunctions or refuses service, the signing operation will fail.
             If this option is not given at all, a system-specific default behavior is invoked.  This may result in some but not all code signatures being timestamped.
             The special value none explicitly disables the use of timestamp services.

I have commented those lines out.  Also ones that rely on them. And I sucessfully built the app. Thank you.

**Comment by rokm** [comment]
> ```
> (.venv) (base) kteh@dyn140176 AFiRM % codesign --help
> codesign
> Usage: codesign [OPTIONS] [files...]
> 
> Positionals:
> files TEXT ... Files to sign
> 
> Options:
> -h,--help Print this help message and exit
> -s,--sign TEXT REQUIRED Code signing identity
> -i,--identifier TEXT File identifier
> -f,--force Replace any existing signatures
> --entitlements TEXT Entitlements plist
> ```

This does not look like the output of the Apple's `codesign` utility, which should be:
```
$ codesign --help
Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
       codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
       codesign -d [options] path ... # display contents
       codesign -h pid ... # display hosting paths
```

Do you have some wrapper script or a 3rd party utility with the same name installed in your environment? 

What is the output of `which codesign`? (should be `/usr/bin/codesign`)

**Comment by kteh123** [comment]
Ahh ok thank you. which codesign gives me:

/Users/kteh/fsl/bin/codesign

I will change it back.
