### ISSUE TITLE
name 'base_events' is not defined when running the exe for asyncio

### ISSUE THREAD

**Issue by vvacc** [pyinstaller/pyinstaller#7538]
## Description of the issue

Error running the exe file:
NameError: name 'base_events' is not defined

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.9.0
* Version of Python: 3.10
* Platform:  Windows
* How you installed Python: pip
* Did you also try this on another platform? Does it work there?
* aiohttp 3.8.4
* asyncio 3.4.3

### Stacktrace / full error message

```
C:\dist>wsgi.exe
Traceback (most recent call last):
File "wsgi.py", line 6, in <module>
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "aiohttp_init.py", line 6, in <module>
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "aiohttp\client.py", line 3, in <module>
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "asyncio_init.py", line 23, in <module>
NameError: name 'base_events' is not defined
[21348] Failed to execute script 'wsgi' due to unhandled exception!
```

**Comment by rokm** [comment]
What does line 6 in `wsgi.py` do - `import aiohttp`? Can you reproduce the error if you try to freeze a simple script that does just `import aiohttp`?

**Comment by vvacc** [comment]
yes it was import aiohttp.

Tried to freeze the following script, wsgi.py:

`
import aiohttp

if name == "main":
    print('Hello')`

with this build comand:
pyinstaller.exe --onefile --hidden-import="asyncio" wsgi.py

the following error appeared:

M:\dist>wsgi.exe
Traceback (most recent call last):
File "wsgi.py", line 1, in <module>
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "aiohttp_init.py", line 6, in <module>
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "aiohttp\client.py", line 3, in <module>
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "asyncio_init.py", line 39, in <module>
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "asyncio\windows_events.py", line 8, in <module>
OSError: [WinError 10022] An invalid argument was supplied

**Comment by rokm** [comment]
>  OSError: [WinError 10022] An invalid argument was supplied

Is M:\ a network drive? Executables running from network drives tend to end up with such errors when they attempt to use Windows network socket library...

**Comment by vvacc** [comment]
Yes is a network drive.

**Comment by rokm** [comment]
> Yes is a network drive.

That won't work, as explained above - move to a local drive.

**Comment by vvacc** [comment]
Clear thanks.
