### ISSUE TITLE
ValueError: bytes must be in range

### ISSUE THREAD

**Issue by sun152121** [pyinstaller/pyinstaller#7540]
pyinstaller --onefile main.py

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Program Files (x86)\Python\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\__main__.py", line 107, in run
    parser = generate_parser()
             ^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\__main__.py", line 78, in generate_parser
    import PyInstaller.building.build_main
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\building\build_main.py", line 35, in <module>
    from PyInstaller.depend import bindepend
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\depend\bindepend.py", line 26, in <module>
    from PyInstaller.depend import dylib, utils
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\depend\utils.py", line 33, in <module>
    from PyInstaller.depend import bytecode
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\depend\bytecode.py", line 95, in <module>
    _call_function_bytecode = bytecode_regex(rb"""
                              ^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\depend\bytecode.py", line 60, in bytecode_regex
    pattern = re.sub(
              ^^^^^^^
  File "D:\Program Files (x86)\Python\Lib\re\__init__.py", line 186, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\depend\bytecode.py", line 62, in <lambda>
    lambda m: _instruction_to_regex(m[1].decode()),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Python\Lib\site-packages\PyInstaller\depend\bytecode.py", line 40, in _instruction_to_regex
    return re.escape(bytes([dis.opmap[x]]))
                     ^^^^^^^^^^^^^^^^^^^^^
ValueError: bytes must be in range(0, 256)

**Comment by sun152121** [comment]
Requirement already satisfied: pyinstaller in d:\program files (x86)\python\lib\site-packages (4.5.1)
Requirement already satisfied: setuptools in d:\program files (x86)\python\lib\site-packages (from pyinstaller) (65.5.0)
Requirement already satisfied: altgraph in d:\program files (x86)\python\lib\site-packages (from pyinstaller) (0.17.3)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in d:\program files (x86)\python\lib\site-packages (from pyinstaller) (2023.1)
Requirement already satisfied: pefile>=2017.8.1 in d:\program files (x86)\python\lib\site-packages (from pyinstaller) (2023.2.7)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in d:\program files (x86)\python\lib\site-packages (from pyinstaller) (0.2.0)

**Comment by rokm** [comment]
> Requirement already satisfied: pyinstaller in d:\program files (x86)\python\lib\site-packages (4.5.1)

Looks like you're using an outdated version of PyInstaller, which is likely incompatible with your python version (which you did not specify...).
