### ISSUE TITLE
problem using tensorflow imported by segmentation models

### ISSUE THREAD

**Issue by vairadiology-portal** [pyinstaller/pyinstaller#7565]
Tried to package a python program that contains imports from tensorflow 2.9.0, keras 2.9.0 and segmentation-models 1.0.1. Got this problem when executing the created exe on Windows 64 bit:

Traceback (most recent call last):
  File "tensorflow\python\autograph\core\ag_ctx.py", line 97, in <module>
  File "inspect.py", line 1147, in getsource
  File "inspect.py", line 1129, in getsourcelines
  File "inspect.py", line 958, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vai_master.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "mainwindow.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "sn_button.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "segmentation_models\__init__.py", line 98, in <module>
  File "segmentation_models\__init__.py", line 67, in set_framework
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "keras\__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\data\__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\data\experimental\__init__.py", line 124, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\data\experimental\ops\parsing_ops.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\ops\parsing_ops.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\ops\parsing_config.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\ops\ragged\ragged_math_ops.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\ops\map_fn.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\autograph\__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\autograph\impl\api.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\autograph\core\ag_ctx.py", line 100, in <module>
  File "tensorflow\python\autograph\utils\ag_logging.py", line 145, in warning
AttributeError: 'NoneType' object has no attribute 'flush'

**Comment by rokm** [comment]
> Tried to package a python program that contains imports from tensorflow 2.9.0, keras 2.9.0 and segmentation-models 1.0.1. Got this problem when executing the created exe on Windows 64 bit:
> 
> Traceback (most recent call last): File "tensorflow\python\autograph\core\ag_ctx.py", line 97, in File "inspect.py", line 1147, in getsource File "inspect.py", line 1129, in getsourcelines File "inspect.py", line 958, in findsource OSError: could not get source code
> 
> ```
> During handling of the above exception, another exception occurred:
> ...
> File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> File "tensorflow\python\autograph\core\ag_ctx.py", line 100, in
> File "tensorflow\python\autograph\utils\ag_logging.py", line 145, in warning
> AttributeError: 'NoneType' object has no attribute 'flush'
>```

You are probably building with `noconsole`/`ẁindowed`  and `tensorflow`'s logging is naively assuming that `sys.stdout` and `sys.stderr` are available, whereas as of #7217, they are `None`. See for example https://github.com/pyinstaller/pyinstaller/issues/7334#issuecomment-1357447176 on how to set dummy streams with `os.devnull`.

However, this is a secondary issue...

>```
>Traceback (most recent call last):
>File "tensorflow\python\autograph\core\ag_ctx.py", line 97, in
>File "inspect.py", line 1147, in getsource
>File "inspect.py", line 1129, in getsourcelines
>File "inspect.py", line 958, in findsource
>OSError: could not get source code
>```

And this is the primary issue. A `tensorflow`-based package you are using (presumably `segmentation-models`?) requires source .py files to be collected, and PyInstaller does not collect those by default. So you need to ensure those are collected.

One way is using a `collect_data_files('segmentation_models', include_py_files=True)` in a custom hook or directly in the spec file. Another way is using the more recent package collection mode mechanism from #6945, again either in a hook via [global hook variable](https://pyinstaller.org/en/stable/hooks.html#hook-global-variables) or directly in the spec file, like this:
```
a = Analysis(
     ...
    module_collection_mode={
        "segmentation_models": "pyz+py",
    },
)
```

**Comment by vairadiology-portal** [comment]
I built the app using this spec:
`# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['vai_master.py'],
    pathex=[],
    binaries=[],
    datas=[('./Vairadiology logo.png', '.')],
    hiddenimports=['pydicom.encoders.gdcm', 'pydicom.encoders.pylibjpeg', 'skimage.filters.edges'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    module_collection_mode={
        "segmentation_models": "pyz+py",
    },
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='vai_master',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    `argv_emulation=False,`
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)`

And got the same output when running the executable:

`Traceback (most recent call last):
  File "tensorflow\python\autograph\core\ag_ctx.py", line 97, in <module>
  File "inspect.py", line 1147, in getsource
  File "inspect.py", line 1129, in getsourcelines
  File "inspect.py", line 958, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vai_master.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "mainwindow.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "sn_button.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "segmentation_models\__init__.py", line 98, in <module>
    set_framework(_framework)
  File "segmentation_models\__init__.py", line 67, in set_framework
    import keras
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "keras\__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\data\__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\data\experimental\__init__.py", line 124, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\data\experimental\ops\parsing_ops.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\ops\parsing_ops.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\ops\parsing_config.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\ops\ragged\ragged_math_ops.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\ops\map_fn.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\autograph\__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\autograph\impl\api.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "tensorflow\python\autograph\core\ag_ctx.py", line 100, in <module>
  File "tensorflow\python\autograph\utils\ag_logging.py", line 145, in warning
AttributeError: 'NoneType' object has no attribute 'flush'
`

**Comment by rokm** [comment]
In that case, there's another package whose sources are still missing - perhaps `keras`? If not, you'll have to track it down yourself, or give us a minimum example that triggers the error.

**Comment by vairadiology-portal** [comment]
Any idea how to track this error? I sent in my previous message the new error output I get when using the spec with your previous suggestion

**Comment by rokm** [comment]
Try adding `"keras": "pyz+py"` to the `module_collection_mode` dictionary. On my test system, that silences a warning about AutoGraph not being available:
``` 
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
```

Now that I think about it, perhaps what's going on is that this warning is also being generated in your case, but it triggers another error due to lack of console. So for the time being, also change `console=False` to `console=True` (and run the executable from command prompt instead of double-clicking on it, so you can see the console output).

**Comment by rokm** [comment]
And once you change back to `console=False`, make sure to provide dummy file objects for `sys.stdout` and `sys.stderr` as per https://github.com/pyinstaller/pyinstaller/issues/7334#issuecomment-1357447176 to avoid issues with naive logging systems.

**Comment by vairadiology-portal** [comment]
Thank you very much. Adding the "keras": "pyz+py" to the .spec file and setting console=True solved the issue. However, when I set console=False and following the issue you commented (added the following lines to the beginning of each file), the issue persists:

if sys.stdout is None:
    sys.stdout = open(os.devnull, "w")
if sys.stderr is None:
    sys.stderr = open(os.devnull, "w")

**Comment by rokm** [comment]
You added the
```python
if sys.stdout is None:
    sys.stdout = open(os.devnull, "w")
if sys.stderr is None:
    sys.stderr = open(os.devnull, "w")
```
block at the start of your program (`vai_master.py`), before you import `tensorflow`/`keras`/`segmentation_models`?
