### ISSUE TITLE
Flask application not rendering index.html

### ISSUE THREAD

**Issue by rafael-wampfler** [pyinstaller/pyinstaller#7567]
Hello

I'm using v5.9.0 and Python 3.11 to compile my Python Flask server into a standalone. For this I'm using the following server.spec file:

```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata
from PyInstaller.utils.hooks import collect_submodules  # Added
import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)

datas = []
datas += collect_data_files('torch')
datas += copy_metadata('torch')
datas += copy_metadata('tqdm')
datas += copy_metadata('regex')
datas += copy_metadata('requests')
datas += copy_metadata('packaging')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')
datas += copy_metadata('importlib_metadata')
datas += copy_metadata('deepspeed')
datas += collect_data_files('ninja')
datas += collect_data_files('deepspeed')

# Added
hiddenimports = []
hiddenimports = collect_submodules('deepspeed')

block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports, 
    #hiddenimports=['pytorch', 'deepspeed'], NOTE: pytorch is not a valid module name, and deepspeed is ncluded in collect_submodules output
    hookspath=['pyinstaller-hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    # Added
    module_collection_mode={
        "deepspeed": "pyz+py",
    },
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

I have in `chatbot/server/pyinstaller-hooks/hook-server.py`:

```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('server')
```

The starting point of my application is in `chatbot/server/main.py` (server is a package) and to setup Flask I'm using:

```
base_dir = '.'
if hasattr(sys, '_MEIPASS'):
    base_dir = os.path.join(sys._MEIPASS)
app = Flask(__name__, static_folder=os.path.join(base_dir, 'static'), template_folder=os.path.join(base_dir, 'templates'))
```

When running main.py I'm getting the error `jinja2.exceptions.TemplateNotFound: index.html`

**Comment by rokm** [comment]
Have you verified that your files are in fact collected, and are collected where you expect them to be? Either by switching to onedir build until you have things figured out, by inspecting `build/<name>/Analysis-00.toc` or by inspecting the generated executable using `pyi-archive_viewer`?

Because if nothing else, that `hook-server.py` hook *should*\* be collecting data files from `server` package into `server` directory in your frozen application's top-level directory, and your `os.path.join(base_dir, 'static')` seems to assume that `static` directory is located in your frozen application's top-level directoy - but if that was supposed to be collected from `server`, then it should be `sys._MEIPASS/server/static`.

\* It should, provided that `server` is discoverable package from PyInstaller's point of view - but I think I recall from your other issue that it should be...

**Comment by rafael-wampfler** [comment]
Thank you very much, `sys._MEIPASS/server/static` did the trick. Unfortunately, I'm getting now another Flask error for a post message:

```
2023-04-14 10:29:12 ERROR    Exception on /new_user [POST]
Traceback (most recent call last):
  File "urllib3/connection.py", line 174, in _new_conn
  File "urllib3/util/connection.py", line 95, in create_connection
  File "urllib3/util/connection.py", line 85, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 703, in urlopen
  File "urllib3/connectionpool.py", line 398, in _make_request
  File "urllib3/connection.py", line 239, in request
  File "http/client.py", line 1282, in request
  File "http/client.py", line 1328, in _send_request
  File "http/client.py", line 1277, in endheaders
  File "http/client.py", line 1037, in _send_output
  File "http/client.py", line 975, in send
  File "urllib3/connection.py", line 205, in connect
  File "urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5d480ea5d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 489, in send
  File "urllib3/connectionpool.py", line 787, in urlopen
  File "urllib3/util/retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='<REDACTED>', port=5005): Max retries exceeded with url: /webhooks/rest/webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d480ea5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 2073, in wsgi_app
  File "flask/app.py", line 1518, in full_dispatch_request
  File "flask/app.py", line 1516, in full_dispatch_request
  File "flask/app.py", line 1502, in dispatch_request
  File "server/main.py", line 259, in new_user
  File "server/server_utils.py", line 379, in restart_server
  File "server/server_utils.py", line 367, in send_user_msg
  File "requests/api.py", line 115, in post
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 587, in request
  File "requests/sessions.py", line 701, in send
  File "requests/adapters.py", line 565, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='<REDACTED>', port=5005): Max retries exceeded with url: /webhooks/rest/webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d480ea5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by rokm** [comment]
No idea about this one, sorry. Is your flask server trying to connect somewhere?

**Comment by rafael-wampfler** [comment]
No, the Flask server just handles the post request, then calls a Huggingface model and returns the result.

**Comment by rokm** [comment]
If you omit the Hugginface model and just return a dummy result, do you get the same error (i.e., is the issue purely on the flask side, or is transformers involved)? If the former, can you isolate the error into simple stand-alone reproducer?

**Comment by rokm** [comment]
Also, to clarify - so the IP and port in the traceback is your server's address and the connection attempts we see in the traceback are internal?

**Comment by rafael-wampfler** [comment]
I will test it later today and let you know. Can you please hide the IP address in your and my post? It should not be public ;) thank you a lot.

**Comment by rafael-wampfler** [comment]
It works now. It was somehow a spurious error and I don't know why it appeared. Seems to be related to Flask and not Pyinstaller.
