### ISSUE TITLE
UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.   return original_import(name, *args, **kwargs)

### ISSUE THREAD

**Issue by vigilancetrent** [pyinstaller/pyinstaller#7578]
```python
77196 INFO: Looking for dynamic libraries
C:\Users\bill\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py:142: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  return original_import(name, *args, **kwargs)
Traceback (most recent call last):
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\isolated\_parent.py", line 373, in call
    return isolated.call(function, *args, **kwargs)
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
    sys.exit(_console_script_run())
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 977, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 899, in build
    exec(code, spec_namespace)
  File "C:\Users\bill\Desktop\solonetwork\tradingview\trderX-master\source\zimpot.spec", line 7, in <module>
    a = Analysis(
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 412, in __init__
    self.__postinit__()
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 695, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    with Python() as isolated:
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\isolated\_parent.py", line 244, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument
```

**Comment by bwoodsend** [comment]
The warning is just noise. The actual error is that `find_binary_dependencies()` appears to be loading something which causes the process to either hard abort or sever its pipes. Can we have a `pip freeze` then rerun after injecting a `print(package)` [here](https://github.com/pyinstaller/pyinstaller/blob/b4d87c24f2447f1aa6b8a44f7fd01f197e81b331/PyInstaller/building/build_main.py#L176)?
