### ISSUE TITLE
Crash when building a project with SQLAlchemy 1.4 -  QWidget: Must construct a QApplication before a QWidget and EOFError

### ISSUE THREAD

**Issue by c-buzz** [pyinstaller/pyinstaller#7600]
Full background has already been reported on [SO](https://stackoverflow.com/q/76121347/5321862).

I'm working with `Windows 10` -  `SQLAlchemy 1.4.41`. Virtual environment specifics are into the log.

**The problem disappears if `sqlalchemy-2.0.11` is installed**

The full log is also here reported:

```
566 INFO: PyInstaller: 5.10.1
566 INFO: Python: 3.8.10
578 INFO: Platform: Windows-10-10.0.19042-SP0
588 INFO: UPX is not available.
588 INFO: Extending PYTHONPATH with paths
['D:\\workspace\\MySolution\\src']
1089 INFO: checking Analysis
1089 INFO: Building Analysis because Analysis-00.toc is non existent
1089 INFO: Initializing module dependency graph...
1089 INFO: Caching module graph hooks...
1109 INFO: Analyzing base_library.zip ...
2784 INFO: Loading module hook 'hook-heapq.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
2986 INFO: Loading module hook 'hook-encodings.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
4206 INFO: Loading module hook 'hook-pickle.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
5247 INFO: Caching module dependency graph...
5396 INFO: running Analysis Analysis-00.toc
5402 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python38\python.exe
5462 INFO: Analyzing D:\workspace\MySolution\src\MyProject2\main.py
5502 INFO: Loading module hook 'hook-PySide2.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
6071 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
6272 INFO: Loading module hook 'hook-xml.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
6684 INFO: Loading module hook 'hook-numpy.py' from 'D:\\workspace\\venvs\\MySolution\\Lib\\site-packages\\numpy\\_pyinstaller'...
7637 INFO: Loading module hook 'hook-difflib.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
7739 INFO: Loading module hook 'hook-platform.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
7939 INFO: Loading module hook 'hook-sysconfig.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
8912 INFO: Loading module hook 'hook-scipy.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
9023 INFO: Loading module hook 'hook-scipy.linalg.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
9263 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
10806 INFO: Loading module hook 'hook-matplotlib.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
11211 INFO: Loading module hook 'hook-packaging.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
11311 INFO: Processing pre-safe import module hook gi from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-gi.py'.
11391 INFO: Loading module hook 'hook-PIL.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
11451 INFO: Loading module hook 'hook-PIL.Image.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
12276 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
13313 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
14086 INFO: Processing pre-safe import module hook six.moves from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
15406 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
17176 INFO: Loading module hook 'hook-pandas.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
18991 INFO: Loading module hook 'hook-pytz.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
19255 INFO: Loading module hook 'hook-pkg_resources.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
22055 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
24379 INFO: Loading module hook 'hook-pandas.plotting.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
25733 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
25753 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
26204 INFO: Loading module hook 'hook-sqlalchemy.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
27707 INFO: Loading module hook 'hook-sqlite3.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
28659 INFO: Loading module hook 'hook-pyqtgraph.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
620 WARNING: Failed to collect submodules for 'pyqtgraph.opengl' because importing 'pyqtgraph.opengl' raised: ModuleNotFoundError: No module named 'OpenGL'
31556 INFO: Loading module hook 'hook-cv2.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
31596 INFO: Loading module hook 'hook-scipy.io.matlab.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
32841 INFO: Loading module hook 'hook-pygments.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
35321 INFO: Processing module hooks...
35602 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
35602 INFO: Matplotlib backend selection method: automatic discovery of used backends
35981 INFO: Trying determine the default backend as first importable candidate from the list: ['Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
36565 INFO: Selected matplotlib backends: ['Qt5Agg']
36916 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
36976 INFO: Processing pre-safe import module hook win32com from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
39208 INFO: Loading module hook 'hook-PySide2.QtCore.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
39576 INFO: Loading module hook 'hook-PySide2.QtDataVisualization.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
39951 INFO: Loading module hook 'hook-PySide2.QtGui.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
40389 INFO: Loading module hook 'hook-PySide2.QtMultimedia.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
40697 INFO: Loading module hook 'hook-PySide2.QtMultimediaWidgets.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
41002 INFO: Loading module hook 'hook-PySide2.QtNetwork.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
41634 INFO: Loading module hook 'hook-PySide2.QtSerialPort.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
41933 INFO: Loading module hook 'hook-PySide2.QtSql.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
42233 INFO: Loading module hook 'hook-PySide2.QtSvg.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
42540 INFO: Loading module hook 'hook-PySide2.QtTest.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
42844 INFO: Loading module hook 'hook-PySide2.QtWidgets.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
43216 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
43216 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
43216 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
43216 INFO: Loading module hook 'hook-sqlalchemy.py' from 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks'...
43553 WARNING: Hidden import "pysqlite2" not found!
43553 WARNING: Hidden import "MySQLdb" not found!
43553 WARNING: Hidden import "psycopg2" not found!
44394 INFO: checking Tree
44394 INFO: Building because root changed
44394 INFO: Building Tree Tree-00.toc
44408 INFO: checking Tree
44408 INFO: Building because root changed
44408 INFO: Building Tree Tree-01.toc
44408 INFO: Looking for ctypes DLLs
44452 WARNING: Ignoring /System/Library/Frameworks/IOKit.framework/IOKit imported from D:\workspace\venvs\MySolution\lib\site-packages\serial\tools\list_ports_osx.py - only basenames are supported with ctypes imports!
44452 WARNING: Ignoring /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation imported from D:\workspace\venvs\MySolution\lib\site-packages\serial\tools\list_ports_osx.py - only basenames are supported with ctypes 
imports!
44462 INFO: Analyzing run-time hooks ...
44482 INFO: Including run-time hook 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
44483 INFO: Including run-time hook 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
44483 INFO: Including run-time hook 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
44483 INFO: Including run-time hook 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
44494 INFO: Including run-time hook 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
44494 INFO: Including run-time hook 'D:\\workspace\\venvs\\MySolution\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyside2.py'
44545 INFO: Looking for dynamic libraries
D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\building\build_main.py:177: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
QWidget: Must construct a QApplication before a QWidget
Traceback (most recent call last):
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\isolated\_parent.py", line 293, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\workspace\venvs\MySolution\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\building\build_main.py", line 978, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\building\build_main.py", line 900, in build
    exec(code, spec_namespace)
  File "MyProject2.spec", line 7, in <module>
    a = Analysis(
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\building\build_main.py", line 424, in __init__
    self.__postinit__()
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\building\build_main.py", line 696, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File "D:\workspace\venvs\MySolution\lib\site-packages\PyInstaller\isolated\_parent.py", line 247, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument
```

**Comment by bwoodsend** [comment]
Looks similar to #7578. [My unanswered question there](https://github.com/pyinstaller/pyinstaller/issues/7578#issuecomment-1512325709) applies here.

**Comment by rokm** [comment]
> QWidget: Must construct a QApplication before a QWidget

One of the modules/packages we import during during dynamic libraries search seems to be instantiating a QWidget during its initialization. To figure out which module/package it is (and why it is doing that), add a `print(package)` [here](https://github.com/pyinstaller/pyinstaller/blob/b4d87c24f2447f1aa6b8a44f7fd01f197e81b331/PyInstaller/building/build_main.py#L176) as suggested in https://github.com/pyinstaller/pyinstaller/issues/7578#issuecomment-1512325709.
