### ISSUE TITLE
init.tcl not found, if more than one Python source file

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#763]
**Original date**: 2013/09/06
**Original reporter**: *mselve AND de DOT ibm DOT  COOM *

The executable built by Pyinstaller fails with:

```
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\<user>\Documents\workspace\TestTcl\build\test_tcl\out00-PYZ.
pyz\testGUI", line 16, in __init__
  File "C:\Users\<user>\Documents\workspace\TestTcl\build\test_tcl\out00-PYZ.
pyz\Tkinter", line 1745, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/<user>/AppData/Local/Temp/lib/tcl8.5
...
```

This happens if the Python code is in two source files.  If everything is put in one Python source file, it works.  I also tried a recent development version (pyinstaller-v2.0-589-g15983b2) and it has the same problem.  It worked in Pyinstaller 1.5.1 though, but unfortunately I can't use version 1.5.1 anymore as I switched to Windows 7 and version 1.5.1 does not work on Windows 7.  It does not matter whether called with the option --onefile or without it, both executables fail with the same error.

Here is minimal test case, enriched with checks for TCL_LIBRARY (inspired by pyinstaller-2.0\buildtests\librariestest_onefile_tkinter.py):

test_tcl.py:

```
from testGUI import WarningWindow, compare
import os
import sys

try:
    tcl_dir = os.environ['TCL_LIBRARY']
    tk_dir = os.environ['TK_LIBRARY']
    compare('Main Tcl', os.path.join(sys.prefix, '_MEI', 'tcl'), tcl_dir)
    compare('Main Tk', os.path.join(sys.prefix, '_MEI', 'tk'), tk_dir)
except KeyError:
    print('Main: TCL_LIBRARY or TK_LIBRARY not set up.')

warnwin = WarningWindow('A warning')
warnwin.mainloop()
```

testGUI.py:

```
import Tkinter
import os
import glob
import sys

class WarningWindow():
    def __init__(self, warn_text):
        try:
            tcl_dir = os.environ['TCL_LIBRARY']
            tk_dir = os.environ['TK_LIBRARY']
            compare('Win Tcl', os.path.join(sys.prefix, '_MEI', 'tcl'), tcl_dir)
            compare('Win Tk', os.path.join(sys.prefix, '_MEI', 'tk'), tk_dir)
        except KeyError:
            print('Win: TCL_LIBRARY or TK_LIBRARY not set up.')

        self.root = Tkinter.Tk()
        
        self.text0 = Tkinter.Label(self.root, text=warn_text,justify='left', bg='orange')
        self.text0.grid(row=0)

        self.button_ok = Tkinter.Button(self.root, text='OK', command=self.ok)
        self.button_ok.grid(row=1)
        
    def ok(self):
        self.root.destroy()
        
    def mainloop(self):
        self.root.protocol('WM_DELETE_WINDOW', self.root.destroy)
        self.root.mainloop()
        
class compare():
    def __init__(self, test_name, expect, frozen):
        expect = os.path.normpath(expect)
        print(test_name)
        print('  Expected: ' + expect)
        print('  Current:  ' + frozen)
        print('')
        # Path must match.
        if not frozen == expect:
            raise SystemExit('Data directory is not set properly.')
        # Directory must exist.
        if not os.path.exists(frozen):
            raise SystemExit('Data directory does not exist.')
        # Directory must contain some .tcl files and not to be empty.
        if not len(glob.glob(frozen + '/*.tcl')) > 0:
            raise SystemExit('Data directory does not contain .tcl files.')
```

Command line called:

python "C:\Program Files\pyinstaller-2.0\pyinstaller.py" --onefile src\test_tcl.py src\testGUI.py

The output when running dist\test_tcl.exe:

```
Main: TCL_LIBRARY or TK_LIBRARY not set up.
Win: TCL_LIBRARY or TK_LIBRARY not set up.
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "C:\Users\<user>\Documents\workspace\TestTcl\build\pyi.win32\test_tcl\
out00-PYZ.pyz\testGUI", line 16, in __init__
  File "C:\Users\<user>\Documents\workspace\TestTcl\build\pyi.win32\test_tcl\
out00-PYZ.pyz\Tkinter", line 1745, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/<user>/AppData/Local/Temp/lib/tcl8.5
...
```

So it seems Pyinstaller 2.0 forgot to set up TCL_LIBRARY when it works on more than one Python source file.  Can this be fixed soon or can you suggest a circumvention?

Regards.

**Comment by matysek** [comment]
Tcl should work.

**Comment by hclivess** [comment]
same problem here, windows 7 64bit seems to be the issue, works normally in win 8 64
