### ISSUE TITLE
PyInstaller crashes when packaging my program due to a KeyError in api.py.

### ISSUE THREAD

**Issue by drunkwcodes** [pyinstaller/pyinstaller#7631]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.11.0```
* Version of Python: 3.10.11
* Platform: Windows 10
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['InspectorUSBMain.py'],
             pathex=['D:\\projects\\InspectorUSB\\src\\InspectorUSB',
			 'D:\\projects\\InspectorUSB\\venv\\Lib\\site-packages\\qt_material'],
             binaries=[],
             datas=[('ui/*.*','ui'),('clientToolU/*.*','clientToolU')],
             hiddenimports=['qt_material','PySide2.QtGui',
			 'PySide2.QtCore','PySide2.QtWidgets','numpy','matplotlib','scipy'],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
a.datas += [('logo.png','D:\\projects\\InspectorUSB\\src\\InspectorUSB\\ui\\icon.png','ui')]
a.datas += [('logo.ico','D:\\projects\\InspectorUSB\\src\\InspectorUSB\\ui\\icon.ico','ui')]
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
			 

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='InspectorUSBMain',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None, icon='D:\\projects\\InspectorUSB\\src\\InspectorUSB\\ui\\icon.ico' )

```

### Stacktrace / full error message

```
27149 INFO: Building PKG (CArchive) InspectorUSBMain.pkg
Traceback (most recent call last):
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\projects\InspectorUSB\venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\building\build_main.py", line 1006, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\building\build_main.py", line 928, in build
    exec(code, spec_namespace)
    exe = EXE(pyz,
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\building\api.py", line 566, in __init__
    self.pkg = PKG(
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\building\api.py", line 240, in __init__
    self.__postinit__()
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "D:\projects\InspectorUSB\venv\lib\site-packages\PyInstaller\building\api.py", line 311, in assemble
    archive_toc.append((dest_name, src_name, self.cdict.get(typecode, False), self.xformdict[typecode]))
KeyError: 'ui'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> a.datas += [('logo.png','D:\\projects\\InspectorUSB\\src\\InspectorUSB\\ui\\icon.png','ui')]
> a.datas += [('logo.ico','D:\\projects\\InspectorUSB\\src\\InspectorUSB\\ui\\icon.ico','ui')]

The format for TOC tuples is (dest_name, src_name, typecode), and `'ui'` is not a valid TOC typecode. Don't try to modify the lists produced by Analysis if you don't know what you are doing - for adding data, use the input `datas` argument instead...

**Comment by drunkwcodes** [comment]
@rokm Thanks for your help.
