### ISSUE TITLE
Building error while using Python: 3.8.10 on linux 

### ISSUE THREAD

**Issue by Pandaa-P** [pyinstaller/pyinstaller#7644]
Trying to compile a project I have to work on windows  but I got this error. 

Pyinstaller --version: 5.11.0
Python: 3.8.10
OS: Linux
I need to use Python: 3.8.10 because of legacy system which require old python version that support it. 
```
102 INFO: PyInstaller: 5.11.0
103 INFO: Python: 3.8.10
115 INFO: Platform: Linux-5.4.0-92-generic-x86_64-with-glibc2.29
121 INFO: UPX is available.
123 INFO: Extending PYTHONPATH with paths
['/home/jackpc/Desktop/test']
421 INFO: checking Analysis
421 INFO: Building Analysis because Analysis-00.toc is non existent
421 INFO: Initializing module dependency graph...
423 INFO: Caching module graph hooks...
433 INFO: Analyzing base_library.zip ...
1541 INFO: Loading module hook 'hook-encodings.py' from '/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
2802 INFO: Loading module hook 'hook-pickle.py' from '/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
3501 INFO: Loading module hook 'hook-heapq.py' from '/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
4119 INFO: Caching module dependency graph...
4266 INFO: running Analysis Analysis-00.toc
4307 INFO: Analyzing /home/jackpc/Desktop/test/jackproject
Traceback (most recent call last):
  File "/home/jackpc/.local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 1006, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 928, in build
    exec(code, spec_namespace)
  File "jackproject.spec", line 7, in <module>
    a = Analysis(
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 428, in __init__
    self.__postinit__()
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 581, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/depend/analysis.py", line 268, in add_script
    self._top_script_node = super().add_script(pathname)
  File "/home/jackpc/.local/lib/python3.8/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1415, in add_script
    with open(pathname, 'rb') as fp:
IsADirectoryError: [Errno 21] Is a directory: '/home/jackpc/Desktop/test/jackproject'

```

**Comment by bwoodsend** [comment]
Is your build command `pyinstaller /home/jackpc/Desktop/test/jackproject`? You need to give PyInstaller a file - not a directory.

**Comment by Pandaa-P** [comment]
I used a `jackproject.spec` file, the project is a folder with multiple scripts inside. 

`-$ pyinstaller jackproject.spec`

**Comment by bwoodsend** [comment]
And what's being passed as the first argument to `Analysis()` in `jackproject.spec` then?

**Comment by Pandaa-P** [comment]
```
a = Analysis(
    ['jackproject'],
)
```

**Comment by bwoodsend** [comment]
>     ['jackproject'],

That needs to be a script - not a directory.

**Comment by Pandaa-P** [comment]
Why closed it man? 
It work fine with py 3.10 but 3.8 give me the headache.
