### ISSUE TITLE
Pyinstaller not working with Transformers - No such file or directory

### ISSUE THREAD

**Issue by santoshlite** [pyinstaller/pyinstaller#7646]
# Context information
- pyinstaller version: 5.11.0
- Python version: Python 3.10.6
- Platform: MacOS 13.2.1
- I am using pyinstaller to create a python sidecar for tauri (I don't think this matters much)
- Transformers version: 4.29.2

# Description of the bug

So, here is my Python code `test.py`

```py
from transformers import AutoProcessor, AutoModelForCausalLM
import requests
from PIL import Image

print("hello world")

processor = AutoProcessor.from_pretrained("microsoft/git-base-textcaps")
model = AutoModelForCausalLM.from_pretrained("microsoft/git-base-textcaps")
```
and here is my `test-aarch64-apple-darwin.spec` file:
```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata

datas = []
datas += collect_data_files('tensorflow')
datas += collect_data_files('torch')
datas += copy_metadata('tensorflow')
datas += copy_metadata('torch')
datas += copy_metadata('tqdm')
datas += copy_metadata('regex')
datas += copy_metadata('sacremoses')
datas += copy_metadata('requests')
datas += copy_metadata('packaging')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')
datas += copy_metadata('importlib_metadata')


block_cipher = None


a = Analysis(
    ['py/test.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=['pkg_resources.py2_warn', 'googleapiclient', 'apiclient', 'tensorflow', 'pytorch', 'sklearn.utils._cython_blas', 'sklearn.neighbors.typedefs', 'sklearn.neighbors.quad_tree', 'sklearn.tree', 'sklearn.tree._utils'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='test-aarch64-apple-darwin',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

```

Finally, here is the output I get when running pyinstaller:
```
hello world
Traceback (most recent call last):
  File "transformers/utils/import_utils.py", line 1172, in _get_module
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "transformers/models/git/processing_git.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "transformers/processing_utils.py", line 30, in <module>
  File "transformers/utils/import_utils.py", line 1201, in direct_transformers_import
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/8p/nt9tykfs3z5cmqdxhs29x4h80000gn/T/_MEIzLeJOM/transformers/__init__.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
  File "transformers/models/auto/processing_auto.py", line 263, in from_pretrained
  File "transformers/models/auto/processing_auto.py", line 94, in processor_class_from_name
  File "transformers/utils/import_utils.py", line 1162, in __getattr__
  File "transformers/utils/import_utils.py", line 1174, in _get_module
RuntimeError: Failed to import transformers.models.git.processing_git because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: '/var/folders/8p/nt9tykfs3z5cmqdxhs29x4h80000gn/T/_MEIzLeJOM/transformers/__init__.py'
[48212] Failed to execute script 'test' due to unhandled exception!
```

## What I have tried
- Using `copy_metadata` to add the appropriate libraries. This helped me get a file with an `import transformers` statement work, but when I call elements from it, it gives me this new error. 
- Looking at that directory they are talking about `/var/folders/8p/nt9tykfs3z5cmqdxhs29x4h80000gn/T/_MEIzLeJOM/transformers/__init__.py1`. I understand this is temporary so I cannot find it. 

Note that all this usually works when I don't use Transformers. 

I'd appreciate any input, I just got started with Pyinstaller!

**Comment by rokm** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/8p/nt9tykfs3z5cmqdxhs29x4h80000gn/T/_MEIzLeJOM/transformers/__init__.py'

You need to ensure that source files for `transformers` are collected.

Either try adding
``` 
datas += collect_data_files('transformers', include_py_files=True, includes=['**/*.py'])
``` 

to your spec, or create [a hook](https://pyinstaller.org/en/stable/hooks.html) for transformers that sets [module_collection_mode global hook variable](https://pyinstaller.org/en/stable/hooks.html#hook-global-variables) to either 'py' or 'pyz+py'.

**Comment by rokm** [comment]
And if you're using `torch˙ on macOS, you'll likely run into issues with duplicated dylibs: see https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/375.
