### ISSUE TITLE
test_ipython fails when running in a virutual env

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#768]
**Original date**: 2013/09/13

When VIRTUAL_ENV is set, ipython wants to add the virtual env's directory to sys.path. This fails since your fakes implementation of site.py does not implement the required functions.
```
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File ".../test_ipython/out00-PYZ.pyz/IPython.terminal.embed", line 300, in embed
  File ".../test_ipython/out00-PYZ.pyz/IPython.config.configurable", line 349, in instance
  File ".../test_ipython/out00-PYZ.pyz/IPython.terminal.embed", line 97, in __init__
  File ".../test_ipython/out00-PYZ.pyz/IPython.terminal.interactiveshell", line 320, in __init__
  File ".../test_ipython/out00-PYZ.pyz/IPython.core.interactiveshell", line 438, in __init__
  File ".../test_ipython/out00-PYZ.pyz/IPython.core.interactiveshell", line 724, in init_virtualenv
AttributeError: 'module' object has no attribute 'addsitedir'
```

**Comment by matysek** [comment]
This should be fixed:
* `python3` branch no longer uses fake `site` module
*  test_ipython works.
