### ISSUE TITLE
ImportError: The _imaging C module is not installed

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#770]
**Original date**: 2013/09/13
**Original reporter**: *antonio AND idxtra DOT  COOM *

Hello,

when I try to run Django on Ubuntu and I get next error:

Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "/home/antonio/Documents/pyinstaller/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/antonio/Documents/pyinstaller/my/build/my/out00-PYZ.pyz/PIL.PalmImagePlugin", line 92, in <module>
  File "/home/antonio/Documents/pyinstaller/my/build/my/out00-PYZ.pyz/PIL.PalmImagePlugin", line 82, in build_prototype_image
  File "/home/antonio/Documents/pyinstaller/my/build/my/out00-PYZ.pyz/PIL.Image", line 1776, in new
  File "/home/antonio/Documents/pyinstaller/my/build/my/out00-PYZ.pyz/PIL.Image", line 39, in __getattr__
ImportError: The _imaging C module is not installed

I have tried to find a solution but there is nothing for this.

**Comment by matysek** [comment]
This bug report is too old.
