### ISSUE TITLE
Python 3.11.4 and pyinstaller 5.12.0 --> pywin32error

### ISSUE THREAD

**Issue by pyinstallerbaggins** [pyinstaller/pyinstaller#7725]
<!--
Welcome to the PyInstaller issue tracker! Before creating an issue, please heed the following:

Running pyinstaller on 3.7.4 works fine but when running python 3.11.4 and pyinstaller 5.12.0 with the below command line flag:

**pyinstaller --clean --distpath “N:\Attribution\my app for User" build_QA.spec**

I get this error output:

  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\_pytest\_code\__init__.py", line 2, in <module>
    from .code import Code  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\_pytest\_code\code.py", line 1004, in <module>
    _PLUGGY_DIR = py.path.local(pluggy.__file__.rstrip("oc"))
                  ^^^^^^^^^^^^^
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\py\_vendored_packages\apipkg.py", line 148, in __makeattr
    result = importobj(modpath, attrname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\py\_vendored_packages\apipkg.py", line 69, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1136, in _find_and_load_unlocked
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\py\_vendored_packages\apipkg.py", line 146, in __makeattr
    raise AttributeError(name)
AttributeError: __spec__

**Comment by pyinstallerbaggins** [comment]
I am running:

Python 3.11.4
pyinstaller 5.12.0
pywin 306
pywin32-ctypes==0.2.1

command line flag:
pyinstaller --clean --distpath “N:\Attribution\my user app" build_QA.spec

**Error:**
```
Traceback (most recent call last):
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 226, in EndUpdateResource
    _resource._EndUpdateResource(handle, discard)
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\win32ctypes\core\ctypes\_util.py", line 61, in check_false
    raise make_error(function, function_name)
OSError: [WinError 110] The system cannot open the device or file specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\PerformanceAttributionApp\paa\venv\scripts\pyinstaller.exe\__main__.py", line 7, in <module>
    import time

  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\building\build_main.py", line 1030, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\building\build_main.py", line 952, in build
    exec(code, spec_namespace)
  File "build_QA.spec", line 29, in <module>
    exe = EXE(pyz,
          ^^^^^^^^
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\building\api.py", line 584, in __init__
    self.__postinit__()
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\building\api.py", line 680, in assemble
    winresource.RemoveAllResources(build_name)
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 245, in RemoveAllResources
    win32api.EndUpdateResource(hsrc, False)
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 225, in EndUpdateResource
    with _pywin32error():
  File "C:\Users\ckeo\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\PerformanceAttributionApp\paa\venv\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (110, 'EndUpdateResourceW', 'The system cannot open the device or file specified.')
```

**Comment by rokm** [comment]
This looks like executable disappearing while being processed - is there an antivirus program interfering with the build process?
