### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for The 'tqdm>=4.27' distribution was not found and is required by this application.

### ISSUE THREAD

**Issue by 17Reset** [pyinstaller/pyinstaller#7730]
When I package a project that contains transformers, the following error will occur:
E:\X\xAccel\J\build>E:\X\xAccel\J\AriesX\release\xAccelAriesX\xAccelAriesX.exe
Traceback (most recent call last):
  File "importlib\metadata\__init__.py", line 563, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transformers\utils\versions.py", line 108, in require_version
  File "importlib\metadata\__init__.py", line 1008, in version
  File "importlib\metadata\__init__.py", line 981, in distribution
  File "importlib\metadata\__init__.py", line 565, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for tqdm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ariesx_main.py", line 14, in <module>
、、、
    import transformers
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "transformers\__init__.py", line 26, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "transformers\dependency_versions_check.py", line 41, in <module>
  File "transformers\utils\versions.py", line 123, in require_version_core
  File "transformers\utils\versions.py", line 110, in require_version
importlib.metadata.PackageNotFoundError: No package metadata was found for The 'tqdm>=4.27' distribution was not found and is required by this application.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
[22688] Failed to execute script 'ariesx_main' due to unhandled exception!

**Comment by rokm** [comment]
You need to collect metadata for `tqdm` (and all other packages for which `transformers` is trying to query metadata). See #5878.
