### ISSUE TITLE
pyinstaller issue when using pydrive2

### ISSUE THREAD

**Issue by senseirenard** [pyinstaller/pyinstaller#7739]
Hello, I am struggling with pydrive, I am making a simple program for uploading and sorting multiple files on a google drive, my code is working when I execute it on Spyder but after using pyinstaller to make an executable i get errors that I don't understand, if you could help me i would be very grateful ! Here is the error I get :

Traceback (most recent call last):
File "app.py", line 123, in
File "pydrive\apiattr.py", line 162, in GetList
File "pydrive\apiattr.py", line 146, in next
File "pydrive\auth.py", line 57, in _decorated
File "pydrive\auth.py", line 125, in _decorated
File "pydrive\auth.py", line 496, in Auth
File "pydrive\auth.py", line 523, in Authorize
File "googleapiclient_helpers.py", line 130, in positional_wrapper
File "googleapiclient\discovery.py", line 287, in build
File "googleapiclient\discovery.py", line 404, in _retrieve_discovery_doc
googleapiclient.errors.UnknownApiNameOrVersion: name: drive version: v2
[17132] Failed to execute script 'app' due to unhandled exception!

and the line 123 of my script is : file_list = drive.ListFile({'q': "'root' in parents and trashed=false"}).GetList()

What I don't understand is why it doesn't happen when executing from Spyder and this line : "googleapiclient.errors.UnknownApiNameOrVersion: name: drive version: v2" doesn't make sense to me

**Comment by bwoodsend** [comment]
The error is originating from a rather misleading data files helper ([code](https://github.com/googleapis/google-api-python-client/blob/642c37cb74591d3ac0ff6bcd8e9876505fbc16b2/googleapiclient/discovery.py#L400-L406)).

Does adding `--collect-datas=googleapiclient.discovery_cache.documents` to your PyInstaller command make any difference?

**Comment by senseirenard** [comment]
It is now working, thank you very much !
