### ISSUE TITLE
Issue while converting Python file having a pickle file to exe

### ISSUE THREAD

**Issue by Nee-DS** [pyinstaller/pyinstaller#7741]
Traceback (most recent call last):
  File "Predict_BERT.py", line 33, in <module>
  File "joblib\numpy_pickle.py", line 648, in load
  File "joblib\numpy_pickle.py", line 577, in _unpickle
  File "pickle.py", line 1212, in load
  File "pickle.py", line 1537, in load_stack_global
  File "pickle.py", line 1579, in find_class
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "bertopic\backend\_sentencetransformers.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sentence_transformers\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sentence_transformers\datasets\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sentence_transformers\datasets\ParallelSentencesDataset.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sentence_transformers\SentenceTransformer.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "transformers\__init__.py", line 26, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "transformers\dependency_versions_check.py", line 41, in <module>
  File "transformers\utils\versions.py", line 123, in require_version_core
  File "transformers\utils\versions.py", line 110, in require_version
importlib.metadata.PackageNotFoundError: The 'tqdm>=4.27' distribution was not found and is required by this application.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
[32160] Failed to execute script 'Predict_BERT' due to unhandled exception!

**Comment by Nee-DS** [comment]
I am getting issues with python file having a pickle file to convert to exe. Above is the error I am getting. I did try the pip install transformers as given above. but got the same issue. Please guide!

**Comment by rokm** [comment]
You need to collect metadata for `tqdm` (and all other packages for which `transformers` is trying to query metadata). See https://github.com/pyinstaller/pyinstaller/issues/5878.
