### ISSUE TITLE
Pydantic V2 no longer containers a compile flag which results in an error during build

### ISSUE THREAD

**Issue by sudilav** [pyinstaller/pyinstaller#7754]
## Description of the issue
With Pydantic V2 (released 30th June 2023), the compiled attribute has been removed:
https://docs.pydantic.dev/2.0/migration/#removed-in-pydantic-v2

However it is used in the hook-pydantic.py and this therefore results in an attribute error that compiled is not an attribute of pydantic, causing our current pipelines to fail.

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.12.0
* Version of Python: 3.9.2
* Platform: Linux
* How you installed Python: pyenv
* Did you also try this on another platform? Yes. Does it work there? No. - This is universal and specific to pydantic.

```
import pydantic
```

### Stacktrace / full error message

```
Traceback (most recent call last):
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/utils/hooks/__init__.py", line 283, in get_module_attribute
     return _get_module_attribute(module_name, attr_name)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/isolated/_parent.py", line 403, in wrapped
     return call(function, *args, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/isolated/_parent.py", line 372, in call
     return isolated.call(function, *args, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/isolated/_parent.py", line 302, in call
     raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
 RuntimeError: Child process call to _get_module_attribute() failed with:
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/isolated/_child.py", line 63, in run_next_command
     output = function(*args, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/utils/hooks/__init__.py", line 279, in _get_module_attribute
     return getattr(module, attr_name)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pydantic/__init__.py", line 206, in __getattr__
     return _getattr_migration(attr_name)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pydantic/_migration.py", line 285, in wrapper
     raise PydanticImportError(f'`{import_path}` has been removed in V2.')
 pydantic.errors.PydanticImportError: `pydantic:compiled` has been removed in V2.
 For further information visit https://errors.pydantic.dev/2.0.1/u/import-error
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
   File "/root/.pyenv/versions/3.9.2/bin/pyinstaller", line 8, in <module>
     sys.exit(_console_script_run())
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
     run()
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/__main__.py", line 180, in run
     run_build(pyi_config, spec_file, **vars(args))
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/__main__.py", line 61, in run_build
     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 1030, in main
     build(specfile, distpath, workpath, clean_build)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 952, in build
     exec(code, spec_namespace)
   File "main.spec", line 7, in <module>
     a = Analysis(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 437, in __init__
     self.__postinit__()
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
     self.assemble()
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 601, in assemble
     self.graph.add_hiddenimports(self.hiddenimports)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 722, in add_hiddenimports
     nodes = self.import_hook(modnm)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1444, in import_hook
     submodule = self._safe_import_module(head, mname, submodule)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 479, in _safe_import_module
     return super()._safe_import_module(module_basename, module_name, parent_package)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1992, in _safe_import_module
     self._process_imports(n)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2811, in _process_imports
     target_modules = self._safe_import_hook(*import_info, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 432, in _safe_import_hook
     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2262, in _safe_import_hook
     target_modules = self.import_hook(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1444, in import_hook
     submodule = self._safe_import_module(head, mname, submodule)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 479, in _safe_import_module
     return super()._safe_import_module(module_basename, module_name, parent_package)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1992, in _safe_import_module
     self._process_imports(n)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2811, in _process_imports
     target_modules = self._safe_import_hook(*import_info, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 432, in _safe_import_hook
     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2262, in _safe_import_hook
     target_modules = self.import_hook(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1444, in import_hook
     submodule = self._safe_import_module(head, mname, submodule)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 479, in _safe_import_module
     return super()._safe_import_module(module_basename, module_name, parent_package)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1992, in _safe_import_module
     self._process_imports(n)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2811, in _process_imports
     target_modules = self._safe_import_hook(*import_info, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 432, in _safe_import_hook
     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2262, in _safe_import_hook
     target_modules = self.import_hook(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1431, in import_hook
     target_package, target_module_partname = self._find_head_package(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1610, in _find_head_package
     target_package = self._safe_import_module(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 479, in _safe_import_module
     return super()._safe_import_module(module_basename, module_name, parent_package)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1992, in _safe_import_module
     self._process_imports(n)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2811, in _process_imports
     target_modules = self._safe_import_hook(*import_info, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 432, in _safe_import_hook
     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2262, in _safe_import_hook
     target_modules = self.import_hook(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1444, in import_hook
     submodule = self._safe_import_module(head, mname, submodule)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 479, in _safe_import_module
     return super()._safe_import_module(module_basename, module_name, parent_package)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1992, in _safe_import_module
     self._process_imports(n)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2811, in _process_imports
     target_modules = self._safe_import_hook(*import_info, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 432, in _safe_import_hook
     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2262, in _safe_import_hook
     target_modules = self.import_hook(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1431, in import_hook
     target_package, target_module_partname = self._find_head_package(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1610, in _find_head_package
     target_package = self._safe_import_module(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 479, in _safe_import_module
     return super()._safe_import_module(module_basename, module_name, parent_package)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1992, in _safe_import_module
     self._process_imports(n)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2811, in _process_imports
     target_modules = self._safe_import_hook(*import_info, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 432, in _safe_import_hook
     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2262, in _safe_import_hook
     target_modules = self.import_hook(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1431, in import_hook
     target_package, target_module_partname = self._find_head_package(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1610, in _find_head_package
     target_package = self._safe_import_module(
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 479, in _safe_import_module
     return super()._safe_import_module(module_basename, module_name, parent_package)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1992, in _safe_import_module
     self._process_imports(n)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2811, in _process_imports
     target_modules = self._safe_import_hook(*import_info, **kwargs)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 368, in _safe_import_hook
     excluded_imports = self._find_all_excluded_imports(source_module.identifier)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 356, in _find_all_excluded_imports
     excluded_imports.update(module_hook.excludedimports)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/imphook.py", line 316, in __getattr__
     self._load_hook_module()
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/depend/imphook.py", line 383, in _load_hook_module
     self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/compat.py", line 612, in importlib_load_source
     return mod_loader.load_module()
   File "<frozen importlib._bootstrap_external>", line 469, in _check_name_wrapper
   File "<frozen importlib._bootstrap_external>", line 969, in load_module
   File "<frozen importlib._bootstrap_external>", line 794, in load_module
   File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
   File "<frozen importlib._bootstrap>", line 711, in _load
   File "<frozen importlib._bootstrap>", line [680](https://git.ccfe.ac.uk/POGDeveloper/GraphicalRTCC/-/jobs/1540544#L680), in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line [790](https://git.ccfe.ac.uk/POGDeveloper/GraphicalRTCC/-/jobs/1540544#L790), in exec_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py", line 22, in <module>
     is_compiled = get_module_attribute('pydantic', 'compiled') in {'True', True}
   File "/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/PyInstaller/utils/hooks/__init__.py", line 285, in get_module_attribute
     raise AttributeError(f"Failed to retrieve attribute {attr_name} from module {module_name}") from e
 AttributeError: Failed to retrieve attribute compiled from module pydantic
```

**Comment by sudilav** [comment]
Apologies, closing, reopened here:
https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/612
