### ISSUE TITLE
How to manual install the latest development version?

### ISSUE THREAD

**Issue by yeying075** [pyinstaller/pyinstaller#7759]
How to manual install the latest development version?
I download a package from https://github.com/pyinstaller/pyinstaller/archive/develop.zip, then put it in C:\Users\fzhxx\anaconda3\envs\Python36\Lib\site-packages\pyinstaller-develop. when I type "python setup.py install" on the command line,reported 
"running install
running bdist_egg
Error: Aborting implicit building of eggs. To install from source, use `pip install .` instead of `python setup.py install`."

**Comment by rokm** [comment]
The error message tells you exactly what to do: "To install from source, use `pip install .` instead of `python setup.py install`."

**Comment by rokm** [comment]
You can also avoid dealing with archive, and instead use: `pip install git+https://github.com/pyinstaller/pyinstaller.git@develop`.

**Comment by bwoodsend** [comment]
And don't put it directly into `site-packages` – pip will copy the right files into `site-packages`. Also PyInstaller dropped support for Python 3.6 a year and a bit ago so what you're trying to do isn't going to work anyway.

**Comment by yeying075** [comment]
@rokm @bwoodsend Thank you for you answers. Can't I download it using a zip pack? if I type "pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip", 
probably due to Chinese Internet issues, it will report 
"WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pyinstaller/pyinstaller/archive/develop.zip
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pyinstaller/pyinstaller/archive/develop.zip
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pyinstaller/pyinstaller/archive/develop.zip
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pyinstaller/pyinstaller/archive/develop.zip
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pyinstaller/pyinstaller/archive/develop.zip
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /pyinstaller/pyinstaller/archive/develop.zip (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))"

**Comment by bwoodsend** [comment]
Are you still using Python 3.6? If you are, it might be that your version of pip is old and therefore contains an old version of certifi which contains an out of data root certificate bundle.

Chinese firewall issues sounds probable to me though.

**Comment by yeying075** [comment]
@bwoodsend I changed it into Python 3.11. the version of pip is 23.1.2.

**Comment by yeying075** [comment]
It's not very serious if I can't download it. My main purpose is packing my project. When I type "pyinstaller manage.spec" it reported "win32ctypes.pywin32.pywintypes.error: (2, 'LoadLibraryEx', '系统找不到指定的文件。')"
Here is the infomation:

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.6.2```
* Version of Python: 3.11
* Platform: Windows
* How you installed Python: official website
* Did you also try this on another platform? Does it work there? 
I didn't try this on another platform.


* try the latest development version, using the following command: 

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
I haven't been able to install this.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ y] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Stacktrace / full error message


```
Traceback (most recent call last):
  File "C:\Users\fzhxx\anaconda3\Scripts\pyinstaller-script.py", line 10, in <module>
    sys.exit(run())
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 885, in build
    exec(code, spec_namespace)
  File "manage.spec", line 6, in <module>
    a = Analysis(['manage.py'],
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 410, in __init__
    self.__postinit__()
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 689, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\isolated\_parent.py", line 337, in call
    return isolated.call(function, *args, **kwargs)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\isolated\_parent.py", line 275, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to find_binary_dependencies() failed with:
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\win32ctypes\core\cffi\_dll.py", line 23, in _LoadLibraryEx
    result = check_null(
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\win32ctypes\core\cffi\_util.py", line 81, in __call__
    self._raise_error(function_name)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\win32ctypes\core\cffi\_util.py", line 92, in _raise_error
    raise exception
OSError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 191, in find_binary_dependencies
    return bindepend.Dependencies(binaries, redirects=binding_redirects, xtrapath=extra_libdirs)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.py", line 287, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.py", line 461, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.py", line 415, in getAssemblies
    res = winmanifest.GetManifestResources(pth)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 979, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 155, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\win32ctypes\pywin32\win32api.py", line 42, in LoadLibraryEx
    with _pywin32error():
  File "C:\Users\fzhxx\anaconda3\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\fzhxx\anaconda3\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (2, 'LoadLibraryEx', '系统找不到指定的文件。')
```

**Comment by bwoodsend** [comment]
Can you rebuild with `--debug=all` and attach the whole build log.
