### ISSUE TITLE
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py:167: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.   __import__(package)

### ISSUE THREAD

**Issue by qhp940304** [pyinstaller/pyinstaller#7771]
```
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py:167: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\isolated\_parent.py", line 293, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "C:\Users\Administrator\Desktop\add\nt.spec", line 11, in <module>
    a = Analysis(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 429, in __init__
    self.__postinit__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 745, in assemble
    isolated.call(find_binary_dependencies, self.binaries, self.binding_redirects, collected_packages)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\isolated\_parent.py", line 247, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument
```

**Comment by rokm** [comment]
That `UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.` is unrelated - it just happens to be the last message printed at the default debug level before we reach binary analysis part that crashes.

Can you modify your installed PyInstaller copy, and add a `print(package)` before the `__import__(package)` line here:
https://github.com/pyinstaller/pyinstaller/blob/3a3aa2f7e6a36eea84f65472bb157bef7dc4a631/PyInstaller/building/build_main.py#L170

This should give you the list of packages that are imported during the analysis, and the last one is the one that crashes the sub-process. Then please copy and paste the whole printed list here.
