### ISSUE TITLE
 pyinstaller hook not working for jsonschema

### ISSUE THREAD

**Issue by Reaster0** [pyinstaller/pyinstaller#7779]
## Description of the issue

jsonschema library aren't bundled in the final package, it build successfully but when i try to run the executable after i get this issue: 
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/reaster/Work/Freebox/execution-daemon/dist/main/jsonschema_specifications/schemas'
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.13.0
* Version of Python: 3.9.16
* Platform: Garuda/Arch linus
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
i've tried on others linux computer on other distros, same issue

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import jsonschema

payload = {
	"notinput": "test"
}

stdin_execSchema = {
	"type": "object",
	"properties": {
		"input": {
			"type": "string"
		}
	},
	"required": ["input"]
}
try:
	jsonschema.validate(payload, stdin_execSchema)
except Exception as e:
	print("payload invalid")
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import jsonschema
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "jsonschema/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "jsonschema/validators.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "jsonschema_specifications/__init__.py", line 11, in <module>
  File "referencing/_core.py", line 297, in __rmatmul__
  File "jsonschema_specifications/_core.py", line 27, in _schemas
  File "pathlib.py", line 1160, in iterdir
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIkOtOX1/jsonschema_specifications/schemas'
[101244] Failed to execute script 'main' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
Fixed already in https://github.com/pyinstaller/pyinstaller-hooks-contrib/commit/0f40dc6e74086e5472aee75070b9077b4c17ab18 but not released. I've released it now.
```
pip install -U pyinstaller-hooks-contrib
```
