### ISSUE TITLE
run exec failed / pandoc / pandoc-types.js

### ISSUE THREAD

**Issue by bfrax** [pyinstaller/pyinstaller#7812]
## Description of the issue

Run failed atfer building a script with python module pandoc
run exec failed with option --onefile but run without this option and after adding folder pandoc/pandoc-types.js in dist folder.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.3```
* Version of Python:3.9
* Platform:GNU Linux debian SMP Debian 5.10.179-1
* Did you also try this on another platform? Does it work there?
do not work on linux debian

* try the latest development version, using the following command:

```shell
pyinstaller exec4.py --clean -F --onefile --hidden-import="PIL._tkinter_finder"
```

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [OK ] start with clean installation
  * [OK ] use the latest development version
  * [OK ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
Traceback (most recent call last):
  File "exec4.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "pandoc/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "pandoc/utils.py", line 13, in <module>
  File "pkg_resources/__init__.py", line 1223, in resource_string
  File "pkg_resources/__init__.py", line 1498, in get_resource_string
  File "pkg_resources/__init__.py", line 1670, in _get
  File "PyInstaller/loader/pyimod02_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIIjSxk9/pandoc/pandoc-types.js'
[22205] Failed to execute script 'exec4' due to unhandled exception!
```

### Question

Please, could you tell me the command line to add pandoc-style with --onefile option!

**Comment by rokm** [comment]
You need to collect the data files from `pandoc`; add `--collect-data pandoc` to your PyInstaller command.
