### ISSUE TITLE
When trying to run selenium, the error No such file or directory

### ISSUE THREAD

**Issue by iyamk** [pyinstaller/pyinstaller#7817]
My program: https://github.com/iyamk/app-selenium
After compilation, I run the program and it works, but when I press Start I see an error:
```
Exception in thread Thread-2 (runner):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "main.py", line 28, in runner
  File "selenium_stealth/__init__.py", line 45, in stealth
  File "selenium_stealth/utils.py", line 8, in with_utils
  File "pathlib.py", line 1058, in read_text
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIox7xlH/selenium_stealth/js/utils.js'
```
There really is no selenium_stealth folder in the application's temporary folder, I don't understand why he doesn't put it there

**Comment by bwoodsend** [comment]
`--collect-data=selenium_stealth`
