### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'apname.exe.notanexecutable'

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#7825]
Since @bwoodsend asked: I am seeing #6854. It also reminded me of Nuitka/Nuitka#2080 which seems to have been caused by CyberArk Endpoint Privilege Manager (and related software), although I still struggle to export relevant logs to pin-point that. If it *is* similar to Nuitka/Nuitka#2080, the problem is simply that the scanner holds a reference to the file, so `pyinstaller` might retry renaming/moving/deleting that file (whatever it is that it is doing).

**Comment by rokm** [comment]
Yes, the problem is "simply" that we are racing for file access with the scanner. The complex part is that we are likely doing so on any processing step where we need to (re)open the file, so all those would need to be (individually) wrapped in some sort of re-try block.

Although since last time we were discussing this, the assembly pipeline underwent couple of cleanups and refactoring, so it might be easier to implement that now: all steps [here](https://github.com/pyinstaller/pyinstaller/blob/3e7d4ccad601a85823ceb6d996973ccf0b93cc0b/PyInstaller/building/api.py#L706-L721) (conveniently encapsulated in functions), the [PKG appending](https://github.com/pyinstaller/pyinstaller/blob/3e7d4ccad601a85823ceb6d996973ccf0b93cc0b/PyInstaller/building/api.py#L786-L790), the [post-processing here](https://github.com/pyinstaller/pyinstaller/blob/3e7d4ccad601a85823ceb6d996973ccf0b93cc0b/PyInstaller/building/api.py#L798-L799), and [here](https://github.com/pyinstaller/pyinstaller/blob/3e7d4ccad601a85823ceb6d996973ccf0b93cc0b/PyInstaller/building/api.py#L826-L830).

**Comment by bwoodsend** [comment]
I guess we could shovel the *open with retry* stuff into a helper then having several steps that need this wouldn't be too bad. 
```python
def antivirus_proof_open(open_or_pefile_PE, *args, **kwargs):
    while True:
        try:
            return open_or_pefile_PE(path, *args, **kwargs)
        except PermissionError:
            logger.warning("Some antivirus is holding a file PyInstaller wants to modify. Waiting for it to finish")
            time.sleep(0.1)
```
We could then add an additional `except FileNotFoundError` to handle the case where an overly zealous antivirus sends the file we just wrote straight into quarantine.

**Comment by rokm** [comment]
Hmm, I was thinking of a wrapper like that, but applied at the higher level - i.e., wrapping whole processing steps/functions in them (e.g., `_retry(winresource.remove_all_resources, build_name))`, `_retry(icon.CopyIcons, build_name, self.icon))`, etc). 

That assumes that `PermissionError` is raised only when the function tries to open executable (which I suppose is reasonable enough) and that the function does not swallow it or re-raise it with different type (which I suppose is not so reasonable to expect).

This way, all retry logic would be concentrated in the high-level code (i.e., in the `EXE.assemble`), instead of being scattered across all helpers.

**Comment by bersbersbers** [comment]
Here's a potentially related issue:

```
Traceback (most recent call last):
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 226, in EndUpdateResource        
    _resource._EndUpdateResource(handle, discard)
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\win32ctypes\core\ctypes\_util.py", line 61, in check_false
    raise make_error(function, function_name)
OSError: [WinError 5] Access is denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\building\build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "project.spec", line 57, in <module>
    exe = EXE(
          ^^^^
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\building\api.py", line 590, in __init__
    self.__postinit__()
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\building\api.py", line 690, in assemble
    icon.CopyIcons(build_name, self.icon)
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\utils\win32\icon.py", line 209, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\PyInstaller\utils\win32\icon.py", line 158, in CopyIcons_FromIco
    win32api.EndUpdateResource(hdst, 0)
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 225, in EndUpdateResource
    with _pywin32error():
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (5, 'EndUpdateResourceW', 'Access is denied.')
```

**Comment by rokm** [comment]
@bersbersbers If you can reproduce this issue (more or less) consistently, can I ask you to take #7840, add the `win32ctypes.pywin32.pywintypes.error` handling to `_retry_operation` introduced there, and wrap the `icon.CopyIcons(build_name, self.icon)` [call](https://github.com/pyinstaller/pyinstaller/blob/faa37215e86ad0099b20f8440d2efeb27e3c21f1/PyInstaller/building/api.py#L732) in the `_retry_operation`? Does that fix the problem in your case?

**Comment by bersbersbers** [comment]
> If you can reproduce this issue (more or less) consistently

Unfortunately, I cannot :( I saw this for the first time today. Will update in case it does come back.

**Comment by rokm** [comment]
> > If you can reproduce this issue (more or less) consistently
> 
> Unfortunately, I cannot :( I saw this for the first time today. Will update in case it does come back.

OK, thanks. At least we got the exception type and error code out of it.

**Comment by bersbersbers** [comment]
By the way, I tried https://github.com/pyinstaller/pyinstaller/commit/275bfe69f8d101361f5d0d1ce466e53aac711ebe which contains https://github.com/pyinstaller/pyinstaller/pull/7871, and it works flawlessly so far. Briefly going back to the original 5.13.0 gave me the older errors in `set_exe_build_timestamp` and several other places. So this seems to be needed and working.

Do I understand correctly that this will only be released with 6.x?

**Comment by rokm** [comment]
> Do I understand correctly that this will only be released with 6.x?

Yes.
