### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by panpengfei21** [pyinstaller/pyinstaller#7832]
## Description of the issue
```
emo/dist/findOEM_APP ; exit;
Traceback (most recent call last):
  File "tecDoc/app/findOEM_APP.py", line 11, in <module>
ModuleNotFoundError: No module named 'login_APP'
[34975] Failed to execute script 'findOEM_APP' due to unhandled exception!
```
### Context information (for bug reports)

* Output of `pyinstaller --version`: 
```
python -m PyInstaller --version                                         
5.13.0
```
* Version of Python: 
```
python --version               
Python 3.11.4
```
* Platform: OS X
* How you installed Python: python.org/downloads

My Project directory
<img width="240" alt="image" src="https://github.com/pyinstaller/pyinstaller/assets/7960250/1e89bf92-1361-4eaf-9e59-e57e982959e8">

findOEM_APP_Test.py
```
import requests
import login_APP

if __name__ == "__main__":
    print("GOGO")
```

I use Pyinstall like below
```
python -m PyInstaller  -F ./tecDoc/app/findOEM_APP_Test.py 
```

But I encountered a error
```
Traceback (most recent call last):
  File "tecDoc/app/findOEM_APP.py", line 11, in <module>
ModuleNotFoundError: No module named 'login_APP'
[34975] Failed to execute script 'findOEM_APP' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

But I remove 'import login_APP',
It working OK
```
GOGO

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

How I fix it. TKS

**Comment by panpengfei21** [comment]
-p DIR, --paths DIR
A path to search for imports (like using PYTHONPATH). Multiple paths are allowed, separated by ':', or use this option multiple times. Equivalent to supplying the pathex argument in the spec file


it is working, when I use 'paths' 
```
python -m PyInstaller --paths=./tecDoc:./tecDoc/app -F ./tecDoc/app/findOEM_APP_Test.py
```
