### ISSUE TITLE
python3 success, pyinstaller fail

### ISSUE THREAD

**Issue by novvoo** [pyinstaller/pyinstaller#7866]
```
MySQL [(none)]> SELECT VERSION();
+------------+
| VERSION()  |
+------------+
| 5.7.30-log |
+------------+
1 row in set (0.00 sec)

```

```
<!--

Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 145, in __init__
  File "sqlalchemy/engine/base.py", line 3288, in raw_connection
  File "sqlalchemy/pool/base.py", line 452, in connect
  File "sqlalchemy/pool/base.py", line 1267, in _checkout
  File "sqlalchemy/pool/base.py", line 716, in checkout
  File "sqlalchemy/pool/impl.py", line 169, in _do_get
  File "sqlalchemy/util/langhelpers.py", line 147, in __exit__
  File "sqlalchemy/pool/impl.py", line 167, in _do_get
  File "sqlalchemy/pool/base.py", line 393, in _create_connection
  File "sqlalchemy/pool/base.py", line 678, in __init__
  File "sqlalchemy/pool/base.py", line 902, in __connect
  File "sqlalchemy/util/langhelpers.py", line 147, in __exit__
  File "sqlalchemy/pool/base.py", line 898, in __connect
  File "sqlalchemy/engine/create.py", line 637, in connect
  File "sqlalchemy/engine/default.py", line 615, in connect
  File "mysql/connector/pooling.py", line 294, in connect
  File "mysql/connector/connection.py", line 169, in __init__
  File "mysql/connector/abstracts.py", line 1217, in connect
  File "mysql/connector/connection.py", line 581, in _open_connection
  File "mysql/connector/connection.py", line 301, in _do_auth
  File "mysql/connector/protocol.py", line 159, in make_auth
  File "mysql/connector/protocol.py", line 94, in _auth_response
  File "mysql/connector/authentication.py", line 77, in get_auth_plugin
mysql.connector.errors.NotSupportedError: Authentication plugin 'mysql_native_password' is not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "flask/app.py", line 2213, in __call__
  File "flask/app.py", line 2193, in wsgi_app
  File "flask_cors/extension.py", line 176, in wrapped_function
  File "flask/app.py", line 2190, in wsgi_app
  File "flask/app.py", line 1486, in full_dispatch_request
  File "flask_cors/extension.py", line 176, in wrapped_function
  File "flask/app.py", line 1484, in full_dispatch_request
  File "flask/app.py", line 1469, in dispatch_request
  File "app.py", line 187, in get_region_post
  File "sqlalchemy/orm/query.py", line 2743, in first
  File "sqlalchemy/orm/query.py", line 2842, in _iter
  File "sqlalchemy/orm/session.py", line 2262, in execute
  File "sqlalchemy/orm/session.py", line 2134, in _execute_internal
  File "sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
  File "<string>", line 2, in _connection_for_bind
  File "sqlalchemy/orm/state_changes.py", line 139, in _go
  File "sqlalchemy/orm/session.py", line 1126, in _connection_for_bind
  File "sqlalchemy/engine/base.py", line 3264, in connect
  File "sqlalchemy/engine/base.py", line 147, in __init__
  File "sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
  File "sqlalchemy/engine/base.py", line 145, in __init__
  File "sqlalchemy/engine/base.py", line 3288, in raw_connection
  File "sqlalchemy/pool/base.py", line 452, in connect
  File "sqlalchemy/pool/base.py", line 1267, in _checkout
  File "sqlalchemy/pool/base.py", line 716, in checkout
  File "sqlalchemy/pool/impl.py", line 169, in _do_get
  File "sqlalchemy/util/langhelpers.py", line 147, in __exit__
  File "sqlalchemy/pool/impl.py", line 167, in _do_get
  File "sqlalchemy/pool/base.py", line 393, in _create_connection
  File "sqlalchemy/pool/base.py", line 678, in __init__
  File "sqlalchemy/pool/base.py", line 902, in __connect
  File "sqlalchemy/util/langhelpers.py", line 147, in __exit__
  File "sqlalchemy/pool/base.py", line 898, in __connect
  File "sqlalchemy/engine/create.py", line 637, in connect
  File "sqlalchemy/engine/default.py", line 615, in connect
  File "mysql/connector/pooling.py", line 294, in connect
  File "mysql/connector/connection.py", line 169, in __init__
  File "mysql/connector/abstracts.py", line 1217, in connect
  File "mysql/connector/connection.py", line 581, in _open_connection
  File "mysql/connector/connection.py", line 301, in _do_auth
  File "mysql/connector/protocol.py", line 159, in make_auth
  File "mysql/connector/protocol.py", line 94, in _auth_response
  File "mysql/connector/authentication.py", line 77, in get_auth_plugin
sqlalchemy.exc.NotSupportedError: (mysql.connector.errors.NotSupportedError) Authentication plugin 'mysql_native_password' is not supported
(Background on this error at: https://sqlalche.me/e/20/tw8g)
```

docker build info
```
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 Werkzeug-2.3.7 altgraph-0.17.3 blinker-1.6.2 certifi-2023.7.22 charset-normalizer-3.2.0 click-8.1.7 flask-2.3.2 flask_cors-4.0.0 flask_sqlalchemy-3.0.5 greenlet-2.0.2 idna-3.4 itsdangerous-2.1.2 mysql-connector-python-8.1.0 protobuf-4.21.12 pyinstaller-5.13.0 pyinstaller-hooks-contrib-2023.7 python-gitlab-3.15.0 requests-2.31.0 requests-toolbelt-1.0.0 sqlalchemy-2.0.20 typing-extensions-4.7.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ pyinstaller -w --upx-dir=/usr/bin --clean --onefile app.py
224 INFO: PyInstaller: 5.13.0
224 INFO: Python: 3.10.5
226 INFO: Platform: Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with
227 INFO: wrote /apps/app.spec
231 INFO: UPX is available but is disabled on non-Windows due to known compatibility problems.
231 INFO: Removing temporary files and cleaning cache in /root/.cache/pyinstaller
232 INFO: Extending PYTHONPATH with paths
['/apps']
482 INFO: checking Analysis
482 INFO: Building Analysis because Analysis-00.toc is non existent
483 INFO: Initializing module dependency graph...
485 INFO: Caching module graph hooks...
502 INFO: Analyzing base_library.zip ...
1680 INFO: Loading module hook 'hook-heapq.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
1838 INFO: Loading module hook 'hook-encodings.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
4186 INFO: Loading module hook 'hook-pickle.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
7110 INFO: Caching module dependency graph...
7306 INFO: running Analysis Analysis-00.toc
7313 INFO: Analyzing /apps/app.py
8749 INFO: Loading module hook 'hook-platform.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
9017 INFO: Loading module hook 'hook-sysconfig.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
9840 INFO: Loading module hook 'hook-difflib.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
10439 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
10584 INFO: Loading module hook 'hook-xml.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
12126 INFO: Loading module hook 'hook-jinja2.py' from '/usr/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
13113 INFO: Loading module hook 'hook-sqlalchemy.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
19990 INFO: Loading module hook 'hook-gitlab.py' from '/usr/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
20225 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/usr/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
21293 INFO: Loading module hook 'hook-charset_normalizer.py' from '/usr/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
21531 INFO: Loading module hook 'hook-certifi.py' from '/usr/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
23033 INFO: Processing module hooks...
23044 INFO: Loading module hook 'hook-sqlalchemy.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
2[350](http://gitlab.com/ops/baseapp/habool/-/jobs/261799#L350)5 WARNING: Hidden import "pysqlite2" not found!
23506 WARNING: Hidden import "MySQLdb" not found!
23506 WARNING: Hidden import "psycopg2" not found!
26322 INFO: Loading module hook 'hook-sqlite3.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
26827 INFO: Looking for ctypes DLLs
26850 INFO: Analyzing run-time hooks ...
26863 INFO: Including run-time hook '/usr/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
26865 INFO: Including run-time hook '/usr/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
26869 INFO: Including run-time hook '/usr/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
26927 INFO: Looking for dynamic libraries
Error loading shared library libgcc_s-a04fdf82.so.1: No such file or directory (needed by /usr/lib/python3.10/site-packages/greenlet/../greenlet.libs/libstdc++-a9383cce.so.6.0.28)
27454 INFO: Looking for eggs
27457 INFO: Using Python library /usr/lib/libpython3.10.so.1.0
27468 INFO: Warnings written to /apps/build/app/warn-app.txt
27592 INFO: Graph cross-reference written to /apps/build/app/xref-app.html
27672 INFO: checking PYZ
27673 INFO: Building PYZ because PYZ-00.toc is non existent
27673 INFO: Building PYZ (ZlibArchive) /apps/build/app/PYZ-00.pyz
29593 INFO: Building PYZ (ZlibArchive) /apps/build/app/PYZ-00.pyz completed successfully.
29624 INFO: checking PKG
29624 INFO: Building PKG because PKG-00.toc is non existent
29624 INFO: Building PKG (CArchive) app.pkg
[361](http://gitlab.com/ops/baseapp/habool/-/jobs/261799#L361)07 INFO: Building PKG (CArchive) app.pkg completed successfully.
36111 INFO: Bootloader /usr/lib/python3.10/site-packages/PyInstaller/bootloader/Linux-64bit-intel-musl/run
36112 INFO: checking EXE
36112 INFO: Building EXE because EXE-00.toc is non existent
36112 INFO: Building EXE from EXE-00.toc
36112 INFO: Copying bootloader EXE to /apps/dist/app
36112 INFO: Appending PKG archive to custom ELF section in EXE
36156 INFO: Building EXE from EXE-00.toc completed successfully.
Removing intermediate container 926542196ecd
 ---> 17bd654c87ae
```

**Comment by bwoodsend** [comment]
Thank you for filling out the issue template so that we can help you.

**Comment by novvoo** [comment]
> Thank you for filling out the issue template so that we can help you.

https://stackoverflow.com/questions/75629278/sqlalchemy-is-not-able-to-connect-to-a-database-when-the-script-is-compiled-to-a
https://stackoverflow.com/questions/76435859/pyinstaller-exe-mysql-connector-errors-notsupportederror-authentication-plugin

**Comment by bwoodsend** [comment]
Looks like authentication methods are treated as dynamically loaded (i.e. invisible to PyInstaller) plugins. Use `--hiddenimport=mysql.connector.plugins.mysql_native_password` to include just the native password plugin or `--collect-submodules=mysql.connector.plugins`to include them all.

**Comment by novvoo** [comment]
> Looks like authentication methods are treated as dynamically loaded (i.e. invisible to PyInstaller) plugins. Use `--hiddenimport=mysql.connector.plugins.mysql_native_password` to include just the native password plugin or `--collect-submodules=mysql.connector.plugins`to include them all.

**OK done.  Good Job**
```
26066 INFO: Loading module hook 'hook-certifi.py' from '/usr/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
28011 INFO: Analyzing hidden import 'mysql.connector.plugins.authentication_kerberos_client'
28030 INFO: Analyzing hidden import 'mysql.connector.plugins.authentication_ldap_sasl_client'
28049 INFO: Analyzing hidden import 'mysql.connector.plugins.authentication_oci_client'
28059 INFO: Analyzing hidden import 'mysql.connector.plugins.caching_sha2_password'
28063 INFO: Analyzing hidden import 'mysql.connector.plugins.mysql_clear_password'
28064 INFO: Analyzing hidden import 'mysql.connector.plugins.mysql_native_password'
28068 INFO: Analyzing hidden import 'mysql.connector.plugins.sha256_password'
28069 INFO: Processing module hooks...
28080 INFO: Loading module hook 'hook-sqlalchemy.py' from '/usr/lib/python3.10/site-packages/PyInstaller/hooks'...
```
