### ISSUE TITLE
No module named _bootlocale

### ISSUE THREAD

**Issue by SHAYKHUL** [pyinstaller/pyinstaller#7882]
pyinstaller editor.py            
/usr/bin/pyinstaller:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
1304 INFO: PyInstaller: 3.5+498e6ee058
1304 INFO: Python: 3.11.4
1309 INFO: Platform: Linux-6.3.0-kali1-amd64-x86_64-with-glibc2.37
1315 INFO: wrote /home/shaykhul/Desktop/PythonProjects/editor.spec
1322 INFO: UPX is available.
1325 INFO: Extending PYTHONPATH with paths
['/home/shaykhul/Desktop/PythonProjects',
 '/home/shaykhul/Desktop/PythonProjects']
1325 INFO: checking Analysis
1325 INFO: Building Analysis because Analysis-00.toc is non existent
1325 INFO: Initializing module dependency graph...
1353 INFO: Initializing module graph hooks...
1361 INFO: Analyzing base_library.zip ...
22971 INFO: Processing pre-find module path hook   distutils
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/shaykhul/Desktop/PythonProjects/editor.spec", line 6, in <module>
    a = Analysis(['editor.py'],
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 243, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 348, in assemble
    self.graph = initialize_modgraph(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/analysis.py", line 613, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1473, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1657, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale

**Comment by rokm** [comment]
> 1304 INFO: PyInstaller: 3.5+498e6ee058
> 1304 INFO: Python: 3.11.4
> 1309 INFO: Platform: Linux-6.3.0-kali1-amd64-x86_64-with-glibc2.37

Kali linux packages an ancient version of PyInstaller that is not compatible with python 3.11. Open a bug report with them.
