### ISSUE TITLE
Problems with external library ibm_db_dll

### ISSUE THREAD

**Issue by bobgeorge1st** [pyinstaller/pyinstaller#7904]
I ran pyinstaller with 
binaries=[('C:\\Python3114-64\\Lib\\site-packages\\ibm_db_dlls', '.\\ibm_db_dlls')]
It breaks with the below shown error message. It worked fine with Python 3.8.5 up to pyinstaller 5.9

* Output of `pyinstaller --version`: 5.13.2
* Version of Python: 3.11.4
* Platform:  Windows-10-10.0.19045-SP0
* How you installed Python: Software Distribution
* Did you also try this on another platform? Does it work there? No

### A minimal example program which shows the error

```
import sqlalchemy.exc
import pandas as pd
import ibm_db
import ibm_db_sa

connection_string = f'db2://<user>:<pw>@<connection_string>;PROTOCOL=TCPIP'
engine = sqlalchemy.create_engine(connection_string)
connection = 'bla'
transaction = connection.begin()

stmnt = 'select * from table fetch first 100 row only'

data = pd.read_sql(stmnt, connection)

print(data)

exit()
```

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python3114-64\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "main.spec", line 7, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 429, in __init__
    self.__postinit__()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 745, in assemble
    isolated.call(find_binary_dependencies, self.binaries, self.binding_redirects, collected_packages)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to find_binary_dependencies() failed with:
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 40, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_dll.py", line 20, in _LoadLibraryEx
    result = check_null(
             ^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_util.py", line 78, in __call__
    self._raise_error(function_name)
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_util.py", line 89, in _raise_error
    raise exception
OSError: [WinError 1006] Der Datenträger einer Datei wurde extern so geändert, dass die geöffnete Datei nicht mehr gültig ist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 187, in find_binary_dependencies
    return bindepend.Dependencies(binaries, redirects=binding_redirects, xtrapath=extra_libdirs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 275, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 449, in getAssemblyFiles
    for assembly in getAssemblies(pth):
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 403, in getAssemblies
    res = winmanifest.GetManifestResources(pth)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 979, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 155, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 39, in LoadLibraryEx
    with _pywin32error():
  File "C:\Python3114-64\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1006, 'LoadLibraryEx', 'Der Datenträger einer Datei wurde extern so geändert, dass die geöffnete Datei nicht mehr gültig ist')


```

**Comment by rokm** [comment]
What are the contents of `C:\Python3114-64\Lib\site-packages\ibm_db_dlls` - does it contain only DLLs, or also non-DLL files?

Can you paste the output when you run PyInstaller with added `--log-level DEBUG`? This should print the file names of DLLs as it analyzes them, so it should indicate what file it crashes on. (The lines of interest should be the ones that follow `INFO: Looking for dynamic libraries`).

**Comment by bobgeorge1st** [comment]
There are 3 entries under `C:\Python3114-64\Lib\site-packages\ibm_db_dlls:`
```
__pycache__
__init__.py
ibm_db.dll
```

and here the lines under `INFO: Looking for dynamic libraries`:
```

64373 INFO: Looking for dynamic libraries
C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py:167: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
3402 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Python3114-64\\Lib\\site-packages\\numpy\\.libs']
3402 INFO: Extra DLL search directories (PATH): 
```

**Comment by rokm** [comment]
> and here the lines under `INFO: Looking for dynamic libraries`:

Sorry, I meant the lines between `INFO: Looking for dynamic libraries` and the error (so everything after that line).

**Comment by bobgeorge1st** [comment]
Here it is:
```
83907 INFO: Looking for dynamic libraries
C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py:167: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
3350 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Python3114-64\\Lib\\site-packages\\numpy\\.libs']
3351 INFO: Extra DLL search directories (PATH): ['C:\\Python3114-64\\Scripts\\', 'C:\\Python3114-64\\', 'C:\\Program Files (x86)\\Zulu\\zulu-8-jre\\bin\\', 'C:\\Program Files\\Zulu\\zulu-8-jre\\bin\\', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\PROGRA~1\\IBM\\SQLLIB\\BIN', 'C:\\PROGRA~1\\IBM\\SQLLIB\\FUNCTION']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python3114-64\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "main.spec", line 7, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 429, in __init__
    self.__postinit__()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 745, in assemble
    isolated.call(find_binary_dependencies, self.binaries, self.binding_redirects, collected_packages)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to find_binary_dependencies() failed with:
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 40, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_dll.py", line 20, in _LoadLibraryEx
    result = check_null(
             ^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_util.py", line 78, in __call__
    self._raise_error(function_name)
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_util.py", line 89, in _raise_error
    raise exception
OSError: [WinError 1006] Der Datenträger einer Datei wurde extern so geändert, dass die geöffnete Datei nicht mehr gültig ist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 187, in find_binary_dependencies
    return bindepend.Dependencies(binaries, redirects=binding_redirects, xtrapath=extra_libdirs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 275, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 449, in getAssemblyFiles
    for assembly in getAssemblies(pth):
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 403, in getAssemblies
    res = winmanifest.GetManifestResources(pth)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 979, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 155, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 39, in LoadLibraryEx
    with _pywin32error():
  File "C:\Python3114-64\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1006, 'LoadLibraryEx', 'Der Datenträger einer Datei wurde extern so geändert, dass die geöffnete Datei nicht mehr gültig ist')

```

**Comment by rokm** [comment]
Hmm, was this with added `--log-level DEBUG`? Do you see `DEBUG:` messages in other part of the log?

**Comment by bobgeorge1st** [comment]
I'm working with a spec-file and set the value `debug=1`, but there are no `DEBUG:` messages

**Comment by rokm** [comment]
> I'm working with a spec-file and set the value `debug=1`, but there are no `DEBUG:` messages

No, that's not the same. Remove the `debug=1` from .spec and add `--log-level DEBUG` to the command-line (even if you build from spec).

**Comment by bobgeorge1st** [comment]
Ok, sorry, but it is only a little bit different:

```
64161 INFO: Looking for dynamic libraries
C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py:167: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
3071 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Python3114-64\\Lib\\site-packages\\numpy\\.libs']
3072 INFO: Extra DLL search directories (PATH): ['C:\\Python3114-64\\Scripts\\', 'C:\\Python3114-64\\', 'C:\\Program Files (x86)\\Zulu\\zulu-8-jre\\bin\\', 'C:\\Program Files\\Zulu\\zulu-8-jre\\bin\\', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\PROGRA~1\\IBM\\SQLLIB\\BIN', 'C:\\PROGRA~1\\IBM\\SQLLIB\\FUNCTION']
Traceback (most recent call last):
3088 DEBUG: Analyzing C:\Python3114-64\Lib\site-packages\ibm_db_dlls\__init__.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python3114-64\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "main.spec", line 7, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 429, in __init__
    self.__postinit__()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 745, in assemble
    isolated.call(find_binary_dependencies, self.binaries, self.binding_redirects, collected_packages)
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to find_binary_dependencies() failed with:
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 40, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_dll.py", line 20, in _LoadLibraryEx
    result = check_null(
             ^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_util.py", line 78, in __call__
    self._raise_error(function_name)
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\core\cffi\_util.py", line 89, in _raise_error
    raise exception
OSError: [WinError 1006] Der Datenträger einer Datei wurde extern so geändert, dass die geöffnete Datei nicht mehr gültig ist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\building\build_main.py", line 187, in find_binary_dependencies
    return bindepend.Dependencies(binaries, redirects=binding_redirects, xtrapath=extra_libdirs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 275, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 449, in getAssemblyFiles
    for assembly in getAssemblies(pth):
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\depend\bindepend.py", line 403, in getAssemblies
    res = winmanifest.GetManifestResources(pth)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 979, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\PyInstaller\utils\win32\winresource.py", line 155, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 39, in LoadLibraryEx
    with _pywin32error():
  File "C:\Python3114-64\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python3114-64\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1006, 'LoadLibraryEx', 'Der Datenträger einer Datei wurde extern so geändert, dass die geöffnete Datei nicht mehr gültig ist')
```

**Comment by rokm** [comment]
> 3088 DEBUG: Analyzing C:\Python3114-64\Lib\site-packages\ibm_db_dlls\__init__.py

Yeah, the problem is that you are passing the whole directory as containing binaries, even though it contains non-binaries.

Try amending 
`binaries=[('C:\Python3114-64\Lib\site-packages\ibm_db_dlls', '.\ibm_db_dlls')]` 
in your spec file into
`binaries=[(r'C:\Python3114-64\Lib\site-packages\ibm_db_dlls\ibm_db.dll', 'ibm_db_dlls')]` 
to collect just the DLL.

(Alternatively, `from PyInstaller.utils.hooks import collect_dynamic_libs` and `binaries = collect_dynamic_libs('ibm_db_dlls')` might also do the trick, considering `ibm_db_dlls` is a package installed in site-packages. With added bonus that you don't have to hard-code the path to it in the spec).

**Comment by bobgeorge1st** [comment]
Great, thank you very much!

**Comment by bobgeorge1st** [comment]
Thanks
