### ISSUE TITLE
Compatibility with bitsandbytes

### ISSUE THREAD

**Issue by carlose2108** [pyinstaller/pyinstaller#7911]
I' m having troubles to compile my application with `bitsandbytes`. The thing is that PyInstaller cannot find `CUDA runtime` library when binary file is executed. I have no issues when binary is built. The target machine has `NVIDIA` driver and `CUDA runtime` installed.

Version:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
Python: 3.8.10
```

Installed packages:
```
async-timeout==4.0.3
attrs==23.1.0
bitsandbytes==0.41.1
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
cmake==3.27.2
cuda-python==12.2.0
cx-Freeze==6.15.6
Cython==3.0.2
exceptiongroup==1.1.3
fastapi==0.85.1
filelock==3.12.2
frozenlist==1.4.0
fsspec==2023.6.0
h11==0.14.0
huggingface-hub==0.16.4
idna==3.4
importlib-metadata==6.8.0
Jinja2==3.1.2
joblib==1.3.2
lit==16.0.6
MarkupSafe==2.1.3
mpmath==1.3.0
multidict==6.0.4
networkx==3.1
numpy==1.24.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
openai==0.27.7
ordered-set==4.1.0
packaging==23.1
patchelf==0.17.2.1
peft==0.3.0
pika==1.3.2
Pillow==10.0.0
pkg_resources==0.0.0
psutil==5.9.5
pydantic==1.10.2
pyinstaller==5.13.1
pyinstaller-hooks-contrib==2023.7
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
sacremoses==0.0.53
safetensors==0.3.1
scipy==1.10.1
six==1.16.0
sniffio==1.3.0
starlette==0.20.4
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
tqdm==4.66.1
transformers==4.32.1
triton==2.0.0
typing_extensions==4.7.1
urllib3==2.0.4
uvicorn==0.19.0
yarl==1.9.2
zipp==3.16.2
zstandard==0.21.0
```
Running binary file:
```

===================================BUG REPORT===================================
bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
bitsandbytes/cuda_setup/main.py:166: UserWarning: /tmp/_MEIQ7daeT:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/x86_64-linux-gnu did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
The following directories listed in your path were found to be non-existent: {PosixPath('tcp'), PosixPath('80'), PosixPath('//10.233.39.238')}
The following directories listed in your path were found to be non-existent: {PosixPath('//10.233.40.83'), PosixPath('tcp'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('tcp'), PosixPath('//10.233.12.214'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('tcp'), PosixPath('80'), PosixPath('//10.233.47.122')}
The following directories listed in your path were found to be non-existent: {PosixPath('//10.233.58.206'), PosixPath('tcp'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('tcp'), PosixPath('//10.233.17.183'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('/notebook/augmented/santi-augoor')}
The following directories listed in your path were found to be non-existent: {PosixPath('http'), PosixPath('//santi-augoor-0'), PosixPath('8888/notebook/augmented/santi-augoor')}
The following directories listed in your path were found to be non-existent: {PosixPath('America/New_York')}
The following directories listed in your path were found to be non-existent: {PosixPath('tcp'), PosixPath('80'), PosixPath('//10.233.47.122')}
The following directories listed in your path were found to be non-existent: {PosixPath('443'), PosixPath('//10.233.0.1'), PosixPath('tcp')}
The following directories listed in your path were found to be non-existent: {PosixPath('//10.233.40.83'), PosixPath('tcp'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('//10.233.52.160'), PosixPath('8888'), PosixPath('tcp')}
The following directories listed in your path were found to be non-existent: {PosixPath('//10.233.51.156'), PosixPath('tcp'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('tcp'), PosixPath('//10.233.12.214'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64/stubs')}
The following directories listed in your path were found to be non-existent: {PosixPath('//10.233.51.156'), PosixPath('tcp'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('//10.233.52.160'), PosixPath('8888'), PosixPath('tcp')}
The following directories listed in your path were found to be non-existent: {PosixPath('tcp'), PosixPath('//10.233.17.183'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('443'), PosixPath('//10.233.0.1'), PosixPath('tcp')}
The following directories listed in your path were found to be non-existent: {PosixPath('//10.233.58.206'), PosixPath('tcp'), PosixPath('80')}
The following directories listed in your path were found to be non-existent: {PosixPath('tcp'), PosixPath('80'), PosixPath('//10.233.39.238')}
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 8.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "application/main.py", line 47, in <module>
    from application.inference.loader import load_tokenizer, load_model, load_lora_adapters
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "application/inference/loader.py", line 8, in <module>
    from peft import PeftModel
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "peft/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "peft/mapping.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "peft/peft_model.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "peft/tuners/__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "peft/tuners/lora.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "bitsandbytes/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "bitsandbytes/research/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "bitsandbytes/research/nn/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "bitsandbytes/research/nn/modules.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "bitsandbytes/optim/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "bitsandbytes/cextension.py", line 20, in <module>
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
[806408] Failed to execute script 'main' due to unhandled exception!
```

Running `python -m bitsandbytes` command in local:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda117.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda111.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda113.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda115.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda120.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda112.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda114.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda110.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_linalg.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libc10_cuda.so
/usr/local/cuda/lib64/libcudart.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.7/compat/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/jovyan/sn-model-inference-service/pyinstaller_venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/cuda/ccuda.cpython-38-x86_64-linux-gnu.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/cuda/cudart.cpython-38-x86_64-linux-gnu.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/cuda/cuda.cpython-38-x86_64-linux-gnu.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/cuda/ccudart.cpython-38-x86_64-linux-gnu.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/cuda/_lib/ccudart/ccudart.cpython-38-x86_64-linux-gnu.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/cuda/tests/test_ccuda.cpython-38-x86_64-linux-gnu.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/cuda/tests/test_ccudart.cpython-38-x86_64-linux-gnu.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/cuda/_cuda/ccuda.cpython-38-x86_64-linux-gnu.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/libbitsandbytes_cuda117.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/~orch/lib/libc10_cuda.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/~orch/lib/libtorch_cuda.so
/home/jovyan/sn-model-inference-service/venv/lib/python3.8/site-packages/~orch/lib/libtorch_cuda_linalg.so
/home/jovyan/sn-model-inference-service/main.dist/libtorch_cuda.so
/home/jovyan/sn-model-inference-service/main.dist/torch/lib/libtorch_cuda_linalg.so
/home/jovyan/sn-model-inference-service/main.dist/torch/lib/libc10_cuda.so
/home/jovyan/sn-model-inference-service/main.dist/torch/lib/libtorch_cuda.so
/home/jovyan/sn-model-inference-service/main.dist/libc10_cuda.so
/home/jovyan/sn-model-inference-service/build/libcudart.so
/home/jovyan/sn-model-inference-service/build/stubs/libcuda.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++ /usr/lib/x86_64-linux-gnu CUDA PATHS +++++++++++
/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libcudart.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.0']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```
Am I missing something?
Hope anyone can help with this.

**Comment by rokm** [comment]
Try modifying the generated .spec files with the following additions:
```python
from PyInstaller.utils.hooks import collect_dynamic_libs

hiddenimports = ['triton._C.libtriton']
binaries = collect_dynamic_libs('bitsandbytes')

...

a = Analysis(
    ...
    binaries=binaries,
    hiddenimports=hiddenimports,
    ...
    module_collection_mode={
        # requires source .py files for JIT
        'bitsandbytes': 'pyz+py',
        # requires source .py files for JIT
        # also tries to read the file pointed to by __file__, so we must avoid PYZ
        'triton': 'py',
    }
)

...
```

The rebuild using the .spec file instead of the .py file: `pyinstaller --clean --noconfirm <name>.spec`.

This seems to suffice to get a basic `import bitsandbytes` program running.

The missing CUDA actually seems to be caused by `bitsandbytes/libbitsandbytes*.so` files not beign collected. That's sovled by `collect_dynamic_libs`.

Then the problem is missing indirect import of `triton._C.libtriton`, which is solved by the `hiddenimport`.

Then the real problems start; `triton` needs to be collected in source form (.py files) for JIT, but we must also avoid collecting .pyc modules into PYZ because [`triton` tries to read the file pointed to by modules' `__file__` attributes](https://github.com/openai/triton/blob/bd5c2117f62c73a9e922d5e93353a39ab3ac269b/python/triton/runtime/jit.py#L77-L98).

Lastly, `bitsandbytes` also uses JIT, so it also needs to have its source .py files collected (but in this case, PYZ does not seem to be a problem).

**Comment by carlose2108** [comment]
Hi @rokm 

Thanks a lot for you response. 
 I'll try it out.

**Comment by carlose2108** [comment]
Thanks a lot for your reply @rokm 

It worked!

Hope this issue post can help anyone else.
