### ISSUE TITLE
Executable cannot detect nested folder structure

### ISSUE THREAD

**Issue by harsha-usethread** [pyinstaller/pyinstaller#7921]
I am trying to import chromadb's module to my executable. However, the executable is not correctly handling a file that is nested in  another subfolder in the module. The error is coming from the importlib_resources import files. The exact path that chromadb uses is "chromadb.migrations.embeddings_queue" which seems to hold a migration file that is a sqlite3 file. I have successfully copied that file to my data set via datas += collect_data_files('chromadb.migrations.embeddings_queue') in my .spec file, however this seems to be an issue with pyinstaller not being able to handle a nested folder structure. importlib_resources would return MultiplexedPath('/opt/homebrew/lib/python3.11/site-packages/chromadb/migrations/embeddings_queue') given the function file("chromadb.migrations.embeddings_queue") however the executable created by pyinstaller returns invalid path error:

Here is the exact error:
Traceback (most recent call last):
  File "main.py", line 234, in <module>
  File "main.py", line 65, in main
  File "main.py", line 86, in ingest_documents
  File "chromadb/__init__.py", line 106, in PersistentClient
  File "chromadb/__init__.py", line 143, in Client
  File "chromadb/config.py", line 243, in instance
  File "chromadb/api/segment.py", line 81, in __init__
  File "chromadb/config.py", line 184, in require
  File "chromadb/config.py", line 243, in instance
  File "chromadb/db/impl/sqlite.py", line 65, in __init__
  File "importlib_resources/_common.py", line 46, in wrapper
  File "importlib_resources/_common.py", line 56, in files
  File "importlib_resources/_common.py", line 113, in from_package
  File "importlib_resources/_compat.py", line 85, in get_resource_reader
  File "importlib_resources/_compat.py", line 63, in _native_reader
  File "importlib_resources/_compat.py", line 60, in _available_reader
  File "<frozen importlib._bootstrap_external>", line 1380, in get_resource_reader
  File "importlib/resources/readers.py", line 110, in __init__
ValueError: Invalid path

**Comment by rokm** [comment]
This looks like some sort of incompatibility between our frozen importer, namespace packages, and importlib resources reader...

As a work-around, can you try forcing collection in pure-source mode? This should bypass our frozen importer for the package, and let python's built-in stuff handle it. I.e., in the spec file, add:
```
a = Analysis(
    ...
    module_collection_mode={        
        'chromadb': 'py',
    }
)
```
and rebuilt the application. You should see the modules of `chromadb` collected as .py files. 

You will still need to deal with hidden imports yourself, particularly for nested namespace packages (but suppose if you came this far, you already did some of that).

**Comment by harsha-usethread** [comment]
This worked! I needed to manually add __init__ files to these locations and add these hidden_modules:
hiddenimports = ['chromadb.telemetry.posthog', 'chromadb.api.segment', 'chromadb.db.impl', 'chromadb.db.impl.sqlite', 'chromadb.migrations', 'chromadb.migrations.embeddings_queue', 'chromadb.segment.impl.manager', 'chromadb.segment.impl.manager.local', 'chromadb.segment.impl.metadata', 'chromadb.segment.impl.metadata.sqlite', 'chromadb.segment.impl.vector', 'chromadb.segment.impl.vector.batch', 'chromadb.segment.impl.vector.brute_force_index', 'chromadb.segment.impl.vector.hnsw_params', 'chromadb.segment.impl.vector.local_hnsw', 'chromadb.segment.impl.vector.local_persistent_hnsw']

But for now it seems to be working? Its not fully running yet but there might be unrelated issues
