### ISSUE TITLE
pack transformers but hook altgraph/Graph.py got an error

### ISSUE THREAD

**Issue by MewemeW** [pyinstaller/pyinstaller#7932]
before add hiddenimports, pyinstaller works fine, but transformers can not be packed. 

then I add code 'hiddenimports=[collect_submodules("transformers")],' at Analysis

```
from PyInstaller.utils.hooks import collect_submodules, collect_all

block_cipher = None

datas, binaries, hiddenimports = collect_all('numpy')

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[collect_submodules("transformers")],
    hookspath=[], 
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

```

it got :

```
374 INFO: Appending 'binaries' from .spec
4375 INFO: Appending 'datas' from .spec
4376 INFO: checking Analysis
4376 INFO: Building Analysis because Analysis-00.toc is non existent
4376 INFO: Initializing module dependency graph...
4379 INFO: Caching module graph hooks...
4397 INFO: Analyzing base_library.zip ...
6020 INFO: Loading module hook 'hook-heapq.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
6111 INFO: Loading module hook 'hook-encodings.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
7699 INFO: Loading module hook 'hook-pickle.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
9231 INFO: Caching module dependency graph...
9413 INFO: running Analysis Analysis-00.toc
9435 INFO: Analyzing /tf/eva/csc/bartcsc/gradio_demo/pyinstall/main.py
9547 INFO: Loading module hook 'hook-difflib.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
9566 INFO: Loading module hook 'hook-rapidfuzz.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/rapidfuzz/__pyinstaller'...
14572 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
15872 INFO: Loading module hook 'hook-platform.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
15921 INFO: Loading module hook 'hook-xml.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
15963 INFO: Loading module hook 'hook-sysconfig.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
16031 INFO: Loading module hook 'hook-numpy.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/numpy/_pyinstaller'...
16053 WARNING: Conda distribution 'numpy', dependency of 'numpy', was not found. If you installed this distribution with pip then you may ignore this warning.
18439 INFO: Loading module hook 'hook-psutil.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
20004 INFO: Processing pre-safe import module hook tensorflow from '/home/anaconda/envs/py38/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-tensorflow.py'.
21105 INFO: Loading module hook 'hook-charset_normalizer.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
21276 INFO: Loading module hook 'hook-certifi.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
21639 INFO: Loading module hook 'hook-packaging.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/hooks'...
26898 INFO: Loading module hook 'hook-regex.py' from '/home/anaconda/envs/py38/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
Traceback (most recent call last):
  File "/home/anaconda/envs/py38/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "main.spec", line 9, in <module>
    a = Analysis(
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 429, in __init__
    self.__postinit__()
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 593, in assemble
    self.graph.add_hiddenimports(self.hiddenimports)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/depend/analysis.py", line 715, in add_hiddenimports
    node = self.find_node(modnm)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1285, in find_node
    data = super(ModuleGraph, self).findNode(name)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/altgraph/ObjectGraph.py", line 153, in findNode
    return self.graph.node_data(ident)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/altgraph/Graph.py", line 293, in node_data
    return self.nodes[node][2]
TypeError: unhashable type: 'list'
```

**Comment by rokm** [comment]
>     hiddenimports=[collect_submodules("transformers")],
is incorrect, because you are passing list of lists instead of list of strings. It should be
```
hiddenimports=collect_submodules("transformers"),
```
or
```
hiddenimports=[*collect_submodules("transformers")],
```

**Comment by MewemeW** [comment]
> > ```
> > hiddenimports=[collect_submodules("transformers")],
> > ```
> 
> is incorrect, because you are passing list of lists instead of list of strings. It should be
> 
> ```
> hiddenimports=collect_submodules("transformers"),
> ```
> 
> or
> 
> ```
> hiddenimports=[*collect_submodules("transformers")],
> ```

Ah! you're right, thanks!
