### ISSUE TITLE
Removing codesign failed on macOS

### ISSUE THREAD

**Issue by BLKSerene** [pyinstaller/pyinstaller#7960]
## Description of the issue
```
SystemError: codesign command (['codesign', '--remove', '--all-architectures', '/Users/blkserene/Desktop/build/test/test']) failed with error code 1!
output: /Users/blkserene/Desktop/build/test/test: invalid or unsupported format for signature
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```6.0.0
* Version of Python: 3.10.11
* Platform: OS X 10.11
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?
Not relevant on other platforms

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
6.0.0 is already the latest development version.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import torch
```

### Stacktrace / full error message

```
296 INFO: PyInstaller: 6.0.0
296 INFO: Python: 3.10.11
315 INFO: Platform: macOS-10.11.6-x86_64-i386-64bit
316 INFO: wrote /Users/blkserene/Desktop/test.spec
321 INFO: Removing temporary files and cleaning cache in /Users/blkserene/Library/Application Support/pyinstaller
327 INFO: Extending PYTHONPATH with paths
['/Users/blkserene/Desktop']
620 INFO: checking Analysis
620 INFO: Building Analysis because Analysis-00.toc is non existent
620 INFO: Initializing module dependency graph...
622 INFO: Caching module graph hooks...
644 INFO: Analyzing base_library.zip ...
1194 INFO: Loading module hook 'hook-heapq.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
1431 INFO: Loading module hook 'hook-encodings.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
2275 INFO: Loading module hook 'hook-pickle.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
3165 INFO: Caching module dependency graph...
3238 INFO: Running Analysis Analysis-00.toc
3238 INFO: Looking for Python shared library...
3243 INFO: Using Python shared library: /Library/Frameworks/Python.framework/Versions/3.10/Python
3243 INFO: Analyzing /Users/blkserene/Desktop/test.py
3263 INFO: Loading module hook 'hook-torch.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
3265 INFO: hook-torch: raising recursion limit to 5000
3612 INFO: Loading module hook 'hook-platform.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
3631 INFO: Loading module hook 'hook-xml.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
3680 INFO: Loading module hook 'hook-packaging.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
3743 INFO: Loading module hook 'hook-pkg_resources.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
4415 INFO: Loading module hook 'hook-sysconfig.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
5374 INFO: Loading module hook 'hook-sympy.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5455 INFO: Loading module hook 'hook-numpy.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/_pyinstaller'...
5919 INFO: Loading module hook 'hook-difflib.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
6109 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
8694 INFO: Loading module hook 'hook-matplotlib.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
9059 INFO: Processing pre-safe import module hook gi from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.py'.
9192 INFO: Loading module hook 'hook-PIL.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
9247 INFO: Loading module hook 'hook-PIL.Image.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
9760 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
10159 INFO: Loading module hook 'hook-jinja2.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
11274 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
11603 INFO: Processing pre-safe import module hook six.moves from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
12524 INFO: Loading module hook 'hook-certifi.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
18817 INFO: Loading module hook 'hook-scipy.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
19065 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
19125 INFO: Loading module hook 'hook-scipy.linalg.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
20457 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
23726 INFO: Loading module hook 'hook-xml.dom.domreg.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
23913 INFO: Loading module hook 'hook-lxml.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
24884 INFO: Loading module hook 'hook-sqlite3.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
27674 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
29942 INFO: Loading module hook 'hook-charset_normalizer.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
30381 INFO: Loading module hook 'hook-pydantic.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
31142 INFO: Processing pre-safe import module hook tensorflow from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-tensorflow.py'.
32530 INFO: Processing pre-safe import module hook distutils from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-distutils.py'.
32531 INFO: Processing pre-find module path hook distutils from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
32755 INFO: Loading module hook 'hook-distutils.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
33495 INFO: Loading module hook 'hook-scipy.io.matlab.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
34337 INFO: Loading module hook 'hook-sklearn.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
34632 INFO: Loading module hook 'hook-sklearn.utils.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
34981 INFO: Loading module hook 'hook-sklearn.metrics.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
36544 INFO: Loading module hook 'hook-sklearn.metrics.cluster.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
36664 INFO: Loading module hook 'hook-sklearn.cluster.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
36909 INFO: Loading module hook 'hook-sklearn.metrics.pairwise.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37076 INFO: Loading module hook 'hook-sklearn.neighbors.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37152 INFO: Loading module hook 'hook-sklearn.linear_model.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
39313 INFO: Loading module hook 'hook-regex.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
39823 INFO: Loading module hook 'hook-sudachipy.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
41450 INFO: Loading module hook 'hook-sacremoses.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
43046 INFO: Loading module hook 'hook-jieba.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
44773 INFO: Loading module hook 'hook-setuptools.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
45727 INFO: Loading module hook 'hook-distutils.util.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
46470 INFO: Processing pre-safe import module hook win32com from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
52628 INFO: Loading module hook 'hook-spacy.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
61520 INFO: Loading module hook 'hook-thinc.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
65037 INFO: Loading module hook 'hook-langcodes.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
70465 INFO: Loading module hook 'hook-pythainlp.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
70542 INFO: Loading module hook 'hook-zoneinfo.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
70634 INFO: Loading module hook 'hook-pycrfsuite.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
74126 INFO: Processing module hooks...
74127 INFO: Loading module hook 'hook-lxml.etree.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
74205 INFO: Loading module hook 'hook-lxml.isoschematron.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
74219 WARNING: Hidden import "sklearn.neighbors._typedefs" not found!
74220 INFO: Loading module hook 'hook-sklearn.tree.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
74889 INFO: Loading module hook 'hook-pymorphy3.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
76825 INFO: Loading module hook 'hook-srsly.msgpack._packer.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
76827 INFO: Loading module hook 'hook-thinc.backends.numpy_ops.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
77185 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
77186 INFO: Matplotlib backend selection method: automatic discovery of used backends
77199 INFO: Discovered Matplotlib backend(s) via `matplotlib.use()` call in module 'sympy.testing.runtests': ['Agg', 'Agg']
77202 INFO: The following Matplotlib backends were discovered by scanning for `matplotlib.use()` calls: ['Agg', 'Agg']. If your backend of choice is not in this list, either add a `matplotlib.use()` call to your code, or configure the backend collection via hook options (see: https://pyinstaller.org/en/stable/hooks-config.html#matplotlib-hooks).
77202 INFO: Selected matplotlib backends: ['Agg', 'Agg']
77366 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
77742 INFO: Loading module hook 'hook-platformdirs.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
77797 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
77798 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
77799 INFO: Loading module hook 'hook-scipy.stats._stats.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
77826 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks'...
78549 INFO: Loading module hook 'hook-lxml.objectify.py' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
84509 INFO: Looking for ctypes DLLs
84513 WARNING: Library vcruntime140_1.dll required via ctypes not found
84514 WARNING: Library vcruntime140.dll required via ctypes not found
84514 WARNING: Library msvcp140.dll required via ctypes not found
84538 WARNING: Library user32 required via ctypes not found
84584 WARNING: Library libnvidia-ml.so.1 required via ctypes not found
84601 WARNING: Ignoring /usr/lib64/libgomp.so.1 imported from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/_inductor/codecache.py - only basenames are supported with ctypes imports!
84622 INFO: Analyzing run-time hooks ...
84672 INFO: Including run-time hook '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
84674 INFO: Including run-time hook '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
84677 INFO: Including run-time hook '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
84681 INFO: Including run-time hook '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
84686 INFO: Including run-time hook '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_mplconfig.py'
84687 INFO: Processing pre-find module path hook _pyi_rth_utils from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/pre_find_module_path/hook-_pyi_rth_utils.py'.
84696 INFO: Including run-time hook '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_setuptools.py'
85263 INFO: Looking for dynamic libraries
88612 INFO: Warnings written to /Users/blkserene/Desktop/build/test/warn-test.txt
88991 INFO: Graph cross-reference written to /Users/blkserene/Desktop/build/test/xref-test.html
89424 INFO: checking PYZ
89425 INFO: Building PYZ because PYZ-00.toc is non existent
89425 INFO: Building PYZ (ZlibArchive) /Users/blkserene/Desktop/build/test/PYZ-00.pyz
93785 INFO: Building PYZ (ZlibArchive) /Users/blkserene/Desktop/build/test/PYZ-00.pyz completed successfully.
93909 INFO: EXE target arch: x86_64
93909 INFO: Code signing identity: None
93916 INFO: checking PKG
93916 INFO: Building PKG because PKG-00.toc is non existent
93916 INFO: Building PKG (CArchive) test.pkg
93967 INFO: Building PKG (CArchive) test.pkg completed successfully.
93968 INFO: Bootloader /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/bootloader/Darwin-64bit/run
93968 INFO: checking EXE
93968 INFO: Building EXE because EXE-00.toc is non existent
93968 INFO: Building EXE from EXE-00.toc
93968 INFO: Copying bootloader EXE to /Users/blkserene/Desktop/build/test/test
93969 INFO: Converting EXE to target arch (x86_64)
93996 INFO: Removing signature(s) from EXE
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/__main__.py", line 205, in _console_script_run
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/__main__.py", line 189, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1033, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 973, in build
    exec(code, spec_namespace)
  File "/Users/blkserene/Desktop/test.spec", line 18, in <module>
    exe = EXE(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/api.py", line 625, in __init__
    self.__postinit__()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/api.py", line 802, in assemble
    osxutils.remove_signature_from_binary(build_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/utils/osx.py", line 364, in remove_signature_from_binary
    raise SystemError(f"codesign command ({cmd_args}) failed with error code {p.returncode}!\noutput: {p.stdout}")
SystemError: codesign command (['codesign', '--remove', '--all-architectures', '/Users/blkserene/Desktop/build/test/test']) failed with error code 1!
output: /Users/blkserene/Desktop/build/test/test: invalid or unsupported format for signature
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Old versions of macOS are not supported, due to `codesign` (which is provided by the OS) being buggy. I recall seeing issues with `codesign` on macOS 10.13, so I doubt 10.11 is likely to fare any better.

In this case, it *might* help if you try to compile the bootloader yourself, using the old toolchain corresponding to that macOS version. This might fix issues with `lipo` and `codesign` not being able to deal with never pre-built `universal2` bootloader.
