### ISSUE TITLE
Problem when packaging Tensorflow on window10

### ISSUE THREAD

**Issue by junjielyu13** [pyinstaller/pyinstaller#7961]
I encountered the following problem when I wanted to package my python files with **tensorflow**

Os: windows 10
python version: 3.11.5
All dependent libraries are up to date

code: 
```python
import cv2
import numpy as np
from tensorflow import keras
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = ""

if __name__=="__main__":
    url = "xxxx"
    capture = cv2.VideoCapture(url)
    model = keras.models.load_model(os.path.join(os.path.dirname(__file__),'cameraMovement.h5'))
    nninput = np.zeros((1,300,400,2),dtype=np.uint8)
    if capture.isOpened():
        ret, frame = capture.read()
        if ret:
            nninput[0,:,:,0]=cv2.cvtColor(cv2.resize(frame,(400,300)),cv2.COLOR_BGR2GRAY)
        t=0
        while ret and t<100:
            t+=1
            ret, frame = capture.read()

        if ret:
            nninput[0,:,:,1]=cv2.cvtColor(cv2.resize(frame,(400,300)),cv2.COLOR_BGR2GRAY)
        
        pred = model.predict(nninput,verbose=0,use_multiprocessing=True)[0]

        print(pred)
````

``` bash
pyinstaller --add-data "./cameraMovement.h5:."  --windowed script.py
```` 

error:
````
Traceback (most recent call last):
  File "script.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\__init__.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\saved_model\saved_model.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\saved_model\builder.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\saved_model\builder_impl.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\framework\dtypes.py", line 37, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
````

**Comment by rokm** [comment]
If I'm reading the traceback correctly, this fails when trying to import `tensorflow` in line 3? Can you reproduce the error if you reduce your script.py to just  
```python
from tensorflow import keras
```
? 

What version of `tensorflow` are you using?

**Comment by junjielyu13** [comment]
> If I'm reading the traceback correctly, this fails when trying to import `tensorflow` in line 3? Can you reproduce the error if you reduce your script.py to just
> 
> ```python
> from tensorflow import keras
> ```
> 
> ?
> 
> What version of `tensorflow` are you using?

````
$ pip list | grep tensor
tensorboard                  2.14.1
tensorboard-data-server      0.7.1
tensorflow                   2.14.0
tensorflow-estimator         2.14.0
tensorflow-intel             2.14.0
tensorflow-io-gcs-filesystem 0.31.0
````

**Comment by rokm** [comment]
I can reproduce; will check what is going on...

**Comment by junjielyu13** [comment]
> If I'm reading the traceback correctly, this fails when trying to import `tensorflow` in line 3? Can you reproduce the error if you reduce your script.py to just

I deleted all the code except this line, but the same problem still occurs. It seems that this is the problem:

``` python
from tensorflow import keras
````

**Comment by rokm** [comment]
Yeah, that makes it easier to debug, since it is a general `tensorflow` + `PyInstaller` issue, instead of it being tied to your model.

**Comment by junjielyu13** [comment]
If I only **import keras**, the problem is the same, Is there any way to solve it?

**Comment by rokm** [comment]
Not until I figure out what is actually wrong.

**Comment by junjielyu13** [comment]
> Not until I figure out what is actually wrong.

thank!!!!!

**Comment by rokm** [comment]
` --hiddenimport ml_dtypes` should take care of this particular problem. 

We'll update the hooks for `tensorflow`; I see 2.14.0 was released yesterday, so that explains why we have not seen the failure on our CI in the contributed hooks repository.

**Comment by junjielyu13** [comment]
Thank you so much!!! It's looks working!!
