### ISSUE TITLE
issue with timeit

### ISSUE THREAD

**Issue by man-in-cloud** [pyinstaller/pyinstaller#7962]
Hi guys
Just upgraded to the latest version and its showing this error. Now reverted back to previous version and its working again.
After the exe is made successfully and I run the app to create a chart. The error below is shown.
this is one of matplotlib dependencies.
The app is running in windows11 via MacOS parallels, been using pyinstaller for a year with no issue until now.

Thank you for the great work guys, please help.
```
Internal Server Error: /incident/view_statistics/
Traceback (most recent call last):
  File "django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "incident\views.py", line 1364, in view_statistics
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\matplotlib\pyplot.py", line 1119, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\matplotlib\figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\matplotlib\backend_bases.py", line 2127, in print_figure
    with cbook._setattr_cm(self, manager=None), \
  File "contextlib.py", line 137, in __enter__
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\matplotlib\backend_bases.py", line 2027, in _switch_canvas_and_return_print_method
    canvas_class = get_registered_canvas_class(fmt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\matplotlib\backend_bases.py", line 148, in get_registered_canvas_class
    backend_class = importlib.import_module(backend_class).FigureCanvas
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\matplotlib\backends\backend_pdf.py", line 44, in <module>
    from . import _backend_pdf_ps
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\matplotlib\backends\_backend_pdf_ps.py", line 8, in <module>
    from fontTools import subset
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\fontTools\__init__.py", line 2, in <module>
    from fontTools.misc.loggingTools import configLogger
  File "C:\Users\user\PycharmProjects\mhk\chart\dist\chart\_internal\fontTools\misc\loggingTools.py", line 3, in <module>
    import timeit
ModuleNotFoundError: No module named 'timeit'
```

**Comment by rokm** [comment]
Hmm, if everything down to `fontTools.misc.loggingTools` ended up automatically collected, I fail to see why we would fail to pick up `timeit` from stdlib. Does it make any difference if you add `timeit` to hiddenimports?
 
Can you reproduce this problem outside of a Django application? Based on the traceback, I think a simple program that does just `import matplotlib.backends.backend_pdf` or even `import fontTools` might do the trick.
