### ISSUE TITLE
no package named "pkg_resources"

### ISSUE THREAD

**Issue by ControlAlternateDel** [pyinstaller/pyinstaller#7964]
## Description of the issue
I tried using pyinstaller on a command line program, the prompt threw this error at me: 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 161, in run
    parser = generate_parser()
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 128, in generate_parser
    import PyInstaller.building.build_main
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 28, in <module>
    from PyInstaller.building.api import COLLECT, EXE, MERGE, PYZ
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\api.py", line 26, in <module>
    from PyInstaller.archive.writers import CArchiveWriter, ZlibArchiveWriter
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\archive\writers.py", line 22, in <module>
    from PyInstaller.building.utils import get_code_object, strip_paths_in_code
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\utils.py", line 33, in <module>
    from PyInstaller.depend.bindepend import match_binding_redirect
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\bindepend.py", line 27, in <module>
    from PyInstaller.depend import dylib, utils
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\utils.py", line 31, in <module>
    from PyInstaller.lib.modulegraph import modulegraph
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 16, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

### Context information (for bug reports)
just plain use the command: pyinstaller

* Output of `pyinstaller --version`: ```ModuleNotFoundError: No module named 'pkg_resources'```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Sounds like `setuptools` is missing in your python environment. I'm not sure how that could happen (as it should be installed as part of PyInstaller's dependencies), unless if you manually removed it after you installed PyInstaller. Try installing it back.

Or you can try using the latest version of PyInstaller, which does not use `pkg_resources` anymore.
