### ISSUE TITLE
Import error for picamer2 library. 

### ISSUE THREAD

**Issue by ajo79** [pyinstaller/pyinstaller#7977]
Normally when i run command - python start_up.py, my application runs fine. I am running this app on raspberry pi 4.  
But when I am trying to create executible file from my application start_up.py
I follow this command  pyinstaller --onefile start_up.py
package get created but when i run the application it gives below error 

--------------------------------------------------------------------------------
```
File "start_up.py", line 13, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "home.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "auto.py", line 36, in <module>
ImportError: cannot import name 'QGlPicamera2' from 'picamera2.previews.qt' (/tmp/_MEItFwl44/picamera2/previews/qt.pyc)
```
--------------------------------------------------------------------------------
my application needs picamer2 library. 

Please help me what should i do?

**Comment by rokm** [comment]
> `ImportError: cannot import name 'QGlPicamera2' from 'picamera2.previews.qt'`

If `QGlPicamera2` cannot be imported from `picamera2.previews.qt`, then this import failed:
https://github.com/raspberrypi/picamera2/blob/0759b0ec3252dc665043bff77e363b02e0937f5d/picamera2/previews/qt.py#L12-L15
```
try:
    from .q_gl_picamera2 import QGlPicamera2
except Exception:
    _log.warning("OpenGL will not be available")
```

To see why, you could temporarily modify your copy of `picamera2` to either 
- add `exc_info=True` to that `_log.warning()` call (which will print exception information)
- add a `rase` after the `_log.warning()` call (which will re-raise the exception)

Or try importing `picamera2.previews.q_gl_picamera2` in your program.

**Comment by ajo79** [comment]
I don't know how to add exc_info=True in picamera2 code . May you please modify this file for me? 
picamera2/previews/qt.py

**Comment by ajo79** [comment]
mistakenly closed the issue

**Comment by ajo79** [comment]
should i modify like this 

try:
    from .q_gl_picamera2 import QGlPicamera2
except Exception as e:
    _log.warning("OpenGL will not be available", exc_info=True)
    raise e

**Comment by bwoodsend** [comment]
That would do.

**Comment by ajo79** [comment]
I tried to include picamera2.previews.q_gl_picamera2 in my project, but it gives below error 

```
pi@raspberrypi:~/BABU/NEW_UI_copy/dist $ sudo ./camera 
Traceback (most recent call last):
  File "camera.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "picamera2/previews/q_gl_picamera2.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "OpenGL/EGL/_init_.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "OpenGL/raw/EGL/_types.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "OpenGL/platform/_init_.py", line 36, in <module>
  File "OpenGL/platform/_init_.py", line 30, in _load
TypeError: 'NoneType' object is not callable
[8283] Failed to execute script 'camera' due to unhandled exception!
pi@raspberrypi:~/BABU/NEW_UI_copy/dist $
```

**Comment by rokm** [comment]
Try adding `--hiddenimport OpenGL.platform.egl` to your PyInstaller command. Or, if that doesn't help, even `--collect-submodules OpenGL`.
