### ISSUE TITLE
Pyinstaller errors with Fastai

### ISSUE THREAD

**Issue by khs123** [pyinstaller/pyinstaller#7985]
## Description of the issue
 I have been using PyInstaller to package my application, which utilizes Torch and Fastai. However, I encountered an issue during the build process. While PyInstaller successfully built the application, I encountered an error when trying to run the generated executable.
 In this situation, I addressed the error by adding 'fastai.layers' to the list of hidden imports.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.0.0```
* Version of Python: 3.8
* Platform: OSX
* How you installed Python: pyenv

### Errors

```
Traceback (most recent call last):
  File "api.py", line 21, in <module>
    from modules.face.faces_v3 import faceAnalysis
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "modules/face/faces_v3.py", line 52, in <module>
    siamese_head = torch.load('models/face/siamese_head.pth')
  File "torch/serialization.py", line 809, in load
  File "torch/serialization.py", line 1172, in _load
  File "torch/serialization.py", line 1165, in find_class
ModuleNotFoundError: No module named 'fastai.layers'
```
In this situation, I  added 'fastai.layers' to the list of hidden imports.
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None
def get_mediapipe_path():
    import mediapipe
    mediapipe_path = mediapipe.__path__[0]
    return mediapipe_path

a = Analysis(
    ['api.py'],
    pathex=[SPECPATH],
    binaries=[],
    datas=[],
    hiddenimports=['fastai.layers'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
mediapipe_tree = Tree(get_mediapipe_path(), prefix='mediapipe', excludes=["*.pyc"])
a.datas += mediapipe_tree
a.binaries = filter(lambda x: 'mediapipe' not in x[0], a.binaries)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='lao_card_reader',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
datas = [
    ('data/*.*', 'data/'),
    ('.env', '.env'),
    ('models/**/*.*', 'models/')
]

```
Then errors
### Stacktrace / full error message

```
Traceback (most recent call last):
  File "torch/_sources.py", line 23, in get_source_lines_and_file
  File "inspect.py", line 979, in getsourcelines
  File "inspect.py", line 798, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "api.py", line 21, in <module>
    from modules.face.faces_v3 import faceAnalysis
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "modules/face/faces_v3.py", line 52, in <module>
    siamese_head = torch.load('models/face/siamese_head.pth')
  File "torch/serialization.py", line 809, in load
  File "torch/serialization.py", line 1172, in _load
  File "torch/serialization.py", line 1165, in find_class
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "fastai/layers.py", line 499, in <module>
  File "torch/jit/_script.py", line 1338, in script
  File "torch/jit/frontend.py", line 262, in get_jit_def
  File "torch/_sources.py", line 120, in parse_def
  File "torch/_sources.py", line 32, in get_source_lines_and_file
OSError: Can't get source for <function _swish_jit_fwd at 0x7f7d6277b040>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

```

**Comment by rokm** [comment]
Sounds like you need to collect sources for your python packages that use `torch` JIT. Presumably that is `fastai`.

Try modifying the `Analysis` in the spec file as follows:
```python
a = Analysis(
    ...
    noarchive=False,
    module_collection_mode={
        'fastai': 'pyz+py',  # collect source .py files in addition to byte-compiled .pyc modules
    },
)
```

**Comment by khs123** [comment]
Thanks you, but new exception raise. Can you help me how to fix this ?
```
  File "api.py", line 23, in <module>
    from modules.recognition_phone_number.reader import PhoneNumberReader
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "modules/recognition_phone_number/reader.py", line 1, in <module>
    from paddleocr import PaddleOCR
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "paddleocr/__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "paddleocr/paddleocr.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "paddle/__init__.py", line 62, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "paddle/distributed/__init__.py", line 54, in <module>
AttributeError: module 'paddle.distributed.communication' has no attribute 'stream'


```

**Comment by rokm** [comment]
Try adding `--hiddenimport paddle.distributed.communication.stream` (or maybe `--collect-submodules paddle.distributed.communication`, or even `--collect-submodules paddle`). 

That said, the  only multiprocessing framework supported by PyInstaller is stdlib's `multiprocessing`, so if you run into any problems with `paddle`, you are on your own.

**Comment by khs123** [comment]
Thanks a lot @rokm
