### ISSUE TITLE
PyInstaller 6.1.0 does not work with oracledb

### ISSUE THREAD

**Issue by luismariosb** [pyinstaller/pyinstaller#8012]
Hi,

I'm running Pyinstaller version 6.1.0 and Python 3.11.5. The code is working and the executable file was created normally (pyinstaller --onefile OracleTest.py) but when I try to run it shows the following error:

```
Traceback (most recent call last):
  File "OracleTest.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "oracledb\__init__.py", line 56, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "oracledb\connection.py", line 45, in <module>
  File "src\\oracledb\\base_impl.pyx", line 48, in init oracledb.base_impl
ModuleNotFoundError: No module named 'secrets'
[20552] Failed to execute script 'OracleTest' due to unhandled exception!
```

I have the following code:

```
import oracledb

un = 'teste'
cs = 'server.teste.com.br:1521/teste'
pw = '******'

with oracledb.connect(user=un, password=pw, dsn=cs) as connection:
    with connection.cursor() as cursor:
        sql = """select sysdate from dual"""
        for r in cursor.execute(sql):
            print(r)
```

Does anyone have any idea what it could be?

Regards,
Luis

**Comment by rokm** [comment]
> File "src\oracledb\base_impl.pyx", line 48, in init oracledb.base_impl
> ModuleNotFoundError: No module named 'secrets'
> [20552] Failed to execute script 'OracleTest' due to unhandled exception!

`oracledb.base_impl` is a binary extension, so PyInstaller cannot scan its imports. 

Try adding `secrets` to hidden imports.

**Comment by luismariosb** [comment]
Hi Rokm,

I added secrets to hidden imports (pyinstaller --hidden-import 'secrets' --onefile OracleTest.py) and I'm facing a new error now:
```
Traceback (most recent call last):
  File "OracleTest.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "oracledb\__init__.py", line 56, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "oracledb\connection.py", line 45, in <module>
ImportError: cannot import name 'base_impl' from partially initialized module 'oracledb' (most likely due to a circular import) (C:\Users\lbraga\AppData\Local\Temp\_MEI316482\oracledb\__init__.pyc)
[35772] Failed to execute script 'OracleTest' due to unhandled exception!
```
I've tried to add base_impl (pyinstaller --add-data './oracledb/base_impl.pxd;oracledb' --hidden-import 'secrets' --onefile OracleTest.py) and I've gotten the following error:

```
Traceback (most recent call last):
  File "OracleTest.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "oracledb\__init__.py", line 56, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "oracledb\connection.py", line 45, in <module>
ImportError: cannot import name 'base_impl' from partially initialized module 'oracledb' (most likely due to a circular import) (C:\Users\lbraga\AppData\Local\Temp\_MEI141442\oracledb\__init__.pyc)
[26832] Failed to execute script 'OracleTest' due to unhandled exception!
```

Would you have any idea how to solve it?

Thank you for your time.
Regards

**Comment by rokm** [comment]
What version of `oracledb` is that? With 1.4.2, `--hidden-import secrets --hidden-import getpass --hidden-import ssl --hidden-import uuid` seems to be enough to get a basic `import oracledb` program running. Could be that some modules are not collected from the package - try adding `--collect-submodules oracledb`.

**Comment by luismariosb** [comment]
Hi Rokm,

The oracledb version is 1.4.2. 
I tried those commands: 
1)  "pyinstaller --hidden-import secrets --hidden-import getpass --hidden-import ssl --hidden-import uuid --onefile OracleTest.py" and "pyinstaller --hidden-import secrets --hidden-import getpass --hidden-import ssl --hidden-import uuid --collect-submodules oracledb --onefile OracleTest.py" both showed error:

```
Traceback (most recent call last):
  File "OracleTest.py", line 7, in <module>
  File "oracledb\connection.py", line 1020, in connect
  File "oracledb\connection.py", line 129, in __init__
  File "src\\oracledb\\impl/thin/connection.pyx", line 76, in oracledb.thin_impl.ThinConnImpl.__init__
  File "oracledb\errors.py", line 127, in _raise_err
oracledb.exceptions.NotSupportedError: DPY-3016: python-oracledb thin mode cannot be used because the cryptography package is not installed
[14080] Failed to execute script 'OracleTest' due to unhandled exception!
```

I tried to include cryptography but I keep getting the same error message.

```
pyinstaller --hidden-import secrets --hidden-import getpass --hidden-import ssl --hidden-import uuid --hidden-import cryptography --onefile OracleTest.py
```

```
682 INFO: PyInstaller: 6.1.0
682 INFO: Python: 3.11.5
710 INFO: Platform: Windows-10-10.0.22621-SP0
715 INFO: wrote D:\lbraga\OneDrive\Trabalho\Empresas\ORACLE\LBRAGA_LAP\Desktop\ProjetoXML\OracleTest.spec
726 INFO: Extending PYTHONPATH with paths
['D:\\lbraga\\OneDrive\\Trabalho\\Empresas\\ORACLE\\LBRAGA_LAP\\Desktop\\ProjetoXML']
1185 INFO: checking Analysis
1187 INFO: Building because hiddenimports changed
1188 INFO: Initializing module dependency graph...
1191 INFO: Caching module graph hooks...
1217 INFO: Analyzing base_library.zip ...
4047 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\lbraga\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
4579 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\lbraga\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
7287 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\lbraga\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
8890 INFO: Caching module dependency graph...
9076 INFO: Running Analysis Analysis-00.toc
9076 INFO: Looking for Python shared library...
9104 INFO: Using Python shared library: C:\Users\lbraga\AppData\Local\Programs\Python\Python311\python311.dll
9104 INFO: Analyzing D:\lbraga\OneDrive\Trabalho\Empresas\ORACLE\LBRAGA_LAP\Desktop\ProjetoXML\OracleTest.py
9354 INFO: Analyzing hidden import 'secrets'
9364 INFO: Analyzing hidden import 'getpass'
9374 INFO: Analyzing hidden import 'ssl'
9423 INFO: Analyzing hidden import 'uuid'
9473 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\lbraga\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
9481 INFO: Analyzing hidden import 'cryptography'
9485 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\Users\\lbraga\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...        
12046 INFO: Processing module hooks...
12709 INFO: Looking for ctypes DLLs
12721 INFO: Analyzing run-time hooks ...
12726 INFO: Including run-time hook 'C:\\Users\\lbraga\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
12735 INFO: Looking for dynamic libraries
13319 INFO: Extra DLL search directories (AddDllDirectory): []
13320 INFO: Extra DLL search directories (PATH): []
13985 INFO: Warnings written to D:\lbraga\OneDrive\Trabalho\Empresas\ORACLE\LBRAGA_LAP\Desktop\ProjetoXML\build\OracleTest\warn-OracleTest.txt
14032 INFO: Graph cross-reference written to D:\lbraga\OneDrive\Trabalho\Empresas\ORACLE\LBRAGA_LAP\Desktop\ProjetoXML\build\OracleTest\xref-OracleTest.html
14052 INFO: checking PYZ
14055 INFO: Building because toc changed
14055 INFO: Building PYZ (ZlibArchive) D:\lbraga\OneDrive\Trabalho\Empresas\ORACLE\LBRAGA_LAP\Desktop\ProjetoXML\build\OracleTest\PYZ-00.pyz
14525 INFO: Building PYZ (ZlibArchive) D:\lbraga\OneDrive\Trabalho\Empresas\ORACLE\LBRAGA_LAP\Desktop\ProjetoXML\build\OracleTest\PYZ-00.pyz completed successfully.
14574 INFO: checking PKG
14580 INFO: Building because toc changed
14581 INFO: Building PKG (CArchive) OracleTest.pkg
18965 INFO: Building PKG (CArchive) OracleTest.pkg completed successfully.
18968 INFO: Bootloader C:\Users\lbraga\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
18969 INFO: checking EXE
18970 INFO: Building because toc changed
18971 INFO: Building EXE from EXE-00.toc
18978 INFO: Copying bootloader EXE to D:\lbraga\OneDrive\Trabalho\Empresas\ORACLE\LBRAGA_LAP\Desktop\ProjetoXML\dist\OracleTest.exe
19014 INFO: Copying icon to EXE
19037 INFO: Copying 0 resources to EXE
19039 INFO: Embedding manifest in EXE
19062 INFO: Appending PKG archive to EXE
19177 INFO: Fixing EXE headers
19871 INFO: Building EXE from EXE-00.toc completed successfully.
```

Regards

**Comment by rokm** [comment]
> ```
> Traceback (most recent call last):
>   File "OracleTest.py", line 7, in <module>
>   File "oracledb\connection.py", line 1020, in connect
>   File "oracledb\connection.py", line 129, in __init__
>   File "src\\oracledb\\impl/thin/connection.pyx", line 76, in oracledb.thin_impl.ThinConnImpl.__init__
>   File "oracledb\errors.py", line 127, in _raise_err
> oracledb.exceptions.NotSupportedError: DPY-3016: python-oracledb thin mode cannot be used because the cryptography package is not installed
> [14080] Failed to execute script 'OracleTest' due to unhandled exception!
> ```

So `oracledb` is missing `cryptography`.

If you check the corresponding source

https://github.com/oracle/python-oracledb/blob/15886336398b26d1d37d0daf0e3ec3e1c992958f/src/oracledb/impl/thin/connection.pyx#L75C33-L76

https://github.com/oracle/python-oracledb/blob/5def438665990fd4eb60d5bfc666ced7fbf72ca5/src/oracledb/impl/thin/crypto.pyx#L32-L39

you will see that you need `cryptography` as a hidden import. Or, depending how how the imports in `cryptography` happen, `cryptography`, `cryptography.hazmat.primitives`,  `cryptography.hazmat.primitives.ciphers`, `cryptography.hazmat.primitives.asymmetric`, and  `cryptography.hazmat.primitives.kdf` might all need to be added to hidden imports (if in doubt, do a brute-force `--collect-submodules cryptography`).

As a side note, `oracledb` seems to have many cythonized extensions, so you'll probably need to accommodate each of them...

**Comment by luismariosb** [comment]
Hi Rokm,

Thanks a lot for your help and your explanation!! It worked like a charm.
I used the following command to compile it:

pyinstaller --hidden-import secrets --hidden-import getpass --hidden-import ssl --hidden-import uuid --collect-submodules cryptography --onefile OracleTest.py

Regards
