### ISSUE TITLE
AttributeError: mic_token

### ISSUE THREAD

**Issue by ZhexuanZhou** [pyinstaller/pyinstaller#8014]
## Description of the issue
I am trying to use pyinstaller to package with gssapi, then i got error which shows no module found ' gssapi.raw.cython_converters'. After that, I include 'gssapi.raw.cython_converters' in my hiddenimports like hiddenimports=['gssapi.raw.cython_converters', ...].

Now, I got the AttributeError: mic_token (the log is shown below). Could you give some hints to solve this problem?

***log***
```
/tmp/_MEIuTh2jc/dateutil/zoneinfo/__init__.py:26: UserWarning: I/O error(2): No such file or directory
Traceback (most recent call last):
  File "/home/ubt/wifi_ztc_server/src/schedule_push_kafka.py", line 44, in <module>
    from src.kafka_product_consummer.kafka_tool_for_schedule import kafkaHandler
  File "src/kafka_product_consummer/kafka_tool_for_schedule.py", line 22, in init src.kafka_product_consummer.kafka_tool_for_schedule
  File "modules/log_parse/kafkaProducter.py", line 10, in init modules.log_parse.kafkaProducter
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "kafka/__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "kafka/admin/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "kafka/admin/client.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "kafka/client_async.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "kafka/cluster.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "kafka/conn.py", line 79, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "gssapi/__init__.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "gssapi/raw/__init__.py", line 118, in <module>
  File "gssapi/raw/ext_iov_mic.pyx", line 31, in init gssapi.raw.ext_iov_mic
  File "enum.py", line 349, in __getattr__
AttributeError: mic_token
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(5.9.0)```
* Version of Python: 3.10
* Platform: Ubuntu 18
* How you installed Python: docker

**Comment by rokm** [comment]
`gssapi.raw` contains a bunch of cythonized extensions, so you'll probably want to just use `--collect-submodules gssapi.raw` to ensure all are properly collected.

Or, if you're building with spec file:
```python
from PyInstaller.utils.hooks import collect_submodules

hiddenimports = collect_submodules('gssapi.raw')
...
hiddenimports += [...]  # any other hidden imports you want to addd
...
a = Analysis(
   ...
   hiddenimports=hiddenimports,
   ...
)
```
