### ISSUE TITLE
Error with gradio and openai package (only these two are installed)

### ISSUE THREAD

**Issue by Mrw33554432** [pyinstaller/pyinstaller#8108]
## Description of the issue
The generated exe fail to run, check traceback below. Seems like it's caused by missing tmp file (fail to include or fail to generate).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.2.0```
* Version of Python: 3.11.5
* Platform: Windows (EN-US)
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
Not tried yet

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [v ] start with clean installation
  * [v] use the latest development version
  * [v ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [v ] Package your program in **--onedir mode**
  * [v ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [v ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
#Only openai and gradio is used in this project
```

### Stacktrace / full error message

```
dist>other.exe
Traceback (most recent call last):
  File "other.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\_simple_templates\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\_simple_templates\simpledropdown.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\components\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\components\annotated_image.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio_client\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio_client\client.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio_client\serializing.py", line 15, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI154602\\gradio_client\\types.json'
[28636] Failed to execute script 'other' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI154602\\gradio_client\\types.json'
> ```

The data files from `gradio_client` need to be collected. Add `--collect-data gradio_client` to your PyInstaller command.

**Comment by Mrw33554432** [comment]
> > ```
> > FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI154602\\gradio_client\\types.json'
> > ```
> 
> The data files from `gradio_client` need to be collected. Add `--collect-data gradio_client` to your PyInstaller command.

`pyinstaller --onefile other.py --collect-data gradio_client`
```
Traceback (most recent call last):
  File "other.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\_simple_templates\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\_simple_templates\simpledropdown.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\components\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\components\annotated_image.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\components\base.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\blocks.py", line 462, in <module>
  File "gradio\blocks_events.py", line 20, in __new__
  File "gradio\component_meta.py", line 86, in create_or_modify_pyi
  File "pathlib.py", line 1058, in read_text
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI15082\\gradio\\blocks_events.pyc'
```
Seems like still happens, but different file this time...
For `--onedir` option
```
Traceback (most recent call last):
  File "other.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\_simple_templates\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\_simple_templates\simpledropdown.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\components\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\components\annotated_image.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\components\base.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "gradio\blocks.py", line 462, in <module>
  File "gradio\blocks_events.py", line 20, in __new__
  File "gradio\component_meta.py", line 86, in create_or_modify_pyi
  File "pathlib.py", line 1058, in read_text
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Desktop\\openai_simple\\dist\\other\\_internal\\gradio\\blocks_events.pyc'
```

**Comment by Mrw33554432** [comment]
> > ```
> > FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI154602\\gradio_client\\types.json'
> > ```
> 
> The data files from `gradio_client` need to be collected. Add `--collect-data gradio_client` to your PyInstaller command.

I tried with the command `--collect-data gradio_client`, and an error persist, but on a different file. 
```
--onefile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI15082\\gradio\\blocks_events.pyc'
```
```
--onedir
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Desktop\\openai_simple\\dist\\other\\_internal\\gradio\\blocks_events.pyc'
```

**Comment by rokm** [comment]
Looks like `gradio` assumes that modules are always available on filesystem, and that they are in the source .py form ([here](https://github.com/gradio-app/gradio/blob/62d35c3d1b3e9d6e39bddbb32ff6b6cf9f1f7f72/gradio/component_meta.py#L86)). This makes it incompatible with PyInstaller's default way of collecting byte-compiled .pyc modules into executable-embedded PYZ archive.

The only way to accommodate that is to completely bypass PYZ and collect as source .py files. You will have to edit the generated spec file, and add the following to `Analysis`:

```python
a = Analysis(
    ...
    module_collection_mode={
        'gradio': 'py',  # Collect gradio package as source .py files
    },
)
```
and then build using the .spec file instead of running PyInstaller directly against the .py file.

**Comment by PillarsZhang** [comment]
Thanks to @rokm , I also added `--collect-data=gradio` (also essential) and now `gradio` launches normally. Here's a summary of the steps I followed.

---

**Tip: How to Package Gradio with PyInstaller?**

1. Generate a spec file (same as pyinstaller). [Reference](https://pyinstaller.org/en/stable/spec-files.html#using-spec-files)

   ```powershell
   pyi-makespec --collect-data=gradio_client --collect-data=gradio name.py
   ```

2. Completely bypass PYZ for gradio. [Reference](https://github.com/pyinstaller/pyinstaller/issues/8108#issuecomment-1814076207)

   ```python
   a = Analysis(
       ...
       module_collection_mode={
           'gradio': 'py',  # Collect gradio package as source .py files
       },
   )
   ```

3. Finally, generate the executable.

   ```powershell
   pyinstaller name.spec
   ```

**Comment by Mrw33554432** [comment]
> Looks like `gradio` assumes that modules are always available on filesystem, and that they are in the source .py form ([here](https://github.com/gradio-app/gradio/blob/62d35c3d1b3e9d6e39bddbb32ff6b6cf9f1f7f72/gradio/component_meta.py#L86)). This makes it with PyInstaller's default way of collecting byte-compiled .pyc modules into executable-embedded PYZ archive.
> 
> The only way to accommodate that is to completely bypass PYZ and collect as source .py files. You will have to edit the generated spec file, and add the following to `Analysis`:
> 
> ```python
> a = Analysis(
>     ...
>     module_collection_mode={
>         'gradio': 'py',  # Collect gradio package as source .py files
>     },
> )
> ```
> 
> and then build using the .spec file instead of running PyInstaller directly against the .py file.

Thanks, it solves the issue!
