### ISSUE TITLE
Libraries error when using pyinstaller

### ISSUE THREAD

**Issue by Rieidi** [pyinstaller/pyinstaller#8109]
Python --version (3.12.0)

my code: 
```
from plyer import notification
import time
import sys

notification.notify(
    title="Título da Notificação",
    message="Corpo da Notificação",
    timeout=10
)

# Adicione uma pausa para que a notificação tenha tempo de ser exibida
time.sleep(15)

# Aguarde o usuário pressionar Enter antes de sair
if getattr(sys, 'frozen', False):
    # Se estiver sendo executado como um executável, não aguarde Enter
    pass
else:
    input("Pressione Enter para sair...")

```
I've tried many things like using --hiden, trying to bring the library together in the .exe but I tested it in 3.11.0 and the same thing happened, it gave me this error, maybe it could be incompatibility
this error also occurs using win10toast and it is only when I use pyinstaller
Error: 
```
Traceback (most recent call last):
  File "plyer\utils.py", line 96, in _ensure_obj
ModuleNotFoundError: No module named 'plyer.platforms'
Traceback (most recent call last):
  File "DD.py", line 5, in <module>
  File "plyer\facades\notification.py", line 84, in notify
  File "plyer\facades\notification.py", line 93, in _notify
NotImplementedError: No usable implementation found!
[15632] Failed to execute script 'DD' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
Does a brute force `--collect-submodules=plyer` help?

**Comment by rokm** [comment]
Collecting submodules of `plyer.platforms.win` (`--collect-submodules plyer.platforms.win`) should probably suffice on Windows.

**Comment by Rieidi** [comment]
I CAN'T BELIEVE I WAS STUCK FOR 5 HOURS IN THE SAME ERROR FOR SUCH A SIMPLE SOLUTION. thank you...
@rokm @bwoodsend

**Comment by Rieidi** [comment]
. Solved
