### ISSUE TITLE
ModuleNotFoundError: No module named '_multiprocessing' -- when `_multiprocessing` is built-in

### ISSUE THREAD

**Issue by JonathonReinhart** [pyinstaller/pyinstaller#8111]
## Description of the issue
It appears that PyInstaller (perhaps `rthooks/pyi_rth_multiprocessing.py`) fails when `_multiprocessing` is built-in to Python, rather than a module.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.2.0```
* Version of Python: `Python 3.11.3+chromium.29` (from [CIPD](https://chromium.googlesource.com/infra/luci/luci-go/+/HEAD/cipd/README.md) package [`infra/3pp/tools/cpython3/linux-amd64/3ywmFUOaOaFOgNvtlG9w1GSzYXssvcYo2UvqnTfZsNsC`](https://chrome-infra-packages.appspot.com/p/infra/3pp/tools/cpython3/linux-amd64/+/3ywmFUOaOaFOgNvtlG9w1GSzYXssvcYo2UvqnTfZsNsC))
* Platform: Linux

### A minimal example program which shows the error

**`testapp.py`**
```python
print("Hello world")
import multiprocessing.connection
print("import ok:")
print(f"multiprocessing.connection: {multiprocessing.connection}")
print(f"multiprocessing.connection._multiprocessing: {multiprocessing.connection._multiprocessing}")
```

When run directly using Python from CIPD (in a virtualenv):
```console
$ python --version
Python 3.11.3+chromium.29

$ python testapp.py 
Hello world
import ok:
multiprocessing.connection: <module 'multiprocessing.connection' from '.../environment/cipd/packages/python311/lib/python3.11/multiprocessing/connection.py'>
multiprocessing.connection._multiprocessing: <module '_multiprocessing' (built-in)>
```

:point_right: Note that `_multiprocessing` is `(built-in)`. :point_left: 

When run directly using Python from Debian:
```console
$ which python3
/usr/bin/python3

$ python3 --version
Python 3.11.5

$ python3 testapp.py 
Hello world
import ok:
multiprocessing.connection: <module 'multiprocessing.connection' from '/usr/lib/python3.11/multiprocessing/connection.py'>
multiprocessing.connection._multiprocessing: <module '_multiprocessing' from '/usr/lib/python3.11/lib-dynload/_multiprocessing.cpython-311-x86_64-linux-gnu.so'>
```

:point_right: Note that `_multiprocessing` is a `.so` module. :point_left: 

### Stacktrace / full error message
Using Python from CIPD:
```
$ pyinstaller --onedir testapp.py
140 INFO: PyInstaller: 6.2.0
140 INFO: Python: 3.11.3+chromium.29
143 INFO: Platform: Linux-6.5.6-1rodete4-amd64-x86_64-with-glibc2.37
143 INFO: wrote .../pyi-test/testapp.spec
146 INFO: Extending PYTHONPATH with paths
['.../pyi-test']
255 INFO: checking Analysis
258 INFO: checking PYZ
314 INFO: checking PKG
315 INFO: Bootloader .../environment/pigweed-venv/lib/python3.11/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
315 INFO: checking EXE
315 INFO: checking COLLECT
315 INFO: Building COLLECT COLLECT-00.toc
327 INFO: Building COLLECT COLLECT-00.toc completed successfully.

$ ./dist/testapp/testapp 
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 107, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 95, in _pyi_rthook
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/popen_forkserver.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/forkserver.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/connection.py", line 21, in <module>
ModuleNotFoundError: No module named '_multiprocessing'
[382207] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

Using Python from Debian:
```
$ pyinstaller --onedir testapp.py 
180 INFO: PyInstaller: 6.2.0
180 INFO: Python: 3.11.5
182 INFO: Platform: Linux-6.5.6-1rodete4-amd64-x86_64-with-glibc2.37
182 INFO: wrote .../pyi-test/testapp.spec
184 INFO: Extending PYTHONPATH with paths
['.../pyi-test']
797 INFO: checking Analysis
800 INFO: Building because hookspath changed
800 INFO: Initializing module dependency graph...
801 INFO: Caching module graph hooks...
808 INFO: Analyzing base_library.zip ...
1425 INFO: Loading module hook 'hook-encodings.py' from '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks'...
1883 INFO: Loading module hook 'hook-heapq.py' from '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks'...
3181 INFO: Loading module hook 'hook-pickle.py' from '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks'...
4492 INFO: Caching module dependency graph...
4565 INFO: Running Analysis Analysis-00.toc
4565 INFO: Looking for Python shared library...
4614 INFO: Using Python shared library: /lib/x86_64-linux-gnu/libpython3.11.so.1.0
4614 INFO: Analyzing .../pyi-test/testapp.py
4646 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks'...
5071 INFO: Loading module hook 'hook-xml.py' from '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks'...
5316 INFO: Processing module hooks...
5548 INFO: Looking for ctypes DLLs
5560 INFO: Analyzing run-time hooks ...
5562 INFO: Including run-time hook '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
5563 INFO: Including run-time hook '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
5565 INFO: Processing pre-find module path hook _pyi_rth_utils from '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks/pre_find_module_path/hook-_pyi_rth_utils.py'.
5566 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks'...
5566 INFO: Including run-time hook '/usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
5572 INFO: Looking for dynamic libraries
5881 INFO: Warnings written to .../pyi-test/build/testapp/warn-testapp.txt
5893 INFO: Graph cross-reference written to .../pyi-test/build/testapp/xref-testapp.html
5902 INFO: checking PYZ
5903 INFO: Building because toc changed
5903 INFO: Building PYZ (ZlibArchive) .../pyi-test/build/testapp/PYZ-00.pyz
6156 INFO: Building PYZ (ZlibArchive) ../pyi-test/build/testapp/PYZ-00.pyz completed successfully.
6172 INFO: checking PKG
6173 INFO: Building because toc changed
6173 INFO: Building PKG (CArchive) testapp.pkg
6182 INFO: Building PKG (CArchive) testapp.pkg completed successfully.
6183 INFO: Bootloader /usr/local/google/home/jrreinhart/.local/lib/python3.11/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
6183 INFO: checking EXE
6183 INFO: Building because toc changed
6183 INFO: Building EXE from EXE-00.toc
6184 INFO: Copying bootloader EXE to .../pyi-test/build/testapp/testapp
6184 INFO: Appending PKG archive to custom ELF section in EXE
6193 INFO: Building EXE from EXE-00.toc completed successfully.
6194 INFO: checking COLLECT
6194 INFO: Building COLLECT COLLECT-00.toc
6215 INFO: Building COLLECT COLLECT-00.toc completed successfully.

$ ./dist/testapp/testapp 
Hello world
import ok:
multiprocessing.connection: <module 'multiprocessing.connection' from '.../pyi-test/dist/testapp/_internal/multiprocessing/connection.pyc'>
multiprocessing.connection._multiprocessing: <module '_multiprocessing' from '.../pyi-test/dist/testapp/_internal/lib-dynload/_multiprocessing.cpython-311-x86_64-linux-gnu.so'>
```

**Comment by rokm** [comment]
Can you open `build/testapp/Analysis-00.toc` for the CIPD-python build, and check where the python shared library was collected from? 

I suspect that the CIPD python doesn't actually have a shared library (and thus cannot work with PyInstaller), and instead we end up collecting shared library from the Debian python, and hence those supposed built-ins end up missing.

**Comment by JonathonReinhart** [comment]
> Can you open `build/testapp/Analysis-00.toc` for the CIPD-python build, and check where the python shared library was collected from?
> 
> I suspect that the CIPD python doesn't actually have a shared library (and thus cannot work with PyInstaller), and instead we end up collecting shared library from the Debian python, and hence those supposed built-ins end up missing.

Bingo.

```python
...
  ('xml.sax.xmlreader',
   '.../environment/cipd/packages/python311/lib/python3.11/xml/sax/xmlreader.py',
   'PYMODULE'),
  ('http.client',
   '.../environment/cipd/packages/python311/lib/python3.11/http/client.py',
   'PYMODULE')]
[('libpython3.11.so.1.0',
   '/lib/x86_64-linux-gnu/libpython3.11.so.1.0',
   'BINARY'),
  ('libz.so.1', '/lib/x86_64-linux-gnu/libz.so.1', 'BINARY'),
  ('libexpat.so.1', '/lib/x86_64-linux-gnu/libexpat.so.1', 'BINARY')],
```

```
$ ldd environment/cipd/packages/python311/bin/python3
        linux-vdso.so.1 (0x00007ffdfa9e9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f32ec31f000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f32ec31a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f32ec23b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f32ec236000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f32ec231000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f32ec04d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f32ec33e000)
```

Interestingly, my Debian `python3` doesn't seem to use `libpython3.11.so` either:
```
$ ldd /usr/bin/python3
        linux-vdso.so.1 (0x00007ffdecffc000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f662846f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6628450000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f6628425000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6628243000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6628568000)
```


Does this mean that PyInstaller has to search/hope that there is a `libpython.so`  which corresponds to the Python instance currently executing PyInstaller? (And this heuristic got it wrong here? because the CIPD & Debian versions happened to be the same?)

**Comment by bwoodsend** [comment]
> Interestingly, my Debian python3 doesn't seem to use libpython3.11.so either:

I think Debian does some weird thing where it creates the `libpython.so` but also statically links the `bin/python3` executable so that it doesn't use the `libpython.so`. It gives some tiny speed boost at the expense of making `bin/python3` several megabytes instead of a few hundred kilobytes.

> Does this mean that PyInstaller has to search/hope that there is a libpython.so which corresponds to the Python instance currently executing PyInstaller? (And this heuristic got it wrong here? because the CIPD & Debian versions happened to be the same?)

Not sure if the matching versions had a hand in this but yes to the rest of it.

**Comment by JonathonReinhart** [comment]
Hmm, well I'm not sure how an issue like this can be fixed unless PyInstaller makes a substantial change where it re-executes Python (using its own front-end executable?!)  using the "found" `libpython.so` to perform the analysis phase...

**Comment by bwoodsend** [comment]
*Fixing* this issue would just mean raising the [libpython.so not found](https://github.com/pyinstaller/pyinstaller/blob/2a5a687867ccda661b944623d7c10673cb26ef4e/PyInstaller/exceptions.py#L55-L64) error. PyInstaller's bootloaders need that library to run.

**Comment by rokm** [comment]
> Does this mean that PyInstaller has to search/hope that there is a `libpython.so` which corresponds to the Python instance currently executing PyInstaller? (And this heuristic got it wrong here? because the CIPD & Debian versions happened to be the same?)

Yes. We typically infer the location of `libpython3.x.so.1.0` from the environment's python executable (`sys.executable`). But like you observed, some python interpreters are actually not using the shared library, so we need additional heuristics to find that library in standard library locations.

In this case, CIPD python did not have shared lib at all - normally, this would raise the "libpython.so not found" error. But because system-provided python was exact match version-wise, its shared lib was picked up instead. I don't think we can come up with a reasonable heuristic to counter that, nor I think it is really worth it, since CIPD python is not compatible with PyInstaller anyway due to lack of the shared lib.

**Comment by bwoodsend** [comment]
The CIPD version is built with `--enable-py-version-override=3.11.3+chromium.29`. We could skip the heuristic search if `"chromium" in sys.version`? It feels very woolly...

**Comment by rokm** [comment]
I suppose we could try detecting known problematic python builds based on sys.version, and raise an error immediately; i.e., something along the lines of "This version of Python is not supported by PyInstaller." instead of the more generic "libpython.so not found" error.

**Comment by davetapley** [comment]
This also occurs with [`uv`](https://docs.astral.sh/uv/).

Per https://github.com/astral-sh/uv/issues/6812#issuecomment-2433282928 workaround is to tell `uv` to use system Python:
```
uv venv --python /usr/bin/python3 system-py-venv

source system-py-venv/bin/activate
uv add pyinstaller # and other dependencies
```

**Comment by rokm** [comment]
> This also occurs with [`uv`](https://docs.astral.sh/uv/).
> 
> Per [astral-sh/uv#6812 (comment)](https://github.com/astral-sh/uv/issues/6812#issuecomment-2433282928) workaround is to tell `uv` to use system Python:
> 
> ```
> uv venv --python /usr/bin/python3 system-py-venv
> 
> source system-py-venv/bin/activate
> uv add pyinstaller # and other dependencies
> ```

Hmm, I thought we fixed `uv` with #8850 and #8868. Is that not the case?

**Comment by davetapley** [comment]
> Hmm, I thought we fixed `uv` with #8850 and #8868. Is that not the case?

Not for me. Happy to get you repro / versions as needed.

One point of confusion: my CI (GitHub Actions) and dev environment (a Codespace) should be on identical Ubuntus and devcontainers, yet only Codespace needs the workaround 🤔

Both worked prior to my switching from pyenv to uv.

**Comment by rokm** [comment]
> Not for me. Happy to get you repro / versions as needed.

If you can provide a repro, it'd be much appreciated.

**Comment by davetapley** [comment]
@rokm 

```py
# repro.py
from multiprocessing import freeze_support, set_start_method

if __name__ == "__main__":
    set_start_method("spawn")  # for cross platform consistency

    freeze_support() # per https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#multi-processing

    print('hello world')
```

```
$ pyinstaller --onefile repro.py 
122 INFO: PyInstaller: 6.9.0, contrib hooks: 2025.4
123 INFO: Python: 3.12.2
124 INFO: Platform: Linux-6.8.0-1027-azure-x86_64-with-glibc2.39
124 INFO: Python environment: /workspaces/ng/.venv
124 INFO: wrote /workspaces/ng/repro.spec
125 INFO: Module search paths (PYTHONPATH):
['/home/vscode/.local/share/uv/python/cpython-3.12.2-linux-x86_64-gnu/lib/python312.zip',
 '/home/vscode/.local/share/uv/python/cpython-3.12.2-linux-x86_64-gnu/lib/python3.12',
 '/home/vscode/.local/share/uv/python/cpython-3.12.2-linux-x86_64-gnu/lib/python3.12/lib-dynload',
 '/workspaces/ng/.venv/lib/python3.12/site-packages',
 '/workspaces/ng/.venv/lib/python3.12/site-packages/setuptools/_vendor',
 '/workspaces/ng']
325 INFO: checking Analysis
325 INFO: Building Analysis because Analysis-00.toc is non existent
325 INFO: Running Analysis Analysis-00.toc
325 INFO: Target bytecode optimization level: 0
325 INFO: Initializing module dependency graph...
326 INFO: Caching module graph hooks...
333 INFO: Analyzing base_library.zip ...
913 INFO: Loading module hook 'hook-heapq.py' from '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks'...
990 INFO: Loading module hook 'hook-encodings.py' from '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks'...
2307 INFO: Loading module hook 'hook-pickle.py' from '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks'...
3369 INFO: Caching module dependency graph...
3446 INFO: Looking for Python shared library...
3471 INFO: Using Python shared library: /lib/x86_64-linux-gnu/libpython3.12.so.1.0
3471 INFO: Analyzing /workspaces/ng/repro.py
3503 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks'...
3655 INFO: Loading module hook 'hook-xml.py' from '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks'...
3882 INFO: Processing module hooks...
4083 INFO: Performing binary vs. data reclassification (2 entries)
4086 INFO: Looking for ctypes DLLs
4092 INFO: Analyzing run-time hooks ...
4093 INFO: Including run-time hook '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
4095 INFO: Including run-time hook '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
4097 INFO: Including run-time hook '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
4100 INFO: Processing pre-find module path hook _pyi_rth_utils from '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks/pre_find_module_path/hook-_pyi_rth_utils.py'.
4100 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from '/workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/hooks'...
4103 INFO: Looking for dynamic libraries
4120 INFO: Warnings written to /workspaces/ng/build/repro/warn-repro.txt
4131 INFO: Graph cross-reference written to /workspaces/ng/build/repro/xref-repro.html
4140 INFO: checking PYZ
4140 INFO: Building PYZ because PYZ-00.toc is non existent
4140 INFO: Building PYZ (ZlibArchive) /workspaces/ng/build/repro/PYZ-00.pyz
4508 INFO: Building PYZ (ZlibArchive) /workspaces/ng/build/repro/PYZ-00.pyz completed successfully.
4517 INFO: checking PKG
4517 INFO: Building PKG because PKG-00.toc is non existent
4517 INFO: Building PKG (CArchive) repro.pkg
8456 INFO: Building PKG (CArchive) repro.pkg completed successfully.
8457 INFO: Bootloader /workspaces/ng/.venv/lib/python3.12/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
8457 INFO: checking EXE
8457 INFO: Building EXE because EXE-00.toc is non existent
8457 INFO: Building EXE from EXE-00.toc
8457 INFO: Copying bootloader EXE to /workspaces/ng/dist/repro
8457 INFO: Appending PKG archive to custom ELF section in EXE
8476 INFO: Building EXE from EXE-00.toc completed successfully.
```

```
$ dist/repro
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 107, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 95, in _pyi_rthook
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/popen_forkserver.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/forkserver.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/connection.py", line 22, in <module>
ModuleNotFoundError: No module named '_multiprocessing'
[57079] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

**Comment by rokm** [comment]
> `122 INFO: PyInstaller: 6.9.0, contrib hooks: 2025.4`

https://github.com/pyinstaller/pyinstaller/pull/8850 and https://github.com/pyinstaller/pyinstaller/pull/8868 are available from PyInstaller 6.11.1 on...

**Comment by davetapley** [comment]
@rokm well that's embarrassing. Sorry for wasting your time. Those fixes work ✅
