### ISSUE TITLE
Missing to include reportlab's Vera.ttf

### ISSUE THREAD

**Issue by legends2k** [pyinstaller/pyinstaller#8135]
Packaging an application with `z3c.rml2pdf` and `preppy` (dependency) modules (both in turn depending on `reportlab`) I noticed a warning:

```
$ pyinstaller --name mERP --hidden-import reportlab --noupx start.py
1033 INFO: PyInstaller: 6.2.0
1033 INFO: Python: 3.8.18
1099 INFO: Platform: Windows-10-10.0.19045-SP0
1166 INFO: wrote D:\Work\mERP\mERP.spec
1150 INFO: Extending PYTHONPATH with paths
['D:\\Work\\mERP']
214 WARNING: discover_hook_directories: Failed to process hook entry point 'EntryPoint(name='hook-dirs', value='freetype.__pyinstaller:get_hook_dirs', group='pyinstaller40')': ModuleNotFoundError: No module named 'freetype.__pyinstaller'
2116 INFO: checking Analysis
2183 INFO: Building because D:\Work\mERP\merp\__init__.py changed
2183 INFO: Initializing module dependency graph...
...
...
71683 INFO: Building EXE from EXE-00.toc completed successfully.
71719 INFO: checking COLLECT
151150 INFO: Building COLLECT COLLECT-00.toc
152367 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

Ignoring it, and running led to

```
Traceback (most recent call last):
  File "reportlab\lib\utils.py", line 523, in open_for_read
  File "reportlab\lib\utils.py", line 463, in open_for_read_by_name
FileNotFoundError: [Errno 2] No such file or directory: 'Vera.ttf'
reportlab.pdfbase.ttfonts.TTFError: Can't open file "Vera.ttf"
```

**Question:** Does reportlab need a hook to specify these data files?  Or if I fix the hooks warning above PyInstaller will automatically pick-up these files?

## Context

* Output of `pyinstaller --version`: ```6.2.0```
* Version of Python: `3.8.18`
* Platform: Windows 10 (en-us)
* How you installed Python?  Unzip embedded Python 3.8 package
* Did you also try this on another platform? Does it work there?  No, didn't try it.
* Try the latest development version, using the following command: Yes, tried it too.
* follow *all* the instructions in our "If Things Go Wrong" Guide?  For the most part.  I see no hooks for reportlab.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

## A minimal example program which shows the error

```
from z3c.rml import rml2pdf
import preppy

def main():
    template = preppy.getModule('template.rml')
    rml = template.getOutput({}, quoteFunc=preppy.stdQuote)
    pdfBytes = rml2pdf.parseString(rml)
    with open('test.pdf', 'wb') as f:
        f.write(pdfBytes.getbuffer())

main()
```

## Full Run Log

```
[3244] PyInstaller Bootloader 6.x
[3244] LOADER: executable is D:\Work\mERP\dist\mERP\mERP.exe
[3244] LOADER: _MEIPASS2 is not set
[3244] LOADER: archivename is D:\Work\mERP\dist\mERP\mERP.exe
[3244] LOADER: Cookie found at offset 0x550686
[3244] LOADER: No need to extract files to run; setting extractionpath to homepath
[3244] LOADER: SetDllDirectory(D:\Work\mERP\dist\mERP\_internal)
[3244] LOADER: Already in the child - running user's code.
[3244] LOADER: Python library: D:\Work\mERP\dist\mERP\_internal\python38.dll
[3244] LOADER: Loaded functions from Python library.
[3244] LOADER: Pre-initializing embedded python interpreter...
[3244] LOADER: Creating PyConfig structure...
[3244] LOADER: Initializing interpreter configuration...
[3244] LOADER: Setting program name...
[3244] LOADER: Setting python home path...
[3244] LOADER: Setting module search paths...
[3244] LOADER: Setting sys.argv...
[3244] LOADER: Applying run-time options...
[3244] LOADER: Starting embedded python interpreter...
[3244] LOADER: setting sys._MEIPASS
[3244] LOADER: importing modules from CArchive
[3244] LOADER: extracted struct
[3244] LOADER: running unmarshalled code object for struct...
[3244] LOADER: extracted pyimod01_archive
[3244] LOADER: running unmarshalled code object for pyimod01_archive...
[3244] LOADER: extracted pyimod02_importers
[3244] LOADER: running unmarshalled code object for pyimod02_importers...
[3244] LOADER: extracted pyimod03_ctypes
[3244] LOADER: running unmarshalled code object for pyimod03_ctypes...
[3244] LOADER: extracted pyimod04_pywin32
[3244] LOADER: running unmarshalled code object for pyimod04_pywin32...
[3244] LOADER: Installing PYZ archive with Python modules.
[3244] LOADER: PYZ archive: PYZ-00.pyz
[3244] LOADER: Running pyiboot01_bootstrap.py
[3244] LOADER: Running pyi_rth_inspect.py
[3244] LOADER: Running pyi_rth_pkgutil.py
[3244] LOADER: Running pyi_rth_multiprocessing.py
[3244] LOADER: Running pyi_rth_pkgres.py
[3244] LOADER: Running pyi_rth_pyside2.py
[3244] LOADER: Running start.py
Traceback (most recent call last):
  File "reportlab\lib\utils.py", line 523, in open_for_read
  File "reportlab\lib\utils.py", line 463, in open_for_read_by_name
FileNotFoundError: [Errno 2] No such file or directory: 'Vera.ttf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reportlab\lib\utils.py", line 530, in open_for_read
  File "reportlab\lib\utils.py", line 476, in rlUrlRead
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 509, in open
  File "urllib\request.py", line 328, in __init__
  File "urllib\request.py", line 354, in full_url
  File "urllib\request.py", line 383, in _parse
ValueError: unknown url type: 'Vera.ttf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reportlab\pdfbase\ttfonts.py", line 151, in TTFOpenFile
  File "reportlab\lib\utils.py", line 534, in open_for_read
  File "reportlab\lib\utils.py", line 532, in open_for_read
OSError: Cannot open resource "Vera.ttf"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "merp\__main__.py", line 12, in <module>
  File "C:\Users\sundaram\AppData\Local\Temp\embedded.g2deixmf.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "merp\form_raw_materials.py", line 10, in <module>
  File "C:\Users\sundaram\AppData\Local\Temp\embedded.g2deixmf.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "merp\utils\ui_utils.py", line 9, in <module>
  File "C:\Users\sundaram\AppData\Local\Temp\embedded.g2deixmf.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "z3c\rml\__init__.py", line 5, in <module>
  File "C:\Users\sundaram\AppData\Local\Temp\embedded.g2deixmf.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "z3c\rml\rlfix.py", line 29, in <module>
  File "C:\Users\sundaram\AppData\Local\Temp\embedded.g2deixmf.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "reportlab\graphics\testshapes.py", line 71, in <module>
  File "reportlab\graphics\testshapes.py", line 66, in resetFonts
  File "reportlab\graphics\testshapes.py", line 33, in _setup
  File "reportlab\pdfbase\ttfonts.py", line 1178, in __init__
  File "reportlab\pdfbase\ttfonts.py", line 1072, in __init__
  File "reportlab\pdfbase\ttfonts.py", line 439, in __init__
  File "reportlab\pdfbase\ttfonts.py", line 175, in __init__
  File "reportlab\pdfbase\ttfonts.py", line 251, in readFile
  File "reportlab\pdfbase\ttfonts.py", line 161, in TTFOpenFile
reportlab.pdfbase.ttfonts.TTFError: Can't open file "Vera.ttf"
[3244] Failed to execute script 'start' due to unhandled exception!
[3244] LOADER: ERROR.
[3244] LOADER: Manually flushing stdout and stderr
[3244] LOADER: Cleaning up Python interpreter.
```

**Comment by rokm** [comment]
> Packaging an application with z3c.rml2pdf and preppy (dependency) modules (both in turn depending on reportlab) I noticed a warning:

> ```214 WARNING: discover_hook_directories: Failed to process hook entry point 'EntryPoint(name='hook-dirs', value='freetype.__pyinstaller:get_hook_dirs', group='pyinstaller40')': ModuleNotFoundError: No module named 'freetype.__pyinstaller'```

This warning comes from `freetype` package declaring the entry-point for PyInstaller hook, but not actually providing one for whatever reason. This doesn't have anything to do with missing fonts, though.

> Question: Does reportlab need a hook to specify these data files? Or if I fix the hooks warning above PyInstaller will automatically pick-up these files?

Yes. PyInstaller does not automatically collect non-python files (arbitrary data files) from packages. In this case, the fonts are shipped with `reportlab` package, so a hook for that package would need to be created to collect them automatically. 

Or, you can add `--collect-data reportlab` to your PyInstaller command to perform the equivalent collection in the generated .spec file.

---

Once you have fonts collected, `freetype` will crash with 
``` 
...
  File "freetype\raw.py", line 52, in <module>
RuntimeError: Freetype library not found
```

because its DLL was not collected. This is probably the missing hook was supposed to address. But again, you can add `--collect-binaries freetype` to your PyInstaller command to take care of it.

**Comment by legends2k** [comment]
@rokm Thanks a ton!  That fixes my build and it works :)

However, if there's a possibility, I'd like to contribute.  This would be a stumbling block for someone using reportlab or freetype.  Can I provide hooks for freetype or reportlab?  Or are the users using these dependencies supposed to pass these flags properly by design?

> This warning comes from freetype package declaring the entry-point for PyInstaller hook, but not actually providing one for whatever reason.

I can debug, where do I look.  `pip list` does list `freetype-py` and `pyinstaller-hooks-contrib`.

**Comment by rokm** [comment]
> Or are the users using these dependencies supposed to pass these flags properly by design?

If no hook exists for the package, the user is supposed to pass the collection flags themselves. The hook can be provided either by user (e.g., included with their program, and passed to PyInstaller via `--additional-hooks-dir` flag durin build), by the package itself (like the `freetype` is trying to), or by the [`pyinstaller-hooks-contrib` ](https://github.com/pyinstaller/pyinstaller-hooks-contrib) package (which actually provides most of the hooks).

> However, if there's a possibility, I'd like to contribute. This would be a stumbling block for someone using reportlab or freetype. Can I provide hooks for freetype or reportlab?

You can submit the hooks for `reportlab` and `freetype` to [`pyinstaller-hooks-contrib` ](https://github.com/pyinstaller/pyinstaller-hooks-contrib), along with basic [test](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/tests/test_libraries.py) for the package (usually an import test suffices).

>>  This warning comes from freetype package declaring the entry-point for PyInstaller hook, but not actually providing one for whatever reason.

> I can debug, where do I look. `pip list` does list `freetype-py` and `pyinstaller-hooks-contrib`.

You should look at `freetype-py` package repository. The entry-points are declared [here](https://github.com/rougier/freetype-py/blob/83bf5d32cd296795bb790f4fa89fc85c78f50630/setup.py#L133-L134), and the referenced module with hooks is [here](https://github.com/rougier/freetype-py/tree/master/freetype/__pyinstaller), but this module is not included in the PyPI wheel. That's the part that needs to be fixed.

**Comment by legends2k** [comment]
I couldn't get around to doing this earlier but looks like you'd already done it, thanks again! 🙏🏾
