### ISSUE TITLE
ModuleNotFoundError: No module named 'sspilib.raw._text' when importing the "requests_ntlm" library

### ISSUE THREAD

**Issue by Yoabites** [pyinstaller/pyinstaller#8136]
## Description of the issue
When the application is packed with pyinstaller and the program includes the "requests_ntlm" library, The app gets an error that does not allow to run the program. The program runs without packaging it just fine, and it does run when packaged and "requests_ntlm" is not imported.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.8.0```
* Version of Python: e.g. 3.11.4
* Platform: Windows 11 Home 10.0.22621 Build 22621, Locale United States
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Tried it with Windows 10 (A Corporate image) .Does it work there? It does not

* Tried dev version, issue has not been resolved.

* Instructions have been followed

### Made sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [Done] start with clean installation
  * [Done] use the latest development version
  * [Done] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [Done] Package your program in **--onedir mode**
  * [Done] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [Done] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
from requests import Session
from requests_ntlm import HttpNtlmAuth

def main():
    print("Print just for the sake of it")
if __name__ == "__main__":
    main();
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "testImport.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "requests_ntlm.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "spnego\__init__.py", line 26, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "spnego\auth.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "spnego\_negotiate.py", line 31, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "spnego\_sspi.py", line 39, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "sspilib\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "sspilib\raw\__init__.py", line 8, in <module>
  File "src\\sspilib\\raw\\_context_attributes.pyx", line 1, in init sspilib.raw._context_attributes
  File "src\\sspilib\\raw\\_security_context.pyx", line 1, in init sspilib.raw._security_context
  File "src\\sspilib\\raw\\_credential.pyx", line 1, in init sspilib.raw._credential
ModuleNotFoundError: No module named 'sspilib.raw._text'
[28756] Failed to execute script 'testProgram' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
`--hiddenimport=sspilib.raw._text`?

**Comment by rokm** [comment]
Or perhaps even a `--collect-submodules=sspilib`, since `sspilib.raw` seems to contain several cythonized modules.

**Comment by the-citto** [comment]
had the same problem and `--collect-submodules=sspilib` fixed it, thanks @rokm

**Comment by jgerardoc** [comment]
I had the same problem, and confirm `--collect-submodules=sspilib` also fixed it, thaks all

**Comment by cheathamklb** [comment]
I am having the same issue. Could you please help me? I would like to run this in jupyter notebook before I create a PROD. TY
