### ISSUE TITLE
libnvrtc.so.12 file not found

### ISSUE THREAD

**Issue by rafael-wampfler** [pyinstaller/pyinstaller#8156]
Hello

I'm using v5.13.0 and Python 3.10 to load a Llama-2 model on a Flask server. For this I'm using the following server.spec file:

```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata
from PyInstaller.utils.hooks import collect_submodules  # Added
import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)

datas = []
datas += collect_data_files('torch')
datas += copy_metadata('torch')
datas += copy_metadata('tqdm')
datas += copy_metadata('regex')
datas += copy_metadata('requests')
datas += copy_metadata('packaging')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')
datas += copy_metadata('importlib_metadata')
datas += copy_metadata('deepspeed')
datas += copy_metadata('huggingface-hub')
datas += copy_metadata('safetensors')
datas += copy_metadata('pyyaml')
datas += copy_metadata('sentencepiece')
datas += copy_metadata('datasets')
datas += copy_metadata('optimum')
datas += copy_metadata('transformers')
datas += copy_metadata('auto_gptq')
datas += copy_metadata('triton')
datas += collect_data_files('ninja')
datas += collect_data_files('deepspeed')
datas += collect_data_files('datasets')
datas += collect_data_files('optimum')
datas += collect_data_files('transformers')
datas += collect_data_files('auto_gptq')
datas += collect_data_files('triton')


# Added
hiddenimports = []
hiddenimports = collect_submodules('deepspeed') + collect_submodules('datasets') + collect_submodules('optimum') + collect_submodules('transformers') + collect_submodules('auto_gptq')
hiddenimports.append('triton._C.libtriton')
hiddenimports.append('tiktoken_ext')
hiddenimports.append('tiktoken_ext.openai_public')

block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports, 
    #hiddenimports=['pytorch', 'deepspeed'], NOTE: pytorch is not a valid module name, and deepspeed is included in collect_submodules output
    hookspath=['pyinstaller-hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    # Added
    module_collection_mode={
        "deepspeed": "pyz+py",
        "datasets": "pyz+py",
        "optimum": "pyz+py",
        "transformers": "pyz+py",
        "auto_gptq": "pyz+py",
        "triton": "py"
    },
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

Possible lines of code to reproduce this are:

```
import transformers
from transformers import AutoModelForCausalLM
tokenizer = transformers.AutoTokenizer.from_pretrained("TheBloke/Llama-2-13B-chat-GPTQ", truncation_side='left', use_fast=False)
model = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-13B-chat-GPTQ", device_map="auto", trust_remote_code=True, revision="main")
```

During runtime I'm getting the following error when trying to do an inference on the Llama-2 model:

```
Traceback (most recent call last):
  File "flask/app.py", line 2190, in wsgi_app
  File "flask/app.py", line 1486, in full_dispatch_request
  File "flask/app.py", line 1484, in full_dispatch_request
  File "flask/app.py", line 1469, in dispatch_request
  File "server/main.py", line 259, in chatbot_response
  File "gpt_j/model.py", line 175, in generate_response
  File "torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "transformers/generation/utils.py", line 1719, in generate
    return self.sample(
  File "transformers/generation/utils.py", line 2856, in sample
    next_tokens.tile(eos_token_id_tensor.shape[0], 1).ne(eos_token_id_tensor.unsqueeze(1)).prod(dim=0)
RuntimeError: Error in dlopen for library libnvrtc.so.12and libnvrtc-b51b459d.so.12
```

It looks like `libnvrtc-b51b459d.so.12` and `libnvrtc.so.12` are not found. How can I include them or point to them in the local system?

Thank you so much for your help!

**Comment by rokm** [comment]
> How can I include them or point to them in the local system?

https://pyinstaller.org/en/stable/spec-files.html#adding-binary-files

If `torch` is installed via pip and uses `nvidia-*` wheels for CUDA libraries, you can also try to use:

```python
from PyInstaller.utils.hooks import collect_dynamic_libs
binaries = collect_dynamic_libs('nvidia.cuda_nvrtc', search_patterns=['lib*.so.*'])
```

(the default search patterns of `collect_dynamic_libs` do not pick up versioned .so files...).

**Comment by rafael-wampfler** [comment]
This solved my problem, thank you very much.
