### ISSUE TITLE
--noconsole not working on Windows

### ISSUE THREAD

**Issue by MikeTheGreat** [pyinstaller/pyinstaller#8177]
Hello!

I've got a minimal Python program that PyInstaller is able to make into a --onedir application just fine on it's own, but when I add the --noconsole option PyInstaller fails with a message about "a virus or potentially unwanted software".

Here's the minimal Python program:

`pass`

(Yup, that's it - it's a file named Test.py with nothing in it but the word `pass ` 😁 )

- I just installed Python 3.12.1 from Python.org (so - the latest version, as of when I wrote this bug report)
- I just installed PyInstaller 6.3.0 (again, latest as of Dec 20, 2023 - it's what `pip install pyinstaller` picked for me).  
    - I know I should use a venv but for simplicity I just installed it using the system Python.  pip said it couldn't install into my write-protected Python install dir so it installed it into my user account instead.  
- I'm running Windows 10 (`ver `says `Microsoft Windows [Version 10.0.22621.2861]`)

When I run the following I get no errors, and can double-click on the .exe file (it doesn't do much, obviously, but there's no errors)
`C:\Users\michp\AppData\Roaming\Python\Python312\Scripts\pyinstaller.exe Test.py`

When I run the following, I get the error listed below (note that the only difference is the -`-noconsole` option)
`C:\Users\michp\AppData\Roaming\Python\Python312\Scripts\pyinstaller.exe --noconsole Test.py`

Error Message:
```
251 INFO: PyInstaller: 6.3.0
251 INFO: Python: 3.12.1
279 INFO: Platform: Windows-11-10.0.22621-SP0
279 INFO: wrote C:\MIkesStuff\Pers\Dropbox\Personal\Tech\OpenInNeoVim\Test.spec
279 INFO: Extending PYTHONPATH with paths
['C:\\MIkesStuff\\Pers\\Dropbox\\Personal\\Tech\\OpenInNeoVim']
530 INFO: checking Analysis
546 INFO: checking PYZ
562 INFO: checking PKG
562 INFO: Bootloader C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
562 INFO: checking EXE
562 INFO: Rebuilding EXE-00.toc because Test.exe missing
562 INFO: Building EXE from EXE-00.toc
562 INFO: Copying bootloader EXE to C:\MIkesStuff\Pers\Dropbox\Personal\Tech\OpenInNeoVim\build\Test\Test.exe
638 WARNING: Execution of 'remove_all_resources' failed on attempt #1 / 20: error(110, 'EndUpdateResourceW', 'The system cannot open the device or file specified.'). Retrying in 0.05 second(s)...
706 WARNING: Execution of 'remove_all_resources' failed on attempt #2 / 20: error(110, 'EndUpdateResourceW', 'The system cannot open the device or file specified.'). Retrying in 0.06 second(s)...
767 INFO: Copying icon to EXE
Traceback (most recent call last):
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\win32ctypes\pywin32\win32api.py", line 209, in BeginUpdateResource
    return _resource._BeginUpdateResource(filename, delete)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\win32ctypes\core\ctypes\_util.py", line 39, in check_null
    raise make_error(function, function_name)
OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\michp\AppData\Roaming\Python\Python312\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\__main__.py", line 214, in _console_script_run
    run()
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\__main__.py", line 198, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\building\build_main.py", line 1071, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\building\build_main.py", line 1011, in build
    exec(code, spec_namespace)
  File "C:\MIkesStuff\Pers\Dropbox\Personal\Tech\OpenInNeoVim\Test.spec", line 18, in <module>
    exe = EXE(
          ^^^^
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\building\api.py", line 628, in __init__
    self.__postinit__()
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\building\api.py", line 741, in assemble
    self._retry_operation(icon.CopyIcons, build_name, self.icon)
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\building\api.py", line 1003, in _retry_operation
    return func(*args)
           ^^^^^^^^^^^
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\utils\win32\icon.py", line 209, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\PyInstaller\utils\win32\icon.py", line 143, in CopyIcons_FromIco
    hdst = win32api.BeginUpdateResource(dstpath, 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\win32ctypes\pywin32\win32api.py", line 208, in BeginUpdateResource
    with _pywin32error():
  File "C:\Program Files\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\michp\AppData\Roaming\Python\Python312\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (225, 'BeginUpdateResourceW', 'Operation did not complete successfully because the file contains a virus or potentially unwanted software.')
```

It seems pretty reasonable that a Python program that does nothing other than 'pass' qualifies as 'unwanted software' 😂.
Still, I'd still like to have PyInstaller generate the .exe for me, without popping a console onto the screen

**Comment by rokm** [comment]
> It seems pretty reasonable that a Python program that does nothing other than 'pass' qualifies as 'unwanted software' 😂.

The problem is that your anti-virus program is picking on the pre-built bootloader executable that is shipped with PyInstaller. Which is the same pre-built executable that everyone using PyInstaller uses (unless they recompile it from source), including malware authors (and I would wager a guess that noconsole/windowed bootloader is more often used for that than the console variant).

> Still, I'd still like to have PyInstaller generate the .exe for me, without popping a console onto the screen

There's nothing we can do about this.

Try rebuilding the bootloader yourself (although #8164 indicates that even that might not help anymore), disable your AV, and/or report the false positive to your AV vendor.
