### ISSUE TITLE
PyInstaller does not include a pre-compiled bootloader win11

### ISSUE THREAD

**Issue by Kralg** [pyinstaller/pyinstaller#8183]
Hi,
I am using win11 and 3.11. I am trying to run auto-py-to-exe and I am getting error:
An error occurred while packaging
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\auto_py_to_exe\packaging.py", line 132, in package
    run_pyinstaller()
  File "C:\Python\Lib\site-packages\PyInstaller\__main__.py", line 198, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python\Lib\site-packages\PyInstaller\__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python\Lib\site-packages\PyInstaller\building\build_main.py", line 1071, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Python\Lib\site-packages\PyInstaller\building\build_main.py", line 1011, in build
    exec(code, spec_namespace)
  File "C:\Users\algis\AppData\Local\Temp\tmphcccg2r3\E36_mqtt_client_gui.spec", line 18, in <module>
    exe = EXE(
          ^^^^
  File "C:\Python\Lib\site-packages\PyInstaller\building\api.py", line 628, in __init__
    self.__postinit__()
  File "C:\Python\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Python\Lib\site-packages\PyInstaller\building\api.py", line 727, in assemble
    raise SystemExit(_MISSING_BOOTLOADER_ERRORMSG)
SystemExit: Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see

I wonder is this normal that there is no bootloader for Win11 ?

**Comment by rokm** [comment]
> I wonder is this normal that there is no bootloader for Win11 ?

It is not - it was likely removed by your anti-virus program.

**Comment by Kralg** [comment]
Mm I see, can you suggest where should it be placed to?

**Comment by rokm** [comment]
The bootloaders should be in `C:\Python\Lib\site-packages\PyInstaller\bootloader`. For x64 system, there should be `Windows-64bit-intel` directory in there, and it should contain four files: `run.exe`, `runw.exe`, `run_d.exe` and `runw_d.exe`.

**Comment by Kralg** [comment]
Thank you. I actually can see that I have but only runw is missing: 
![image](https://github.com/pyinstaller/pyinstaller/assets/26962388/4b075665-8437-47fa-bf28-5f919c8f4ddd)

**Comment by rokm** [comment]
Yeah, I kind of expected that `runw.exe` is the missing one - that's the windowed/noconsole variant, and the most likely target of the anti-virus programs (the malware packed with PyInstaller is probably also using noconsole mode to stay hidden, so it uses that bootloader variant).

**Comment by Kralg** [comment]
Mm, can you suggest what way is best to get runw.exe?

**Comment by rokm** [comment]
Download PyInstaller source, rebuild the bootloader executables yourself, and then install PyInstaller with custom rebuilt bootloaders. And hope that the executables will be different enough (different toolchain) to have AV let them be. Otherwise, disable the AV and reinstall PyInstaller.
