### ISSUE TITLE
Operation did not complete successfully because the file contains a virus or potentially unwanted software.

### ISSUE THREAD

**Issue by enXov** [pyinstaller/pyinstaller#8193]
To put it simply, I am making a system like automatic update in a python project, something like clickonce in csharp works fine, but when converting the project to .exe format, after 14285 INFO: Copying icon to EXE, I get an error like this

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\win32ctypes\pywin32\win32api.py", line 209, in BeginUpdateResource
    return _resource._BeginUpdateResource(filename, delete)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 39, in check_null
    raise make_error(function, function_name)
OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 214, in _console_script_run
    run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 198, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 1071, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 1011, in build
    exec(code, spec_namespace)
  File "C:\Users\xxx\Desktop\xxx\xxx\xxx.spec", line 18, in <module>
    exe = EXE(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\api.py", line 628, in __init__
    self.__postinit__()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\api.py", line 741, in assemble
    self._retry_operation(icon.CopyIcons, build_name, self.icon)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\api.py", line 1003, in _retry_operation
    return func(*args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\utils\win32\icon.py", line 209, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\utils\win32\icon.py", line 143, in CopyIcons_FromIco
    hdst = win32api.BeginUpdateResource(dstpath, 0)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\win32ctypes\pywin32\win32api.py", line 209, in BeginUpdateResource
    return _resource._BeginUpdateResource(filename, delete)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (225, 'BeginUpdateResourceW', 'Operation did not complete successfully because the file contains a virus or potentially unwanted software.')

I am using python version 3.9 and my pyinstaller version is the latest version

and I think the error is most likely that the code is giving the unreliable software error because it connects to the server and downloads the new version of the application from there, but I don't know how to solve it

The command I typed when converting to exe format
pyinstaller main.py --onefile --noconsole --windowed --add-data "C:/Users/xxx/Desktop/xxx/xxx;." --add-data "C:/Users/xxx/Desktop/xxx/xxx;xxx/" --hidden-import urllib.request --hidden-import requests --icon "C:\Users\xxx\Desktop\xxx\Icons\SetUp\Checker\Update Checker.ico" --name "Update Checker"

**Comment by enXov** [comment]
Update afterwards:
Conceivable solutions and solutions available on the internet:
Go to the error in the code and fix it ❌ because the code is dynamically written, you can't find that try exception, you can remove it but it won't recognize other errors this time
Turning off windows defender ❌ this doesn't work either because it automatically deletes this exe file because I'm going to throw it to a different computer and windows defender is turned on on those computers 
Actually, the reason I wrote here is that maybe there is a parameter like --safe-mode or --disable-virus-scan in pyinstaller and I don't know it, otherwise there seems to be no other solution, maybe I should switch to older versions of pyinstaller

**Comment by bwoodsend** [comment]
>  Actually, the reason I wrote here is that maybe there is a parameter like --safe-mode or --disable-virus-scan in pyinstaller and I don't know it, otherwise there seems to be no other solution, maybe I should switch to older versions of pyinstaller

How can you possibly read that template and still think that?

**Comment by divisa-developer** [comment]
I've run into this issue too, Is there really no workaroud for this?

**Comment by bwoodsend** [comment]
See [here](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md#reporting-false-positives-to-av-vendors) for what you're supposed to do. I've had this conversation so many times. I don't want have it again.

**Comment by divisa-developer** [comment]
> See [here](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md#reporting-false-positives-to-av-vendors) for what you're supposed to do. I've had this conversation so many times. I don't want have it again.

Thank you kindly, I will look into it and sorry for commenting on a closed issue.

**Comment by WAvdBeek** [comment]
disabling the virus scanner did work for me
