### ISSUE TITLE
ModuleNotFoundError: No module named 'asyncio.base_events'

### ISSUE THREAD

**Issue by hyunr01** [pyinstaller/pyinstaller#8204]
## Description of the issue
I'm trying to compile my .py file into a .exe file, but I keep encountering the ModuleNotFoundError for 'asyncio.base_events' even after trying multiple fixes such as adding "from asyncio import base_events" to the base code file, adding --hidden-import=asyncio, --hidden-import=asyncio.base_events, adding the --path to the asyncio.base_events directory, etc.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.3.0```
* Version of Python:  3.11
* Platform:  Windows 11
* How you installed Python:  python.org/downloads
* Did you also try this on another platform? Does it work there? -> Haven't tried

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

### A minimal example program which shows the error

```
Not sure if this is possible as my program taps into multiple API modules (pyupbit/unicorn-binance) that uses websockets to receive/send data.

```

### Stacktrace / full error message

```
Traceback (most recent call last):
    File "test_auto_gui.py", line 11, in <module>
    File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
    File "pyupbit\__init__.py", line 5, in <module>
    File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
    File "pyupbit\websocket_api.py", line 2, in <module>
    File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
    File "asyncio\__init__.py", line 21, in <module>
ModuleNotFoundError: No module named 'asyncio.base_events'
[23624] Failed to execute script 'test_auto_gui' due to unhandled exception!
```

**Comment by 17864219845** [comment]
解决了嘛，江湖救急啊。想问问怎么解决的。

**Comment by 17864219845** [comment]
Dear friend, can you tell me how to solve it
