### ISSUE TITLE
Exe failed to execute when import seedir

### ISSUE THREAD

**Issue by H1DDENADM1N** [pyinstaller/pyinstaller#8205]
## Description of the issue
I wrote a `treeseedir.py`, and it runs normally with `python .\treeseedir.py`, but the exe generated by pyinstaller has no effect. It only flashes the command line window and cannot create files or copy. I hope you can Help.
### Context information (for bug reports)

Traceback

```
Traceback (most recent call last):
  File "treeseedir.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "seedir\__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "seedir\realdir.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "seedir\folderstructure.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "seedir\printing.py", line 81, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sudoo\\AppData\\Local\\Temp\\_MEI208002\\seedir\\words.txt'
[23416] Failed to execute script 'treeseedir' due to unhandled exception!

```

treeseedir.py

```
import os
import pyperclip
import seedir

def my_style(item):
    outdict = {}
    # get the extension
    ext = os.path.splitext(item)[1]
    if ext in ('.txt', '.md', '.doc'):
        outdict['filestart'] = '✏️'
    elif ext in ('.png', '.jpg', '.gif'):
        outdict['filestart'] = '🖼️'
    elif ext == '.mp3':
        outdict['filestart'] = '🎵'
    else:
    # If none of them match
        outdict['filestart'] = '📄'

    parent = os.path.basename(os.path.dirname(item))
    if parent == 'assets':
        outdict['folderstart'] = '🅰️ '
    return outdict


def copy_txt_to_clipboard(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
            pyperclip.copy(content)
            print("The contents of the file have been copied to the clipboard")
    except FileNotFoundError:
        print(f"File not found：{file_path}")
    except Exception as e:
        print(f"Error：{e}")


def main():
    # Get the current folder path and set the exploration level depth
    path = os.getcwd()
    level_limit = 20

    # Set output file name
    file_name = os.path.split(path)[-1] + '_seedir.txt'

    content_str = seedir.seedir(path, style='emoji', printout=False, formatter=my_style, sticky_formatter=True, exclude_folders=['.git','.history'], depthlimit=level_limit)
    # Open the Txt file and start analyzing the directory structure
    with open(file_name, 'w', encoding='utf-8') as seedir_file:
        seedir_file.write(content_str)
    print(f"seedir file {file_name} generated。")
    txt_file_path = file_name
    copy_txt_to_clipboard(txt_file_path)


if __name__ == "__main__":
    main()
```

* Output of `pyinstaller --version`: ```6.3.0```
* Version of Python: 3.10.11
* Platform: Windows (EN)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?
No, I don't have other platform.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import os
import seedir


def main():
    path = os.getcwd()

    file_name = os.path.split(path)[-1] + '_seedir.txt'

    content_str = seedir.seedir(path, style='emoji', printout=False,)
    with open(file_name, 'w', encoding='utf-8') as seedir_file:
        seedir_file.write(content_str)


if __name__ == "__main__":
    main()
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "minimalexample.py", line 2, in <module>
    import seedir
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "seedir\__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "seedir\realdir.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "seedir\folderstructure.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "seedir\printing.py", line 81, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sudoo\\AppData\\Local\\Temp\\_MEI262162\\seedir\\words.txt'
[20200] Failed to execute script 'minimalexample' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sudoo\\AppData\\Local\\Temp\\_MEI262162\\seedir\\words.txt'
> [20200] Failed to execute script 'minimalexample' due to unhandled exception!
> ```

You need to collect the data files of `seedir` package - e.g., add `--collect-data seedir` to your PyInstaller command.
