### ISSUE TITLE
Getting AssertionError: Expected exactly one LC_BUILD_VERSION or LC_VERSION_MIN_MACOSX command!

### ISSUE THREAD

**Issue by rohts-patil** [pyinstaller/pyinstaller#8220]
> Traceback (most recent call last):
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 214, in _console_script_run
    run()
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 198, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 1071, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 1011, in build
    exec(code, spec_namespace)
  File "hooks.spec", line 4, in <module>
    a = Analysis(
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 470, in __init__
    self.__postinit__()
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 854, in assemble
    sdk_version = osxutils.get_macos_sdk_version(src_name)
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/utils/osx.py", line 113, in get_macos_sdk_version
    version_cmd = _find_version_cmd(header)
  File "/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/utils/osx.py", line 98, in _find_version_cmd
    assert len(version_cmd) == 1, "Expected exactly one LC_BUILD_VERSION or LC_VERSION_MIN_MACOSX command!"
AssertionError: Expected exactly one LC_BUILD_VERSION or LC_VERSION_MIN_MACOSX command!

Getting the above error while running `pyinstaller hooks.spec --clean`

**Comment by bwoodsend** [comment]
Could you edit your copy of `/Users/rohit.patil/Desktop/Git/cs/llm/venv/lib/python3.9/site-packages/PyInstaller/utils/osx.py` and insert a `print(filename)` at [this line](https://github.com/pyinstaller/pyinstaller/blob/ee44bbbfd588c5cba6a139954b77b7cb4b197fc7/PyInstaller/utils/osx.py#L110) then rebuild, look at whatever filename gets printed immediately before the exception then upload that file (you might need to hide it in a zip file to stop GitHub from complaining) so that we can see what it is and why it has more than one SDK version?

**Comment by rokm** [comment]
Suppose we should add the number of version commands in the assertion error message, so we won't have to guess whether it was 0 or > 1.

And since the error originates from

https://github.com/pyinstaller/pyinstaller/blob/ee44bbbfd588c5cba6a139954b77b7cb4b197fc7/PyInstaller/building/build_main.py#L851-L861

we should make it non-fatal, and instead just add the offending binary to the list of binaries to warn about.

**Comment by bwoodsend** [comment]
In the absence of any information to the contrary, I'm assuming that #8221 fixes this.

**Comment by rohts-patil** [comment]
@bwoodsend When will this get released?
