### ISSUE TITLE
Azure Cognitive Speech Service files not found

### ISSUE THREAD

**Issue by rafael-wampfler** [pyinstaller/pyinstaller#8236]
Hello

I'm using v5.13.0 and Python 3.10. I'm using the following server.spec file:

```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata
from PyInstaller.utils.hooks import collect_submodules  # Added
import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)
from PyInstaller.utils.hooks import collect_dynamic_libs
binaries = collect_dynamic_libs('nvidia.cuda_nvrtc', search_patterns=['lib*.so.*'])

datas = []
datas += collect_data_files('torch')
datas += copy_metadata('torch')
datas += copy_metadata('tqdm')
datas += copy_metadata('regex')
datas += copy_metadata('requests')
datas += copy_metadata('packaging')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')
datas += copy_metadata('importlib_metadata')
datas += copy_metadata('deepspeed')
datas += copy_metadata('huggingface-hub')
datas += copy_metadata('safetensors')
datas += copy_metadata('pyyaml')
datas += copy_metadata('sentencepiece')
datas += copy_metadata('datasets')
datas += copy_metadata('optimum')
datas += copy_metadata('transformers')
datas += copy_metadata('auto_gptq')
datas += copy_metadata('triton')
datas += collect_data_files('ninja')
datas += collect_data_files('deepspeed')
datas += collect_data_files('datasets')
datas += collect_data_files('optimum')
datas += collect_data_files('transformers')
datas += collect_data_files('auto_gptq')
datas += collect_data_files('triton')

# Added
hiddenimports = []
hiddenimports = collect_submodules('deepspeed') + collect_submodules('datasets') + collect_submodules('optimum') + collect_submodules('transformers') + collect_submodules('auto_gptq')
hiddenimports.append('triton._C.libtriton')
hiddenimports.append('tiktoken_ext')
hiddenimports.append('tiktoken_ext.openai_public')

block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports, 
    #hiddenimports=['pytorch', 'deepspeed'], NOTE: pytorch is not a valid module name, and deepspeed is included in collect_submodules output
    hookspath=['pyinstaller-hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    # Added
    module_collection_mode={
        "deepspeed": "pyz+py",
        "datasets": "pyz+py",
        "optimum": "pyz+py",
        "transformers": "pyz+py",
        "auto_gptq": "pyz+py",
        "triton": "py"
    },
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

The compilation works well but when I start the program I'm getting the following error:

```
Traceback (most recent call last):
  File "server/main.py", line 58, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "azure/cognitiveservices/speech/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "azure/cognitiveservices/speech/speech.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "azure/cognitiveservices/speech/interop.py", line 20, in <module>
  File "ctypes/__init__.py", line 460, in LoadLibrary
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.PyInstallerImportError: Failed to load dynlib/dll '/tmp/_MEITEFdF2/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so'. Most likely this dynlib/dll was not found when the application was frozen.
[183533] Failed to execute script 'main' due to unhandled exception!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 382, in __init__
OSError: /tmp/_MEIGXJt9t/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory
```

I'm using Azure Cognitive Speech Services (`from azure.cognitiveservices.speech as speechsdk`). It sounds like the problem is coming from this library.

Thank you so much for your help!

**Comment by rokm** [comment]
Does `collect_dynamic_libs('azure.cognitiveservices.speech')` not collect the file mentioned in the error?

**Comment by rafael-wampfler** [comment]
Thank you very much for your help. This resolved the issue.
