### ISSUE TITLE
RuntimeError: OpenSSL 3.0's legacy provider failed to load.

### ISSUE THREAD

**Issue by v1c5anchez** [pyinstaller/pyinstaller#8240]
## Description of the issue

I recently bundled a python application (via [pyinstaller](https://github.com/pyinstaller/pyinstaller)) in order to run it with [systemd](https://en.wikipedia.org/wiki/Systemd).

When I try to run it via [systemd](https://en.wikipedia.org/wiki/Systemd) it fails.

This is how I run it:

```
systemctl start zs
```
### Bundle command
```
PYTHON_VERSION=$(env/bin/python --version | cut -d' ' -f2 | cut -d'.' -f1,2)
env/bin/pyinstaller --clean -F -p . -p /usr/lib/python$PYTHON_VERSION/site-packages/ -n zs  zs.py
```
Then I move the file into here:
```
/usr/bin/zs
```

### Systemd configuration file
```
#cat /etc/systemd/system/zs.service
[Unit]
Description=ZS
After=mysqld.service

[Service]
ExecStart=/usr/bin/zs

[Install]
WantedBy=multi-user.target
```

###  Log file
```
# journalctl -u zs --since="2014-01-17 13:13:00"
...
ene 17 13:13:48  systemd[1]: zs.service: Failed with result 'exit-code'.
ene 17 13:18:56  systemd[1]: Started ZS.
ene 17 13:18:58  zs[29709]: Traceback (most recent call last):
ene 17 13:18:58  zs[29709]:   File "zs.py", line 33, in <module>
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ene 17 13:18:58  zs[29709]:   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
ene 17 13:18:58  zs[29709]:   File "workers/gvm.py", line 26, in <module>
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ene 17 13:18:58  zs[29709]:   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
ene 17 13:18:58  zs[29709]:   File "gvm/connections.py", line 32, in <module>
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ene 17 13:18:58  zs[29709]:   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
ene 17 13:18:58  zs[29709]:   File "paramiko/__init__.py", line 22, in <module>
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ene 17 13:18:58  zs[29709]:   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
ene 17 13:18:58  zs[29709]:   File "paramiko/transport.py", line 132, in <module>
ene 17 13:18:58  zs[29709]:   File "paramiko/transport.py", line 206, in Transport
ene 17 13:18:58  zs[29709]:   File "paramiko/kex_curve25519.py", line 30, in is_available
ene 17 13:18:58  zs[29709]:   File "cryptography/hazmat/primitives/asymmetric/x25519.py", line 59, in generate
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ene 17 13:18:58  zs[29709]:   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
ene 17 13:18:58  zs[29709]:   File "cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ene 17 13:18:58  zs[29709]:   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
ene 17 13:18:58  zs[29709]:   File "cryptography/hazmat/backends/openssl/backend.py", line 27, in <module>
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ene 17 13:18:58  zs[29709]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ene 17 13:18:58  zs[29709]:   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
ene 17 13:18:58  zs[29709]:   File "cryptography/hazmat/bindings/openssl/binding.py", line 167, in <module>
ene 17 13:18:58  zs[29709]:   File "cryptography/hazmat/bindings/openssl/binding.py", line 134, in init_static_locks
ene 17 13:18:58  zs[29709]:   File "cryptography/hazmat/bindings/openssl/binding.py", line 123, in _ensure_ffi_initialized
ene 17 13:18:58  zs[29709]:   File "cryptography/hazmat/bindings/openssl/binding.py", line 43, in _legacy_provider_error
ene 17 13:18:58  zs[29709]: RuntimeError: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting th>
ene 17 13:18:58  zs[29709]: [29709] Failed to execute script 'zs' due to unhandled exception!
```

### Context information

* Output of `pyinstaller --version`: 6.3.0
* Version of Python: 3.11.5
* Platform: Arch Linux
* How you installed Python: pacman -S python
* Did you also try this on another platform? Does it work there? N/A

### [venv](https://docs.python.org/3.11/library/venv.html) dependencies
```
altgraph==0.17.4
appdirs==1.4.4
astroid==2.15.8
async-timeout==4.0.3
bcrypt==4.0.1
black==23.10.1
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.2.0
click==8.1.7
coverage==7.3.1
cryptography==41.0.4
defusedxml==0.7.1
dill==0.3.7
docker==6.1.3
exceptiongroup==1.1.3
idna==3.4
ifaddr==0.2.0
importlib-metadata==6.8.0
iniconfig==2.0.0
ipcalc==1.99.0
IPy==1.1
isort==5.12.0
lazy-object-proxy==1.9.0
lxml==4.9.3
mccabe==0.7.0
mock==5.1.0
mypy==1.6.1
mypy-extensions==1.0.0
mysql-connector-python==8.1.0
netaddr==0.9.0
netifaces==0.11.0
nose2==0.13.0
packaging==23.1
paramiko==3.3.1
pathspec==0.11.2
pipdeptree==2.13.0
platformdirs==3.10.0
pluggy==1.3.0
protobuf==4.21.12
psutil==5.9.5
pyasn1==0.5.0
pyclean==2.7.5
pycparser==2.21
pycryptodome==3.19.0
pyinstaller==6.3.0
pyinstaller-hooks-contrib==2023.12
pylint==2.17.6
PyNaCl==1.5.0
pyparsing==3.1.1
pyspeedtest==1.2.7
pytest==7.4.2
python-crontab==3.0.0
python-dateutil==2.8.2
python-gvm==24.1.0
requests==2.31.0
requests-mock==1.11.0
rsa==4.9
scapy==2.5.0
simplejson==3.19.1
six==1.16.0
speedtest-cli==2.1.3
toml==0.10.2
tomli==2.0.1
tomlkit==0.12.1
typing_extensions==4.8.0
urllib3==2.0.5
websocket-client==1.6.3
wrapt==1.15.0
xmltodict==0.13.0
zeroconf==0.115.0
zipp==3.17.0
```
### NOTE:
Prior to venv packages installation I ran the following:
```
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1
```

**Comment by bwoodsend** [comment]
> env/bin/pyinstaller --clean -F -p . -p /usr/lib/python$PYTHON_VERSION/site-packages/ -n zs  zs.py

Probably not the cause but having PyInstaller in one environment then injecting another environment's `site-packages` like that is a pretty sure way to cause self inflicted trouble. Either put all your dependencies in the virtual environment or install pyinstaller into the global one.

**Comment by v1c5anchez** [comment]
> > env/bin/pyinstaller --clean -F -p . -p /usr/lib/python$PYTHON_VERSION/site-packages/ -n zs  zs.py
> 
> Probably not the cause but having PyInstaller in one environment then injecting another environments `site-packages` like that is a pretty sure way to cause self inflicted trouble. Either put all your dependencies in the virtual environment or install pyinstaller into the global one.

@bwoodsend , It was an issue related to the [cryptography](https://github.com/pyca/cryptography) library environment variables, not _Pyinstaller_.

This is the [solution](https://github.com/pyca/cryptography/issues/10198).

Please, feel free to delete this issue.

My apologies.
