### ISSUE TITLE
Trying to PyInstaller with Enthought Canopy distribution

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#828]
**Original date**: 2013/11/22

built a super simple one-line program
print "hello world"
and tried to use pyinstaller but always get the following error:

Note: I'm running the Enthought Canopy install 1.1 on a Mac 

```
(Canopy 32bit) new-host-3:Experiments nyq$ pyinstaller ./ezhello.py --onefile ezhello.spec
18 INFO: wrote /Users/nyq/Dropbox/Python/pyqt/Experiments/ezhello.spec
40 INFO: UPX is not available.
57 INFO: Processing hook hook-os
140 INFO: Processing hook hook-time
178 INFO: Processing hook hook-_sre
196 INFO: Processing hook hook-cStringIO
203 INFO: Processing hook hook-codecs
211 INFO: Processing hook hook-encodings
594 INFO: Processing hook hook-cPickle
674 INFO: Extending PYTHONPATH with /Users/nyq/Dropbox/Python/pyqt/Experiments
674 INFO: Extending PYTHONPATH with /Users/nyq/Dropbox/Python/pyqt/Experiments
674 INFO: checking Analysis
674 INFO: building because ezhello.spec changed
674 INFO: running Analysis out00-Analysis.toc
683 INFO: Analyzing /Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/_pyi_bootstrap.py
693 INFO: Processing hook hook-os
706 INFO: Processing hook hook-site
717 INFO: Processing hook hook-encodings
785 INFO: Processing hook hook-time
812 INFO: Processing hook hook-_sre
829 INFO: Processing hook hook-cStringIO
835 INFO: Processing hook hook-codecs
1188 INFO: Processing hook hook-cPickle
1295 INFO: Processing hook hook-pydoc
1387 INFO: Processing hook hook-email
1427 INFO: Processing hook hook-httplib
1456 INFO: Processing hook hook-email.message
1681 INFO: Analyzing /Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py
1712 INFO: Analyzing /Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyi_archive.py
1741 INFO: Analyzing /Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyi_carchive.py
1770 INFO: Analyzing /Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyi_os_path.py
1774 INFO: Analyzing ./ezhello.py
1774 INFO: Analyzing ezhello.spec
1774 INFO: Hidden import 'codecs' has been found otherwise
1774 INFO: Hidden import 'encodings' has been found otherwise
1774 INFO: Looking for run-time hooks
1832 INFO: Using Python library /Users/nyq/Library/Enthought/Canopy_32bit/User/bin/Python
1846 INFO: /Users/nyq/Dropbox/Python/pyqt/Experiments/build/ezhello/out00-Analysis.toc no change!
1850 INFO: checking PYZ
1854 INFO: checking PKG
1854 INFO: building because out00-PKG.toc missing or bad
1854 INFO: building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==2.1', 'console_scripts', 'pyinstaller')()
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/build.py", line 1924, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/build.py", line 1873, in build
    execfile(spec)
  File "/Users/nyq/Dropbox/Python/pyqt/Experiments/ezhello.spec", line 17, in <module>
    console=True )
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/build.py", line 1170, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/build.py", line 1008, in __init__
    self.__postinit__()
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/build.py", line 309, in __postinit__
    self.assemble()
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/build.py", line 1069, in assemble
    archive.build(self.name, mytoc)
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyi_archive.py", line 217, in build
    self._finalize()
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyi_carchive.py", line 190, in _finalize
    self.save_toc(toc_pos)
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyi_carchive.py", line 351, in save_toc
    tocstr = self.toc.tobinary()
  File "/Users/nyq/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyi_carchive.py", line 85, in tobinary
    nmlen + entrylen, dpos, dlen, ulen, flag, typcd, nm + pad))
struct.error: argument for 's' must be a string
(Canopy 32bit) new-host-3:Experiments nyq$ 
```

**Comment by matysek** [comment]
Main supported Python distribution is CPython. We would welcome any pull requests adding Enthough support if it does not work with latest dev versions.
