### ISSUE TITLE
selenium-manager.exe doesn't exist

### ISSUE THREAD

**Issue by yolorkit** [pyinstaller/pyinstaller#8296]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.0.0``` minimum non working version, in ```5.13.2``` everything works
* Version of Python: 3.11.8
* Platform: Windows 10/2019 (Ukrainian, English)
* How you installed Python: python.org/downloads
* On multiple Linux distributions everything works upto version ```6.3.0```. On multiple Windows fresh installs it fails the same way, Windows 10 and Windows 2019 were tested

### A minimal example program which shows the error
options = Options()
options.add_argument("--headless")
driver = webdriver.Firefox(options=options)

I run it like this:

```
pyinstaller.exe --upx-dir "${upxe}" --distpath "${dist}" -w --onefile `
	--hidden-import "pyexcel_ods" --hidden-import "pyexcel_ods.odsr" --hidden-import "pyexcel_ods.odsw" `
	--hidden-import "pyexcel_io.readers.csvr" --hidden-import "pyexcel_io.readers.tsv" `
	--hidden-import "pyexcel_io.readers.tsvz" --hidden-import "pyexcel_io.writers.csvw" `
	--hidden-import "pyexcel_io.writers.csvz" --hidden-import "pyexcel_io.writers.tsv" `
	--hidden-import "pyexcel_io.writers.tsvz" --hidden-import "pyexcel_io.readers.tsv" `
	--hidden-import "pyexcel_io.readers.tsvz" "${pySrcDir}\main_gui.py" "${pySrcDir}\main_window_ui.py"
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\__main__.py", line 214, in _console_script_run
    run()
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\__main__.py", line 198, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\building\build_main.py", line 1071, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\building\build_main.py", line 1011, in build
    exec(code, spec_namespace)
  File "D:\admin\Source\main_gui.spec", line 18, in <module>
    exe = EXE(
          ^^^^
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\building\api.py", line 609, in __init__
    self.pkg = PKG(
               ^^^^
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\building\api.py", line 238, in __init__
    self.__postinit__()
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\building\api.py", line 329, in assemble
    CArchiveWriter(self.name, bootstrap_toc + archive_toc, pylib_name=self.python_lib_name)
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\archive\writers.py", line 141, in __init__
    toc_entry = self._write_entry(fp, entry)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\archive\writers.py", line 226, in _write_entry
    return self._write_file(fp, src_name, dest_name, typecode, compress=compress)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Arhiv\Install_Configure\python-environments\certs_env\Lib\site-packages\PyInstaller\archive\writers.py", line 246, in _write_file
    data_length = os.stat(src_name).st_size
                  ^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\User\\AppData\\Local\\pyinstaller\\bincache01py31164bit\\selenium\\webdriver\\common\\windows\\selenium-manager.exe'
```

However in version 5.13.2 I got this:
```719 INFO: Extra DLL search directories (PATH): ['C:\\Arhiv\\Install_Configure\\python-environments\\certs_env\\Lib\\site-packages\\PyQt5\\Qt5\\bin', 'C:\\Arhiv\\Install_Configure\\python-environments\\certs_env\\Scripts', 'C:\\Program Files\\PowerShell\\7', 'C:\\Program Files\\Python311\\Scripts\\', 'C:\\Program Files\\Python311\\', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'D:\\mssql\\86\\Microsoft SQL Server\\150\\DTS\\Binn\\', 'C:\\Program Files\\Meld\\', 'D:\\mssql\\64\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\', 'D:\\mssql\\86\\Microsoft SQL Server\\130\\Tools\\Binn\\', 'D:\\mssql\\64\\Microsoft SQL Server\\130\\Tools\\Binn\\', 'D:\\mssql\\64\\Microsoft SQL Server\\130\\DTS\\Binn\\', 'C:\\Program Files\\PuTTY\\', 'C:\\Program Files\\PowerShell\\7\\', 'C:\\Arhiv\\Install_Configure\\python-environments\\certs_env\\Scripts\\', 'C:\\Users\\u18\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Program Files\\Azure Data Studio\\bin']```

So i think PATH variable isn't look upon starting with 6.0.0

**Comment by rokm** [comment]
> So i think PATH variable isn't look upon starting with 6.0.0

`PATH` is irrelevant for a 3rd party executable that is supposed to be collected as part of a package, since collection of that is handled by [the hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-selenium.py#L15).

Prior to v6.0, the .exe was picked up as a data file, but with v6.0 we reclassify it as a binary, and consequently it undergoes the UPX processing. Could be that something went wrong there.

But to be sure, can you try re-running PyInstaller with `--clean` option to attempt build with clean bincache? Does the error persist?

**Comment by rokm** [comment]
I did a quick test on my Windows 10 VM, and trying to process `selenium-manager.exe` with UPX results in Windows Defender blocking access to the file.

So as a work-around, you could either disable UPX completely, or just for that file: `--upx-exclude selenium-manager.exe`.

**Comment by swamp-fish** [comment]
```--clean``` option didn't help. But i confirm that removing ```upx``` or adding an option ```--upx-exclude selenium-manager.exe``` results in a successful compilation. Thank you!
