### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte

### ISSUE THREAD

**Issue by avfranco-br** [pyinstaller/pyinstaller#8299]
Hello, couldn't find a way to solve this error. The python script works fine running from everywhere else (terminal, VS Code, HF Spaces). It's a gradio python app. Any help is welcome. Thanks.

```Traceback (most recent call last):
  File "app.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ea4all/__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1234, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ea4all/app_ea4all_agent.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "gradio/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "gradio/_simple_templates/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "gradio/_simple_templates/simpledropdown.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "gradio/components/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "gradio/components/annotated_image.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "gradio/components/base.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "gradio/blocks.py", line 462, in <module>
  File "gradio/blocks_events.py", line 20, in __new__
  File "gradio/component_meta.py", line 91, in create_or_modify_pyi
  File "pathlib.py", line 1059, in read_text
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
[76272] Failed to execute script 'app' due to unhandled exception!```

**Comment by bwoodsend** [comment]
https://github.com/gradio-app/gradio/blob/065c5b163c4badb9d9cbd06d627fb4ba086003e7/gradio/component_meta.py#L89-L91

```python
    source_file = Path(inspect.getfile(component_class))

    source_code = source_file.read_text()
```
That's a broken package. `inspect.getfile()` may return a `.pyc` file and/or a file that doesn't exist on the file system. They should be using `inspect.getsource()` for which you'd then need to `--add-data` in whatever `.py` file defines the class you're passing into that function. (This is assuming that whatever they're doing with that source code isn't even more misguided than their implementation. It looks like they're generating more Python code from Python code which will probably violate macOS's sandbox if written to the wrong part of the file system.)

**Comment by rokm** [comment]
> https://github.com/gradio-app/gradio/blob/065c5b163c4badb9d9cbd06d627fb4ba086003e7/gradio/component_meta.py#L89-L91
> 
> ```python
>     source_file = Path(inspect.getfile(component_class))
> 
>     source_code = source_file.read_text()
> ```
> 
> That's a broken package. `inspect.getfile()` may return a `.pyc` file and/or a file that doesn't exist on the file system. They should be using `inspect.getsource()` for which you'd then need to `--add-data` in whatever `.py` file defines the class you're passing into that function. (This is assuming that whatever they're doing with that source code isn't even more misguided than their implementation).

The only way this will work in PyInstaller-frozen application in its current (broken) form is if you force collection mode of the modules/packages that are being processed by that mechanism to source .py files only (i.e., no byte-compiled modules in PYZ archive), using [module_collection_mode](https://pyinstaller.org/en/stable/hooks.html). 

You can pass a `module_collection_mode` dictionary to `Analysis` in the spec file (but you need to build via .spec file for that to work). See https://github.com/pyinstaller/pyinstaller/issues/8241#issuecomment-1898286617 for an example - of course, in your case, you will need to replace the module name, and set the collection mode to just `'py'`.

**Comment by avfranco-br** [comment]
Thank you @bwoodsend , @rokm,

Going to try with the module_collection_mode and hopefully it works.

Alexandre

**Comment by avfranco-br** [comment]
> > https://github.com/gradio-app/gradio/blob/065c5b163c4badb9d9cbd06d627fb4ba086003e7/gradio/component_meta.py#L89-L91
> > ```python
> >     source_file = Path(inspect.getfile(component_class))
> > 
> >     source_code = source_file.read_text()
> > ```
> > That's a broken package. `inspect.getfile()` may return a `.pyc` file and/or a file that doesn't exist on the file system. They should be using `inspect.getsource()` for which you'd then need to `--add-data` in whatever `.py` file defines the class you're passing into that function. (This is assuming that whatever they're doing with that source code isn't even more misguided than their implementation).
> 
> The only way this will work in PyInstaller-frozen application in its current (broken) form is if you force collection mode of the modules/packages that are being processed by that mechanism to source .py files only (i.e., no byte-compiled modules in PYZ archive), using [module_collection_mode](https://pyinstaller.org/en/stable/hooks.html).
> 
> You can pass a `module_collection_mode` dictionary to `Analysis` in the spec file (but you need to build via .spec file for that to work). See [#8241 (comment)](https://github.com/pyinstaller/pyinstaller/issues/8241#issuecomment-1898286617) for an example - of course, in your case, you will need to replace the module name, and set the collection mode to just `'py'`.

Hi @rokm, I've added into .spec file some new lines but still not working. I'd be doing something wrong or missing something else. Can you please advise?

```
added_files = [
    ('../lib/python3.11/site-packages/gradio/*.py', 'gradio'),
    ('../lib/python3.11/site-packages/gradio_client/types.json', 'gradio_client'),
    ('../apm_store', 'apm_store'),
    ]
a = Analysis(
    ['app.py', 'app.spec'],
    pathex=[],
    binaries=added_binaries,
    datas=added_files,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    module_collection_mode={
        'BlocksMeta': 'py',
        'create_or_modify_pyi': 'py',
    }
```

Thanks,
Alexandre

**Comment by rokm** [comment]
Which module/component is being processed by that mechanism?

>```
>    module_collection_mode={
>        'BlocksMeta': 'py',
>        'create_or_modify_pyi': 'py',
>    }
>```

These look bogus (as `create_or_modify_pyi` is a function name, not a module name).

Based on the original traceback, I would start with

```
    module_collection_mode={
        'gradio': 'py',
        'ea4all': 'py',
    }
```

**Comment by avfranco-br** [comment]
Thanks @rokm,

The app is now being started `[68483] LOADER: Running app.py`, but unfortunately so many other exceptions. I'll try a bit more to find out what the reasons are.

Regards,
Alexandre
