### ISSUE TITLE
add hook for PyGTK+ 3

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#835]
**Original date**: 2013/12/17
**Original reporter**: *aaron_caffrey AND hotmail DOT  COOM *

```
[frost@frost-pc pyinstaller-develop]$ python2 pyinstaller.py -F pdf2img.py 
22 INFO: wrote /home/frost/Desktop/New Folder/pyinstaller-develop/pdf2img/pdf2img.spec
50 INFO: UPX is not available.
92 INFO: Processing hook hook-os
204 INFO: Processing hook hook-time
207 INFO: Processing hook hook-cPickle
278 INFO: Processing hook hook-_sre
400 INFO: Processing hook hook-cStringIO
496 INFO: Processing hook hook-encodings
510 INFO: Processing hook hook-codecs
850 INFO: Extending PYTHONPATH with /home/frost/Desktop/New Folder/pyinstaller-develop
850 INFO: checking Analysis
850 INFO: building Analysis because out00-Analysis.toc non existent
850 INFO: running Analysis out00-Analysis.toc
899 INFO: Analyzing /home/frost/Desktop/New Folder/pyinstaller-develop/PyInstaller/loader/_pyi_bootstrap.py
933 INFO: Processing hook hook-os
948 INFO: Processing hook hook-site
965 INFO: Processing hook hook-encodings
1071 INFO: Processing hook hook-time
1074 INFO: Processing hook hook-cPickle
1146 INFO: Processing hook hook-_sre
1270 INFO: Processing hook hook-cStringIO
1381 INFO: Processing hook hook-codecs
1762 INFO: Processing hook hook-pydoc
1881 INFO: Processing hook hook-email
1937 INFO: Processing hook hook-httplib
1970 INFO: Processing hook hook-email.message
2024 INFO: Analyzing /home/frost/Desktop/New Folder/pyinstaller-develop/PyInstaller/loader/pyi_importers.py
2073 INFO: Analyzing /home/frost/Desktop/New Folder/pyinstaller-develop/PyInstaller/loader/pyi_archive.py
2119 INFO: Analyzing /home/frost/Desktop/New Folder/pyinstaller-develop/PyInstaller/loader/pyi_carchive.py
2165 INFO: Analyzing /home/frost/Desktop/New Folder/pyinstaller-develop/PyInstaller/loader/pyi_os_path.py
2170 INFO: Analyzing pdf2img.py
2246 INFO: Hidden import 'codecs' has been found otherwise
2246 INFO: Hidden import 'encodings' has been found otherwise
2246 INFO: Looking for run-time hooks
3607 INFO: Using Python library /usr/lib/libpython2.7.so.1.0
3626 INFO: Warnings written to /home/frost/Desktop/New Folder/pyinstaller-develop/pdf2img/build/pdf2img/warnpdf2img.txt
3635 INFO: checking PYZ
3635 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
3635 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
4428 INFO: checking PKG
4428 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
4428 INFO: building PKG (CArchive) out00-PKG.pkg
7545 INFO: checking EXE
7546 INFO: rebuilding out00-EXE.toc because pdf2img missing
7546 INFO: building EXE from out00-EXE.toc
7546 INFO: Appending archive to EXE /home/frost/Desktop/New Folder/pyinstaller-develop/pdf2img/dist/pdf2img

```

Opening a new terminal and going to the dist directory:

```

[frost@frost-pc dist]$ chmod +x pdf2img 
[frost@frost-pc dist]$ ./pdf2img 
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/frost/Desktop/New Folder/pyinstaller-develop/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/frost/Desktop/New Folder/pyinstaller-develop/pdf2img/build/pdf2img/out00-PYZ.pyz/gi", line 27, in <module>
  File "/home/frost/Desktop/New Folder/pyinstaller-develop/PyInstaller/loader/pyi_importers.py", line 414, in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
ImportError: could not import gobject (error was: ImportError("could not import gi._glib (error was: 'No module named _glib')",))

```

**Comment by htgoebel** [comment]
Reson: pygtk is not actively developed anymore and this is the successor of pygtk: https://wiki.gnome.org/action/show/Projects/PyGObject?action=show&redirect=PyGObject
