### ISSUE TITLE
Error occured after converting .py file to exe file by using pyinstaller

### ISSUE THREAD

**Issue by shankarumane7** [pyinstaller/pyinstaller#8360]
**This is code:**

```python
# -*- coding: utf-8 -*-
"""
Created on Fri Dec 22 20:09:06 2023

@author: SHANKAR UMANE
"""


from tkinter import *
from tkinter import filedialog
import cv2
import fitz
from pyzbar.pyzbar import decode
import os
import shutil
import numpy as np
import json





mes_1 = ''
qr = 0
file_list = []
path_1 = os.getcwd()
config_file_path = os.path.join(path_1, 'config_file.json')
if not os.path.exists(config_file_path):
    dir_path = {}
    dir_path['config_file_path']=config_file_path
    with open(config_file_path, 'w') as config_file:
        json.dump(dir_path, config_file, indent=2)
    print ('config_file_created')  

with open(config_file_path, 'r') as config_file:
    dir_path = json.load(config_file)        
    

def config_file_reader():
    global dir_path, config_file_path
    with open(config_file_path, 'r') as config_file:
        dir_path = json.load(config_file)
    

def config_file_writer():
    global dir_path, config_file_path
    with open(config_file_path, 'w') as config_file:
        json.dump(dir_path, config_file, indent=2)
    


def set_destination_path():
    global dir_path, config_file_path
    path = filedialog.askdirectory()
    #path = 'r'+ '"' +path+'"'
    dir_path['destination_path']=path
    config_file_writer()
    #if path:
    #    label2.config(text=f"Destination Path: {path}")

def set_source_file_path():
    global dir_path
    path = filedialog.askdirectory()
    #path = 'r'+ '"' +path+'"'
    dir_path['source_file_path']=path
    config_file_writer()
    #if path:
    #    label2.config(text=f"Source File Path: {path}")




# Below are functions to start
def extract_images_from_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    all_qr_codes_data = []
    
    for page_num in range(doc.page_count):
        images = extract_images_from_page(doc, page_num)
        qr_codes_data = read_qr_codes_from_images(images)
        all_qr_codes_data.extend(qr_codes_data)
    global qr
    if (len(all_qr_codes_data)) == 0:
        qr+=1
        ir_name='NO_QR_ CODE_'+str(qr)+'  '
        all_qr_codes_data.append(ir_name)
    return all_qr_codes_data

def extract_images_from_page(doc, page_num):
    page = doc[page_num]
    images = page.get_images(full=True)
    
    image_list = []
    for img_index, img_info in enumerate(images):
        xref = img_info[0]
        base_image = doc.extract_image(xref)
        image_bytes = base_image["image"]
        nparr = np.frombuffer(image_bytes, np.uint8)
        image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        image_list.append(image)
    
    return image_list

def read_qr_codes_from_images(images):
    qr_codes_data = []
    for image in images:
        qr_codes = decode(image)
        for qr_code in qr_codes:
            qr_space = qr_code.data.decode('utf-8')
            qr_space = qr_space +'  '
            qr_codes_data.append(qr_space)
    
    return qr_codes_data





def rename_and_move_pdf(pdf_path, destination_directory):
    global mes_1, label2, file_list
    # Extract QR codes and generate a new file name
    all_qr_codes_data = extract_images_from_pdf(pdf_path)
    new_file = []
    for i in all_qr_codes_data:
        data = i
        first_space_index = data.index(' ')
        second_space_index = data.find(' ', first_space_index + 1)
        ir = data[:(second_space_index)]
        ir_no = ir.replace(' ', '')
        new_file.append(ir_no)

    new_file_name = ', '.join(new_file)

    # Ensure that the destination directory exists
    os.makedirs(destination_directory, exist_ok=True)

    # Rename and move the PDF file with the concatenated filename
    renamed_pdf_path = os.path.join(destination_directory, f"{new_file_name}.pdf")
    shutil.copy2(pdf_path, renamed_pdf_path)

    mes_1 = f'{new_file[0]}...= ' + str(len(new_file))
    file_list.append(mes_1)
    

    new_file.clear()

    # Delete the original PDF file from the source directory
    os.remove(pdf_path)

# ... (remaining code remains unchanged)

def start():
    global dir_path, config_file_path, file_list
    if ('config_file_path' in dir_path and
            'destination_path' in dir_path and
            'source_file_path' in dir_path and
            dir_path['config_file_path'] and
            dir_path['destination_path'] and
            dir_path['source_file_path']):
        
        source_pdf_directory = dir_path['source_file_path']
        destination_directory = dir_path['destination_path']
        # If there is no QR code on it, then rename the file with QR_CODE_NOT_FOUND
        qr = 0
        # Get a list of all PDF files in the specified source directory
        pdf_files = [file for file in os.listdir(source_pdf_directory) if file.endswith('.pdf')]
        for pdf_file in pdf_files:
            pdf_path = os.path.join(source_pdf_directory, pdf_file)
            rename_and_move_pdf(pdf_path, destination_directory)
            

        # Update the label with the information
        file_list.append(' RENAMED SUCCESSFULLY ')
        label2.config(state=NORMAL)
        label2.delete(1.0, END)
        label2.insert(INSERT, '\n'.join(file_list))
        label2.config(state=DISABLED)
        
    else:
        label2.config(state=NORMAL)
        label2.delete(1.0, END)
        label2.insert(INSERT, 'Create config_file_path, destination_path, source_file_path')
        label2.config(state=DISABLED)

    
# Above functions to start

# this message will be displayed on label2



root = Tk()
root.title('PDF AUTO RENAMER')
root.iconbitmap(os.path.join(path_1, 'PDF RENAMER.ico'))
root.geometry('360x400')
root.configure(bg='gray93')
root.resizable(False, False)

# Menu Bar
menu_bar = Menu(root)
root.config(menu=menu_bar)

# File Menu
file_menu = Menu(menu_bar, tearoff=0)
menu_bar.add_cascade(label="File", menu=file_menu)

# Submenu for setting source file path
file_menu.add_command(label="Set Source File Path", command=set_source_file_path)

# Submenu for setting destination path
file_menu.add_command(label="Set Destination Path", command=set_destination_path)

scrollbar = Scrollbar(root)
scrollbar.pack(side=RIGHT, fill=Y)

btn_start = Button(root, text='START', height=2, width=10, command=start)
btn_quit = Button(root, text='QUIT', height=2, width=10, command=root.destroy)
btn_stop = Button(root, text='STOP', height=2, width=10)
label1 = Label(root, text='DESCRIPTION (FILE NAME -- NUMBER OF IR)', bg='#FCE6C9', padx=40, pady=1)
label1.pack()
label2 = Text(root, wrap=WORD, width=40, height=18, bg='white', state=DISABLED, yscrollcommand=scrollbar.set)
label2.pack(pady=10, padx=5)
scrollbar.config(command=label2.yview)


btn_start.place(x=10, y=330)
btn_quit.place(x=210, y=330)
btn_stop.place(x=110, y=330)
root.mainloop()
```
                                              
Error : 
```
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 35, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "plistlib.py", line 70, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: Module use of python39.dll conflicts with this version of Python.
```

**Comment by rokm** [comment]
Like the error message states, the `pyexpat` extension module for incompatible python version was collected into frozen application.

Two most obvious reasons would be:
- (mis)use of PyInstaller's `--path` option to incorrectly set the python search path, or
- your build environment having `PYTHONPATH` environment variable set and pointing to a specific python environment (that differs from the one from which PyInstaller is being ran).

**Comment by shankarumane7** [comment]
thank you rokm sir, It works fine. Code is converted to exe file successfully. I created new environment with new path.
