### ISSUE TITLE
MacOS error: mapped file has no Team ID and is not a platform binary

### ISSUE THREAD

**Issue by LeManhTruong** [pyinstaller/pyinstaller#8376]
Hi, I freezing my python code to execuatble file (--onefile format), and I run it inside another MacOS app, I get below error: 

`Error loading Python lib '/var/folders/1v/cngzmq110pjgp7jmgls59dlw0000gn/T/_MEIOFS0Zs/libpython3.10.dylib': dlopen: dlopen(/var/folders/1v/cngzmq110pjgp7jmgls59dlw0000gn/T/_MEIOFS0Zs/libpython3.10.dylib, 0x000A): tried: '/var/folders/1v/cngzmq110pjgp7jmgls59dlw0000gn/T/_MEIOFS0Zs/libpython3.10.dylib' (code signature in <566D92CC-3CDA-377A-AA2A-6458CDCB4D87> '/private/var/folders/1v/cngzmq110pjgp7jmgls59dlw0000gn/T/_MEIOFS0Zs/libpython3.10.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/private/var/folders/1v/cngzmq110pjgp7jmgls59dlw0000gn/T/_MEIOFS0Zs/libpython3.10.dylib' (code signature in <566D92CC-3CDA-377A-AA2A-6458CDCB4D87> '/private/var/folders/1v/cngzmq110pjgp7jmgls59dlw0000gn/T/_MEIOFS0Zs/libpython3.10.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?))`

Has anyone ever encountered this situation? and is there any way to solve this problem?

**Comment by rokm** [comment]
If you're trying to run frozen application from a singed macOS app, then the frozen application *and its binaries* need to be signed as well. Since this is onefile application, you can post-hoc sign only the application executable itself, but not the shared libraries that are stored in application's embedded archive. 

Does using [`--codesign-identity`](https://pyinstaller.org/en/stable/usage.html#cmdoption-codesign-identity) to sign binaries during collection help?

**Comment by LeManhTruong** [comment]
Hi rokm, When I was using `--codesign-identity` to build the executable file

`pyinstaller -F my_app.py --codesign-identity <my_code_sign_cert>`

I created `<my_code_sign_cert>` following the tutorial at [here](https://www.simplified.guide/macos/keychain-cert-code-signing-create). After that, I run the executable file on the terminal 

`./dist/my_app`

I got the same error.

**Comment by rokm** [comment]
Yeah, this does not work with self-signed certificate. I think this is because we enable hardened run-time by default.

Can you try removing the following from your local copy of `PyInstaller/utils/osx.py`:
https://github.com/pyinstaller/pyinstaller/blob/8bee1749c0d8f29fbc338e2ef6b8bfa5354174c2/PyInstaller/utils/osx.py#L375-L376

The executable built with `--codesign-identity` should run from terminal, then.

---

How did you sign the main app? Are you using the same self-signed certificate there?

**Comment by LeManhTruong** [comment]
Hi rokm, after I remove 

`extra_args.append('--options=runtime')  # hardened runtime ` in my local code. It worked with my self-signed cert.

But when I change to my company cert `--codesign-identity "Developer ID Application: ****"` I another error

`SystemError: Failed to process binary '/Users/MacBook/Library/Application Support/pyinstaller/bincache00py31064bit/arm64/471a19cc79d4afaf52eb619778ff0844133180e54d718d541e245a3d2ab79ba6/no-entitlements/lib-dynload/_struct.cpython-310-darwin.so'!`

**Comment by rokm** [comment]
What is the full error traceback?

**Comment by LeManhTruong** [comment]
This is my traceback

```
Traceback (most recent call last):
  File "/Users/macbook/miniconda3/envs/anode01/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/__main__.py", line 205, in _console_script_run
    run()
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/__main__.py", line 189, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1033, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 973, in build
    exec(code, spec_namespace)
  File "/Users/macbook/Documents/dev/ANode/ANode/tmp_sign.spec", line 18, in <module>
    exe = EXE(
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/api.py", line 606, in __init__
    self.pkg = PKG(
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/api.py", line 238, in __init__
    self.__postinit__()
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/api.py", line 289, in assemble
    src_name = process_collected_binary(
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/utils.py", line 301, in process_collected_binary
    raise SystemError(f"Failed to process binary {cached_name!r}!") from e
SystemError: Failed to process binary '/Users/macbook/Library/Application Support/pyinstaller/bincache00py31064bit/arm64/471a19cc79d4afaf52eb619778ff0844133180e54d718d541e245a3d2ab79ba6/no-entitlements/lib-dynload/_struct.cpython-310-darwin.so'!
```

**Comment by rokm** [comment]
Is there another traceback preceding this one? Presumably one that mentions codesign command?

**Comment by rokm** [comment]
Since presumably this is codesign failing, what happens if you try running this command from command-line:
```
codesign -s "Developer ID Application: ****" --force --all-architectures --timestamp /Users/macbook/Library/Application Support/pyinstaller/bincache00py31064bit/arm64/471a19cc79d4afaf52eb619778ff0844133180e54d718d541e245a3d2ab79ba6/no-entitlements/lib-dynload/_struct.cpython-310-darwin.so
```

**Comment by LeManhTruong** [comment]
Yeah, full my traceback below

```
1788 DEBUG: Signing file '/Users/macbook/Library/Application Support/pyinstaller/bincache00py31064bit/arm64/471a19cc79d4afaf52eb619778ff0844133180e54d718d541e245a3d2ab79ba6/no-entitlements/lib-dynload/_struct.cpython-310-darwin.so'
Traceback (most recent call last):
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/utils.py", line 282, in process_collected_binary
    osxutils.sign_binary(cached_name, codesign_identity, entitlements_file)
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/utils/osx.py", line 386, in sign_binary
    raise SystemError(f"codesign command ({cmd_args}) failed with error code {p.returncode}!\noutput: {p.stdout}")
SystemError: codesign command (['codesign', '-s', 'Developer ID Application: ****', '--force', '--all-architectures', '--timestamp', '/Users/macbook/Library/Application Support/pyinstaller/bincache00py31064bit/arm64/471a19cc79d4afaf52eb619778ff0844133180e54d718d541e245a3d2ab79ba6/no-entitlements/lib-dynload/_struct.cpython-310-darwin.so']) failed with error code 1!
output: /Users/macbook/Library/Application Support/pyinstaller/bincache00py31064bit/arm64/471a19cc79d4afaf52eb619778ff0844133180e54d718d541e245a3d2ab79ba6/no-entitlements/lib-dynload/_struct.cpython-310-darwin.so: replacing existing signature
Warning: unable to build chain to self-signed root for signer "Developer ID Application: ****"
/Users/macbook/Library/Application Support/pyinstaller/bincache00py31064bit/arm64/471a19cc79d4afaf52eb619778ff0844133180e54d718d541e245a3d2ab79ba6/no-entitlements/lib-dynload/_struct.cpython-310-darwin.so: errSecInternalComponent


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/miniconda3/envs/anode01/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/__main__.py", line 205, in _console_script_run
    run()
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/__main__.py", line 189, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1033, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 973, in build
    exec(code, spec_namespace)
  File "/Users/macbook/Documents/dev/ANode/ANode/tmp_sign.spec", line 18, in <module>
    exe = EXE(
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/api.py", line 606, in __init__
    self.pkg = PKG(
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/api.py", line 238, in __init__
    self.__postinit__()
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/api.py", line 289, in assemble
    src_name = process_collected_binary(
  File "/Users/macbook/miniconda3/envs/anode01/lib/python3.10/site-packages/PyInstaller/building/utils.py", line 301, in process_collected_binary
    raise SystemError(f"Failed to process binary {cached_name!r}!") from e
SystemError: Failed to process binary '/Users/macbook/Library/Application Support/pyinstaller/bincache00py31064bit/arm64/471a19cc79d4afaf52eb619778ff0844133180e54d718d541e245a3d2ab79ba6/no-entitlements/lib-dynload/_struct.cpython-310-darwin.so'!
```

**Comment by rokm** [comment]
> ```
> Warning: unable to build chain to self-signed root for signer "Developer ID Application: ****"
> ```

Looks like a certificate issue that has nothing to do with PyInstaller itself - you'll have to search around for this error message and potential fixes.

**Comment by LeManhTruong** [comment]
After I fixed the above error by adding a few certs from [Apple PKI](https://www.apple.com/certificateauthority/). And make sure the certificate when I build the executable file and build the main app (my MacOS app) is the same. It worked.
Thank you so much.
