### ISSUE TITLE
pyinstaller dosent work well with .spec file

### ISSUE THREAD

**Issue by AlexiJemano** [pyinstaller/pyinstaller#8377]
so instead of writing:
```
pyinstaller --noconfirm --log-level=WARN \
    --onefile --nowindow \
    --add-data="README:." \
    --add-data="image1.png:img" \
    --add-binary="libfoo.so:lib" \

```

I used an .spec file and when I wrote in termenal:`pyinstaller main.spec` and I thought evreything was fine but when I run the file I get an error

` `Error loading python DLL "C\Users\Administrator\Documents\IT\Python\pythonProject3\biuld\main\_internal\python311.dll". LoadLibrary: The specified moudle couldnot be found``

.spec file
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['main.py'],
             pathex=['C:/Users/Administrator/Documents/IT/Python/pythonProject3'],
             binaries=[],
             datas=[('config.ini', '.'), ('data/*', 'data')],  # Include entire data folder
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='your_script',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
```

main.py
```
import threading
import tkinter as tk
from tkinter import ttk
import pygame
import patoolib
import configparser
from tkinter import filedialog
import wmi
import psutil
import GPUtil
import winshell
import getpass
from tqdm import tqdm  # Import tqdm for the progress bar
status = 0

root = tk.Tk()
root.title("My Window")
root.attributes("-fullscreen", True)
# # Import the tcl file
# root.tk.call('source', 'data/Forest/forest-light.tcl')
#
# # Set the theme with the theme_use method
# ttk.Style().theme_use('forest-light')
# Create a style
config = configparser.ConfigParser()
config.read("config.ini")
app_name = config.get("Settings", "AppName")
button_image = tk.PhotoImage(file="data/button.png")
# Creating an app with a theme: this is the ThemedTk object
# The theme will applied to every ttk widget in your application
recOS = config.get("Recommended-System-Req", "OS")
recGPU = config.get("Recommended-System-Req", "Graphics")
recCPU = config.get("Recommended-System-Req", "Processor")
recRAM = config.get("Recommended-System-Req", "Memory")
recStorage = config.get("Recommended-System-Req", "Storage")
recCPU_Cores = config.get("Recommended-System-Req", "CPU_Cores")
recCPU_Fre = config.get("Recommended-System-Req", "CPU_Fre")
recGPU_VRAM = config.get("Recommended-System-Req", "GPU_VRAM")
var = tk.IntVar()
var1 = tk.IntVar()
var2 = tk.IntVar()
var3 = tk.IntVar()
var4 = tk.IntVar()
var5 = tk.IntVar()
shortcut_var1 = tk.IntVar()
shortcut_var2 = tk.IntVar()
opt1PATH = config.get("Optional", "Optional1")
opt1NAME = config.get("Optional", "Optional1_Name")
opt2PATH = config.get("Optional", "Optional2")
opt2NAME = config.get("Optional", "Optional2_Name")
opt3PATH = config.get("Optional", "Optional3")
opt3NAME = config.get("Optional", "Optional3_Name")
opt4PATH = config.get("Optional", "Optional4")
opt4NAME = config.get("Optional", "Optional4_Name")
opt5PATH = config.get("Optional", "Optional5")
opt5NAME = config.get("Optional", "Optional5_Name")
music = config.get("Settings", "Music")

# Connect to WMI (requires installation)
c = wmi.WMI()
os = c.Win32_OperatingSystem()[0]
os_name = os.Caption


def get_gpu_name():
    try:
        w = wmi.WMI()
        for gpu in w.Win32_VideoController():
            return gpu.Name
    except Exception as e:
        print("Error:", e)
        return None


def get_cpu_info():
    cpu_info = {
        "cpu_name": get_cpu_name(),
        "cpu_count_physical": psutil.cpu_count(logical=False),
        "cpu_count_logical": psutil.cpu_count(logical=True),
        "cpu_frequency": psutil.cpu_freq().current,
        "cpu_usage_percent": psutil.cpu_percent(interval=1, percpu=True)
    }
    return cpu_info


def get_cpu_name():
    try:
        w = wmi.WMI()
        for processor in w.Win32_Processor():
            return processor.Name
    except Exception as e:
        print("Error:", e)
        return None


def get_total_memory():
    mem = psutil.virtual_memory()
    return mem.total


total_memory_bytes = get_total_memory()
total_memory_gb = total_memory_bytes / (1024 ** 3)  # Convert bytes to GB
formatted_total_memory = "{:.2f} GB".format(total_memory_gb)


def get_storage_info():
    partitions = psutil.disk_partitions(all=True)
    storage_info = {}
    for partition in partitions:
        try:
            partition_usage = psutil.disk_usage(partition.mountpoint)
            storage_info[partition.mountpoint] = partition_usage.total
        except Exception as e:
            print("Error while getting storage info for partition {}: {}".format(partition.mountpoint, e))
    return storage_info


if __name__ == "__main__":
    storage_info = get_storage_info()
    Storage = ""
    for partition, total_storage_bytes in storage_info.items():
        total_storage_gb = total_storage_bytes / (1024 ** 3)  # Convert bytes to GB
        formatted_total_storage = "{:.2f} GB".format(total_storage_gb)
        Storage += "{}: {}\n".format(partition, formatted_total_storage)


def get_vram_info():
    try:
        gpus = GPUtil.getGPUs()
        vram_info = {}
        for gpu in gpus:
            vram_info[gpu.id] = {
                "name": gpu.name,
                "vram": gpu.memoryTotal
            }
        return vram_info
    except Exception as e:
        print("Error:", e)
        return None


if __name__ == "__main__":
    vram_info = get_vram_info()
    if vram_info:
        for gpu_id, gpu_info in vram_info.items():
            print("GPU {}: {} - VRAM: {} MB".format(gpu_id, gpu_info['name'], gpu_info['vram']))
    else:
        print("No GPUs detected or an error occurred.")

# Your specs:
uOS = os.Caption
uGPU = get_gpu_name()
uCPU = get_cpu_name()
uCPU_Cores = psutil.cpu_count(logical=False)
uCPU_Fre = psutil.cpu_freq().current
uRAM = formatted_total_memory
uStorage = Storage
uGPU_Sto = vram_info


def show_welcome_screen():
    global welcome_label, next_button, smallerText
    welcome_label = tk.Label(
        root,
        text="Welcome to the Unpacker!",
        font=("Calibri", 42),
        pady=40

    )
    welcome_label.pack()

    smallerText = tk.Label(
        root,
        text="Welcome to <AppName> WorldoInstaller,to continue press NEXT 5 times!",
        font=("Arial", 24),
        pady=40
    )
    smallerText.pack()

    next_button = tk.Button(
        root,
        text="NEXT!",
        command=show_system_requirements_page,
        width=35,  # Increase width for horizontal size
        height=3,  # Increase height for vertical size
        font=("Arial", 14, "bold"),
        fg="white",
        bg="purple",
        padx=10,
        pady=5,
        relief="raised",
        activebackground="gray",
    )
    next_button.pack()

def show_system_requirements_page():
    welcome_label.pack_forget()
    next_button.pack_forget()
    smallerText.pack_forget()

    global system_requirements_label, os_label, gpu_label, cpu_label, ram_label, text_label, Recomended, Yours, os_label1, gpu_label1, cpu_label1, ram_label1, testte, sto_label, sto_label1, recCPU, recOS, recGPU, recRAM, recStorage, recCPU_Cores, recCPU_Fre, recGPU_VRAM, uOS, uGPU, uCPU, uCPU_Cores, uCPU_Cores, uCPU_Frem, uRAM, uStorage, uGPU_Sto, next_button1

    # Create a label for the title
    system_requirements_label = tk.Label(
        root,
        text="System Requirements:",
        font=("Arial", 48),
        pady=20
    )
    system_requirements_label.pack()
    system_requirements_label.place(x=0, y=60, width=1900, height=60)

    Recomended = tk.Label(
        root,
        text="Recommended System Specs:",
        font=("Arial", 28),
        pady=20
    )
    Recomended.pack()
    Recomended.place(x=50, y=140, width=500, height=50)

    Yours = tk.Label(
        root,
        text="You're System Specs:",
        font=("Arial", 28),
        pady=20
    )
    Yours.pack()
    Yours.place(x=1000, y=140, width=500, height=50)

    # Create labels for each requirement category
    os_label = tk.Label(
        root,
        text=f"Operating System: {recOS}",
        font=("Arial", 16)
    )
    os_label.pack()
    os_label.place(x=0, y=200, width=500, height=50)

    os_label1 = tk.Label(
        root,
        text=f"Operating System: {uOS}",
        font=("Arial", 16)
    )
    os_label1.pack()
    os_label1.place(x=900, y=200, width=500, height=50)

    gpu_label = tk.Label(
        root,
        text=f"Graphics Card (GPU): {recGPU} and {recGPU_VRAM}",
        font=("Arial", 16)
    )
    gpu_label.pack()
    gpu_label.place(x=0, y=250, width=600, height=50)

    gpu_label1 = tk.Label(
        root,
        text=f"Graphics Card (GPU): {uGPU} and {uGPU_Sto} VRAM",
        font=("Arial", 16)
    )
    gpu_label1.pack()
    gpu_label1.place(x=900, y=250, width=650, height=50)

    cpu_label = tk.Label(
        root,
        text=f"Processor (CPU): {recCPU} and {recCPU_Cores} and {recCPU_Fre}",
        font=("Arial", 16)
    )
    cpu_label.pack()
    cpu_label.place(x=0, y=300, width=600, height=50)

    cpu_label1 = tk.Label(
        root,
        text=f"Processor (CPU): {uCPU}",
        font=("Arial", 16)
    )
    cpu_label1.pack()
    cpu_label1.place(x=940, y=300, width=600, height=50)

    ram_label = tk.Label(
        root,
        text=f"Memory (RAM): {recRAM}",
        font=("Arial", 16)
    )
    ram_label.pack()
    ram_label.place(x=0, y=350, width=600, height=50)

    ram_label1 = tk.Label(
        root,
        text=f"Memory (RAM): {uRAM}",
        font=("Arial", 16)
    )
    ram_label1.pack()
    ram_label1.place(x=850, y=350, width=600, height=50)

    sto_label = tk.Label(
        root,
        text=f"Memory (RAM): {recStorage}",
        font=("Arial", 16)
    )
    sto_label.pack()
    sto_label.place(x=0, y=400, width=600, height=50)

    sto_label1 = tk.Label(
        root,
        text=f"Memory Storage: {uStorage}",
        font=("Arial", 16)
    )
    sto_label1.pack()
    sto_label1.place(x=900, y=400, width=500, height=80)

    next_button1 = tk.Button(
        root,
        text="NEXT!",
        command=optional_page,
        width=35,  # Increase width for horizontal size
        height=3,  # Increase height for vertical size
        font=("Arial", 14, "bold"),
        fg="white",
        bg="purple",
        padx=10,
        pady=5,
        relief="raised",
        activebackground="gray",
    )
    next_button1.pack(side="top", pady=10)

    def print_selection():
        print("Checkbox state:", var1.get())  # Assuming var1 is a tkinter IntVar


def print_selection():
    if (var1.get() == 1) & (var2.get() == 0) & (var3.get() == 0) & (var4.get() == 0) & (var5.get() == 0):
        print('Extract Optional1')
    elif (var1.get() == 0) & (var2.get() == 1) & (var3.get() == 0) & (var4.get() == 0) & (var5.get() == 0):
        print('Extract Optional2')
    elif (var1.get() == 0) & (var2.get() == 0) & (var3.get() == 1) & (var4.get() == 0) & (var5.get() == 0):
        print('Extract Optional3')
    elif (var1.get() == 0) & (var2.get() == 0) & (var3.get() == 0) & (var4.get() == 1) & (var5.get() == 0):
        print('Extract Optional4')
    elif (var1.get() == 0) & (var2.get() == 0) & (var3.get() == 0) & (var4.get() == 0) & (var5.get() == 1):
        print('Extract Optional5')


def optional_page():
    global system_requirements_label, os_label, gpu_label, cpu_label, ram_label, Recomended, Yours, \
        os_label1, gpu_label1, cpu_label1, ram_label1, sto_label, sto_label1, next_button1, app_name, mainreq, components_label, optional, c1, c2, c3, c4, c5, c6, c7, c8

    # Hide all elements related to the system requirements page:
    system_requirements_label.destroy()
    os_label.destroy()
    gpu_label.destroy()
    cpu_label.destroy()
    ram_label.destroy()
    Recomended.destroy()  # Hide "Recommended System Specs" label
    Yours.destroy()  # Hide "You're System Specs" label
    os_label1.destroy()
    gpu_label1.destroy()
    ram_label1.destroy()
    sto_label.destroy()
    cpu_label1.destroy()
    sto_label1.destroy()
    next_button1.destroy()  # Hide the "NEXT!" button
    root.update()
    # Now, you can create and display the optional page content:
    # Create the "Components" label for the optional page:
    components_label = tk.Label(
        root,
        text=f"{app_name} Components:",
        font=("Arial", 48),
        pady=20
    )
    components_label.pack()
    components_label.place(x=0, y=60, width=1900, height=60)

    # You can continue adding more elements for the optional page as needed

    mainreq = tk.Label(
        root,
        text="Requierd:",
        font=("Arial", 28),
        pady=20
    )
    mainreq.pack()
    mainreq.place(x=50, y=140, width=500, height=50)

    optional = tk.Label(
        root,
        text="Optional:",
        font=("Arial", 28),
        pady=20
    )
    optional.pack()
    optional.place(x=1000, y=140, width=500, height=50)

    c1 = tk.Checkbutton(root, text='Main Game', variable=var, onvalue=1, offvalue=0, command=None, state="disabled")
    c1.config(font=('Arial', 16))
    c1.pack()
    c1.place(x=10, y=200, width=500, height=50)

    c2 = tk.Checkbutton(root, text=f'{opt1NAME}', variable=var1, onvalue=1, offvalue=0, command=print_selection)
    c2.config(font=('Arial', 16))
    c2.pack()
    c2.place(x=900, y=200, width=500, height=50)

    c3 = tk.Checkbutton(root, text=f'{opt2NAME}', variable=var2, onvalue=1, offvalue=0, command=print_selection)
    c3.config(font=('Arial', 16))
    c3.pack()
    c3.place(x=900, y=250, width=500, height=50)

    c4 = tk.Checkbutton(root, text=f'{opt3NAME}', variable=var3, onvalue=1, offvalue=0, command=print_selection)
    c4.config(font=('Arial', 16))
    c4.pack()
    c4.place(x=900, y=300, width=500, height=50)

    c5 = tk.Checkbutton(root, text=f'{opt4NAME}', variable=var4, onvalue=1, offvalue=0, command=print_selection)
    c5.config(font=('Arial', 16))
    c5.pack()
    c5.place(x=900, y=350, width=500, height=50)

    c6 = tk.Checkbutton(root, text=f'{opt5NAME}', variable=var5, onvalue=1, offvalue=0, command=print_selection)
    c6.config(font=('Arial', 16))
    c6.pack()
    c6.place(x=900, y=400, width=500, height=50)

    next_button1 = tk.Button(
        root,
        text="NEXT!",
        command=show_extraction_screen,
        width=35,  # Increase width for horizontal size
        height=3,  # Increase height for vertical size
        font=("Arial", 14, "bold"),
        fg="white",
        bg="purple",
        padx=10,
        pady=5,
        relief="raised",
        activebackground="gray",
    )
    next_button1.pack(side="top", pady=10)


def show_extraction_screen():
    global welcome_label, next_button, smallerText, extract_button
    global mainreq, optional, c1, c2, c3, c4, c5, c6, components_label, next_button1, components_label2, mainreq2, c22, c33

    # Destroy the labels and checkboxes
    next_button1.destroy()
    components_label.destroy()
    mainreq.destroy()
    optional.destroy()
    c1.destroy()
    c2.destroy()
    c3.destroy()
    c4.destroy()
    c5.destroy()
    c6.destroy()
    welcome_label.pack_forget()
    next_button.pack_forget()
    smallerText.pack_forget()

    components_label2 = tk.Label(
        root,
        text=f"Extraction Path",
        font=("Arial", 48),
        pady=20
    )
    components_label2.pack()
    components_label2.place(x=0, y=60, width=1900, height=60)

    mainreq2 = tk.Label(
        root,
        text="Optional:",
        font=("Arial", 28),
        pady=20
    )
    mainreq2.pack()
    mainreq2.place(x=50, y=140, width=500, height=50)

    c22 = tk.Checkbutton(root, text="Create ShortCut", variable=shortcut_var1, onvalue=1, offvalue=0, command=print_selection)
    c22.config(font=('Arial', 16))
    c22.pack()
    c22.place(x=0, y=200, width=500, height=50)

    c33 = tk.Checkbutton(root, text='Create StartMenu ShortCut', variable=shortcut_var2, onvalue=1, offvalue=0, command=print_selection)
    c33.config(font=('Arial', 16))
    c33.pack()
    c33.place(x=0, y=250, width=500, height=50)

    extract_button = tk.Button(
        root,
        text="Choose Directory and Extract",
        command=extract_files,
        width = 35,  # Increase width for horizontal size
        height = 3,  # Increase height for vertical size
        font = ("Arial", 14, "bold"),
        fg = "white",
        bg = "purple",
        padx = 10,
        pady = 5,
        relief = "raised",
        activebackground = "gray",
    )
    extract_button.pack(pady=20)


installation_label = None


def animate_dots():
    if installation_label.cget("text") == f"{app_name} is installing...":
        installation_label.config(text=f"{app_name} is installing")
    else:
        installation_label.config(text=installation_label.cget("text") + ".")
    root.after(500, animate_dots)  # Update every 500 milliseconds


def simulate_installation():
    global installation_label
    installation_label.config(text=f"{app_name} is installing...")
    root.update()

    # Your installation logic goes here
    # This is just a placeholder
    import time
    time.sleep(5)  # Simulate installation process taking 5 seconds
    root.update()

def buttonclose():
    extract_button_close = tk.Button(
        root,
        text="Close!",
        command=root.destroy,
        width=35,  # Increase width for horizontal size
        height=3,  # Increase height for vertical size
        font=("Arial", 14, "bold"),
        fg="white",
        bg="purple",
        padx=10,
        pady=5,
        relief="raised",
        activebackground="gray",
    )
    extract_button_close.pack(pady=20)

def extract_files():
    global shortcut_var1, extract_button, c33, c22, mainreq2, components_label2, status, installation_label, extract_buttonCLOSE
    output_directory_function = filedialog.askdirectory()
    if not output_directory_function:
        print("No directory selected.")
        return


    if callable(output_directory_function):  # Check if the returned object is a function
        output_directory = output_directory_function()  # Call the function to get the directory path
    else:
        output_directory = output_directory_function

    if output_directory:
        extract_button.destroy()
        c33.destroy()
        c22.destroy()
        mainreq2.destroy()
        components_label2.destroy()

        if installation_label is None:
            installation_label = tk.Label(
                root,
                text=f"{app_name} is installing...",
                font=("Arial", 48),
                pady=20
            )
            installation_label.pack()


        # Simulate installation process
        simulate_installation()

        # Extract main file
        config = configparser.ConfigParser()
        config.read("config.ini")
        fileName = config.get('Settings', 'fileName')

        # Configure the progress bar
        progress = ttk.Progressbar(root, orient='horizontal', length=300, mode='determinate')
        # Configure the progress bar using pack with the correct options
        progress.pack(fill='x', padx=2, pady=2)
        progress_label = tk.Label(root, text="Extracting...")
        progress_label.pack(fill='x', padx=2, pady=2)

        # Function to update the progress bar
        def update_progress_bar(value):
            progress['value'] = value
            root.update_idletasks()

        # Function to handle the extraction process
        def extract():
            patoolib.extract_archive(fileName, outdir=output_directory)
            update_progress_bar(100)  # Set the progress bar to 100% after extraction

        # Start the extraction process in a separate thread
        threading.Thread(target=extract).start()

        # Start the Tkinter main loop
        root.update()

        # Progress Bar
        with tqdm(total=1, desc="Extracting", unit="file") as pbar:
            patoolib.extract_archive(fileName, outdir=output_directory)
            pbar.update(1)  # Update the progress bar
            update_progress_bar(100)  # Set the progress bar to 100% after extraction
            installation_label.config(text=f"{app_name} was successfully installed!\nNow you can Close the App. \n (Press the Red Button) ")

        # Extract optional files based on selected checkboxes
        optional_files = [
            ("Optional1", var1.get(), "Optional1"),  # (Config key, checkbox variable, path variable)
            ("Optional2", var2.get(), "Optional2"),
            ("Optional3", var3.get(), "Optional3"),
            ("Optional4", var4.get(), "Optional4"),
            ("Optional5", var5.get(), "Optional5"),
        ]

        for config_key, is_checked, path_var in optional_files:
            if is_checked:
                opt_path = config.get("Optional", config_key)  # Get path from config
                patoolib.extract_archive(f"{opt_path}", outdir=output_directory)


        if shortcut_var1.get() == 1:
            # Get the name of the executable from the config file
            executable_name = config.get("Settings", "Shortcut")
            # Create the full path to the executable
            executable_path = (f"{output_directory}/{executable_name}")
            # Create the shortcut using winshell
            shortcut_path = winshell.desktop() + "\\" + "SharpShooter3D - www.worldtorrent.000.pe.lnk"
            with winshell.shortcut(shortcut_path) as shortcut:
                shortcut.path = executable_path
                shortcut.description = f"Shortcut for {app_name}"
                # You can set other properties of the shortcut as needed
            print(f"Shortcut created at: {shortcut_path}")

        if shortcut_var2.get() == 1:
            username = getpass.getuser()
            executable_path2 = (f"{output_directory}/{executable_name}")
            shortcut_path2 = winshell.start_menu() + "\\" + "SharpShooter3D - www.worldtorrent.000.pe.lnk"
            with winshell.shortcut(shortcut_path2) as shortcut:
                shortcut.path = executable_path2
                shortcut.description = f"Shortcut for {app_name}"
                # You can set other properties of the shortcut as needed
            print(f"Shortcut created at: {shortcut_path2}")
            buttonclose()

def translate_text(text, target_language):
    print("Still working :(")


pygame.mixer.init()


def play_music():
    pygame.mixer.music.load(music)  # Load the music file
    pygame.mixer.music.play(-1)  # Play the music indefinitely (looping)


global playing
playing = False  # Start with music paused
global mainreq, optional, c1, c2, c3, c4, c5, c6, components_label, next_button1

def mute():
    global playing, volume
    if playing:
        pygame.mixer.music.stop()  # Stop the music specifically
        volume = 0  # Set volume to 0 when stopped
        music_button.config(bg="red", text="Start Music")  # Configure the music button directly
        playing = False
    else:
        play_music()  # Call the existing play_music function
        music_button.config(bg="green", text="Stop Music")  # Configure the music button directly
        playing = True


root.title(f"{app_name} Installer")  # Set the window title with AppName
root.wm_maxsize(width=root.winfo_screenwidth(), height=root.winfo_screenheight())
root.wm_minsize(width=root.winfo_screenwidth(), height=root.winfo_screenheight())
title_bar = tk.Frame(root, bg="gray", height=40)  # Gray background, 40 pixels high
title_bar.pack(fill=tk.X)  # Pack it at the top, filling the entire width
close_button = tk.Button(title_bar, text=" ", bg="red", width=20, height=2, fg="white", command=root.destroy)
close_button.pack(side=tk.RIGHT, padx=5)  # Pack to the right with some padding
minimize_button = tk.Button(title_bar, text=" ", bg="blue", width=20, height=2, fg="white", command=root.iconify)
minimize_button.pack(side=tk.LEFT)

title_label = tk.Label(
    title_bar,
    text="Your Title Here",  # Replace with your desired text
    font=("Arial", 16, "bold"),  # Adjust font as needed
    fg="white",  # Set text color (white in this example)
    bg="gray",  # Set background color (gray in this example)
    bd=0,  # Remove border
    anchor=tk.CENTER  # Center the text within the label
)

footer_bar = tk.Frame(root, bg="gray", height=40)
footer_bar.pack(side=tk.BOTTOM, fill=tk.X)
music_button = tk.Button(footer_bar, text="Start Music" if not playing else "Stop Music",
                         bg="green" if not playing else "red", width=20, height=2, fg="white", command=mute)
music_button.pack(side=tk.LEFT, padx=5)
lau_button = tk.Button(footer_bar, text="", bg="orange", width=20, height=2, fg="white", command=translate_text)
lau_button.pack(side=tk.RIGHT)
show_welcome_screen()  # Start with the welcome screen
title_label.pack(expand=True)
title_label.config(text=f"{app_name} Worldo Installer - Beta_v1")
welcome_label.config(text=f"{app_name} Installer Setup")
smallerText.config(text=f"Welcome to {app_name} WorldoInstaller\nPress NEXT to continue ")
canvas = tk.Canvas(root, width=root.winfo_width(), height=root.winfo_height())
canvas.pack(fill="both", expand=True)

# Create the canvas and place it at the bottom (adjust as needed)
canvas = tk.Canvas(root, width=800, height=600, bg="gray")
canvas.place(relx=0, rely=1, relwidth=1, relheight=1)  # Fill the bottom part

root.mainloop()
```

**Comment by rokm** [comment]
```
 Error loading python DLL "C\Users\Administrator\Documents\IT\Python\pythonProject3\biuld\main_internal\python311.dll". LoadLibrary: The specified moudle couldnot be found``
```

Are you trying to run the executable in the `build` directory instead of the one in `dist` directory?

**Comment by rokm** [comment]
Also, your spec file is wrong:
```
          exclude_binaries=True,
```
`exclude_binaries` should be `False` in onefile builds. And you need to pass `a.datas` and `a.binaries` to `EXE` as well. In your case, the executable ends up running in onedir mode, and looking for external python shared library.

Use `pyinstaller` or `pyi-makespec` with all the command-line options (that you listed at the start) to generate a valid onefile spec for you, and use that.

**Comment by AlexiJemano** [comment]
So like now compiling is working better I use this prompt

`pyinstaller --noconfirm --onedir --console --icon "C:/Users/Administrator/Documents/IT/Python/pythonProject3/data/worldtorrent.ico" --add-data "C:/Users/Administrator/Documents/IT/Python/pythonProject3/data;data/" --add-data "C:/Users/Administrator/Documents/IT/Python/pythonProject3/config.ini;."  "C:/Users/Administrator/Documents/IT/Python/pythonProject3/main.py"`

but when I run the .exe I get an error:
[
![Screenshot (101)](https://github.com/pyinstaller/pyinstaller/assets/157528500/f032849d-0dc3-4135-b264-007616004a09)
](url)

The problem is that the config.ini dose exist in _internal and all the data is there so I dont know why it dosent read it (so if you didnt understand the configpaser moudule is a python moudule that allow you to work with .ini files, when i test it localy as a .py the program works fine but when I compile it in to a .exe it says that the section in the .ini file named "Settings" dosent exist)

**Comment by rokm** [comment]
Can we see the code that tries to load that .ini file? 

My first guess would be that you are trying to read it with relative path, e.g., 

```
config.read('config.ini')
```

instead of anchoring the path, e.g., 

```
config.read(os.path.join(os.path.dirname(__file__), 'config.ini'))
```

as described [in documentation](https://pyinstaller.org/en/stable/runtime-information.html#using-file)...

**Comment by AlexiJemano** [comment]
yea sure the config.ini:

```
[Settings]
fileName: data/SharpShooter3D Extreme Edition.7z
; The location of the archive
outputLocation: C:\Ghost Toolbox
; DONT TOUCH! it will overwrite the information when user is asked where to extract
AppName: SharpShooter3D Extreme Edition
; The name of the Game
Shortcut: SharpShooter3D Extreme Edition\SharpShooter3D\SharpShooter3D Extreme Edition.exe
; The location of the main .exe
; NOTE!!
; Please include the main folder or the Shortcut will not work!
Music: data/piano.mp3
[Recommended-System-Req]
OS: Windows XP, Vista, 7, 8, 10, 11
Processor: Intel Core 3 Duo
Memory: 2 GB RAM
Graphics: AMD RADEON C26411
Storage: 300 MB available space
CPU_Cores: 2 Cores
CPU_Fre: 1.8 GHz
GPU_VRAM: 1GB VRAM
; Self explanitory get the info from Steam, Epic Games, etc

[Optional]
; IF YOU HAVE ADITIONAL CONTENT LIKE OST, DEMO GANE, ETC PUT THE HERE AS THE EXEMPLE
Optional1: data/SharpShooter3D OST.7z
Optional1_Name: SharpShooter3D OST
Optional2: EMPTY
Optional2_Name: EMPTY
Optional3: EMPTY
Optional3_Name: EMPTY
Optional4: EMPTY
Optional4_Name: EMPTY
Optional5: EMPTY
Optional5_Name: EMPTY
```
And I tried to use` config.read(os.path.join(os.path.dirname(__file__), 'config.ini'))` but dosent work same error

**Comment by rokm** [comment]
I asked for code that loads the .ini file (so I can see how you are trying to load it), not the .ini file itself...

Can you add an explicit check whether config file exists (`os.path.isfile`) before trying to load it? Or load the file and dump its contents? Because as far as I can tell, if the file does not exist, `configparser` does not raise an error, but you would get missing section/entry error later on.

**Comment by AlexiJemano** [comment]
Oh sorry there you go: (I also give a little bit of the code where i show how I use data from .ini to create variables or to use some data)
```
config = configparser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), 'config.ini'))
app_name = config.get("Settings", "AppName")
button_image = tk.PhotoImage(file="data/button.png")
# Creating an app with a theme: this is the ThemedTk object
# The theme will applied to every ttk widget in your application
recOS = config.get("Recommended-System-Req", "OS")
recGPU = config.get("Recommended-System-Req", "Graphics")
recCPU = config.get("Recommended-System-Req", "Processor")
recRAM = config.get("Recommended-System-Req", "Memory")
recStorage = config.get("Recommended-System-Req", "Storage")
recCPU_Cores = config.get("Recommended-System-Req", "CPU_Cores")
recCPU_Fre = config.get("Recommended-System-Req", "CPU_Fre")
recGPU_VRAM = config.get("Recommended-System-Req", "GPU_VRAM")
```

**Comment by rokm** [comment]
What if you change this part
```
config = configparser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), 'config.ini'))
```

into

```
config_file = os.path.join(os.path.dirname(__file__), 'config.ini') 
print(f"Config file: {config_file}")
assert os.path.isfile(config_file), f"Config file {config_file} does not exit!")

config = configparser.ConfigParser()
config.read(config_file)
```

Does the code make it past the assert? And does the the printed config file name point to the correct location?

**Comment by AlexiJemano** [comment]
Yes it dose make past the assert - `Config file: C:\Users\Administrator\Documents\IT\Python\pythonProject3\config.ini` (The Output I get and the program works fine locally) 

Also I edited your code because it gave syntax problems:
```
config_file = os.path.join(os.path.dirname(__file__), 'config.ini')
print(f"Config file: {config_file}")
assert os.path.isfile(config_file), f"Config file {config_file} does not exist!"  # Added closing parenthesis

config = configparser.ConfigParser()
config.read(config_file)
```

So I was able to compile it and actually to see the tkinter windows I also see that my program can work with config.ini I see all of the varibles but it for some reasone dont works with data folder. It is showing that it dosent exist. But in _internal folder I see it.

**Comment by AlexiJemano** [comment]
the error:
```
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "main.py", line 683, in mute
  File "main.py", line 667, in play_music
pygame.error: No file 'data/piano.mp3' found in working directory 'C:\Users\Administrator\Documents\IT\Python\pythonProject3\dist\main'.
```

**Comment by AlexiJemano** [comment]
Also I see that this is the problem with the directory at the end it should be \main\_internal\

**Comment by rokm** [comment]
> ``` 
> pygame.error: No file 'data/piano.mp3' found in working directory 'C:\Users\Administrator\Documents\IT\Python\pythonProject3\dist\main'.
> ``` 

That looks like another case of a file being referenced with relative path that relies on current working directory. That won't work with PyInstaller - you have to use absolute paths that are anchored to `__file__`.

**Comment by AlexiJemano** [comment]
I simply put the data folder in dist\main so it fixed. Thanks for everything💕!
