### ISSUE TITLE
pyintaller dosent want to work with patoolib

### ISSUE THREAD

**Issue by AlexiJemano** [pyinstaller/pyinstaller#8384]
so I have a py program that uses patoolib to extract a file and in pycharm it works fine but when I use pyinstaller it dosent want to work.

1.Pyinstaller Prompt:

`pyinstaller --noconfirm --onedir --console --icon "C:/Users/Administrator/Documents/IT/Python/pythonProject3/data/worldtorrent.ico" --add-data "C:/Users/Administrator/Documents/IT/Python/pythonProject3/data;data/" --add-data "C:/Users/Administrator/Documents/IT/Python/pythonProject3/config.ini;." --hidden-import "C:/Users/Administrator/Documents/IT/Python/pythonProject3/hook-patoolib.py"  # I put the directory to the hidden imports "C:/Users/Administrator/Documents/IT/Python/pythonProject3/main.py" `

2. Error:

```
INFO patool: Extracting data/SharpShooter3D Extreme Edition.7z ...      # YOU CAN SEE THAT THE PROGRAM SEESS THE FILE
Exception in thread Thread-1 (extract):                                                    
Traceback (most recent call last):
  File "patoolib\__init__.py", line 647, in get_archive_cmdlist_func
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'patoolib.programs'                    # Error caused bc moudule not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "main.py", line 601, in extract
Extracting:   0%|                                                                              | 0/1 [00:00<?, ?file/s]  File "patoolib\__init__.py", line 794, in extract_archive
INFO patool: Extracting data/SharpShooter3D Extreme Edition.7z ...                         # I think the tries agine
Extracting:   0%|                                                                              | 0/1 [00:00<?, ?file/s]          # And it starts showing the progress bar
Exception in Tkinter callback
  File "patoolib\__init__.py", line 564, in _extract_archive
  File "patoolib\__init__.py", line 650, in get_archive_cmdlist_func
patoolib.util.PatoolError: cannot import module .programs.p7zip in patoolib
Traceback (most recent call last):
  File "patoolib\__init__.py", line 647, in get_archive_cmdlist_func
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'patoolib.programs'                                    # Same error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "main.py", line 612, in extract_files
  File "patoolib\__init__.py", line 794, in extract_archive
  File "patoolib\__init__.py", line 564, in _extract_archive
  File "patoolib\__init__.py", line 650, in get_archive_cmdlist_func
patoolib.util.PatoolError: cannot import module .programs.p7zip in patoolib                            # Same error
```
Hidden-Imports file:
```

#-----------------------------------------------------------------------------
# Copyright (c) 2013-2017, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


"""
patoolib uses importlib and pyinstaller doesn't find it and add it to the list of needed modules
"""


hiddenimports = [
    'patoolib.programs',
    'patoolib.programs.ar',
    'patoolib.programs.arc',
    'patoolib.programs.archmage',
    'patoolib.programs.bsdcpio',
    'patoolib.programs.bsdtar',
    'patoolib.programs.bzip2',
    'patoolib.programs.cabextract',
    'patoolib.programs.chmlib',
    'patoolib.programs.clzip',
    'patoolib.programs.compress',
    'patoolib.programs.cpio',
    'patoolib.programs.dpkg',
    'patoolib.programs.flac',
    'patoolib.programs.genisoimage',
    'patoolib.programs.gzip',
    'patoolib.programs.isoinfo',
    'patoolib.programs.lbzip2',
    'patoolib.programs.lcab',
    'patoolib.programs.lha',
    'patoolib.programs.lhasa',
    'patoolib.programs.lrzip',
    'patoolib.programs.lzip',
    'patoolib.programs.lzma',
    'patoolib.programs.lzop',
    'patoolib.programs.mac',
    'patoolib.programs.nomarch',
    'patoolib.programs.p7azip',
    'patoolib.programs.p7rzip',
    'patoolib.programs.p7zip',
    'patoolib.programs.pbzip2',
    'patoolib.programs.pdlzip',
    'patoolib.programs.pigz',
    'patoolib.programs.plzip',
    'patoolib.programs.py_bz2',
    'patoolib.programs.py_echo',
    'patoolib.programs.py_gzip',
    'patoolib.programs.py_lzma',
    'patoolib.programs.py_tarfile',
    'patoolib.programs.py_zipfile',
    'patoolib.programs.rar',
    'patoolib.programs.rpm',
    'patoolib.programs.rpm2cpio',
    'patoolib.programs.rzip',
    'patoolib.programs.shar',
    'patoolib.programs.shorten',
    'patoolib.programs.star',
    'patoolib.programs.tar',
    'patoolib.programs.unace',
    'patoolib.programs.unadf',
    'patoolib.programs.unalz',
    'patoolib.programs.uncompress',
    'patoolib.programs.unrar',
    'patoolib.programs.unshar',
    'patoolib.programs.unzip',
    'patoolib.programs.xdms',
    'patoolib.programs.xz',
    'patoolib.programs.zip',
    'patoolib.programs.zoo',
    'patoolib.programs.zopfli',
    'patoolib.programs.zpaq',
]
```
I also tried with a smaller one:

`hiddenimports = ['patoolib.programs', 'patoolib.programs.ar', 'patoolib.programs.arc', 'patoolib.programs.p7zip'] `

**Comment by rokm** [comment]
> --hidden-import "C:/Users/Administrator/Documents/IT/Python/pythonProject3/hook-patoolib.py"

`--hidden-import` is used to verbatim specify hidden imports (`--hidden-import patoolib.programs.ar --hiddenimport patoolib.programs.arc`, and so on); you cannot use it to specify a path to hook - that's done via [--additional-hooks-dir](https://pyinstaller.org/en/stable/usage.html#cmdoption-additional-hooks-dir).

And you don't really need a hook there, you can just add [`--collect-submodules patoolib.programs`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-submodules) to your PyInstaller command.
