### ISSUE TITLE
PyInstaller and 

### ISSUE THREAD

**Issue by happymvd** [pyinstaller/pyinstaller#8392]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(6.5.2)```
* Version of Python: 
* Platform: <!--  Windows 
* How you installed Python: <!-- python.org/downloads>
* Did you also try this on another platform? Does it work there? No, I only have access to Windows

### A minimal example program which shows the error
I am working on a Windows 11 computer with Python 3.11.9 installed as the only version of Python
I am working in Virtual Studio Code
I have created and activated a venv virtual environment for my project (not a conda one)
I used the pip command to install xarray into the virtual environment
I have a test script called Testing.py and the only thing it does is "import xarray as xr" and then it prints a message to the terminal window
This works 100% in python in the VSC terminal window
I then issue the following command
pyinstaller --onefile Testing.py

This creates a file called Testing.exe for me
When I run Testing.exe I get the following error message shown below

Please, is there anyone who can suggest what I need to do to get around this problem .... I need to distribute my project when it is complete
```
(My code)
import xarray as xr
import datetime as dt
import os
import sys
print('this is working')
```

### Stacktrace / full error message

**Traceback (most recent call last):
File "importlib\metadata_init_.py", line 563, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Testing.py", line 20, in
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "xarray_init_.py", line 3, in
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "xarray\testing_init_.py", line 1, in
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "xarray\testing\assertions.py", line 11, in
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "xarray\core\duck_array_ops.py", line 36, in
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "xarray\core\dask_array_ops.py", line 3, in
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "xarray\core\nputils.py", line 14, in
File "xarray\namedarray\utils.py", line 60, in module_available
File "importlib\metadata_init_.py", line 1009, in version
File "importlib\metadata_init_.py", line 982, in distribution
File "importlib\metadata_init_.py", line 565, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for numpy
[15596] Failed to execute script 'Testing' due to unhandled exception!**

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Looks like `xarray` is trying to query `numpy` version via its metadata, which is not collected by default. Try adding [`--copy-metadata numpy`](https://pyinstaller.org/en/stable/usage.html#cmdoption-copy-metadata) to your PyInstaller command.

**Comment by happymvd** [comment]
Thank you that worked well
