### ISSUE TITLE
Patoolib - Error AttributeError: 'NoneType' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by H1ghSyst3m** [pyinstaller/pyinstaller#8398]
## Description of the issue
I compiled a code that uses patoolib. 

If I start the code directly through python, it works perfect with no problems, but if I start the .exe then I get a error

### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.5.0
* Version of Python: 3.10.6
* Platform: Windows 11
* How you installed Python: python.org
* Did you also try this on another platform? Not tried

* try the latest development version, using the following command:

### Stacktrace / full error message
After starting the .exe, I get:

```
Traceback (most recent call last):
  File "MainScript.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "Assets\Modules\FileCreator.py", line 21, in <module>
    import patoolib
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "patoolib\__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "patoolib\fileutil.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "patoolib\log.py", line 40, in <module>
AttributeError: 'NoneType' object has no attribute 'encoding'
```

I also already made a hook for patoolib from the previous patoolib problem

I package the Script with: `pyinstaller --windowed --icon="Assets/Images/logo/x128.ico" --add-data "Assets/Modules;Assets/Modules" --add-data "Assets/Images;Assets/Images" MainScript.py`

**Comment by rokm** [comment]
That's a bug in `patoolib` - it is trying to access `encoding` attribute of `sys.stderr` [here](https://github.com/wummel/patool/blob/4c43466eb0b8895eb48c3406fa3b6d93a06dfc85/patoolib/log.py#L40) without first ensuring that it is not `None`. Which is the case when you use `--windowed` mode (or run your code with `pythonw.exe` instead of `python.exe`).

Report the bug to `patool`; for a work-around, see [this section of our docs](https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#sys-stdin-sys-stdout-and-sys-stderr-in-noconsole-windowed-applications-windows-only).

**Comment by H1ghSyst3m** [comment]
Thanks. I could make a workaround :D
