### ISSUE TITLE
Compile python2 

### ISSUE THREAD

**Issue by Aggelos11** [pyinstaller/pyinstaller#8400]
Hi ! I tried to compile a python 2 python script using pyinstaller but I get the following error. Does anyone know the cause of this and the solution ?

pyinstaller --onefile ZReporter.py
433 INFO: PyInstaller: 3.3.1
434 INFO: Python: 2.7.18
438 INFO: Platform: Linux-5.18.0-kali7-amd64-x86_64-with-debian-kali-rolling
440 INFO: wrote /opt/ZReporter/ZReporter.spec
497 INFO: UPX is available.
516 INFO: Extending PYTHONPATH with paths
['/opt/ZReporter', '/opt/ZReporter']
540 INFO: checking Analysis
545 INFO: Building Analysis because out00-Analysis.toc is non existent
547 INFO: Initializing module dependency graph...
558 INFO: Initializing module graph hooks...
724 INFO: running Analysis out00-Analysis.toc
838 INFO: Caching module hooks...
848 INFO: Analyzing /opt/ZReporter/ZReporter.py
4821 INFO: Loading module hooks...
4822 INFO: Loading module hook "hook-httplib.py"...
4823 INFO: Loading module hook "hook-encodings.py"...
5714 INFO: Looking for ctypes DLLs
5715 INFO: Analyzing run-time hooks ...
5727 INFO: Looking for dynamic libraries
6069 INFO: Looking for eggs
6069 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
File "/usr/local/bin/pyinstaller", line 8, in
sys.exit(run())
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/main.py", line 94, in run
run_build(pyi_config, spec_file, **vars(args))
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/main.py", line 46, in run_build
PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 791, in main
build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 737, in build
exec(text, spec_namespace)
File "", line 16, in
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 213, in init
self.postinit()
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/datastruct.py", line 161, in postinit
self.assemble()
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 545, in assemble
self._check_python_library(self.binaries)
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 614, in _check_python_library
python_lib = bindepend.get_python_library_path()
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/bindepend.py", line 880, in get_python_library_path
python_libname = findLibrary(name)
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/bindepend.py", line 765, in findLibrary
utils.load_ldconfig_cache()
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/utils.py", line 380, in load_ldconfig_cache
path = m.groups()[-1]
AttributeError: 'NoneType' object has no attribute 'groups'
does anyone know the solution to this ?
 
 
Somebody told me that version of pyinstaller that supported python 2 no longer work . So how am I going to compile python 2 code using pyinstaller (to make an executable for Linux )?

**Comment by bwoodsend** [comment]
Python 2 is not supported. Nor are ancient versions of PyInstaller. If you're determined to stick to obsolete software then you're on your own.
