### ISSUE TITLE
DLL load failed with very specific library

### ISSUE THREAD

**Issue by mtsamorim** [pyinstaller/pyinstaller#8405]
Hello guys, I recently created a program that uses several libraries related in some way to geology or geospatial data, and the files that my program reads are .nc or .nc4, it is running perfectly if I run it myself using a command like
`python program.py`
So I decided to create an executable of it with pyinstaller and at first everything seemed to go well, the program's interface opens perfectly, but when it gets to the part where it appears that it uses netCDF4, which is the part that reads .nc4 files, some kind of error which I am leaving below.

```
Exception in Tkinter callback
Traceback (most recent call last):
File "tkinter_init.py", line 1892, in call
File "interface.py", line 251, in
File "interface.py", line 603, in select_variables
File "interface.py", line 49, in init
File "interface.py", line 75, in read_variables_from_netcdf
File "xarray\backends\api.py", line 541, in open_dataset
File "xarray\backends\netCDF4_.py", line 578, in open_dataset
File "xarray\backends\netCDF4_.py", line 349, in open
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "netCDF4_init_.py", line 31, in
ImportError: DLL load failed while importing netCDF4: The specified module could not be found.
```

I've tried everything when I can, I've already passed several variables on the pyinstaller command line when generating the executable, but even so, when it gets to this part of the program, it gives me this error, would anyone have any idea what it could be and how to fix it? ? I even went so far as to create another environment in conda to install everything again to see if the problem was the previous environment but it continues, I will be extremely grateful if someone helps me with this persistent and annoying error that only happens in the program's executable, as the code is working perfectly

I really needed this program as an executable, but it is giving an error in this specific library

**Comment by rokm** [comment]
Can you reproduce the problem if you build the following program in your environment?

```python
import netCDF4
print(netCDF4)
```

If so, can you attach full build log?

What version of `netCDF4` are you using?

**Comment by mtsamorim** [comment]
> Can you reproduce the problem if you build the following program in your environment?
> 
> ```python
> import netCDF4
> print(netCDF4)
> ```
> 
> If so, can you attach full build log?
> 
> What version of `netCDF4` are you using?

Hello, sorry I didn't understand very well.

Do you want me to create a code with just

import netCDF4
print(netCDF4)

and create a build and pass the Logs? In this case, the lines when creating the program?

My version is 1.6.5

**Comment by rokm** [comment]
Yes, I want you to try building and running that two-line test program with your python + PyInstaller environment. And if the test program has the same "DLL load failed" error, attach the PyInstaller's build log here.

Are you perhaps using Anaconda python 3.8 or 3.9?

**Comment by mtsamorim** [comment]
> Yes, I want you to try building and running that two-line test program with your python + PyInstaller environment. And if the test program has the same "DLL load failed" error, attach the PyInstaller's build log here.
> 
> Are you perhaps using Anaconda python 3.8 or 3.9?

I created the program with just these two lines

when I run `python test.py` it returns this, operating normally
<module 'netCDF4' from 'C:\\Users\\malva\\anaconda3\\envs\\my_new_env\\lib\\site-packages\\netCDF4\\__init__.py'>

Now using pyinstaller:

These are the lines from when the build was being created
```
4212 INFO: PyInstaller: 6.5.0, contrib hooks: 2024.3
4212 INFO: Python: 3.8.19 (conda)
4227 INFO: Platform: Windows-10-10.0.19045-SP0
4227 INFO: wrote C:\Users\malva\Documents\nettest\net.spec
4274 INFO: Extending PYTHONPATH with paths
['C:\\Users\\malva\\Documents\\nettest']
5337 INFO: checking Analysis
5337 INFO: Building Analysis because Analysis-00.toc is non existent
5337 INFO: Initializing module dependency graph...
5352 INFO: Caching module graph hooks...
5618 INFO: Analyzing base_library.zip ...
14381 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
14928 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
21482 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
24298 INFO: Caching module dependency graph...
24691 INFO: Running Analysis Analysis-00.toc
24707 INFO: Looking for Python shared library...
24722 INFO: Using Python shared library: C:\Users\malva\anaconda3\envs\meu_novo_env\python38.dll
24722 INFO: Analyzing C:\Users\malva\Documents\nettest\net.py
24738 INFO: Loading module hook 'hook-netCDF4.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
24864 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
24875 INFO: Processing module hooks...
24961 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Lib\\site-packages\\numpy\\_pyinstaller'...
27280 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
28008 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
29652 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
30558 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
33761 INFO: Loading module hook 'hook-cftime.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
33777 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
34089 INFO: Performing binary vs. data reclassification (99 entries)
34480 INFO: Looking for ctypes DLLs
34527 INFO: Analyzing run-time hooks ...
34527 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
34543 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
34558 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks'...
34558 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
34558 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
34605 INFO: Looking for dynamic libraries
C:\Users\malva\anaconda3\envs\meu_novo_env\lib\site-packages\PyInstaller\building\build_main.py:199: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
36723 INFO: Extra DLL search directories (AddDllDirectory): []
36724 INFO: Extra DLL search directories (PATH): []
42341 WARNING: Library not found: could not resolve 'ze_loader.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\omptarget.rtl.level0.dll'.
42341 WARNING: Library not found: could not resolve 'msmpi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\mkl_blacs_msmpi_lp64.2.dll'.
42341 WARNING: Library not found: could not resolve 'sycl6.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\omptarget.sycl.wrap.dll'.
42341 WARNING: Library not found: could not resolve 'impi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\mkl_blacs_intelmpi_lp64.2.dll'.
42341 WARNING: Library not found: could not resolve 'pgmath.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\mkl_pgi_thread.2.dll'.
42356 WARNING: Library not found: could not resolve 'pgc.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\mkl_pgi_thread.2.dll'.
42356 WARNING: Library not found: could not resolve 'pgf90.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\mkl_pgi_thread.2.dll'.
42356 WARNING: Library not found: could not resolve 'impi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\mkl_blacs_intelmpi_ilp64.2.dll'.
42356 WARNING: Library not found: could not resolve 'msmpi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\Library\\bin\\mkl_blacs_msmpi_ilp64.2.dll'.
42356 WARNING: Library not found: could not resolve 'hdf5-77cabd2d0cdda3b9e5a90cdef3b85990.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\netCDF4\\_netCDF4.cp38-win_amd64.pyd'.
42356 WARNING: Library not found: could not resolve 'netcdf-bee8b573bfb889c39210c1197a881861.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\meu_novo_env\\lib\\site-packages\\netCDF4\\_netCDF4.cp38-win_amd64.pyd'.
42419 INFO: Warnings written to C:\Users\malva\Documents\nettest\build\net\warn-net.txt
42622 INFO: Graph cross-reference written to C:\Users\malva\Documents\nettest\build\net\xref-net.html
42731 INFO: checking PYZ
42731 INFO: Building PYZ because PYZ-00.toc is non existent
42731 INFO: Building PYZ (ZlibArchive) C:\Users\malva\Documents\nettest\build\net\PYZ-00.pyz
44575 INFO: Building PYZ (ZlibArchive) C:\Users\malva\Documents\nettest\build\net\PYZ-00.pyz completed successfully.
44638 INFO: checking PKG
44638 INFO: Building PKG because PKG-00.toc is non existent
44638 INFO: Building PKG (CArchive) net.pkg
44685 INFO: Building PKG (CArchive) net.pkg completed successfully.
44685 INFO: Bootloader C:\Users\malva\anaconda3\envs\meu_novo_env\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
44685 INFO: checking EXE
44685 INFO: Building EXE because EXE-00.toc is non existent
44685 INFO: Building EXE from EXE-00.toc
44685 INFO: Copying bootloader EXE to C:\Users\malva\Documents\nettest\build\net\net.exe
44981 INFO: Copying icon to EXE
45122 INFO: Copying 0 resources to EXE
45122 INFO: Embedding manifest in EXE
45247 INFO: Appending PKG archive to EXE
45263 INFO: Fixing EXE headers
46106 INFO: Building EXE from EXE-00.toc completed successfully.
46122 INFO: checking COLLECT
46122 INFO: Building COLLECT because COLLECT-00.toc is non existent
46122 INFO: Building COLLECT COLLECT-00.toc
59675 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

And now the error that appears when I run test.exe in the dist folder
```
Traceback (most recent call last):
  File "net.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "netCDF4\__init__.py", line 31, in <module>
ImportError: DLL load failed while importing _netCDF4: The specified module could not be found.
[11208] Failed to execute script 'net' due to unhandled exception!
```

I hope that's it my friend, I tried looking for a log.txt file but I couldn't find it

Versions I'm using in my environment
Python [3.8.19]
pyinstaller  [6.5.0]       
pyinstaller-hooks-contrib [2024.3]
netcdf4 [1.6.5]
numpy [1.24.3] 

I created a new environment and installed all the libraries thinking the error was due to the previous environment but it still continues,

**Comment by rokm** [comment]
The problem is that Anaconda python 3.8 and 3.9 have defunct `os.add_dll_directory()`, and then `delvewheel` (which is used by `netCDF4` to bundle DLLs on Windows needs to load the DLLs in a way that requires extra files to be collected.

If you can switch to python 3.10 or later, it should work out of the box. Same if you switch to python.org python 3.8.

If you absolutely need to stay with your Anaconda python 3.8, then you will need to edit `hook-netCDF4.py` in `C:\Users\malva\anaconda3\envs\meu_novo_env\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks`, and add the following at the end:
```python
from PyInstaller.utils.hooks import collect_delvewheel_libs_directory
datas, binaries = collect_delvewheel_libs_directory("netCDF4")
```

I.e., after changes, the file should look like:
```python
# ------------------------------------------------------------------
# Copyright (c) 2020 PyInstaller Development Team.
#
# This file is distributed under the terms of the GNU General Public
# License (version 2.0 or later).
#
# The full license is available in LICENSE.GPL.txt, distributed with
# this software.
#
# SPDX-License-Identifier: GPL-2.0-or-later
# ------------------------------------------------------------------

from PyInstaller.utils.hooks import is_module_satisfies

# netCDF4 (tested with v.1.1.9) has some hidden imports
hiddenimports = ['netCDF4.utils']

# Around netCDF4 1.4.0, netcdftime changed name to cftime
if is_module_satisfies("netCDF4 < 1.4.0"):
    hiddenimports += ['netcdftime']
else:
    hiddenimports += ['cftime']

# Starting with netCDF 1.6.4, certifi is a hidden import made in
# netCDF4/_netCDF4.pyx.
if is_module_satisfies("netCDF4 >= 1.6.4"):
    hiddenimports += ['certifi']

from PyInstaller.utils.hooks import collect_delvewheel_libs_directory
datas, binaries = collect_delvewheel_libs_directory("netCDF4")
```

Then all files from `netCDF4.libs` directory should be collected, and `netCDF4` should load.

**Comment by mtsamorim** [comment]
Hey my friend, I just came back here to say thank you. Thank you very much, I thought it would be a very absurd error, but these lines that you said to put in the file worked perfectly and now the application is working perfectly, thank you very much. In the future I will start using Python 3.10 to avoid this problem.
