### ISSUE TITLE
 DLL load failed "_network" with Pyinstaller

### ISSUE THREAD

**Issue by mtsamorim** [pyinstaller/pyinstaller#8415]
Hello guys, I recently had a similar problem with the DLL pyinstaller, a user here at pyinstaller even advised me to use Python 10 as I wouldn't have this problem, but now I can't migrate the project to Python 10 and it caused a problem similar in another library I'm using

when i run `code.py`  it works perfectly the problem happens when using pyinstaller to create an executable

I will leave the versions of the libraries that seem to be causing problems and the log of the creation of the executable and the error that appears afterwards

**Python: 3.8.18**
**pyproj: 3.5.0**
**pyinstaller: 6.3.0**
**pyinstaller-hooks-contrib 2024.0**
**gdal: 3.4.3**
**geopandas:  0.8.2**

Log when I create the code executable:

```
3465 INFO: PyInstaller: 6.3.0
3466 INFO: Python: 3.8.18 (conda)
3492 INFO: Platform: Windows-10-10.0.19045-SP0
3496 INFO: wrote C:\Users\malva\OneDrive\Área de Trabalho\V6\FMDprocessor.spec
3526 INFO: Extending PYTHONPATH with paths
['C:\\Users\\malva\\OneDrive\\Área de Trabalho\\V6']
4747 INFO: Appending 'datas' from .spec
4758 INFO: checking Analysis
4759 INFO: Building Analysis because Analysis-00.toc is non existent
4763 INFO: Initializing module dependency graph...
4770 INFO: Caching module graph hooks...
4967 INFO: Analyzing base_library.zip ...
19958 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
22716 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
33489 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
38503 INFO: Caching module dependency graph...
39178 INFO: Running Analysis Analysis-00.toc
39178 INFO: Looking for Python shared library...
39216 INFO: Using Python shared library: C:\Users\malva\anaconda3\envs\FMD\python38.dll
39216 INFO: Analyzing C:\Users\malva\OneDrive\Área de Trabalho\V6\FMDprocessor.py
39843 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
41636 INFO: Processing pre-safe import module hook distutils from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-distutils.py'.
41641 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
43013 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
43197 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
43721 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
44629 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
46189 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
47723 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
52196 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
53127 INFO: Loading module hook 'hook-psutil.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
57593 INFO: Loading module hook 'hook-pandas.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
3368 INFO: NumExpr defaulting to 4 threads.
65836 INFO: Loading module hook 'hook-pytz.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
67331 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
79420 INFO: Processing pre-safe import module hook six.moves from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
86451 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
112432 INFO: Loading module hook 'hook-pandas.plotting.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
113205 INFO: Loading module hook 'hook-matplotlib.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
139077 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
143851 INFO: Processing pre-safe import module hook gi from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-gi.py'.
149291 INFO: Loading module hook 'hook-PIL.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
153870 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
188644 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
191821 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
205938 INFO: Loading module hook 'hook-importlib_metadata.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
209923 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
211557 INFO: Loading module hook 'hook-jinja2.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
219635 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
222527 INFO: Loading module hook 'hook-importlib_resources.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
222708 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
225439 INFO: Loading module hook 'hook-openpyxl.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
225949 INFO: Loading module hook 'hook-lxml.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
229860 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
234668 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
236113 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
239365 INFO: Loading module hook 'hook-PyQt5.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
241713 INFO: Loading module hook 'hook-dask.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
247181 INFO: Loading module hook 'hook-netCDF4.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
250545 INFO: Loading module hook 'hook-bokeh.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
265380 INFO: Loading module hook 'hook-selenium.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
268386 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
287516 INFO: Loading module hook 'hook-cftime.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
291088 INFO: Loading module hook 'hook-osgeo.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
292129 INFO: Loading module hook 'hook-geopandas.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
292247 INFO: Loading module hook 'hook-shapely.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
292834 INFO: Loading module hook 'hook-pyproj.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
292965 WARNING: Datas for pyproj not found at:
C:\Users\malva\anaconda3\envs\FMD\Library\share\proj
294067 INFO: Loading module hook 'hook-fiona.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
296337 INFO: Processing module hooks...
296370 WARNING: Hidden import "fiona._shim" not found!
296382 INFO: Loading module hook 'hook-lxml.etree.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
296704 INFO: Loading module hook 'hook-lxml.isoschematron.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
296906 WARNING: Hidden import "importlib_resources.trees" not found!
296907 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
296913 INFO: Matplotlib backend selection method: automatic discovery of used backends
298669 INFO: Trying determine the default backend as first importable candidate from the list: ['Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
300737 INFO: Selected matplotlib backends: ['Qt5Agg']
301887 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
303189 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
303754 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
304470 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
305016 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
306856 INFO: Loading module hook 'hook-setuptools._distutils.command.check.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
307584 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
307589 INFO: checking Tree
307590 INFO: Building Tree because Tree-00.toc is non existent
307591 INFO: Building Tree Tree-00.toc
307997 INFO: checking Tree
307998 INFO: Building Tree because Tree-01.toc is non existent
308000 INFO: Building Tree Tree-01.toc
308056 INFO: checking Tree
308058 INFO: Building Tree because Tree-02.toc is non existent
308059 INFO: Building Tree Tree-02.toc
308075 INFO: Loading module hook 'hook-lxml.objectify.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
308671 INFO: Performing binary vs. data reclassification (3896 entries)
316061 INFO: Looking for ctypes DLLs
316381 INFO: Analyzing run-time hooks ...
316451 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
316465 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
316474 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks'...
316478 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
316486 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
316497 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
316504 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
316518 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
316525 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
316559 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_osgeo.py'
316568 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pyproj.py'
316573 INFO: Including run-time hook 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
317768 INFO: Looking for dynamic libraries
C:\Users\malva\anaconda3\envs\FMD\lib\site-packages\PyInstaller\building\build_main.py:194: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
335642 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\numpy\\.libs', 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyQt5\\Qt5\\bin', 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\osgeo', 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\osgeo']
335643 INFO: Extra DLL search directories (PATH): ['C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\osgeo', 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\PyQt5\\Qt5\\bin']
362858 WARNING: Library not found: could not resolve 'mpich2mpi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_blacs_mpich2_lp64.1.dll'.
362859 WARNING: Library not found: could not resolve 'pgmath.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_pgi_thread.1.dll'.
362862 WARNING: Library not found: could not resolve 'pgf90.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_pgi_thread.1.dll'.
362863 WARNING: Library not found: could not resolve 'pgc.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_pgi_thread.1.dll'.
362866 WARNING: Library not found: could not resolve 'sycl7.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\omptarget.sycl.wrap.dll'.
362868 WARNING: Library not found: could not resolve 'msmpi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_blacs_msmpi_lp64.1.dll'.
362874 WARNING: Library not found: could not resolve 'ze_loader.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\omptarget.rtl.level0.dll'.
362876 WARNING: Library not found: could not resolve 'msmpi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_blacs_msmpi_ilp64.1.dll'.
362878 WARNING: Library not found: could not resolve 'mpich2mpi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_blacs_mpich2_ilp64.1.dll'.
362880 WARNING: Library not found: could not resolve 'impi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_blacs_intelmpi_ilp64.1.dll'.
362881 WARNING: Library not found: could not resolve 'impi.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\Library\\bin\\mkl_blacs_intelmpi_lp64.1.dll'.
362896 WARNING: Library not found: could not resolve 'gdal-fd9ba3209f601e85fe39e4d1757194df.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\fiona\\schema.cp38-win_amd64.pyd'.
362898 WARNING: Library not found: could not resolve 'gdal-fd9ba3209f601e85fe39e4d1757194df.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\fiona\\_err.cp38-win_amd64.pyd'.
362900 WARNING: Library not found: could not resolve 'gdal-fd9ba3209f601e85fe39e4d1757194df.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\fiona\\_geometry.cp38-win_amd64.pyd'.
362905 WARNING: Library not found: could not resolve 'gdal-fd9ba3209f601e85fe39e4d1757194df.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\fiona\\ogrext.cp38-win_amd64.pyd'.
362908 WARNING: Library not found: could not resolve 'gdal-fd9ba3209f601e85fe39e4d1757194df.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\fiona\\crs.cp38-win_amd64.pyd'.
362910 WARNING: Library not found: could not resolve 'gdal-fd9ba3209f601e85fe39e4d1757194df.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\fiona\\_env.cp38-win_amd64.pyd'.
362913 WARNING: Library not found: could not resolve 'proj-bcd73c5ade3a4f4ce36b168b3f34a026.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\pyproj\\_sync.cp38-win_amd64.pyd'.
362915 WARNING: Library not found: could not resolve 'proj-bcd73c5ade3a4f4ce36b168b3f34a026.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\pyproj\\_transformer.cp38-win_amd64.pyd'.
362921 WARNING: Library not found: could not resolve 'proj-bcd73c5ade3a4f4ce36b168b3f34a026.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\pyproj\\_crs.cp38-win_amd64.pyd'.
362925 WARNING: Library not found: could not resolve 'proj-bcd73c5ade3a4f4ce36b168b3f34a026.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\pyproj\\list.cp38-win_amd64.pyd'.
362929 WARNING: Library not found: could not resolve 'proj-bcd73c5ade3a4f4ce36b168b3f34a026.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\pyproj\\_geod.cp38-win_amd64.pyd'.
362941 WARNING: Library not found: could not resolve 'proj-bcd73c5ade3a4f4ce36b168b3f34a026.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\pyproj\\database.cp38-win_amd64.pyd'.
362948 WARNING: Library not found: could not resolve 'proj-bcd73c5ade3a4f4ce36b168b3f34a026.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\pyproj\\_datadir.cp38-win_amd64.pyd'.
362951 WARNING: Library not found: could not resolve 'proj-bcd73c5ade3a4f4ce36b168b3f34a026.dll', dependency of 'C:\\Users\\malva\\anaconda3\\envs\\FMD\\lib\\site-packages\\pyproj\\_network.cp38-win_amd64.pyd'.
364244 INFO: Warnings written to C:\Users\malva\OneDrive\Área de Trabalho\V6\build\FMDprocessor\warn-FMDprocessor.txt
366719 INFO: Graph cross-reference written to C:\Users\malva\OneDrive\Área de Trabalho\V6\build\FMDprocessor\xref-FMDprocessor.html
368759 INFO: checking PYZ
368764 INFO: Building PYZ because PYZ-00.toc is non existent
368765 INFO: Building PYZ (ZlibArchive) C:\Users\malva\OneDrive\Área de Trabalho\V6\build\FMDprocessor\PYZ-00.pyz
390204 INFO: Building PYZ (ZlibArchive) C:\Users\malva\OneDrive\Área de Trabalho\V6\build\FMDprocessor\PYZ-00.pyz completed successfully.
391712 INFO: checking PKG
391713 INFO: Building PKG because PKG-00.toc is non existent
391715 INFO: Building PKG (CArchive) FMDprocessor.pkg
761406 INFO: Building PKG (CArchive) FMDprocessor.pkg completed successfully.
762080 INFO: Bootloader C:\Users\malva\anaconda3\envs\FMD\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
762081 INFO: checking EXE
762084 INFO: Building EXE because EXE-00.toc is non existent
762086 INFO: Building EXE from EXE-00.toc
762089 INFO: Copying bootloader EXE to C:\Users\malva\OneDrive\Área de Trabalho\V6\dist\FMDprocessor.exe
762805 INFO: Copying icon to EXE
763029 INFO: Copying 0 resources to EXE
763030 INFO: Embedding manifest in EXE
763222 INFO: Appending PKG archive to EXE
766087 INFO: Fixing EXE headers
783350 INFO: Building EXE from EXE-00.toc completed successfully.
```

Error given when trying to run the created executable

```
Traceback (most recent call last):
  File "FMDprocessor.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "geopandas\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "geopandas\geoseries.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyproj\__init__.py", line 63, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyproj\network.py", line 10, in <module>
ImportError: DLL load failed while importing _network: The specified module could not be found.
[10344] Failed to execute script 'FMDprocessor' due to unhandled exception!
```

I would be grateful for help from the members of this wonderful community

**Comment by rokm** [comment]
This is the same kind of problem that you had in #8405, and if you cannot move from Anaconda python 3.8/3.9 (i.e., update to >= 3.10 or use python.org python 3.8 instead of Anaconda), you will need to update `hook-pyproj.py` to collect the external `pyproj.libs` directory using `PyInstaller.utils.hooks.collect_delvewheel_libs_directory` helper. See pyinstaller/pyinstaller-hooks-contrib#726.

**Comment by mtsamorim** [comment]
It's because as it said "_network" there I thought it was some file hook-network.py, As I hadn't, I thought it could be another problem.

So I do the same procedure as the error I already had, right? 
```
from PyInstaller.utils.hooks import collect_delvewheel_libs_directory
datas, binaries = collect_delvewheel_libs_directory("pyproj")
```

**Comment by rokm** [comment]
> It's because as it said "_network" there I thought it was some file hook-network.py, As I hadn't, I thought it could be another problem.

That's why you have to read the whole traceback, to see where the error is being raised from.
 
> So I do the same procedure as the error I already had, right? 

It's slightly different, because `datas` is already populated in that hook, so instead of overwriting it, you need to merge the results.

You can just look at changes made in https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/726 and apply those locally.

**Comment by mtsamorim** [comment]
I looked at the pyinstaller documentation and pyinstaller/pyinstaller-hooks-contrib#726, In my base code do I import this function and apply the code line?

```
from PyInstaller.utils.hooks import collect_delvewheel_libs_directory
datas, binaries = collect_delvewheel_libs_directory("pyproj", datas=datas, binaries=binaries)
```

**Comment by rokm** [comment]
Yes, if you're going to put it at the end of the hook (make sure `binaries` is initialized to empty list, or don't pass it to the function at all).

**Comment by mtsamorim** [comment]
Actually, sorry for the doubt and confusion, when you say hook do you mean hook-pyproj.py alright? I was thinking it was to put it in my project code lol

**Comment by rokm** [comment]
> Actually, sorry for the doubt and confusion, when you say hook do you mean hook-pyproj.py alright? I was thinking it was to put it in my project code lol

Yes - you should be modifying your local copy of the `hook-pyproj.py`, not your program code.

**Comment by mtsamorim** [comment]
Thank you very much man, I'll test it here. I will try to migrate to Python 3.10 later to avoid these problems
