### ISSUE TITLE
Built exe does not work with pyzmq 13.1.0 and simplejson

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#842]
**Original date**: 2014/01/03
**Original reporter**: *olemoign*

The build completes, but when I run:

```
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\zmq", line 52, in <module>
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\zmq.sugar", line 16, in <module>
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\zmq.sugar.constants", line 16, in <module>
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\zmq.sugar.backend", line 17, in <module>
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\zmq.core", line 26, in <module>
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 409, in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
  File "socket.pyx", line 65, in init zmq.core.socket (zmq\core\socket.c:9119)
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\zmq.utils.jsonapi", line 52, in <module>
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\simplejson", line 112, in <module>
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\simplejson.scanner", line 10, in <module>
  File "C:\Users\Olivier\Developer\mdt\build_tools\win\build\make_node_mgr\out00-PYZ.pyz\simplejson.scanner", line 6, in _import_c_make_scanner
  File "C:\Users\Olivier\Developer\mdt\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 409, in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
SystemError: dynamic module not initialized properly
```

If I compile in one dir instead of one file, it works.
If I remove simplejson (pyzmq then imports json instead), it works too.

**Comment by htgoebel** [comment]
@olemoign: THis seams to be an old issue from you. Is it still valid with the current `python3` branch head? If so, please submit a minimal example and more details, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.

**Comment by olemoign** [comment]
I did a fresh install with the `python3`branch but I can't test if the problem is solved as I'm facing #1420.

**Comment by olemoign** [comment]
Hi,
I retried today with Pyinstaller 3 and the problem seems resolved.
Thank you for the work.

**Comment by matysek** [comment]
@olemoign Could you please try latest `develop` version if that still works for you? There were some recent changes related to pyzmq support.

**Comment by olemoign** [comment]
Same with the latest `develop`, it's now working. I even tried with pyzmq 13.1 and 14.7.
