### ISSUE TITLE
PyInstaller uses deprecated python module

### ISSUE THREAD

**Issue by alittwin** [pyinstaller/pyinstaller#8455]
After updating setuptools from 69.2.0 to 69.5.1 I stumbled upon an issue: 'uu' is a deprecated package, but when I exclude it using Analysis class and 'excludes' attribute then after building the application by PyInstaller, I get this error message when I try to run the application:

```cmd
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 68, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\_vendor\jaraco\text\__init__.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\_vendor\jaraco\context.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "urllib\request.py", line 88, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "http\client.py", line 72, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\message.py", line 10, in <module>
ModuleNotFoundError: No module named 'uu'
[14344] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```

It seems like PyInstaller is using deprecated module pkg_resources from setuptools, I even found migration guide on the Internet https://importlib-resources.readthedocs.io/en/latest/migration.html. I opened it as an issue, not a question, because it seems to me that PyInstaller shouldn't use deprecated modules. Please let me know if you're planning to migrate to importlib.resources, importlib.metadata in near future.

**Comment by rokm** [comment]
The traceback clearly indicates that the import of `uu` happens in stdlib's `email.message` module. Which probably means you are using python 3.10.x or older, where it was not deprecated yet - https://github.com/python/cpython/blob/v3.10.14/Lib/email/message.py#L10

As for `pkg_resources` - that run-time hook is included and ran because something in your dependency tree is importing `pkg_resources`. Not much we can do about that, either. You can always try to exclude it, and see if anything raises error about it. But again, much like the `uu` "issue", this has nothing to do with PyInstaller itself.

**Comment by alittwin** [comment]
Yes, the issue was was caused by Python < 3.11, after changing version it started working, thank you for help and sorry for the trouble.
