### ISSUE TITLE
Exception: unknown file c:\users\broth\appdata\local\temp\_mei138842\spectrum\data\DOLPHINS.wav

### ISSUE THREAD

**Issue by snowuyl** [pyinstaller/pyinstaller#8457]
## Description of the issue
pyinstaller can generate main.exe successfully. But main.exe failed to run with the following error message.
Exception: unknown file c:\users\broth\appdata\local\temp\_mei138842\spectrum\data\DOLPHINS.wav

Context information (for bug reports)
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.6.0```
* Version of Python: 3.11.9
* Platform: Windows 11
* How you installed Python: Windows store

### A minimal example program which shows the error

```
Please unzip [pyHrvTest.zip](https://github.com/pyinstaller/pyinstaller/files/15242915/pyHrvTest.zip) and run deploy.bat from command prompt to generate main.exe. And run main.exe.
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyhrvtest\hr.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyhrv\__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyhrv\hrv.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyhrv\frequency_domain.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "spectrum\__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "spectrum\datasets.py", line 148, in <module>
  File "spectrum\datasets.py", line 146, in spectrum_data
Exception: unknown file c:\users\broth\appdata\local\temp\_mei138842\spectrum\data\DOLPHINS.wav
```

**Comment by snowuyl** [comment]
[pyHrvTest.zip](https://github.com/pyinstaller/pyinstaller/files/15242915/pyHrvTest.zip)

**Comment by bwoodsend** [comment]
`--collect-data=spectrum`?

**Comment by snowuyl** [comment]
Thanks for your reply! Do you mean I need to add this option when generating main.exe file?

**Comment by rokm** [comment]
> Thanks for your reply! Do you mean I need to add this option when generating main.exe file?

Yes.

**Comment by snowuyl** [comment]
Thanks for your reply! I run the following command to generate main.exe. main.exe can be generated successfully but failed to run with the following error messages. 
pyinstaller --onefile --noconsole --collect-data=spectrum main.py

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyhrvtest\hr.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyhrv\__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyhrv\hrv.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyhrv\nonlinear.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "nolds\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "nolds\datasets.py", line 260, in <module>
  File "nolds\datasets.py", line 113, in load_brown72
  File "pkg_resources\__init__.py", line 1187, in resource_stream
  File "pkg_resources\__init__.py", line 1466, in get_resource_stream
  File "pkg_resources\__init__.py", line 1469, in get_resource_string
  File "pkg_resources\__init__.py", line 1640, in _get
  File "PyInstaller\loader\pyimod02_importers.py", line 228, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\broth\\AppData\\Local\\Temp\\_MEI88242\\nolds\\datasets\\brown72.npy'

**Comment by rokm** [comment]
It's the same kind of problem - you need to also collect data from `nolds` package. I.e., also add `--collect-data=nolds`.

**Comment by snowuyl** [comment]
Thanks for your great support! I can run main.exe after changing command as follows.
pyinstaller --onefile --noconsole --collect-data=spectrum --collect-data=nolds main.py
