### ISSUE TITLE
NotADirectoryError _internal/lz4/frame - site-packages/pandas/_libs/window/aggregations.cpython-310-aarch64-linux-gnu.so

### ISSUE THREAD

**Issue by programmeddeath1** [pyinstaller/pyinstaller#8553]
I am trying to run pyinstaller for a PyQT application with ROS and ultralytics Computer vision libraries. It is failing during COLLECT as below - while collectingfor pandas _libs window aggregations
```
488059 INFO: checking EXE
488133 INFO: checking COLLECT
488133 INFO: Building COLLECT because COLLECT-00.toc is non existent
WARNING: The output directory "/home/greenpi/app/main_delta_app/src/delta_gui/dist/deltaapp" and ALL ITS CONTENTS will be REMOVED! Continue? (y/N)y
On your own risk, you can use the option `--noconfirm` to get rid of this question.
494838 INFO: Removing dir /home/greenpi/app/main_delta_app/src/delta_gui/dist/deltaapp
495085 INFO: Building COLLECT COLLECT-00.toc
.......
printhere  - /home/greenpi/.local/lib/python3.10/site-packages/pandas/_libs/pandas_parser.cpython-310-aarch64-linux-gnu.so
printhere  - /home/greenpi/.local/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-aarch64-linux-gnu.so
Traceback (most recent call last):
  File "/home/greenpi/.local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/home/greenpi/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 228, in _console_script_run
    run()
  File "/home/greenpi/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 212, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/greenpi/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/greenpi/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1186, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/greenpi/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1126, in build
    exec(code, spec_namespace)
  File "deltaapp.spec", line 76, in <module>
    coll = COLLECT(
  File "/home/greenpi/.local/lib/python3.10/site-packages/PyInstaller/building/api.py", line 1107, in __init__
    self.__postinit__()
  File "/home/greenpi/.local/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/home/greenpi/.local/lib/python3.10/site-packages/PyInstaller/building/api.py", line 1146, in assemble
    os.makedirs(dest_dir, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/home/greenpi/app/main_delta_app/src/delta_gui/dist/deltaapp/_internal/lz4/frame'
```

```
# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from PyInstaller.utils.hooks import collect_data_files

# Add ROS paths
ros_paths = [
    '/home/greenpi/noetic_ws/install_isolated/lib/python3/dist-packages',
    '/home/greenpi/noetic_ws/devel_isolated/lib/python3/dist-packages',
    '/opt/ros/noetic/lib/python3/dist-packages'
]

# Extend the Python path
sys.path.extend(ros_paths)

graphviz_binaries = [
    ('/usr/bin/neato', 'graphviz/bin/neato'),
    ('/usr/bin/dot', 'graphviz/bin/dot'),
    ('/usr/bin/fdp', 'graphviz/bin/fdp'),
    ('/usr/bin/sfdp', 'graphviz/bin/sfdp'),
    ('/usr/bin/twopi', 'graphviz/bin/twopi'),
    ('/usr/bin/circo', 'graphviz/bin/circo'),
    #('/usr/lib/aarch64-linux-gnu/graphviz','graphviz')
]

# Collect data files for pygraphviz
datas = collect_data_files('pygraphviz')

# Include additional data files
datas += [
    ('../delta_description/config/delta_robot.rviz',
     'delta_robot.rviz',
     'config'
     )
]

a = Analysis(
    ['main_qthread_docker.py'],
    pathex=ros_paths + sys.path,
    binaries=graphviz_binaries,
    datas=datas,
    hiddenimports=[
        'roslib',
        'rospy',
        'std_msgs',
        'geometry_msgs',
        'sensor_msgs',
        # Add other ROS packages that your application depends on
    ],

    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PySide2'],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='deltaapp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='deltaapp',
)
```

What could be the issue here should i downgrade pandas?
pandas version is 2.2.2
pyinstaller is 6.6.0
lz4==3.1.3+dfsg

**Comment by rokm** [comment]
This looks like failing to create a directory, presumably because a file with the same name already exists? Can you check the partial build result if 
`/home/greenpi/app/main_delta_app/src/delta_gui/dist/deltaapp/_internal/lz4` or `/home/greenpi/app/main_delta_app/src/delta_gui/dist/deltaapp/_internal/lz4/frame` is a file?

**Comment by programmeddeath1** [comment]
/home/greenpi/app/main_delta_app/src/delta_gui/dist/deltaapp/_internal/lz4 is a file

**Comment by rokm** [comment]
> /home/greenpi/app/main_delta_app/src/delta_gui/dist/deltaapp/_internal/lz4 is a file

Then that's what is causing the problem. Can you open `build/deltaapp/Analysis-00.toc` and find out where it was collected from?

**Comment by programmeddeath1** [comment]
i grepped lz4 in Analysis-00.toc and heres the output
```
grep lz4 "Analysis-00.toc" 
  '/home/greenpi/noetic_ws/devel_isolated/roslz4/lib/python3/dist-packages',
  ('lz4.frame',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4/frame/__init__.py',
  ('lz4',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4/__init__.py',
  ('lz4.version',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4/version.py',
  ('lz4', '/usr/bin/lz4', 'BINARY'),
  ('lz4/frame/_frame.cpython-310-aarch64-linux-gnu.so',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4/frame/_frame.cpython-310-aarch64-linux-gnu.so',
  ('lz4/_version.cpython-310-aarch64-linux-gnu.so',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4/_version.cpython-310-aarch64-linux-gnu.so',
  ('liblz4.so.1', '/lib/aarch64-linux-gnu/liblz4.so.1', 'BINARY'),
  ('lz4-4.3.3.dist-info/METADATA',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4-4.3.3.dist-info/METADATA',
  ('lz4-4.3.3.dist-info/WHEEL',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4-4.3.3.dist-info/WHEEL',
  ('lz4-4.3.3.dist-info/RECORD',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4-4.3.3.dist-info/RECORD',
  ('lz4-4.3.3.dist-info/top_level.txt',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4-4.3.3.dist-info/top_level.txt',
  ('lz4-4.3.3.dist-info/REQUESTED',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4-4.3.3.dist-info/REQUESTED',
  ('lz4-4.3.3.dist-info/INSTALLER',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4-4.3.3.dist-info/INSTALLER',
  ('lz4-4.3.3.dist-info/LICENSE',
   '/home/greenpi/.local/lib/python3.10/site-packages/lz4-4.3.3.dist-info/LICENSE',
  ('unlz4', 'lz4', 'SYMLINK'),
  ('lz4c', 'lz4', 'SYMLINK'),
  ('lz4cat', 'lz4', 'SYMLINK'),
```
This lz4. frame seems to be coming from the ros package roslz4. How do i make it specifically ignore the ros one and only build the default python one?

**Comment by rokm** [comment]
The problem is that you have `lz4` package, and that has a `lz4.frame._frame` binary extension, which we need to collect as `lz4/frame/_frame.cpython-310-aarch64-linux-gnu.so`.

But at the same time, you are collecting `/usr/bin/lz4` into top-level application directory, which leads to file/directory name clash.

One way to work around this would be to collect `/usr/bin/lz4` into `bin` sub-directory instead of top-level application directory (and add that sub-directory to `PATH` at run-time). In your spec, I don't see you collecting that `lz4` executable, though, so I guess the question now is where does this directive for collecting `lz4` executable (as well as `unlz4`, `lz4c`, `lz4cat`) come from?

**Comment by programmeddeath1** [comment]
a lot of my packages are imported from ros python directory. Before i run pyinstaller I am sourcing the following 
I need to source this before I run my PyQt application too to use specific ros modules.
```
source /home/greenpi/noetic_ws/devel_isolated/setup.bash
source ~/app/rosserial/devel/setup.bash
```
Which adds a lot of directories to the PYTHONPATH
```
echo $PYTHONPATH
/home/greenpi/app/rosserial/devel/lib/python3/dist-packages:/home/greenpi/app/main_delta_app/devel/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/xacro/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_rviz/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rviz/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/turtle_actionlib/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/turtlesim/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/tf_conversions/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/tf2_kdl/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/laser_geometry/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/interactive_markers/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/tf2_geometry_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/tf/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/tf2_ros/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/stereo_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_image_view/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/map_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/cv_bridge/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/sensor_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_launch/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/roswtf/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/nodelet_topic_tools/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/diagnostic_analysis/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/actionlib_tutorials/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/actionlib/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosbag/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/topic_tools/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/tf2_py/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/smach_ros/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_reconfigure/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_gui_py/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rostopic/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rospy_tutorials/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosnode/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosmsg/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/message_filters/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/joint_state_publisher/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/dynamic_reconfigure/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/diagnostic_common_diagnostics/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/diagnostic_updater/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/roscpp_tutorials/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/nodelet/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/bondpy/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/roscpp/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/visualization_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/control_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/trajectory_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/tf2_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/std_srvs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/smach_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/shape_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_py_common/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosgraph_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/nav_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/geometry_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/diagnostic_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/bond/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/actionlib_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/std_msgs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/smclib/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/smach/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_web/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_topic/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_top/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_tf_tree/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_srv/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_shell/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_service_caller/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_runtime_monitor/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_robot_steering/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_robot_monitor/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_robot_dashboard/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_py_console/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_publisher/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_pose_view/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_plot/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_nav_view/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_msg/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_moveit/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_logger_level/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_gui/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_graph/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_dep/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_console/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_bag_plugins/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_bag/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rqt_action/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rostest/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/roslz4/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/resource_retriever/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/qt_gui_cpp/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/angles/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosunit/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/roslaunch/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/python_qt_binding/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosservice/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rospy/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosparam/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/roslib/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosmaster/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosmake/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/roslint/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosgraph/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/roscreate/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosclean/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/rosboost_cfg/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/qt_gui_py_common/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/qt_gui/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/qt_dotgraph/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/joint_state_publisher_gui/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/genpy/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/gennodejs/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/genlisp/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/geneus/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/gencpp/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/genmsg/lib/python3/dist-packages:/home/greenpi/noetic_ws/devel_isolated/catkin/lib/python3/dist-packages
```

Could it be picking from these packages. So when I source and then run pyinstaller, if it picks all dependencies from the PYTHONPATH then it will trigger collecting lz4 from here too i guess.

**Comment by rokm** [comment]
Even so, it shouldn't be collecting `/usr/bin/lz4` executable, unless explicitly told to do so - either in the spec file, or by some hook. So if you are not collecting `/usr/bin/lz4` in the spec file, perhaps there's a hook that does this?

Can you run a clean build (`pyinstaller --clean --noconfirm`) and attach the full build log here? So we can see what hooks are being ran during the build...

**Comment by rokm** [comment]
FWIW, if you don't need the `lz4` package anywhere, you could try excluding it by adding it to `excludes` list that is passed to `Analysis` in the spec. That will probably get you past this particular error, but if something actually uses this package, you will end up with run-time missing-module error. In that case, you will need to determine why `/usr/bin/lz4` executable is collected, and alter that collection (i.e., into sub-directory).

**Comment by programmeddeath1** [comment]
I am not using lz4 compression which means one of the packages imported is using it internally. 

If i need to alter the collection, what exactly  would i need to do? Will I have to create separate hooks for both? Could you guide me with the steps or some reference documentation for me to understand what I might need to do?

I'll try excluding lz4 and see if it just picks the lz4 from the ros environment.

**Comment by rokm** [comment]
Like I said, the main problem here is that for some reason `/usr/bin/lz4` is being collected. PyInstaller does not collect system-installed executables like that (which is why you need `graphviz_binaries` in your spec file - although the entries there look wrong; the destination argument should be destination directory, not destination filename), so I think you should figure what is triggering collection of that file. 

(I would ask for full reproduction steps, but I have no desire to deal with ROS, and that PYTHONPATH you posted earlier looks horrible on its own.)

You could of course also try to suppress collection of  `/usr/bin/lz4` executable without trying to figure out what causes it - but the only way to do so right now is in the spec file. After `Analysis` is instantiated (`a = Analysis()`) and before its attributes are passed on to other objects, you can loop over `a.datas` and `a.binaries` and remove the corresponding entries based on their names.

**Comment by programmeddeath1** [comment]
Hi yes the graphviz datas binaries posted here was the wrong one with the file names instead of folder names, had corrected that.

I got the app to work by skipping the lz4 using excludes, but I still want to explore what could be causing it to be triggered, because I don't want a missing/Not found to cause problems later in the app run.

Sorry i think i missed one of your earlier comments so here is the output for the clean noconfirm [run](https://github.com/programmeddeath1/webhost/blob/master/build_log_pyinstaller_lz4.txt)

It shows that roslz4 is extended from PYTHONPATH, which seems to be triggering the lz4 hook

**Comment by rokm** [comment]
> Sorry i think i missed one of your earlier comments so here is the output for the clean noconfirm [run](https://github.com/programmeddeath1/webhost/blob/master/build_log_pyinstaller_lz4.txt)

Hmm, this looks OK - the only external hooks ran are the one for `numpy` and for `yt_dlp`, and that does not seem to have to do anything with `lz4` executable.

> It shows that roslz4 is extended from PYTHONPATH, which seems to be triggering the lz4 hook

The [hook for `lz4`](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-lz4.py) is collecting only metadata of python `lz4` package, so I doubt it has anything to do with `/usr/bin/lz4` executable.

I suppose we can try approaching this from the opposite direction:

1. if you freeze the following simple program in your environment,
```python
import lz4
print("hello")
```
do you see `/usr/bin/lz4` collected or not?

2. what about if you freeze the following program?
```python
import roslz4
print("hello")
```
