### ISSUE TITLE
No module named '_pywrapfst' (nemo_text_processing)

### ISSUE THREAD

**Issue by rafael-wampfler** [pyinstaller/pyinstaller#8568]
Hello

I'm using v6.7.0 and Python 3.9 to compile my Python Flask server into a standalone. For this I'm using the following server.spec file:

```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata
from PyInstaller.utils.hooks import collect_submodules 
import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)
from PyInstaller.utils.hooks import collect_dynamic_libs
binaries = collect_dynamic_libs('nvidia.cuda_nvrtc', search_patterns=['lib*.so.*'])
binaries += collect_dynamic_libs('azure.cognitiveservices.speech')

datas = []
datas += collect_data_files('torch')
datas += copy_metadata('torch')
datas += copy_metadata('tqdm')
datas += copy_metadata('regex')
datas += copy_metadata('requests')
datas += copy_metadata('packaging')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')
datas += copy_metadata('importlib_metadata')
datas += copy_metadata('deepspeed')
datas += copy_metadata('huggingface-hub')
datas += copy_metadata('safetensors')
datas += copy_metadata('pyyaml')
datas += copy_metadata('sentencepiece')
datas += copy_metadata('datasets')
datas += copy_metadata('optimum')
datas += copy_metadata('transformers')
datas += copy_metadata('auto_gptq')
datas += copy_metadata('triton')
datas += copy_metadata('nemo_text_processing')
datas += collect_data_files('ninja')
datas += collect_data_files('deepspeed')
datas += collect_data_files('datasets')
datas += collect_data_files('optimum')
datas += collect_data_files('transformers')
datas += collect_data_files('auto_gptq')
datas += collect_data_files('triton')
datas += collect_data_files('nemo_text_processing')

# Added
hiddenimports = []
hiddenimports = collect_submodules('deepspeed') + collect_submodules('datasets') + collect_submodules('optimum') + collect_submodules('transformers') + collect_submodules('auto_gptq')
hiddenimports.append('triton._C.libtriton')
hiddenimports.append('tiktoken_ext')
hiddenimports.append('tiktoken_ext.openai_public')

block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports, 
    #hiddenimports=['pytorch', 'deepspeed'], NOTE: pytorch is not a valid module name, and deepspeed is included in collect_submodules output
    hookspath=['pyinstaller-hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    # Added
    module_collection_mode={
        "deepspeed": "pyz+py",
        "datasets": "pyz+py",
        "optimum": "pyz+py",
        "transformers": "pyz+py",
        "auto_gptq": "pyz+py",
        "triton": "py"
    },
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

I have added now a new module nemo_text_processing and I'm getting the following error at runtime:

```
Traceback (most recent call last):
  File "server/main.py", line 61, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "nemo_text_processing/text_normalization/__init__.py", line 15, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "nemo_text_processing/text_normalization/normalize.py", line 28, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pynini/__init__.py", line 1, in <module>
  File "extensions/_pynini.pyx", line 1, in init _pynini
ModuleNotFoundError: No module named '_pywrapfst'
[126799] Failed to execute script 'main' due to unhandled exception!
```

I have added nemo_text_processing to collect_data_files and copy_metadata but it does not work. What is the correct way to handle this?

**Comment by rokm** [comment]
Add `_pywrapfst` to hidden imports?

**Comment by rafael-wampfler** [comment]
Thank you very much for your answer, highly appreciated. I have added it as `hiddenimports.append('_pywrapfst')`. But now another error appears:

```
Traceback (most recent call last):
  File "server/main.py", line 944, in <module>
  File "nemo_text_processing/text_normalization/normalize.py", line 121, in __init__
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "nemo_text_processing/text_normalization/en/__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "nemo_text_processing/text_normalization/en/graph_utils.py", line 85, in <module>
  File "extensions/_pynini.pyx", line 1033, in _pynini.string_file
  File "extensions/_pynini.pyx", line 1109, in _pynini.string_file
_pywrapfst.FstIOError: Read failed
[186519] Failed to execute script 'main' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
Is there not another line of error message after that?

**Comment by rafael-wampfler** [comment]
Sorry, I forgot to copy the full error message. I have updated my post above.

**Comment by rokm** [comment]
Hmmm, based on the traceback, I can reproduce that error with
```
import nemo_text_processing.text_normalization
n = nemo_text_processing.text_normalization.Normalizer("lower_cased")
```

and fix it with `--collect-data nemo_text_processing`. But I see that you should have the equivalent `collect_data_files('nemo_text_processing')` in your .spec file already.

Can you check that for example `nemo_text_processing/text_normalization/en/data/suppletive.tsv` is collected in the frozen application (by checking `build/<name>/Analysis-00.toc`, or perhaps better, inspecting the executable's contents with `pyi-archive_viewer`)?

**Comment by rafael-wampfler** [comment]
I could resolve the problem. I removed `collect_data_files('nemo_text_processing')` because I thought it is no more necessary. When adding again, it works.

Unfortunately, there is another small issue with collecting files.

I have the following structure:

```
server (package)
   - main.py
   - Other python files
   - test.txt
   - pyinstaller-hooks
       - hook-server.py
       - hook-image.py
 image_generation (package)
   - some python files
   - images.json
```

In my spec file I have `hookspath=['pyinstaller-hooks']`. I have the following hooks:

hook-server.py
```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('server')
```

hook-image.py
```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('image_generation')
```

In main.py I now want to access images.json in the following way:

```
base_dir = '.'
if hasattr(sys, '_MEIPASS'):
        base_dir = os.path.join(sys._MEIPASS)
f = open(os.path.join(base_dir, 'image_generation', "images.json"))
```

This throws then the following error:

```
Traceback (most recent call last):
  File "server/main.py", line 948, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEILXN9NM/images.json'
[232107] Failed to execute script 'main' due to unhandled exception!
```

Accessing text.txt on the other hand works:

```
with open(os.path.join(base_dir, 'server', "topics.txt"), 'r') as file:
      prompt_topics = file.read()
```

**Comment by bwoodsend** [comment]
That is not a valid way to reference data files. See https://pyinstaller.org/en/stable/runtime-information.html#using-file

**Comment by rokm** [comment]
Is the hook executed, and is the `images.json` collected? (Again, best to check by inspecting the executable with `pyi-archive_viewer`).

The path in the error message,
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEILXN9NM/images.json'
```
seems to suggest that there is the `'image_generation'` component missing in the `os.path.join()` call. Can you verify which is incorrect here - the code snippet or the error message?

**Comment by rafael-wampfler** [comment]
I could solve the issue by moving the file images.json to the server package.

Thank you so much for your help.
