### ISSUE TITLE
 No module named 'Qt.QtSvg'; 'Qt' is not a package when I use Qt.py package

### ISSUE THREAD

**Issue by wandth** [pyinstaller/pyinstaller#8586]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.7.0```
* Version of Python: 3.10.11
* Platform: Windows10
* How you installed Python: venv
* Did you also try this on another platform? Does it work there?  ```no```

I write a  new project use PySide2 and used Qt.py (https://github.com/mottosso/Qt.py) ,
then I packed it

## runtime error
``` shell
E:\work\unreal\unrealManager\dist>E:\work\unreal\unrealManager\dist\unrealManager.exe
[24460] PyInstaller Bootloader 6.x
[24460] LOADER: executable is E:\work\unreal\unrealManager\dist\unrealManager.exe
[24460] LOADER: _MEIPASS2 is not set
[24460] LOADER: archivename is E:\work\unreal\unrealManager\dist\unrealManager.exe
[24460] LOADER: Cookie found at offset 0x6C80323
[24460] LOADER: initializing security descriptor for temporary directory...
[24460] LOADER: initializing security descriptor from string: D:(A;;FA;;;S-1-5-21-2713284416-1792508369-80763592-5154)
[24460] LOADER: creating temporary directory...
[24460] LOADER: Found runtime-tmpdir ./
[24460] LOADER: absolute runtime tmpdir is E:\work\unreal\unrealManager\dist\
[24460] LOADER: Successfully resolved the specified runtime-tmpdir
[24460] LOADER: created temporary directory: E:\work\unreal\unrealManager\dist\_MEI244602
[24460] LOADER: Extracting binaries
[24460] LOADER: Executing self as child
[24460] LOADER: set _MEIPASS2 to E:\work\unreal\unrealManager\dist\_MEI244602
[24460] LOADER: Setting up to run child
[24460] LOADER: Creating child process
[24460] LOADER: Waiting for child process to finish...
[41088] PyInstaller Bootloader 6.x
[41088] LOADER: executable is E:\work\unreal\unrealManager\dist\unrealManager.exe
[41088] LOADER: _MEIPASS2 is E:\work\unreal\unrealManager\dist\_MEI244602
[41088] LOADER: archivename is E:\work\unreal\unrealManager\dist\unrealManager.exe
[41088] LOADER: Cookie found at offset 0x6C80323
[41088] LOADER: SetDllDirectory(E:\work\unreal\unrealManager\dist\_MEI244602)
[41088] LOADER: Already in the child - running user's code.
[41088] LOADER: Python library: E:\work\unreal\unrealManager\dist\_MEI244602\python310.dll
[41088] LOADER: Loaded functions from Python library.
[41088] LOADER: Pre-initializing embedded python interpreter...
[41088] LOADER: Creating PyConfig structure...
[41088] LOADER: Initializing interpreter configuration...
[41088] LOADER: Setting program name...
[41088] LOADER: Setting python home path...
[41088] LOADER: Setting module search paths...
[41088] LOADER: Setting sys.argv...
[41088] LOADER: Applying run-time options...
[41088] LOADER: Starting embedded python interpreter...
[41088] LOADER: setting sys._MEIPASS
[41088] LOADER: importing modules from CArchive
[41088] LOADER: extracted struct
[41088] LOADER: running unmarshalled code object for struct...
[41088] LOADER: extracted pyimod01_archive
[41088] LOADER: running unmarshalled code object for pyimod01_archive...
[41088] LOADER: extracted pyimod02_importers
[41088] LOADER: running unmarshalled code object for pyimod02_importers...
[41088] LOADER: extracted pyimod03_ctypes
[41088] LOADER: running unmarshalled code object for pyimod03_ctypes...
[41088] LOADER: extracted pyimod04_pywin32
[41088] LOADER: running unmarshalled code object for pyimod04_pywin32...
[41088] LOADER: Installing PYZ archive with Python modules.
[41088] LOADER: PYZ archive: PYZ-00.pyz
[41088] LOADER: Running pyiboot01_bootstrap.py
[41088] LOADER: Running pyi_rth_inspect.py
[41088] LOADER: Running pyi_rth_pyside2.py
[41088] LOADER: Running pyi_rth_pkgutil.py
[41088] LOADER: Running pyi_rth_multiprocessing.py
[41088] LOADER: Running mainWindow.py
Traceback (most recent call last):
  File "unrealManager\mainWindow.py", line 7, in <module>
  File "C:\Users\wkd1049\AppData\Local\Temp\embedded.sizfhnur.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "dayu_widgets\__init__.py", line 14, in <module>
  File "C:\Users\wkd1049\AppData\Local\Temp\embedded.sizfhnur.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "dayu_widgets\theme.py", line 18, in <module>
  File "C:\Users\wkd1049\AppData\Local\Temp\embedded.sizfhnur.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "dayu_widgets\utils.py", line 38, in <module>
  File "C:\Users\wkd1049\AppData\Local\Temp\embedded.sizfhnur.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "dayu_widgets\qt\__init__.py", line 22, in <module>
  File "C:\Users\wkd1049\AppData\Local\Temp\embedded.sizfhnur.zip\shibokensupport\__feature__.py", line 142, in _import
ModuleNotFoundError: No module named 'Qt.QtSvg'; 'Qt' is not a package
[41088] Failed to execute script 'mainWindow' due to unhandled exception!
[41088] LOADER: ERROR.
[41088] LOADER: Manually flushing stdout and stderr
[41088] LOADER: Cleaning up Python interpreter.
[24460] LOADER: Back to parent (RC: 1)
[24460] LOADER: Doing cleanup
[24460] LOADER: Freeing archive status for E:\work\unreal\unrealManager\dist\unrealManager.exe
```

this same as that
- #https://github.com/pyinstaller/pyinstaller/issues/4218#issuecomment-623207487

**Comment by rokm** [comment]
You'll probably need to add the PySide2 submodules to hidden imports in order for it to work with `Qt.py`'s virtual modules.

I.e., try adding `--hiddenimport PySide2.QtSvg` to your PyInstaller command

**Comment by wandth** [comment]
> You'll probably need to add the PySide2 submodules to hidden imports in order for it to work with `Qt.py`'s virtual modules.
> 
> I.e., try adding `--hiddenimport PySide2.QtSvg` to your PyInstaller command

if works fine, thanks
