### ISSUE TITLE
a error in using pyinstaller to build a python source code

### ISSUE THREAD

**Issue by leizhu1989** [pyinstaller/pyinstaller#8604]
docker: paddlepaddle/paddle:latest-dev
python：3.9
pyinstaller：6.3.0
command: pyinstaller -n paddleocrtest --distpath=/paddle/PaddleOCR/dist --clean --onefile --hidden-import imghdr --hidden-import imgaug --hidden-import pyclipper --collect-data paddle --collect-all paddleocr /paddle/PaddleOCR/demo.py 

error：
30763 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
32148 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
39579 INFO: Loading module hook 'hook-pandas.plotting.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
48859 INFO: Analyzing hidden import 'imghdr'
48862 INFO: Analyzing hidden import 'imgaug'
50509 INFO: Analyzing hidden import 'pyclipper'
50510 INFO: Analyzing hidden import 'paddleocr.ppstructure'
50511 INFO: Analyzing hidden import 'paddleocr.ppstructure.layout'
50511 INFO: Analyzing hidden import 'paddleocr.ppstructure.layout.predict_layout'
50514 INFO: Analyzing hidden import 'paddleocr.ppstructure.predict_system'
50520 INFO: Analyzing hidden import 'paddleocr.ppstructure.recovery'
50521 INFO: Analyzing hidden import 'paddleocr.ppstructure.recovery.recovery_to_doc'
50843 INFO: Analyzing hidden import 'paddleocr.ppstructure.recovery.table_process'
50854 INFO: Analyzing hidden import 'paddleocr.ppstructure.table'
50854 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.convert_label2html'
50857 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.eval_table'
50859 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.matcher'
50863 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.predict_structure'
50867 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.predict_table'
50873 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.table_master_match'
50886 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.tablepyxl'
50887 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.tablepyxl.style'
50893 INFO: Analyzing hidden import 'paddleocr.ppstructure.table.tablepyxl.tablepyxl'
51363 INFO: Analyzing hidden import 'paddleocr.ppstructure.utility'
51365 INFO: Analyzing hidden import 'paddleocr.tools'
51366 INFO: Processing module hooks...
51366 INFO: Loading module hook 'hook-scipy.stats._stats.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
52715 INFO: Loading module hook 'hook-gi.repository.Gtk.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
52764 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
52893 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
53422 INFO: Loading module hook 'hook-gi.repository.GObject.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
53588 INFO: Loading module hook 'hook-gi.repository.GLib.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
53636 WARNING: Hidden import "importlib_resources.trees" not found!
53776 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
53799 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
53800 INFO: Matplotlib backend selection method: automatic discovery of used backends
53810 INFO: Discovered Matplotlib backend(s) via matplotlib.use() call in module 'paddle.dataset.uci_housing': ['Agg']
53814 INFO: The following Matplotlib backends were discovered by scanning for matplotlib.use() calls: ['Agg']. If your backend of choice is not in this list, either add a matplotlib.use() call to your code, or configure the backend collection via hook options (see: https://pyinstaller.org/en/stable/hooks-config.html#matplotlib-hooks).
53814 INFO: Selected matplotlib backends: ['Agg']
53818 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from '/usr/local/lib/python3.9/dist-packages/PyInstaller/hooks'...
53878 INFO: Performing binary vs. data reclassification (2498 entries)
54035 INFO: Looking for ctypes DLLs
54223 WARNING: Library user32 required via ctypes not found
54634 WARNING: Library msvcrt required via ctypes not found
Traceback (most recent call last):
File "/usr/local/bin/pyinstaller", line 8, in
sys.exit(_console_script_run())
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/main.py", line 214, in _console_script_run
run()
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/main.py", line 198, in run
run_build(pyi_config, spec_file, **vars(args))
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/main.py", line 69, in run_build
PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/build_main.py", line 1071, in main
build(specfile, distpath, workpath, clean_build)
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/build_main.py", line 1011, in build
exec(code, spec_namespace)
File "/paddle/PaddleOCR/paddleocrtest.spec", line 13, in
a = Analysis(
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/build_main.py", line 470, in init
self.postinit()
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/datastruct.py", line 184, in postinit
self.assemble()
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/build_main.py", line 683, in assemble
for (dest, source) in format_binaries_and_datas(self.graph.metadata_required()))
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/depend/analysis.py", line 775, in metadata_required
out |= self._metadata_from(
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/depend/analysis.py", line 834, in _metadata_from
out.update(copy_metadata(package))
File "/usr/local/lib/python3.9/dist-packages/PyInstaller/utils/hooks/init.py", line 973, in copy_metadata
dest_path = os.path.join(*src_path.parts[-2:])
AttributeError: 'Path' object has no attribute 'parts'

**Comment by rokm** [comment]
What version of `importlib-metadata` do you have installed in that python environment?

**Comment by rokm** [comment]
Or rather, how is `paddle` installed? Is it a zipped egg? PyInstaller 6.x does not support those anymore. 

The only way I can seem to trigger a `AttributeError: 'Path' object has no attribute 'parts'` is if I try to collect metadata of a package that is installed as a zipped egg.

**Comment by bwoodsend** [comment]
There is no distribution or package called `paddle` or `paddleocr` on that docker container.

**Comment by rokm** [comment]
Hmmm, then this is triggered by something else that is installed as zipped egg in there. The error seems to originate from processing of automatically-detected uses of metadata (`self.graph.metadata_required()`).

**Comment by rokm** [comment]
`/usr/local/lib/python3.9/dist-packages/setuptools-50.3.2-py3.9.egg` is a pretty likely candidate.

An `import setuptools` program is enough to trigger
```
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/__main__.py", line 231, in _console_script_run
    run()
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/build_main.py", line 1216, in main
    build(specfile, distpath, workpath, clean_build)
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/build_main.py", line 1156, in build
    exec(code, spec_namespace)
  File "/home/program.spec", line 4, in <module>
    a = Analysis(
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/build_main.py", line 556, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/building/build_main.py", line 771, in assemble
    for (dest, source) in format_binaries_and_datas(self.graph.metadata_required()))
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/depend/analysis.py", line 792, in metadata_required
    out |= self._metadata_from(
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/depend/analysis.py", line 851, in _metadata_from
    out.update(copy_metadata(package))
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/utils/hooks/__init__.py", line 973, in copy_metadata
    dest_path = os.path.join(*src_path.parts[-2:])
AttributeError: 'Path' object has no attribute 'parts'
```

It's also quite easy to imagine that `paddle` ends up pulling `setuptools` in.

**Comment by rokm** [comment]
I suppose we should check whether `dist._path` is an instance of `pathlib.Path` here: https://github.com/pyinstaller/pyinstaller/blob/79de48524d1407508ec7bfd4bea1703b5d4e44d0/PyInstaller/utils/hooks/__init__.py#L966

(in the case of zipped egg, it is `zipp.Path`)

The question is, should we abort with an error, or emit a warning and continue?

**Comment by bwoodsend** [comment]
I think an environment with uncollectable packages is sufficiently dangerous enough to be an error.
