### ISSUE TITLE
Adding a data file from a 3rd party package

### ISSUE THREAD

**Issue by aantn** [pyinstaller/pyinstaller#8620]
What is the correct way to explicitly package a data file in a third party library? I am trying to use pyinstaller on [HolmesGPT](https://github.com/robusta-dev/holmesgpt/) which has a dependency on [LiteLLM](https://github.com/BerriAI/litellm).

I get the following error:

```
Traceback (most recent call last):
  File "importlib/resources.py", line 97, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/holmesgpt/holmesgpt/anthropic_tokenizer.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "holmes.py", line 1, in <module>
    from holmes.main import run
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "holmes/main.py", line 15, in <module>
    from holmes.config import Config
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "holmes/config.py", line [13](https://github.com/robusta-dev/holmesgpt/actions/runs/9645639928/job/26600287574#step:5:14), in <module>
    from holmes.core.tool_calling_llm import (IssueInvestigator, ToolCallingLLM,
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "holmes/core/tool_calling_llm.py", line 8, in <module>
    import litellm
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "litellm/__init__.py", line 734, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "litellm/cost_calculator.py", line [15](https://github.com/robusta-dev/holmesgpt/actions/runs/9645639928/job/26600287574#step:5:16), in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 4[19](https://github.com/robusta-dev/holmesgpt/actions/runs/9645639928/job/26600287574#step:5:20), in exec_module
  File "litellm/utils.py", line 98, in <module>
  File "importlib/resources.py", line 1[21](https://github.com/robusta-dev/holmesgpt/actions/runs/9645639928/job/26600287574#step:5:22), in open_text
  File "importlib/resources.py", line 111, in open_binary
FileNotFoundError: 'anthropic_tokenizer.json' resource not found in 'litellm.llms.tokenizers'
[2938] Failed to execute script 'holmes' due to unhandled exception!
```

**Comment by rokm** [comment]
[`--collect-data packagename`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-data)

In your case, either `--collect-data litellm` or `--collect-data litellm.llms.tokenizers` depending on whether the data files are located in multiple sub-packages or just that particular sub-package.

**Comment by aantn** [comment]
Thank you for the rapid reply. For some reason that is working on python3.10 but not on python3.9. Both are tested in clean GitHub action runners. The same litellm dependency version was installed on both (1.40.25).

Any ideas?

**Comment by aantn** [comment]
And sorry! I looked through the manual but completely missed that somehow!

**Comment by rokm** [comment]
Could be a difference in `importlib.resources` behavior. Try adding `--hiddenimport litellm.llms.tokenizers` - perhaps the older version requires module to be present.

**Comment by aantn** [comment]
Thank you! That did the trick.

It might be worth adding a mention of `--collect-data` to https://pyinstaller.org/en/stable/spec-files.html#using-data-files-from-a-module

I think that is where I originally looked for `--collect-data` and didn't find it. I know that page is about the spec file, but it does mention other command line equivalents.

In any event, thank you again for all the help!
