### ISSUE TITLE
Error due to latest version of setuptools

### ISSUE THREAD

**Issue by 17Reset** [pyinstaller/pyinstaller#8665]
An error has occurred with the latest version of setuptools 71.0.0.
```
16451 INFO: Loading module hook 'hook-importlib_metadata.py' from 'G:\\X\\\Joker\\Configure\\joker_env\\Lib\\site-packages\\PyInstaller\\hooks'...
Traceback (most recent call last):
  File "D:\Python\Lib\importlib\metadata\__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\imphook.py", line 383, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\compat.py", line 583, in importlib_load_source
    mod_loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\hooks\hook-importlib_metadata.py", line 24, in <module>
    datas = copy_metadata('importlib_metadata')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 957, in copy_metadata
    dist = importlib_metadata.distribution(package_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\importlib\metadata\__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\importlib\metadata\__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for importlib_metadata

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "G:\X\Joker\Configure\joker_env\Scripts\pyinstaller.exe\__main__.py", line 8, in <module>
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\__main__.py", line 231, in _console_script_run
    run()
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\building\build_main.py", line 1216, in main
    build(specfile, distpath, workpath, clean_build)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\building\build_main.py", line 1156, in build
    exec(code, spec_namespace)
  File "G:\X\Joker\xLib\compiler\release\xLib Compiler.spec", line 4, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\building\build_main.py", line 556, in __init__
    self.__postinit__()
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\building\build_main.py", line 699, in assemble
    self.graph.add_hiddenimports(self.hiddenimports)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 744, in add_hiddenimports
    nodes = self.import_hook(modnm)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1232, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1232, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1232, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1245, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1232, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1245, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1245, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1232, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2257, in _safe_import_hook
    self.import_hook(
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1271, in import_hook
    for target_submodule in self._import_importable_package_submodules(
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1520, in _import_importable_package_submodules
    submodule = self._safe_import_module(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1232, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1232, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 501, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1792, in _safe_import_module
    self._process_imports(n)
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2591, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 368, in _safe_import_hook
    excluded_imports = self._find_all_excluded_imports(source_module.identifier)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\analysis.py", line 356, in _find_all_excluded_imports
    excluded_imports.update(module_hook.excludedimports)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\imphook.py", line 316, in __getattr__
    self._load_hook_module()
  File "G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\depend\imphook.py", line 386, in _load_hook_module
    raise ImportErrorWhenRunningHook(self.hook_module_name, self.hook_filename)
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_importlib_metadata required by hook for module G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\hooks\hook-importlib_metadata.py. Please check whether module __PyInstaller_hooks_0_importlib_metadata actually exists and whether the hook is compatible with your version of G:\X\Joker\Configure\joker_env\Lib\site-packages\PyInstaller\hooks\hook-importlib_metadata.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller
```

**Comment by bashonly** [comment]
Related: https://github.com/pypa/setuptools/issues/4477#issuecomment-2235157325

**Comment by bwoodsend** [comment]
Can we have a minimal reproducer example (and please not a link to a CI job)? I can't see this issue.

The stacktrace implies that you could get the error just by running `python .../site-packages/PyInstaller/hooks/hook-importlib_metadata.py` – can you confirm if that's true?

**Comment by rokm** [comment]
Looks like with new `setuptools`, you get `importlib_metadata` and `importlib_requirements` *for free*:

```
$ python
Python 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib_metadata'
>>> import importlib_resources
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib_resources'
>>> import setuptools
>>> import importlib_metadata
>>> importlib_metadata
<module 'importlib_metadata' from '/home/rok/tmp/pyi-setuptools-latest/venv/lib64/python3.12/site-packages/setuptools/_vendor/importlib_metadata/__init__.py'>
>>> import importlib_resources
>>> importlib_resources
<module 'importlib_resources' from '/home/rok/tmp/pyi-setuptools-latest/venv/lib64/python3.12/site-packages/setuptools/_vendor/importlib_resources/__init__.py'>
```

So I think those errors crop up only if `setuptools` happens to be imported during analysis prior to the part that tries to import `importlib_metadata`. And then the hook for `importlib_metadata` raises error because the `importlib-metadata` package's metadata is, in fact, unavailable.

There seems to also be issue with `PyInstaller.utils.hooks.check_requirement()` being called for `importlib-metadata` and `importlib-resources`...

**Comment by rokm** [comment]
Ah, actually... the error in `hook-importlib_metadata` can be reproduced with 
```
import importlib_metadata
print("hello")
```

and setuptools 71.0.0. 

They fixed this 71.0.1 by providing minimal metadata (but that in turn causes problems with `PyInstaller.utils.hooks.check_requirement()` in `importlib_resources` hook, because it does not provide version information...

**Comment by rokm** [comment]
I've opened https://github.com/pypa/setuptools/issues/4482, since this is caused by missing / partial metadata that `setuptools` provides for its now-exposed vendored dependencies.

**Comment by rokm** [comment]
Looks like we have failures on our CI that are likely caused by the new setuptools, even after 71.0.3 that addressed the metadata issues.

**Comment by reese-long** [comment]
Downgrading setuptools before building with Pyinstaller is a workaround:
```pip install --force-reinstall -v "setuptools<70"```
