### ISSUE TITLE
Failed to execute script due to unhandled exception no module named 'babel.numbers'

### ISSUE THREAD

**Issue by sengmonkham** [pyinstaller/pyinstaller#8670]
I made a simple to do list app in tkinter which i then converted to an exe file using pyinstaller but when i try to run it  is giving me an error: 

Unhandled exception in script
failed to execute script due to unhandled exception no module named 'babel.numbers'
Traceback (most recent call last):
  File "to.py", line 105, in <module>
  File "tkcalendar\dateentry.py", line 128, in __init__
  File "tkcalendar\calendar_.py", line 258, in __init__
  File "babel\dates.py", line 285, in get_day_names
  File "babel\core.py", line 773, in days
  File "babel\core.py", line 439, in _data
  File "babel\localedata.py", line 137, in load
  File "babel\localedata.py", line 143, in load
ModuleNotFoundError: No module named 'babel.numbers'

I opened cmd and tried to install babel but it was already in my system

C:\Users\Administrator>pip install babel
Requirement already satisfied: babel in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (2.15.0)

can someone tell me why i am facing this error

**Comment by sengmonkham** [comment]
I figured it out on my own 
the solution was to use the "--hidden-import " option to specify the " babel.numbers"  module.
If anyone is facing this issue use this command in cmd to convert your file

pyinstaller --onefile --hidden-import=babel.numbers todo_list.py

you can also include  -w to eliminate the terminal:

pyinstaller --onefile --hidden-import=babel.numbers  -w todo_list.py
