### ISSUE TITLE
I get "UnicodeDecodeError" when there are Chinese characters in source code

### ISSUE THREAD

**Issue by zy0016** [pyinstaller/pyinstaller#8681]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.8.0```
* Version of Python: Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:13:20) [MSC v.1940 32 bit (Intel)] on win32
* Platform:  windows 10
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
E:\code\python\资产支持计划周报表格取数逻辑>pyinstaller --onefile main.py func.py FTPSync.py product_file_sync.py
394 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
394 INFO: Python: 3.12.4
448 INFO: Platform: Windows-10-10.0.19045-SP0
449 INFO: Python environment: D:\Python312-32
452 INFO: wrote E:\code\python\资产支持计划周报表格取数逻辑\main.spec
469 INFO: Module search paths (PYTHONPATH):
['D:\\Python312-32\\Scripts\\pyinstaller.exe',
 'D:\\Python312-32\\python312.zip',
 'D:\\Python312-32\\DLLs',
 'D:\\Python312-32\\Lib',
 'D:\\Python312-32',
 'D:\\Python312-32\\Lib\\site-packages',
 'E:\\code\\python\\资产支持计划周报表格取数逻辑',
 'E:\\code\\python\\资产支持计划周报表格取数逻辑',
 'E:\\code\\python\\资产支持计划周报表格取数逻辑',
 'E:\\code\\python\\资产支持计划周报表格取数逻辑']
863 INFO: checking Analysis
872 INFO: Building because D:\Python312-32\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_inspect.py changed
872 INFO: Running Analysis Analysis-00.toc
872 INFO: Target bytecode optimization level: 0
873 INFO: Initializing module dependency graph...
874 INFO: Caching module graph hooks...
894 INFO: Analyzing base_library.zip ...
2723 INFO: Loading module hook 'hook-encodings.py' from 'D:\\Python312-32\\Lib\\site-packages\\PyInstaller\\hooks'...
4921 INFO: Loading module hook 'hook-pickle.py' from 'D:\\Python312-32\\Lib\\site-packages\\PyInstaller\\hooks'...
6042 INFO: Loading module hook 'hook-heapq.py' from 'D:\\Python312-32\\Lib\\site-packages\\PyInstaller\\hooks'...
6619 INFO: Caching module dependency graph...
6790 INFO: Looking for Python shared library...
6821 INFO: Using Python shared library: D:\Python312-32\python312.dll
6821 INFO: Analyzing E:\code\python\资产支持计划周报表格取数逻辑\main.py
7051 INFO: Loading module hook 'hook-cryptography.py' from 'D:\\Python312-32\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
D:\Python312-32\Lib\site-packages\cryptography\hazmat\backends\openssl\backend.py:17: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.
  from cryptography.hazmat.bindings.openssl import binding
D:\Python312-32\Lib\site-packages\cryptography\hazmat\backends\openssl\backend.py:17: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.
  from cryptography.hazmat.bindings.openssl import binding
8873 INFO: Loading module hook 'hook-bcrypt.py' from 'D:\\Python312-32\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
9310 INFO: Loading module hook 'hook-nacl.py' from 'D:\\Python312-32\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
9721 INFO: Loading module hook 'hook-platform.py' from 'D:\\Python312-32\\Lib\\site-packages\\PyInstaller\\hooks'...
9784 INFO: Loading module hook 'hook-openpyxl.py' from 'D:\\Python312-32\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10096 INFO: Loading module hook 'hook-lxml.py' from 'D:\\Python312-32\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10691 INFO: Loading module hook 'hook-lxml.etree.py' from 'D:\\Python312-32\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10877 INFO: Loading module hook 'hook-xml.py' from 'D:\\Python312-32\\Lib\\site-packages\\PyInstaller\\hooks'...
10906 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'D:\\Python312-32\\Lib\\site-packages\\PyInstaller\\hooks'...
11880 INFO: Loading module hook 'hook-cx_Oracle.py' from 'D:\\Python312-32\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
11884 INFO: Analyzing E:\code\python\资产支持计划周报表格取数逻辑\func.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Python312-32\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\Python312-32\Lib\site-packages\PyInstaller\__main__.py", line 231, in _console_script_run
    run()
  File "D:\Python312-32\Lib\site-packages\PyInstaller\__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Python312-32\Lib\site-packages\PyInstaller\__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\Python312-32\Lib\site-packages\PyInstaller\building\build_main.py", line 1216, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:\Python312-32\Lib\site-packages\PyInstaller\building\build_main.py", line 1156, in build
    exec(code, spec_namespace)
  File "E:\code\python\资产支持计划周报表格取数逻辑\main.spec", line 4, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "D:\Python312-32\Lib\site-packages\PyInstaller\building\build_main.py", line 556, in __init__
    self.__postinit__()
  File "D:\Python312-32\Lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "D:\Python312-32\Lib\site-packages\PyInstaller\building\build_main.py", line 696, in assemble
    program_scripts.append(self.graph.add_script(script))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python312-32\Lib\site-packages\PyInstaller\depend\analysis.py", line 283, in add_script
    return super().add_script(pathname, caller=caller)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python312-32\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1153, in add_script
    contents = importlib.util.decode_source(contents)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 794, in decode_source
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 783: invalid continuation byte

E:\code\python\资产支持计划周报表格取数逻辑>
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.
[资产支持计划周报表格取数逻辑.zip](https://github.com/user-attachments/files/16343303/default.zip)

**Comment by zy0016** [comment]
update: I use the 6.9.0 pyinstaller
E:\code\python\资产支持计划周报表格取数逻辑>pyinstaller --version
6.9.0

**Comment by rqx110** [comment]
试试将func.py保存为utf-8格式的文件编码

**Comment by bwoodsend** [comment]
That `file_suffix = "..."` bit isn't valid unicode. Even normal Python can't read it.

```console
$ python 资产支持计划周报表格取数逻辑/func.py 
SyntaxError: Non-UTF-8 code starting with '\xd7' in file 资产支持计划周报表格取数逻辑/func.py on line 31, but no encoding declared; see https://peps.python.org/pep-0263/ for details
```
