### ISSUE TITLE
Unknown error message

### ISSUE THREAD

**Issue by 17Reset** [pyinstaller/pyinstaller#8682]
Why is there the following message? Although this does not affect me to package out an exe file

```
INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
INFO: Python: 3.12.4
INFO: Platform: Windows-11-10.0.26100-SP0
···
···
···
INFO: Loading module hook 'hook-cryptography.py' from 'G:\\xlab\\Configure\\joker_env\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
WARNING: hook-cryptography: failed to determine whether cryptography is using OpenSSL >= 3.0.0
Traceback (most recent call last):
  File "G:\xlab\Configure\joker_env\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py", line 62, in <module>
    uses_openssl3 = _check_cryptography_openssl3()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\xlab\Configure\joker_env\Lib\site-packages\PyInstaller\isolated\_parent.py", line 420, in wrapped
    return call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\xlab\Configure\joker_env\Lib\site-packages\PyInstaller\isolated\_parent.py", line 389, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\xlab\Configure\joker_env\Lib\site-packages\PyInstaller\isolated\_parent.py", line 319, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to _check_cryptography_openssl3() failed with:
  File "G:\xlab\Configure\joker_env\Lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\xlab\Configure\joker_env\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py", line 60, in _check_cryptography_openssl3
    return bool(backend._lib.CRYPTOGRAPHY_OPENSSL_300_OR_GREATER)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'CRYPTOGRAPHY_OPENSSL_300_OR_GREATER'
```
```
(joker_env) G:\xlab\Deploy>uv pip show cryptography
Name: cryptography
Version: 43.0.0
Location: G:\xlab\Configure\joker_env\Lib\site-packages
Requires: cffi
Required-by: paramiko
```

**Comment by rokm** [comment]
Looks like the attribute we are checking has been removed in cryptography 43.0.0. 

In the retrospect, we should probably be using `backend.openssl_version_number()` instead...
