### ISSUE TITLE
Pyinstaller along with interpolator and PySide6

### ISSUE THREAD

**Issue by afrbd** [pyinstaller/pyinstaller#8685]
## Description of the issue
Hi there.
I am unable to run a freezed exe of an app containing `scipy.interpolate.interp1d`. I have currently added required hooks from numpy _pyinstaller directory[the hook-numpy.py] (and for pyside6 and shibokeh6) and have also added scipy.interpolate as hidden_import. The code and spec file are as following:
```python
from PySide6.QtWidgets import QMainWindow,QLabel, QApplication
from PySide6.QtCore import QRect
import sys
import numpy as np
from scipy.interpolate import interp1d

if __name__ == '__main__':
    appctxt = QApplication([])       # 1. Instantiate ApplicationContext
    window = QMainWindow()
    window.resize(250, 150)
    lbl = QLabel(window)
    lbl.setGeometry(QRect(20,50, 200,50))
        # Example data points (you can replace these with your own data)
    x = np.array([0, 1, 2, 3, 4])
    y = np.array([0, 2, 1, 3, 4])

    # Create an interpolation function
    interpolated_function = interp1d(x, y, kind='linear')

    # Evaluate the function at a new point (e.g., x=2.5)
    new_x = 2.5
    interpolated_value = interpolated_function(new_x)

    lbl.setText(f"Interpolated value at x={new_x}: {interpolated_value}")

    window.show()
    exit_code = appctxt.app.exec_()      # 2. Invoke appctxt.app.exec_()
    sys.exit(exit_code)
```
```python
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['scipy._lib.messagestream','scipy','scipy.signal','scipy.signal.bsplines','scipy.special','scipy.special._ufuncs_cxx','scipy.linalg.cython_blas','scipy.linalg.cython_lapack','scipy.integrate','scipy.integrate.quadrature','scipy.integrate.odepack','scipy.integrate._odepack','scipy.integrate.quadpack','scipy.integrate._quadpack','scipy.integrate._ode','scipy.integrate.vode','scipy.integrate._dop','scipy._lib','scipy._build_utils','scipy.__config__','scipy.integrate.lsoda','scipy.cluster','scipy.constants','scipy.fftpack','scipy.interpolate','scipy.io','scipy.linalg','scipy.misc','scipy.ndimage','scipy.odr','scipy.optimize','scipy.setup','scipy.sparse','scipy.spatial','scipy.special','scipy.stats','scipy.version','numpy.f2py'],
    hookspath=['/hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    icon='Icon.ico',
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='main',
)

```
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(6.8.0)```
* Version of Python: 3.11.9
* Platform: Windows
* How you installed Python:  python.org/downloads
* Did you also try this on another platform? Does it work there? On ubuntu virtual machine. It didn't also work!
  * [done] start with clean installation(in a virtual environment)
  * [done] use the latest development version
  * [done] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [done] Package your program in **--onedir mode**
  * [done] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [done] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "scipy\interpolate\__init__.py", line 167, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "scipy\interpolate\_interpolate.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "scipy\special\__init__.py", line 781, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "scipy\special\_support_alternative_backends.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "scipy\_lib\_array_api.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "scipy\_lib\array_api_compat\numpy\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "numpy\f2py\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "numpy\f2py\f2py2e.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "numpy\f2py\crackfortran.py", line 159, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "numpy\f2py\auxfuncs.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
  File "numpy\f2py\cfuncs.py", line 19, in <module>
AttributeError: 'NoneType' object has no attribute 'write'
```
before I had added hook-numpy.py the error was for the same file:
```
No module named 'numpy.f2py'
```
which I can't reproduce due to automatically finding hooks of virtual environment directory.
```
'C:\\DATA_LD\\LDS\\Lib\\site-packages\\PyInstaller\\hooks'
```

**Comment by rokm** [comment]
> ### Stacktrace / full error message
> 
> ```
>  ...
>   File "numpy\f2py\auxfuncs.py", line 19, in <module>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 421, in exec_module
>   File "numpy\f2py\cfuncs.py", line 19, in <module>
> AttributeError: 'NoneType' object has no attribute 'write'
> ```

See https://github.com/orgs/pyinstaller/discussions/8679.

**Comment by afrbd** [comment]
Thanks it was solved
