### ISSUE TITLE
Permissions set on the application temp directory prevent onefile executables from importing modules after switching users

### ISSUE THREAD

**Issue by haboustak** [pyinstaller/pyinstaller#8711]
## Description of the issue
A python script that changes the current user via `os.setuid()` causes `PermissionError` exceptions when importing Python modules after switching users, due to the permissions (`0o700`) set on the application temporary directory. These are the default permissions for directories created by `mkdtmp()`.

Setting the directory permissions to `0o755` within the bootloader should resolve the issue. Granting these additional permissions could be a considered a security issue, so it may be desirable to match the owner and permissions of the temp directory to the owner and permissions of the original executable. That is, any user that can read, write, or execute the pyinstaller-packaged executable can also read, write, or execute the temporary directory.

### Context information
* Output of `pyinstaller --version`: ```6.9.0```
* Version of Python: `3.11.2`
* Platform: `Debian 12.5`
* How you installed Python: `apt install python3`
* Did you also try this on another platform? Does it work there?: `Did not try other platforms`

* Try the latest development version:  `Latest development version is worse, script refuses to start.`

### A minimal example program which shows the error

```python
import os
import sys

def main():
    if os.geteuid() != 0:
        print("ERROR: You must execute this script as root");
        sys.exit(1)

    # Reproducer assumes uid 1000 is a valid user. This is the ID
    # used by the first non-system user on Debian 12.
    os.setuid(1000)

    # Any import of a non-built-in module fails after switching user
    import requests

    print('ok')

if __name__ == '__main__':
    main()
```

### Stacktrace / full error message

```
$ pyinstaller --onefile --distpath ./dist -n script.onefile ./script.py
$ sudo ./dist/script.onefile 
Traceback (most recent call last):
  File "script.py", line 20, in <module>
    main()
  File "script.py", line 14, in main
    import requests
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "requests/__init__.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "urllib3/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "logging/__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1080, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen zipimport>", line 169, in find_spec
  File "<frozen importlib._bootstrap>", line 435, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 798, in spec_from_file_location
  File "<frozen zipimport>", line 228, in get_filename
  File "<frozen zipimport>", line 758, in _get_module_code
  File "<frozen zipimport>", line 592, in _get_data
PermissionError: [Errno 13] Permission denied: '/tmp/_MEIkgoJNm/base_library.zip'
[316158] Failed to execute script 'script' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
Matching the executable's permissions sounds reasonable to me although I think we need caps in case the executable has either too strict/liberal permissions. We need a minimum of `0o700` in case the application currently only has `0o500`. You're not supposed to write to the `_MEI` directory so I'm reluctant to grant the write bits. And whilst I'm struggling to wrap my head around the consequences of it, I can't believe that propagating the `setuid`/`setguid` bits is a good idea.

How does `(current_permissions | 0o700) & 0o755` sound?

**Comment by rokm** [comment]
I don't think automatic inference is a good idea, as it might lead to mismatch between expectations/intentions of the executable creator and actual permissions being set on the target system (explicitly by the user, or implicitly by whatever mechanism places the executable in its final location).

I think I would prefer this to be an explicit build-time bootloader flag - "allow other users read-only access to temporary directory". If not specified (the default), we continue creating directories with `0o700`, otherwise, we use `0o755`. (EDIT: to clarify, I mean run-time bootloader option, set at application build time).

**Comment by bwoodsend** [comment]
Yeah, that sounds better. Should we use a fully generalised `--runtime-tempdir-permissions=0o755` option or reduce it to a boolean switch which toggles it from `0o700` to `0o755`?

**Comment by rokm** [comment]
> Yeah, that sounds better. Should we use a fully generalised `--runtime-tempdir-permissions=0o755` option or reduce it to a boolean switch which toggles it from `0o700` to `0o755`?

I'd prefer an "abstract" switch, because at least in theory, we could then try also mapping it to Windows codepath.

**Comment by haboustak** [comment]
The build-time switch sounds fine with me, especially if you can handle this `PermissionError` during `import` and provide some guidance to the person performing the application packaging ("ERROR: Import failed due to insufficient application temp dir permissions").

As far as concerns on granting too many permissions, like `0o777`, POSIX has umask for that and so something similar would have made sense to me.

The problem I see with *not* following the ACLs on the target executable is that the *end-user* is no longer in control of permissions. Normally they have the ultimate control of who can read or execute a binary. I might put a pyinstaller-packaged application in `/usr/local/sbin` with permissions `0o744` and then it's extracted into the temp dir as `0o755` allowing non-owners the ability to execute anything extracted to the temp dir while the application runs.

**Comment by rokm** [comment]
> The problem I see with _not_ following the ACLs on the target executable is that the _end-user_ is no longer in control of permissions. Normally they have the ultimate control of who can read or execute a binary.

*Should* they be, though? I mean, for the main executable, definitely yes, and nothing changes in that regard. But for the guts of the frozen application?

> I might put a pyinstaller-packaged application in `/usr/local/sbin` with permissions `0o744` and then it's extracted into the temp dir as `0o755` allowing non-owners the ability to execute anything extracted to the temp dir while the application runs.

If we followed the ACLs in that case and created temporary directory with `0o744`, then your root-changed-into-user example would not work either, would it? Since the directory needs `x` permission for non-owners to access its contents.

**Comment by rokm** [comment]
I suppose the question might really be, what should be default permissions for extracted *files* (executable and non-executable), in addition to those for directories.

EDIT: I guess that is what you meant by having `umask` equivalent?

**Comment by rokm** [comment]
But quite honestly, I'm starting to question whether ~we~ I really want to extend onefile's permission system to accommodate this use case to that extent. 

Because unless these root-changed-into-user scenarios are very common, it might make more sense to require you to change ownership or permissions of the `sys._MEIPASS` (and its sub-directories and/or files) from within python code before you change the user.

**Comment by bwoodsend** [comment]
I'd rather give people the `0o755` flag than encourage them to modify `sys._MEIPASS` at runtime.

**Comment by haboustak** [comment]
> Because unless these root-changed-into-user scenarios are very common, it might make more sense to require you to change ownership or permissions of the `sys._MEIPASS` (and its sub-directories and/or files) from within python code before you change the user.

You should be able to pyinstall a script that you didn't write. It's OK for the packager to control `onefile` permissions, but I don't think it's reasonable for the script to be aware that it's running via `pyinstaller --onefile`.

> I suppose the question might really be, what should be default permissions for extracted _files_ (executable and non-executable), in addition to those for directories.

I've thought more about this and I generally agree that there are issues with the extracted content, not just the temp dir. When I mentioned `umask`, my perspective is that all files are extracted with either mode 777 (for directories or executables) or 666 (for data files). Then we'd rely on the umask (default `022`) to restrict access.

The way you'd use umask to transfer executable permissions to the onefile directory is to calculate the umask based on the executable. Something like this in `pyi_main.c`
```c
struct stat info;
if (stat(pyi_ctx->executable_filename, &info) != 0)
    return -1;

mode_t archive_mask = (~info.st_mode & 077);
PYI_DEBUG("LOADER: executable permissions: %o\n", info.st_mode);
PYI_DEBUG("LOADER: archive umask: %o\n", archive_mask);
```

Then you can set `umask(archive_mask)` and files created with 777 permissions will grant `rwx` to owner, and match the executable for group and other.

For the group permissions to work as expected, you'd need to set the group on both the temp dir and the extracted files. You can do this by setting `set-gid` on the temp dir before extracting. It might be better to put these attributes on the context and set them for each file or directory as it's extracted.

```c
if (pyi_create_temporary_application_directory(pyi_ctx) < 0) {
    PYI_ERROR("Could not create temporary directory!\n");
    return -1;
}

if (chown(pyi_ctx->application_home_dir, info.st_uid, info.st_gid) != 0) {
    PYI_DEBUG("LOADER: could not home_dir owner\n");
}
if (chmod(pyi_ctx->application_home_dir, info.st_mode | S_ISGID) != 0) {
    PYI_DEBUG("LOADER: could not set homd_dir mode\n");
}
```

Here's what happens if you combine these ideas and run a basic script as a normal user without the whole `os.setuid` part, just focusing on matching the permissions on files extracted due to `--onedir` to the permissions set by the end user on the executable.

```
$ groups
haboustak dialout sudo wireshark docker

$ chmod 740 ./dist/script.onefile
$ chgrp dialout dist/script.onefile
$ ls -al ./dist/script.onefile 
-rwxr----- 1 haboustak dialout 7095144 Aug  6 22:52 ./dist/script.onefile

$ ls -al /tmp/_MEIlynfLa/
total 14128
drwxr-S---  3 haboustak dialout    4096 Aug  6 23:06 .
drwxrwxrwt 34 root       root       4096 Aug  6 23:06 ..
-rw-r-----  1 haboustak dialout 1437256 Aug  6 23:06 base_library.zip
-rw-r-----  1 haboustak dialout   74688 Aug  6 23:06 libbz2.so.1.0
-rw-r-----  1 haboustak dialout 4713752 Aug  6 23:06 libcrypto.so.3
drwxr-S---  2 haboustak dialout    4096 Aug  6 23:06 lib-dynload
-rw-r-----  1 haboustak dialout  174216 Aug  6 23:06 libexpat.so.1
-rw-r-----  1 haboustak dialout  190456 Aug  6 23:06 liblzma.so.5
-rw-r-----  1 haboustak dialout 7732544 Aug  6 23:06 libpython3.11.so.1.0
-rw-r-----  1 haboustak dialout  121280 Aug  6 23:06 libz.so.1
```

The `umask` and `set-gid` bit are just conveniences to reduce code. You can set all these owners/permissions manually when extracting files.

**Comment by rokm** [comment]
> > Because unless these root-changed-into-user scenarios are very common, it might make more sense to require you to change ownership or permissions of the `sys._MEIPASS` (and its sub-directories and/or files) from within python code before you change the user.
> 
> You should be able to pyinstall a script that you didn't write. 

As long as script's behavior is not inherently incompatible with PyInstaller's run-time behavior (or specific build mode).

> It's OK for the packager to control `onefile` permissions, but I don't think it's reasonable for the script to be aware that it's running via `pyinstaller --onefile`.

I don't think it's reasonable to run the application via sudo and de-elevate privileges / switch to user in the middle of execution, either. In addition to issues with `sys._MEIPASS` permissions in onefile mode, by the time you get around to the `os.setuid` call, all the run-time hooks have been run as well, and those might have set up their own temporary directories as well; same goes for 3rd party packages that  might have been imported during the process. This latter part applies to both `onefile` and `onedir` mode, but depending on your script and packages it uses, it might not be a problem.

> > I suppose the question might really be, what should be default permissions for extracted _files_ (executable and non-executable), in addition to those for directories.
> 
> I've thought more about this and I generally agree that there are issues with the extracted content, not just the temp dir. When I mentioned `umask`, my perspective is that all files are extracted with either mode 777 (for directories or executables) or 666 (for data files). Then we'd rely on the umask (default `022`) to restrict access.
> 
> The way you'd use umask to transfer executable permissions to the onefile directory is to calculate the umask based on the executable. Something like this in `pyi_main.c`
> 
> ```c
> struct stat info;
> if (stat(pyi_ctx->executable_filename, &info) != 0)
>     return -1;
> 
> mode_t archive_mask = (~info.st_mode & 077);
> PYI_DEBUG("LOADER: executable permissions: %o\n", info.st_mode);
> PYI_DEBUG("LOADER: archive umask: %o\n", archive_mask);
> ```
> 
> Then you can set `umask(archive_mask)` and files created with 777 permissions will grant `rwx` to owner, and match the executable for group and other.
> 
> For the group permissions to work as expected, you'd need to set the group on both the temp dir and the extracted files. You can do this by setting `set-gid` on the temp dir before extracting. It might be better to put these attributes on the context and set them for each file or directory as it's extracted.
> 
> ```c
> if (pyi_create_temporary_application_directory(pyi_ctx) < 0) {
>     PYI_ERROR("Could not create temporary directory!\n");
>     return -1;
> }
> 
> if (chown(pyi_ctx->application_home_dir, info.st_uid, info.st_gid) != 0) {
>     PYI_DEBUG("LOADER: could not home_dir owner\n");
> }
> if (chmod(pyi_ctx->application_home_dir, info.st_mode | S_ISGID) != 0) {
>     PYI_DEBUG("LOADER: could not set homd_dir mode\n");
> }
> ```
> 
> Here's what happens if you combine these ideas and run a basic script as a normal user without the whole `os.setuid` part, just focusing on matching the permissions on files extracted due to `--onedir` to the permissions set by the end user on the executable.
> 
> ```
> $ groups
> haboustak dialout sudo wireshark docker
> 
> $ chmod 740 ./dist/script.onefile
> $ chgrp dialout dist/script.onefile
> $ ls -al ./dist/script.onefile 
> -rwxr----- 1 haboustak dialout 7095144 Aug  6 22:52 ./dist/script.onefile
> 
> $ ls -al /tmp/_MEIlynfLa/
> total 14128
> drwxr-S---  3 haboustak dialout    4096 Aug  6 23:06 .
> drwxrwxrwt 34 root       root       4096 Aug  6 23:06 ..
> -rw-r-----  1 haboustak dialout 1437256 Aug  6 23:06 base_library.zip
> -rw-r-----  1 haboustak dialout   74688 Aug  6 23:06 libbz2.so.1.0
> -rw-r-----  1 haboustak dialout 4713752 Aug  6 23:06 libcrypto.so.3
> drwxr-S---  2 haboustak dialout    4096 Aug  6 23:06 lib-dynload
> -rw-r-----  1 haboustak dialout  174216 Aug  6 23:06 libexpat.so.1
> -rw-r-----  1 haboustak dialout  190456 Aug  6 23:06 liblzma.so.5
> -rw-r-----  1 haboustak dialout 7732544 Aug  6 23:06 libpython3.11.so.1.0
> -rw-r-----  1 haboustak dialout  121280 Aug  6 23:06 libz.so.1
> ```
> 
> The `umask` and `set-gid` bit are just conveniences to reduce code. You can set all these owners/permissions manually when extracting files.

I suppose this approach is indeed more flexible, because your original `os.setuid` example could be accommodated either by having the executable owned by root and permissions set to 755 (essentially what the proposed 755 flag would do) or by having it owned by user and permissions set to 700. The former would allow all other users to read the contents of `sys._MEIIPASS` (and execute any executables found in there), the latter would give the specific user write access to `sys._MEIPASS` (but that's the same as if directory's ownership was changed from python code before the `os.setuid` call).

So as long as it is explicitly opt-in, I'm fine with this approach instead of just 755 flag (it will be POSIX-specific, but that's OK). I cannot think of a scenario other than the discussed one where this could be useful, and we wouldn't want to expose users that don't need this behavior to potential corner cases (e.g., someone running user-owned executable as root and then complaining that (the same) user has full access to `sys._MEIPASS` of application running under root privileges).
