### ISSUE TITLE
KeyError on Flask app using pyinstaller with `setuptools_scm`

### ISSUE THREAD

**Issue by matt-sd-watson** [pyinstaller/pyinstaller#8721]
I at attempting to package a Python package containing numerous modules that is Flask application into an executable. The pkg is generated successfully using the following spec:

```
# -*- mode: python ; coding: utf-8 -*-
import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)

a = Analysis(
    ['my_app/wsgi.py'],
    pathex=[],
    binaries=[],
    datas=[('rakaia', 'rakaia'), ('rakaia/templates', 'templates'), ('rakaia/assets', 'assets'),
    ('/home/matt/anaconda3/lib/python3.9/site-packages/jupyter_dash', 'jupyter_dash'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_canvas', 'dash_canvas'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_ag_grid', 'dash_ag_grid'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_draggable', 'dash_draggable'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_testing_stub', 'dash_testing_stub'),
('/home/matt/anaconda3/lib/python3.9/site-packages/setuptools.pth', 'setuptools.pth'),
('/home/matt/anaconda3/lib/python3.9/site-packages/setuptools_scm', 'setuptools_scm'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_tour_component', 'dash_tour_component'),
('/home/matt/anaconda3/lib/python3.9/site-packages/anndata', 'anndata'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_bootstrap_components', 'dash_bootstrap_components'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_google_auth', 'dash_google_auth'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash', 'dash'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_extensions', 'dash_extensions'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_table', 'dash_table'),
('/home/matt/anaconda3/lib/python3.9/site-packages/setuptools', 'setuptools'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_auth', 'dash_auth'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_uploader', 'dash_uploader'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_bootstrap_templates', 'dash_bootstrap_templates'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_html_components', 'dash_html_components'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_bio', 'dash_bio'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_mantine_components', 'dash_mantine_components'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_daq', 'dash_daq'),
('/home/matt/anaconda3/lib/python3.9/site-packages/dash_core_components', 'dash_core_components')
],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='my_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```
However, upon trying to execute the executable, I get the following trace:

```
Traceback (most recent call last):
  File "anndata/_metadata.py", line 28, in <module>
  File "/tmp/_MEIlzkku8/setuptools_scm/_get_version_impl.py", line 155, in get_version
    maybe_version = _get_version(config, force_write_version_files=True)
  File "/tmp/_MEIlzkku8/setuptools_scm/_get_version_impl.py", line 93, in _get_version
    parsed_version = parse_version(config)
  File "/tmp/_MEIlzkku8/setuptools_scm/_get_version_impl.py", line 56, in parse_version
    or parse_scm_version(config)
  File "/tmp/_MEIlzkku8/setuptools_scm/_get_version_impl.py", line 35, in parse_scm_version
    return _entrypoints.version_from_entrypoint(
  File "/tmp/_MEIlzkku8/setuptools_scm/_entrypoints.py", line 53, in version_from_entrypoint
    for ep in iter_matching_entrypoints(root, entrypoint, config):
  File "/tmp/_MEIlzkku8/setuptools_scm/discover.py", line 63, in iter_matching_entrypoints
    for ep in iter_entry_points(entrypoint):
  File "/tmp/_MEIlzkku8/setuptools_scm/_entrypoints.py", line 63, in iter_entry_points
    eps: EntryPoints = entry_points(group=group)
  File "/tmp/_MEIlzkku8/setuptools_scm/_entrypoints.py", line 38, in entry_points
    return EntryPoints(legacy_entry_points()[group])
KeyError: 'setuptools_scm.parse_scm'
```

This is my current condaa environment using `pip freeze`:

```
altgraph==0.17.4
anndata==0.9.1
async-generator==1.10
attrs==23.1.0
beautifulsoup4==4.12.2
cachelib==0.9.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
click-log==0.4.0
colorspacious==1.1.2
contourpy==1.0.7
coverage==7.5.4
cryptography==41.0.1
cycler==0.11.0
Cython==0.29.35
dash==2.10.2
dash-ag-grid==2.3.0
dash-auth==2.0.0
dash-bootstrap-components==1.4.1
dash-core-components==2.0.0
dash-draggable==0.1.2
dash-extensions==1.0.1
dash-google-auth==0.1.2
dash-html-components==2.0.0
dash-mantine-components==0.12.1
dash-table==5.0.0
dash-testing-stub==0.0.2
dash-tour-component==0.0.2
dash_canvas==0.1.0
dash_daq==0.5.0
dash_uploader==0.7.0a1
dill==0.3.6
diskcache==5.6.1
dnspython==2.6.1
EditorConfig==0.12.3
exceptiongroup==1.1.1
fcswrite==0.6.2
Flask==2.2.5
Flask-Caching==2.0.2
Flask-Dance==7.0.0
Flask-HTTPAuth==4.8.0
fonttools==4.39.4
freeport==0.1.15
glasbey==0.2.0
h11==0.14.0
h5py==3.8.0
idna==3.4
igraph==0.10.4
imagecodecs==2023.3.16
imageio==2.31.0
imctools==2.1.8
importlib-metadata==6.6.0
importlib-resources==5.12.0
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
joblib==1.2.0
jsbeautifier==1.14.8
kaleido==0.2.1
kiwisolver==1.4.4
lazy_loader==0.2
leidenalg==0.9.1
llvmlite==0.40.0
lxml==4.9.2
MarkupSafe==2.1.3
matplotlib==3.7.1
mongomock==4.1.2
more-itertools==9.1.0
multiprocess==0.70.14
natsort==8.3.1
networkx==3.1
numba==0.57.0
numexpr==2.8.7
numpy==1.24.3
oauthlib==3.2.2
opencv-python-headless==4.7.0.72
outcome==1.2.0
packaging==24.1
pandas==2.0.2
patsy==0.5.3
percy==2.0.2
PhenoGraph==1.5.7
Pillow==9.5.0
pipenv==2023.7.23
plotly==5.14.1
pluggy==1.0.0
psutil==5.9.5
pycparser==2.21
pydantic==1.10.8
pyinstaller==6.9.0
pyinstaller-hooks-contrib==2024.7
pymongo==4.6.1
pynndescent==0.5.10
pyOpenSSL==23.2.0
pyparsing==3.0.9
PySocks==1.7.1
pytest==7.3.1
pytest-cov==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyWavelets==1.4.1
readimc==0.7.0
requests==2.31.0
requests-oauthlib==1.3.1
scanpy==1.9.3
scikit-image==0.21.0
scikit-learn==1.2.2
scipy==1.10.1
sd-material-ui==4.6.0
seaborn==0.12.2
selenium==4.2.0
sentinels==1.0.0
session_info==1.0.0
setuptools-scm==8.1.0
shortuuid==1.0.12
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
statsmodels==0.14.0
stdlib-list==0.8.0
steinbock==0.16.1
tenacity==8.2.2
texttable==1.6.7
threadpoolctl==3.1.0
tifffile==2023.4.12
tomli==2.0.1
tqdm==4.65.0
trio==0.22.0
trio-websocket==0.10.2
typing_extensions==4.6.3
tzdata==2023.3
umap-learn==0.5.6
urllib3==1.26.16
urllib3-secure-extra==0.1.0
URLObject==2.4.3
virtualenv-clone==0.5.7
waitress==2.1.2
Werkzeug==2.2.3
wsproto==1.2.0
xmltodict==0.13.0
xtiff==0.7.9
zipp==3.15.0
```

**Comment by rokm** [comment]
You need to collect metadata and modules for `setuptools_scm.parse_scm` entry-point, using [`PyInstaller.utils.hooks.collect_entry_point`](https://pyinstaller.org/en/stable/hooks.html#PyInstaller.utils.hooks.collect_entry_point).

For example,

```
from PyInstaller.utils.hooks import collect_entry_point

ep_datas, ep_hiddenimprts = collect_entry_point('setuptools_scm.parse_scm')

...

a = Analysis(
    ...
    datas=other_datas + ep_datas,
    hiddenimports=other_hiddenimports + ep_hiddenimprts,
   ...
)

...
```

**Comment by bwoodsend** [comment]
[Sigh] And here's yet another package with a [silly, fragile overcomplicated way](https://github.com/scverse/anndata/blob/823bb0d60fa9db130cebc02423e632722d001514/src/anndata/__init__.py#L5-L15) of setting the `__version__` attribute.

You might also be able to use `--exclude-import=setuptools_scm` to force it to use `from ._version import __version__` instead.

**Comment by rokm** [comment]
> --exclude-import 

[`--exclude-module`](https://pyinstaller.org/en/stable/usage.html#cmdoption-exclude-module) or its alias, `--exclude`.
