### ISSUE TITLE
Issues with pyinstaller 6.10 vs. pytest vs. typeguard

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#8728]
## Description of the issue

`pyinstaller` fails, or includes an unwanted `typeguard` plugin, when freezing an app that uses `pytest`. Likely related to https://github.com/pyinstaller/pyinstaller/pull/8720, since `setuptools` seems be vendoring `typeguard`.

### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.10.0
* Version of Python: 3.12.4
* Platform: Windows
* How you installed Python: scoop
* Did you also try this on another platform? No
* Try the latest development version: done, same thing

### A minimal example program which shows the error

`bug.py`
```python
import pytest

pytest.main()
```

### Commands
```
# Working
pip install pyinstaller==6.9  pytest && pyinstaller bug.py --noconfirm --log-level=DEBUG && dist\bug\bug.exe

# Failing
pip install pyinstaller==6.10 pytest && pyinstaller bug.py --noconfirm --log-level=DEBUG && dist\bug\bug.exe

# Working somewhat, but having an unwanted plugin
pip install pyinstaller==6.10 pytest && pyinstaller bug.py --noconfirm --log-level=DEBUG --exclude-module=typeguard --hidden-import=unittest.mock && dist\bug\bug.exe
```

### Stacktrace / full error message

```
# Working
======================================================================================== test session starts ========================================================================================
platform win32 -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Code\Bug
collected 0 items                                                                                                                                                                                     

======================================================================================= no tests ran in 0.02s ======================================================================================= 


# Failing
Traceback (most recent call last):
  File "C:\ws\Bug\bug.py", line 6, in <module>
    pytest.main()
  File "_pytest\config\__init__.py", line 156, in main
  File "_pytest\config\__init__.py", line 341, in _prepareconfig
  File "pluggy\_hooks.py", line 513, in __call__
  File "pluggy\_manager.py", line 120, in _hookexec
  File "pluggy\_callers.py", line 139, in _multicall
  File "pluggy\_callers.py", line 122, in _multicall
  File "_pytest\helpconfig.py", line 105, in pytest_cmdline_parse
  File "pluggy\_callers.py", line 103, in _multicall
  File "_pytest\config\__init__.py", line 1140, in pytest_cmdline_parse
  File "_pytest\config\__init__.py", line 1490, in parse
  File "_pytest\config\__init__.py", line 1377, in _preparse
  File "pluggy\_manager.py", line 421, in load_setuptools_entrypoints
  File "importlib\metadata\__init__.py", line 205, in load
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'typeguard._pytest_plugin'
[PYI-20768:ERROR] Failed to execute script 'bug' due to unhandled exception!


# Working somewhat, but having an unwanted plugin
======================================================================================== test session starts ========================================================================================
platform win32 -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Code\Bug
plugins: typeguard-4.3.0
collected 0 items                                                                                                                                                                                     

======================================================================================= no tests ran in 0.01s ======================================================================================= 

```

**Comment by bersbersbers** [comment]
`--exclude-module=setuptools._vendor.typeguard` does not help, either.

**Comment by rokm** [comment]
Do you have (stand-alone) `typeguard` installed in your python environment?

**Comment by rokm** [comment]
A quick test with a clean virtual environment.

First, no stand-alone typeguard:

```
>c:\Users\Rok\AppData\Local\Programs\Python\Python312\python.exe -m venv venv
>venv\Scripts\activate
>python -m pip install -U pip wheel setuptools
>python -m pip install pyinstaller pytest
```

```
>python -m pip freeze
altgraph==0.17.4
colorama==0.4.6
iniconfig==2.0.0
packaging==24.1
pefile==2023.2.7
pluggy==1.5.0
pyinstaller==6.10.0
pyinstaller-hooks-contrib==2024.8
pytest==8.3.2
pywin32-ctypes==0.2.2
setuptools==72.1.0
wheel==0.44.0
```

Trying to run unfrozen:

```
>python bug.py
====================================================================== test session starts =======================================================================
platform win32 -- Python 3.12.1, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\Rok\Development\pyi-pytest
collected 0 items

===================================================================== no tests ran in 0.00s ======================================================================
```

Trying to freeze:

```
>pyinstaller --clean --noconfirm bug.py

>dist\bug\bug.exe
Traceback (most recent call last):
  File "bug.py", line 2, in <module>
    pytest.main()
  File "_pytest\config\__init__.py", line 156, in main
  File "_pytest\config\__init__.py", line 341, in _prepareconfig
  File "pluggy\_hooks.py", line 513, in __call__
  File "pluggy\_manager.py", line 120, in _hookexec
  File "pluggy\_callers.py", line 139, in _multicall
  File "pluggy\_callers.py", line 122, in _multicall
  File "_pytest\helpconfig.py", line 105, in pytest_cmdline_parse
  File "pluggy\_callers.py", line 103, in _multicall
  File "_pytest\config\__init__.py", line 1140, in pytest_cmdline_parse
  File "_pytest\config\__init__.py", line 1490, in parse
  File "_pytest\config\__init__.py", line 1377, in _preparse
  File "pluggy\_manager.py", line 421, in load_setuptools_entrypoints
  File "importlib\metadata\__init__.py", line 205, in load
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "typeguard\__init__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "typeguard\_checkers.py", line 34, in <module>
ModuleNotFoundError: No module named 'unittest.mock'
[PYI-8800:ERROR] Failed to execute script 'bug' due to unhandled exception!
```

The issue here is likely that I've added `unittest` to excluded imports in setuptools hook:
https://github.com/pyinstaller/pyinstaller/blob/88e0cb5697bde00a3c358df1f5353659a8d23354/PyInstaller/hooks/hook-setuptools.py#L31

Working around by adding `--hiddenimport unittest.mock`:

>pyinstaller --clean --noconfirm bug.py --hiddenimport unittest.mock

```
>dist\bug\bug.exe
====================================================================== test session starts =======================================================================
platform win32 -- Python 3.12.1, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\Rok\Development\pyi-pytest
plugins: typeguard-4.3.0
collected 0 items

===================================================================== no tests ran in 0.01s ======================================================================
```

It works, but the typeguard-4.3.0 plugin is there, coming from vendored setuptools. In frozen application, the run-time hooks probably end up triggering import of setuptools, and so its packages become available, along with vendored `typeguard` and its plugin.

I'll have to check if the import can be avoided...

-----------------------

If we now install stand-alone `typeguard`.

```
>pip install typeguard
```

```
>pip freeze
altgraph==0.17.4
colorama==0.4.6
iniconfig==2.0.0
packaging==24.1
pefile==2023.2.7
pluggy==1.5.0
pyinstaller==6.10.0
pyinstaller-hooks-contrib==2024.8
pytest==8.3.2
pywin32-ctypes==0.2.2
setuptools==72.1.0
typeguard==4.3.0
typing_extensions==4.12.2
wheel==0.44.0
```

```
>python bug.py
====================================================================== test session starts =======================================================================
platform win32 -- Python 3.12.1, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\Rok\Development\pyi-pytest
plugins: typeguard-4.3.0
collected 0 items

===================================================================== no tests ran in 0.02s ======================================================================
```

```
pyinstaller --clean --noconfirm bug.py 
```

```
>dist\bug\bug.exe
Traceback (most recent call last):
  File "bug.py", line 2, in <module>
    pytest.main()
  File "_pytest\config\__init__.py", line 156, in main
  File "_pytest\config\__init__.py", line 341, in _prepareconfig
  File "pluggy\_hooks.py", line 513, in __call__
  File "pluggy\_manager.py", line 120, in _hookexec
  File "pluggy\_callers.py", line 139, in _multicall
  File "pluggy\_callers.py", line 122, in _multicall
  File "_pytest\helpconfig.py", line 105, in pytest_cmdline_parse
  File "pluggy\_callers.py", line 103, in _multicall
  File "_pytest\config\__init__.py", line 1140, in pytest_cmdline_parse
  File "_pytest\config\__init__.py", line 1490, in parse
  File "_pytest\config\__init__.py", line 1377, in _preparse
  File "pluggy\_manager.py", line 421, in load_setuptools_entrypoints
  File "importlib\metadata\__init__.py", line 205, in load
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'typeguard._pytest_plugin'
[PYI-5476:ERROR] Failed to execute script 'bug' due to unhandled exception!
```

Which is the same error that you reported. This one probably happens because we end up collecting typeguard metadata, and so pytest entry point is exposed via it,
but we do not collect the corresponding `typeguard._pytest_plugin` module.

In this case, I'll have to look into why the metadata is collected in the first place (since it doesn't seem that we have a hook for typeguard that would do this).

Adding the hidden import takes care of the problem:

```
pyinstaller --clean --noconfirm bug.py --hiddenimport typeguard._pytest_plugin
```

```
>dist\bug\bug.exe
====================================================================== test session starts =======================================================================
platform win32 -- Python 3.12.1, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\Rok\Development\pyi-pytest
plugins: typeguard-4.3.0
collected 0 items

===================================================================== no tests ran in 0.00s ======================================================================
```

**Comment by rokm** [comment]
Hmm, actually, it seems that without stand-alone `typeguard` installed, we end up collecting a spurious copy of `typeguard` metadata in top-level application directory with 6.10.0, while we did not with 6.9.0...

**Comment by bersbersbers** [comment]
> Do you have (stand-alone) `typeguard` installed in your python environment?

Usually, yes. That may explain why I saw certain issues that I was not able to cleanly reproduce in the minimal example above.

But do note that I do not want to deploy `typeguard` (as the import order is a little different there - the entry point is in my package, so it is already loaded when I run `pytest` and thus `typeguard` plugin, and then it outputs warning. Without pyinstaller, `pytest` and `typeguard` are imported first, and then everything works fine. Anyway.) So I have it in my environment but it is explicitly excluded from `pyinstaller`, which worked fine up to (including) 6.9.

**Comment by rokm** [comment]
As a work-around, does it work as expected if you install `setuptools[core]` instead of `setuptools`, to avoid having setuptools-vendored packages altogether?

**Comment by bersbersbers** [comment]
> As a work-around, does it work as expected if you install `setuptools[core]` instead of `setuptools`

No, same thing.

> to avoid having setuptools-vendored packages altogether?

Note that

> Dependencies are still vendored for bootstrapping purposes

https://setuptools.pypa.io/en/stable/history.html#id16

**Comment by rokm** [comment]
Aha, I misunderstood what `[core]` extra was supposed to do. Thanks for the link!

If you take a failing build, and manually remove `typeguard-X.Y.Z` metadata directory from both top-level `_internal` directory (assuming it is there) and from `_internal/setuptools/_vendor`, then the plugin should not appear in entry-points, and the missing module(s) should also not be a problem. Is that the case?

**Comment by bersbersbers** [comment]
> If you take a failing build, and manually remove `typeguard-X.Y.Z` metadata directory from both top-level `_internal` directory (assuming it is there) and from `_internal/setuptools/_vendor`, then the plugin should not appear in entry-points, and the missing module(s) should also not be a problem. Is that the case?

This is perfectly correct, yes:

```
[PYI-1488:ERROR] Failed to execute script 'bug' due to unhandled exception!

(.venv) C:\Code\Bug>rmdir /s /q dist\bug\_internal\typeguard-4.3.0.dist-info 

(.venv) C:\Code\Bug>rmdir /s /q dist\bug\_internal\setuptools\_vendor\typeguard-4.3.0.dist-info

(.venv) C:\Code\Bug>dist\bug\bug.exe
======================================================================================== test session starts ========================================================================================
platform win32 -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Code\Bug
collected 0 items

======================================================================================= no tests ran in 0.01s =======================================================================================
```

**Comment by rokm** [comment]
Yeah, I guess we'll have to figure out where rogue top-level metadata is coming from (my current hypothesis is that this is triggered by automatic detection/collection code) and somehow block it. And also not collect all metadata and data from vendored setuptools packages like we do now, but only for those packages where we would also collect for top-level packages...

**Comment by rokm** [comment]
@bersbersbers Can you check if https://github.com/rokm/pyinstaller/tree/setuptools-71-improvements fixes the problem (especially without breaking anything else in your actual use case)?

**Comment by bersbersbers** [comment]
> if https://github.com/rokm/pyinstaller/tree/setuptools-71-improvements fixes the problem (especially without breaking anything else in your actual use case)?

Yes it does! Everything seems to work as before 6.10. Thanks a lot!

fyi, I am packaging a somewhat large number of packages, including matplotlib, numpy, PySide6, pyqtgraph, and pytest, and all of their dependencies, and the packaged pytest still runs fine.
