### ISSUE TITLE
ImportError: PyiFrozenImporter cannot handle module 'pymupdf'

### ISSUE THREAD

**Issue by dplcz** [pyinstaller/pyinstaller#8743]
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 187, in get_code
  File "PyInstaller\loader\pyimod01_archive.py", line 149, in extract
MemoryError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pdf_test.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 400, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 189, in get_code
ImportError: PyiFrozenImporter cannot handle module 'pymupdf'
[23612] Failed to execute script 'pdf_test' due to unhandled exception!

**Comment by bwoodsend** [comment]
The [basic example](https://github.com/pymupdf/pymupdf?tab=readme-ov-file#usage) works for me. Fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) if you want us to be able to do anything.

**Comment by rokm** [comment]
Considering the underlying error is `MemoryError` during PYZ extraction, I would say either this is a low-memory issue, or you have somehow ended up with (partially?) corrupted executable and its PKG/PYZ archive.
