### ISSUE TITLE
Control-C stack trace when  onefile executable being expanded

### ISSUE THREAD

**Issue by taers232c** [pyinstaller/pyinstaller#8775]
If I type control-C while a onefile executable is being expanded, can I disable/suppress the stack trace?

Thanks
```
$ gam version
^CTraceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_inspect.py", line 52, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_inspect.py", line 14, in _pyi_rthook
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "inspect.py", line 145, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "ast.py", line 28, in <module>
  File "re/__init__.py", line 124, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1528, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1502, in _get_spec
  File "<frozen zipimport>", line 111, in find_spec
  File "<frozen importlib._bootstrap>", line 675, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 822, in spec_from_file_location
  File "<frozen zipimport>", line 170, in get_filename
  File "<frozen zipimport>", line 700, in _get_module_code
  File "<frozen zipimport>", line 556, in _get_data
KeyboardInterrupt
[219781] Failed to execute script 'pyi_rth_inspect' due to unhandled exception!
```

**Comment by rokm** [comment]
> If I type control-C while a onefile executable is being expanded, can I disable/suppress the stack trace?

Not really, because you are interrupting PyInstaller's bootstrap scripts / runtime hooks.
