### ISSUE TITLE
Inquirer doesn't work in conda ebvironment

### ISSUE THREAD

**Issue by SmoothTurtle872** [pyinstaller/pyinstaller#8780]
## Description of the issue
whenever I create an executable in pyinstaller that uses inquirer, the executable generates without errors however when I run it erros out. This only happens with inquirer as far as I'm aware. 
The crash is as follows
```
Traceback (most recent call last):
  File "importlib\metadata\__init__.py", line 397, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\prompt.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\render\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\render\console\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\events.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "readchar\__init__.py", line 6, in <module>
  File "importlib\metadata\__init__.py", line 889, in version
  File "importlib\metadata\__init__.py", line 862, in distribution
  File "importlib\metadata\__init__.py", line 399, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for readchar
[PYI-4504:ERROR] Failed to execute script 'main' due to unhandled exception!
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.10.0```
* Version of Python: 3.12.4, 3.12.5 (as far as I'm aware only when using conda)
* Platform: Windows
* How you installed Python: conda
* Did you also try this on another platform? Does it work there? I have not tried this on another platform recently however I have an older project that I believe is from 3.12.4 and uses inquirer but was not installed with conda.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import inquirer
print(inquirer.list_choice(choices=["test","test2"]))
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "importlib\metadata\__init__.py", line 397, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\prompt.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\render\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\render\console\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "inquirer\events.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "readchar\__init__.py", line 6, in <module>
  File "importlib\metadata\__init__.py", line 889, in version
  File "importlib\metadata\__init__.py", line 862, in distribution
  File "importlib\metadata\__init__.py", line 399, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for readchar
[PYI-4504:ERROR] Failed to execute script 'main' due to unhandled exception!
```

**Comment by rokm** [comment]
>```
>   File "readchar\__init__.py", line 6, in <module>
>  File "importlib\metadata\__init__.py", line 889, in version
>  File "importlib\metadata\__init__.py", line 862, in distribution
>  File "importlib\metadata\__init__.py", line 399, in from_name
>importlib.metadata.PackageNotFoundError: No package metadata was found for readchar
>```

As implied by the error message, `readchar` requires its metadata (because [it is trying to query version](https://github.com/magmax/python-readchar/blob/3aa882e1037f2d4a7c4d26323512389ec79cb519/readchar/__init__.py#L6) from it). 

Adding [`--copy-metadata readchar`](https://pyinstaller.org/en/stable/usage.html#cmdoption-copy-metadata) to your PyInstaller command should take care of this particular problem.

**Comment by SmoothTurtle872** [comment]
Its fixed, thx
