### ISSUE TITLE
PyInstaller.isolated._parent.SubprocessDiedError: Child process died calling _collect_submodules() with args=('torch.distributed.optim', 'warn once') and kwargs={}. Its exit code was -11.

### ISSUE THREAD

**Issue by swleuet** [pyinstaller/pyinstaller#8795]
When I use pyinstaller to pack a python script containing pytorch, this error happens:
```
/home/python311pkg/lib/python3.11/site-packages/torch/distributed/pipeline/__init__.py:2: UserWarning: torch.distributed.pipeline is deprecated. For up-to-date pipeline parallel implementation, please refer to the PiPPy library under the PyTorch organization (Pipeline Parallelism for PyTorch): https://github.com/pytorch/PiPPy
  warnings.warn(
Traceback (most recent call last):
  File "/home/python311pkg/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/__main__.py", line 231, in _console_script_run
    run()
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1227, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1167, in build
    exec(code, spec_namespace)
  File "/home/license_plate/license_plate_single_device_36.spec", line 4, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 558, in __init__
    self.__postinit__()
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 698, in assemble
    program_scripts.append(self.graph.add_script(script))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/analysis.py", line 268, in add_script
    self._top_script_node = super().add_script(pathname)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1177, in add_script
    self._process_imports(n)
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2608, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2065, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1249, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1428, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/analysis.py", line 502, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1809, in _safe_import_module
    self._process_imports(n)
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2608, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/analysis.py", line 437, in _safe_import_hook
    ret_modules = super()._safe_import_hook(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2065, in _safe_import_hook
    target_modules = self.import_hook(
                     ^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1249, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1428, in _find_head_package
    target_package = self._safe_import_module(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/analysis.py", line 502, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1809, in _safe_import_module
    self._process_imports(n)
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2608, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/analysis.py", line 368, in _safe_import_hook
    excluded_imports = self._find_all_excluded_imports(source_module.identifier)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/analysis.py", line 356, in _find_all_excluded_imports
    excluded_imports.update(module_hook.excludedimports)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/imphook.py", line 316, in __getattr__
    self._load_hook_module()
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/depend/imphook.py", line 383, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/compat.py", line 610, in importlib_load_source
    mod_loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/python311pkg/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/stdhooks/hook-torch.py", line 43, in <module>
    hiddenimports = collect_submodules("torch")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/utils/hooks/__init__.py", line 636, in collect_submodules
    modules, subpackages, on_error = isolated_python.call(_collect_submodules, name, on_error)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python311pkg/lib/python3.11/site-packages/PyInstaller/isolated/_parent.py", line 322, in call
    raise SubprocessDiedError(
PyInstaller.isolated._parent.SubprocessDiedError: Child process died calling _collect_submodules() with args=('torch.distributed.optim', 'warn once') and kwargs={}. Its exit code was -11.

```
My torch version is '2.3.1+cpu' and my pyinstaller is '6.10.0'
The python script can run appropriately when I use python script.py directly in the virtual environment where the pack happened.

**Comment by rokm** [comment]
What happens if you try to import `torch.distributed.optim` in python session? Does it also crash?

**Comment by swleuet** [comment]
> 

Yes, it will cause 'Segmentation fault (core dumped)' when I use python script.py directly. In this version of pytorch, 'torch.distributed.optim' has been replaced by 'torch.optim'.

**Comment by swleuet** [comment]
> What happens if you try to import `torch.distributed.optim` in python session? Does it also crash?

Yes, it will cause 'Segmentation fault (core dumped)' when I use python script.py directly. In this version of pytorch, 'torch.distributed.optim' has been replaced by 'torch.optim'.

**Comment by rokm** [comment]
> > What happens if you try to import `torch.distributed.optim` in python session? Does it also crash?
> 
> Yes, it will cause 'Segmentation fault (core dumped)' when I use python script.py directly. 

If an attempt to import a module causes a segfault, then that's a problem with either `torch` or with your environment. FWIW, I cannot reproduce that segfault on my main linux system with (distribution-packaged) python 3.11.10 and torch 2.3.1+cpu. 

What distribution are you using, how did you install python, and what packages do you have installed in that environment (e.g., what is output of `pip freeze`)?

> In this version of pytorch, 'torch.distributed.optim' has been replaced by 'torch.optim'.

I don't think so - [`torch.distributed.optim`](https://github.com/pytorch/pytorch/tree/v2.3.1/torch/distributed/optim) and [`torch.optim`](https://github.com/pytorch/pytorch/tree/v2.3.1/torch/optim) seem to be two distinct modules.

**Comment by swleuet** [comment]
> > > What happens if you try to import `torch.distributed.optim` in python session? Does it also crash?
> > 
> > 
> > Yes, it will cause 'Segmentation fault (core dumped)' when I use python script.py directly.
> 
> If an attempt to import a module causes a segfault, then that's a problem with either `torch` or with your environment. FWIW, I cannot reproduce that segfault on my main linux system with (distribution-packaged) python 3.11.10 and torch 2.3.1+cpu.
> 
> What distribution are you using, how did you install python, and what packages do you have installed in that environment (e.g., what is output of `pip freeze`)?
> 
> > In this version of pytorch, 'torch.distributed.optim' has been replaced by 'torch.optim'.
> 
> I don't think so - [`torch.distributed.optim`](https://github.com/pytorch/pytorch/tree/v2.3.1/torch/distributed/optim) and [`torch.optim`](https://github.com/pytorch/pytorch/tree/v2.3.1/torch/optim) seem to be two distinct modules.

The virtual environment is Python 3.11.0rc1. The output of `pip freeze` is the following:
absl-py==2.1.0
altgraph==0.17.4
attrs==24.2.0
blinker==1.8.2
certifi==2024.8.30
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.3.0
cycler==0.12.1
dill==0.3.8
expecttest==0.2.1
filelock==3.13.1
Flask==3.0.3
Flask-JWT-Extended==4.6.0
fonttools==4.53.1
fsspec==2024.2.0
grpcio==1.66.1
hypothesis==6.112.0
idna==3.8
itsdangerous==2.2.0
Jinja2==3.1.3
kiwisolver==1.4.7
Markdown==3.7
MarkupSafe==2.1.5
matplotlib==3.9.2
ml-dtypes==0.4.0
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.3
onnx==1.16.2
onnxscript==0.1.0.dev20240906
opencv-python==4.8.0.76
packaging==24.1
pandas==2.2.2
pillow==10.2.0
protobuf==5.28.0
psutil==6.0.0
py-cpuinfo==9.0.0
pyinstaller==5.7.0
pyinstaller-hooks-contrib==2024.8
PyJWT==2.9.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.2
requests==2.32.3
scipy==1.14.1
seaborn==0.13.2
six==1.16.0
sortedcontainers==2.4.0
sympy==1.12
tensorboard==2.17.1
tensorboard-data-server==0.7.2
torch==2.3.1+cpu
torchaudio==2.3.1+cpu
torchvision==0.18.1+cpu
tqdm==4.66.5
typing_extensions==4.9.0
tzdata==2024.1
ultralytics==8.2.87
ultralytics-thop==2.0.6
urllib3==2.2.2
Werkzeug==3.0.4

Actually the problem has been solved in my virtual environment by using pyinstaller '5.7.0'. Thanks a lot for your help. But I still don't know the reason.
