### ISSUE TITLE
onefile breaks uvicorn

### ISSUE THREAD

**Issue by sevenrats** [pyinstaller/pyinstaller#8817]
## Description of the issue

using the --onefile option of pyinstaller breaks uvicorn apps. pressing ctrl-c no longer works properly.

### Context information (for bug reports)

* Output of `pyinstaller --version`: every version back to at least the last 5.x version is confirmed to have the issue
* Version of Python: 3.11
* Platform: debian bookworm
* How you installed Python: apt
* Did you also try this on another platform? Does it work there? No, dunno

### A minimal example program which shows the error

```
#proof.py
from fastapi import FastAPI
import uvicorn

# Create a FastAPI app instance
app = FastAPI()

# Define a basic route
@app.get("/")
def read_root():
    return {"message": "Hello, World!"}

@app.get("/items/{item_id}")
def read_item(item_id: int, q: str = None):
    return {"item_id": item_id, "query": q}

# Main entry point to run the server programmatically with uvicorn
if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)
```

```
pyinstaller --onefile proof.py
./dist/proof

# NOW PRESS CTRL-C
```

This example WILL WORK CORRECTLY if its run normally or packed without --onefile

### Stacktrace / full error message

```
INFO:     Started server process [792781]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
^CINFO:     Shutting down
INFO:     Finished server process [792781]
ERROR:    Traceback (most recent call last):
  File "asyncio/runners.py", line 190, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 640, in run_until_complete
  File "asyncio/base_events.py", line 607, in run_forever
  File "asyncio/base_events.py", line 1922, in _run_once
  File "asyncio/events.py", line 80, in _run
  File "uvicorn/server.py", line 68, in serve
  File "contextlib.py", line 144, in __exit__
  File "uvicorn/server.py", line 328, in capture_signals
  File "asyncio/runners.py", line 157, in _on_sigint
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starlette/routing.py", line 700, in lifespan
  File "uvicorn/lifespan/on.py", line 137, in receive
  File "asyncio/queues.py", line 158, in get
asyncio.exceptions.CancelledError

```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
In onefile mode you have two processes: the parent that unpacks the archive, runs the child, and cleans up after child is done; and the child process that runs your code.

If you run the program in terminal and press Ctrl+C, *both* processes are signaled via the process group they are in. In addition, the parent process by default forwards received signals to the child. So child ends up being signaled twice in this case, resulting in the error that you see.

So if you want to use Ctrl+C with onefile applications, you need to use [--bootloader-ignore-signals](https://pyinstaller.org/en/stable/usage.html#cmdoption-bootloader-ignore-signals) to prevent parent from forwarding the signal to the child. Note that this applies to all signals, though, so you lose the ability to signal the child by signaling the parent (whether this is a problem or not depends on the situation; same goes for double-signaling, which is the flip side of the same issue).
