### ISSUE TITLE
DLL load failed while importing QtCore:

### ISSUE THREAD

**Issue by Scienion-ToHa** [pyinstaller/pyinstaller#8818]
Hello and thank you already in advance for your time and help.

I am fighting very hard with qt6 in the last couple of days.

I always get error by starting my gui app (created by qt6-tools desiger) and i can't solve that on my own.

I am very thankful for every kind of help on that matter.

I am using pyqt6 6.7.3 
qmake --version
QMake version 3.1
Using Qt version 5.15.2 in C:/ProgramData/anaconda3/Library/lib

my main.py

import sys
from PyQt6 import QtWidgets, uic

from ui_interface import Ui_MainWindow

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)

app = QtWidgets.QApplication(sys.argv)

window = MainWindow()
window.show()
app.exec()

**Comment by rokm** [comment]
Is this really PyInstaller related, or is it a generic PyQt6 + (Anaconda) python issue?

> I am using pyqt6 6.7.3
> qmake --version
> QMake version 3.1
> Using Qt version 5.15.2 in C:/ProgramData/anaconda3/Library/lib

I doubt that PyQt6 is using Qt5. Also, I'm quite sure that PyQt6 is currently at 6.7.1 (with 6.7.2 being development version). The Qt6 itself, though, did recently have 6.7.3 release (and consequently PyQt6-Qt6 PyPI wheel is at 6.7.3).

How did you install PyQt6? And what version of Anaconda python is that? If you are using PyPI wheels for PyQt6 and Anaconda python 3.8 or 3.9, then you might have a problem with defunct `os.add_dll_directory` that is used to set DLL search path...

**Comment by Scienion-ToHa** [comment]
Hello. Thank you very much for your response.

I tried a lot in the past few days.

I would prefer to load the ui file directly via uic but in the end I need a working way and dont care so much about it.

I am using Windows 10

1. Try




I installed everything directly on my pc
pyqt6 6.0.2
 pyqt6-tools 6.0.2.3.2
Python 3.6.6
a) Using the ui file

my main
```
import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6 import uic
from standard import Standard


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        uic.loadUi("mainwindow.ui", self)


app = QtWidgets.QApplication(sys.argv)
window = MainWindow()
window.show()
app.exec() 
```


error:
```
python mainUI.py
Traceback (most recent call last):
  File "C:\Users\t.hagara\Downloads\New GUI\mainUI.py", line 13, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\t.hagara\Downloads\New GUI\mainUI.py", line 9, in __init__
    uic.loadUi("interface.ui", self)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\load_ui.py", line 86, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\Loader\loader.py", line 62, in loadUi
    return self.parse(filename)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 1014, in parse
    self._handle_widget(ui_file.widget)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 842, in _handle_widget
    self.traverseWidgetTree(el)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 271, in createWidget
    self.stack.push(self._setupObject(widget_class, parent, elem))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 233, in _setupObject
    obj = self.factory.createQtObject(class_name, object_name,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\objcreator.py", line 101, in createQtObject
    ctor = self.findQObjectType(ctor_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\objcreator.py", line 127, in findQObjectType
    w = module.search(classname)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\Loader\qobjectcreator.py", line 113, in search
    module = __import__(mname, {}, {}, (cls,))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'standard'
```

b) Transform file to python code

my main

import sys
from PyQt6 import QtWidgets, uic

from ui_interface import Ui_MainWindow


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)


app = QtWidgets.QApplication(sys.argv)

window = MainWindow()
window.show()
app.exec()
 

error:
```
python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from ui_interface import Ui_MainWindow
  File "C:\Users\t.hagara\Downloads\New GUI\ui_interface.py", line 11, in <module>
    from PySide6.QtCore import *
ImportError: DLL load failed: The specified procedure could not be found.
```

2. I installed Anaconda and tried the same

Python 3.12.4
PyQt6 6.7.1
conda 24.9.1
Pyside6 6.7.3

When I try to install PyQt6-tools i get the following output:

```
install pyqt6-tools
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.4.2.3.3-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from pyqt6-tools) (8.1.7)
Collecting pyqt6==6.4.2 (from pyqt6-tools)
  Using cached PyQt6-6.4.2-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
INFO: pip is looking at multiple versions of pyqt6-tools to determine which version is compatible with other requirements. This could take a while.
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.3.1.3.3-py3-none-any.whl.metadata (8.3 kB)
Collecting pyqt6==6.3.1 (from pyqt6-tools)
  Using cached PyQt6-6.3.1-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl.metadata (8.3 kB)
Collecting pyqt6==6.1.0 (from pyqt6-tools)
  Using cached PyQt6-6.1.0.tar.gz (946 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\adm.t.hagara\AppData\Local\Temp\pip-build-env-0bvm00b4\overlay\Lib\site-packages\sipbuild\api.py", line 28, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\adm.t.hagara\AppData\Local\Temp\pip-build-env-0bvm00b4\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 74, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\adm.t.hagara\AppData\Local\Temp\pip-build-env-0bvm00b4\overlay\Lib\site-packages\sipbuild\project.py", line 624, in setup
          self.update(tool)
        File "C:\Users\adm.t.hagara\AppData\Local\Temp\pip-install-ugd8g_gx\pyqt6_cf8319f538194df2bc0f59f8f050a8ea\project.py", line 157, in update
          raise UserException(
      sipbuild.exceptions.UserException
      Traceback (most recent call last):
        File "C:\ProgramData\anaconda3\Lib\shutil.py", line 637, in _rmtree_unsafe
          os.rmdir(path)
      PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ADMT~1.HAG\\AppData\\Local\\Temp\\tmpbhzuq0cx'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\ProgramData\anaconda3\Lib\tempfile.py", line 905, in onexc
          _os.unlink(path)
      PermissionError: [WinError 5] Access is denied: 'C:\\Users\\ADMT~1.HAG\\AppData\\Local\\Temp\\tmpbhzuq0cx'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\ProgramData\anaconda3\Lib\weakref.py", line 666, in _exitfunc
          f()
        File "C:\ProgramData\anaconda3\Lib\weakref.py", line 590, in __call__
          return info.func(*info.args, **(info.kwargs or {}))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\tempfile.py", line 935, in _cleanup
          cls._rmtree(name, ignore_errors=ignore_errors)
        File "C:\ProgramData\anaconda3\Lib\tempfile.py", line 930, in _rmtree
          _shutil.rmtree(name, onexc=onexc)
        File "C:\ProgramData\anaconda3\Lib\shutil.py", line 781, in rmtree
          return _rmtree_unsafe(path, onexc)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\shutil.py", line 639, in _rmtree_unsafe
          onexc(os.rmdir, path, err)
        File "C:\ProgramData\anaconda3\Lib\tempfile.py", line 920, in onexc
          cls._rmtree(path, ignore_errors=ignore_errors,
        File "C:\ProgramData\anaconda3\Lib\tempfile.py", line 930, in _rmtree
          _shutil.rmtree(name, onexc=onexc)
        File "C:\ProgramData\anaconda3\Lib\shutil.py", line 781, in rmtree
          return _rmtree_unsafe(path, onexc)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\shutil.py", line 639, in _rmtree_unsafe
          onexc(os.rmdir, path, err)
        File "C:\ProgramData\anaconda3\Lib\shutil.py", line 637, in _rmtree_unsafe
          os.rmdir(path)
      PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ADMT~1.HAG\\AppData\\Local\\Temp\\tmpbhzuq0cx'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

same main files

1, UI File

```
python mainUI.py
Traceback (most recent call last):
  File "C:\Users\t.hagara\Downloads\New GUI\mainUI.py", line 13, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\t.hagara\Downloads\New GUI\mainUI.py", line 9, in __init__
    uic.loadUi("interface.ui", self)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\load_ui.py", line 86, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\Loader\loader.py", line 62, in loadUi
    return self.parse(filename)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 1014, in parse
    self._handle_widget(ui_file.widget)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 842, in _handle_widget
    self.traverseWidgetTree(el)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 280, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 271, in createWidget
    self.stack.push(self._setupObject(widget_class, parent, elem))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\uiparser.py", line 233, in _setupObject
    obj = self.factory.createQtObject(class_name, object_name,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\objcreator.py", line 101, in createQtObject
    ctor = self.findQObjectType(ctor_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\objcreator.py", line 127, in findQObjectType
    w = module.search(classname)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PyQt6\uic\Loader\qobjectcreator.py", line 113, in search
    module = __import__(mname, {}, {}, (cls,))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'standard'
```

2. python code

```
python main.py
Traceback (most recent call last):
  File "C:\Users\t.hagara\Downloads\New GUI\main.py", line 4, in <module>
    from ui_interface import Ui_MainWindow
  File "C:\Users\t.hagara\Downloads\New GUI\ui_interface.py", line 15, in <module>
    from standard import Standard
ModuleNotFoundError: No module named 'standard'
```
when i dlete the line from from standard import Standard from the ui python code i get the following output:

```
python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from ui_interface import Ui_MainWindow
  File "C:\Users\t.hagara\Downloads\New GUI\ui_interface.py", line 11, in <module>
    from PySide6.QtCore import *
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by rokm** [comment]
In your `main.py`, you are importing from `PyQt6`; but in ui_interface.py (also imported from `main.py`) you are importing from `PySide6`. You can't really mix the two of them.

Either way, this is issue tracker for PyInstaller, not a general python support forum.
