### ISSUE TITLE
tkinter not detected on Python 3.13

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#8820]
```
(.venv) C:\Git\project>python312 -c "from PyInstaller.utils.hooks.tcl_tk import tcltk_info; print(tcltk_info.available)"
274 INFO: TclTkInfo: initializing cached Tcl/Tk info...
True

(.venv) C:\Git\project>python -c "from PyInstaller.utils.hooks.tcl_tk import tcltk_info; print(tcltk_info.available)"   
322 INFO: TclTkInfo: initializing cached Tcl/Tk info...
False
```

PyInstaller 6.10 on Windows 11, installing Python via scoop

**Comment by bersbersbers** [comment]
Looks like this may be an issue with virtual environments similar to https://stackoverflow.com/questions/29320039/python-tkinter-throwing-tcl-error

```
python -c "from tkinter import Tcl; Tcl()"        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from tkinter import Tcl; Tcl()
                             ~~~^^
  File "C:\Scoop\apps\python\current\Lib\tkinter\__init__.py", line 2572, in Tcl
    return Tk(screenName, baseName, className, useTk)
  File "C:\Scoop\apps\python\current\Lib\tkinter\__init__.py", line 2459, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Scoop/apps/python/current/lib/tcl8.6 C:/Scoop/apps/python/lib/tcl8.6 C:/Scoop/apps/lib/tcl8.6 C:/Scoop/apps/python/library C:/Scoop/apps/library C:/Scoop/apps/tcl8.6.14/library C:/Scoop/tcl8.6.14/library

This probably means that Tcl wasn't installed properly.
```

**Comment by bersbersbers** [comment]
Looks like this is not even a Scoop issue, but a general Python 3.13 one:

https://discuss.python.org/t/3-13-0-tkinter-versus-venv-in-windows-10/67151

**Comment by bersbersbers** [comment]
Duplicate of https://github.com/python/cpython/issues/125235
