### ISSUE TITLE
OSError 22 : Invalid argument issue

### ISSUE THREAD

**Issue by Neel-Rystad** [pyinstaller/pyinstaller#8836]
I am trying to build an executable for my flask app and I keep running into the following error:

```Traceback (most recent call last):
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\building\api.py", line 1033, in _retry_operation
    return func(*args)
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\utils\win32\winutils.py", line 77, in set_exe_build_timestamp
    with open(exe_path, 'wb') as fp:
OSError: [Errno 22] Invalid argument: 'C:\\My_Repos\\recommender\\dist\\app.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\neelabhs\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\neelabhs\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\My_Repos\recommender\env\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\__main__.py", line 231, in _console_script_run
    run()
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\building\build_main.py", line 1227, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\building\build_main.py", line 1167, in build
    exec(code, spec_namespace)
  File "app.spec", line 24, in <module>
    exe = EXE(
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\building\api.py", line 658, in __init__
    self.__postinit__()
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\building\api.py", line 855, in assemble
    self._retry_operation(winutils.set_exe_build_timestamp, build_name, build_timestamp)
  File "C:\My_Repos\recommender\env\lib\site-packages\PyInstaller\building\api.py", line 1052, in _retry_operation
    raise RuntimeError(f"Execution of {func_name!r} failed - no more attempts left!") from e
RuntimeError: Execution of 'set_exe_build_timestamp' failed - no more attempts left!
```

The app.exe does exist in the dist folder of the project directory. 
Here is my spec file: -
```# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=['C:\\My_Repos\\recommender'],
    binaries=[],
    datas=[
        ('C:\\My_Repos\\recommender\\templates', 'templates'), 
        ('C:\\My_Repos\\recommender\\static', 'static'),       
        ('C:\\My_Repos\\recommender\\.env', '.env'),            
        ('C:\\My_Repos\\recommender\\embeddings', 'embeddings')
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

I am using the following command to build the executable: -
`>>>pyinstaller app.spec`

**Comment by rokm** [comment]
This usually means that your anti-virus program is blocking access to the executable during its assembly process. Can you check if this is the case (e.g., by temporarily disabling it)?
