### ISSUE TITLE
universal2 builds IncompatibleBinaryArchError

### ISSUE THREAD

**Issue by startergo** [pyinstaller/pyinstaller#8843]
## Description of the issue
IncompatibleBinaryArchError
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11.0```
* Version of Python: ``` 3.12.3```
* Platform: ``` OS X```
* How you installed Python: ```pyenv```
* Did you also try this on another platform? Does it work there?
No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
Traceback (most recent call last):
  File "/Users/mbp151/OpenCore-Legacy-Patcher/./Build-Project.command", line 167, in <module>
    main()
  File "/Users/mbp151/OpenCore-Legacy-Patcher/./Build-Project.command", line 104, in main
    ).generate()
      ^^^^^^^^^^
  File "/Users/mbp151/OpenCore-Legacy-Patcher/ci_tooling/build_modules/application.py", line 171, in generate
    self._generate_application()
  File "/Users/mbp151/OpenCore-Legacy-Patcher/ci_tooling/build_modules/application.py", line 46, in _generate_application
    subprocess_wrapper.run_and_verify(_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/mbp151/OpenCore-Legacy-Patcher/opencore_legacy_patcher/support/subprocess_wrapper.py", line 75, in run_and_verify
    verify(run(*args, **kwargs))
  File "/Users/mbp151/OpenCore-Legacy-Patcher/opencore_legacy_patcher/support/subprocess_wrapper.py", line 66, in verify
    raise Exception(f"Process failed with exit code {process_result.returncode}")
Exception: Process failed with exit code 1

“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
Generating OpenCore-Patcher.app
ERROR:root:Subprocess failed.
ERROR:root:    Command: ['/Users/mbp151/.pyenv/versions/3.12.3/bin/python3', '-m', 'PyInstaller', './OpenCore-Patcher-GUI.spec', '--noconfirm']
ERROR:root:    Return Code: 1
ERROR:root:    Standard Output:
ERROR:root:        None
ERROR:root:    Standard Error:
ERROR:root:        325 INFO: PyInstaller: 6.11.0, contrib hooks: 2024.9
ERROR:root:        326 INFO: Python: 3.12.3
ERROR:root:        352 INFO: Platform: macOS-15.0.1-x86_64-i386-64bit
ERROR:root:        352 INFO: Python environment: /Users/mbp151/.pyenv/versions/3.12.3
ERROR:root:        695 INFO: Module search paths (PYTHONPATH):
ERROR:root:        ['/Users/mbp151/OpenCore-Legacy-Patcher',
ERROR:root:         '/Users/mbp151/.pyenv/versions/3.12.3/lib/python312.zip',
ERROR:root:         '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12',
ERROR:root:         '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/lib-dynload',
ERROR:root:         '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages',
ERROR:root:         '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/setuptools/_vendor',
ERROR:root:         '/Users/mbp151/OpenCore-Legacy-Patcher',
ERROR:root:         '/Users/mbp151/OpenCore-Legacy-Patcher']
ERROR:root:        969 INFO: Appending 'datas' from .spec
ERROR:root:        970 INFO: checking Analysis
ERROR:root:        982 INFO: Building because hookspath changed
ERROR:root:        982 INFO: Running Analysis Analysis-00.toc
ERROR:root:        982 INFO: Target bytecode optimization level: 0
ERROR:root:        982 INFO: Initializing module dependency graph...
ERROR:root:        983 INFO: Initializing module graph hook caches...
ERROR:root:        1030 INFO: Analyzing base_library.zip ...
ERROR:root:        2123 INFO: Processing standard module hook 'hook-encodings.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        3762 INFO: Processing standard module hook 'hook-pickle.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        5066 INFO: Processing standard module hook 'hook-heapq.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        5555 INFO: Caching module dependency graph...
ERROR:root:        5645 INFO: Looking for Python shared library...
ERROR:root:        5649 INFO: Using Python shared library: /Users/mbp151/.pyenv/versions/3.12.3/lib/libpython3.12.dylib
ERROR:root:        5650 INFO: Analyzing /Users/mbp151/OpenCore-Legacy-Patcher/OpenCore-Patcher-GUI.command
ERROR:root:        5680 INFO: Processing pre-safe-import-module hook 'hook-packaging.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        5683 INFO: SetuptoolsInfo: initializing cached setuptools info...
ERROR:root:        9830 INFO: Processing standard module hook 'hook-packaging.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        9942 INFO: Processing standard module hook 'hook-xml.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        10278 INFO: Processing standard module hook 'hook-xml.etree.cElementTree.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        10874 INFO: Processing standard module hook 'hook-platform.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        12226 INFO: Processing pre-safe-import-module hook 'hook-typing_extensions.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        13137 INFO: Processing standard module hook 'hook-charset_normalizer.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/_pyinstaller_hooks_contrib/stdhooks'
ERROR:root:        13281 INFO: Processing standard module hook 'hook-certifi.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/_pyinstaller_hooks_contrib/stdhooks'
ERROR:root:        13816 INFO: Processing standard module hook 'hook-difflib.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        14132 INFO: Processing standard module hook 'hook-sysconfig.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        14633 INFO: Processing standard module hook 'hook-multiprocessing.util.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        15921 INFO: Processing module hooks (post-graph stage)...
ERROR:root:        16069 INFO: Processing standard module hook 'hook-pkg_resources.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        16455 INFO: Processing pre-safe-import-module hook 'hook-jaraco.text.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        16455 INFO: Setuptools: 'jaraco.text' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.jaraco.text'!
ERROR:root:        16462 INFO: Processing standard module hook 'hook-setuptools.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        16475 INFO: Processing pre-safe-import-module hook 'hook-distutils.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        16502 INFO: Processing pre-safe-import-module hook 'hook-jaraco.functools.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        16502 INFO: Setuptools: 'jaraco.functools' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.jaraco.functools'!
ERROR:root:        16513 INFO: Processing pre-safe-import-module hook 'hook-more_itertools.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        16514 INFO: Setuptools: 'more_itertools' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.more_itertools'!
ERROR:root:        16746 INFO: Processing pre-safe-import-module hook 'hook-importlib_metadata.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        16747 INFO: Setuptools: 'importlib_metadata' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.importlib_metadata'!
ERROR:root:        16774 INFO: Processing standard module hook 'hook-setuptools._vendor.importlib_metadata.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        16776 INFO: Processing pre-safe-import-module hook 'hook-zipp.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        16777 INFO: Setuptools: 'zipp' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.zipp'!
ERROR:root:        16813 INFO: Processing pre-safe-import-module hook 'hook-importlib_resources.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        16813 INFO: Setuptools: 'importlib_resources' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.importlib_resources'!
ERROR:root:        17094 INFO: Processing pre-safe-import-module hook 'hook-tomli.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        17094 INFO: Setuptools: 'tomli' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.tomli'!
ERROR:root:        17766 INFO: Processing pre-safe-import-module hook 'hook-wheel.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        17984 INFO: Processing standard module hook 'hook-setuptools._vendor.jaraco.text.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks'
ERROR:root:        17986 INFO: Processing pre-safe-import-module hook 'hook-jaraco.context.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        17987 INFO: Setuptools: 'jaraco.context' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.jaraco.context'!
ERROR:root:        17997 INFO: Processing pre-safe-import-module hook 'hook-backports.tarfile.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        17998 INFO: Setuptools: 'backports.tarfile' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.backports.tarfile'!
ERROR:root:        18104 INFO: Processing standard module hook 'hook-backports.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/_pyinstaller_hooks_contrib/stdhooks'
ERROR:root:        18107 INFO: Processing pre-safe-import-module hook 'hook-platformdirs.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module'
ERROR:root:        18108 INFO: Setuptools: 'platformdirs' appears to be a setuptools-vendored copy - creating alias to 'setuptools._vendor.platformdirs'!
ERROR:root:        18466 INFO: Performing binary vs. data reclassification (14 entries)
ERROR:root:        18476 INFO: Looking for ctypes DLLs
ERROR:root:        18486 WARNING: Ignoring /usr/lib/libc.dylib imported from /Users/mbp151/OpenCore-Legacy-Patcher/opencore_legacy_patcher/volume/properties.py - only basenames are supported with ctypes imports!
ERROR:root:        18513 INFO: Analyzing run-time hooks ...
ERROR:root:        18518 INFO: Including run-time hook 'pyi_rth_inspect.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/rthooks'
ERROR:root:        18521 INFO: Including run-time hook 'pyi_rth_pkgres.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/rthooks'
ERROR:root:        18526 INFO: Including run-time hook 'pyi_rth_setuptools.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/rthooks'
ERROR:root:        18528 INFO: Including run-time hook 'pyi_rth_multiprocessing.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/rthooks'
ERROR:root:        18530 INFO: Including run-time hook 'pyi_rth_pkgutil.py' from '/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/hooks/rthooks'
ERROR:root:        18546 INFO: Looking for dynamic libraries
ERROR:root:        18879 INFO: Warnings written to /Users/mbp151/OpenCore-Legacy-Patcher/build/OpenCore-Patcher-GUI/warn-OpenCore-Patcher-GUI.txt
ERROR:root:        18924 INFO: Graph cross-reference written to /Users/mbp151/OpenCore-Legacy-Patcher/build/OpenCore-Patcher-GUI/xref-OpenCore-Patcher-GUI.html
ERROR:root:        19077 INFO: checking PYZ
ERROR:root:        19084 INFO: Building because toc changed
ERROR:root:        19084 INFO: Building PYZ (ZlibArchive) /Users/mbp151/OpenCore-Legacy-Patcher/build/OpenCore-Patcher-GUI/PYZ-00.pyz
ERROR:root:        19801 INFO: Building PYZ (ZlibArchive) /Users/mbp151/OpenCore-Legacy-Patcher/build/OpenCore-Patcher-GUI/PYZ-00.pyz completed successfully.
ERROR:root:        19815 INFO: EXE target arch: universal2
ERROR:root:        19815 INFO: Code signing identity: None
ERROR:root:        19817 INFO: checking PKG
ERROR:root:        19818 INFO: Building because toc changed
ERROR:root:        19818 INFO: Building PKG (CArchive) OpenCore-Patcher.pkg
ERROR:root:        19835 INFO: Building PKG (CArchive) OpenCore-Patcher.pkg completed successfully.
ERROR:root:        19836 INFO: Bootloader /Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
ERROR:root:        19836 INFO: checking EXE
ERROR:root:        19838 INFO: Building because toc changed
ERROR:root:        19838 INFO: Building EXE from EXE-00.toc
ERROR:root:        19839 INFO: Copying bootloader EXE to /Users/mbp151/OpenCore-Legacy-Patcher/build/OpenCore-Patcher-GUI/OpenCore-Patcher
ERROR:root:        19840 INFO: Converting EXE to target arch (universal2)
ERROR:root:        19843 INFO: Removing signature(s) from EXE
ERROR:root:        19888 INFO: Appending PKG archive to EXE
ERROR:root:        19895 INFO: Fixing EXE headers for code signing
ERROR:root:        19908 INFO: Re-signing the EXE
ERROR:root:        19980 INFO: Building EXE from EXE-00.toc completed successfully.
ERROR:root:        19984 INFO: checking COLLECT
ERROR:root:        19984 INFO: Building COLLECT because COLLECT-00.toc is non existent
ERROR:root:        19984 INFO: Removing dir /Users/mbp151/OpenCore-Legacy-Patcher/dist/OpenCore-Patcher
ERROR:root:        19985 INFO: Building COLLECT COLLECT-00.toc
ERROR:root:        Traceback (most recent call last):
ERROR:root:          File "<frozen runpy>", line 198, in _run_module_as_main
ERROR:root:          File "<frozen runpy>", line 88, in _run_code
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/__main__.py", line 321, in <module>
ERROR:root:            run()
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/__main__.py", line 215, in run
ERROR:root:            run_build(pyi_config, spec_file, **vars(args))
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/__main__.py", line 70, in run_build
ERROR:root:            PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 1252, in main
ERROR:root:            build(specfile, distpath, workpath, clean_build)
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 1192, in build
ERROR:root:            exec(code, spec_namespace)
ERROR:root:          File "./OpenCore-Patcher-GUI.spec", line 62, in <module>
ERROR:root:            coll = COLLECT(exe,
ERROR:root:                   ^^^^^^^^^^^^
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/building/api.py", line 1122, in __init__
ERROR:root:            self.__postinit__()
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
ERROR:root:            self.assemble()
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/building/api.py", line 1168, in assemble
ERROR:root:            src_name = process_collected_binary(
ERROR:root:                       ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/building/utils.py", line 309, in process_collected_binary
ERROR:root:            osxutils.binary_to_target_arch(cached_name, target_arch, display_name=src_name)
ERROR:root:          File "/Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/site-packages/PyInstaller/utils/osx.py", line 340, in binary_to_target_arch
ERROR:root:            raise IncompatibleBinaryArchError(f"{display_name} is not a fat binary!")
ERROR:root:        PyInstaller.utils.osx.IncompatibleBinaryArchError: /Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/lib-dynload/_struct.cpython-312-darwin.so is not a fat binary!
ERROR:root:
Traceback (most recent call last):
  File "/Users/mbp151/OpenCore-Legacy-Patcher/./Build-Project.command", line 167, in <module>
    main()
  File "/Users/mbp151/OpenCore-Legacy-Patcher/./Build-Project.command", line 104, in main
    ).generate()
      ^^^^^^^^^^
  File "/Users/mbp151/OpenCore-Legacy-Patcher/ci_tooling/build_modules/application.py", line 171, in generate
    self._generate_application()
  File "/Users/mbp151/OpenCore-Legacy-Patcher/ci_tooling/build_modules/application.py", line 46, in _generate_application
    subprocess_wrapper.run_and_verify(_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/mbp151/OpenCore-Legacy-Patcher/opencore_legacy_patcher/support/subprocess_wrapper.py", line 75, in run_and_verify
    verify(run(*args, **kwargs))
  File "/Users/mbp151/OpenCore-Legacy-Patcher/opencore_legacy_patcher/support/subprocess_wrapper.py", line 66, in verify
    raise Exception(f"Process failed with exit code {process_result.returncode}")
Exception: Process failed with exit code 1

```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by startergo** [comment]
Tried versions:
```
3.11.9
* 3.12.3 (set by /Users/mbp151/.pyenv/version)
  3.13.0b1
```
with the same error.

**Comment by rokm** [comment]
> ERROR:root:        PyInstaller.utils.osx.IncompatibleBinaryArchError: /Users/mbp151/.pyenv/versions/3.12.3/lib/python3.12/lib-dynload/_struct.cpython-312-darwin.so is not a fat binary!

You cannot build `universal2` binary if your Python is single-arch.

**Comment by startergo** [comment]
> You cannot build `universal2` binary if your Python is single-arch.

Can you please elaborate on this?
I am following the build instructions here:
https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/SOURCE.md
And nowhere it says to install multi-arch Python. How can I install multi-arch python?

it fails on this command:
```
python3 Build-Project.command
```

**Comment by rokm** [comment]
> Can you please elaborate on this?

https://pyinstaller.org/en/stable/feature-notes.html#macos-multi-arch-support

>   I am following the build instructions here: ... And nowhere it says to install multi-arch Python.  

It clearly says "Additionally, ensure that it was downloaded from the official source, [python.org](https://www.python.org/downloads/macos/)."

> How can I install multi-arch python?

python.org build are `universal2`. 

For pyenv, it's up to you to look up how to make it build a `universal2` python for you.

**Comment by startergo** [comment]
> It clearly says "Additionally, ensure that it was downloaded from the official source, [python.org](https://www.python.org/downloads/macos/)."

Those versions did not work, but this did:
https://github.com/macadmins/python
