### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 586: character maps to <undefined>

### ISSUE THREAD

**Issue by charles-cooper** [pyinstaller/pyinstaller#8865]
running into an issue with pyinstaller on windows when a data file has an emoji in it

https://github.com/vyperlang/vyper/actions/runs/11684959271/job/32537318181?pr=4342#step:5:44

copying the traceback,
```
[23 lines of output]
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-k54l0862\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-k54l0862\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
      self.run_setup()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-k54l0862\overlay\Lib\site-packages\setuptools\build_meta.py", line 5[21](https://github.com/vyperlang/vyper/actions/runs/11684959271/job/32537318181?pr=4342#step:5:22), in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-k54l0862\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
      exec(code, locals())
    File "<string>", line 40, in <module>
    File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\encodings\cp1252.py", line [23](https://github.com/vyperlang/vyper/actions/runs/11684959271/job/32537318181?pr=4342#step:5:24), in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 586: character maps to <undefined>
  [end of output]
```

the offending line seems to be a change to the readme which adds this emoji 🐍 (`U+1F40D`)

commit to check out: https://github.com/vyperlang/vyper/pull/4342/commits/abb5c29aca2be869871d9cea553dac09a32c4675

pyinstaller version: 6.11.0

**Comment by rokm** [comment]
That traceback seems to be coming from `pip` while it is processing `d:\a\vyper\vyper` (i.e., `pip install .`). It has nothing to do with PyInstaller. 

Try splitting that `pip install . && pip install pyinstaller && ./make.cmd freeze` command into three distinct steps, and you'll likely see that it fails on the first one.

**Comment by charles-cooper** [comment]
hmm yea seems to be the case. i'll investigate more and reopen if i still think it is a pyinstaller issue.

**Comment by charles-cooper** [comment]
@rokm confirmed, was an issue in my setup.py. thanks!
