### ISSUE TITLE
ModuleNotFoundError: No module named 'logging.config'

### ISSUE THREAD

**Issue by VigersRay** [pyinstaller/pyinstaller#8867]
## Description of the issue
If i start binary file i get error:
ModuleNotFoundError: No module named 'logging.config'

If I unzip the binary and check the logging directory it will have this content.
```
__init__.pyc
```
But the content should look like this
```
__init__.pyc
config.pyc
handlers.pyc
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.11.0
* Version of Python: 3.10.2
* Platform: Ubuntu 22.04
* How you installed Python: apt
* Did you also try this on another platform? Does it work there?: Try on windows - also no work.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import yaml
import logging

from pathlib import Path
from contextlib import suppress
from models.config import Paths
from logging.config import dictConfig


def setup_logging(paths: Paths):
    with paths.logging_config_file.open("r") as f:
        logging_config = yaml.safe_load(f)
        with suppress(KeyError):
            log_dir = paths.log_path
            patch_filename(logging_config['handlers']['file'], log_dir)
            log_dir.mkdir(exist_ok=True)
        dictConfig(logging_config)
    logging.info("Logging configured successfully")


def patch_filename(dct: dict, log_dir: Path):
    dct["filename"] = log_dir / dct["filename"]
```

```
pyinstaller --clean --onefile app/main.py \
  --name "main" \
  --add-data "app/models:models" \
  --add-data "app/services:services" \
  --add-data "app/config:config" \
  --add-data "app/utils:utils" \
  --add-data "app/internal:internal" \
  --add-data "app/cogs:cogs" \
  --add-data "app/jobs:jobs" \
  --add-data "app/locale/*:locale" \
  --add-data "app/prototypes/*:prototypes" \
  --hidden-import nextcord \
  --hidden-import asyncpg \
  --hidden-import yaml \
  --hidden-import colorlog \
  --hidden-import babel \
  --hidden-import fluent \
  --hidden-import apscheduler \
  --collect-all asyncpg
```

### Stacktrace / full error message

```
PyInstaller: running path finder hook for path: '/tmp/_MEI1FmGne/logging'
PyInstaller: hook succeeded
PyiFrozenImporter(/tmp/_MEI1FmGne/logging): find_spec: called with fullname='logging.config', target='logging.config'
PyiFrozenImporter(/tmp/_MEI1FmGne/logging): find_spec: 'logging.config' not found in PYZ...
PyiFrozenImporter(/tmp/_MEI1FmGne/logging): find_spec: attempting resolve using fallback finder FileFinder('/tmp/_MEI1FmGne/logging').
PyiFrozenImporter(/tmp/_MEI1FmGne/logging): find_spec: fallback finder returned spec: None.
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen app.main>", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen config.setup_logging>", line 3, in <module>
  File "<frozen app.config.setup_logging>", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'logging.config'
[PYI-11668:ERROR] Failed to execute script 'main' due to unhandled exception!
[PYI-11668:DEBUG] LOADER: ERROR.
[PYI-11668:DEBUG] LOADER: manually flushing stdout and stderr...
[PYI-11668:DEBUG] LOADER: cleaning up Python interpreter...

```

**Comment by VigersRay** [comment]
I also want to note that in another project with the same use of logging.config and similar packaging on the same system, such a bug does not occur.
The only difference is in the packages that I add to the binary and the code structure.
```
pyinstaller --clean --onefile app/main.py \
  --name "main" \
  --add-data "app/models:models" \
  --add-data "app/services:services" \
  --add-data "app/config:config" \
  --add-data "app/handlers:handlers" \
  --add-data "app/utils:utils" \
  --hidden-import aiogram \
  --hidden-import discord \
  --hidden-import discordoauth2 \
  --hidden-import asyncpg \
  --hidden-import uvicorn \
  --hidden-import fastapi \
  --hidden-import fastapi.templating \
  --hidden-import qrcode \
  --hidden-import colorlog \
  --collect-all asyncpg
  ```

**Comment by bwoodsend** [comment]
Do you have another directory called `logging` somewhere shadowing the standard library package? You can check where PyInstaller is pulling `logging` from by looking in either `build/*/xref-*.html` or the various `build/*/*.toc` files.

**Comment by VigersRay** [comment]
> Do you have another directory called logging somewhere shadowing the standard library package? You can check where PyInstaller is pulling logging from by looking in either build/*/xref-*.html or the various build/*/*.toc files.

Current project
```
<div class="node">
  <a name="logging"></a>
  <a target="code" href="/usr/lib/python3.10/logging/__init__.py" type="text/plain"><tt>logging</tt></a>
<span class="moduletype">Package</span>  <div class="import">
imports:
    <a href="#atexit">atexit</a>
 &#8226;   <a href="#collections.abc">collections.abc</a>
 &#8226;   <a href="#io">io</a>
 &#8226;   <a href="#os">os</a>
 &#8226;   <a href="#pickle">pickle</a>
 &#8226;   <a href="#re">re</a>
 &#8226;   <a href="#string">string</a>
 &#8226;   <a href="#sys">sys</a>
 &#8226;   <a href="#threading">threading</a>
 &#8226;   <a href="#time">time</a>
 &#8226;   <a href="#traceback">traceback</a>
 &#8226;   <a href="#warnings">warnings</a>
 &#8226;   <a href="#weakref">weakref</a>
```

Other project
```
<div class="node">
  <a name="logging"></a>
  <a target="code" href="/usr/lib/python3.10/logging/__init__.py" type="text/plain"><tt>logging</tt></a>
<span class="moduletype">Package</span>  <div class="import">
imports:
    <a href="#atexit">atexit</a>
 &#8226;   <a href="#collections.abc">collections.abc</a>
 &#8226;   <a href="#io">io</a>
 &#8226;   <a href="#os">os</a>
 &#8226;   <a href="#pickle">pickle</a>
 &#8226;   <a href="#re">re</a>
 &#8226;   <a href="#string">string</a>
 &#8226;   <a href="#sys">sys</a>
 &#8226;   <a href="#threading">threading</a>
 &#8226;   <a href="#time">time</a>
 &#8226;   <a href="#traceback">traceback</a>
 &#8226;   <a href="#warnings">warnings</a>
 &#8226;   <a href="#weakref">weakref</a>

<div class="node">
  <a name="logging.config"></a>
  <a target="code" href="/usr/lib/python3.10/logging/config.py" type="text/plain"><tt>logging.config</tt></a>
<span class="moduletype">SourceModule</span>  <div class="import">
imports:
    <a href="#configparser">configparser</a>
 &#8226;   <a href="#errno">errno</a>
 &#8226;   <a href="#io">io</a>
 &#8226;   <a href="#json">json</a>
 &#8226;   <a href="#logging">logging</a>
 &#8226;   <a href="#logging.handlers">logging.handlers</a>
 &#8226;   <a href="#re">re</a>
 &#8226;   <a href="#select">select</a>
 &#8226;   <a href="#socketserver">socketserver</a>
 &#8226;   <a href="#struct">struct</a>
 &#8226;   <a href="#sys">sys</a>
 &#8226;   <a href="#threading">threading</a>
 &#8226;   <a href="#traceback">traceback</a>


<div class="node">
  <a name="logging.handlers"></a>
  <a target="code" href="/usr/lib/python3.10/logging/handlers.py" type="text/plain"><tt>logging.handlers</tt></a>
<span class="moduletype">SourceModule</span>  <div class="import">
imports:
    <a href="#base64">base64</a>
 &#8226;   <a href="#copy">copy</a>
 &#8226;   <a href="#email.message">email.message</a>
 &#8226;   <a href="#email.utils">email.utils</a>
 &#8226;   <a href="#http.client">http.client</a>
 &#8226;   <a href="#io">io</a>
 &#8226;   <a href="#logging">logging</a>
 &#8226;   <a href="#os">os</a>
 &#8226;   <a href="#pickle">pickle</a>
 &#8226;   <a href="#queue">queue</a>
 &#8226;   <a href="#re">re</a>
 &#8226;   <a href="#smtplib">smtplib</a>
 &#8226;   <a href="#socket">socket</a>
 &#8226;   <a href="#stat">stat</a>
 &#8226;   <a href="#struct">struct</a>
 &#8226;   <a href="#threading">threading</a>
 &#8226;   <a href="#time">time</a>
 &#8226;   <a href="#urllib.parse">urllib.parse</a>
 &#8226;   <a href="#win32evtlog">win32evtlog</a>
 &#8226;   <a href="#win32evtlogutil">win32evtlogutil</a>
```

**Comment by VigersRay** [comment]
Also current project have this
```
<div class="node">
  <a name="configparser"></a>
  <a target="code" href="/usr/lib/python3.10/configparser.py" type="text/plain"><tt>configparser</tt></a>
<span class="moduletype">SourceModule</span>  <div class="import">
imports:
    <a href="#collections">collections</a>
 &#8226;   <a href="#collections.abc">collections.abc</a>
 &#8226;   <a href="#functools">functools</a>
 &#8226;   <a href="#io">io</a>
 &#8226;   <a href="#itertools">itertools</a>
 &#8226;   <a href="#os">os</a>
 &#8226;   <a href="#re">re</a>
 &#8226;   <a href="#sys">sys</a>
 &#8226;   <a href="#warnings">warnings</a>
```
Other work project have this
```
<div class="node">
  <a name="configparser"></a>
  <a target="code" href="/usr/lib/python3.10/configparser.py" type="text/plain"><tt>configparser</tt></a>
<span class="moduletype">SourceModule</span>  <div class="import">
imports:
    <a href="#collections">collections</a>
 &#8226;   <a href="#collections.abc">collections.abc</a>
 &#8226;   <a href="#functools">functools</a>
 &#8226;   <a href="#io">io</a>
 &#8226;   <a href="#itertools">itertools</a>
 &#8226;   <a href="#os">os</a>
 &#8226;   <a href="#re">re</a>
 &#8226;   <a href="#sys">sys</a>
 &#8226;   <a href="#warnings">warnings</a>

  </div>
  <div class="import">
imported by:
    <a href="#logging.config">logging.config</a>

  </div>
```

**Comment by rokm** [comment]
Hmm, does adding `--hiddenimport logging.config` and `--hiddenimport logging.handlers` to your PyInstaller command make any difference?

---

How come your entry-point script and modules are also marked as `frozen` in the traceback:
```
  File "<frozen __main__>", line 3, in <module>
...
  File "<frozen app.main>", line 10, in <module>
...
  File "<frozen config.setup_logging>", line 3, in <module>
...
  File "<frozen app.config.setup_logging>", line 7, in <module>
...
```

Were these pre-compiled or obfuscated prior to being analyzed and collected by PyInstaller? For example, are you using pyarmor?

**Comment by VigersRay** [comment]
> Were these pre-compiled or obfuscated prior to being analyzed and collected by PyInstaller? For example, are you using pyarmor?

Yes, I use pyarmor, but in another project there are no problems when using pyarmor.

**Comment by rokm** [comment]
> > Were these pre-compiled or obfuscated prior to being analyzed and collected by PyInstaller? For example, are you using pyarmor?
> 
> Yes, I use pyarmor, but in another project there are no problems when using pyarmor.

Then I would guess that's your problem - you are feeding obfuscated modules to PyInstaller, which cannot analyze imports from your modules. Perhaps in the other project you have some other (hidden) imports that end up referencing `logging.config` and that's why it is collected. You can check the xref of the working program to see what modules `logging.config` was referred from (e.g., the "imported by:" under `logging.config` entry).

**Comment by VigersRay** [comment]
> Hmm, does adding `--hiddenimport logging.config` and `--hiddenimport logging.handlers` to your PyInstaller command make any difference?

add `--hiddenimport logging.config` resolve problem. At least there is no more error.

**Comment by VigersRay** [comment]
> > > Were these pre-compiled or obfuscated prior to being analyzed and collected by PyInstaller? For example, are you using pyarmor?
> > 
> > 
> > Yes, I use pyarmor, but in another project there are no problems when using pyarmor.
> 
> Then I would guess that's your problem - you are feeding obfuscated modules to PyInstaller, which cannot analyze imports from your modules. Perhaps in the other project you have some other (hidden) imports that end up referencing `logging.config` and that's why it is collected. You can check the xref of the working program to see what modules `logging.config` was referred from (e.g., the "imported by:" under `logging.config` entry).

Yes, that be uvicorn.
```
<div class="node">
  <a name="logging.config"></a>
  <a target="code" href="/usr/lib/python3.10/logging/config.py" type="text/plain"><tt>logging.config</tt></a>
<span class="moduletype">SourceModule</span>  <div class="import">
imports:
    <a href="#configparser">configparser</a>
 &#8226;   <a href="#errno">errno</a>
 &#8226;   <a href="#io">io</a>
 &#8226;   <a href="#json">json</a>
 &#8226;   <a href="#logging">logging</a>
 &#8226;   <a href="#logging.handlers">logging.handlers</a>
 &#8226;   <a href="#re">re</a>
 &#8226;   <a href="#select">select</a>
 &#8226;   <a href="#socketserver">socketserver</a>
 &#8226;   <a href="#struct">struct</a>
 &#8226;   <a href="#sys">sys</a>
 &#8226;   <a href="#threading">threading</a>
 &#8226;   <a href="#traceback">traceback</a>

  </div>
  <div class="import">
imported by:
    <a href="#uvicorn.config">uvicorn.config</a>

  </div>

</div>
  ```
