### ISSUE TITLE
Not work with pyside6.

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [pyinstaller/pyinstaller#8883]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11.1```
* Version of Python: ```3.10.1```
* Platform: ```Windows 10```
* How you installed Python: python.org/downloads

### Stacktrace / full error message

```146 INFO: PyInstaller: 6.11.1, contrib hooks: 2024.10
146 INFO: Python: 3.10.1
153 INFO: Platform: Windows-10-10.0.19045-SP0
153 INFO: Python environment: D:\python_3.10.1
157 INFO: Module search paths (PYTHONPATH):
['D:\\python_3.10.1\\scripts\\pyinstaller.exe',
 'D:\\python_3.10.1\\python310.zip',
 'D:\\python_3.10.1\\DLLs',
 'D:\\python_3.10.1\\lib',
 'D:\\python_3.10.1',
 'D:\\python_3.10.1\\lib\\site-packages',
 'D:\\src']
456 INFO: checking Analysis
456 INFO: Building Analysis because Analysis-00.toc is non existent
458 INFO: Running Analysis Analysis-00.toc
459 INFO: Target bytecode optimization level: 0
459 INFO: Initializing module dependency graph...
461 INFO: Initializing module graph hook caches...
472 INFO: Analyzing base_library.zip ...
941 INFO: Processing standard module hook 'hook-heapq.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
968 INFO: Processing standard module hook 'hook-encodings.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
1440 INFO: Processing standard module hook 'hook-pickle.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
1755 INFO: Caching module dependency graph...
1799 INFO: Looking for Python shared library...
1806 INFO: Using Python shared library: D:\python_3.10.1\python310.dll
1806 INFO: Analyzing D:\src\main.py
1810 INFO: Processing standard module hook 'hook-PySide6.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
1936 INFO: Processing standard module hook 'hook-shiboken6.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
1941 INFO: Processing standard module hook 'hook-PySide6.QtNetwork.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
2303 INFO: Processing standard module hook 'hook-PySide6.QtWidgets.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
2477 INFO: Processing standard module hook 'hook-PySide6.QtCore.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
2629 INFO: Processing standard module hook 'hook-PySide6.QtGui.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
2945 INFO: Processing standard module hook 'hook-platform.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
2983 INFO: Processing standard module hook 'hook-lxml.py' from 'D:\\python_3.10.1\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
3242 INFO: Processing standard module hook 'hook-lxml.etree.py' from 'D:\\python_3.10.1\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
3302 INFO: Processing standard module hook 'hook-cv2.py' from 'D:\\python_3.10.1\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
3638 INFO: Processing standard module hook 'hook-numpy.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
3839 INFO: Processing standard module hook 'hook-sysconfig.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
4188 INFO: Processing standard module hook 'hook-difflib.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
4234 INFO: Processing standard module hook 'hook-multiprocessing.util.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
4255 INFO: Processing standard module hook 'hook-xml.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
4847 INFO: Processing standard module hook 'hook-charset_normalizer.py' from 'D:\\python_3.10.1\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
4887 INFO: Processing pre-safe-import-module hook 'hook-typing_extensions.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module'
4889 INFO: SetuptoolsInfo: initializing cached setuptools info...
5425 INFO: Processing module hooks (post-graph stage)...
5508 INFO: Processing standard module hook 'hook-lxml.isoschematron.py' from 'D:\\python_3.10.1\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
5538 INFO: Processing standard module hook 'hook-lxml.objectify.py' from 'D:\\python_3.10.1\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
5543 INFO: Performing binary vs. data reclassification (130 entries)
5579 INFO: Looking for ctypes DLLs
5586 INFO: Analyzing run-time hooks ...
5588 INFO: Including run-time hook 'pyi_rth_inspect.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks\\rthooks'
5589 INFO: Including run-time hook 'pyi_rth_pkgutil.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks\\rthooks'
5591 INFO: Including run-time hook 'pyi_rth_multiprocessing.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks\\rthooks'
5592 INFO: Including run-time hook 'pyi_rth_pyside6.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks\\rthooks'
5593 INFO: Processing pre-find-module-path hook 'hook-_pyi_rth_utils.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path'
5595 INFO: Processing standard module hook 'hook-_pyi_rth_utils.py' from 'D:\\python_3.10.1\\lib\\site-packages\\PyInstaller\\hooks'
5723 INFO: Looking for dynamic libraries
QPixmap: Must construct a QGuiApplication before a QPixmap
Traceback (most recent call last):
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\building\build_main.py", line 286, in find_binary_dependencies
    child.call(import_library, package)
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\isolated\_parent.py", line 322, in call
    raise SubprocessDiedError(
PyInstaller.isolated._parent.SubprocessDiedError: Child process died calling import_library() with args=('components.launcher',) and kwargs={}. Its exit code was 3221226505.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "D:\python_3.10.1\scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\__main__.py", line 231, in _console_script_run
    run()
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\building\build_main.py", line 1252, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\building\build_main.py", line 1192, in build
    exec(code, spec_namespace)
  File "D:\python_3.10.1\make_min_py_env.spec", line 61, in <module>
    grub(r"D:\src\main.py", r"D:\bin")
  File "D:\python_3.10.1\make_min_py_env.spec", line 8, in grub
    res = Analysis(
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\building\build_main.py", line 581, in __init__
    self.__postinit__()
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\building\build_main.py", line 949, in assemble
    find_binary_dependencies(self.binaries, collected_packages, self.graph._bindepend_symlink_suppression)
  File "D:\python_3.10.1\lib\site-packages\PyInstaller\building\build_main.py", line 290, in find_binary_dependencies
    raise isolated.SubprocessDiedError(
PyInstaller.isolated._parent.SubprocessDiedError: Isolated subprocess crashed while importing package 'components.launcher'! Package import list: ['PySide6', 'PySide6.support', 'importlib', 'importlib.metadata', 'urllib', 'email', '_pyi_rth_utils', 'xmlrpc', 'xml.parsers', 'xml', 'http', 'xml.sax', 'ctypes', 'multiprocessing.dummy', 'multiprocessing', 'collections', 'encodings', 'components.launcher', 'checkers.xgtf', 'checkers.xgtf.obj_detector', 'cv2', 'cv2.utils', 'cv2.typing', 'cv2.misc', 'cv2.mat_wrapper', 'cv2.gapi', 'cv2.data', 'numpy.core', 'numpy._utils', 'numpy._core', 'numpy.testing', 'numpy.ma', 'numpy.matrixlib', 'numpy.linalg', 'numpy._typing', 'numpy.lib', 'html', 'pydoc_data', 'concurrent.futures', 'concurrent', 'numpy.testing._private', 'unittest', 'asyncio', 'numpy', 'numpy.strings', 'numpy.char', 'numpy.rec', 'numpy.typing', 'numpy.f2py', 'numpy.f2py._backends', 'charset_normalizer', 'json', 'numpy.polynomial', 'numpy.random', 'numpy.fft', 'lxml', 'lxml.isoschematron', 'lxml.includes.libxslt', 'lxml.includes.libxml', 'lxml.includes.libexslt', 'lxml.includes.extlibs', 'lxml.includes', 'lxml.html', 'checkers.pascal_voc.object_detector', 'checkers.pascal_voc', 'checkers.pascal_voc.segmentation_or_pose', 'common', 'shiboken6', 'logging']
The list of required libraries could not be compiled. Continuation is not possible!
```

**Comment by rokm** [comment]
You'll have to change the code in `components.launcher` to not instantiate `QPixmap()` when it is imported (but do it on demand or somesuch). On Windows,  we import all packages prior to binary dependency analysis, and so importing `components.launcher` throws causes `QPixmap: Must construct a QGuiApplication before a QPixmap` error.

Alternatively, you can modify your local PyInstaller copy and add `components.launcher` to the list of suppressed imports at the end of this code block:

https://github.com/pyinstaller/pyinstaller/blob/a2a6d1e5f1a8db5b7558b2158f2af21cb6a8e0b4/PyInstaller/building/build_main.py#L261-L279

**Comment by Yrij-Zhavoronkov** [comment]
Thanks for the prompt response ;)

**Comment by C0rn3j** [comment]
I ran into the same issue on Windows, but with `python-magic` - built from this PR repo that is hanging there but hopefully will be merged soon (it contains prebuilt wheels) - 

`export PIP_FIND_LINKS=https://github.com/ddelange/python-magic/releases/expanded_assets/0.4.28.post8`

I effectively do just this, which works on macOS/Linux (albeit with stock python-magic, not PR build):

```python
import magic
mime = magic.Magic(mime=True)
```

Do I also need to override this locally, and is there a nicer way to do so other than hacking pyinstaller .py files or reworking the code, perhaps in a spec file?

```python
# CI with full log - https://github.com/Taiko2k/Tauon/actions/runs/12528574630/job/34943296152
56220 INFO: Compiling collected GLib schema files in 'D:/a/Tauon/Tauon/build/windows/_pyi_gschema_compilation'...
56235 DEBUG: Output from glib-compile-schemas:

56297 DEBUG: Module collection settings: {}
56297 DEBUG: Target optimization level 0 matches run-time optimization level 0 - using modulegraph's code-object cache.
56313 INFO: Looking for dynamic libraries
Traceback (most recent call last):
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 286, in find_binary_dependencies
    child.call(import_library, package)
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/isolated/_parent.py", line 322, in call
    raise SubprocessDiedError(
PyInstaller.isolated._parent.SubprocessDiedError: Child process died calling import_library() with args=('magic',) and kwargs={}. Its exit code was 3221225477.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:/a/Tauon/Tauon/.venv/bin/pyinstaller.exe/__main__.py", line 7, in <module>
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/__main__.py", line 231, in _console_script_run
    run()
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 1252, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 1192, in build
    exec(code, spec_namespace)
  File "windows.spec", line 23, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 581, in __init__
    self.__postinit__()
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 949, in assemble
    find_binary_dependencies(self.binaries, collected_packages, self.graph._bindepend_symlink_suppression)
  File "D:/a/Tauon/Tauon/.venv/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 290, in find_binary_dependencies
    raise isolated.SubprocessDiedError(
PyInstaller.isolated._parent.SubprocessDiedError: Isolated subprocess crashed while importing package 'magic'! Package import list: ['zipfile', 'zipfile._path', 'importlib', 'importlib.metadata', 'importlib.resources', 'urllib', 'email', '_distutils_hack', 'setuptools', 'setuptools._distutils.compat', 'setuptools._vendor.jaraco.functools', 'setuptools._distutils', 'setuptools._vendor.more_itertools', 'json', 'setuptools._distutils.command', 'unittest', 'asyncio', 'concurrent.futures', 'multiprocessing.dummy', 'xmlrpc', 'xml.parsers', 'xml', 'xml.sax', 'http', 'multiprocessing', 'concurrent', 'packaging', 'pkg_resources', 'packaging.licenses', 'setuptools._vendor.platformdirs', 'setuptools._vendor.jaraco.text', 'setuptools._vendor.backports.tarfile', 'setuptools._vendor.backports', 'setuptools._vendor.backports.tarfile.compat', 'backports', 'html', 'pydoc_data', 'setuptools._vendor.importlib_metadata', 'setuptools._vendor.importlib_metadata.compat', 'setuptools._vendor.zipp', 'setuptools._vendor.zipp.compat', 'setuptools._vendor.wheel', 'setuptools.compat', 'setuptools._vendor.wheel.cli', 'setuptools._vendor.wheel.vendored.packaging', 'setuptools._vendor.wheel.vendored', 'setuptools.config._validate_pyproject', 'setuptools._vendor.packaging', 'setuptools._vendor.tomli', 'tomllib', 'setuptools.config', 'setuptools.command', 'zeroconf._handlers', 'zeroconf', 'zeroconf._utils', 'ifaddr', 'ctypes.macholib', 'zeroconf._protocol', 'tekore', 'tekore._sender', 'httpx', 'httpcore', 'httpcore._backends', 'anyio', 'anyio.streams', 'anyio._core', 'anyio.abc', 'sniffio', 'anyio._backends', 'idna', 'httpcore._sync', 'h11', 'certifi', 'httpcore._async', 'httpx._transports', 'tekore._client', 'tekore._client.decor', 'tekore._client.api', 'tekore._client.api.playlist', 'tekore._client.api.player', 'tekore._client.api.browse', 'tekore._auth', 'tekore._auth.expiring', 'tekore._model', 'tekore._model.show', 'pydantic', 'zoneinfo', 'pydantic.v1', 'Cython', 'Cython.Build', 'Cython.Distutils', 'pyximport', 'xml.etree', 'Cython.Plex', 'Cython.Tempita', 'Cython.Compiler', 'Cython.Debugger', 'annotated_types', 'pydantic.plugin', 'pydantic._internal', 'pydantic.deprecated', 'pydantic_core', 'tekore._model.chapter', 'tekore._model.audiobook', 'tekore._model.album', 'pylast', 'xml.dom', 'dbm', 'collections', 're', 'encodings', 'comtypes.client', 'comtypes.tools.codegenerator', 'comtypes.tools', 'keyboard', 'lynxtray', 'plexapi', 'pychromecast', 'pychromecast.controllers', 'google.protobuf.pyext', 'google.protobuf.internal', 'google.protobuf', 'gi.overrides', 'cairo', 'gi', 'comtypes', 'comtypes.server', 'comtypes._post_coinit', 'natsort', 'natsort.compat', 'opencc', 'pypresence', 'setproctitle', 'jxlpy', 'tidalapi', 'urllib3.util', 'urllib3.http2', 'urllib3', 'urllib3.contrib.emscripten', 'urllib3.contrib', 'mpegdash', 'isodate', 'dateutil.parser', 'dateutil.tz', 'dateutil.zoneinfo', 'dateutil', 'unidecode', 'send2trash', 'send2trash.win', 'send2trash.mac', 'PIL', 'bs4', 'soupsieve', 'charset_normalizer', 'bs4.builder', 'requests', 'mutagen.mp3', 'mutagen.asf', 'mutagen.mp4', 'mutagen.id3', 'mutagen', 'musicbrainzngs', 'magic', 'tauon', 'tauon.t_modules', 'sdl2dll', 'pip', 'pip._internal.utils', 'pip._vendor.platformdirs', 'pip._vendor', 'pip._vendor.tomli', 'pip._vendor.distro', 'pip._vendor.msgpack', 'pip._vendor.idna', 'pip._internal', 'pip._vendor.urllib3.util', 'pip._vendor.urllib3', 'pip._vendor.urllib3.packages', 'pip._vendor.urllib3.packages.backports', 'pip._vendor.urllib3.contrib', 'pip._internal.cli', 'pip._vendor.pyproject_hooks', 'pip._vendor.pyproject_hooks._in_process', 'pip._vendor.packaging', 'pip._internal.models', 'pip._internal.locations', 'jaraco.collections', 'pip._vendor.rich', 'pip._vendor.pygments.styles', 'pip._vendor.pygments', 'pip._vendor.pygments.filters', 'pip._vendor.pygments.lexers', 'pip._internal.req', 'pip._internal.network', 'pip._vendor.cachecontrol.caches', 'pip._vendor.certifi', 'pip._vendor.cachecontrol', 'pip._vendor.requests', 'pip._internal.index', 'pip._internal.vcs', 'pip._internal.operations.install', 'pip._internal.operations', 'pip._vendor.distlib', 'pip._internal.operations.build', 'pip._internal.metadata', 'pip._internal.metadata.importlib', 'pip._vendor.pkg_resources', 'pip._internal.commands', 'sdl2', 'gi.repository', 'ctypes', 'logging']
```

**Comment by rokm** [comment]
> Do I also need to override this locally, and is there a nicer way to do so other than hacking pyinstaller .py files or reworking the code, perhaps in a spec file?

You'll have to hack the [pyinstaller/PyInstaller/building/build_main.py](https://github.com/pyinstaller/pyinstaller/blob/a2a6d1e5f1a8db5b7558b2158f2af21cb6a8e0b4/PyInstaller/building/build_main.py#L261-L279).

Does importing `magic` crash the interpreter only in PyInstaller's subprocess, or also outside of it?

**Comment by bwoodsend** [comment]
All PyInstaller is doing is importing the package. If doing that causes the Python interpreter to crash (and by _crash_ I mean something akin to a segfault and not just a Python exception) then that means your environment is broken and as will be anything you run or build in it.

So what you should be doing is deciding whether you need this `magic` package (and in your case, it sounds like you do) then figure if you do, figure out why `python -c "import magic"` causes such a meltdown.
