### ISSUE TITLE
Running pyinstaller binary throws error related to shared library libbcc.so 

### ISSUE THREAD

**Issue by fatimaZahra5** [pyinstaller/pyinstaller#8887]
Hi, I am creating a python executable on my Ubuntu machine, where it runs fine but when i try to run the same executable on a different machine it throws this error:
```
Traceback (most recent call last):
  File "apscheduler/schedulers/base.py", line 845, in _dispatch_event
  File "agent/run.py", line 38, in job_listener
    from agent.tasks.linux.packet_sniffing import LinuxSnifferRunner
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "agent/tasks/linux/packet_sniffing/__init__.py", line 1, in <module>
    from .packet_sniffer import PacketSniffer
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "agent/tasks/linux/packet_sniffing/packet_sniffer.py", line 14, in <module>
    from bcc import BPF
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "bcc/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "bcc/libbcc.py", line 20, in <module>
  File "ctypes/__init__.py", line 387, in __getattr__
  File "ctypes/__init__.py", line 392, in __getitem__
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b
```

I am creating the executable with **--onefile** option and have added the binary paths for the libbcc in the main.spec file like this:
`binaries=[('/usr/lib/x86_64-linux-gnu/libbcc.so.0', '.')],`

**Comment by rokm** [comment]
What version of Ubuntu are you building on, and what linux distribution is running on the other machine?

**Comment by fatimaZahra5** [comment]
> What version of Ubuntu are you building on, and what linux distribution is running on the other machine?

The ubuntu version I am building on is 22 and I have tried running it on  ubuntu versions 23.04 and 22.04.4 LTS  and also centos  stream 9.

**Comment by rokm** [comment]
Adding
```
 binaries=[('/usr/lib/x86_64-linux-gnu/libbcc.so.0', '.')],
```
to the spec should do the trick. 

I've built a test program on Ubuntu 22.04 and ran it under 23.04, and with `libbcc.so.0` collected, it seems to work (without collection, it tries to load system copy of the library, and fails either due to it not being installed or due to the missing symbol).

In your case, though, a system copy is still being loaded, which leads me to believe that the shared library was not collected. After you added `binaries=...` to the .spec file, did you rebuild the program by running PyInstaller against the spec file, or did you build it again by running PyInstaller against the .py file? (The latter case would re-generate and overwrite the .spec, and thus discard the modification that you made).

**Comment by fatimaZahra5** [comment]
I built it against the main.spec file after making the changes to the spec file. This is the command I am using
`pyinstaller main.spec`

**Comment by rokm** [comment]
Can you run `pyi-archive_viewer <path-to-executable>` and check that `libbcc.so.0` is collected?

**Comment by fatimaZahra5** [comment]
yes I can see libbcc.so.0 is collected.

**Comment by rokm** [comment]
Hmm, then it should work.

Can you try freezing the following sample program:

```
from bcc import BPF
print("Hello")
```

in the same way as your application? And if it throws the same error, please upload the executable somewhere so I can take a look at it.

**Comment by fatimaZahra5** [comment]
I tried freezing the sample program and it ran without an error. For my application, I removed the old dist and build folders and created a new executable with --clean and that solved the problem. However, I encounter another issue when i create a binary on ubuntu 23.04, which runs fine on it but will give me following error for  22.04.4 LTS.

`[PYI-1635:ERROR] Failed to load Python shared library '/tmp/_MEIgqNX4X/libpython3.11.so': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/_MEIgqNX4X/libexpat.so.1)`

**Comment by rokm** [comment]
> However, I encounter another issue when i create a binary on ubuntu 23.04, which runs fine on it but will give me following error for 22.04.4 LTS.
> 
> `[PYI-1635:ERROR] Failed to load Python shared library '/tmp/_MEIgqNX4X/libpython3.11.so': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/_MEIgqNX4X/libexpat.so.1)`

See https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible

You can run frozen application only on systems that have glibc of same or higher version than your build system. So you can build on 22.04 and run on 22.04 and 23.04 (and later), but you cannot build on 23.04 and run on 22.04 (or earlier).

**Comment by fatimaZahra5** [comment]
Okay I get it now why I do not face the same issue when building on an older version and running on a newer version of linux. @rokm Thank you for helping out.
