### ISSUE TITLE
on linux pyinstaller should bundle libdb-*.so

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#889]
**Original date**: 2014/04/16
**Original reporter**: *jothiram DOT s AND gmail DOT  COOM *

Hello,

I have been using bb-freeze and I just moved to pyinstaller.

With pyinstaller when I compiled my python executable it missed one of the libraries 'libdb-4.8.0.so' while bb-freeze had it.

Because of this, one person who is running Ubuntu 12.04 64 bit. got the below error
 
“Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "/usr/local/lib/python2.6/dist-packages/PyInstaller-2.1-py2.6.egg/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/jothirams/svnspx/build/svnspx/out00-PYZ.pyz/pysvn", line 99, in <module>
  File "/usr/local/lib/python2.6/dist-packages/PyInstaller-2.1-py2.6.egg/PyInstaller/loader/pyi_importers.py", line 409, in load_module
ImportError: libdb-4.8.so: cannot open shared object file: No such file or directory”

Any thoughts on why this library was missed by pyinstaller.

Im using pyinstaller 2.1

**Comment by htgoebel** [comment]
This is already solved in 3b0a0a6cc1736.
