### ISSUE TITLE
PyQt6 ImportError: DLL load failed while importing QtWidgets

### ISSUE THREAD

**Issue by heyzzk** [pyinstaller/pyinstaller#8890]
Hello,
I am trying to make a PyQt6 application and run it on another Windows 10 computer which doesn't have python installed. I can build the exe file with pyinstaller and run it well on the build computer. But when I copy to exe(or one folder) to the destination computer and run it, it prompted with "ImportError: DLL load failed while importing QtWidgets". Could you provide me any suggestion about how to fix it please?

**Here is the code.**
```
import sys
from PyQt6.QtWidgets import QApplication, QLabel, QPushButton, QVBoxLayout, QWidget

def on_button_click():
    label.setText("you click the button")

app = QApplication(sys.argv)

window = QWidget()
window.setWindowTitle("PyQt6 demo")
window.resize(300, 200)

layout = QVBoxLayout()

label = QLabel("welcome to use PyQt6！")
layout.addWidget(label)

button = QPushButton("click me")
button.clicked.connect(on_button_click)
layout.addWidget(button)

window.setLayout(layout)
window.show()

sys.exit(app.exec())
```

**Here is the build log.**
```
PS I:\git\host\debug> pyinstaller.exe .\debug.py
295 INFO: PyInstaller: 6.10.0, contrib hooks: 2024.8
295 INFO: Python: 3.12.0
334 INFO: Platform: Windows-10-10.0.19045-SP0
334 INFO: Python environment: C:\Python312
338 INFO: wrote I:\git\SystemMeter\host\debug\debug.spec
355 INFO: Module search paths (PYTHONPATH):
['C:\\Python312\\Scripts\\pyinstaller.exe',
 'C:\\Python312\\python312.zip',
 'C:\\Python312\\DLLs',
 'C:\\Python312\\Lib',
 'C:\\Python312',
 'C:\\Users\\jack\\AppData\\Roaming\\Python\\Python312\\site-packages',
 'C:\\Python312\\Lib\\site-packages',
 'C:\\Python312\\Lib\\site-packages\\win32',
 'C:\\Python312\\Lib\\site-packages\\win32\\lib',
 'C:\\Python312\\Lib\\site-packages\\Pythonwin',
 'I:\\git\\SystemMeter\\host\\debug']
651 INFO: checking Analysis
655 INFO: Building because I:\git\SystemMeter\host\debug\debug.py changed
656 INFO: Running Analysis Analysis-00.toc
656 INFO: Target bytecode optimization level: 0
657 INFO: Initializing module dependency graph...
658 INFO: Caching module graph hooks...
675 INFO: Analyzing base_library.zip ...
2907 INFO: Processing standard module hook 'hook-heapq.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'
3004 INFO: Processing standard module hook 'hook-encodings.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'
4978 INFO: Processing standard module hook 'hook-pickle.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'
6461 INFO: Caching module dependency graph...
6601 INFO: Looking for Python shared library...
6611 INFO: Using Python shared library: C:\Python312\python312.dll
6611 INFO: Analyzing I:\git\SystemMeter\host\debug\debug.py
6617 INFO: Processing standard module hook 'hook-PyQt6.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'
6738 INFO: Processing standard module hook 'hook-PyQt6.QtWidgets.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'
6865 INFO: Processing module hooks (post-graph stage)...
6916 INFO: Processing standard module hook 'hook-PyQt6.QtCore.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'
7067 INFO: Processing standard module hook 'hook-PyQt6.QtGui.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'
7411 INFO: Performing binary vs. data reclassification (108 entries)
7459 INFO: Looking for ctypes DLLs
7470 INFO: Analyzing run-time hooks ...
7471 INFO: Including run-time hook 'pyi_rth_inspect.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks'
7473 INFO: Including run-time hook 'pyi_rth_pyqt6.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks'
7476 INFO: Processing pre-find-module-path hook 'hook-_pyi_rth_utils.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path'
7478 INFO: Processing standard module hook 'hook-_pyi_rth_utils.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'
7484 INFO: Including run-time hook 'pyi_rth_pkgutil.py' from 'C:\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks'
7493 INFO: Looking for dynamic libraries
7645 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Python312\\Lib\\site-packages\\PyQt6\\Qt6\\bin']
7645 INFO: Extra DLL search directories (PATH): ['C:\\Python312\\Lib\\site-packages\\PyQt6\\Qt6\\bin']
8598 INFO: Warnings written to I:\git\SystemMeter\host\debug\build\debug\warn-debug.txt
8616 INFO: Graph cross-reference written to I:\git\SystemMeter\host\debug\build\debug\xref-debug.html
8623 INFO: checking PYZ
8640 INFO: checking PKG
8641 INFO: Building because I:\git\SystemMeter\host\debug\debug.py changed
8642 INFO: Building PKG (CArchive) debug.pkg
8660 INFO: Building PKG (CArchive) debug.pkg completed successfully.
8661 INFO: Bootloader C:\Python312\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
8663 INFO: checking EXE
8664 INFO: Rebuilding EXE-00.toc because pkg is more recent
8664 INFO: Building EXE from EXE-00.toc
8665 INFO: Copying bootloader EXE to I:\git\SystemMeter\host\debug\build\debug\debug.exe
8714 INFO: Copying icon to EXE
8754 INFO: Copying 0 resources to EXE
8755 INFO: Embedding manifest in EXE
8797 INFO: Appending PKG archive to EXE
8806 INFO: Fixing EXE headers
9117 INFO: Building EXE from EXE-00.toc completed successfully.
9121 INFO: checking COLLECT
WARNING: The output directory "I:\git\SystemMeter\host\debug\dist\debug" and ALL ITS CONTENTS will be REMOVED! Continue? (y/N)y
On your own risk, you can use the option `--noconfirm` to get rid of this question.
13569 INFO: Removing dir I:\git\SystemMeter\host\debug\dist\debug
13604 INFO: Building COLLECT COLLECT-00.toc
13822 INFO: Building COLLECT COLLECT-00.toc completed successfully.
PS I:\git\host\debug>
```

**Here is the error I got.**
```
C:\Users\aaa>Z:\debug\debug.exe
Traceback (most recent call last):
  File "debug.py", line 2, in <module>
ImportError: DLL load failed while importing QtWidgets: Cannot find the specified program.
[PYI-6732:ERROR] Failed to execute script 'debug' due to unhandled exception!
C:\Users\aaa>
```

Thanks!

**Comment by rokm** [comment]
Hmm, can you rebuild that debug with added `--clean` argument, then archive both `build` and `dist` directories and upload the archive somewhere so I can take a look at it?

**Comment by rokm** [comment]
Also, does it make any difference if you copy the application bundle to a local disk (assuming that `z:\` in the test case is a network share or somesuch)? And can you check that when copying the files, they were not somehow corrupted (for example, by checking their checksums).

What version of Windows is running on the target machine?

**Comment by heyzzk** [comment]
Hi Rokm, 

thanks for your help!
I have uploaded the archive as follows.
    https://github.com/heyzzk/debug/blob/main/debug-20241120.zip

And yes, I used to run it directly on the network share of the virtual machine, but I tried copying it to the C drive and still encountered the same error after execution.
I am certain that the data is not corrupted.

My build computer is Windows10 Professional 10.0.19045.4780. The testing computer is Windows10 Professional 10.0.10240.

**Comment by rokm** [comment]
> The testing computer is Windows10 Professional 10.0.10240.

Yeah, I've tried with build 10.0.10240 (Win 10 Pro version 1507) VM that I have left from debugging a different issue. 

I can confirm that neither your build nor my locally-made build works in there. But then again, if I install python 3.12.0 and latest PyQt6 on that machine. it also fails:

```
>python debug.py
Traceback (most recent call last):
  File "[...]\debug.py", line 2, in <module>
    from PyQt6.QtWidgets import QApplication, QLabel, QPushButton, QVBoxLayout, QWidget
ImportError: DLL load failed while importing QtWidgets: The specified procedure could not be found.
```

So I don't think there's anything we can do about that. See https://doc.qt.io/qt-6/supported-platforms.html, which lists  `Windows 10 (1809 or later)` as supported platform (that's build 17763). Also [this](https://forum.qt.io/topic/139636/how-to-deal-with-qt6-minimum-windows-version-requirements), for example.

**Comment by heyzzk** [comment]
Hi Rokm,

the information you provided is very helpful. The exe file generated after switching to pyqt5 can run on target win10, which is great. Just the display effect is slightly different from pyqt6, it looks a little odd.
My issue has been resolved and can be closed now.
I have been struggling for a long time myself, but I don't know that it's due to compatibility issues.
Thank you very much!
