### ISSUE TITLE
Importing OpenVINO Fails After Updating openvino_telemetry to the Latest Version

### ISSUE THREAD

**Issue by yang-ahuan** [pyinstaller/pyinstaller#8908]
## Problem Description
Hi there~! I'm not entirely sure where to post this, so here it is

`openvino_telemetry` is a required dependency for OpenVINO. After updating `openvino_telemetry` to version `2024.5.0`, I encountered issues when importing OpenVINO:
* Sometimes, the executable doesn't stop automatically after finishing execution.
* Occasionally, the following traceback appears:
```=python
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 170, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 37, in _pyi_rthook
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "pkg_resources\__init__.py", line 96, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "jaraco\text\__init__.py", line 231, in <module>
  File "pathlib.py", line 1134, in read_text
  File "pathlib.py", line 1119, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\{TEMP_PATH}\\_MEI159442\\setuptools\\_vendor\\jaraco\\text\\Lorem ipsum.txt'
[PYI-12092:ERROR] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```

## Environment
* OS version: Windows 11
* Python version: 3.10.11
* Pyinstaller version: 6.11.1
* Openvino telemetry version: 2024.5.0 **(latest)**

## Reproduce
Only `import openvino` and bundle by pyinstaller

## Temporary Workaround
Downgrading `openvino_telemetry` to version `2024.1.0` resolves the issue.

Let me know if additional details are needed. Thank you!

**Comment by rokm** [comment]
Looks like `import openvino` triggers the spawning of a `multiprocessing` worker sub-process.

Does modifying your reproducer into:
```python
import multiprocessing
multiprocessing.freeze_support()

import openvino
``` 
fix the problem? (See [docs](https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#multi-processing) for details).

**Comment by rokm** [comment]
And the `multiprocessing` worker process is spawned from [here](https://github.com/openvinotoolkit/telemetry/blob/4a7e3b6672a488910e3910f045c7cd0da889b1c5/src/backend/backend_ga4.py#L55-L57). According to git blame, that was indeed a recent addition, which is why you are seeing the issue with 2024.5 but not with earlier versions.

**Comment by yang-ahuan** [comment]
Wow, thank you for the quick response! The above solution resolved my issue, and it was a huge help. I really appreciate you identifying the root cause—this is amazing. Thank you so much!
