### ISSUE TITLE
ModuleNotFoundError: No module named 'pathlib'

### ISSUE THREAD

**Issue by cvergari** [pyinstaller/pyinstaller#8909]
## Description of the issue
Hi,

I am receiving the following error when compiling a program:

```
File "PyInstaller\loader\pyimod02_importers.py", line 22, in <module>
ModuleNotFoundError: No module named 'pathlib'
```

Strange enough, the issue goes away if I rename the python script.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11.1```
* Version of Python: 3.12.8
* Platform: Windows 11
* How you installed Python: miniconda + new environment
* Did you also try this on another platform? Does it work there?
I tried in Debian (wsl) Windows Linux Subsystem: same result!

* try the latest development version

Tried: same result !

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

I tried adding "--collect-submodules=pathlib" but that did not solve the problem.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

# Steps to reproduce:
```
- create new conda environment: `conda create --name myenv -c conda-forge pyinstaller`
- create two new scripts, one named "run.py", the other "copy_and_transform_Edge_dicom.py". Both scripts only contain `print('ok!')`. The parent folder is also called "copy_and_transform_Edge_dicom".
- compile them both in windows (`pyinstaller copy_and_transform_Edge_dicom.py --onedir` and `pyinstaller run.py --onedir`)
- run the executables; run.exe works, the other raises the error.
```

### Stacktrace / full error message

# Log of the script that fails:

```
[PYI-7064:DEBUG] PyInstaller Bootloader 6.x
[PYI-7064:DEBUG] LOADER: executable file: C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\copy_and_transform_Edge_dicom.exe
[PYI-7064:DEBUG] LOADER: trying to load executable-embedded archive...
[PYI-7064:DEBUG] LOADER: attempting to open archive C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\copy_and_transform_Edge_dicom.exe
[PYI-7064:DEBUG] LOADER: cookie found at offset 0x59BB7
[PYI-7064:DEBUG] LOADER: archive file: C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\copy_and_transform_Edge_dicom.exe
[PYI-7064:DEBUG] LOADER: application has onedir semantics...
[PYI-7064:DEBUG] LOADER: _PYI_ARCHIVE_FILE not defined...
[PYI-7064:DEBUG] LOADER: process level = 1
[PYI-7064:DEBUG] LOADER: application's top-level directory: C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal
[PYI-7064:DEBUG] LOADER: calling SetDllDirectory: C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal
[PYI-7064:DEBUG] LOADER: splash screen is unavailable.
[PYI-7064:DEBUG] LOADER: ucrtbase.dll found: C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\ucrtbase.dll
[PYI-7064:DEBUG] LOADER: loading Python shared library: C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\python312.dll
[PYI-7064:DEBUG] LOADER: loaded functions from Python shared library.
[PYI-7064:DEBUG] LOADER: pre-initializing embedded python interpreter...
[PYI-7064:DEBUG] LOADER: creating PyConfig structure...
[PYI-7064:DEBUG] LOADER: initializing interpreter configuration...
[PYI-7064:DEBUG] LOADER: setting program name...
[PYI-7064:DEBUG] LOADER: setting python home path...
[PYI-7064:DEBUG] LOADER: setting module search paths...
[PYI-7064:DEBUG] LOADER: setting sys.argv...
[PYI-7064:DEBUG] LOADER: applying run-time options...
[PYI-7064:DEBUG] LOADER: starting embedded python interpreter...
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# zipimport: found 155 names in 'C:\\Dropbox\\Python\\LBMpy\\edge\\dist\\copy_and_transform_Edge_dicom\\_internal\\base_library.zip'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <class '_frozen_importlib.FrozenImporter'>
import 'encodings.aliases' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\encodings\">
import 'encodings' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import 'encodings.utf_8' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\encodings\">
import 'encodings.cp1252' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\encodings\">
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <class '_frozen_importlib.FrozenImporter'>
import 'io' # <class '_frozen_importlib.FrozenImporter'>
[PYI-7064:DEBUG] LOADER: setting sys._MEIPASS
[PYI-7064:DEBUG] LOADER: importing modules from PKG/CArchive
[PYI-7064:DEBUG] LOADER: extracted struct
[PYI-7064:DEBUG] LOADER: running unmarshalled code object for module struct...
import '_struct' # <class '_frozen_importlib.BuiltinImporter'>
[PYI-7064:DEBUG] LOADER: extracted pyimod01_archive
[PYI-7064:DEBUG] LOADER: running unmarshalled code object for module pyimod01_archive...
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <class '_frozen_importlib.FrozenImporter'>
import '_collections_abc' # <class '_frozen_importlib.FrozenImporter'>
import 'genericpath' # <class '_frozen_importlib.FrozenImporter'>
import '_winapi' # <class '_frozen_importlib.BuiltinImporter'>
import 'ntpath' # <class '_frozen_importlib.FrozenImporter'>
import 'os' # <class '_frozen_importlib.FrozenImporter'>
import 'zlib' # <class '_frozen_importlib.BuiltinImporter'>
[PYI-7064:DEBUG] LOADER: extracted pyimod02_importers
[PYI-7064:DEBUG] LOADER: running unmarshalled code object for module pyimod02_importers...
# code object from 'C:\\Dropbox\\Python\\LBMpy\\edge\\dist\\copy_and_transform_Edge_dicom\\_internal\\pathlib.pyc'
# code object from 'C:\\Dropbox\\Python\\LBMpy\\edge\\dist\\copy_and_transform_Edge_dicom\\_internal\\fnmatch.pyc'
import 'posixpath' # <class '_frozen_importlib.FrozenImporter'>
import 'types' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
import 'keyword' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import 'reprlib' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import 'enum' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
import 're._constants' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\re\">
import 're._parser' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\re\">
import 're._casefix' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\re\">
import 're._compiler' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\re\">
import 'copyreg' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import 're' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import 'fnmatch' # <_frozen_importlib_external.SourcelessFileLoader object at 0x00000205577F5460>
import 'warnings' # <zipimporter object "C:\Dropbox\Python\LBMpy\edge\dist\copy_and_transform_Edge_dicom\_internal\base_library.zip\">
import 'errno' # <class '_frozen_importlib.BuiltinImporter'>
# code object from 'C:\\Dropbox\\Python\\LBMpy\\edge\\dist\\copy_and_transform_Edge_dicom\\_internal\\urllib\\__init__.pyc'
import 'urllib' # <_frozen_importlib_external.SourcelessFileLoader object at 0x00000205578872C0>
# code object from 'C:\\Dropbox\\Python\\LBMpy\\edge\\dist\\copy_and_transform_Edge_dicom\\_internal\\urllib\\parse.pyc'
import 'math' # <class '_frozen_importlib.BuiltinImporter'>
# code object from 'C:\\Dropbox\\Python\\LBMpy\\edge\\dist\\copy_and_transform_Edge_dicom\\_internal\\ipaddress.pyc'
import 'ipaddress' # <_frozen_importlib_external.SourcelessFileLoader object at 0x00000205578A6780>
import 'urllib.parse' # <_frozen_importlib_external.SourcelessFileLoader object at 0x0000020557887380>
import 'pathlib' # <_frozen_importlib_external.SourcelessFileLoader object at 0x00000205577D9BB0>
# code object from 'C:\\Dropbox\\Python\\LBMpy\\edge\\dist\\copy_and_transform_Edge_dicom\\_internal\\tokenize.pyc'
# code object from 'C:\\Dropbox\\Python\\LBMpy\\edge\\dist\\copy_and_transform_Edge_dicom\\_internal\\token.pyc'
import 'token' # <_frozen_importlib_external.SourcelessFileLoader object at 0x0000020557AF7D70>
import '_tokenize' # <class '_frozen_importlib.BuiltinImporter'>
import 'tokenize' # <_frozen_importlib_external.SourcelessFileLoader object at 0x00000205577F5130>
[PYI-7064:DEBUG] LOADER: extracted pyimod03_ctypes
[PYI-7064:DEBUG] LOADER: running unmarshalled code object for module pyimod03_ctypes...
[PYI-7064:DEBUG] LOADER: extracted pyimod04_pywin32
[PYI-7064:DEBUG] LOADER: running unmarshalled code object for module pyimod04_pywin32...
[PYI-7064:DEBUG] LOADER: looking for PYZ archive TOC entry...
[PYI-7064:DEBUG] LOADER: path to PYZ archive stored into sys._pyinstaller_pyz...
[PYI-7064:DEBUG] LOADER: running pyiboot01_bootstrap.py
Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 462, in install
  File "PyInstaller\loader\pyimod02_importers.py", line 122, in __init__
ImportError: Cannot load frozen modules.
[PYI-7064:ERROR] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
[PYI-7064:DEBUG] LOADER: ERROR.
[PYI-7064:DEBUG] LOADER: manually flushing stdout and stderr...
[PYI-7064:DEBUG] LOADER: cleaning up Python interpreter...
# clear sys.path_importer_cache
# clear sys.path_hooks
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_exc
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.__interactivehook__
# clear sys.meta_path
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _thread
# cleanup[2] removing _warnings
# cleanup[2] removing _weakref
# cleanup[2] removing winreg
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing nt
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing time
# cleanup[2] removing zipimport
# destroy zipimport
# cleanup[2] removing _codecs
# cleanup[2] removing codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing encodings.cp1252
# cleanup[2] removing _signal
# cleanup[2] removing _abc
# cleanup[2] removing abc
# cleanup[2] removing io
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing struct
# cleanup[2] removing _struct
# cleanup[2] removing pyimod01_archive
# cleanup[2] removing _stat
# cleanup[2] removing stat
# cleanup[2] removing _collections_abc
# cleanup[2] removing genericpath
# cleanup[2] removing _winapi
# cleanup[2] removing ntpath
# cleanup[2] removing os.path
# cleanup[2] removing os
# cleanup[2] removing zlib
# cleanup[2] removing pyimod02_importers
# cleanup[2] removing posixpath
# cleanup[2] removing types
# cleanup[2] removing _operator
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing itertools
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing collections
# cleanup[2] removing _functools
# cleanup[2] removing functools
# cleanup[2] removing enum
# cleanup[2] removing _sre
# cleanup[2] removing re._constants
# cleanup[2] removing re._parser
# cleanup[2] removing re._casefix
# cleanup[2] removing re._compiler
# cleanup[2] removing copyreg
# cleanup[2] removing re
# cleanup[2] removing fnmatch
# cleanup[2] removing warnings
# cleanup[2] removing errno
# destroy errno
# cleanup[2] removing urllib
# destroy urllib
# cleanup[2] removing math
# cleanup[2] removing ipaddress
# cleanup[2] removing urllib.parse
# destroy urllib.parse
# cleanup[2] removing pathlib
# cleanup[2] removing token
# destroy token
# cleanup[2] removing _tokenize
# cleanup[2] removing tokenize
# cleanup[2] removing pyimod03_ctypes
# cleanup[2] removing pyimod04_pywin32
# destroy _signal
# cleanup[3] wiping pyimod04_pywin32
# cleanup[3] wiping pyimod03_ctypes
# cleanup[3] wiping tokenize
# destroy collections
# cleanup[3] wiping _tokenize
# cleanup[3] wiping pathlib
# destroy fnmatch
# cleanup[3] wiping ipaddress
# cleanup[3] wiping math
# cleanup[3] wiping warnings
# cleanup[3] wiping re
# destroy re._constants
# destroy re._casefix
# destroy re._compiler
# destroy enum
# destroy copyreg
# cleanup[3] wiping re._parser
# cleanup[3] wiping _sre
# cleanup[3] wiping functools
# cleanup[3] wiping _functools
# cleanup[3] wiping _collections
# cleanup[3] wiping itertools
# cleanup[3] wiping _operator
# cleanup[3] wiping types
# cleanup[3] wiping posixpath
# cleanup[3] wiping pyimod02_importers
# destroy pathlib
# destroy io
# destroy tokenize
# cleanup[3] wiping zlib
# cleanup[3] wiping os
# destroy abc
# cleanup[3] wiping os.path
# destroy genericpath
# cleanup[3] wiping ntpath
# cleanup[3] wiping _winapi
# cleanup[3] wiping _collections_abc
# cleanup[3] wiping stat
# cleanup[3] wiping _stat
# destroy _stat
# cleanup[3] wiping pyimod01_archive
# cleanup[3] wiping _struct
# cleanup[3] wiping struct
# cleanup[3] wiping _abc
# cleanup[3] wiping encodings.cp1252
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping time
# cleanup[3] wiping _frozen_importlib_external
# cleanup[3] wiping nt
# cleanup[3] wiping marshal
# cleanup[3] wiping _io
# cleanup[3] wiping winreg
# cleanup[3] wiping _weakref
# cleanup[3] wiping _warnings
# cleanup[3] wiping _thread
# cleanup[3] wiping _imp
# cleanup[3] wiping _frozen_importlib
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy sys.monitoring
# destroy nt
# destroy stat
# destroy zlib
# destroy os
# destroy re._parser
# destroy _sre
# destroy posixpath
# destroy ntpath
# destroy _tokenize
# destroy _thread
# destroy _collections_abc
# destroy _weakref
# destroy functools
# destroy math
# destroy re
# destroy types
# destroy warnings
# destroy ipaddress
# destroy winreg
# destroy _struct
# destroy _abc
# destroy _winapi
# destroy _operator
# destroy _functools
# destroy itertools
# destroy _collections
# clear sys.meta_path
# clear sys.modules
# destroy codecs
# destroy encodings.aliases
# destroy encodings.utf_8
# destroy encodings.cp1252
# destroy _codecs
# destroy builtins
# destroy _frozen_importlib_external
# destroy _frozen_importlib
# destroy _imp
# destroy marshal
# destroy sys
# destroy time
# destroy _warnings
# destroy _io
# clear sys.audit hooks
[PYI-7064:DEBUG] LOADER: unloading Python shared library...
[PYI-7064:DEBUG] LOADER: end of process reached!
```

**Comment by bwoodsend** [comment]
Can you reproduce with a normal python.org/downloads Python? We don't support conda.

**Comment by rokm** [comment]
>``` 
>[PYI-7064:DEBUG] LOADER: running pyiboot01_bootstrap.py
>Traceback (most recent call last):
>  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 20, in <module>
>  File "PyInstaller\loader\pyimod02_importers.py", line 462, in install
>  File "PyInstaller\loader\pyimod02_importers.py", line 122, in __init__
>ImportError: Cannot load frozen modules.
>```

The reported line numbers make sense no here. They match what we had in PyInstaller 5.13.1:

`pyimod02_importers.py`, line 462, `install()` -> creates `PyiFrozenImporter` instance: https://github.com/pyinstaller/pyinstaller/blob/v5.13.1/PyInstaller/loader/pyimod02_importers.py#L462

`pyimod02_importers.py`, line 122, `PyiFrozenImporter.__init__()` raises `raise ImportError("Cannot load frozen modules.")`: https://github.com/pyinstaller/pyinstaller/blob/v5.13.1/PyInstaller/loader/pyimod02_importers.py#L122

In v6.11.1, not only do the lines not match, we don't even have the `ImportError: Cannot load frozen modules.` error message anymore (it was removed in changes to loader made in v6.10.0): https://github.com/pyinstaller/pyinstaller/blob/v6.11.1/PyInstaller/loader/pyimod02_importers.py

So what I think is going here is a caching issue, and old bootstrap modules are being used.

Do you perhaps have old `build` directory that was created with previous PyInstaller version? Does it help if you remove it, or if you run PyInstaller with added `--clean` option?

**Comment by cvergari** [comment]
> Do you perhaps have old `build` directory that was created with previous PyInstaller version? Does it help if you remove it, or if you run PyInstaller with added `--clean` option?

Removing the build folder does indeed solve the problem. I think I updated Pyinstaller, which broke my compiled program, so I reverted to the previous version but the newer one must have left something in the build folder as well. Then nothing worked anymore... and the solution was so simple.

Thanks!

**Comment by rokm** [comment]
Hmm, we'll need to take a closer look at caching of those bootstrap modules. I'm pretty sure they are based on file timestamps (since this is how all caching in PyInstaller is done), and so their change fails to be detected. Off the top of my head, I can think of two scenarios:
- seeing how you're building in a `c:\Dropbox` and assuming this is a Dropbox-synced folder, perhaps dropbox is messing up the timestamps
- perhaps installing PyInstaller through conda does not set the timestamps of PyInstaller's .py files to the current time (= time of installation) but for example to the time of packaging, and those could end up being "older" than the files in cache even if they were generated prior to the upgrade

FWIW, I can manually reproduce the issue on linux if I build the program using 5.13.2, then upgrade to the latest version, update the timestamps of cached `build/<name>/localpycs/*.pyc` via `touch`, and then try to rebuild the program without `--clean` option.

But regardless of the underlying reason, it would likely make sense to switch from timestamp-based cache to hash-based one, at least for `localpycs` cache...

**Comment by bwoodsend** [comment]
I wonder how much point there is in keeping the cache at all. As far as I'm aware, the only common time it really gets to skip anything (as opposed to thinking it can and being wrong) is if you change an `--add-data` or flag.

**Comment by rokm** [comment]
I've tested with Anaconda, and it looks like the Anaconda-packaged files indeed end up having their creation/modification timestamp restored to (presumably) time of packaging. For example, installing PyInstaller 6.9.0 from main conda channel results in `pyimod02_importers.py` having timestamp set to July 22nd 2024, and updating it to 6.11.1 from conda-forge results in `pyimod02_importers.py` having timestamp set to November 11th 2024 (and as a bonus, the parent directory has its timestamp set to the time of installation. So it seems Anaconda goes out of its way to restrore/set the timestamps of the files it installs). In contrast, installing the package via pip sets the timestamp to the current date/time (= time of installation).

**Comment by rokm** [comment]
> I wonder how much point there is in keeping the cache at all. As far as I'm aware, the only common time it really gets to skip anything (as opposed to thinking it can and being wrong) is if you change an `--add-data` or flag.

The caching in question here at a lower level, in `compile_pymodule` helper - although if we forced the clean build (i.e., removed the `build/<name>` directory at the start of the build), the `build/<name>/localpycs` directory would also be cleared/removed.

https://github.com/pyinstaller/pyinstaller/blob/4d114b2faff0f82cf11c837800cd6e26c76e4f2e/PyInstaller/building/utils.py#L629-L711

This helper is used to create .pyc files for cases when we need to pass paths to on-disk .pyc files to the TOC list. Normally, we use this for bootstrap modules that are passed to the PKG TOC. It is also used for .pyc files that are to be collected as files - either because of module collection mode (although in practice, we do not use `pyc` mode anywhere yet) or because `noarchive` debug option is used. In contrast, it is not used when constructing PYZ - there, we either retrieve code objects from (modulegraph's) code-object cache, or compile them on-the-fly while keeping the code-object only in memory.

The "proper way" to fix the problem would be to introduce source-hash-based check instead of the timestamp based one. But this is complicated by the fact that we can also obtain the code object from code-cache (where we could still look up the source as well), or that our source can already be a .pyc (possibly without the accompanying source) and thus we are just copying the code object (and striping paths from it).

Therefore, I'm leaning towards slightly less optimal, but easier solution - we remove the check in L665-672, and *always* obtain the code object (whether by compiling it from source, retrieving it from code-object cache, or by reading it from input pyc file). Then, before writing it, we check for existence of the output file, and if present, read the marshaled code object from it, and compare it to the one we have. And then (overwrite) the file only if the code object is different. 

This would avoid unnecessary writes (e.g., to minimize writes on an SSD), but would also ensure that we do not invalidate cached PKG/COLLECT when the content of these .pyc files is unchanged.

Does that sound reasonable?

**Comment by bwoodsend** [comment]
Fine by me.
