### ISSUE TITLE
TypeError: expected string or bytes-like object, got 'NoneType' in discover_hook_directories()

### ISSUE THREAD

**Issue by g2eg02y** [pyinstaller/pyinstaller#8915]
### **Environment Details:**
- **PyInstaller Version:** 6.11.1  
- **Python Version:** 3.12.7  
- **Platform:** Linux 6.11.2 (x86_64)  
- **UPX:** Available but disabled (due to compatibility reasons).  

### **Issue:**
When attempting to package my Python script using the `--onefile` option, PyInstaller fails with a `RuntimeError` originating from `discover_hook_directories()`. The error traceback indicates a `NoneType` issue when normalizing metadata entry points in the `importlib.metadata` module.

### **Steps to Reproduce:**
1. Create a Python script (`chess.py` in this case).
2. Run PyInstaller with the following command:
   ```bash
   pyinstaller chess.py --onefile
   ```
3. Observe the error during the build process.

### **Traceback:** Traceback (most recent call last):
```
  File "/usr/bin/pyinstaller", line 33, in <module>
    sys.exit(load_entry_point('pyinstaller==6.11.1', 'console_scripts', 'pyinstaller')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 231, in _console_script_run
    run()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 1252, in main
    build(specfile, distpath, workpath, clean_build)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 1192, in build
    exec(code, spec_namespace)
  File "/home/g2eg02y/wadas/KratosKnife/botnet-generator/chess.spec", line 4, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 532, in __init__
    self.hookspath += discover_hook_directories()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/isolated/_parent.py", line 435, in wrapped
    return call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/isolated/_parent.py", line 404, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/isolated/_parent.py", line 334, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to discover_hook_directories() failed with:
  File "/usr/lib/python3/dist-packages/PyInstaller/isolated/_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 101, in discover_hook_directories
    entry_points = importlib_metadata.entry_points(group='pyinstaller40', name='hook-dirs')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 913, in entry_points
    return EntryPoints(eps).select(**params)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 911, in <genexpr>
    dist.entry_points for dist in _unique(distributions())
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
        ^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 835, in _normalized_name
    or super()._normalized_name
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 462, in _normalized_name
    return Prepared.normalize(self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 762, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/re/__init__.py", line 186, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

### **What I Have Tried:**
1. Upgrading PyInstaller and dependencies.
2. Clearing and reinstalling dependencies.
3. Using a fresh virtual environment.
4. Running `pip check` and inspecting package metadata.
5. Debugging with `--log-level=DEBUG`.

Despite these steps, the issue persists.

### **Possible Cause:**
It seems the issue is related to malformed or missing metadata in one of the installed Python packages. Specifically, `importlib.metadata` encounters a `NoneType` object while normalizing a `name` attribute.

---

## **Expected Behavior:**
PyInstaller should handle metadata issues gracefully, possibly by skipping over invalid entries or providing more actionable error messages.

---

## **Additional Context:**
- The Python environment is managed system-wide (`/usr` path) but also tested in a virtual environment with the same results.
- The `UPX` warning does not appear related to the issue but is included for context.

**Comment by rokm** [comment]
I take it you get the same error if you run the following snippet in python?

```python
import importlib.metadata
entry_points = importlib.metadata.entry_points(group='pyinstaller40', name='hook-dirs')
```

Since the rest of the error traces back into `importlib.metadata` itself, I would say that this means you have a package with broken metadata installed in your python environment.

And there's nothing we can really to do about it (there is nothing to "skip over", since we cannot even obtain the list of entry-point records from `importlib.metadata.entry_points()`).

**Comment by rokm** [comment]
Perhaps you can try enumerating all available distributions via `importlib_metadata.distributions()` and see which one has its `name` set to `None`? 

E.g., something like
```
import importlib.metadata
[(dist.name, dist._path) for dist in importlib.metadata.distributions()]
```

or even

```
import importlib.metadata
[(dist.name, dist._path) for dist in importlib.metadata.distributions() if dist.name is None]
```

EDIT: fixed `importlib_metadata` -> `importlib.metadata`, which is the one that is actually used in the original report.
