### ISSUE TITLE
Module only partially copied - No module named 'zeroconf._utils.ipaddress'

### ISSUE THREAD

**Issue by C0rn3j** [pyinstaller/pyinstaller#8935]
* pyinstaller: 6.11.1
* Python: 3.12.7 / 3.13.x on the build system
* Platform: Arch Linux
* How you installed Python: System
* Did you also try this on another platform? Does it work there: macOS fails the same way
* Try the latest development version: Still happens

The app uses pychromecast, which has a dependency on zeroconf.

I have tried adding both as a hiddenimport, but it still fails.

```
Traceback (most recent call last):
  File "tauon/t_modules/t_main.py", line 8549, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_chrome.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pychromecast/__init__.py", line 15, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "zeroconf/__init__.py", line 24, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "zeroconf/_core.py", line 32, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "zeroconf/_engine.py", line 38, in <module>
  File "src/zeroconf/_listener.py", line 1, in init zeroconf._listener
  File "src/zeroconf/_services/info.py", line 1, in init zeroconf._services.info
ModuleNotFoundError: No module named 'zeroconf._utils.ipaddress'
```

It turns out the module is there, but only partially:

![image](https://github.com/user-attachments/assets/876c02ac-60f9-40d3-836e-ba5abbe437e9)

One can repro this by 
* Cloning https://github.com/C0rn3j/Tauon/tree/macos-dmg at commit https://github.com/C0rn3j/Tauon/commit/63ec6b8fa37f0321be940dd2e38f96d8c118d2fd
* Running `./run.sh 1` to setup the venv - close the app
* Then running `source .venv/bin/activate; pyinstaller --log-level=DEBUG --noconfirm --clean linux.spec; ./dist/TauonMusicBox/Tauon\ Music\ Box` which throws the above error

The pychromecast module is loaded like such:
```python
try:
	from tauon.t_modules.t_chrome import Chrome
except ModuleNotFoundError:
	logging.exception("Test exception DELETE THIS LINE.")
	logging.warning("Unable to import Chrome(pychromecast), chromecast support will be disabled.")
except Exception:
	logging.exception("Unknown error trying to import Chrome(pychromecast), chromecast support will be disabled.")
finally:
	chrome = Chrome(tauon)
	logging.debug("Found import Chrome(pychromecast) for chromecast support")
```

Which imports from this file - https://github.com/C0rn3j/Tauon/blob/macos-dmg/src/tauon/t_modules/t_chrome.py

**Comment by C0rn3j** [comment]
Adding these two seems to have done the trick for now - thank you!

```python
"zeroconf._utils.ipaddress",
"zeroconf._handlers.answers",
```
